.Dd 2025-09-30
.Dt ADMISSIONS 3ossl
.Os
.Sh NAME
.Nm ADMISSIONS ,
.Nm ADMISSIONS_get0_admissionAuthority ,
.Nm ADMISSIONS_get0_namingAuthority ,
.Nm ADMISSIONS_get0_professionInfos ,
.Nm ADMISSIONS_set0_admissionAuthority ,
.Nm ADMISSIONS_set0_namingAuthority ,
.Nm ADMISSIONS_set0_professionInfos ,
.Nm ADMISSION_SYNTAX ,
.Nm ADMISSION_SYNTAX_get0_admissionAuthority ,
.Nm ADMISSION_SYNTAX_get0_contentsOfAdmissions ,
.Nm ADMISSION_SYNTAX_set0_admissionAuthority ,
.Nm ADMISSION_SYNTAX_set0_contentsOfAdmissions ,
.Nm NAMING_AUTHORITY ,
.Nm NAMING_AUTHORITY_get0_authorityId ,
.Nm NAMING_AUTHORITY_get0_authorityURL ,
.Nm NAMING_AUTHORITY_get0_authorityText ,
.Nm NAMING_AUTHORITY_set0_authorityId ,
.Nm NAMING_AUTHORITY_set0_authorityURL ,
.Nm NAMING_AUTHORITY_set0_authorityText ,
.Nm PROFESSION_INFO ,
.Nm PROFESSION_INFOS ,
.Nm PROFESSION_INFO_get0_addProfessionInfo ,
.Nm PROFESSION_INFO_get0_namingAuthority ,
.Nm PROFESSION_INFO_get0_professionItems ,
.Nm PROFESSION_INFO_get0_professionOIDs ,
.Nm PROFESSION_INFO_get0_registrationNumber ,
.Nm PROFESSION_INFO_set0_addProfessionInfo ,
.Nm PROFESSION_INFO_set0_namingAuthority ,
.Nm PROFESSION_INFO_set0_professionItems ,
.Nm PROFESSION_INFO_set0_professionOIDs ,
.Nm PROFESSION_INFO_set0_registrationNumber
.Nd Accessors and settors for ADMISSION_SYNTAX
.Sh SYNOPSIS
.Ft typedef struct NamingAuthority_st NAMING_AUTHORITY;
 typedef struct ProfessionInfo_st PROFESSION_INFO;
 typedef
.Fo STACK_OF
.Fa PROFESSION_INFO
.Fc
 PROFESSION_INFOS;
.Ft typedef struct Admissions_st ADMISSIONS;
 typedef struct AdmissionSyntax_st ADMISSION_SYNTAX;

 const ASN1_OBJECT *
.Fo NAMING_AUTHORITY_get0_authorityId
.Fa "      const NAMING_AUTHORITY *n"
.Fc
.Ft void
.Fo NAMING_AUTHORITY_set0_authorityId
.Fa "NAMING_AUTHORITY *n"
.Fa "ASN1_OBJECT* namingAuthorityId"
.Fc
.Ft const ASN1_IA5STRING *
.Fo NAMING_AUTHORITY_get0_authorityURL
.Fa "      const NAMING_AUTHORITY *n"
.Fc
.Ft void
.Fo NAMING_AUTHORITY_set0_authorityURL
.Fa "NAMING_AUTHORITY *n"
.Fa "ASN1_IA5STRING* namingAuthorityUrl"
.Fc
.Ft const ASN1_STRING *
.Fo NAMING_AUTHORITY_get0_authorityText
.Fa "      const NAMING_AUTHORITY *n"
.Fc
.Ft void
.Fo NAMING_AUTHORITY_set0_authorityText
.Fa "NAMING_AUTHORITY *n"
.Fa "ASN1_STRING* namingAuthorityText"
.Fc
.Ft const GENERAL_NAME *
.Fo ADMISSION_SYNTAX_get0_admissionAuthority
.Fa "      const ADMISSION_SYNTAX *as"
.Fc
.Ft void
.Fo ADMISSION_SYNTAX_set0_admissionAuthority
.Fa "      ADMISSION_SYNTAX *as"
.Fa "GENERAL_NAME *aa"
.Fc
.Ft const
.Fo STACK_OF
.Fa ADMISSIONS
.Fc
 *ADMISSION_SYNTAX_get0_contentsOfAdmissions(
.Bd -literal
     const ADMISSION_SYNTAX *as);
 void ADMISSION_SYNTAX_set0_contentsOfAdmissions(
     ADMISSION_SYNTAX *as, STACK_OF(ADMISSIONS) *a);
.Ed
.Ft const GENERAL_NAME *
.Fo ADMISSIONS_get0_admissionAuthority
.Fa "const ADMISSIONS *a"
.Fc
.Ft void
.Fo ADMISSIONS_set0_admissionAuthority
.Fa "ADMISSIONS *a"
.Fa "GENERAL_NAME *aa"
.Fc
.Ft const NAMING_AUTHORITY *
.Fo ADMISSIONS_get0_namingAuthority
.Fa "const ADMISSIONS *a"
.Fc
.Ft void
.Fo ADMISSIONS_set0_namingAuthority
.Fa "ADMISSIONS *a"
.Fa "NAMING_AUTHORITY *na"
.Fc
.Ft const PROFESSION_INFOS *
.Fo ADMISSIONS_get0_professionInfos
.Fa "const ADMISSIONS *a"
.Fc
.Ft void
.Fo ADMISSIONS_set0_professionInfos
.Fa "ADMISSIONS *a"
.Fa "PROFESSION_INFOS *pi"
.Fc
.Ft const ASN1_OCTET_STRING *
.Fo PROFESSION_INFO_get0_addProfessionInfo
.Fa "      const PROFESSION_INFO *pi"
.Fc
.Ft void
.Fo PROFESSION_INFO_set0_addProfessionInfo
.Fa "      PROFESSION_INFO *pi"
.Fa "ASN1_OCTET_STRING *aos"
.Fc
.Ft const NAMING_AUTHORITY *
.Fo PROFESSION_INFO_get0_namingAuthority
.Fa "      const PROFESSION_INFO *pi"
.Fc
.Ft void
.Fo PROFESSION_INFO_set0_namingAuthority
.Fa "      PROFESSION_INFO *pi"
.Fa "NAMING_AUTHORITY *na"
.Fc
.Ft const
.Fo STACK_OF
.Fa ASN1_STRING
.Fc
 *PROFESSION_INFO_get0_professionItems(
.Bd -literal
     const PROFESSION_INFO *pi);
 void PROFESSION_INFO_set0_professionItems(
     PROFESSION_INFO *pi, STACK_OF(ASN1_STRING) *as);
 const STACK_OF(ASN1_OBJECT) *PROFESSION_INFO_get0_professionOIDs(
     const PROFESSION_INFO *pi);
 void PROFESSION_INFO_set0_professionOIDs(
     PROFESSION_INFO *pi, STACK_OF(ASN1_OBJECT) *po);
 const ASN1_PRINTABLESTRING *PROFESSION_INFO_get0_registrationNumber(
     const PROFESSION_INFO *pi);
 void PROFESSION_INFO_set0_registrationNumber(
     PROFESSION_INFO *pi, ASN1_PRINTABLESTRING *rn);
.Ed
.Sh DESCRIPTION
The
.Vt PROFESSION_INFOS ,
.Sy ADMISSION_SYNTAX ,
.Vt ADMISSIONS ,
and
.Vt PROFESSION_INFO
types are opaque structures representing the analogous types defined in
the Common PKI Specification published by
.Lk https://www.t7ev.org .
Knowledge of those structures and their semantics is assumed.
.Pp
The conventional routines to convert between DER and the local format
are described in
.Xr d2i_X509 3 .
The conventional routines to allocate and free the types are defined in
.Xr X509_dup 3 .
.Pp
The
.Vt PROFESSION_INFOS
type is a stack of
.Vt PROFESSION_INFO ;
see
.Xr DEFINE_STACK_OF 3
for details.
.Pp
The
.Vt NAMING_AUTHORITY
type has an authority ID and URL, and text fields.
The
.Fn NAMING_AUTHORITY_get0_authorityId ,
.Xr NAMING_AUTHORITY_get0_get0_authorityURL 3 ,
and
.Xr NAMING_AUTHORITY_get0_get0_authorityText 3 ,
functions return pointers to those values within the object.
The
.Fn NAMING_AUTHORITY_set0_authorityId ,
.Xr NAMING_AUTHORITY_set0_get0_authorityURL 3 ,
and
.Xr NAMING_AUTHORITY_set0_get0_authorityText 3 ,
functions free any existing value and set the pointer to the specified
value.
.Pp
The
.Sy ADMISSION_SYNTAX
type has an authority name and a stack of
.Sy ADMISSION
objects.
The
.Fn ADMISSION_SYNTAX_get0_admissionAuthority
and
.Xr ADMISSION_SYNTAX_get0_contentsOfAdmissions 3
functions return pointers to those values within the object.
The
.Fn ADMISSION_SYNTAX_set0_admissionAuthority
and
.Xr ADMISSION_SYNTAX_set0_contentsOfAdmissions 3
functions free any existing value and set the pointer to the specified
value.
.Pp
The
.Sy ADMISSION
type has an authority name, authority object, and a stack of
.Vt PROFESSION_INFO
items.
The
.Fn ADMISSIONS_get0_admissionAuthority ,
.Fn ADMISSIONS_get0_namingAuthority ,
and
.Fn ADMISSIONS_get0_professionInfos
functions return pointers to those values within the object.
The
.Fn ADMISSIONS_set0_admissionAuthority ,
.Fn ADMISSIONS_set0_namingAuthority ,
and
.Fn ADMISSIONS_set0_professionInfos
functions free any existing value and set the pointer to the specified
value.
.Pp
The
.Vt PROFESSION_INFO
type has a name authority, stacks of profession Items and OIDs, a
registration number, and additional profession info.
The functions
.Fn PROFESSION_INFO_get0_addProfessionInfo ,
.Fn PROFESSION_INFO_get0_namingAuthority ,
.Xr PROFESSION_INFO_get0_professionItems 3 ,
.Xr PROFESSION_INFO_get0_professionOIDs 3 ,
and
.Xr PROFESSION_INFO_get0_registrationNumber 3
functions return pointers to those values within the object.
The
.Fn PROFESSION_INFO_set0_addProfessionInfo ,
.Fn PROFESSION_INFO_set0_namingAuthority ,
.Xr PROFESSION_INFO_set0_professionItems 3 ,
.Xr PROFESSION_INFO_set0_professionOIDs 3 ,
and
.Xr PROFESSION_INFO_set0_registrationNumber 3
functions free any existing value and set the pointer to the specified
value.
.Sh RETURN VALUES
Described above.
Note that all of the
.Em get0
functions return a pointer to the internal data structure and must not
be freed.
.Sh SEE ALSO
.Xr X509_dup 3 ,
.Xr d2i_X509 3 ,
.Sh COPYRIGHT
Copyright 2017-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
