.Dd 2025-09-30
.Dt ASN1_STRING_LENGTH 3ossl
.Os
.Sh NAME
.Nm ASN1_STRING_dup ,
.Nm ASN1_STRING_cmp ,
.Nm ASN1_STRING_set ,
.Nm ASN1_STRING_length ,
.Nm ASN1_STRING_type ,
.Nm ASN1_STRING_get0_data ,
.Nm ASN1_STRING_data ,
.Nm ASN1_STRING_to_UTF8
.Nd ASN1_STRING utility functions
.Sh SYNOPSIS
.In openssl/asn1.h
.Ft int
.Fo ASN1_STRING_length
.Fa "ASN1_STRING *x"
.Fc
.Ft const unsigned char *
.Fo ASN1_STRING_get0_data
.Fa "const ASN1_STRING *x"
.Fc
.Ft unsigned char *
.Fo ASN1_STRING_data
.Fa "ASN1_STRING *x"
.Fc
.Ft ASN1_STRING *
.Fo ASN1_STRING_dup
.Fa "const ASN1_STRING *a"
.Fc
.Ft int
.Fo ASN1_STRING_cmp
.Fa "ASN1_STRING *a"
.Fa "ASN1_STRING *b"
.Fc
.Ft int
.Fo ASN1_STRING_set
.Fa "ASN1_STRING *str"
.Fa "const void *data"
.Fa "int len"
.Fc
.Ft int
.Fo ASN1_STRING_type
.Fa "const ASN1_STRING *x"
.Fc
.Ft int
.Fo ASN1_STRING_to_UTF8
.Fa "unsigned char **out"
.Fa "const ASN1_STRING *in"
.Fc
.Sh DESCRIPTION
These functions allow an
.Vt ASN1_STRING
structure to be manipulated.
.Pp
.Fn ASN1_STRING_length
returns the length of the content of
.Fa x .
.Fa x
.Sy MUST NOT
be NULL.
.Pp
.Fn ASN1_STRING_get0_data
returns an internal pointer to the data of
.Fa x .
Since this is an internal pointer it should
.Sy not
be freed or modified in any way.
.Fa x
.Sy MUST NOT
be NULL.
.Pp
.Fn ASN1_STRING_data
is similar to
.Fn ASN1_STRING_get0_data
except the returned value is not constant.
This function is deprecated: applications should use
.Fn ASN1_STRING_get0_data
instead.
.Pp
.Fn ASN1_STRING_dup
returns a copy of the structure
.Fa a .
.Pp
.Fn ASN1_STRING_cmp
compares
.Fa a
and
.Fa b
returning 0 if the two are identical.
The string types and content are compared.
.Pp
.Fn ASN1_STRING_set
sets the data of string
.Fa str
to the buffer
.Fa data
or length
.Fa len .
The supplied data is copied.
If
.Fa len
is -1 then the length is determined by strlen(data).
.Pp
.Fn ASN1_STRING_type
returns the type of
.Fa x ,
using standard constants such as
.Sy V_ASN1_OCTET_STRING .
.Pp
.Fn ASN1_STRING_to_UTF8
converts the string
.Fa in
to UTF8 format, the converted data is allocated in a buffer in
.Em *out .
The length of
.Fa out
is returned or a negative error code.
The buffer
.Em *out
should be freed using
.Xr OPENSSL_free 3 .
.Sh NOTES
Almost all ASN1 types in OpenSSL are represented as an
.Vt ASN1_STRING
structure.
Other types such as
.Sy ASN1_OCTET_STRING
are simply typedef'ed to
.Vt ASN1_STRING
and the functions call the
.Vt ASN1_STRING
equivalents.
.Vt ASN1_STRING
is also used for some
.Sy CHOICE
types which consist entirely of primitive string types such as
.Sy DirectoryString
and
.Sy Time .
.Pp
These functions should
.Sy not
be used to examine or modify
.Sy ASN1_INTEGER
or
.Sy ASN1_ENUMERATED
types: the relevant
.Sy INTEGER
or
.Sy ENUMERATED
utility functions should be used instead.
.Pp
In general it cannot be assumed that the data returned by
.Fn ASN1_STRING_data
is null terminated or does not contain embedded nulls.
The actual format of the data will depend on the actual string type
itself: for example for an IA5String the data will be ASCII, for a
BMPString two bytes per character in big endian format, and for a
UTF8String it will be in UTF8 format.
.Pp
Similar care should be take to ensure the data is in the correct format
when calling
.Fn ASN1_STRING_set .
.Sh RETURN VALUES
.Fn ASN1_STRING_length
returns the length of the content of
.Fa x .
.Pp
.Fn ASN1_STRING_get0_data
and
.Fn ASN1_STRING_data
return an internal pointer to the data of
.Fa x .
.Pp
.Fn ASN1_STRING_dup
returns a valid
.Vt ASN1_STRING
structure or NULL if an error occurred.
.Pp
.Fn ASN1_STRING_cmp
returns an integer greater than, equal to, or less than 0, according to
whether
.Fa a
is greater than, equal to, or less than
.Fa b .
.Pp
.Fn ASN1_STRING_set
returns 1 on success or 0 on error.
.Pp
.Fn ASN1_STRING_type
returns the type of
.Fa x .
.Pp
.Fn ASN1_STRING_to_UTF8
returns the number of bytes in output string
.Fa out
or a negative value if an error occurred.
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh COPYRIGHT
Copyright 2002-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
