.Dd 2025-09-30
.Dt ASN1_STRING_TABLE_ADD 3ossl
.Os
.Sh NAME
.Nm ASN1_STRING_TABLE ,
.Nm ASN1_STRING_TABLE_add ,
.Nm ASN1_STRING_TABLE_get ,
.Nm ASN1_STRING_TABLE_cleanup
.Nd ASN1_STRING_TABLE manipulation functions
.Sh SYNOPSIS
.In openssl/asn1.h
.Ft typedef struct asn1_string_table_st ASN1_STRING_TABLE;

 int
.Fo ASN1_STRING_TABLE_add
.Fa "int nid"
.Fa "long minsize"
.Fa "long maxsize"
.Fa "unsigned long mask"
.Fa "unsigned long flags"
.Fc
.Ft ASN1_STRING_TABLE *
.Fo ASN1_STRING_TABLE_get
.Fa "int nid"
.Fc
.Ft void
.Fo ASN1_STRING_TABLE_cleanup
.Fa void
.Fc
.Sh DESCRIPTION
.Ss Types
.Vt ASN1_STRING_TABLE
is a table which holds string information (basically minimum size,
maximum size, type and etc) for a NID object.
.Ss Functions
.Fn ASN1_STRING_TABLE_add
adds a new
.Vt ASN1_STRING_TABLE
item into the local ASN1 string table based on the
.Fa nid
along with other parameters.
.Pp
If the item is already in the table, fields of
.Vt ASN1_STRING_TABLE
are updated (depending on the values of those parameters, e.g.,
.Fa minsize
and
.Fa maxsize
>= 0,
.Fa mask
and
.Fa flags
!= 0). If the
.Fa nid
is standard, a copy of the standard
.Vt ASN1_STRING_TABLE
is created and updated with other parameters.
.Pp
.Fn ASN1_STRING_TABLE_get
searches for an
.Vt ASN1_STRING_TABLE
item based on
.Fa nid .
It will search the local table first, then the standard one.
.Pp
.Fn ASN1_STRING_TABLE_cleanup
frees all
.Vt ASN1_STRING_TABLE
items added by
.Fn ASN1_STRING_TABLE_add .
.Sh RETURN VALUES
.Fn ASN1_STRING_TABLE_add
returns 1 on success, 0 if an error occurred.
.Pp
.Fn ASN1_STRING_TABLE_get
returns a valid
.Vt ASN1_STRING_TABLE
structure or NULL if nothing is found.
.Pp
.Fn ASN1_STRING_TABLE_cleanup
does not return a value.
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh COPYRIGHT
Copyright 2017-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
