.Dd 2025-09-30
.Dt ASN1_AUX_CB 3ossl
.Os
.Sh NAME
.Nm ASN1_AUX ,
.Nm ASN1_PRINT_ARG ,
.Nm ASN1_STREAM_ARG ,
.Nm ASN1_aux_cb ,
.Nm ASN1_aux_const_cb
.Nd ASN.1 auxiliary data
.Sh SYNOPSIS
.In openssl/asn1t.h
.Ft struct ASN1_AUX_st {
     void *app_data;
     int flags;
     int ref_offset;             /* Offset of reference value */
     int ref_lock;               /* Offset to an CRYPTO_RWLOCK */
     ASN1_aux_cb *asn1_cb;
     int enc_offset;             /* Offset of ASN1_ENCODING structure */
     ASN1_aux_const_cb *asn1_const_cb; /* for ASN1_OP_I2D_ and ASN1_OP_PRINT_ */
 };
 typedef struct ASN1_AUX_st ASN1_AUX;

 struct ASN1_PRINT_ARG_st {
     BIO *out;
     int indent;
     const ASN1_PCTX *pctx;
 };
 typedef struct ASN1_PRINT_ARG_st ASN1_PRINT_ARG;

 struct ASN1_STREAM_ARG_st {
     BIO *out;
     BIO *ndef_bio;
     unsigned char **boundary;
 };
 typedef struct ASN1_STREAM_ARG_st ASN1_STREAM_ARG;

 typedef int
.Fo ASN1_aux_cb
.Fa "int operation"
.Fa "ASN1_VALUE **in"
.Fa "const ASN1_ITEM *it"
.Fa "void *exarg"
.Fc
.Ft typedef int
.Fo ASN1_aux_const_cb
.Fa "int operation"
.Fa "const ASN1_VALUE **in"
.Fa "const ASN1_ITEM *it"
.Fa "void *exarg"
.Fc
.Sh DESCRIPTION
ASN.1 data structures can be associated with an
.Sy ASN1_AUX
object to supply additional information about the ASN.1 structure.
An
.Sy ASN1_AUX
structure is associated with the structure during the definition of the
ASN.1 template.
For example an
.Sy ASN1_AUX
structure will be associated by using one of the various ASN.1 template
definition macros that supply auxiliary information such as
.Xr ASN1_SEQUENCE_enc 3 ,
.Xr ASN1_SEQUENCE_ref 3 ,
.Xr ASN1_SEQUENCE_cb_const_cb 3 ,
.Xr ASN1_SEQUENCE_const_cb 3 ,
.Xr ASN1_SEQUENCE_cb 3
or
.Xr ASN1_NDEF_SEQUENCE_cb 3 .
.Pp
An
.Sy ASN1_AUX
structure contains the following information.
.Bl -tag -width Ds
.It Em app_data
Arbitrary application data
.It Em flags
Flags which indicate the auxiliarly functionality supported.
.Pp
The
.Sy ASN1_AFLG_REFCOUNT
flag indicates that objects support reference counting.
.Pp
The
.Sy ASN1_AFLG_ENCODING
flag indicates that the original encoding of the object will be saved.
.Pp
The
.Sy ASN1_AFLG_BROKEN
flag is a work around for broken encoders where the sequence length
value may not be correct.
This should generally not be used.
.Pp
The
.Sy ASN1_AFLG_CONST_CB
flag indicates that the "const" form of the
.Sy ASN1_AUX
callback should be used in preference to the non-const form.
.It Em ref_offset
If the
.Sy ASN1_AFLG_REFCOUNT
flag is set then this value is assumed to be an offset into the
.Vt ASN1_VALUE
structure where a
.Sy CRYPTO_REF_COUNT
may be found for the purposes of reference counting.
.It Em ref_lock
If the
.Sy ASN1_AFLG_REFCOUNT
flag is set then this value is assumed to be an offset into the
.Vt ASN1_VALUE
structure where a
.Sy CRYPTO_RWLOCK
may be found for the purposes of reference counting.
.It Em asn1_cb
A callback that will be invoked at various points during the processing
of the
.Vt ASN1_VALUE .
See below for further details.
.It Em enc_offset
Offset into the
.Vt ASN1_VALUE
object where the original encoding of the object will be saved if the
.Sy ASN1_AFLG_ENCODING
flag has been set.
.It Em asn1_const_cb
A callback that will be invoked at various points during the processing
of the
.Vt ASN1_VALUE .
This is used in preference to the
.Em asn1_cb
callback if the
.Sy ASN1_AFLG_CONST_CB
flag is set.
See below for further details.
.El
.Pp
During the processing of an
.Vt ASN1_VALUE
object the callbacks set via
.Em asn1_cb
or
.Em asn1_const_cb
will be invoked as a result of various events indicated via the
.Fa operation
parameter.
The value of
.Em *in
will be the
.Vt ASN1_VALUE
object being processed based on the template in
.Fa it .
An additional operation specific parameter may be passed in
.Fa exarg .
The currently supported operations are as follows.
The callbacks should return a positive value on success or zero on
error, unless otherwise noted below.
.Bl -tag -width Ds
.It Sy ASN1_OP_NEW_PRE
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure prior to an
.Vt ASN1_VALUE
object being allocated.
The callback may allocate the
.Vt ASN1_VALUE
itself and store it in
.Em *pval .
If it does so it should return 2 from the callback.
On error it should return 0.
.It Sy ASN1_OP_NEW_POST
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure after an
.Vt ASN1_VALUE
object has been allocated.
The allocated object is in
.Em *pval .
.It Sy ASN1_OP_FREE_PRE
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately before an
.Vt ASN1_VALUE
is freed.
If the callback originally constructed the
.Vt ASN1_VALUE
via
.Sy ASN1_OP_NEW_PRE
then it should free it at this point and return 2 from the callback.
Otherwise it should return 1 for success or 0 on error.
.It Sy ASN1_OP_FREE_POST
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately after
.Vt ASN1_VALUE
sub-structures are freed.
.It Sy ASN1_OP_D2I_PRE
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately before a "d2i" operation for the
.Vt ASN1_VALUE .
.It Sy ASN1_OP_D2I_POST
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately after a "d2i" operation for the
.Vt ASN1_VALUE .
.It Sy ASN1_OP_I2D_PRE
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately before a "i2d" operation for the
.Vt ASN1_VALUE .
.It Sy ASN1_OP_I2D_POST
Invoked when processing a
.Sy CHOICE ,
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately after a "i2d" operation for the
.Vt ASN1_VALUE .
.It Sy ASN1_OP_PRINT_PRE
Invoked when processing a
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately before printing the
.Vt ASN1_VALUE .
The
.Fa exarg
argument will be a pointer to an
.Sy ASN1_PRINT_ARG
structure (see below).
.It Sy ASN1_OP_PRINT_POST
Invoked when processing a
.Sy SEQUENCE
or
.Sy NDEF_SEQUENCE
structure immediately after printing the
.Vt ASN1_VALUE .
The
.Fa exarg
argument will be a pointer to an
.Sy ASN1_PRINT_ARG
structure (see below).
.It Sy ASN1_OP_STREAM_PRE
Invoked immediately prior to streaming the
.Vt ASN1_VALUE
data using indefinite length encoding.
The
.Fa exarg
argument will be a pointer to a
.Sy ASN1_STREAM_ARG
structure (see below).
.It Sy ASN1_OP_STREAM_POST
Invoked immediately after streaming the
.Vt ASN1_VALUE
data using indefinite length encoding.
The
.Fa exarg
argument will be a pointer to a
.Sy ASN1_STREAM_ARG
structure (see below).
.It Sy ASN1_OP_DETACHED_PRE
Invoked immediately prior to processing the
.Vt ASN1_VALUE
data as a "detached" value (as used in CMS and PKCS7). The
.Fa exarg
argument will be a pointer to a
.Sy ASN1_STREAM_ARG
structure (see below).
.It Sy ASN1_OP_DETACHED_POST
Invoked immediately after processing the
.Vt ASN1_VALUE
data as a "detached" value (as used in CMS and PKCS7). The
.Fa exarg
argument will be a pointer to a
.Sy ASN1_STREAM_ARG
structure (see below).
.It Sy ASN1_OP_DUP_PRE
Invoked immediate prior to an ASN1_VALUE being duplicated via a call to
.Xr ASN1_item_dup 3 .
.It Sy ASN1_OP_DUP_POST
Invoked immediate after to an ASN1_VALUE has been duplicated via a call
to
.Xr ASN1_item_dup 3 .
.It Sy ASN1_OP_GET0_LIBCTX
Invoked in order to obtain the
.Sy OSSL_LIB_CTX
associated with an
.Vt ASN1_VALUE
if any.
A pointer to an
.Sy OSSL_LIB_CTX
should be stored in
.Em *exarg
if such a value exists.
.It Sy ASN1_OP_GET0_PROPQ
Invoked in order to obtain the property query string associated with an
.Vt ASN1_VALUE
if any.
A pointer to the property query string should be stored in
.Em *exarg
if such a value exists.
.El
.Pp
An
.Sy ASN1_PRINT_ARG
object is used during processing of
.Sy ASN1_OP_PRINT_PRE
and
.Sy ASN1_OP_PRINT_POST
callback operations.
It contains the following information.
.Bl -tag -width Ds
.It Em out
The
.Sy BIO
being used to print the data out.
.It Em ndef_bio
The current number of indent spaces that should be used for printing
this data.
.It Em pctx
The context for the
.Sy ASN1_PCTX
operation.
.El
.Pp
An
.Sy ASN1_STREAM_ARG
object is used during processing of
.Sy ASN1_OP_STREAM_PRE ,
.Sy ASN1_OP_STREAM_POST ,
.Sy ASN1_OP_DETACHED_PRE
and
.Sy ASN1_OP_DETACHED_POST
callback operations.
It contains the following information.
.Bl -tag -width Ds
.It Em out
The
.Sy BIO
to stream through
.It Em ndef_bio
The
.Sy BIO
with filters appended
.It Em boundary
The streaming I/O boundary.
.El
.Sh RETURN VALUES
The callbacks return 0 on error and a positive value on success.
Some operations require specific positive success values as noted above.
.Sh SEE ALSO
.Xr ASN1_item_new_ex 3
.Sh HISTORY
The
.Fn ASN1_aux_const_cb
callback and the
.Sy ASN1_OP_GET0_LIBCTX
and
.Sy ASN1_OP_GET0_PROPQ
operation types were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2021-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
