.Dd 2025-09-30
.Dt ASN1_INTEGER_GET_INT64 3ossl
.Os
.Sh NAME
.Nm ASN1_INTEGER_get_uint64 ,
.Nm ASN1_INTEGER_set_uint64 ,
.Nm ASN1_INTEGER_get_int64 ,
.Nm ASN1_INTEGER_get ,
.Nm ASN1_INTEGER_set_int64 ,
.Nm ASN1_INTEGER_set ,
.Nm BN_to_ASN1_INTEGER ,
.Nm ASN1_INTEGER_to_BN ,
.Nm ASN1_ENUMERATED_get_int64 ,
.Nm ASN1_ENUMERATED_get ,
.Nm ASN1_ENUMERATED_set_int64 ,
.Nm ASN1_ENUMERATED_set ,
.Nm BN_to_ASN1_ENUMERATED ,
.Nm ASN1_ENUMERATED_to_BN
.Nd ASN.1 INTEGER and ENUMERATED utilities
.Sh SYNOPSIS
.In openssl/asn1.h
.Ft int
.Fo ASN1_INTEGER_get_int64
.Fa "int64_t *pr"
.Fa "const ASN1_INTEGER *a"
.Fc
.Ft long
.Fo ASN1_INTEGER_get
.Fa "const ASN1_INTEGER *a"
.Fc
.Ft int
.Fo ASN1_INTEGER_set_int64
.Fa "ASN1_INTEGER *a"
.Fa "int64_t r"
.Fc
.Ft int
.Fo ASN1_INTEGER_set
.Fa "ASN1_INTEGER *a"
.Fa "long v"
.Fc
.Ft int
.Fo ASN1_INTEGER_get_uint64
.Fa "uint64_t *pr"
.Fa "const ASN1_INTEGER *a"
.Fc
.Ft int
.Fo ASN1_INTEGER_set_uint64
.Fa "ASN1_INTEGER *a"
.Fa "uint64_t r"
.Fc
.Ft ASN1_INTEGER *
.Fo BN_to_ASN1_INTEGER
.Fa "const BIGNUM *bn"
.Fa "ASN1_INTEGER *ai"
.Fc
.Ft BIGNUM *
.Fo ASN1_INTEGER_to_BN
.Fa "const ASN1_INTEGER *ai"
.Fa "BIGNUM *bn"
.Fc
.Ft int
.Fo ASN1_ENUMERATED_get_int64
.Fa "int64_t *pr"
.Fa "const ASN1_ENUMERATED *a"
.Fc
.Ft long
.Fo ASN1_ENUMERATED_get
.Fa "const ASN1_ENUMERATED *a"
.Fc
.Ft int
.Fo ASN1_ENUMERATED_set_int64
.Fa "ASN1_ENUMERATED *a"
.Fa "int64_t r"
.Fc
.Ft int
.Fo ASN1_ENUMERATED_set
.Fa "ASN1_ENUMERATED *a"
.Fa "long v"
.Fc
.Ft ASN1_ENUMERATED *
.Fo BN_to_ASN1_ENUMERATED
.Fa "const BIGNUM *bn"
.Fa "ASN1_ENUMERATED *ai"
.Fc
.Ft BIGNUM *
.Fo ASN1_ENUMERATED_to_BN
.Fa "const ASN1_ENUMERATED *ai"
.Fa "BIGNUM *bn"
.Fc
.Sh DESCRIPTION
These functions convert to and from
.Vt ASN1_INTEGER
and
.Vt ASN1_ENUMERATED
structures.
.Pp
.Fn ASN1_INTEGER_get_int64
converts an
.Vt ASN1_INTEGER
into an
.Vt int64_t
type If successful it returns 1 and sets
.Em *pr
to the value of
.Fa a .
If it fails (due to invalid type or the value being too big to fit into
an
.Vt int64_t
type) it returns 0.
.Pp
.Fn ASN1_INTEGER_get_uint64
is similar to
.Xr ASN1_INTEGER_get_int64_t 3
except it converts to a
.Vt uint64_t
type and an error is returned if the passed integer is negative.
.Pp
.Fn ASN1_INTEGER_get
also returns the value of
.Fa a
but it returns 0 if
.Fa a
is NULL and -1 on error (which is ambiguous because -1 is a legitimate
value for an
.Vt ASN1_INTEGER Ns ).
New applications should use
.Fn ASN1_INTEGER_get_int64
instead.
.Pp
.Fn ASN1_INTEGER_set_int64
sets the value of
.Vt ASN1_INTEGER
.Fa a
to the
.Vt int64_t
value
.Fa r .
.Pp
.Fn ASN1_INTEGER_set_uint64
sets the value of
.Vt ASN1_INTEGER
.Fa a
to the
.Vt uint64_t
value
.Fa r .
.Pp
.Fn ASN1_INTEGER_set
sets the value of
.Vt ASN1_INTEGER
.Fa a
to the
.Vt long
value
.Fa v .
.Pp
.Fn BN_to_ASN1_INTEGER
converts
.Vt BIGNUM
.Fa bn
to an
.Vt ASN1_INTEGER .
If
.Fa ai
is NULL a new
.Vt ASN1_INTEGER
structure is returned.
If
.Fa ai
is not NULL then the existing structure will be used instead.
.Pp
.Fn ASN1_INTEGER_to_BN
converts ASN1_INTEGER
.Fa ai
into a
.Vt BIGNUM .
If
.Fa bn
is NULL a new
.Vt BIGNUM
structure is returned.
If
.Fa bn
is not NULL then the existing structure will be used instead.
.Pp
.Fn ASN1_ENUMERATED_get_int64 ,
.Fn ASN1_ENUMERATED_set_int64 ,
.Fn ASN1_ENUMERATED_set ,
.Fn BN_to_ASN1_ENUMERATED
and
.Fn ASN1_ENUMERATED_to_BN
behave in an identical way to their ASN1_INTEGER counterparts except
they operate on an
.Vt ASN1_ENUMERATED
value.
.Pp
.Fn ASN1_ENUMERATED_get
returns the value of
.Fa a
in a similar way to
.Fn ASN1_INTEGER_get
but it returns
.Sy 0xffffffffL
if the value of
.Fa a
will not fit in a long type.
New applications should use
.Fn ASN1_ENUMERATED_get_int64
instead.
.Sh NOTES
In general an
.Vt ASN1_INTEGER
or
.Vt ASN1_ENUMERATED
type can contain an integer of almost arbitrary size and so cannot
always be represented by a C
.Vt int64_t
type.
However, in many cases (for example version numbers) they represent
small integers which can be more easily manipulated if converted to an
appropriate C integer type.
.Sh BUGS
The ambiguous return values of
.Fn ASN1_INTEGER_get
and
.Fn ASN1_ENUMERATED_get
mean these functions should be avoided if possible.
They are retained for compatibility.
Normally the ambiguous return values are not legitimate values for the
fields they represent.
.Sh RETURN VALUES
.Fn ASN1_INTEGER_set_int64 ,
.Fn ASN1_INTEGER_set ,
.Fn ASN1_ENUMERATED_set_int64
and
.Fn ASN1_ENUMERATED_set
return 1 for success and 0 for failure.
They will only fail if a memory allocation error occurs.
.Pp
.Fn ASN1_INTEGER_get_int64
and
.Fn ASN1_ENUMERATED_get_int64
return 1 for success and 0 for failure.
They will fail if the passed type is incorrect (this will only happen if
there is a programming error) or if the value exceeds the range of an
.Vt int64_t
type.
.Pp
.Fn BN_to_ASN1_INTEGER
and
.Fn BN_to_ASN1_ENUMERATED
return an
.Vt ASN1_INTEGER
or
.Vt ASN1_ENUMERATED
structure respectively or NULL if an error occurs.
They will only fail due to a memory allocation error.
.Pp
.Fn ASN1_INTEGER_to_BN
and
.Fn ASN1_ENUMERATED_to_BN
return a
.Vt BIGNUM
structure of NULL if an error occurs.
They can fail if the passed type is incorrect (due to programming error)
or due to a memory allocation failure.
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh HISTORY
.Fn ASN1_INTEGER_set_int64 ,
.Fn ASN1_INTEGER_get_int64 ,
.Fn ASN1_ENUMERATED_set_int64
and
.Fn ASN1_ENUMERATED_get_int64
were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2015-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
