.Dd 2025-09-30
.Dt ASN1_STRING_NEW 3ossl
.Os
.Sh NAME
.Nm ASN1_STRING_new ,
.Nm ASN1_STRING_type_new ,
.Nm ASN1_STRING_free
.Nd ASN1_STRING allocation functions
.Sh SYNOPSIS
.In openssl/asn1.h
.Ft ASN1_STRING *
.Fo ASN1_STRING_new
.Fa void
.Fc
.Ft ASN1_STRING *
.Fo ASN1_STRING_type_new
.Fa "int type"
.Fc
.Ft void
.Fo ASN1_STRING_free
.Fa "ASN1_STRING *a"
.Fc
.Sh DESCRIPTION
.Fn ASN1_STRING_new
returns an allocated
.Vt ASN1_STRING
structure.
Its type is undefined.
.Pp
.Fn ASN1_STRING_type_new
returns an allocated
.Vt ASN1_STRING
structure of type
.Fa type .
.Pp
.Fn ASN1_STRING_free
frees up
.Fa a .
If
.Fa a
is NULL nothing is done.
.Sh NOTES
Other string types call the
.Vt ASN1_STRING
functions.
For example
.Xr ASN1_OCTET_STRING_new 3
calls ASN1_STRING_type_new(V_ASN1_OCTET_STRING).
.Sh RETURN VALUES
.Fn ASN1_STRING_new
and
.Fn ASN1_STRING_type_new
return a valid
.Vt ASN1_STRING
structure or NULL if an error occurred.
.Pp
.Fn ASN1_STRING_free
does not return a value.
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh COPYRIGHT
Copyright 2002-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
