.Dd 2025-09-30
.Dt ASYNC_WAIT_CTX_NEW 3ossl
.Os
.Sh NAME
.Nm ASYNC_WAIT_CTX_new ,
.Nm ASYNC_WAIT_CTX_free ,
.Nm ASYNC_WAIT_CTX_set_wait_fd ,
.Nm ASYNC_WAIT_CTX_get_fd ,
.Nm ASYNC_WAIT_CTX_get_all_fds ,
.Nm ASYNC_WAIT_CTX_get_changed_fds ,
.Nm ASYNC_WAIT_CTX_clear_fd ,
.Nm ASYNC_WAIT_CTX_set_callback ,
.Nm ASYNC_WAIT_CTX_get_callback ,
.Nm ASYNC_WAIT_CTX_set_status ,
.Nm ASYNC_WAIT_CTX_get_status ,
.Nm ASYNC_callback_fn ,
.Nm ASYNC_STATUS_UNSUPPORTED ,
.Nm ASYNC_STATUS_ERR ,
.Nm ASYNC_STATUS_OK ,
.Nm ASYNC_STATUS_EAGAIN
.Nd functions to manage waiting for asynchronous jobs to complete
.Sh SYNOPSIS
.In openssl/async.h
.Fd #define ASYNC_STATUS_UNSUPPORTED    0
.Fd #define ASYNC_STATUS_ERR            1
.Fd #define ASYNC_STATUS_OK             2
.Fd #define ASYNC_STATUS_EAGAIN         3
.Ft typedef int
.Fo 
.Fa *ASYNC_callback_fn
.Fc
(void *arg);
.Ft ASYNC_WAIT_CTX *
.Fo ASYNC_WAIT_CTX_new
.Fa void
.Fc
.Ft void
.Fo ASYNC_WAIT_CTX_free
.Fa "ASYNC_WAIT_CTX *ctx"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_set_wait_fd
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "const void *key"
.Fa "OSSL_ASYNC_FD fd"
.Fa "void *custom_data"
.Fa "void (*cleanup)(ASYNC_WAIT_CTX *"
.Fa "const void *"
.Fa OSSL_ASYNC_FD
.Fa "void *)"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_get_fd
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "const void *key"
.Fa "OSSL_ASYNC_FD *fd"
.Fa "void **custom_data"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_get_all_fds
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "OSSL_ASYNC_FD *fd"
.Fa "size_t *numfds"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_get_changed_fds
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "OSSL_ASYNC_FD *addfd"
.Fa "size_t *numaddfds"
.Fa "OSSL_ASYNC_FD *delfd"
.Fa "size_t *numdelfds"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_clear_fd
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "const void *key"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_set_callback
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "ASYNC_callback_fn callback"
.Fa "void *callback_arg"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_get_callback
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "ASYNC_callback_fn *callback"
.Fa "void **callback_arg"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_set_status
.Fa "ASYNC_WAIT_CTX *ctx"
.Fa "int status"
.Fc
.Ft int
.Fo ASYNC_WAIT_CTX_get_status
.Fa "ASYNC_WAIT_CTX *ctx"
.Fc
.Sh DESCRIPTION
For an overview of how asynchronous operations are implemented in
OpenSSL see
.Xr ASYNC_start_job 3 .
An
.Vt ASYNC_WAIT_CTX
object represents an asynchronous "session", i.e.
a related set of crypto operations.
For example in SSL terms this would have a one-to-one correspondence
with an SSL connection.
.Pp
Application code must create an
.Vt ASYNC_WAIT_CTX
using the
.Fn ASYNC_WAIT_CTX_new
function prior to calling
.Xr ASYNC_start_job 3
(see
.Xr ASYNC_start_job 3 Ns ).
When the job is started it is associated with the
.Vt ASYNC_WAIT_CTX
for the duration of that job.
An
.Vt ASYNC_WAIT_CTX
should only be used for one
.Sy ASYNC_JOB
at any one time, but can be reused after an
.Sy ASYNC_JOB
has finished for a subsequent
.Sy ASYNC_JOB .
When the session is complete (e.g.
the SSL connection is closed), application code cleans up with
.Fn ASYNC_WAIT_CTX_free .
.Pp
.Vt ASYNC_WAIT_CTX Ns s
can have "wait" file descriptors associated with them.
Calling
.Fn ASYNC_WAIT_CTX_get_all_fds
and passing in a pointer to an
.Vt ASYNC_WAIT_CTX
in the
.Fa ctx
parameter will return the wait file descriptors associated with that job
in
.Em *fd .
The number of file descriptors returned will be stored in
.Em *numfds .
It is the caller's responsibility to ensure that sufficient memory has
been allocated in
.Em *fd
to receive all the file descriptors.
Calling
.Fn ASYNC_WAIT_CTX_get_all_fds
with a NULL
.Fa fd
value will return no file descriptors but will still populate
.Em *numfds .
Therefore, application code is typically expected to call this function
twice: once to get the number of fds, and then again when sufficient
memory has been allocated.
If only one asynchronous engine is being used then normally this call
will only ever return one fd.
If multiple asynchronous engines are being used then more could be
returned.
.Pp
The function
.Fn ASYNC_WAIT_CTX_get_changed_fds
can be used to detect if any fds have changed since the last call time
.Xr ASYNC_start_job 3
returned
.Sy ASYNC_PAUSE
(or since the
.Vt ASYNC_WAIT_CTX
was created if no
.Sy ASYNC_PAUSE
result has been received).
The
.Fa numaddfds
and
.Fa numdelfds
parameters will be populated with the number of fds added or deleted
respectively.
.Em *addfd
and
.Em *delfd
will be populated with the list of added and deleted fds respectively.
Similarly to
.Fn ASYNC_WAIT_CTX_get_all_fds
either of these can be NULL, but if they are not NULL then the caller is
responsible for ensuring sufficient memory is allocated.
.Pp
Implementers of async aware code (e.g.
engines) are encouraged to return a stable fd for the lifetime of the
.Vt ASYNC_WAIT_CTX
in order to reduce the "churn" of regularly changing fds - although no
guarantees of this are provided to applications.
.Pp
Applications can wait for the file descriptor to be ready for "read"
using a system function call such as select or poll (being ready for
"read" indicates that the job should be resumed).
If no file descriptor is made available then an application will have to
periodically "poll" the job by attempting to restart it to see if it is
ready to continue.
.Pp
Async aware code (e.g.
engines) can get the current
.Vt ASYNC_WAIT_CTX
from the job via
.Xr ASYNC_get_wait_ctx 3
and provide a file descriptor to use for waiting on by calling
.Fn ASYNC_WAIT_CTX_set_wait_fd .
Typically this would be done by an engine immediately prior to calling
.Xr ASYNC_pause_job 3
and not by end user code.
An existing association with a file descriptor can be obtained using
.Fn ASYNC_WAIT_CTX_get_fd
and cleared using
.Fn ASYNC_WAIT_CTX_clear_fd .
Both of these functions requires a
.Fa key
value which is unique to the async aware code.
This could be any unique value but a good candidate might be the
.Sy ENGINE *
for the engine.
The
.Fa custom_data
parameter can be any value, and will be returned in a subsequent call to
.Fn ASYNC_WAIT_CTX_get_fd .
The
.Fn ASYNC_WAIT_CTX_set_wait_fd
function also expects a pointer to a "cleanup" routine.
This can be NULL but if provided will automatically get called when the
.Vt ASYNC_WAIT_CTX
is freed, and gives the engine the opportunity to close the fd or any
other resources.
Note: The "cleanup" routine does not get called if the fd is cleared
directly via a call to
.Fn ASYNC_WAIT_CTX_clear_fd .
.Pp
An example of typical usage might be an async capable engine.
User code would initiate cryptographic operations.
The engine would initiate those operations asynchronously and then call
.Fn ASYNC_WAIT_CTX_set_wait_fd
followed by
.Xr ASYNC_pause_job 3
to return control to the user code.
The user code can then perform other tasks or wait for the job to be
ready by calling "select" or other similar function on the wait file
descriptor.
The engine can signal to the user code that the job should be resumed by
making the wait file descriptor "readable".
Once resumed the engine should clear the wake signal on the wait file
descriptor.
.Pp
As well as a file descriptor, user code may also be notified via a
callback.
The callback and data pointers are stored within the
.Vt ASYNC_WAIT_CTX
along with an additional status field that can be used for the
notification of retries from an engine.
This additional method can be used when the user thinks that a file
descriptor is too costly in terms of CPU cycles or in some context where
a file descriptor is not appropriate.
.Pp
.Fn ASYNC_WAIT_CTX_set_callback
sets the callback and the callback argument.
The callback will be called to notify user code when an engine completes
a cryptography operation.
It is a requirement that the callback function is small and nonblocking
as it will be run in the context of a polling mechanism or an interrupt.
.Pp
.Fn ASYNC_WAIT_CTX_get_callback
returns the callback set in the
.Vt ASYNC_WAIT_CTX
structure.
.Pp
.Fn ASYNC_WAIT_CTX_set_status
allows an engine to set the current engine status.
The possible status values are the following:
.Bl -tag -width Ds
.It Sy ASYNC_STATUS_UNSUPPORTED
The engine does not support the callback mechanism.
This is the default value.
The engine must call
.Fn ASYNC_WAIT_CTX_set_status
to set the status to some value other than
.Sy ASYNC_STATUS_UNSUPPORTED
if it intends to enable the callback mechanism.
.It Sy ASYNC_STATUS_ERR
The engine has a fatal problem with this request.
The user code should clean up this session.
.It Sy ASYNC_STATUS_OK
The request has been successfully submitted.
.It Sy ASYNC_STATUS_EAGAIN
The engine has some problem which will be recovered soon, such as a
buffer is full, so user code should resume the job.
.El
.Pp
.Fn ASYNC_WAIT_CTX_get_status
allows user code to obtain the current status value.
If the status is any value other than
.Sy ASYNC_STATUS_OK
then the user code should not expect to receive a callback from the
engine even if one has been set.
.Pp
An example of the usage of the callback method might be the following.
User code would initiate cryptographic operations, and the engine code
would dispatch this operation to hardware, and if the dispatch is
successful, then the engine code would call
.Xr ASYNC_pause_job 3
to return control to the user code.
After that, user code can perform other tasks.
When the hardware completes the operation, normally it is detected by a
polling function or an interrupt, as the user code set a callback by
calling
.Fn ASYNC_WAIT_CTX_set_callback
previously, then the registered callback will be called.
.Pp
.Fn ASYNC_WAIT_CTX_free
frees up a single
.Vt ASYNC_WAIT_CTX
object.
If the argument is NULL, nothing is done.
.Sh RETURN VALUES
.Fn ASYNC_WAIT_CTX_new
returns a pointer to the newly allocated
.Vt ASYNC_WAIT_CTX
or NULL on error.
.Pp
ASYNC_WAIT_CTX_set_wait_fd, ASYNC_WAIT_CTX_get_fd,
ASYNC_WAIT_CTX_get_all_fds, ASYNC_WAIT_CTX_get_changed_fds,
ASYNC_WAIT_CTX_clear_fd, ASYNC_WAIT_CTX_set_callback,
ASYNC_WAIT_CTX_get_callback and ASYNC_WAIT_CTX_set_status all return 1
on success or 0 on error.
.Fn ASYNC_WAIT_CTX_get_status
returns the engine status.
.Sh NOTES
On Windows platforms the
.Pa <openssl/async.h>
header is dependent on some of the types customarily made available by
including
.Pa <windows.h> .
The application developer is likely to require control over when the
latter is included, commonly as one of the first included headers.
Therefore, it is defined as an application developer's responsibility to
include
.Pa <windows.h>
prior to
.Pa <openssl/async.h> .
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr ASYNC_start_job 3
.Sh HISTORY
.Fn ASYNC_WAIT_CTX_new ,
.Fn ASYNC_WAIT_CTX_free ,
.Fn ASYNC_WAIT_CTX_set_wait_fd ,
.Fn ASYNC_WAIT_CTX_get_fd ,
.Fn ASYNC_WAIT_CTX_get_all_fds ,
.Fn ASYNC_WAIT_CTX_get_changed_fds
and
.Fn ASYNC_WAIT_CTX_clear_fd
were added in OpenSSL 1.1.0.
.Pp
.Fn ASYNC_WAIT_CTX_set_callback ,
.Fn ASYNC_WAIT_CTX_get_callback ,
.Fn ASYNC_WAIT_CTX_set_status ,
and
.Fn ASYNC_WAIT_CTX_get_status
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
