.Dd 2025-09-30
.Dt BIO_F_BUFFER 3ossl
.Os
.Sh NAME
.Nm BIO_get_buffer_num_lines ,
.Nm BIO_set_read_buffer_size ,
.Nm BIO_set_write_buffer_size ,
.Nm BIO_set_buffer_size ,
.Nm BIO_set_buffer_read_data ,
.Nm BIO_f_buffer
.Nd buffering BIO
.Sh SYNOPSIS
.In openssl/bio.h
.Ft const BIO_METHOD *
.Fo BIO_f_buffer
.Fa void
.Fc
.Ft long
.Fo BIO_get_buffer_num_lines
.Fa "BIO *b"
.Fc
.Ft long
.Fo BIO_set_read_buffer_size
.Fa "BIO *b"
.Fa "long size"
.Fc
.Ft long
.Fo BIO_set_write_buffer_size
.Fa "BIO *b"
.Fa "long size"
.Fc
.Ft long
.Fo BIO_set_buffer_size
.Fa "BIO *b"
.Fa "long size"
.Fc
.Ft long
.Fo BIO_set_buffer_read_data
.Fa "BIO *b"
.Fa "void *buf"
.Fa "long num"
.Fc
.Sh DESCRIPTION
.Fn BIO_f_buffer
returns the buffering BIO method.
.Pp
Data written to a buffering BIO is buffered and periodically written to
the next BIO in the chain.
Data read from a buffering BIO comes from an internal buffer which is
filled from the next BIO in the chain.
Both
.Xr BIO_gets 3
and
.Xr BIO_puts 3
are supported.
.Pp
Calling
.Xr BIO_reset 3
on a buffering BIO clears any buffered data.
.Pp
.Fn BIO_get_buffer_num_lines
returns the number of lines currently buffered.
.Pp
.Fn BIO_set_read_buffer_size ,
.Fn BIO_set_write_buffer_size
and
.Fn BIO_set_buffer_size
set the read, write or both read and write buffer sizes to
.Fa size .
The initial buffer size is DEFAULT_BUFFER_SIZE, currently 4096. Any
attempt to reduce the buffer size below DEFAULT_BUFFER_SIZE is ignored.
Any buffered data is cleared when the buffer is resized.
.Pp
.Fn BIO_set_buffer_read_data
clears the read buffer and fills it with
.Fa num
bytes of
.Fa buf .
If
.Fa num
is larger than the current buffer size the buffer is expanded.
.Sh NOTES
These functions, other than
.Fn BIO_f_buffer ,
are implemented as macros.
.Pp
Buffering BIOs implement
.Xr BIO_read_ex 3
and
.Xr BIO_gets 3
by using
.Xr BIO_read_ex 3
operations on the next BIO in the chain and storing the result in an
internal buffer, from which bytes are given back to the caller as
appropriate for the call; a
.Xr BIO_gets 3
is guaranteed to give the caller a whole line, and
.Xr BIO_read_ex 3
is guaranteed to give the caller the number of bytes it asks for, unless
there's an error or end of communication is reached in the next BIO. By
prepending a buffering BIO to a chain it is therefore possible to
provide
.Xr BIO_gets 3
or exact size
.Xr BIO_read_ex 3
functionality if the following BIOs do not support it.
.Pp
Do not add more than one
.Fn BIO_f_buffer
to a BIO chain.
The result of doing so will force a full read of the size of the
internal buffer of the top
.Fn BIO_f_buffer ,
which is 4 KiB at a minimum.
.Pp
Data is only written to the next BIO in the chain when the write buffer
fills or when
.Xr BIO_flush 3
is called.
It is therefore important to call
.Xr BIO_flush 3
whenever any pending data should be written such as when removing a
buffering BIO using
.Xr BIO_pop 3 .
.Xr BIO_flush 3
may need to be retried if the ultimate source/sink BIO is non blocking.
.Sh RETURN VALUES
.Fn BIO_f_buffer
returns the buffering BIO method.
.Pp
.Fn BIO_get_buffer_num_lines
returns the number of lines buffered (may be 0) or a negative value in
case of errors.
.Pp
.Fn BIO_set_read_buffer_size ,
.Fn BIO_set_write_buffer_size
and
.Fn BIO_set_buffer_size
return 1 if the buffer was successfully resized or <=0 for failure.
.Pp
.Fn BIO_set_buffer_read_data
returns 1 if the data was set correctly or <=0 if there was an error.
.Sh SEE ALSO
.Xr bio 7 ,
.Xr BIO_reset 3 ,
.Xr BIO_flush 3 ,
.Xr BIO_pop 3 ,
.Xr BIO_ctrl 3 .
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
