.Dd 2025-09-30
.Dt BIO_METH_NEW 3ossl
.Os
.Sh NAME
.Nm BIO_get_new_index ,
.Nm BIO_meth_new ,
.Nm BIO_meth_free ,
.Nm BIO_meth_get_read_ex ,
.Nm BIO_meth_set_read_ex ,
.Nm BIO_meth_get_write_ex ,
.Nm BIO_meth_set_write_ex ,
.Nm BIO_meth_get_write ,
.Nm BIO_meth_set_write ,
.Nm BIO_meth_get_read ,
.Nm BIO_meth_set_read ,
.Nm BIO_meth_get_puts ,
.Nm BIO_meth_set_puts ,
.Nm BIO_meth_get_gets ,
.Nm BIO_meth_set_gets ,
.Nm BIO_meth_get_ctrl ,
.Nm BIO_meth_set_ctrl ,
.Nm BIO_meth_get_create ,
.Nm BIO_meth_set_create ,
.Nm BIO_meth_get_destroy ,
.Nm BIO_meth_set_destroy ,
.Nm BIO_meth_get_callback_ctrl ,
.Nm BIO_meth_set_callback_ctrl ,
.Nm BIO_meth_set_sendmmsg ,
.Nm BIO_meth_get_sendmmsg ,
.Nm BIO_meth_set_recvmmsg ,
.Nm BIO_meth_get_recvmmsg
.Nd Routines to build up BIO methods
.Sh SYNOPSIS
.In openssl/bio.h
.Ft int
.Fo BIO_get_new_index
.Fa void
.Fc
.Ft BIO_METHOD *
.Fo BIO_meth_new
.Fa "int type"
.Fa "const char *name"
.Fc
.Ft void
.Fo BIO_meth_free
.Fa "BIO_METHOD *biom"
.Fc
.Ft int
.Fo BIO_meth_set_write_ex
.Fa "BIO_METHOD *biom"
.Fa "int (*bwrite)(BIO *"
.Fa "const char *"
.Fa size_t
.Fa "size_t *)"
.Fc
.Ft int
.Fo BIO_meth_set_write
.Fa "BIO_METHOD *biom"
.Fa "int (*write)(BIO *"
.Fa "const char *"
.Fa int)
.Fc
.Ft int
.Fo BIO_meth_set_read_ex
.Fa "BIO_METHOD *biom"
.Fa "int (*bread)(BIO *"
.Fa "char *"
.Fa size_t
.Fa "size_t *)"
.Fc
.Ft int
.Fo BIO_meth_set_read
.Fa "BIO_METHOD *biom"
.Fa "int (*read)(BIO *"
.Fa "char *"
.Fa int)
.Fc
.Ft int
.Fo BIO_meth_set_puts
.Fa "BIO_METHOD *biom"
.Fa "int (*puts)(BIO *"
.Fa "const char *)"
.Fc
.Ft int
.Fo BIO_meth_set_gets
.Fa "BIO_METHOD *biom"
.Fa "int (*gets)(BIO *"
.Fa "char *"
.Fa int)
.Fc
.Ft int
.Fo BIO_meth_set_ctrl
.Fa "BIO_METHOD *biom"
.Fa "long (*ctrl)(BIO *"
.Fa int
.Fa long
.Fa "void *)"
.Fc
.Ft int
.Fo BIO_meth_set_create
.Fa "BIO_METHOD *biom"
.Fa "int (*create)(BIO *)"
.Fc
.Ft int
.Fo BIO_meth_set_destroy
.Fa "BIO_METHOD *biom"
.Fa "int (*destroy)(BIO *)"
.Fc
.Ft int
.Fo BIO_meth_set_callback_ctrl
.Fa "BIO_METHOD *biom"
.Fa "long (*callback_ctrl)(BIO *"
.Fa int
.Fa "BIO_info_cb *)"
.Fc
.Ft int
.Fo BIO_meth_set_sendmmsg
.Fa "BIO_METHOD *biom"
.Fa "ossl_ssize_t (*f) (BIO *"
.Fa "BIO_MSG *"
.Fa size_t
.Fa size_t
.Fa uint64_t)
.Fc
.Ft int
.Fo BIO_meth_set_recvmmsg
.Fa "BIO_METHOD *biom"
.Fa "ossl_ssize_t (*f) (BIO *"
.Fa "BIO_MSG *"
.Fa size_t
.Fa size_t
.Fa uint64_t)
.Fc
The following functions have been deprecated since OpenSSL 3.5:
.Ft int
.Fo 
.Fa "*BIO_meth_get_write_ex(const BIO_METHOD *biom)"
.Fc
(BIO *, const char *, size_t,
.Bd -literal
                                                size_t *);
 int (*BIO_meth_get_write(const BIO_METHOD *biom))(BIO *, const char *, int);
.Ed
.Ft int
.Fo 
.Fa "*BIO_meth_get_read_ex(const BIO_METHOD *biom)"
.Fc
(BIO *, char *, size_t, size_t *);
.Ft int
.Fo 
.Fa "*BIO_meth_get_read(const BIO_METHOD *biom)"
.Fc
(BIO *, char *, int);
.Ft int
.Fo 
.Fa "*BIO_meth_get_puts(const BIO_METHOD *biom)"
.Fc
(BIO *, const char *);
.Ft int
.Fo 
.Fa "*BIO_meth_get_gets(const BIO_METHOD *biom)"
.Fc
(BIO *, char *, int);
.Ft long
.Fo 
.Fa "*BIO_meth_get_ctrl(const BIO_METHOD *biom)"
.Fc
(BIO *, int, long, void *);
.Ft int
.Fo 
.Fa "*BIO_meth_get_create(const BIO_METHOD *bion)"
.Fc
(BIO *);
.Ft int
.Fo 
.Fa "*BIO_meth_get_destroy(const BIO_METHOD *biom)"
.Fc
(BIO *);
.Ft long
.Fo 
.Fa "*BIO_meth_get_callback_ctrl(const BIO_METHOD *biom)"
.Fc
(BIO *, int, BIO_info_cb *);
.Ft ossl_ssize_t
.Fo 
.Fa "*BIO_meth_get_sendmmsg(const BIO_METHOD *biom)"
.Fc
(BIO *,
.Bd -literal
                                                               BIO_MSG *,
                                                               size_t,
                                                               size_t,
                                                               uint64_t);
 ossl_ssize_t (*BIO_meth_get_recvmmsg(const BIO_METHOD *biom))(BIO *,
                                                               BIO_MSG *,
                                                               size_t,
                                                               size_t,
                                                               uint64_t);
.Ed
.Sh DESCRIPTION
The
.Vt BIO_METHOD
type is a structure used for the implementation of new BIO types.
It provides a set of functions used by OpenSSL for the implementation of
the various BIO capabilities.
See the
.Xr bio 7
page for more information.
.Pp
.Fn BIO_meth_new
creates a new
.Vt BIO_METHOD
structure that contains a type identifier
.Fa type
and a string that represents its
.Fa name .
.Fa type
can be set to either
.Sy BIO_TYPE_NONE
or via
.Fn BIO_get_new_index
if a unique type is required for searching (See
.Xr BIO_find_type 3 )
.Pp
Note that
.Fn BIO_get_new_index
can only be used 127 times before it returns an error.
.Pp
The set of standard OpenSSL provided BIO types is provided in
.Pa <openssl/bio.h> .
Some examples include
.Sy BIO_TYPE_BUFFER
and
.Sy BIO_TYPE_CIPHER .
Filter BIOs should have a type which have the "filter" bit set
.Pf ( Sy BIO_TYPE_FILTER Ns ).
Source/sink BIOs should have the "source/sink" bit set
.Pf ( Sy BIO_TYPE_SOURCE_SINK Ns ).
File descriptor based BIOs (e.g.
socket, fd, connect, accept etc) should additionally have the
"descriptor" bit set
.Pf ( Sy BIO_TYPE_DESCRIPTOR Ns ).
See the
.Xr BIO_find_type 3
page for more information.
.Pp
.Fn BIO_meth_free
destroys a
.Vt BIO_METHOD
structure and frees up any memory associated with it.
If the argument is NULL, nothing is done.
.Pp
.Xr BIO_meth_get_write_ex 3
and
.Fn BIO_meth_set_write_ex
get and set the function used for writing arbitrary length data to the
BIO respectively.
This function will be called in response to the application calling
.Xr BIO_write_ex 3
or
.Xr BIO_write 3 .
The parameters for the function have the same meaning as for
.Xr BIO_write_ex 3 .
Older code may call
.Xr BIO_meth_get_write 3
and
.Fn BIO_meth_set_write
instead.
Applications should not call both
.Fn BIO_meth_set_write_ex
and
.Fn BIO_meth_set_write
or call
.Xr BIO_meth_get_write 3
when the function was set with
.Fn BIO_meth_set_write_ex .
.Pp
.Xr BIO_meth_get_read_ex 3
and
.Fn BIO_meth_set_read_ex
get and set the function used for reading arbitrary length data from the
BIO respectively.
This function will be called in response to the application calling
.Xr BIO_read_ex 3
or
.Xr BIO_read 3 .
The parameters for the function have the same meaning as for
.Xr BIO_read_ex 3 .
Older code may call
.Xr BIO_meth_get_read 3
and
.Fn BIO_meth_set_read
instead.
Applications should not call both
.Fn BIO_meth_set_read_ex
and
.Fn BIO_meth_set_read
or call
.Xr BIO_meth_get_read 3
when the function was set with
.Fn BIO_meth_set_read_ex .
.Pp
.Xr BIO_meth_get_puts 3
and
.Fn BIO_meth_set_puts
get and set the function used for writing a NULL terminated string to
the BIO respectively.
This function will be called in response to the application calling
.Xr BIO_puts 3 .
The parameters for the function have the same meaning as for
.Xr BIO_puts 3 .
.Pp
.Xr BIO_meth_get_gets 3
and
.Fn BIO_meth_set_gets
get and set the function typically used for reading a line of data from
the BIO respectively (see the
.Xr BIO_gets 3
page for more information).
This function will be called in response to the application calling
.Xr BIO_gets 3 .
The parameters for the function have the same meaning as for
.Xr BIO_gets 3 .
.Pp
.Xr BIO_meth_get_ctrl 3
and
.Fn BIO_meth_set_ctrl
get and set the function used for processing ctrl messages in the BIO
respectively.
See the
.Xr BIO_ctrl 3
page for more information.
This function will be called in response to the application calling
.Xr BIO_ctrl 3 .
The parameters for the function have the same meaning as for
.Xr BIO_ctrl 3 .
.Pp
.Xr BIO_meth_get_create 3
and
.Fn BIO_meth_set_create
get and set the function used for creating a new instance of the BIO
respectively.
This function will be called in response to the application calling
.Xr BIO_new 3
and passing in a pointer to the current BIO_METHOD. The
.Xr BIO_new 3
function will allocate the memory for the new BIO, and a pointer to this
newly allocated structure will be passed as a parameter to the function.
If a create function is set,
.Xr BIO_new 3
will not mark the BIO as initialised on allocation.
.Xr BIO_set_init 3
must then be called either by the create function, or later, by a BIO
ctrl function, once BIO initialisation is complete.
.Pp
.Xr BIO_meth_get_destroy 3
and
.Fn BIO_meth_set_destroy
get and set the function used for destroying an instance of a BIO
respectively.
This function will be called in response to the application calling
.Xr BIO_free 3 .
A pointer to the BIO to be destroyed is passed as a parameter.
The destroy function should be used for BIO specific clean up.
The memory for the BIO itself should not be freed by this function.
.Pp
.Xr BIO_meth_get_callback_ctrl 3
and
.Fn BIO_meth_set_callback_ctrl
get and set the function used for processing callback ctrl messages in
the BIO respectively.
See the
.Xr BIO_callback_ctrl 3
page for more information.
This function will be called in response to the application calling
.Xr BIO_callback_ctrl 3 .
The parameters for the function have the same meaning as for
.Xr BIO_callback_ctrl 3 .
.Pp
.Xr BIO_meth_get_sendmmsg 3 ,
.Fn BIO_meth_set_sendmmsg ,
.Xr BIO_meth_get_recvmmsg 3
and
.Fn BIO_meth_set_recvmmsg
get and set the functions used for handling
.Xr BIO_sendmmsg 3
and
.Xr BIO_recvmmsg 3
calls respectively.
See
.Xr BIO_sendmmsg 3
for more information.
.Sh RETURN VALUES
.Fn BIO_get_new_index
returns the new BIO type value or -1 if an error occurred.
.Pp
BIO_meth_new(int type, const char *name) returns a valid
.Vt BIO_METHOD
or NULL if an error occurred.
.Pp
The
.Sy BIO_meth_set
functions return 1 on success or 0 on error.
.Pp
The
.Sy BIO_meth_get
functions return the corresponding function pointers.
.Sh BUGS
It is not safe to use
.Qo Li BIO_meth_get_ Qc
functions to reuse the
.Sy BIO
implementation of
.Sy BIO Ns s
implemented by OpenSSL itself with application-implemented
.Sy BIO Ns s.
Instead either the applications ought to implement these functions
themselves or they should implement a filter BIO.
.Pp
For more details please see
.Lk https://github.com/openssl/openssl/issues/26047 .
.Sh SEE ALSO
.Xr bio 7 ,
.Xr BIO_find_type 3 ,
.Xr BIO_ctrl 3 ,
.Xr BIO_read_ex 3 ,
.Xr BIO_new 3
.Sh HISTORY
The functions
.Xr BIO_meth_get_sendmmsg 3 ,
.Fn BIO_meth_set_sendmmsg ,
.Xr BIO_meth_get_recvmmsg 3
and
.Fn BIO_meth_set_recvmmsg
were added in OpenSSL 3.2.
.Pp
All the other functions described here were added in OpenSSL 1.1.0.
.Pp
The functions
.Xr BIO_meth_get_read_ex 3 ,
.Xr BIO_meth_get_write_ex 3 ,
.Xr BIO_meth_get_write 3 ,
.Xr BIO_meth_get_read 3 ,
.Xr BIO_meth_get_puts 3 ,
.Xr BIO_meth_get_gets 3 ,
.Xr BIO_meth_get_ctrl 3 ,
.Xr BIO_meth_get_create 3 ,
.Xr BIO_meth_get_destroy 3 ,
.Xr BIO_meth_get_callback_ctrl 3 ,
.Xr BIO_meth_get_sendmmsg 3
and
.Xr BIO_meth_get_recvmmsg 3
are deprecated since OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
