.Dd 2025-09-30
.Dt BIO_S_CORE 3ossl
.Os
.Sh NAME
.Nm BIO_s_core ,
.Nm BIO_new_from_core_bio
.Nd OSSL_CORE_BIO functions
.Sh SYNOPSIS
.In openssl/bio.h
.Ft const BIO_METHOD *
.Fo BIO_s_core
.Fa void
.Fc
.Ft BIO *
.Fo BIO_new_from_core_bio
.Fa "OSSL_LIB_CTX *libctx"
.Fa "OSSL_CORE_BIO *corebio"
.Fc
.Sh DESCRIPTION
.Fn BIO_s_core
returns the core BIO method function.
.Pp
A core BIO is treated as source/sink BIO which communicates to some
external BIO. This is primarily useful to provider authors.
A number of calls from libcrypto into a provider supply an OSSL_CORE_BIO
parameter.
This represents a BIO within libcrypto, but cannot be used directly by a
provider.
Instead it should be wrapped using a
.Fn BIO_s_core .
.Pp
Once a BIO is constructed based on
.Fn BIO_s_core ,
the associated OSSL_CORE_BIO object should be set on it using
BIO_set_data(3). Note that the BIO will only operate correctly if it is
associated with a library context constructed using
OSSL_LIB_CTX_new_from_dispatch(3). To associate the BIO with a library
context construct it using BIO_new_ex(3).
.Pp
.Fn BIO_new_from_core_bio
is a convenience function that constructs a new BIO based on
.Fn BIO_s_core
and that is associated with the given library context.
It then also sets the OSSL_CORE_BIO object on the BIO using
BIO_set_data(3).
.Sh RETURN VALUES
.Fn BIO_s_core
return a core BIO
.Sy BIO_METHOD
structure.
.Pp
.Fn BIO_new_from_core_bio
returns a BIO structure on success or NULL on failure.
A failure will most commonly be because the library context was not
constructed using OSSL_LIB_CTX_new_from_dispatch(3).
.Sh HISTORY
.Fn BIO_s_core
and
.Fn BIO_new_from_core_bio
were added in OpenSSL 3.0.
.Sh EXAMPLES
Create a core BIO and write some data to it:
.Bd -literal
 int some_function(OSSL_LIB_CTX *libctx, OSSL_CORE_BIO *corebio) {
     BIO *cbio = BIO_new_from_core_bio(libctx, corebio);

     if (cbio == NULL)
         return 0;

     BIO_puts(cbio, "Hello World\en");

     BIO_free(cbio);
     return 1;
 }
.Ed
.Sh COPYRIGHT
Copyright 2021-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
