.Dd 2025-09-30
.Dt BIO_GET_DATA 3ossl
.Os
.Sh NAME
.Nm BIO_set_data ,
.Nm BIO_get_data ,
.Nm BIO_set_init ,
.Nm BIO_get_init ,
.Nm BIO_set_shutdown ,
.Nm BIO_get_shutdown
.Nd functions for managing BIO state information
.Sh SYNOPSIS
.In openssl/bio.h
.Ft void
.Fo BIO_set_data
.Fa "BIO *a"
.Fa "void *ptr"
.Fc
.Ft void *
.Fo BIO_get_data
.Fa "BIO *a"
.Fc
.Ft void
.Fo BIO_set_init
.Fa "BIO *a"
.Fa "int init"
.Fc
.Ft int
.Fo BIO_get_init
.Fa "BIO *a"
.Fc
.Ft void
.Fo BIO_set_shutdown
.Fa "BIO *a"
.Fa "int shut"
.Fc
.Ft int
.Fo BIO_get_shutdown
.Fa "BIO *a"
.Fc
.Sh DESCRIPTION
These functions are mainly useful when implementing a custom BIO.
.Pp
The
.Fn BIO_set_data
function associates the custom data pointed to by
.Fa ptr
with the BIO. This data can subsequently be retrieved via a call to
.Fn BIO_get_data .
This can be used by custom BIOs for storing implementation specific
information.
.Pp
The
.Fn BIO_set_init
function sets the value of the BIO's "init" flag to indicate whether
initialisation has been completed for this BIO or not.
A nonzero value indicates that initialisation is complete, whilst zero
indicates that it is not.
Often initialisation will complete during initial construction of the
BIO. For some BIOs however, initialisation may not complete until after
additional steps have occurred (for example through calling custom
ctrls).
The
.Fn BIO_get_init
function returns the value of the "init" flag.
.Pp
The
.Fn BIO_set_shutdown
and
.Fn BIO_get_shutdown
functions set and get the state of this BIO's shutdown (i.e.
BIO_CLOSE) flag.
If set then the underlying resource is also closed when the BIO is
freed.
.Sh RETURN VALUES
.Fn BIO_get_data
returns a pointer to the implementation specific custom data associated
with this BIO, or NULL if none has been set.
.Pp
.Fn BIO_get_init
returns the state of the BIO's init flag.
.Pp
.Fn BIO_get_shutdown
returns the stat of the BIO's shutdown (i.e.
BIO_CLOSE) flag.
.Sh SEE ALSO
.Xr bio 7 ,
.Xr BIO_meth_new 3
.Sh HISTORY
The functions described here were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
