.Dd 2025-09-30
.Dt BIO_PARSE_HOSTSERV 3ossl
.Os
.Sh NAME
.Nm BIO_hostserv_priorities ,
.Nm BIO_parse_hostserv
.Nd utility routines to parse a standard host and service string
.Sh SYNOPSIS
.In openssl/bio.h
.Ft enum BIO_hostserv_priorities {
     BIO_PARSE_PRIO_HOST, BIO_PARSE_PRIO_SERV
 };
 int
.Fo BIO_parse_hostserv
.Fa "const char *hostserv"
.Fa "char **host"
.Fa "char **service"
.Fa "enum BIO_hostserv_priorities hostserv_prio"
.Fc
.Sh DESCRIPTION
.Fn BIO_parse_hostserv
will parse the information given in
.Fa hostserv ,
create strings with the hostname and service name and give those back
via
.Fa host
and
.Fa service .
Those will need to be freed after they are used.
.Fa hostserv_prio
helps determine if
.Fa hostserv
shall be interpreted primarily as a hostname or a service name in
ambiguous cases.
.Pp
The syntax the
.Fn BIO_parse_hostserv
recognises is:
.Bd -literal
 host + ':' + service
 host + ':' + '*'
 host + ':'
        ':' + service
 '*'  + ':' + service
 host
 service
.Ed
.Pp
The host part can be a name or an IP address.
If it's a IPv6 address, it MUST be enclosed in brackets, such as
'[::1]'.
.Pp
The service part can be a service name or its port number.
A service name will be mapped to a port number using the system function
.Xr getservbyname 3 .
.Pp
The returned values will depend on the given
.Fa hostserv
string and
.Fa hostserv_prio ,
as follows:
.Bd -literal
 host + ':' + service  => *host = "host", *service = "service"
 host + ':' + '*'      => *host = "host", *service = NULL
 host + ':'            => *host = "host", *service = NULL
        ':' + service  => *host = NULL, *service = "service"
  '*' + ':' + service  => *host = NULL, *service = "service"

 in case no ':' is present in the string, the result depends on
 hostserv_prio, as follows:

 when hostserv_prio == BIO_PARSE_PRIO_HOST
 host                 => *host = "host", *service untouched

 when hostserv_prio == BIO_PARSE_PRIO_SERV
 service              => *host untouched, *service = "service"
.Ed
.Sh RETURN VALUES
.Fn BIO_parse_hostserv
returns 1 on success or 0 on error.
.Sh SEE ALSO
.Xr BIO_ADDRINFO 3
.Sh COPYRIGHT
Copyright 2016-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
