.Dd 2025-09-30
.Dt BIO_PRINTF 3ossl
.Os
.Sh NAME
.Nm BIO_printf ,
.Nm BIO_vprintf ,
.Nm BIO_snprintf ,
.Nm BIO_vsnprintf
.Nd formatted output to a BIO
.Sh SYNOPSIS
.In openssl/bio.h
.Ft int
.Fo BIO_printf
.Fa "BIO *bio"
.Fa "const char *format"
.Fa ...
.Fc
.Ft int
.Fo BIO_vprintf
.Fa "BIO *bio"
.Fa "const char *format"
.Fa "va_list args"
.Fc
.Ft int
.Fo BIO_snprintf
.Fa "char *buf"
.Fa "size_t n"
.Fa "const char *format"
.Fa ...
.Fc
.Ft int
.Fo BIO_vsnprintf
.Fa "char *buf"
.Fa "size_t n"
.Fa "const char *format"
.Fa "va_list args"
.Fc
.Sh DESCRIPTION
.Fn BIO_printf
is similar to the standard C
.Xr printf 3
function, except that the output is sent to the specified BIO,
.Fa bio ,
rather than standard output.
All common format specifiers are supported.
.Pp
.Fn BIO_vprintf
is similar to the
.Xr vprintf 3
function found on many platforms, the output is sent to the specified
BIO,
.Fa bio ,
rather than standard output.
All common format specifiers are supported.
The argument list
.Fa args
is a stdarg argument list.
.Pp
.Fn BIO_snprintf
is for platforms that do not have the common
.Xr snprintf 3
function.
It is like
.Xr sprintf 3
except that the size parameter,
.Fa n ,
specifies the size of the output buffer.
.Pp
.Fn BIO_vsnprintf
is to
.Fn BIO_snprintf
as
.Fn BIO_vprintf
is to
.Fn BIO_printf .
.Sh RETURN VALUES
All functions return the number of bytes written, or -1 on error.
For
.Fn BIO_snprintf
and
.Fn BIO_vsnprintf
this includes when the output buffer is too small.
.Sh NOTES
Except when
.Fa n
is 0, both
.Fn BIO_snprintf
and
.Fn BIO_vsnprintf
always terminate their output with
.Qo Li '\e0' Qc .
This includes cases where -1 is returned, such as when there is
insufficient space to output the whole string.
.Sh COPYRIGHT
Copyright 2017-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
