.Dd 2025-09-30
.Dt BIO_SET_CALLBACK 3ossl
.Os
.Sh NAME
.Nm BIO_set_callback_ex ,
.Nm BIO_get_callback_ex ,
.Nm BIO_set_callback ,
.Nm BIO_get_callback ,
.Nm BIO_set_callback_arg ,
.Nm BIO_get_callback_arg ,
.Nm BIO_debug_callback ,
.Nm BIO_debug_callback_ex ,
.Nm BIO_callback_fn_ex ,
.Nm BIO_callback_fn
.Nd BIO callback functions
.Sh SYNOPSIS
.In openssl/bio.h
.Ft typedef long
.Fo 
.Fa *BIO_callback_fn_ex
.Fc
(BIO *b, int oper, const char *argp,
.Bd -literal
                                    size_t len, int argi,
                                    long argl, int ret, size_t *processed);
.Ed
.Ft void
.Fo BIO_set_callback_ex
.Fa "BIO *b"
.Fa "BIO_callback_fn_ex callback"
.Fc
.Ft BIO_callback_fn_ex
.Fo BIO_get_callback_ex
.Fa "const BIO *b"
.Fc
.Ft void
.Fo BIO_set_callback_arg
.Fa "BIO *b"
.Fa "char *arg"
.Fc
.Ft char *
.Fo BIO_get_callback_arg
.Fa "const BIO *b"
.Fc
.Ft long
.Fo BIO_debug_callback_ex
.Fa "BIO *bio"
.Fa "int oper"
.Fa "const char *argp"
.Fa "size_t len"
.Fa "int argi"
.Fa "long argl"
.Fa "int ret"
.Fa "size_t *processed"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft typedef long
.Fo 
.Fa *BIO_callback_fn
.Fc
(BIO *b, int oper, const char *argp, int argi,
.Bd -literal
                                 long argl, long ret);
 void BIO_set_callback(BIO *b, BIO_callback_fn cb);
 BIO_callback_fn BIO_get_callback(const BIO *b);
 long BIO_debug_callback(BIO *bio, int cmd, const char *argp, int argi,
                         long argl, long ret);

 typedef struct bio_mmsg_cb_args_st {
     BIO_MSG    *msg;
     size_t      stride, num_msg;
     uint64_t    flags;
     size_t     *msgs_processed;
 } BIO_MMSG_CB_ARGS;
.Ed
.Sh DESCRIPTION
.Fn BIO_set_callback_ex
and
.Fn BIO_get_callback_ex
set and retrieve the BIO callback.
The callback is called during most high-level BIO operations.
It can be used for debugging purposes to trace operations on a BIO or to
modify its operation.
.Pp
.Xr BIO_set_callback 3
and
.Xr BIO_get_callback 3
set and retrieve the old format BIO callback.
New code should not use these functions, but they are retained for
backwards compatibility.
Any callback set via
.Fn BIO_set_callback_ex
will get called in preference to any set by
.Xr BIO_set_callback 3 .
.Pp
.Fn BIO_set_callback_arg
and
.Fn BIO_get_callback_arg
are macros which can be used to set and retrieve an argument for use in
the callback.
.Pp
.Fn BIO_debug_callback_ex
is a standard debugging callback which prints out information relating
to each BIO operation.
If the callback argument is set it is interpreted as a BIO to send the
information to, otherwise stderr is used.
The
.Xr BIO_debug_callback 3
function is the deprecated version of the same callback for use with the
old callback format
.Xr BIO_set_callback 3
function.
.Pp
BIO_callback_fn_ex is the type of the callback function and
BIO_callback_fn is the type of the old format callback function.
The meaning of each argument is described below:
.Bl -tag -width Ds
.It Fa b
The BIO the callback is attached to is passed in
.Fa b .
.It Fa oper
.Fa oper
is set to the operation being performed.
For some operations the callback is called twice, once before and once
after the actual operation, the latter case has
.Fa oper
or'ed with BIO_CB_RETURN.
.It Fa len
The length of the data requested to be read or written.
This is only useful if
.Fa oper
is BIO_CB_READ, BIO_CB_WRITE or BIO_CB_GETS.
.It Fa argp Fa argi Fa argl
The meaning of the arguments
.Fa argp ,
.Fa argi
and
.Fa argl
depends on the value of
.Fa oper ,
that is the operation being performed.
.It Fa processed
.Fa processed
is a pointer to a location which will be updated with the amount of data
that was actually read or written.
Only used for BIO_CB_READ, BIO_CB_WRITE, BIO_CB_GETS and BIO_CB_PUTS.
.It Fa ret
.Fa ret
is the return value that would be returned to the application if no
callback were present.
The actual value returned is the return value of the callback itself.
In the case of callbacks called before the actual BIO operation 1 is
placed in
.Fa ret ,
if the return value is not positive it will be immediately returned to
the application and the BIO operation will not be performed.
.El
.Pp
The callback should normally simply return
.Fa ret
when it has finished processing, unless it specifically wishes to modify
the value returned to the application.
.Sh CALLBACK OPERATIONS
In the notes below,
.Fa callback
defers to the actual callback function that is called.
.Bl -tag -width Ds
.It Sy BIO_free(b)
.Bd -literal
 callback_ex(b, BIO_CB_FREE, NULL, 0, 0, 0L, 1L, NULL)
.Ed
or
.Bd -literal
 callback(b, BIO_CB_FREE, NULL, 0L, 0L, 1L)
.Ed
.Pp
is called before the free operation.
.It Sy BIO_read_ex(b, data, dlen, readbytes)
.Bd -literal
 callback_ex(b, BIO_CB_READ, data, dlen, 0, 0L, 1L, NULL)
.Ed
or
.Bd -literal
 callback(b, BIO_CB_READ, data, dlen, 0L, 1L)
.Ed
.Pp
is called before the read and
.Bd -literal
 callback_ex(b, BIO_CB_READ | BIO_CB_RETURN, data, dlen, 0, 0L, retvalue,
             &readbytes)
.Ed
.Pp
or
.Bd -literal
 callback(b, BIO_CB_READ|BIO_CB_RETURN, data, dlen, 0L, retvalue)
.Ed
.Pp
after.
.It Sy BIO_write(b, data, dlen, written)
.Bd -literal
 callback_ex(b, BIO_CB_WRITE, data, dlen, 0, 0L, 1L, NULL)
.Ed
or
.Bd -literal
 callback(b, BIO_CB_WRITE, datat, dlen, 0L, 1L)
.Ed
.Pp
is called before the write and
.Bd -literal
 callback_ex(b, BIO_CB_WRITE | BIO_CB_RETURN, data, dlen, 0, 0L, retvalue,
             &written)
.Ed
.Pp
or
.Bd -literal
 callback(b, BIO_CB_WRITE|BIO_CB_RETURN, data, dlen, 0L, retvalue)
.Ed
.Pp
after.
.It Sy BIO_gets(b, buf, size)
.Bd -literal
 callback_ex(b, BIO_CB_GETS, buf, size, 0, 0L, 1, NULL, NULL)
.Ed
or
.Bd -literal
 callback(b, BIO_CB_GETS, buf, size, 0L, 1L)
.Ed
.Pp
is called before the operation and
.Bd -literal
 callback_ex(b, BIO_CB_GETS | BIO_CB_RETURN, buf, size, 0, 0L, retvalue,
             &readbytes)
.Ed
.Pp
or
.Bd -literal
 callback(b, BIO_CB_GETS|BIO_CB_RETURN, buf, size, 0L, retvalue)
.Ed
.Pp
after.
.It Sy BIO_puts(b, buf)
.Bd -literal
 callback_ex(b, BIO_CB_PUTS, buf, 0, 0, 0L, 1L, NULL);
.Ed
or
.Bd -literal
 callback(b, BIO_CB_PUTS, buf, 0, 0L, 1L)
.Ed
.Pp
is called before the operation and
.Bd -literal
 callback_ex(b, BIO_CB_PUTS | BIO_CB_RETURN, buf, 0, 0, 0L, retvalue, &written)
.Ed
.Pp
or
.Bd -literal
 callback(b, BIO_CB_PUTS|BIO_CB_RETURN, buf, 0, 0L, retvalue)
.Ed
.Pp
after.
.It Sy BIO_ctrl(BIO *b, int cmd, long larg, void *parg)
.Bd -literal
 callback_ex(b, BIO_CB_CTRL, parg, 0, cmd, larg, 1L, NULL)
.Ed
or
.Bd -literal
 callback(b, BIO_CB_CTRL, parg, cmd, larg, 1L)
.Ed
.Pp
is called before the call and
.Bd -literal
 callback_ex(b, BIO_CB_CTRL | BIO_CB_RETURN, parg, 0, cmd, larg, ret, NULL)
.Ed
.Pp
or
.Bd -literal
 callback(b, BIO_CB_CTRL|BIO_CB_RETURN, parg, cmd, larg, ret)
.Ed
.Pp
after.
.Pp
Note:
.Sy cmd
==
.Sy BIO_CTRL_SET_CALLBACK
is special, because
.Sy parg
is not the argument of type
.Sy BIO_info_cb
itself.
In this case
.Sy parg
is a pointer to the actual call parameter, see
.Sy BIO_callback_ctrl .
.It Sy BIO_sendmmsg(BIO *b, BIO_MSG *msg, size_t stride, size_t num_msg, uint64_t flags, size_t *msgs_processed)
.Bd -literal
  callback_ex(b, BIO_CB_SENDMMSG, args, 0, 0, 0, 1, NULL)
.Ed
or
.Bd -literal
  callback(b, BIO_CB_SENDMMSG, args, 0, 0, 1)
.Ed
.Pp
is called before the call and
.Bd -literal
  callback_ex(b, BIO_CB_SENDMMSG | BIO_CB_RETURN, args, ret, 0, 0, ret, NULL)
.Ed
.Pp
or
.Bd -literal
  callback(b, BIO_CB_SENDMMSG | BIO_CB_RETURN, args, ret, 0, 0, ret)
.Ed
.Pp
after.
.Pp
.Sy args
is a pointer to a
.Sy BIO_MMSG_CB_ARGS
structure containing the arguments passed to
.Xr BIO_sendmmsg 3 .
.Fa ret
is the return value of the
.Xr BIO_sendmmsg 3
call.
The return value of
.Xr BIO_sendmmsg 3
is altered to the value returned by the
.Sy BIO_CB_SENDMMSG | BIO_CB_RETURN
call.
.It Sy BIO_recvmmsg(BIO *b, BIO_MSG *msg, size_t stride, size_t num_msg, uint64_t flags, size_t *msgs_processed)
See the documentation for
.Xr BIO_sendmmsg 3 .
.Xr BIO_recvmmsg 3
works identically except that
.Sy BIO_CB_RECVMMSG
is used instead of
.Sy BIO_CB_SENDMMSG .
.El
.Sh RETURN VALUES
.Fn BIO_get_callback_ex
and
.Xr BIO_get_callback 3
return the callback function previously set by a call to
.Fn BIO_set_callback_ex
and
.Xr BIO_set_callback 3
respectively.
.Pp
.Fn BIO_get_callback_arg
returns a
.Vt char
pointer to the value previously set via a call to
.Fn BIO_set_callback_arg .
.Pp
.Xr BIO_debug_callback 3
returns 1 or
.Fa ret
if it's called after specific BIO operations.
.Sh EXAMPLES
The
.Fn BIO_debug_callback_ex
function is an example, its source is in crypto/bio/bio_cb.c
.Sh HISTORY
The
.Fn BIO_debug_callback_ex
function was added in OpenSSL 3.0.
.Pp
.Xr BIO_set_callback 3 ,
.Xr BIO_get_callback 3 ,
and
.Xr BIO_debug_callback 3
were deprecated in OpenSSL 3.0. Use the non-deprecated _ex functions
instead.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
