.Dd 2025-09-30
.Dt BIO_SENDMMSG 3ossl
.Os
.Sh NAME
.Nm BIO_sendmmsg ,
.Nm BIO_recvmmsg ,
.Nm BIO_dgram_set_local_addr_enable ,
.Nm BIO_dgram_get_local_addr_enable ,
.Nm BIO_dgram_get_local_addr_cap ,
.Nm BIO_err_is_non_fatal
.Nd send and receive multiple datagrams in a single call
.Sh SYNOPSIS
.In openssl/bio.h
.Ft typedef struct bio_msg_st {
     void *data;
     size_t data_len;
     BIO_ADDR *peer, *local;
     uint64_t flags;
 } BIO_MSG;

 int
.Fo BIO_sendmmsg
.Fa "BIO *b"
.Fa "BIO_MSG *msg"
.Fa "size_t stride"
.Fa "size_t num_msg"
.Fa "uint64_t flags"
.Fa "size_t *msgs_processed"
.Fc
.Ft int
.Fo BIO_recvmmsg
.Fa "BIO *b"
.Fa "BIO_MSG *msg"
.Fa "size_t stride"
.Fa "size_t num_msg"
.Fa "uint64_t flags"
.Fa "size_t *msgs_processed"
.Fc
.Ft int
.Fo BIO_dgram_set_local_addr_enable
.Fa "BIO *b"
.Fa "int enable"
.Fc
.Ft int
.Fo BIO_dgram_get_local_addr_enable
.Fa "BIO *b"
.Fa "int *enable"
.Fc
.Ft int
.Fo BIO_dgram_get_local_addr_cap
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_err_is_non_fatal
.Fa "unsigned int errcode"
.Fc
.Sh DESCRIPTION
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
functions can be used to send and receive multiple messages in a single
call to a BIO. They are analogous to sendmmsg(2) and recvmmsg(2) on
operating systems which provide those functions.
.Pp
The
.Vt BIO_MSG
structure provides a subset of the functionality of the
.Sy struct msghdr
structure defined by POSIX. These functions accept an array of
.Vt BIO_MSG
structures.
On any particular invocation, these functions may process all of the
passed structures, some of them, or none of them.
This is indicated by the value stored in
.Em *msgs_processed ,
which expresses the number of messages processed.
.Pp
The caller should set the
.Em data
member of a
.Vt BIO_MSG
to a buffer containing the data to send, or to be filled with a received
message.
.Em data_len
should be set to the size of the buffer in bytes.
If the given
.Vt BIO_MSG
is processed (in other words, if the integer returned by the function is
greater than or equal to that
.Vt BIO_MSG Ns 's
array index),
.Em data_len
will be modified to specify the actual amount of data sent or received.
.Pp
The
.Fa flags
field of a
.Vt BIO_MSG
provides input per-message flags to the invocation.
If the invocation processes that
.Vt BIO_MSG ,
the
.Fa flags
field is written with output per-message flags, or zero if no such flags
are applicable.
.Pp
Currently, no input or output per-message flags are defined and this
field should be set to zero before calling
.Fn BIO_sendmmsg
or
.Fn BIO_recvmmsg .
.Pp
The
.Fa flags
argument to
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
provides global flags which affect the entire invocation.
No global flags are currently defined and this argument should be set to
zero.
.Pp
When these functions are used to send and receive datagrams, the
.Em peer
field of a
.Vt BIO_MSG
allows the destination address of sent datagrams to be specified on a
per-datagram basis, and the source address of received datagrams to be
determined.
The
.Em peer
field should be set to point to a
.Sy BIO_ADDR ,
which will be read by
.Fn BIO_sendmmsg
and used as the destination address for sent datagrams, and written by
.Fn BIO_recvmmsg
with the source address of received datagrams.
.Pp
Similarly, the
.Em local
field of a
.Vt BIO_MSG
allows the source address of sent datagrams to be specified on a
per-datagram basis, and the destination address of received datagrams to
be determined.
Unlike
.Em peer ,
support for
.Em local
must be explicitly enabled on a
.Vt BIO
before it can be used; see
.Fn BIO_dgram_set_local_addr_enable .
If
.Em local
is non-NULL in a
.Vt BIO_MSG
and support for
.Em local
has not been enabled, processing of that
.Vt BIO_MSG
fails.
.Pp
.Em peer
and
.Em local
should be set to NULL if they are not required.
Support for
.Em local
may not be available on all platforms; on these platforms, these
functions always fail if
.Em local
is non-NULL.
.Pp
If
.Em local
is specified and local address support is enabled, but the operating
system does not report a local address for a specific received message,
the
.Sy BIO_ADDR
it points to will be cleared (address family set to
.Qo Li AF_UNSPEC Qc Ns ).
This is known to happen on Windows when a packet is received which was
sent by the local system, regardless of whether the packet's destination
address was the loopback address or the IP address of a local
non-loopback interface.
This is also known to happen on macOS in some circumstances, such as for
packets sent before local address support was enabled for a receiving
socket.
These are OS-specific limitations.
As such, users of this API using local address support should expect to
sometimes receive a cleared local
.Sy BIO_ADDR
instead of the correct value.
.Pp
The
.Fa stride
argument must be set to
.Qo Li sizeof(BIO_MSG) Qc .
This argument facilitates backwards compatibility if fields are added to
.Vt BIO_MSG .
Callers must zero-initialize
.Vt BIO_MSG .
.Pp
.Fa num_msg
should be sent to the maximum number of messages to send or receive,
which is also the length of the array pointed to by
.Fa msg .
.Pp
.Fa msgs_processed
must be non-NULL and points to an integer written with the number of
messages successfully processed; see the RETURN VALUES section for
further discussion.
.Pp
Unlike most BIO functions, these functions explicitly support
multi-threaded use.
Multiple concurrent writers and multiple concurrent readers of the same
BIO are permitted in any combination.
As such, these functions do not clear, set, or otherwise modify BIO
retry flags.
The return value must be used to determine whether an operation should
be retried; see below.
.Pp
The support for concurrent use extends to
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
only, and no other function may be called on a given BIO while any call
to
.Fn BIO_sendmmsg
or
.Fn BIO_recvmmsg
is in progress, or vice versa.
.Pp
.Fn BIO_dgram_set_local_addr_enable
and
.Fn BIO_dgram_get_local_addr_enable
control whether local address support is enabled.
To enable local address support, call
.Fn BIO_dgram_set_local_addr_enable
with an argument of 1. The call will fail if local address support is
not available for the platform.
.Fn BIO_dgram_get_local_addr_enable
retrieves the value set by
.Fn BIO_dgram_set_local_addr_enable .
.Pp
.Fn BIO_dgram_get_local_addr_cap
determines if the
.Vt BIO
is capable of supporting local addresses.
.Pp
.Fn BIO_err_is_non_fatal
determines if a packed error code represents an error which is transient
in nature.
.Sh NOTES
Some implementations of the
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
BIO methods might always process at most one message at a time, for
example when OS-level functionality to transmit or receive multiple
messages at a time is not available.
.Sh RETURN VALUES
On success, the functions
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
return 1 and write the number of messages successfully processed (which
need not be nonzero) to
.Fa msgs_processed .
Where a positive value n is written to
.Fa msgs_processed ,
all entries in the
.Vt BIO_MSG
array from 0 through n-1 inclusive have their
.Em data_len
and
.Fa flags
fields updated with the results of the operation on that message.
If the call was to
.Fn BIO_recvmmsg
and the
.Em peer
or
.Em local
fields of that message are non-NULL, the
.Sy BIO_ADDR
structures they point to are written with the relevant address.
.Pp
On failure, the functions
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
return 0 and write zero to
.Fa msgs_processed .
Thus
.Fa msgs_processed
is always written regardless of the outcome of the function call.
.Pp
If
.Fn BIO_sendmmsg
and
.Fn BIO_recvmmsg
fail, they always raise an
.Sy ERR_LIB_BIO
error using
.Xr ERR_raise 3 .
Any error may be raised, but the following in particular may be noted:
.Bl -tag -width Ds
.It Sy BIO_R_LOCAL_ADDR_NOT_AVAILABLE
The
.Em local
field was set to a non-NULL value, but local address support is not
available or not enabled on the BIO.
.It Sy BIO_R_PEER_ADDR_NOT_AVAILABLE
The
.Em peer
field was set to a non-NULL value, but peer address support is not
available on the BIO.
.It Sy BIO_R_UNSUPPORTED_METHOD
The
.Fn BIO_sendmmsg
or
.Fn BIO_recvmmsg
method is not supported on the BIO.
.It Sy BIO_R_NON_FATAL
The call failed due to a transient, non-fatal error (for example,
because the BIO is in nonblocking mode and the call would otherwise have
blocked).
.Pp
Implementations of this interface which do not make system calls and
thereby pass through system error codes using
.Sy ERR_LIB_SYS
(for example, memory-based implementations) should issue this reason
code to indicate a transient failure.
However, users of this interface should not test for this reason code
directly, as there are multiple possible packed error codes representing
a transient failure; use
.Fn BIO_err_is_non_fatal
instead (discussed below).
.It Socket errors
OS-level socket errors are reported using an error with library code
.Sy ERR_LIB_SYS ;
for a packed error code
.Fa errcode
where
.Qo Li ERR_SYSTEM_ERROR(errcode) == 1 Qc ,
the OS-level socket error code can be retrieved using
.Qo Li ERR_GET_REASON(errcode) Qc .
The packed error code can be retrieved by calling
.Xr ERR_peek_last_error 3
after the call to
.Fn BIO_sendmmsg
or
.Fn BIO_recvmmsg
returns 0.
.It Non-fatal errors
Whether an error is transient can be determined by passing the packed
error code to
.Fn BIO_err_is_non_fatal .
Callers should do this instead of testing the reason code directly, as
there are many possible error codes which can indicate a transient
error, many of which are system specific.
.El
.Pp
Third parties implementing custom BIOs supporting the
.Fn BIO_sendmmsg
or
.Fn BIO_recvmmsg
methods should note that it is a required part of the API contract that
an error is always raised when either of these functions return 0.
.Pp
.Fn BIO_dgram_set_local_addr_enable
returns 1 if local address support was successfully enabled or disabled
and 0 otherwise.
.Pp
.Fn BIO_dgram_get_local_addr_enable
returns 1 if the local address support enable flag was successfully
retrieved.
.Pp
.Fn BIO_dgram_get_local_addr_cap
returns 1 if the
.Vt BIO
can support local addresses.
.Pp
.Fn BIO_err_is_non_fatal
returns 1 if the passed packed error code represents an error which is
transient in nature.
.Sh HISTORY
These functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
