.Dd 2025-09-30
.Dt BIO_SHOULD_RETRY 3ossl
.Os
.Sh NAME
.Nm BIO_should_read ,
.Nm BIO_should_write ,
.Nm BIO_should_io_special ,
.Nm BIO_retry_type ,
.Nm BIO_should_retry ,
.Nm BIO_get_retry_BIO ,
.Nm BIO_get_retry_reason ,
.Nm BIO_set_retry_reason
.Nd BIO retry functions
.Sh SYNOPSIS
.In openssl/bio.h
.Ft int
.Fo BIO_should_read
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_should_write
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_should_io_special
.Fa "iBIO *b"
.Fc
.Ft int
.Fo BIO_retry_type
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_should_retry
.Fa "BIO *b"
.Fc
.Ft BIO *
.Fo BIO_get_retry_BIO
.Fa "BIO *bio"
.Fa "int *reason"
.Fc
.Ft int
.Fo BIO_get_retry_reason
.Fa "BIO *bio"
.Fc
.Ft void
.Fo BIO_set_retry_reason
.Fa "BIO *bio"
.Fa "int reason"
.Fc
.Sh DESCRIPTION
These functions determine why a BIO is not able to read or write data.
They will typically be called after a failed
.Xr BIO_read_ex 3
or
.Xr BIO_write_ex 3
call.
.Pp
.Fn BIO_should_retry
is true if the call that produced this condition should then be retried
at a later time.
.Pp
If
.Fn BIO_should_retry
is false then the cause is an error condition.
.Pp
.Fn BIO_should_read
is true if the cause of the condition is that the BIO has insufficient
data to return.
Check for readability and/or retry the last operation.
.Pp
.Fn BIO_should_write
is true if the cause of the condition is that the BIO has pending data
to write.
Check for writability and/or retry the last operation.
.Pp
.Fn BIO_should_io_special
is true if some "special" condition, that is a reason other than reading
or writing is the cause of the condition.
.Pp
.Fn BIO_retry_type
returns a mask of the cause of a retry condition consisting of the
values
.Sy BIO_FLAGS_READ ,
.Sy BIO_FLAGS_WRITE ,
.Sy BIO_FLAGS_IO_SPECIAL
though current BIO types will only set one of these.
.Pp
.Fn BIO_get_retry_BIO
determines the precise reason for the special condition, it returns the
BIO that caused this condition and if
.Fa reason
is not NULL it contains the reason code.
The meaning of the reason code and the action that should be taken
depends on the type of BIO that resulted in this condition.
.Pp
.Fn BIO_get_retry_reason
returns the reason for a special condition if passed the relevant BIO,
for example as returned by
.Fn BIO_get_retry_BIO .
.Pp
.Fn BIO_set_retry_reason
sets the retry reason for a special condition for a given BIO. This
would usually only be called by BIO implementations.
.Sh NOTES
.Fn BIO_should_read ,
.Fn BIO_should_write ,
.Fn BIO_should_io_special ,
.Fn BIO_retry_type ,
and
.Fn BIO_should_retry ,
are implemented as macros.
.Pp
If
.Fn BIO_should_retry
returns false then the precise "error condition" depends on the BIO type
that caused it and the return code of the BIO operation.
For example if a call to
.Xr BIO_read_ex 3
on a socket BIO returns 0 and
.Fn BIO_should_retry
is false then the cause will be that the connection closed.
A similar condition on a file BIO will mean that it has reached EOF.
Some BIO types may place additional information on the error queue.
For more details see the individual BIO type manual pages.
.Pp
If the underlying I/O structure is in a blocking mode almost all current
BIO types will not request a retry, because the underlying I/O calls
will not.
If the application knows that the BIO type will never signal a retry
then it need not call
.Fn BIO_should_retry
after a failed BIO I/O call.
This is typically done with file BIOs.
.Pp
SSL BIOs are the only current exception to this rule: they can request a
retry even if the underlying I/O structure is blocking, if a handshake
occurs during a call to
.Xr BIO_read 3 .
An application can retry the failed call immediately or avoid this
situation by setting SSL_MODE_AUTO_RETRY on the underlying SSL
structure.
.Pp
While an application may retry a failed non blocking call immediately
this is likely to be very inefficient because the call will fail
repeatedly until data can be processed or is available.
An application will normally wait until the necessary condition is
satisfied.
How this is done depends on the underlying I/O structure.
.Pp
For example if the cause is ultimately a socket and
.Fn BIO_should_read
is true then a call to
.Xr select 3
may be made to wait until data is available and then retry the BIO
operation.
By combining the retry conditions of several non blocking BIOs in a
single
.Xr select 3
call it is possible to service several BIOs in a single thread, though
the performance may be poor if SSL BIOs are present because long delays
can occur during the initial handshake process.
.Pp
It is possible for a BIO to block indefinitely if the underlying I/O
structure cannot process or return any data.
This depends on the behaviour of the platforms I/O functions.
This is often not desirable: one solution is to use non blocking I/O and
use a timeout on the
.Xr select 3
(or equivalent) call.
.Sh BUGS
The OpenSSL ASN1 functions cannot gracefully deal with non blocking I/O:
that is they cannot retry after a partial read or write.
This is usually worked around by only passing the relevant data to ASN1
functions when the entire structure can be read or written.
.Sh RETURN VALUES
.Fn BIO_should_read ,
.Fn BIO_should_write ,
.Fn BIO_should_io_special ,
and
.Fn BIO_should_retry
return either 1 or 0 based on the actual conditions of the
.Vt BIO .
.Pp
.Fn BIO_retry_type
returns a flag combination presenting the cause of a retry condition or
false if there is no retry condition.
.Pp
.Fn BIO_get_retry_BIO
returns a valid
.Vt BIO
structure.
.Pp
.Fn BIO_get_retry_reason
returns the reason for a special condition.
.Sh SEE ALSO
.Xr bio 7
.Sh HISTORY
The
.Fn BIO_get_retry_reason
and
.Fn BIO_set_retry_reason
functions were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2000-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
