.Dd 2025-09-30
.Dt BIO_GET_RPOLL_DESCRIPTOR 3ossl
.Os
.Sh NAME
.Nm BIO_get_rpoll_descriptor ,
.Nm BIO_get_wpoll_descriptor
.Nd obtain a structure which can be used to determine when a BIO object can next be read or written
.Sh SYNOPSIS
.In openssl/bio.h
.Ft typedef struct bio_poll_descriptor_st {
     uint32_t type;
     union {
         int        fd;
         void       *custom;
         uintptr_t  custom_ui;
     } value;
 } BIO_POLL_DESCRIPTOR;

 int
.Fo BIO_get_rpoll_descriptor
.Fa "BIO *b"
.Fa "BIO_POLL_DESCRIPTOR *desc"
.Fc
.Ft int
.Fo BIO_get_wpoll_descriptor
.Fa "BIO *b"
.Fa "BIO_POLL_DESCRIPTOR *desc"
.Fc
.Sh DESCRIPTION
.Fn BIO_get_rpoll_descriptor
and
.Fn BIO_get_wpoll_descriptor ,
on success, fill
.Em *desc
with a poll descriptor.
A poll descriptor is a tagged union structure which represents some kind
of OS or non-OS resource which can be used to synchronise on I/O
availability events.
.Pp
.Fn BIO_get_rpoll_descriptor
outputs a descriptor which can be used to determine when the BIO can
(potentially) next be read, and
.Fn BIO_get_wpoll_descriptor
outputs a descriptor which can be used to determine when the BIO can
(potentially) next be written.
.Pp
It is permissible for
.Fn BIO_get_rpoll_descriptor
and
.Fn BIO_get_wpoll_descriptor
to output the same descriptor.
.Pp
Poll descriptors can represent different kinds of information.
A typical kind of resource which might be represented by a poll
descriptor is an OS file descriptor which can be used with APIs such as
.Xr select 3 .
.Pp
The kinds of poll descriptor defined by OpenSSL are:
.Bl -tag -width Ds
.It BIO_POLL_DESCRIPTOR_TYPE_NONE
Represents the absence of a valid poll descriptor.
It may be used by
.Fn BIO_get_rpoll_descriptor
or
.Fn BIO_get_wpoll_descriptor
to indicate that the BIO is not pollable for readability or writeability
respectively.
.Pp
For this type, no field within the
.Em value
field of the
.Vt BIO_POLL_DESCRIPTOR
is valid.
.It BIO_POLL_DESCRIPTOR_TYPE_SOCK_FD
The poll descriptor represents an OS socket resource.
The field
.Em value.fd
in the
.Vt BIO_POLL_DESCRIPTOR
is valid if it is not set to -1.
.Pp
The resource is whatever kind of handle is used by a given OS to
represent sockets, which may vary by OS. For example, on Windows, the
value is a
.Sy SOCKET
for use with the Winsock API. On POSIX-like platforms, it is a file
descriptor.
.Pp
Where a poll descriptor of this type is output by
.Fn BIO_get_rpoll_descriptor ,
it should be polled for readability to determine when the BIO might next
be able to successfully complete a
.Xr BIO_read 3
operation; likewise, where a poll descriptor of this type is output by
.Fn BIO_get_wpoll_descriptor ,
it should be polled for writeability to determine when the BIO might
next be able to successfully complete a
.Xr BIO_write 3
operation.
.It BIO_POLL_DESCRIPTOR_CUSTOM_START
Type values beginning with this value (inclusive) are reserved for
application allocation for custom poll descriptor types.
Any of the definitions in the union field
.Em value
can be used by the application arbitrarily as opaque values.
.El
.Pp
Because poll descriptors are a tagged union structure, they can
represent different kinds of information.
New types of poll descriptor may be defined, including by applications,
according to their needs.
.Sh RETURN VALUES
The functions
.Fn BIO_get_rpoll_descriptor
and
.Fn BIO_get_wpoll_descriptor
return 1 on success and 0 on failure.
.Pp
These functions are permitted to succeed and initialise
.Em *desc
with a poll descriptor of type
.Sy BIO_POLL_DESCRIPTOR_TYPE_NONE
to indicate that the BIO is not pollable for readability or writeability
respectively.
.Sh SEE ALSO
.Xr SSL_handle_events 3 ,
.Xr SSL_get_event_timeout 3 ,
.Xr SSL_get_rpoll_descriptor 3 ,
.Xr SSL_get_wpoll_descriptor 3 ,
.Xr bio 7
.Sh HISTORY
The
.Fn BIO_get_rpoll_descriptor
and
.Fn BIO_get_wpoll_descriptor
functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2022-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
