.Dd 2025-09-30
.Dt BIO_CTRL 3ossl
.Os
.Sh NAME
.Nm BIO_ctrl ,
.Nm BIO_callback_ctrl ,
.Nm BIO_ptr_ctrl ,
.Nm BIO_int_ctrl ,
.Nm BIO_reset ,
.Nm BIO_seek ,
.Nm BIO_tell ,
.Nm BIO_flush ,
.Nm BIO_eof ,
.Nm BIO_set_close ,
.Nm BIO_get_close ,
.Nm BIO_pending ,
.Nm BIO_wpending ,
.Nm BIO_ctrl_pending ,
.Nm BIO_ctrl_wpending ,
.Nm BIO_get_info_callback ,
.Nm BIO_set_info_callback ,
.Nm BIO_info_cb ,
.Nm BIO_get_ktls_send ,
.Nm BIO_get_ktls_recv ,
.Nm BIO_set_conn_mode ,
.Nm BIO_get_conn_mode ,
.Nm BIO_set_tfo
.Nd BIO control operations
.Sh SYNOPSIS
.In openssl/bio.h
.Ft typedef int
.Fo BIO_info_cb
.Fa "BIO *b"
.Fa "int state"
.Fa "int res"
.Fc
.Ft long
.Fo BIO_ctrl
.Fa "BIO *bp"
.Fa "int cmd"
.Fa "long larg"
.Fa "void *parg"
.Fc
.Ft long
.Fo BIO_callback_ctrl
.Fa "BIO *b"
.Fa "int cmd"
.Fa "BIO_info_cb *cb"
.Fc
.Ft void *
.Fo BIO_ptr_ctrl
.Fa "BIO *bp"
.Fa "int cmd"
.Fa "long larg"
.Fc
.Ft long
.Fo BIO_int_ctrl
.Fa "BIO *bp"
.Fa "int cmd"
.Fa "long larg"
.Fa "int iarg"
.Fc
.Ft int
.Fo BIO_reset
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_seek
.Fa "BIO *b"
.Fa "int ofs"
.Fc
.Ft int
.Fo BIO_tell
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_flush
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_eof
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_set_close
.Fa "BIO *b"
.Fa "long flag"
.Fc
.Ft int
.Fo BIO_get_close
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_pending
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_wpending
.Fa "BIO *b"
.Fc
.Ft size_t
.Fo BIO_ctrl_pending
.Fa "BIO *b"
.Fc
.Ft size_t
.Fo BIO_ctrl_wpending
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_get_info_callback
.Fa "BIO *b"
.Fa "BIO_info_cb **cbp"
.Fc
.Ft int
.Fo BIO_set_info_callback
.Fa "BIO *b"
.Fa "BIO_info_cb *cb"
.Fc
.Ft int
.Fo BIO_get_ktls_send
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_get_ktls_recv
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_set_conn_mode
.Fa "BIO *b"
.Fa "int mode"
.Fc
.Ft int
.Fo BIO_get_conn_mode
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_set_tfo
.Fa "BIO *b"
.Fa "int onoff"
.Fc
.Sh DESCRIPTION
.Fn BIO_ctrl ,
.Fn BIO_callback_ctrl ,
.Fn BIO_ptr_ctrl
and
.Fn BIO_int_ctrl
are BIO "control" operations taking arguments of various types.
These functions are not normally called directly, various macros are
used instead.
The standard macros are described below, macros specific to a particular
type of BIO are described in the specific BIOs manual page as well as
any special features of the standard calls.
.Pp
.Fn BIO_reset
typically resets a BIO to some initial state, in the case of file
related BIOs for example it rewinds the file pointer to the start of the
file.
.Pp
.Fn BIO_seek
resets a file related BIO's (that is file descriptor and FILE BIOs) file
position pointer to
.Fa ofs
bytes from start of file.
.Pp
.Fn BIO_tell
returns the current file position of a file related BIO.
.Pp
.Fn BIO_flush
normally writes out any internally buffered data, in some cases it is
used to signal EOF and that no more data will be written.
.Pp
.Fn BIO_eof
returns 1 if the BIO has read EOF, the precise meaning of "EOF" varies
according to the BIO type.
.Pp
.Fn BIO_set_close
sets the BIO
.Fa b
close flag to
.Fa flag .
.Fa flag
can take the value BIO_CLOSE or BIO_NOCLOSE. Typically BIO_CLOSE is used
in a source/sink BIO to indicate that the underlying I/O stream should
be closed when the BIO is freed.
.Pp
.Fn BIO_get_close
returns the BIOs close flag.
.Pp
.Fn BIO_pending ,
.Fn BIO_ctrl_pending ,
.Fn BIO_wpending
and
.Fn BIO_ctrl_wpending
return the number of pending characters in the BIOs read and write
buffers.
Not all BIOs support these calls.
.Fn BIO_ctrl_pending
and
.Fn BIO_ctrl_wpending
return a size_t type and are functions,
.Fn BIO_pending
and
.Fn BIO_wpending
are macros which call
.Fn BIO_ctrl .
.Pp
.Fn BIO_get_ktls_send
returns 1 if the BIO is using the Kernel TLS data-path for sending.
Otherwise, it returns zero.
.Fn BIO_get_ktls_recv
returns 1 if the BIO is using the Kernel TLS data-path for receiving.
Otherwise, it returns zero.
.Pp
.Fn BIO_get_conn_mode
returns the BIO connection mode.
.Fn BIO_set_conn_mode
sets the BIO connection mode.
.Pp
.Fn BIO_set_tfo
disables TCP Fast Open when
.Fa onoff
is 0, and enables TCP Fast Open when
.Fa onoff
is nonzero.
Setting the value to 1 is equivalent to setting
.Sy BIO_SOCK_TFO
in
.Fn BIO_set_conn_mode .
.Sh RETURN VALUES
.Fn BIO_reset
normally returns 1 for success and <=0 for failure.
File BIOs are an exception, they return 0 for success and -1 for
failure.
.Pp
.Fn BIO_seek
and
.Fn BIO_tell
both return the current file position on success and -1 for failure,
except file BIOs which for
.Fn BIO_seek
always return 0 for success and -1 for failure.
.Pp
.Fn BIO_flush
returns 1 for success and <=0 for failure.
.Pp
.Fn BIO_eof
returns 1 if EOF has been reached, 0 if not, or negative values for
failure.
.Pp
.Fn BIO_set_close
returns 1 on success or <=0 for failure.
.Pp
.Fn BIO_get_close
returns the close flag value: BIO_CLOSE or BIO_NOCLOSE. It also returns
other negative values if an error occurs.
.Pp
.Fn BIO_pending ,
.Fn BIO_ctrl_pending ,
.Fn BIO_wpending
and
.Fn BIO_ctrl_wpending
return the amount of pending data.
.Fn BIO_pending
and
.Fn BIO_wpending
return negative value or 0 on error.
.Fn BIO_ctrl_pending
and
.Fn BIO_ctrl_wpending
return 0 on error.
.Pp
.Fn BIO_get_ktls_send
returns 1 if the BIO is using the Kernel TLS data-path for sending.
Otherwise, it returns zero.
.Fn BIO_get_ktls_recv
returns 1 if the BIO is using the Kernel TLS data-path for receiving.
Otherwise, it returns zero.
.Pp
.Fn BIO_set_conn_mode
returns 1 for success and 0 for failure.
.Fn BIO_get_conn_mode
returns the current connection mode.
Which may contain the bitwise-or of the following flags:
.Bd -literal
 BIO_SOCK_REUSEADDR
 BIO_SOCK_V6_ONLY
 BIO_SOCK_KEEPALIVE
 BIO_SOCK_NONBLOCK
 BIO_SOCK_NODELAY
 BIO_SOCK_TFO
.Ed
.Pp
.Fn BIO_set_tfo
returns 1 for success, and 0 for failure.
.Sh NOTES
.Fn BIO_flush ,
because it can write data may return 0 or -1 indicating that the call
should be retried later in a similar manner to
.Xr BIO_write_ex 3 .
The
.Xr BIO_should_retry 3
call should be used and appropriate action taken is the call fails.
.Pp
The return values of
.Fn BIO_pending
and
.Fn BIO_wpending
may not reliably determine the amount of pending data in all cases.
For example in the case of a file BIO some data may be available in the
FILE structures internal buffers but it is not possible to determine
this in a portably way.
For other types of BIO they may not be supported.
.Pp
Filter BIOs if they do not internally handle a particular
.Fn BIO_ctrl
operation usually pass the operation to the next BIO in the chain.
This often means there is no need to locate the required BIO for a
particular operation, it can be called on a chain and it will be
automatically passed to the relevant BIO. However, this can cause
unexpected results: for example no current filter BIOs implement
.Fn BIO_seek ,
but this may still succeed if the chain ends in a FILE or file
descriptor BIO.
.Pp
Source/sink BIOs return an 0 if they do not recognize the
.Fn BIO_ctrl
operation.
.Sh BUGS
Some of the return values are ambiguous and care should be taken.
In particular a return value of 0 can be returned if an operation is not
supported, if an error occurred, if EOF has not been reached and in the
case of
.Fn BIO_seek
on a file BIO for a successful operation.
.Pp
In older versions of OpenSSL the
.Fn BIO_ctrl_pending
and
.Fn BIO_ctrl_wpending
could return values greater than INT_MAX on error.
.Sh HISTORY
The
.Fn BIO_get_ktls_send
and
.Fn BIO_get_ktls_recv
macros were added in OpenSSL 3.0. They were modified to never return -1
in OpenSSL 3.0.4.
.Pp
The
.Fn BIO_get_conn_mode ,
.Fn BIO_set_conn_mode
and
.Fn BIO_set_tfo
functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2000-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
