.Dd 2025-09-30
.Dt BIO_S_DATAGRAM 3ossl
.Os
.Sh NAME
.Nm BIO_s_datagram ,
.Nm BIO_new_dgram ,
.Nm BIO_ctrl_dgram_connect ,
.Nm BIO_ctrl_set_connected ,
.Nm BIO_dgram_recv_timedout ,
.Nm BIO_dgram_send_timedout ,
.Nm BIO_dgram_get_peer ,
.Nm BIO_dgram_set_peer ,
.Nm BIO_dgram_detect_peer_addr ,
.Nm BIO_dgram_get_mtu_overhead
.Nd Network BIO with datagram semantics
.Sh SYNOPSIS
.In openssl/bio.h
.Ft BIO_METHOD *
.Fo BIO_s_datagram
.Fa void
.Fc
.Ft BIO *
.Fo BIO_new_dgram
.Fa "int fd"
.Fa "int close_flag"
.Fc
.Ft int
.Fo BIO_ctrl_dgram_connect
.Fa "BIO *bio"
.Fa "const BIO_ADDR *peer"
.Fc
.Ft int
.Fo BIO_ctrl_set_connected
.Fa "BIO *bio"
.Fa "const BIO_ADDR *peer"
.Fc
.Ft int
.Fo BIO_dgram_recv_timedout
.Fa "BIO *bio"
.Fc
.Ft int
.Fo BIO_dgram_send_timedout
.Fa "BIO *bio"
.Fc
.Ft int
.Fo BIO_dgram_get_peer
.Fa "BIO *bio"
.Fa "BIO_ADDR *peer"
.Fc
.Ft int
.Fo BIO_dgram_set_peer
.Fa "BIO *bio"
.Fa "const BIO_ADDR *peer"
.Fc
.Ft int
.Fo BIO_dgram_get_mtu_overhead
.Fa "BIO *bio"
.Fc
.Ft int
.Fo BIO_dgram_detect_peer_addr
.Fa "BIO *bio"
.Fa "BIO_ADDR *peer"
.Fc
.Sh DESCRIPTION
.Fn BIO_s_datagram
is a BIO implementation designed for use with network sockets which
provide datagram semantics, such as UDP sockets.
It is suitable for use with DTLSv1 or QUIC.
.Pp
Because
.Fn BIO_s_datagram
has datagram semantics, a single
.Xr BIO_write 3
call sends a single datagram and a single
.Xr BIO_read 3
call receives a single datagram.
If the size of the buffer passed to
.Xr BIO_read 3
is inadequate, the datagram is silently truncated.
.Pp
For a memory-based BIO which provides datagram semantics identical to
those of
.Fn BIO_s_datagram ,
see
.Xr BIO_s_dgram_pair 3 .
.Pp
This BIO supports the
.Xr BIO_sendmmsg 3
and
.Xr BIO_recvmmsg 3
functions.
.Pp
When using
.Fn BIO_s_datagram ,
it is important to note that:
.Bl -tag -width Ds
.It
This BIO can be used with either a connected or unconnected network
socket.
A connected socket is a network socket which has had
.Xr BIO_connect 3
or a similar OS-specific function called on it.
Such a socket can only receive datagrams from the specified peer.
Any other socket is an unconnected socket and can receive datagrams from
any host.
.It
Despite their naming, neither
.Fn BIO_ctrl_dgram_connect
nor
.Fn BIO_ctrl_set_connected
cause a socket to become connected.
These controls are provided to indicate to the BIO how the underlying
socket is configured and how it is to be used; see below.
.It
Use of
.Fn BIO_s_datagram
with an unconnected network socket is hazardous hecause any successful
call to
.Xr BIO_read 3
results in the peer address used for any subsequent call to
.Xr BIO_write 3
being set to the source address of the datagram received by that call to
.Xr BIO_read 3 .
Thus, unless the caller calls
.Fn BIO_dgram_set_peer
immediately prior to every call to
.Xr BIO_write 3 ,
or never calls
.Xr BIO_read 3 ,
any host on the network may cause future datagrams written to be
redirected to that host.
Therefore, it is recommended that users either use
.Xr BIO_s_dgram 3
only with a connected socket, or, if using
.Xr BIO_s_dgram 3
with an unconnected socket, to use the
.Xr BIO_sendmmsg 3
and
.Xr BIO_recvmmsg 3
methods only and forego use of
.Xr BIO_read 3
and
.Xr BIO_write 3 .
An exception is where
.Xr DTLSv1_listen 3
must be used; see
.Xr DTLSv1_listen 3
for further discussion.
.It
Unlike
.Xr BIO_read 3
and
.Xr BIO_write 3 ,
the
.Xr BIO_sendmmsg 3
and
.Xr BIO_recvmmsg 3
methods are stateless and do not cause the internal state of the
.Fn BIO_s_datagram
to change.
.El
.Pp
Various controls are available for configuring the
.Fn BIO_s_datagram
using
.Xr BIO_ctrl 3 :
.Bl -tag -width Ds
.It BIO_ctrl_dgram_connect (BIO_CTRL_DGRAM_CONNECT)
This is equivalent to calling
.Xr BIO_dgram_set_peer 3 .
.Pp
Despite its name, this function does not cause the underlying socket to
become connected.
.It BIO_ctrl_set_connected (BIO_CTRL_SET_CONNECTED)
This informs the
.Fn BIO_s_datagram
whether the underlying socket has been connected, and therefore how the
.Fn BIO_s_datagram
should attempt to use the socket.
.Pp
If the
.Fa peer
argument is non-NULL,
.Fn BIO_s_datagram
assumes that the underlying socket has been connected and will attempt
to use the socket using OS APIs which do not specify peer addresses (for
example, send(3) and recv(3) or similar).
The
.Fa peer
argument should specify the peer address to which the socket is
connected.
.Pp
If the
.Fa peer
argument is NULL,
.Fn BIO_s_datagram
assumes that the underlying socket is not connected and will attempt to
use the socket using an OS APIs which specify peer addresses (for
example, sendto(3) and recvfrom(3)).
.Pp
This control does not affect the operation of
.Xr BIO_sendmmsg 3
or
.Xr BIO_recvmmsg 3 .
.It BIO_dgram_get_peer (BIO_CTRL_DGRAM_GET_PEER)
This outputs a
.Vt BIO_ADDR
which specifies one of the following values, whichever happened most
recently:
.Bl -tag -width Ds
.It
The peer address last passed to
.Fn BIO_dgram_set_peer ,
.Fn BIO_ctrl_dgram_connect
or
.Fn BIO_ctrl_set_connected .
.It
The peer address of the datagram last received by a call to
.Xr BIO_read 3 .
.El
.It BIO_dgram_set_peer (BIO_CTRL_DGRAM_SET_PEER)
Sets the peer address to be used for subsequent writes to this BIO.
.Pp
Warning: When used with an unconnected network socket, the value set may
be modified by future calls to
.Xr BIO_read 3 ,
making use of
.Fn BIO_s_datagram
hazardous when used with unconnected network sockets; see above.
.Pp
This does not affect the operation of
.Xr BIO_sendmmsg 3 .
.Xr BIO_recvmmsg 3
does not affect the value set by
.Fn BIO_dgram_set_peer .
.It BIO_dgram_detect_peer_addr (BIO_CTRL_DGRAM_DETECT_PEER_ADDR)
This is similar to
.Fn BIO_dgram_get_peer
except that if the peer address has not been set on the BIO object, an
OS call such as getpeername(2) will be attempted to try and autodetect
the peer address to which the underlying socket is connected.
Other BIOs may also implement this control if they are capable of
sensing a peer address, without necessarily also implementing
.Fn BIO_dgram_set_peer
and
.Fn BIO_dgram_get_peer .
.It BIO_dgram_recv_timeout (BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP)
Returns 1 if the last I/O operation performed on the BIO (for example,
via a call to
.Xr BIO_read 3 )
may have been caused by a receive timeout.
.It BIO_dgram_send_timedout (BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP)
Returns 1 if the last I/O operation performed on the BIO (for example,
via a call to
.Xr BIO_write 3 )
may have been caused by a send timeout.
.It BIO_dgram_get_mtu_overhead (BIO_CTRL_DGRAM_GET_MTU_OVERHEAD)
Returns a quantity in bytes which is a rough estimate of the number of
bytes of overhead which should typically be added to a datagram payload
size in order to estimate the final size of the Layer 3 (e.g.
IP) packet which will contain the datagram.
In most cases, the maximum datagram payload size which can be
transmitted can be determined by determining the link MTU in bytes and
subtracting the value returned by this call.
.Pp
The value returned by this call depends on the network layer protocol
being used.
.Pp
The value returned is not fully reliable because datagram overheads can
be higher in atypical network configurations, for example where IPv6
extension headers or IPv4 options are used.
.It BIO_CTRL_DGRAM_SET_DONT_FRAG
If
.Em num
is nonzero, configures the underlying network socket to enable Don't
Fragment mode, in which datagrams will be set with the IP Don't Fragment
(DF) bit set.
If
.Em num
is zero, Don't Fragment mode is disabled.
.It BIO_CTRL_DGRAM_QUERY_MTU
Queries the OS for its assessment of the Path MTU for the destination to
which the underlying network socket, and returns that Path MTU in bytes.
This control can only be used with a connected socket.
.Pp
This is not supported on all platforms and depends on OS support being
available.
Returns 0 on failure.
.It BIO_CTRL_DGRAM_MTU_DISCOVER
This control requests that Path MTU discovery be enabled on the
underlying network socket.
.It BIO_CTRL_DGRAM_GET_FALLBACK_MTU
Returns the estimated minimum size of datagram payload which should
always be supported on the BIO. This size is determined by the minimum
MTU required to be supported by the applicable underlying network layer.
Use of datagrams of this size may lead to suboptimal performance, but
should be routable in all circumstances.
The value returned is the datagram payload size in bytes and does not
include the size of layer 3 or layer 4 protocol headers.
.It BIO_CTRL_DGRAM_MTU_EXCEEDED
Returns 1 if the last attempted write to the BIO failed due to the size
of the attempted write exceeding the applicable MTU.
.It BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT
Accepts a pointer to a
.Sy struct timeval .
If the time specified is zero, disables receive timeouts.
Otherwise, configures the specified time interval as the receive timeout
for the socket for the purposes of future
.Xr BIO_read 3
calls.
.It BIO_CTRL_DGRAM_SET_PEEK_MODE
If
.Sy num
is nonzero, enables peek mode; otherwise, disables peek mode.
Where peek mode is enabled, calls to
.Xr BIO_read 3
read datagrams from the underlying network socket in peek mode, meaning
that a future call to
.Xr BIO_read 3
will yield the same datagram until peek mode is disabled.
.Pp
.Xr BIO_recvmmsg 3
is not affected by this control.
.El
.Pp
.Fn BIO_new_dgram
is a helper function which instantiates a
.Fn BIO_s_datagram
and sets the BIO to use the socket given in
.Fa fd
by calling
.Xr BIO_set_fd 3 .
.Sh RETURN VALUES
.Fn BIO_s_datagram
returns a BIO method.
.Pp
.Fn BIO_new_dgram
returns a BIO on success and NULL on failure.
.Pp
.Fn BIO_ctrl_dgram_connect ,
.Fn BIO_ctrl_set_connected
and
.Fn BIO_dgram_set_peer
return 1 on success and 0 on failure.
.Pp
.Fn BIO_dgram_get_peer
and
.Fn BIO_dgram_detect_peer_addr
return 0 on failure and the number of bytes for the outputted address
representation (a positive value) on success.
.Pp
.Fn BIO_dgram_recv_timedout
and
.Fn BIO_dgram_send_timedout
return 0 or 1 depending on the circumstance; see discussion above.
.Pp
.Fn BIO_dgram_get_mtu_overhead
returns a value in bytes.
.Sh SEE ALSO
.Xr BIO_sendmmsg 3 ,
.Xr BIO_s_dgram_pair 3 ,
.Xr DTLSv1_listen 3 ,
.Xr bio 7
.Sh COPYRIGHT
Copyright 2022-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
