.Dd 2025-09-30
.Dt BIO_F_READBUFFER 3ossl
.Os
.Sh NAME
.Nm BIO_f_readbuffer
.Nd read only buffering BIO that supports BIO_tell() and BIO_seek()
.Sh SYNOPSIS
.In openssl/bio.h
.Ft const BIO_METHOD *
.Fo BIO_f_readbuffer
.Fa void
.Fc
.Sh DESCRIPTION
.Fn BIO_f_readbuffer
returns the read buffering BIO method.
.Pp
This BIO filter can be inserted on top of BIO's that do not support
.Xr BIO_tell 3
or
.Xr BIO_seek 3
(e.g.
A file BIO that uses stdin).
.Pp
Data read from a read buffering BIO comes from an internal buffer which
is filled from the next BIO in the chain.
.Pp
.Xr BIO_gets 3
is supported for read buffering BIOs.
Writing data to a read buffering BIO is not supported.
.Pp
Calling
.Xr BIO_reset 3
on a read buffering BIO does not clear any buffered data.
.Sh NOTES
Read buffering BIOs implement
.Xr BIO_read_ex 3
by using
.Xr BIO_read_ex 3
operations on the next BIO (e.g.
a file BIO) in the chain and storing the result in an internal buffer,
from which bytes are given back to the caller as appropriate for the
call.
.Xr BIO_read_ex 3
is guaranteed to give the caller the number of bytes it asks for, unless
there's an error or end of communication is reached in the next BIO. The
internal buffer can grow to cache the entire contents of the next BIO in
the chain.
.Xr BIO_seek 3
uses the internal buffer, so that it can only seek into data that is
already read.
.Sh RETURN VALUES
.Fn BIO_f_readbuffer
returns the read buffering BIO method.
.Sh SEE ALSO
.Xr bio 7 ,
.Xr BIO_read 3 ,
.Xr BIO_gets 3 ,
.Xr BIO_reset 3 ,
.Xr BIO_ctrl 3 .
.Sh COPYRIGHT
Copyright 2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
