.Dd 2025-09-30
.Dt BIO_NEW 3ossl
.Os
.Sh NAME
.Nm BIO_new_ex ,
.Nm BIO_new ,
.Nm BIO_up_ref ,
.Nm BIO_free ,
.Nm BIO_vfree ,
.Nm BIO_free_all
.Nd BIO allocation and freeing functions
.Sh SYNOPSIS
.In openssl/bio.h
.Ft BIO *
.Fo BIO_new_ex
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const BIO_METHOD *type"
.Fc
.Ft BIO *
.Fo BIO_new
.Fa "const BIO_METHOD *type"
.Fc
.Ft int
.Fo BIO_up_ref
.Fa "BIO *a"
.Fc
.Ft int
.Fo BIO_free
.Fa "BIO *a"
.Fc
.Ft void
.Fo BIO_vfree
.Fa "BIO *a"
.Fc
.Ft void
.Fo BIO_free_all
.Fa "BIO *a"
.Fc
.Sh DESCRIPTION
The
.Fn BIO_new_ex
function returns a new BIO using method
.Fa type
associated with the library context
.Fa libctx
(see OSSL_LIB_CTX(3)). The library context may be NULL to indicate the
default library context.
.Fa type
.Sy MUST NOT
be NULL.
.Pp
The
.Fn BIO_new
is the same as
.Fn BIO_new_ex
except the default library context is always used.
.Pp
.Fn BIO_up_ref
increments the reference count associated with the BIO object.
.Pp
.Fn BIO_free
frees up a single BIO,
.Fn BIO_vfree
also frees up a single BIO but it does not return a value.
If
.Fa a
is NULL nothing is done.
Calling
.Fn BIO_free
may also have some effect on the underlying I/O structure, for example
it may close the file being referred to under certain circumstances.
For more details see the individual BIO_METHOD descriptions.
.Pp
.Fn BIO_free_all
frees up an entire BIO chain, it does not halt if an error occurs
freeing up an individual BIO in the chain.
If
.Fa a
is NULL nothing is done.
.Sh RETURN VALUES
.Fn BIO_new_ex
and
.Fn BIO_new
return a newly created BIO or NULL if the call fails.
.Pp
.Fn BIO_up_ref
and
.Fn BIO_free
return 1 for success and 0 for failure.
.Pp
.Fn BIO_free_all
and
.Fn BIO_vfree
do not return values.
.Sh NOTES
If
.Fn BIO_free
is called on a BIO chain it will only free one BIO resulting in a memory
leak.
.Pp
Calling
.Fn BIO_free_all
on a single BIO has the same effect as calling
.Fn BIO_free
on it other than the discarded return value.
.Sh HISTORY
.Xr BIO_set 3
was removed in OpenSSL 1.1.0 as BIO type is now opaque.
.Pp
.Fn BIO_new_ex
was added in OpenSSL 3.0.
.Sh EXAMPLES
Create a memory BIO:
.Bd -literal
 BIO *mem = BIO_new(BIO_s_mem());
.Ed
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
