.Dd 2025-09-30
.Dt BIO_S_CONNECT 3ossl
.Os
.Sh NAME
.Nm BIO_s_connect ,
.Nm BIO_new_connect ,
.Nm BIO_set_conn_hostname ,
.Nm BIO_set_conn_port ,
.Nm BIO_set_conn_address ,
.Nm BIO_set_conn_ip_family ,
.Nm BIO_get_conn_hostname ,
.Nm BIO_get_conn_port ,
.Nm BIO_get_conn_address ,
.Nm BIO_get_conn_ip_family ,
.Nm BIO_set_nbio ,
.Nm BIO_set_sock_type ,
.Nm BIO_get_sock_type ,
.Nm BIO_get0_dgram_bio ,
.Nm BIO_do_connect
.Nd connect BIO
.Sh SYNOPSIS
.In openssl/bio.h
.Ft const BIO_METHOD *
.Fo BIO_s_connect
.Fa void
.Fc
.Ft BIO *
.Fo BIO_new_connect
.Fa "const char *name"
.Fc
.Ft long
.Fo BIO_set_conn_hostname
.Fa "BIO *b"
.Fa "char *name"
.Fc
.Ft long
.Fo BIO_set_conn_port
.Fa "BIO *b"
.Fa "char *port"
.Fc
.Ft long
.Fo BIO_set_conn_address
.Fa "BIO *b"
.Fa "BIO_ADDR *addr"
.Fc
.Ft long
.Fo BIO_set_conn_ip_family
.Fa "BIO *b"
.Fa "long family"
.Fc
.Ft const char *
.Fo BIO_get_conn_hostname
.Fa "BIO *b"
.Fc
.Ft const char *
.Fo BIO_get_conn_port
.Fa "BIO *b"
.Fc
.Ft const BIO_ADDR *
.Fo BIO_get_conn_address
.Fa "BIO *b"
.Fc
.Ft const long
.Fo BIO_get_conn_ip_family
.Fa "BIO *b"
.Fc
.Ft long
.Fo BIO_set_nbio
.Fa "BIO *b"
.Fa "long n"
.Fc
.Ft int
.Fo BIO_set_sock_type
.Fa "BIO *b"
.Fa "int sock_type"
.Fc
.Ft int
.Fo BIO_get_sock_type
.Fa "BIO *b"
.Fc
.Ft int
.Fo BIO_get0_dgram_bio
.Fa "BIO *B"
.Fa "BIO **dgram_bio"
.Fc
.Ft long
.Fo BIO_do_connect
.Fa "BIO *b"
.Fc
.Sh DESCRIPTION
.Fn BIO_s_connect
returns the connect BIO method.
This is a wrapper round the platform's TCP/IP socket connection
routines.
.Pp
Using connect BIOs, TCP/IP connections can be made and data transferred
using only BIO routines.
In this way any platform specific operations are hidden by the BIO
abstraction.
.Pp
Read and write operations on a connect BIO will perform I/O on the
underlying connection.
If no connection is established and the port and hostname (see below) is
set up properly then a connection is established first.
.Pp
Connect BIOs support
.Xr BIO_puts 3
and
.Xr BIO_gets 3 .
.Pp
If the close flag is set on a connect BIO then any active connection is
shutdown and the socket closed when the BIO is freed.
.Pp
Calling
.Xr BIO_reset 3
on a connect BIO will close any active connection and reset the BIO into
a state where it can connect to the same host again.
.Pp
.Fn BIO_new_connect
combines
.Xr BIO_new 3
and
.Fn BIO_set_conn_hostname
into a single call: that is it creates a new connect BIO with hostname
.Fa name .
.Pp
.Fn BIO_set_conn_hostname
uses the string
.Fa name
to set the hostname.
The hostname can be an IP address; if the address is an IPv6 one, it
must be enclosed in brackets
.Qo Li [ Qc
and
.Qo Li ] Qc .
The hostname can also include the port in the form hostname:port; see
.Xr BIO_parse_hostserv 3
and
.Fn BIO_set_conn_port
for details.
.Pp
.Fn BIO_set_conn_port
sets the port to
.Fa port .
.Fa port
can be the numerical form or a service string such as "http", which will
be mapped to a port number using the system function
.Xr getservbyname 3 .
.Pp
.Fn BIO_set_conn_address
sets the address and port information using a BIO_ADDR(3ssl).
.Pp
.Fn BIO_set_conn_ip_family
sets the IP family.
.Pp
.Fn BIO_get_conn_hostname
returns the hostname of the connect BIO or NULL if the BIO is
initialized but no hostname is set.
This return value is an internal pointer which should not be modified.
.Pp
.Fn BIO_get_conn_port
returns the port as a string.
This return value is an internal pointer which should not be modified.
.Pp
.Fn BIO_get_conn_address
returns the address information as a BIO_ADDR. This return value is an
internal pointer which should not be modified.
.Pp
.Fn BIO_get_conn_ip_family
returns the IP family of the connect BIO.
.Pp
.Fn BIO_set_nbio
sets the non blocking I/O flag to
.Fa n .
If
.Fa n
is zero then blocking I/O is set.
If
.Fa n
is 1 then non blocking I/O is set.
Blocking I/O is the default.
The call to
.Fn BIO_set_nbio
should be made before the connection is established because non blocking
I/O is set during the connect process.
.Pp
.Fn BIO_do_connect
attempts to connect the supplied BIO. This performs an SSL/TLS handshake
as far as supported by the BIO. For non-SSL BIOs the connection is done
typically at TCP level.
If domain name resolution yields multiple IP addresses all of them are
tried after
.Xr connect 3
failures.
The function returns 1 if the connection was established successfully.
A zero or negative value is returned if the connection could not be
established.
The call
.Xr BIO_should_retry 3
should be used for non blocking connect BIOs to determine if the call
should be retried.
If a connection has already been established this call has no effect.
.Pp
.Fn BIO_set_sock_type
can be used to set a socket type value as would be passed in a call to
socket(2). The only currently supported values are
.Sy SOCK_STREAM
(the default) and
.Sy SOCK_DGRAM .
If
.Sy SOCK_DGRAM
is configured, the connection created is a UDP datagram socket handled
via
.Xr BIO_s_datagram 3 .
I/O calls such as
.Xr BIO_read 3
and
.Xr BIO_write 3
are forwarded transparently to an internal
.Xr BIO_s_datagram 3
instance.
The created
.Xr BIO_s_datagram 3
instance can be retrieved using
.Fn BIO_get0_dgram_bio
if desired, which writes a pointer to the
.Xr BIO_s_datagram 3
instance to
.Em *dgram_bio .
The lifetime of the internal
.Xr BIO_s_datagram 3
is managed by
.Fn BIO_s_connect
and does not need to be freed by the caller.
.Pp
.Fn BIO_get_sock_type
retrieves the value set using
.Fn BIO_set_sock_type .
.Sh NOTES
If blocking I/O is set then a non positive return value from any I/O
call is caused by an error condition, although a zero return will
normally mean that the connection was closed.
.Pp
If the port name is supplied as part of the hostname then this will
override any value set with
.Fn BIO_set_conn_port .
This may be undesirable if the application does not wish to allow
connection to arbitrary ports.
This can be avoided by checking for the presence of the ':' character in
the passed hostname and either indicating an error or truncating the
string at that point.
.Pp
The values returned by
.Fn BIO_get_conn_hostname ,
.Fn BIO_get_conn_address ,
and
.Fn BIO_get_conn_port
are updated when a connection attempt is made.
Before any connection attempt the values returned are those set by the
application itself.
.Pp
Applications do not have to call
.Fn BIO_do_connect
but may wish to do so to separate the connection process from other I/O
processing.
.Pp
If non blocking I/O is set then retries will be requested as
appropriate.
.Pp
It addition to
.Xr BIO_should_read 3
and
.Xr BIO_should_write 3
it is also possible for
.Xr BIO_should_io_special 3
to be true during the initial connection process with the reason
BIO_RR_CONNECT. If this is returned then this is an indication that a
connection attempt would block, the application should then take
appropriate action to wait until the underlying socket has connected and
retry the call.
.Pp
.Fn BIO_set_conn_hostname ,
.Fn BIO_set_conn_port ,
.Fn BIO_get_conn_hostname ,
.Fn BIO_set_conn_address ,
.Fn BIO_get_conn_port ,
.Fn BIO_get_conn_address ,
.Fn BIO_set_conn_ip_family ,
.Fn BIO_get_conn_ip_family ,
.Fn BIO_set_nbio ,
and
.Fn BIO_do_connect
are macros.
.Sh RETURN VALUES
.Fn BIO_s_connect
returns the connect BIO method.
.Pp
.Fn BIO_set_conn_address ,
.Fn BIO_set_conn_port ,
and
.Fn BIO_set_conn_ip_family
return 1 or <=0 if an error occurs.
.Pp
.Fn BIO_set_conn_hostname
returns 1 on success and <=0 on failure.
.Pp
.Fn BIO_get_conn_address
returns the address information or NULL if none was set.
.Pp
.Fn BIO_get_conn_hostname
returns the connected hostname or NULL if none was set.
.Pp
.Fn BIO_get_conn_ip_family
returns the address family or -1 if none was set.
.Pp
.Fn BIO_get_conn_port
returns a string representing the connected port or NULL if not set.
.Pp
.Fn BIO_set_nbio
returns 1 or <=0 if an error occurs.
.Pp
.Fn BIO_do_connect
returns 1 if the connection was successfully established and <=0 if the
connection failed.
.Pp
.Fn BIO_set_sock_type
returns 1 on success or 0 on failure.
.Pp
.Fn BIO_get_sock_type
returns a socket type or 0 if the call is not supported.
.Pp
.Fn BIO_get0_dgram_bio
returns 1 on success or 0 on failure.
.Sh EXAMPLES
This is example connects to a webserver on the local host and attempts
to retrieve a page and copy the result to standard output.
.Bd -literal
 BIO *cbio, *out;
 int len;
 char tmpbuf[1024];

 cbio = BIO_new_connect("localhost:http");
 out = BIO_new_fp(stdout, BIO_NOCLOSE);
 if (BIO_do_connect(cbio) <= 0) {
     fprintf(stderr, "Error connecting to server\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }
 BIO_puts(cbio, "GET / HTTP/1.0\en\en");
 for (;;) {
     len = BIO_read(cbio, tmpbuf, 1024);
     if (len <= 0)
         break;
     BIO_write(out, tmpbuf, len);
 }
 BIO_free(cbio);
 BIO_free(out);
.Ed
.Sh SEE ALSO
.Xr BIO_ADDR 3 ,
.Xr BIO_parse_hostserv 3
.Sh HISTORY
.Xr BIO_set_conn_int_port 3 ,
.Xr BIO_get_conn_int_port 3 ,
.Xr BIO_set_conn_ip 3 ,
and
.Xr BIO_get_conn_ip 3
were removed in OpenSSL 1.1.0. Use
.Fn BIO_set_conn_address
and
.Fn BIO_get_conn_address
instead.
.Pp
Connect BIOs support
.Xr BIO_gets 3
since OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
