.Dd 2025-09-30
.Dt BIO_F_SSL 3ossl
.Os
.Sh NAME
.Nm BIO_do_handshake ,
.Nm BIO_f_ssl ,
.Nm BIO_set_ssl ,
.Nm BIO_get_ssl ,
.Nm BIO_set_ssl_mode ,
.Nm BIO_set_ssl_renegotiate_bytes ,
.Nm BIO_get_num_renegotiates ,
.Nm BIO_set_ssl_renegotiate_timeout ,
.Nm BIO_new_ssl ,
.Nm BIO_new_ssl_connect ,
.Nm BIO_new_buffer_ssl_connect ,
.Nm BIO_ssl_copy_session_id ,
.Nm BIO_ssl_shutdown
.Nd SSL BIO
.Sh SYNOPSIS
.In openssl/bio.h
.In openssl/ssl.h
.Ft const BIO_METHOD *
.Fo BIO_f_ssl
.Fa void
.Fc
.Ft long
.Fo BIO_set_ssl
.Fa "BIO *b"
.Fa "SSL *ssl"
.Fa "long c"
.Fc
.Ft long
.Fo BIO_get_ssl
.Fa "BIO *b"
.Fa "SSL **sslp"
.Fc
.Ft long
.Fo BIO_set_ssl_mode
.Fa "BIO *b"
.Fa "long client"
.Fc
.Ft long
.Fo BIO_set_ssl_renegotiate_bytes
.Fa "BIO *b"
.Fa "long num"
.Fc
.Ft long
.Fo BIO_set_ssl_renegotiate_timeout
.Fa "BIO *b"
.Fa "long seconds"
.Fc
.Ft long
.Fo BIO_get_num_renegotiates
.Fa "BIO *b"
.Fc
.Ft BIO *
.Fo BIO_new_ssl
.Fa "SSL_CTX *ctx"
.Fa "int client"
.Fc
.Ft BIO *
.Fo BIO_new_ssl_connect
.Fa "SSL_CTX *ctx"
.Fc
.Ft BIO *
.Fo BIO_new_buffer_ssl_connect
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo BIO_ssl_copy_session_id
.Fa "BIO *to"
.Fa "BIO *from"
.Fc
.Ft void
.Fo BIO_ssl_shutdown
.Fa "BIO *bio"
.Fc
.Ft long
.Fo BIO_do_handshake
.Fa "BIO *b"
.Fc
.Sh DESCRIPTION
.Fn BIO_f_ssl
returns the SSL BIO method.
This is a filter BIO which is a wrapper round the OpenSSL SSL routines
adding a BIO "flavour" to SSL I/O.
.Pp
I/O performed on an SSL BIO communicates using the SSL protocol with the
SSLs read and write BIOs.
If an SSL connection is not established then an attempt is made to
establish one on the first I/O call.
.Pp
If a BIO is appended to an SSL BIO using
.Xr BIO_push 3
it is automatically used as the SSL BIOs read and write BIOs.
.Pp
Calling
.Xr BIO_reset 3
on an SSL BIO closes down any current SSL connection by calling
.Xr SSL_shutdown 3 .
.Xr BIO_reset 3
is then sent to the next BIO in the chain: this will typically
disconnect the underlying transport.
The SSL BIO is then reset to the initial accept or connect state.
.Pp
If the close flag is set when an SSL BIO is freed then the internal SSL
structure is also freed using
.Xr SSL_free 3 .
.Pp
.Fn BIO_set_ssl
sets the internal SSL pointer of SSL BIO
.Fa b
to
.Fa ssl
using the close flag
.Fa c .
.Pp
.Fn BIO_get_ssl
retrieves the SSL pointer of SSL BIO
.Fa b ,
it can then be manipulated using the standard SSL library functions.
.Pp
.Fn BIO_set_ssl_mode
sets the SSL BIO mode to
.Fa client .
If
.Fa client
is 1 client mode is set.
If
.Fa client
is 0 server mode is set.
.Pp
.Fn BIO_set_ssl_renegotiate_bytes
sets the renegotiate byte count of SSL BIO
.Fa b
to
.Fa num .
When set after every
.Fa num
bytes of I/O (read and write) the SSL session is automatically
renegotiated.
.Fa num
must be at least 512 bytes.
.Pp
.Fn BIO_set_ssl_renegotiate_timeout
sets the renegotiate timeout of SSL BIO
.Fa b
to
.Fa seconds .
When the renegotiate timeout elapses the session is automatically
renegotiated.
.Pp
.Fn BIO_get_num_renegotiates
returns the total number of session renegotiations due to I/O or timeout
of SSL BIO
.Fa b .
.Pp
.Fn BIO_new_ssl
allocates an SSL BIO using SSL_CTX
.Fa ctx
and using client mode if
.Fa client
is non zero.
.Pp
.Fn BIO_new_ssl_connect
creates a new BIO chain consisting of an SSL BIO (using
.Fa ctx )
followed by a connect BIO.
.Pp
.Fn BIO_new_buffer_ssl_connect
creates a new BIO chain consisting of a buffering BIO, an SSL BIO (using
.Fa ctx Ns ),
and a connect BIO.
.Pp
.Fn BIO_ssl_copy_session_id
copies an SSL session id between BIO chains
.Fa from
and
.Fa to .
It does this by locating the SSL BIOs in each chain and calling
.Xr SSL_copy_session_id 3
on the internal SSL pointer.
.Pp
.Fn BIO_ssl_shutdown
closes down an SSL connection on BIO chain
.Fa bio .
It does this by locating the SSL BIO in the chain and calling
.Xr SSL_shutdown 3
on its internal SSL pointer.
.Pp
.Fn BIO_do_handshake
attempts to complete an SSL handshake on the supplied BIO and establish
the SSL connection.
For non-SSL BIOs the connection is done typically at TCP level.
If domain name resolution yields multiple IP addresses all of them are
tried after
.Xr connect 3
failures.
The function returns 1 if the connection was established successfully.
A zero or negative value is returned if the connection could not be
established.
The call
.Xr BIO_should_retry 3
should be used for nonblocking connect BIOs to determine if the call
should be retried.
If a connection has already been established this call has no effect.
.Sh NOTES
SSL BIOs are exceptional in that if the underlying transport is non
blocking they can still request a retry in exceptional circumstances.
Specifically this will happen if a session renegotiation takes place
during a
.Xr BIO_read_ex 3
operation, one case where this happens is when step up occurs.
.Pp
The SSL flag SSL_AUTO_RETRY can be set to disable this behaviour.
That is when this flag is set an SSL BIO using a blocking transport will
never request a retry.
.Pp
Since unknown
.Xr BIO_ctrl 3
operations are sent through filter BIOs the servers name and port can be
set using
.Xr BIO_set_host 3
on the BIO returned by
.Fn BIO_new_ssl_connect
without having to locate the connect BIO first.
.Pp
Applications do not have to call
.Fn BIO_do_handshake
but may wish to do so to separate the handshake process from other I/O
processing.
.Pp
.Fn BIO_set_ssl ,
.Fn BIO_get_ssl ,
.Fn BIO_set_ssl_mode ,
.Fn BIO_set_ssl_renegotiate_bytes ,
.Fn BIO_set_ssl_renegotiate_timeout ,
.Fn BIO_get_num_renegotiates ,
and
.Fn BIO_do_handshake
are implemented as macros.
.Pp
.Fn BIO_ssl_copy_session_id
is not currently supported on QUIC SSL objects and fails if called on
such an object.
.Sh RETURN VALUES
.Fn BIO_f_ssl
returns the SSL
.Sy BIO_METHOD
structure.
.Pp
.Fn BIO_set_ssl ,
.Fn BIO_get_ssl ,
.Fn BIO_set_ssl_mode ,
.Fn BIO_set_ssl_renegotiate_bytes ,
.Fn BIO_set_ssl_renegotiate_timeout
and
.Fn BIO_get_num_renegotiates
return 1 on success or a value which is less than or equal to 0 if an
error occurred.
.Pp
.Fn BIO_new_ssl ,
.Fn BIO_new_ssl_connect
and
.Fn BIO_new_buffer_ssl_connect
return a valid
.Vt BIO
structure on success or
.Dv NULL
if an error occurred.
.Pp
.Fn BIO_ssl_copy_session_id
returns 1 on success or 0 on error, or if called on a QUIC SSL object.
.Pp
.Fn BIO_do_handshake
returns 1 if the connection was established successfully.
A zero or negative value is returned if the connection could not be
established.
.Sh EXAMPLES
This SSL/TLS client example attempts to retrieve a page from an SSL/TLS
web server.
The I/O routines are identical to those of the unencrypted example in
.Xr BIO_s_connect 3 .
.Bd -literal
 BIO *sbio, *out;
 int len;
 char tmpbuf[1024];
 SSL_CTX *ctx;
 SSL *ssl;

 /* XXX Seed the PRNG if needed. */

 ctx = SSL_CTX_new(TLS_client_method());

 /* XXX Set verify paths and mode here. */

 sbio = BIO_new_ssl_connect(ctx);
 BIO_get_ssl(sbio, &ssl);
 if (ssl == NULL) {
     fprintf(stderr, "Can't locate SSL pointer\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }

 /* XXX We might want to do other things with ssl here */

 /* An empty host part means the loopback address */
 BIO_set_conn_hostname(sbio, ":https");

 out = BIO_new_fp(stdout, BIO_NOCLOSE);
 if (BIO_do_connect(sbio) <= 0) {
     fprintf(stderr, "Error connecting to server\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }

 /* XXX Could examine ssl here to get connection info */

 BIO_puts(sbio, "GET / HTTP/1.0\en\en");
 for (;;) {
     len = BIO_read(sbio, tmpbuf, 1024);
     if (len <= 0)
         break;
     BIO_write(out, tmpbuf, len);
 }
 BIO_free_all(sbio);
 BIO_free(out);
.Ed
.Pp
Here is a simple server example.
It makes use of a buffering BIO to allow lines to be read from the SSL
BIO using BIO_gets.
It creates a pseudo web page containing the actual request from a client
and also echoes the request to standard output.
.Bd -literal
 BIO *sbio, *bbio, *acpt, *out;
 int len;
 char tmpbuf[1024];
 SSL_CTX *ctx;
 SSL *ssl;

 /* XXX Seed the PRNG if needed. */

 ctx = SSL_CTX_new(TLS_server_method());
 if (!SSL_CTX_use_certificate_file(ctx, "server.pem", SSL_FILETYPE_PEM)
         || !SSL_CTX_use_PrivateKey_file(ctx, "server.pem", SSL_FILETYPE_PEM)
         || !SSL_CTX_check_private_key(ctx)) {
     fprintf(stderr, "Error setting up SSL_CTX\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }

 /* XXX Other things like set verify locations, EDH temp callbacks. */

 /* New SSL BIO setup as server */
 sbio = BIO_new_ssl(ctx, 0);
 BIO_get_ssl(sbio, &ssl);
 if (ssl == NULL) {
     fprintf(stderr, "Can't locate SSL pointer\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }

 bbio = BIO_new(BIO_f_buffer());
 sbio = BIO_push(bbio, sbio);
 acpt = BIO_new_accept("4433");

 /*
  * By doing this when a new connection is established
  * we automatically have sbio inserted into it. The
  * BIO chain is now 'swallowed' by the accept BIO and
  * will be freed when the accept BIO is freed.
  */
 BIO_set_accept_bios(acpt, sbio);
 out = BIO_new_fp(stdout, BIO_NOCLOSE);

 /* First call to BIO_do_accept() sets up accept BIO */
 if (BIO_do_accept(acpt) <= 0) {
     fprintf(stderr, "Error setting up accept BIO\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }
.Ed
.Pp
/* Second call to
.Xr BIO_do_accept 3
waits for incoming connection */
.br
if (BIO_do_accept(acpt) <= 0) {
.br
fprintf(stderr, "Error accepting connection\en");
.br
ERR_print_errors_fp(stderr);
.br
exit(1);
.br
}
.Bd -literal
 /* We only want one connection so remove and free accept BIO */
 sbio = BIO_pop(acpt);
 BIO_free_all(acpt);

 if (BIO_do_handshake(sbio) <= 0) {
     fprintf(stderr, "Error in SSL handshake\en");
     ERR_print_errors_fp(stderr);
     exit(1);
 }

 BIO_puts(sbio, "HTTP/1.0 200 OK\er\enContent-type: text/plain\er\en\er\en");
 BIO_puts(sbio, "\er\enConnection Established\er\enRequest headers:\er\en");
 BIO_puts(sbio, "--------------------------------------------------\er\en");

 for (;;) {
     len = BIO_gets(sbio, tmpbuf, 1024);
     if (len <= 0)
         break;
     BIO_write(sbio, tmpbuf, len);
     BIO_write(out, tmpbuf, len);
     /* Look for blank line signifying end of headers*/
     if (tmpbuf[0] == '\er' || tmpbuf[0] == '\en')
         break;
 }

 BIO_puts(sbio, "--------------------------------------------------\er\en");
 BIO_puts(sbio, "\er\en");
 BIO_flush(sbio);
 BIO_free_all(sbio);
.Ed
.Sh HISTORY
In OpenSSL before 1.0.0 the
.Xr BIO_pop 3
call was handled incorrectly, the I/O BIO reference count was
incorrectly incremented (instead of decremented) and dissociated with
the SSL BIO even if the SSL BIO was not explicitly being popped (e.g.
a pop higher up the chain).
Applications which included workarounds for this bug (e.g.
freeing BIOs more than once) should be modified to handle this fix or
they may free up an already freed BIO.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
