.Dd 2025-09-30
.Dt BN_BLINDING_NEW 3ossl
.Os
.Sh NAME
.Nm BN_BLINDING_new ,
.Nm BN_BLINDING_free ,
.Nm BN_BLINDING_update ,
.Nm BN_BLINDING_convert ,
.Nm BN_BLINDING_invert ,
.Nm BN_BLINDING_convert_ex ,
.Nm BN_BLINDING_invert_ex ,
.Nm BN_BLINDING_is_current_thread ,
.Nm BN_BLINDING_set_current_thread ,
.Nm BN_BLINDING_lock ,
.Nm BN_BLINDING_unlock ,
.Nm BN_BLINDING_get_flags ,
.Nm BN_BLINDING_set_flags ,
.Nm BN_BLINDING_create_param
.Nd blinding related BIGNUM functions
.Sh SYNOPSIS
.In openssl/bn.h
.Ft BN_BLINDING *
.Fo BN_BLINDING_new
.Fa "const BIGNUM *A"
.Fa "const BIGNUM *Ai"
.Fa "BIGNUM *mod"
.Fc
.Ft void
.Fo BN_BLINDING_free
.Fa "BN_BLINDING *b"
.Fc
.Ft int
.Fo BN_BLINDING_update
.Fa "BN_BLINDING *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_BLINDING_convert
.Fa "BIGNUM *n"
.Fa "BN_BLINDING *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_BLINDING_invert
.Fa "BIGNUM *n"
.Fa "BN_BLINDING *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_BLINDING_convert_ex
.Fa "BIGNUM *n"
.Fa "BIGNUM *r"
.Fa "BN_BLINDING *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_BLINDING_invert_ex
.Fa "BIGNUM *n"
.Fa "const BIGNUM *r"
.Fa "BN_BLINDING *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_BLINDING_is_current_thread
.Fa "BN_BLINDING *b"
.Fc
.Ft void
.Fo BN_BLINDING_set_current_thread
.Fa "BN_BLINDING *b"
.Fc
.Ft int
.Fo BN_BLINDING_lock
.Fa "BN_BLINDING *b"
.Fc
.Ft int
.Fo BN_BLINDING_unlock
.Fa "BN_BLINDING *b"
.Fc
.Ft unsigned long
.Fo BN_BLINDING_get_flags
.Fa "const BN_BLINDING *b"
.Fc
.Ft void
.Fo BN_BLINDING_set_flags
.Fa "BN_BLINDING *b"
.Fa "unsigned long flags"
.Fc
.Ft BN_BLINDING *
.Fo BN_BLINDING_create_param
.Fa "BN_BLINDING *b"
.Fa "const BIGNUM *e"
.Fa "BIGNUM *m"
.Fa "BN_CTX *ctx"
.Fa "int (*bn_mod_exp)(BIGNUM *r"
.Fa "const BIGNUM *a"
.Fa "const BIGNUM *p"
.Fa "const BIGNUM *m"
.Fa "BN_CTX *ctx"
.Fa "BN_MONT_CTX *m_ctx)"
.Fa "BN_MONT_CTX *m_ctx"
.Fc
.Sh DESCRIPTION
.Fn BN_BLINDING_new
allocates a new
.Vt BN_BLINDING
structure and copies the
.Fa A
and
.Fa \&Ai
values into the newly created
.Vt BN_BLINDING
object.
.Pp
.Fn BN_BLINDING_free
frees the
.Vt BN_BLINDING
structure.
If
.Fa b
is NULL, nothing is done.
.Pp
.Fn BN_BLINDING_update
updates the
.Vt BN_BLINDING
parameters by squaring the
.Fa A
and
.Fa \&Ai
or, after specific number of uses and if the necessary parameters are
set, by re-creating the blinding parameters.
.Pp
.Fn BN_BLINDING_convert_ex
multiplies
.Fa n
with the blinding factor
.Fa A .
If
.Fa r
is not NULL a copy the inverse blinding factor
.Fa \&Ai
will be returned in
.Fa r
(this is useful if a
.Sy RSA
object is shared among several threads).
.Fn BN_BLINDING_invert_ex
multiplies
.Fa n
with the inverse blinding factor
.Fa \&Ai .
If
.Fa r
is not NULL it will be used as the inverse blinding.
.Pp
.Fn BN_BLINDING_convert
and
.Fn BN_BLINDING_invert
are wrapper functions for
.Fn BN_BLINDING_convert_ex
and
.Fn BN_BLINDING_invert_ex
with
.Fa r
set to NULL.
.Pp
.Fn BN_BLINDING_is_current_thread
returns whether the
.Vt BN_BLINDING
structure is owned by the current thread.
This is to help users provide proper locking if needed for
multi-threaded use.
.Pp
.Fn BN_BLINDING_set_current_thread
sets the current thread as the owner of the
.Vt BN_BLINDING
structure.
.Pp
.Fn BN_BLINDING_lock
locks the
.Vt BN_BLINDING
structure.
.Pp
.Fn BN_BLINDING_unlock
unlocks the
.Vt BN_BLINDING
structure.
.Pp
.Fn BN_BLINDING_get_flags
returns the BN_BLINDING flags.
Currently there are two supported flags:
.Sy BN_BLINDING_NO_UPDATE
and
.Sy BN_BLINDING_NO_RECREATE .
.Sy BN_BLINDING_NO_UPDATE
inhibits the automatic update of the
.Vt BN_BLINDING
parameters after each use and
.Sy BN_BLINDING_NO_RECREATE
inhibits the automatic re-creation of the
.Vt BN_BLINDING
parameters after a fixed number of uses (currently 32). In newly
allocated
.Vt BN_BLINDING
objects no flags are set.
.Fn BN_BLINDING_set_flags
sets the
.Vt BN_BLINDING
parameters flags.
.Pp
.Fn BN_BLINDING_create_param
creates new
.Vt BN_BLINDING
parameters using the exponent
.Fa e
and the modulus
.Fa m .
.Sy bn_mod_exp
and
.Fa m_ctx
can be used to pass special functions for exponentiation (normally
.Xr BN_mod_exp_mont 3
and
.Vt BN_MONT_CTX Ns ).
.Sh RETURN VALUES
.Fn BN_BLINDING_new
returns the newly allocated
.Vt BN_BLINDING
structure or NULL in case of an error.
.Pp
.Fn BN_BLINDING_update ,
.Fn BN_BLINDING_convert ,
.Fn BN_BLINDING_invert ,
.Fn BN_BLINDING_convert_ex
and
.Fn BN_BLINDING_invert_ex
return 1 on success and 0 if an error occurred.
.Pp
.Fn BN_BLINDING_is_current_thread
returns 1 if the current thread owns the
.Vt BN_BLINDING
object, 0 otherwise.
.Pp
.Fn BN_BLINDING_set_current_thread
doesn't return anything.
.Pp
.Fn BN_BLINDING_lock ,
.Fn BN_BLINDING_unlock
return 1 if the operation succeeded or 0 on error.
.Pp
.Fn BN_BLINDING_get_flags
returns the currently set
.Vt BN_BLINDING
flags (a
.Sy unsigned long
value).
.Pp
.Fn BN_BLINDING_create_param
returns the newly created
.Vt BN_BLINDING
parameters or NULL on error.
.Sh HISTORY
.Xr BN_BLINDING_thread_id 3
was first introduced in OpenSSL 1.0.0, and it deprecates
.Xr BN_BLINDING_set_thread_id 3
and
.Xr BN_BLINDING_get_thread_id 3 .
.Sh COPYRIGHT
Copyright 2005-2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
