.Dd 2025-09-30
.Dt BN_COPY 3ossl
.Os
.Sh NAME
.Nm BN_copy ,
.Nm BN_dup ,
.Nm BN_with_flags
.Nd copy BIGNUMs
.Sh SYNOPSIS
.In openssl/bn.h
.Ft BIGNUM *
.Fo BN_copy
.Fa "BIGNUM *to"
.Fa "const BIGNUM *from"
.Fc
.Ft BIGNUM *
.Fo BN_dup
.Fa "const BIGNUM *from"
.Fc
.Ft void
.Fo BN_with_flags
.Fa "BIGNUM *dest"
.Fa "const BIGNUM *b"
.Fa "int flags"
.Fc
.Sh DESCRIPTION
.Fn BN_copy
copies
.Fa from
to
.Fa to .
.Fn BN_dup
creates a new
.Vt BIGNUM
containing the value
.Fa from .
.Pp
BN_with_flags creates a
.Sy temporary
shallow copy of
.Fa b
in
.Fa dest .
It places significant restrictions on the copied data.
Applications that do no adhere to these restrictions may encounter
unexpected side effects or crashes.
For that reason use of this function is discouraged.
Any flags provided in
.Fa flags
will be set in
.Fa dest
in addition to any flags already set in
.Fa b .
For example this might commonly be used to create a temporary copy of a
BIGNUM with the
.Sy BN_FLG_CONSTTIME
flag set for constant time operations.
The temporary copy in
.Fa dest
will share some internal state with
.Fa b .
For this reason the following restrictions apply to the use of
.Fa dest :
.Bl -bullet
.It
.Fa dest
should be a newly allocated BIGNUM obtained via a call to
.Xr BN_new 3 .
It should not have been used for other purposes or initialised in any
way.
.It
.Fa dest
must only be used in "read-only" operations, i.e.
typically those functions where the relevant parameter is declared
"const".
.It
.Fa dest
must be used and freed before any further subsequent use of
.Fa b
.El
.Sh RETURN VALUES
.Fn BN_copy
returns
.Fa to
on success, NULL on error.
.Fn BN_dup
returns the new
.Vt BIGNUM ,
and NULL on error.
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh COPYRIGHT
Copyright 2000-2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
