.Dd 2025-09-30
.Dt BN_CMP 3ossl
.Os
.Sh NAME
.Nm BN_cmp ,
.Nm BN_ucmp ,
.Nm BN_is_zero ,
.Nm BN_is_one ,
.Nm BN_is_word ,
.Nm BN_abs_is_word ,
.Nm BN_is_odd ,
.Nm BN_are_coprime
.Nd BIGNUM comparison and test functions
.Sh SYNOPSIS
.In openssl/bn.h
.Ft int
.Fo BN_cmp
.Fa "const BIGNUM *a"
.Fa "const BIGNUM *b"
.Fc
.Ft int
.Fo BN_ucmp
.Fa "const BIGNUM *a"
.Fa "const BIGNUM *b"
.Fc
.Ft int
.Fo BN_is_zero
.Fa "const BIGNUM *a"
.Fc
.Ft int
.Fo BN_is_one
.Fa "const BIGNUM *a"
.Fc
.Ft int
.Fo BN_is_word
.Fa "const BIGNUM *a"
.Fa "const BN_ULONG w"
.Fc
.Ft int
.Fo BN_abs_is_word
.Fa "const BIGNUM *a"
.Fa "const BN_ULONG w"
.Fc
.Ft int
.Fo BN_is_odd
.Fa "const BIGNUM *a"
.Fc
.Ft int
.Fo BN_are_coprime
.Fa "BIGNUM *a"
.Fa "const BIGNUM *b"
.Fa "BN_CTX *ctx"
.Fc
.Sh DESCRIPTION
.Fn BN_cmp
compares the numbers
.Fa a
and
.Fa b .
.Fn BN_ucmp
compares their absolute values.
.Pp
.Fn BN_is_zero ,
.Fn BN_is_one ,
.Fn BN_is_word
and
.Fn BN_abs_is_word
test if
.Fa a
equals 0, 1,
.Fa w ,
or
.Pf \(ba Fa w
\(barespectively.
.Fn BN_is_odd
tests if
.Fa a
is odd.
.Pp
.Fn BN_are_coprime
determines if
.Fa a
and
.Fa b
are coprime.
.Fa ctx
is used internally for storing temporary variables.
The values of
.Fa a
and
.Fa b
and
.Fa ctx
must not be NULL.
.Sh RETURN VALUES
.Fn BN_cmp
returns -1 if
.Fa a
\(la
.Fa b ,
0 if
.Fa a
==
.Fa b
and 1 if
.Fa a
\(ra
.Fa b .
.Fn BN_ucmp
is the same using the absolute values of
.Fa a
and
.Fa b .
.Pp
.Fn BN_is_zero ,
.Fn BN_is_one
.Fn BN_is_word ,
.Fn BN_abs_is_word
and
.Fn BN_is_odd
return 1 if the condition is true, 0 otherwise.
.Pp
.Fn BN_are_coprime
returns 1 if the
.Vt BIGNUM Ns 's
are coprime, otherwise it returns 0.
.Sh HISTORY
Prior to OpenSSL 1.1.0,
.Fn BN_is_zero ,
.Fn BN_is_one ,
.Fn BN_is_word ,
.Fn BN_abs_is_word
and
.Fn BN_is_odd
were macros.
.Pp
The function
.Fn BN_are_coprime
was added in OpenSSL 3.1.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
