.Dd 2025-09-30
.Dt BN_RAND 3ossl
.Os
.Sh NAME
.Nm BN_rand_ex ,
.Nm BN_rand ,
.Nm BN_priv_rand_ex ,
.Nm BN_priv_rand ,
.Nm BN_pseudo_rand ,
.Nm BN_rand_range_ex ,
.Nm BN_rand_range ,
.Nm BN_priv_rand_range_ex ,
.Nm BN_priv_rand_range ,
.Nm BN_pseudo_rand_range
.Nd generate pseudo-random number
.Sh SYNOPSIS
.In openssl/bn.h
.Ft int
.Fo BN_rand_ex
.Fa "BIGNUM *rnd"
.Fa "int bits"
.Fa "int top"
.Fa "int bottom"
.Fa "unsigned int strength"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_rand
.Fa "BIGNUM *rnd"
.Fa "int bits"
.Fa "int top"
.Fa "int bottom"
.Fc
.Ft int
.Fo BN_priv_rand_ex
.Fa "BIGNUM *rnd"
.Fa "int bits"
.Fa "int top"
.Fa "int bottom"
.Fa "unsigned int strength"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_priv_rand
.Fa "BIGNUM *rnd"
.Fa "int bits"
.Fa "int top"
.Fa "int bottom"
.Fc
.Ft int
.Fo BN_rand_range_ex
.Fa "BIGNUM *rnd"
.Fa "const BIGNUM *range"
.Fa "unsigned int strength"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_rand_range
.Fa "BIGNUM *rnd"
.Fa "const BIGNUM *range"
.Fc
.Ft int
.Fo BN_priv_rand_range_ex
.Fa "BIGNUM *rnd"
.Fa "const BIGNUM *range"
.Fa "unsigned int strength"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo BN_priv_rand_range
.Fa "BIGNUM *rnd"
.Fa "const BIGNUM *range"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo BN_pseudo_rand
.Fa "BIGNUM *rnd"
.Fa "int bits"
.Fa "int top"
.Fa "int bottom"
.Fc
.Ft int
.Fo BN_pseudo_rand_range
.Fa "BIGNUM *rnd"
.Fa "const BIGNUM *range"
.Fc
.Sh DESCRIPTION
.Fn BN_rand_ex
generates a cryptographically strong pseudo-random number of
.Fa bits
in length and security strength at least
.Fa strength
bits using the random number generator for the library context
associated with
.Fa ctx .
The function stores the generated data in
.Fa rnd .
The parameter
.Fa ctx
may be NULL in which case the default library context is used.
If
.Fa bits
is less than zero, or too small to accommodate the requirements
specified by the
.Fa top
and
.Fa bottom
parameters, an error is returned.
The
.Fa top
parameters specifies requirements on the most significant bit of the
generated number.
If it is
.Sy BN_RAND_TOP_ANY ,
there is no constraint.
If it is
.Sy BN_RAND_TOP_ONE ,
the top bit must be one.
If it is
.Sy BN_RAND_TOP_TWO ,
the two most significant bits of the number will be set to 1, so that
the product of two such random numbers will always have
.Pf 2* Fa bits
length.
If
.Fa bottom
is
.Sy BN_RAND_BOTTOM_ODD ,
the number will be odd; if it is
.Sy BN_RAND_BOTTOM_ANY
it can be odd or even.
If
.Fa bits
is 1 then
.Fa top
cannot also be
.Sy BN_RAND_TOP_TWO .
.Pp
.Fn BN_rand
is the same as
.Fn BN_rand_ex
except that the default library context is always used.
.Pp
.Fn BN_rand_range_ex
generates a cryptographically strong pseudo-random number
.Fa rnd ,
of security strength at least
.Fa strength
bits, in the range 0 \(la=
.Fa rnd
\(la
.Fa range
using the random number generator for the library context associated
with
.Fa ctx .
The parameter
.Fa ctx
may be NULL in which case the default library context is used.
.Pp
.Fn BN_rand_range
is the same as
.Fn BN_rand_range_ex
except that the default library context is always used.
.Pp
.Fn BN_priv_rand_ex ,
.Fn BN_priv_rand ,
.Xr BN_priv_rand_rand_ex 3
and
.Fn BN_priv_rand_range
have the same semantics as
.Fn BN_rand_ex ,
.Fn BN_rand ,
.Fn BN_rand_range_ex
and
.Fn BN_rand_range
respectively.
They are intended to be used for generating values that should remain
private, and mirror the same difference between
.Xr RAND_bytes 3
and
.Xr RAND_priv_bytes 3 .
.Sh NOTES
Always check the error return value of these functions and do not take
randomness for granted: an error occurs if the CSPRNG has not been
seeded with enough randomness to ensure an unpredictable byte sequence.
.Sh RETURN VALUES
The functions return 1 on success, 0 on error.
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr RAND_add 3 ,
.Xr RAND_bytes 3 ,
.Xr RAND_priv_bytes 3 ,
.Xr RAND 7 ,
.Xr EVP_RAND 7
.Sh HISTORY
.Bl -bullet
.It
Starting with OpenSSL release 1.1.0,
.Fn BN_pseudo_rand
has been identical to
.Fn BN_rand
and
.Fn BN_pseudo_rand_range
has been identical to
.Fn BN_rand_range .
The
.Fn BN_pseudo_rand
and
.Fn BN_pseudo_rand_range
functions were deprecated in OpenSSL 3.0.
.It
The
.Fn BN_priv_rand
and
.Fn BN_priv_rand_range
functions were added in OpenSSL 1.1.1.
.It
The
.Fn BN_rand_ex ,
.Fn BN_priv_rand_ex ,
.Fn BN_rand_range_ex
and
.Fn BN_priv_rand_range_ex
functions were added in OpenSSL 3.0.
.El
.Sh COPYRIGHT
Copyright 2000-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
