.Dd 2025-09-30
.Dt BN_ZERO 3ossl
.Os
.Sh NAME
.Nm BN_zero ,
.Nm BN_one ,
.Nm BN_value_one ,
.Nm BN_set_word ,
.Nm BN_get_word
.Nd BIGNUM assignment operations
.Sh SYNOPSIS
.In openssl/bn.h
.Ft void
.Fo BN_zero
.Fa "BIGNUM *a"
.Fc
.Ft int
.Fo BN_one
.Fa "BIGNUM *a"
.Fc
.Ft const BIGNUM *
.Fo BN_value_one
.Fa void
.Fc
.Ft int
.Fo BN_set_word
.Fa "BIGNUM *a"
.Fa "BN_ULONG w"
.Fc
.Ft unsigned BN_ULONG
.Fo BN_get_word
.Fa "BIGNUM *a"
.Fc
.Sh DESCRIPTION
.Vt BN_ULONG
is a macro that will be an unsigned integral type optimized for the most
efficient implementation on the local platform.
.Pp
.Fn BN_zero ,
.Fn BN_one
and
.Fn BN_set_word
set
.Fa a
to the values 0, 1 and
.Fa w
respectively.
.Fn BN_zero
and
.Fn BN_one
are macros.
.Pp
.Fn BN_value_one
returns a
.Vt BIGNUM
constant of value 1. This constant is useful for use in comparisons and
assignment.
.Pp
.Fn BN_get_word
returns
.Fa a ,
if it can be represented as a
.Vt BN_ULONG .
.Sh RETURN VALUES
.Fn BN_get_word
returns the value
.Fa a ,
or all-bits-set if
.Fa a
cannot be represented as a single integer.
.Pp
.Fn BN_one
and
.Fn BN_set_word
return 1 on success, 0 otherwise.
.Fn BN_value_one
returns the constant.
.Fn BN_zero
never fails and returns no value.
.Sh BUGS
If a
.Vt BIGNUM
is equal to the value of all-bits-set, it will collide with the error
condition returned by
.Fn BN_get_word
which uses that as an error value.
.Pp
.Vt BN_ULONG
should probably be a typedef.
.Sh SEE ALSO
.Xr BN_bn2bin 3
.Sh HISTORY
In OpenSSL 0.9.8,
.Fn BN_zero
was changed to not return a value; previous versions returned an int.
.Sh COPYRIGHT
Copyright 2000-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
