.Dd 2025-09-30
.Dt BUF_MEM_NEW 3ossl
.Os
.Sh NAME
.Nm BUF_MEM_new ,
.Nm BUF_MEM_new_ex ,
.Nm BUF_MEM_free ,
.Nm BUF_MEM_grow ,
.Nm BUF_MEM_grow_clean ,
.Nm BUF_reverse
.Nd simple character array structure
.Sh SYNOPSIS
.In openssl/buffer.h
.Ft BUF_MEM *
.Fo BUF_MEM_new
.Fa void
.Fc
.Ft BUF_MEM *
.Fo BUF_MEM_new_ex
.Fa "unsigned long flags"
.Fc
.Ft void
.Fo BUF_MEM_free
.Fa "BUF_MEM *a"
.Fc
.Ft int
.Fo BUF_MEM_grow
.Fa "BUF_MEM *str"
.Fa "int len"
.Fc
.Ft size_t
.Fo BUF_MEM_grow_clean
.Fa "BUF_MEM *str"
.Fa "size_t len"
.Fc
.Ft void
.Fo BUF_reverse
.Fa "unsigned char *out"
.Fa "const unsigned char *in"
.Fa "size_t size"
.Fc
.Sh DESCRIPTION
The buffer library handles simple character arrays.
Buffers are used for various purposes in the library, most notably
memory BIOs.
.Pp
.Fn BUF_MEM_new
allocates a new buffer of zero size.
.Pp
.Fn BUF_MEM_new_ex
allocates a buffer with the specified flags.
The flag
.Sy BUF_MEM_FLAG_SECURE
specifies that the
.Sy data
pointer should be allocated on the secure heap; see
.Xr CRYPTO_secure_malloc 3 .
.Pp
.Fn BUF_MEM_free
frees up an already existing buffer.
The data is zeroed before freeing up in case the buffer contains
sensitive data.
If the argument is NULL, nothing is done.
.Pp
.Fn BUF_MEM_grow
changes the size of an already existing buffer to
.Fa len .
Any data already in the buffer is preserved if it increases in size.
.Pp
.Fn BUF_MEM_grow_clean
is similar to
.Fn BUF_MEM_grow
but it sets any free'd or additionally-allocated memory to zero.
.Pp
.Fn BUF_reverse
reverses
.Fa size
bytes at
.Fa in
into
.Fa out .
If
.Fa in
is NULL, the array is reversed in-place.
.Sh RETURN VALUES
.Fn BUF_MEM_new
returns the buffer or NULL on error.
.Pp
.Fn BUF_MEM_free
has no return value.
.Pp
.Fn BUF_MEM_grow
and
.Fn BUF_MEM_grow_clean
return zero on error or the new size (i.e.,
.Fa len Ns ).
.Sh SEE ALSO
.Xr bio 7 ,
.Xr CRYPTO_secure_malloc 3 .
.Sh HISTORY
The
.Fn BUF_MEM_new_ex
function was added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
