.Dd 2025-09-30
.Dt CMS_GET1_RECEIPTREQUEST 3ossl
.Os
.Sh NAME
.Nm CMS_ReceiptRequest_create0_ex ,
.Nm CMS_ReceiptRequest_create0 ,
.Nm CMS_add1_ReceiptRequest ,
.Nm CMS_get1_ReceiptRequest ,
.Nm CMS_ReceiptRequest_get0_values
.Nd CMS signed receipt request functions
.Sh SYNOPSIS
.In openssl/cms.h
.Ft CMS_ReceiptRequest *
.Fo CMS_ReceiptRequest_create0_ex
.Fa "      unsigned char *id"
.Fa "int idlen"
.Fa "int allorfirst"
.Fa "STACK_OF(GENERAL_NAMES) *receiptList"
.Fa "STACK_OF(GENERAL_NAMES) *receiptsTo"
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft CMS_ReceiptRequest *
.Fo CMS_ReceiptRequest_create0
.Fa "      unsigned char *id"
.Fa "int idlen"
.Fa "int allorfirst"
.Fa "STACK_OF(GENERAL_NAMES) *receiptList"
.Fa "STACK_OF(GENERAL_NAMES) *receiptsTo"
.Fc
.Ft int
.Fo CMS_add1_ReceiptRequest
.Fa "CMS_SignerInfo *si"
.Fa "CMS_ReceiptRequest *rr"
.Fc
.Ft int
.Fo CMS_get1_ReceiptRequest
.Fa "CMS_SignerInfo *si"
.Fa "CMS_ReceiptRequest **prr"
.Fc
.Ft void
.Fo CMS_ReceiptRequest_get0_values
.Fa "CMS_ReceiptRequest *rr"
.Fa "ASN1_STRING **pcid"
.Fa "int *pallorfirst"
.Fa "STACK_OF(GENERAL_NAMES) **plist"
.Fa "STACK_OF(GENERAL_NAMES) **prto"
.Fc
.Sh DESCRIPTION
.Fn CMS_ReceiptRequest_create0_ex
creates a signed receipt request structure.
The
.Sy signedContentIdentifier
field is set using
.Fa id
and
.Fa idlen ,
or it is set to 32 bytes of pseudo random data if
.Fa id
is NULL. If
.Fa receiptList
is NULL the allOrFirstTier option in
.Em receiptsFrom
is used and set to the value of the
.Fa allorfirst
parameter.
If
.Fa receiptList
is not NULL the
.Fa receiptList
option in
.Em receiptsFrom
is used.
The
.Fa receiptsTo
parameter specifies the
.Fa receiptsTo
field value.
The library context
.Fa libctx
is used to find the public random generator.
.Pp
.Fn CMS_ReceiptRequest_create0
is similar to
.Fn CMS_ReceiptRequest_create0_ex
but uses default values of NULL for the library context
.Fa libctx .
.Pp
The
.Fn CMS_add1_ReceiptRequest
function adds a signed receipt request
.Fa rr
to SignerInfo structure
.Fa si .
.Pp
int
.Fn CMS_get1_ReceiptRequest
looks for a signed receipt request in
.Fa si ,
if any is found it is decoded and written to
.Fa prr .
.Pp
.Fn CMS_ReceiptRequest_get0_values
retrieves the values of a receipt request.
The signedContentIdentifier is copied to
.Fa pcid .
If the
.Sy allOrFirstTier
option of
.Sy receiptsFrom
is used its value is copied to
.Fa pallorfirst
otherwise the
.Fa receiptList
field is copied to
.Fa plist .
The
.Fa receiptsTo
parameter is copied to
.Fa prto .
.Sh NOTES
For more details of the meaning of the fields see RFC2634.
.Pp
The contents of a signed receipt should only be considered meaningful if
the corresponding CMS_ContentInfo structure can be successfully verified
using
.Xr CMS_verify 3 .
.Sh RETURN VALUES
.Fn CMS_ReceiptRequest_create0_ex
and
.Fn CMS_ReceiptRequest_create0
return a signed receipt request structure or NULL if an error occurred.
.Pp
.Fn CMS_add1_ReceiptRequest
returns 1 for success or 0 if an error occurred.
.Pp
.Fn CMS_get1_ReceiptRequest
returns 1 is a signed receipt request is found and decoded.
It returns 0 if a signed receipt request is not present and -1 if it is
present but malformed.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_sign 3 ,
.Xr CMS_sign_receipt 3 ,
.Xr CMS_verify 3
.Xr CMS_verify_receipt 3
.Sh HISTORY
The function
.Fn CMS_ReceiptRequest_create0_ex
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2008-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
