.Dd 2025-09-30
.Dt CMS_DIGEST_CREATE 3ossl
.Os
.Sh NAME
.Nm CMS_digest_create_ex ,
.Nm CMS_digest_create
.Nd Create CMS DigestedData object
.Sh SYNOPSIS
.In openssl/cms.h
.Ft CMS_ContentInfo *
.Fo CMS_digest_create_ex
.Fa "BIO *in"
.Fa "const EVP_MD *md"
.Fa "unsigned int flags"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Ft CMS_ContentInfo *
.Fo CMS_digest_create
.Fa "BIO *in"
.Fa "const EVP_MD *md"
.Fa "unsigned int flags"
.Fc
.Sh DESCRIPTION
.Fn CMS_digest_create_ex
creates a
.Vt CMS_ContentInfo
structure with a type
.Sy NID_pkcs7_digest .
The data supplied via the
.Fa in
BIO is digested using
.Fa md .
The library context
.Em libctx
and the property query
.Fa propq
are used when retrieving algorithms from providers.
The
.Fa flags
field supports the
.Sy CMS_DETACHED
and
.Sy CMS_STREAM
flags, Internally
.Xr CMS_final 3
is called unless
.Sy CMS_STREAM
is specified.
.Pp
The
.Vt CMS_ContentInfo
structure can be freed using
.Xr CMS_ContentInfo_free 3 .
.Pp
.Fn CMS_digest_create
is similar to
.Fn CMS_digest_create_ex
but uses default values of NULL for the library context
.Em libctx
and the property query
.Fa propq .
.Sh RETURN VALUES
If the allocation fails,
.Fn CMS_digest_create_ex
and
.Fn CMS_digest_create
return NULL and set an error code that can be obtained by
.Xr ERR_get_error 3 .
Otherwise they return a pointer to the newly allocated structure.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_final 3 Ns >
.Sh HISTORY
The
.Fn CMS_digest_create_ex
method was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
