.Dd 2025-09-30
.Dt CMS_COMPRESS 3ossl
.Os
.Sh NAME
.Nm CMS_compress
.Nd create a CMS CompressedData structure
.Sh SYNOPSIS
.In openssl/cms.h
.Ft CMS_ContentInfo *
.Fo CMS_compress
.Fa "BIO *in"
.Fa "int comp_nid"
.Fa "unsigned int flags"
.Fc
.Sh DESCRIPTION
.Fn CMS_compress
creates and returns a CMS CompressedData structure.
.Fa comp_nid
is the compression algorithm to use or
.Sy NID_undef
to use the default algorithm (zlib compression).
.Fa in
is the content to be compressed.
.Fa flags
is an optional set of flags.
.Pp
The only currently supported compression algorithm is zlib using the NID
NID_zlib_compression.
.Pp
If zlib support is not compiled into OpenSSL then
.Fn CMS_compress
will return an error.
.Pp
If the
.Sy CMS_TEXT
flag is set MIME headers for type
.Sy text/plain
are prepended to the data.
.Pp
Normally the supplied content is translated into MIME canonical format
(as required by the S/MIME specifications) if
.Sy CMS_BINARY
is set no translation occurs.
This option should be used if the supplied data is in binary format
otherwise the translation will corrupt it.
If
.Sy CMS_BINARY
is set then
.Sy CMS_TEXT
is ignored.
.Pp
If the
.Sy CMS_STREAM
flag is set a partial
.Vt CMS_ContentInfo
structure is returned suitable for streaming I/O: no data is read from
the BIO
.Fa in .
.Pp
The compressed data is included in the CMS_ContentInfo structure, unless
.Sy CMS_DETACHED
is set in which case it is omitted.
This is rarely used in practice and is not supported by
.Xr SMIME_write_CMS 3 .
.Pp
If the flag
.Sy CMS_STREAM
is set the returned
.Vt CMS_ContentInfo
structure is
.Sy not
complete and outputting its contents via a function that does not
properly finalize the
.Vt CMS_ContentInfo
structure will give unpredictable results.
.Pp
Several functions including
.Xr SMIME_write_CMS 3 ,
.Xr i2d_CMS_bio_stream 3 ,
.Xr PEM_write_bio_CMS_stream 3
finalize the structure.
Alternatively finalization can be performed by obtaining the streaming
ASN1
.Vt BIO
directly using
.Xr BIO_new_CMS 3 .
.Pp
Additional compression parameters such as the zlib compression level
cannot currently be set.
.Sh RETURN VALUES
.Fn CMS_compress
returns either a CMS_ContentInfo structure or NULL if an error occurred.
The error can be obtained from ERR_get_error(3).
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_uncompress 3
.Sh HISTORY
The
.Sy CMS_STREAM
flag was added in OpenSSL 1.0.0.
.Sh COPYRIGHT
Copyright 2008-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
