.Dd 2025-09-30
.Dt CMS_GET0_RECIPIENTINFOS 3ossl
.Os
.Sh NAME
.Nm CMS_get0_RecipientInfos ,
.Nm CMS_RecipientInfo_type ,
.Nm CMS_RecipientInfo_ktri_get0_signer_id ,
.Nm CMS_RecipientInfo_ktri_cert_cmp ,
.Nm CMS_RecipientInfo_set0_pkey ,
.Nm CMS_RecipientInfo_kekri_get0_id ,
.Nm CMS_RecipientInfo_kari_set0_pkey_and_peer ,
.Nm CMS_RecipientInfo_kari_set0_pkey ,
.Nm CMS_RecipientInfo_kekri_id_cmp ,
.Nm CMS_RecipientInfo_set0_key ,
.Nm CMS_RecipientInfo_decrypt ,
.Nm CMS_RecipientInfo_encrypt
.Nd CMS envelopedData RecipientInfo routines
.Sh SYNOPSIS
.In openssl/cms.h
.Bd -literal
 STACK_OF(CMS_RecipientInfo) *CMS_get0_RecipientInfos(CMS_ContentInfo *cms);
 int CMS_RecipientInfo_type(CMS_RecipientInfo *ri);
.Ed
.Ft int
.Fo CMS_RecipientInfo_ktri_get0_signer_id
.Fa "CMS_RecipientInfo *ri"
.Fa "ASN1_OCTET_STRING **keyid"
.Fa "X509_NAME **issuer"
.Fa "ASN1_INTEGER **sno"
.Fc
.Ft int
.Fo CMS_RecipientInfo_ktri_cert_cmp
.Fa "CMS_RecipientInfo *ri"
.Fa "X509 *cert"
.Fc
.Ft int
.Fo CMS_RecipientInfo_set0_pkey
.Fa "CMS_RecipientInfo *ri"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft int
.Fo CMS_RecipientInfo_kari_set0_pkey_and_peer
.Fa "CMS_RecipientInfo *ri"
.Fa "EVP_PKEY *pk"
.Fa "X509 *peer"
.Fc
.Ft int
.Fo CMS_RecipientInfo_kari_set0_pkey
.Fa "CMS_RecipientInfo *ri"
.Fa "EVP_PKEY *pk"
.Fc
.Ft int
.Fo CMS_RecipientInfo_kekri_get0_id
.Fa "CMS_RecipientInfo *ri"
.Fa "X509_ALGOR **palg"
.Fa "ASN1_OCTET_STRING **pid"
.Fa "ASN1_GENERALIZEDTIME **pdate"
.Fa "ASN1_OBJECT **potherid"
.Fa "ASN1_TYPE **pothertype"
.Fc
.Ft int
.Fo CMS_RecipientInfo_kekri_id_cmp
.Fa "CMS_RecipientInfo *ri"
.Fa "const unsigned char *id"
.Fa "size_t idlen"
.Fc
.Ft int
.Fo CMS_RecipientInfo_set0_key
.Fa "CMS_RecipientInfo *ri"
.Fa "unsigned char *key"
.Fa "size_t keylen"
.Fc
.Ft int
.Fo CMS_RecipientInfo_decrypt
.Fa "CMS_ContentInfo *cms"
.Fa "CMS_RecipientInfo *ri"
.Fc
.Ft int
.Fo CMS_RecipientInfo_encrypt
.Fa "CMS_ContentInfo *cms"
.Fa "CMS_RecipientInfo *ri"
.Fc
.Sh DESCRIPTION
The function
.Xr CMS_get0_RecipientInfos 3
returns all the CMS_RecipientInfo structures associated with a CMS
EnvelopedData structure.
.Pp
.Xr CMS_RecipientInfo_type 3
returns the type of CMS_RecipientInfo structure
.Fa ri .
It will currently return CMS_RECIPINFO_TRANS, CMS_RECIPINFO_AGREE,
CMS_RECIPINFO_KEK, CMS_RECIPINFO_PASS, or CMS_RECIPINFO_OTHER.
.Pp
.Fn CMS_RecipientInfo_ktri_get0_signer_id
retrieves the certificate recipient identifier associated with a
specific CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_TRANS. Either the keyidentifier will
be set in
.Fa keyid
or
.Sy both
issuer name and serial number in
.Fa issuer
and
.Fa sno .
.Pp
.Fn CMS_RecipientInfo_ktri_cert_cmp
compares the certificate
.Fa cert
against the CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_TRANS. It returns zero if the
comparison is successful and non zero if not.
.Pp
.Fn CMS_RecipientInfo_set0_pkey
associates the private key
.Fa pkey
with the CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_TRANS.
.Pp
.Fn CMS_RecipientInfo_kari_set0_pkey_and_peer
associates the private key
.Fa pkey
and peer certificate
.Fa peer
with the CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_AGREE.
.Pp
.Fn CMS_RecipientInfo_kari_set0_pkey
associates the private key
.Fa pkey
with the CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_AGREE.
.Pp
.Fn CMS_RecipientInfo_kekri_get0_id
retrieves the key information from the CMS_RecipientInfo structure
.Fa ri
which must be of type CMS_RECIPINFO_KEK. Any of the remaining parameters
can be NULL if the application is not interested in the value of a
field.
Where a field is optional and absent NULL will be written to the
corresponding parameter.
The keyEncryptionAlgorithm field is written to
.Fa palg ,
the
.Sy keyIdentifier
field is written to
.Fa pid ,
the
.Sy date
field if present is written to
.Fa pdate ,
if the
.Sy other
field is present the components
.Sy keyAttrId
and
.Sy keyAttr
are written to parameters
.Fa potherid
and
.Fa pothertype .
.Pp
.Fn CMS_RecipientInfo_kekri_id_cmp
compares the ID in the
.Fa id
and
.Fa idlen
parameters against the
.Sy keyIdentifier
CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_KEK. It returns zero if the
comparison is successful and non zero if not.
.Pp
.Fn CMS_RecipientInfo_set0_key
associates the symmetric key
.Fa key
of length
.Fa keylen
with the CMS_RecipientInfo structure
.Fa ri ,
which must be of type CMS_RECIPINFO_KEK.
.Pp
.Fn CMS_RecipientInfo_decrypt
attempts to decrypt CMS_RecipientInfo structure
.Fa ri
in structure
.Fa cms .
A key must have been associated with the structure first.
.Pp
.Fn CMS_RecipientInfo_encrypt
attempts to encrypt CMS_RecipientInfo structure
.Fa ri
in structure
.Fa cms .
A key must have been associated with the structure first and the content
encryption key must be available: for example by a previous call to
.Fn CMS_RecipientInfo_decrypt .
.Sh NOTES
The main purpose of these functions is to enable an application to
lookup recipient keys using any appropriate technique when the simpler
method of
.Xr CMS_decrypt 3
is not appropriate.
.Pp
In typical usage and application will retrieve all CMS_RecipientInfo
structures using
.Xr CMS_get0_RecipientInfos 3
and check the type of each using
.Xr CMS_RecipientInfo_type 3 .
Depending on the type the CMS_RecipientInfo structure can be ignored or
its key identifier data retrieved using an appropriate function.
Then if the corresponding secret or private key can be obtained by any
appropriate means it can then associated with the structure and
.Fn CMS_RecipientInfo_decrypt
called.
If successful
.Xr CMS_decrypt 3
can be called with a NULL key to decrypt the enveloped content.
.Pp
The
.Fn CMS_RecipientInfo_encrypt
can be used to add a new recipient to an existing enveloped data
structure.
Typically an application will first decrypt an appropriate
CMS_RecipientInfo structure to make the content encrypt key available,
it will then add a new recipient using a function such as
.Xr CMS_add1_recipient_cert 3
and finally encrypt the content encryption key using
.Fn CMS_RecipientInfo_encrypt .
.Sh RETURN VALUES
.Xr CMS_get0_RecipientInfos 3
returns all CMS_RecipientInfo structures, or NULL if an error occurs.
.Pp
.Fn CMS_RecipientInfo_ktri_get0_signer_id ,
.Fn CMS_RecipientInfo_set0_pkey ,
.Fn CMS_RecipientInfo_kekri_get0_id ,
.Fn CMS_RecipientInfo_set0_key
and
.Fn CMS_RecipientInfo_decrypt
return 1 for success or 0 if an error occurs.
.Fn CMS_RecipientInfo_encrypt
return 1 for success or 0 if an error occurs.
.Pp
.Fn CMS_RecipientInfo_ktri_cert_cmp
and
.Xr CMS_RecipientInfo_kekri_cmp 3
return 0 for a successful comparison and non zero otherwise.
.Pp
Any error can be obtained from
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_decrypt 3
.Sh HISTORY
.Sy CMS_RecipientInfo_kari_set0_pkey_and_peer
and
.Sy CMS_RecipientInfo_kari_set0_pkey
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2008-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
