.Dd 2025-09-30
.Dt CMS_DECRYPT 3ossl
.Os
.Sh NAME
.Nm CMS_decrypt ,
.Nm CMS_decrypt_set1_pkey_and_peer ,
.Nm CMS_decrypt_set1_pkey ,
.Nm CMS_decrypt_set1_password
.Nd decrypt content from a CMS envelopedData structure
.Sh SYNOPSIS
.In openssl/cms.h
.Ft int
.Fo CMS_decrypt
.Fa "CMS_ContentInfo *cms"
.Fa "EVP_PKEY *pkey"
.Fa "X509 *cert"
.Fa "BIO *dcont"
.Fa "BIO *out"
.Fa "unsigned int flags"
.Fc
.Ft int
.Fo CMS_decrypt_set1_pkey_and_peer
.Fa "CMS_ContentInfo *cms"
.Fa "EVP_PKEY *pk"
.Fa "X509 *cert"
.Fa "X509 *peer"
.Fc
.Ft int
.Fo CMS_decrypt_set1_pkey
.Fa "CMS_ContentInfo *cms"
.Fa "EVP_PKEY *pk"
.Fa "X509 *cert"
.Fc
.Ft int
.Fo CMS_decrypt_set1_password
.Fa "CMS_ContentInfo *cms"
.Fa "unsigned char *pass"
.Fa "ossl_ssize_t passlen"
.Fc
.Sh DESCRIPTION
.Fn CMS_decrypt
extracts the decrypted content from a CMS EnvelopedData or
AuthEnvelopedData structure.
It uses
.Fn CMS_decrypt_set1_pkey
to decrypt the content with the recipient private key
.Fa pkey
if
.Fa pkey
is not NULL. In this case, the associated certificate is recommended to
provide in
.Fa cert
- see the NOTES below.
.Fa out
is a BIO to write the content to and
.Fa flags
is an optional set of flags.
If
.Fa pkey
is NULL the function assumes that decryption was already done (e.g.,
using
.Fn CMS_decrypt_set1_pkey
or
.Fn CMS_decrypt_set1_password )
and just provides the content unless
.Fa cert ,
.Fa dcont ,
and
.Fa out
are NULL as well.
The
.Fa dcont
parameter is used in the rare case where the encrypted content is
detached.
It will normally be set to NULL.
.Pp
.Fn CMS_decrypt_set1_pkey_and_peer
decrypts the CMS_ContentInfo structure
.Fa cms
using the private key
.Fa pkey ,
the corresponding certificate
.Fa cert ,
which is recommended but may be NULL, and the (optional) originator
certificate
.Fa peer .
On success, it also records in
.Fa cms
the decryption key
.Fa pkey ,
and then should be followed by
.Qo Li CMS_decrypt(cms, NULL, NULL, dcont, out, flags) Qc .
This call deallocates any decryption key stored in
.Fa cms .
.Pp
.Fn CMS_decrypt_set1_pkey
is the same as
.Fn CMS_decrypt_set1_pkey_and_peer
with
.Fa peer
being NULL.
.Pp
.Fn CMS_decrypt_set1_password
decrypts the CMS_ContentInfo structure
.Fa cms
using the secret
.Fa pass
of length
.Fa passlen .
On success, it also records in
.Fa cms
the decryption key used, and then should be followed by
.Qo Li CMS_decrypt(cms, NULL, NULL, dcont, out, flags) Qc .
This call deallocates any decryption key stored in
.Fa cms .
.Sh NOTES
Although the recipients certificate is not needed to decrypt the data it
is needed to locate the appropriate (of possible several) recipients in
the CMS structure.
.Pp
If
.Fa cert
is set to NULL all possible recipients are tried.
This case however is problematic.
To thwart the MMA attack (Bleichenbacher's attack on PKCS #1 v1.5 RSA
padding) all recipients are tried whether they succeed or not.
If no recipient succeeds then a random symmetric key is used to decrypt
the content: this will typically output garbage and may (but is not
guaranteed to) ultimately return a padding error only.
If
.Fn CMS_decrypt
just returned an error when all recipient encrypted keys failed to
decrypt an attacker could use this in a timing attack.
If the special flag
.Sy CMS_DEBUG_DECRYPT
is set then the above behaviour is modified and an error
.Sy is
returned if no recipient encrypted key can be decrypted
.Sy without
generating a random content encryption key.
Applications should use this flag with
.Sy extreme caution
especially in automated gateways as it can leave them open to attack.
.Pp
It is possible to determine the correct recipient key by other means
(for example looking them up in a database) and setting them in the CMS
structure in advance using the CMS utility functions such as
.Xr CMS_set1_pkey 3 ,
or use
.Fn CMS_decrypt_set1_password
if the recipient has a symmetric key.
In these cases both
.Fa cert
and
.Fa pkey
should be set to NULL.
.Pp
To process KEKRecipientInfo types
.Xr CMS_set1_key 3
or
.Xr CMS_RecipientInfo_set0_key 3
and
.Xr CMS_RecipientInfo_decrypt 3
should be called before
.Fn CMS_decrypt
and
.Fa cert
and
.Fa pkey
set to NULL.
.Pp
The following flags can be passed in the
.Fa flags
parameter.
.Pp
If the
.Sy CMS_TEXT
flag is set MIME headers for type
.Qo Li text/plain Qc
are deleted from the content.
If the content is not of type
.Qo Li text/plain Qc
then an error is returned.
.Sh RETURN VALUES
.Fn CMS_decrypt ,
.Fn CMS_decrypt_set1_pkey_and_peer ,
.Fn CMS_decrypt_set1_pkey ,
and
.Fn CMS_decrypt_set1_password
return either 1 for success or 0 for failure.
The error can be obtained from ERR_get_error(3).
.Sh BUGS
The
.Sy set1_
part of these function names is misleading and should better read:
.Sy with_ .
.Pp
The lack of single pass processing and the need to hold all data in
memory as mentioned in
.Xr CMS_verify 3
also applies to
.Fn CMS_decrypt .
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_encrypt 3
.Sh HISTORY
.Fn CMS_decrypt_set1_pkey_and_peer
and
.Fn CMS_decrypt_set1_password
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2008-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
