.Dd 2025-09-30
.Dt CMS_ENCRYPTEDDATA_ENCRYPT 3ossl
.Os
.Sh NAME
.Nm CMS_EncryptedData_encrypt_ex ,
.Nm CMS_EncryptedData_encrypt
.Nd Create CMS EncryptedData
.Sh SYNOPSIS
.In openssl/cms.h
.Ft CMS_ContentInfo *
.Fo CMS_EncryptedData_encrypt_ex
.Fa "BIO *in"
.Fa "const EVP_CIPHER *cipher"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "unsigned int flags"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Ft CMS_ContentInfo *
.Fo CMS_EncryptedData_encrypt
.Fa "BIO *in"
.Fa "const EVP_CIPHER *cipher"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "unsigned int flags"
.Fc
.Sh DESCRIPTION
.Fn CMS_EncryptedData_encrypt_ex
creates a
.Vt CMS_ContentInfo
structure with a type
.Sy NID_pkcs7_encrypted .
.Fa in
is a BIO containing the data to encrypt using
.Fa cipher
and the encryption key
.Fa key
of size
.Fa keylen
bytes.
The library context
.Em libctx
and the property query
.Fa propq
are used when retrieving algorithms from providers.
.Fa flags
is a set of optional flags.
.Pp
The
.Fa flags
field supports the options
.Sy CMS_DETACHED ,
.Sy CMS_STREAM
and
.Sy CMS_PARTIAL .
Internally
.Xr CMS_final 3
is called unless
.Sy CMS_STREAM
and/or
.Sy CMS_PARTIAL
is specified.
.Pp
The algorithm passed in the
.Fa cipher
parameter must support ASN1 encoding of its parameters.
.Pp
The
.Vt CMS_ContentInfo
structure can be freed using
.Xr CMS_ContentInfo_free 3 .
.Pp
.Fn CMS_EncryptedData_encrypt
is similar to
.Fn CMS_EncryptedData_encrypt_ex
but uses default values of NULL for the library context
.Em libctx
and the property query
.Fa propq .
.Sh RETURN VALUES
If the allocation fails,
.Fn CMS_EncryptedData_encrypt_ex
and
.Fn CMS_EncryptedData_encrypt
return NULL and set an error code that can be obtained by
.Xr ERR_get_error 3 .
Otherwise they return a pointer to the newly allocated structure.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_final 3 ,
.Xr CMS_EncryptedData_decrypt 3
.Sh HISTORY
The
.Fn CMS_EncryptedData_encrypt_ex
method was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
