.Dd 2025-09-30
.Dt CRYPTO_THREAD_RUN_ONCE 3ossl
.Os
.Sh NAME
.Nm CRYPTO_THREAD_run_once ,
.Nm CRYPTO_THREAD_lock_new ,
.Nm CRYPTO_THREAD_read_lock ,
.Nm CRYPTO_THREAD_write_lock ,
.Nm CRYPTO_THREAD_unlock ,
.Nm CRYPTO_THREAD_lock_free ,
.Nm CRYPTO_atomic_add ,
.Nm CRYPTO_atomic_add64 ,
.Nm CRYPTO_atomic_and ,
.Nm CRYPTO_atomic_or ,
.Nm CRYPTO_atomic_load ,
.Nm CRYPTO_atomic_store ,
.Nm CRYPTO_atomic_load_int ,
.Nm OSSL_set_max_threads ,
.Nm OSSL_get_max_threads ,
.Nm OSSL_get_thread_support_flags ,
.Nm OSSL_THREAD_SUPPORT_FLAG_THREAD_POOL ,
.Nm OSSL_THREAD_SUPPORT_FLAG_DEFAULT_SPAWN
.Nd OpenSSL thread support
.Sh SYNOPSIS
.In openssl/crypto.h
.Ft CRYPTO_ONCE CRYPTO_ONCE_STATIC_INIT;
 int
.Fo CRYPTO_THREAD_run_once
.Fa "CRYPTO_ONCE *once"
.Fa "void (*init)(void)"
.Fc
.Ft CRYPTO_RWLOCK *
.Fo CRYPTO_THREAD_lock_new
.Fa void
.Fc
.Ft int
.Fo CRYPTO_THREAD_read_lock
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_THREAD_write_lock
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_THREAD_unlock
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft void
.Fo CRYPTO_THREAD_lock_free
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_add
.Fa "int *val"
.Fa "int amount"
.Fa "int *ret"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_add64
.Fa "uint64_t *val"
.Fa "uint64_t op"
.Fa "uint64_t *ret"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_and
.Fa "uint64_t *val"
.Fa "uint64_t op"
.Fa "uint64_t *ret"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_or
.Fa "uint64_t *val"
.Fa "uint64_t op"
.Fa "uint64_t *ret"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_load
.Fa "uint64_t *val"
.Fa "uint64_t *ret"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_store
.Fa "uint64_t *dst"
.Fa "uint64_t val"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo CRYPTO_atomic_load_int
.Fa "int *val"
.Fa "int *ret"
.Fa "CRYPTO_RWLOCK *lock"
.Fc
.Ft int
.Fo OSSL_set_max_threads
.Fa "OSSL_LIB_CTX *ctx"
.Fa "uint64_t max_threads"
.Fc
.Ft uint64_t
.Fo OSSL_get_max_threads
.Fa "OSSL_LIB_CTX *ctx"
.Fc
.Ft uint32_t
.Fo OSSL_get_thread_support_flags
.Fa void
.Fc
.Fd #define OSSL_THREAD_SUPPORT_FLAG_THREAD_POOL
.Fd #define OSSL_THREAD_SUPPORT_FLAG_DEFAULT_SPAWN
.Sh DESCRIPTION
OpenSSL can be safely used in multi-threaded applications provided that
support for the underlying OS threading API is built-in.
Currently, OpenSSL supports the pthread and Windows APIs.
OpenSSL can also be built without any multi-threading support, for
example on platforms that don't provide any threading support or that
provide a threading API that is not yet supported by OpenSSL.
.Pp
The following multi-threading function are provided:
.Bl -bullet
.It
.Fn CRYPTO_THREAD_run_once
can be used to perform one-time initialization.
The
.Fa once
argument must be a pointer to a static object of type
.Vt CRYPTO_ONCE
that was statically initialized to the value
.Sy CRYPTO_ONCE_STATIC_INIT .
The
.Em init
argument is a pointer to a function that performs the desired exactly
once initialization.
In particular, this can be used to allocate locks in a thread-safe
manner, which can then be used with the locking functions below.
.It
.Fn CRYPTO_THREAD_lock_new
allocates, initializes and returns a new read/write lock.
.It
.Fn CRYPTO_THREAD_read_lock
locks the provided
.Fa lock
for reading.
.It
.Fn CRYPTO_THREAD_write_lock
locks the provided
.Fa lock
for writing.
.It
.Fn CRYPTO_THREAD_unlock
unlocks the previously locked
.Fa lock .
.It
.Fn CRYPTO_THREAD_lock_free
frees the provided
.Fa lock .
If the argument is NULL, nothing is done.
.It
.Fn CRYPTO_atomic_add
atomically adds
.Fa amount
to
.Em *val
and returns the result of the operation in
.Em *ret .
.Fa lock
will be locked, unless atomic operations are supported on the specific
platform.
Because of this, if a variable is modified by
.Fn CRYPTO_atomic_add
then
.Fn CRYPTO_atomic_add
must be the only way that the variable is modified.
If atomic operations are not supported and
.Fa lock
is NULL, then the function will fail.
.It
.Fn CRYPTO_atomic_add64
atomically adds
.Fa op
to
.Em *val
and returns the result of the operation in
.Em *ret .
.Fa lock
will be locked, unless atomic operations are supported on the specific
platform.
Because of this, if a variable is modified by
.Fn CRYPTO_atomic_add64
then
.Fn CRYPTO_atomic_add64
must be the only way that the variable is modified.
If atomic operations are not supported and
.Fa lock
is NULL, then the function will fail.
.It
.Fn CRYPTO_atomic_and
performs an atomic bitwise and of
.Fa op
and
.Em *val
and stores the result back in
.Em *val .
It also returns the result of the operation in
.Em *ret .
.Fa lock
will be locked, unless atomic operations are supported on the specific
platform.
Because of this, if a variable is modified by
.Fn CRYPTO_atomic_and
or read by
.Fn CRYPTO_atomic_load
then
.Fn CRYPTO_atomic_and
must be the only way that the variable is modified.
If atomic operations are not supported and
.Fa lock
is NULL, then the function will fail.
.It
.Fn CRYPTO_atomic_or
performs an atomic bitwise or of
.Fa op
and
.Em *val
and stores the result back in
.Em *val .
It also returns the result of the operation in
.Em *ret .
.Fa lock
will be locked, unless atomic operations are supported on the specific
platform.
Because of this, if a variable is modified by
.Fn CRYPTO_atomic_or
or read by
.Fn CRYPTO_atomic_load
then
.Fn CRYPTO_atomic_or
must be the only way that the variable is modified.
If atomic operations are not supported and
.Fa lock
is NULL, then the function will fail.
.It
.Fn CRYPTO_atomic_load
atomically loads the contents of
.Em *val
into
.Em *ret .
.Fa lock
will be locked, unless atomic operations are supported on the specific
platform.
Because of this, if a variable is modified by
.Fn CRYPTO_atomic_or
or read by
.Fn CRYPTO_atomic_load
then
.Fn CRYPTO_atomic_load
must be the only way that the variable is read.
If atomic operations are not supported and
.Fa lock
is NULL, then the function will fail.
.It
.Fn CRYPTO_atomic_store
atomically stores the contents of
.Fa val
into
.Em *dst .
.Fa lock
will be locked, unless atomic operations are supported on the specific
platform.
.It
.Fn CRYPTO_atomic_load_int
works identically to
.Fn CRYPTO_atomic_load
but operates on an
.Vt int
value instead of a
.Vt uint64_t
value.
.It
.Fn OSSL_set_max_threads
sets the maximum number of threads to be used by the thread pool.
If the argument is 0, thread pooling is disabled.
OpenSSL will not create any threads and existing threads in the thread
pool will be torn down.
The maximum thread count is a limit, not a target.
Threads will not be spawned unless (and until) there is demand.
Thread polling is disabled by default.
To enable threading you must call
.Fn OSSL_set_max_threads
explicitly.
Under no circumstances is this done for you.
.It
.Fn OSSL_get_thread_support_flags
determines what thread pool functionality OpenSSL is compiled with and
is able to support in the current run time environment.
.Sy OSSL_THREAD_SUPPORT_FLAG_THREAD_POOL
indicates that the base thread pool functionality is available, and
.Sy OSSL_THREAD_SUPPORT_FLAG_DEFAULT_SPAWN
indicates that the default thread pool model is available.
The default thread pool model is currently the only model available,
therefore both of these flags must be set for thread pool functionality
to be used.
.El
.Sh RETURN VALUES
.Fn CRYPTO_THREAD_run_once
returns 1 on success, or 0 on error.
.Pp
.Fn CRYPTO_THREAD_lock_new
returns the allocated lock, or NULL on error.
.Pp
.Fn CRYPTO_THREAD_lock_free
returns no value.
.Pp
.Fn OSSL_set_max_threads
returns 1 on success and 0 on failure.
Returns failure if OpenSSL-managed thread pooling is not supported (for
example, if it is not supported on the current platform, or because
OpenSSL is not built with the necessary support).
.Pp
.Fn OSSL_get_max_threads
returns the maximum number of threads currently allowed to be used by
the thread pool.
If thread pooling is disabled or not available, returns 0.
.Pp
.Fn OSSL_get_thread_support_flags
returns zero or more
.Sy OSSL_THREAD_SUPPORT_FLAG
values.
.Pp
The other functions return 1 on success, or 0 on error.
.Sh NOTES
On Windows platforms the CRYPTO_THREAD_* types and functions in the
.Pa <openssl/crypto.h>
header are dependent on some of the types customarily made available by
including
.Pa <windows.h> .
The application developer is likely to require control over when the
latter is included, commonly as one of the first included headers.
Therefore, it is defined as an application developer's responsibility to
include
.Pa <windows.h>
prior to
.Pa <openssl/crypto.h>
where use of CRYPTO_THREAD_* types and functions is required.
.Sh EXAMPLES
You can find out if OpenSSL was configured with thread support:
.Bd -literal
 #include <openssl/opensslconf.h>
 #if defined(OPENSSL_THREADS)
     /* thread support enabled */
 #else
     /* no thread support */
 #endif
.Ed
.Pp
This example safely initializes and uses a lock.
.Bd -literal
 #ifdef _WIN32
 # include <windows.h>
 #endif
 #include <openssl/crypto.h>

 static CRYPTO_ONCE once = CRYPTO_ONCE_STATIC_INIT;
 static CRYPTO_RWLOCK *lock;

 static void myinit(void)
 {
     lock = CRYPTO_THREAD_lock_new();
 }

 static int mylock(void)
 {
     if (!CRYPTO_THREAD_run_once(&once, void init) || lock == NULL)
         return 0;
     return CRYPTO_THREAD_write_lock(lock);
 }

 static int myunlock(void)
 {
     return CRYPTO_THREAD_unlock(lock);
 }

 int serialized(void)
 {
     int ret = 0;

     if (!mylock()) {
        /* Do not unlock unless the lock was successfully acquired. */
        return 0;
     }

     /* Your code here, do not return without releasing the lock! */
     ret = ... ;
     myunlock();
     return ret;
 }
.Ed
.Pp
Finalization of locks is an advanced topic, not covered in this example.
This can only be done at process exit or when a dynamically loaded
library is no longer in use and is unloaded.
The simplest solution is to just "leak" the lock in applications and not
repeatedly load/unload shared libraries that allocate locks.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr openssl-threads 7 .
.Sh HISTORY
.Fn CRYPTO_atomic_load_int ,
.Fn OSSL_set_max_threads ,
.Fn OSSL_get_max_threads ,
.Fn OSSL_get_thread_support_flags
were added in OpenSSL 3.2.
.Pp
.Fn CRYPTO_atomic_store ,
.Fn CRYPTO_atomic_add64 ,
.Fn CRYPTO_atomic_and
were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
