.Dd 2025-09-30
.Dt CTLOG_NEW 3ossl
.Os
.Sh NAME
.Nm CTLOG_new_ex ,
.Nm CTLOG_new ,
.Nm CTLOG_new_from_base64 ,
.Nm CTLOG_new_from_base64_ex ,
.Nm CTLOG_free ,
.Nm CTLOG_get0_name ,
.Nm CTLOG_get0_log_id ,
.Nm CTLOG_get0_public_key
.Nd encapsulates information about a Certificate Transparency log
.Sh SYNOPSIS
.In openssl/ct.h
.Ft CTLOG *
.Fo CTLOG_new_ex
.Fa "EVP_PKEY *public_key"
.Fa "const char *name"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft CTLOG *
.Fo CTLOG_new
.Fa "EVP_PKEY *public_key"
.Fa "const char *name"
.Fc
.Ft int
.Fo CTLOG_new_from_base64_ex
.Fa "CTLOG **ct_log"
.Fa "const char *pkey_base64"
.Fa "const char *name"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo CTLOG_new_from_base64
.Fa "CTLOG ** ct_log"
.Fa "const char *pkey_base64"
.Fa "const char *name"
.Fc
.Ft void
.Fo CTLOG_free
.Fa "CTLOG *log"
.Fc
.Ft const char *
.Fo CTLOG_get0_name
.Fa "const CTLOG *log"
.Fc
.Ft void
.Fo CTLOG_get0_log_id
.Fa "const CTLOG *log"
.Fa "const uint8_t **log_id"
.Fa "size_t *log_id_len"
.Fc
.Ft EVP_PKEY *
.Fo CTLOG_get0_public_key
.Fa "const CTLOG *log"
.Fc
.Sh DESCRIPTION
.Fn CTLOG_new_ex
returns a new CTLOG that represents the Certificate Transparency (CT)
log with the given public key and associates it with the library context
.Fa libctx
and property query string
.Fa propq .
A name must also be provided that can be used to help users identify
this log.
Ownership of the public key is transferred.
.Pp
.Fn CTLOG_new
does the same thing as
.Fn CTLOG_new_ex
but with the default library context and the default property query
string.
.Pp
.Fn CTLOG_new_from_base64_ex
also creates a new CTLOG, but takes the public key in base64-encoded DER
form and sets the ct_log pointer to point to the new CTLOG. The base64
will be decoded and the public key parsed.
The CTLOG will be associated with the given library context
.Fa libctx
and property query string
.Fa propq .
.Pp
.Fn CTLOG_new_from_base64
does the same thing as
.Fn CTLOG_new_from_base64_ex
except that the default library context and property query string are
used.
.Pp
Regardless of whether
.Fn CTLOG_new
or
.Fn CTLOG_new_from_base64
is used, it is the caller's responsibility to pass the CTLOG to
.Fn CTLOG_free
once it is no longer needed.
This will delete it and, if created by
.Fn CTLOG_new ,
the EVP_PKEY that was passed to it.
If the argument to
.Fn CTLOG_free
is NULL, nothing is done.
.Pp
.Fn CTLOG_get0_name
returns the name of the log, as provided when the CTLOG was created.
Ownership of the string remains with the CTLOG.
.Pp
.Fn CTLOG_get0_log_id
sets *log_id to point to a string containing that log's LogID (see RFC
6962). It sets *log_id_len to the length of that LogID. For a v1 CT log,
the LogID will be a SHA-256 hash (i.e.
32 bytes long).
Ownership of the string remains with the CTLOG.
.Pp
.Fn CTLOG_get0_public_key
returns the public key of the CT log.
Ownership of the EVP_PKEY remains with the CTLOG.
.Sh RETURN VALUES
.Fn CTLOG_new
will return NULL if an error occurs.
.Pp
.Fn CTLOG_new_from_base64
will return 1 on success, 0 otherwise.
.Sh SEE ALSO
.Xr ct 7
.Sh HISTORY
The functions
.Fn CTLOG_new_ex
and
.Fn CTLOG_new_from_base64_ex
were added in OpenSSL 3.0. All other functions were added in OpenSSL
1.1.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
