.Dd 2025-09-30
.Dt D2I_RSAPRIVATEKEY 3ossl
.Os
.Sh NAME
.Nm d2i_DSAPrivateKey ,
.Nm d2i_DSAPrivateKey_bio ,
.Nm d2i_DSAPrivateKey_fp ,
.Nm d2i_DSAPublicKey ,
.Nm d2i_DSA_PUBKEY ,
.Nm d2i_DSA_PUBKEY_bio ,
.Nm d2i_DSA_PUBKEY_fp ,
.Nm d2i_DSAparams ,
.Nm d2i_RSAPrivateKey ,
.Nm d2i_RSAPrivateKey_bio ,
.Nm d2i_RSAPrivateKey_fp ,
.Nm d2i_RSAPublicKey ,
.Nm d2i_RSAPublicKey_bio ,
.Nm d2i_RSAPublicKey_fp ,
.Nm d2i_RSA_PUBKEY ,
.Nm d2i_RSA_PUBKEY_bio ,
.Nm d2i_RSA_PUBKEY_fp ,
.Nm d2i_DHparams ,
.Nm d2i_DHparams_bio ,
.Nm d2i_DHparams_fp ,
.Nm d2i_ECParameters ,
.Nm d2i_ECPrivateKey ,
.Nm d2i_ECPrivateKey_bio ,
.Nm d2i_ECPrivateKey_fp ,
.Nm d2i_EC_PUBKEY ,
.Nm d2i_EC_PUBKEY_bio ,
.Nm d2i_EC_PUBKEY_fp ,
.Nm i2d_RSAPrivateKey ,
.Nm i2d_RSAPrivateKey_bio ,
.Nm i2d_RSAPrivateKey_fp ,
.Nm i2d_RSAPublicKey ,
.Nm i2d_RSAPublicKey_bio ,
.Nm i2d_RSAPublicKey_fp ,
.Nm i2d_RSA_PUBKEY ,
.Nm i2d_RSA_PUBKEY_bio ,
.Nm i2d_RSA_PUBKEY_fp ,
.Nm i2d_DHparams ,
.Nm i2d_DHparams_bio ,
.Nm i2d_DHparams_fp ,
.Nm i2d_DSAPrivateKey ,
.Nm i2d_DSAPrivateKey_bio ,
.Nm i2d_DSAPrivateKey_fp ,
.Nm i2d_DSAPublicKey ,
.Nm i2d_DSA_PUBKEY ,
.Nm i2d_DSA_PUBKEY_bio ,
.Nm i2d_DSA_PUBKEY_fp ,
.Nm i2d_DSAparams ,
.Nm i2d_ECParameters ,
.Nm i2d_ECPrivateKey ,
.Nm i2d_ECPrivateKey_bio ,
.Nm i2d_ECPrivateKey_fp ,
.Nm i2d_EC_PUBKEY ,
.Nm i2d_EC_PUBKEY_bio ,
.Nm i2d_EC_PUBKEY_fp
.Nd DEPRECATED
.Sh SYNOPSIS
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft TYPE *
.Fo d2i_TYPEPrivateKey
.Fa "TYPE **a"
.Fa "const unsigned char **ppin"
.Fa "long length"
.Fc
.Ft TYPE *
.Fo d2i_TYPEPrivateKey_bio
.Fa "BIO *bp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPEPrivateKey_fp
.Fa "FILE *fp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPEPublicKey
.Fa "TYPE **a"
.Fa "const unsigned char **ppin"
.Fa "long length"
.Fc
.Ft TYPE *
.Fo d2i_TYPEPublicKey_bio
.Fa "BIO *bp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPEPublicKey_fp
.Fa "FILE *fp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPEparams
.Fa "TYPE **a"
.Fa "const unsigned char **ppin"
.Fa "long length"
.Fc
.Ft TYPE *
.Fo d2i_TYPEparams_bio
.Fa "BIO *bp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPEparams_fp
.Fa "FILE *fp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPE_PUBKEY
.Fa "TYPE **a"
.Fa "const unsigned char **ppin"
.Fa "long length"
.Fc
.Ft TYPE *
.Fo d2i_TYPE_PUBKEY_bio
.Fa "BIO *bp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPE_PUBKEY_fp
.Fa "FILE *fp"
.Fa "TYPE **a"
.Fc
.Ft int
.Fo i2d_TYPEPrivateKey
.Fa "const TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPEPrivateKey
.Fa "TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPEPrivateKey_fp
.Fa "FILE *fp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPrivateKey_fp
.Fa "FILE *fp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPrivateKey_bio
.Fa "BIO *bp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPrivateKey_bio
.Fa "BIO *bp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPublicKey
.Fa "const TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPEPublicKey
.Fa "TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPEPublicKey_fp
.Fa "FILE *fp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPublicKey_fp
.Fa "FILE *fp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPublicKey_bio
.Fa "BIO *bp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEPublicKey_bio
.Fa "BIO *bp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEparams
.Fa "const TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPEparams
.Fa "TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPEparams_fp
.Fa "FILE *fp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEparams_fp
.Fa "FILE *fp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEparams_bio
.Fa "BIO *bp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPEparams_bio
.Fa "BIO *bp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_PUBKEY
.Fa "const TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPE_PUBKEY
.Fa "TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPE_PUBKEY_fp
.Fa "FILE *fp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_PUBKEY_fp
.Fa "FILE *fp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_PUBKEY_bio
.Fa "BIO *bp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_PUBKEY_bio
.Fa "BIO *bp"
.Fa "TYPE *a"
.Fc
.Sh DESCRIPTION
All functions described here are deprecated.
Please use
.Xr OSSL_DECODER 3
instead of the
.Sy d2i
functions and
.Xr OSSL_ENCODER 3
instead of the
.Sy i2d
functions.
See
.Sx Migration
below.
.Pp
In the description here,
.Sy Vt TYPE
is used a placeholder for any of the OpenSSL datatypes, such as
.Sy RSA .
The function parameters
.Fa ppin
and
.Fa ppout
are generally either both named
.Em pp
in the headers, or
.Em in
and
.Em out .
.Pp
All the functions here behave the way that's described in
.Xr d2i_X509 3 .
.Pp
Please note that not all functions in the synopsis are available for all
key types.
For example, there are no
.Xr d2i_RSAparams 3
or
.Xr i2d_RSAparams 3 ,
because the PKCS#1
.Sy RSA
structure doesn't include any key parameters.
.Pp
.Sy d2i_ Ns Vt TYPE Ns PrivateKey Ns
.Xr 3
and derivates thereof decode DER encoded
.Sy Vt TYPE
private key data organized in a type specific structure.
.Pp
.Sy d2i_ Ns Vt TYPE Ns PublicKey Ns
.Xr 3
and derivates thereof decode DER encoded
.Sy Vt TYPE
public key data organized in a type specific structure.
.Pp
.Sy d2i_ Ns Vt TYPE Ns params Ns
.Xr 3
and derivates thereof decode DER encoded
.Sy Vt TYPE
key parameters organized in a type specific structure.
.Pp
.Sy d2i_ Ns Vt TYPE Ns _PUBKEY Ns
.Xr 3
and derivates thereof decode DER encoded
.Sy Vt TYPE
public key data organized in a
.Sy SubjectPublicKeyInfo
structure.
.Pp
.Sy i2d_ Ns Vt TYPE Ns PrivateKey Ns
.Xr 3
and derivates thereof encode the private key
.Sy Vt TYPE
data into a type specific DER encoded structure.
.Pp
.Sy i2d_ Ns Vt TYPE Ns PublicKey Ns
.Xr 3
and derivates thereof encode the public key
.Sy Vt TYPE
data into a type specific DER encoded structure.
.Pp
.Sy i2d_ Ns Vt TYPE Ns params Ns
.Xr 3
and derivates thereof encode the
.Sy Vt TYPE
key parameters data into a type specific DER encoded structure.
.Pp
.Sy i2d_ Ns Vt TYPE Ns _PUBKEY Ns
.Xr 3
and derivates thereof encode the public key
.Sy Vt TYPE
data into a DER encoded
.Sy SubjectPublicKeyInfo
structure.
.Pp
For example,
.Xr d2i_RSAPrivateKey 3
and
.Xr d2i_RSAPublicKey 3
expects the structure defined by PKCS#1. Similarly,
.Xr i2d_RSAPrivateKey 3
and
.Xr i2d_RSAPublicKey 3
produce DER encoded string organized according to PKCS#1.
.Ss Migration
Migration from the diverse
.Sy Vt TYPE Ns s
requires using corresponding new OpenSSL types.
For all
.Sy Vt TYPE Ns s
described here, the corresponding new type is
.Sy EVP_PKEY .
The rest of this section assumes that this has been done, exactly how to
do that is described elsewhere.
.Pp
There are two migration paths:
.Bl -bullet
.It
Replace
.Pf b<d2i_ Vt TYPE Ns PrivateKey()>
with
.Xr d2i_PrivateKey 3 ,
.Pf b<d2i_ Vt TYPE Ns PublicKey()>
with
.Xr d2i_PublicKey 3 ,
.Pf b<d2i_ Vt TYPE Ns params()>
with
.Xr d2i_KeyParams 3 ,
.Pf b<d2i_ Vt TYPE Ns _PUBKEY()>
with
.Xr d2i_PUBKEY 3 ,
.Pf b<i2d_ Vt TYPE Ns PrivateKey()>
with
.Xr i2d_PrivateKey 3 ,
.Pf b<i2d_ Vt TYPE Ns PublicKey()>
with
.Xr i2d_PublicKey 3 ,
.Pf b<i2d_ Vt TYPE Ns params()>
with
.Xr i2d_KeyParams 3 ,
.Pf b<i2d_ Vt TYPE Ns _PUBKEY()>
with
.Xr i2d_PUBKEY 3 .
A caveat is that
.Xr i2d_PrivateKey 3
may output a DER encoded PKCS#8 outermost structure instead of the type
specific structure, and that
.Xr d2i_PrivateKey 3
recognises and unpacks a PKCS#8 structures.
.It
Use
.Xr OSSL_DECODER 3
and
.Xr OSSL_ENCODER 3 .
How to migrate is described below.
All those descriptions assume that the key to be encoded is in the
variable
.Em pkey .
.El
.Pp
.Em Migrating Sy i2d No functions to Sy OSSL_ENCODER
.Pp
The exact
.Xr OSSL_ENCODER 3
output is driven by arguments rather than by function names.
The sample code to get DER encoded output in a type specific structure
is uniform, the only things that vary are the selection of what part of
the
.Sy EVP_PKEY
should be output, and the structure.
The
.Sy i2d
functions names can therefore be translated into two variables,
.Em selection
and
.Em structure
as follows:
.Bl -tag -width Ds
.It Sy i2d_ Ns Vt TYPE Ns PrivateKey Ns () translates into:
.Bd -literal
 int selection = EVP_PKEY_KEYPAIR;
 const char *structure = "type-specific";
.Ed
.It Sy i2d_ Ns Vt TYPE Ns PublicKey Ns () translates into:
.Bd -literal
 int selection = EVP_PKEY_PUBLIC_KEY;
 const char *structure = "type-specific";
.Ed
.It Sy i2d_ Ns Vt TYPE Ns params Ns () translates into:
.Bd -literal
 int selection = EVP_PKEY_PARAMETERS;
 const char *structure = "type-specific";
.Ed
.It Sy i2d_ Ns Vt TYPE Ns _PUBKEY Ns () translates into:
.Bd -literal
 int selection = EVP_PKEY_PUBLIC_KEY;
 const char *structure = "SubjectPublicKeyInfo";
.Ed
.El
The following sample code does the rest of the work:
.Bd -literal
 unsigned char *p = buffer;     /* |buffer| is supplied by the caller */
 size_t len = buffer_size;      /* assumed be the size of |buffer| */
 OSSL_ENCODER_CTX *ctx =
     OSSL_ENCODER_CTX_new_for_pkey(pkey, selection, "DER", structure,
                                   NULL, NULL);
 if (ctx == NULL) {
     /* fatal error handling */
 }
 if (OSSL_ENCODER_CTX_get_num_encoders(ctx) == 0) {
     OSSL_ENCODER_CTX_free(ctx);
     /* non-fatal error handling */
 }
 if (!OSSL_ENCODER_to_data(ctx, &p, &len)) {
     OSSL_ENCODER_CTX_free(ctx);
     /* error handling */
 }
 OSSL_ENCODER_CTX_free(ctx);
.Ed
.Sh NOTES
The letters
.Sy i
and
.Sy d
in
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
stand for "internal" (that is, an internal C structure) and "DER"
respectively.
So
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
converts from internal to DER.
.Pp
The functions can also understand
.Sy BER
forms.
.Pp
The actual TYPE structure passed to
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
must be a valid populated
.Sy Vt TYPE
structure -- it
.Sy cannot
simply be fed with an empty structure such as that returned by
.Xr TYPE_new 3 .
.Pp
The encoded data is in binary form and may contain embedded zeros.
Therefore, any FILE pointers or BIOs should be opened in binary mode.
Functions such as
.Xr strlen 3
will
.Sy not
return the correct length of the encoded structure.
.Pp
The ways that
.Em *ppin
and
.Em *ppout
are incremented after the operation can trap the unwary.
See the
.Sy WARNINGS
section in
.Xr d2i_X509 3
for some common errors.
The reason for this-auto increment behaviour is to reflect a typical
usage of ASN1 functions: after one structure is encoded or decoded
another will be processed after it.
.Pp
The following points about the data types might be useful:
.Bl -tag -width Ds
.It Sy DSA_PUBKEY
Represents a DSA public key using a
.Sy SubjectPublicKeyInfo
structure.
.It Sy DSAPublicKey Ns , Sy DSAPrivateKey
Use a non-standard OpenSSL format and should be avoided; use
.Sy DSA_PUBKEY ,
.Xr PEM_write_PrivateKey 3 ,
or similar instead.
.El
.Sh RETURN VALUES
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3 ,
.Sy d2i_ Ns Vt TYPE Ns _bio Ns
.Xr 3
and
.Sy d2i_ Ns Vt TYPE Ns _fp Ns
.Xr 3
return a valid
.Sy Vt TYPE
structure or NULL if an error occurs.
If the "reuse" capability has been used with a valid structure being
passed in via
.Fa a ,
then the object is freed in the event of error and
.Em *a
is set to NULL.
.Pp
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
returns the number of bytes successfully encoded or a negative value if
an error occurs.
.Pp
.Sy i2d_ Ns Vt TYPE Ns _bio Ns
.Xr 3
and
.Sy i2d_ Ns Vt TYPE Ns _fp Ns
.Xr 3
return 1 for success and 0 if an error occurs.
.Sh SEE ALSO
.Xr OSSL_ENCODER 3 ,
.Xr OSSL_DECODER 3 ,
.Xr d2i_PrivateKey 3 ,
.Xr d2i_PublicKey 3 ,
.Xr d2i_KeyParams 3 ,
.Xr d2i_PUBKEY 3 ,
.Xr i2d_PrivateKey 3 ,
.Xr i2d_PublicKey 3 ,
.Xr i2d_KeyParams 3 ,
.Xr i2d_PUBKEY 3
.Sh COPYRIGHT
Copyright 2020-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
