.Dd 2025-09-30
.Dt D2I_PRIVATEKEY 3ossl
.Os
.Sh NAME
.Nm d2i_PrivateKey_ex ,
.Nm d2i_PrivateKey ,
.Nm d2i_PublicKey ,
.Nm d2i_KeyParams ,
.Nm d2i_AutoPrivateKey_ex ,
.Nm d2i_AutoPrivateKey ,
.Nm i2d_PrivateKey ,
.Nm i2d_PublicKey ,
.Nm i2d_KeyParams ,
.Nm i2d_KeyParams_bio ,
.Nm d2i_PrivateKey_ex_bio ,
.Nm d2i_PrivateKey_bio ,
.Nm d2i_PrivateKey_ex_fp ,
.Nm d2i_PrivateKey_fp ,
.Nm d2i_KeyParams_bio ,
.Nm i2d_PrivateKey_bio ,
.Nm i2d_PrivateKey_fp
.Nd decode and encode functions for reading and saving EVP_PKEY structures
.Sh SYNOPSIS
.In openssl/evp.h
.Ft EVP_PKEY *
.Fo d2i_PrivateKey_ex
.Fa "int type"
.Fa "EVP_PKEY **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo d2i_PrivateKey
.Fa "int type"
.Fa "EVP_PKEY **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fc
.Ft EVP_PKEY *
.Fo d2i_PublicKey
.Fa "int type"
.Fa "EVP_PKEY **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fc
.Ft EVP_PKEY *
.Fo d2i_KeyParams
.Fa "int type"
.Fa "EVP_PKEY **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fc
.Ft EVP_PKEY *
.Fo d2i_AutoPrivateKey_ex
.Fa "EVP_PKEY **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo d2i_AutoPrivateKey
.Fa "EVP_PKEY **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fc
.Ft int
.Fo i2d_PrivateKey
.Fa "const EVP_PKEY *a"
.Fa "unsigned char **pp"
.Fc
.Ft int
.Fo i2d_PublicKey
.Fa "const EVP_PKEY *a"
.Fa "unsigned char **pp"
.Fc
.Ft int
.Fo i2d_KeyParams
.Fa "const EVP_PKEY *a"
.Fa "unsigned char **pp"
.Fc
.Ft int
.Fo i2d_KeyParams_bio
.Fa "BIO *bp"
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft EVP_PKEY *
.Fo d2i_KeyParams_bio
.Fa "int type"
.Fa "EVP_PKEY **a"
.Fa "BIO *in"
.Fc
.In openssl/x509.h
.Ft EVP_PKEY *
.Fo d2i_PrivateKey_ex_bio
.Fa "BIO *bp"
.Fa "EVP_PKEY **a"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo d2i_PrivateKey_bio
.Fa "BIO *bp"
.Fa "EVP_PKEY **a"
.Fc
.Ft EVP_PKEY *
.Fo d2i_PrivateKey_ex_fp
.Fa "FILE *fp"
.Fa "EVP_PKEY **a"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo d2i_PrivateKey_fp
.Fa "FILE *fp"
.Fa "EVP_PKEY **a"
.Fc
.Ft int
.Fo i2d_PrivateKey_bio
.Fa "BIO *bp"
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft int
.Fo i2d_PrivateKey_fp
.Fa "FILE *fp"
.Fa "const EVP_PKEY *pkey"
.Fc
.Sh DESCRIPTION
.Fn d2i_PrivateKey_ex
decodes a private key using algorithm
.Fa type .
It attempts to use any key-specific format or PKCS#8 unencrypted
PrivateKeyInfo format.
The
.Fa type
parameter should be a public key algorithm constant such as
.Sy EVP_PKEY_RSA .
An error occurs if the decoded key does not match
.Fa type .
Some private key decoding implementations may use cryptographic
algorithms (for example to automatically derive the public key if it is
not explicitly included in the encoding).
In this case the supplied library context
.Fa libctx
and property query string
.Fa propq
are used.
If successful and the
.Fa a
parameter is not NULL the function assigns the returned
.Vt EVP_PKEY
structure pointer to
.Em *a ,
overwriting any previous value.
.Pp
.Fn d2i_PrivateKey
does the same as
.Fn d2i_PrivateKey_ex
except that the default library context and property query string are
used.
.Fn d2i_PublicKey
does the same for public keys.
.Fn d2i_KeyParams
does the same for key parameters.
.Pp
The
.Fn d2i_PrivateKey_ex_bio
and
.Fn d2i_PrivateKey_bio
functions are similar to
.Fn d2i_PrivateKey_ex
and
.Fn d2i_PrivateKey
respectively except that they decode the data read from the given BIO.
The
.Fn d2i_PrivateKey_ex_fp
and
.Fn d2i_PrivateKey_fp
functions are the same except that they read the data from the given
FILE.
.Pp
.Fn d2i_AutoPrivateKey_ex
and
.Fn d2i_AutoPrivateKey
are similar to
.Fn d2i_PrivateKey_ex
and
.Fn d2i_PrivateKey
respectively except that they attempt to automatically detect the
private key format.
.Pp
.Fn i2d_PrivateKey
encodes
.Fa a .
It uses a key specific format or, if none is defined for that key type,
PKCS#8 unencrypted PrivateKeyInfo format.
.Fn i2d_PublicKey
does the same for public keys.
.Fn i2d_KeyParams
does the same for key parameters.
These functions are similar to the
.Xr d2i_X509 3
functions; see
.Xr d2i_X509 3 .
.Fn i2d_PrivateKey_bio
and
.Fn i2d_PrivateKey_fp
do the same thing except that they encode to a
.Vt BIO
or
.Vt FILE
respectively.
Again, these work similarly to the functions described in
.Xr d2i_X509 3 .
.Sh NOTES
All the functions that operate on data in memory update the data pointer
.Em *pp
after a successful operation, just like the other d2i and i2d functions;
see
.Xr d2i_X509 3 .
.Pp
All these functions use DER format and unencrypted keys.
Applications wishing to encrypt or decrypt private keys should use other
functions such as
.Xr d2i_PKCS8PrivateKey 3
instead.
.Pp
To decode a key with type
.Sy EVP_PKEY_EC ,
.Fn d2i_PublicKey
requires
.Em *a
to be a non-NULL EVP_PKEY structure assigned an EC_KEY structure
referencing the proper EC_GROUP.
.Sh RETURN VALUES
The
.Fn d2i_PrivateKey_ex ,
.Fn d2i_PrivateKey ,
.Fn d2i_AutoPrivateKey_ex ,
.Fn d2i_AutoPrivateKey ,
.Fn d2i_PrivateKey_ex_bio ,
.Fn d2i_PrivateKey_bio ,
.Fn d2i_PrivateKey_ex_fp ,
.Fn d2i_PrivateKey_fp ,
.Fn d2i_PublicKey ,
.Fn d2i_KeyParams
and
.Fn d2i_KeyParams_bio
functions return a valid
.Vt EVP_PKEY
structure or NULL if an error occurs.
The error code can be obtained by calling
.Xr ERR_get_error 3 .
.Pp
.Fn i2d_PrivateKey ,
.Fn i2d_PublicKey
and
.Fn i2d_KeyParams
return the number of bytes successfully encoded or a negative value if
an error occurs.
The error code can be obtained by calling
.Xr ERR_get_error 3 .
.Pp
.Fn i2d_PrivateKey_bio ,
.Fn i2d_PrivateKey_fp
and
.Fn i2d_KeyParams_bio
return 1 if successfully encoded or zero if an error occurs.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr d2i_PKCS8PrivateKey_bio 3
.Sh HISTORY
.Fn d2i_PrivateKey_ex ,
.Fn d2i_PrivateKey_ex_bio ,
.Fn d2i_PrivateKey_ex_fp ,
and
.Fn d2i_AutoPrivateKey_ex
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2017-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
