.Dd 2025-09-30
.Dt D2I_X509 3ossl
.Os
.Sh NAME
.Nm d2i_ACCESS_DESCRIPTION ,
.Nm d2i_ADMISSIONS ,
.Nm d2i_ADMISSION_SYNTAX ,
.Nm d2i_ASIdOrRange ,
.Nm d2i_ASIdentifierChoice ,
.Nm d2i_ASIdentifiers ,
.Nm d2i_ASN1_BIT_STRING ,
.Nm d2i_ASN1_BMPSTRING ,
.Nm d2i_ASN1_ENUMERATED ,
.Nm d2i_ASN1_GENERALIZEDTIME ,
.Nm d2i_ASN1_GENERALSTRING ,
.Nm d2i_ASN1_IA5STRING ,
.Nm d2i_ASN1_INTEGER ,
.Nm d2i_ASN1_NULL ,
.Nm d2i_ASN1_OBJECT ,
.Nm d2i_ASN1_OCTET_STRING ,
.Nm d2i_ASN1_PRINTABLE ,
.Nm d2i_ASN1_PRINTABLESTRING ,
.Nm d2i_ASN1_SEQUENCE_ANY ,
.Nm d2i_ASN1_SET_ANY ,
.Nm d2i_ASN1_T61STRING ,
.Nm d2i_ASN1_TIME ,
.Nm d2i_ASN1_TYPE ,
.Nm d2i_ASN1_UINTEGER ,
.Nm d2i_ASN1_UNIVERSALSTRING ,
.Nm d2i_ASN1_UTCTIME ,
.Nm d2i_ASN1_UTF8STRING ,
.Nm d2i_ASN1_VISIBLESTRING ,
.Nm d2i_ASRange ,
.Nm d2i_AUTHORITY_INFO_ACCESS ,
.Nm d2i_AUTHORITY_KEYID ,
.Nm d2i_BASIC_CONSTRAINTS ,
.Nm d2i_CERTIFICATEPOLICIES ,
.Nm d2i_CMS_ContentInfo ,
.Nm d2i_CMS_ReceiptRequest ,
.Nm d2i_CMS_bio ,
.Nm d2i_CRL_DIST_POINTS ,
.Nm d2i_DHxparams ,
.Nm d2i_DIRECTORYSTRING ,
.Nm d2i_DISPLAYTEXT ,
.Nm d2i_DIST_POINT ,
.Nm d2i_DIST_POINT_NAME ,
.Nm d2i_DSA_SIG ,
.Nm d2i_ECDSA_SIG ,
.Nm d2i_ECPKParameters ,
.Nm d2i_EDIPARTYNAME ,
.Nm d2i_ESS_CERT_ID ,
.Nm d2i_ESS_CERT_ID_V2 ,
.Nm d2i_ESS_ISSUER_SERIAL ,
.Nm d2i_ESS_SIGNING_CERT ,
.Nm d2i_ESS_SIGNING_CERT_V2 ,
.Nm d2i_EXTENDED_KEY_USAGE ,
.Nm d2i_GENERAL_NAME ,
.Nm d2i_GENERAL_NAMES ,
.Nm d2i_IPAddressChoice ,
.Nm d2i_IPAddressFamily ,
.Nm d2i_IPAddressOrRange ,
.Nm d2i_IPAddressRange ,
.Nm d2i_ISSUER_SIGN_TOOL ,
.Nm d2i_ISSUING_DIST_POINT ,
.Nm d2i_NAMING_AUTHORITY ,
.Nm d2i_NETSCAPE_CERT_SEQUENCE ,
.Nm d2i_NETSCAPE_SPKAC ,
.Nm d2i_NETSCAPE_SPKI ,
.Nm d2i_NOTICEREF ,
.Nm d2i_OCSP_BASICRESP ,
.Nm d2i_OCSP_CERTID ,
.Nm d2i_OCSP_CERTSTATUS ,
.Nm d2i_OCSP_CRLID ,
.Nm d2i_OCSP_ONEREQ ,
.Nm d2i_OCSP_REQINFO ,
.Nm d2i_OCSP_REQUEST ,
.Nm d2i_OCSP_RESPBYTES ,
.Nm d2i_OCSP_RESPDATA ,
.Nm d2i_OCSP_RESPID ,
.Nm d2i_OCSP_RESPONSE ,
.Nm d2i_OCSP_REVOKEDINFO ,
.Nm d2i_OCSP_SERVICELOC ,
.Nm d2i_OCSP_SIGNATURE ,
.Nm d2i_OCSP_SINGLERESP ,
.Nm d2i_OSSL_AA_DIST_POINT ,
.Nm d2i_OSSL_ALLOWED_ATTRIBUTES_CHOICE ,
.Nm d2i_OSSL_ALLOWED_ATTRIBUTES_ITEM ,
.Nm d2i_OSSL_ALLOWED_ATTRIBUTES_SYNTAX ,
.Nm d2i_OSSL_ATAV ,
.Nm d2i_OSSL_ATTRIBUTE_DESCRIPTOR ,
.Nm d2i_OSSL_ATTRIBUTE_MAPPING ,
.Nm d2i_OSSL_ATTRIBUTE_MAPPINGS ,
.Nm d2i_OSSL_ATTRIBUTE_TYPE_MAPPING ,
.Nm d2i_OSSL_ATTRIBUTE_VALUE_MAPPING ,
.Nm d2i_OSSL_ATTRIBUTES_SYNTAX ,
.Nm d2i_OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX ,
.Nm d2i_OSSL_BASIC_ATTR_CONSTRAINTS ,
.Nm d2i_OSSL_CMP_ATAVS ,
.Nm d2i_OSSL_CMP_MSG ,
.Nm d2i_OSSL_CMP_PKIHEADER ,
.Nm d2i_OSSL_CMP_PKISI ,
.Nm d2i_OSSL_CRMF_CERTID ,
.Nm d2i_OSSL_CRMF_CERTTEMPLATE ,
.Nm d2i_OSSL_CRMF_ENCRYPTEDKEY ,
.Nm d2i_OSSL_CRMF_ENCRYPTEDVALUE ,
.Nm d2i_OSSL_CRMF_MSG ,
.Nm d2i_OSSL_CRMF_MSGS ,
.Nm d2i_OSSL_CRMF_PBMPARAMETER ,
.Nm d2i_OSSL_CRMF_PKIPUBLICATIONINFO ,
.Nm d2i_OSSL_CRMF_SINGLEPUBINFO ,
.Nm d2i_OSSL_DAY_TIME ,
.Nm d2i_OSSL_DAY_TIME_BAND ,
.Nm d2i_OSSL_HASH ,
.Nm d2i_OSSL_IETF_ATTR_SYNTAX ,
.Nm d2i_OSSL_INFO_SYNTAX ,
.Nm d2i_OSSL_INFO_SYNTAX_POINTER ,
.Nm d2i_OSSL_ISSUER_SERIAL ,
.Nm d2i_OSSL_NAMED_DAY ,
.Nm d2i_OSSL_OBJECT_DIGEST_INFO ,
.Nm d2i_OSSL_PRIVILEGE_POLICY_ID ,
.Nm d2i_OSSL_ROLE_SPEC_CERT_ID ,
.Nm d2i_OSSL_ROLE_SPEC_CERT_ID_SYNTAX ,
.Nm d2i_OSSL_TARGET_CERT ,
.Nm d2i_OSSL_TARGET ,
.Nm d2i_OSSL_TARGETING_INFORMATION ,
.Nm d2i_OSSL_TARGETS ,
.Nm d2i_OSSL_TIME_PERIOD ,
.Nm d2i_OSSL_TIME_SPEC ,
.Nm d2i_OSSL_TIME_SPEC_ABSOLUTE ,
.Nm d2i_OSSL_TIME_SPEC_DAY ,
.Nm d2i_OSSL_TIME_SPEC_MONTH ,
.Nm d2i_OSSL_TIME_SPEC_TIME ,
.Nm d2i_OSSL_TIME_SPEC_WEEKS ,
.Nm d2i_OSSL_TIME_SPEC_X_DAY_OF ,
.Nm d2i_OSSL_USER_NOTICE_SYNTAX ,
.Nm d2i_OTHERNAME ,
.Nm d2i_PBE2PARAM ,
.Nm d2i_PBEPARAM ,
.Nm d2i_PBKDF2PARAM ,
.Nm d2i_PBMAC1PARAM ,
.Nm d2i_PKCS12 ,
.Nm d2i_PKCS12_BAGS ,
.Nm d2i_PKCS12_MAC_DATA ,
.Nm d2i_PKCS12_SAFEBAG ,
.Nm d2i_PKCS12_bio ,
.Nm d2i_PKCS12_fp ,
.Nm d2i_PKCS7 ,
.Nm d2i_PKCS7_DIGEST ,
.Nm d2i_PKCS7_ENCRYPT ,
.Nm d2i_PKCS7_ENC_CONTENT ,
.Nm d2i_PKCS7_ENVELOPE ,
.Nm d2i_PKCS7_ISSUER_AND_SERIAL ,
.Nm d2i_PKCS7_RECIP_INFO ,
.Nm d2i_PKCS7_SIGNED ,
.Nm d2i_PKCS7_SIGNER_INFO ,
.Nm d2i_PKCS7_SIGN_ENVELOPE ,
.Nm d2i_PKCS7_bio ,
.Nm d2i_PKCS7_fp ,
.Nm d2i_PKCS8_PRIV_KEY_INFO ,
.Nm d2i_PKCS8_PRIV_KEY_INFO_bio ,
.Nm d2i_PKCS8_PRIV_KEY_INFO_fp ,
.Nm d2i_PKCS8_bio ,
.Nm d2i_PKCS8_fp ,
.Nm d2i_PKEY_USAGE_PERIOD ,
.Nm d2i_POLICYINFO ,
.Nm d2i_POLICYQUALINFO ,
.Nm d2i_PROFESSION_INFO ,
.Nm d2i_PROXY_CERT_INFO_EXTENSION ,
.Nm d2i_PROXY_POLICY ,
.Nm d2i_RSA_OAEP_PARAMS ,
.Nm d2i_RSA_PSS_PARAMS ,
.Nm d2i_SCRYPT_PARAMS ,
.Nm d2i_SCT_LIST ,
.Nm d2i_SXNET ,
.Nm d2i_SXNETID ,
.Nm d2i_TS_ACCURACY ,
.Nm d2i_TS_MSG_IMPRINT ,
.Nm d2i_TS_MSG_IMPRINT_bio ,
.Nm d2i_TS_MSG_IMPRINT_fp ,
.Nm d2i_TS_REQ ,
.Nm d2i_TS_REQ_bio ,
.Nm d2i_TS_REQ_fp ,
.Nm d2i_TS_RESP ,
.Nm d2i_TS_RESP_bio ,
.Nm d2i_TS_RESP_fp ,
.Nm d2i_TS_STATUS_INFO ,
.Nm d2i_TS_TST_INFO ,
.Nm d2i_TS_TST_INFO_bio ,
.Nm d2i_TS_TST_INFO_fp ,
.Nm d2i_USERNOTICE ,
.Nm d2i_X509 ,
.Nm d2i_X509_bio ,
.Nm d2i_X509_fp ,
.Nm d2i_X509_ACERT ,
.Nm d2i_X509_ACERT_bio ,
.Nm d2i_X509_ACERT_fp ,
.Nm d2i_X509_ALGOR ,
.Nm d2i_X509_ALGORS ,
.Nm d2i_X509_ATTRIBUTE ,
.Nm d2i_X509_CERT_AUX ,
.Nm d2i_X509_CINF ,
.Nm d2i_X509_CRL ,
.Nm d2i_X509_CRL_INFO ,
.Nm d2i_X509_CRL_bio ,
.Nm d2i_X509_CRL_fp ,
.Nm d2i_X509_EXTENSION ,
.Nm d2i_X509_EXTENSIONS ,
.Nm d2i_X509_NAME ,
.Nm d2i_X509_NAME_ENTRY ,
.Nm d2i_X509_PUBKEY ,
.Nm d2i_X509_PUBKEY_bio ,
.Nm d2i_X509_PUBKEY_fp ,
.Nm d2i_X509_REQ ,
.Nm d2i_X509_REQ_INFO ,
.Nm d2i_X509_REQ_bio ,
.Nm d2i_X509_REQ_fp ,
.Nm d2i_X509_REVOKED ,
.Nm d2i_X509_SIG ,
.Nm d2i_X509_VAL ,
.Nm i2d_ACCESS_DESCRIPTION ,
.Nm i2d_ADMISSIONS ,
.Nm i2d_ADMISSION_SYNTAX ,
.Nm i2d_ASIdOrRange ,
.Nm i2d_ASIdentifierChoice ,
.Nm i2d_ASIdentifiers ,
.Nm i2d_ASN1_BIT_STRING ,
.Nm i2d_ASN1_BMPSTRING ,
.Nm i2d_ASN1_ENUMERATED ,
.Nm i2d_ASN1_GENERALIZEDTIME ,
.Nm i2d_ASN1_GENERALSTRING ,
.Nm i2d_ASN1_IA5STRING ,
.Nm i2d_ASN1_INTEGER ,
.Nm i2d_ASN1_NULL ,
.Nm i2d_ASN1_OBJECT ,
.Nm i2d_ASN1_OCTET_STRING ,
.Nm i2d_ASN1_PRINTABLE ,
.Nm i2d_ASN1_PRINTABLESTRING ,
.Nm i2d_ASN1_SEQUENCE_ANY ,
.Nm i2d_ASN1_SET_ANY ,
.Nm i2d_ASN1_T61STRING ,
.Nm i2d_ASN1_TIME ,
.Nm i2d_ASN1_TYPE ,
.Nm i2d_ASN1_UNIVERSALSTRING ,
.Nm i2d_ASN1_UTCTIME ,
.Nm i2d_ASN1_UTF8STRING ,
.Nm i2d_ASN1_VISIBLESTRING ,
.Nm i2d_ASN1_bio_stream ,
.Nm i2d_ASRange ,
.Nm i2d_AUTHORITY_INFO_ACCESS ,
.Nm i2d_AUTHORITY_KEYID ,
.Nm i2d_BASIC_CONSTRAINTS ,
.Nm i2d_CERTIFICATEPOLICIES ,
.Nm i2d_CMS_ContentInfo ,
.Nm i2d_CMS_ReceiptRequest ,
.Nm i2d_CMS_bio ,
.Nm i2d_CRL_DIST_POINTS ,
.Nm i2d_DHxparams ,
.Nm i2d_DIRECTORYSTRING ,
.Nm i2d_DISPLAYTEXT ,
.Nm i2d_DIST_POINT ,
.Nm i2d_DIST_POINT_NAME ,
.Nm i2d_DSA_SIG ,
.Nm i2d_ECDSA_SIG ,
.Nm i2d_ECPKParameters ,
.Nm i2d_EDIPARTYNAME ,
.Nm i2d_ESS_CERT_ID ,
.Nm i2d_ESS_CERT_ID_V2 ,
.Nm i2d_ESS_ISSUER_SERIAL ,
.Nm i2d_ESS_SIGNING_CERT ,
.Nm i2d_ESS_SIGNING_CERT_V2 ,
.Nm i2d_EXTENDED_KEY_USAGE ,
.Nm i2d_GENERAL_NAME ,
.Nm i2d_GENERAL_NAMES ,
.Nm i2d_IPAddressChoice ,
.Nm i2d_IPAddressFamily ,
.Nm i2d_IPAddressOrRange ,
.Nm i2d_IPAddressRange ,
.Nm i2d_ISSUER_SIGN_TOOL ,
.Nm i2d_ISSUING_DIST_POINT ,
.Nm i2d_NAMING_AUTHORITY ,
.Nm i2d_NETSCAPE_CERT_SEQUENCE ,
.Nm i2d_NETSCAPE_SPKAC ,
.Nm i2d_NETSCAPE_SPKI ,
.Nm i2d_NOTICEREF ,
.Nm i2d_OCSP_BASICRESP ,
.Nm i2d_OCSP_CERTID ,
.Nm i2d_OCSP_CERTSTATUS ,
.Nm i2d_OCSP_CRLID ,
.Nm i2d_OCSP_ONEREQ ,
.Nm i2d_OCSP_REQINFO ,
.Nm i2d_OCSP_REQUEST ,
.Nm i2d_OCSP_RESPBYTES ,
.Nm i2d_OCSP_RESPDATA ,
.Nm i2d_OCSP_RESPID ,
.Nm i2d_OCSP_RESPONSE ,
.Nm i2d_OCSP_REVOKEDINFO ,
.Nm i2d_OCSP_SERVICELOC ,
.Nm i2d_OCSP_SIGNATURE ,
.Nm i2d_OCSP_SINGLERESP ,
.Nm i2d_OSSL_AA_DIST_POINT ,
.Nm i2d_OSSL_ALLOWED_ATTRIBUTES_CHOICE ,
.Nm i2d_OSSL_ALLOWED_ATTRIBUTES_ITEM ,
.Nm i2d_OSSL_ALLOWED_ATTRIBUTES_SYNTAX ,
.Nm i2d_OSSL_ATAV ,
.Nm i2d_OSSL_ATTRIBUTE_DESCRIPTOR ,
.Nm i2d_OSSL_ATTRIBUTE_MAPPING ,
.Nm i2d_OSSL_ATTRIBUTE_MAPPINGS ,
.Nm i2d_OSSL_ATTRIBUTE_TYPE_MAPPING ,
.Nm i2d_OSSL_ATTRIBUTE_VALUE_MAPPING ,
.Nm i2d_OSSL_ATTRIBUTES_SYNTAX ,
.Nm i2d_OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX ,
.Nm i2d_OSSL_BASIC_ATTR_CONSTRAINTS ,
.Nm i2d_OSSL_CMP_ATAVS ,
.Nm i2d_OSSL_CMP_MSG ,
.Nm i2d_OSSL_CMP_PKIHEADER ,
.Nm i2d_OSSL_CMP_PKISI ,
.Nm i2d_OSSL_CRMF_CERTID ,
.Nm i2d_OSSL_CRMF_CERTTEMPLATE ,
.Nm i2d_OSSL_CRMF_ENCRYPTEDKEY ,
.Nm i2d_OSSL_CRMF_ENCRYPTEDVALUE ,
.Nm i2d_OSSL_CRMF_MSG ,
.Nm i2d_OSSL_CRMF_MSGS ,
.Nm i2d_OSSL_CRMF_PBMPARAMETER ,
.Nm i2d_OSSL_CRMF_PKIPUBLICATIONINFO ,
.Nm i2d_OSSL_CRMF_SINGLEPUBINFO ,
.Nm i2d_OSSL_HASH ,
.Nm i2d_OSSL_DAY_TIME ,
.Nm i2d_OSSL_DAY_TIME_BAND ,
.Nm i2d_OSSL_IETF_ATTR_SYNTAX ,
.Nm i2d_OSSL_INFO_SYNTAX ,
.Nm i2d_OSSL_INFO_SYNTAX_POINTER ,
.Nm i2d_OSSL_ISSUER_SERIAL ,
.Nm i2d_OSSL_NAMED_DAY ,
.Nm i2d_OSSL_OBJECT_DIGEST_INFO ,
.Nm i2d_OSSL_PRIVILEGE_POLICY_ID ,
.Nm i2d_OSSL_ROLE_SPEC_CERT_ID ,
.Nm i2d_OSSL_ROLE_SPEC_CERT_ID_SYNTAX ,
.Nm i2d_OSSL_TARGET_CERT ,
.Nm i2d_OSSL_TARGET ,
.Nm i2d_OSSL_TARGETING_INFORMATION ,
.Nm i2d_OSSL_TARGETS ,
.Nm i2d_OSSL_TIME_PERIOD ,
.Nm i2d_OSSL_TIME_SPEC ,
.Nm i2d_OSSL_TIME_SPEC_ABSOLUTE ,
.Nm i2d_OSSL_TIME_SPEC_DAY ,
.Nm i2d_OSSL_TIME_SPEC_MONTH ,
.Nm i2d_OSSL_TIME_SPEC_TIME ,
.Nm i2d_OSSL_TIME_SPEC_WEEKS ,
.Nm i2d_OSSL_TIME_SPEC_X_DAY_OF ,
.Nm i2d_OSSL_USER_NOTICE_SYNTAX ,
.Nm i2d_OTHERNAME ,
.Nm i2d_PBE2PARAM ,
.Nm i2d_PBEPARAM ,
.Nm i2d_PBKDF2PARAM ,
.Nm i2d_PBMAC1PARAM ,
.Nm i2d_PKCS12 ,
.Nm i2d_PKCS12_BAGS ,
.Nm i2d_PKCS12_MAC_DATA ,
.Nm i2d_PKCS12_SAFEBAG ,
.Nm i2d_PKCS12_bio ,
.Nm i2d_PKCS12_fp ,
.Nm i2d_PKCS7 ,
.Nm i2d_PKCS7_DIGEST ,
.Nm i2d_PKCS7_ENCRYPT ,
.Nm i2d_PKCS7_ENC_CONTENT ,
.Nm i2d_PKCS7_ENVELOPE ,
.Nm i2d_PKCS7_ISSUER_AND_SERIAL ,
.Nm i2d_PKCS7_NDEF ,
.Nm i2d_PKCS7_RECIP_INFO ,
.Nm i2d_PKCS7_SIGNED ,
.Nm i2d_PKCS7_SIGNER_INFO ,
.Nm i2d_PKCS7_SIGN_ENVELOPE ,
.Nm i2d_PKCS7_bio ,
.Nm i2d_PKCS7_fp ,
.Nm i2d_PKCS8PrivateKeyInfo_bio ,
.Nm i2d_PKCS8PrivateKeyInfo_fp ,
.Nm i2d_PKCS8_PRIV_KEY_INFO ,
.Nm i2d_PKCS8_PRIV_KEY_INFO_bio ,
.Nm i2d_PKCS8_PRIV_KEY_INFO_fp ,
.Nm i2d_PKCS8_bio ,
.Nm i2d_PKCS8_fp ,
.Nm i2d_PKEY_USAGE_PERIOD ,
.Nm i2d_POLICYINFO ,
.Nm i2d_POLICYQUALINFO ,
.Nm i2d_PROFESSION_INFO ,
.Nm i2d_PROXY_CERT_INFO_EXTENSION ,
.Nm i2d_PROXY_POLICY ,
.Nm i2d_RSA_OAEP_PARAMS ,
.Nm i2d_RSA_PSS_PARAMS ,
.Nm i2d_SCRYPT_PARAMS ,
.Nm i2d_SCT_LIST ,
.Nm i2d_SXNET ,
.Nm i2d_SXNETID ,
.Nm i2d_TS_ACCURACY ,
.Nm i2d_TS_MSG_IMPRINT ,
.Nm i2d_TS_MSG_IMPRINT_bio ,
.Nm i2d_TS_MSG_IMPRINT_fp ,
.Nm i2d_TS_REQ ,
.Nm i2d_TS_REQ_bio ,
.Nm i2d_TS_REQ_fp ,
.Nm i2d_TS_RESP ,
.Nm i2d_TS_RESP_bio ,
.Nm i2d_TS_RESP_fp ,
.Nm i2d_TS_STATUS_INFO ,
.Nm i2d_TS_TST_INFO ,
.Nm i2d_TS_TST_INFO_bio ,
.Nm i2d_TS_TST_INFO_fp ,
.Nm i2d_USERNOTICE ,
.Nm i2d_X509 ,
.Nm i2d_X509_bio ,
.Nm i2d_X509_fp ,
.Nm i2d_X509_ACERT ,
.Nm i2d_X509_ACERT_bio ,
.Nm i2d_X509_ACERT_fp ,
.Nm i2d_X509_ALGOR ,
.Nm i2d_X509_ALGORS ,
.Nm i2d_X509_ATTRIBUTE ,
.Nm i2d_X509_CERT_AUX ,
.Nm i2d_X509_CINF ,
.Nm i2d_X509_CRL ,
.Nm i2d_X509_CRL_INFO ,
.Nm i2d_X509_CRL_bio ,
.Nm i2d_X509_CRL_fp ,
.Nm i2d_X509_EXTENSION ,
.Nm i2d_X509_EXTENSIONS ,
.Nm i2d_X509_NAME ,
.Nm i2d_X509_NAME_ENTRY ,
.Nm i2d_X509_PUBKEY ,
.Nm i2d_X509_PUBKEY_bio ,
.Nm i2d_X509_PUBKEY_fp ,
.Nm i2d_X509_REQ ,
.Nm i2d_X509_REQ_INFO ,
.Nm i2d_X509_REQ_bio ,
.Nm i2d_X509_REQ_fp ,
.Nm i2d_X509_REVOKED ,
.Nm i2d_X509_SIG ,
.Nm i2d_X509_VAL ,
.Nd convert objects from/to ASN.1/DER representation
.Sh SYNOPSIS
.Ft TYPE *
.Fo d2i_TYPE
.Fa "TYPE **a"
.Fa "const unsigned char **ppin"
.Fa "long length"
.Fc
.Ft TYPE *
.Fo d2i_TYPE_bio
.Fa "BIO *bp"
.Fa "TYPE **a"
.Fc
.Ft TYPE *
.Fo d2i_TYPE_fp
.Fa "FILE *fp"
.Fa "TYPE **a"
.Fc
.Ft int
.Fo i2d_TYPE
.Fa "const TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPE
.Fa "TYPE *a"
.Fa "unsigned char **ppout"
.Fc
.Ft int
.Fo i2d_TYPE_fp
.Fa "FILE *fp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_fp
.Fa "FILE *fp"
.Fa "TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_bio
.Fa "BIO *bp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo i2d_TYPE_bio
.Fa "BIO *bp"
.Fa "TYPE *a"
.Fc
.Sh DESCRIPTION
In the description here,
.Sy Vt TYPE
is used a placeholder for any of the OpenSSL datatypes, such as
.Sy X509_CRL .
The function parameters
.Fa ppin
and
.Fa ppout
are generally either both named
.Em pp
in the headers, or
.Em in
and
.Em out .
.Pp
These functions convert OpenSSL objects to and from their ASN.1/DER
encoding.
Unlike the C structures which can have pointers to sub-objects within,
the DER is a serialized encoding, suitable for sending over the network,
writing to a file, and so on.
.Pp
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3
attempts to decode
.Em len
bytes at
.Em *ppin .
If successful a pointer to the
.Sy Vt TYPE
structure is returned and
.Em *ppin
is incremented to the byte following the parsed data.
If
.Fa a
is not NULL then a pointer to the returned structure is also written to
.Em *a .
If an error occurred then NULL is returned.
The caller retains ownership of the returned object and needs to free it
when it is no longer needed, e.g.
using
.Xr X509_free 3
for X509 objects or
.Xr DSA_SIG_free 3
for DSA_SIG objects.
.Pp
On a successful return, if
.Em *a
is not NULL then it is assumed that
.Em *a
contains a valid
.Sy Vt TYPE
structure and an attempt is made to reuse it.
For
.Sy Vt TYPE
structures where it matters it is possible to set up a library context
on the decoded structure this way (see the
.Sy EXAMPLES
section).
However using the "reuse" capability for other purposes is
.Sy strongly discouraged
(see
.Sy BUGS
below, and the discussion in the
.Sy RETURN VALUES
section).
.Pp
.Sy d2i_ Ns Vt TYPE Ns _bio Ns
.Xr 3
is similar to
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3
except it attempts to parse data from BIO
.Fa bp .
.Pp
.Sy d2i_ Ns Vt TYPE Ns _fp Ns
.Xr 3
is similar to
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3
except it attempts to parse data from FILE pointer
.Fa fp .
.Pp
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
encodes the structure pointed to by
.Fa a
into DER format.
If
.Fa ppout
is not NULL, it writes the DER encoded data to the buffer at
.Em *ppout ,
and increments it to point after the data just written.
If the return value is negative an error occurred, otherwise it returns
the length of the encoded data.
.Pp
If
.Em *ppout
is NULL memory will be allocated for a buffer and the encoded data
written to it.
In this case
.Em *ppout
is not incremented and it points to the start of the data just written.
.Pp
.Sy i2d_ Ns Vt TYPE Ns _bio Ns
.Xr 3
is similar to
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
except it writes the encoding of the structure
.Fa a
to BIO
.Fa bp
and it returns 1 for success and 0 for failure.
.Pp
.Sy i2d_ Ns Vt TYPE Ns _fp Ns
.Xr 3
is similar to
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
except it writes the encoding of the structure
.Fa a
to FILE pointer
.Fa fp
and it returns 1 for success and 0 for failure.
.Pp
These routines do not encrypt private keys and therefore offer no
security; use
.Xr PEM_write_PrivateKey 3
or similar for writing to files.
.Sh NOTES
The letters
.Sy i
and
.Sy d
in
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
stand for "internal" (that is, an internal C structure) and "DER"
respectively.
So
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
converts from internal to DER.
.Pp
The functions can also understand
.Sy BER
forms.
.Pp
The actual TYPE structure passed to
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
must be a valid populated
.Sy Vt TYPE
structure -- it
.Sy cannot
simply be fed with an empty structure such as that returned by
.Xr TYPE_new 3 .
.Pp
The encoded data is in binary form and may contain embedded zeros.
Therefore, any FILE pointers or BIOs should be opened in binary mode.
Functions such as
.Xr strlen 3
will
.Sy not
return the correct length of the encoded structure.
.Pp
The ways that
.Em *ppin
and
.Em *ppout
are incremented after the operation can trap the unwary.
See the
.Sy WARNINGS
section for some common errors.
The reason for this-auto increment behaviour is to reflect a typical
usage of ASN1 functions: after one structure is encoded or decoded
another will be processed after it.
.Pp
The following points about the data types might be useful:
.Bl -tag -width Ds
.It Sy ASN1_OBJECT
Represents an ASN1 OBJECT IDENTIFIER.
.It Sy DHparams
Represents a PKCS#3 DH parameters structure.
.It Sy DHxparams
Represents an ANSI X9.42 DH parameters structure.
.It Sy ECDSA_SIG
Represents an ECDSA signature.
.It Sy X509_ALGOR
Represents an
.Sy AlgorithmIdentifier
structure as used in IETF RFC 6960 and elsewhere.
.It Sy X509_NAME
Represents a
.Sy Name
type as used for subject and issuer names in IETF RFC 6960 and
elsewhere.
.It Sy X509_REQ
Represents a PKCS#10 certificate request.
.It Sy X509_SIG
Represents the
.Sy DigestInfo
structure defined in PKCS#1 and PKCS#7.
.El
.Sh RETURN VALUES
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3 ,
.Sy d2i_ Ns Vt TYPE Ns _bio Ns
.Xr 3
and
.Sy d2i_ Ns Vt TYPE Ns _fp Ns
.Xr 3
return a valid
.Sy Vt TYPE
structure or NULL if an error occurs.
If the "reuse" capability has been used with a valid structure being
passed in via
.Fa a ,
then the object is freed in the event of error and
.Em *a
is set to NULL.
.Pp
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
returns the number of bytes successfully encoded or a negative value if
an error occurs.
.Pp
.Sy i2d_ Ns Vt TYPE Ns _bio Ns
.Xr 3
and
.Sy i2d_ Ns Vt TYPE Ns _fp Ns
.Xr 3 ,
as well as
.Xr i2d_ASN1_bio_stream 3 ,
return 1 for success and 0 if an error occurs.
.Sh EXAMPLES
Allocate and encode the DER encoding of an X509 structure:
.Bd -literal
 int len;
 unsigned char *buf;

 buf = NULL;
 len = i2d_X509(x, &buf);
 if (len < 0)
     /* error */
.Ed
.Pp
Attempt to decode a buffer:
.Bd -literal
 X509 *x;
 unsigned char *buf;
 const unsigned char *p;
 int len;

 /* Set up buf and len to point to the input buffer. */
 p = buf;
 x = d2i_X509(NULL, &p, len);
 if (x == NULL)
     /* error */
.Ed
.Pp
Alternative technique:
.Bd -literal
 X509 *x;
 unsigned char *buf;
 const unsigned char *p;
 int len;

 /* Set up buf and len to point to the input buffer. */
 p = buf;
 x = NULL;

 if (d2i_X509(&x, &p, len) == NULL)
     /* error */
.Ed
.Pp
Setting up a library context and property query:
.Bd -literal
 X509 *x;
 unsigned char *buf;
 const unsigned char *p;
 int len;
 OSSL_LIB_CTX *libctx = ....;
 const char *propq = ....;

 /* Set up buf and len to point to the input buffer. */
 p = buf;
 x = X509_new_ex(libctx, propq);

 if (d2i_X509(&x, &p, len) == NULL)
     /* error, x was freed and NULL assigned to it (see RETURN VALUES) */
.Ed
.Sh WARNINGS
Using a temporary variable is mandatory.
A common mistake is to attempt to use a buffer directly as follows:
.Bd -literal
 int len;
 unsigned char *buf;

 len = i2d_X509(x, NULL);
 buf = OPENSSL_malloc(len);
 ...
 i2d_X509(x, &buf);
 ...
 OPENSSL_free(buf);
.Ed
.Pp
This code will result in
.Em buf
apparently containing garbage because it was incremented after the call
to point after the data just written.
Also
.Em buf
will no longer contain the pointer allocated by
.Xr OPENSSL_malloc 3
and the subsequent call to
.Xr OPENSSL_free 3
is likely to crash.
.Pp
Another trap to avoid is misuse of the
.Fa a
argument to
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3 :
.Bd -literal
 X509 *x;

 if (d2i_X509(&x, &p, len) == NULL)
     /* error */
.Ed
.Pp
This will probably crash somewhere in
.Xr d2i_X509 3 .
The reason for this is that the variable
.Em x
is uninitialized and an attempt will be made to interpret its (invalid)
value as an
.Sy X509
structure, typically causing a segmentation violation.
If
.Em x
is set to NULL first then this will not happen.
.Sh BUGS
In some versions of OpenSSL the "reuse" behaviour of
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3
when
.Em *a
is valid is broken and some parts of the reused structure may persist if
they are not present in the new one.
Additionally, in versions of OpenSSL prior to 1.1.0, when the "reuse"
behaviour is used and an error occurs the behaviour is inconsistent.
Some functions behaved as described here, while some did not free
.Em *a
on error and did not set
.Em *a
to NULL.
.Pp
As a result of the above issues the "reuse" behaviour is strongly
discouraged.
.Pp
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
will not return an error in many versions of OpenSSL, if mandatory
fields are not initialized due to a programming error then the encoded
structure may contain invalid data or omit the fields entirely and will
not be parsed by
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3 .
This may be fixed in future so code should not assume that
.Sy i2d_ Ns Vt TYPE Ns
.Xr 3
will always succeed.
.Pp
Any function which encodes a structure
.Pf ( Sy i2d_ Ns Vt TYPE Ns
.Xr 3 ,
.Sy i2d_ Ns Vt TYPE Ns _bio Ns
.Xr 3
or
.Sy i2d_ Ns Vt TYPE Ns _fp Ns
.Xr 3 )
may return a stale encoding if the structure has been modified after
deserialization or previous serialization.
This is because some objects cache the encoding for efficiency reasons.
.Sh HISTORY
.Xr d2i_OSSL_ATTRIBUTES_SYNTAX 3 ,
.Xr d2i_OSSL_BASIC_ATTR_CONSTRAINTS 3 ,
.Xr d2i_OSSL_CMP_ATAVS 3 ,
.Xr d2i_OSSL_IETF_ATTR_SYNTAX 3 ,
.Xr d2i_OSSL_TARGET 3 ,
.Xr d2i_OSSL_TARGETING_INFORMATION 3 ,
.Xr d2i_OSSL_TARGETS 3 ,
.Xr d2i_OSSL_USER_NOTICE_SYNTAX 3 ,
.Xr d2i_PBMAC1PARAM 3 ,
.Xr d2i_X509_ACERT 3 ,
.Xr d2i_X509_ACERT_bio 3 ,
.Xr d2i_X509_ACERT_fp 3 ,
.Xr i2d_OSSL_ATTRIBUTES_SYNTAX 3 ,
.Xr i2d_OSSL_BASIC_ATTR_CONSTRAINTS 3 ,
.Xr i2d_OSSL_CMP_ATAVS 3 ,
.Xr i2d_OSSL_IETF_ATTR_SYNTAX 3 ,
.Xr i2d_OSSL_TARGET 3 ,
.Xr i2d_OSSL_TARGETING_INFORMATION 3 ,
.Xr i2d_OSSL_TARGETS 3 ,
.Xr i2d_OSSL_USER_NOTICE_SYNTAX 3 ,
.Xr i2d_PBMAC1PARAM 3 ,
.Xr i2d_X509_ACERT 3 ,
.Xr i2d_X509_ACERT_bio 3 ,
.Xr i2d_X509_ACERT_fp 3
were added in OpenSSL 3.4.
.Pp
.Xr d2i_OSSL_AA_DIST_POINT 3 ,
.Xr d2i_OSSL_ALLOWED_ATTRIBUTES_CHOICE 3 ,
.Xr d2i_OSSL_ALLOWED_ATTRIBUTES_ITEM 3 ,
.Xr d2i_OSSL_ALLOWED_ATTRIBUTES_SYNTAX 3 ,
.Xr d2i_OSSL_ATAV 3 ,
.Xr d2i_OSSL_ATTRIBUTE_DESCRIPTOR 3 ,
.Xr d2i_OSSL_ATTRIBUTE_MAPPING 3 ,
.Xr d2i_OSSL_ATTRIBUTE_MAPPINGS 3 ,
.Xr d2i_OSSL_ATTRIBUTE_TYPE_MAPPING 3 ,
.Xr d2i_OSSL_ATTRIBUTE_VALUE_MAPPING 3 ,
.Xr d2i_OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX 3 ,
.Xr d2i_OSSL_HASH 3 ,
.Xr d2i_OSSL_INFO_SYNTAX 3 ,
.Xr d2i_OSSL_INFO_SYNTAX_POINTER 3 ,
.Xr d2i_OSSL_PRIVILEGE_POLICY_ID 3 ,
.Xr d2i_OSSL_ROLE_SPEC_CERT_ID 3 ,
.Xr d2i_OSSL_ROLE_SPEC_CERT_ID_SYNTAX 3 ,
.Xr i2d_OSSL_AA_DIST_POINT 3 ,
.Xr i2d_OSSL_ALLOWED_ATTRIBUTES_CHOICE 3 ,
.Xr i2d_OSSL_ALLOWED_ATTRIBUTES_ITEM 3 ,
.Xr i2d_OSSL_ALLOWED_ATTRIBUTES_SYNTAX 3 ,
.Xr i2d_OSSL_ATAV 3 ,
.Xr i2d_OSSL_ATTRIBUTE_DESCRIPTOR 3 ,
.Xr i2d_OSSL_ATTRIBUTE_MAPPING 3 ,
.Xr i2d_OSSL_ATTRIBUTE_MAPPINGS 3 ,
.Xr i2d_OSSL_ATTRIBUTE_TYPE_MAPPING 3 ,
.Xr i2d_OSSL_ATTRIBUTE_VALUE_MAPPING 3 ,
.Xr i2d_OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX 3 ,
.Xr i2d_OSSL_HASH 3 ,
.Xr i2d_OSSL_INFO_SYNTAX 3 ,
.Xr i2d_OSSL_INFO_SYNTAX_POINTER 3 ,
.Xr i2d_OSSL_PRIVILEGE_POLICY_ID 3 ,
.Xr i2d_OSSL_ROLE_SPEC_CERT_ID 3 ,
.Xr i2d_OSSL_ROLE_SPEC_CERT_ID_SYNTAX 3 ,
.Xr d2i_OSSL_CRMF_ENCRYPTEDKEY 3 ,
.Xr i2d_OSSL_CRMF_ENCRYPTEDKEY 3 ,
.Xr d2i_OSSL_DAY_TIME 3 ,
.Xr d2i_OSSL_DAY_TIME_BAND 3 ,
.Xr d2i_OSSL_NAMED_DAY 3 ,
.Xr d2i_OSSL_TIME_PERIOD 3 ,
.Xr d2i_OSSL_TIME_SPEC 3 ,
.Xr d2i_OSSL_TIME_SPEC_ABSOLUTE 3 ,
.Xr d2i_OSSL_TIME_SPEC_DAY 3 ,
.Xr d2i_OSSL_TIME_SPEC_MONTH 3 ,
.Xr d2i_OSSL_TIME_SPEC_TIME 3 ,
.Xr d2i_OSSL_TIME_SPEC_WEEKS 3 ,
.Xr d2i_OSSL_TIME_SPEC_X_DAY_OF 3 ,
.Xr i2d_OSSL_DAY_TIME 3 ,
.Xr i2d_OSSL_DAY_TIME_BAND 3 ,
.Xr i2d_OSSL_NAMED_DAY 3 ,
.Xr i2d_OSSL_TIME_PERIOD 3 ,
.Xr i2d_OSSL_TIME_SPEC 3 ,
.Xr i2d_OSSL_TIME_SPEC_ABSOLUTE 3 ,
.Xr i2d_OSSL_TIME_SPEC_DAY 3 ,
.Xr i2d_OSSL_TIME_SPEC_MONTH 3 ,
.Xr i2d_OSSL_TIME_SPEC_TIME 3 ,
.Xr i2d_OSSL_TIME_SPEC_WEEKS 3 ,
.Xr i2d_OSSL_TIME_SPEC_X_DAY_OF 3
were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 1998-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
