.Dd 2025-09-30
.Dt D2I_SSL_SESSION 3ossl
.Os
.Sh NAME
.Nm d2i_SSL_SESSION ,
.Nm d2i_SSL_SESSION_ex ,
.Nm i2d_SSL_SESSION
.Nd convert SSL_SESSION object from/to ASN1 representation
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft SSL_SESSION *
.Fo d2i_SSL_SESSION
.Fa "SSL_SESSION **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fc
.Ft SSL_SESSION *
.Fo d2i_SSL_SESSION_ex
.Fa "SSL_SESSION **a"
.Fa "const unsigned char **pp"
.Fa "long length"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo i2d_SSL_SESSION
.Fa "SSL_SESSION *in"
.Fa "unsigned char **pp"
.Fc
.Sh DESCRIPTION
These functions decode and encode an SSL_SESSION object.
For encoding details see
.Xr d2i_X509 3 .
.Pp
SSL_SESSION objects keep internal link information about the session
cache list, when being inserted into one SSL_CTX object's session cache.
One SSL_SESSION object, regardless of its reference count, must
therefore only be used with one SSL_CTX object (and the SSL objects
created from this SSL_CTX object).
.Sh RETURN VALUES
.Fn d2i_SSL_SESSION
and
.Fn d2i_SSL_SESSION_ex
return a pointer to the newly allocated SSL_SESSION object.
In case of failure the NULL-pointer is returned and the error message
can be retrieved from the error stack.
.Pp
.Fn i2d_SSL_SESSION
returns the size of the ASN1 representation in bytes.
When the session is not valid,
.Sy 0
is returned and no operation is performed.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_SESSION_free 3 ,
.Xr SSL_CTX_sess_set_get_cb 3 ,
.Xr d2i_X509 3
.Sh HISTORY
The function
.Fn d2i_SSL_SESSION_ex
was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2001-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
