.Dd 2025-09-30
.Dt DEFINE_STACK_OF 3ossl
.Os
.Sh NAME
.Nm DEFINE_STACK_OF ,
.Nm DEFINE_STACK_OF_CONST ,
.Nm DEFINE_SPECIAL_STACK_OF ,
.Nm DEFINE_SPECIAL_STACK_OF_CONST ,
.Nm sk_TYPE_num ,
.Nm sk_TYPE_value ,
.Nm sk_TYPE_new ,
.Nm sk_TYPE_new_null ,
.Nm sk_TYPE_reserve ,
.Nm sk_TYPE_free ,
.Nm sk_TYPE_zero ,
.Nm sk_TYPE_delete ,
.Nm sk_TYPE_delete_ptr ,
.Nm sk_TYPE_push ,
.Nm sk_TYPE_unshift ,
.Nm sk_TYPE_pop ,
.Nm sk_TYPE_shift ,
.Nm sk_TYPE_pop_free ,
.Nm sk_TYPE_insert ,
.Nm sk_TYPE_set ,
.Nm sk_TYPE_find ,
.Nm sk_TYPE_find_ex ,
.Nm sk_TYPE_find_all ,
.Nm sk_TYPE_sort ,
.Nm sk_TYPE_is_sorted ,
.Nm sk_TYPE_dup ,
.Nm sk_TYPE_deep_copy ,
.Nm sk_TYPE_set_cmp_func ,
.Nm sk_TYPE_new_reserve ,
.Nm OPENSSL_sk_deep_copy ,
.Nm OPENSSL_sk_delete ,
.Nm OPENSSL_sk_delete_ptr ,
.Nm OPENSSL_sk_dup ,
.Nm OPENSSL_sk_find ,
.Nm OPENSSL_sk_find_ex ,
.Nm OPENSSL_sk_find_all ,
.Nm OPENSSL_sk_free ,
.Nm OPENSSL_sk_insert ,
.Nm OPENSSL_sk_is_sorted ,
.Nm OPENSSL_sk_new ,
.Nm OPENSSL_sk_new_null ,
.Nm OPENSSL_sk_new_reserve ,
.Nm OPENSSL_sk_num ,
.Nm OPENSSL_sk_pop ,
.Nm OPENSSL_sk_pop_free ,
.Nm OPENSSL_sk_push ,
.Nm OPENSSL_sk_reserve ,
.Nm OPENSSL_sk_set ,
.Nm OPENSSL_sk_set_cmp_func ,
.Nm OPENSSL_sk_shift ,
.Nm OPENSSL_sk_sort ,
.Nm OPENSSL_sk_unshift ,
.Nm OPENSSL_sk_value ,
.Nm OPENSSL_sk_zero
.Nd stack container
.Sh SYNOPSIS
.In openssl/safestack.h
.Bd -literal
 STACK_OF(TYPE)
 DEFINE_STACK_OF(TYPE)
 DEFINE_STACK_OF_CONST(TYPE)
 DEFINE_SPECIAL_STACK_OF(FUNCTYPE, TYPE)
 DEFINE_SPECIAL_STACK_OF_CONST(FUNCTYPE, TYPE)
.Ed
.Ft typedef int
.Fo 
.Fa *sk_TYPE_compfunc
.Fc
(const TYPE *const *a, const TYPE *const *b);
.Ft typedef TYPE *
.Fo 
.Fa *sk_TYPE_copyfunc
.Fc
(const TYPE *a);
.Ft typedef void
.Fo 
.Fa *sk_TYPE_freefunc
.Fc
(TYPE *a);
.Ft int
.Fo sk_TYPE_num
.Fa "const STACK_OF(TYPE) *sk"
.Fc
.Ft TYPE *
.Fo sk_TYPE_value
.Fa "const STACK_OF(TYPE) *sk"
.Fa "int idx"
.Fc
.Bd -literal
 STACK_OF(TYPE) *sk_TYPE_new(sk_TYPE_compfunc compare);
 STACK_OF(TYPE) *sk_TYPE_new_null(void);
 int sk_TYPE_reserve(STACK_OF(TYPE) *sk, int n);
 void sk_TYPE_free(STACK_OF(TYPE) *sk);
 void sk_TYPE_zero(STACK_OF(TYPE) *sk);
 TYPE *sk_TYPE_delete(STACK_OF(TYPE) *sk, int i);
 TYPE *sk_TYPE_delete_ptr(STACK_OF(TYPE) *sk, TYPE *ptr);
 int sk_TYPE_push(STACK_OF(TYPE) *sk, const TYPE *ptr);
 int sk_TYPE_unshift(STACK_OF(TYPE) *sk, const TYPE *ptr);
 TYPE *sk_TYPE_pop(STACK_OF(TYPE) *sk);
 TYPE *sk_TYPE_shift(STACK_OF(TYPE) *sk);
 void sk_TYPE_pop_free(STACK_OF(TYPE) *sk, sk_TYPE_freefunc freefunc);
 int sk_TYPE_insert(STACK_OF(TYPE) *sk, TYPE *ptr, int idx);
 TYPE *sk_TYPE_set(STACK_OF(TYPE) *sk, int idx, const TYPE *ptr);
 int sk_TYPE_find(STACK_OF(TYPE) *sk, TYPE *ptr);
 int sk_TYPE_find_ex(STACK_OF(TYPE) *sk, TYPE *ptr);
 int sk_TYPE_find_all(STACK_OF(TYPE) *sk, TYPE *ptr, int *pnum);
 void sk_TYPE_sort(const STACK_OF(TYPE) *sk);
 int sk_TYPE_is_sorted(const STACK_OF(TYPE) *sk);
 STACK_OF(TYPE) *sk_TYPE_dup(const STACK_OF(TYPE) *sk);
 STACK_OF(TYPE) *sk_TYPE_deep_copy(const STACK_OF(TYPE) *sk,
                                   sk_TYPE_copyfunc copyfunc,
                                   sk_TYPE_freefunc freefunc);
 sk_TYPE_compfunc (*sk_TYPE_set_cmp_func(STACK_OF(TYPE) *sk,
                                         sk_TYPE_compfunc compare));
 STACK_OF(TYPE) *sk_TYPE_new_reserve(sk_TYPE_compfunc compare, int n);
.Ed
.Sh DESCRIPTION
Applications can create and use their own stacks by placing any of the
macros described below in a header file.
These macros define typesafe inline functions that wrap around the
utility
.Sy OPENSSL_sk_
API. In the description here,
.Sy Vt TYPE
is used as a placeholder for any of the OpenSSL datatypes, such as
.Sy X509 .
.Pp
The
.Xr STACK_OF 3
macro returns the name for a stack of the specified
.Sy Vt TYPE .
This is an opaque pointer to a structure declaration.
This can be used in every header file that references the stack.
There are several
.Sy DEFINE...
macros that create static inline functions for all of the functions
described on this page.
This should normally be used in one source file, and the stack
manipulation is wrapped with application-specific functions.
.Pp
.Xr DEFINE_STACK_OF 3
creates set of functions for a stack of
.Sy Vt TYPE
elements.
The type is referenced by
.Sy STACK_OF Ns ( Ns Sy Vt TYPE )
and each function name begins with
.Sy sk_ Ns Vt TYPE Ns _ .
.Xr DEFINE_STACK_OF_CONST 3
is identical to
.Xr DEFINE_STACK_OF 3
except each element is constant.
.Bd -literal
 /* DEFINE_STACK_OF(TYPE) */
 TYPE *sk_TYPE_value(STACK_OF(TYPE) *sk, int idx);
 /* DEFINE_STACK_OF_CONST(TYPE) */
 const TYPE *sk_TYPE_value(STACK_OF(TYPE) *sk, int idx);
.Ed
.Pp
.Xr DEFINE_SPECIAL_STACK_OF 3
and
.Xr DEFINE_SPECIAL_STACK_OF_CONST 3
are similar except
.Sy FUNCNAME
is used in the function names:
.Bd -literal
 /* DEFINE_SPECIAL_STACK_OF(TYPE, FUNCNAME) */
 TYPE *sk_FUNCNAME_value(STACK_OF(TYPE) *sk, int idx);
 /* DEFINE_SPECIAL_STACK_OF(TYPE, FUNCNAME) */
 const TYPE *sk_FUNCNAME_value(STACK_OF(TYPE) *sk, int idx);
.Ed
.Pp
.Sy sk_ Ns Vt TYPE Ns _num Ns
.Xr 3
returns the number of elements in
.Fa sk
or -1 if
.Fa sk
is NULL.
.Pp
.Sy sk_ Ns Vt TYPE Ns _value Ns
.Xr 3
returns element
.Fa idx
in
.Fa sk ,
where
.Fa idx
starts at zero.
If
.Fa idx
is out of range then NULL is returned.
.Pp
.Sy sk_ Ns Vt TYPE Ns _new Ns
.Xr 3
allocates a new empty stack using comparison function
.Em compare .
If
.Em compare
is NULL then no comparison function is used.
This function is equivalent to
.Sy sk_ Ns Vt TYPE Ns _new_reserve Ns ( Ns Em compare ,
0).
.Pp
.Sy sk_ Ns Vt TYPE Ns _new_null Ns
.Xr 3
allocates a new empty stack with no comparison function.
This function is equivalent to
.Sy sk_ Ns Vt TYPE Ns _new_reserve Ns (NULL,
0).
.Pp
.Sy sk_ Ns Vt TYPE Ns _reserve Ns
.Xr 3
allocates additional memory in the
.Fa sk
structure such that the next
.Em n
calls to
.Sy sk_ Ns Vt TYPE Ns _insert Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _push Ns
.Xr 3
or
.Sy sk_ Ns Vt TYPE Ns _unshift Ns
.Xr 3
will not fail or cause memory to be allocated or reallocated.
If
.Em n
is zero, any excess space allocated in the
.Fa sk
structure is freed.
On error
.Fa sk
is unchanged.
.Pp
.Sy sk_ Ns Vt TYPE Ns _new_reserve Ns
.Xr 3
allocates a new stack.
The new stack will have additional memory allocated to hold
.Em n
elements if
.Em n
is positive.
The next
.Em n
calls to
.Sy sk_ Ns Vt TYPE Ns _insert Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _push Ns
.Xr 3
or
.Sy sk_ Ns Vt TYPE Ns _unshift Ns
.Xr 3
will not fail or cause memory to be allocated or reallocated.
If
.Em n
is zero or less than zero, no memory is allocated.
.Sy sk_ Ns Vt TYPE Ns _new_reserve Ns
.Xr 3
also sets the comparison function
.Em compare
to the newly created stack.
If
.Em compare
is NULL then no comparison function is used.
.Pp
.Sy sk_ Ns Vt TYPE Ns _set_cmp_func Ns
.Xr 3
sets the comparison function of
.Fa sk
to
.Em compare .
The previous comparison function is returned or NULL if there was no
previous comparison function.
.Pp
.Sy sk_ Ns Vt TYPE Ns _free Ns
.Xr 3
frees up the
.Fa sk
structure.
It does
.Em not
free up any elements of
.Fa sk .
After this call
.Fa sk
is no longer valid.
.Pp
.Sy sk_ Ns Vt TYPE Ns _zero Ns
.Xr 3
sets the number of elements in
.Fa sk
to zero.
It does not free
.Fa sk
so after this call
.Fa sk
is still valid.
.Pp
.Sy sk_ Ns Vt TYPE Ns _pop_free Ns
.Xr 3
frees up all elements of
.Fa sk
and
.Fa sk
itself.
The free function
.Xr freefunc 3
is called on each element to free it.
.Pp
.Sy sk_ Ns Vt TYPE Ns _delete Ns
.Xr 3
deletes element
.Em i
from
.Fa sk .
It returns the deleted element or NULL if
.Em i
is out of range.
.Pp
.Sy sk_ Ns Vt TYPE Ns _delete_ptr Ns
.Xr 3
deletes element matching
.Em ptr
from
.Fa sk .
It returns the deleted element or NULL if no element matching
.Em ptr
was found.
.Pp
.Sy sk_ Ns Vt TYPE Ns _insert Ns
.Xr 3
inserts
.Em ptr
into
.Fa sk
at position
.Fa idx .
Any existing elements at or after
.Fa idx
are moved downwards.
If
.Fa idx
is out of range the new element is appended to
.Fa sk .
.Sy sk_ Ns Vt TYPE Ns _insert Ns
.Xr 3
either returns the number of elements in
.Fa sk
after the new element is inserted or zero if an error (such as memory
allocation failure) occurred.
.Pp
.Sy sk_ Ns Vt TYPE Ns _push Ns
.Xr 3
appends
.Em ptr
to
.Fa sk
it is equivalent to:
.Bd -literal
 sk_TYPE_insert(sk, ptr, -1);
.Ed
.Pp
.Sy sk_ Ns Vt TYPE Ns _unshift Ns
.Xr 3
inserts
.Em ptr
at the start of
.Fa sk
it is equivalent to:
.Bd -literal
 sk_TYPE_insert(sk, ptr, 0);
.Ed
.Pp
.Sy sk_ Ns Vt TYPE Ns _pop Ns
.Xr 3
returns and removes the last element from
.Fa sk .
.Pp
.Sy sk_ Ns Vt TYPE Ns _shift Ns
.Xr 3
returns and removes the first element from
.Fa sk .
.Pp
.Sy sk_ Ns Vt TYPE Ns _set Ns
.Xr 3
sets element
.Fa idx
of
.Fa sk
to
.Em ptr
replacing the current element.
The new element value is returned or NULL if an error occurred: this
will only happen if
.Fa sk
is NULL or
.Fa idx
is out of range.
.Pp
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
searches
.Fa sk
for the element
.Em ptr .
In the case where no comparison function has been specified, the
function performs a linear search for a pointer equal to
.Em ptr .
In the case where a comparison function has been specified, the function
performs a search for a element that the comparison function indicates
is a match.
If the stack is sorted, a binary search is used, otherwise, a linear
search is used.
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
returns the index of a matching element or
.Sy -1
if there is no match.
.Pp
.Sy sk_ Ns Vt TYPE Ns _find_ex Ns
.Xr 3
operates like
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
except when a comparison function has been specified and no matching
element is found.
Instead of returning
.Sy -1 ,
.Sy sk_ Ns Vt TYPE Ns _find_ex Ns
.Xr 3
returns the index of the element either before or after the location
where
.Em ptr
would be if it were present in
.Fa sk .
The function also does not guarantee that the first matching element in
the sorted stack is returned.
.Pp
.Sy sk_ Ns Vt TYPE Ns _find_all Ns
.Xr 3
operates like
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
but it also sets the
.Em *pnum
to number of matching elements in the stack.
In case no comparison function has been specified the
.Em *pnum
will be always set to 1 if matching element was found, 0 otherwise.
.Pp
.Sy sk_ Ns Vt TYPE Ns _sort Ns
.Xr 3
sorts
.Fa sk
using the supplied comparison function.
.Pp
.Sy sk_ Ns Vt TYPE Ns _is_sorted Ns
.Xr 3
returns
.Sy 1
if
.Fa sk
is sorted and
.Sy 0
otherwise.
.Pp
.Sy sk_ Ns Vt TYPE Ns _dup Ns
.Xr 3
returns a shallow copy of
.Fa sk
or an empty stack if the passed stack is NULL. Note the pointers in the
copy are identical to the original.
.Pp
.Sy sk_ Ns Vt TYPE Ns _deep_copy Ns
.Xr 3
returns a new stack where each element has been copied or an empty stack
if the passed stack is NULL. Copying is performed by the supplied
.Xr copyfunc 3
and freeing by
.Xr freefunc 3 .
The function
.Xr freefunc 3
is only called if an error occurs.
.Sh NOTES
Care should be taken when accessing stacks in multi-threaded
environments.
Any operation which increases the size of a stack such as
.Sy sk_ Ns Vt TYPE Ns _insert Ns
.Xr 3
or
.Sy sk_ Ns Vt TYPE Ns _push Ns
.Xr 3
can "grow" the size of an internal array and cause race conditions if
the same stack is accessed in a different thread.
Operations such as
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _sort Ns
.Xr 3
can also reorder the stack.
.Pp
Any comparison function supplied should use a metric suitable for use in
a binary search operation.
That is it should return zero, a positive or negative value if
.Em a
is equal to, greater than or less than
.Em b
respectively.
.Pp
Care should be taken when checking the return values of the functions
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _find_ex Ns
.Xr 3 .
They return an index to the matching element.
In particular
.Sy 0
indicates a matching first element.
A failed search is indicated by a
.Sy -1
return value.
.Pp
.Xr STACK_OF 3 ,
.Xr DEFINE_STACK_OF 3 ,
.Xr DEFINE_STACK_OF_CONST 3 ,
and
.Xr DEFINE_SPECIAL_STACK_OF 3
are implemented as macros.
.Pp
It is not an error to call
.Sy sk_ Ns Vt TYPE Ns _num Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _value Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _free Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _zero Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _pop_free Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _delete Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _delete_ptr Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _pop Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _shift Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _find_ex Ns
.Xr 3 ,
and
.Sy sk_ Ns Vt TYPE Ns _find_all Ns
.Xr 3
on a NULL stack, empty stack, or with an invalid index.
An error is not raised in these conditions.
.Pp
The underlying utility
.Sy OPENSSL_sk_
API should not be used directly.
It defines these functions:
.Xr OPENSSL_sk_deep_copy 3 ,
.Xr OPENSSL_sk_delete 3 ,
.Xr OPENSSL_sk_delete_ptr 3 ,
.Xr OPENSSL_sk_dup 3 ,
.Xr OPENSSL_sk_find 3 ,
.Xr OPENSSL_sk_find_ex 3 ,
.Xr OPENSSL_sk_find_all 3 ,
.Xr OPENSSL_sk_free 3 ,
.Xr OPENSSL_sk_insert 3 ,
.Xr OPENSSL_sk_is_sorted 3 ,
.Xr OPENSSL_sk_new 3 ,
.Xr OPENSSL_sk_new_null 3 ,
.Xr OPENSSL_sk_new_reserve 3 ,
.Xr OPENSSL_sk_num 3 ,
.Xr OPENSSL_sk_pop 3 ,
.Xr OPENSSL_sk_pop_free 3 ,
.Xr OPENSSL_sk_push 3 ,
.Xr OPENSSL_sk_reserve 3 ,
.Xr OPENSSL_sk_set 3 ,
.Xr OPENSSL_sk_set_cmp_func 3 ,
.Xr OPENSSL_sk_shift 3 ,
.Xr OPENSSL_sk_sort 3 ,
.Xr OPENSSL_sk_unshift 3 ,
.Xr OPENSSL_sk_value 3 ,
.Xr OPENSSL_sk_zero 3 .
.Sh RETURN VALUES
.Sy sk_ Ns Vt TYPE Ns _num Ns
.Xr 3
returns the number of elements in the stack or
.Sy -1
if the passed stack is NULL.
.Pp
.Sy sk_ Ns Vt TYPE Ns _value Ns
.Xr 3
returns a pointer to a stack element or NULL if the index is out of
range.
.Pp
.Sy sk_ Ns Vt TYPE Ns _new Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _new_null Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _new_reserve Ns
.Xr 3
return an empty stack or NULL if an error occurs.
.Pp
.Sy sk_ Ns Vt TYPE Ns _reserve Ns
.Xr 3
returns
.Sy 1
on successful allocation of the required memory or
.Sy 0
on error.
.Pp
.Sy sk_ Ns Vt TYPE Ns _set_cmp_func Ns
.Xr 3
returns the old comparison function or NULL if there was no old
comparison function.
.Pp
.Sy sk_ Ns Vt TYPE Ns _free Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _zero Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _pop_free Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _sort Ns
.Xr 3
do not return values.
.Pp
.Sy sk_ Ns Vt TYPE Ns _pop Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _shift Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _delete Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _delete_ptr Ns
.Xr 3
return a pointer to the deleted element or NULL on error.
.Pp
.Sy sk_ Ns Vt TYPE Ns _insert Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _push Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _unshift Ns
.Xr 3
return the total number of elements in the stack and 0 if an error
occurred.
.Pp
.Sy sk_ Ns Vt TYPE Ns _set Ns
.Xr 3
returns a pointer to the replacement element or NULL on error.
.Pp
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _find_ex Ns
.Xr 3
return an index to the found element or
.Sy -1
on error.
.Pp
.Sy sk_ Ns Vt TYPE Ns _is_sorted Ns
.Xr 3
returns
.Sy 1
if the stack is sorted and
.Sy 0
if it is not.
.Pp
.Sy sk_ Ns Vt TYPE Ns _dup Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _deep_copy Ns
.Xr 3
return a pointer to the copy of the stack or NULL on error.
.Sh HISTORY
Before OpenSSL 1.1.0, this was implemented via macros and not inline
functions and was not a public API.
.Pp
.Sy sk_ Ns Vt TYPE Ns _reserve Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _new_reserve Ns
.Xr 3
were added in OpenSSL 1.1.1.
.Pp
From OpenSSL 3.2.0, the
.Sy sk_ Ns Vt TYPE Ns _find Ns
.Xr 3 ,
.Sy sk_ Ns Vt TYPE Ns _find_ex Ns
.Xr 3
and
.Sy sk_ Ns Vt TYPE Ns _find_all Ns
.Xr 3
calls are read-only and do not sort the stack.
To avoid any performance implications this change introduces,
.Sy sk_ Ns Vt TYPE Ns _sort Ns
.Xr 3
should be called before these find operations.
.Pp
Before OpenSSL 3.3.0
.Sy sk_ Ns Vt TYPE Ns _push Ns
.Xr 3
returned -1 if
.Fa sk
was NULL. It was changed to return 0 in this condition as for other
errors.
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
