.Dd 2025-09-30
.Dt DH_GET0_PQG 3ossl
.Os
.Sh NAME
.Nm DH_get0_pqg ,
.Nm DH_set0_pqg ,
.Nm DH_get0_key ,
.Nm DH_set0_key ,
.Nm DH_get0_p ,
.Nm DH_get0_q ,
.Nm DH_get0_g ,
.Nm DH_get0_priv_key ,
.Nm DH_get0_pub_key ,
.Nm DH_clear_flags ,
.Nm DH_test_flags ,
.Nm DH_set_flags ,
.Nm DH_get0_engine ,
.Nm DH_get_length ,
.Nm DH_set_length
.Nd Routines for getting and setting data in a DH object
.Sh SYNOPSIS
.In openssl/dh.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo DH_get0_pqg
.Fa "const DH *dh"
.Fa "const BIGNUM **p"
.Fa "const BIGNUM **q"
.Fa "const BIGNUM **g"
.Fc
.Ft int
.Fo DH_set0_pqg
.Fa "DH *dh"
.Fa "BIGNUM *p"
.Fa "BIGNUM *q"
.Fa "BIGNUM *g"
.Fc
.Ft void
.Fo DH_get0_key
.Fa "const DH *dh"
.Fa "const BIGNUM **pub_key"
.Fa "const BIGNUM **priv_key"
.Fc
.Ft int
.Fo DH_set0_key
.Fa "DH *dh"
.Fa "BIGNUM *pub_key"
.Fa "BIGNUM *priv_key"
.Fc
.Ft const BIGNUM *
.Fo DH_get0_p
.Fa "const DH *dh"
.Fc
.Ft const BIGNUM *
.Fo DH_get0_q
.Fa "const DH *dh"
.Fc
.Ft const BIGNUM *
.Fo DH_get0_g
.Fa "const DH *dh"
.Fc
.Ft const BIGNUM *
.Fo DH_get0_priv_key
.Fa "const DH *dh"
.Fc
.Ft const BIGNUM *
.Fo DH_get0_pub_key
.Fa "const DH *dh"
.Fc
.Ft void
.Fo DH_clear_flags
.Fa "DH *dh"
.Fa "int flags"
.Fc
.Ft int
.Fo DH_test_flags
.Fa "const DH *dh"
.Fa "int flags"
.Fc
.Ft void
.Fo DH_set_flags
.Fa "DH *dh"
.Fa "int flags"
.Fc
.Ft long
.Fo DH_get_length
.Fa "const DH *dh"
.Fc
.Ft int
.Fo DH_set_length
.Fa "DH *dh"
.Fa "long length"
.Fc
.Ft ENGINE *
.Fo DH_get0_engine
.Fa "DH *d"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_get_bn_param 3
for any methods that return a
.Vt BIGNUM .
Refer to
.Xr EVP_PKEY-DH 7
for more information.
.Pp
A DH object contains the parameters
.Fa p ,
.Fa q
and
.Fa g .
Note that the
.Fa q
parameter is optional.
It also contains a public key
.Pf ( Fa pub_key )
and (optionally) a private key
.Pf ( Fa priv_key Ns ).
.Pp
The
.Fa p ,
.Fa q
and
.Fa g
parameters can be obtained by calling
.Fn DH_get0_pqg .
If the parameters have not yet been set then
.Em *p ,
.Em *q
and
.Em *g
will be set to NULL. Otherwise they are set to pointers to their
respective values.
These point directly to the internal representations of the values and
therefore should not be freed directly.
Any of the out parameters
.Fa p ,
.Fa q ,
and
.Fa g
can be NULL, in which case no value will be returned for that parameter.
.Pp
The
.Fa p ,
.Fa q
and
.Fa g
values can be set by calling
.Fn DH_set0_pqg
and passing the new values for
.Fa p ,
.Fa q
and
.Fa g
as parameters to the function.
Calling this function transfers the memory management of the values to
the DH object, and therefore the values that have been passed in should
not be freed directly after this function has been called.
The
.Fa q
parameter may be NULL.
.Fn DH_set0_pqg
also checks if the parameters associated with
.Fa p
and
.Fa g
and optionally
.Fa q
are associated with known safe prime groups.
If it is a safe prime group then the value of
.Fa q
will be set to q = (p - 1) / 2 if
.Fa q
is NULL. The optional length parameter will be set to
.Pf BN_num_bits( Fa q )
if
.Fa q
is not NULL.
.Pp
To get the public and private key values use the
.Fn DH_get0_key
function.
A pointer to the public key will be stored in
.Em *pub_key ,
and a pointer to the private key will be stored in
.Em *priv_key .
Either may be NULL if they have not been set yet, although if the
private key has been set then the public key must be.
The values point to the internal representation of the public key and
private key values.
This memory should not be freed directly.
Any of the out parameters
.Fa pub_key
and
.Fa priv_key
can be NULL, in which case no value will be returned for that parameter.
.Pp
The public and private key values can be set using
.Fn DH_set0_key .
Either parameter may be NULL, which means the corresponding DH field is
left untouched.
As with
.Fn DH_set0_pqg
this function transfers the memory management of the key values to the
DH object, and therefore they should not be freed directly after this
function has been called.
.Pp
Any of the values
.Fa p ,
.Fa q ,
.Fa g ,
.Fa priv_key ,
and
.Fa pub_key
can also be retrieved separately by the corresponding function
.Fn DH_get0_p ,
.Fn DH_get0_q ,
.Fn DH_get0_g ,
.Fn DH_get0_priv_key ,
and
.Fn DH_get0_pub_key ,
respectively.
.Pp
.Fn DH_set_flags
sets the flags in the
.Fa flags
parameter on the DH object.
Multiple flags can be passed in one go (bitwise ORed together).
Any flags that are already set are left set.
.Fn DH_test_flags
tests to see whether the flags passed in the
.Fa flags
parameter are currently set in the DH object.
Multiple flags can be tested in one go.
All flags that are currently set are returned, or zero if none of the
flags are set.
.Fn DH_clear_flags
clears the specified flags within the DH object.
.Pp
.Fn DH_get0_engine
returns a handle to the ENGINE that has been set for this DH object, or
NULL if no such ENGINE has been set.
This function is deprecated.
All engines should be replaced by providers.
.Pp
The
.Fn DH_get_length
and
.Fn DH_set_length
functions get and set the optional length parameter associated with this
DH object.
If the length is nonzero then it is used, otherwise it is ignored.
The
.Fa length
parameter indicates the length of the secret exponent (private key) in
bits.
For safe prime groups the optional length parameter
.Fa length
can be set to a value greater or equal to 2 *
.Pf maximum_target_security_strength(BN_num_bits( Fa p Ns ))
as listed in SP800-56Ar3 Table(s) 25 & 26. These functions are
deprecated and should be replaced with
.Xr EVP_PKEY_CTX_set_params 3
and
.Xr EVP_PKEY_get_int_param 3
using the parameter key
.Sy OSSL_PKEY_PARAM_DH_PRIV_LEN
as described in
.Xr EVP_PKEY-DH 7 .
.Sh NOTES
Values retrieved with
.Fn DH_get0_key
are owned by the DH object used in the call and may therefore
.Em not
be passed to
.Fn DH_set0_key .
If needed, duplicate the received value using
.Xr BN_dup 3
and pass the duplicate.
The same applies to
.Fn DH_get0_pqg
and
.Fn DH_set0_pqg .
.Sh RETURN VALUES
.Fn DH_set0_pqg
and
.Fn DH_set0_key
return 1 on success or 0 on failure.
.Pp
.Fn DH_get0_p ,
.Fn DH_get0_q ,
.Fn DH_get0_g ,
.Fn DH_get0_priv_key ,
and
.Fn DH_get0_pub_key
return the respective value, or NULL if it is unset.
.Pp
.Fn DH_test_flags
returns the current state of the flags in the DH object.
.Pp
.Fn DH_get0_engine
returns the ENGINE set for the DH object or NULL if no ENGINE has been
set.
.Pp
.Fn DH_get_length
returns the length of the secret exponent (private key) in bits, or zero
if no such length has been explicitly set.
.Sh SEE ALSO
.Xr DH_new 3 ,
.Xr DH_new 3 ,
.Xr DH_generate_parameters 3 ,
.Xr DH_generate_key 3 ,
.Xr DH_set_method 3 ,
.Xr DH_size 3 ,
.Xr DH_meth_new 3
.Sh HISTORY
The functions described here were added in OpenSSL 1.1.0.
.Pp
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
