.Dd 2025-09-30
.Dt DH_GENERATE_PARAMETERS 3ossl
.Os
.Sh NAME
.Nm DH_generate_parameters_ex ,
.Nm DH_generate_parameters ,
.Nm DH_check ,
.Nm DH_check_params ,
.Nm DH_check_ex ,
.Nm DH_check_params_ex ,
.Nm DH_check_pub_key_ex
.Nd generate and check Diffie-Hellman parameters
.Sh SYNOPSIS
.In openssl/dh.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo DH_generate_parameters_ex
.Fa "DH *dh"
.Fa "int prime_len"
.Fa "int generator"
.Fa "BN_GENCB *cb"
.Fc
.Ft int
.Fo DH_check
.Fa "DH *dh"
.Fa "int *codes"
.Fc
.Ft int
.Fo DH_check_params
.Fa "DH *dh"
.Fa "int *codes"
.Fc
.Ft int
.Fo DH_check_ex
.Fa "const DH *dh"
.Fc
.Ft int
.Fo DH_check_params_ex
.Fa "const DH *dh"
.Fc
.Ft int
.Fo DH_check_pub_key_ex
.Fa "const DH *dh"
.Fa "const BIGNUM *pub_key"
.Fc
.Pp
The following functions have been deprecated since OpenSSL 0.9.8, and
can be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft DH *
.Fo DH_generate_parameters
.Fa "int prime_len"
.Fa "int generator"
.Fa "void (*callback)(int"
.Fa int
.Fa "void *)"
.Fa "void *cb_arg"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_check 3 ,
.Xr EVP_PKEY_public_check 3 ,
.Xr EVP_PKEY_private_check 3
and
.Xr EVP_PKEY_param_check 3 .
.Pp
.Fn DH_generate_parameters_ex
generates Diffie-Hellman parameters that can be shared among a group of
users, and stores them in the provided
.Vt DH
structure.
The pseudo-random number generator must be seeded before calling it.
The parameters generated by
.Fn DH_generate_parameters_ex
should not be used in signature schemes.
.Pp
.Fa prime_len
is the length in bits of the safe prime to be generated.
.Fa generator
is a small number \(ra 1, typically 2 or 5.
.Pp
A callback function may be used to provide feedback about the progress
of the key generation.
If
.Fa cb
is not
.Dv NULL ,
it will be called as described in
.Xr BN_generate_prime 3
while a random prime number is generated, and when a prime has been
found,
.Sy BN_GENCB_call(cb, 3, 0)
is called.
See
.Xr BN_generate_prime_ex 3
for information on the
.Xr BN_GENCB_call 3
function.
.Pp
.Fn DH_generate_parameters
is similar to
.Xr DH_generate_prime_ex 3
but expects an old-style callback function; see
.Xr BN_generate_prime 3
for information on the old-style callback.
.Pp
.Fn DH_check_params
confirms that the
.Sy p
and
.Sy g
are likely enough to be valid.
This is a lightweight check, if a more thorough check is needed, use
.Fn DH_check .
The value of
.Sy *codes
is updated with any problems found.
If
.Sy *codes
is zero then no problems were found, otherwise the following bits may be
set:
.Bl -tag -width Ds
.It DH_CHECK_P_NOT_PRIME
The parameter
.Sy p
has been determined to not being an odd prime.
Note that the lack of this bit doesn't guarantee that
.Sy p
is a prime.
.It DH_NOT_SUITABLE_GENERATOR
The generator
.Sy g
is not suitable.
Note that the lack of this bit doesn't guarantee that
.Sy g
is suitable, unless
.Sy p
is known to be a strong prime.
.It DH_MODULUS_TOO_SMALL
The modulus is too small.
.It DH_MODULUS_TOO_LARGE
The modulus is too large.
.El
.Pp
.Fn DH_check
confirms that the Diffie-Hellman parameters
.Fa dh
are valid.
The value of
.Sy *codes
is updated with any problems found.
If
.Sy *codes
is zero then no problems were found, otherwise the following bits may be
set:
.Bl -tag -width Ds
.It DH_CHECK_P_NOT_PRIME
The parameter
.Sy p
is not prime.
.It DH_CHECK_P_NOT_SAFE_PRIME
The parameter
.Sy p
is not a safe prime and no
.Sy q
value is present.
.It DH_UNABLE_TO_CHECK_GENERATOR
The generator
.Sy g
cannot be checked for suitability.
.It DH_NOT_SUITABLE_GENERATOR
The generator
.Sy g
is not suitable.
.It DH_CHECK_Q_NOT_PRIME
The parameter
.Sy q
is not prime.
.It DH_CHECK_INVALID_Q_VALUE
The parameter
.Sy q
is invalid.
.It DH_CHECK_INVALID_J_VALUE
The parameter
.Sy j
is invalid.
.El
.Pp
If 0 is returned or
.Sy *codes
is set to a nonzero value the supplied parameters should not be used for
Diffie-Hellman operations otherwise the security properties of the key
exchange are not guaranteed.
.Pp
.Fn DH_check_ex ,
.Fn DH_check_params
and
.Fn DH_check_pub_key_ex
are similar to
.Fn DH_check
and
.Fn DH_check_params
respectively, but the error reasons are added to the thread's error
queue instead of provided as return values from the function.
.Sh RETURN VALUES
.Fn DH_generate_parameters_ex ,
.Fn DH_check
and
.Fn DH_check_params
return 1 if the check could be performed, 0 otherwise.
.Pp
.Fn DH_generate_parameters
returns a pointer to the DH structure or NULL if the parameter
generation fails.
.Pp
.Fn DH_check_ex ,
.Fn DH_check_params
and
.Fn DH_check_pub_key_ex
return 1 if the check is successful, 0 for failed.
.Pp
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr DH_new 3 ,
.Xr ERR_get_error 3 ,
.Xr RAND_bytes 3 ,
.Xr DH_free 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
.Fn DH_generate_parameters
was deprecated in OpenSSL 0.9.8; use
.Fn DH_generate_parameters_ex
instead.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
