.Dd 2025-09-30
.Dt DH_GET_1024_160 3ossl
.Os
.Sh NAME
.Nm DH_get_1024_160 ,
.Nm DH_get_2048_224 ,
.Nm DH_get_2048_256 ,
.Nm BN_get0_nist_prime_192 ,
.Nm BN_get0_nist_prime_224 ,
.Nm BN_get0_nist_prime_256 ,
.Nm BN_get0_nist_prime_384 ,
.Nm BN_get0_nist_prime_521 ,
.Nm BN_get_rfc2409_prime_768 ,
.Nm BN_get_rfc2409_prime_1024 ,
.Nm BN_get_rfc3526_prime_1536 ,
.Nm BN_get_rfc3526_prime_2048 ,
.Nm BN_get_rfc3526_prime_3072 ,
.Nm BN_get_rfc3526_prime_4096 ,
.Nm BN_get_rfc3526_prime_6144 ,
.Nm BN_get_rfc3526_prime_8192
.Nd Create standardized public primes or DH pairs
.Sh SYNOPSIS
.In openssl/dh.h
.Ft const BIGNUM *
.Fo BN_get0_nist_prime_192
.Fa void
.Fc
.Ft const BIGNUM *
.Fo BN_get0_nist_prime_224
.Fa void
.Fc
.Ft const BIGNUM *
.Fo BN_get0_nist_prime_256
.Fa void
.Fc
.Ft const BIGNUM *
.Fo BN_get0_nist_prime_384
.Fa void
.Fc
.Ft const BIGNUM *
.Fo BN_get0_nist_prime_521
.Fa void
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc2409_prime_768
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc2409_prime_1024
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc3526_prime_1536
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc3526_prime_2048
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc3526_prime_3072
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc3526_prime_4096
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc3526_prime_6144
.Fa "BIGNUM *bn"
.Fc
.Ft BIGNUM *
.Fo BN_get_rfc3526_prime_8192
.Fa "BIGNUM *bn"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.In openssl/dh.h
.Ft DH *
.Fo DH_get_1024_160
.Fa void
.Fc
.Ft DH *
.Fo DH_get_2048_224
.Fa void
.Fc
.Ft DH *
.Fo DH_get_2048_256
.Fa void
.Fc
.Sh DESCRIPTION
.Fn DH_get_1024_160 ,
.Fn DH_get_2048_224 ,
and
.Fn DH_get_2048_256
each return a DH object for the IETF RFC 5114 value.
These functions are deprecated.
Applications should instead use
.Xr EVP_PKEY_CTX_set_dh_rfc5114 3
and
.Xr EVP_PKEY_CTX_set_dhx_rfc5114 3
as described in
.Xr EVP_PKEY_CTX_ctrl 3
or by setting the
.Sy OSSL_PKEY_PARAM_GROUP_NAME
as specified in
.Xr EVP_PKEY-DH 7 )
to one of "dh_1024_160", "dh_2048_224" or "dh_2048_256".
.Pp
.Fn BN_get0_nist_prime_192 ,
.Fn BN_get0_nist_prime_224 ,
.Fn BN_get0_nist_prime_256 ,
.Fn BN_get0_nist_prime_384 ,
and
.Fn BN_get0_nist_prime_521
functions return a BIGNUM for the specific NIST prime curve (e.g.,
P-256).
.Pp
.Fn BN_get_rfc2409_prime_768 ,
.Fn BN_get_rfc2409_prime_1024 ,
.Fn BN_get_rfc3526_prime_1536 ,
.Fn BN_get_rfc3526_prime_2048 ,
.Fn BN_get_rfc3526_prime_3072 ,
.Fn BN_get_rfc3526_prime_4096 ,
.Fn BN_get_rfc3526_prime_6144 ,
and
.Fn BN_get_rfc3526_prime_8192
functions return a BIGNUM for the specified size from IETF RFC 2409. If
.Fa bn
is not NULL, the BIGNUM will be set into that location as well.
.Sh RETURN VALUES
Defined above.
.Sh HISTORY
The functions
.Fn DH_get_1024_160 ,
.Fn DH_get_2048_224
and
.Fn DH_get_2048_256
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
