.Dd 2025-09-30
.Dt DH_GENERATE_KEY 3ossl
.Os
.Sh NAME
.Nm DH_generate_key ,
.Nm DH_compute_key ,
.Nm DH_compute_key_padded
.Nd perform Diffie-Hellman key exchange
.Sh SYNOPSIS
.In openssl/dh.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo DH_generate_key
.Fa "DH *dh"
.Fc
.Ft int
.Fo DH_compute_key
.Fa "unsigned char *key"
.Fa "const BIGNUM *pub_key"
.Fa "DH *dh"
.Fc
.Ft int
.Fo DH_compute_key_padded
.Fa "unsigned char *key"
.Fa "const BIGNUM *pub_key"
.Fa "DH *dh"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_derive_init 3
and
.Xr EVP_PKEY_derive 3 .
.Pp
.Fn DH_generate_key
performs the first step of a Diffie-Hellman key exchange by generating
private and public DH values.
By calling
.Fn DH_compute_key
or
.Fn DH_compute_key_padded ,
these are combined with the other party's public value to compute the
shared key.
.Pp
.Fn DH_generate_key
expects
.Fa dh
to contain the shared parameters
.Sy dh-\(rap
and
.Sy dh-\(rag .
It generates a random private DH value unless
.Sy dh-\(rapriv_key
is already set, and computes the corresponding public value
.Sy dh-\(rapub_key ,
which can then be published.
.Pp
.Fn DH_compute_key
computes the shared secret from the private DH value in
.Fa dh
and the other party's public value in
.Fa pub_key
and stores it in
.Fa key .
.Fa key
must point to
.Sy DH_size(dh)
bytes of memory.
The padding style is RFC 5246 (8.1.2) that strips leading zero bytes.
It is not constant time due to the leading zero bytes being stripped.
The return value should be considered public.
.Pp
.Fn DH_compute_key_padded
is similar but stores a fixed number of bytes.
The padding style is NIST SP 800-56A (C.1) that retains leading zero
bytes.
It is constant time due to the leading zero bytes being retained.
The return value should be considered public.
.Sh RETURN VALUES
.Fn DH_generate_key
returns 1 on success, 0 otherwise.
.Pp
.Fn DH_compute_key
returns the size of the shared secret on success, -1 on error.
.Pp
.Fn DH_compute_key_padded
returns
.Sy DH_size(dh)
on success, -1 on error.
.Pp
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr EVP_PKEY_derive 3 ,
.Xr DH_new 3 ,
.Xr ERR_get_error 3 ,
.Xr RAND_bytes 3 ,
.Xr DH_size 3
.Sh HISTORY
.Fn DH_compute_key_padded
was added in OpenSSL 1.0.2.
.Pp
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
