.Dd 2025-09-30
.Dt DH_METH_NEW 3ossl
.Os
.Sh NAME
.Nm DH_meth_new ,
.Nm DH_meth_free ,
.Nm DH_meth_dup ,
.Nm DH_meth_get0_name ,
.Nm DH_meth_set1_name ,
.Nm DH_meth_get_flags ,
.Nm DH_meth_set_flags ,
.Nm DH_meth_get0_app_data ,
.Nm DH_meth_set0_app_data ,
.Nm DH_meth_get_generate_key ,
.Nm DH_meth_set_generate_key ,
.Nm DH_meth_get_compute_key ,
.Nm DH_meth_set_compute_key ,
.Nm DH_meth_get_bn_mod_exp ,
.Nm DH_meth_set_bn_mod_exp ,
.Nm DH_meth_get_init ,
.Nm DH_meth_set_init ,
.Nm DH_meth_get_finish ,
.Nm DH_meth_set_finish ,
.Nm DH_meth_get_generate_params ,
.Nm DH_meth_set_generate_params
.Nd Routines to build up DH methods
.Sh SYNOPSIS
.In openssl/dh.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft DH_METHOD *
.Fo DH_meth_new
.Fa "const char *name"
.Fa "int flags"
.Fc
.Ft void
.Fo DH_meth_free
.Fa "DH_METHOD *dhm"
.Fc
.Ft DH_METHOD *
.Fo DH_meth_dup
.Fa "const DH_METHOD *dhm"
.Fc
.Ft const char *
.Fo DH_meth_get0_name
.Fa "const DH_METHOD *dhm"
.Fc
.Ft int
.Fo DH_meth_set1_name
.Fa "DH_METHOD *dhm"
.Fa "const char *name"
.Fc
.Ft int
.Fo DH_meth_get_flags
.Fa "const DH_METHOD *dhm"
.Fc
.Ft int
.Fo DH_meth_set_flags
.Fa "DH_METHOD *dhm"
.Fa "int flags"
.Fc
.Ft void *
.Fo DH_meth_get0_app_data
.Fa "const DH_METHOD *dhm"
.Fc
.Ft int
.Fo DH_meth_set0_app_data
.Fa "DH_METHOD *dhm"
.Fa "void *app_data"
.Fc
.Ft int
.Fo 
.Fa "*DH_meth_get_generate_key(const DH_METHOD *dhm)"
.Fc
(DH *);
.Ft int
.Fo DH_meth_set_generate_key
.Fa "DH_METHOD *dhm"
.Fa "int (*generate_key)(DH *)"
.Fc
.Ft int
.Fo 
.Fa "*DH_meth_get_compute_key(const DH_METHOD *dhm)"
.Fc
.Bd -literal
     (unsigned char *key, const BIGNUM *pub_key, DH *dh);
 int DH_meth_set_compute_key(DH_METHOD *dhm,
     int (*compute_key)(unsigned char *key, const BIGNUM *pub_key, DH *dh));
.Ed
.Ft int
.Fo 
.Fa "*DH_meth_get_bn_mod_exp(const DH_METHOD *dhm)"
.Fc
.Bd -literal
     (const DH *dh, BIGNUM *r, const BIGNUM *a, const BIGNUM *p,
      const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx);
 int DH_meth_set_bn_mod_exp(DH_METHOD *dhm,
     int (*bn_mod_exp)(const DH *dh, BIGNUM *r, const BIGNUM *a,
                       const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx,
                       BN_MONT_CTX *m_ctx));
.Ed
.Ft int
.Fo 
.Fa "*DH_meth_get_init(const DH_METHOD *dhm)"
.Fc
(DH *);
.Ft int
.Fo DH_meth_set_init
.Fa "DH_METHOD *dhm"
.Fa "int (*init)(DH *)"
.Fc
.Ft int
.Fo 
.Fa "*DH_meth_get_finish(const DH_METHOD *dhm)"
.Fc
(DH *);
.Ft int
.Fo DH_meth_set_finish
.Fa "DH_METHOD *dhm"
.Fa "int (*finish)(DH *)"
.Fc
.Ft int
.Fo 
.Fa "*DH_meth_get_generate_params(const DH_METHOD *dhm)"
.Fc
.Bd -literal
     (DH *, int, int, BN_GENCB *);
 int DH_meth_set_generate_params(DH_METHOD *dhm,
     int (*generate_params)(DH *, int, int, BN_GENCB *));
.Ed
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the provider APIs.
.Pp
The
.Vt DH_METHOD
type is a structure used for the provision of custom DH implementations.
It provides a set of functions used by OpenSSL for the implementation of
the various DH capabilities.
.Pp
.Fn DH_meth_new
creates a new
.Vt DH_METHOD
structure.
It should be given a unique
.Fa name
and a set of
.Fa flags .
The
.Fa name
should be a NULL terminated string, which will be duplicated and stored
in the
.Vt DH_METHOD
object.
It is the callers responsibility to free the original string.
The flags will be used during the construction of a new
.Sy DH
object based on this
.Vt DH_METHOD .
Any new
.Sy DH
object will have those flags set by default.
.Pp
.Fn DH_meth_dup
creates a duplicate copy of the
.Vt DH_METHOD
object passed as a parameter.
This might be useful for creating a new
.Vt DH_METHOD
based on an existing one, but with some differences.
.Pp
.Fn DH_meth_free
destroys a
.Vt DH_METHOD
structure and frees up any memory associated with it.
If the argument is NULL, nothing is done.
.Pp
.Fn DH_meth_get0_name
will return a pointer to the name of this DH_METHOD. This is a pointer
to the internal name string and so should not be freed by the caller.
.Fn DH_meth_set1_name
sets the name of the DH_METHOD to
.Fa name .
The string is duplicated and the copy is stored in the DH_METHOD
structure, so the caller remains responsible for freeing the memory
associated with the name.
.Pp
.Fn DH_meth_get_flags
returns the current value of the flags associated with this DH_METHOD.
.Fn DH_meth_set_flags
provides the ability to set these flags.
.Pp
The functions
.Fn DH_meth_get0_app_data
and
.Fn DH_meth_set0_app_data
provide the ability to associate implementation specific data with the
DH_METHOD. It is the application's responsibility to free this data
before the DH_METHOD is freed via a call to
.Fn DH_meth_free .
.Pp
.Xr DH_meth_get_generate_key 3
and
.Fn DH_meth_set_generate_key
get and set the function used for generating a new DH key pair
respectively.
This function will be called in response to the application calling
.Xr DH_generate_key 3 .
The parameter for the function has the same meaning as for
.Xr DH_generate_key 3 .
.Pp
.Xr DH_meth_get_compute_key 3
and
.Xr DH_meth_set_compute_key 3
get and set the function used for computing a new DH shared secret
respectively.
This function will be called in response to the application calling
.Xr DH_compute_key 3 .
The parameters for the function have the same meaning as for
.Xr DH_compute_key 3 .
.Pp
.Xr DH_meth_get_bn_mod_exp 3
and
.Xr DH_meth_set_bn_mod_exp 3
get and set the function used for computing the following value:
.Bd -literal
 r = a ^ p mod m
.Ed
.Pp
This function will be called by the default OpenSSL function for
.Xr DH_generate_key 3 .
The result is stored in the
.Sy r
parameter.
This function may be NULL unless using the default generate key
function, in which case it must be present.
.Pp
.Xr DH_meth_get_init 3
and
.Fn DH_meth_set_init
get and set the function used for creating a new DH instance
respectively.
This function will be called in response to the application calling
.Xr DH_new 3
(if the current default DH_METHOD is this one) or
.Xr DH_new_method 3 .
The
.Xr DH_new 3
and
.Xr DH_new_method 3
functions will allocate the memory for the new DH object, and a pointer
to this newly allocated structure will be passed as a parameter to the
function.
This function may be NULL.
.Pp
.Xr DH_meth_get_finish 3
and
.Fn DH_meth_set_finish
get and set the function used for destroying an instance of a DH object
respectively.
This function will be called in response to the application calling
.Xr DH_free 3 .
A pointer to the DH to be destroyed is passed as a parameter.
The destroy function should be used for DH implementation specific clean
up.
The memory for the DH itself should not be freed by this function.
This function may be NULL.
.Pp
.Xr DH_meth_get_generate_params 3
and
.Xr DH_meth_set_generate_params 3
get and set the function used for generating DH parameters respectively.
This function will be called in response to the application calling
.Xr DH_generate_parameters_ex 3
(or
.Xr DH_generate_parameters 3 ) .
The parameters for the function have the same meaning as for
.Xr DH_generate_parameters_ex 3 .
This function may be NULL.
.Sh RETURN VALUES
.Fn DH_meth_new
and
.Fn DH_meth_dup
return the newly allocated DH_METHOD object or NULL on failure.
.Pp
.Fn DH_meth_get0_name
and
.Fn DH_meth_get_flags
return the name and flags associated with the DH_METHOD respectively.
.Pp
All other
.Xr DH_meth_get_* 3
functions return the appropriate function pointer that has been set in
the DH_METHOD, or NULL if no such pointer has yet been set.
.Pp
.Fn DH_meth_set1_name
and all
.Xr DH_meth_set_* 3
functions return 1 on success or 0 on failure.
.Sh SEE ALSO
.Xr DH_new 3 ,
.Xr DH_new 3 ,
.Xr DH_generate_parameters 3 ,
.Xr DH_generate_key 3 ,
.Xr DH_set_method 3 ,
.Xr DH_size 3 ,
.Xr DH_get0_pqg 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
The functions described here were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
