.Dd 2025-09-30
.Dt DH_SET_METHOD 3ossl
.Os
.Sh NAME
.Nm DH_set_default_method ,
.Nm DH_get_default_method ,
.Nm DH_set_method ,
.Nm DH_new_method ,
.Nm DH_OpenSSL
.Nd select DH method
.Sh SYNOPSIS
.In openssl/dh.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo DH_set_default_method
.Fa "const DH_METHOD *meth"
.Fc
.Ft const DH_METHOD *
.Fo DH_get_default_method
.Fa void
.Fc
.Ft int
.Fo DH_set_method
.Fa "DH *dh"
.Fa "const DH_METHOD *meth"
.Fc
.Ft DH *
.Fo DH_new_method
.Fa "ENGINE *engine"
.Fc
.Ft const DH_METHOD *
.Fo DH_OpenSSL
.Fa void
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the provider APIs.
.Pp
A
.Sy DH_METHOD
specifies the functions that OpenSSL uses for Diffie-Hellman operations.
By modifying the method, alternative implementations such as hardware
accelerators may be used.
IMPORTANT: See the NOTES section for important information about how
these DH API functions are affected by the use of
.Vt ENGINE
API calls.
.Pp
Initially, the default DH_METHOD is the OpenSSL internal implementation,
as returned by
.Fn DH_OpenSSL .
.Pp
.Fn DH_set_default_method
makes
.Fa meth
the default method for all DH structures created later.
.Sy NB :
This is true only whilst no ENGINE has been set as a default for DH, so
this function is no longer recommended.
This function is not thread-safe and should not be called at the same
time as other OpenSSL functions.
.Pp
.Fn DH_get_default_method
returns a pointer to the current default DH_METHOD. However, the
meaningfulness of this result is dependent on whether the ENGINE API is
being used, so this function is no longer recommended.
.Pp
.Fn DH_set_method
selects
.Fa meth
to perform all operations using the key
.Fa dh .
This will replace the DH_METHOD used by the DH key and if the previous
method was supplied by an ENGINE, the handle to that ENGINE will be
released during the change.
It is possible to have DH keys that only work with certain DH_METHOD
implementations (e.g.
from an ENGINE module that supports embedded hardware-protected keys),
and in such cases attempting to change the DH_METHOD for the key can
have unexpected results.
.Pp
.Fn DH_new_method
allocates and initializes a DH structure so that
.Fa engine
will be used for the DH operations.
If
.Fa engine
is NULL, the default ENGINE for DH operations is used, and if no default
ENGINE is set, the DH_METHOD controlled by
.Fn DH_set_default_method
is used.
.Pp
A new DH_METHOD object may be constructed using
.Xr DH_meth_new 3
(see
.Xr DH_meth_new 3 Ns ).
.Sh RETURN VALUES
.Fn DH_OpenSSL
and
.Fn DH_get_default_method
return pointers to the respective
.Sy DH_METHOD Ns s.
.Pp
.Fn DH_set_default_method
returns no value.
.Pp
.Fn DH_set_method
returns nonzero if the provided
.Fa meth
was successfully set as the method for
.Fa dh
(including unloading the ENGINE handle if the previous method was
supplied by an ENGINE).
.Pp
.Fn DH_new_method
returns NULL and sets an error code that can be obtained by
.Xr ERR_get_error 3
if the allocation fails.
Otherwise it returns a pointer to the newly allocated structure.
.Sh SEE ALSO
.Xr DH_new 3 ,
.Xr DH_new 3 ,
.Xr DH_meth_new 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
