.Dd 2025-09-30
.Dt DH_SIZE 3ossl
.Os
.Sh NAME
.Nm DH_size ,
.Nm DH_bits ,
.Nm DH_security_bits
.Nd get Diffie-Hellman prime size and security bits
.Sh SYNOPSIS
.In openssl/dh.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo DH_bits
.Fa "const DH *dh"
.Fc
.Ft int
.Fo DH_size
.Fa "const DH *dh"
.Fc
.Ft int
.Fo DH_security_bits
.Fa "const DH *dh"
.Fc
.Sh DESCRIPTION
The functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_get_bits 3 ,
.Xr EVP_PKEY_get_security_bits 3
and
.Xr EVP_PKEY_get_size 3 .
.Pp
.Fn DH_bits
returns the number of significant bits.
.Pp
.Fa dh
and
.Sy dh-\(rap
must not be
.Dv NULL .
.Pp
.Fn DH_size
returns the Diffie-Hellman prime size in bytes.
It can be used to determine how much memory must be allocated for the
shared secret computed by
.Xr DH_compute_key 3 .
.Pp
.Fn DH_security_bits
returns the number of security bits of the given
.Fa dh
key.
See
.Xr BN_security_bits 3 .
.Sh RETURN VALUES
.Fn DH_bits
returns the number of bits in the key, or -1 if
.Fa dh
doesn't hold any key parameters.
.Pp
.Fn DH_size
returns the prime size of Diffie-Hellman in bytes, or -1 if
.Fa dh
doesn't hold any key parameters.
.Pp
.Fn DH_security_bits
returns the number of security bits, or -1 if
.Fa dh
doesn't hold any key parameters.
.Sh SEE ALSO
.Xr EVP_PKEY_get_bits 3 ,
.Xr DH_new 3 ,
.Xr DH_generate_key 3 ,
.Xr BN_num_bits 3
.Sh HISTORY
All functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
