.Dd 2025-09-30
.Dt DSA_METH_NEW 3ossl
.Os
.Sh NAME
.Nm DSA_meth_new ,
.Nm DSA_meth_free ,
.Nm DSA_meth_dup ,
.Nm DSA_meth_get0_name ,
.Nm DSA_meth_set1_name ,
.Nm DSA_meth_get_flags ,
.Nm DSA_meth_set_flags ,
.Nm DSA_meth_get0_app_data ,
.Nm DSA_meth_set0_app_data ,
.Nm DSA_meth_get_sign ,
.Nm DSA_meth_set_sign ,
.Nm DSA_meth_get_sign_setup ,
.Nm DSA_meth_set_sign_setup ,
.Nm DSA_meth_get_verify ,
.Nm DSA_meth_set_verify ,
.Nm DSA_meth_get_mod_exp ,
.Nm DSA_meth_set_mod_exp ,
.Nm DSA_meth_get_bn_mod_exp ,
.Nm DSA_meth_set_bn_mod_exp ,
.Nm DSA_meth_get_init ,
.Nm DSA_meth_set_init ,
.Nm DSA_meth_get_finish ,
.Nm DSA_meth_set_finish ,
.Nm DSA_meth_get_paramgen ,
.Nm DSA_meth_set_paramgen ,
.Nm DSA_meth_get_keygen ,
.Nm DSA_meth_set_keygen
.Nd Routines to build up DSA methods
.Sh SYNOPSIS
.In openssl/dsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft DSA_METHOD *
.Fo DSA_meth_new
.Fa "const char *name"
.Fa "int flags"
.Fc
.Ft void
.Fo DSA_meth_free
.Fa "DSA_METHOD *dsam"
.Fc
.Ft DSA_METHOD *
.Fo DSA_meth_dup
.Fa "const DSA_METHOD *meth"
.Fc
.Ft const char *
.Fo DSA_meth_get0_name
.Fa "const DSA_METHOD *dsam"
.Fc
.Ft int
.Fo DSA_meth_set1_name
.Fa "DSA_METHOD *dsam"
.Fa "const char *name"
.Fc
.Ft int
.Fo DSA_meth_get_flags
.Fa "const DSA_METHOD *dsam"
.Fc
.Ft int
.Fo DSA_meth_set_flags
.Fa "DSA_METHOD *dsam"
.Fa "int flags"
.Fc
.Ft void *
.Fo DSA_meth_get0_app_data
.Fa "const DSA_METHOD *dsam"
.Fc
.Ft int
.Fo DSA_meth_set0_app_data
.Fa "DSA_METHOD *dsam"
.Fa "void *app_data"
.Fc
.Ft DSA_SIG *
.Fo 
.Fa "*DSA_meth_get_sign(const DSA_METHOD *dsam)"
.Fc
(const unsigned char *,
.Bd -literal
                                                       int, DSA *);
 int DSA_meth_set_sign(DSA_METHOD *dsam, DSA_SIG *(*sign)(const unsigned char *,
                                                          int, DSA *));
.Ed
.Ft int
.Fo 
.Fa "*DSA_meth_get_sign_setup(const DSA_METHOD *dsam)"
.Fc
(DSA *, BN_CTX *,$
.Bd -literal
                                                        BIGNUM **, BIGNUM **);
 int DSA_meth_set_sign_setup(DSA_METHOD *dsam, int (*sign_setup)(DSA *, BN_CTX *,
                                                                 BIGNUM **, BIGNUM **));
.Ed
.Ft int
.Fo 
.Fa "*DSA_meth_get_verify(const DSA_METHOD *dsam)"
.Fc
(const unsigned char *,
.Bd -literal
                                                    int, DSA_SIG *, DSA *);
 int DSA_meth_set_verify(DSA_METHOD *dsam, int (*verify)(const unsigned char *,
                                                         int, DSA_SIG *, DSA *));
.Ed
.Ft int
.Fo 
.Fa "*DSA_meth_get_mod_exp(const DSA_METHOD *dsam)"
.Fc
(DSA *dsa, BIGNUM *rr, BIGNUM *a1,
.Bd -literal
                                                     BIGNUM *p1, BIGNUM *a2, BIGNUM *p2,
                                                     BIGNUM *m, BN_CTX *ctx,
                                                     BN_MONT_CTX *in_mont);
 int DSA_meth_set_mod_exp(DSA_METHOD *dsam, int (*mod_exp)(DSA *dsa, BIGNUM *rr,
                                                           BIGNUM *a1, BIGNUM *p1,
                                                           BIGNUM *a2, BIGNUM *p2,
                                                           BIGNUM *m, BN_CTX *ctx,
                                                           BN_MONT_CTX *mont));
.Ed
.Ft int
.Fo 
.Fa "*DSA_meth_get_bn_mod_exp(const DSA_METHOD *dsam)"
.Fc
(DSA *dsa, BIGNUM *r, BIGNUM *a,
.Bd -literal
                                                        const BIGNUM *p, const BIGNUM *m,
                                                        BN_CTX *ctx, BN_MONT_CTX *mont);
 int DSA_meth_set_bn_mod_exp(DSA_METHOD *dsam, int (*bn_mod_exp)(DSA *dsa,
                                                                 BIGNUM *r,
                                                                 BIGNUM *a,
                                                                 const BIGNUM *p,
                                                                 const BIGNUM *m,
                                                                 BN_CTX *ctx,
                                                                 BN_MONT_CTX *mont));
.Ed
.Ft int
.Fo 
.Fa "*DSA_meth_get_init(const DSA_METHOD *dsam)"
.Fc
(DSA *);
.Ft int
.Fo DSA_meth_set_init
.Fa "DSA_METHOD *dsam"
.Fa "int (*init)(DSA *)"
.Fc
.Ft int
.Fo 
.Fa "*DSA_meth_get_finish(const DSA_METHOD *dsam)"
.Fc
(DSA *);
.Ft int
.Fo DSA_meth_set_finish
.Fa "DSA_METHOD *dsam"
.Fa "int (*finish)(DSA *)"
.Fc
.Ft int
.Fo 
.Fa "*DSA_meth_get_paramgen(const DSA_METHOD *dsam)"
.Fc
(DSA *, int,
.Bd -literal
                                                      const unsigned char *,
                                                      int, int *, unsigned long *,
                                                      BN_GENCB *);
 int DSA_meth_set_paramgen(DSA_METHOD *dsam,
                           int (*paramgen)(DSA *, int, const unsigned char *,
                                           int, int *, unsigned long *, BN_GENCB *));
.Ed
.Ft int
.Fo 
.Fa "*DSA_meth_get_keygen(const DSA_METHOD *dsam)"
.Fc
(DSA *);
.Ft int
.Fo DSA_meth_set_keygen
.Fa "DSA_METHOD *dsam"
.Fa "int (*keygen)(DSA *)"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications and extension implementations should instead use the
OSSL_PROVIDER APIs.
.Pp
The
.Vt DSA_METHOD
type is a structure used for the provision of custom DSA
implementations.
It provides a set of functions used by OpenSSL for the implementation of
the various DSA capabilities.
.Pp
.Fn DSA_meth_new
creates a new
.Vt DSA_METHOD
structure.
It should be given a unique
.Fa name
and a set of
.Fa flags .
The
.Fa name
should be a NULL terminated string, which will be duplicated and stored
in the
.Vt DSA_METHOD
object.
It is the callers responsibility to free the original string.
The flags will be used during the construction of a new
.Sy DSA
object based on this
.Vt DSA_METHOD .
Any new
.Sy DSA
object will have those flags set by default.
.Pp
.Fn DSA_meth_dup
creates a duplicate copy of the
.Vt DSA_METHOD
object passed as a parameter.
This might be useful for creating a new
.Vt DSA_METHOD
based on an existing one, but with some differences.
.Pp
.Fn DSA_meth_free
destroys a
.Vt DSA_METHOD
structure and frees up any memory associated with it.
If the argument is NULL, nothing is done.
.Pp
.Fn DSA_meth_get0_name
will return a pointer to the name of this DSA_METHOD. This is a pointer
to the internal name string and so should not be freed by the caller.
.Fn DSA_meth_set1_name
sets the name of the DSA_METHOD to
.Fa name .
The string is duplicated and the copy is stored in the DSA_METHOD
structure, so the caller remains responsible for freeing the memory
associated with the name.
.Pp
.Fn DSA_meth_get_flags
returns the current value of the flags associated with this DSA_METHOD.
.Fn DSA_meth_set_flags
provides the ability to set these flags.
.Pp
The functions
.Fn DSA_meth_get0_app_data
and
.Fn DSA_meth_set0_app_data
provide the ability to associate implementation specific data with the
DSA_METHOD. It is the application's responsibility to free this data
before the DSA_METHOD is freed via a call to
.Fn DSA_meth_free .
.Pp
.Xr DSA_meth_get_sign 3
and
.Xr DSA_meth_set_sign 3
get and set the function used for creating a DSA signature respectively.
This function will be called in response to the application calling
.Xr DSA_do_sign 3
(or
.Xr DSA_sign 3 ) .
The parameters for the function have the same meaning as for
.Xr DSA_do_sign 3 .
.Pp
.Xr DSA_meth_get_sign_setup 3
and
.Xr DSA_meth_set_sign_setup 3
get and set the function used for precalculating the DSA signature
values
.Sy k^-1
and
.Sy r .
This function will be called in response to the application calling
.Xr DSA_sign_setup 3 .
The parameters for the function have the same meaning as for
.Xr DSA_sign_setup 3 .
.Pp
.Xr DSA_meth_get_verify 3
and
.Xr DSA_meth_set_verify 3
get and set the function used for verifying a DSA signature
respectively.
This function will be called in response to the application calling
.Xr DSA_do_verify 3
(or
.Xr DSA_verify 3 ) .
The parameters for the function have the same meaning as for
.Xr DSA_do_verify 3 .
.Pp
.Xr DSA_meth_get_mod_exp 3
and
.Xr DSA_meth_set_mod_exp 3
get and set the function used for computing the following value:
.Bd -literal
 rr = a1^p1 * a2^p2 mod m
.Ed
.Pp
This function will be called by the default OpenSSL method during
verification of a DSA signature.
The result is stored in the
.Sy rr
parameter.
This function may be NULL.
.Pp
.Xr DSA_meth_get_bn_mod_exp 3
and
.Xr DSA_meth_set_bn_mod_exp 3
get and set the function used for computing the following value:
.Bd -literal
 r = a ^ p mod m
.Ed
.Pp
This function will be called by the default OpenSSL function for
.Xr DSA_sign_setup 3 .
The result is stored in the
.Sy r
parameter.
This function may be NULL.
.Pp
.Xr DSA_meth_get_init 3
and
.Fn DSA_meth_set_init
get and set the function used for creating a new DSA instance
respectively.
This function will be called in response to the application calling
.Xr DSA_new 3
(if the current default DSA_METHOD is this one) or
.Xr DSA_new_method 3 .
The
.Xr DSA_new 3
and
.Xr DSA_new_method 3
functions will allocate the memory for the new DSA object, and a pointer
to this newly allocated structure will be passed as a parameter to the
function.
This function may be NULL.
.Pp
.Xr DSA_meth_get_finish 3
and
.Fn DSA_meth_set_finish
get and set the function used for destroying an instance of a DSA object
respectively.
This function will be called in response to the application calling
.Xr DSA_free 3 .
A pointer to the DSA to be destroyed is passed as a parameter.
The destroy function should be used for DSA implementation specific
clean up.
The memory for the DSA itself should not be freed by this function.
This function may be NULL.
.Pp
.Xr DSA_meth_get_paramgen 3
and
.Xr DSA_meth_set_paramgen 3
get and set the function used for generating DSA parameters
respectively.
This function will be called in response to the application calling
.Xr DSA_generate_parameters_ex 3
(or
.Xr DSA_generate_parameters 3 ) .
The parameters for the function have the same meaning as for
.Xr DSA_generate_parameters_ex 3 .
.Pp
.Xr DSA_meth_get_keygen 3
and
.Fn DSA_meth_set_keygen
get and set the function used for generating a new DSA key pair
respectively.
This function will be called in response to the application calling
.Xr DSA_generate_key 3 .
The parameter for the function has the same meaning as for
.Xr DSA_generate_key 3 .
.Sh RETURN VALUES
.Fn DSA_meth_new
and
.Fn DSA_meth_dup
return the newly allocated DSA_METHOD object or NULL on failure.
.Pp
.Fn DSA_meth_get0_name
and
.Fn DSA_meth_get_flags
return the name and flags associated with the DSA_METHOD respectively.
.Pp
All other
.Xr DSA_meth_get_* 3
functions return the appropriate function pointer that has been set in
the DSA_METHOD, or NULL if no such pointer has yet been set.
.Pp
.Fn DSA_meth_set1_name
and all
.Xr DSA_meth_set_* 3
functions return 1 on success or 0 on failure.
.Sh SEE ALSO
.Xr DSA_new 3 ,
.Xr DSA_new 3 ,
.Xr DSA_generate_parameters 3 ,
.Xr DSA_generate_key 3 ,
.Xr DSA_dup_DH 3 ,
.Xr DSA_do_sign 3 ,
.Xr DSA_set_method 3 ,
.Xr DSA_SIG_new 3 ,
.Xr DSA_sign 3 ,
.Xr DSA_size 3 ,
.Xr DSA_get0_pqg 3
.Sh HISTORY
The functions described here were deprecated in OpenSSL 3.0.
.Pp
The functions described here were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
