.Dd 2025-09-30
.Dt DSA_GENERATE_PARAMETERS 3ossl
.Os
.Sh NAME
.Nm DSA_generate_parameters_ex ,
.Nm DSA_generate_parameters
.Nd generate DSA parameters
.Sh SYNOPSIS
.In openssl/dsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo DSA_generate_parameters_ex
.Fa "DSA *dsa"
.Fa "int bits"
.Fa "const unsigned char *seed"
.Fa "int seed_len"
.Fa "int *counter_ret"
.Fa "unsigned long *h_ret"
.Fa "BN_GENCB *cb"
.Fc
.Pp
The following functions have been deprecated since OpenSSL 0.9.8, and
can be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft DSA *
.Fo DSA_generate_parameters
.Fa "int bits"
.Fa "unsigned char *seed"
.Fa "int seed_len"
.Fa "int *counter_ret"
.Fa "unsigned long *h_ret"
.Fa "void (*callback)(int"
.Fa int
.Fa "void *)"
.Fa "void *cb_arg"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_paramgen_init 3
and
.Xr EVP_PKEY_keygen 3
as described in
.Xr EVP_PKEY-DSA 7 .
.Pp
.Fn DSA_generate_parameters_ex
generates primes p and q and a generator g for use in the DSA and stores
the result in
.Fa dsa .
.Pp
.Fa bits
is the length of the prime p to be generated.
For lengths under 2048 bits, the length of q is 160 bits; for lengths
greater than or equal to 2048 bits, the length of q is set to 256 bits.
.Pp
If
.Fa seed
is NULL, the primes will be generated at random.
If
.Fa seed_len
is less than the length of q, an error is returned.
.Pp
.Fn DSA_generate_parameters_ex
places the iteration count in
.Pf * Fa counter_ret
and a counter used for finding a generator in
.Pf * Fa h_ret ,
unless these are
.Dv NULL .
.Pp
A callback function may be used to provide feedback about the progress
of the key generation.
If
.Fa cb
is not
.Dv NULL ,
it will be called as shown below.
For information on the BN_GENCB structure and the BN_GENCB_call function
discussed below, refer to
.Xr BN_generate_prime 3 .
.Pp
.Fn DSA_generate_parameters
is similar to
.Fn DSA_generate_parameters_ex
but expects an old-style callback function; see
.Xr BN_generate_prime 3
for information on the old-style callback.
.Bl -bullet
.It
When a candidate for q is generated,
.Sy BN_GENCB_call(cb, 0, m++)
is called (m is 0 for the first candidate).
.It
When a candidate for q has passed a test by trial division,
.Sy BN_GENCB_call(cb, 1, -1)
is called.
While a candidate for q is tested by Miller-Rabin primality tests,
.Sy BN_GENCB_call(cb, 1, i)
is called in the outer loop (once for each witness that confirms that
the candidate may be prime); i is the loop counter (starting at 0).
.It
When a prime q has been found,
.Sy BN_GENCB_call(cb, 2, 0)
and
.Sy BN_GENCB_call(cb, 3, 0)
are called.
.It
Before a candidate for p (other than the first) is generated and tested,
.Sy BN_GENCB_call(cb, 0, counter)
is called.
.It
When a candidate for p has passed the test by trial division,
.Sy BN_GENCB_call(cb, 1, -1)
is called.
While it is tested by the Miller-Rabin primality test,
.Sy BN_GENCB_call(cb, 1, i)
is called in the outer loop (once for each witness that confirms that
the candidate may be prime).
i is the loop counter (starting at 0).
.It
When p has been found,
.Sy BN_GENCB_call(cb, 2, 1)
is called.
.It
When the generator has been found,
.Sy BN_GENCB_call(cb, 3, 1)
is called.
.El
.Sh RETURN VALUES
.Fn DSA_generate_parameters_ex
returns a 1 on success, or 0 otherwise.
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Pp
.Fn DSA_generate_parameters
returns a pointer to the DSA structure or
.Dv NULL
if the parameter generation fails.
.Sh BUGS
Seed lengths greater than 20 are not supported.
.Sh SEE ALSO
.Xr DSA_new 3 ,
.Xr ERR_get_error 3 ,
.Xr RAND_bytes 3 ,
.Xr DSA_free 3 ,
.Xr BN_generate_prime 3
.Sh HISTORY
.Fn DSA_generate_parameters_ex
was deprecated in OpenSSL 3.0.
.Pp
.Fn DSA_generate_parameters
was deprecated in OpenSSL 0.9.8; use
.Fn DSA_generate_parameters_ex
instead.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
