.Dd 2025-09-30
.Dt DSA_GENERATE_KEY 3ossl
.Os
.Sh NAME
.Nm DSA_generate_key
.Nd generate DSA key pair
.Sh SYNOPSIS
.In openssl/dsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo DSA_generate_key
.Fa "DSA *a"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_keygen_init 3
and
.Xr EVP_PKEY_keygen 3
as described in
.Xr EVP_PKEY-DSA 7 .
.Pp
.Fn DSA_generate_key
expects
.Fa a
to contain DSA parameters.
It generates a new key pair and stores it in
.Sy a-\(rapub_key
and
.Sy a-\(rapriv_key .
.Pp
The random generator must be seeded prior to calling
.Fn DSA_generate_key .
If the automatic seeding or reseeding of the OpenSSL CSPRNG fails due to
external circumstances (see
.Xr RAND 7 Ns ),
the operation will fail.
.Sh RETURN VALUES
.Fn DSA_generate_key
returns 1 on success, 0 otherwise.
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr DSA_new 3 ,
.Xr ERR_get_error 3 ,
.Xr RAND_bytes 3 ,
.Xr DSA_generate_parameters_ex 3
.Sh HISTORY
This function was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
