.Dd 2025-09-30
.Dt EC_GROUP_COPY 3ossl
.Os
.Sh NAME
.Nm EC_GROUP_get0_order ,
.Nm EC_GROUP_order_bits ,
.Nm EC_GROUP_get0_cofactor ,
.Nm EC_GROUP_copy ,
.Nm EC_GROUP_dup ,
.Nm EC_GROUP_method_of ,
.Nm EC_GROUP_set_generator ,
.Nm EC_GROUP_get0_generator ,
.Nm EC_GROUP_get_order ,
.Nm EC_GROUP_get_cofactor ,
.Nm EC_GROUP_set_curve_name ,
.Nm EC_GROUP_get_curve_name ,
.Nm EC_GROUP_set_asn1_flag ,
.Nm EC_GROUP_get_asn1_flag ,
.Nm EC_GROUP_set_point_conversion_form ,
.Nm EC_GROUP_get_point_conversion_form ,
.Nm EC_GROUP_get0_seed ,
.Nm EC_GROUP_get_seed_len ,
.Nm EC_GROUP_set_seed ,
.Nm EC_GROUP_get_degree ,
.Nm EC_GROUP_check ,
.Nm EC_GROUP_check_named_curve ,
.Nm EC_GROUP_check_discriminant ,
.Nm EC_GROUP_cmp ,
.Nm EC_GROUP_get_basis_type ,
.Nm EC_GROUP_get_trinomial_basis ,
.Nm EC_GROUP_get_pentanomial_basis ,
.Nm EC_GROUP_get0_field ,
.Nm EC_GROUP_get_field_type
.Nd Functions for manipulating EC_GROUP objects
.Sh SYNOPSIS
.In openssl/ec.h
.Ft int
.Fo EC_GROUP_copy
.Fa "EC_GROUP *dst"
.Fa "const EC_GROUP *src"
.Fc
.Ft EC_GROUP *
.Fo EC_GROUP_dup
.Fa "const EC_GROUP *src"
.Fc
.Ft int
.Fo EC_GROUP_set_generator
.Fa "EC_GROUP *group"
.Fa "const EC_POINT *generator"
.Fa "const BIGNUM *order"
.Fa "const BIGNUM *cofactor"
.Fc
.Ft const EC_POINT *
.Fo EC_GROUP_get0_generator
.Fa "const EC_GROUP *group"
.Fc
.Ft int
.Fo EC_GROUP_get_order
.Fa "const EC_GROUP *group"
.Fa "BIGNUM *order"
.Fa "BN_CTX *ctx"
.Fc
.Ft const BIGNUM *
.Fo EC_GROUP_get0_order
.Fa "const EC_GROUP *group"
.Fc
.Ft int
.Fo EC_GROUP_order_bits
.Fa "const EC_GROUP *group"
.Fc
.Ft int
.Fo EC_GROUP_get_cofactor
.Fa "const EC_GROUP *group"
.Fa "BIGNUM *cofactor"
.Fa "BN_CTX *ctx"
.Fc
.Ft const BIGNUM *
.Fo EC_GROUP_get0_cofactor
.Fa "const EC_GROUP *group"
.Fc
.Ft const BIGNUM *
.Fo EC_GROUP_get0_field
.Fa "const EC_GROUP *group"
.Fc
.Ft void
.Fo EC_GROUP_set_curve_name
.Fa "EC_GROUP *group"
.Fa "int nid"
.Fc
.Ft int
.Fo EC_GROUP_get_curve_name
.Fa "const EC_GROUP *group"
.Fc
.Ft void
.Fo EC_GROUP_set_asn1_flag
.Fa "EC_GROUP *group"
.Fa "int flag"
.Fc
.Ft int
.Fo EC_GROUP_get_asn1_flag
.Fa "const EC_GROUP *group"
.Fc
.Ft void
.Fo EC_GROUP_set_point_conversion_form
.Fa "EC_GROUP *group"
.Fa "point_conversion_form_t form"
.Fc
.Ft point_conversion_form_t
.Fo EC_GROUP_get_point_conversion_form
.Fa "const EC_GROUP *group"
.Fc
.Ft unsigned char *
.Fo EC_GROUP_get0_seed
.Fa "const EC_GROUP *group"
.Fc
.Ft size_t
.Fo EC_GROUP_get_seed_len
.Fa "const EC_GROUP *group"
.Fc
.Ft size_t
.Fo EC_GROUP_set_seed
.Fa "EC_GROUP *group"
.Fa "const unsigned char *"
.Fa "size_t len"
.Fc
.Ft int
.Fo EC_GROUP_get_degree
.Fa "const EC_GROUP *group"
.Fc
.Ft int
.Fo EC_GROUP_check
.Fa "const EC_GROUP *group"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_GROUP_check_named_curve
.Fa "const EC_GROUP *group"
.Fa "int nist_only"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_GROUP_check_discriminant
.Fa "const EC_GROUP *group"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_GROUP_cmp
.Fa "const EC_GROUP *a"
.Fa "const EC_GROUP *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_GROUP_get_basis_type
.Fa "const EC_GROUP *group"
.Fc
.Ft int
.Fo EC_GROUP_get_trinomial_basis
.Fa "const EC_GROUP *group"
.Fa "unsigned int *k"
.Fc
.Ft int
.Fo EC_GROUP_get_pentanomial_basis
.Fa "const EC_GROUP *group"
.Fa "unsigned int *k1"
.Fa "unsigned int *k2"
.Fa "unsigned int *k3"
.Fc
.Ft int
.Fo EC_GROUP_get_field_type
.Fa "const EC_GROUP *group"
.Fc
The following function has been deprecated since OpenSSL 3.0, and can be
hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft const EC_METHOD *
.Fo EC_GROUP_method_of
.Fa "const EC_GROUP *group"
.Fc
.Sh DESCRIPTION
.Fn EC_GROUP_copy
copies the curve
.Fa src
into
.Fa dst .
Both
.Fa src
and
.Fa dst
must use the same EC_METHOD.
.Pp
.Fn EC_GROUP_dup
creates a new EC_GROUP object and copies the content from
.Fa src
to the newly created EC_GROUP object.
.Pp
.Fn EC_GROUP_method_of
obtains the EC_METHOD of
.Fa group .
This function was deprecated in OpenSSL 3.0, since EC_METHOD is no
longer a public concept.
.Pp
.Fn EC_GROUP_set_generator
sets curve parameters that must be agreed by all participants using the
curve.
These parameters include the
.Fa generator ,
the
.Fa order
and the
.Fa cofactor .
The
.Fa generator
is a well defined point on the curve chosen for cryptographic
operations.
Integers used for point multiplications will be between 0 and n-1 where
n is the
.Fa order .
The
.Fa order
multiplied by the
.Fa cofactor
gives the number of points on the curve.
.Pp
.Fn EC_GROUP_get0_generator
returns the generator for the identified
.Fa group .
.Pp
.Fn EC_GROUP_get_order
retrieves the order of
.Fa group
and copies its value into
.Fa order .
It fails in case
.Fa group
is not fully initialized (i.e., its order is not set or set to zero).
.Pp
.Fn EC_GROUP_get_cofactor
retrieves the cofactor of
.Fa group
and copies its value into
.Fa cofactor .
It fails in case
.Fa group
is not fully initialized or if the cofactor is not set (or set to zero).
.Pp
The functions
.Fn EC_GROUP_set_curve_name
and
.Fn EC_GROUP_get_curve_name ,
set and get the NID for the curve respectively (see
.Xr EC_GROUP_new 3 Ns ).
If a curve does not have a NID associated with it, then
EC_GROUP_get_curve_name will return NID_undef.
.Pp
The asn1_flag value is used to determine whether the curve encoding uses
explicit parameters or a named curve using an ASN1 OID: many
applications only support the latter form.
If asn1_flag is
.Sy OPENSSL_EC_NAMED_CURVE
then the named curve form is used and the parameters must have a
corresponding named curve NID set.
If asn1_flags is
.Sy OPENSSL_EC_EXPLICIT_CURVE
the parameters are explicitly encoded.
The functions
.Fn EC_GROUP_get_asn1_flag
and
.Fn EC_GROUP_set_asn1_flag
get and set the status of the asn1_flag for the curve.
Note:
.Sy OPENSSL_EC_EXPLICIT_CURVE
was added in OpenSSL 1.1.0, for previous versions of OpenSSL the value 0
must be used instead.
Before OpenSSL 1.1.0 the default form was to use explicit parameters
(meaning that applications would have to explicitly set the named curve
form) in OpenSSL 1.1.0 and later the named curve form is the default.
.Pp
The point_conversion_form for a curve controls how EC_POINT data is
encoded as ASN1 as defined in X9.62 (ECDSA). point_conversion_form_t is
an enum defined as follows:
.Bd -literal
 typedef enum {
        /** the point is encoded as z||x, where the octet z specifies
         *   which solution of the quadratic equation y is  */
        POINT_CONVERSION_COMPRESSED = 2,
        /** the point is encoded as z||x||y, where z is the octet 0x04  */
        POINT_CONVERSION_UNCOMPRESSED = 4,
        /** the point is encoded as z||x||y, where the octet z specifies
         *  which solution of the quadratic equation y is  */
        POINT_CONVERSION_HYBRID = 6
 } point_conversion_form_t;
.Ed
.Pp
For POINT_CONVERSION_UNCOMPRESSED the point is encoded as an octet
signifying the UNCOMPRESSED form has been used followed by the octets
for x, followed by the octets for y.
.Pp
For any given x coordinate for a point on a curve it is possible to
derive two possible y values.
For POINT_CONVERSION_COMPRESSED the point is encoded as an octet
signifying that the COMPRESSED form has been used AND which of the two
possible solutions for y has been used, followed by the octets for x.
.Pp
For POINT_CONVERSION_HYBRID the point is encoded as an octet signifying
the HYBRID form has been used AND which of the two possible solutions
for y has been used, followed by the octets for x, followed by the
octets for y.
.Pp
The functions
.Fn EC_GROUP_set_point_conversion_form
and
.Fn EC_GROUP_get_point_conversion_form ,
set and get the point_conversion_form for the curve respectively.
.Pp
ANSI X9.62 (ECDSA standard) defines a method of generating the curve
parameter b from a random number.
This provides advantages in that a parameter obtained in this way is
highly unlikely to be susceptible to special purpose attacks, or have
any trapdoors in it.
If the seed is present for a curve then the b parameter was generated in
a verifiable fashion using that seed.
The OpenSSL EC library does not use this seed value but does enable you
to inspect it using
.Fn EC_GROUP_get0_seed .
This returns a pointer to a memory block containing the seed that was
used.
The length of the memory block can be obtained using
.Fn EC_GROUP_get_seed_len .
A number of the built-in curves within the library provide seed values
that can be obtained.
It is also possible to set a custom seed using
.Fn EC_GROUP_set_seed
and passing a pointer to a memory block, along with the length of the
seed.
Again, the EC library will not use this seed value, although it will be
preserved in any ASN1 based communications.
.Pp
.Fn EC_GROUP_get_degree
gets the degree of the field.
For Fp fields this will be the number of bits in p. For F2^m fields this
will be the value m.
.Pp
.Fn EC_GROUP_get_field_type
identifies what type of field the EC_GROUP structure supports, which
will be either F2^m or Fp.
.Pp
The function
.Fn EC_GROUP_check_discriminant
calculates the discriminant for the curve and verifies that it is valid.
For a curve defined over Fp the discriminant is given by the formula
4*a^3 + 27*b^2 whilst for F2^m curves the discriminant is simply b. In
either case for the curve to be valid the discriminant must be non zero.
.Pp
The function
.Fn EC_GROUP_check
behaves in the following way: For the OpenSSL default provider it
performs a number of checks on a curve to verify that it is valid.
Checks performed include verifying that the discriminant is non zero;
that a generator has been defined; that the generator is on the curve
and has the correct order.
For the OpenSSL FIPS provider it uses
.Fn EC_GROUP_check_named_curve
to conform to SP800-56Ar3.
.Pp
The function
.Fn EC_GROUP_check_named_curve
determines if the group's domain parameters match one of the built-in
curves supported by the library.
The curve name is returned as a
.Sy NID
if it matches.
If the group's domain parameters have been modified then no match will
be found.
If the curve name of the given group is
.Sy NID_undef
(e.g.
it has been created by using explicit parameters with no curve name),
then this method can be used to lookup the name of the curve that
matches the group domain parameters.
The built-in curves contain aliases, so that multiple NID's can map to
the same domain parameters.
For such curves it is unspecified which of the aliases will be returned
if the curve name of the given group is NID_undef.
If
.Fa nist_only
is 1 it will only look for NIST approved curves, otherwise it searches
all built-in curves.
This function may be passed a BN_CTX object in the
.Fa ctx
parameter.
The
.Fa ctx
parameter may be NULL.
.Pp
.Fn EC_GROUP_cmp
compares
.Fa a
and
.Fa b
to determine whether they represent the same curve or not.
.Pp
The functions
.Fn EC_GROUP_get_basis_type ,
.Fn EC_GROUP_get_trinomial_basis
and
.Fn EC_GROUP_get_pentanomial_basis
should only be called for curves defined over an F2^m field.
Addition and multiplication operations within an F2^m field are
performed using an irreducible polynomial function f(x).
This function is either a trinomial of the form:
.Pp
f(x) = x^m + x^k + 1 with m > k >= 1
.Pp
or a pentanomial of the form:
.Pp
f(x) = x^m + x^k3 + x^k2 + x^k1 + 1 with m > k3 > k2 > k1 >= 1
.Pp
The function
.Fn EC_GROUP_get_basis_type
returns a NID identifying whether a trinomial or pentanomial is in use
for the field.
The function
.Fn EC_GROUP_get_trinomial_basis
must only be called where f(x) is of the trinomial form, and returns the
value of
.Fa k .
Similarly the function
.Fn EC_GROUP_get_pentanomial_basis
must only be called where f(x) is of the pentanomial form, and returns
the values of
.Fa k1 ,
.Fa k2
and
.Fa k3
respectively.
.Sh RETURN VALUES
The following functions return 1 on success or 0 on error:
.Fn EC_GROUP_copy ,
.Fn EC_GROUP_set_generator ,
.Fn EC_GROUP_check ,
.Fn EC_GROUP_check_discriminant ,
.Fn EC_GROUP_get_trinomial_basis
and
.Fn EC_GROUP_get_pentanomial_basis .
.Pp
.Fn EC_GROUP_dup
returns a pointer to the duplicated curve, or NULL on error.
.Pp
.Fn EC_GROUP_method_of
returns the EC_METHOD implementation in use for the given curve or NULL
on error.
.Pp
.Fn EC_GROUP_get0_generator
returns the generator for the given curve or NULL on error.
.Pp
.Fn EC_GROUP_get_order
returns 0 if the order is not set (or set to zero) for
.Fa group
or if copying into
.Fa order
fails, 1 otherwise.
.Pp
.Fn EC_GROUP_get_cofactor
returns 0 if the cofactor is not set (or is set to zero) for
.Fa group
or if copying into
.Fa cofactor
fails, 1 otherwise.
.Pp
.Fn EC_GROUP_get_curve_name
returns the curve name (NID) for
.Fa group
or will return NID_undef if no curve name is associated.
.Pp
.Fn EC_GROUP_get_asn1_flag
returns the ASN1 flag for the specified
.Fa group
\&.
.Pp
.Fn EC_GROUP_get_point_conversion_form
returns the point_conversion_form for
.Fa group .
.Pp
.Fn EC_GROUP_get_degree
returns the degree for
.Fa group
or 0 if the operation is not supported by the underlying group
implementation.
.Pp
.Fn EC_GROUP_get_field_type
returns either
.Sy NID_X9_62_prime_field
for prime curves or
.Sy NID_X9_62_characteristic_two_field
for binary curves; these values are defined in the
.Pa <openssl/obj_mac.h>
header file.
.Pp
.Fn EC_GROUP_check_named_curve
returns the nid of the matching named curve, otherwise it returns 0 for
no match, or -1 on error.
.Pp
.Fn EC_GROUP_get0_order
returns an internal pointer to the group order.
.Fn EC_GROUP_order_bits
returns the number of bits in the group order.
.Fn EC_GROUP_get0_cofactor
returns an internal pointer to the group cofactor.
.Fn EC_GROUP_get0_field
returns an internal pointer to the group field.
For curves over GF(p), this is the modulus; for curves over GF(2^m),
this is the irreducible polynomial defining the field.
.Pp
.Fn EC_GROUP_get0_seed
returns a pointer to the seed that was used to generate the parameter b,
or NULL if the seed is not specified.
.Fn EC_GROUP_get_seed_len
returns the length of the seed or 0 if the seed is not specified.
.Pp
.Fn EC_GROUP_set_seed
returns the length of the seed that has been set.
If the supplied seed is NULL, or the supplied seed length is 0, the
return value will be 1. On error 0 is returned.
.Pp
.Fn EC_GROUP_cmp
returns 0 if the curves are equal, 1 if they are not equal, or -1 on
error.
.Pp
.Fn EC_GROUP_get_basis_type
returns the values NID_X9_62_tpBasis or NID_X9_62_ppBasis (as defined in
.Pa <openssl/obj_mac.h> )
for a trinomial or pentanomial respectively.
Alternatively in the event of an error a 0 is returned.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr EC_GROUP_new 3 ,
.Xr EC_POINT_new 3 ,
.Xr EC_POINT_add 3 ,
.Xr EC_KEY_new 3 ,
.Xr EC_GFp_simple_method 3 ,
.Xr d2i_ECPKParameters 3
.Sh HISTORY
.Fn EC_GROUP_method_of
was deprecated in OpenSSL 3.0.
.Fn EC_GROUP_get0_field ,
.Fn EC_GROUP_check_named_curve
and
.Fn EC_GROUP_get_field_type
were added in OpenSSL 3.0.
.Fn EC_GROUP_get0_order ,
.Fn EC_GROUP_order_bits
and
.Fn EC_GROUP_get0_cofactor
were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2013-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
