.Dd 2025-09-30
.Dt EC_GFP_SIMPLE_METHOD 3ossl
.Os
.Sh NAME
.Nm EC_GFp_simple_method ,
.Nm EC_GFp_mont_method ,
.Nm EC_GFp_nist_method ,
.Nm EC_GFp_nistp224_method ,
.Nm EC_GFp_nistp256_method ,
.Nm EC_GFp_nistp521_method ,
.Nm EC_GF2m_simple_method ,
.Nm EC_METHOD_get_field_type
.Nd Functions for obtaining EC_METHOD objects
.Sh SYNOPSIS
.In openssl/ec.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft const EC_METHOD *
.Fo EC_GFp_simple_method
.Fa void
.Fc
.Ft const EC_METHOD *
.Fo EC_GFp_mont_method
.Fa void
.Fc
.Ft const EC_METHOD *
.Fo EC_GFp_nist_method
.Fa void
.Fc
.Ft const EC_METHOD *
.Fo EC_GFp_nistp224_method
.Fa void
.Fc
.Ft const EC_METHOD *
.Fo EC_GFp_nistp256_method
.Fa void
.Fc
.Ft const EC_METHOD *
.Fo EC_GFp_nistp521_method
.Fa void
.Fc
.Ft const EC_METHOD *
.Fo EC_GF2m_simple_method
.Fa void
.Fc
.Ft int
.Fo EC_METHOD_get_field_type
.Fa "const EC_METHOD *meth"
.Fc
.Sh DESCRIPTION
All const EC_METHOD *EC_GF* functions were deprecated in OpenSSL 3.0,
since EC_METHOD is no longer a public concept.
.Pp
The Elliptic Curve library provides a number of different
implementations through a single common interface.
When constructing a curve using EC_GROUP_new (see
.Xr EC_GROUP_new 3 )
an implementation method must be provided.
The functions described here all return a const pointer to an
.Sy EC_METHOD
structure that can be passed to EC_GROUP_NEW. It is important that the
correct implementation type for the form of curve selected is used.
.Pp
For F2^m curves there is only one implementation choice, i.e.
EC_GF2_simple_method.
.Pp
For Fp curves the lowest common denominator implementation is the
EC_GFp_simple_method implementation.
All other implementations are based on this one.
EC_GFp_mont_method builds on EC_GFp_simple_method but adds the use of
montgomery multiplication (see
.Xr BN_mod_mul_montgomery 3 Ns ).
EC_GFp_nist_method offers an implementation optimised for use with NIST
recommended curves (NIST curves are available through
EC_GROUP_new_by_curve_name as described in
.Xr EC_GROUP_new 3 Ns ).
.Pp
The functions EC_GFp_nistp224_method, EC_GFp_nistp256_method and
EC_GFp_nistp521_method offer 64 bit optimised implementations for the
NIST P224, P256 and P521 curves respectively.
Note, however, that these implementations are not available on all
platforms.
.Pp
.Fn EC_METHOD_get_field_type
was deprecated in OpenSSL 3.0. Applications should use
.Xr EC_GROUP_get_field_type 3
as a replacement (see
.Xr EC_GROUP_copy 3 Ns ).
.Sh RETURN VALUES
All EC_GFp* functions and EC_GF2m_simple_method always return a const
pointer to an EC_METHOD structure.
.Pp
EC_METHOD_get_field_type returns an integer that identifies the type of
field the EC_METHOD structure supports.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr EC_GROUP_new 3 ,
.Xr EC_GROUP_copy 3 ,
.Xr EC_POINT_new 3 ,
.Xr EC_POINT_add 3 ,
.Xr EC_KEY_new 3 ,
.Xr d2i_ECPKParameters 3 ,
.Xr BN_mod_mul_montgomery 3
.Sh HISTORY
.Fn EC_GFp_simple_method ,
EC_GFp_mont_method(void),
.Fn EC_GFp_nist_method ,
.Fn EC_GFp_nistp224_method ,
.Fn EC_GFp_nistp256_method ,
.Fn EC_GFp_nistp521_method ,
.Fn EC_GF2m_simple_method ,
and
.Fn EC_METHOD_get_field_type
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2013-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
