.Dd 2025-09-30
.Dt EC_KEY_NEW 3ossl
.Os
.Sh NAME
.Nm EVP_EC_gen ,
.Nm EC_KEY_get_method ,
.Nm EC_KEY_set_method ,
.Nm EC_KEY_new_ex ,
.Nm EC_KEY_new ,
.Nm EC_KEY_get_flags ,
.Nm EC_KEY_set_flags ,
.Nm EC_KEY_clear_flags ,
.Nm EC_KEY_new_by_curve_name_ex ,
.Nm EC_KEY_new_by_curve_name ,
.Nm EC_KEY_free ,
.Nm EC_KEY_copy ,
.Nm EC_KEY_dup ,
.Nm EC_KEY_up_ref ,
.Nm EC_KEY_get0_engine ,
.Nm EC_KEY_get0_group ,
.Nm EC_KEY_set_group ,
.Nm EC_KEY_get0_private_key ,
.Nm EC_KEY_set_private_key ,
.Nm EC_KEY_get0_public_key ,
.Nm EC_KEY_set_public_key ,
.Nm EC_KEY_get_conv_form ,
.Nm EC_KEY_set_conv_form ,
.Nm EC_KEY_set_asn1_flag ,
.Nm EC_KEY_decoded_from_explicit_params ,
.Nm EC_KEY_precompute_mult ,
.Nm EC_KEY_generate_key ,
.Nm EC_KEY_check_key ,
.Nm EC_KEY_set_public_key_affine_coordinates ,
.Nm EC_KEY_oct2key ,
.Nm EC_KEY_key2buf ,
.Nm EC_KEY_oct2priv ,
.Nm EC_KEY_priv2oct ,
.Nm EC_KEY_priv2buf
.Nd Functions for creating, destroying and manipulating EC_KEY objects
.Sh SYNOPSIS
.In openssl/ec.h
.Ft EVP_PKEY *
.Fo EVP_EC_gen
.Fa "const char *curve"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft EC_KEY *
.Fo EC_KEY_new_ex
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Ft EC_KEY *
.Fo EC_KEY_new
.Fa void
.Fc
.Ft int
.Fo EC_KEY_get_flags
.Fa "const EC_KEY *key"
.Fc
.Ft void
.Fo EC_KEY_set_flags
.Fa "EC_KEY *key"
.Fa "int flags"
.Fc
.Ft void
.Fo EC_KEY_clear_flags
.Fa "EC_KEY *key"
.Fa "int flags"
.Fc
.Ft EC_KEY *
.Fo EC_KEY_new_by_curve_name_ex
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fa "int nid"
.Fc
.Ft EC_KEY *
.Fo EC_KEY_new_by_curve_name
.Fa "int nid"
.Fc
.Ft void
.Fo EC_KEY_free
.Fa "EC_KEY *key"
.Fc
.Ft EC_KEY *
.Fo EC_KEY_copy
.Fa "EC_KEY *dst"
.Fa "const EC_KEY *src"
.Fc
.Ft EC_KEY *
.Fo EC_KEY_dup
.Fa "const EC_KEY *src"
.Fc
.Ft int
.Fo EC_KEY_up_ref
.Fa "EC_KEY *key"
.Fc
.Ft ENGINE *
.Fo EC_KEY_get0_engine
.Fa "const EC_KEY *eckey"
.Fc
.Ft const EC_GROUP *
.Fo EC_KEY_get0_group
.Fa "const EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_set_group
.Fa "EC_KEY *key"
.Fa "const EC_GROUP *group"
.Fc
.Ft const BIGNUM *
.Fo EC_KEY_get0_private_key
.Fa "const EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_set_private_key
.Fa "EC_KEY *key"
.Fa "const BIGNUM *priv_key"
.Fc
.Ft const EC_POINT *
.Fo EC_KEY_get0_public_key
.Fa "const EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_set_public_key
.Fa "EC_KEY *key"
.Fa "const EC_POINT *pub"
.Fc
.Ft point_conversion_form_t
.Fo EC_KEY_get_conv_form
.Fa "const EC_KEY *key"
.Fc
.Ft void
.Fo EC_KEY_set_conv_form
.Fa "EC_KEY *eckey"
.Fa "point_conversion_form_t cform"
.Fc
.Ft void
.Fo EC_KEY_set_asn1_flag
.Fa "EC_KEY *eckey"
.Fa "int asn1_flag"
.Fc
.Ft int
.Fo EC_KEY_decoded_from_explicit_params
.Fa "const EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_generate_key
.Fa "EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_check_key
.Fa "const EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_set_public_key_affine_coordinates
.Fa "EC_KEY *key"
.Fa "BIGNUM *x"
.Fa "BIGNUM *y"
.Fc
.Ft const EC_KEY_METHOD *
.Fo EC_KEY_get_method
.Fa "const EC_KEY *key"
.Fc
.Ft int
.Fo EC_KEY_set_method
.Fa "EC_KEY *key"
.Fa "const EC_KEY_METHOD *meth"
.Fc
.Ft int
.Fo EC_KEY_oct2key
.Fa "EC_KEY *eckey"
.Fa "const unsigned char *buf"
.Fa "size_t len"
.Fa "BN_CTX *ctx"
.Fc
.Ft size_t
.Fo EC_KEY_key2buf
.Fa "const EC_KEY *eckey"
.Fa "point_conversion_form_t form"
.Fa "unsigned char **pbuf"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_KEY_oct2priv
.Fa "EC_KEY *eckey"
.Fa "const unsigned char *buf"
.Fa "size_t len"
.Fc
.Ft size_t
.Fo EC_KEY_priv2oct
.Fa "const EC_KEY *eckey"
.Fa "unsigned char *buf"
.Fa "size_t len"
.Fc
.Ft size_t
.Fo EC_KEY_priv2buf
.Fa "const EC_KEY *eckey"
.Fa "unsigned char **pbuf"
.Fc
.Ft int
.Fo EC_KEY_precompute_mult
.Fa "EC_KEY *key"
.Fa "BN_CTX *ctx"
.Fc
.Sh DESCRIPTION
.Fn EVP_EC_gen
generates a new EC key pair on the given
.Fa curve .
.Pp
All of the functions described below are deprecated.
Applications should instead use
.Fn EVP_EC_gen ,
.Xr EVP_PKEY_Q_keygen 3 ,
or
.Xr EVP_PKEY_keygen_init 3
and
.Xr EVP_PKEY_keygen 3 .
.Pp
An EC_KEY represents a public key and, optionally, the associated
private key.
A new EC_KEY with no associated curve can be constructed by calling
.Fn EC_KEY_new_ex
and specifying the associated library context in
.Fa ctx
(see
.Xr OSSL_LIB_CTX 3 )
and property query string
.Fa propq .
The
.Fa ctx
parameter may be NULL in which case the default library context is used.
The reference count for the newly created EC_KEY is initially set to 1.
A curve can be associated with the EC_KEY by calling
.Fn EC_KEY_set_group .
.Pp
.Fn EC_KEY_new
is the same as
.Fn EC_KEY_new_ex
except that the default library context is always used.
.Pp
Alternatively a new EC_KEY can be constructed by calling
.Fn EC_KEY_new_by_curve_name_ex
and supplying the nid of the associated curve, the library context to be
used
.Fa ctx
(see
.Xr OSSL_LIB_CTX 3 )
and any property query string
.Fa propq .
The
.Fa ctx
parameter may be NULL in which case the default library context is used.
The
.Fa propq
value may also be NULL. See
.Xr EC_GROUP_new 3
for a description of curve names.
This function simply wraps calls to
.Fn EC_KEY_new_ex
and
.Xr EC_GROUP_new_by_curve_name_ex 3 .
.Pp
.Fn EC_KEY_new_by_curve_name
is the same as
.Fn EC_KEY_new_by_curve_name_ex
except that the default library context is always used and a NULL
property query string.
.Pp
Calling
.Fn EC_KEY_free
decrements the reference count for the EC_KEY object, and if it has
dropped to zero then frees the memory associated with it.
If
.Fa key
is NULL nothing is done.
.Pp
.Fn EC_KEY_copy
copies the contents of the EC_KEY in
.Fa src
into
.Em dest .
.Pp
.Fn EC_KEY_dup
creates a new EC_KEY object and copies
.Em ec_key
into it.
.Pp
.Fn EC_KEY_up_ref
increments the reference count associated with the EC_KEY object.
.Pp
.Fn EC_KEY_get0_engine
returns a handle to the ENGINE that has been set for this EC_KEY object.
.Pp
.Fn EC_KEY_generate_key
generates a new public and private key for the supplied
.Fa eckey
object.
.Fa eckey
must have an EC_GROUP object associated with it before calling this
function.
The private key is a random integer (0 < priv_key < order, where
.Em order
is the order of the EC_GROUP object).
The public key is an EC_POINT on the curve calculated by multiplying the
generator for the curve by the private key.
.Pp
.Fn EC_KEY_check_key
performs various sanity checks on the EC_KEY object to confirm that it
is valid.
.Pp
.Fn EC_KEY_set_public_key_affine_coordinates
sets the public key for
.Fa key
based on its affine coordinates; i.e., it constructs an EC_POINT object
based on the supplied
.Fa x
and
.Fa y
values and sets the public key to be this EC_POINT. It also performs
certain sanity checks on the key to confirm that it is valid.
.Pp
The functions
.Fn EC_KEY_get0_group ,
.Fn EC_KEY_set_group ,
.Fn EC_KEY_get0_private_key ,
.Fn EC_KEY_set_private_key ,
.Fn EC_KEY_get0_public_key ,
and
.Fn EC_KEY_set_public_key
get and set the EC_GROUP object, the private key, and the EC_POINT
public key for the
.Fa key
respectively.
The function
.Fn EC_KEY_set_private_key
accepts NULL as the priv_key argument to securely clear the private key
component from the EC_KEY.
.Pp
The functions
.Fn EC_KEY_get_conv_form
and
.Fn EC_KEY_set_conv_form
get and set the point_conversion_form for the
.Fa key .
For a description of point_conversion_forms please see
.Xr EC_POINT_new 3 .
.Pp
.Fn EC_KEY_set_flags
sets the flags in the
.Fa flags
parameter on the EC_KEY object.
Any flags that are already set are left set.
The flags currently defined are EC_FLAG_NON_FIPS_ALLOW and
EC_FLAG_FIPS_CHECKED. In addition there is the flag
EC_FLAG_COFACTOR_ECDH which is specific to ECDH.
.Fn EC_KEY_get_flags
returns the current flags that are set for this EC_KEY.
.Fn EC_KEY_clear_flags
clears the flags indicated by the
.Fa flags
parameter; all other flags are left in their existing state.
.Pp
.Fn EC_KEY_set_asn1_flag
sets the asn1_flag on the underlying EC_GROUP object (if set).
Refer to
.Xr EC_GROUP_copy 3
for further information on the asn1_flag.
.Pp
.Fn EC_KEY_decoded_from_explicit_params
returns 1 if the group of the
.Fa key
was decoded from data with explicitly encoded group parameters, -1 if
the
.Fa key
is NULL or the group parameters are missing, and 0 otherwise.
.Pp
.Fn EC_KEY_precompute_mult
stores multiples of the underlying EC_GROUP generator for faster point
multiplication.
See also
.Xr EC_POINT_add 3 .
Modern versions should instead switch to named curves which OpenSSL has
hardcoded lookup tables for.
.Pp
.Fn EC_KEY_oct2key
and
.Fn EC_KEY_key2buf
are identical to the functions
.Xr EC_POINT_oct2point 3
and
.Xr EC_POINT_point2buf 3
except they use the public key EC_POINT in
.Fa eckey .
.Pp
.Fn EC_KEY_oct2priv
and
.Fn EC_KEY_priv2oct
convert between the private key component of
.Fa eckey
and octet form.
The octet form consists of the content octets of the
.Em privateKey
OCTET STRING in an
.Em ECPrivateKey
ASN.1 structure.
.Pp
The function
.Fn EC_KEY_priv2oct
must be supplied with a buffer long enough to store the octet form.
The return value provides the number of octets stored.
Calling the function with a NULL buffer will not perform the conversion
but will just return the required buffer length.
.Pp
The function
.Fn EC_KEY_priv2buf
allocates a buffer of suitable length and writes an EC_KEY to it in
octet format.
The allocated buffer is written to
.Em *pbuf
and its length is returned.
The caller must free up the allocated buffer with a call to
.Xr OPENSSL_free 3 .
Since the allocated buffer value is written to
.Em *pbuf
the
.Fa pbuf
parameter
.Sy MUST NOT
be
.Dv NULL .
.Pp
.Fn EC_KEY_priv2buf
converts an EC_KEY private key into an allocated buffer.
.Sh RETURN VALUES
.Fn EC_KEY_new_ex ,
.Fn EC_KEY_new ,
.Fn EC_KEY_new_by_curve_name_ex ,
.Fn EC_KEY_new_by_curve_name
and
.Fn EC_KEY_dup
return a pointer to the newly created EC_KEY object, or NULL on error.
.Pp
.Fn EC_KEY_get_flags
returns the flags associated with the EC_KEY object as an integer.
.Pp
.Fn EC_KEY_copy
returns a pointer to the destination key, or NULL on error.
.Pp
.Fn EC_KEY_get0_engine
returns a pointer to an ENGINE, or NULL if it wasn't set.
.Pp
.Fn EC_KEY_up_ref ,
.Fn EC_KEY_set_group ,
.Fn EC_KEY_set_public_key ,
.Fn EC_KEY_precompute_mult ,
.Fn EC_KEY_generate_key ,
.Fn EC_KEY_check_key ,
.Fn EC_KEY_set_public_key_affine_coordinates ,
.Fn EC_KEY_oct2key
and
.Fn EC_KEY_oct2priv
return 1 on success or 0 on error.
.Pp
.Fn EC_KEY_set_private_key
returns 1 on success or 0 on error except when the priv_key argument is
NULL, in that case it returns 0, for legacy compatibility, and should
not be treated as an error.
.Pp
.Fn EC_KEY_get0_group
returns the EC_GROUP associated with the EC_KEY.
.Pp
.Fn EC_KEY_get0_private_key
returns the private key associated with the EC_KEY.
.Pp
.Fn EC_KEY_get_conv_form
return the point_conversion_form for the EC_KEY.
.Pp
.Fn EC_KEY_key2buf ,
.Fn EC_KEY_priv2oct
and
.Fn EC_KEY_priv2buf
return the length of the buffer or 0 on error.
.Sh SEE ALSO
.Xr EVP_PKEY_Q_keygen 3
.Xr crypto 7 ,
.Xr EC_GROUP_new 3 ,
.Xr EC_GROUP_copy 3 ,
.Xr EC_POINT_new 3 ,
.Xr EC_POINT_add 3 ,
.Xr EC_GFp_simple_method 3 ,
.Xr d2i_ECPKParameters 3 ,
.Xr OSSL_LIB_CTX 3
.Sh HISTORY
.Fn EVP_EC_gen
was added in OpenSSL 3.0. All other functions described here were
deprecated in OpenSSL 3.0. For replacement see
.Xr EVP_PKEY-EC 7 .
.Sh COPYRIGHT
Copyright 2013-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
