.Dd 2025-09-30
.Dt EC_POINT_NEW 3ossl
.Os
.Sh NAME
.Nm EC_POINT_set_Jprojective_coordinates_GFp ,
.Nm EC_POINT_point2buf ,
.Nm EC_POINT_new ,
.Nm EC_POINT_free ,
.Nm EC_POINT_clear_free ,
.Nm EC_POINT_copy ,
.Nm EC_POINT_dup ,
.Nm EC_POINT_method_of ,
.Nm EC_POINT_set_to_infinity ,
.Nm EC_POINT_get_Jprojective_coordinates_GFp ,
.Nm EC_POINT_set_affine_coordinates ,
.Nm EC_POINT_get_affine_coordinates ,
.Nm EC_POINT_set_compressed_coordinates ,
.Nm EC_POINT_set_affine_coordinates_GFp ,
.Nm EC_POINT_get_affine_coordinates_GFp ,
.Nm EC_POINT_set_compressed_coordinates_GFp ,
.Nm EC_POINT_set_affine_coordinates_GF2m ,
.Nm EC_POINT_get_affine_coordinates_GF2m ,
.Nm EC_POINT_set_compressed_coordinates_GF2m ,
.Nm EC_POINT_point2oct ,
.Nm EC_POINT_oct2point ,
.Nm EC_POINT_point2bn ,
.Nm EC_POINT_bn2point ,
.Nm EC_POINT_point2hex ,
.Nm EC_POINT_hex2point
.Nd Functions for creating, destroying and manipulating EC_POINT objects
.Sh SYNOPSIS
.In openssl/ec.h
.Ft EC_POINT *
.Fo EC_POINT_new
.Fa "const EC_GROUP *group"
.Fc
.Ft void
.Fo EC_POINT_free
.Fa "EC_POINT *point"
.Fc
.Ft void
.Fo EC_POINT_clear_free
.Fa "EC_POINT *point"
.Fc
.Ft int
.Fo EC_POINT_copy
.Fa "EC_POINT *dst"
.Fa "const EC_POINT *src"
.Fc
.Ft EC_POINT *
.Fo EC_POINT_dup
.Fa "const EC_POINT *src"
.Fa "const EC_GROUP *group"
.Fc
.Ft int
.Fo EC_POINT_set_to_infinity
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *point"
.Fc
.Ft int
.Fo EC_POINT_set_affine_coordinates
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "const BIGNUM *y"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_get_affine_coordinates
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "BIGNUM *x"
.Fa "BIGNUM *y"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_set_compressed_coordinates
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "int y_bit"
.Fa "BN_CTX *ctx"
.Fc
.Ft size_t
.Fo EC_POINT_point2oct
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "point_conversion_form_t form"
.Fa "unsigned char *buf"
.Fa "size_t len"
.Fa "BN_CTX *ctx"
.Fc
.Ft size_t
.Fo EC_POINT_point2buf
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *point"
.Fa "point_conversion_form_t form"
.Fa "unsigned char **pbuf"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_oct2point
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const unsigned char *buf"
.Fa "size_t len"
.Fa "BN_CTX *ctx"
.Fc
.Ft char *
.Fo EC_POINT_point2hex
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "point_conversion_form_t form"
.Fa "BN_CTX *ctx"
.Fc
.Ft EC_POINT *
.Fo EC_POINT_hex2point
.Fa "const EC_GROUP *group"
.Fa "const char *hex"
.Fa "EC_POINT *p"
.Fa "BN_CTX *ctx"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft const EC_METHOD *
.Fo EC_POINT_method_of
.Fa "const EC_POINT *point"
.Fc
.Ft int
.Fo EC_POINT_set_Jprojective_coordinates_GFp
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "const BIGNUM *y"
.Fa "const BIGNUM *z"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_get_Jprojective_coordinates_GFp
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "BIGNUM *x"
.Fa "BIGNUM *y"
.Fa "BIGNUM *z"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_set_affine_coordinates_GFp
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "const BIGNUM *y"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_get_affine_coordinates_GFp
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "BIGNUM *x"
.Fa "BIGNUM *y"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_set_compressed_coordinates_GFp
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "int y_bit"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_set_affine_coordinates_GF2m
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "const BIGNUM *y"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_get_affine_coordinates_GF2m
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "BIGNUM *x"
.Fa "BIGNUM *y"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_set_compressed_coordinates_GF2m
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *p"
.Fa "const BIGNUM *x"
.Fa "int y_bit"
.Fa "BN_CTX *ctx"
.Fc
.Ft BIGNUM *
.Fo EC_POINT_point2bn
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fa "point_conversion_form_t form"
.Fa "BIGNUM *bn"
.Fa "BN_CTX *ctx"
.Fc
.Ft EC_POINT *
.Fo EC_POINT_bn2point
.Fa "const EC_GROUP *group"
.Fa "const BIGNUM *bn"
.Fa "EC_POINT *p"
.Fa "BN_CTX *ctx"
.Fc
.Sh DESCRIPTION
An
.Vt EC_POINT
structure represents a point on a curve.
A new point is constructed by calling the function
.Fn EC_POINT_new
and providing the
.Fa group
object that the point relates to.
.Pp
.Fn EC_POINT_free
frees the memory associated with the
.Vt EC_POINT .
if
.Fa point
is NULL nothing is done.
.Pp
.Fn EC_POINT_clear_free
destroys any sensitive data held within the EC_POINT and then frees its
memory.
If
.Fa point
is NULL nothing is done.
.Pp
.Fn EC_POINT_copy
copies the point
.Fa src
into
.Fa dst .
Both
.Fa src
and
.Fa dst
must use the same
.Sy EC_METHOD .
.Pp
.Fn EC_POINT_dup
creates a new
.Vt EC_POINT
object and copies the content from
.Fa src
to the newly created
.Vt EC_POINT
object.
.Pp
.Fn EC_POINT_method_of
obtains the
.Sy EC_METHOD
associated with
.Fa point .
This function was deprecated in OpenSSL 3.0, since EC_METHOD is no
longer a public concept.
.Pp
A valid point on a curve is the special point at infinity.
A point is set to be at infinity by calling
.Fn EC_POINT_set_to_infinity .
.Pp
The affine coordinates for a point describe a point in terms of its x
and y position.
The function
.Fn EC_POINT_set_affine_coordinates
sets the
.Fa x
and
.Fa y
coordinates for the point
.Fa p
defined over the curve given in
.Fa group .
The function
.Fn EC_POINT_get_affine_coordinates
sets
.Fa x
and
.Fa y ,
either of which may be NULL, to the corresponding coordinates of
.Fa p .
.Pp
The functions
.Fn EC_POINT_set_affine_coordinates_GFp
and
.Fn EC_POINT_set_affine_coordinates_GF2m
are synonyms for
.Fn EC_POINT_set_affine_coordinates .
They are defined for backwards compatibility only and should not be
used.
.Pp
The functions
.Fn EC_POINT_get_affine_coordinates_GFp
and
.Fn EC_POINT_get_affine_coordinates_GF2m
are synonyms for
.Fn EC_POINT_get_affine_coordinates .
They are defined for backwards compatibility only and should not be
used.
.Pp
As well as the affine coordinates, a point can alternatively be
described in terms of its Jacobian projective coordinates (for Fp curves
only).
Jacobian projective coordinates are expressed as three values x, y and
z. Working in this coordinate system provides more efficient point
multiplication operations.
A mapping exists between Jacobian projective coordinates and affine
coordinates.
A Jacobian projective coordinate (x, y, z) can be written as an affine
coordinate as (x/(z^2), y/(z^3)). Conversion to Jacobian projective from
affine coordinates is simple.
The coordinate (x, y) is mapped to (x, y, 1). Although deprecated in
OpenSSL 3.0 and should no longer be used, to set or get the projective
coordinates in older versions use
.Fn EC_POINT_set_Jprojective_coordinates_GFp
and
.Fn EC_POINT_get_Jprojective_coordinates_GFp
respectively.
Modern versions should instead use
.Fn EC_POINT_set_affine_coordinates
and
.Fn EC_POINT_get_affine_coordinates ,
performing the conversion manually using the above maps in such rare
circumstances.
.Pp
Points can also be described in terms of their compressed coordinates.
For a point (x, y), for any given value for x such that the point is on
the curve there will only ever be two possible values for y. Therefore,
a point can be set using the
.Fn EC_POINT_set_compressed_coordinates
function where
.Fa x
is the x coordinate and
.Fa y_bit
is a value 0 or 1 to identify which of the two possible values for y
should be used.
.Pp
The functions
.Fn EC_POINT_set_compressed_coordinates_GFp
and
.Fn EC_POINT_set_compressed_coordinates_GF2m
are synonyms for
.Fn EC_POINT_set_compressed_coordinates .
They are defined for backwards compatibility only and should not be
used.
.Pp
In addition
.Vt EC_POINT
can be converted to and from various external representations.
The octet form is the binary encoding of the
.Sy ECPoint
structure (as defined in RFC5480 and used in certificates and TLS
records): only the content octets are present, the
.Sy OCTET STRING
tag and length are not included.
.Vt BIGNUM
form is the octet form interpreted as a big endian integer converted to
a
.Vt BIGNUM
structure.
Hexadecimal form is the octet form converted to a NULL terminated
character string where each character is one of the printable values 0-9
or A-F (or a-f).
.Pp
The functions
.Fn EC_POINT_point2oct ,
.Fn EC_POINT_oct2point ,
.Fn EC_POINT_point2bn ,
.Fn EC_POINT_bn2point ,
.Fn EC_POINT_point2hex
and
.Fn EC_POINT_hex2point
convert from and to EC_POINTs for the formats: octet, BIGNUM and
hexadecimal respectively.
.Pp
The function
.Fn EC_POINT_point2oct
encodes the given curve point
.Fa p
as an octet string into the buffer
.Fa buf
of size
.Fa len ,
using the specified conversion form
.Fa form .
The encoding conforms with Sec.
2.3.3 of the SECG SEC 1 ("Elliptic Curve Cryptography") standard.
Similarly the function
.Fn EC_POINT_oct2point
decodes a curve point into
.Fa p
from the octet string contained in the given buffer
.Fa buf
of size
.Fa len ,
conforming to Sec.
2.3.4 of the SECG SEC 1 ("Elliptic Curve Cryptography") standard.
.Pp
The functions
.Fn EC_POINT_point2hex
and
.Fn EC_POINT_point2bn
convert a point
.Fa p ,
respectively, to the hexadecimal or BIGNUM representation of the same
encoding of the function
.Fn EC_POINT_point2oct .
Vice versa, similarly to the function
.Fn EC_POINT_oct2point ,
the functions
.Fn EC_POINT_hex2point
and
.Fn EC_POINT_point2bn
decode the hexadecimal or BIGNUM representation into the EC_POINT
.Fa p .
.Pp
Notice that, according to the standard, the octet string encoding of the
point at infinity for a given curve is fixed to a single octet of value
zero and that, vice versa, a single octet of size zero is decoded as the
point at infinity.
.Pp
The function
.Fn EC_POINT_point2oct
must be supplied with a buffer long enough to store the octet form.
The return value provides the number of octets stored.
Calling the function with a NULL buffer will not perform the conversion
but will still return the required buffer length.
.Pp
The function
.Fn EC_POINT_point2buf
allocates a buffer of suitable length and writes an EC_POINT to it in
octet format.
The allocated buffer is written to
.Sy *pbuf
and its length is returned.
The caller must free up the allocated buffer with a call to
.Xr OPENSSL_free 3 .
Since the allocated buffer value is written to
.Sy *pbuf
the
.Fa pbuf
parameter
.Sy MUST NOT
be
.Dv NULL .
.Pp
The function
.Fn EC_POINT_point2hex
will allocate sufficient memory to store the hexadecimal string.
It is the caller's responsibility to free this memory with a subsequent
call to
.Xr OPENSSL_free 3 .
.Sh RETURN VALUES
.Fn EC_POINT_new
and
.Fn EC_POINT_dup
return the newly allocated EC_POINT or NULL on error.
.Pp
The following functions return 1 on success or 0 on error:
.Fn EC_POINT_copy ,
.Fn EC_POINT_set_to_infinity ,
.Fn EC_POINT_set_Jprojective_coordinates_GFp ,
.Fn EC_POINT_get_Jprojective_coordinates_GFp ,
.Fn EC_POINT_set_affine_coordinates_GFp ,
.Fn EC_POINT_get_affine_coordinates_GFp ,
.Fn EC_POINT_set_compressed_coordinates_GFp ,
.Fn EC_POINT_set_affine_coordinates_GF2m ,
.Fn EC_POINT_get_affine_coordinates_GF2m ,
.Fn EC_POINT_set_compressed_coordinates_GF2m
and
.Fn EC_POINT_oct2point .
.Pp
EC_POINT_method_of returns the EC_METHOD associated with the supplied
EC_POINT.
.Pp
.Fn EC_POINT_point2oct
and
.Fn EC_POINT_point2buf
return the length of the required buffer or 0 on error.
.Pp
.Fn EC_POINT_point2bn
returns the pointer to the BIGNUM supplied, or NULL on error.
.Pp
.Fn EC_POINT_bn2point
returns the pointer to the EC_POINT supplied, or NULL on error.
.Pp
.Fn EC_POINT_point2hex
returns a pointer to the hex string, or NULL on error.
.Pp
.Fn EC_POINT_hex2point
returns the pointer to the EC_POINT supplied, or NULL on error.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr EC_GROUP_new 3 ,
.Xr EC_GROUP_copy 3 ,
.Xr EC_POINT_add 3 ,
.Xr EC_KEY_new 3 ,
.Xr EC_GFp_simple_method 3 ,
.Xr d2i_ECPKParameters 3
.Sh HISTORY
.Fn EC_POINT_method_of ,
.Fn EC_POINT_set_Jprojective_coordinates_GFp ,
.Fn EC_POINT_get_Jprojective_coordinates_GFp ,
.Fn EC_POINT_set_affine_coordinates_GFp ,
.Fn EC_POINT_get_affine_coordinates_GFp ,
.Fn EC_POINT_set_compressed_coordinates_GFp ,
.Fn EC_POINT_set_affine_coordinates_GF2m ,
.Fn EC_POINT_get_affine_coordinates_GF2m ,
.Fn EC_POINT_set_compressed_coordinates_GF2m ,
.Fn EC_POINT_point2bn ,
and
.Fn EC_POINT_bn2point
were deprecated in OpenSSL 3.0.
.Pp
.Sy EC_POINT_set_affine_coordinates ,
.Sy EC_POINT_get_affine_coordinates ,
and
.Sy EC_POINT_set_compressed_coordinates
were added in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2013-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
