.Dd 2025-09-30
.Dt EC_POINT_ADD 3ossl
.Os
.Sh NAME
.Nm EC_POINT_add ,
.Nm EC_POINT_dbl ,
.Nm EC_POINT_invert ,
.Nm EC_POINT_is_at_infinity ,
.Nm EC_POINT_is_on_curve ,
.Nm EC_POINT_cmp ,
.Nm EC_POINT_make_affine ,
.Nm EC_POINTs_make_affine ,
.Nm EC_POINTs_mul ,
.Nm EC_POINT_mul ,
.Nm EC_GROUP_precompute_mult ,
.Nm EC_GROUP_have_precompute_mult
.Nd Functions for performing mathematical operations and tests on EC_POINT objects
.Sh SYNOPSIS
.In openssl/ec.h
.Ft int
.Fo EC_POINT_add
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *r"
.Fa "const EC_POINT *a"
.Fa "const EC_POINT *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_dbl
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *r"
.Fa "const EC_POINT *a"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_invert
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *a"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_is_at_infinity
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *p"
.Fc
.Ft int
.Fo EC_POINT_is_on_curve
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *point"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_cmp
.Fa "const EC_GROUP *group"
.Fa "const EC_POINT *a"
.Fa "const EC_POINT *b"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINT_mul
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *r"
.Fa "const BIGNUM *n"
.Fa "const EC_POINT *q"
.Fa "const BIGNUM *m"
.Fa "BN_CTX *ctx"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo EC_POINT_make_affine
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *point"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINTs_make_affine
.Fa "const EC_GROUP *group"
.Fa "size_t num"
.Fa "EC_POINT *points[]"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_POINTs_mul
.Fa "const EC_GROUP *group"
.Fa "EC_POINT *r"
.Fa "const BIGNUM *n"
.Fa "size_t num"
.Fa "const EC_POINT *p[]"
.Fa "const BIGNUM *m[]"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_GROUP_precompute_mult
.Fa "EC_GROUP *group"
.Fa "BN_CTX *ctx"
.Fc
.Ft int
.Fo EC_GROUP_have_precompute_mult
.Fa "const EC_GROUP *group"
.Fc
.Sh DESCRIPTION
EC_POINT_add adds the two points
.Fa a
and
.Fa b
and places the result in
.Fa r .
Similarly EC_POINT_dbl doubles the point
.Fa a
and places the result in
.Fa r .
In both cases it is valid for
.Fa r
to be one of
.Fa a
or
.Fa b .
.Pp
EC_POINT_invert calculates the inverse of the supplied point
.Fa a .
The result is placed back in
.Fa a .
.Pp
The function EC_POINT_is_at_infinity tests whether the supplied point is
at infinity or not.
.Pp
EC_POINT_is_on_curve tests whether the supplied point is on the curve or
not.
.Pp
EC_POINT_cmp compares the two supplied points and tests whether or not
they are equal.
.Pp
The functions EC_POINT_make_affine and EC_POINTs_make_affine force the
internal representation of the EC_POINT(s) into the affine coordinate
system.
In the case of EC_POINTs_make_affine the value
.Fa num
provides the number of points in the array
.Sy points
to be forced.
These functions were deprecated in OpenSSL 3.0 and should no longer be
used.
Modern versions automatically perform this conversion when needed.
.Pp
EC_POINT_mul calculates the value generator *
.Fa n
+
.Fa q
*
.Fa m
and stores the result in
.Fa r .
The value
.Fa n
may be NULL in which case the result is just
.Fa q
*
.Fa m
(variable point multiplication).
Alternatively, both
.Fa q
and
.Fa m
may be NULL, and
.Fa n
non-NULL, in which case the result is just generator *
.Fa n
(fixed point multiplication).
When performing a single fixed or variable point multiplication, the
underlying implementation uses a constant time algorithm, when the input
scalar (either
.Fa n
or
.Fa m )
is in the range [0, ec_group_order).
.Pp
Although deprecated in OpenSSL 3.0 and should no longer be used,
EC_POINTs_mul calculates the value generator *
.Fa n
+
.Sy q[0]
*
.Sy m[0]
+ ... +
.Sy q[num-1]
*
.Sy m[num-1] .
As for EC_POINT_mul the value
.Fa n
may be NULL or
.Fa num
may be zero.
When performing a fixed point multiplication
.Pf ( Fa n
is non-NULL and
.Fa num
is 0) or a variable point multiplication
.Pf ( Fa n
is NULL and
.Fa num
is 1), the underlying implementation uses a constant time algorithm,
when the input scalar (either
.Fa n
or
.Sy m[0] )
is in the range [0, ec_group_order).
Modern versions should instead use
.Fn EC_POINT_mul ,
combined (if needed) with
.Fn EC_POINT_add
in such rare circumstances.
.Pp
The function EC_GROUP_precompute_mult stores multiples of the generator
for faster point multiplication, whilst EC_GROUP_have_precompute_mult
tests whether precomputation has already been done.
See
.Xr EC_GROUP_copy 3
for information about the generator.
Precomputation functionality was deprecated in OpenSSL 3.0. Users of
.Fn EC_GROUP_precompute_mult
and
.Fn EC_GROUP_have_precompute_mult
should switch to named curves which OpenSSL has hardcoded lookup tables
for.
.Sh RETURN VALUES
The following functions return 1 on success or 0 on error: EC_POINT_add,
EC_POINT_dbl, EC_POINT_invert, EC_POINT_make_affine,
EC_POINTs_make_affine, EC_POINTs_make_affine, EC_POINT_mul,
EC_POINTs_mul and EC_GROUP_precompute_mult.
.Pp
EC_POINT_is_at_infinity returns 1 if the point is at infinity, or 0
otherwise.
.Pp
EC_POINT_is_on_curve returns 1 if the point is on the curve, 0 if not,
or -1 on error.
.Pp
EC_POINT_cmp returns 1 if the points are not equal, 0 if they are, or -1
on error.
.Pp
EC_GROUP_have_precompute_mult return 1 if a precomputation has been
done, or 0 if not.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr EC_GROUP_new 3 ,
.Xr EC_GROUP_copy 3 ,
.Xr EC_POINT_new 3 ,
.Xr EC_KEY_new 3 ,
.Xr EC_GFp_simple_method 3 ,
.Xr d2i_ECPKParameters 3
.Sh HISTORY
.Fn EC_POINT_make_affine ,
.Fn EC_POINTs_make_affine ,
.Fn EC_POINTs_mul ,
.Fn EC_GROUP_precompute_mult ,
and
.Fn EC_GROUP_have_precompute_mult
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2013-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
