.Dd 2025-09-30
.Dt ECDSA_SIGN 3ossl
.Os
.Sh NAME
.Nm ECDSA_size ,
.Nm ECDSA_sign ,
.Nm ECDSA_do_sign ,
.Nm ECDSA_verify ,
.Nm ECDSA_do_verify ,
.Nm ECDSA_sign_setup ,
.Nm ECDSA_sign_ex ,
.Nm ECDSA_do_sign_ex
.Nd deprecated low-level elliptic curve digital signature algorithm (ECDSA) functions
.Sh SYNOPSIS
.In openssl/ecdsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo ECDSA_size
.Fa "const EC_KEY *eckey"
.Fc
.Ft int
.Fo ECDSA_sign
.Fa "int type"
.Fa "const unsigned char *dgst"
.Fa "int dgstlen"
.Fa "unsigned char *sig"
.Fa "unsigned int *siglen"
.Fa "EC_KEY *eckey"
.Fc
.Ft ECDSA_SIG *
.Fo ECDSA_do_sign
.Fa "const unsigned char *dgst"
.Fa "int dgst_len"
.Fa "EC_KEY *eckey"
.Fc
.Ft int
.Fo ECDSA_verify
.Fa "int type"
.Fa "const unsigned char *dgst"
.Fa "int dgstlen"
.Fa "const unsigned char *sig"
.Fa "int siglen"
.Fa "EC_KEY *eckey"
.Fc
.Ft int
.Fo ECDSA_do_verify
.Fa "const unsigned char *dgst"
.Fa "int dgst_len"
.Fa "const ECDSA_SIG *sig"
.Fa "EC_KEY* eckey"
.Fc
.Ft ECDSA_SIG *
.Fo ECDSA_do_sign_ex
.Fa "const unsigned char *dgst"
.Fa "int dgstlen"
.Fa "const BIGNUM *kinv"
.Fa "const BIGNUM *rp"
.Fa "EC_KEY *eckey"
.Fc
.Ft int
.Fo ECDSA_sign_setup
.Fa "EC_KEY *eckey"
.Fa "BN_CTX *ctx"
.Fa "BIGNUM **kinv"
.Fa "BIGNUM **rp"
.Fc
.Ft int
.Fo ECDSA_sign_ex
.Fa "int type"
.Fa "const unsigned char *dgst"
.Fa "int dgstlen"
.Fa "unsigned char *sig"
.Fa "unsigned int *siglen"
.Fa "const BIGNUM *kinv"
.Fa "const BIGNUM *rp"
.Fa "EC_KEY *eckey"
.Fc
.Sh DESCRIPTION
See
.Xr ECDSA_SIG_new 3
for a description of the
.Vt ECDSA_SIG
object.
.Pp
See
.Xr i2d_ECDSA_SIG 3
and
.Xr d2i_ECDSA_SIG 3
for information about encoding and decoding ECDSA signatures to/from
DER.
.Pp
All of the functions described below are deprecated.
Applications should use the higher level
.Sy EVP
interface such as
.Xr EVP_DigestSignInit 3
or
.Xr EVP_DigestVerifyInit 3
instead.
.Pp
.Fn ECDSA_size
returns the maximum length of a DER encoded ECDSA signature created with
the private EC key
.Fa eckey .
To obtain the actual signature size use
.Xr EVP_PKEY_sign 3
with a NULL
.Fa sig
parameter.
.Pp
.Fn ECDSA_sign
computes a digital signature of the
.Fa dgstlen
bytes hash value
.Fa dgst
using the private EC key
.Fa eckey .
The DER encoded signatures is stored in
.Fa sig
and its length is returned in
.Fa siglen .
Note:
.Fa sig
must point to ECDSA_size(eckey) bytes of memory.
The parameter
.Fa type
is currently ignored.
.Fn ECDSA_sign
is wrapper function for
.Fn ECDSA_sign_ex
with
.Fa kinv
and
.Fa rp
set to NULL.
.Pp
.Fn ECDSA_do_sign
is similar to
.Fn ECDSA_sign
except the signature is returned as a newly allocated
.Vt ECDSA_SIG
structure (or NULL on error).
.Fn ECDSA_do_sign
is a wrapper function for
.Fn ECDSA_do_sign_ex
with
.Fa kinv
and
.Fa rp
set to NULL.
.Pp
.Fn ECDSA_verify
verifies that the signature in
.Fa sig
of size
.Fa siglen
is a valid ECDSA signature of the hash value
.Fa dgst
of size
.Fa dgstlen
using the public key
.Fa eckey .
The parameter
.Fa type
is ignored.
.Pp
.Fn ECDSA_do_verify
is similar to
.Fn ECDSA_verify
except the signature is presented in the form of a pointer to an
.Vt ECDSA_SIG
structure.
.Pp
The remaining functions utilise the internal
.Fa kinv
and
.Em r
values used during signature computation.
Most applications will never need to call these and some external ECDSA
ENGINE implementations may not support them at all if either
.Fa kinv
or
.Em r
is not NULL.
.Pp
.Fn ECDSA_sign_setup
may be used to precompute parts of the signing operation.
.Fa eckey
is the private EC key and
.Fa ctx
is a pointer to
.Vt BN_CTX
structure (or NULL). The precomputed values or returned in
.Fa kinv
and
.Fa rp
and can be used in a later call to
.Fn ECDSA_sign_ex
or
.Fn ECDSA_do_sign_ex .
.Pp
.Fn ECDSA_sign_ex
computes a digital signature of the
.Fa dgstlen
bytes hash value
.Fa dgst
using the private EC key
.Fa eckey
and the optional pre-computed values
.Fa kinv
and
.Fa rp .
The DER encoded signature is stored in
.Fa sig
and its length is returned in
.Fa siglen .
Note:
.Fa sig
must point to ECDSA_size(eckey) bytes of memory.
The parameter
.Fa type
is ignored.
.Pp
.Fn ECDSA_do_sign_ex
is similar to
.Fn ECDSA_sign_ex
except the signature is returned as a newly allocated
.Vt ECDSA_SIG
structure (or NULL on error).
.Sh RETURN VALUES
.Fn ECDSA_size
returns the maximum length signature or 0 on error.
.Pp
.Fn ECDSA_sign ,
.Fn ECDSA_sign_ex
and
.Fn ECDSA_sign_setup
return 1 if successful or 0 on error.
.Pp
.Fn ECDSA_do_sign
and
.Fn ECDSA_do_sign_ex
return a pointer to an allocated
.Vt ECDSA_SIG
structure or NULL on error.
.Pp
.Fn ECDSA_verify
and
.Fn ECDSA_do_verify
return 1 for a valid signature, 0 for an invalid signature and -1 on
error.
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh EXAMPLES
Creating an ECDSA signature of a given SHA-256 hash value using the
named curve prime256v1 (aka P-256). This example uses deprecated
functionality.
See
.Sx DESCRIPTION .
.Pp
First step: create an EC_KEY object (note: this part is
.Sy not
ECDSA specific)
.Bd -literal
 int ret;
 ECDSA_SIG *sig;
 EC_KEY *eckey;

 eckey = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
 if (eckey == NULL)
     /* error */
 if (EC_KEY_generate_key(eckey) == 0)
     /* error */
.Ed
.Pp
Second step: compute the ECDSA signature of a SHA-256 hash value using
.Fn ECDSA_do_sign :
.Bd -literal
 sig = ECDSA_do_sign(digest, 32, eckey);
 if (sig == NULL)
     /* error */
.Ed
.Pp
or using
.Fn ECDSA_sign :
.Bd -literal
 unsigned char *buffer, *pp;
 int buf_len;

 buf_len = ECDSA_size(eckey);
 buffer = OPENSSL_malloc(buf_len);
 pp = buffer;
 if (ECDSA_sign(0, dgst, dgstlen, pp, &buf_len, eckey) == 0)
     /* error */
.Ed
.Pp
Third step: verify the created ECDSA signature using
.Fn ECDSA_do_verify :
.Bd -literal
 ret = ECDSA_do_verify(digest, 32, sig, eckey);
.Ed
.Pp
or using
.Fn ECDSA_verify :
.Bd -literal
 ret = ECDSA_verify(0, digest, 32, buffer, buf_len, eckey);
.Ed
.Pp
and finally evaluate the return value:
.Bd -literal
 if (ret == 1)
     /* signature ok */
 else if (ret == 0)
     /* incorrect signature */
 else
     /* error */
.Ed
.Sh CONFORMING TO
ANSI X9.62, US Federal Information Processing Standard FIPS186-2
(Digital Signature Standard, DSS)
.Sh SEE ALSO
.Xr EC_KEY_new 3 ,
.Xr EVP_DigestSignInit 3 ,
.Xr EVP_DigestVerifyInit 3 ,
.Xr EVP_PKEY_sign 3
.Xr i2d_ECDSA_SIG 3 ,
.Xr d2i_ECDSA_SIG 3
.Sh HISTORY
All functionality described here was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2004-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
