.Dd 2025-09-30
.Dt ECDSA_SIG_NEW 3ossl
.Os
.Sh NAME
.Nm ECDSA_SIG_new ,
.Nm ECDSA_SIG_free ,
.Nm ECDSA_SIG_get0 ,
.Nm ECDSA_SIG_get0_r ,
.Nm ECDSA_SIG_get0_s ,
.Nm ECDSA_SIG_set0
.Nd Functions for creating, destroying and manipulating ECDSA_SIG objects
.Sh SYNOPSIS
.In openssl/ecdsa.h
.Ft ECDSA_SIG *
.Fo ECDSA_SIG_new
.Fa void
.Fc
.Ft void
.Fo ECDSA_SIG_free
.Fa "ECDSA_SIG *sig"
.Fc
.Ft void
.Fo ECDSA_SIG_get0
.Fa "const ECDSA_SIG *sig"
.Fa "const BIGNUM **pr"
.Fa "const BIGNUM **ps"
.Fc
.Ft const BIGNUM *
.Fo ECDSA_SIG_get0_r
.Fa "const ECDSA_SIG *sig"
.Fc
.Ft const BIGNUM *
.Fo ECDSA_SIG_get0_s
.Fa "const ECDSA_SIG *sig"
.Fc
.Ft int
.Fo ECDSA_SIG_set0
.Fa "ECDSA_SIG *sig"
.Fa "BIGNUM *r"
.Fa "BIGNUM *s"
.Fc
.Sh DESCRIPTION
.Vt ECDSA_SIG
is an opaque structure consisting of two BIGNUMs for the
.Fa r
and
.Fa s
value of an Elliptic Curve Digital Signature Algorithm (ECDSA) signature
(see FIPS186-4 or X9.62). The
.Vt ECDSA_SIG
object was mainly used by the deprecated low level functions described
in
.Xr ECDSA_sign 3 ,
it is still required in order to be able to set or get the values of
.Fa r
and
.Fa s
into or from a signature.
This is mainly used for testing purposes as shown in the
.Sx EXAMPLES .
.Pp
.Fn ECDSA_SIG_new
allocates an empty
.Vt ECDSA_SIG
structure.
Note: before OpenSSL 1.1.0, the
.Fa r
and
.Fa s
components were initialised.
.Pp
.Fn ECDSA_SIG_free
frees the
.Vt ECDSA_SIG
structure
.Fa sig .
If the argument is NULL, nothing is done.
.Pp
.Fn ECDSA_SIG_get0
returns internal pointers the
.Fa r
and
.Fa s
values contained in
.Fa sig
and stores them in
.Em *pr
and
.Em *ps ,
respectively.
The pointer
.Fa pr
or
.Fa ps
can be NULL, in which case the corresponding value is not returned.
.Pp
The values
.Fa r ,
.Fa s
can also be retrieved separately by the corresponding function
.Fn ECDSA_SIG_get0_r
and
.Fn ECDSA_SIG_get0_s ,
respectively.
.Pp
Non-NULL
.Fa r
and
.Fa s
values can be set on the
.Fa sig
by calling
.Fn ECDSA_SIG_set0 .
Calling this function transfers the memory management of the values to
the
.Vt ECDSA_SIG
object, and therefore the values that have been passed in should not be
freed by the caller.
.Pp
See
.Xr i2d_ECDSA_SIG 3
and
.Xr d2i_ECDSA_SIG 3
for information about encoding and decoding ECDSA signatures to/from
DER.
.Sh RETURN VALUES
.Fn ECDSA_SIG_new
returns NULL if the allocation fails.
.Pp
.Fn ECDSA_SIG_set0
returns 1 on success or 0 on failure.
.Pp
.Fn ECDSA_SIG_get0_r
and
.Fn ECDSA_SIG_get0_s
return the corresponding value, or NULL if it is unset.
.Sh EXAMPLES
Extract signature
.Fa r
and
.Fa s
values from a ECDSA
.Em signature
of size
.Em signaturelen :
.Bd -literal
 ECDSA_SIG *obj;
 const BIGNUM *r, *s;

 /* Load a signature into the ECDSA_SIG object */
 obj = d2i_ECDSA_SIG(NULL, &signature, signaturelen);
 if (obj == NULL)
     /* error */

 r = ECDSA_SIG_get0_r(obj);
 s = ECDSA_SIG_get0_s(obj);
 if (r == NULL || s == NULL)
     /* error */

 /* Use BN_bn2binpad() here to convert to r and s into byte arrays */

 /*
  * Do not try to access I<r> or I<s> after calling ECDSA_SIG_free(),
  * as they are both freed by this call.
  */
 ECDSA_SIG_free(obj);
.Ed
.Pp
Convert
.Fa r
and
.Fa s
byte arrays into an ECDSA_SIG
.Em signature
of size
.Em signaturelen :
.Bd -literal
 ECDSA_SIG *obj = NULL;
 unsigned char *signature = NULL;
 size_t signaturelen;
 BIGNUM *rbn = NULL, *sbn = NULL;

 obj = ECDSA_SIG_new();
 if (obj == NULL)
     /* error */
 rbn = BN_bin2bn(r, rlen, NULL);
 sbn = BN_bin2bn(s, slen, NULL);
 if (rbn == NULL || sbn == NULL)
     /* error */

 if (!ECDSA_SIG_set0(obj, rbn, sbn))
     /* error */
 /* Set these to NULL since they are now owned by obj */
 rbn = sbn = NULL;

 signaturelen = i2d_ECDSA_SIG(obj, &signature);
 if (signaturelen <= 0)
     /* error */

 /*
  * This signature could now be passed to L<EVP_DigestVerify(3)>
  * or L<EVP_DigestVerifyFinal(3)>
  */

 BN_free(rbn);
 BN_free(sbn);
 OPENSSL_free(signature);
 ECDSA_SIG_free(obj);
.Ed
.Sh CONFORMING TO
ANSI X9.62, US Federal Information Processing Standard FIPS186-4
(Digital Signature Standard, DSS)
.Sh SEE ALSO
.Xr EC_KEY_new 3 ,
.Xr EVP_DigestSignInit 3 ,
.Xr EVP_DigestVerifyInit 3 ,
.Xr EVP_PKEY_sign 3
.Xr i2d_ECDSA_SIG 3 ,
.Xr d2i_ECDSA_SIG 3 ,
.Xr ECDSA_sign 3
.Sh COPYRIGHT
Copyright 2004-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
