.Dd 2025-09-30
.Dt ECPKPARAMETERS_PRINT 3ossl
.Os
.Sh NAME
.Nm ECPKParameters_print ,
.Nm ECPKParameters_print_fp
.Nd Functions for decoding and encoding ASN1 representations of elliptic curve entities
.Sh SYNOPSIS
.In openssl/ec.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo ECPKParameters_print
.Fa "BIO *bp"
.Fa "const EC_GROUP *x"
.Fa "int off"
.Fc
.Ft int
.Fo ECPKParameters_print_fp
.Fa "FILE *fp"
.Fa "const EC_GROUP *x"
.Fa "int off"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_print_params 3
.Pp
The ECPKParameters represent the public parameters for an
.Sy EC_GROUP
structure, which represents a curve.
.Pp
The
.Fn ECPKParameters_print
and
.Fn ECPKParameters_print_fp
functions print a human-readable output of the public parameters of the
EC_GROUP to
.Fa bp
or
.Fa fp .
The output lines are indented by
.Fa off
spaces.
.Sh RETURN VALUES
.Fn ECPKParameters_print
and
.Fn ECPKParameters_print_fp
return 1 for success and 0 if an error occurs.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr EC_GROUP_new 3 ,
.Xr EC_GROUP_copy 3 ,
.Xr EC_POINT_new 3 ,
.Xr EC_POINT_add 3 ,
.Xr EC_KEY_new 3 ,
.Xr EC_GFp_simple_method 3 ,
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2013-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
