.Dd 2025-09-30
.Dt ERR_REMOVE_STATE 3ossl
.Os
.Sh NAME
.Nm ERR_remove_thread_state ,
.Nm ERR_remove_state
.Nd DEPRECATED
.Sh SYNOPSIS
The following function has been deprecated since OpenSSL 1.0.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo ERR_remove_state
.Fa "unsigned long tid"
.Fc
.Pp
The following function has been deprecated since OpenSSL 1.1.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo ERR_remove_thread_state
.Fa "void *tid"
.Fc
.Sh DESCRIPTION
.Fn ERR_remove_state
frees the error queue associated with the specified thread, identified
by
.Fa tid .
.Fn ERR_remove_thread_state
does the same thing, except the identifier is an opaque pointer.
.Sh RETURN VALUES
.Fn ERR_remove_state
and
.Fn ERR_remove_thread_state
return no value.
.Sh SEE ALSO
.Pf L Xr OPENSSL_init_crypto 3
.Sh HISTORY
.Fn ERR_remove_state
was deprecated in OpenSSL 1.0.0 and
.Fn ERR_remove_thread_state
was deprecated in OpenSSL 1.1.0; these functions and should not be used.
.Sh COPYRIGHT
Copyright 2000-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
