.Dd 2025-09-30
.Dt ERR_GET_ERROR 3ossl
.Os
.Sh NAME
.Nm ERR_get_error ,
.Nm ERR_peek_error ,
.Nm ERR_peek_last_error ,
.Nm ERR_get_error_line ,
.Nm ERR_peek_error_line ,
.Nm ERR_peek_last_error_line ,
.Nm ERR_peek_error_func ,
.Nm ERR_peek_last_error_func ,
.Nm ERR_peek_error_data ,
.Nm ERR_peek_last_error_data ,
.Nm ERR_get_error_all ,
.Nm ERR_peek_error_all ,
.Nm ERR_peek_last_error_all ,
.Nm ERR_get_error_line_data ,
.Nm ERR_peek_error_line_data ,
.Nm ERR_peek_last_error_line_data
.Nd obtain error code and data
.Sh SYNOPSIS
.In openssl/err.h
.Ft unsigned long
.Fo ERR_get_error
.Fa void
.Fc
.Ft unsigned long
.Fo ERR_peek_error
.Fa void
.Fc
.Ft unsigned long
.Fo ERR_peek_last_error
.Fa void
.Fc
.Ft unsigned long
.Fo ERR_peek_error_line
.Fa "const char **file"
.Fa "int *line"
.Fc
.Ft unsigned long
.Fo ERR_peek_last_error_line
.Fa "const char **file"
.Fa "int *line"
.Fc
.Ft unsigned long
.Fo ERR_peek_error_func
.Fa "const char **func"
.Fc
.Ft unsigned long
.Fo ERR_peek_last_error_func
.Fa "const char **func"
.Fc
.Ft unsigned long
.Fo ERR_peek_error_data
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Ft unsigned long
.Fo ERR_peek_last_error_data
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Ft unsigned long
.Fo ERR_get_error_all
.Fa "const char **file"
.Fa "int *line"
.Fa "const char **func"
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Ft unsigned long
.Fo ERR_peek_error_all
.Fa "const char **file"
.Fa "int *line"
.Fa "const char **func"
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Ft unsigned long
.Fo ERR_peek_last_error_all
.Fa "const char **file"
.Fa "int *line"
.Fa "const char *func"
.Fa "const char **data"
.Fa "int *flags"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft unsigned long
.Fo ERR_get_error_line
.Fa "const char **file"
.Fa "int *line"
.Fc
.Ft unsigned long
.Fo ERR_get_error_line_data
.Fa "const char **file"
.Fa "int *line"
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Ft unsigned long
.Fo ERR_peek_error_line_data
.Fa "const char **file"
.Fa "int *line"
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Ft unsigned long
.Fo ERR_peek_last_error_line_data
.Fa "const char **file"
.Fa "int *line"
.Fa "const char **data"
.Fa "int *flags"
.Fc
.Sh DESCRIPTION
.Fn ERR_get_error
returns the earliest error code from the thread's error queue and
removes the entry.
This function can be called repeatedly until there are no more error
codes to return.
.Pp
.Fn ERR_peek_error
returns the earliest error code from the thread's error queue without
modifying it.
.Pp
.Fn ERR_peek_last_error
returns the latest error code from the thread's error queue without
modifying it.
.Pp
See
.Xr ERR_GET_LIB 3
for obtaining further specific information such as the reason of the
error, and
.Xr ERR_error_string 3
for human-readable error messages.
.Pp
.Fn ERR_get_error_all
is the same as
.Fn ERR_get_error ,
but on success it additionally stores the filename, line number and
function where the error occurred in
.Pf * Fa file ,
.Pf * Fa line
and
.Pf * Fa func ,
and also extra text and flags in
.Pf * Fa data ,
.Pf * Fa flags .
If any of those parameters are NULL, it will not be changed.
An unset filename is indicated as "", i.e.
an empty string.
An unset line number is indicated as 0. An unset function name is
indicated as "", i.e.
an empty string.
.Pp
A pointer returned this way by these functions and the ones below is
valid until the respective entry is overwritten in the error queue.
.Pp
.Fn ERR_peek_error_line
and
.Fn ERR_peek_last_error_line
are the same as
.Fn ERR_peek_error
and
.Fn ERR_peek_last_error ,
but on success they additionally store the filename and line number
where the error occurred in
.Pf * Fa file
and
.Pf * Fa line ,
as far as they are not NULL. An unset filename is indicated as "", i.e.,
an empty string.
An unset line number is indicated as 0.
.Pp
.Fn ERR_peek_error_func
and
.Fn ERR_peek_last_error_func
are the same as
.Fn ERR_peek_error
and
.Fn ERR_peek_last_error ,
but on success they additionally store the name of the function where
the error occurred in
.Pf * Fa func ,
unless it is NULL. An unset function name is indicated as "".
.Pp
.Fn ERR_peek_error_data
and
.Fn ERR_peek_last_error_data
are the same as
.Fn ERR_peek_error
and
.Fn ERR_peek_last_error ,
but on success they additionally store additional data and flags
associated with the error code in
.Pf * Fa data
and
.Pf * Fa flags ,
as far as they are not NULL. Unset data is indicated as "". In this case
the value given for the flag is irrelevant (and equals 0).
.Pf * Fa data
contains a string if
.Pf * Fa flags Ns & Ns Sy ERR_TXT_STRING
is true.
.Pp
.Fn ERR_peek_error_all
and
.Fn ERR_peek_last_error_all
are combinations of all of the above.
.Pp
.Fn ERR_get_error_line ,
.Fn ERR_get_error_line_data ,
.Fn ERR_peek_error_line_data
and
.Fn ERR_peek_last_error_line_data
are older variants of
.Fn ERR_get_error_all ,
.Fn ERR_peek_error_all
and
.Fn ERR_peek_last_error_all ,
and may give confusing results.
They should no longer be used and are therefore deprecated.
.Pp
An application
.Sy MUST NOT
free the
.Pf * Fa data
pointer (or any other pointers returned by these functions) with
.Xr OPENSSL_free 3
as freeing is handled automatically by the error library.
.Sh RETURN VALUES
The error code, or 0 if there is no error in the queue.
.Sh SEE ALSO
.Xr ERR_error_string 3 ,
.Xr ERR_GET_LIB 3
.Sh HISTORY
.Fn ERR_peek_error_func ,
.Fn ERR_peek_last_error_func ,
.Fn ERR_peek_error_data ,
.Fn ERR_peek_last_error_data ,
.Fn ERR_peek_error_all
and
.Fn ERR_peek_last_error_all
were added in OpenSSL 3.0.
.Pp
.Fn ERR_get_error_line ,
.Fn ERR_get_error_line_data ,
.Fn ERR_peek_error_line_data
and
.Fn ERR_peek_last_error_line_data
became deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
