.Dd 2025-09-30
.Dt ERR_PUT_ERROR 3ossl
.Os
.Sh NAME
.Nm ERR_raise ,
.Nm ERR_raise_data ,
.Nm ERR_put_error ,
.Nm ERR_add_error_data ,
.Nm ERR_add_error_vdata ,
.Nm ERR_add_error_txt ,
.Nm ERR_add_error_mem_bio
.Nd record an error
.Sh SYNOPSIS
.In openssl/err.h
.Ft void
.Fo ERR_raise
.Fa "int lib"
.Fa "int reason"
.Fc
.Ft void
.Fo ERR_raise_data
.Fa "int lib"
.Fa "int reason"
.Fa "const char *fmt"
.Fa ...
.Fc
.Ft void
.Fo ERR_add_error_data
.Fa "int num"
.Fa ...
.Fc
.Ft void
.Fo ERR_add_error_vdata
.Fa "int num"
.Fa "va_list arg"
.Fc
.Ft void
.Fo ERR_add_error_txt
.Fa "const char *sep"
.Fa "const char *txt"
.Fc
.Ft void
.Fo ERR_add_error_mem_bio
.Fa "const char *sep"
.Fa "BIO *bio"
.Fc
The following function has been deprecated since OpenSSL 3.0, and can be
hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo ERR_put_error
.Fa "int lib"
.Fa "int func"
.Fa "int reason"
.Fa "const char *file"
.Fa "int line"
.Fc
.Sh DESCRIPTION
.Fn ERR_raise
adds a new error to the thread's error queue.
The error occurred in the library
.Fa lib
for the reason given by the
.Fa reason
code.
Furthermore, the name of the file, the line, and name of the function
where the error occurred is saved with the error record.
.Pp
.Fn ERR_raise_data
does the same thing as
.Fn ERR_raise ,
but also lets the caller specify additional information as a format
string
.Fa fmt
and an arbitrary number of values, which are processed with
.Xr BIO_snprintf 3 .
.Pp
.Fn ERR_put_error
adds an error code to the thread's error queue.
It signals that the error of reason code
.Fa reason
occurred in function
.Fa func
of library
.Fa lib ,
in line number
.Fa line
of
.Fa file .
This function is usually called by a macro.
.Pp
.Fn ERR_add_error_data
associates the concatenation of its
.Fa num
string arguments as additional data with the error code added last.
.Fn ERR_add_error_vdata
is similar except the argument is a
.Vt va_list .
Multiple calls to these functions append to the current top of the error
queue.
The total length of the string data per error is limited to 4096
characters.
.Pp
.Fn ERR_add_error_txt
appends the given text string as additional data to the last error queue
entry, after inserting the optional separator string if it is not NULL
and the top error entry does not yet have additional data.
In case the separator is at the end of the text it is not appended to
the data.
The
.Fa sep
argument may be for instance "\en" to insert a line break when needed.
If the associated data would become more than 4096 characters long
(which is the limit given above) it is split over sufficiently many new
copies of the last error queue entry.
.Pp
.Fn ERR_add_error_mem_bio
is the same as
.Fn ERR_add_error_txt
except that the text string is taken from the given memory BIO. It
appends '\e0' to the BIO contents if not already NUL-terminated.
.Pp
.Xr ERR_load_strings 3
can be used to register error strings so that the application can a
generate human-readable error messages for the error code.
.Ss Reporting errors
.Pp
.Em OpenSSL library reports
.Pp
Each OpenSSL sub-library has library code
.Sy ERR_LIB_XXX
and has its own set of reason codes
.Sy XXX_R_... .
These are both passed in combination to
.Fn ERR_raise
and
.Fn ERR_raise_data ,
and the combination ultimately produces the correct error text for the
reported error.
.Pp
All these macros and the numbers they have as values are specific to
OpenSSL's libraries.
OpenSSL reason codes normally consist of textual error descriptions.
For example, the function
.Xr ssl3_read_bytes 3
reports a "handshake failure" as follows:
.Bd -literal
 ERR_raise(ERR_LIB_SSL, SSL_R_SSL_HANDSHAKE_FAILURE);
.Ed
.Pp
There are two exceptions:
.Bl -tag -width Ds
.It Sy ERR_LIB_SYS
This "library code" indicates that a system error is being reported.
In this case, the reason code given to
.Fn ERR_raise
and
.Fn ERR_raise_data
.Em must
be
.Xr errno 3 .
.Bd -literal
 ERR_raise(ERR_LIB_SYS, errno);
.Ed
.It Sy ERR_R_XXX
This set of error codes is considered global, and may be used in
combination with any sub-library code.
.Bd -literal
 ERR_raise(ERR_LIB_RSA, ERR_R_PASSED_INVALID_ARGUMENT);
.Ed
.El
.Pp
.Em Other pieces of software
.Pp
Other pieces of software that may want to use OpenSSL's error reporting
system, such as engines or applications, must normally get their own
numbers.
.Bl -bullet
.It
To get a "library" code, call
.Xr ERR_get_next_error_library 3 ;
this gives the calling code a dynamic number, usable for the duration of
the process.
.It
Reason codes for each such "library" are determined or generated by the
authors of that code.
They must be numbers in the range 1 to 524287 (in other words, they must
be nonzero unsigned 18 bit integers).
.El
.Pp
The exceptions mentioned in
.Sx OpenSSL library reports
above are valid for other pieces of software, i.e.
they may use
.Sy ERR_LIB_SYS
to report system errors:
.Bd -literal
 ERR_raise(ERR_LIB_SYS, errno);
.Ed
.Pp
\&... and they may use
.Sy ERR_R_XXX
macros together with their own "library" code.
.Bd -literal
 int app_lib_code = ERR_get_next_error_library();

 /* ... */

 ERR_raise(app_lib_code, ERR_R_PASSED_INVALID_ARGUMENT);
.Ed
.Sh RETURN VALUES
.Fn ERR_raise ,
.Fn ERR_raise_data ,
.Fn ERR_put_error ,
.Fn ERR_add_error_data ,
.Fn ERR_add_error_vdata
.Fn ERR_add_error_txt ,
and
.Fn ERR_add_error_mem_bio
return no values.
.Sh NOTES
.Fn ERR_raise ,
.Fn ERR_raise
and
.Fn ERR_put_error
are implemented as macros.
.Sh SEE ALSO
.Xr ERR_load_strings 3 ,
.Xr ERR_get_next_error_library 3
.Sh HISTORY
ERR_raise, ERR_raise_data,
.Fn ERR_add_error_txt
and
.Fn ERR_add_error_mem_bio
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
