.Dd 2025-09-30
.Dt ERR_CLEAR_ERROR 3ossl
.Os
.Sh NAME
.Nm ERR_clear_error
.Nd clear the error queue
.Sh SYNOPSIS
.In openssl/err.h
.Ft void
.Fo ERR_clear_error
.Fa void
.Fc
.Sh DESCRIPTION
.Fn ERR_clear_error
empties the current thread's error queue.
.Sh RETURN VALUES
.Fn ERR_clear_error
has no return value.
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh COPYRIGHT
Copyright 2000-2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
