.Dd 2025-09-30
.Dt ERR_GET_LIB 3ossl
.Os
.Sh NAME
.Nm ERR_GET_LIB ,
.Nm ERR_GET_REASON ,
.Nm ERR_FATAL_ERROR
.Nd get information from error codes
.Sh SYNOPSIS
.In openssl/err.h
.Ft int
.Fo ERR_GET_LIB
.Fa "unsigned long e"
.Fc
.Ft int
.Fo ERR_GET_REASON
.Fa "unsigned long e"
.Fc
.Ft int
.Fo ERR_FATAL_ERROR
.Fa "unsigned long e"
.Fc
.Sh DESCRIPTION
The error code returned by
.Xr ERR_get_error 3
consists of a library number and reason code.
.Fn ERR_GET_LIB
and
.Fn ERR_GET_REASON
can be used to extract these.
.Pp
.Fn ERR_FATAL_ERROR
indicates whether a given error code is a fatal error.
.Pp
The library number describes where the error occurred, the reason code
is the information about what went wrong.
.Pp
Each sub-library of OpenSSL has a unique library number; the reason code
is unique within each sub-library.
Note that different libraries may use the same value to signal different
reasons.
.Pp
.Sy ERR_R_...
reason codes such as
.Sy ERR_R_MALLOC_FAILURE
are globally unique.
However, when checking for sub-library specific reason codes, be sure to
also compare the library number.
.Pp
.Fn ERR_GET_LIB ,
.Fn ERR_GET_REASON ,
and
.Fn ERR_FATAL_ERROR
are macros.
.Sh RETURN VALUES
The library number, reason code, and whether the error is fatal,
respectively.
Starting with OpenSSL 3.0.0, the function code is always set to zero.
.Sh NOTES
Applications should not make control flow decisions based on specific
error codes.
Error codes are subject to change at any time (even in patch releases of
OpenSSL). A particular error code can only be considered meaningful for
control flow decisions if it is explicitly documented as such.
New failure codes may still appear at any time.
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh HISTORY
.Fn ERR_GET_LIB
and
.Fn ERR_GET_REASON
are available in all versions of OpenSSL.
.Pp
.Xr ERR_GET_FUNC 3
was removed in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
