.Dd 2025-09-30
.Dt EVP_DESX_CBC 3ossl
.Os
.Sh NAME
.Nm EVP_desx_cbc
.Nd EVP DES-X cipher
.Sh SYNOPSIS
.In openssl/evp.h
.Ft const EVP_CIPHER *
.Fo EVP_desx_cbc
.Fa void
.Fc
.Sh DESCRIPTION
The DES-X encryption algorithm for EVP.
.Pp
All modes below use a key length of 128 bits and acts on blocks of
128-bits.
.Bl -tag -width Ds
.It EVP_desx_cbc()
The DES-X algorithm in CBC mode.
.Pp
This algorithm is not provided by the OpenSSL default provider.
To use it is necessary to load either the OpenSSL legacy provider or
another implementation.
.El
.Pp
Developers should be aware of the negative performance implications of
calling this function multiple times and should consider using
.Xr EVP_CIPHER_fetch 3
with
.Xr EVP_CIPHER-DES 7
instead.
See
.Xr crypto 7
for further information.
.Sh RETURN VALUES
These functions return an
.Sy EVP_CIPHER
structure that contains the implementation of the symmetric cipher.
See
.Xr EVP_CIPHER_meth_new 3
for details of the
.Sy EVP_CIPHER
structure.
.Sh SEE ALSO
.Xr evp 7 ,
.Xr EVP_EncryptInit 3 ,
.Xr EVP_CIPHER_meth_new 3
.Sh COPYRIGHT
Copyright 2017-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
