.Dd 2025-09-30
.Dt EVP_PKEY_CTX_GET_ALGOR 3ossl
.Os
.Sh NAME
.Nm EVP_CIPHER_CTX_get_algor ,
.Nm EVP_CIPHER_CTX_get_algor_params ,
.Nm EVP_CIPHER_CTX_set_algor_params ,
.Nm EVP_PKEY_CTX_get_algor ,
.Nm EVP_PKEY_CTX_get_algor_params ,
.Nm EVP_PKEY_CTX_set_algor_params
.Nd pass AlgorithmIdentifier and its params to/from algorithm implementations
.Sh SYNOPSIS
.Ft int
.Fo EVP_TYPE_CTX_get_algor
.Fa "EVP_TYPE_CTX *ctx"
.Fa "X509_ALGOR **alg"
.Fc
.Ft int
.Fo EVP_TYPE_CTX_get_algor_params
.Fa "EVP_TYPE_CTX *ctx"
.Fa "X509_ALGOR *alg"
.Fc
.Ft int
.Fo EVP_TYPE_CTX_set_algor_params
.Fa "EVP_TYPE_CTX *ctx"
.Fa "const X509_ALGOR *alg"
.Fc
.Sh DESCRIPTION
In the description here and the
.Sx SYNOPSIS
above,
.Sy Em TYPE
is used as a placeholder for any EVP operation type.
.Pp
.Sy EVP_ Ns Em TYPE Ns _CTX_get_algor Ns
.Xr 3
attempts to retrieve a complete AlgorithmIdentifier from the
.Sy EVP_ Ns Em TYPE
implementation, and populates
.Em *alg
with it.
If
.Fa alg
is NULL, calling this function will serve to see if calling this
function is supported at all by the
.Sy EVP_ Ns Em TYPE
implementation.
If
.Em *alg
is NULL, space will be allocated automatically, and assigned to
.Em *alg .
.Pp
.Sy EVP_ Ns Em TYPE Ns _CTX_get_algor_params Ns
.Xr 3
attempts to retrieve the
.Em parameters
part of an AlgorithmIdentifier from the
.Sy EVP_ Ns Em TYPE
implementation, and populates
.Em alg- Ns parameters>
with it.
If
.Fa alg
is NULL, calling this function will serve to see if calling this
function is supported at all by the
.Sy EVP_ Ns Em TYPE
implementation.
If
.Em alg->parameters
is NULL, space will be allocated automatically, and assigned to
.Em alg->parameters .
If
.Em alg->parameters
is not NULL, its previous contents will be overwritten with the
retrieved AlgorithmIdentifier parameters.
Beware!
.Pp
.Sy EVP_ Ns Em TYPE Ns _CTX_set_algor_params Ns
.Xr 3
attempts to pass
.Em alg->parameters
to the
.Sy EVP_ Ns Em TYPE
implementation.
If
.Fa alg
is NULL, calling this function will serve to see if calling this
function is supported at all by the
.Sy EVP_ Ns Em TYPE
implementation.
.Sh RETURN VALUES
All functions return 1 for success, and 0 or a negative number if an
error occurs.
In particular, -2 is returned when the function isn't supported by the
.Sy EVP_ Ns Em TYPE
implementation.
.Sh HISTORY
These functions were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
