.Dd 2025-09-30
.Dt EVP_PKEY_SET1_ENCODED_PUBLIC_KEY 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_set1_encoded_public_key ,
.Nm EVP_PKEY_get1_encoded_public_key ,
.Nm EVP_PKEY_set1_tls_encodedpoint ,
.Nm EVP_PKEY_get1_tls_encodedpoint
.Nd functions to set and get public key data within an EVP_PKEY
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_set1_encoded_public_key
.Fa "EVP_PKEY *pkey"
.Fa "const unsigned char *pub"
.Fa "size_t publen"
.Fc
.Ft size_t
.Fo EVP_PKEY_get1_encoded_public_key
.Fa "EVP_PKEY *pkey"
.Fa "unsigned char **ppub"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo EVP_PKEY_set1_tls_encodedpoint
.Fa "EVP_PKEY *pkey"
.Fa "const unsigned char *pt"
.Fa "size_t ptlen"
.Fc
.Ft size_t
.Fo EVP_PKEY_get1_tls_encodedpoint
.Fa "EVP_PKEY *pkey"
.Fa "unsigned char **ppt"
.Fc
.Sh DESCRIPTION
.Fn EVP_PKEY_set1_encoded_public_key
can be used to set the public key value within an existing EVP_PKEY
object, which does not yet have either a public or private key assigned.
For the built-in OpenSSL algorithms this currently only works for those
that support key exchange or key encapsulation.
Parameters are not set as part of this operation, so typically an
application will create an EVP_PKEY first, set the parameters on it, and
then call this function.
For example setting the parameters might be done using
.Xr EVP_PKEY_copy_parameters 3 .
.Pp
The format for the encoded public key will depend on the algorithm in
use.
For DH it should be encoded as a positive integer in big-endian form.
For EC is should be a point conforming to Sec.
2.3.4 of the SECG SEC 1 ("Elliptic Curve Cryptography") standard.
For
.Sy X25519
and
.Sy X448
it should be encoded in the format defined by RFC7748. For
.Sy ML-KEM-512 ,
.Sy ML-KEM-768
and
.Sy ML-KEM-1024 ,
this is the public key format defined in
.Sy FIPS 203
(the 12-bit per-coefficient encoded public
.Em t
vector and 32-byte matrix seed
.Em rho Ns ).
.Pp
The key to be updated is supplied in
.Fa pkey .
The buffer containing the encoded key is pointed to be
.Fa pub .
The length of the buffer is supplied in
.Fa publen .
.Pp
.Fn EVP_PKEY_get1_encoded_public_key
does the equivalent operation except that the encoded public key is
returned to the application.
The key containing the public key data is supplied in
.Fa pkey .
A buffer containing the encoded key will be allocated and stored in
.Sy *ppub .
The length of the encoded public key is returned by the function.
The application is responsible for freeing the allocated buffer.
.Pp
The macro
.Fn EVP_PKEY_set1_tls_encodedpoint
is deprecated and simply calls
.Fn EVP_PKEY_set1_encoded_public_key
with all the same arguments.
New applications should use
.Fn EVP_PKEY_set1_encoded_public_key
instead.
.Pp
The macro
.Fn EVP_PKEY_get1_tls_encodedpoint
is deprecated and simply calls
.Fn EVP_PKEY_get1_encoded_public_key
with all the same arguments.
New applications should use
.Fn EVP_PKEY_get1_encoded_public_key
instead.
.Sh RETURN VALUES
.Fn EVP_PKEY_set1_encoded_public_key
returns 1 for success and 0 or a negative value for failure.
.Pp
.Fn EVP_PKEY_get1_encoded_public_key
returns the length of the encoded key or 0 for failure.
.Sh EXAMPLES
See
.Xr EVP_PKEY_derive_init 3
and
.Xr EVP_PKEY_derive 3
for information about performing a key exchange operation.
.Ss Set up a peer's EVP_PKEY ready for a key exchange operation
.Bd -literal
 #include <openssl/evp.h>

 int exchange(EVP_PKEY *ourkey, unsigned char *peer_pub, size_t peer_pub_len)
 {
     EVP_PKEY *peerkey = EVP_PKEY_new();

     if (peerkey == NULL || EVP_PKEY_copy_parameters(peerkey, ourkey) <= 0)
         return 0;

     if (EVP_PKEY_set1_encoded_public_key(peerkey, peer_pub,
                                          peer_pub_len) <= 0)
         return 0;

     /* Do the key exchange here */

     EVP_PKEY_free(peerkey);

     return 1;
 }
.Ed
.Ss Get an encoded public key to send to a peer
.Bd -literal
 #include <openssl/evp.h>

 int get_encoded_pub_key(EVP_PKEY *ourkey)
 {
     unsigned char *pubkey;
     size_t pubkey_len;

    pubkey_len = EVP_PKEY_get1_encoded_public_key(ourkey, &pubkey);
    if (pubkey_len == 0)
        return 0;

    /*
     * Send the encoded public key stored in the buffer at "pubkey" and of
     * length pubkey_len, to the peer.
     */

    OPENSSL_free(pubkey);
    return 1;
 }
.Ed
.Sh SEE ALSO
.Xr EVP_PKEY_new 3 ,
.Xr EVP_PKEY_copy_parameters 3 ,
.Xr EVP_PKEY_derive_init 3 ,
.Xr EVP_PKEY_derive 3 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-EC 7 ,
.Xr EVP_PKEY-X25519 7 ,
.Xr EVP_PKEY-X448 7 ,
.Xr EVP_PKEY-ML-KEM-512 7 ,
.Xr EVP_PKEY-ML-KEM-768 7 ,
.Xr EVP_PKEY-ML-KEM-1024 7 .
.Sh HISTORY
.Fn EVP_PKEY_set1_encoded_public_key
and
.Fn EVP_PKEY_get1_encoded_public_key
were added in OpenSSL 3.0.
.Pp
.Fn EVP_PKEY_set1_tls_encodedpoint
and
.Fn EVP_PKEY_get1_tls_encodedpoint
were deprecated in OpenSSL 3.0.
.Pp
Support for
.Sy ML-KEM
was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
