.Dd 2025-09-30
.Dt EVP_PKEY_COPY_PARAMETERS 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_missing_parameters ,
.Nm EVP_PKEY_copy_parameters ,
.Nm EVP_PKEY_parameters_eq ,
.Nm EVP_PKEY_cmp_parameters ,
.Nm EVP_PKEY_eq ,
.Nm EVP_PKEY_cmp
.Nd public key parameter and comparison functions
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_missing_parameters
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft int
.Fo EVP_PKEY_copy_parameters
.Fa "EVP_PKEY *to"
.Fa "const EVP_PKEY *from"
.Fc
.Ft int
.Fo EVP_PKEY_parameters_eq
.Fa "const EVP_PKEY *a"
.Fa "const EVP_PKEY *b"
.Fc
.Ft int
.Fo EVP_PKEY_eq
.Fa "const EVP_PKEY *a"
.Fa "const EVP_PKEY *b"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo EVP_PKEY_cmp_parameters
.Fa "const EVP_PKEY *a"
.Fa "const EVP_PKEY *b"
.Fc
.Ft int
.Fo EVP_PKEY_cmp
.Fa "const EVP_PKEY *a"
.Fa "const EVP_PKEY *b"
.Fc
.Sh DESCRIPTION
The function
.Fn EVP_PKEY_missing_parameters
returns 1 if the public key parameters of
.Fa pkey
are missing and 0 if they are present or the algorithm doesn't use
parameters.
.Pp
The function
.Fn EVP_PKEY_copy_parameters
copies the parameters from key
.Fa from
to key
.Fa to .
An error is returned if the parameters are missing in
.Fa from
or present in both
.Fa from
and
.Fa to
and mismatch.
If the parameters in
.Fa from
and
.Fa to
are both present and match this function has no effect.
.Pp
The function
.Fn EVP_PKEY_parameters_eq
checks the parameters of keys
.Fa a
and
.Fa b
for equality.
.Pp
The function
.Fn EVP_PKEY_eq
checks the keys
.Fa a
and
.Fa b
for equality, including their parameters if they are available.
.Sh NOTES
The main purpose of the functions
.Fn EVP_PKEY_missing_parameters
and
.Fn EVP_PKEY_copy_parameters
is to handle public keys in certificates where the parameters are
sometimes omitted from a public key if they are inherited from the CA
that signed it.
.Pp
The deprecated functions
.Fn EVP_PKEY_cmp
and
.Fn EVP_PKEY_cmp_parameters
differ in their return values compared to other
.Xr _cmp 3
functions.
They are aliases for
.Fn EVP_PKEY_eq
and
.Fn EVP_PKEY_parameters_eq .
.Pp
The function
.Fn EVP_PKEY_cmp
previously only checked the key parameters (if there are any) and the
public key, assuming that there always was a public key and that private
key equality could be derived from that.
Because it's no longer assumed that the private key in an
.Xr EVP_PKEY 3
is always accompanied by a public key, the comparison can not rely on
public key comparison alone.
.Pp
Instead,
.Fn EVP_PKEY_eq
(and therefore also
.Fn EVP_PKEY_cmp )
now compares:
.Bl -enum
.It
the key parameters (if there are any)
.It
the public keys or the private keys of the two
.Vt EVP_PKEY Ns s,
depending on what they both contain.
.El
.Sh RETURN VALUES
The function
.Fn EVP_PKEY_missing_parameters
returns 1 if the public key parameters of
.Fa pkey
are missing and 0 if they are present or the algorithm doesn't use
parameters.
.Pp
These functions
.Fn EVP_PKEY_copy_parameters
returns 1 for success and 0 for failure.
.Pp
The functions
.Fn EVP_PKEY_cmp_parameters ,
.Fn EVP_PKEY_parameters_eq ,
.Fn EVP_PKEY_cmp
and
.Fn EVP_PKEY_eq
return 1 if their inputs match, 0 if they don't match, -1 if the key
types are different and -2 if the operation is not supported.
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_keygen 3
.Sh HISTORY
The
.Fn EVP_PKEY_cmp
and
.Fn EVP_PKEY_cmp_parameters
functions were deprecated in OpenSSL 3.0.
.Pp
The
.Fn EVP_PKEY_eq
and
.Fn EVP_PKEY_parameters_eq
were added in OpenSSL 3.0 to replace
.Fn EVP_PKEY_cmp
and
.Fn EVP_PKEY_cmp_parameters .
.Sh COPYRIGHT
Copyright 2006-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
