.Dd 2025-09-30
.Dt EVP_KDF 3ossl
.Os
.Sh NAME
.Nm EVP_KDF ,
.Nm EVP_KDF_fetch ,
.Nm EVP_KDF_free ,
.Nm EVP_KDF_up_ref ,
.Nm EVP_KDF_CTX ,
.Nm EVP_KDF_CTX_new ,
.Nm EVP_KDF_CTX_free ,
.Nm EVP_KDF_CTX_dup ,
.Nm EVP_KDF_CTX_reset ,
.Nm EVP_KDF_derive ,
.Nm EVP_KDF_CTX_get_kdf_size ,
.Nm EVP_KDF_get0_provider ,
.Nm EVP_KDF_CTX_kdf ,
.Nm EVP_KDF_is_a ,
.Nm EVP_KDF_get0_name ,
.Nm EVP_KDF_names_do_all ,
.Nm EVP_KDF_get0_description ,
.Nm EVP_KDF_CTX_get_params ,
.Nm EVP_KDF_CTX_set_params ,
.Nm EVP_KDF_do_all_provided ,
.Nm EVP_KDF_get_params ,
.Nm EVP_KDF_gettable_params ,
.Nm EVP_KDF_gettable_ctx_params ,
.Nm EVP_KDF_settable_ctx_params ,
.Nm EVP_KDF_CTX_gettable_params ,
.Nm EVP_KDF_CTX_settable_params
.Nd EVP KDF routines
.Sh SYNOPSIS
.In openssl/kdf.h
.Ft typedef struct evp_kdf_st EVP_KDF;
 typedef struct evp_kdf_ctx_st EVP_KDF_CTX;

 EVP_KDF_CTX *
.Fo EVP_KDF_CTX_new
.Fa "EVP_KDF *kdf"
.Fc
.Ft const EVP_KDF *
.Fo EVP_KDF_CTX_kdf
.Fa "EVP_KDF_CTX *ctx"
.Fc
.Ft void
.Fo EVP_KDF_CTX_free
.Fa "EVP_KDF_CTX *ctx"
.Fc
.Ft EVP_KDF_CTX *
.Fo EVP_KDF_CTX_dup
.Fa "const EVP_KDF_CTX *src"
.Fc
.Ft void
.Fo EVP_KDF_CTX_reset
.Fa "EVP_KDF_CTX *ctx"
.Fc
.Ft size_t
.Fo EVP_KDF_CTX_get_kdf_size
.Fa "EVP_KDF_CTX *ctx"
.Fc
.Ft int
.Fo EVP_KDF_derive
.Fa "EVP_KDF_CTX *ctx"
.Fa "unsigned char *key"
.Fa "size_t keylen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_KDF_up_ref
.Fa "EVP_KDF *kdf"
.Fc
.Ft void
.Fo EVP_KDF_free
.Fa "EVP_KDF *kdf"
.Fc
.Ft EVP_KDF *
.Fo EVP_KDF_fetch
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *algorithm"
.Fa "const char *properties"
.Fc
.Ft int
.Fo EVP_KDF_is_a
.Fa "const EVP_KDF *kdf"
.Fa "const char *name"
.Fc
.Ft const char *
.Fo EVP_KDF_get0_name
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const char *
.Fo EVP_KDF_get0_description
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const OSSL_PROVIDER *
.Fo EVP_KDF_get0_provider
.Fa "const EVP_KDF *kdf"
.Fc
.Ft void
.Fo EVP_KDF_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*fn)(EVP_KDF *kdf"
.Fa "void *arg)"
.Fa "void *arg"
.Fc
.Ft int
.Fo EVP_KDF_names_do_all
.Fa "const EVP_KDF *kdf"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
.Ft int
.Fo EVP_KDF_get_params
.Fa "EVP_KDF *kdf"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_KDF_CTX_get_params
.Fa "EVP_KDF_CTX *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_KDF_CTX_set_params
.Fa "EVP_KDF_CTX *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KDF_gettable_params
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KDF_gettable_ctx_params
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KDF_settable_ctx_params
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KDF_CTX_gettable_params
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KDF_CTX_settable_params
.Fa "const EVP_KDF *kdf"
.Fc
.Ft const OSSL_PROVIDER *
.Fo EVP_KDF_get0_provider
.Fa "const EVP_KDF *kdf"
.Fc
.Sh DESCRIPTION
The EVP KDF routines are a high-level interface to Key Derivation
Function algorithms and should be used instead of algorithm-specific
functions.
.Pp
After creating a
.Vt EVP_KDF_CTX
for the required algorithm using
.Fn EVP_KDF_CTX_new ,
inputs to the algorithm are supplied either by passing them as part of
the
.Fn EVP_KDF_derive
call or using calls to
.Fn EVP_KDF_CTX_set_params
before calling
.Fn EVP_KDF_derive
to derive the key.
.Ss Types
.Vt EVP_KDF
is a type that holds the implementation of a KDF.
.Pp
.Vt EVP_KDF_CTX
is a context type that holds the algorithm inputs.
.Ss Algorithm implementation fetching
.Fn EVP_KDF_fetch
fetches an implementation of a KDF
.Fa algorithm ,
given a library context
.Fa libctx
and a set of
.Fa properties .
See
.Xr crypto 7
for further information.
.Pp
See
.Xr OSSL_PROVIDER-default 7
for the lists of algorithms supported by the default provider.
.Pp
The returned value must eventually be freed with
.Xr EVP_KDF_free 3 .
.Pp
.Fn EVP_KDF_up_ref
increments the reference count of an already fetched KDF.
.Pp
.Fn EVP_KDF_free
frees a fetched algorithm.
NULL is a valid parameter, for which this function is a no-op.
.Ss Context manipulation functions
.Fn EVP_KDF_CTX_new
creates a new context for the KDF implementation
.Fa kdf .
.Pp
.Fn EVP_KDF_CTX_free
frees up the context
.Fa ctx .
If
.Fa ctx
is NULL, nothing is done.
.Pp
.Fn EVP_KDF_CTX_kdf
returns the
.Vt EVP_KDF
associated with the context
.Fa ctx .
.Ss Computing functions
.Fn EVP_KDF_CTX_reset
resets the context to the default state as if the context had just been
created.
.Pp
.Fn EVP_KDF_derive
processes any parameters in
.Em Params
and then derives
.Fa keylen
bytes of key material and places it in the
.Fa key
buffer.
If the algorithm produces a fixed amount of output then an error will
occur unless the
.Fa keylen
parameter is equal to that output size, as returned by
.Fn EVP_KDF_CTX_get_kdf_size .
.Pp
.Fn EVP_KDF_get_params
retrieves details about the implementation
.Fa kdf .
The set of parameters given with
.Em params
determine exactly what parameters should be retrieved.
Note that a parameter that is unknown in the underlying context is
simply ignored.
.Pp
.Fn EVP_KDF_CTX_get_params
retrieves chosen parameters, given the context
.Fa ctx
and its underlying context.
The set of parameters given with
.Em params
determine exactly what parameters should be retrieved.
Note that a parameter that is unknown in the underlying context is
simply ignored.
.Pp
.Fn EVP_KDF_CTX_set_params
passes chosen parameters to the underlying context, given a context
.Fa ctx .
The set of parameters given with
.Em params
determine exactly what parameters are passed down.
Note that a parameter that is unknown in the underlying context is
simply ignored.
Also, what happens when a needed parameter isn't passed down is defined
by the implementation.
.Pp
.Fn EVP_KDF_gettable_params
returns an
.Xr OSSL_PARAM 3
array that describes the retrievable and settable parameters.
.Fn EVP_KDF_gettable_params
returns parameters that can be used with
.Fn EVP_KDF_get_params .
.Pp
.Fn EVP_KDF_gettable_ctx_params
and
.Fn EVP_KDF_CTX_gettable_params
return constant
.Xr OSSL_PARAM 3
arrays that describe the retrievable parameters that can be used with
.Fn EVP_KDF_CTX_get_params .
.Fn EVP_KDF_gettable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_KDF_CTX_gettable_params
returns the parameters that can be retrieved in the context's current
state.
.Pp
.Fn EVP_KDF_settable_ctx_params
and
.Fn EVP_KDF_CTX_settable_params
return constant
.Xr OSSL_PARAM 3
arrays that describe the settable parameters that can be used with
.Fn EVP_KDF_CTX_set_params .
.Fn EVP_KDF_settable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_KDF_CTX_settable_params
returns the parameters that can be retrieved in the context's current
state.
.Ss Information functions
.Fn EVP_KDF_CTX_get_kdf_size
returns the output size if the algorithm produces a fixed amount of
output and
.Sy SIZE_MAX
otherwise.
If an error occurs then 0 is returned.
For some algorithms an error may result if input parameters necessary to
calculate a fixed output size have not yet been supplied.
.Pp
.Fn EVP_KDF_is_a
returns 1 if
.Fa kdf
is an implementation of an algorithm that's identifiable with
.Fa name ,
otherwise 0.
.Pp
.Fn EVP_KDF_get0_provider
returns the provider that holds the implementation of the given
.Fa kdf .
.Pp
.Fn EVP_KDF_do_all_provided
traverses all KDF implemented by all activated providers in the given
library context
.Fa libctx ,
and for each of the implementations, calls the given function
.Em fn
with the implementation method and the given
.Fa arg
as argument.
.Pp
.Fn EVP_KDF_get0_name
return the name of the given KDF. For fetched KDFs with multiple names,
only one of them is returned; it's recommended to use
.Fn EVP_KDF_names_do_all
instead.
.Pp
.Fn EVP_KDF_names_do_all
traverses all names for
.Fa kdf ,
and calls
.Em fn
with each name and
.Fa data .
.Pp
.Fn EVP_KDF_get0_description
returns a description of the
.Fa kdf ,
meant for display and human consumption.
The description is at the discretion of the
.Fa kdf
implementation.
.Sh PARAMETERS
The standard parameter names are:
.Bl -tag -width Ds
.It \(dqpass" ( Ns Sy OSSL_KDF_PARAM_PASSWORD Ns ) <octet string>
Some KDF implementations require a password.
For those KDF implementations that support it, this parameter sets the
password.
.It \(dqsalt" ( Ns Sy OSSL_KDF_PARAM_SALT Ns ) <octet string>
Some KDF implementations can take a non-secret unique cryptographic
salt.
For those KDF implementations that support it, this parameter sets the
salt.
.Pp
The default value, if any, is implementation dependent.
.It \(dqiter" ( Ns Sy OSSL_KDF_PARAM_ITER Ns ) <unsigned integer>
Some KDF implementations require an iteration count.
For those KDF implementations that support it, this parameter sets the
iteration count.
.Pp
The default value, if any, is implementation dependent.
.It \(dqproperties" ( Ns Sy OSSL_KDF_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqmac" ( Ns Sy OSSL_KDF_PARAM_MAC Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_KDF_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqcipher" ( Ns Sy OSSL_KDF_PARAM_CIPHER Ns ) <UTF8 string>
For KDF implementations that use an underlying computation MAC, digest
or cipher, these parameters set what the algorithm should be.
.Pp
The value is always the name of the intended algorithm, or the
properties.
.Pp
Note that not all algorithms may support all possible underlying
implementations.
.It \(dqkey" ( Ns Sy OSSL_KDF_PARAM_KEY Ns ) <octet string>
Some KDF implementations require a key.
For those KDF implementations that support it, this octet string
parameter sets the key.
.It \(dqinfo" ( Ns Sy OSSL_KDF_PARAM_INFO Ns ) <octet string>
Some KDF implementations, such as
.Xr EVP_KDF-HKDF 7 ,
take an 'info' parameter for binding the derived key material to
application- and context-specific information.
This parameter sets the info, fixed info, other info or shared info
argument.
You can specify this parameter multiple times, and each instance will be
concatenated to form the final value.
.It \(dqmaclen" ( Ns Sy OSSL_KDF_PARAM_MAC_SIZE Ns ) <unsigned integer>
Used by implementations that use a MAC with a variable output size
(KMAC). For those KDF implementations that support it, this parameter
sets the MAC output size.
.Pp
The default value, if any, is implementation dependent.
The length must never exceed what can be given with a
.Vt size_t .
.It \(dqmaxmem_bytes" ( Ns Sy OSSL_KDF_PARAM_SCRYPT_MAXMEM Ns ) <unsigned integer>
Memory-hard password-based KDF algorithms, such as scrypt, use an amount
of memory that depends on the load factors provided as input.
For those KDF implementations that support it, this
.Sy uint64_t
parameter sets an upper limit on the amount of memory that may be
consumed while performing a key derivation.
If this memory usage limit is exceeded because the load factors are
chosen too high, the key derivation will fail.
.Pp
The default value is implementation dependent.
The memory size must never exceed what can be given with a
.Vt size_t .
.El
.Sh RETURN VALUES
.Fn EVP_KDF_fetch
returns a pointer to a newly fetched
.Vt EVP_KDF ,
or NULL if allocation failed.
.Pp
.Fn EVP_KDF_get0_provider
returns a pointer to the provider for the KDF, or NULL on error.
.Pp
.Fn EVP_KDF_up_ref
returns 1 on success, 0 on error.
.Pp
.Fn EVP_KDF_CTX_new
returns either the newly allocated
.Vt EVP_KDF_CTX
structure or NULL if an error occurred.
.Pp
.Fn EVP_KDF_CTX_free
and
.Fn EVP_KDF_CTX_reset
do not return a value.
.Pp
.Fn EVP_KDF_CTX_get_kdf_size
returns the output size.
.Sy SIZE_MAX
is returned to indicate that the algorithm produces a variable amount of
output; 0 to indicate failure.
.Pp
.Fn EVP_KDF_get0_name
returns the name of the KDF, or NULL on error.
.Pp
.Fn EVP_KDF_names_do_all
returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.Pp
The remaining functions return 1 for success and 0 for failure.
.Sh NOTES
The KDF life-cycle is described in
.Xr life_cycle-kdf 7 .
In the future, the transitions described there will be enforced.
When this is done, it will not be considered a breaking change to the
API.
.Sh SEE ALSO
.Xr OSSL_PROVIDER-default 7 ,
.Xr life_cycle-kdf 7 .
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
