.Dd 2025-09-30
.Dt EVP_PKEY_GET_ATTR 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_get_attr ,
.Nm EVP_PKEY_get_attr_count ,
.Nm EVP_PKEY_get_attr_by_NID ,
.Nm EVP_PKEY_get_attr_by_OBJ ,
.Nm EVP_PKEY_delete_attr ,
.Nm EVP_PKEY_add1_attr ,
.Nm EVP_PKEY_add1_attr_by_OBJ ,
.Nm EVP_PKEY_add1_attr_by_NID ,
.Nm EVP_PKEY_add1_attr_by_txt
.Nd EVP_PKEYX509_ATTRIBUTE No functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft int
.Fo EVP_PKEY_get_attr_count
.Fa "const EVP_PKEY *key"
.Fc
.Ft int
.Fo EVP_PKEY_get_attr_by_NID
.Fa "const EVP_PKEY *key"
.Fa "int nid"
.Fa "int lastpos"
.Fc
.Ft int
.Fo EVP_PKEY_get_attr_by_OBJ
.Fa "const EVP_PKEY *key"
.Fa "const ASN1_OBJECT *obj"
.Fa "int lastpos"
.Fc
.Ft X509_ATTRIBUTE *
.Fo EVP_PKEY_get_attr
.Fa "const EVP_PKEY *key"
.Fa "int loc"
.Fc
.Ft X509_ATTRIBUTE *
.Fo EVP_PKEY_delete_attr
.Fa "EVP_PKEY *key"
.Fa "int loc"
.Fc
.Ft int
.Fo EVP_PKEY_add1_attr
.Fa "EVP_PKEY *key"
.Fa "X509_ATTRIBUTE *attr"
.Fc
.Ft int
.Fo EVP_PKEY_add1_attr_by_OBJ
.Fa "EVP_PKEY *key"
.Fa "const ASN1_OBJECT *obj"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_add1_attr_by_NID
.Fa "EVP_PKEY *key"
.Fa "int nid"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_add1_attr_by_txt
.Fa "EVP_PKEY *key"
.Fa "const char *attrname"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Sh DESCRIPTION
These functions are used by
.Sy PKCS12 .
.Pp
.Fn EVP_PKEY_get_attr_by_OBJ
finds the location of the first matching object
.Fa obj
in the
.Fa key
attribute list.
The search starts at the position after
.Fa lastpos .
If the returned value is positive then it can be used on the next call
to
.Fn EVP_PKEY_get_attr_by_OBJ
as the value of
.Fa lastpos
in order to iterate through the remaining attributes.
.Fa lastpos
can be set to any negative value on the first call, in order to start
searching from the start of the attribute list.
.Pp
.Fn EVP_PKEY_get_attr_by_NID
is similar to
.Fn EVP_PKEY_get_attr_by_OBJ
except that it passes the numerical identifier (NID)
.Fa nid
associated with the object.
See <openssl/obj_mac.h> for a list of NID_*.
.Pp
.Fn EVP_PKEY_get_attr
returns the
.Vt X509_ATTRIBUTE
object at index
.Fa loc
in the
.Fa key
attribute list.
.Fa loc
should be in the range from 0 to
.Fn EVP_PKEY_get_attr_count
- 1.
.Pp
.Fn EVP_PKEY_delete_attr
removes the
.Vt X509_ATTRIBUTE
object at index
.Fa loc
in the
.Fa key
attribute list.
.Pp
.Fn EVP_PKEY_add1_attr
pushes a copy of the passed in
.Vt X509_ATTRIBUTE
object to the
.Fa key
attribute list.
A new
.Fa key
attribute list is created if required.
An error occurs if either
.Fa attr
is NULL, or the attribute already exists.
.Pp
.Fn EVP_PKEY_add1_attr_by_OBJ
creates a new
.Vt X509_ATTRIBUTE
using
.Xr X509_ATTRIBUTE_set1_object 3
and
.Xr X509_ATTRIBUTE_set1_data 3
to assign a new
.Fa obj
with type
.Fa type
and data
.Fa bytes
of length
.Fa len
and then pushes it to the
.Fa key
object's attribute list.
If
.Fa obj
already exists in the attribute list then an error occurs.
.Pp
.Fn EVP_PKEY_add1_attr_by_NID
is similar to
.Fn EVP_PKEY_add1_attr_by_OBJ
except that it passes the numerical identifier (NID)
.Fa nid
associated with the object.
See <openssl/obj_mac.h> for a list of NID_*.
.Pp
.Fn EVP_PKEY_add1_attr_by_txt
is similar to
.Fn EVP_PKEY_add1_attr_by_OBJ
except that it passes a name
.Fa attrname
associated with the object.
See <openssl/obj_mac.h> for a list of SN_* names.
.Sh RETURN VALUES
.Fn EVP_PKEY_get_attr_count
returns the number of attributes in the
.Fa key
object attribute list or -1 if the attribute list is NULL.
.Pp
.Fn EVP_PKEY_get_attr_by_OBJ
returns -1 if either the list is empty OR the object is not found,
otherwise it returns the location of the object in the list.
.Pp
.Fn EVP_PKEY_get_attr_by_NID
is similar to
.Fn EVP_PKEY_get_attr_by_OBJ ,
except that it returns -2 if the
.Fa nid
is not known by OpenSSL.
.Pp
.Fn EVP_PKEY_get_attr
returns either a
.Vt X509_ATTRIBUTE
or NULL if there is a error.
.Pp
.Fn EVP_PKEY_delete_attr
returns either the removed
.Vt X509_ATTRIBUTE
or NULL if there is a error.
.Pp
.Fn EVP_PKEY_add1_attr ,
.Fn EVP_PKEY_add1_attr_by_OBJ ,
.Fn EVP_PKEY_add1_attr_by_NID
and
.Fn EVP_PKEY_add1_attr_by_txt
return 1 on success or 0 otherwise.
.Sh NOTES
A
.Vt EVP_PKEY
object's attribute list is initially NULL. All the above functions
listed will return an error unless
.Fn EVP_PKEY_add1_attr
is called.
All functions listed assume that the
.Fa key
is not NULL.
.Sh SEE ALSO
.Xr X509_ATTRIBUTE 3
.Sh COPYRIGHT
Copyright 2023-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
