.Dd 2025-09-30
.Dt EVP_PKEY_CTX_CTRL 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_CTX_ctrl ,
.Nm EVP_PKEY_CTX_ctrl_str ,
.Nm EVP_PKEY_CTX_ctrl_uint64 ,
.Nm EVP_PKEY_CTX_md ,
.Nm EVP_PKEY_CTX_set_signature_md ,
.Nm EVP_PKEY_CTX_get_signature_md ,
.Nm EVP_PKEY_CTX_set_mac_key ,
.Nm EVP_PKEY_CTX_set_group_name ,
.Nm EVP_PKEY_CTX_get_group_name ,
.Nm EVP_PKEY_CTX_set_rsa_padding ,
.Nm EVP_PKEY_CTX_get_rsa_padding ,
.Nm EVP_PKEY_CTX_set_rsa_pss_saltlen ,
.Nm EVP_PKEY_CTX_get_rsa_pss_saltlen ,
.Nm EVP_PKEY_CTX_set_rsa_keygen_bits ,
.Nm EVP_PKEY_CTX_set_rsa_keygen_pubexp ,
.Nm EVP_PKEY_CTX_set1_rsa_keygen_pubexp ,
.Nm EVP_PKEY_CTX_set_rsa_keygen_primes ,
.Nm EVP_PKEY_CTX_set_rsa_mgf1_md_name ,
.Nm EVP_PKEY_CTX_set_rsa_mgf1_md ,
.Nm EVP_PKEY_CTX_get_rsa_mgf1_md ,
.Nm EVP_PKEY_CTX_get_rsa_mgf1_md_name ,
.Nm EVP_PKEY_CTX_set_rsa_oaep_md_name ,
.Nm EVP_PKEY_CTX_set_rsa_oaep_md ,
.Nm EVP_PKEY_CTX_get_rsa_oaep_md ,
.Nm EVP_PKEY_CTX_get_rsa_oaep_md_name ,
.Nm EVP_PKEY_CTX_set0_rsa_oaep_label ,
.Nm EVP_PKEY_CTX_get0_rsa_oaep_label ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_bits ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_q_bits ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_md ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_md_props ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_gindex ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_type ,
.Nm EVP_PKEY_CTX_set_dsa_paramgen_seed ,
.Nm EVP_PKEY_CTX_set_dh_paramgen_prime_len ,
.Nm EVP_PKEY_CTX_set_dh_paramgen_subprime_len ,
.Nm EVP_PKEY_CTX_set_dh_paramgen_generator ,
.Nm EVP_PKEY_CTX_set_dh_paramgen_type ,
.Nm EVP_PKEY_CTX_set_dh_paramgen_gindex ,
.Nm EVP_PKEY_CTX_set_dh_paramgen_seed ,
.Nm EVP_PKEY_CTX_set_dh_rfc5114 ,
.Nm EVP_PKEY_CTX_set_dhx_rfc5114 ,
.Nm EVP_PKEY_CTX_set_dh_pad ,
.Nm EVP_PKEY_CTX_set_dh_nid ,
.Nm EVP_PKEY_CTX_set_dh_kdf_type ,
.Nm EVP_PKEY_CTX_get_dh_kdf_type ,
.Nm EVP_PKEY_CTX_set0_dh_kdf_oid ,
.Nm EVP_PKEY_CTX_get0_dh_kdf_oid ,
.Nm EVP_PKEY_CTX_set_dh_kdf_md ,
.Nm EVP_PKEY_CTX_get_dh_kdf_md ,
.Nm EVP_PKEY_CTX_set_dh_kdf_outlen ,
.Nm EVP_PKEY_CTX_get_dh_kdf_outlen ,
.Nm EVP_PKEY_CTX_set0_dh_kdf_ukm ,
.Nm EVP_PKEY_CTX_get0_dh_kdf_ukm ,
.Nm EVP_PKEY_CTX_set_ec_paramgen_curve_nid ,
.Nm EVP_PKEY_CTX_set_ec_param_enc ,
.Nm EVP_PKEY_CTX_set_ecdh_cofactor_mode ,
.Nm EVP_PKEY_CTX_get_ecdh_cofactor_mode ,
.Nm EVP_PKEY_CTX_set_ecdh_kdf_type ,
.Nm EVP_PKEY_CTX_get_ecdh_kdf_type ,
.Nm EVP_PKEY_CTX_set_ecdh_kdf_md ,
.Nm EVP_PKEY_CTX_get_ecdh_kdf_md ,
.Nm EVP_PKEY_CTX_set_ecdh_kdf_outlen ,
.Nm EVP_PKEY_CTX_get_ecdh_kdf_outlen ,
.Nm EVP_PKEY_CTX_set0_ecdh_kdf_ukm ,
.Nm EVP_PKEY_CTX_get0_ecdh_kdf_ukm ,
.Nm EVP_PKEY_CTX_set1_id ,
.Nm EVP_PKEY_CTX_get1_id ,
.Nm EVP_PKEY_CTX_get1_id_len ,
.Nm EVP_PKEY_CTX_set_kem_op
.Nd algorithm specific control operations
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_CTX_ctrl
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int keytype"
.Fa "int optype"
.Fa "int cmd"
.Fa "int p1"
.Fa "void *p2"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_ctrl_uint64
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int keytype"
.Fa "int optype"
.Fa "int cmd"
.Fa "uint64_t value"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_ctrl_str
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *type"
.Fa "const char *value"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int optype"
.Fa "int cmd"
.Fa "const char *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_signature_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_signature_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD **pmd"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_mac_key
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *key"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_group_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *name"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_group_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "char *name"
.Fa "size_t namelen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_kem_op
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *op"
.Fc
.In openssl/rsa.h
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_padding
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int pad"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_rsa_padding
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int *pad"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_pss_saltlen
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int saltlen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_rsa_pss_saltlen
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int *saltlen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_keygen_bits
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int mbits"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set1_rsa_keygen_pubexp
.Fa "EVP_PKEY_CTX *ctx"
.Fa "BIGNUM *pubexp"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_keygen_primes
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int primes"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_mgf1_md_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *mdname"
.Fa "const char *mdprops"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_mgf1_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_rsa_mgf1_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD **md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_rsa_mgf1_md_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "char *name"
.Fa "size_t namelen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_oaep_md_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *mdname"
.Fa "const char *mdprops"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_oaep_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_rsa_oaep_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD **md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_rsa_oaep_md_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "char *name"
.Fa "size_t namelen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set0_rsa_oaep_label
.Fa "EVP_PKEY_CTX *ctx"
.Fa "void *label"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get0_rsa_oaep_label
.Fa "EVP_PKEY_CTX *ctx"
.Fa "unsigned char **label"
.Fc
.In openssl/dsa.h
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_bits
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int nbits"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_q_bits
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int qbits"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_md_props
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *md_name"
.Fa "const char *md_properties"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_type
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *name"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_gindex
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int gindex"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dsa_paramgen_seed
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *seed"
.Fa "size_t seedlen"
.Fc
.In openssl/dh.h
.Ft int
.Fo EVP_PKEY_CTX_set_dh_paramgen_prime_len
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_paramgen_subprime_len
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_paramgen_generator
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int gen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_paramgen_type
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int type"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_pad
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int pad"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_nid
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int nid"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_rfc5114
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int rfc5114"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dhx_rfc5114
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int rfc5114"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_paramgen_gindex
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int gindex"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_paramgen_seed
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *seed"
.Fa "size_t seedlen"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_kdf_type
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int kdf"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_dh_kdf_type
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set0_dh_kdf_oid
.Fa "EVP_PKEY_CTX *ctx"
.Fa "ASN1_OBJECT *oid"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get0_dh_kdf_oid
.Fa "EVP_PKEY_CTX *ctx"
.Fa "ASN1_OBJECT **oid"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_kdf_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_dh_kdf_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD **md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_dh_kdf_outlen
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_dh_kdf_outlen
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int *len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set0_dh_kdf_ukm
.Fa "EVP_PKEY_CTX *ctx"
.Fa "unsigned char *ukm"
.Fa "int len"
.Fc
.In openssl/ec.h
.Ft int
.Fo EVP_PKEY_CTX_set_ec_paramgen_curve_nid
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int nid"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_ec_param_enc
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int param_enc"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_ecdh_cofactor_mode
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int cofactor_mode"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_ecdh_cofactor_mode
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_ecdh_kdf_type
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int kdf"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_ecdh_kdf_type
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_ecdh_kdf_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_ecdh_kdf_md
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const EVP_MD **md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_ecdh_kdf_outlen
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_ecdh_kdf_outlen
.Fa "EVP_PKEY_CTX *ctx"
.Fa "int *len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set0_ecdh_kdf_ukm
.Fa "EVP_PKEY_CTX *ctx"
.Fa "unsigned char *ukm"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set1_id
.Fa "EVP_PKEY_CTX *ctx"
.Fa "void *id"
.Fa "size_t id_len"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get1_id
.Fa "EVP_PKEY_CTX *ctx"
.Fa "void *id"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get1_id_len
.Fa "EVP_PKEY_CTX *ctx"
.Fa "size_t *id_len"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.In openssl/rsa.h
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_keygen_pubexp
.Fa "EVP_PKEY_CTX *ctx"
.Fa "BIGNUM *pubexp"
.Fc
.In openssl/dh.h
.Ft int
.Fo EVP_PKEY_CTX_get0_dh_kdf_ukm
.Fa "EVP_PKEY_CTX *ctx"
.Fa "unsigned char **ukm"
.Fc
.In openssl/ec.h
.Ft int
.Fo EVP_PKEY_CTX_get0_ecdh_kdf_ukm
.Fa "EVP_PKEY_CTX *ctx"
.Fa "unsigned char **ukm"
.Fc
.Sh DESCRIPTION
.Fn EVP_PKEY_CTX_ctrl
sends a control operation to the context
.Fa ctx .
The key type used must match
.Fa keytype
if it is not -1. The parameter
.Fa optype
is a mask indicating which operations the control can be applied to.
The control command is indicated in
.Fa cmd
and any additional arguments in
.Fa p1
and
.Fa p2 .
.Pp
For
.Fa cmd
=
.Sy EVP_PKEY_CTRL_SET_MAC_KEY ,
.Fa p1
is the length of the MAC key, and
.Fa p2
is the MAC key.
This is used by Poly1305, SipHash, HMAC and CMAC.
.Pp
Applications will not normally call
.Fn EVP_PKEY_CTX_ctrl
directly but will instead call one of the algorithm specific functions
below.
.Pp
.Fn EVP_PKEY_CTX_ctrl_uint64
is a wrapper that directly passes a uint64 value as
.Fa p2
to
.Fn EVP_PKEY_CTX_ctrl .
.Pp
.Fn EVP_PKEY_CTX_ctrl_str
allows an application to send an algorithm specific control operation to
a context
.Fa ctx
in string form.
This is intended to be used for options specified on the command line or
in text files.
The commands supported are documented in the openssl utility command
line pages for the option
.Em -pkeyopt
which is supported by the
.Em pkeyutl ,
.Em genpkey
and
.Em req
commands.
.Pp
.Fn EVP_PKEY_CTX_md
sends a message digest control operation to the context
.Fa ctx .
The message digest is specified by its name
.Fa md .
.Pp
.Fn EVP_PKEY_CTX_set_signature_md
sets the message digest type used in a signature.
It can be used in the RSA, DSA and ECDSA algorithms.
.Pp
EVP_PKEY_CTX_get_signature_md()gets the message digest type used in a
signature.
It can be used in the RSA, DSA and ECDSA algorithms.
.Pp
Key generation typically involves setting up parameters to be used and
generating the private and public key data.
Some algorithm implementations allow private key data to be set
explicitly using
.Fn EVP_PKEY_CTX_set_mac_key .
In this case key generation is simply the process of setting up the
parameters for the key and then setting the raw key data to the value
explicitly.
Normally applications would call
.Xr EVP_PKEY_new_raw_private_key 3
or similar functions instead.
.Pp
.Fn EVP_PKEY_CTX_set_mac_key
can be used with any of the algorithms supported by the
.Xr EVP_PKEY_new_raw_private_key 3
function.
.Pp
.Fn EVP_PKEY_CTX_set_group_name
sets the group name to
.Fa name
for parameter and key generation.
For example for EC keys this will set the curve name and for DH keys it
will set the name of the finite field group.
.Pp
.Fn EVP_PKEY_CTX_get_group_name
finds the group name that's currently set with
.Fa ctx ,
and writes it to the location that
.Fa name
points at, as long as its size
.Fa namelen
is large enough to store that name, including a terminating NUL byte.
.Ss RSA parameters
.Fn EVP_PKEY_CTX_set_rsa_padding
sets the RSA padding mode for
.Fa ctx .
The
.Fa pad
parameter can take the value
.Sy RSA_PKCS1_PADDING
for PKCS#1 padding,
.Sy RSA_NO_PADDING
for no padding,
.Sy RSA_PKCS1_OAEP_PADDING
for OAEP padding (encrypt and decrypt only),
.Sy RSA_X931_PADDING
for X9.31 padding (signature operations only),
.Sy RSA_PKCS1_PSS_PADDING
(sign and verify only) and
.Sy RSA_PKCS1_WITH_TLS_PADDING
for TLS RSA ClientKeyExchange message padding (decryption only).
.Pp
Two RSA padding modes behave differently if
.Fn EVP_PKEY_CTX_set_signature_md
is used.
If this function is called for PKCS#1 padding the plaintext buffer is an
actual digest value and is encapsulated in a DigestInfo structure
according to PKCS#1 when signing and this structure is expected (and
stripped off) when verifying.
If this control is not used with RSA and PKCS#1 padding then the
supplied data is used directly and not encapsulated.
In the case of X9.31 padding for RSA the algorithm identifier byte is
added or checked and removed if this control is called.
If it is not called then the first byte of the plaintext buffer is
expected to be the algorithm identifier byte.
.Pp
.Fn EVP_PKEY_CTX_get_rsa_padding
gets the RSA padding mode for
.Fa ctx .
.Pp
.Fn EVP_PKEY_CTX_set_rsa_pss_saltlen
sets the RSA PSS salt length to
.Fa saltlen .
As its name implies it is only supported for PSS padding.
If this function is not called then the salt length is maximized up to
the digest length when signing and auto detection when verifying.
Four special values are supported:
.Bl -tag -width Ds
.It Sy RSA_PSS_SALTLEN_DIGEST
sets the salt length to the digest length.
.It Sy RSA_PSS_SALTLEN_MAX
sets the salt length to the maximum permissible value.
.It Sy RSA_PSS_SALTLEN_AUTO
causes the salt length to be automatically determined based on the
.Sy PSS
block structure when verifying.
When signing, it has the same meaning as
.Sy RSA_PSS_SALTLEN_MAX .
.It Sy RSA_PSS_SALTLEN_AUTO_DIGEST_MAX
causes the salt length to be automatically determined based on the
.Sy PSS
block structure when verifying, like
.Sy RSA_PSS_SALTLEN_AUTO .
When signing, the salt length is maximized up to a maximum of the digest
length to comply with FIPS 186-4 section 5.5.
.El
.Pp
.Fn EVP_PKEY_CTX_get_rsa_pss_saltlen
gets the RSA PSS salt length for
.Fa ctx .
The padding mode must already have been set to
.Sy RSA_PKCS1_PSS_PADDING .
.Pp
.Fn EVP_PKEY_CTX_set_rsa_keygen_bits
sets the RSA key length for RSA key generation to
.Em bits .
If not specified 2048 bits is used.
.Pp
.Fn EVP_PKEY_CTX_set1_rsa_keygen_pubexp
sets the public exponent value for RSA key generation to the value
stored in
.Fa pubexp .
Currently it should be an odd integer.
In accordance with the OpenSSL naming convention, the
.Fa pubexp
pointer must be freed independently of the EVP_PKEY_CTX (ie, it is
internally copied).
If not specified 65537 is used.
.Pp
.Fn EVP_PKEY_CTX_set_rsa_keygen_pubexp
does the same as
.Fn EVP_PKEY_CTX_set1_rsa_keygen_pubexp
except that there is no internal copy and therefore
.Fa pubexp
should not be modified or freed after the call.
.Pp
.Fn EVP_PKEY_CTX_set_rsa_keygen_primes
sets the number of primes for RSA key generation to
.Fa primes .
If not specified 2 is used.
.Pp
.Fn EVP_PKEY_CTX_set_rsa_mgf1_md_name
sets the MGF1 digest for RSA padding schemes to the digest named
.Fa mdname .
If the RSA algorithm implementation for the selected provider supports
it then the digest will be fetched using the properties
.Fa mdprops .
If not explicitly set the signing digest is used.
The padding mode must have been set to
.Sy RSA_PKCS1_OAEP_PADDING
or
.Sy RSA_PKCS1_PSS_PADDING .
.Pp
.Fn EVP_PKEY_CTX_set_rsa_mgf1_md
does the same as
.Fn EVP_PKEY_CTX_set_rsa_mgf1_md_name
except that the name of the digest is inferred from the supplied
.Fa md
and it is not possible to specify any properties.
.Pp
.Fn EVP_PKEY_CTX_get_rsa_mgf1_md_name
gets the name of the MGF1 digest algorithm for
.Fa ctx .
If not explicitly set the signing digest is used.
The padding mode must have been set to
.Sy RSA_PKCS1_OAEP_PADDING
or
.Sy RSA_PKCS1_PSS_PADDING .
.Pp
.Fn EVP_PKEY_CTX_get_rsa_mgf1_md
does the same as
.Fn EVP_PKEY_CTX_get_rsa_mgf1_md_name
except that it returns a pointer to an EVP_MD object instead.
Note that only known, built-in EVP_MD objects will be returned.
The EVP_MD object may be NULL if the digest is not one of these (such as
a digest only implemented in a third party provider).
.Pp
.Fn EVP_PKEY_CTX_set_rsa_oaep_md_name
sets the message digest type used in RSA OAEP to the digest named
.Fa mdname .
If the RSA algorithm implementation for the selected provider supports
it then the digest will be fetched using the properties
.Fa mdprops .
The padding mode must have been set to
.Sy RSA_PKCS1_OAEP_PADDING .
.Pp
.Fn EVP_PKEY_CTX_set_rsa_oaep_md
does the same as
.Fn EVP_PKEY_CTX_set_rsa_oaep_md_name
except that the name of the digest is inferred from the supplied
.Fa md
and it is not possible to specify any properties.
.Pp
.Fn EVP_PKEY_CTX_get_rsa_oaep_md_name
gets the message digest algorithm name used in RSA OAEP and stores it in
the buffer
.Fa name
which is of size
.Fa namelen .
The padding mode must have been set to
.Sy RSA_PKCS1_OAEP_PADDING .
The buffer should be sufficiently large for any expected digest
algorithm names or the function will fail.
.Pp
.Fn EVP_PKEY_CTX_get_rsa_oaep_md
does the same as
.Fn EVP_PKEY_CTX_get_rsa_oaep_md_name
except that it returns a pointer to an EVP_MD object instead.
Note that only known, built-in EVP_MD objects will be returned.
The EVP_MD object may be NULL if the digest is not one of these (such as
a digest only implemented in a third party provider).
.Pp
.Fn EVP_PKEY_CTX_set0_rsa_oaep_label
sets the RSA OAEP label to binary data
.Fa label
and its length in bytes to
.Fa len .
If
.Fa label
is NULL or
.Fa len
is 0, the label is cleared.
The library takes ownership of the label so the caller should not free
the original memory pointed to by
.Fa label .
The padding mode must have been set to
.Sy RSA_PKCS1_OAEP_PADDING .
.Pp
.Fn EVP_PKEY_CTX_get0_rsa_oaep_label
gets the RSA OAEP label to
.Fa label .
The return value is the label length.
The padding mode must have been set to
.Sy RSA_PKCS1_OAEP_PADDING .
The resulting pointer is owned by the library and should not be freed by
the caller.
.Pp
.Sy RSA_PKCS1_WITH_TLS_PADDING
is used when decrypting an RSA encrypted TLS pre-master secret in a TLS
ClientKeyExchange message.
It is the same as RSA_PKCS1_PADDING except that it additionally verifies
that the result is the correct length and the first two bytes are the
protocol version initially requested by the client.
If the encrypted content is publicly invalid then the decryption will
fail.
However, if the padding checks fail then decryption will still appear to
succeed but a random TLS premaster secret will be returned instead.
This padding mode accepts two parameters which can be set using the
.Xr EVP_PKEY_CTX_set_params 3
function.
These are OSSL_ASYM_CIPHER_PARAM_TLS_CLIENT_VERSION and
OSSL_ASYM_CIPHER_PARAM_TLS_NEGOTIATED_VERSION, both of which are
expected to be unsigned integers.
Normally only the first of these will be set and represents the TLS
protocol version that was first requested by the client (e.g.
0x0303 for TLSv1.2, 0x0302 for TLSv1.1 etc).
Historically some buggy clients would use the negotiated protocol
version instead of the protocol version first requested.
If this behaviour should be tolerated then
OSSL_ASYM_CIPHER_PARAM_TLS_NEGOTIATED_VERSION should be set to the
actual negotiated protocol version.
Otherwise it should be left unset.
.Pp
Similarly to the
.Sy RSA_PKCS1_WITH_TLS_PADDING
above, since OpenSSL version 3.2.0, the use of
.Sy RSA_PKCS1_PADDING
will return a randomly generated message instead of padding errors in
case padding checks fail.
Applications that want to remain secure while using earlier versions of
OpenSSL, or a provider that doesn't implement the implicit rejection
mechanism, still need to handle both the error code from the RSA
decryption operation and the returned message in a side channel secure
manner.
This protection against Bleichenbacher attacks can be disabled by
setting
.Sy OSSL_ASYM_CIPHER_PARAM_IMPLICIT_REJECTION
(an unsigned integer) to 0.
.Ss DSA parameters
.Fn EVP_PKEY_CTX_set_dsa_paramgen_bits
sets the number of bits used for DSA parameter generation to
.Fa nbits .
If not specified, 2048 is used.
.Pp
.Fn EVP_PKEY_CTX_set_dsa_paramgen_q_bits
sets the number of bits in the subprime parameter
.Em q
for DSA parameter generation to
.Fa qbits .
If not specified, 224 is used.
If a digest function is specified below, this parameter is ignored and
instead, the number of bits in
.Em q
matches the size of the digest.
.Pp
.Fn EVP_PKEY_CTX_set_dsa_paramgen_md
sets the digest function used for DSA parameter generation to
.Fa md .
If not specified, one of SHA-1, SHA-224, or SHA-256 is selected to match
the bit length of
.Em q
above.
.Pp
.Fn EVP_PKEY_CTX_set_dsa_paramgen_md_props
sets the digest function used for DSA parameter generation using
.Fa md_name
and
.Fa md_properties
to retrieve the digest from a provider.
If not specified,
.Fa md_name
will be set to one of SHA-1, SHA-224, or SHA-256 depending on the bit
length of
.Em q
above.
.Fa md_properties
is a property query string that has a default value of '' if not
specified.
.Pp
.Fn EVP_PKEY_CTX_set_dsa_paramgen_gindex
sets the
.Fa gindex
used by the generator G. The default value is -1 which uses unverifiable
g, otherwise a positive value uses verifiable g. This value must be
saved if key validation of g is required, since it is not part of a
persisted key.
.Pp
.Fn EVP_PKEY_CTX_set_dsa_paramgen_seed
sets the
.Fa seed
to use for generation rather than using a randomly generated value for
the seed.
This is useful for testing purposes only and can fail if the seed does
not produce primes for both p & q on its first iteration.
This value must be saved if key validation of p, q, and verifiable g are
required, since it is not part of a persisted key.
.Pp
.Fn EVP_PKEY_CTX_set_dsa_paramgen_type
sets the generation type to use FIPS186-4 generation if
.Fa name
is "fips186_4", or FIPS186-2 generation if
.Fa name
is "fips186_2". The default value for the default provider is
"fips186_2". The default value for the FIPS provider is "fips186_4".
.Ss DH parameters
.Fn EVP_PKEY_CTX_set_dh_paramgen_prime_len
sets the length of the DH prime parameter
.Em p
for DH parameter generation.
If this function is not called then 2048 is used.
Only accepts lengths greater than or equal to 256.
.Pp
.Fn EVP_PKEY_CTX_set_dh_paramgen_subprime_len
sets the length of the DH optional subprime parameter
.Em q
for DH parameter generation.
The default is 256 if the prime is at least 2048 bits long or 160
otherwise.
The DH paramgen type must have been set to "fips186_4".
.Pp
.Fn EVP_PKEY_CTX_set_dh_paramgen_generator
sets DH generator to
.Fa gen
for DH parameter generation.
If not specified 2 is used.
.Pp
.Fn EVP_PKEY_CTX_set_dh_paramgen_type
sets the key type for DH parameter generation.
The supported parameters are:
.Bl -tag -width Ds
.It Sy DH_PARAMGEN_TYPE_GROUP
Use a named group.
If only the safe prime parameter
.Em p
is set this can be used to select a ffdhe safe prime group of the
correct size.
.It Sy DH_PARAMGEN_TYPE_FIPS_186_4
FIPS186-4 FFC parameter generator.
.It Sy DH_PARAMGEN_TYPE_FIPS_186_2
FIPS186-2 FFC parameter generator (X9.42 DH).
.It Sy DH_PARAMGEN_TYPE_GENERATOR
Uses a safe prime generator g (PKCS#3 format).
.El
.Pp
The default in the default provider is
.Sy DH_PARAMGEN_TYPE_GENERATOR
for the "DH" keytype, and
.Sy DH_PARAMGEN_TYPE_FIPS_186_2
for the "DHX" keytype.
In the FIPS provider the default value is
.Sy DH_PARAMGEN_TYPE_GROUP
for the "DH" keytype and
.Pf < Sy DH_PARAMGEN_TYPE_FIPS_186_4
for the "DHX" keytype.
.Pp
.Fn EVP_PKEY_CTX_set_dh_paramgen_gindex
sets the
.Fa gindex
used by the generator G. The default value is -1 which uses unverifiable
g, otherwise a positive value uses verifiable g. This value must be
saved if key validation of g is required, since it is not part of a
persisted key.
.Pp
.Fn EVP_PKEY_CTX_set_dh_paramgen_seed
sets the
.Fa seed
to use for generation rather than using a randomly generated value for
the seed.
This is useful for testing purposes only and can fail if the seed does
not produce primes for both p & q on its first iteration.
This value must be saved if key validation of p, q, and verifiable g are
required, since it is not part of a persisted key.
.Pp
.Fn EVP_PKEY_CTX_set_dh_pad
sets the DH padding mode.
If
.Fa pad
is 1 the shared secret is padded with zeros up to the size of the DH
prime
.Em p .
If
.Fa pad
is zero (the default) then no padding is performed.
.Pp
.Fn EVP_PKEY_CTX_set_dh_nid
sets the DH parameters to values corresponding to
.Fa nid
as defined in RFC7919 or RFC3526. The
.Fa nid
parameter must be
.Sy NID_ffdhe2048 ,
.Sy NID_ffdhe3072 ,
.Sy NID_ffdhe4096 ,
.Sy NID_ffdhe6144 ,
.Sy NID_ffdhe8192 ,
.Sy NID_modp_1536 ,
.Sy NID_modp_2048 ,
.Sy NID_modp_3072 ,
.Sy NID_modp_4096 ,
.Sy NID_modp_6144 ,
.Sy NID_modp_8192
or
.Sy NID_undef
to clear the stored value.
This function can be called during parameter or key generation.
The nid parameter and the rfc5114 parameter are mutually exclusive.
.Pp
.Fn EVP_PKEY_CTX_set_dh_rfc5114
and
.Fn EVP_PKEY_CTX_set_dhx_rfc5114
both set the DH parameters to the values defined in RFC5114. The
.Fa rfc5114
parameter must be 1, 2 or 3 corresponding to RFC5114 sections 2.1, 2.2
and 2.3. or 0 to clear the stored value.
This macro can be called during parameter generation.
The
.Fa ctx
must have a key type of
.Sy EVP_PKEY_DHX .
The rfc5114 parameter and the nid parameter are mutually exclusive.
.Ss DH key derivation function parameters
Note that all of the following functions require that the
.Fa ctx
parameter has a private key type of
.Sy EVP_PKEY_DHX .
When using key derivation, the output of
.Xr EVP_PKEY_derive 3
is the output of the KDF instead of the DH shared secret.
The KDF output is typically used as a Key Encryption Key (KEK) that in
turn encrypts a Content Encryption Key (CEK).
.Pp
.Fn EVP_PKEY_CTX_set_dh_kdf_type
sets the key derivation function type to
.Fa kdf
for DH key derivation.
Possible values are
.Sy EVP_PKEY_DH_KDF_NONE
and
.Sy EVP_PKEY_DH_KDF_X9_42
which uses the key derivation specified in RFC2631 (based on the keying
algorithm described in X9.42). When using key derivation, the
.Em kdf_oid ,
.Em kdf_md
and
.Em kdf_outlen
parameters must also be specified.
.Pp
.Fn EVP_PKEY_CTX_get_dh_kdf_type
gets the key derivation function type for
.Fa ctx
used for DH key derivation.
Possible values are
.Sy EVP_PKEY_DH_KDF_NONE
and
.Sy EVP_PKEY_DH_KDF_X9_42 .
.Pp
.Fn EVP_PKEY_CTX_set0_dh_kdf_oid
sets the key derivation function object identifier to
.Fa oid
for DH key derivation.
This OID should identify the algorithm to be used with the Content
Encryption Key.
The library takes ownership of the object identifier so the caller
should not free the original memory pointed to by
.Fa oid .
.Pp
.Fn EVP_PKEY_CTX_get0_dh_kdf_oid
gets the key derivation function oid for
.Fa ctx
used for DH key derivation.
The resulting pointer is owned by the library and should not be freed by
the caller.
.Pp
.Fn EVP_PKEY_CTX_set_dh_kdf_md
sets the key derivation function message digest to
.Fa md
for DH key derivation.
Note that RFC2631 specifies that this digest should be SHA1 but OpenSSL
tolerates other digests.
.Pp
.Fn EVP_PKEY_CTX_get_dh_kdf_md
gets the key derivation function message digest for
.Fa ctx
used for DH key derivation.
.Pp
.Fn EVP_PKEY_CTX_set_dh_kdf_outlen
sets the key derivation function output length to
.Fa len
for DH key derivation.
.Pp
.Fn EVP_PKEY_CTX_get_dh_kdf_outlen
gets the key derivation function output length for
.Fa ctx
used for DH key derivation.
.Pp
.Fn EVP_PKEY_CTX_set0_dh_kdf_ukm
sets the user key material to
.Fa ukm
and its length to
.Fa len
for DH key derivation.
This parameter is optional and corresponds to the partyAInfo field in
RFC2631 terms.
The specification requires that it is 512 bits long but this is not
enforced by OpenSSL. The library takes ownership of the user key
material so the caller should not free the original memory pointed to by
.Fa ukm .
.Pp
.Fn EVP_PKEY_CTX_get0_dh_kdf_ukm
gets the user key material for
.Fa ctx .
The return value is the user key material length.
The resulting pointer is owned by the library and should not be freed by
the caller.
.Ss EC parameters
Use
.Fn EVP_PKEY_CTX_set_group_name
(described above) to set the curve name to
.Fa name
for parameter and key generation.
.Pp
.Fn EVP_PKEY_CTX_set_ec_paramgen_curve_nid
does the same as
.Fn EVP_PKEY_CTX_set_group_name ,
but is specific to EC and uses a
.Fa nid
rather than a name string.
.Pp
For EC parameter generation, one of
.Fn EVP_PKEY_CTX_set_group_name
or
.Fn EVP_PKEY_CTX_set_ec_paramgen_curve_nid
must be called or an error occurs because there is no default curve.
These function can also be called to set the curve explicitly when
generating an EC key.
.Pp
.Fn EVP_PKEY_CTX_get_group_name
(described above) can be used to obtain the curve name that's currently
set with
.Fa ctx .
.Pp
.Fn EVP_PKEY_CTX_set_ec_param_enc
sets the EC parameter encoding to
.Fa param_enc
when generating EC parameters or an EC key.
The encoding can be
.Sy OPENSSL_EC_EXPLICIT_CURVE
for explicit parameters (the default in versions of OpenSSL before
1.1.0) or
.Sy OPENSSL_EC_NAMED_CURVE
to use named curve form.
For maximum compatibility the named curve form should be used.
Note: the
.Sy OPENSSL_EC_NAMED_CURVE
value was added in OpenSSL 1.1.0; previous versions should use 0
instead.
.Ss ECDH parameters
.Fn EVP_PKEY_CTX_set_ecdh_cofactor_mode
sets the cofactor mode to
.Fa cofactor_mode
for ECDH key derivation.
Possible values are 1 to enable cofactor key derivation, 0 to disable it
and -1 to clear the stored cofactor mode and fallback to the private key
cofactor mode.
.Pp
.Fn EVP_PKEY_CTX_get_ecdh_cofactor_mode
returns the cofactor mode for
.Fa ctx
used for ECDH key derivation.
Possible values are 1 when cofactor key derivation is enabled and 0
otherwise.
.Ss ECDH key derivation function parameters
.Fn EVP_PKEY_CTX_set_ecdh_kdf_type
sets the key derivation function type to
.Fa kdf
for ECDH key derivation.
Possible values are
.Sy EVP_PKEY_ECDH_KDF_NONE
and
.Sy EVP_PKEY_ECDH_KDF_X9_63
which uses the key derivation specified in X9.63. When using key
derivation, the
.Em kdf_md
and
.Em kdf_outlen
parameters must also be specified.
.Pp
.Fn EVP_PKEY_CTX_get_ecdh_kdf_type
returns the key derivation function type for
.Fa ctx
used for ECDH key derivation.
Possible values are
.Sy EVP_PKEY_ECDH_KDF_NONE
and
.Sy EVP_PKEY_ECDH_KDF_X9_63 .
.Pp
.Fn EVP_PKEY_CTX_set_ecdh_kdf_md
sets the key derivation function message digest to
.Fa md
for ECDH key derivation.
Note that X9.63 specifies that this digest should be SHA1 but OpenSSL
tolerates other digests.
.Pp
.Fn EVP_PKEY_CTX_get_ecdh_kdf_md
gets the key derivation function message digest for
.Fa ctx
used for ECDH key derivation.
.Pp
.Fn EVP_PKEY_CTX_set_ecdh_kdf_outlen
sets the key derivation function output length to
.Fa len
for ECDH key derivation.
.Pp
.Fn EVP_PKEY_CTX_get_ecdh_kdf_outlen
gets the key derivation function output length for
.Fa ctx
used for ECDH key derivation.
.Pp
.Fn EVP_PKEY_CTX_set0_ecdh_kdf_ukm
sets the user key material to
.Fa ukm
for ECDH key derivation.
This parameter is optional and corresponds to the shared info in X9.63
terms.
The library takes ownership of the user key material so the caller
should not free the original memory pointed to by
.Fa ukm .
.Pp
.Fn EVP_PKEY_CTX_get0_ecdh_kdf_ukm
gets the user key material for
.Fa ctx .
The return value is the user key material length.
The resulting pointer is owned by the library and should not be freed by
the caller.
.Ss Other parameters
.Fn EVP_PKEY_CTX_set1_id ,
.Fn EVP_PKEY_CTX_get1_id
and
.Fn EVP_PKEY_CTX_get1_id_len
are used to manipulate the special identifier field for specific
signature algorithms such as SM2. The
.Fn EVP_PKEY_CTX_set1_id
sets an ID pointed by
.Fa id
with the length
.Fa id_len
to the library.
The library takes a copy of the id so that the caller can safely free
the original memory pointed to by
.Fa id .
.Fn EVP_PKEY_CTX_get1_id_len
returns the length of the ID set via a previous call to
.Fn EVP_PKEY_CTX_set1_id .
The length is usually used to allocate adequate memory for further calls
to
.Fn EVP_PKEY_CTX_get1_id .
.Fn EVP_PKEY_CTX_get1_id
returns the previously set ID value to caller in
.Fa id .
The caller should allocate adequate memory space for the
.Fa id
before calling
.Fn EVP_PKEY_CTX_get1_id .
.Pp
.Fn EVP_PKEY_CTX_set_kem_op
sets the KEM operation to run.
This can be set after
.Xr EVP_PKEY_encapsulate_init 3
or
.Xr EVP_PKEY_decapsulate_init 3
to select the kem operation.
For the key types that support encapsulation and don't have the default
operation, e.g.
RSA, this function must be called before
.Xr EVP_PKEY_encapsulate 3
or
.Xr EVP_PKEY_decapsulate 3 .
.Pp
The supported parameters for the built-in algorithms are documented in
.Xr EVP_KEM-RSA 7 ,
.Xr EVP_KEM-EC 7 ,
.Xr EVP_KEM-X25519 7 ,
.Xr EVP_KEM-X448 7 ,
and
.Xr EVP_KEM-ML-KEM 7 .
.Sh RETURN VALUES
All other functions described on this page return a positive value for
success and 0 or a negative value for failure.
In particular a return value of -2 indicates the operation is not
supported by the public key algorithm.
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_set_params 3 ,
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_encrypt 3 ,
.Xr EVP_PKEY_decrypt 3 ,
.Xr EVP_PKEY_sign 3 ,
.Xr EVP_PKEY_verify 3 ,
.Xr EVP_PKEY_verify_recover 3 ,
.Xr EVP_PKEY_derive 3 ,
.Xr EVP_PKEY_keygen 3
.Xr EVP_PKEY_encapsulate 3
.Xr EVP_PKEY_decapsulate 3
.Sh HISTORY
.Fn EVP_PKEY_CTX_get_rsa_oaep_md_name ,
.Fn EVP_PKEY_CTX_get_rsa_mgf1_md_name ,
.Fn EVP_PKEY_CTX_set_rsa_mgf1_md_name ,
.Fn EVP_PKEY_CTX_set_rsa_oaep_md_name ,
.Fn EVP_PKEY_CTX_set_dsa_paramgen_md_props ,
.Fn EVP_PKEY_CTX_set_dsa_paramgen_gindex ,
.Fn EVP_PKEY_CTX_set_dsa_paramgen_type ,
.Fn EVP_PKEY_CTX_set_dsa_paramgen_seed ,
.Fn EVP_PKEY_CTX_set_group_name
and
.Fn EVP_PKEY_CTX_get_group_name
were added in OpenSSL 3.0.
.Pp
The
.Fn EVP_PKEY_CTX_set1_id ,
.Fn EVP_PKEY_CTX_get1_id
and
.Fn EVP_PKEY_CTX_get1_id_len
macros were added in 1.1.1, other functions were added in OpenSSL 1.0.0.
.Pp
In OpenSSL 1.1.1 and below the functions were mostly macros.
From OpenSSL 3.0 they are all functions.
.Pp
.Fn EVP_PKEY_CTX_set_rsa_keygen_pubexp ,
.Fn EVP_PKEY_CTX_get0_dh_kdf_ukm ,
and
.Fn EVP_PKEY_CTX_get0_ecdh_kdf_ukm
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2006-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
