.Dd 2025-09-30
.Dt EVP_PKEY_METH_NEW 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_meth_new ,
.Nm EVP_PKEY_meth_free ,
.Nm EVP_PKEY_meth_copy ,
.Nm EVP_PKEY_meth_find ,
.Nm EVP_PKEY_meth_add0 ,
.Nm EVP_PKEY_METHOD ,
.Nm EVP_PKEY_meth_set_init ,
.Nm EVP_PKEY_meth_set_copy ,
.Nm EVP_PKEY_meth_set_cleanup ,
.Nm EVP_PKEY_meth_set_paramgen ,
.Nm EVP_PKEY_meth_set_keygen ,
.Nm EVP_PKEY_meth_set_sign ,
.Nm EVP_PKEY_meth_set_verify ,
.Nm EVP_PKEY_meth_set_verify_recover ,
.Nm EVP_PKEY_meth_set_signctx ,
.Nm EVP_PKEY_meth_set_verifyctx ,
.Nm EVP_PKEY_meth_set_encrypt ,
.Nm EVP_PKEY_meth_set_decrypt ,
.Nm EVP_PKEY_meth_set_derive ,
.Nm EVP_PKEY_meth_set_ctrl ,
.Nm EVP_PKEY_meth_set_digestsign ,
.Nm EVP_PKEY_meth_set_digestverify ,
.Nm EVP_PKEY_meth_set_check ,
.Nm EVP_PKEY_meth_set_public_check ,
.Nm EVP_PKEY_meth_set_param_check ,
.Nm EVP_PKEY_meth_set_digest_custom ,
.Nm EVP_PKEY_meth_get_init ,
.Nm EVP_PKEY_meth_get_copy ,
.Nm EVP_PKEY_meth_get_cleanup ,
.Nm EVP_PKEY_meth_get_paramgen ,
.Nm EVP_PKEY_meth_get_keygen ,
.Nm EVP_PKEY_meth_get_sign ,
.Nm EVP_PKEY_meth_get_verify ,
.Nm EVP_PKEY_meth_get_verify_recover ,
.Nm EVP_PKEY_meth_get_signctx ,
.Nm EVP_PKEY_meth_get_verifyctx ,
.Nm EVP_PKEY_meth_get_encrypt ,
.Nm EVP_PKEY_meth_get_decrypt ,
.Nm EVP_PKEY_meth_get_derive ,
.Nm EVP_PKEY_meth_get_ctrl ,
.Nm EVP_PKEY_meth_get_digestsign ,
.Nm EVP_PKEY_meth_get_digestverify ,
.Nm EVP_PKEY_meth_get_check ,
.Nm EVP_PKEY_meth_get_public_check ,
.Nm EVP_PKEY_meth_get_param_check ,
.Nm EVP_PKEY_meth_get_digest_custom ,
.Nm EVP_PKEY_meth_remove
.Nd manipulating EVP_PKEY_METHOD structure
.Sh SYNOPSIS
.In openssl/evp.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft typedef struct evp_pkey_method_st EVP_PKEY_METHOD;

 EVP_PKEY_METHOD *
.Fo EVP_PKEY_meth_new
.Fa "int id"
.Fa "int flags"
.Fc
.Ft void
.Fo EVP_PKEY_meth_free
.Fa "EVP_PKEY_METHOD *pmeth"
.Fc
.Ft void
.Fo EVP_PKEY_meth_copy
.Fa "EVP_PKEY_METHOD *dst"
.Fa "const EVP_PKEY_METHOD *src"
.Fc
.Ft const EVP_PKEY_METHOD *
.Fo EVP_PKEY_meth_find
.Fa "int type"
.Fc
.Ft int
.Fo EVP_PKEY_meth_add0
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fc
.Ft int
.Fo EVP_PKEY_meth_remove
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_init
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*init) (EVP_PKEY_CTX *ctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_copy
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*copy) (EVP_PKEY_CTX *dst"
.Fa "const EVP_PKEY_CTX *src)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_cleanup
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "void (*cleanup) (EVP_PKEY_CTX *ctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_paramgen
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*paramgen_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*paramgen) (EVP_PKEY_CTX *ctx"
.Fa "EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_keygen
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*keygen_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*keygen) (EVP_PKEY_CTX *ctx"
.Fa "EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_sign
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*sign_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*sign) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "size_t *siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_verify
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*verify_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*verify) (EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *sig"
.Fa "size_t siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_verify_recover
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*verify_recover_init) (EVP_PKEY_CTX                                                                    *ctx)"
.Fa "int (*verify_recover) (EVP_PKEY_CTX                                                               *ctx"
.Fa "unsigned char                                                               *sig"
.Fa "size_t *siglen"
.Fa "const unsigned                                                               char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_signctx
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*signctx_init) (EVP_PKEY_CTX *ctx"
.Fa "EVP_MD_CTX *mctx)"
.Fa "int (*signctx) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "size_t *siglen"
.Fa "EVP_MD_CTX *mctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_verifyctx
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*verifyctx_init) (EVP_PKEY_CTX *ctx"
.Fa "EVP_MD_CTX *mctx)"
.Fa "int (*verifyctx) (EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *sig"
.Fa "int siglen"
.Fa "EVP_MD_CTX *mctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_encrypt
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*encrypt_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*encryptfn) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outlen"
.Fa "const unsigned char *in"
.Fa "size_t inlen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_decrypt
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*decrypt_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*decrypt) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outlen"
.Fa "const unsigned char *in"
.Fa "size_t inlen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_derive
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*derive_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (*derive) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *key"
.Fa "size_t *keylen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_ctrl
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*ctrl) (EVP_PKEY_CTX *ctx"
.Fa "int type"
.Fa "int p1"
.Fa "void *p2)"
.Fa "int (*ctrl_str) (EVP_PKEY_CTX *ctx"
.Fa "const char *type"
.Fa "const char *value)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_digestsign
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*digestsign) (EVP_MD_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "size_t *siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_digestverify
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*digestverify) (EVP_MD_CTX *ctx"
.Fa "const unsigned char *sig"
.Fa "size_t siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_check
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*check) (EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_public_check
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*check) (EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_param_check
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*check) (EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_set_digest_custom
.Fa "EVP_PKEY_METHOD *pmeth"
.Fa "int (*digest_custom) (EVP_PKEY_CTX *ctx"
.Fa "EVP_MD_CTX *mctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_init
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pinit) (EVP_PKEY_CTX *ctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_copy
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pcopy) (EVP_PKEY_CTX *dst"
.Fa "EVP_PKEY_CTX *src)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_cleanup
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "void (**pcleanup) (EVP_PKEY_CTX *ctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_paramgen
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pparamgen_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**pparamgen) (EVP_PKEY_CTX *ctx"
.Fa "EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_keygen
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pkeygen_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**pkeygen) (EVP_PKEY_CTX *ctx"
.Fa "EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_sign
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**psign_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**psign) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "size_t *siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_verify
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pverify_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**pverify) (EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *sig"
.Fa "size_t siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_verify_recover
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pverify_recover_init) (EVP_PKEY_CTX                                                                      *ctx)"
.Fa "int (**pverify_recover) (EVP_PKEY_CTX                                                                 *ctx"
.Fa "unsigned char                                                                 *sig"
.Fa "size_t *siglen"
.Fa "const unsigned                                                                 char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_signctx
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**psignctx_init) (EVP_PKEY_CTX *ctx"
.Fa "EVP_MD_CTX *mctx)"
.Fa "int (**psignctx) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "size_t *siglen"
.Fa "EVP_MD_CTX *mctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_verifyctx
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pverifyctx_init) (EVP_PKEY_CTX *ctx"
.Fa "EVP_MD_CTX *mctx)"
.Fa "int (**pverifyctx) (EVP_PKEY_CTX *ctx"
.Fa "const unsigned char *sig"
.Fa "int siglen"
.Fa "EVP_MD_CTX *mctx)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_encrypt
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pencrypt_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**pencryptfn) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outlen"
.Fa "const unsigned char *in"
.Fa "size_t inlen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_decrypt
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pdecrypt_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**pdecrypt) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outlen"
.Fa "const unsigned char *in"
.Fa "size_t inlen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_derive
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pderive_init) (EVP_PKEY_CTX *ctx)"
.Fa "int (**pderive) (EVP_PKEY_CTX *ctx"
.Fa "unsigned char *key"
.Fa "size_t *keylen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_ctrl
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pctrl) (EVP_PKEY_CTX *ctx"
.Fa "int type"
.Fa "int p1"
.Fa "void *p2)"
.Fa "int (**pctrl_str) (EVP_PKEY_CTX *ctx"
.Fa "const char *type"
.Fa "const char *value)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_digestsign
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**digestsign) (EVP_MD_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "size_t *siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_digestverify
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**digestverify) (EVP_MD_CTX *ctx"
.Fa "const unsigned char *sig"
.Fa "size_t siglen"
.Fa "const unsigned char *tbs"
.Fa "size_t tbslen)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_check
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pcheck) (EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_public_check
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pcheck) (EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_param_check
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pcheck) (EVP_PKEY *pkey)"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get_digest_custom
.Fa "const EVP_PKEY_METHOD *pmeth"
.Fa "int (**pdigest_custom) (EVP_PKEY_CTX *ctx"
.Fa "EVP_MD_CTX *mctx)"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the OSSL_PROVIDER APIs.
.Pp
.Vt EVP_PKEY_METHOD
is a structure which holds a set of methods for a specific public key
cryptographic algorithm.
Those methods are usually used to perform different jobs, such as
generating a key, signing or verifying, encrypting or decrypting, etc.
.Pp
There are two places where the
.Vt EVP_PKEY_METHOD
objects are stored: one is a built-in static array representing the
standard methods for different algorithms, and the other one is a stack
of user-defined application-specific methods, which can be manipulated
by using
.Xr EVP_PKEY_meth_add0 3 .
.Pp
The
.Vt EVP_PKEY_METHOD
objects are usually referenced by
.Vt EVP_PKEY_CTX
objects.
.Ss Methods
The methods are the underlying implementations of a particular public
key algorithm present by the
.Vt EVP_PKEY_CTX
object.
.Bd -literal
 int (*init) (EVP_PKEY_CTX *ctx);
 int (*copy) (EVP_PKEY_CTX *dst, const EVP_PKEY_CTX *src);
 void (*cleanup) (EVP_PKEY_CTX *ctx);
.Ed
.Pp
The
.Xr init 3
method is called to initialize algorithm-specific data when a new
.Vt EVP_PKEY_CTX
is created.
As opposed to
.Xr init 3 ,
the
.Xr cleanup 3
method is called when an
.Vt EVP_PKEY_CTX
is freed.
The
.Xr copy 3
method is called when an
.Vt EVP_PKEY_CTX
is being duplicated.
Refer to
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_CTX_new_id 3 ,
.Xr EVP_PKEY_CTX_free 3
and
.Xr EVP_PKEY_CTX_dup 3 .
.Bd -literal
 int (*paramgen_init) (EVP_PKEY_CTX *ctx);
 int (*paramgen) (EVP_PKEY_CTX *ctx, EVP_PKEY *pkey);
.Ed
.Pp
The
.Xr paramgen_init 3
and
.Xr paramgen 3
methods deal with key parameter generation.
They are called by
.Xr EVP_PKEY_paramgen_init 3
and
.Xr EVP_PKEY_paramgen 3
to handle the parameter generation process.
.Bd -literal
 int (*keygen_init) (EVP_PKEY_CTX *ctx);
 int (*keygen) (EVP_PKEY_CTX *ctx, EVP_PKEY *pkey);
.Ed
.Pp
The
.Xr keygen_init 3
and
.Xr keygen 3
methods are used to generate the actual key for the specified algorithm.
They are called by
.Xr EVP_PKEY_keygen_init 3
and
.Xr EVP_PKEY_keygen 3 .
.Bd -literal
 int (*sign_init) (EVP_PKEY_CTX *ctx);
 int (*sign) (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen,
              const unsigned char *tbs, size_t tbslen);
.Ed
.Pp
The
.Xr sign_init 3
and
.Xr sign 3
methods are used to generate the signature of a piece of data using a
private key.
They are called by
.Xr EVP_PKEY_sign_init 3
and
.Xr EVP_PKEY_sign 3 .
.Bd -literal
 int (*verify_init) (EVP_PKEY_CTX *ctx);
 int (*verify) (EVP_PKEY_CTX *ctx,
                const unsigned char *sig, size_t siglen,
                const unsigned char *tbs, size_t tbslen);
.Ed
.Pp
The
.Xr verify_init 3
and
.Xr verify 3
methods are used to verify whether a signature is valid.
They are called by
.Xr EVP_PKEY_verify_init 3
and
.Xr EVP_PKEY_verify 3 .
.Bd -literal
 int (*verify_recover_init) (EVP_PKEY_CTX *ctx);
 int (*verify_recover) (EVP_PKEY_CTX *ctx,
                        unsigned char *rout, size_t *routlen,
                        const unsigned char *sig, size_t siglen);
.Ed
.Pp
The
.Xr verify_recover_init 3
and
.Xr verify_recover 3
methods are used to verify a signature and then recover the digest from
the signature (for instance, a signature that was generated by RSA
signing algorithm).
They are called by
.Xr EVP_PKEY_verify_recover_init 3
and
.Xr EVP_PKEY_verify_recover 3 .
.Bd -literal
 int (*signctx_init) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx);
 int (*signctx) (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen,
                 EVP_MD_CTX *mctx);
.Ed
.Pp
The
.Xr signctx_init 3
and
.Xr signctx 3
methods are used to sign a digest present by a
.Vt EVP_MD_CTX
object.
They are called by the EVP_DigestSign functions.
See
.Xr EVP_DigestSignInit 3
for details.
.Bd -literal
 int (*verifyctx_init) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx);
 int (*verifyctx) (EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen,
                   EVP_MD_CTX *mctx);
.Ed
.Pp
The
.Xr verifyctx_init 3
and
.Xr verifyctx 3
methods are used to verify a signature against the data in a
.Vt EVP_MD_CTX
object.
They are called by the various EVP_DigestVerify functions.
See
.Xr EVP_DigestVerifyInit 3
for details.
.Bd -literal
 int (*encrypt_init) (EVP_PKEY_CTX *ctx);
 int (*encrypt) (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen,
                 const unsigned char *in, size_t inlen);
.Ed
.Pp
The
.Xr encrypt_init 3
and
.Xr encrypt 3
methods are used to encrypt a piece of data.
They are called by
.Xr EVP_PKEY_encrypt_init 3
and
.Xr EVP_PKEY_encrypt 3 .
.Bd -literal
 int (*decrypt_init) (EVP_PKEY_CTX *ctx);
 int (*decrypt) (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen,
                 const unsigned char *in, size_t inlen);
.Ed
.Pp
The
.Xr decrypt_init 3
and
.Xr decrypt 3
methods are used to decrypt a piece of data.
They are called by
.Xr EVP_PKEY_decrypt_init 3
and
.Xr EVP_PKEY_decrypt 3 .
.Bd -literal
 int (*derive_init) (EVP_PKEY_CTX *ctx);
 int (*derive) (EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen);
.Ed
.Pp
The
.Xr derive_init 3
and
.Xr derive 3
methods are used to derive the shared secret from a public key algorithm
(for instance, the DH algorithm).
They are called by
.Xr EVP_PKEY_derive_init 3
and
.Xr EVP_PKEY_derive 3 .
.Bd -literal
 int (*ctrl) (EVP_PKEY_CTX *ctx, int type, int p1, void *p2);
 int (*ctrl_str) (EVP_PKEY_CTX *ctx, const char *type, const char *value);
.Ed
.Pp
The
.Xr ctrl 3
and
.Xr ctrl_str 3
methods are used to adjust algorithm-specific settings.
See
.Xr EVP_PKEY_CTX_ctrl 3
and related functions for details.
.Bd -literal
 int (*digestsign) (EVP_MD_CTX *ctx, unsigned char *sig, size_t *siglen,
                    const unsigned char *tbs, size_t tbslen);
 int (*digestverify) (EVP_MD_CTX *ctx, const unsigned char *sig,
                      size_t siglen, const unsigned char *tbs,
                      size_t tbslen);
.Ed
.Pp
The
.Xr digestsign 3
and
.Xr digestverify 3
methods are used to generate or verify a signature in a one-shot mode.
They could be called by
.Xr EVP_DigestSign 3
and
.Xr EVP_DigestVerify 3 .
.Bd -literal
 int (*check) (EVP_PKEY *pkey);
 int (*public_check) (EVP_PKEY *pkey);
 int (*param_check) (EVP_PKEY *pkey);
.Ed
.Pp
The
.Xr check 3 ,
.Xr public_check 3
and
.Xr param_check 3
methods are used to validate a key-pair, the public component and
parameters respectively for a given
.Sy pkey .
They could be called by
.Xr EVP_PKEY_check 3 ,
.Xr EVP_PKEY_public_check 3
and
.Xr EVP_PKEY_param_check 3
respectively.
.Bd -literal
 int (*digest_custom) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx);
.Ed
.Pp
The
.Xr digest_custom 3
method is used to generate customized digest content before the real
message is passed to functions like
.Xr EVP_DigestSignUpdate 3
or
.Xr EVP_DigestVerifyInit 3 .
This is usually required by some public key signature algorithms like
SM2 which requires a hashed prefix to the message to be signed.
The
.Xr digest_custom 3
function will be called by
.Xr EVP_DigestSignInit 3
and
.Xr EVP_DigestVerifyInit 3 .
.Ss Functions
.Fn EVP_PKEY_meth_new
creates and returns a new
.Vt EVP_PKEY_METHOD
object, and associates the given
.Fa id
and
.Fa flags .
The following flags are supported:
.Bd -literal
 EVP_PKEY_FLAG_AUTOARGLEN
 EVP_PKEY_FLAG_SIGCTX_CUSTOM
.Ed
.Pp
If an
.Vt EVP_PKEY_METHOD
is set with the
.Sy EVP_PKEY_FLAG_AUTOARGLEN
flag, the maximum size of the output buffer will be automatically
calculated or checked in corresponding EVP methods by the EVP framework.
Thus the implementations of these methods don't need to care about
handling the case of returning output buffer size by themselves.
For details on the output buffer size, refer to
.Xr EVP_PKEY_sign 3 .
.Pp
The
.Sy EVP_PKEY_FLAG_SIGCTX_CUSTOM
is used to indicate the
.Xr signctx 3
method of an
.Vt EVP_PKEY_METHOD
is always called by the EVP framework while doing a digest signing
operation by calling
.Xr EVP_DigestSignFinal 3 .
.Pp
.Fn EVP_PKEY_meth_free
frees an existing
.Vt EVP_PKEY_METHOD
pointed by
.Fa pmeth .
If the argument is NULL, nothing is done.
.Pp
.Fn EVP_PKEY_meth_copy
copies an
.Vt EVP_PKEY_METHOD
object from
.Fa src
to
.Fa dst .
.Pp
.Fn EVP_PKEY_meth_find
finds an
.Vt EVP_PKEY_METHOD
object with the
.Fa id .
This function first searches through the user-defined method objects and
then the built-in objects.
.Pp
.Fn EVP_PKEY_meth_add0
adds
.Fa pmeth
to the user defined stack of methods.
.Pp
.Fn EVP_PKEY_meth_remove
removes an
.Vt EVP_PKEY_METHOD
object added by
.Fn EVP_PKEY_meth_add0 .
.Pp
The EVP_PKEY_meth_set functions set the corresponding fields of
.Vt EVP_PKEY_METHOD
structure with the arguments passed.
.Pp
The EVP_PKEY_meth_get functions get the corresponding fields of
.Vt EVP_PKEY_METHOD
structure to the arguments provided.
.Sh RETURN VALUES
.Fn EVP_PKEY_meth_new
returns a pointer to a new
.Vt EVP_PKEY_METHOD
object or returns NULL on error.
.Pp
.Fn EVP_PKEY_meth_free
and
.Fn EVP_PKEY_meth_copy
do not return values.
.Pp
.Fn EVP_PKEY_meth_find
returns a pointer to the found
.Vt EVP_PKEY_METHOD
object or returns NULL if not found.
.Pp
.Fn EVP_PKEY_meth_add0
returns 1 if method is added successfully or 0 if an error occurred.
.Pp
.Fn EVP_PKEY_meth_remove
returns 1 if method is removed successfully or 0 if an error occurred.
.Pp
All EVP_PKEY_meth_set and EVP_PKEY_meth_get functions have no return
values.
For the 'get' functions, function pointers are returned by arguments.
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
The signature of the
.Em copy
functional argument of
.Fn EVP_PKEY_meth_set_copy
has changed in OpenSSL 3.0 so its
.Fa src
parameter is now constified.
.Sh COPYRIGHT
Copyright 2017-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
