.Dd 2025-09-30
.Dt EVP_PKEY2PKCS8 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY2PKCS8 ,
.Nm EVP_PKCS82PKEY_ex ,
.Nm EVP_PKCS82PKEY
.Nd Convert a private key to/from PKCS8
.Sh SYNOPSIS
.In openssl/x509.h
.Ft PKCS8_PRIV_KEY_INFO *
.Fo EVP_PKEY2PKCS8
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft EVP_PKEY *
.Fo EVP_PKCS82PKEY
.Fa "const PKCS8_PRIV_KEY_INFO *p8"
.Fc
.Ft EVP_PKEY *
.Fo EVP_PKCS82PKEY_ex
.Fa "const PKCS8_PRIV_KEY_INFO *p8"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Sh DESCRIPTION
.Fn EVP_PKEY2PKCS8
converts a private key
.Fa pkey
into a returned PKCS8 object.
.Pp
.Fn EVP_PKCS82PKEY_ex
converts a PKCS8 object
.Fa p8
into a returned private key.
It uses
.Fa libctx
and
.Fa propq
when fetching algorithms.
.Pp
.Fn EVP_PKCS82PKEY
is similar to
.Fn EVP_PKCS82PKEY_ex
but uses default values of NULL for the
.Fa libctx
and
.Fa propq .
.Sh RETURN VALUES
.Fn EVP_PKEY2PKCS8
returns a PKCS8 object on success.
.Fn EVP_PKCS82PKEY
and
.Fn EVP_PKCS82PKEY_ex
return a private key on success.
.Pp
All functions return NULL if the operation fails.
.Sh SEE ALSO
.Xr PKCS8_pkey_add1_attr 3 ,
.Sh COPYRIGHT
Copyright 2020-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
