.Dd 2025-09-30
.Dt EVP_PKEY_METH_GET_COUNT 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_meth_get_count ,
.Nm EVP_PKEY_meth_get0 ,
.Nm EVP_PKEY_meth_get0_info
.Nd enumerate public key methods
.Sh SYNOPSIS
.In openssl/evp.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft size_t
.Fo EVP_PKEY_meth_get_count
.Fa void
.Fc
.Ft const EVP_PKEY_METHOD *
.Fo EVP_PKEY_meth_get0
.Fa "size_t idx"
.Fc
.Ft void
.Fo EVP_PKEY_meth_get0_info
.Fa "int *ppkey_id"
.Fa "int *pflags"
.Fa "const EVP_PKEY_METHOD *meth"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the OSSL_PROVIDER APIs.
.Pp
.Xr EVP_PKEY_meth_count 3
returns a count of the number of public key methods available: it
includes standard methods and any methods added by the application.
.Pp
.Fn EVP_PKEY_meth_get0
returns the public key method
.Fa idx .
The value of
.Fa idx
must be between zero and
.Fn EVP_PKEY_meth_get_count
- 1.
.Pp
.Fn EVP_PKEY_meth_get0_info
returns the public key ID (a NID) and any flags associated with the
public key method
.Sy *meth .
.Sh RETURN VALUES
.Xr EVP_PKEY_meth_count 3
returns the number of available public key methods.
.Pp
.Fn EVP_PKEY_meth_get0
return a public key method or
.Dv NULL
if
.Fa idx
is out of range.
.Pp
.Fn EVP_PKEY_meth_get0_info
does not return a value.
.Sh SEE ALSO
.Xr EVP_PKEY_new 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2002-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
