.Dd 2025-09-30
.Dt EVP_VERIFYINIT 3ossl
.Os
.Sh NAME
.Nm EVP_VerifyInit_ex ,
.Nm EVP_VerifyInit ,
.Nm EVP_VerifyUpdate ,
.Nm EVP_VerifyFinal_ex ,
.Nm EVP_VerifyFinal
.Nd EVP signature verification functions
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_VerifyInit_ex
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fa "ENGINE *impl"
.Fc
.Ft int
.Fo EVP_VerifyUpdate
.Fa "EVP_MD_CTX *ctx"
.Fa "const void *d"
.Fa "unsigned int cnt"
.Fc
.Ft int
.Fo EVP_VerifyFinal_ex
.Fa "EVP_MD_CTX *ctx"
.Fa "const unsigned char *sigbuf"
.Fa "unsigned int siglen"
.Fa "EVP_PKEY *pkey"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo EVP_VerifyFinal
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *sigbuf"
.Fa "unsigned int siglen"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft int
.Fo EVP_VerifyInit
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fc
.Sh DESCRIPTION
The EVP signature verification routines are a high-level interface to
digital signatures.
.Pp
.Fn EVP_VerifyInit_ex
sets up verification context
.Fa ctx
to use digest
.Fa type
from ENGINE
.Fa impl .
.Fa ctx
must be created by calling
.Xr EVP_MD_CTX_new 3
before calling this function.
.Pp
.Fn EVP_VerifyUpdate
hashes
.Fa cnt
bytes of data at
.Fa d
into the verification context
.Fa ctx .
This function can be called several times on the same
.Fa ctx
to include additional data.
.Pp
.Fn EVP_VerifyFinal_ex
verifies the data in
.Fa ctx
using the public key
.Fa pkey
and
.Fa siglen
bytes in
.Fa sigbuf .
The library context
.Fa libctx
and property query
.Fa propq
are used when creating a context to use with the key
.Fa pkey .
.Pp
.Fn EVP_VerifyFinal
is similar to
.Fn EVP_VerifyFinal_ex
but uses default values of NULL for the library context
.Fa libctx
and the property query
.Fa propq .
.Pp
.Fn EVP_VerifyInit
initializes verification context
.Fa ctx
to use the default implementation of digest
.Fa type .
.Sh RETURN VALUES
.Fn EVP_VerifyInit_ex
and
.Fn EVP_VerifyUpdate
return 1 for success and 0 for failure.
.Pp
.Fn EVP_VerifyFinal_ex
and
.Fn EVP_VerifyFinal
return 1 for a correct signature, 0 for failure and a negative value if
some other error occurred.
.Pp
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh NOTES
The
.Sy EVP
interface to digital signatures should almost always be used in
preference to the low-level interfaces.
This is because the code then becomes transparent to the algorithm used
and much more flexible.
.Pp
The call to
.Fn EVP_VerifyFinal
internally finalizes a copy of the digest context.
This means that calls to
.Fn EVP_VerifyUpdate
and
.Fn EVP_VerifyFinal
can be called later to digest and verify additional data.
Applications may disable this behavior by setting the
EVP_MD_CTX_FLAG_FINALISE context flag via
.Xr EVP_MD_CTX_set_flags 3 .
.Pp
Since only a copy of the digest context is ever finalized the context
must be cleaned up after use by calling
.Xr EVP_MD_CTX_free 3
or a memory leak will occur.
.Pp
Note that not all providers support continuation, in case the selected
provider does not allow to duplicate contexts
.Fn EVP_VerifyFinal
will finalize the digest context and attempting to process additional
data via
.Fn EVP_VerifyUpdate
will result in an error.
.Sh BUGS
Older versions of this documentation wrongly stated that calls to
.Fn EVP_VerifyUpdate
could not be made after calling
.Fn EVP_VerifyFinal .
.Pp
Since the public key is passed in the call to
.Xr EVP_SignFinal 3
any error relating to the private key (for example an unsuitable key and
digest combination) will not be indicated until after potentially large
amounts of data have been passed through
.Xr EVP_SignUpdate 3 .
.Pp
It is not possible to change the signing parameters using these
function.
.Pp
The previous two bugs are fixed in the newer
.Xr EVP_DigestVerify* 3
function.
.Sh SEE ALSO
.Xr evp 7 ,
.Xr EVP_SignInit 3 ,
.Xr EVP_DigestInit 3 ,
.Xr evp 7 ,
.Xr HMAC 3 ,
.Xr MD2 3 ,
.Xr MD5 3 ,
.Xr MDC2 3 ,
.Xr RIPEMD160 3 ,
.Xr SHA1 3 ,
.Xr openssl-dgst 1
.Sh HISTORY
The function
.Fn EVP_VerifyFinal_ex
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
