.Dd 2025-09-30
.Dt EVP_DES_CBC 3ossl
.Os
.Sh NAME
.Nm EVP_des_cbc ,
.Nm EVP_des_cfb ,
.Nm EVP_des_cfb1 ,
.Nm EVP_des_cfb8 ,
.Nm EVP_des_cfb64 ,
.Nm EVP_des_ecb ,
.Nm EVP_des_ofb ,
.Nm EVP_des_ede ,
.Nm EVP_des_ede_cbc ,
.Nm EVP_des_ede_cfb ,
.Nm EVP_des_ede_cfb64 ,
.Nm EVP_des_ede_ecb ,
.Nm EVP_des_ede_ofb ,
.Nm EVP_des_ede3 ,
.Nm EVP_des_ede3_cbc ,
.Nm EVP_des_ede3_cfb ,
.Nm EVP_des_ede3_cfb1 ,
.Nm EVP_des_ede3_cfb8 ,
.Nm EVP_des_ede3_cfb64 ,
.Nm EVP_des_ede3_ecb ,
.Nm EVP_des_ede3_ofb ,
.Nm EVP_des_ede3_wrap
.Nd EVP DES cipher
.Sh SYNOPSIS
.In openssl/evp.h
.Ft const EVP_CIPHER *
.Fo EVP_ciphername
.Fa void
.Fc
.Em EVP_ciphername
is used a placeholder for any of the described cipher functions, such as
.Em EVP_des_cbc .
.Sh DESCRIPTION
The DES encryption algorithm for EVP.
.Bl -tag -width Ds
.It EVP_des_cbc(), EVP_des_ecb(), EVP_des_cfb(), EVP_des_cfb1(), EVP_des_cfb8(), EVP_des_cfb64(), EVP_des_ofb()
DES in CBC, ECB, CFB with 64-bit shift, CFB with 1-bit shift, CFB with
8-bit shift and OFB modes.
.Pp
None of these algorithms are provided by the OpenSSL default provider.
To use them it is necessary to load either the OpenSSL legacy provider
or another implementation.
.It EVP_des_ede(), EVP_des_ede_cbc(), EVP_des_ede_cfb(), EVP_des_ede_cfb64(), EVP_des_ede_ecb(), EVP_des_ede_ofb()
Two key triple DES in ECB, CBC, CFB with 64-bit shift and OFB modes.
.It EVP_des_ede3(), EVP_des_ede3_cbc(), EVP_des_ede3_cfb(), EVP_des_ede3_cfb1(), EVP_des_ede3_cfb8(), EVP_des_ede3_cfb64(), EVP_des_ede3_ecb(), EVP_des_ede3_ofb()
Three-key triple DES in ECB, CBC, CFB with 64-bit shift, CFB with 1-bit
shift, CFB with 8-bit shift and OFB modes.
.It EVP_des_ede3_wrap()
Triple-DES key wrap according to RFC 3217 Section 3.
.El
.Sh NOTES
Developers should be aware of the negative performance implications of
calling these functions multiple times and should consider using
.Xr EVP_CIPHER_fetch 3
with
.Xr EVP_CIPHER-DES 7
instead.
See
.Xr crypto 7
for further information.
.Sh RETURN VALUES
These functions return an
.Sy EVP_CIPHER
structure that contains the implementation of the symmetric cipher.
See
.Xr EVP_CIPHER_meth_new 3
for details of the
.Sy EVP_CIPHER
structure.
.Sh SEE ALSO
.Xr evp 7 ,
.Xr EVP_EncryptInit 3 ,
.Xr EVP_CIPHER_meth_new 3
.Sh COPYRIGHT
Copyright 2017-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
