.Dd 2025-09-30
.Dt EVP_CAMELLIA_128_ECB 3ossl
.Os
.Sh NAME
.Nm EVP_camellia_128_cbc ,
.Nm EVP_camellia_192_cbc ,
.Nm EVP_camellia_256_cbc ,
.Nm EVP_camellia_128_cfb ,
.Nm EVP_camellia_192_cfb ,
.Nm EVP_camellia_256_cfb ,
.Nm EVP_camellia_128_cfb1 ,
.Nm EVP_camellia_192_cfb1 ,
.Nm EVP_camellia_256_cfb1 ,
.Nm EVP_camellia_128_cfb8 ,
.Nm EVP_camellia_192_cfb8 ,
.Nm EVP_camellia_256_cfb8 ,
.Nm EVP_camellia_128_cfb128 ,
.Nm EVP_camellia_192_cfb128 ,
.Nm EVP_camellia_256_cfb128 ,
.Nm EVP_camellia_128_ctr ,
.Nm EVP_camellia_192_ctr ,
.Nm EVP_camellia_256_ctr ,
.Nm EVP_camellia_128_ecb ,
.Nm EVP_camellia_192_ecb ,
.Nm EVP_camellia_256_ecb ,
.Nm EVP_camellia_128_ofb ,
.Nm EVP_camellia_192_ofb ,
.Nm EVP_camellia_256_ofb
.Nd EVP Camellia cipher
.Sh SYNOPSIS
.In openssl/evp.h
.Ft const EVP_CIPHER *
.Fo EVP_ciphername
.Fa void
.Fc
.Em EVP_ciphername
is used a placeholder for any of the described cipher functions, such as
.Em EVP_camellia_128_cbc .
.Sh DESCRIPTION
The Camellia encryption algorithm for EVP.
.Bl -tag -width Ds
.It EVP_camellia_128_cbc(), EVP_camellia_192_cbc(), EVP_camellia_256_cbc(), EVP_camellia_128_cfb(), EVP_camellia_192_cfb(), EVP_camellia_256_cfb(), EVP_camellia_128_cfb1(), EVP_camellia_192_cfb1(), EVP_camellia_256_cfb1(), EVP_camellia_128_cfb8(), EVP_camellia_192_cfb8(), EVP_camellia_256_cfb8(), EVP_camellia_128_cfb128(), EVP_camellia_192_cfb128(), EVP_camellia_256_cfb128(), EVP_camellia_128_ctr(), EVP_camellia_192_ctr(), EVP_camellia_256_ctr(), EVP_camellia_128_ecb(), EVP_camellia_192_ecb(), EVP_camellia_256_ecb(), EVP_camellia_128_ofb(), EVP_camellia_192_ofb(), EVP_camellia_256_ofb()
Camellia for 128, 192 and 256 bit keys in the following modes: CBC, CFB
with 128-bit shift, CFB with 1-bit shift, CFB with 8-bit shift, CTR, ECB
and OFB.
.El
.Sh NOTES
Developers should be aware of the negative performance implications of
calling these functions multiple times and should consider using
.Xr EVP_CIPHER_fetch 3
with
.Xr EVP_CIPHER-CAMELLIA 7
instead.
See
.Xr crypto 7
for further information.
.Sh RETURN VALUES
These functions return an
.Sy EVP_CIPHER
structure that contains the implementation of the symmetric cipher.
See
.Xr EVP_CIPHER_meth_new 3
for details of the
.Sy EVP_CIPHER
structure.
.Sh SEE ALSO
.Xr evp 7 ,
.Xr EVP_EncryptInit 3 ,
.Xr EVP_CIPHER_meth_new 3
.Sh COPYRIGHT
Copyright 2017-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
