.Dd 2025-09-30
.Dt EVP_PKEY_PRINT_PRIVATE 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_print_public ,
.Nm EVP_PKEY_print_private ,
.Nm EVP_PKEY_print_params ,
.Nm EVP_PKEY_print_public_fp ,
.Nm EVP_PKEY_print_private_fp ,
.Nm EVP_PKEY_print_params_fp
.Nd public key algorithm printing routines
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_print_public
.Fa "BIO *out"
.Fa "const EVP_PKEY *pkey"
.Fa "int indent"
.Fa "ASN1_PCTX *pctx"
.Fc
.Ft int
.Fo EVP_PKEY_print_public_fp
.Fa "FILE *fp"
.Fa "const EVP_PKEY *pkey"
.Fa "int indent"
.Fa "ASN1_PCTX *pctx"
.Fc
.Ft int
.Fo EVP_PKEY_print_private
.Fa "BIO *out"
.Fa "const EVP_PKEY *pkey"
.Fa "int indent"
.Fa "ASN1_PCTX *pctx"
.Fc
.Ft int
.Fo EVP_PKEY_print_private_fp
.Fa "FILE *fp"
.Fa "const EVP_PKEY *pkey"
.Fa "int indent"
.Fa "ASN1_PCTX *pctx"
.Fc
.Ft int
.Fo EVP_PKEY_print_params
.Fa "BIO *out"
.Fa "const EVP_PKEY *pkey"
.Fa "int indent"
.Fa "ASN1_PCTX *pctx"
.Fc
.Ft int
.Fo EVP_PKEY_print_params_fp
.Fa "FILE *fp"
.Fa "const EVP_PKEY *pkey"
.Fa "int indent"
.Fa "ASN1_PCTX *pctx"
.Fc
.Sh DESCRIPTION
The functions
.Fn EVP_PKEY_print_public ,
.Fn EVP_PKEY_print_private
and
.Fn EVP_PKEY_print_params
print out the public, private or parameter components of key
.Fa pkey
respectively.
The key is sent to
.Vt BIO
.Fa out
in human readable form.
The parameter
.Fa indent
indicates how far the printout should be indented.
.Pp
The
.Fa pctx
parameter allows the print output to be finely tuned by using ASN1
printing options.
If
.Fa pctx
is set to NULL then default values will be used.
.Pp
The functions
.Fn EVP_PKEY_print_public_fp ,
.Fn EVP_PKEY_print_private_fp
and
.Fn EVP_PKEY_print_params_fp
do the same as the
.Vt BIO
based functions but use
.Vt FILE
.Fa fp
instead.
.Sh NOTES
Currently no public key algorithms include any options in the
.Fa pctx
parameter.
.Pp
If the key does not include all the components indicated by the function
then only those contained in the key will be printed.
For example passing a public key to
.Fn EVP_PKEY_print_private
will only print the public components.
.Sh RETURN VALUES
These functions all return 1 for success and 0 or a negative value for
failure.
In particular a return value of -2 indicates the operation is not
supported by the public key algorithm.
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_keygen 3
.Sh HISTORY
The functions
.Fn EVP_PKEY_print_public ,
.Fn EVP_PKEY_print_private ,
and
.Fn EVP_PKEY_print_params
were added in OpenSSL 1.0.0.
.Pp
The functions
.Fn EVP_PKEY_print_public_fp ,
.Fn EVP_PKEY_print_private_fp ,
and
.Fn EVP_PKEY_print_params_fp
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2006-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
