.Dd 2025-09-30
.Dt EVP_BLAKE2B512 3ossl
.Os
.Sh NAME
.Nm EVP_blake2b512 ,
.Nm EVP_blake2s256
.Nd BLAKE2 For EVP
.Sh SYNOPSIS
.In openssl/evp.h
.Ft const EVP_MD *
.Fo EVP_blake2b512
.Fa void
.Fc
.Ft const EVP_MD *
.Fo EVP_blake2s256
.Fa void
.Fc
.Sh DESCRIPTION
BLAKE2 is an improved version of BLAKE, which was submitted to the NIST
SHA-3 algorithm competition.
The BLAKE2s and BLAKE2b algorithms are described in RFC 7693.
.Bl -tag -width Ds
.It EVP_blake2s256()
The BLAKE2s algorithm that produces a 256-bit output from a given input.
.It EVP_blake2b512()
The BLAKE2b algorithm that produces a 512-bit output from a given input.
.El
.Sh NOTES
Developers should be aware of the negative performance implications of
calling these functions multiple times and should consider using
.Xr EVP_MD_fetch 3
with
.Xr EVP_MD-BLAKE2 7
instead.
See
.Xr crypto 7
for further information.
.Pp
Both algorithms support a variable-length digest, but this is only
available through
.Xr EVP_MD-BLAKE2 7 .
.Sh RETURN VALUES
These functions return a
.Sy EVP_MD
structure that contains the implementation of the message digest.
See
.Xr EVP_MD_meth_new 3
for details of the
.Sy EVP_MD
structure.
.Sh CONFORMING TO
RFC 7693.
.Sh SEE ALSO
.Xr evp 7 ,
.Xr EVP_DigestInit 3
.Sh COPYRIGHT
Copyright 2017-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
