.Dd 2025-09-30
.Dt EVP_ENCODEINIT 3ossl
.Os
.Sh NAME
.Nm EVP_ENCODE_CTX_new ,
.Nm EVP_ENCODE_CTX_free ,
.Nm EVP_ENCODE_CTX_copy ,
.Nm EVP_ENCODE_CTX_num ,
.Nm EVP_EncodeInit ,
.Nm EVP_EncodeUpdate ,
.Nm EVP_EncodeFinal ,
.Nm EVP_EncodeBlock ,
.Nm EVP_DecodeInit ,
.Nm EVP_DecodeUpdate ,
.Nm EVP_DecodeFinal ,
.Nm EVP_DecodeBlock
.Nd EVP base64 encode/decode routines
.Sh SYNOPSIS
.In openssl/evp.h
.Ft EVP_ENCODE_CTX *
.Fo EVP_ENCODE_CTX_new
.Fa void
.Fc
.Ft void
.Fo EVP_ENCODE_CTX_free
.Fa "EVP_ENCODE_CTX *ctx"
.Fc
.Ft int
.Fo EVP_ENCODE_CTX_copy
.Fa "EVP_ENCODE_CTX *dctx"
.Fa "EVP_ENCODE_CTX *sctx"
.Fc
.Ft int
.Fo EVP_ENCODE_CTX_num
.Fa "EVP_ENCODE_CTX *ctx"
.Fc
.Ft void
.Fo EVP_EncodeInit
.Fa "EVP_ENCODE_CTX *ctx"
.Fc
.Ft int
.Fo EVP_EncodeUpdate
.Fa "EVP_ENCODE_CTX *ctx"
.Fa "unsigned char *out"
.Fa "int *outl"
.Fa "const unsigned char *in"
.Fa "int inl"
.Fc
.Ft void
.Fo EVP_EncodeFinal
.Fa "EVP_ENCODE_CTX *ctx"
.Fa "unsigned char *out"
.Fa "int *outl"
.Fc
.Ft int
.Fo EVP_EncodeBlock
.Fa "unsigned char *t"
.Fa "const unsigned char *f"
.Fa "int n"
.Fc
.Ft void
.Fo EVP_DecodeInit
.Fa "EVP_ENCODE_CTX *ctx"
.Fc
.Ft int
.Fo EVP_DecodeUpdate
.Fa "EVP_ENCODE_CTX *ctx"
.Fa "unsigned char *out"
.Fa "int *outl"
.Fa "const unsigned char *in"
.Fa "int inl"
.Fc
.Ft int
.Fo EVP_DecodeFinal
.Fa "EVP_ENCODE_CTX *ctx"
.Fa "unsigned char *out"
.Fa "int *outl"
.Fc
.Ft int
.Fo EVP_DecodeBlock
.Fa "unsigned char *t"
.Fa "const unsigned char *f"
.Fa "int n"
.Fc
.Sh DESCRIPTION
The EVP encode routines provide a high-level interface to base64
encoding and decoding.
Base64 encoding converts binary data into a printable form that uses the
characters A-Z, a-z, 0-9, "+" and "/" to represent the data.
For every 3 bytes of binary data provided 4 bytes of base64 encoded data
will be produced plus some occasional newlines (see below).
If the input data length is not a multiple of 3 then the output data
will be padded at the end using the "=" character.
.Pp
.Fn EVP_ENCODE_CTX_new
allocates, initializes and returns a context to be used for the
encode/decode functions.
.Pp
.Fn EVP_ENCODE_CTX_free
cleans up an encode/decode context
.Fa ctx
and frees up the space allocated to it.
If the argument is NULL, nothing is done.
.Pp
Encoding of binary data is performed in blocks of 48 input bytes (or
less for the final block).
For each 48 byte input block encoded 64 bytes of base64 data is output
plus an additional newline character (i.e.
65 bytes in total).
The final block (which may be less than 48 bytes) will output 4 bytes
for every 3 bytes of input.
If the data length is not divisible by 3 then a full 4 bytes is still
output for the final 1 or 2 bytes of input.
Similarly a newline character will also be output.
.Pp
.Fn EVP_EncodeInit
initialises
.Fa ctx
for the start of a new encoding operation.
.Pp
.Fn EVP_EncodeUpdate
encode
.Fa inl
bytes of data found in the buffer pointed to by
.Fa in .
The output is stored in the buffer
.Fa out
and the number of bytes output is stored in
.Sy *outl .
It is the caller's responsibility to ensure that the buffer at
.Fa out
is sufficiently large to accommodate the output data.
Only full blocks of data (48 bytes) will be immediately processed and
output by this function.
Any remainder is held in the
.Fa ctx
object and will be processed by a subsequent call to
.Fn EVP_EncodeUpdate
or
.Fn EVP_EncodeFinal .
To calculate the required size of the output buffer add together the
value of
.Fa inl
with the amount of unprocessed data held in
.Fa ctx
and divide the result by 48 (ignore any remainder).
This gives the number of blocks of data that will be processed.
Ensure the output buffer contains 65 bytes of storage for each block,
plus an additional byte for a NUL terminator.
.Fn EVP_EncodeUpdate
may be called repeatedly to process large amounts of input data.
In the event of an error
.Fn EVP_EncodeUpdate
will set
.Sy *outl
to 0 and return 0. On success 1 will be returned.
.Pp
.Fn EVP_EncodeFinal
must be called at the end of an encoding operation.
It will process any partial block of data remaining in the
.Fa ctx
object.
The output data will be stored in
.Fa out
and the length of the data written will be stored in
.Sy *outl .
It is the caller's responsibility to ensure that
.Fa out
is sufficiently large to accommodate the output data which will never be
more than 65 bytes plus an additional NUL terminator (i.e.
66 bytes in total).
.Pp
.Fn EVP_ENCODE_CTX_copy
can be used to copy a context
.Fa sctx
to a context
.Fa dctx .
.Fa dctx
must be initialized before calling this function.
.Pp
.Fn EVP_ENCODE_CTX_num
will return the number of as yet unprocessed bytes still to be encoded
or decoded that are pending in the
.Fa ctx
object.
.Pp
.Fn EVP_EncodeBlock
encodes a full block of input data in
.Fa f
and of length
.Fa n
and stores it in
.Fa t .
For every 3 bytes of input provided 4 bytes of output data will be
produced.
If
.Fa n
is not divisible by 3 then the block is encoded as a final block of data
and the output is padded such that it is always divisible by 4.
Additionally a NUL terminator character will be added.
For example if 16 bytes of input data is provided then 24 bytes of
encoded data is created plus 1 byte for a NUL terminator (i.e.
25 bytes in total).
The length of the data generated
.Em without
the NUL terminator is returned from the function.
.Pp
.Fn EVP_DecodeInit
initialises
.Fa ctx
for the start of a new decoding operation.
.Pp
.Fn EVP_DecodeUpdate
decodes
.Fa inl
characters of data found in the buffer pointed to by
.Fa in .
The output is stored in the buffer
.Fa out
and the number of bytes output is stored in
.Sy *outl .
It is the caller's responsibility to ensure that the buffer at
.Fa out
is sufficiently large to accommodate the output data.
This function will attempt to decode as much data as possible in chunks
of up to 80 base64 characters at a time.
Residual input shorter than the internal chunk size will be buffered in
.Fa ctx
if its length is not a multiple of 4 (including any padding), to be
processed in future calls to
.Fn EVP_DecodeUpdate
or
.Fn EVP_DecodeFinal .
If the final chunk length is a multiple of 4, it is decoded immediately
and not buffered.
.Pp
Any whitespace, newline or carriage return characters are ignored.
For compatibility with
.Sy PEM ,
the
.Sy -
(hyphen) character is treated as a soft end-of-input, subsequent bytes
are not buffered, and the return value will be 0 to indicate that the
end of the base64 input has been detected.
The soft end-of-input, if present, MUST occur after a multiple of 4
valid base64 input bytes.
The soft end-of-input condition is not remembered in
.Fa ctx ,
it is up to the caller to avoid further calls to
.Fn EVP_DecodeUpdate
after a 0 or negative (error) return.
.Pp
If any invalid base64 characters are encountered or if the base64
padding character
.Pf ( Sy = )
is encountered in the middle of the data then
.Fn EVP_DecodeUpdate
returns -1 to indicate an error.
A return value of 0 or 1 indicates successful processing of the data.
A return value of 0 additionally indicates that the last 4 bytes
processed ended with base64 padding
.Pf ( Sy = Ns ),
or that the next 4 byte group starts with the soft end-of-input
.Pf ( Sy - )
character, and therefore no more input data is expected to be processed.
.Pp
For every 4 valid base64 bytes processed (ignoring whitespace, carriage
returns and line feeds), 3 bytes of binary output data will be produced
(except at the end of data terminated with one or two padding
characters).
.Pp
.Fn EVP_DecodeFinal
should be called at the end of a decoding operation, but it will never
decode additional data.
If there is no residual data it will return 1 to indicate success.
If there is residual data, its length is not a multiple of 4, i.e.
it was not properly padded, -1 is is returned in that case to indicate
an error.
.Pp
.Fn EVP_DecodeBlock
will decode the block of
.Fa n
characters of base64 data contained in
.Fa f
and store the result in
.Fa t .
Any leading whitespace will be trimmed as will any trailing whitespace,
newlines, carriage returns or EOF characters.
Internal whitespace MUST NOT be present.
After trimming the data in
.Fa f
MUST consist entirely of valid base64 characters or padding (only at the
tail of the input) and its length MUST be divisible by 4. For every 4
input bytes exactly 3 output bytes will be produced.
Padding bytes
.Pf ( Sy = )
(even if internal) are decoded to 6 zero bits, the caller is responsible
for taking trailing padding into account, by ignoring as many bytes at
the tail of the returned output.
.Fn EVP_DecodeBlock
will return the length of the data decoded or -1 on error.
.Sh RETURN VALUES
.Fn EVP_ENCODE_CTX_new
returns a pointer to the newly allocated EVP_ENCODE_CTX object or NULL
on error.
.Pp
.Fn EVP_ENCODE_CTX_num
returns the number of bytes pending encoding or decoding in
.Fa ctx .
.Pp
.Fn EVP_EncodeUpdate
returns 0 on error or 1 on success.
.Pp
.Fn EVP_EncodeBlock
returns the number of bytes encoded excluding the NUL terminator.
.Pp
.Fn EVP_DecodeUpdate
returns -1 on error and 0 or 1 on success.
If 0 is returned then no more non-padding base64 characters are
expected.
.Pp
.Fn EVP_DecodeFinal
returns -1 on error or 1 on success.
.Pp
.Fn EVP_DecodeBlock
returns the length of the data decoded or -1 on error.
.Sh SEE ALSO
.Xr evp 7
.Sh HISTORY
The
.Fn EVP_DecodeUpdate
function was fixed in OpenSSL 3.5, so now it produces the number of
bytes specified in
.Sy outl*
and does not decode padding bytes
.Pf ( Sy = )
to 6 zero bits.
.Sh COPYRIGHT
Copyright 2016-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
