.Dd 2025-09-30
.Dt EVP_KEM_FREE 3ossl
.Os
.Sh NAME
.Nm EVP_KEM_fetch ,
.Nm EVP_KEM_free ,
.Nm EVP_KEM_up_ref ,
.Nm EVP_KEM_get0_name ,
.Nm EVP_KEM_is_a ,
.Nm EVP_KEM_get0_provider ,
.Nm EVP_KEM_do_all_provided ,
.Nm EVP_KEM_names_do_all ,
.Nm EVP_KEM_get0_description ,
.Nm EVP_KEM_gettable_ctx_params ,
.Nm EVP_KEM_settable_ctx_params
.Nd Functions to manage EVP_KEM algorithm objects
.Sh SYNOPSIS
.In openssl/evp.h
.Ft EVP_KEM *
.Fo EVP_KEM_fetch
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *algorithm"
.Fa "const char *properties"
.Fc
.Ft void
.Fo EVP_KEM_free
.Fa "EVP_KEM *kem"
.Fc
.Ft int
.Fo EVP_KEM_up_ref
.Fa "EVP_KEM *kem"
.Fc
.Ft const char *
.Fo EVP_KEM_get0_name
.Fa "const EVP_KEM *kem"
.Fc
.Ft int
.Fo EVP_KEM_is_a
.Fa "const EVP_KEM *kem"
.Fa "const char *name"
.Fc
.Ft OSSL_PROVIDER *
.Fo EVP_KEM_get0_provider
.Fa "const EVP_KEM *kem"
.Fc
.Ft void
.Fo EVP_KEM_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*fn)(EVP_KEM *kem"
.Fa "void *arg)"
.Fa "void *arg"
.Fc
.Ft int
.Fo EVP_KEM_names_do_all
.Fa "const EVP_KEM *kem"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
.Ft const char *
.Fo EVP_KEM_get0_description
.Fa "const EVP_KEM *kem"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KEM_gettable_ctx_params
.Fa "const EVP_KEM *kem"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_KEM_settable_ctx_params
.Fa "const EVP_KEM *kem"
.Fc
.Sh DESCRIPTION
.Fn EVP_KEM_fetch
fetches the implementation for the given
.Fa algorithm
from any provider offering it, within the criteria given by the
.Fa properties
and in the scope of the given library context
.Fa ctx
(see
.Xr OSSL_LIB_CTX 3 Ns ).
The algorithm will be one offering functions for performing asymmetric
kem related tasks such as key encapsulation and decapsulation.
See
.Xr crypto 7
for further information.
.Pp
The returned value must eventually be freed with
.Fn EVP_KEM_free .
.Pp
.Fn EVP_KEM_free
decrements the reference count for the
.Vt EVP_KEM
structure.
Typically this structure will have been obtained from an earlier call to
.Fn EVP_KEM_fetch .
If the reference count drops to 0 then the structure is freed.
If the argument is NULL, nothing is done.
.Pp
.Fn EVP_KEM_up_ref
increments the reference count for an
.Vt EVP_KEM
structure.
.Pp
.Fn EVP_KEM_is_a
returns 1 if
.Fa kem
is an implementation of an algorithm that's identifiable with
.Fa name ,
otherwise 0.
.Pp
.Fn EVP_KEM_get0_provider
returns the provider that
.Fa kem
was fetched from.
.Pp
.Fn EVP_KEM_do_all_provided
traverses all EVP_KEMs implemented by all activated providers in the
given library context
.Fa libctx ,
and for each of the implementations, calls the given function
.Em fn
with the implementation method and the given
.Fa arg
as argument.
.Pp
.Fn EVP_KEM_get0_name
returns the algorithm name from the provided implementation for the
given
.Fa kem .
Note that the
.Fa kem
may have multiple synonyms associated with it.
In this case the first name from the algorithm definition is returned.
Ownership of the returned string is retained by the
.Fa kem
object and should not be freed by the caller.
.Pp
.Fn EVP_KEM_names_do_all
traverses all names for
.Fa kem ,
and calls
.Em fn
with each name and
.Fa data .
.Pp
.Fn EVP_KEM_get0_description
returns a description of the
.Fa kem ,
meant for display and human consumption.
The description is at the discretion of the
.Fa kem
implementation.
.Pp
.Fn EVP_KEM_gettable_ctx_params
and
.Fn EVP_KEM_settable_ctx_params
return a constant
.Xr OSSL_PARAM 3
array that describes the names and types of key parameters that can be
retrieved or set by a key encapsulation algorithm using
.Xr EVP_PKEY_CTX_get_params 3
and
.Xr EVP_PKEY_CTX_set_params 3 .
.Sh RETURN VALUES
.Fn EVP_KEM_fetch
returns a pointer to an
.Vt EVP_KEM
for success or
.Dv NULL
for failure.
.Pp
.Fn EVP_KEM_up_ref
returns 1 for success or 0 otherwise.
.Pp
.Fn EVP_KEM_names_do_all
returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.Pp
.Fn EVP_KEM_gettable_ctx_params
and
.Fn EVP_KEM_settable_ctx_params
return a constant
.Xr OSSL_PARAM 3
array or NULL on error.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr OSSL_PROVIDER 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
