.Dd 2025-09-30
.Dt EVP_MAC 3ossl
.Os
.Sh NAME
.Nm EVP_MAC ,
.Nm EVP_MAC_fetch ,
.Nm EVP_MAC_up_ref ,
.Nm EVP_MAC_free ,
.Nm EVP_MAC_is_a ,
.Nm EVP_MAC_get0_name ,
.Nm EVP_MAC_names_do_all ,
.Nm EVP_MAC_get0_description ,
.Nm EVP_MAC_get0_provider ,
.Nm EVP_MAC_get_params ,
.Nm EVP_MAC_gettable_params ,
.Nm EVP_MAC_CTX ,
.Nm EVP_MAC_CTX_new ,
.Nm EVP_MAC_CTX_free ,
.Nm EVP_MAC_CTX_dup ,
.Nm EVP_MAC_CTX_get0_mac ,
.Nm EVP_MAC_CTX_get_params ,
.Nm EVP_MAC_CTX_set_params ,
.Nm EVP_MAC_CTX_get_mac_size ,
.Nm EVP_MAC_CTX_get_block_size ,
.Nm EVP_Q_mac ,
.Nm EVP_MAC_init ,
.Nm EVP_MAC_init_SKEY ,
.Nm EVP_MAC_update ,
.Nm EVP_MAC_final ,
.Nm EVP_MAC_finalXOF ,
.Nm EVP_MAC_gettable_ctx_params ,
.Nm EVP_MAC_settable_ctx_params ,
.Nm EVP_MAC_CTX_gettable_params ,
.Nm EVP_MAC_CTX_settable_params ,
.Nm EVP_MAC_do_all_provided
.Nd EVP MAC routines
.Sh SYNOPSIS
.In openssl/evp.h
.Ft typedef struct evp_mac_st EVP_MAC;
 typedef struct evp_mac_ctx_st EVP_MAC_CTX;

 EVP_MAC *
.Fo EVP_MAC_fetch
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *algorithm"
.Fa "const char *properties"
.Fc
.Ft int
.Fo EVP_MAC_up_ref
.Fa "EVP_MAC *mac"
.Fc
.Ft void
.Fo EVP_MAC_free
.Fa "EVP_MAC *mac"
.Fc
.Ft int
.Fo EVP_MAC_is_a
.Fa "const EVP_MAC *mac"
.Fa "const char *name"
.Fc
.Ft const char *
.Fo EVP_MAC_get0_name
.Fa "const EVP_MAC *mac"
.Fc
.Ft int
.Fo EVP_MAC_names_do_all
.Fa "const EVP_MAC *mac"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
.Ft const char *
.Fo EVP_MAC_get0_description
.Fa "const EVP_MAC *mac"
.Fc
.Ft const OSSL_PROVIDER *
.Fo EVP_MAC_get0_provider
.Fa "const EVP_MAC *mac"
.Fc
.Ft int
.Fo EVP_MAC_get_params
.Fa "EVP_MAC *mac"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft EVP_MAC_CTX *
.Fo EVP_MAC_CTX_new
.Fa "EVP_MAC *mac"
.Fc
.Ft void
.Fo EVP_MAC_CTX_free
.Fa "EVP_MAC_CTX *ctx"
.Fc
.Ft EVP_MAC_CTX *
.Fo EVP_MAC_CTX_dup
.Fa "const EVP_MAC_CTX *src"
.Fc
.Ft EVP_MAC *
.Fo EVP_MAC_CTX_get0_mac
.Fa "EVP_MAC_CTX *ctx"
.Fc
.Ft int
.Fo EVP_MAC_CTX_get_params
.Fa "EVP_MAC_CTX *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_MAC_CTX_set_params
.Fa "EVP_MAC_CTX *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft size_t
.Fo EVP_MAC_CTX_get_mac_size
.Fa "EVP_MAC_CTX *ctx"
.Fc
.Ft size_t
.Fo EVP_MAC_CTX_get_block_size
.Fa "EVP_MAC_CTX *ctx"
.Fc
.Ft unsigned char *
.Fo EVP_Q_mac
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *name"
.Fa "const char *propq"
.Fa "const char *subalg"
.Fa "const OSSL_PARAM *params"
.Fa "const void *key"
.Fa "size_t keylen"
.Fa "const unsigned char *data"
.Fa "size_t datalen"
.Fa "unsigned char *out"
.Fa "size_t outsize"
.Fa "size_t *outlen"
.Fc
.Ft int
.Fo EVP_MAC_init
.Fa "EVP_MAC_CTX *ctx"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_MAC_init_SKEY
.Fa "EVP_MAC_CTX *ctx"
.Fa "EVP_SKEY *skey"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_MAC_update
.Fa "EVP_MAC_CTX *ctx"
.Fa "const unsigned char *data"
.Fa "size_t datalen"
.Fc
.Ft int
.Fo EVP_MAC_final
.Fa "EVP_MAC_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsize"
.Fc
.Ft int
.Fo EVP_MAC_finalXOF
.Fa "EVP_MAC_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t outsize"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MAC_gettable_params
.Fa "const EVP_MAC *mac"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MAC_gettable_ctx_params
.Fa "const EVP_MAC *mac"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MAC_settable_ctx_params
.Fa "const EVP_MAC *mac"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MAC_CTX_gettable_params
.Fa "EVP_MAC_CTX *ctx"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MAC_CTX_settable_params
.Fa "EVP_MAC_CTX *ctx"
.Fc
.Ft void
.Fo EVP_MAC_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*fn)(EVP_MAC *mac"
.Fa "void *arg)"
.Fa "void *arg"
.Fc
.Sh DESCRIPTION
These types and functions help the application to calculate MACs of
different types and with different underlying algorithms if there are
any.
.Pp
MACs are a bit complex insofar that some of them use other algorithms
for actual computation.
HMAC uses a digest, and CMAC uses a cipher.
Therefore, there are sometimes two contexts to keep track of, one for
the MAC algorithm itself and one for the underlying computation
algorithm if there is one.
.Pp
To make things less ambiguous, this manual talks about a "context" or
"MAC context", which is to denote the MAC level context, and about a
"underlying context", or "computation context", which is to denote the
context for the underlying computation algorithm if there is one.
.Ss Types
.Vt EVP_MAC
is a type that holds the implementation of a MAC.
.Pp
.Vt EVP_MAC_CTX
is a context type that holds internal MAC information as well as a
reference to a computation context, for those MACs that rely on an
underlying computation algorithm.
.Ss Algorithm implementation fetching
.Fn EVP_MAC_fetch
fetches an implementation of a MAC
.Fa algorithm ,
given a library context
.Fa libctx
and a set of
.Fa properties .
See
.Xr crypto 7
for further information.
.Pp
See
.Xr OSSL_PROVIDER-default 7
for the list of algorithms supported by the default provider.
.Pp
The returned value must eventually be freed with
.Xr EVP_MAC_free 3 .
.Pp
.Fn EVP_MAC_up_ref
increments the reference count of an already fetched MAC.
.Pp
.Fn EVP_MAC_free
frees a fetched algorithm.
NULL is a valid parameter, for which this function is a no-op.
.Ss Context manipulation functions
.Fn EVP_MAC_CTX_new
creates a new context for the MAC type
.Fa mac .
The created context can then be used with most other functions described
here.
.Pp
.Fn EVP_MAC_CTX_free
frees the contents of the context, including an underlying context if
there is one, as well as the context itself.
NULL is a valid parameter, for which this function is a no-op.
.Pp
.Fn EVP_MAC_CTX_dup
duplicates the
.Fa src
context and returns a newly allocated context.
.Pp
.Fn EVP_MAC_CTX_get0_mac
returns the
.Vt EVP_MAC
associated with the context
.Fa ctx .
.Ss Computing functions
.Fn EVP_Q_mac
computes the message authentication code of
.Fa data
with length
.Fa datalen
using the MAC algorithm
.Fa name
and the key
.Fa key
with length
.Fa keylen .
The MAC algorithm is fetched using any given
.Fa libctx
and property query string
.Fa propq .
It takes parameters
.Fa subalg
and further
.Fa params ,
both of which may be NULL if not needed.
If
.Fa out
is not NULL, it places the result in the memory pointed at by
.Fa out ,
but only if
.Fa outsize
is sufficient (otherwise no computation is made).
If
.Fa out
is NULL, it allocates and uses a buffer of suitable length, which will
be returned on success and must be freed by the caller.
In either case, also on error, it assigns the number of bytes written to
.Em *outlen
unless
.Fa outlen
is NULL.
.Pp
.Fn EVP_MAC_init
sets up the underlying context
.Fa ctx
with information given via the
.Fa key
and
.Fa params
arguments.
The MAC
.Fa key
has a length of
.Fa keylen
and the parameters in
.Fa params
are processed before setting the key.
If
.Fa key
is NULL, the key must be set via
.Fa params
either as part of this call or separately using
.Fn EVP_MAC_CTX_set_params .
Providing non-NULL
.Fa params
to this function is equivalent to calling
.Fn EVP_MAC_CTX_set_params
with those
.Fa params
for the same
.Fa ctx
beforehand.
Note: There are additional requirements for some MAC algorithms during
re-initalization (i.e.
calling
.Fn EVP_MAC_init
on an EVP_MAC after
.Fn EVP_MAC_final
has been called on the same object).
See the NOTES section below.
.Pp
.Fn EVP_MAC_init
should be called before
.Fn EVP_MAC_update
and
.Fn EVP_MAC_final .
.Pp
.Fn EVP_MAC_init_SKEY
is similar to
.Fn EVP_MAC_init
but it accepts an opaque
.Vt EVP_SKEY
object as a key.
.Pp
.Fn EVP_MAC_update
adds
.Fa datalen
bytes from
.Fa data
to the MAC input.
.Pp
.Fn EVP_MAC_final
does the final computation and stores the result in the memory pointed
at by
.Fa out
of size
.Fa outsize ,
and sets the number of bytes written in
.Em *outl
at.
If
.Fa out
is NULL or
.Fa outsize
is too small, then no computation is made.
To figure out what the output length will be and allocate space for it
dynamically, simply call with
.Fa out
being NULL and
.Fa outl
pointing at a valid location, then allocate space and make a second call
with
.Fa out
pointing at the allocated space.
.Pp
.Fn EVP_MAC_finalXOF
does the final computation for an XOF based MAC and stores the result in
the memory pointed at by
.Fa out
of size
.Fa outsize .
.Pp
.Fn EVP_MAC_get_params
retrieves details about the implementation
.Fa mac .
The set of parameters given with
.Fa params
determine exactly what parameters should be retrieved.
Note that a parameter that is unknown in the underlying context is
simply ignored.
.Pp
.Fn EVP_MAC_CTX_get_params
retrieves chosen parameters, given the context
.Fa ctx
and its underlying context.
The set of parameters given with
.Fa params
determine exactly what parameters should be retrieved.
Note that a parameter that is unknown in the underlying context is
simply ignored.
.Pp
.Fn EVP_MAC_CTX_set_params
passes chosen parameters to the underlying context, given a context
.Fa ctx .
The set of parameters given with
.Fa params
determine exactly what parameters are passed down.
If
.Fa params
are NULL, the underlying context should do nothing and return 1. Note
that a parameter that is unknown in the underlying context is simply
ignored.
Also, what happens when a needed parameter isn't passed down is defined
by the implementation.
.Pp
.Fn EVP_MAC_gettable_params
returns an
.Xr OSSL_PARAM 3
array that describes the retrievable and settable parameters.
.Fn EVP_MAC_gettable_params
returns parameters that can be used with
.Fn EVP_MAC_get_params .
.Pp
.Fn EVP_MAC_gettable_ctx_params
and
.Fn EVP_MAC_CTX_gettable_params
return constant
.Xr OSSL_PARAM 3
arrays that describe the retrievable parameters that can be used with
.Fn EVP_MAC_CTX_get_params .
.Fn EVP_MAC_gettable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_MAC_CTX_gettable_params
returns the parameters that can be retrieved in the context's current
state.
.Pp
.Fn EVP_MAC_settable_ctx_params
and
.Fn EVP_MAC_CTX_settable_params
return constant
.Xr OSSL_PARAM 3
arrays that describe the settable parameters that can be used with
.Fn EVP_MAC_CTX_set_params .
.Fn EVP_MAC_settable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_MAC_CTX_settable_params
returns the parameters that can be retrieved in the context's current
state.
.Ss Information functions
.Fn EVP_MAC_CTX_get_mac_size
returns the MAC output size for the given context.
.Pp
.Fn EVP_MAC_CTX_get_block_size
returns the MAC block size for the given context.
Not all MAC algorithms support this.
.Pp
.Fn EVP_MAC_is_a
checks if the given
.Fa mac
is an implementation of an algorithm that's identifiable with
.Fa name .
.Pp
.Fn EVP_MAC_get0_provider
returns the provider that holds the implementation of the given
.Fa mac .
.Pp
.Fn EVP_MAC_do_all_provided
traverses all MAC implemented by all activated providers in the given
library context
.Fa libctx ,
and for each of the implementations, calls the given function
.Em fn
with the implementation method and the given
.Fa arg
as argument.
.Pp
.Fn EVP_MAC_get0_name
return the name of the given MAC. For fetched MACs with multiple names,
only one of them is returned; it's recommended to use
.Fn EVP_MAC_names_do_all
instead.
.Pp
.Fn EVP_MAC_names_do_all
traverses all names for
.Fa mac ,
and calls
.Em fn
with each name and
.Fa data .
.Pp
.Fn EVP_MAC_get0_description
returns a description of the
.Fa mac ,
meant for display and human consumption.
The description is at the discretion of the mac implementation.
.Sh PARAMETERS
Parameters are identified by name as strings, and have an expected data
type and maximum size.
OpenSSL has a set of macros for parameter names it expects to see in its
own MAC implementations.
Here, we show all three, the OpenSSL macro for the parameter name, the
name in string form, and a type description.
.Pp
The standard parameter names are:
.Bl -tag -width Ds
.It \(dqkey" ( Ns Sy OSSL_MAC_PARAM_KEY Ns ) <octet string>
Its value is the MAC key as an array of bytes.
.Pp
For MACs that use an underlying computation algorithm, the algorithm
must be set first, see parameter names "algorithm" below.
.It \(dqiv" ( Ns Sy OSSL_MAC_PARAM_IV Ns ) <octet string>
Some MAC implementations (GMAC) require an IV, this parameter sets the
IV.
.It \(dqcustom" ( Ns Sy OSSL_MAC_PARAM_CUSTOM Ns ) <octet string>
Some MAC implementations (KMAC, BLAKE2) accept a Customization String,
this parameter sets the Customization String.
The default value is the empty string.
.It \(dqsalt" ( Ns Sy OSSL_MAC_PARAM_SALT Ns ) <octet string>
This option is used by BLAKE2 MAC.
.It \(dqxof" ( Ns Sy OSSL_MAC_PARAM_XOF Ns ) <integer>
It's a simple flag, the value 0 or 1 are expected.
.Pp
This option is used by KMAC.
.It \(dqdigest-noinit" ( Ns Sy OSSL_MAC_PARAM_DIGEST_NOINIT Ns ) <integer>
A simple flag to set the MAC digest to not initialise the implementation
specific data.
The value 0 or 1 is expected.
.Pp
This option is deprecated and will be removed in a future release.
The option may be set, but is ignored.
.It \(dqdigest-oneshot" ( Ns Sy OSSL_MAC_PARAM_DIGEST_ONESHOT Ns ) <integer>
A simple flag to set the MAC digest to be a oneshot operation.
The value 0 or 1 is expected.
.Pp
This option is deprecated and will be removed in a future release.
The option may be set, but is ignored.
.It \(dqproperties" ( Ns Sy OSSL_MAC_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_MAC_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqcipher" ( Ns Sy OSSL_MAC_PARAM_CIPHER Ns ) <UTF8 string>
For MAC implementations that use an underlying computation cipher or
digest, these parameters set what the algorithm should be.
.Pp
The value is always the name of the intended algorithm, or the
properties.
.Pp
Note that not all algorithms may support all digests.
HMAC does not support variable output length digests such as SHAKE128 or
SHAKE256.
.It \(dqsize" ( Ns Sy OSSL_MAC_PARAM_SIZE Ns ) <unsigned integer>
For MAC implementations that support it, set the output size that
.Fn EVP_MAC_final
should produce.
The allowed sizes vary between MAC implementations, but must never
exceed what can be given with a
.Vt size_t .
.It \(dqtls-data-size" ( Ns Sy OSSL_MAC_PARAM_TLS_DATA_SIZE Ns ) <unsigned integer>
This parameter is only supported by HMAC. If set then special handling
is activated for calculating the MAC of a received mac-then-encrypt TLS
record where variable length record padding has been used (as in the
case of CBC mode ciphersuites).
The value represents the total length of the record that is having the
MAC calculated including the received MAC and the record padding.
.Pp
When used EVP_MAC_update must be called precisely twice.
The first time with the 13 bytes of TLS "header" data, and the second
time with the entire record including the MAC itself and any padding.
The entire record length must equal the value passed in the
"tls-data-size" parameter.
The length passed in the
.Fa datalen
parameter to
.Fn EVP_MAC_update
should be equal to the length of the record after the MAC and any
padding has been removed.
.El
.Pp
All these parameters should be used before the calls to any of
.Fn EVP_MAC_init ,
.Fn EVP_MAC_update
and
.Fn EVP_MAC_final
for a full computation.
Anything else may give undefined results.
.Sh NOTES
The MAC life-cycle is described in
.Xr life_cycle-mac 7 .
In the future, the transitions described there will be enforced.
When this is done, it will not be considered a breaking change to the
API.
.Pp
The usage of the parameter names "custom", "iv" and "salt" correspond to
the names used in the standard where the algorithm was defined.
.Pp
Some MAC algorithms store internal state that cannot be extracted during
re-initalization.
For example GMAC cannot extract an
.Sy IV
from the underlying CIPHER context, and so calling
.Fn EVP_MAC_init
on an EVP_MAC object after
.Fn EVP_MAC_final
has been called cannot reset its cipher state to what it was when the
.Sy IV
was initially generated.
For such instances, an
.Sy OSSL_MAC_PARAM_IV
parameter must be passed with each call to
.Fn EVP_MAC_init .
.Sh RETURN VALUES
.Fn EVP_MAC_fetch
returns a pointer to a newly fetched
.Vt EVP_MAC ,
or NULL if allocation failed.
.Pp
.Fn EVP_MAC_up_ref
returns 1 on success, 0 on error.
.Pp
.Fn EVP_MAC_names_do_all
returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.Pp
.Fn EVP_MAC_free
returns nothing at all.
.Pp
.Fn EVP_MAC_is_a
returns 1 if the given method can be identified with the given name,
otherwise 0.
.Pp
.Fn EVP_MAC_get0_name
returns a name of the MAC, or NULL on error.
.Pp
.Fn EVP_MAC_get0_provider
returns a pointer to the provider for the MAC, or NULL on error.
.Pp
.Fn EVP_MAC_CTX_new
and
.Fn EVP_MAC_CTX_dup
return a pointer to a newly created EVP_MAC_CTX, or NULL if allocation
failed.
.Pp
.Fn EVP_MAC_CTX_free
returns nothing at all.
.Pp
.Fn EVP_MAC_CTX_get_params
and
.Fn EVP_MAC_CTX_set_params
return 1 on success, 0 on error.
.Pp
.Fn EVP_Q_mac
returns a pointer to the computed MAC value, or NULL on error.
.Pp
.Fn EVP_MAC_init ,
.Fn EVP_MAC_init_SKEY ,
.Fn EVP_MAC_update ,
.Fn EVP_MAC_final ,
and
.Fn EVP_MAC_finalXOF
return 1 on success, 0 on error.
.Pp
.Fn EVP_MAC_CTX_get_mac_size
returns the expected output size, or 0 if it isn't set.
If it isn't set, a call to
.Fn EVP_MAC_init
will set it.
.Pp
.Fn EVP_MAC_CTX_get_block_size
returns the block size, or 0 if it isn't set.
If it isn't set, a call to
.Fn EVP_MAC_init
will set it.
.Pp
.Fn EVP_MAC_do_all_provided
returns nothing at all.
.Sh EXAMPLES
.Bd -literal
  #include <stdlib.h>
  #include <stdio.h>
  #include <string.h>
  #include <stdarg.h>
  #include <unistd.h>

  #include <openssl/evp.h>
  #include <openssl/err.h>
  #include <openssl/params.h>

  int main() {
      EVP_MAC *mac = EVP_MAC_fetch(NULL, getenv("MY_MAC"), NULL);
      const char *cipher = getenv("MY_MAC_CIPHER");
      const char *digest = getenv("MY_MAC_DIGEST");
      const char *key = getenv("MY_KEY");
      EVP_MAC_CTX *ctx = NULL;

      unsigned char buf[4096];
      size_t read_l;
      size_t final_l;

      size_t i;

      OSSL_PARAM params[3];
      size_t params_n = 0;

      if (cipher != NULL)
          params[params_n++] =
              OSSL_PARAM_construct_utf8_string("cipher", (char*)cipher, 0);
      if (digest != NULL)
          params[params_n++] =
              OSSL_PARAM_construct_utf8_string("digest", (char*)digest, 0);
      params[params_n] = OSSL_PARAM_construct_end();

      if (mac == NULL
          || key == NULL
          || (ctx = EVP_MAC_CTX_new(mac)) == NULL
          || !EVP_MAC_init(ctx, (const unsigned char *)key, strlen(key),
                           params))
          goto err;

      while ( (read_l = read(STDIN_FILENO, buf, sizeof(buf))) > 0) {
          if (!EVP_MAC_update(ctx, buf, read_l))
              goto err;
      }

      if (!EVP_MAC_final(ctx, buf, &final_l, sizeof(buf)))
          goto err;

      printf("Result: ");
      for (i = 0; i < final_l; i++)
          printf("%02X", buf[i]);
      printf("\en");

      EVP_MAC_CTX_free(ctx);
      EVP_MAC_free(mac);
      exit(0);

   err:
      EVP_MAC_CTX_free(ctx);
      EVP_MAC_free(mac);
      fprintf(stderr, "Something went wrong\en");
      ERR_print_errors_fp(stderr);
      exit (1);
  }
.Ed
A run of this program, called with correct environment variables, can
look like this:
.Bd -literal
  $ MY_MAC=cmac MY_KEY=secret0123456789 MY_MAC_CIPHER=aes-128-cbc \e
    LD_LIBRARY_PATH=. ./foo < foo.c
  Result: C5C06683CD9DDEF904D754505C560A4E
.Ed
.Pp
(in this example, that program was stored in
.Pa foo.c
and compiled to
.Pa ./foo )
.Sh SEE ALSO
.Xr property 7
.Xr OSSL_PARAM 3 ,
.Xr EVP_MAC-BLAKE2 7 ,
.Xr EVP_MAC-CMAC 7 ,
.Xr EVP_MAC-GMAC 7 ,
.Xr EVP_MAC-HMAC 7 ,
.Xr EVP_MAC-KMAC 7 ,
.Xr EVP_MAC-Siphash 7 ,
.Xr EVP_MAC-Poly1305 7 ,
.Xr provider-mac 7 ,
.Xr life_cycle-mac 7
.Sh HISTORY
These functions were added in OpenSSL 3.0.
.Pp
The
.Fn EVP_MAC_init_SKEY
function was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2018-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
