.Dd 2025-09-30
.Dt EVP_SKEY 3ossl
.Os
.Sh NAME
.Nm EVP_SKEY ,
.Nm EVP_SKEY_generate ,
.Nm EVP_SKEY_import ,
.Nm EVP_SKEY_import_raw_key ,
.Nm EVP_SKEY_up_ref ,
.Nm EVP_SKEY_export ,
.Nm EVP_SKEY_get0_raw_key ,
.Nm EVP_SKEY_get0_key_id ,
.Nm EVP_SKEY_get0_skeymgmt_name ,
.Nm EVP_SKEY_get0_provider_name ,
.Nm EVP_SKEY_free ,
.Nm EVP_SKEY_is_a ,
.Nm EVP_SKEY_to_provider
.Nd opaque symmetric key allocation and handling functions
.Sh SYNOPSIS
.In openssl/evp.h
.Ft typedef evp_skey_st EVP_SKEY;

 EVP_SKEY *
.Fo EVP_SKEY_generate
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *skeymgmtname"
.Fa "const char *propquery"
.Fa "const OSSL_PARAM *params"
.Fc
.Ft EVP_SKEY *
.Fo EVP_SKEY_import
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *skeymgmtname"
.Fa "const char *propquery"
.Fa "int selection"
.Fa "const OSSL_PARAM *params"
.Fc
.Ft EVP_SKEY *
.Fo EVP_SKEY_import_raw_key
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *skeymgmtname"
.Fa "unsigned char *key"
.Fa "size_t *len"
.Fa "const char *propquery"
.Fc
.Ft int
.Fo EVP_SKEY_export
.Fa "const EVP_SKEY *skey"
.Fa "int selection"
.Fa "OSSL_CALLBACK *export_cb"
.Fa "void *export_cbarg"
.Fc
.Ft int
.Fo EVP_SKEY_get0_raw_key
.Fa "const EVP_SKEY *skey"
.Fa "const unsigned char **key"
.Fa "size_t *len"
.Fc
.Ft const char *
.Fo EVP_SKEY_get0_key_id
.Fa "const EVP_SKEY *skey"
.Fc
.Ft const char *
.Fo EVP_SKEY_get0_skeymgmt_name
.Fa "const EVP_SKEY *skey"
.Fc
.Ft const char *
.Fo EVP_SKEY_get0_provider_name
.Fa "const EVP_SKEY *skey"
.Fc
.Ft int
.Fo EVP_SKEY_up_ref
.Fa "EVP_SKEY *key"
.Fc
.Ft void
.Fo EVP_SKEY_free
.Fa "EVP_SKEY *key"
.Fc
.Ft int
.Fo EVP_SKEY_is_a
.Fa "const EVP_SKEY *skey"
.Fa "const char *name"
.Fc
.Ft EVP_SKEY *
.Fo EVP_SKEY_to_provider
.Fa "EVP_SKEY *skey"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "OSSL_PROVIDER *prov"
.Fa "const char *propquery"
.Fc
.Sh DESCRIPTION
.Vt EVP_SKEY
is a generic structure to hold symmetric keys as opaque objects.
The keys themselves are often referred to as the "internal key", and are
handled by providers using
.Xr EVP_SKEYMGMT 3 .
.Pp
Conceptually, an
.Vt EVP_SKEY
internal key may hold a symmetric key, and along with those, key
parameters if the key type requires them.
.Pp
The
.Fn EVP_SKEY_generate
functions creates a new
.Vt EVP_SKEY
object and initializes it according to the
.Fa params
argument.
.Pp
The
.Fn EVP_SKEY_import
function allocates an empty
.Vt EVP_SKEY
structure which is used by OpenSSL to store symmetric keys, assigns the
.Sy EVP_SKEYMGMT
object associated with the key, and initializes the object from the
.Fa params
argument.
.Pp
The
.Fn EVP_SKEY_import_raw_key
function is a helper that creates an
.Vt EVP_SKEY
object containing the raw byte representation of the symmetric keys.
.Pp
The
.Fn EVP_SKEY_export
function extracts values from a key
.Fa skey
using the
.Fa selection .
.Fa selection
is described below.
It uses a callback
.Fa export_cb
that gets passed the value of
.Fa export_cbarg .
See
.Xr openssl-core.h 7
for more information about the callback.
Note that the
.Xr OSSL_PARAM 3
array that is passed to the callback is not persistent after the
callback returns.
.Pp
The
.Fn EVP_SKEY_get0_raw_key
returns a pointer to a raw key bytes to the passed address and sets the
key len.
The returned address is managed by the internal key management and
shouldn't be freed explicitly.
The operation can fail when the underlying key management doesn't
support export of the secret key.
.Pp
The
.Fn EVP_SKEY_get0_key_id
returns a NUL-terminated string providing some human-readable identifier
of the key if provided by the underlying key management.
The pointer becomes invalid after freeing the EVP_SKEY object.
.Pp
The
.Fn EVP_SKEY_get0_skeymgmt_name
and
.Fn EVP_SKEY_get0_provider_name
return the names of the associated EVP_SKEYMGMT object and its provider
correspondingly.
.Pp
.Fn EVP_SKEY_up_ref
increments the reference count of
.Fa key .
.Pp
.Fn EVP_SKEY_free
decrements the reference count of
.Fa key
and, if the reference count is zero, frees it.
If
.Fa key
is NULL, nothing is done.
.Pp
.Fn EVP_SKEY_is_a
checks if the key type of
.Fa skey
is
.Fa name .
.Pp
.Fn EVP_SKEY_to_provider
simplifies the task of importing a
.Fa skey
into a different provider identified by
.Fa prov .
If
.Fa prov
is NULL, the default provider for the key type identified via
.Fa skey
is used.
.Ss Selections
The following constants can be used for
.Fa selection :
.Bl -tag -width Ds
.It Sy OSSL_SKEYMGMT_SELECT_SECRET_KEY
Only the raw key representation will be selected.
.It Sy OSSL_SKEYMGMT_SELECT_PARAMETERS
Only the key parameters will be selected.
This includes optional key parameters.
.It Sy OSSL_SKEYMGMT_SELECT_ALL
All parameters will be selected.
.El
.Sh NOTES
The
.Vt EVP_SKEY
structure is used by various OpenSSL functions which require a general
symmetric key without reference to any particular algorithm.
.Pp
The
.Fn EVP_SKEY_to_provider
function will fail and return NULL if the origin key
.Fa skey
cannot be exported from its provider.
.Sh RETURN VALUES
.Fn EVP_SKEY_generate ,
.Fn EVP_SKEY_import
and
.Fn EVP_SKEY_import_raw_key
return either the newly allocated
.Vt EVP_SKEY
structure or NULL if an error occurred.
.Pp
.Fn EVP_SKEY_get0_key_id
returns either a valid pointer or NULL.
.Pp
.Fn EVP_SKEY_up_ref
returns 1 for success and 0 on failure.
.Pp
.Fn EVP_SKEY_export
and
.Fn EVP_SKEY_get0_raw_key
return 1 for success and 0 on failure.
.Pp
.Fn EVP_SKEY_get0_skeymgmt_name
and
.Fn EVP_SKEY_get0_provider_name
return the names of the associated EVP_SKEYMGMT object and its provider
correspondigly.
.Pp
.Fn EVP_SKEY_is_a
returns 1 if
.Fa skey
has the key type
.Fa name ,
otherwise 0.
.Pp
.Fn EVP_SKEY_to_provider
returns a new
.Vt EVP_SKEY
suitable for operations with the
.Fa prov
provider or NULL in case of failure.
.Sh SEE ALSO
.Xr EVP_SKEYMGMT 3 ,
.Xr provider 7 ,
.Xr OSSL_PARAM 3
.Sh HISTORY
The
.Vt EVP_SKEY
API and functions
.Fn EVP_SKEY_export ,
.Fn EVP_SKEY_free ,
.Fn EVP_SKEY_get0_raw_key ,
.Fn EVP_SKEY_import ,
.Fn EVP_SKEY_import_raw_key ,
.Fn EVP_SKEY_up_ref ,
.Fn EVP_SKEY_generate ,
.Fn EVP_SKEY_get0_key_id ,
.Fn EVP_SKEY_get0_provider_name ,
.Fn EVP_SKEY_get0_skeymgmt_name ,
.Fn EVP_SKEY_is_a ,
.Fn EVP_SKEY_to_provider
were introduced in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
