.Dd 2025-09-30
.Dt EVP_SKEYMGMT 3ossl
.Os
.Sh NAME
.Nm EVP_SKEYMGMT ,
.Nm EVP_SKEYMGMT_fetch ,
.Nm EVP_SKEYMGMT_up_ref ,
.Nm EVP_SKEYMGMT_free ,
.Nm EVP_SKEYMGMT_get0_provider ,
.Nm EVP_SKEYMGMT_is_a ,
.Nm EVP_SKEYMGMT_get0_description ,
.Nm EVP_SKEYMGMT_get0_name ,
.Nm EVP_SKEYMGMT_do_all_provided ,
.Nm EVP_SKEYMGMT_names_do_all ,
.Nm EVP_SKEYMGMT_get0_gen_settable_params ,
.Nm EVP_SKEYMGMT_get0_imp_settable_params
.Nd EVP key management routines for opaque symmetric keys
.Sh SYNOPSIS
.In openssl/evp.h
.Ft typedef struct evp_sskeymgmt_st EVP_SKEYMGMT;

 EVP_SKEYMGMT *
.Fo EVP_SKEYMGMT_fetch
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *algorithm"
.Fa "const char *properties"
.Fc
.Ft int
.Fo EVP_SKEYMGMT_up_ref
.Fa "EVP_SKEYMGMT *skeymgmt"
.Fc
.Ft void
.Fo EVP_SKEYMGMT_free
.Fa "EVP_SKEYMGMT *skeymgmt"
.Fc
.Ft const OSSL_PROVIDER *
.Fo EVP_SKEYMGMT_get0_provider
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fc
.Ft int
.Fo EVP_SKEYMGMT_is_a
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fa "const char *name"
.Fc
.Ft const char *
.Fo EVP_SKEYMGMT_get0_name
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fc
.Ft const char *
.Fo EVP_SKEYMGMT_get0_description
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fc
.Ft void
.Fo EVP_SKEYMGMT_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*fn)(EVP_SKEYMGMT *skeymgmt"
.Fa "void *arg)"
.Fa "void *arg"
.Fc
.Ft int
.Fo EVP_SKEYMGMT_names_do_all
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_SKEYMGMT_get0_gen_settable_params
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_SKEYMGMT_get0_imp_settable_params
.Fa "const EVP_SKEYMGMT *skeymgmt"
.Fc
.Sh DESCRIPTION
.Vt EVP_SKEYMGMT
is a method object that represents symmetric key management
implementations for different cryptographic algorithms.
This method object provides functionality to allow providers to import
key material from the outside, as well as export key material to the
outside.
.Pp
Most of the functionality can only be used internally and has no public
interface, this opaque object is simply passed into other functions when
needed.
.Pp
.Fn EVP_SKEYMGMT_fetch
looks for an algorithm within a provider that has been loaded into the
.Vt OSSL_LIB_CTX
given by
.Fa ctx ,
having the name given by
.Fa algorithm
and the properties given by
.Fa properties .
.Pp
.Fn EVP_SKEYMGMT_up_ref
increments the reference count for the given
.Vt EVP_SKEYMGMT
.Fa skeymgmt .
.Pp
.Fn EVP_SKEYMGMT_free
decrements the reference count for the given
.Vt EVP_SKEYMGMT
.Fa skeymgmt ,
and when the count reaches zero, frees it.
If the argument is NULL, nothing is done.
.Pp
.Fn EVP_SKEYMGMT_get0_provider
returns the provider that has this particular implementation.
.Pp
.Fn EVP_SKEYMGMT_is_a
checks if
.Fa skeymgmt
is an implementation of an algorithm that's identified by
.Fa name .
.Pp
.Fn EVP_SKEYMGMT_get0_name
returns the algorithm name from the provided implementation for the
given
.Fa skeymgmt .
Note that the
.Fa skeymgmt
may have multiple synonyms associated with it.
In this case the first name from the algorithm definition is returned.
Ownership of the returned string is retained by the
.Fa skeymgmt
object and should not be freed by the caller.
.Pp
.Fn EVP_SKEYMGMT_names_do_all
traverses all names for the
.Fa skeymgmt ,
and calls
.Em fn
with each name and
.Fa data .
.Pp
.Fn EVP_SKEYMGMT_get0_description
returns a description of the
.Fa skeymgmt ,
meant for display and human consumption.
The description is at the discretion of the
.Fa skeymgmt
implementation.
.Pp
.Fn EVP_SKEYMGMT_do_all_provided
traverses all key
.Fa skeymgmt
implementations by all activated providers in the library context
.Fa libctx ,
and for each of the implementations, calls
.Em fn
with the implementation method and
.Fa data
as arguments.
.Pp
.Fn EVP_SKEYMGMT_get0_gen_settable_params
and
.Fn EVP_SKEYMGMT_get0_imp_settable_params
get a constant
.Xr OSSL_PARAM 3
array that describes the settable parameters that can be used with
.Xr EVP_SKEY_generate 3
and
.Xr EVP_SKEY_import 3
correspondingly.
.Sh NOTES
.Fn EVP_SKEYMGMT_fetch
may be called implicitly by other fetching functions, using the same
library context and properties.
Any other API that uses symmetric keys will typically do this.
.Sh RETURN VALUES
.Fn EVP_SKEYMGMT_fetch
returns a pointer to the key management implementation represented by an
EVP_SKEYMGMT object, or NULL on error.
.Pp
.Fn EVP_SKEYMGMT_up_ref
returns 1 on success, or 0 on error.
.Pp
.Fn EVP_SKEYMGMT_names_do_all
returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.Pp
.Fn EVP_SKEYMGMT_free
doesn't return any value.
.Pp
.Fn EVP_SKEYMGMT_get0_provider
returns a pointer to a provider object, or NULL on error.
.Pp
.Fn EVP_SKEYMGMT_is_a
returns 1 if
.Fa skeymgmt
was identifiable, otherwise 0.
.Pp
.Fn EVP_SKEYMGMT_get0_name
returns the algorithm name, or NULL on error.
.Pp
.Fn EVP_SKEYMGMT_get0_description
returns a pointer to a description, or NULL if there isn't one.
.Sh SEE ALSO
.Xr EVP_SKEY 3 ,
.Xr EVP_MD_fetch 3 ,
.Xr OSSL_LIB_CTX 3
.Sh HISTORY
.Vt EVP_SKEYMGMT
structure and functions
.Fn EVP_SKEYMGMT_fetch ,
.Fn EVP_SKEYMGMT_up_ref ,
.Fn EVP_SKEYMGMT_free ,
.Fn EVP_SKEYMGMT_get0_provider ,
.Fn EVP_SKEYMGMT_is_a ,
.Fn EVP_SKEYMGMT_get0_description ,
.Fn EVP_SKEYMGMT_get0_name ,
.Fn EVP_SKEYMGMT_do_all_provided ,
.Fn EVP_SKEYMGMT_names_do_all ,
.Fn EVP_SKEYMGMT_get0_gen_settable_params ,
.Fn EVP_SKEYMGMT_get0_imp_settable_params
were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
