.Dd 2025-09-30
.Dt EVP_SM4_CBC 3ossl
.Os
.Sh NAME
.Nm EVP_sm4_cbc ,
.Nm EVP_sm4_ecb ,
.Nm EVP_sm4_cfb ,
.Nm EVP_sm4_cfb128 ,
.Nm EVP_sm4_ofb ,
.Nm EVP_sm4_ctr
.Nd EVP SM4 cipher
.Sh SYNOPSIS
.In openssl/evp.h
.Ft const EVP_CIPHER *
.Fo EVP_sm4_cbc
.Fa void
.Fc
.Ft const EVP_CIPHER *
.Fo EVP_sm4_ecb
.Fa void
.Fc
.Ft const EVP_CIPHER *
.Fo EVP_sm4_cfb
.Fa void
.Fc
.Ft const EVP_CIPHER *
.Fo EVP_sm4_cfb128
.Fa void
.Fc
.Ft const EVP_CIPHER *
.Fo EVP_sm4_ofb
.Fa void
.Fc
.Ft const EVP_CIPHER *
.Fo EVP_sm4_ctr
.Fa void
.Fc
.Sh DESCRIPTION
The SM4 blockcipher (GB/T 32907-2016) for EVP.
.Pp
All modes below use a key length of 128 bits and acts on blocks of 128
bits.
.Bl -tag -width Ds
.It EVP_sm4_cbc(), EVP_sm4_ecb(), EVP_sm4_cfb(), EVP_sm4_cfb128(), EVP_sm4_ofb(), EVP_sm4_ctr()
The SM4 blockcipher with a 128-bit key in CBC, ECB, CFB, OFB and CTR
modes respectively.
.El
.Sh NOTES
Developers should be aware of the negative performance implications of
calling these functions multiple times and should consider using
.Xr EVP_CIPHER_fetch 3
with
.Xr EVP_CIPHER-SM4 7
instead.
See
.Xr crypto 7
for further information.
.Sh RETURN VALUES
These functions return a
.Sy EVP_CIPHER
structure that contains the implementation of the symmetric cipher.
See
.Xr EVP_CIPHER_meth_new 3
for details of the
.Sy EVP_CIPHER
structure.
.Sh SEE ALSO
.Xr evp 7 ,
.Xr EVP_EncryptInit 3 ,
.Xr EVP_CIPHER_meth_new 3
.Sh COPYRIGHT
Copyright 2017-2023 The OpenSSL Project Authors.
All Rights Reserved.
Copyright 2017 Ribose Inc.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
