.Dd 2025-09-30
.Dt EVP_PKEY_SET_TYPE 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_set_type ,
.Nm EVP_PKEY_set_type_str ,
.Nm EVP_PKEY_set_type_by_keymgmt
.Nd functions to change the EVP_PKEY type
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_set_type
.Fa "EVP_PKEY *pkey"
.Fa "int type"
.Fc
.Ft int
.Fo EVP_PKEY_set_type_str
.Fa "EVP_PKEY *pkey"
.Fa "const char *str"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_set_type_by_keymgmt
.Fa "EVP_PKEY *pkey"
.Fa "EVP_KEYMGMT *keymgmt"
.Fc
.Sh DESCRIPTION
All the functions described here behave the same in so far that they
clear all the previous key data and methods from
.Fa pkey ,
and reset it to be of the type of key given by the different arguments.
If
.Fa pkey
is NULL, these functions will still return the same return values as if
it wasn't.
.Pp
.Fn EVP_PKEY_set_type
initialises
.Fa pkey
to contain an internal legacy key.
When doing this, it finds a
.Xr EVP_PKEY_ASN1_METHOD 3
corresponding to
.Fa type ,
and associates
.Fa pkey
with the findings.
It is an error if no
.Xr EVP_PKEY_ASN1_METHOD 3
could be found for
.Fa type .
.Pp
.Fn EVP_PKEY_set_type_str
initialises
.Fa pkey
to contain an internal legacy key.
When doing this, it finds a
.Xr EVP_PKEY_ASN1_METHOD 3
corresponding to
.Fa str
that has then length
.Fa len ,
and associates
.Fa pkey
with the findings.
It is an error if no
.Xr EVP_PKEY_ASN1_METHOD 3
could be found for
.Fa type .
.Pp
For both
.Fn EVP_PKEY_set_type
and
.Fn EVP_PKEY_set_type_str ,
.Fa pkey
gets a numeric type, which can be retrieved with
.Xr EVP_PKEY_get_id 3 .
This numeric type is taken from the
.Xr EVP_PKEY_ASN1_METHOD 3
that was found, and is equal to or closely related to
.Fa type
in the case of
.Fn EVP_PKEY_set_type ,
or related to
.Fa str
in the case of
.Fn EVP_PKEY_set_type_str .
.Pp
.Fn EVP_PKEY_set_type_by_keymgmt
initialises
.Fa pkey
to contain an internal provider side key.
When doing this, it associates
.Fa pkey
with
.Fa keymgmt .
For keys initialised like this, the numeric type retrieved with
.Xr EVP_PKEY_get_id 3
will always be
.Sy EVP_PKEY_NONE .
.Sh RETURN VALUES
All functions described here return 1 if successful, or 0 on error.
.Sh SEE ALSO
.Xr EVP_PKEY_assign 3 ,
.Xr EVP_PKEY_get_id 3 ,
.Xr EVP_PKEY_get0_RSA 3 ,
.Xr EVP_PKEY_copy_parameters 3 ,
.Xr EVP_PKEY_ASN1_METHOD 3 ,
.Xr EVP_KEYMGMT 3
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
