.Dd 2025-09-30
.Dt EVP_DIGESTINIT 3ossl
.Os
.Sh NAME
.Nm EVP_MD_fetch ,
.Nm EVP_MD_up_ref ,
.Nm EVP_MD_free ,
.Nm EVP_MD_get_params ,
.Nm EVP_MD_gettable_params ,
.Nm EVP_MD_CTX_new ,
.Nm EVP_MD_CTX_reset ,
.Nm EVP_MD_CTX_free ,
.Nm EVP_MD_CTX_dup ,
.Nm EVP_MD_CTX_copy ,
.Nm EVP_MD_CTX_copy_ex ,
.Nm EVP_MD_CTX_ctrl ,
.Nm EVP_MD_CTX_set_params ,
.Nm EVP_MD_CTX_get_params ,
.Nm EVP_MD_settable_ctx_params ,
.Nm EVP_MD_gettable_ctx_params ,
.Nm EVP_MD_CTX_settable_params ,
.Nm EVP_MD_CTX_gettable_params ,
.Nm EVP_MD_CTX_set_flags ,
.Nm EVP_MD_CTX_clear_flags ,
.Nm EVP_MD_CTX_test_flags ,
.Nm EVP_Q_digest ,
.Nm EVP_Digest ,
.Nm EVP_DigestInit_ex2 ,
.Nm EVP_DigestInit_ex ,
.Nm EVP_DigestInit ,
.Nm EVP_DigestUpdate ,
.Nm EVP_DigestFinal_ex ,
.Nm EVP_DigestFinalXOF ,
.Nm EVP_DigestFinal ,
.Nm EVP_DigestSqueeze ,
.Nm EVP_MD_is_a ,
.Nm EVP_MD_get0_name ,
.Nm EVP_MD_get0_description ,
.Nm EVP_MD_names_do_all ,
.Nm EVP_MD_get0_provider ,
.Nm EVP_MD_get_type ,
.Nm EVP_MD_get_pkey_type ,
.Nm EVP_MD_get_size ,
.Nm EVP_MD_get_block_size ,
.Nm EVP_MD_get_flags ,
.Nm EVP_MD_CTX_get0_name ,
.Nm EVP_MD_CTX_md ,
.Nm EVP_MD_CTX_get0_md ,
.Nm EVP_MD_CTX_get1_md ,
.Nm EVP_MD_CTX_get_type ,
.Nm EVP_MD_CTX_get_size_ex ,
.Nm EVP_MD_CTX_get_block_size ,
.Nm EVP_MD_CTX_get0_md_data ,
.Nm EVP_MD_CTX_update_fn ,
.Nm EVP_MD_CTX_set_update_fn ,
.Nm EVP_md_null ,
.Nm EVP_get_digestbyname ,
.Nm EVP_get_digestbynid ,
.Nm EVP_get_digestbyobj ,
.Nm EVP_MD_CTX_get_pkey_ctx ,
.Nm EVP_MD_CTX_set_pkey_ctx ,
.Nm EVP_MD_do_all_provided ,
.Nm EVP_MD_type ,
.Nm EVP_MD_nid ,
.Nm EVP_MD_name ,
.Nm EVP_MD_pkey_type ,
.Nm EVP_MD_size ,
.Nm EVP_MD_block_size ,
.Nm EVP_MD_flags ,
.Nm EVP_MD_xof ,
.Nm EVP_MD_CTX_size ,
.Nm EVP_MD_CTX_get_size ,
.Nm EVP_MD_CTX_block_size ,
.Nm EVP_MD_CTX_type ,
.Nm EVP_MD_CTX_pkey_ctx ,
.Nm EVP_MD_CTX_md_data
.Nd EVP digest routines
.Sh SYNOPSIS
.In openssl/evp.h
.Ft EVP_MD *
.Fo EVP_MD_fetch
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *algorithm"
.Fa "const char *properties"
.Fc
.Ft int
.Fo EVP_MD_up_ref
.Fa "EVP_MD *md"
.Fc
.Ft void
.Fo EVP_MD_free
.Fa "EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_get_params
.Fa "const EVP_MD *digest"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MD_gettable_params
.Fa "const EVP_MD *digest"
.Fc
.Ft EVP_MD_CTX *
.Fo EVP_MD_CTX_new
.Fa void
.Fc
.Ft int
.Fo EVP_MD_CTX_reset
.Fa "EVP_MD_CTX *ctx"
.Fc
.Ft void
.Fo EVP_MD_CTX_free
.Fa "EVP_MD_CTX *ctx"
.Fc
.Ft void
.Fo EVP_MD_CTX_ctrl
.Fa "EVP_MD_CTX *ctx"
.Fa "int cmd"
.Fa "int p1"
.Fa "void* p2"
.Fc
.Ft int
.Fo EVP_MD_CTX_get_params
.Fa "EVP_MD_CTX *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_MD_CTX_set_params
.Fa "EVP_MD_CTX *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MD_settable_ctx_params
.Fa "const EVP_MD *md"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MD_gettable_ctx_params
.Fa "const EVP_MD *md"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MD_CTX_settable_params
.Fa "EVP_MD_CTX *ctx"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_MD_CTX_gettable_params
.Fa "EVP_MD_CTX *ctx"
.Fc
.Ft void
.Fo EVP_MD_CTX_set_flags
.Fa "EVP_MD_CTX *ctx"
.Fa "int flags"
.Fc
.Ft void
.Fo EVP_MD_CTX_clear_flags
.Fa "EVP_MD_CTX *ctx"
.Fa "int flags"
.Fc
.Ft int
.Fo EVP_MD_CTX_test_flags
.Fa "const EVP_MD_CTX *ctx"
.Fa "int flags"
.Fc
.Ft int
.Fo EVP_Q_digest
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *name"
.Fa "const char *propq"
.Fa "const void *data"
.Fa "size_t datalen"
.Fa "unsigned char *md"
.Fa "size_t *mdlen"
.Fc
.Ft int
.Fo EVP_Digest
.Fa "const void *data"
.Fa "size_t count"
.Fa "unsigned char *md"
.Fa "unsigned int *size"
.Fa "const EVP_MD *type"
.Fa "ENGINE *impl"
.Fc
.Ft int
.Fo EVP_DigestInit_ex2
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_DigestInit_ex
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fa "ENGINE *impl"
.Fc
.Ft int
.Fo EVP_DigestUpdate
.Fa "EVP_MD_CTX *ctx"
.Fa "const void *d"
.Fa "size_t cnt"
.Fc
.Ft int
.Fo EVP_DigestFinal_ex
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *md"
.Fa "unsigned int *s"
.Fc
.Ft int
.Fo EVP_DigestFinalXOF
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t outlen"
.Fc
.Ft int
.Fo EVP_DigestSqueeze
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t outlen"
.Fc
.Ft EVP_MD_CTX *
.Fo EVP_MD_CTX_dup
.Fa "const EVP_MD_CTX *in"
.Fc
.Ft int
.Fo EVP_MD_CTX_copy_ex
.Fa "EVP_MD_CTX *out"
.Fa "const EVP_MD_CTX *in"
.Fc
.Ft int
.Fo EVP_DigestInit
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fc
.Ft int
.Fo EVP_DigestFinal
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *md"
.Fa "unsigned int *s"
.Fc
.Ft int
.Fo EVP_MD_CTX_copy
.Fa "EVP_MD_CTX *out"
.Fa "EVP_MD_CTX *in"
.Fc
.Ft const char *
.Fo EVP_MD_get0_name
.Fa "const EVP_MD *md"
.Fc
.Ft const char *
.Fo EVP_MD_get0_description
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_is_a
.Fa "const EVP_MD *md"
.Fa "const char *name"
.Fc
.Ft int
.Fo EVP_MD_names_do_all
.Fa "const EVP_MD *md"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
.Ft const OSSL_PROVIDER *
.Fo EVP_MD_get0_provider
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_get_type
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_get_pkey_type
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_get_size
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_get_block_size
.Fa "const EVP_MD *md"
.Fc
.Ft unsigned long
.Fo EVP_MD_get_flags
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_xof
.Fa "const EVP_MD *md"
.Fc
.Ft const EVP_MD *
.Fo EVP_MD_CTX_get0_md
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft EVP_MD *
.Fo EVP_MD_CTX_get1_md
.Fa "EVP_MD_CTX *ctx"
.Fc
.Ft const char *
.Fo EVP_MD_CTX_get0_name
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft int
.Fo EVP_MD_CTX_get_size_ex
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft int
.Fo EVP_MD_CTX_get_block_size
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft int
.Fo EVP_MD_CTX_get_type
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft void *
.Fo EVP_MD_CTX_get0_md_data
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft const EVP_MD *
.Fo EVP_md_null
.Fa void
.Fc
.Ft const EVP_MD *
.Fo EVP_get_digestbyname
.Fa "const char *name"
.Fc
.Ft const EVP_MD *
.Fo EVP_get_digestbynid
.Fa "int type"
.Fc
.Ft const EVP_MD *
.Fo EVP_get_digestbyobj
.Fa "const ASN1_OBJECT *o"
.Fc
.Ft EVP_PKEY_CTX *
.Fo EVP_MD_CTX_get_pkey_ctx
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft void
.Fo EVP_MD_CTX_set_pkey_ctx
.Fa "EVP_MD_CTX *ctx"
.Fa "EVP_PKEY_CTX *pctx"
.Fc
.Ft void
.Fo EVP_MD_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*fn)(EVP_MD *mac"
.Fa "void *arg)"
.Fa "void *arg"
.Fc
.Fd #define EVP_MD_type EVP_MD_get_type
.Fd #define EVP_MD_nid EVP_MD_get_type
.Fd #define EVP_MD_name EVP_MD_get0_name
.Fd #define EVP_MD_pkey_type EVP_MD_get_pkey_type
.Fd #define EVP_MD_size EVP_MD_get_size
.Fd #define EVP_MD_block_size EVP_MD_get_block_size
.Fd #define EVP_MD_flags EVP_MD_get_flags
.Fd #define EVP_MD_CTX_get_size EVP_MD_CTX_get_size_ex
.Fd #define EVP_MD_CTX_size EVP_MD_CTX_get_size_ex
.Fd #define EVP_MD_CTX_block_size EVP_MD_CTX_get_block_size
.Fd #define EVP_MD_CTX_type EVP_MD_CTX_get_type
.Fd #define EVP_MD_CTX_pkey_ctx EVP_MD_CTX_get_pkey_ctx
.Fd #define EVP_MD_CTX_md_data EVP_MD_CTX_get0_md_data
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft const EVP_MD *
.Fo EVP_MD_CTX_md
.Fa "const EVP_MD_CTX *ctx"
.Fc
.Ft int
.Fo 
.Fa "*EVP_MD_CTX_update_fn(EVP_MD_CTX *ctx)"
.Fc
(EVP_MD_CTX *ctx,
.Bd -literal
                                              const void *data, size_t count);
.Ed
.Ft void
.Fo EVP_MD_CTX_set_update_fn
.Fa "EVP_MD_CTX *ctx"
.Fa "int (*update)(EVP_MD_CTX *ctx"
.Fa "const void *data"
.Fa "size_t count)"
.Fc
.Sh DESCRIPTION
The EVP digest routines are a high-level interface to message digests,
and Extendable Output Functions (XOF).
.Pp
The
.Vt EVP_MD
type is a structure for digest method implementation.
.Pp
Each Message digest algorithm (such as SHA256) produces a fixed size
output length which is returned when
.Fn EVP_DigestFinal_ex
is called.
Extendable Output Functions (XOF) such as SHAKE256 have a variable sized
output length
.Fa outlen
which can be used with either
.Fn EVP_DigestFinalXOF
or
.Fn EVP_DigestSqueeze .
.Fn EVP_DigestFinal_ex
may also be used for an XOF, but the "xoflen" must be set beforehand
(See
.Sx PARAMETERS Ns ).
Note that
.Fn EVP_MD_get_size
and
.Fn EVP_MD_CTX_get_size_ex
behave differently for an XOF.
.Bl -tag -width Ds
.It EVP_MD_fetch()
Fetches the digest implementation for the given
.Fa algorithm
from any provider offering it, within the criteria given by the
.Fa properties .
See
.Xr crypto 7
for further information.
.Pp
The returned value must eventually be freed with
.Fn EVP_MD_free .
.Pp
Fetched
.Vt EVP_MD
structures are reference counted.
.It EVP_MD_up_ref()
Increments the reference count for an
.Vt EVP_MD
structure.
.It EVP_MD_free()
Decrements the reference count for the fetched
.Vt EVP_MD
structure.
If the reference count drops to 0 then the structure is freed.
If the argument is NULL, nothing is done.
.It EVP_MD_CTX_new()
Allocates and returns a digest context.
.It EVP_MD_CTX_reset()
Resets the digest context
.Fa ctx .
This can be used to reuse an already existing context.
.It EVP_MD_CTX_free()
Cleans up digest context
.Fa ctx
and frees up the space allocated to it.
If the argument is NULL, nothing is done.
.It EVP_MD_CTX_ctrl()
.Em This is a legacy method. EVP_MD_CTX_set_params() and EVP_MD_CTX_get_params() is the mechanism that should be used to set and get parameters that are used by providers.
.Pp
Performs digest-specific control actions on context
.Fa ctx .
The control command is indicated in
.Fa cmd
and any additional arguments in
.Fa p1
and
.Fa p2 .
.Fn EVP_MD_CTX_ctrl
must be called after
.Fn EVP_DigestInit_ex2 .
Other restrictions may apply depending on the control type and digest
implementation.
.Pp
If this function happens to be used with a fetched
.Vt EVP_MD ,
it will translate the controls that are known to OpenSSL into
.Xr OSSL_PARAM 3
parameters with keys defined by OpenSSL and call
.Fn EVP_MD_CTX_get_params
or
.Fn EVP_MD_CTX_set_params
as is appropriate for each control command.
.Pp
See
.Sx CONTROLS
below for more information, including what translations are being done.
.It EVP_MD_get_params()
Retrieves the requested list of
.Em params
from a MD
.Fa md .
See
.Sx PARAMETERS
below for more information.
.It EVP_MD_CTX_get_params()
Retrieves the requested list of
.Em params
from a MD context
.Fa ctx .
See
.Sx PARAMETERS
below for more information.
.It EVP_MD_CTX_set_params()
Sets the list of
.Em params
into a MD context
.Fa ctx .
See
.Sx PARAMETERS
below for more information.
.It EVP_MD_gettable_params()
Get a constant
.Xr OSSL_PARAM 3
array that describes the retrievable parameters that can be used with
.Fn EVP_MD_get_params .
.It EVP_MD_gettable_ctx_params(), EVP_MD_CTX_gettable_params()
Get a constant
.Xr OSSL_PARAM 3
array that describes the retrievable parameters that can be used with
.Fn EVP_MD_CTX_get_params .
.Fn EVP_MD_gettable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_MD_CTX_gettable_params
returns the parameters that can be retrieved in the context's current
state.
.It EVP_MD_settable_ctx_params(), EVP_MD_CTX_settable_params()
Get a constant
.Xr OSSL_PARAM 3
array that describes the settable parameters that can be used with
.Fn EVP_MD_CTX_set_params .
.Fn EVP_MD_settable_ctx_params
returns the parameters that can be set from the algorithm, whereas
.Fn EVP_MD_CTX_settable_params
returns the parameters that can be set in the context's current state.
.It EVP_MD_CTX_set_flags(), EVP_MD_CTX_clear_flags(), EVP_MD_CTX_test_flags()
Sets, clears and tests
.Fa ctx
flags.
See
.Sx FLAGS
below for more information.
.It EVP_Q_digest() is a quick one-shot digest function.
It hashes
.Fa datalen
bytes of data at
.Fa data
using the digest algorithm
.Fa name ,
which is fetched using the optional
.Fa libctx
and
.Fa propq
parameters.
The digest value is placed in
.Fa md
and its length is written at
.Fa mdlen
if the pointer is not NULL. At most
.Sy EVP_MAX_MD_SIZE
bytes will be written.
.It EVP_Digest()
A wrapper around the Digest Init_ex, Update and Final_ex functions.
Hashes
.Fa count
bytes of data at
.Fa data
using a digest
.Fa type
from ENGINE
.Fa impl .
The digest value is placed in
.Fa md
and its length is written at
.Fa size
if the pointer is not NULL. At most
.Sy EVP_MAX_MD_SIZE
bytes will be written.
If
.Fa impl
is NULL the default implementation of digest
.Fa type
is used.
.It EVP_DigestInit_ex2()
Sets up digest context
.Fa ctx
to use a digest
.Fa type .
.Fa type
is typically supplied by a function such as
.Xr EVP_sha1 3 ,
or a value explicitly fetched with
.Fn EVP_MD_fetch .
.Fa ctx
.Sy MUST NOT
be NULL.
.Pp
The parameters
.Sy params
are set on the context after initialisation.
.Pp
The
.Fa type
parameter can be NULL if
.Fa ctx
has been already initialized with another
.Fn EVP_DigestInit_ex
call and has not been reset with
.Fn EVP_MD_CTX_reset .
.It EVP_DigestInit_ex()
Sets up digest context
.Fa ctx
to use a digest
.Fa type .
.Fa type
is typically supplied by a function such as
.Xr EVP_sha1 3 ,
or a value explicitly fetched with
.Fn EVP_MD_fetch .
.Pp
If
.Fa impl
is non-NULL, its implementation of the digest
.Fa type
is used if there is one, and if not, the default implementation is used.
.Pp
The
.Fa type
parameter can be NULL if
.Fa ctx
has been already initialized with another
.Fn EVP_DigestInit_ex
call and has not been reset with
.Fn EVP_MD_CTX_reset .
.It EVP_DigestUpdate()
Hashes
.Fa cnt
bytes of data at
.Fa d
into the digest context
.Fa ctx .
This function can be called several times on the same
.Fa ctx
to hash additional data.
.It EVP_DigestFinal_ex()
Retrieves the digest value from
.Fa ctx
and places it in
.Fa md .
If the
.Fa s
parameter is not NULL then the number of bytes of data written (i.e.
the length of the digest) will be written to the integer at
.Fa s ,
at most
.Sy EVP_MAX_MD_SIZE
bytes will be written unless the digest implementation allows changing
the digest size and it is set to a larger value by the application.
After calling
.Fn EVP_DigestFinal_ex
no additional calls to
.Fn EVP_DigestUpdate
can be made, but
.Fn EVP_DigestInit_ex2
can be called to initialize a new digest operation.
.Fa ctx
.Sy MUST NOT
be NULL.
.It EVP_DigestFinalXOF()
Interfaces to extendable-output functions, XOFs, such as SHAKE128 and
SHAKE256. It retrieves the digest value from
.Fa ctx
and places it in
.Fa outlen Ns -sized
.Fa out .
After calling this function no additional calls to
.Fn EVP_DigestUpdate
can be made, but
.Fn EVP_DigestInit_ex2
can be called to initialize a new operation.
.Fn EVP_DigestFinalXOF
may only be called once
.It EVP_DigestSqueeze()
Similar to
.Fn EVP_DigestFinalXOF
but allows multiple calls to be made to squeeze variable length output
data.
.Fn EVP_DigestFinalXOF
should not be called after this.
.It EVP_MD_CTX_dup()
Can be used to duplicate the message digest state from
.Fa in .
This is useful to avoid multiple
.Fn EVP_MD_fetch
calls or if large amounts of data are to be hashed which only differ in
the last few bytes.
.It EVP_MD_CTX_copy_ex()
Can be used to copy the message digest state from
.Fa in
to
.Fa out .
This is useful if large amounts of data are to be hashed which only
differ in the last few bytes.
.It EVP_DigestInit()
Behaves in the same way as
.Fn EVP_DigestInit_ex2
except it doesn't set any parameters and calls
.Fn EVP_MD_CTX_reset
so it cannot be used with an
.Fa type
of NULL.
.It EVP_DigestFinal()
Similar to
.Fn EVP_DigestFinal_ex
except after computing the digest the digest context
.Fa ctx
is automatically cleaned up with
.Fn EVP_MD_CTX_reset .
.It EVP_MD_CTX_copy()
Similar to
.Fn EVP_MD_CTX_copy_ex
except the destination
.Fa out
does not have to be initialized.
.It EVP_MD_is_a()
Returns 1 if
.Fa md
is an implementation of an algorithm that's identifiable with
.Fa name ,
otherwise 0.
.Pp
If
.Fa md
is a legacy digest (it's the return value from the likes of
.Xr EVP_sha256 3
rather than the result of an
.Fn EVP_MD_fetch ) ,
only cipher names registered with the default library context (see
.Xr OSSL_LIB_CTX 3 )
will be considered.
.It EVP_MD_xof()
Returns 1 if
.Fa md
is an Extendable-output Function (XOF) otherwise it returns 0. SHAKE128
and SHAKE256 are XOF functions.
It returns 0 for BLAKE2B algorithms.
.It EVP_MD_get0_name(), EVP_MD_CTX_get0_name()
Return the name of the given message digest.
For fetched message digests with multiple names, only one of them is
returned; it's recommended to use
.Fn EVP_MD_names_do_all
instead.
.It EVP_MD_names_do_all()
Traverses all names for the
.Fa md ,
and calls
.Em fn
with each name and
.Fa data .
This is only useful with fetched
.Vt EVP_MD Ns s.
.It EVP_MD_get0_description()
Returns a description of the digest, meant for display and human
consumption.
The description is at the discretion of the digest implementation.
.It EVP_MD_get0_provider()
Returns an
.Sy OSSL_PROVIDER
pointer to the provider that implements the given
.Vt EVP_MD .
.It EVP_MD_get_size()
Return the size of the message digest when passed an
.Vt EVP_MD ,
i.e.
the size of the hash.
A negative value or 0 can occur for invalid size.
For an XOF with no default size this returns 0.
.It EVP_MD_CTX_get_size_ex(), EVP_MD_CTX_get_size()
For a normal digest this is the same as
.Fn EVP_MD_get_size .
For an XOF this returns the "xoflen" if it has been set, otherwise it
returns 0.
.It EVP_MD_get_block_size(), EVP_MD_CTX_get_block_size()
Return the block size of the message digest when passed an
.Vt EVP_MD
or an
.Vt EVP_MD_CTX
structure.
.It EVP_MD_get_type(), EVP_MD_CTX_get_type()
Return the NID of the OBJECT IDENTIFIER representing the given message
digest when passed an
.Vt EVP_MD
structure.
For example,
.Qo Li EVP_MD_get_type(EVP_sha1()) Qc
returns
.Sy NID_sha1 .
This function is normally used when setting ASN1 OIDs.
.It EVP_MD_CTX_get0_md_data()
Return the digest method private data for the passed
.Vt EVP_MD_CTX .
The space is allocated by OpenSSL and has the size originally set with
.Xr EVP_MD_meth_set_app_datasize 3 .
.It EVP_MD_CTX_get0_md(), EVP_MD_CTX_get1_md()
.Fn EVP_MD_CTX_get0_md
returns the
.Vt EVP_MD
structure corresponding to the passed
.Vt EVP_MD_CTX .
This will be the same
.Vt EVP_MD
object originally passed to
.Fn EVP_DigestInit_ex2
(or other similar function) when the EVP_MD_CTX was first initialised.
Note that where explicit fetch is in use (see
.Xr EVP_MD_fetch 3 )
the value returned from this function will not have its reference count
incremented and therefore it should not be used after the EVP_MD_CTX is
freed.
.Fn EVP_MD_CTX_get1_md
is the same except the ownership is passed to the caller and is from the
passed
.Vt EVP_MD_CTX .
.It EVP_MD_CTX_set_update_fn()
Sets the update function for
.Fa ctx
to
.Em update .
This is the function that is called by
.Fn EVP_DigestUpdate .
If not set, the update function from the
.Vt EVP_MD
type specified at initialization is used.
.It EVP_MD_CTX_update_fn()
Returns the update function for
.Fa ctx .
.It EVP_MD_get_flags()
Returns the
.Fa md
flags.
Note that these are different from the
.Vt EVP_MD_CTX
ones.
See
.Xr EVP_MD_meth_set_flags 3
for more information.
.It EVP_MD_get_pkey_type()
Returns the NID of the public key signing algorithm associated with this
digest.
For example
.Xr EVP_sha1 3
is associated with RSA so this will return
.Sy NID_sha1WithRSAEncryption .
Since digests and signature algorithms are no longer linked this
function is only retained for compatibility reasons.
.It EVP_md_null()
A "null" message digest that does nothing: i.e.
the hash it returns is of zero length.
.It EVP_get_digestbyname(), EVP_get_digestbynid(), EVP_get_digestbyobj()
Returns an
.Vt EVP_MD
structure when passed a digest name, a digest
.Sy NID
or an
.Sy ASN1_OBJECT
structure respectively.
.Pp
The
.Fn EVP_get_digestbyname
function is present for backwards compatibility with OpenSSL prior to
version 3 and is different to the
.Fn EVP_MD_fetch
function since it does not attempt to "fetch" an implementation of the
cipher.
Additionally, it only knows about digests that are built-in to OpenSSL
and have an associated NID. Similarly
.Fn EVP_get_digestbynid
and
.Fn EVP_get_digestbyobj
also return objects without an associated implementation.
.Pp
When the digest objects returned by these functions are used (such as in
a call to
.Fn EVP_DigestInit_ex )
an implementation of the digest will be implicitly fetched from the
loaded providers.
This fetch could fail if no suitable implementation is available.
Use
.Fn EVP_MD_fetch
instead to explicitly fetch the algorithm and an associated
implementation from a provider.
.Pp
See
.Xr crypto 7
for more information about fetching.
.Pp
The digest objects returned from these functions do not need to be freed
with
.Fn EVP_MD_free .
.It EVP_MD_CTX_get_pkey_ctx()
Returns the
.Vt EVP_PKEY_CTX
assigned to
.Fa ctx .
The returned pointer should not be freed by the caller.
.It EVP_MD_CTX_set_pkey_ctx()
Assigns an
.Vt EVP_PKEY_CTX
to
.Vt EVP_MD_CTX .
This is usually used to provide a customized
.Vt EVP_PKEY_CTX
to
.Xr EVP_DigestSignInit 3
or
.Xr EVP_DigestVerifyInit 3 .
The
.Fa pctx
passed to this function should be freed by the caller.
A NULL
.Fa pctx
pointer is also allowed to clear the
.Vt EVP_PKEY_CTX
assigned to
.Fa ctx .
In such case, freeing the cleared
.Vt EVP_PKEY_CTX
or not depends on how the
.Vt EVP_PKEY_CTX
is created.
.It EVP_MD_do_all_provided()
Traverses all messages digests implemented by all activated providers in
the given library context
.Fa libctx ,
and for each of the implementations, calls the given function
.Em fn
with the implementation method and the given
.Fa arg
as argument.
.El
.Sh PARAMETERS
See
.Xr OSSL_PARAM 3
for information about passing parameters.
.Pp
.Fn EVP_MD_CTX_set_params
and
.Fn EVP_MD_CTX_get_params
can be used with the following OSSL_PARAM keys:
.Bl -tag -width Ds
.It \(dqxoflen" ( Ns Sy OSSL_DIGEST_PARAM_XOFLEN Ns ) <unsigned integer>
Sets or gets the digest length for extendable output functions.
The value should not exceed what can be given using a
.Vt size_t .
It may be used by SHAKE-128 and SHAKE-256 to set the output length used
by
.Fn EVP_DigestFinal_ex
and
.Fn EVP_DigestFinal .
.It \(dqsize" ( Ns Sy OSSL_DIGEST_PARAM_SIZE Ns ) <unsigned integer>
Sets or gets a fixed digest length.
The value should not exceed what can be given using a
.Vt size_t .
It may be used by BLAKE2B-512 to set the output length used by
.Fn EVP_DigestFinal_ex
and
.Fn EVP_DigestFinal .
.El
.Pp
.Fn EVP_MD_CTX_set_params
can be used with the following OSSL_PARAM keys:
.Bl -tag -width Ds
.It \(dqpad-type" ( Ns Sy OSSL_DIGEST_PARAM_PAD_TYPE Ns ) <unsigned integer>
Sets the padding type.
It is used by the MDC2 algorithm.
.El
.Pp
.Fn EVP_MD_CTX_get_params
can be used with the following OSSL_PARAM keys:
.Bl -tag -width Ds
.It \(dqmicalg" ( Ns Sy OSSL_DIGEST_PARAM_MICALG Ns ) <UTF8 string>.
Gets the digest Message Integrity Check algorithm string.
This is used when creating S/MIME multipart/signed messages, as
specified in RFC 3851. It may be used by external engines or providers.
.El
.Sh CONTROLS
.Fn EVP_MD_CTX_ctrl
can be used to send the following standard controls:
.Bl -tag -width Ds
.It EVP_MD_CTRL_MICALG
Gets the digest Message Integrity Check algorithm string.
This is used when creating S/MIME multipart/signed messages, as
specified in RFC 3851. The string value is written to
.Fa p2 .
.Pp
When used with a fetched
.Vt EVP_MD ,
.Fn EVP_MD_CTX_get_params
gets called with an
.Xr OSSL_PARAM 3
item with the key "micalg"
.Pf ( Sy OSSL_DIGEST_PARAM_MICALG Ns ).
.It EVP_MD_CTRL_XOF_LEN
This control sets the digest length for extendable output functions to
.Fa p1 .
Sending this control directly should not be necessary, the use of
.Fn EVP_DigestFinalXOF
is preferred.
Currently used by SHAKE algorithms.
.Pp
When used with a fetched
.Vt EVP_MD ,
.Fn EVP_MD_CTX_get_params
gets called with an
.Xr OSSL_PARAM 3
item with the key "xoflen"
.Pf ( Sy OSSL_DIGEST_PARAM_XOFLEN Ns ).
.El
.Sh FLAGS
.Fn EVP_MD_CTX_set_flags ,
.Fn EVP_MD_CTX_clear_flags
and
.Fn EVP_MD_CTX_test_flags
can be used the manipulate and test these
.Vt EVP_MD_CTX
flags:
.Bl -tag -width Ds
.It EVP_MD_CTX_FLAG_ONESHOT
This flag instructs the digest to optimize for one update only, if
possible.
.It EVP_MD_CTX_FLAG_CLEANED
This flag is for internal use only and
.Em must not
be used in user code.
.It EVP_MD_CTX_FLAG_REUSE
This flag is for internal use only and
.Em must not
be used in user code.
.It EVP_MD_CTX_FLAG_NO_INIT
This flag instructs
.Fn EVP_DigestInit
and similar not to initialise the implementation specific data.
.It EVP_MD_CTX_FLAG_FINALISE
Some functions such as EVP_DigestSign only finalise copies of internal
contexts so additional data can be included after the finalisation call.
This is inefficient if this functionality is not required, and can be
disabled with this flag.
.El
.Sh RETURN VALUES
.Bl -tag -width Ds
.It EVP_MD_fetch()
Returns a pointer to a
.Vt EVP_MD
for success or NULL for failure.
.It EVP_MD_up_ref()
Returns 1 for success or 0 for failure.
.It EVP_Q_digest(), EVP_Digest(), EVP_DigestInit_ex2(), EVP_DigestInit_ex(), EVP_DigestInit(), EVP_DigestUpdate(), EVP_DigestFinal_ex(), EVP_DigestFinalXOF(), and EVP_DigestFinal()
return 1 for success and 0 for failure.
.It EVP_MD_CTX_ctrl()
Returns 1 if successful or 0 for failure.
.It EVP_MD_CTX_set_params(), EVP_MD_CTX_get_params()
Returns 1 if successful or 0 for failure.
.It EVP_MD_CTX_settable_params(), EVP_MD_CTX_gettable_params()
Return an array of constant
.Xr OSSL_PARAM 3 Ns s,
or NULL if there is none to get.
.It EVP_MD_CTX_dup()
Returns a new EVP_MD_CTX if successful or NULL on failure.
.It EVP_MD_CTX_copy_ex()
Returns 1 if successful or 0 for failure.
.It EVP_MD_get_type(), EVP_MD_get_pkey_type()
Returns the NID of the corresponding OBJECT IDENTIFIER or NID_undef if
none exists.
.It EVP_MD_get_size(), EVP_MD_get_block_size(), EVP_MD_CTX_get_size(), EVP_MD_CTX_get_block_size()
Returns the digest or block size in bytes or -1 for failure.
.It EVP_md_null()
Returns a pointer to the
.Vt EVP_MD
structure of the "null" message digest.
.It EVP_get_digestbyname(), EVP_get_digestbynid(), EVP_get_digestbyobj()
Returns either an
.Vt EVP_MD
structure or NULL if an error occurs.
.It EVP_MD_CTX_set_pkey_ctx()
This function has no return value.
.It EVP_MD_names_do_all()
Returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.El
.Sh NOTES
The
.Sy EVP
interface to message digests should almost always be used in preference
to the low-level interfaces.
This is because the code then becomes transparent to the digest used and
much more flexible.
.Pp
New applications should use the SHA-2 (such as
.Xr EVP_sha256 3 )
or the SHA-3 digest algorithms (such as
.Xr EVP_sha3_512 3 Ns ).
The other digest algorithms are still in common use.
.Pp
For most applications the
.Fa impl
parameter to
.Fn EVP_DigestInit_ex
will be set to NULL to use the default digest implementation.
.Pp
Ignoring failure returns of
.Fn EVP_DigestInit_ex ,
.Fn EVP_DigestInit_ex2 ,
or
.Fn EVP_DigestInit
can lead to undefined behavior on subsequent calls updating or
finalizing the
.Vt EVP_MD_CTX
such as the
.Fn EVP_DigestUpdate
or
.Fn EVP_DigestFinal
functions.
The only valid calls on the
.Vt EVP_MD_CTX
when initialization fails are calls that attempt another initialization
of the context or release the context.
.Pp
The functions
.Fn EVP_DigestInit ,
.Fn EVP_DigestFinal
and
.Fn EVP_MD_CTX_copy
are obsolete but are retained to maintain compatibility with existing
code.
New applications should use
.Fn EVP_DigestInit_ex ,
.Fn EVP_DigestFinal_ex
and
.Fn EVP_MD_CTX_copy_ex
because they can efficiently reuse a digest context instead of
initializing and cleaning it up on each call and allow non default
implementations of digests to be specified.
.Pp
If digest contexts are not cleaned up after use, memory leaks will
occur.
.Pp
.Fn EVP_MD_CTX_get0_name ,
.Fn EVP_MD_CTX_get_size ,
.Fn EVP_MD_CTX_get_block_size ,
.Fn EVP_MD_CTX_get_type ,
.Fn EVP_get_digestbynid
and
.Fn EVP_get_digestbyobj
are defined as macros.
.Pp
.Fn EVP_MD_CTX_ctrl
sends commands to message digests for additional configuration or
control.
.Sh EXAMPLES
This example digests the data "Test Message\en" and "Hello World\en",
using the digest name passed on the command line.
.Bd -literal
 #include <stdio.h>
 #include <string.h>
 #include <openssl/evp.h>

 int main(int argc, char *argv[])
 {
     EVP_MD_CTX *mdctx;
     const EVP_MD *md;
     char mess1[] = "Test Message\en";
     char mess2[] = "Hello World\en";
     unsigned char md_value[EVP_MAX_MD_SIZE];
     unsigned int md_len, i;

     if (argv[1] == NULL) {
         printf("Usage: mdtest digestname\en");
         exit(1);
     }

     md = EVP_get_digestbyname(argv[1]);
     if (md == NULL) {
         printf("Unknown message digest %s\en", argv[1]);
         exit(1);
     }

     mdctx = EVP_MD_CTX_new();
     if (mdctx == NULL) {
        printf("Message digest create failed.\en");
        exit(1);
     }
     if (!EVP_DigestInit_ex2(mdctx, md, NULL)) {
         printf("Message digest initialization failed.\en");
         EVP_MD_CTX_free(mdctx);
         exit(1);
     }
     if (!EVP_DigestUpdate(mdctx, mess1, strlen(mess1))) {
         printf("Message digest update failed.\en");
         EVP_MD_CTX_free(mdctx);
         exit(1);
     }
     if (!EVP_DigestUpdate(mdctx, mess2, strlen(mess2))) {
         printf("Message digest update failed.\en");
         EVP_MD_CTX_free(mdctx);
         exit(1);
     }
     if (!EVP_DigestFinal_ex(mdctx, md_value, &md_len)) {
         printf("Message digest finalization failed.\en");
         EVP_MD_CTX_free(mdctx);
         exit(1);
     }
     EVP_MD_CTX_free(mdctx);

     printf("Digest is: ");
     for (i = 0; i < md_len; i++)
         printf("%02x", md_value[i]);
     printf("\en");

     exit(0);
 }
.Ed
.Sh SEE ALSO
.Xr EVP_MD_meth_new 3 ,
.Xr openssl-dgst 1 ,
.Xr evp 7 ,
.Xr OSSL_PROVIDER 3 ,
.Xr OSSL_PARAM 3 ,
.Xr property 7 ,
.Xr crypto 7 ,
.Xr provider-digest 7 ,
.Xr life_cycle-digest 7
.Pp
The full list of digest algorithms are provided below.
.Pp
.Xr EVP_blake2b512 3 ,
.Xr EVP_md2 3 ,
.Xr EVP_md4 3 ,
.Xr EVP_md5 3 ,
.Xr EVP_mdc2 3 ,
.Xr EVP_ripemd160 3 ,
.Xr EVP_sha1 3 ,
.Xr EVP_sha224 3 ,
.Xr EVP_sha3_224 3 ,
.Xr EVP_sm3 3 ,
.Xr EVP_whirlpool 3
.Sh HISTORY
The
.Xr EVP_MD_CTX_create 3
and
.Xr EVP_MD_CTX_destroy 3
functions were renamed to
.Fn EVP_MD_CTX_new
and
.Fn EVP_MD_CTX_free
in OpenSSL 1.1.0, respectively.
.Pp
The link between digests and signing algorithms was fixed in OpenSSL 1.0
and later, so now
.Xr EVP_sha1 3
can be used with RSA and DSA.
.Pp
The
.Xr EVP_dss1 3
function was removed in OpenSSL 1.1.0.
.Pp
The
.Fn EVP_MD_CTX_set_pkey_ctx
function was added in OpenSSL 1.1.1.
.Pp
The
.Fn EVP_Q_digest ,
.Fn EVP_DigestInit_ex2 ,
.Fn EVP_MD_fetch ,
.Fn EVP_MD_free ,
.Fn EVP_MD_up_ref ,
.Fn EVP_MD_get_params ,
.Fn EVP_MD_CTX_set_params ,
.Fn EVP_MD_CTX_get_params ,
.Fn EVP_MD_gettable_params ,
.Fn EVP_MD_gettable_ctx_params ,
.Fn EVP_MD_settable_ctx_params ,
.Fn EVP_MD_CTX_settable_params
and
.Fn EVP_MD_CTX_gettable_params
functions were added in OpenSSL 3.0.
.Pp
The
.Fn EVP_MD_type ,
.Fn EVP_MD_nid ,
.Fn EVP_MD_name ,
.Fn EVP_MD_pkey_type ,
.Fn EVP_MD_size ,
.Fn EVP_MD_block_size ,
.Fn EVP_MD_flags ,
.Fn EVP_MD_CTX_size ,
.Fn EVP_MD_CTX_block_size ,
.Fn EVP_MD_CTX_type ,
and
.Fn EVP_MD_CTX_md_data
functions were renamed to include
.Qo Li get Qc
or
.Qo Li get0 Qc
in their names in OpenSSL 3.0, respectively.
The old names are kept as non-deprecated alias macros.
.Pp
The
.Fn EVP_MD_CTX_md
function was deprecated in OpenSSL 3.0; use
.Fn EVP_MD_CTX_get0_md
instead.
.Xr EVP_MD_CTX_update_fn 3
and
.Fn EVP_MD_CTX_set_update_fn
were deprecated in OpenSSL 3.0.
.Pp
The
.Fn EVP_MD_CTX_dup
function was added in OpenSSL 3.1.
.Pp
The
.Fn EVP_DigestSqueeze
function was added in OpenSSL 3.3.
.Pp
The
.Fn EVP_MD_CTX_get_size_ex
and
.Xr EVP_xof 3
functions were added in OpenSSL 3.4. The macros
.Fn EVP_MD_CTX_get_size
and
.Dv EVP_MD_CTX_size
were changed in OpenSSL 3.4 to be aliases for
.Fn EVP_MD_CTX_get_size_ex ,
previously they were aliases for EVP_MD_get_size which returned a
constant value.
This is required for XOF digests since they do not have a fixed size.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
