.Dd 2025-09-30
.Dt EVP_PKEY_SETTABLE_PARAMS 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_settable_params ,
.Nm EVP_PKEY_set_params ,
.Nm EVP_PKEY_set_int_param ,
.Nm EVP_PKEY_set_size_t_param ,
.Nm EVP_PKEY_set_bn_param ,
.Nm EVP_PKEY_set_utf8_string_param ,
.Nm EVP_PKEY_set_octet_string_param
.Nd set key parameters into a key
.Sh SYNOPSIS
.In openssl/evp.h
.Ft const OSSL_PARAM *
.Fo EVP_PKEY_settable_params
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft int
.Fo EVP_PKEY_set_params
.Fa "EVP_PKEY *pkey"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_PKEY_set_int_param
.Fa "EVP_PKEY *pkey"
.Fa "const char *key_name"
.Fa "int in"
.Fc
.Ft int
.Fo EVP_PKEY_set_size_t_param
.Fa "EVP_PKEY *pkey"
.Fa "const char *key_name"
.Fa "size_t in"
.Fc
.Ft int
.Fo EVP_PKEY_set_bn_param
.Fa "EVP_PKEY *pkey"
.Fa "const char *key_name"
.Fa "const BIGNUM *bn"
.Fc
.Ft int
.Fo EVP_PKEY_set_utf8_string_param
.Fa "EVP_PKEY *pkey"
.Fa "const char *key_name"
.Fa "const char *str"
.Fc
.Ft int
.Fo EVP_PKEY_set_octet_string_param
.Fa "EVP_PKEY *pkey"
.Fa "const char *key_name"
.Fa "const unsigned char *buf"
.Fa "size_t bsize"
.Fc
.Sh DESCRIPTION
These functions can be used to set additional parameters into an
existing
.Vt EVP_PKEY .
.Pp
.Fn EVP_PKEY_set_params
sets one or more
.Em params
into a
.Fa pkey .
See
.Xr OSSL_PARAM 3
for information about parameters.
.Pp
.Fn EVP_PKEY_settable_params
returns a constant list of
.Em params
indicating the names and types of key parameters that can be set.
See
.Xr OSSL_PARAM 3
for information about parameters.
.Pp
.Fn EVP_PKEY_set_int_param
sets an integer value
.Fa in
into a key
.Fa pkey
for the associated field
.Fa key_name .
.Pp
.Fn EVP_PKEY_set_size_t_param
sets an size_t value
.Fa in
into a key
.Fa pkey
for the associated field
.Fa key_name .
.Pp
.Fn EVP_PKEY_set_bn_param
sets the BIGNUM value
.Fa bn
into a key
.Fa pkey
for the associated field
.Fa key_name .
.Pp
.Fn EVP_PKEY_set_utf8_string_param
sets the UTF8 string
.Fa str
into a key
.Fa pkey
for the associated field
.Fa key_name .
.Pp
.Fn EVP_PKEY_set_octet_string_param
sets the octet string value
.Fa buf
with a size
.Fa bsize
into a key
.Fa pkey
for the associated field
.Fa key_name .
.Sh NOTES
These functions only work for
.Vt EVP_PKEY Ns s
that contain a provider side key.
.Sh RETURN VALUES
.Fn EVP_PKEY_settable_params
returns NULL on error or if it is not supported,
.Pp
All other methods return 1 if a value was successfully set, or 0 if
there was an error.
.Sh SEE ALSO
.Xr EVP_PKEY_gettable_params 3 ,
.Xr EVP_PKEY_CTX_new 3 ,
.Xr provider-keymgmt 7 ,
.Xr OSSL_PARAM 3 ,
.Sh HISTORY
These functions were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
