.Dd 2025-09-30
.Dt EVP_SIGNINIT 3ossl
.Os
.Sh NAME
.Nm EVP_SignInit ,
.Nm EVP_SignInit_ex ,
.Nm EVP_SignUpdate ,
.Nm EVP_SignFinal_ex ,
.Nm EVP_SignFinal
.Nd EVP signing functions
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_SignInit_ex
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fa "ENGINE *impl"
.Fc
.Ft int
.Fo EVP_SignUpdate
.Fa "EVP_MD_CTX *ctx"
.Fa "const void *d"
.Fa "unsigned int cnt"
.Fc
.Ft int
.Fo EVP_SignFinal_ex
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *md"
.Fa "unsigned int *s"
.Fa "EVP_PKEY *pkey"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo EVP_SignFinal
.Fa "EVP_MD_CTX *ctx"
.Fa "unsigned char *sig"
.Fa "unsigned int *s"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft void
.Fo EVP_SignInit
.Fa "EVP_MD_CTX *ctx"
.Fa "const EVP_MD *type"
.Fc
.Sh DESCRIPTION
The EVP signature routines are a high-level interface to digital
signatures.
.Pp
.Fn EVP_SignInit_ex
sets up signing context
.Fa ctx
to use digest
.Fa type
from
.Vt ENGINE
.Fa impl .
.Fa ctx
must be created with
.Xr EVP_MD_CTX_new 3
before calling this function.
.Pp
.Fn EVP_SignUpdate
hashes
.Fa cnt
bytes of data at
.Fa d
into the signature context
.Fa ctx .
This function can be called several times on the same
.Fa ctx
to include additional data.
.Pp
.Fn EVP_SignFinal_ex
signs the data in
.Fa ctx
using the private key
.Fa pkey
and places the signature in
.Fa sig .
The library context
.Fa libctx
and property query
.Fa propq
are used when creating a context to use with the key
.Fa pkey .
.Fa sig
must be at least
.Qo Li EVP_PKEY_get_size(pkey) Qc
bytes in size.
.Fa s
is an OUT parameter, and not used as an IN parameter.
The number of bytes of data written (i.e.
the length of the signature) will be written to the integer at
.Fa s ,
at most
.Qo Li EVP_PKEY_get_size(pkey) Qc
bytes will be written.
.Pp
.Fn EVP_SignFinal
is similar to
.Fn EVP_SignFinal_ex
but uses default values of NULL for the library context
.Fa libctx
and the property query
.Fa propq .
.Pp
.Fn EVP_SignInit
initializes a signing context
.Fa ctx
to use the default implementation of digest
.Fa type .
.Sh RETURN VALUES
.Fn EVP_SignInit_ex ,
.Fn EVP_SignUpdate ,
.Fn EVP_SignFinal_ex
and
.Fn EVP_SignFinal
return 1 for success and 0 for failure.
.Pp
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh NOTES
The
.Sy EVP
interface to digital signatures should almost always be used in
preference to the low-level interfaces.
This is because the code then becomes transparent to the algorithm used
and much more flexible.
.Pp
When signing with some private key types the random number generator
must be seeded.
If the automatic seeding or reseeding of the OpenSSL CSPRNG fails due to
external circumstances (see
.Xr RAND 7 Ns ),
the operation will fail.
.Pp
The call to
.Fn EVP_SignFinal
internally finalizes a copy of the digest context.
This means that calls to
.Fn EVP_SignUpdate
and
.Fn EVP_SignFinal
can be called later to digest and sign additional data.cApplications may
disable this behavior by setting the EVP_MD_CTX_FLAG_FINALISE context
flag via
.Xr EVP_MD_CTX_set_flags 3 .
.Pp
Since only a copy of the digest context is ever finalized the context
must be cleaned up after use by calling
.Xr EVP_MD_CTX_free 3
or a memory leak will occur.
.Pp
Note that not all providers support continuation, in case the selected
provider does not allow to duplicate contexts
.Fn EVP_SignFinal
will finalize the digest context and attempting to process additional
data via
.Fn EVP_SignUpdate
will result in an error.
.Sh BUGS
Older versions of this documentation wrongly stated that calls to
.Fn EVP_SignUpdate
could not be made after calling
.Fn EVP_SignFinal .
.Pp
Since the private key is passed in the call to
.Fn EVP_SignFinal
any error relating to the private key (for example an unsuitable key and
digest combination) will not be indicated until after potentially large
amounts of data have been passed through
.Fn EVP_SignUpdate .
.Pp
It is not possible to change the signing parameters using these
function.
.Pp
The previous two bugs are fixed in the newer
.Xr EVP_DigestSign* 3
functions.
.Sh SEE ALSO
.Xr EVP_PKEY_get_size 3 ,
.Xr EVP_PKEY_get_bits 3 ,
.Xr EVP_PKEY_get_security_bits 3 ,
.Xr EVP_VerifyInit 3 ,
.Xr EVP_DigestInit 3 ,
.Xr evp 7 ,
.Xr HMAC 3 ,
.Xr MD2 3 ,
.Xr MD5 3 ,
.Xr MDC2 3 ,
.Xr RIPEMD160 3 ,
.Xr SHA1 3 ,
.Xr openssl-dgst 1
.Sh HISTORY
The function
.Fn EVP_SignFinal_ex
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
