.Dd 2025-09-30
.Dt EVP_RAND 3ossl
.Os
.Sh NAME
.Nm EVP_RAND ,
.Nm EVP_RAND_fetch ,
.Nm EVP_RAND_free ,
.Nm EVP_RAND_up_ref ,
.Nm EVP_RAND_CTX ,
.Nm EVP_RAND_CTX_new ,
.Nm EVP_RAND_CTX_free ,
.Nm EVP_RAND_CTX_up_ref ,
.Nm EVP_RAND_instantiate ,
.Nm EVP_RAND_uninstantiate ,
.Nm EVP_RAND_generate ,
.Nm EVP_RAND_reseed ,
.Nm EVP_RAND_nonce ,
.Nm EVP_RAND_enable_locking ,
.Nm EVP_RAND_verify_zeroization ,
.Nm EVP_RAND_get_strength ,
.Nm EVP_RAND_get_state ,
.Nm EVP_RAND_get0_provider ,
.Nm EVP_RAND_CTX_get0_rand ,
.Nm EVP_RAND_is_a ,
.Nm EVP_RAND_get0_name ,
.Nm EVP_RAND_names_do_all ,
.Nm EVP_RAND_get0_description ,
.Nm EVP_RAND_CTX_get_params ,
.Nm EVP_RAND_CTX_set_params ,
.Nm EVP_RAND_do_all_provided ,
.Nm EVP_RAND_get_params ,
.Nm EVP_RAND_gettable_ctx_params ,
.Nm EVP_RAND_settable_ctx_params ,
.Nm EVP_RAND_CTX_gettable_params ,
.Nm EVP_RAND_CTX_settable_params ,
.Nm EVP_RAND_gettable_params ,
.Nm EVP_RAND_STATE_UNINITIALISED ,
.Nm EVP_RAND_STATE_READY ,
.Nm EVP_RAND_STATE_ERROR
.Nd EVP RAND routines
.Sh SYNOPSIS
.In openssl/evp.h
.Ft typedef struct evp_rand_st EVP_RAND;
 typedef struct evp_rand_ctx_st EVP_RAND_CTX;

 EVP_RAND *
.Fo EVP_RAND_fetch
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *algorithm"
.Fa "const char *properties"
.Fc
.Ft int
.Fo EVP_RAND_up_ref
.Fa "EVP_RAND *rand"
.Fc
.Ft void
.Fo EVP_RAND_free
.Fa "EVP_RAND *rand"
.Fc
.Ft EVP_RAND_CTX *
.Fo EVP_RAND_CTX_new
.Fa "EVP_RAND *rand"
.Fa "EVP_RAND_CTX *parent"
.Fc
.Ft void
.Fo EVP_RAND_CTX_free
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft int
.Fo EVP_RAND_CTX_up_ref
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft EVP_RAND *
.Fo EVP_RAND_CTX_get0_rand
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft int
.Fo EVP_RAND_get_params
.Fa "EVP_RAND *rand"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_RAND_CTX_get_params
.Fa "EVP_RAND_CTX *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_RAND_CTX_set_params
.Fa "EVP_RAND_CTX *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_RAND_gettable_params
.Fa "const EVP_RAND *rand"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_RAND_gettable_ctx_params
.Fa "const EVP_RAND *rand"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_RAND_settable_ctx_params
.Fa "const EVP_RAND *rand"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_RAND_CTX_gettable_params
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_RAND_CTX_settable_params
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft const char *
.Fo EVP_RAND_get0_name
.Fa "const EVP_RAND *rand"
.Fc
.Ft const char *
.Fo EVP_RAND_get0_description
.Fa "const EVP_RAND *rand"
.Fc
.Ft int
.Fo EVP_RAND_is_a
.Fa "const EVP_RAND *rand"
.Fa "const char *name"
.Fc
.Ft const OSSL_PROVIDER *
.Fo EVP_RAND_get0_provider
.Fa "const EVP_RAND *rand"
.Fc
.Ft void
.Fo EVP_RAND_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*fn)(EVP_RAND *rand"
.Fa "void *arg)"
.Fa "void *arg"
.Fc
.Ft int
.Fo EVP_RAND_names_do_all
.Fa "const EVP_RAND *rand"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
.Ft int
.Fo EVP_RAND_instantiate
.Fa "EVP_RAND_CTX *ctx"
.Fa "unsigned int strength"
.Fa "int prediction_resistance"
.Fa "const unsigned char *pstr"
.Fa "size_t pstr_len"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo EVP_RAND_uninstantiate
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft int
.Fo EVP_RAND_generate
.Fa "EVP_RAND_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t outlen"
.Fa "unsigned int strength"
.Fa "int prediction_resistance"
.Fa "const unsigned char *addin"
.Fa "size_t addin_len"
.Fc
.Ft int
.Fo EVP_RAND_reseed
.Fa "EVP_RAND_CTX *ctx"
.Fa "int prediction_resistance"
.Fa "const unsigned char *ent"
.Fa "size_t ent_len"
.Fa "const unsigned char *addin"
.Fa "size_t addin_len"
.Fc
.Ft int
.Fo EVP_RAND_nonce
.Fa "EVP_RAND_CTX *ctx"
.Fa "unsigned char *out"
.Fa "size_t outlen"
.Fc
.Ft int
.Fo EVP_RAND_enable_locking
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft int
.Fo EVP_RAND_verify_zeroization
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft unsigned int
.Fo EVP_RAND_get_strength
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Ft int
.Fo EVP_RAND_get_state
.Fa "EVP_RAND_CTX *ctx"
.Fc
.Fd #define EVP_RAND_STATE_UNINITIALISED    0
.Fd #define EVP_RAND_STATE_READY            1
.Fd #define EVP_RAND_STATE_ERROR            2
.Sh DESCRIPTION
The EVP RAND routines are a high-level interface to random number
generators both deterministic and not.
If you just want to generate random bytes then you don't need to use
these functions: just call
.Xr RAND_bytes 3
or
.Xr RAND_priv_bytes 3 .
If you want to do more, these calls should be used instead of the older
RAND and RAND_DRBG functions.
.Pp
After creating a
.Vt EVP_RAND_CTX
for the required algorithm using
.Fn EVP_RAND_CTX_new ,
inputs to the algorithm are supplied either by passing them as part of
the
.Fn EVP_RAND_instantiate
call or using calls to
.Fn EVP_RAND_CTX_set_params
before calling
.Fn EVP_RAND_instantiate .
Finally, call
.Fn EVP_RAND_generate
to produce cryptographically secure random bytes.
.Ss Types
.Vt EVP_RAND
is a type that holds the implementation of a RAND.
.Pp
.Vt EVP_RAND_CTX
is a context type that holds the algorithm inputs.
.Vt EVP_RAND_CTX
structures are reference counted.
.Ss Algorithm implementation fetching
.Fn EVP_RAND_fetch
fetches an implementation of a RAND
.Fa algorithm ,
given a library context
.Fa libctx
and a set of
.Fa properties .
See
.Xr crypto 7
for further information.
.Pp
The returned value must eventually be freed with
.Xr EVP_RAND_free 3 .
.Pp
.Fn EVP_RAND_up_ref
increments the reference count of an already fetched RAND.
.Pp
.Fn EVP_RAND_free
frees a fetched algorithm.
NULL is a valid parameter, for which this function is a no-op.
.Ss Context manipulation functions
.Fn EVP_RAND_CTX_new
creates a new context for the RAND implementation
.Fa rand .
If not NULL,
.Fa parent
specifies the seed source for this implementation.
Not all random number generators need to have a seed source specified.
If a parent is required, a NULL
.Fa parent
will utilise the operating system entropy sources.
It is recommended to minimise the number of random number generators
that rely on the operating system for their randomness because this is
often scarce.
.Pp
.Fn EVP_RAND_CTX_free
frees up the context
.Fa ctx .
If
.Fa ctx
is NULL, nothing is done.
.Pp
.Fn EVP_RAND_CTX_get0_rand
returns the
.Vt EVP_RAND
associated with the context
.Fa ctx .
.Ss Random Number Generator Functions
.Fn EVP_RAND_instantiate
processes any parameters in
.Em params
and then instantiates the RAND
.Fa ctx
with a minimum security strength of <strength> and personalisation
string
.Fa pstr
of length <pstr_len>. If
.Fa prediction_resistance
is specified, fresh entropy from a live source will be sought.
This call operates as per NIST SP 800-90A and SP 800-90C.
.Pp
.Fn EVP_RAND_uninstantiate
uninstantiates the RAND
.Fa ctx
as per NIST SP 800-90A and SP 800-90C. Subsequent to this call, the RAND
cannot be used to generate bytes.
It can only be freed or instantiated again.
.Pp
.Fn EVP_RAND_generate
produces random bytes from the RAND
.Fa ctx
with the additional input
.Fa addin
of length
.Fa addin_len .
The bytes produced will meet the security
.Fa strength .
If
.Fa prediction_resistance
is specified, fresh entropy from a live source will be sought.
This call operates as per NIST SP 800-90A and SP 800-90C.
.Pp
.Fn EVP_RAND_reseed
reseeds the RAND with new entropy.
Entropy
.Fa ent
of length
.Fa ent_len
bytes can be supplied as can additional input
.Fa addin
of length
.Fa addin_len
bytes.
In the FIPS provider, both are treated as additional input as per NIST
SP-800-90Ar1, Sections 9.1 and 9.2. Additional seed material is also
drawn from the RAND's parent or the operating system.
If
.Fa prediction_resistance
is specified, fresh entropy from a live source will be sought.
This call operates as per NIST SP 800-90A and SP 800-90C.
.Pp
.Fn EVP_RAND_nonce
creates a nonce in
.Fa out
of length
.Fa outlen
bytes from the RAND
.Fa ctx .
.Pp
.Fn EVP_RAND_enable_locking
enables locking for the RAND
.Fa ctx
and all of its parents.
After this
.Fa ctx
will operate in a thread safe manner, albeit more slowly.
This function is not itself thread safe if called with the same
.Fa ctx
from multiple threads.
Typically locking should be enabled before a
.Fa ctx
is shared across multiple threads.
.Pp
.Fn EVP_RAND_get_params
retrieves details about the implementation
.Fa rand .
The set of parameters given with
.Em params
determine exactly what parameters should be retrieved.
Note that a parameter that is unknown in the underlying context is
simply ignored.
.Pp
.Fn EVP_RAND_CTX_get_params
retrieves chosen parameters, given the context
.Fa ctx
and its underlying context.
The set of parameters given with
.Em params
determine exactly what parameters should be retrieved.
Note that a parameter that is unknown in the underlying context is
simply ignored.
.Pp
.Fn EVP_RAND_CTX_set_params
passes chosen parameters to the underlying context, given a context
.Fa ctx .
The set of parameters given with
.Em params
determine exactly what parameters are passed down.
Note that a parameter that is unknown in the underlying context is
simply ignored.
Also, what happens when a needed parameter isn't passed down is defined
by the implementation.
.Pp
.Fn EVP_RAND_gettable_params
returns an
.Xr OSSL_PARAM 3
array that describes the retrievable and settable parameters.
.Fn EVP_RAND_gettable_params
returns parameters that can be used with
.Fn EVP_RAND_get_params .
.Pp
.Fn EVP_RAND_gettable_ctx_params
and
.Fn EVP_RAND_CTX_gettable_params
return constant
.Xr OSSL_PARAM 3
arrays that describe the retrievable parameters that can be used with
.Fn EVP_RAND_CTX_get_params .
.Fn EVP_RAND_gettable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_RAND_CTX_gettable_params
returns the parameters that can be retrieved in the context's current
state.
.Pp
.Fn EVP_RAND_settable_ctx_params
and
.Fn EVP_RAND_CTX_settable_params
return constant
.Xr OSSL_PARAM 3
arrays that describe the settable parameters that can be used with
.Fn EVP_RAND_CTX_set_params .
.Fn EVP_RAND_settable_ctx_params
returns the parameters that can be retrieved from the algorithm, whereas
.Fn EVP_RAND_CTX_settable_params
returns the parameters that can be retrieved in the context's current
state.
.Ss Information functions
.Fn EVP_RAND_get_strength
returns the security strength of the RAND
.Fa ctx .
.Pp
.Fn EVP_RAND_get_state
returns the current state of the RAND
.Fa ctx .
States defined by the OpenSSL RNGs are:
.Bl -bullet
.It
.Dv EVP_RAND_STATE_UNINITIALISED :
this RNG is currently uninitialised.
The instantiate call will change this to the ready state.
.It
.Dv EVP_RAND_STATE_READY :
this RNG is currently ready to generate output.
.It
.Dv EVP_RAND_STATE_ERROR :
this RNG is in an error state.
.El
.Pp
.Fn EVP_RAND_is_a
returns 1 if
.Fa rand
is an implementation of an algorithm that's identifiable with
.Fa name ,
otherwise 0.
.Pp
.Fn EVP_RAND_get0_provider
returns the provider that holds the implementation of the given
.Fa rand .
.Pp
.Fn EVP_RAND_do_all_provided
traverses all RAND implemented by all activated providers in the given
library context
.Fa libctx ,
and for each of the implementations, calls the given function
.Em fn
with the implementation method and the given
.Fa arg
as argument.
.Pp
.Fn EVP_RAND_get0_name
returns the canonical name of
.Fa rand .
.Pp
.Fn EVP_RAND_names_do_all
traverses all names for
.Fa rand ,
and calls
.Em fn
with each name and
.Fa data .
.Pp
.Fn EVP_RAND_get0_description
returns a description of the rand, meant for display and human
consumption.
The description is at the discretion of the rand implementation.
.Pp
.Fn EVP_RAND_verify_zeroization
confirms if the internal DRBG state is currently zeroed.
This is used by the FIPS provider to support the mandatory self tests.
.Sh PARAMETERS
The standard parameter names are:
.Bl -tag -width Ds
.It \(dqstate" ( Ns Sy OSSL_RAND_PARAM_STATE Ns ) <integer>
Returns the state of the random number generator.
.It \(dqstrength" ( Ns Sy OSSL_RAND_PARAM_STRENGTH Ns ) <unsigned integer>
Returns the bit strength of the random number generator.
.It \(dqfips-indicator" ( Ns Sy OSSL_RAND_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This option is used by the OpenSSL FIPS provider and is not supported by
all EVP_RAND sources.
.El
.Pp
For rands that are also deterministic random bit generators (DRBGs),
these additional parameters are recognised.
Not all parameters are relevant to, or are understood by all DRBG rands:
.Bl -tag -width Ds
.It \(dqreseed_requests" ( Ns Sy OSSL_DRBG_PARAM_RESEED_REQUESTS Ns ) <unsigned integer>
Reads or set the number of generate requests before reseeding the
associated RAND ctx.
.It \(dqreseed_time_interval" ( Ns Sy OSSL_DRBG_PARAM_RESEED_TIME_INTERVAL Ns ) <integer>
Reads or set the number of elapsed seconds before reseeding the
associated RAND ctx.
.It \(dqmax_request" ( Ns Sy OSSL_RAND_PARAM_MAX_REQUEST Ns ) <unsigned integer>
Specifies the maximum number of bytes that can be generated in a single
call to OSSL_FUNC_rand_generate.
.It \(dqmin_entropylen" ( Ns Sy OSSL_DRBG_PARAM_MIN_ENTROPYLEN Ns ) <unsigned integer>
.It \(dqmax_entropylen" ( Ns Sy OSSL_DRBG_PARAM_MAX_ENTROPYLEN Ns ) <unsigned integer>
Specify the minimum and maximum number of bytes of random material that
can be used to seed the DRBG.
.It \(dqmin_noncelen" ( Ns Sy OSSL_DRBG_PARAM_MIN_NONCELEN Ns ) <unsigned integer>
.It \(dqmax_noncelen" ( Ns Sy OSSL_DRBG_PARAM_MAX_NONCELEN Ns ) <unsigned integer>
Specify the minimum and maximum number of bytes of nonce that can be
used to seed the DRBG.
.It \(dqmax_perslen" ( Ns Sy OSSL_DRBG_PARAM_MAX_PERSLEN Ns ) <unsigned integer>
.It \(dqmax_adinlen" ( Ns Sy OSSL_DRBG_PARAM_MAX_ADINLEN Ns ) <unsigned integer>
Specify the minimum and maximum number of bytes of personalisation
string that can be used with the DRBG.
.It \(dqreseed_counter" ( Ns Sy OSSL_DRBG_PARAM_RESEED_COUNTER Ns ) <unsigned integer>
Specifies the number of times the DRBG has been seeded or reseeded.
.It \(dqproperties" ( Ns Sy OSSL_RAND_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqmac" ( Ns Sy OSSL_RAND_PARAM_MAC Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_RAND_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqcipher" ( Ns Sy OSSL_RAND_PARAM_CIPHER Ns ) <UTF8 string>
For RAND implementations that use an underlying computation MAC, digest
or cipher, these parameters set what the algorithm should be.
.Pp
The value is always the name of the intended algorithm, or the
properties in the case of
.Sy OSSL_RAND_PARAM_PROPERTIES .
.El
.Sh NOTES
The use of a nonzero value for the
.Fa prediction_resistance
argument to
.Fn EVP_RAND_instantiate ,
.Fn EVP_RAND_generate
or
.Fn EVP_RAND_reseed
should be used sparingly.
In the default setup, this will cause all public and private DRBGs to be
reseeded on next use.
Since, by default, public and private DRBGs are allocated on a per
thread basis, this can result in significant overhead for highly
multi-threaded applications.
For normal use-cases, the default "reseed_requests" and
"reseed_time_interval" thresholds ensure sufficient prediction
resistance over time and you can reduce those values if you think they
are too high.
Explicitly requesting prediction resistance is intended for more special
use-cases like generating long-term secrets.
.Pp
An
.Vt EVP_RAND_CTX
needs to have locking enabled if it acts as the parent of more than one
child and the children can be accessed concurrently.
This must be done by explicitly calling
.Fn EVP_RAND_enable_locking .
.Pp
The RAND life-cycle is described in
.Xr life_cycle-rand 7 .
In the future, the transitions described there will be enforced.
When this is done, it will not be considered a breaking change to the
API.
.Sh RETURN VALUES
.Fn EVP_RAND_fetch
returns a pointer to a newly fetched
.Vt EVP_RAND ,
or NULL if allocation failed.
.Pp
.Fn EVP_RAND_get0_provider
returns a pointer to the provider for the RAND, or NULL on error.
.Pp
.Fn EVP_RAND_CTX_get0_rand
returns a pointer to the
.Vt EVP_RAND
associated with the context.
.Pp
.Fn EVP_RAND_get0_name
returns the name of the random number generation algorithm.
.Pp
.Fn EVP_RAND_up_ref
returns 1 on success, 0 on error.
.Pp
.Fn EVP_RAND_names_do_all
returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.Pp
.Fn EVP_RAND_CTX_new
returns either the newly allocated
.Vt EVP_RAND_CTX
structure or NULL if an error occurred.
.Pp
.Fn EVP_RAND_CTX_free
does not return a value.
.Pp
.Fn EVP_RAND_CTX_up_ref
returns 1 on success, 0 on error.
.Pp
.Fn EVP_RAND_nonce
returns 1 on success, 0 on error.
.Pp
.Fn EVP_RAND_get_strength
returns the strength of the random number generator in bits.
.Pp
.Fn EVP_RAND_gettable_params ,
.Fn EVP_RAND_gettable_ctx_params
and
.Fn EVP_RAND_settable_ctx_params
return an array of OSSL_PARAMs.
.Pp
.Fn EVP_RAND_verify_zeroization
returns 1 if the internal DRBG state is currently zeroed, and 0 if not.
.Pp
The remaining functions return 1 for success and 0 or a negative value
for failure.
.Sh SEE ALSO
.Xr RAND_bytes 3 ,
.Xr EVP_RAND-CTR-DRBG 7 ,
.Xr EVP_RAND-HASH-DRBG 7 ,
.Xr EVP_RAND-HMAC-DRBG 7 ,
.Xr EVP_RAND-TEST-RAND 7 ,
.Xr provider-rand 7 ,
.Xr life_cycle-rand 7
.Sh HISTORY
.Fn EVP_RAND_CTX_up_ref
was added in OpenSSL 3.1.
.Pp
The remaining functions were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
