.Dd 2025-09-30
.Dt EVP_PKEY_GET_SIZE 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_get_size ,
.Nm EVP_PKEY_get_bits ,
.Nm EVP_PKEY_get_security_bits ,
.Nm EVP_PKEY_bits ,
.Nm EVP_PKEY_security_bits ,
.Nm EVP_PKEY_size
.Nd EVP_PKEY information functions
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_get_size
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft int
.Fo EVP_PKEY_get_bits
.Fa "const EVP_PKEY *pkey"
.Fc
.Ft int
.Fo EVP_PKEY_get_security_bits
.Fa "const EVP_PKEY *pkey"
.Fc
.Fd #define EVP_PKEY_bits EVP_PKEY_get_bits
.Fd #define EVP_PKEY_security_bits EVP_PKEY_get_security_bits
.Fd #define EVP_PKEY_size EVP_PKEY_get_size
.Sh DESCRIPTION
.Fn EVP_PKEY_get_size
returns the maximum suitable size for the output buffers for almost all
operations that can be done with
.Fa pkey .
This corresponds to the provider parameter
.Sy OSSL_PKEY_PARAM_MAX_SIZE .
The primary documented use is with
.Xr EVP_SignFinal 3
and
.Xr EVP_SealInit 3 ,
but it isn't limited there.
The returned size is also large enough for the output buffer of
.Xr EVP_PKEY_sign 3 ,
.Xr EVP_PKEY_encrypt 3 ,
.Xr EVP_PKEY_decrypt 3 ,
.Xr EVP_PKEY_derive 3 .
.Pp
It must be stressed that, unless the documentation for the operation
that's being performed says otherwise, the size returned by
.Fn EVP_PKEY_get_size
is only preliminary and not exact, so the final contents of the target
buffer may be smaller.
It is therefore crucial to take note of the size given back by the
function that performs the operation, such as
.Xr EVP_PKEY_sign 3
(the
.Em siglen
argument will receive that length), to avoid bugs.
.Pp
.Fn EVP_PKEY_get_bits
returns the cryptographic length of the cryptosystem to which the key in
.Fa pkey
belongs, in bits.
Note that the definition of cryptographic length is specific to the key
cryptosystem.
This length corresponds to the provider parameter
.Sy OSSL_PKEY_PARAM_BITS .
.Pp
.Fn EVP_PKEY_get_security_bits
returns the number of security bits of the given
.Fa pkey ,
bits of security is defined in NIST SP800-57. This corresponds to the
provider parameter
.Sy OSSL_PKEY_PARAM_SECURITY_BITS .
.Sh RETURN VALUES
.Fn EVP_PKEY_get_size ,
.Fn EVP_PKEY_get_bits
and
.Fn EVP_PKEY_get_security_bits
return a positive number, or 0 if this size isn't available.
.Sh NOTES
Most functions that have an output buffer and are mentioned with
.Fn EVP_PKEY_get_size
have a functionality where you can pass NULL for the buffer and still
pass a pointer to an integer and get the exact size that this function
call delivers in the context that it's called in.
This allows those functions to be called twice, once to find out the
exact buffer size, then allocate the buffer in between, and call that
function again actually output the data.
For those functions, it isn't strictly necessary to call
.Fn EVP_PKEY_get_size
to find out the buffer size, but may be useful in cases where it's
desirable to know the upper limit in advance.
.Pp
It should also be especially noted that
.Fn EVP_PKEY_get_size
shouldn't be used to get the output size for
.Xr EVP_DigestSignFinal 3 ,
according to
.Xr EVP_DigestSignFinal 3 .
.Sh SEE ALSO
.Xr provider-keymgmt 7 ,
.Xr EVP_SignFinal 3 ,
.Xr EVP_SealInit 3 ,
.Xr EVP_PKEY_sign 3 ,
.Xr EVP_PKEY_encrypt 3 ,
.Xr EVP_PKEY_decrypt 3 ,
.Xr EVP_PKEY_derive 3
.Sh HISTORY
The
.Fn EVP_PKEY_bits ,
.Fn EVP_PKEY_security_bits ,
and
.Fn EVP_PKEY_size
functions were renamed to include
.Qo Li get Qc
in their names in OpenSSL 3.0, respectively.
The old names are kept as non-deprecated alias macros.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
