.Dd 2025-09-30
.Dt EVP_PKEY_GET_DEFAULT_DIGEST_NID 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_get_default_digest_nid ,
.Nm EVP_PKEY_get_default_digest_name
.Nd get default signature digest
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_get_default_digest_name
.Fa "EVP_PKEY *pkey"
.Fa "char *mdname"
.Fa "size_t mdname_sz"
.Fc
.Ft int
.Fo EVP_PKEY_get_default_digest_nid
.Fa "EVP_PKEY *pkey"
.Fa "int *pnid"
.Fc
.Sh DESCRIPTION
.Fn EVP_PKEY_get_default_digest_name
fills in the default message digest name for the public key signature
operations associated with key
.Fa pkey
into
.Fa mdname ,
up to at most
.Fa mdname_sz
bytes including the ending NUL byte.
The name could be
.Qo Li \(dqUNDEF" Qc ,
signifying that a digest must (for return value 2) or may (for return
value 1) be left unspecified.
.Pp
.Fn EVP_PKEY_get_default_digest_nid
sets
.Fa pnid
to the default message digest NID for the public key signature
operations associated with key
.Fa pkey .
Note that some signature algorithms (i.e.
Ed25519 and Ed448) do not use a digest during signing.
In this case
.Fa pnid
will be set to NID_undef.
This function is only reliable for legacy keys, which are keys with a
.Sy EVP_PKEY_ASN1_METHOD ;
these keys have typically been loaded from engines, or created with
.Xr EVP_PKEY_assign_RSA 3
or similar.
.Sh NOTES
For all current standard OpenSSL public key algorithms SHA256 is
returned.
.Sh RETURN VALUES
.Fn EVP_PKEY_get_default_digest_name
and
.Fn EVP_PKEY_get_default_digest_nid
both return 1 if the message digest is advisory (that is other digests
can be used) and 2 if it is mandatory (other digests can not be used).
They return 0 or a negative value for failure.
In particular a return value of -2 indicates the operation is not
supported by the public key algorithm.
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_sign 3 ,
.Xr EVP_PKEY_digestsign_supports_digest 3 ,
.Xr EVP_PKEY_verify 3 ,
.Xr EVP_PKEY_verify_recover 3 ,
.Sh HISTORY
This function was added in OpenSSL 1.0.0.
.Sh COPYRIGHT
Copyright 2006-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
