.Dd 2025-09-30
.Dt EVP_MD_METH_NEW 3ossl
.Os
.Sh NAME
.Nm EVP_MD_meth_new ,
.Nm EVP_MD_meth_dup ,
.Nm EVP_MD_meth_free ,
.Nm EVP_MD_meth_set_input_blocksize ,
.Nm EVP_MD_meth_set_result_size ,
.Nm EVP_MD_meth_set_app_datasize ,
.Nm EVP_MD_meth_set_flags ,
.Nm EVP_MD_meth_set_init ,
.Nm EVP_MD_meth_set_update ,
.Nm EVP_MD_meth_set_final ,
.Nm EVP_MD_meth_set_copy ,
.Nm EVP_MD_meth_set_cleanup ,
.Nm EVP_MD_meth_set_ctrl ,
.Nm EVP_MD_meth_get_input_blocksize ,
.Nm EVP_MD_meth_get_result_size ,
.Nm EVP_MD_meth_get_app_datasize ,
.Nm EVP_MD_meth_get_flags ,
.Nm EVP_MD_meth_get_init ,
.Nm EVP_MD_meth_get_update ,
.Nm EVP_MD_meth_get_final ,
.Nm EVP_MD_meth_get_copy ,
.Nm EVP_MD_meth_get_cleanup ,
.Nm EVP_MD_meth_get_ctrl
.Nd Routines to build up legacy EVP_MD methods
.Sh SYNOPSIS
.In openssl/evp.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft EVP_MD *
.Fo EVP_MD_meth_new
.Fa "int md_type"
.Fa "int pkey_type"
.Fc
.Ft void
.Fo EVP_MD_meth_free
.Fa "EVP_MD *md"
.Fc
.Ft EVP_MD *
.Fo EVP_MD_meth_dup
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_meth_set_input_blocksize
.Fa "EVP_MD *md"
.Fa "int blocksize"
.Fc
.Ft int
.Fo EVP_MD_meth_set_result_size
.Fa "EVP_MD *md"
.Fa "int resultsize"
.Fc
.Ft int
.Fo EVP_MD_meth_set_app_datasize
.Fa "EVP_MD *md"
.Fa "int datasize"
.Fc
.Ft int
.Fo EVP_MD_meth_set_flags
.Fa "EVP_MD *md"
.Fa "unsigned long flags"
.Fc
.Ft int
.Fo EVP_MD_meth_set_init
.Fa "EVP_MD *md"
.Fa "int (*init)(EVP_MD_CTX *ctx)"
.Fc
.Ft int
.Fo EVP_MD_meth_set_update
.Fa "EVP_MD *md"
.Fa "int (*update)(EVP_MD_CTX *ctx"
.Fa "const void *data"
.Fa "size_t count)"
.Fc
.Ft int
.Fo EVP_MD_meth_set_final
.Fa "EVP_MD *md"
.Fa "int (*final)(EVP_MD_CTX *ctx"
.Fa "unsigned char *md)"
.Fc
.Ft int
.Fo EVP_MD_meth_set_copy
.Fa "EVP_MD *md"
.Fa "int (*copy)(EVP_MD_CTX *to"
.Fa "const EVP_MD_CTX *from)"
.Fc
.Ft int
.Fo EVP_MD_meth_set_cleanup
.Fa "EVP_MD *md"
.Fa "int (*cleanup)(EVP_MD_CTX *ctx)"
.Fc
.Ft int
.Fo EVP_MD_meth_set_ctrl
.Fa "EVP_MD *md"
.Fa "int (*ctrl)(EVP_MD_CTX *ctx"
.Fa "int cmd"
.Fa "int p1"
.Fa "void *p2)"
.Fc
.Ft int
.Fo EVP_MD_meth_get_input_blocksize
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_meth_get_result_size
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_MD_meth_get_app_datasize
.Fa "const EVP_MD *md"
.Fc
.Ft unsigned long
.Fo EVP_MD_meth_get_flags
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo 
.Fa "*EVP_MD_meth_get_init(const EVP_MD *md)"
.Fc
(EVP_MD_CTX *ctx);
.Ft int
.Fo 
.Fa "*EVP_MD_meth_get_update(const EVP_MD *md)"
.Fc
(EVP_MD_CTX *ctx,
.Bd -literal
                                                 const void *data,
                                                 size_t count);
 int (*EVP_MD_meth_get_final(const EVP_MD *md))(EVP_MD_CTX *ctx,
                                                unsigned char *md);
 int (*EVP_MD_meth_get_copy(const EVP_MD *md))(EVP_MD_CTX *to,
                                               const EVP_MD_CTX *from);
 int (*EVP_MD_meth_get_cleanup(const EVP_MD *md))(EVP_MD_CTX *ctx);
 int (*EVP_MD_meth_get_ctrl(const EVP_MD *md))(EVP_MD_CTX *ctx, int cmd,
                                               int p1, void *p2);
.Ed
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the OSSL_PROVIDER APIs.
.Pp
The
.Vt EVP_MD
type is a structure for digest method implementation.
It can also have associated public/private key signing and verifying
routines.
.Pp
.Fn EVP_MD_meth_new
creates a new
.Vt EVP_MD
structure.
These
.Vt EVP_MD
structures are reference counted.
.Pp
.Fn EVP_MD_meth_dup
creates a copy of
.Fa md .
.Pp
.Fn EVP_MD_meth_free
decrements the reference count for the
.Vt EVP_MD
structure.
If the reference count drops to 0 then the structure is freed.
If the argument is NULL, nothing is done.
.Pp
.Fn EVP_MD_meth_set_input_blocksize
sets the internal input block size for the method
.Fa md
to
.Fa blocksize
bytes.
.Pp
.Fn EVP_MD_meth_set_result_size
sets the size of the result that the digest method in
.Fa md
is expected to produce to
.Fa resultsize
bytes.
.Pp
The digest method may have its own private data, which OpenSSL will
allocate for it.
.Fn EVP_MD_meth_set_app_datasize
should be used to set the size for it to
.Fa datasize .
.Pp
.Fn EVP_MD_meth_set_flags
sets the flags to describe optional behaviours in the particular
.Fa md .
Several flags can be or'd together.
The available flags are:
.Bl -tag -width Ds
.It EVP_MD_FLAG_ONESHOT
This digest method can only handle one block of input.
.It EVP_MD_FLAG_XOF
This digest method is an extensible-output function (XOF) and supports
the
.Sy EVP_MD_CTRL_XOF_LEN
control.
.It EVP_MD_FLAG_DIGALGID_NULL
When setting up a DigestAlgorithmIdentifier, this flag will have the
parameter set to NULL by default.
Use this for PKCS#1.
.Em Note: if combined with EVP_MD_FLAG_DIGALGID_ABSENT, the latter will override.
.It EVP_MD_FLAG_DIGALGID_ABSENT
When setting up a DigestAlgorithmIdentifier, this flag will have the
parameter be left absent by default.
.Em Note: if combined with EVP_MD_FLAG_DIGALGID_NULL, the latter will be overridden.
.It EVP_MD_FLAG_DIGALGID_CUSTOM
Custom DigestAlgorithmIdentifier handling via ctrl, with
.Sy EVP_MD_FLAG_DIGALGID_ABSENT
as default.
.Em Note: if combined with EVP_MD_FLAG_DIGALGID_NULL, the latter will be overridden.
Currently unused.
.It EVP_MD_FLAG_FIPS
This digest method is suitable for use in FIPS mode.
Currently unused.
.El
.Pp
.Fn EVP_MD_meth_set_init
sets the digest init function for
.Fa md .
The digest init function is called by
.Xr EVP_Digest 3 ,
.Xr EVP_DigestInit 3 ,
.Xr EVP_DigestInit_ex 3 ,
EVP_SignInit,
.Xr EVP_SignInit_ex 3 ,
.Xr EVP_VerifyInit 3
and
.Xr EVP_VerifyInit_ex 3 .
.Pp
.Fn EVP_MD_meth_set_update
sets the digest update function for
.Fa md .
The digest update function is called by
.Xr EVP_Digest 3 ,
.Xr EVP_DigestUpdate 3
and
.Xr EVP_SignUpdate 3 .
.Pp
.Fn EVP_MD_meth_set_final
sets the digest final function for
.Fa md .
The digest final function is called by
.Xr EVP_Digest 3 ,
.Xr EVP_DigestFinal 3 ,
.Xr EVP_DigestFinal_ex 3 ,
.Xr EVP_SignFinal 3
and
.Xr EVP_VerifyFinal 3 .
.Pp
.Fn EVP_MD_meth_set_copy
sets the function for
.Fa md
to do extra computations after the method's private data structure has
been copied from one
.Sy EVP_MD_CTX
to another.
If all that's needed is to copy the data, there is no need for this copy
function.
Note that the copy function is passed two
.Sy EVP_MD_CTX * ,
the private data structure is then available with
.Xr EVP_MD_CTX_get0_md_data 3 .
This copy function is called by
.Xr EVP_MD_CTX_copy 3
and
.Xr EVP_MD_CTX_copy_ex 3 .
.Pp
.Fn EVP_MD_meth_set_cleanup
sets the function for
.Fa md
to do extra cleanup before the method's private data structure is
cleaned out and freed.
Note that the cleanup function is passed a
.Sy EVP_MD_CTX * ,
the private data structure is then available with
.Xr EVP_MD_CTX_get0_md_data 3 .
This cleanup function is called by
.Xr EVP_MD_CTX_reset 3
and
.Xr EVP_MD_CTX_free 3 .
.Pp
.Fn EVP_MD_meth_set_ctrl
sets the control function for
.Fa md .
See
.Xr EVP_MD_CTX_ctrl 3
for the available controls.
.Pp
.Fn EVP_MD_meth_get_input_blocksize ,
.Fn EVP_MD_meth_get_result_size ,
.Fn EVP_MD_meth_get_app_datasize ,
.Fn EVP_MD_meth_get_flags ,
.Xr EVP_MD_meth_get_init 3 ,
.Xr EVP_MD_meth_get_update 3 ,
.Xr EVP_MD_meth_get_final 3 ,
.Xr EVP_MD_meth_get_copy 3 ,
.Xr EVP_MD_meth_get_cleanup 3
and
.Xr EVP_MD_meth_get_ctrl 3
are all used to retrieve the method data given with the
.Xr EVP_MD_meth_set_* 3
functions above.
.Sh RETURN VALUES
.Fn EVP_MD_meth_new
and
.Fn EVP_MD_meth_dup
return a pointer to a newly created
.Vt EVP_MD ,
or NULL on failure.
All
.Xr EVP_MD_meth_set_* 3
functions return 1.
.Xr EVP_MD_get_input_blocksize 3 ,
.Fn EVP_MD_meth_get_result_size ,
.Fn EVP_MD_meth_get_app_datasize
and
.Fn EVP_MD_meth_get_flags
return the indicated sizes or flags.
All other
.Xr EVP_CIPHER_meth_get_* 3
functions return pointers to their respective
.Fa md
function.
.Sh SEE ALSO
.Xr EVP_DigestInit 3 ,
.Xr EVP_SignInit 3 ,
.Xr EVP_VerifyInit 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
The
.Vt EVP_MD
structure was openly available in OpenSSL before version 1.1. The
functions described here were added in OpenSSL 1.1. The
.Vt EVP_MD
structure created with these functions became reference counted in
OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2015-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
