.Dd 2025-09-30
.Dt EVP_PKEY_ASN1_GET_COUNT 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_asn1_find ,
.Nm EVP_PKEY_asn1_find_str ,
.Nm EVP_PKEY_asn1_get_count ,
.Nm EVP_PKEY_asn1_get0 ,
.Nm EVP_PKEY_asn1_get0_info
.Nd enumerate public key ASN.1 methods
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_asn1_get_count
.Fa void
.Fc
.Ft const EVP_PKEY_ASN1_METHOD *
.Fo EVP_PKEY_asn1_get0
.Fa "int idx"
.Fc
.Ft const EVP_PKEY_ASN1_METHOD *
.Fo EVP_PKEY_asn1_find
.Fa "ENGINE **pe"
.Fa "int type"
.Fc
.Ft const EVP_PKEY_ASN1_METHOD *
.Fo EVP_PKEY_asn1_find_str
.Fa "ENGINE **pe"
.Fa "const char *str"
.Fa "int len"
.Fc
.Ft int
.Fo EVP_PKEY_asn1_get0_info
.Fa "int *ppkey_id"
.Fa "int *pkey_base_id"
.Fa "int *ppkey_flags"
.Fa "const char **pinfo"
.Fa "const char **ppem_str"
.Fa "const EVP_PKEY_ASN1_METHOD *ameth"
.Fc
.Sh DESCRIPTION
.Xr EVP_PKEY_asn1_count 3
returns a count of the number of public key ASN.1 methods available: it
includes standard methods and any methods added by the application.
.Pp
.Fn EVP_PKEY_asn1_get0
returns the public key ASN.1 method
.Fa idx .
The value of
.Fa idx
must be between zero and
.Fn EVP_PKEY_asn1_get_count
- 1.
.Pp
.Fn EVP_PKEY_asn1_find
looks up the
.Sy EVP_PKEY_ASN1_METHOD
with NID
.Fa type .
If
.Fa pe
isn't
.Dv NULL ,
then it will look up an engine implementing a
.Sy EVP_PKEY_ASN1_METHOD
for the NID
.Fa type
and return that instead, and also set
.Sy *pe
to point at the engine that implements it.
.Pp
.Fn EVP_PKEY_asn1_find_str
looks up the
.Sy EVP_PKEY_ASN1_METHOD
with PEM type string
.Fa str .
Just like
.Fn EVP_PKEY_asn1_find ,
if
.Fa pe
isn't
.Dv NULL ,
then it will look up an engine implementing a
.Sy EVP_PKEY_ASN1_METHOD
for the NID
.Fa type
and return that instead, and also set
.Sy *pe
to point at the engine that implements it.
.Pp
.Fn EVP_PKEY_asn1_get0_info
returns the public key ID, base public key ID (both NIDs), any flags,
the method description and PEM type string associated with the public
key ASN.1 method
.Sy *ameth .
.Pp
.Xr EVP_PKEY_asn1_count 3 ,
.Fn EVP_PKEY_asn1_get0 ,
.Fn EVP_PKEY_asn1_find
and
.Fn EVP_PKEY_asn1_find_str
are not thread safe, but as long as all
.Sy EVP_PKEY_ASN1_METHOD
objects are added before the application gets threaded, using them is
safe.
See
.Xr EVP_PKEY_asn1_add0 3 .
.Sh RETURN VALUES
.Xr EVP_PKEY_asn1_count 3
returns the number of available public key methods.
.Pp
.Fn EVP_PKEY_asn1_get0
return a public key method or
.Dv NULL
if
.Fa idx
is out of range.
.Pp
.Fn EVP_PKEY_asn1_get0_info
returns 0 on failure, 1 on success.
.Sh SEE ALSO
.Xr EVP_PKEY_asn1_new 3 ,
.Xr EVP_PKEY_asn1_add0 3
.Sh COPYRIGHT
Copyright 2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
