.Dd 2025-09-30
.Dt EVP_PKEY_CTX_SET_PARAMS 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_CTX_set_params ,
.Nm EVP_PKEY_CTX_settable_params ,
.Nm EVP_PKEY_CTX_get_params ,
.Nm EVP_PKEY_CTX_gettable_params
.Nd provider parameter passing operations
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_CTX_set_params
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const OSSL_PARAM *params"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_PKEY_CTX_settable_params
.Fa "const EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_get_params
.Fa "EVP_PKEY_CTX *ctx"
.Fa "OSSL_PARAM *params"
.Fc
.Ft const OSSL_PARAM *
.Fo EVP_PKEY_CTX_gettable_params
.Fa "const EVP_PKEY_CTX *ctx"
.Fc
.Sh DESCRIPTION
The
.Fn EVP_PKEY_CTX_get_params
and
.Fn EVP_PKEY_CTX_set_params
functions allow transfer of arbitrary key parameters to and from
providers.
Not all parameters may be supported by all providers.
See
.Xr OSSL_PROVIDER 3
for more information on providers.
The
.Fa params
field is a pointer to a list of
.Vt OSSL_PARAM
structures, terminated with a
.Xr OSSL_PARAM_END 3
struct.
See
.Xr OSSL_PARAM 3
for information about passing parameters.
These functions must only be called after the EVP_PKEY_CTX has been
initialised for use in an operation.
These methods replace the
.Xr EVP_PKEY_CTX_ctrl 3
mechanism.
(EVP_PKEY_CTX_ctrl now calls these methods internally to interact with
providers).
.Pp
.Fn EVP_PKEY_CTX_gettable_params
and
.Fn EVP_PKEY_CTX_settable_params
get a constant
.Xr OSSL_PARAM 3
array that describes the gettable and settable parameters for the
current algorithm implementation, i.e.
parameters that can be used with
.Fn EVP_PKEY_CTX_get_params
and
.Fn EVP_PKEY_CTX_set_params
respectively.
These functions must only be called after the EVP_PKEY_CTX has been
initialised for use in an operation.
.Ss Parameters
Examples of EVP_PKEY parameters include the following:
.Pp
.Xr provider-keymgmt 7
.Xr provider-keyexch 7
.Xr provider-signature 7
.Pp
.Xr EVP_PKEY-RSA 7
.Xr EVP_PKEY-RSA 7
.Xr EVP_PKEY-FFC 7
.Xr EVP_PKEY-FFC 7
.Xr EVP_PKEY-DSA 7
.Xr EVP_PKEY-DSA 7
.Xr EVP_PKEY-DH 7
.Xr EVP_PKEY-DH 7
.Xr EVP_PKEY-EC 7
.Xr EVP_PKEY-X25519 7
.Xr EVP_PKEY-ML-DSA 7
.Xr EVP_PKEY-ML-KEM 7
.Sh RETURN VALUES
.Fn EVP_PKEY_CTX_set_params
returns 1 for success or 0 otherwise.
.Fn EVP_PKEY_CTX_settable_params
returns an OSSL_PARAM array on success or NULL on error.
It may also return NULL if there are no settable parameters available.
.Pp
All other functions and macros described on this page return a positive
value for success and 0 or a negative value for failure.
In particular a return value of -2 indicates the operation is not
supported by the public key algorithm.
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_encrypt 3 ,
.Xr EVP_PKEY_decrypt 3 ,
.Xr EVP_PKEY_sign 3 ,
.Xr EVP_PKEY_verify 3 ,
.Xr EVP_PKEY_verify_recover 3 ,
.Xr EVP_PKEY_derive 3 ,
.Xr EVP_PKEY_keygen 3
.Sh HISTORY
All functions were added in OpenSSL 3.0.
.Pp
Support for
.Sy ML-DSA Ns >
and
.Sy ML-KEM
was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
