.Dd 2025-09-30
.Dt EVP_PKEY_CHECK 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_check ,
.Nm EVP_PKEY_param_check ,
.Nm EVP_PKEY_param_check_quick ,
.Nm EVP_PKEY_public_check ,
.Nm EVP_PKEY_public_check_quick ,
.Nm EVP_PKEY_private_check ,
.Nm EVP_PKEY_pairwise_check
.Nd key and parameter validation functions
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_PKEY_check
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_param_check
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_param_check_quick
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_public_check
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_public_check_quick
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_private_check
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Ft int
.Fo EVP_PKEY_pairwise_check
.Fa "EVP_PKEY_CTX *ctx"
.Fc
.Sh DESCRIPTION
.Fn EVP_PKEY_param_check
validates the parameters component of the key given by
.Fa ctx .
This check will always succeed for key types that do not have
parameters.
.Pp
.Fn EVP_PKEY_param_check_quick
validates the parameters component of the key given by
.Fa ctx
like
.Fn EVP_PKEY_param_check
does.
However some algorithm implementations may offer a quicker form of
validation that omits some checks in order to perform a lightweight
sanity check of the key.
If a quicker form is not provided then this function call does the same
thing as
.Fn EVP_PKEY_param_check .
.Pp
.Fn EVP_PKEY_public_check
validates the public component of the key given by
.Fa ctx .
.Pp
.Fn EVP_PKEY_public_check_quick
validates the public component of the key given by
.Fa ctx
like
.Fn EVP_PKEY_public_check
does.
However some algorithm implementations may offer a quicker form of
validation that omits some checks in order to perform a lightweight
sanity check of the key.
If a quicker form is not provided then this function call does the same
thing as
.Fn EVP_PKEY_public_check .
.Pp
.Fn EVP_PKEY_private_check
validates the private component of the key given by
.Fa ctx .
.Pp
.Fn EVP_PKEY_pairwise_check
validates that the public and private components have the correct
mathematical relationship to each other for the key given by
.Fa ctx .
.Pp
.Fn EVP_PKEY_check
is an alias for the
.Fn EVP_PKEY_pairwise_check
function.
.Sh NOTES
Key validation used by the OpenSSL FIPS provider complies with the rules
within SP800-56A and SP800-56B. For backwards compatibility reasons the
OpenSSL default provider may use checks that are not as restrictive for
certain key types.
For further information see
.Xr EVP_PKEY-DSA 7 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-EC 7
and
.Xr EVP_PKEY-RSA 7 .
.Pp
Refer to SP800-56A and SP800-56B for rules relating to when these
functions should be called during key establishment.
It is not necessary to call these functions after locally calling an
approved key generation method, but may be required for assurance
purposes when receiving keys from a third party.
.Pp
The
.Fn EVP_PKEY_pairwise_check
and
.Fn EVP_PKEY_private_check
might not be bounded by any key size limits as private keys are not
expected to be supplied by attackers.
For that reason they might take an unbounded time if run on arbitrarily
large keys.
.Sh RETURN VALUES
All functions return 1 for success or others for failure.
They return -2 if the operation is not supported for the specific
algorithm.
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_fromdata 3 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-FFC 7 ,
.Xr EVP_PKEY-DSA 7 ,
.Xr EVP_PKEY-EC 7 ,
.Xr EVP_PKEY-RSA 7 ,
.Sh HISTORY
.Fn EVP_PKEY_check ,
.Fn EVP_PKEY_public_check
and
.Fn EVP_PKEY_param_check
were added in OpenSSL 1.1.1.
.Pp
.Fn EVP_PKEY_param_check_quick ,
.Fn EVP_PKEY_public_check_quick ,
.Fn EVP_PKEY_private_check
and
.Fn EVP_PKEY_pairwise_check
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2006-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
