.Dd 2025-09-30
.Dt EVP_SET_DEFAULT_PROPERTIES 3ossl
.Os
.Sh NAME
.Nm EVP_set_default_properties ,
.Nm EVP_default_properties_enable_fips ,
.Nm EVP_default_properties_is_fips_enabled ,
.Nm EVP_get1_default_properties
.Nd manage default properties for future algorithm fetches
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_set_default_properties
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft char *
.Fo EVP_get1_default_properties
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft int
.Fo EVP_default_properties_enable_fips
.Fa "OSSL_LIB_CTX *libctx"
.Fa "int enable"
.Fc
.Ft int
.Fo EVP_default_properties_is_fips_enabled
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Sh DESCRIPTION
.Fn EVP_set_default_properties
sets the default properties for all future EVP algorithm fetches,
implicit as well as explicit.
See
.Xr crypto 7
for information about implicit and explicit fetching.
.Pp
EVP_set_default_properties stores the properties given with the string
.Fa propq
among the EVP data that's been stored in the library context given with
.Fa libctx
(NULL signifies the default library context).
.Pp
Any previous default property for the specified library context will be
dropped.
.Pp
.Fn EVP_get1_default_properties
gets the default properties set for all future EVP algorithm fetches,
implicit as well as explicit, for the specific library context.
.Pp
.Fn EVP_default_properties_enable_fips
sets the 'fips=yes' to be a default property if
.Fa enable
is non zero, otherwise it clears 'fips' from the default property query
for the given
.Fa libctx .
It merges the fips default property query with any existing query
strings that have been set via
.Fn EVP_set_default_properties .
.Pp
.Fn EVP_default_properties_is_fips_enabled
indicates if 'fips=yes' is a default property for the given
.Fa libctx .
.Sh NOTES
.Fn EVP_set_default_properties
and
.Fn EVP_default_properties_enable_fips
are not thread safe.
They are intended to be called only during the initialisation phase of a
.Fa libctx .
.Pp
.Fn EVP_get1_default_properties
is not thread safe.
The application must ensure that the context reference is valid and
default fetching properties are not being modified by a different
thread.
.Sh RETURN VALUES
.Fn EVP_set_default_properties
and
.Fn EVP_default_properties_enable_fips
return 1 on success, or 0 on failure.
An error is placed on the error stack if a failure occurs.
.Pp
.Fn EVP_default_properties_is_fips_enabled
returns 1 if the 'fips=yes' default property is set for the given
.Fa libctx ,
otherwise it returns 0.
.Pp
.Fn EVP_get1_default_properties
returns allocated memory that must be freed by
.Xr OPENSSL_free 3
on success and NULL on failure.
.Sh SEE ALSO
.Xr EVP_MD_fetch 3
.Sh HISTORY
The functions
.Fn EVP_set_default_properties ,
.Fn EVP_default_properties_enable_fips ,
.Fn EVP_default_properties_is_fips_enabled
were added in OpenSSL 3.0.
.Pp
The function
.Fn EVP_get1_default_properties
was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
