.Dd 2025-09-30
.Dt EVP_CIPHER_CTX_GET_ORIGINAL_IV 3ossl
.Os
.Sh NAME
.Nm EVP_CIPHER_CTX_get_original_iv ,
.Nm EVP_CIPHER_CTX_get_updated_iv ,
.Nm EVP_CIPHER_CTX_iv ,
.Nm EVP_CIPHER_CTX_original_iv ,
.Nm EVP_CIPHER_CTX_iv_noconst
.Nd Routines to inspect EVP_CIPHER_CTX IV data
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo EVP_CIPHER_CTX_get_original_iv
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "void *buf"
.Fa "size_t len"
.Fc
.Ft int
.Fo EVP_CIPHER_CTX_get_updated_iv
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "void *buf"
.Fa "size_t len"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft const unsigned char *
.Fo EVP_CIPHER_CTX_iv
.Fa "const EVP_CIPHER_CTX *ctx"
.Fc
.Ft const unsigned char *
.Fo EVP_CIPHER_CTX_original_iv
.Fa "const EVP_CIPHER_CTX *ctx"
.Fc
.Ft unsigned char *
.Fo EVP_CIPHER_CTX_iv_noconst
.Fa "EVP_CIPHER_CTX *ctx"
.Fc
.Sh DESCRIPTION
.Fn EVP_CIPHER_CTX_get_original_iv
and
.Fn EVP_CIPHER_CTX_get_updated_iv
copy initialization vector (IV) information from the
.Vt EVP_CIPHER_CTX
into the caller-supplied buffer.
.Xr EVP_CIPHER_CTX_get_iv_length 3
can be used to determine an appropriate buffer size, and if the supplied
buffer is too small, an error will be returned (and no data copied).
.Fn EVP_CIPHER_CTX_get_original_iv
accesses the ("original") IV that was supplied when the
.Vt EVP_CIPHER_CTX
was initialized, and
.Fn EVP_CIPHER_CTX_get_updated_iv
accesses the current "IV state" of the cipher, which is updated during
cipher operation for certain cipher modes (e.g., CBC and OFB).
.Pp
The functions
.Fn EVP_CIPHER_CTX_iv ,
.Fn EVP_CIPHER_CTX_original_iv ,
and
.Fn EVP_CIPHER_CTX_iv_noconst
are deprecated functions that provide similar (at a conceptual level)
functionality.
.Fn EVP_CIPHER_CTX_iv
returns a pointer to the beginning of the "IV state" as maintained
internally in the
.Vt EVP_CIPHER_CTX ;
.Fn EVP_CIPHER_CTX_original_iv
returns a pointer to the beginning of the ("original") IV, as maintained
by the
.Vt EVP_CIPHER_CTX ,
that was provided when the
.Vt EVP_CIPHER_CTX
was initialized; and
.Xr EVP_CIPHER_CTX_get_iv_noconst 3
is the same as
.Fn EVP_CIPHER_CTX_iv
but has a different return type for the pointer.
.Sh RETURN VALUES
.Fn EVP_CIPHER_CTX_get_original_iv
and
.Fn EVP_CIPHER_CTX_get_updated_iv
return 1 on success and 0 on failure.
.Pp
The functions
.Fn EVP_CIPHER_CTX_iv ,
.Fn EVP_CIPHER_CTX_original_iv ,
and
.Fn EVP_CIPHER_CTX_iv_noconst
return a pointer to an IV as an array of bytes on success, and NULL on
failure.
.Sh HISTORY
.Fn EVP_CIPHER_CTX_get_original_iv
and
.Fn EVP_CIPHER_CTX_get_updated_iv
were added in OpenSSL 3.0.0.
.Pp
.Fn EVP_CIPHER_CTX_iv ,
.Fn EVP_CIPHER_CTX_original_iv ,
and
.Fn EVP_CIPHER_CTX_iv_noconst
were added in OpenSSL 1.1.0, and were deprecated in OpenSSL 3.0.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
