.Dd 2025-09-30
.Dt EVP_PKEY_CTX_SET_RSA_PSS_KEYGEN_MD 3ossl
.Os
.Sh NAME
.Nm EVP_PKEY_CTX_set_rsa_pss_keygen_md ,
.Nm EVP_PKEY_CTX_set_rsa_pss_keygen_md_name ,
.Nm EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md ,
.Nm EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md_name ,
.Nm EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen
.Nd EVP_PKEY RSA-PSS algorithm support functions
.Sh SYNOPSIS
.In openssl/rsa.h
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_pss_keygen_md
.Fa "EVP_PKEY_CTX *pctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_pss_keygen_md_name
.Fa "EVP_PKEY_CTX *ctx"
.Fa "const char *mdname"
.Fa "const char *mdprops"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md
.Fa "EVP_PKEY_CTX *pctx"
.Fa "const EVP_MD *md"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md_name
.Fa "EVP_PKEY_CTX *pctx"
.Fa "const char *mdname"
.Fc
.Ft int
.Fo EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen
.Fa "EVP_PKEY_CTX *pctx"
.Fa "int saltlen"
.Fc
.Sh DESCRIPTION
These are the functions that implement
.Xr RSA-PSS 7 .
.Ss Signing and Verification
The macro
.Xr EVP_PKEY_CTX_set_rsa_padding 3
is supported but an error is returned if an attempt is made to set the
padding mode to anything other than
.Sy PSS .
It is otherwise similar to the
.Sy RSA
version.
.Pp
The
.Xr EVP_PKEY_CTX_set_rsa_pss_saltlen 3
macro is used to set the salt length.
If the key has usage restrictions then an error is returned if an
attempt is made to set the salt length below the minimum value.
It is otherwise similar to the
.Sy RSA
operation except detection of the salt length (using
RSA_PSS_SALTLEN_AUTO) is not supported for verification if the key has
usage restrictions.
.Pp
The
.Xr EVP_PKEY_CTX_set_signature_md 3
and
.Xr EVP_PKEY_CTX_set_rsa_mgf1_md 3
functions are used to set the digest and MGF1 algorithms respectively.
If the key has usage restrictions then an error is returned if an
attempt is made to set the digest to anything other than the restricted
value.
Otherwise these are similar to the
.Sy RSA
versions.
.Ss Key Generation
As with RSA key generation the
.Xr EVP_PKEY_CTX_set_rsa_keygen_bits 3
and
.Xr EVP_PKEY_CTX_set_rsa_keygen_pubexp 3
macros are supported for RSA-PSS: they have exactly the same meaning as
for the RSA algorithm.
.Pp
Optional parameter restrictions can be specified when generating a PSS
key.
If any restrictions are set (using the macros described below) then
.Sy all
parameters are restricted.
For example, setting a minimum salt length also restricts the digest and
MGF1 algorithms.
If any restrictions are in place then they are reflected in the
corresponding parameters of the public key when (for example) a
certificate request is signed.
.Pp
.Fn EVP_PKEY_CTX_set_rsa_pss_keygen_md
restricts the digest algorithm the generated key can use to
.Fa md .
.Fn EVP_PKEY_CTX_set_rsa_pss_keygen_md_name
does the same thing, but passes the algorithm by name rather than by
.Sy EVP_MD .
.Pp
.Fn EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md
restricts the MGF1 algorithm the generated key can use to
.Fa md .
.Fn EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md_name
does the same thing, but passes the algorithm by name rather than by
.Sy EVP_MD .
.Pp
.Fn EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen
restricts the minimum salt length to
.Fa saltlen .
.Sh NOTES
A context for the
.Sy RSA-PSS
algorithm can be obtained by calling:
.Bd -literal
 EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA_PSS, NULL);
.Ed
.Sh RETURN VALUES
All these functions return 1 for success and 0 or a negative value for
failure.
In particular a return value of -2 indicates the operation is not
supported by the public key algorithm.
.Sh SEE ALSO
.Xr RSA-PSS 7 ,
.Xr EVP_PKEY_CTX_new 3 ,
.Xr EVP_PKEY_CTX_ctrl_str 3 ,
.Xr EVP_PKEY_derive 3
.Sh COPYRIGHT
Copyright 2017-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
