.Dd 2025-09-30
.Dt HMAC 3ossl
.Os
.Sh NAME
.Nm HMAC ,
.Nm HMAC_CTX_new ,
.Nm HMAC_CTX_reset ,
.Nm HMAC_CTX_free ,
.Nm HMAC_Init ,
.Nm HMAC_Init_ex ,
.Nm HMAC_Update ,
.Nm HMAC_Final ,
.Nm HMAC_CTX_copy ,
.Nm HMAC_CTX_set_flags ,
.Nm HMAC_CTX_get_md ,
.Nm HMAC_size
.Nd HMAC message authentication code
.Sh SYNOPSIS
.In openssl/hmac.h
.Ft unsigned char *
.Fo HMAC
.Fa "const EVP_MD *evp_md"
.Fa "const void *key"
.Fa "int key_len"
.Fa "const unsigned char *data"
.Fa "size_t data_len"
.Fa "unsigned char *md"
.Fa "unsigned int *md_len"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft HMAC_CTX *
.Fo HMAC_CTX_new
.Fa void
.Fc
.Ft int
.Fo HMAC_CTX_reset
.Fa "HMAC_CTX *ctx"
.Fc
.Ft int
.Fo HMAC_Init_ex
.Fa "HMAC_CTX *ctx"
.Fa "const void *key"
.Fa "int key_len"
.Fa "const EVP_MD *md"
.Fa "ENGINE *impl"
.Fc
.Ft int
.Fo HMAC_Update
.Fa "HMAC_CTX *ctx"
.Fa "const unsigned char *data"
.Fa "size_t len"
.Fc
.Ft int
.Fo HMAC_Final
.Fa "HMAC_CTX *ctx"
.Fa "unsigned char *md"
.Fa "unsigned int *len"
.Fc
.Ft void
.Fo HMAC_CTX_free
.Fa "HMAC_CTX *ctx"
.Fc
.Ft int
.Fo HMAC_CTX_copy
.Fa "HMAC_CTX *dctx"
.Fa "HMAC_CTX *sctx"
.Fc
.Ft void
.Fo HMAC_CTX_set_flags
.Fa "HMAC_CTX *ctx"
.Fa "unsigned long flags"
.Fc
.Ft const EVP_MD *
.Fo HMAC_CTX_get_md
.Fa "const HMAC_CTX *ctx"
.Fc
.Ft size_t
.Fo HMAC_size
.Fa "const HMAC_CTX *e"
.Fc
.Pp
The following function has been deprecated since OpenSSL 1.1.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo HMAC_Init
.Fa "HMAC_CTX *ctx"
.Fa "const void *key"
.Fa "int key_len"
.Fa "const EVP_MD *md"
.Fc
.Sh DESCRIPTION
HMAC is a MAC (message authentication code), i.e.
a keyed hash function used for message authentication, which is based on
a hash function.
.Pp
.Fn HMAC
computes the message authentication code of the
.Fa data_len
bytes at
.Fa data
using the hash function
.Fa evp_md
and the key
.Fa key
which is
.Fa key_len
bytes long.
The
.Fa key
may also be NULL with
.Fa key_len
being 0.
.Pp
It places the result in
.Fa md
(which must have space for the output of the hash function, which is no
more than
.Sy EVP_MAX_MD_SIZE
bytes).
If
.Fa md
is NULL, the digest is placed in a static array.
The size of the output is placed in
.Fa md_len ,
unless it is NULL. Note: passing a NULL value for
.Fa md
to use the static array is not thread safe.
.Pp
.Fa evp_md
is a message digest such as
.Xr EVP_sha1 3 ,
.Xr EVP_ripemd160 3
etc.
HMAC does not support variable output length digests such as
.Xr EVP_shake128 3
and
.Xr EVP_shake256 3 .
.Pp
.Fn HMAC
uses the default
.Sy OSSL_LIB_CTX .
Use
.Xr EVP_Q_mac 3
instead if a library context is required.
.Pp
All of the functions described below are deprecated.
Applications should instead use
.Xr EVP_MAC_CTX_new 3 ,
.Xr EVP_MAC_CTX_free 3 ,
.Xr EVP_MAC_init 3 ,
.Xr EVP_MAC_update 3
and
.Xr EVP_MAC_final 3
or the 'quick' single-shot MAC function
.Xr EVP_Q_mac 3 .
.Pp
.Fn HMAC_CTX_new
creates a new HMAC_CTX in heap memory.
.Pp
.Fn HMAC_CTX_reset
clears an existing
.Vt HMAC_CTX
and associated resources, making it suitable for new computations as if
it was newly created with
.Fn HMAC_CTX_new .
.Pp
.Fn HMAC_CTX_free
erases the key and other data from the
.Vt HMAC_CTX ,
releases any associated resources and finally frees the
.Vt HMAC_CTX
itself.
If the argument is NULL, nothing is done.
.Pp
The following functions may be used if the message is not completely
stored in memory:
.Pp
.Fn HMAC_Init_ex
initializes or reuses a
.Vt HMAC_CTX
structure to use the hash function
.Fa evp_md
and key
.Fa key .
If both are NULL, or if
.Fa key
is NULL and
.Fa evp_md
is the same as the previous call, then the existing key is reused.
.Fa ctx
must have been created with
.Fn HMAC_CTX_new
before the first use of an
.Vt HMAC_CTX
in this function.
.Pp
If
.Fn HMAC_Init_ex
is called with
.Fa key
NULL and
.Fa evp_md
is not the same as the previous digest used by
.Fa ctx
then an error is returned because reuse of an existing key with a
different digest is not supported.
.Pp
.Fn HMAC_Init
initializes a
.Vt HMAC_CTX
structure to use the hash function
.Fa evp_md
and the key
.Fa key
which is
.Fa key_len
bytes long.
.Pp
.Fn HMAC_Update
can be called repeatedly with chunks of the message to be authenticated
.Pf ( Fa len
bytes at
.Fa data Ns ).
.Pp
.Fn HMAC_Final
places the message authentication code in
.Fa md ,
which must have space for the hash function output.
.Pp
.Fn HMAC_CTX_copy
copies all of the internal state from
.Fa sctx
into
.Fa dctx .
.Pp
.Fn HMAC_CTX_set_flags
applies the specified flags to the internal EVP_MD_CTXs.
These flags have the same meaning as for
.Xr EVP_MD_CTX_set_flags 3 .
.Pp
.Fn HMAC_CTX_get_md
returns the EVP_MD that has previously been set for the supplied
HMAC_CTX.
.Pp
.Fn HMAC_size
returns the length in bytes of the underlying hash function output.
.Sh RETURN VALUES
.Fn HMAC
returns a pointer to the message authentication code or NULL if an error
occurred.
.Pp
.Fn HMAC_CTX_new
returns a pointer to a new
.Vt HMAC_CTX
on success or NULL if an error occurred.
.Pp
.Fn HMAC_CTX_reset ,
.Fn HMAC_Init_ex ,
.Fn HMAC_Update ,
.Fn HMAC_Final
and
.Fn HMAC_CTX_copy
return 1 for success or 0 if an error occurred.
.Pp
.Fn HMAC_CTX_get_md
return the EVP_MD previously set for the supplied HMAC_CTX or NULL if no
EVP_MD has been set.
.Pp
.Fn HMAC_size
returns the length in bytes of the underlying hash function output or
zero on error.
.Sh CONFORMING TO
RFC 2104
.Sh SEE ALSO
.Xr SHA1 3 ,
EVP_Q_mac(3),
.Xr evp 7
.Sh HISTORY
All functions except for
.Fn HMAC
were deprecated in OpenSSL 3.0.
.Pp
.Xr HMAC_CTX_init 3
was replaced with
.Fn HMAC_CTX_reset
in OpenSSL 1.1.0.
.Pp
.Xr HMAC_CTX_cleanup 3
existed in OpenSSL before version 1.1.0.
.Pp
.Fn HMAC_CTX_new ,
.Fn HMAC_CTX_free
and
.Fn HMAC_CTX_get_md
are new in OpenSSL 1.1.0.
.Pp
.Fn HMAC_Init_ex ,
.Fn HMAC_Update
and
.Fn HMAC_Final
did not return values in OpenSSL before version 1.0.0.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
