.Dd 2025-09-30
.Dt I2D_CMS_BIO_STREAM 3ossl
.Os
.Sh NAME
.Nm i2d_CMS_bio_stream
.Nd output CMS_ContentInfo structure in BER format
.Sh SYNOPSIS
.In openssl/cms.h
.Ft int
.Fo i2d_CMS_bio_stream
.Fa "BIO *out"
.Fa "CMS_ContentInfo *cms"
.Fa "BIO *data"
.Fa "int flags"
.Fc
.Sh DESCRIPTION
.Fn i2d_CMS_bio_stream
outputs a CMS_ContentInfo structure in BER format.
.Pp
It is otherwise identical to the function
.Xr SMIME_write_CMS 3 .
.Sh NOTES
This function is effectively a version of the
.Xr i2d_CMS_bio 3
supporting streaming.
.Sh BUGS
The prefix "i2d" is arguably wrong because the function outputs BER
format.
.Sh RETURN VALUES
.Fn i2d_CMS_bio_stream
returns 1 for success or 0 for failure.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_sign 3 ,
.Xr CMS_verify 3 ,
.Xr CMS_encrypt 3
.Xr CMS_decrypt 3 ,
.Xr SMIME_write_CMS 3 ,
.Xr PEM_write_bio_CMS_stream 3
.Sh HISTORY
The
.Fn i2d_CMS_bio_stream
function was added in OpenSSL 1.0.0.
.Sh COPYRIGHT
Copyright 2008-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
