.Dd 2025-09-30
.Dt MD5 3ossl
.Os
.Sh NAME
.Nm MD2 ,
.Nm MD4 ,
.Nm MD5 ,
.Nm MD2_Init ,
.Nm MD2_Update ,
.Nm MD2_Final ,
.Nm MD4_Init ,
.Nm MD4_Update ,
.Nm MD4_Final ,
.Nm MD5_Init ,
.Nm MD5_Update ,
.Nm MD5_Final
.Nd MD2, MD4, and MD5 hash functions
.Sh SYNOPSIS
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.In openssl/md2.h
.Ft unsigned char *
.Fo MD2
.Fa "const unsigned char *d"
.Fa "unsigned long n"
.Fa "unsigned char *md"
.Fc
.Ft int
.Fo MD2_Init
.Fa "MD2_CTX *c"
.Fc
.Ft int
.Fo MD2_Update
.Fa "MD2_CTX *c"
.Fa "const unsigned char *data"
.Fa "unsigned long len"
.Fc
.Ft int
.Fo MD2_Final
.Fa "unsigned char *md"
.Fa "MD2_CTX *c"
.Fc
.Pp
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.In openssl/md4.h
.Ft unsigned char *
.Fo MD4
.Fa "const unsigned char *d"
.Fa "unsigned long n"
.Fa "unsigned char *md"
.Fc
.Ft int
.Fo MD4_Init
.Fa "MD4_CTX *c"
.Fc
.Ft int
.Fo MD4_Update
.Fa "MD4_CTX *c"
.Fa "const void *data"
.Fa "unsigned long len"
.Fc
.Ft int
.Fo MD4_Final
.Fa "unsigned char *md"
.Fa "MD4_CTX *c"
.Fc
.Pp
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.In openssl/md5.h
.Ft unsigned char *
.Fo MD5
.Fa "const unsigned char *d"
.Fa "unsigned long n"
.Fa "unsigned char *md"
.Fc
.Ft int
.Fo MD5_Init
.Fa "MD5_CTX *c"
.Fc
.Ft int
.Fo MD5_Update
.Fa "MD5_CTX *c"
.Fa "const void *data"
.Fa "unsigned long len"
.Fc
.Ft int
.Fo MD5_Final
.Fa "unsigned char *md"
.Fa "MD5_CTX *c"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_DigestInit_ex 3 ,
.Xr EVP_DigestUpdate 3
and
.Xr EVP_DigestFinal_ex 3 .
.Pp
MD2, MD4, and MD5 are cryptographic hash functions with a 128 bit
output.
.Pp
.Fn MD2 ,
.Fn MD4 ,
and
.Fn MD5
compute the MD2, MD4, and MD5 message digest of the
.Fa n
bytes at
.Fa d
and place it in
.Fa md
(which must have space for MD2_DIGEST_LENGTH == MD4_DIGEST_LENGTH ==
MD5_DIGEST_LENGTH == 16 bytes of output).
If
.Fa md
is NULL, the digest is placed in a static array.
.Pp
The following functions may be used if the message is not completely
stored in memory:
.Pp
.Fn MD2_Init
initializes a
.Vt MD2_CTX
structure.
.Pp
.Fn MD2_Update
can be called repeatedly with chunks of the message to be hashed
.Pf ( Fa len
bytes at
.Fa data Ns ).
.Pp
.Fn MD2_Final
places the message digest in
.Fa md ,
which must have space for MD2_DIGEST_LENGTH == 16 bytes of output, and
erases the
.Vt MD2_CTX .
.Pp
.Fn MD4_Init ,
.Fn MD4_Update ,
.Fn MD4_Final ,
.Fn MD5_Init ,
.Fn MD5_Update ,
and
.Fn MD5_Final
are analogous using an
.Vt MD4_CTX
and
.Vt MD5_CTX
structure.
The parameter
.Sy MUST NOT
be NULL.
.Pp
Applications should use the higher level functions
.Xr EVP_DigestInit 3
etc.
instead of calling the hash functions directly.
.Sh NOTE
MD2, MD4, and MD5 are recommended only for compatibility with existing
applications.
In new applications, hashes from the SHA-2 or SHA-3 family should be
preferred.
.Sh RETURN VALUES
.Fn MD2 ,
.Fn MD4 ,
and
.Fn MD5
return pointers to the hash value.
.Pp
.Fn MD2_Init ,
.Fn MD2_Update ,
.Fn MD2_Final ,
.Fn MD4_Init ,
.Fn MD4_Update ,
.Fn MD4_Final ,
.Fn MD5_Init ,
.Fn MD5_Update ,
and
.Fn MD5_Final
return 1 for success, 0 otherwise.
.Sh CONFORMING TO
RFC 1319, RFC 1320, RFC 1321
.Sh SEE ALSO
.Xr EVP_DigestInit 3 ,
.Xr EVP_MD-SHA2 7 ,
.Xr EVP_MD-SHA3 7
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
