.Dd 2025-09-30
.Dt NCONF_NEW_EX 3ossl
.Os
.Sh NAME
.Nm NCONF_new_ex ,
.Nm NCONF_new ,
.Nm NCONF_free ,
.Nm NCONF_default ,
.Nm NCONF_load ,
.Nm NCONF_get0_libctx ,
.Nm NCONF_get_section ,
.Nm NCONF_get_section_names
.Nd functionality to Load and parse configuration files manually
.Sh SYNOPSIS
.In openssl/conf.h
.Ft typedef struct {
     char *section;
     char *name;
     char *value;
 } CONF_VALUE;

 CONF *
.Fo NCONF_new_ex
.Fa "OSSL_LIB_CTX *libctx"
.Fa "CONF_METHOD *meth"
.Fc
.Ft CONF *
.Fo NCONF_new
.Fa "CONF_METHOD *meth"
.Fc
.Ft void
.Fo NCONF_free
.Fa "CONF *conf"
.Fc
.Ft CONF_METHOD *
.Fo NCONF_default
.Fa void
.Fc
.Ft int
.Fo NCONF_load
.Fa "CONF *conf"
.Fa "const char *file"
.Fa "long *eline"
.Fc
.Ft OSSL_LIB_CTX *
.Fo NCONF_get0_libctx
.Fa "const CONF *conf"
.Fc
.Bd -literal
 STACK_OF(CONF_VALUE) *NCONF_get_section(const CONF *conf, const char *name);
 STACK_OF(OPENSSL_CSTRING) *NCONF_get_section_names(const CONF *conf);
.Ed
.Sh DESCRIPTION
.Fn NCONF_new_ex
creates a new CONF object in heap memory and assigns to it a context
.Fa libctx
that can be used during loading.
If the method table
.Fa meth
is set to NULL then the default value of
.Fn NCONF_default
is used.
.Pp
.Fn NCONF_new
is similar to
.Fn NCONF_new_ex
but sets the
.Fa libctx
to NULL.
.Pp
.Fn NCONF_free
frees the data associated with
.Fa conf
and then frees the
.Fa conf
object.
If the argument is NULL, nothing is done.
.Pp
.Fn NCONF_load
parses the file named
.Em filename
and adds the values found to
.Fa conf .
If an error occurs
.Fa file
and
.Fa eline
list the file and line that the load failed on if they are not NULL.
.Pp
.Fn NCONF_default
gets the default method table for processing a configuration file.
.Pp
.Fn NCONF_get0_libctx
gets the library context associated with the
.Fa conf
parameter.
.Pp
.Xr NCONF_get_section_names 3
gets the names of the sections associated with the
.Fa conf
as
.Sy STACK_OF(OPENSSL_CSTRING)
strings.
The individual strings are associated with the
.Fa conf
and will be invalid after
.Fa conf
is freed.
The returned stack must be freed with
.Xr sk_OPENSSL_CSTRING_free 3 .
.Pp
.Xr NCONF_get_section 3
gets the config values associated with the
.Fa conf
from the config section
.Em name
as
.Sy STACK_OF(CONF_VALUE)
structures.
The returned stack is associated with the
.Fa conf
and will be invalid after
.Fa conf
is freed.
It must not be freed by the caller.
.Sh RETURN VALUES
.Fn NCONF_load
returns 1 on success or 0 on error.
.Pp
.Fn NCONF_new_ex
and
.Fn NCONF_new
return a newly created
.Vt CONF
object or NULL if an error occurs.
.Sh SEE ALSO
.Xr CONF_modules_load_file 3 ,
.Sh HISTORY
.Fn NCONF_new_ex ,
.Fn NCONF_get0_libctx ,
and
.Xr NCONF_get_section_names 3
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
