.Dd 2025-09-30
.Dt OCSP_REQUEST_ADD1_NONCE 3ossl
.Os
.Sh NAME
.Nm OCSP_request_add1_nonce ,
.Nm OCSP_basic_add1_nonce ,
.Nm OCSP_check_nonce ,
.Nm OCSP_copy_nonce
.Nd OCSP nonce functions
.Sh SYNOPSIS
.In openssl/ocsp.h
.Ft int
.Fo OCSP_request_add1_nonce
.Fa "OCSP_REQUEST *req"
.Fa "unsigned char *val"
.Fa "int len"
.Fc
.Ft int
.Fo OCSP_basic_add1_nonce
.Fa "OCSP_BASICRESP *resp"
.Fa "unsigned char *val"
.Fa "int len"
.Fc
.Ft int
.Fo OCSP_copy_nonce
.Fa "OCSP_BASICRESP *resp"
.Fa "OCSP_REQUEST *req"
.Fc
.Ft int
.Fo OCSP_check_nonce
.Fa "OCSP_REQUEST *req"
.Fa "OCSP_BASICRESP *resp"
.Fc
.Sh DESCRIPTION
.Fn OCSP_request_add1_nonce
adds a nonce of value
.Fa val
and length
.Fa len
to OCSP request
.Fa req .
If
.Fa val
is
.Dv NULL
a random nonce is used.
If
.Fa len
is zero or negative a default length will be used (currently 16 bytes).
.Pp
.Fn OCSP_basic_add1_nonce
is identical to
.Fn OCSP_request_add1_nonce
except it adds a nonce to OCSP basic response
.Fa resp .
.Pp
.Fn OCSP_check_nonce
compares the nonce value in
.Fa req
and
.Fa resp .
.Pp
.Fn OCSP_copy_nonce
copies any nonce value present in
.Fa req
to
.Fa resp .
.Sh RETURN VALUES
.Fn OCSP_request_add1_nonce
and
.Fn OCSP_basic_add1_nonce
return 1 for success and 0 for failure.
.Pp
.Fn OCSP_copy_nonce
returns 1 if a nonce was successfully copied, 2 if no nonce was present
in
.Fa req
and 0 if an error occurred.
.Pp
.Fn OCSP_check_nonce
returns the result of the nonce comparison between
.Fa req
and
.Fa resp .
The return value indicates the result of the comparison.
If nonces are present and equal 1 is returned.
If the nonces are absent 2 is returned.
If a nonce is present in the response only 3 is returned.
If nonces are present and unequal 0 is returned.
If the nonce is present in the request only then -1 is returned.
.Sh NOTES
For most purposes the nonce value in a request is set to a random value
so the
.Fa val
parameter in
.Fn OCSP_request_add1_nonce
is usually NULL.
.Pp
An OCSP nonce is typically added to an OCSP request to thwart replay
attacks by checking the same nonce value appears in the response.
.Pp
Some responders may include a nonce in all responses even if one is not
supplied.
.Pp
Some responders cache OCSP responses and do not sign each response for
performance reasons.
As a result they do not support nonces.
.Pp
The return values of
.Fn OCSP_check_nonce
can be checked to cover each case.
A positive return value effectively indicates success: nonces are both
present and match, both absent or present in the response only.
A nonzero return additionally covers the case where the nonce is present
in the request only: this will happen if the responder doesn't support
nonces.
A zero return value indicates present and mismatched nonces: this should
be treated as an error condition.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr OCSP_cert_to_id 3 ,
.Xr OCSP_REQUEST_new 3 ,
.Xr OCSP_resp_find_status 3 ,
.Xr OCSP_response_status 3 ,
.Xr OCSP_sendreq_new 3
.Sh COPYRIGHT
Copyright 2015-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
