.Dd 2025-09-30
.Dt OPENSSL_RISCVCAP 3ossl
.Os
.Sh NAME
.Nm OPENSSL_riscvcap
.Nd the RISC-V processor capabilities vector
.Sh SYNOPSIS
.Bd -literal
 env OPENSSL_riscvcap=... <application>
.Ed
.Sh DESCRIPTION
libcrypto supports RISC-V instruction set extensions.
These extensions are denoted by individual extension names in the
capabilities vector.
For Linux platform, when libcrypto is initialized, the results returned
by the RISC-V Hardware Probing syscall (hwprobe) are stored in the
vector.
Otherwise all capabilities are disabled.
.Pp
To override the set of instructions available to an application, you can
set the
.Sy OPENSSL_riscvcap
environment variable before you start the application.
.Pp
The environment variable is similar to the RISC-V ISA string defined in
the RISC-V Instruction Set Manual.
It is case insensitive.
Though due to the limit of the environment variable parser inside
libcrypto, an extension must be prefixed with an underscore to make it
recognizable.
This also applies to the Vector extension.
.Bd -literal
 OPENSSL_riscvcap="rv64gc_v_zba_zbb_zbs..."
.Ed
.Pp
Note that extension implication is currently not implemented.
For example, when "rv64gc_b" is provided as the environment variable,
zba/zbb/zbs would not be implied in the capability vector.
.Pp
Currently only these extensions are recognized:
.Bl -tag -width Ds
.It ZBA
Address Generation
.Pp
Could be detected using hwprobe for Linux kernel >= 6.5
.It ZBB
Basic bit-manipulation
.Pp
Could be detected using hwprobe for Linux kernel >= 6.5
.It ZBC
Carry-less multiplication
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZBS
Single-bit instructions
.Pp
Could be detected using hwprobe for Linux kernel >= 6.5
.It ZBKB
Bit-manipulation for Cryptography
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZBKC
Carry-less multiplication for Cryptography
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZBKX
Crossbar permutations
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZKND
NIST Suite: AES Decryption
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZKNE
NIST Suite: AES Encryption
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZKNH
NIST Suite: Hash Function Instructions
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZKSED
ShangMi Suite: SM4 Block Cipher Instructions
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZKSH
ShangMi Suite: SM3 Hash Function Instructions
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZKR
Entropy Source Extension
.It ZKT
Data Independent Execution Latency
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It V
Vector Extension for Application Processors
.Pp
Could be detected using hwprobe for Linux kernel >= 6.5
.It ZVBB
Vector Basic Bit-manipulation
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVBC
Vector Carryless Multiplication
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKB
Vector Cryptography Bit-manipulation
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKG
Vector GCM/GMAC
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKNED
NIST Suite: Vector AES Block Cipher
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKNHA
NIST Suite: Vector SHA-2 Secure Hash
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKNHB
NIST Suite: Vector SHA-2 Secure Hash
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKSED
ShangMi Suite: SM4 Block Cipher
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.It ZVKSH
ShangMi Suite: SM3 Secure Hash
.Pp
Could be detected using hwprobe for Linux kernel >= 6.8
.El
.Sh RETURN VALUES
Not available.
.Sh EXAMPLES
Check currently detected capabilities
.Bd -literal
 $ openssl info -cpusettings
 OPENSSL_riscvcap=ZBA_ZBB_ZBC_ZBS_V
.Ed
.Pp
Disables all instruction set extensions:
.Bd -literal
 OPENSSL_riscvcap="rv64gc"
.Ed
.Pp
Only enable the vector extension:
.Bd -literal
 OPENSSL_riscvcap="rv64gc_v"
.Ed
.Sh COPYRIGHT
Copyright 2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
