.Dd 2025-09-30
.Dt OPENSSL_IA32CAP 3ossl
.Os
.Sh NAME
.Nm OPENSSL_ia32cap
.Nd the x86[_64] processor capabilities vector
.Sh SYNOPSIS
.Bd -literal
 env OPENSSL_ia32cap=... <application>
.Ed
.Sh DESCRIPTION
OpenSSL supports a range of x86[_64] instruction set extensions and
features.
These extensions are denoted by individual bits or groups of bits stored
internally as ten 32-bit capability vectors and for simplicity
represented logically below as five 64-bit vectors.
This logical vector (LV) representation is used to streamline the
definition of the OPENSSL_ia32cap environment variable.
.Pp
Upon toolkit initialization, the capability vectors are populated
through successive executions of the CPUID instruction, after which any
OPENSSL_ia32cap environment variable capability bit modifications are
applied.
After toolkit initialization is complete, populated vectors are then
used to choose between different code paths to provide optimal
performance across a wide range of x86[_64] based processors.
.Pp
Further CPUID information can be found in the Intel(R) Architecture
Instruction Set Extensions Programming Reference, and the AMD64
Architecture Programmer's Manual (Volume 3).
.Ss Notable Capability Bits for LV0
The following are notable capability bits from logical vector 0 (LV0)
resulting from the following execution of CPUID.(EAX=01H).EDX and
CPUID.(EAX=01H).ECX:
.Bl -tag -width Ds
.It bit #0+4 denoting presence of Time-Stamp Counter;
.It bit #0+19 denoting availability of CLFLUSH instruction;
.It bit #0+20, reserved by Intel, is used to choose among RC4 code paths;
.It bit #0+23 denoting MMX support;
.It bit #0+24, FXSR bit, denoting availability of XMM registers;
.It bit #0+25 denoting SSE support;
.It bit #0+26 denoting SSE2 support;
.It bit #0+28 denoting Hyperthreading, which is used to distinguish cores with shared cache;
.It bit #0+30, reserved by Intel, denotes specifically Intel CPUs;
.It bit #0+33 denoting availability of PCLMULQDQ instruction;
.It bit #0+41 denoting SSSE3, Supplemental SSE3, support;
.It bit #0+43 denoting AMD XOP support (forced to zero on non-AMD CPUs);
.It bit #0+54 denoting availability of MOVBE instruction;
.It bit #0+57 denoting AES-NI instruction set extension;
.It bit #0+58, XSAVE bit, lack of which in combination with MOVBE is used to identify Atom Silvermont core;
.It bit #0+59, OSXSAVE bit, denoting availability of YMM registers;
.It bit #0+60 denoting AVX extension;
.It bit #0+62 denoting availability of RDRAND instruction;
.El
.Ss Notable Capability Bits for LV1
The following are notable capability bits from logical vector 1 (LV1)
resulting from the following execution of CPUID.(EAX=07H,ECX=0H).EBX and
CPUID.(EAX=07H,ECX=0H).ECX:
.Bl -tag -width Ds
.It bit #64+3 denoting availability of BMI1 instructions, e.g. ANDN;
.It bit #64+5 denoting availability of AVX2 instructions;
.It bit #64+8 denoting availability of BMI2 instructions, e.g. MULX and RORX;
.It bit #64+16 denoting availability of AVX512F extension;
.It bit #64+17 denoting availability of AVX512DQ extension;
.It bit #64+18 denoting availability of RDSEED instruction;
.It bit #64+19 denoting availability of ADCX and ADOX instructions;
.It bit #64+21 denoting availability of AVX512IFMA extension;
.It bit #64+29 denoting availability of SHA extension;
.It bit #64+30 denoting availability of AVX512BW extension;
.It bit #64+31 denoting availability of AVX512VL extension;
.It bit #64+41 denoting availability of VAES extension;
.It bit #64+42 denoting availability of VPCLMULQDQ extension;
.El
.Ss Notable Capability Bits for LV2
The following are notable capability bits from logical vector 2 (LV2)
resulting from the following execution of CPUID.(EAX=07H,ECX=0H).EDX and
CPUID.(EAX=07H,ECX=1H).EAX:
.Bl -tag -width Ds
.It bit #128+15 denoting availability of Hybrid CPU;
.It bit #128+29 denoting support for IA32_ARCH_CAPABILITIES MSR;
.It bit #128+32 denoting availability of SHA512 extension;
.It bit #128+33 denoting availability of SM3 extension;
.It bit #128+34 denoting availability of SM4 extension;
.It bit #128+55 denoting availability of AVX-IFMA extension;
.El
.Ss Notable Capability Bits for LV3
The following are notable capability bits from logical vector 3 (LV3)
resulting from the following execution of CPUID.(EAX=07H,ECX=1H).EDX and
CPUID.(EAX=07H,ECX=1H).EBX:
.Bl -tag -width Ds
.It bit #192+19 denoting availability of AVX10 Converged Vector ISA extension;
.It bit #192+21 denoting availability of APX_F extension;
.El
.Ss Notable Capability Bits for LV4
The following are notable capability bits from logical vector 4 (LV4)
resulting from the following execution of CPUID.(EAX=07H,ECX=1H).ECX and
CPUID.(EAX=24H,ECX=0H).EBX:
.Bl -tag -width Ds
.It bits #256+32+[0:7] denoting AVX10 Converged Vector ISA Version (8 bits);
.It bit #256+48 denoting AVX10 XMM support;
.It bit #256+49 denoting AVX10 YMM support;
.It bit #256+50 denoting AVX10 ZMM support;
.El
.Ss OPENSSL_ia32cap environment variable
The
.Sy OPENSSL_ia32cap
environment variable provides a mechanism to override the default
capability vector values at library initialization time.
The variable consists of a series of 64-bit numbers representing each of
the logical vectors (LV) described above.
Each value is delimited by a
.Pf ' Sy : Ns '.
Decimal/Octal/Hexadecimal values representations are supported.
.Pp
.Qo Li env OPENSSL_ia32cap=LV0:LV1:LV2:LV3:LV4 Qc
.Pp
Used in this form, each non-null logical vector will *overwrite* the
entire corresponding capability vector pair with the provided value.
To keep compatibility with the behaviour of the original OPENSSL_ia32cap
environment variable <env OPENSSL_ia32cap=LV0:LV1>, the next capability
vector pairs will be set to zero.
.Pp
To illustrate, the following will zero all capability bits in logical
vectors 1 and further (disable all post-AVX extensions):
.Pp
.Qo Li env OPENSSL_ia32cap=:0 Qc
.Pp
The following will zero all capability bits in logical vectors 2 and
further:
.Pp
.Qo Li env OPENSSL_ia32cap=::0 Qc
.Pp
The following will zero all capability bits only in logical vector 1:
.Qo Li env OPENSSL_ia32cap=:0:::: Qc
.Pp
A more likely usage scenario would be to disable specific instruction
set extensions.
The
.Pf ' Sy ~ Ns '
character is used to specify a bit mask of the extensions to be disabled
for a particular logical vector.
.Pp
To illustrate, the following will disable AVX2 code paths and further
extensions:
.Pp
.Qo Li env OPENSSL_ia32cap=:~0x20000000000 Qc
.Pp
The following will disable AESNI (LV0 bit 57) and VAES (LV1 bit 41)
extensions and therefore any code paths using those extensions but leave
the rest of the logical vectors unchanged:
.Pp
.Qo Li env OPENSSL_ia32cap=~0x200000000000000:~0x20000000000:~0x0:~0x0:~0x0 Qc
.Sh NOTES
Not all capability bits are copied from CPUID output verbatim.
An example of this is the somewhat less intuitive clearing of LV0 bit
#28, or ~0x10000000 in the "environment variable" terms.
It has been adjusted to reflect whether or not the data cache is
actually shared between logical cores.
This in turn affects the decision on whether or not expensive
countermeasures against cache-timing attacks are applied, most notably
in AES assembler module.
.Sh RETURN VALUES
Not available.
.Sh COPYRIGHT
Copyright 2004-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
