.Dd 2025-09-30
.Dt OPENSSL_INIT_CRYPTO 3ossl
.Os
.Sh NAME
.Nm OPENSSL_INIT_new ,
.Nm OPENSSL_INIT_set_config_filename ,
.Nm OPENSSL_INIT_set_config_appname ,
.Nm OPENSSL_INIT_set_config_file_flags ,
.Nm OPENSSL_INIT_free ,
.Nm OPENSSL_init_crypto ,
.Nm OPENSSL_cleanup ,
.Nm OPENSSL_atexit ,
.Nm OPENSSL_thread_stop_ex ,
.Nm OPENSSL_thread_stop
.Nd OpenSSL initialisation and deinitialisation functions
.Sh SYNOPSIS
.In openssl/crypto.h
.Ft void
.Fo OPENSSL_cleanup
.Fa void
.Fc
.Ft int
.Fo OPENSSL_init_crypto
.Fa "uint64_t opts"
.Fa "const OPENSSL_INIT_SETTINGS *settings"
.Fc
.Ft int
.Fo OPENSSL_atexit
.Fa "void (*handler)(void)"
.Fc
.Ft void
.Fo OPENSSL_thread_stop_ex
.Fa "OSSL_LIB_CTX *ctx"
.Fc
.Ft void
.Fo OPENSSL_thread_stop
.Fa void
.Fc
.Ft OPENSSL_INIT_SETTINGS *
.Fo OPENSSL_INIT_new
.Fa void
.Fc
.Ft int
.Fo OPENSSL_INIT_set_config_filename
.Fa "OPENSSL_INIT_SETTINGS *init"
.Fa "const char* filename"
.Fc
.Ft int
.Fo OPENSSL_INIT_set_config_file_flags
.Fa "OPENSSL_INIT_SETTINGS *init"
.Fa "unsigned long flags"
.Fc
.Ft int
.Fo OPENSSL_INIT_set_config_appname
.Fa "OPENSSL_INIT_SETTINGS *init"
.Fa "const char* name"
.Fc
.Ft void
.Fo OPENSSL_INIT_free
.Fa "OPENSSL_INIT_SETTINGS *init"
.Fc
.Sh DESCRIPTION
During normal operation OpenSSL (libcrypto) will allocate various
resources at start up that must, subsequently, be freed on close down of
the library.
Additionally some resources are allocated on a per thread basis (if the
application is multi-threaded), and these resources must be freed prior
to the thread closing.
.Pp
As of version 1.1.0 OpenSSL will automatically allocate all resources
that it needs so no explicit initialisation is required.
Similarly it will also automatically deinitialise as required.
.Pp
However, there may be situations when explicit initialisation is
desirable or needed, for example when some nondefault initialisation is
required.
The function
.Fn OPENSSL_init_crypto
can be used for this purpose for libcrypto (see also
.Xr OPENSSL_init_ssl 3
for the libssl equivalent).
.Pp
Numerous internal OpenSSL functions call
.Fn OPENSSL_init_crypto .
Therefore, in order to perform nondefault initialisation,
.Fn OPENSSL_init_crypto
MUST be called by application code prior to any other OpenSSL function
calls.
.Pp
The
.Fa opts
parameter specifies which aspects of libcrypto should be initialised.
Valid options are:
.Bl -tag -width Ds
.It OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS
Suppress automatic loading of the libcrypto error strings.
This option is not a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_crypto
with the option
.Sy OPENSSL_INIT_LOAD_CRYPTO_STRINGS
will be ignored.
.It OPENSSL_INIT_LOAD_CRYPTO_STRINGS
Automatic loading of the libcrypto error strings.
With this option the library will automatically load the libcrypto error
strings.
This option is a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_crypto
with the option
.Sy OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS
will be ignored.
.It OPENSSL_INIT_ADD_ALL_CIPHERS
With this option the library will automatically load and make available
all libcrypto ciphers.
This option is a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_crypto
with the option
.Sy OPENSSL_INIT_NO_ADD_ALL_CIPHERS
will be ignored.
.It OPENSSL_INIT_ADD_ALL_DIGESTS
With this option the library will automatically load and make available
all libcrypto digests.
This option is a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_crypto
with the option
.Sy OPENSSL_INIT_NO_ADD_ALL_DIGESTS
will be ignored.
.It OPENSSL_INIT_NO_ADD_ALL_CIPHERS
With this option the library will suppress automatic loading of
libcrypto ciphers.
This option is not a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_crypto
with the option
.Sy OPENSSL_INIT_ADD_ALL_CIPHERS
will be ignored.
.It OPENSSL_INIT_NO_ADD_ALL_DIGESTS
With this option the library will suppress automatic loading of
libcrypto digests.
This option is not a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_crypto
with the option
.Sy OPENSSL_INIT_ADD_ALL_DIGESTS
will be ignored.
.It OPENSSL_INIT_LOAD_CONFIG
With this option an OpenSSL configuration file will be automatically
loaded and used by calling
.Xr OPENSSL_config 3 .
This is a default option.
Note that in OpenSSL 1.1.1 this was the default for libssl but not for
libcrypto (see
.Xr OPENSSL_init_ssl 3
for further details about libssl initialisation).
In OpenSSL 1.1.0 this was a nondefault option for both libssl and
libcrypto.
See the description of
.Fn OPENSSL_INIT_new ,
below.
.It OPENSSL_INIT_NO_LOAD_CONFIG
With this option the loading of OpenSSL configuration files will be
suppressed.
It is the equivalent of calling
.Xr OPENSSL_no_config 3 .
This is not a default option.
.It OPENSSL_INIT_ASYNC
With this option the library with automatically initialise the libcrypto
async sub-library (see
.Xr ASYNC_start_job 3 Ns ).
This is a default option.
.It OPENSSL_INIT_ENGINE_RDRAND
With this option the library will automatically load and initialise the
RDRAND engine (if available).
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_DYNAMIC
With this option the library will automatically load and initialise the
dynamic engine.
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_OPENSSL
With this option the library will automatically load and initialise the
openssl engine.
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_CRYPTODEV
With this option the library will automatically load and initialise the
cryptodev engine (if available).
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_CAPI
With this option the library will automatically load and initialise the
CAPI engine (if available).
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_PADLOCK
With this option the library will automatically load and initialise the
padlock engine (if available).
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_AFALG
With this option the library will automatically load and initialise the
AFALG engine.
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ENGINE_ALL_BUILTIN
With this option the library will automatically load and initialise all
the built in engines listed above with the exception of the openssl and
afalg engines.
This not a default option and is deprecated in OpenSSL 3.0.
.It OPENSSL_INIT_ATFORK
With this option the library will register its fork handlers.
See OPENSSL_fork_prepare(3) for details.
.It OPENSSL_INIT_NO_ATEXIT
By default OpenSSL will attempt to clean itself up when the process
exits via an "atexit" handler.
Using this option suppresses that behaviour.
This means that the application will have to clean up OpenSSL explicitly
using
.Fn OPENSSL_cleanup .
.El
.Pp
Multiple options may be combined together in a single call to
.Fn OPENSSL_init_crypto .
For example:
.Bd -literal
 OPENSSL_init_crypto(OPENSSL_INIT_NO_ADD_ALL_CIPHERS
                     | OPENSSL_INIT_NO_ADD_ALL_DIGESTS, NULL);
.Ed
.Pp
The
.Fn OPENSSL_cleanup
function deinitialises OpenSSL (both libcrypto and libssl).
All resources allocated by OpenSSL are freed.
Typically there should be no need to call this function directly as it
is initiated automatically on application exit.
This is done via the standard C library
.Xr atexit 3
function.
In the event that the application will close in a manner that will not
call the registered
.Xr atexit 3
handlers then the application should call
.Fn OPENSSL_cleanup
directly.
Developers of libraries using OpenSSL are discouraged from calling this
function and should instead, typically, rely on auto-deinitialisation.
This is to avoid error conditions where both an application and a
library it depends on both use OpenSSL, and the library deinitialises it
before the application has finished using it.
.Pp
Once
.Fn OPENSSL_cleanup
has been called the library cannot be reinitialised.
Attempts to call
.Fn OPENSSL_init_crypto
will fail and an ERR_R_INIT_FAIL error will be added to the error stack.
Note that because initialisation has failed OpenSSL error strings will
not be available, only an error code.
This code can be put through the openssl errstr command line application
to produce a human readable error (see
.Xr openssl-errstr 1 Ns ).
.Pp
The
.Fn OPENSSL_atexit
function enables the registration of a function to be called during
.Fn OPENSSL_cleanup .
Stop handlers are called after deinitialisation of resources local to a
thread, but before other process wide resources are freed.
In the event that multiple stop handlers are registered, no guarantees
are made about the order of execution.
.Pp
The
.Fn OPENSSL_thread_stop_ex
function deallocates resources associated with the current thread for
the given OSSL_LIB_CTX
.Fa ctx .
The
.Fa ctx
parameter can be NULL in which case the default OSSL_LIB_CTX is used.
.Pp
Typically, this function will be called automatically by the library
when the thread exits as long as the OSSL_LIB_CTX has not been freed
before the thread exits.
If
.Xr OSSL_LIB_CTX_free 3
is called OPENSSL_thread_stop_ex will be called automatically for the
current thread (but not any other threads that may have used this
OSSL_LIB_CTX).
.Pp
OPENSSL_thread_stop_ex should be called on all threads that will exit
after the OSSL_LIB_CTX is freed.
Typically this is not necessary for the default OSSL_LIB_CTX (because
all resources are cleaned up on library exit) except if thread local
resources should be freed before library exit, or under the
circumstances described in the NOTES section below.
.Pp
.Fn OPENSSL_thread_stop
is the same as
.Fn OPENSSL_thread_stop_ex
except that the default OSSL_LIB_CTX is always used.
.Pp
The
.Sy OPENSSL_INIT_LOAD_CONFIG
flag will load a configuration file, as with
.Xr CONF_modules_load_file 3
with NULL filename and application name and the
.Sy CONF_MFLAGS_IGNORE_MISSING_FILE ,
.Sy CONF_MFLAGS_IGNORE_RETURN_CODES
and
.Sy CONF_MFLAGS_DEFAULT_SECTION
flags.
The filename, application name, and flags can be customized by providing
a non-null
.Vt OPENSSL_INIT_SETTINGS
object.
The object can be allocated via
.Sy OPENSSL_INIT_new() .
The
.Sy OPENSSL_INIT_set_config_filename()
function can be used to specify a nondefault filename, which is copied
and need not refer to persistent storage.
Similarly,
.Fn OPENSSL_INIT_set_config_appname
can be used to specify a nondefault application name.
Finally, OPENSSL_INIT_set_file_flags can be used to specify nondefault
flags.
If the
.Sy CONF_MFLAGS_IGNORE_RETURN_CODES
flag is not included, any errors in the configuration file will cause an
error return from
.Sy OPENSSL_init_crypto
or indirectly
.Xr OPENSSL_init_ssl 3 .
The object can be released with
.Fn OPENSSL_INIT_free
when done.
If the argument to
.Fn OPENSSL_INIT_free
is NULL, nothing is done.
.Sh NOTES
Resources local to a thread are deallocated automatically when the
thread exits (e.g.
in a pthreads environment, when
.Xr pthread_exit 3
is called).
On Windows platforms this is done in response to a DLL_THREAD_DETACH
message being sent to the libcrypto32.dll entry point.
Some windows functions may cause threads to exit without sending this
message (for example
.Xr ExitProcess 3 ) .
If the application uses such functions, then the application must free
up OpenSSL resources directly via a call to
.Fn OPENSSL_thread_stop
on each thread.
Similarly this message will also not be sent if OpenSSL is linked
statically, and therefore applications using static linking should also
call
.Fn OPENSSL_thread_stop
on each thread.
Additionally if OpenSSL is loaded dynamically via
.Xr LoadLibrary 3
and the threads are not destroyed until after
.Xr FreeLibrary 3
is called then each thread should call
.Fn OPENSSL_thread_stop
prior to the
.Xr FreeLibrary 3
call.
.Pp
On Linux/Unix where OpenSSL has been loaded via
.Xr dlopen 3
and the application is multi-threaded and if
.Xr dlclose 3
is subsequently called prior to the threads being destroyed then OpenSSL
will not be able to deallocate resources associated with those threads.
The application should either call
.Fn OPENSSL_thread_stop
on each thread prior to the
.Xr dlclose 3
call, or alternatively the original
.Xr dlopen 3
call should use the RTLD_NODELETE flag (where available on the
platform).
.Sh RETURN VALUES
The functions OPENSSL_init_crypto,
.Fn OPENSSL_atexit
and
.Fn OPENSSL_INIT_set_config_appname
return 1 on success or 0 on error.
.Sh SEE ALSO
.Xr OPENSSL_init_ssl 3
.Sh HISTORY
The
.Fn OPENSSL_init_crypto ,
.Fn OPENSSL_cleanup ,
.Fn OPENSSL_atexit ,
.Fn OPENSSL_thread_stop ,
.Fn OPENSSL_INIT_new ,
.Fn OPENSSL_INIT_set_config_appname
and
.Fn OPENSSL_INIT_free
functions were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
