.Dd 2025-09-30
.Dt OPENSSL_INIT_SSL 3ossl
.Os
.Sh NAME
.Nm OPENSSL_init_ssl
.Nd OpenSSL (libssl and libcrypto) initialisation
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo OPENSSL_init_ssl
.Fa "uint64_t opts"
.Fa "const OPENSSL_INIT_SETTINGS *settings"
.Fc
.Sh DESCRIPTION
During normal operation OpenSSL (libssl and libcrypto) will allocate
various resources at start up that must, subsequently, be freed on close
down of the library.
Additionally some resources are allocated on a per thread basis (if the
application is multi-threaded), and these resources must be freed prior
to the thread closing.
.Pp
As of version 1.1.0 OpenSSL will automatically allocate all resources
that it needs so no explicit initialisation is required.
Similarly it will also automatically deinitialise as required.
.Pp
However, there may be situations when explicit initialisation is
desirable or needed, for example when some nondefault initialisation is
required.
The function
.Fn OPENSSL_init_ssl
can be used for this purpose.
Calling this function will explicitly initialise BOTH libcrypto and
libssl.
To explicitly initialise ONLY libcrypto see the
.Xr OPENSSL_init_crypto 3
function.
.Pp
Numerous internal OpenSSL functions call
.Fn OPENSSL_init_ssl .
Therefore, in order to perform nondefault initialisation,
.Fn OPENSSL_init_ssl
MUST be called by application code prior to any other OpenSSL function
calls.
.Pp
The
.Fa opts
parameter specifies which aspects of libssl and libcrypto should be
initialised.
Valid options for libcrypto are described on the
.Xr OPENSSL_init_crypto 3
page.
In addition to any libcrypto specific option the following libssl
options can also be used:
.Bl -tag -width Ds
.It OPENSSL_INIT_NO_LOAD_SSL_STRINGS
Suppress automatic loading of the libssl error strings.
This option is not a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_ssl
with the option
.Sy OPENSSL_INIT_LOAD_SSL_STRINGS
will be ignored.
.It OPENSSL_INIT_LOAD_SSL_STRINGS
Automatic loading of the libssl error strings.
This option is a default option.
Once selected subsequent calls to
.Fn OPENSSL_init_ssl
with the option
.Sy OPENSSL_INIT_LOAD_SSL_STRINGS
will be ignored.
.El
.Pp
.Fn OPENSSL_init_ssl
takes a
.Fa settings
parameter which can be used to set parameter values.
See
.Xr OPENSSL_init_crypto 3
for details.
.Sh RETURN VALUES
The function
.Fn OPENSSL_init_ssl
returns 1 on success or 0 on error.
.Sh SEE ALSO
.Xr OPENSSL_init_crypto 3
.Sh HISTORY
The
.Fn OPENSSL_init_ssl
function was added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
