.Dd 2025-09-30
.Dt OPENSSL_GMTIME 3ossl
.Os
.Sh NAME
.Nm OPENSSL_gmtime ,
.Nm OPENSSL_gmtime_adj ,
.Nm OPENSSL_gmtime_diff
.Nd platform-agnostic OpenSSL time routines
.Sh SYNOPSIS
.In openssl/crypto.h
.Ft struct tm *
.Fo OPENSSL_gmtime
.Fa "const time_t *timer"
.Fa "struct tm *result"
.Fc
.Ft int
.Fo OPENSSL_gmtime_adj
.Fa "struct tm *tm"
.Fa "int offset_day"
.Fa "long offset_sec"
.Fc
.Ft int
.Fo OPENSSL_gmtime_diff
.Fa "int *pday"
.Fa "int *psec"
.Fa "const struct tm *from"
.Fa "const struct tm *to"
.Fc
.Sh DESCRIPTION
.Fn OPENSSL_gmtime
returns the UTC time specified by
.Fa timer
into the provided
.Fa result
argument.
.Pp
.Fn OPENSSL_gmtime_adj
adds the offsets in
.Fa offset_day
and
.Fa offset_sec
to
.Vt tm .
.Pp
.Fn OPENSSL_gmtime_diff
calculates the difference between
.Fa from
and
.Fa to .
.Sh NOTES
It is an error to call
.Fn OPENSSL_gmtime
with
.Fa result
equal to NULL. The contents of the time_t given by
.Fa timer
are stored into the
.Fa result .
Calling with
.Fa timer
equal to NULL means use the current time.
.Pp
.Fn OPENSSL_gmtime_adj
converts
.Vt tm
into a days and seconds value, adds the offsets, then converts back into
a
.Vt struct tm
specified by
.Vt tm .
Leap seconds are not considered.
.Pp
.Fn OPENSSL_gmtime_diff
calculates the difference between the two
.Vt struct tm
structures
.Fa from
and
.Fa to .
The difference in days is placed into
.Em *pday ,
the remaining seconds are placed to
.Em *psec .
The value in
.Em *psec
will be less than the number of seconds per day (3600). Leap seconds are
not considered.
.Sh RETURN VALUES
.Fn OPENSSL_gmtime
returns NULL on error, or
.Fa result
on success.
.Pp
.Fn OPENSSL_gmtime_adj
and
.Fn OPENSSL_gmtime_diff
return 0 on error, and 1 on success.
.Sh HISTORY
.Fn OPENSSL_gmtime ,
.Fn OPENSSL_gmtime_adj
and
.Fn OPENSSL_gmtime_diff
have been in OpenSSL since 1.0.0.
.Sh COPYRIGHT
Copyright 2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
