.Dd 2025-09-30
.Dt OPENSSL_STRCASECMP 3ossl
.Os
.Sh NAME
.Nm OPENSSL_strcasecmp ,
.Nm OPENSSL_strncasecmp
.Nd compare two strings ignoring case
.Sh SYNOPSIS
.In openssl/crypto.h
.Ft int
.Fo OPENSSL_strcasecmp
.Fa "const char *s1"
.Fa "const char *s2"
.Fc
.Ft int
.Fo OPENSSL_strncasecmp
.Fa "const char *s1"
.Fa "const char *s2"
.Fa "size_t n"
.Fc
.Sh DESCRIPTION
The OPENSSL_strcasecmp function performs a byte-by-byte comparison of
the strings
.Fa s1
and
.Fa s2 ,
ignoring the case of the characters.
.Pp
The OPENSSL_strncasecmp function is similar, except that it compares no
more than
.Fa n
bytes of
.Fa s1
and
.Fa s2 .
.Pp
In POSIX-compatible system and on Windows these functions use "C" locale
for case insensitive.
Otherwise the comparison is done in current locale.
.Sh RETURN VALUES
Both functions return an integer less than, equal to, or greater than
zero if s1 is found, respectively, to be less than, to match, or be
greater than s2.
.Sh NOTES
OpenSSL extensively uses case insensitive comparison of ASCII strings.
Though OpenSSL itself is locale-agnostic, the applications using OpenSSL
libraries may unpredictably suffer when they use localization (e.g.
Turkish locale is well-known with a specific I/i cases).
These functions use C locale for string comparison.
.Sh HISTORY
These functions were added in OpenSSL 3.0.3.
.Sh COPYRIGHT
Copyright 2022-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
