.Dd 2025-09-30
.Dt OPENSSL_INSTRUMENT_BUS 3ossl
.Os
.Sh NAME
.Nm OPENSSL_instrument_bus ,
.Nm OPENSSL_instrument_bus2
.Nd instrument references to memory bus
.Sh SYNOPSIS
.Fd #ifdef OPENSSL_CPUID_OBJ
.Ft size_t
.Fo OPENSSL_instrument_bus
.Fa "unsigned int *vector"
.Fa "size_t num"
.Fc
.Ft size_t
.Fo OPENSSL_instrument_bus2
.Fa "unsigned int *vector"
.Fa "size_t num"
.Fa "size_t max"
.Fc
.Fd #endif
.Sh DESCRIPTION
It was empirically found that timings of references to primary memory
are subject to irregular, apparently non-deterministic variations.
The subroutines in question instrument these references for purposes of
gathering randomness for random number generator.
In order to make it bus-bound a 'flush cache line' instruction is used
between probes.
In addition probes are added to
.Fa vector
elements in atomic or interlocked manner, which should contribute
additional noise on multi-processor systems.
This also means that
.Sy vector[num]
should be zeroed upon invocation (if you want to retrieve actual probe
values).
.Pp
.Fn OPENSSL_instrument_bus
performs
.Fa num
probes and records the number of oscillator cycles every probe took.
.Pp
.Fn OPENSSL_instrument_bus2
on the other hand
.Sy accumulates
consecutive probes with the same value, i.e.
in a way it records duration of periods when probe values appeared
deterministic.
The subroutine performs at most
.Fa max
probes in attempt to fill the
.Sy vector[num] ,
with
.Fa max
value of 0 meaning "as many as it takes."
.Sh RETURN VALUES
Return value of 0 indicates that CPU is not capable of performing the
benchmark, either because oscillator counter or 'flush cache line' is
not available on current platform.
For reference, on x86 'flush cache line' was introduced with the SSE2
extensions.
.Pp
Otherwise number of recorded values is returned.
.Sh COPYRIGHT
Copyright 2011-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
