.Dd 2025-09-30
.Dt OPENSSL_LOAD_U16_LE 3ossl
.Os
.Sh NAME
.Nm OPENSSL_load_u16_le ,
.Nm OPENSSL_load_u16_be ,
.Nm OPENSSL_load_u32_le ,
.Nm OPENSSL_load_u32_be ,
.Nm OPENSSL_load_u64_le ,
.Nm OPENSSL_load_u64_be ,
.Nm OPENSSL_store_u16_le ,
.Nm OPENSSL_store_u16_be ,
.Nm OPENSSL_store_u32_le ,
.Nm OPENSSL_store_u32_be ,
.Nm OPENSSL_store_u64_le ,
.Nm OPENSSL_store_u64_be
.Nd Read and write unsigned 16, 32 and 64-bit integers in a specific byte order
.Sh SYNOPSIS
.In openssl/byteorder.h
.Ft static ossl_inline unsigned char *
.Fo OPENSSL_store_u16_le
.Fa "         unsigned char *out"
.Fa "uint16_t val"
.Fc
.Ft static ossl_inline unsigned char *
.Fo OPENSSL_store_u16_be
.Fa "         unsigned char *out"
.Fa "uint16_t val"
.Fc
.Ft static ossl_inline unsigned char *
.Fo OPENSSL_store_u32_le
.Fa "         unsigned char *out"
.Fa "uint32_t val"
.Fc
.Ft static ossl_inline unsigned char *
.Fo OPENSSL_store_u32_be
.Fa "         unsigned char *out"
.Fa "uint32_t val"
.Fc
.Ft static ossl_inline unsigned char *
.Fo OPENSSL_store_u64_le
.Fa "         unsigned char *out"
.Fa "uint64_t val"
.Fc
.Ft static ossl_inline unsigned char *
.Fo OPENSSL_store_u64_be
.Fa "         unsigned char *out"
.Fa "uint64_t val"
.Fc
.Ft static ossl_inline const unsigned char *
.Fo OPENSSL_load_u16_le
.Fa "         uint16_t *val"
.Fa "const unsigned char *in"
.Fc
.Ft static ossl_inline const unsigned char *
.Fo OPENSSL_load_u16_be
.Fa "         uint16_t *val"
.Fa "const unsigned char *in"
.Fc
.Ft static ossl_inline const unsigned char *
.Fo OPENSSL_load_u32_le
.Fa "         uint32_t *val"
.Fa "const unsigned char *in"
.Fc
.Ft static ossl_inline const unsigned char *
.Fo OPENSSL_load_u32_be
.Fa "         uint32_t *val"
.Fa "const unsigned char *in"
.Fc
.Ft static ossl_inline const unsigned char *
.Fo OPENSSL_load_u64_le
.Fa "         uint64_t *val"
.Fa "const unsigned char *in"
.Fc
.Ft static ossl_inline const unsigned char *
.Fo OPENSSL_load_u64_be
.Fa "         uint64_t *val"
.Fa "const unsigned char *in"
.Fc
.Sh DESCRIPTION
These functions read and write 16, 32 and 64 bit unsigned integers in a
specified byte order.
The
.Qo Li _be Qc
functions use big-endian byte order, while the
.Qo Li _le Qc
functions use little-endian byte order.
They're implemented directly in the header file, and declared static.
When the compiler supports inline functions, they're also declared
inline.
An optimising compiler will often convert these to just one or two
machine instructions: a load or store with a possible byte swap.
.Pp
The
.Qo Li load Qc
functions write the decoded integer value at the address pointed to by
.Fa val ,
which must be a valid (possibly suitably aligned) address of an object
of the appropriate type.
The
.Qo Li store Qc
functions write the encoding of
.Fa val
at the address pointed to by
.Fa out .
.Pp
For convenience, these functions return the updated input or output
pointer, making it easy to continue reading or writing more data at the
next memory location.
.Pp
No bounds checks are performed, the caller is responsible for making
sure that the input or output buffers are sufficiently large for the
requested read or write.
.Sh RETURN VALUES
All these functions return the next memory address following the last
byte written or read.
.Sh HISTORY
These functions were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
