.Dd 2025-09-30
.Dt OPENSSL_HEXCHAR2INT 3ossl
.Os
.Sh NAME
.Nm OPENSSL_hexchar2int ,
.Nm OPENSSL_hexstr2buf_ex ,
.Nm OPENSSL_hexstr2buf ,
.Nm OPENSSL_buf2hexstr_ex ,
.Nm OPENSSL_buf2hexstr
.Nd Hex encoding and decoding functions
.Sh SYNOPSIS
.In openssl/crypto.h
.Ft int
.Fo OPENSSL_hexchar2int
.Fa "unsigned char c"
.Fc
.Ft int
.Fo OPENSSL_hexstr2buf_ex
.Fa "unsigned char *buf"
.Fa "size_t buf_n"
.Fa "long *buflen"
.Fa "const char *str"
.Fa "const char sep"
.Fc
.Ft unsigned char *
.Fo OPENSSL_hexstr2buf
.Fa "const char *str"
.Fa "long *len"
.Fc
.Ft int
.Fo OPENSSL_buf2hexstr_ex
.Fa "char *str"
.Fa "size_t str_n"
.Fa "size_t *strlength"
.Fa "const unsigned char *buf"
.Fa "long buflen"
.Fa "const char sep"
.Fc
.Ft char *
.Fo OPENSSL_buf2hexstr
.Fa "const unsigned char *buf"
.Fa "long buflen"
.Fc
.Sh DESCRIPTION
.Fn OPENSSL_hexchar2int
converts a hexadecimal character to its numeric equivalent.
.Pp
.Fn OPENSSL_hexstr2buf_ex
decodes the hex string
.Fa str
and places the resulting string of bytes in the given
.Fa buf .
The character
.Fa sep
is the separator between the bytes, setting this to '\e0' means that
there is no separator.
.Fa buf_n
gives the size of the buffer.
If
.Fa buflen
is not NULL, it is filled in with the result length.
To find out how large the result will be, call this function with NULL
for
.Fa buf .
Colons between two-character hex "bytes" are accepted and ignored.
An odd number of hex digits is an error.
.Pp
.Fn OPENSSL_hexstr2buf
does the same thing as
.Fn OPENSSL_hexstr2buf_ex ,
but allocates the space for the result, and returns the result.
It uses a default separator of ':'. The memory is allocated by calling
.Xr OPENSSL_malloc 3
and should be released by calling
.Xr OPENSSL_free 3 .
.Pp
.Fn OPENSSL_buf2hexstr_ex
encodes the contents of the given
.Fa buf
with length
.Fa buflen
and places the resulting hexadecimal character string in the given
.Fa str .
The character
.Fa sep
is the separator between the bytes, setting this to '\e0' means that
there is no separator.
.Fa str_n
gives the size of the of the string buffer.
If
.Fa strlength
is not NULL, it is filled in with the result length.
To find out how large the result will be, call this function with NULL
for
.Fa str .
.Pp
.Fn OPENSSL_buf2hexstr
does the same thing as
.Fn OPENSSL_buf2hexstr_ex ,
but allocates the space for the result, and returns the result.
It uses a default separator of ':'. The memory is allocated by calling
.Xr OPENSSL_malloc 3
and should be released by calling
.Xr OPENSSL_free 3 .
.Sh RETURN VALUES
OPENSSL_hexchar2int returns the value of a decoded hex character, or -1
on error.
.Pp
.Fn OPENSSL_buf2hexstr
and
.Fn OPENSSL_hexstr2buf
return a pointer to allocated memory, or NULL on error.
.Pp
.Fn OPENSSL_buf2hexstr_ex
and
.Fn OPENSSL_hexstr2buf_ex
return 1 on success, or 0 on error.
.Sh COPYRIGHT
Copyright 2016-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
