.Dd 2025-09-30
.Dt OPENSSL_VERSION 3ossl
.Os
.Sh NAME
.Nm OPENSSL_VERSION_MAJOR ,
.Nm OPENSSL_VERSION_MINOR ,
.Nm OPENSSL_VERSION_PATCH ,
.Nm OPENSSL_VERSION_PRE_RELEASE ,
.Nm OPENSSL_VERSION_BUILD_METADATA ,
.Nm OPENSSL_VERSION_TEXT ,
.Nm OPENSSL_VERSION_PREREQ ,
.Nm OPENSSL_version_major ,
.Nm OPENSSL_version_minor ,
.Nm OPENSSL_version_patch ,
.Nm OPENSSL_version_pre_release ,
.Nm OPENSSL_version_build_metadata ,
.Nm OpenSSL_version ,
.Nm OPENSSL_VERSION_NUMBER ,
.Nm OpenSSL_version_num ,
.Nm OPENSSL_info
.Nd get OpenSSL version number and other information
.Sh SYNOPSIS
.In openssl/opensslv.h
.Fd #define OPENSSL_VERSION_MAJOR  x
.Fd #define OPENSSL_VERSION_MINOR  y
.Fd #define OPENSSL_VERSION_PATCH  z
.Ft /* The definitions here are typical release values */
 #define OPENSSL_VERSION_PRE_RELEASE ""
 #define OPENSSL_VERSION_BUILD_METADATA ""

 #define OPENSSL_VERSION_TEXT "OpenSSL x.y.z xx XXX xxxx"

 #define
.Fo OPENSSL_VERSION_PREREQ
.Fa maj
.Fa min
.Fc
.In openssl/crypto.h
.Ft unsigned int
.Fo OPENSSL_version_major
.Fa void
.Fc
.Ft unsigned int
.Fo OPENSSL_version_minor
.Fa void
.Fc
.Ft unsigned int
.Fo OPENSSL_version_patch
.Fa void
.Fc
.Ft const char *
.Fo OPENSSL_version_pre_release
.Fa void
.Fc
.Ft const char *
.Fo OPENSSL_version_build_metadata
.Fa void
.Fc
.Ft const char *
.Fo OpenSSL_version
.Fa "int t"
.Fc
.Ft const char *
.Fo OPENSSL_info
.Fa "int t"
.Fc
.Ft /* from openssl/opensslv.h */
 #define OPENSSL_VERSION_NUMBER 0xnnnnnnnnL

 /* from openssl/crypto.h */
 unsigned long
.Fo OpenSSL_version_num
.Fa 
.Fc
.Sh DESCRIPTION
.Ss Macros
The three macros
.Sy OPENSSL_VERSION_MAJOR ,
.Sy OPENSSL_VERSION_MINOR
and
.Sy OPENSSL_VERSION_PATCH
represent the three parts of a version identifier,
.Sy Em MAJOR Ns . Ns Em MINOR Ns . Ns Em PATCH .
.Pp
The macro
.Sy OPENSSL_VERSION_PRE_RELEASE
is an added bit of text that indicates that this is a pre-release
version, such as
.Qo Li \(dq-dev" Qc
for an ongoing development snapshot or
.Qo Li \(dq-alpha3" Qc
for an alpha release.
The value must be a string.
.Pp
The macro
.Sy OPENSSL_VERSION_BUILD_METADATA
is extra information, reserved for other parties, such as
.Qo Li \(dq+fips" Qc ,
or
.Qo Li \(dq+vendor.1" Qc Ns ).
The OpenSSL project will not touch this macro (will leave it an empty
string).
The value must be a string.
.Pp
.Sy OPENSSL_VERSION_STR
is a convenience macro to get the short version identifier string,
.Qo Li \(dq Ns Em MAJOR Ns . Ns Em MINOR Ns . Ns Em PATCH Ns \(dq Qc .
.Pp
.Sy OPENSSL_FULL_VERSION_STR
is a convenience macro to get the longer version identifier string,
which combines
.Sy OPENSSL_VERSION_STR ,
.Sy OPENSSL_VERSION_PRE_RELEASE
and
.Sy OPENSSL_VERSION_BUILD_METADATA .
.Pp
.Sy OPENSSL_VERSION_TEXT
is a convenience macro to get a full descriptive version text, which
includes
.Sy OPENSSL_FULL_VERSION_STR
and the release date.
.Pp
.Sy OPENSSL_VERSION_PREREQ
is a useful macro for checking whether the OpenSSL version for the
headers in use is at least at the given pre-requisite major
.Pf ( Vt maj )
and minor
.Pf ( Vt min )
number or not.
It will evaluate to true if the header version number
.Pf ( Sy OPENSSL_VERSION_MAJOR Ns . Ns Sy OPENSSL_VERSION_MINOR )
is greater than or equal to
.Vt maj Ns . Ns Vt min .
.Pp
.Sy OPENSSL_VERSION_NUMBER
is a combination of the major, minor and patch version into a single
integer 0xMNN00PP0L, where:
.Bl -tag -width Ds
.It M
is the number from
.Sy OPENSSL_VERSION_MAJOR ,
in hexadecimal notation
.It NN
is the number from
.Sy OPENSSL_VERSION_MINOR ,
in hexadecimal notation
.It PP
is the number from
.Sy OPENSSL_VERSION_PATCH ,
in hexadecimal notation
.El
.Ss Functions
.Fn OPENSSL_version_major ,
.Fn OPENSSL_version_minor ,
.Fn OPENSSL_version_patch ,
.Fn OPENSSL_version_pre_release ,
and
.Fn OPENSSL_version_build_metadata
return the values of the macros above for the build of the library,
respectively.
.Pp
.Fn OpenSSL_version
returns different strings depending on
.Fa t :
.Bl -tag -width Ds
.It OPENSSL_VERSION
The value of
.Sy OPENSSL_VERSION_TEXT
.It OPENSSL_VERSION_STRING
The value of
.Sy OPENSSL_VERSION_STR
.It OPENSSL_FULL_VERSION_STRING
The value of
.Sy OPENSSL_FULL_VERSION_STR
.It OPENSSL_CFLAGS
The compiler flags set for the compilation process in the form
.Qo Li compiler: ... Qc
if available, or
.Qo Li compiler: information not available Qc
otherwise.
.It OPENSSL_BUILT_ON
The date of the build process in the form
.Qo Li built on: ... Qc
if available or
.Qo Li built on: date not available Qc
otherwise.
The date would not be available in a reproducible build, for example.
.It OPENSSL_PLATFORM
The "Configure" target of the library build in the form
.Qo Li platform: ... Qc
if available, or
.Qo Li platform: information not available Qc
otherwise.
.It OPENSSL_DIR
The
.Sy OPENSSLDIR
setting of the library build in the form
.Qo Li OPENSSLDIR: \(dq..." Qc
if available, or
.Qo Li OPENSSLDIR: N/A Qc
otherwise.
.It OPENSSL_ENGINES_DIR
The
.Sy ENGINESDIR
setting of the library build in the form
.Qo Li ENGINESDIR: \(dq..." Qc
if available, or
.Qo Li ENGINESDIR: N/A Qc
otherwise.
This option is deprecated in OpenSSL 3.0.
.It OPENSSL_MODULES_DIR
The
.Sy MODULESDIR
setting of the library build in the form
.Qo Li MODULESDIR: \(dq..." Qc
if available, or
.Qo Li MODULESDIR: N/A Qc
otherwise.
.It OPENSSL_CPU_INFO
The current OpenSSL cpu settings.
This is the current setting of the cpu capability flags.
It is usually automatically configured but may be set via an environment
variable.
The value has the same syntax as the environment variable.
For x86 the string looks like
.Qo Li CPUINFO: OPENSSL_ia32cap=0x123:0x456 Qc
or
.Qo Li CPUINFO: N/A Qc
if not available.
.It OPENSSL_WINCTX
The Windows install context.
The Windows install context is used to compute the OpenSSL registry key
name on Windows.
The full registry key is
.Qo Li SOFTWARE\eWOW6432Node\eOpenSSL-{major}.{minor}-{context} Qc ,
where
.Qo Li {major} Qc ,
.Qo Li {minor} Qc
and
.Qo Li {context} Qc
are OpenSSL's major version number, minor version number and the Windows
install context, respectively.
.El
.Pp
For an unknown
.Fa t ,
the text
.Qo Li not available Qc
is returned.
.Pp
.Fn OPENSSL_info
also returns different strings depending on
.Fa t :
.Bl -tag -width Ds
.It OPENSSL_INFO_CONFIG_DIR
The configured
.Qo Li OPENSSLDIR Qc ,
which is the default location for OpenSSL configuration files.
.It OPENSSL_INFO_ENGINES_DIR
The configured
.Qo Li ENGINESDIR Qc ,
which is the default location for OpenSSL engines.
.It OPENSSL_INFO_MODULES_DIR
The configured
.Qo Li MODULESDIR Qc ,
which is the default location for dynamically loadable OpenSSL modules
other than engines.
.It OPENSSL_INFO_DSO_EXTENSION
The configured dynamically loadable module extension.
.It OPENSSL_INFO_DIR_FILENAME_SEPARATOR
The separator between a directory specification and a filename.
Note that on some operating systems, this is not the same as the
separator between directory elements.
.It OPENSSL_INFO_LIST_SEPARATOR
The OpenSSL list separator.
This is typically used in strings that are lists of items, such as the
value of the environment variable
.Qo Li $PATH Qc
on Unix (where the separator is
.Qo Li : Qc )
or
.Qo Li %PATH% Qc
on Windows (where the separator is
.Qo Li ; Qc Ns ).
.It OPENSSL_INFO_CPU_SETTINGS
The current OpenSSL cpu settings.
This is the current setting of the cpu capability flags.
It is usually automatically configured but may be set via an environment
variable.
The value has the same syntax as the environment variable.
For x86 the string looks like
.Qo Li OPENSSL_ia32cap=0x123:0x456 Qc .
.It OPENSSL_INFO_WINDOWS_CONTEXT
The Windows install context.
The Windows install context is used to compute the OpenSSL registry key
name on Windows.
The full registry key is
.Qo Li SOFTWARE\eWOW6432Node\eOpenSSL-{major}.{minor}-{context} Qc ,
where
.Qo Li {major} Qc ,
.Qo Li {minor} Qc
and
.Qo Li {context} Qc
are OpenSSL's major version number, minor version number and the Windows
install context, respectively.
.El
.Pp
For an unknown
.Fa t ,
NULL is returned.
.Pp
.Fn OpenSSL_version_num
returns the value of
.Sy OPENSSL_VERSION_NUMBER .
.Sh RETURN VALUES
.Fn OPENSSL_version_major ,
.Fn OPENSSL_version_minor
and
.Fn OPENSSL_version_patch
return the version number parts as integers.
.Pp
.Fn OPENSSL_version_pre_release
and
.Fn OPENSSL_version_build_metadata
return the values of
.Sy OPENSSL_VERSION_PRE_RELEASE
and
.Sy OPENSSL_VERSION_BUILD_METADATA
respectively as constant strings.
For any of them that is undefined, the empty string is returned.
.Pp
.Fn OpenSSL_version
returns constant strings.
.Sh SEE ALSO
.Xr crypto 7
.Sh HISTORY
The macros and functions described here were added in OpenSSL 3.0,
except for OPENSSL_VERSION_NUMBER and
.Fn OpenSSL_version_num .
.Sh BUGS
There was a discrepancy between this manual and commentary + code in
.Pa <openssl/opensslv.h> ,
where the latter suggested that the four least significant bits of
.Sy OPENSSL_VERSION_NUMBER
could be
.Qo Li 0x0f Qc
in released OpenSSL versions.
.Sh COPYRIGHT
Copyright 2018-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
