.Dd 2025-09-30
.Dt OSSL_CMP_HDR_GET0_TRANSACTIONID 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_HDR_get0_transactionID ,
.Nm OSSL_CMP_HDR_get0_recipNonce ,
.Nm OSSL_CMP_HDR_get0_geninfo_ITAVs
.Nd functions manipulating CMP message headers
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft ASN1_OCTET_STRING *
.Fo OSSL_CMP_HDR_get0_transactionID
.Fa "const                                                      OSSL_CMP_PKIHEADER *hdr"
.Fc
.Ft ASN1_OCTET_STRING *
.Fo OSSL_CMP_HDR_get0_recipNonce
.Fa "const                                                   OSSL_CMP_PKIHEADER *hdr"
.Fc
.Bd -literal
 STACK_OF(OSSL_CMP_ITAV)
     *OSSL_CMP_HDR_get0_geninfo_ITAVs(const OSSL_CMP_PKIHEADER *hdr);
.Ed
.Sh DESCRIPTION
OSSL_CMP_HDR_get0_transactionID returns the transaction ID of the given
PKIHeader.
.Pp
OSSL_CMP_HDR_get0_recipNonce returns the recipient nonce of the given
PKIHeader.
.Pp
.Xr OSSL_CMP_HDR_get0_geninfo_ITAVs 3
returns the list of ITAVs in the generalInfo field of the given
PKIHeader.
.Sh NOTES
CMP is defined in RFC 4210.
.Sh RETURN VALUES
The functions return the intended pointer value as described above or
NULL if the respective entry does not exist and on error.
.Sh HISTORY
The OpenSSL CMP support was added in OpenSSL 3.0.
.Pp
.Xr OSSL_CMP_HDR_get0_geninfo_ITAVs 3
was added in OpenSSL 3.3.
.Sh COPYRIGHT
Copyright 2007-2019 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
