.Dd 2025-09-30
.Dt OSSL_CMP_MSG_HTTP_PERFORM 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_MSG_http_perform
.Nd client-side HTTP(S) transfer of a CMP request-response pair
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft OSSL_CMP_MSG *
.Fo OSSL_CMP_MSG_http_perform
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const OSSL_CMP_MSG *req"
.Fc
.Sh DESCRIPTION
.Fn OSSL_CMP_MSG_http_perform
sends the given PKIMessage
.Fa req
to the CMP server specified in
.Fa ctx
and returns the result obtained from it.
.Pp
If
.Xr OSSL_CMP_CTX_set_transfer_cb_arg 3
has been used to set the transfer callback argument then the provided
pointer
.Em bios
is taken as a two-element
.Sy BIO
array to use for the exchange with the server as described for the
.Em bio
and
.Em rbio
parameters of
.Xr OSSL_HTTP_open 3 .
For instance, the two BIO pointers may be equal and refer to a TLS
connection, such as in BRSKI-AE where a pre-established TLS channel is
reused for CMP.
.Pp
Otherwise the server specified via
.Xr OSSL_CMP_CTX_set1_server 3
and optionally
.Xr OSSL_CMP_CTX_set_serverPort 3
is contacted, where the default port is 80 for HTTP and 443 for HTTPS.
The HTTP path (aka "CMP alias" in this context) to use is by default
.Qo Li / Qc ,
otherwise the string specified via
.Xr OSSL_CMP_CTX_set1_serverPath 3 .
On success the function returns the server's response PKIMessage.
.Pp
The function makes use of any HTTP callback function set via
.Xr OSSL_CMP_CTX_set_http_cb 3 .
It respects any timeout value set via
.Xr OSSL_CMP_CTX_set_option 3
with an
.Sy OSSL_CMP_OPT_MSG_TIMEOUT
argument.
It also respects any HTTP(S) proxy options set via
.Xr OSSL_CMP_CTX_set1_proxy 3
and
.Xr OSSL_CMP_CTX_set1_no_proxy 3
and the respective environment variables.
Proxying plain HTTP is supported directly, while using a proxy for HTTPS
connections requires a suitable callback function such as
.Xr OSSL_HTTP_proxy_connect 3 .
.Sh NOTES
CMP is defined in RFC 4210. HTTP transfer for CMP is defined in RFC
6712.
.Sh RETURN VALUES
.Fn OSSL_CMP_MSG_http_perform
returns the received CMP response message on success, else NULL.
.Sh SEE ALSO
.Xr OSSL_CMP_CTX_new 3 ,
.Xr OSSL_HTTP_open 3 ,
and
.Xr OSSL_HTTP_proxy_connect 3 .
.Sh HISTORY
The OpenSSL CMP support was added in OpenSSL 3.0.
.Pp
The
.Fn OSSL_CMP_MSG_http_perform
use of transfer_cb_arg was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2007-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
