.Dd 2025-09-30
.Dt OSSL_PARAM_PRINT_TO_BIO 3ossl
.Os
.Sh NAME
.Nm OSSL_PARAM_print_to_bio
.Nd OSSL_PARAM interrogation utilities
.Sh SYNOPSIS
.In openssl/params.h
.Ft int
.Fo OSSL_PARAM_print_to_bio
.Fa "const OSSL_PARAM *p"
.Fa "BIO *bio"
.Fa "int print_values"
.Fc
.Sh DESCRIPTION
.Fn OSSL_PARAM_print_to_bio
formats each parameter contained in the passed in array of
.Sy OSSL_PARAM
values
.Fa p ,
and prints both the key, and optionally its value, to a provided
.Vt BIO .
.Fa p
must be a non-null array of OSSL_PARAM values, terminated with a value
containing a null
.Em key
member.
.Fa print_values
is a control parameter, indicating that key values should be printed, in
addition to key names.
.Sh RETURN VALUES
.Fn OSSL_PARAM_print_to_bio
returns 1 on success, and 0 on failure
.Sh HISTORY
.Fn OSSL_PARAM_print_to_bio
was added in OpenSSL 3.5
.Sh COPYRIGHT
Copyright 2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
