.Dd 2025-09-30
.Dt OSSL_CRMF_PBMP_NEW 3ossl
.Os
.Sh NAME
.Nm OSSL_CRMF_pbm_new ,
.Nm OSSL_CRMF_pbmp_new
.Nd functions for producing Password-Based MAC (PBM)
.Sh SYNOPSIS
.In openssl/crmf.h
.Ft int
.Fo OSSL_CRMF_pbm_new
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "const OSSL_CRMF_PBMPARAMETER *pbmp"
.Fa "const unsigned char *msg"
.Fa "size_t msglen"
.Fa "const unsigned char *sec"
.Fa "size_t seclen"
.Fa "unsigned char **mac"
.Fa "size_t *maclen"
.Fc
.Ft OSSL_CRMF_PBMPARAMETER *
.Fo OSSL_CRMF_pbmp_new
.Fa "OSSL_LIB_CTX *libctx"
.Fa "size_t saltlen"
.Fa "int owfnid"
.Fa "size_t itercnt"
.Fa "int macnid"
.Fc
.Sh DESCRIPTION
.Fn OSSL_CRMF_pbm_new
generates a PBM (Password-Based MAC) based on given PBM parameters
.Fa pbmp ,
message
.Fa msg ,
and secret
.Fa sec ,
along with the respective lengths
.Fa msglen
and
.Fa seclen .
The optional library context
.Fa libctx
and
.Fa propq
parameters may be used to influence the selection of the MAC algorithm
referenced in the
.Fa pbmp ;
see
.Xr crypto 7
for further information.
On success writes the address of the newly allocated MAC via the
.Fa mac
reference parameter and writes the length via the
.Fa maclen
reference parameter unless it its NULL.
.Pp
.Fn OSSL_CRMF_pbmp_new
initializes and returns a new
.Sy PBMParameter
structure with a new random salt of given length
.Fa saltlen ,
OWF (one-way function) NID
.Fa owfnid ,
OWF iteration count
.Fa itercnt ,
and MAC NID
.Fa macnid .
The library context
.Fa libctx
parameter may be used to select the provider for the random number
generation (DRBG) and may be NULL for the default.
.Sh NOTES
The algorithms for the OWF (one-way function) and for the MAC (message
authentication code) may be any with a NID defined in
.Pa <openssl/objects.h> .
As specified by RFC 4210, these should include NID_hmac_sha1.
.Pp
RFC 4210 recommends that the salt SHOULD be at least 8 bytes (64 bits)
long, where 16 bytes is common.
.Pp
The iteration count must be at least 100, as stipulated by RFC 4211, and
is limited to at most 100000 to avoid DoS through manipulated or
otherwise malformed input.
.Sh RETURN VALUES
.Fn OSSL_CRMF_pbm_new
returns 1 on success, 0 on error.
.Pp
.Fn OSSL_CRMF_pbmp_new
returns a new and initialized OSSL_CRMF_PBMPARAMETER structure, or NULL
on error.
.Sh EXAMPLES
.Bd -literal
 OSSL_CRMF_PBMPARAMETER *pbm = NULL;
 unsigned char *msg = "Hello";
 unsigned char *sec = "SeCrEt";
 unsigned char *mac = NULL;
 size_t maclen;

 if ((pbm = OSSL_CRMF_pbmp_new(16, NID_sha256, 500, NID_hmac_sha1) == NULL))
     goto err;
 if (!OSSL_CRMF_pbm_new(pbm, msg, 5, sec, 6, &mac, &maclen))
     goto err;
.Ed
.Sh SEE ALSO
RFC 4211 section 4.4
.Sh HISTORY
The OpenSSL CRMF support was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2007-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
