.Dd 2025-09-30
.Dt OSSL_HTTP_PARSE_URL 3ossl
.Os
.Sh NAME
.Nm OSSL_HTTP_adapt_proxy ,
.Nm OSSL_parse_url ,
.Nm OSSL_HTTP_parse_url ,
.Nm OCSP_parse_url
.Nd http utility functions
.Sh SYNOPSIS
.In openssl/http.h
.Ft const char *
.Fo OSSL_HTTP_adapt_proxy
.Fa "const char *proxy"
.Fa "const char *no_proxy"
.Fa "const char *server"
.Fa "int use_ssl"
.Fc
.Ft int
.Fo OSSL_parse_url
.Fa "const char *url"
.Fa "char **pscheme"
.Fa "char **puser"
.Fa "char **phost"
.Fa "char **pport"
.Fa "int *pport_num"
.Fa "char **ppath"
.Fa "char **pquery"
.Fa "char **pfrag"
.Fc
.Ft int
.Fo OSSL_HTTP_parse_url
.Fa "const char *url"
.Fa "int *pssl"
.Fa "char **puser"
.Fa "char **phost"
.Fa "char **pport"
.Fa "int *pport_num"
.Fa "char **ppath"
.Fa "char **pquery"
.Fa "char **pfrag"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo OCSP_parse_url
.Fa "const char *url"
.Fa "char **phost"
.Fa "char **pport"
.Fa "char **ppath"
.Fa "int *pssl"
.Fc
.Sh DESCRIPTION
.Fn OSSL_HTTP_adapt_proxy
takes an optional proxy hostname
.Fa proxy
and returns it transformed according to the optional
.Fa no_proxy
parameter,
.Fa server ,
.Fa use_ssl ,
and the applicable environment variable, as follows.
If
.Fa proxy
is NULL, take any default value from the
.Qo Li http_proxy Qc
environment variable, or from
.Qo Li https_proxy Qc
if
.Fa use_ssl
is nonzero.
If this still does not yield a proxy hostname, take any further default
value from the
.Qo Li HTTP_PROXY Qc
environment variable, or from
.Qo Li HTTPS_PROXY Qc
if
.Fa use_ssl
is nonzero.
If
.Fa no_proxy
is NULL, take any default exclusion value from the
.Qo Li no_proxy Qc
environment variable, or else from
.Qo Li NO_PROXY Qc .
Return the determined proxy host unless the exclusion value, which is a
list of proxy hosts separated by
.Qo Li , Qc
and/or whitespace, contains
.Fa server .
Otherwise return NULL. When
.Fa server
is a string delimited by
.Qo Li [ Qc
and
.Qo Li ] Qc ,
which are used for IPv6 addresses, the enclosing
.Qo Li [ Qc
and
.Qo Li ] Qc
are stripped prior to comparison.
.Pp
.Fn OSSL_parse_url
parses its input string
.Fa url
as a URL of the form
.Qo Li [scheme://][userinfo@]host[:port][/path][?query][#fragment] Qc
and splits it up into scheme, userinfo, host, port, path, query, and
fragment components.
The host (or server) component may be a DNS name or an IP address where
IPv6 addresses must be enclosed in square brackets
.Qo Li [ Qc
and
.Qo Li ] Qc .
The port component is optional and defaults to
.Qo Li 0 Qc .
If given, it must be in decimal form.
If the
.Fa pport_num
argument is not NULL the integer value of the port number is assigned to
.Em *pport_num
on success.
The path component is also optional and defaults to
.Qo Li / Qc .
Each non-NULL result pointer argument
.Fa pscheme ,
.Fa puser ,
.Fa phost ,
.Fa pport ,
.Fa ppath ,
.Fa pquery ,
and
.Fa pfrag ,
is assigned the respective url component.
Any IPv6 address in
.Em *phost
is enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
On success, they are guaranteed to contain non-NULL string pointers,
else NULL. It is the responsibility of the caller to free them using
.Xr OPENSSL_free 3 .
If
.Fa pquery
is NULL, any given query component is handled as part of the path.
A string returned via
.Em *ppath
is guaranteed to begin with a
.Qo Li / Qc
character.
For absent scheme, userinfo, port, query, and fragment components an
empty string is provided.
.Pp
.Fn OSSL_HTTP_parse_url
is a special form of
.Fn OSSL_parse_url
where the scheme, if given, must be
.Qo Li http Qc
or
.Qo Li https Qc .
If
.Fa pssl
is not NULL,
.Em *pssl
is assigned 1 in case parsing was successful and the scheme is
.Qo Li https Qc ,
else 0. The port component is optional and defaults to
.Qo Li 443 Qc
if the scheme is
.Qo Li https Qc ,
else
.Qo Li 80 Qc .
Note that relative paths must be given with a leading
.Qo Li / Qc ,
otherwise the first path element is interpreted as the host.
.Pp
Calling the deprecated function OCSP_parse_url(url, host, port, path,
ssl) is equivalent to OSSL_HTTP_parse_url(url, ssl, NULL, host, port,
NULL, path, NULL, NULL).
.Sh RETURN VALUES
.Fn OSSL_HTTP_adapt_proxy
returns NULL if no proxy is to be used, otherwise a constant proxy
hostname string, which is either the proxy name handed in or an
environment variable value.
.Pp
.Fn OSSL_parse_url ,
.Fn OSSL_HTTP_parse_url ,
and
.Fn OCSP_parse_url
return 1 on success, 0 on error.
.Sh SEE ALSO
.Xr OSSL_HTTP_transfer 3
.Sh HISTORY
.Fn OSSL_HTTP_adapt_proxy ,
.Fn OSSL_parse_url
and
.Fn OSSL_HTTP_parse_url
were added in OpenSSL 3.0.
.Fn OCSP_parse_url
was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
