.Dd 2025-09-30
.Dt OSSL_CALLBACK 3ossl
.Os
.Sh NAME
.Nm OSSL_CALLBACK ,
.Nm OSSL_PASSPHRASE_CALLBACK
.Nd OpenSSL Core type to define callbacks
.Sh SYNOPSIS
.In openssl/core.h
.Ft typedef int
.Fo 
.Fa OSSL_CALLBACK
.Fc
(const OSSL_PARAM params[], void *arg);
.Ft typedef int
.Fo 
.Fa OSSL_PASSPHRASE_CALLBACK
.Fc
(char *pass, size_t pass_size,
.Bd -literal
                                        size_t *pass_len,
                                        const OSSL_PARAM params[],
                                        void *arg);
.Ed
.Sh DESCRIPTION
For certain events or activities, provider functionality may need help
from the application or the calling OpenSSL libraries themselves.
For example, user input or direct (possibly optional) user output could
be implemented this way.
.Pp
Callback functions themselves are always provided by or through the
calling OpenSSL libraries, along with a generic pointer to data
.Em arg .
As far as the function receiving the pointer to the function pointer and
.Em arg
is concerned, the data that
.Em arg
points at is opaque, and the pointer should simply be passed back to the
callback function when it's called.
.Bl -tag -width Ds
.It Vt OSSL_CALLBACK
This is a generic callback function.
When calling this callback function, the caller is expected to build an
.Xr OSSL_PARAM 3
array of data it wants or is expected to pass back, and pass that as
.Em params ,
as well as the opaque data pointer it received, as
.Em arg .
.It Vt OSSL_PASSPHRASE_CALLBACK
This is a specialised callback function, used specifically to prompt the
user for a passphrase.
When calling this callback function, a buffer to store the pass phrase
needs to be given with
.Em pass ,
and its size with
.Em pass_size .
The length of the prompted pass phrase will be given back in
.Em *pass_len .
.Pp
Additional parameters can be passed with the
.Xr OSSL_PARAM 3
array
.Em params ,
.El
.Sh RETURN VALUES
Functions of type
.Vt OSSL_CALLBACK
and
.Vt OSSL_PASSPHRASE_CALLBACK
must return 1 on success and 0 on failure.
.Sh SEE ALSO
.Xr openssl-core.h 7
.Sh HISTORY
The types described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2022-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
