.Dd 2025-09-30
.Dt OSSL_PROVIDER 3ossl
.Os
.Sh NAME
.Nm OSSL_PROVIDER_set_default_search_path ,
.Nm OSSL_PROVIDER_get0_default_search_path ,
.Nm OSSL_PROVIDER ,
.Nm OSSL_PROVIDER_load ,
.Nm OSSL_PROVIDER_try_load ,
.Nm OSSL_PROVIDER_unload ,
.Nm OSSL_PROVIDER_load_ex ,
.Nm OSSL_PROVIDER_try_load_ex ,
.Nm OSSL_PROVIDER_available ,
.Nm OSSL_PROVIDER_do_all ,
.Nm OSSL_PROVIDER_gettable_params ,
.Nm OSSL_PROVIDER_get_params ,
.Nm OSSL_PROVIDER_query_operation ,
.Nm OSSL_PROVIDER_unquery_operation ,
.Nm OSSL_PROVIDER_get0_provider_ctx ,
.Nm OSSL_PROVIDER_get0_dispatch ,
.Nm OSSL_PROVIDER_add_builtin ,
.Nm OSSL_PROVIDER_get0_name ,
.Nm OSSL_PROVIDER_get_capabilities ,
.Nm OSSL_PROVIDER_add_conf_parameter ,
.Nm OSSL_PROVIDER_get_conf_parameters ,
.Nm OSSL_PROVIDER_conf_get_bool ,
.Nm OSSL_PROVIDER_self_test
.Nd provider routines
.Sh SYNOPSIS
.In openssl/provider.h
.Ft typedef struct ossl_provider_st OSSL_PROVIDER;

 int
.Fo OSSL_PROVIDER_set_default_search_path
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *path"
.Fc
.Ft const char *
.Fo OSSL_PROVIDER_get0_default_search_path
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft OSSL_PROVIDER *
.Fo OSSL_PROVIDER_load
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *name"
.Fc
.Ft OSSL_PROVIDER *
.Fo OSSL_PROVIDER_load_ex
.Fa "OSSL_LIB_CTX *"
.Fa "const char *name"
.Fa "OSSL_PARAM *params"
.Fc
.Ft OSSL_PROVIDER *
.Fo OSSL_PROVIDER_try_load
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *name"
.Fa "int retain_fallbacks"
.Fc
.Ft OSSL_PROVIDER *
.Fo OSSL_PROVIDER_try_load_ex
.Fa "OSSL_LIB_CTX *"
.Fa "const char *name"
.Fa "OSSL_PARAM *params"
.Fa "int retain_fallbacks"
.Fc
.Ft int
.Fo OSSL_PROVIDER_unload
.Fa "OSSL_PROVIDER *prov"
.Fc
.Ft int
.Fo OSSL_PROVIDER_available
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *name"
.Fc
.Ft int
.Fo OSSL_PROVIDER_do_all
.Fa "OSSL_LIB_CTX *ctx"
.Fa "int (*cb)(OSSL_PROVIDER *provider"
.Fa "void *cbdata)"
.Fa "void *cbdata"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_PROVIDER_gettable_params
.Fa "OSSL_PROVIDER *prov"
.Fc
.Ft int
.Fo OSSL_PROVIDER_get_params
.Fa "OSSL_PROVIDER *prov"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft const OSSL_ALGORITHM *
.Fo OSSL_PROVIDER_query_operation
.Fa "const OSSL_PROVIDER *prov"
.Fa "int operation_id"
.Fa "int *no_cache"
.Fc
.Ft void
.Fo OSSL_PROVIDER_unquery_operation
.Fa "const OSSL_PROVIDER *prov"
.Fa "int operation_id"
.Fa "const OSSL_ALGORITHM *algs"
.Fc
.Ft void *
.Fo OSSL_PROVIDER_get0_provider_ctx
.Fa "const OSSL_PROVIDER *prov"
.Fc
.Ft const OSSL_DISPATCH *
.Fo OSSL_PROVIDER_get0_dispatch
.Fa "const OSSL_PROVIDER *prov"
.Fc
.Ft int
.Fo OSSL_PROVIDER_add_builtin
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *name"
.Fa "ossl_provider_init_fn *init_fn"
.Fc
.Ft const char *
.Fo OSSL_PROVIDER_get0_name
.Fa "const OSSL_PROVIDER *prov"
.Fc
.Ft int
.Fo OSSL_PROVIDER_get_capabilities
.Fa "const OSSL_PROVIDER *prov"
.Fa "const char *capability"
.Fa "OSSL_CALLBACK *cb"
.Fa "void *arg"
.Fc
.Ft int
.Fo OSSL_PROVIDER_add_conf_parameter
.Fa "OSSL_PROVIDER *prov"
.Fa "const char *name"
.Fa "const char *value"
.Fc
.Ft int
.Fo OSSL_PROVIDER_get_conf_parameters
.Fa "OSSL_PROVIDER *prov"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_PROVIDER_conf_get_bool
.Fa "const OSSL_PROVIDER *prov"
.Fa "const char *name"
.Fa "int defval"
.Fc
.Ft int
.Fo OSSL_PROVIDER_self_test
.Fa "const OSSL_PROVIDER *prov"
.Fc
.Sh DESCRIPTION
.Vt OSSL_PROVIDER
is a type that holds internal information about implementation providers
(see
.Xr provider 7
for information on what a provider is).
A provider can be built in to the application or the OpenSSL libraries,
or can be a loadable module.
The functions described here handle both forms.
.Pp
Some of these functions operate within a library context, please see
.Xr OSSL_LIB_CTX 3
for further details.
.Ss Functions
.Fn OSSL_PROVIDER_set_default_search_path
specifies the default search
.Fa path
that is to be used for looking for providers in the specified
.Fa libctx .
If left unspecified, an environment variable and a fall back default
value will be used instead.
.Pp
.Fn OSSL_PROVIDER_get0_default_search_path
retrieves the default search
.Fa path
that is to be used for looking for providers in the specified
.Fa libctx .
If successful returns the path or empty string; the path is valid until
the context is released or
.Fn OSSL_PROVIDER_set_default_search_path
is called.
.Pp
.Fn OSSL_PROVIDER_add_builtin
is used to add a built in provider to
.Vt OSSL_PROVIDER
store in the given library context, by associating a provider name with
a provider initialization function.
This name can then be used with
.Fn OSSL_PROVIDER_load .
.Pp
.Fn OSSL_PROVIDER_load
loads and initializes a provider.
This may simply initialize a provider that was previously added with
.Fn OSSL_PROVIDER_add_builtin
and run its given initialization function, or load a provider module
with the given name and run its provider entry point,
.Qo Li OSSL_provider_init Qc .
The
.Fa name
can be a path to a provider module, in that case the provider name as
returned by
.Fn OSSL_PROVIDER_get0_name
will be the path.
Interpretation of relative paths is platform dependent and they are
relative to the configured "MODULESDIR" directory or the path set in the
environment variable OPENSSL_MODULES if set.
.Pp
.Fn OSSL_PROVIDER_try_load
functions like
.Fn OSSL_PROVIDER_load ,
except that it does not disable the fallback providers if the provider
cannot be loaded and initialized or if
.Fa retain_fallbacks
is nonzero.
If the provider loads successfully and
.Fa retain_fallbacks
is zero, the fallback providers are disabled.
.Pp
.Fn OSSL_PROVIDER_load_ex
and
.Fn OSSL_PROVIDER_try_load_ex
are the variants of the previous functions accepting an
.Qo Li OSSL_PARAM Qc
array of the parameters that are passed as the configuration of the
loaded provider.
The parameters of any type but
.Qo Li OSSL_PARAM_UTF8_STRING Qc
are silently ignored.
If the parameters are provided, they replace
.Sy all
the ones specified in the configuration file.
.Pp
.Fn OSSL_PROVIDER_unload
unloads the given provider.
For a provider added with
.Fn OSSL_PROVIDER_add_builtin ,
this simply runs its teardown function.
.Pp
.Fn OSSL_PROVIDER_available
checks if a named provider is available for use.
.Pp
.Fn OSSL_PROVIDER_do_all
iterates over all loaded providers, calling
.Fa cb
for each one, with the current provider in
.Fa provider
and the
.Fa cbdata
that comes from the caller.
If no other provider has been loaded before calling this function, the
default provider is still available as fallback.
See
.Xr OSSL_PROVIDER-default 7
for more information on this fallback behaviour.
.Pp
.Fn OSSL_PROVIDER_gettable_params
is used to get a provider parameter descriptor set as a constant
.Xr OSSL_PARAM 3
array.
.Pp
.Fn OSSL_PROVIDER_get_params
is used to get provider parameter values.
The caller must prepare the
.Xr OSSL_PARAM 3
array before calling this function, and the variables acting as buffers
for this parameter array should be filled with data when it returns
successfully.
.Pp
.Fn OSSL_PROVIDER_add_conf_parameter
sets the provider configuration parameter
.Fa name
to
.Fa value .
Provider configuration parameters are managed by the OpenSSL core and
normally set in the configuration file, but can also be set early in the
main program before a provider is in use by multiple threads.
Parameters that only affect provider initialisation must, for now, be
set in the configuration file, only parameters that are also queried
later have any affect when set via this interface.
Only text parameters can be given, and it's up to the provider to
interpret them.
.Pp
.Fn OSSL_PROVIDER_get_conf_parameters
retrieves global configuration parameters associated with
.Fa prov .
These configuration parameters are stored for each provider by the
OpenSSL core, not the provider itself, parameters managed by the
provider are queried via
.Sy OSSL_PROVIDER_get_params()
described above.
The parameters are returned by reference, not as copies, and so the
elements of the
.Em param
array must have
.Sy OSSL_PARAM_UTF8_PTR
as their
.Sy data_type .
.Pp
.Fn OSSL_PROVIDER_conf_get_bool
parses the global configuration parameter
.Fa name
associated with provider
.Fa prov
as a boolean value, returning a default value
.Fa defval
when unable to retrieve or parse the parameter.
Parameter values equal (case-insensitively) to
.Qo Li 1 Qc ,
.Qo Li on Qc ,
.Qo Li yes Qc ,
or
.Qo Li true Qc
yield a true (nonzero) result.
Parameter values equal (case-insensitively) to
.Qo Li 0 Qc ,
.Qo Li off Qc ,
.Qo Li no Qc ,
or
.Qo Li false Qc
yield a false (zero) result.
.Pp
.Fn OSSL_PROVIDER_self_test
is used to run a provider's self tests on demand.
If the self tests fail then the provider will fail to provide any
further services and algorithms.
.Xr OSSL_SELF_TEST_set_callback 3
may be called beforehand in order to display diagnostics for the running
self tests.
.Pp
.Fn OSSL_PROVIDER_query_operation
calls the provider's
.Em query_operation
function (see
.Xr provider 7 Ns ),
if the provider has one.
It returns an array of
.Em OSSL_ALGORITHM
for the given
.Fa operation_id
terminated by an all NULL OSSL_ALGORITHM entry.
This is considered a low-level function that most applications should
not need to call.
.Pp
.Fn OSSL_PROVIDER_unquery_operation
calls the provider's
.Em unquery_operation
function (see
.Xr provider 7 Ns ),
if the provider has one.
This is considered a low-level function that most applications should
not need to call.
.Pp
.Fn OSSL_PROVIDER_get0_provider_ctx
returns the provider context for the given provider.
The provider context is an opaque handle set by the provider itself and
is passed back to the provider by libcrypto in various function calls.
.Pp
.Fn OSSL_PROVIDER_get0_dispatch
returns the provider's dispatch table as it was returned in the
.Em out
parameter from the provider's init function.
See
.Xr provider-base 7 .
.Pp
If it is permissible to cache references to this array then
.Em *no_store
is set to 0 or 1 otherwise.
If the array is not cacheable then it is assumed to have a short
lifetime.
.Pp
.Fn OSSL_PROVIDER_get0_name
returns the name of the given provider.
.Pp
.Fn OSSL_PROVIDER_get_capabilities
provides information about the capabilities supported by the provider
specified in
.Fa prov
with the capability name
.Fa capability .
For each capability of that name supported by the provider it will call
the callback
.Fa cb
and supply a set of
.Xr OSSL_PARAM 3 Ns s
describing the capability.
It will also pass back the argument
.Fa arg .
For more details about capabilities and what they can be used for please
see
.Xr provider-base 7 .
.Sh RETURN VALUES
.Fn OSSL_PROVIDER_set_default_search_path ,
.Xr OSSL_PROVIDER_add 3 ,
.Fn OSSL_PROVIDER_unload ,
.Fn OSSL_PROVIDER_get_params ,
.Fn OSSL_PROVIDER_add_conf_parameter ,
.Fn OSSL_PROVIDER_get_conf_parameters
and
.Fn OSSL_PROVIDER_get_capabilities
return 1 on success, or 0 on error.
.Pp
.Fn OSSL_PROVIDER_get0_default_search_path
returns a pointer to a path on success, or NULL on error or if the path
has not previously been set.
.Pp
.Fn OSSL_PROVIDER_load
and
.Fn OSSL_PROVIDER_try_load
return a pointer to a provider object on success, or NULL on error.
.Pp
.Fn OSSL_PROVIDER_do_all
returns 1 if the callback
.Fa cb
returns 1 for every provider it is called with, or 0 if any provider
callback invocation returns 0; callback processing stops at the first
callback invocation on a provider that returns 0.
.Pp
.Fn OSSL_PROVIDER_available
returns 1 if the named provider is available, otherwise 0.
.Pp
.Fn OSSL_PROVIDER_gettable_params
returns a pointer to an array of constant
.Xr OSSL_PARAM 3 ,
or NULL if none is provided.
.Pp
.Fn OSSL_PROVIDER_get_params
and returns 1 on success, or 0 on error.
.Pp
.Fn OSSL_PROVIDER_query_operation
returns an array of OSSL_ALGORITHM or NULL on error.
.Pp
.Fn OSSL_PROVIDER_self_test
returns 1 if the self tests pass, or 0 on error.
.Sh EXAMPLES
This demonstrates how to load the provider module "foo" and ask for its
build information.
.Bd -literal
 #include <openssl/params.h>
 #include <openssl/provider.h>
 #include <openssl/err.h>

 OSSL_PROVIDER *prov = NULL;
 const char *build = NULL;
 OSSL_PARAM request[] = {
     { "buildinfo", OSSL_PARAM_UTF8_PTR, &build, 0, 0 },
     { NULL, 0, NULL, 0, 0 }
 };

 if ((prov = OSSL_PROVIDER_load(NULL, "foo")) != NULL
     && OSSL_PROVIDER_get_params(prov, request))
     printf("Provider 'foo' buildinfo: %s\en", build);
 else
     ERR_print_errors_fp(stderr);
.Ed
.Sh SEE ALSO
.Xr openssl-core.h 7 ,
.Xr OSSL_LIB_CTX 3 ,
.Xr provider 7
.Sh HISTORY
The type and functions described here were added in OpenSSL 3.0.
.Pp
The
.Em OSSL_PROVIDER_load_ex
and
.Em OSSL_PROVIDER_try_load_ex
functions were added in OpenSSL 3.2.
.Pp
The
.Em OSSL_PROVIDER_add_conf_parameter ,
.Em OSSL_PROVIDER_get_conf_parameters ,
and
.Em OSSL_PROVIDER_conf_get_bool
functions were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
