.Dd 2025-09-30
.Dt OSSL_INDICATOR_SET_CALLBACK 3ossl
.Os
.Sh NAME
.Nm OSSL_INDICATOR_set_callback ,
.Nm OSSL_INDICATOR_get_callback
.Nd specify a callback for FIPS indicators
.Sh SYNOPSIS
.In openssl/indicator.h
typedef int (OSSL_INDICATOR_CALLBACK)(const char *type, const char
*desc,
.br
const OSSL_PARAM
.Oo
.Oc
params);
.Ft void
.Fo OSSL_INDICATOR_set_callback
.Fa "OSSL_LIB_CTX *libctx"
.Fa "OSSL_INDICATOR_CALLBACK *cb"
.Fc
.Ft void
.Fo OSSL_INDICATOR_get_callback
.Fa "OSSL_LIB_CTX *libctx"
.Fa "OSSL_INDICATOR_CALLBACK **cb"
.Fc
.Sh DESCRIPTION
.Fn OSSL_INDICATOR_set_callback
sets a user callback
.Fa cb
associated with a
.Fa libctx
that will be called when a non approved FIPS operation is detected.
.Pp
The user's callback may be triggered multiple times during an algorithm
operation to indicate different approved mode checks have failed.
.Pp
Non approved operations may only occur if the user has deliberately
chosen to do so (either by setting a global FIPS configuration option or
via an option in an algorithm's operation context).
.Pp
The user's callback
.Vt OSSL_INDICATOR_CALLBACK
.Em type
and
.Em desc
contain the algorithm type and operation that is not approved.
.Em params
is not currently used.
.Pp
If the user callback returns 0, an error will occur in the caller.
This can be used for testing purposes.
.Sh RETURN VALUES
.Fn OSSL_INDICATOR_get_callback
returns the callback that has been set via
.Fn OSSL_INDICATOR_set_callback
for the given library context
.Fa libctx ,
or NULL if no callback is currently set.
.Sh EXAMPLES
A simple indicator callback to log non approved FIPS operations
.Bd -literal
 static int indicator_cb(const char *type, const char *desc,
                         const OSSL_PARAM params[])
 {
     if (type != NULL && desc != NULL)
         fprintf(stdout, "%s %s is not approved\en", type, desc);
end:
     /* For Testing purposes you could return 0 here to cause an error */
     return 1;
 }

 OSSL_INDICATOR_set_callback(libctx, indicator_cb);
.Ed
.Sh SEE ALSO
.Xr openssl-core.h 7 ,
.Xr OSSL_PROVIDER-FIPS 7
.Xr OSSL_LIB_CTX 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
