.Dd 2025-09-30
.Dt OSSL_CRMF_MSG_SET1_REGCTRL_REGTOKEN 3ossl
.Os
.Sh NAME
.Nm OSSL_CRMF_MSG_get0_regCtrl_regToken ,
.Nm OSSL_CRMF_MSG_set1_regCtrl_regToken ,
.Nm OSSL_CRMF_MSG_get0_regCtrl_authenticator ,
.Nm OSSL_CRMF_MSG_set1_regCtrl_authenticator ,
.Nm OSSL_CRMF_MSG_PKIPublicationInfo_push0_SinglePubInfo ,
.Nm OSSL_CRMF_MSG_set0_SinglePubInfo ,
.Nm OSSL_CRMF_MSG_set_PKIPublicationInfo_action ,
.Nm OSSL_CRMF_MSG_get0_regCtrl_pkiPublicationInfo ,
.Nm OSSL_CRMF_MSG_set1_regCtrl_pkiPublicationInfo ,
.Nm OSSL_CRMF_MSG_get0_regCtrl_protocolEncrKey ,
.Nm OSSL_CRMF_MSG_set1_regCtrl_protocolEncrKey ,
.Nm OSSL_CRMF_MSG_get0_regCtrl_oldCertID ,
.Nm OSSL_CRMF_MSG_set1_regCtrl_oldCertID ,
.Nm OSSL_CRMF_CERTID_gen
.Nd functions getting or setting CRMF Registration Controls
.Sh SYNOPSIS
.In openssl/crmf.h
.Ft ASN1_UTF8STRING
    *
.Fo OSSL_CRMF_MSG_get0_regCtrl_regToken
.Fa "const OSSL_CRMF_MSG *msg"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set1_regCtrl_regToken
.Fa "OSSL_CRMF_MSG *msg"
.Fa "const ASN1_UTF8STRING *tok"
.Fc
.Ft ASN1_UTF8STRING
    *
.Fo OSSL_CRMF_MSG_get0_regCtrl_authenticator
.Fa "const OSSL_CRMF_MSG *msg"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set1_regCtrl_authenticator
.Fa "OSSL_CRMF_MSG *msg"
.Fa "const ASN1_UTF8STRING *auth"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_PKIPublicationInfo_push0_SinglePubInfo
.Fa "                                   OSSL_CRMF_PKIPUBLICATIONINFO *pi"
.Fa "OSSL_CRMF_SINGLEPUBINFO *spi"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set0_SinglePubInfo
.Fa "OSSL_CRMF_SINGLEPUBINFO *spi"
.Fa "int method"
.Fa "GENERAL_NAME *nm"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set_PKIPublicationInfo_action
.Fa "                                   OSSL_CRMF_PKIPUBLICATIONINFO *pi"
.Fa "int action"
.Fc
.Ft OSSL_CRMF_PKIPUBLICATIONINFO
    *
.Fo OSSL_CRMF_MSG_get0_regCtrl_pkiPublicationInfo
.Fa "const OSSL_CRMF_MSG *msg"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set1_regCtrl_pkiPublicationInfo
.Fa "OSSL_CRMF_MSG *msg"
.Fa "const OSSL_CRMF_PKIPUBLICATIONINFO *pi"
.Fc
.Ft X509_PUBKEY
    *
.Fo OSSL_CRMF_MSG_get0_regCtrl_protocolEncrKey
.Fa "const OSSL_CRMF_MSG *msg"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set1_regCtrl_protocolEncrKey
.Fa "OSSL_CRMF_MSG *msg"
.Fa "const X509_PUBKEY *pubkey"
.Fc
.Ft OSSL_CRMF_CERTID
    *
.Fo OSSL_CRMF_MSG_get0_regCtrl_oldCertID
.Fa "const OSSL_CRMF_MSG *msg"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_set1_regCtrl_oldCertID
.Fa "OSSL_CRMF_MSG *msg"
.Fa "const OSSL_CRMF_CERTID *cid"
.Fc
.Ft OSSL_CRMF_CERTID *
.Fo OSSL_CRMF_CERTID_gen
.Fa "const X509_NAME *issuer"
.Fa "const ASN1_INTEGER *serial"
.Fc
.Sh DESCRIPTION
Each of the
.Xr OSSL_CRMF_MSG_get0_regCtrl_X 3
functions returns the respective control X in the given
.Fa msg ,
if present.
.Pp
.Fn OSSL_CRMF_MSG_set1_regCtrl_regToken
sets the regToken control in the given
.Fa msg
copying the given
.Fa tok
as value.
See RFC 4211, section 6.1.
.Pp
.Fn OSSL_CRMF_MSG_set1_regCtrl_authenticator
sets the authenticator control in the given
.Fa msg
copying the given
.Fa auth
as value.
See RFC 4211, section 6.2.
.Pp
.Fn OSSL_CRMF_MSG_PKIPublicationInfo_push0_SinglePubInfo
pushes the given
.Fa spi
to
.Em si .
Consumes the
.Fa spi
pointer.
.Pp
.Fn OSSL_CRMF_MSG_set0_SinglePubInfo
sets in the given SinglePubInfo
.Fa spi
the
.Fa method
and publication location, in the form of a GeneralName,
.Fa nm .
The publication location is optional, and therefore
.Fa nm
may be NULL. The function consumes the
.Fa nm
pointer if present.
Available methods are:
.br
# define OSSL_CRMF_PUB_METHOD_DONTCARE 0
.br
# define OSSL_CRMF_PUB_METHOD_X500 1
.br
# define OSSL_CRMF_PUB_METHOD_WEB 2
.br
# define OSSL_CRMF_PUB_METHOD_LDAP 3
.Pp
.Fn OSSL_CRMF_MSG_set_PKIPublicationInfo_action
sets the action in the given
.Fa pi
using the given
.Fa action
as value.
See RFC 4211, section 6.3. Available actions are:
.br
# define OSSL_CRMF_PUB_ACTION_DONTPUBLISH 0
.br
# define OSSL_CRMF_PUB_ACTION_PLEASEPUBLISH 1
.Pp
.Fn OSSL_CRMF_MSG_set1_regCtrl_pkiPublicationInfo
sets the pkiPublicationInfo control in the given
.Fa msg
copying the given
.Fa tok
as value.
See RFC 4211, section 6.3.
.Pp
.Fn OSSL_CRMF_MSG_set1_regCtrl_protocolEncrKey
sets the protocolEncrKey control in the given
.Fa msg
copying the given
.Fa pubkey
as value.
See RFC 4211 section 6.6.
.Pp
.Fn OSSL_CRMF_MSG_set1_regCtrl_oldCertID
sets the
.Sy oldCertID
regToken control in the given
.Fa msg
copying the given
.Fa cid
as value.
See RFC 4211, section 6.5.
.Pp
OSSL_CRMF_CERTID_gen produces an OSSL_CRMF_CERTID_gen structure copying
the given
.Fa issuer
name and
.Fa serial
number.
.Sh RETURN VALUES
All
.Xr OSSL_CRMF_MSG_get0_* 3
functions return the respective pointer value or NULL if not present and
on error.
.Pp
All
.Xr OSSL_CRMF_MSG_set1_* 3
functions return 1 on success, 0 on error.
.Pp
.Fn OSSL_CRMF_CERTID_gen
returns a pointer to the resulting structure or NULL on error.
.Sh NOTES
A function
.Xr OSSL_CRMF_MSG_set1_regCtrl_pkiArchiveOptions 3
for setting an Archive Options Control is not yet implemented due to
missing features to create the needed OSSL_CRMF_PKIARCHIVEOPTINS
content.
.Sh SEE ALSO
RFC 4211
.Sh HISTORY
The OpenSSL CRMF support was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2007-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
