.Dd 2025-09-30
.Dt OSSL_STORE_ATTACH 3ossl
.Os
.Sh NAME
.Nm OSSL_STORE_attach
.Nd Functions to read objects from a BIO
.Sh SYNOPSIS
.In openssl/store.h
.Ft OSSL_STORE_CTX *
.Fo OSSL_STORE_attach
.Fa "BIO *bio"
.Fa "const char *scheme"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "const UI_METHOD *ui_method"
.Fa "void *ui_data"
.Fa "const OSSL_PARAM params[]"
.Fa "OSSL_STORE_post_process_info_fn post_process"
.Fa "void *post_process_data"
.Fc
.Sh DESCRIPTION
.Fn OSSL_STORE_attach
works like
.Xr OSSL_STORE_open 3 ,
except it takes a
.Vt BIO
.Fa bio
instead of a
.Em uri ,
along with a
.Fa scheme
to determine what loader should be used to process the data.
The reference count of the
.Vt BIO
object is increased by 1 if the call is successful.
.Sh RETURN VALUES
.Fn OSSL_STORE_attach
returns a pointer to a
.Vt OSSL_STORE_CTX
on success, or NULL on failure.
.Sh SEE ALSO
.Xr ossl_store 7 ,
.Xr OSSL_STORE_open 3
.Sh HISTORY
.Fn OSSL_STORE_attach
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
