.Dd 2025-09-30
.Dt OSSL_STORE_OPEN 3ossl
.Os
.Sh NAME
.Nm OSSL_STORE_CTX ,
.Nm OSSL_STORE_post_process_info_fn ,
.Nm OSSL_STORE_open ,
.Nm OSSL_STORE_open_ex ,
.Nm OSSL_STORE_ctrl ,
.Nm OSSL_STORE_load ,
.Nm OSSL_STORE_eof ,
.Nm OSSL_STORE_delete ,
.Nm OSSL_STORE_error ,
.Nm OSSL_STORE_close
.Nd Types and functions to read objects from a URI
.Sh SYNOPSIS
.In openssl/store.h
.Ft typedef struct ossl_store_ctx_st OSSL_STORE_CTX;

 typedef OSSL_STORE_INFO *
.Fo 
.Fa *OSSL_STORE_post_process_info_fn
.Fc
(OSSL_STORE_INFO *,
.Bd -literal
                                                             void *);
.Ed
.Ft OSSL_STORE_CTX *
.Fo OSSL_STORE_open
.Fa "const char *uri"
.Fa "const UI_METHOD *ui_method"
.Fa "void *ui_data"
.Fa "OSSL_STORE_post_process_info_fn post_process"
.Fa "void *post_process_data"
.Fc
.Ft OSSL_STORE_CTX *

.Fo OSSL_STORE_open_ex
.Fa "const char *uri"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "const UI_METHOD *ui_method"
.Fa "void *ui_data"
.Fa "const OSSL_PARAM params[]"
.Fa "OSSL_STORE_post_process_info_fn post_process"
.Fa "void *post_process_data"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_load
.Fa "OSSL_STORE_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_STORE_eof
.Fa "OSSL_STORE_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_STORE_delete
.Fa "const char *uri"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "const UI_METHOD *ui_method"
.Fa "void *ui_data"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_STORE_error
.Fa "OSSL_STORE_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_STORE_close
.Fa "OSSL_STORE_CTX *ctx"
.Fc
The following function has been deprecated since OpenSSL 3.0, and can be
hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo OSSL_STORE_ctrl
.Fa "OSSL_STORE_CTX *ctx"
.Fa "int cmd"
.Fa "... /* args */"
.Fc
.Sh DESCRIPTION
These functions help the application to fetch supported objects (see
.Xr OSSL_STORE_INFO 3
for information on which those are) from a given URI. The general method
to do so is to "open" the URI using
.Fn OSSL_STORE_open ,
read each available and supported object using
.Fn OSSL_STORE_load
as long as
.Fn OSSL_STORE_eof
hasn't been reached, and finish it off with
.Fn OSSL_STORE_close .
.Pp
The retrieved information is stored in a
.Vt OSSL_STORE_INFO ,
which is further described in
.Xr OSSL_STORE_INFO 3 .
.Ss Types
.Vt OSSL_STORE_CTX
is a context variable that holds all the internal information for
.Fn OSSL_STORE_open ,
.Fn OSSL_STORE_open_ex ,
.Fn OSSL_STORE_load ,
.Fn OSSL_STORE_eof
and
.Fn OSSL_STORE_close
to work together.
.Ss Functions
.Fn OSSL_STORE_open_ex
takes a uri or path
.Fa uri ,
password UI method
.Fa ui_method
with associated data
.Fa ui_data ,
and post processing callback
.Fa post_process
with associated data
.Fa post_process_data ,
a library context
.Fa libctx
with an associated property query
.Fa propq ,
and opens a channel to the data located at the URI and returns a
.Vt OSSL_STORE_CTX
with all necessary internal information.
The given
.Fa ui_method
and
.Fa ui_data
will be reused by all functions that use
.Vt OSSL_STORE_CTX
when interaction is needed, for instance to provide a password.
The auxiliary
.Xr OSSL_PARAM 3
parameters in
.Em params
can be set to further modify the store operation.
The given
.Fa post_process
and
.Fa post_process_data
will be reused by
.Fn OSSL_STORE_load
to manipulate or drop the value to be returned.
The
.Fa post_process
function drops values by returning NULL, which will cause
.Fn OSSL_STORE_load
to start its process over with loading the next object, until
.Fa post_process
returns something other than NULL, or the end of data is reached as
indicated by
.Fn OSSL_STORE_eof .
.Pp
.Fn OSSL_STORE_open
is similar to
.Fn OSSL_STORE_open_ex
but uses NULL for the
.Em params ,
the library context
.Fa libctx
and property query
.Fa propq .
.Pp
.Fn OSSL_STORE_ctrl
takes a
.Vt OSSL_STORE_CTX ,
and command number
.Fa cmd
and more arguments not specified here.
The available loader specific command numbers and arguments they each
take depends on the loader that's used and is documented together with
that loader.
.Pp
There are also global controls available:
.Bl -tag -width Ds
.It Sy OSSL_STORE_C_USE_SECMEM
Controls if the loader should attempt to use secure memory for any
allocated
.Vt OSSL_STORE_INFO
and its contents.
This control expects one argument, a pointer to an
.Vt int
that is expected to have the value 1 (yes) or 0 (no).
Any other value is an error.
.El
.Pp
.Fn OSSL_STORE_load
takes a
.Vt OSSL_STORE_CTX
and tries to load the next available object and return it wrapped with
.Vt OSSL_STORE_INFO .
.Pp
.Fn OSSL_STORE_delete
deletes the object identified by
.Fa uri .
.Pp
.Fn OSSL_STORE_eof
takes a
.Vt OSSL_STORE_CTX
and checks if we've reached the end of data.
.Pp
.Fn OSSL_STORE_error
takes a
.Vt OSSL_STORE_CTX
and checks if an error occurred in the last
.Fn OSSL_STORE_load
call.
Note that it may still be meaningful to try and load more objects,
unless
.Fn OSSL_STORE_eof
shows that the end of data has been reached.
.Pp
.Fn OSSL_STORE_close
takes a
.Vt OSSL_STORE_CTX ,
closes the channel that was opened by
.Fn OSSL_STORE_open
and frees all other information that was stored in the
.Vt OSSL_STORE_CTX ,
as well as the
.Vt OSSL_STORE_CTX
itself.
If
.Fa ctx
is NULL it does nothing.
.Sh NOTES
A string without a scheme prefix (that is, a non-URI string) is
implicitly interpreted as using the
.Pa file:
scheme.
.Pp
There are some tools that can be used together with
.Fn OSSL_STORE_open
to determine if any failure is caused by an unparsable URI, or if it's a
different error (such as memory allocation failures); if the URI was
parsable but the scheme unregistered, the top error will have the reason
.Qo Li OSSL_STORE_R_UNREGISTERED_SCHEME Qc .
.Pp
These functions make no direct assumption regarding the pass phrase
received from the password callback.
The loaders may make assumptions, however.
For example, the
.Sy file:
scheme loader inherits the assumptions made by OpenSSL functionality
that handles the different file types; this is mostly relevant for
PKCS#12 objects.
See
.Xr passphrase-encoding 7
for further information.
.Sh RETURN VALUES
.Fn OSSL_STORE_open
returns a pointer to a
.Vt OSSL_STORE_CTX
on success, or NULL on failure.
.Pp
.Fn OSSL_STORE_load
returns a pointer to a
.Vt OSSL_STORE_INFO
on success, or NULL on error or when end of data is reached.
Use
.Fn OSSL_STORE_error
and
.Fn OSSL_STORE_eof
to determine the meaning of a returned NULL.
.Pp
.Fn OSSL_STORE_eof
returns 1 if the end of data has been reached or an error occurred, 0
otherwise.
.Pp
.Fn OSSL_STORE_error
returns 1 if an error occurred in an
.Fn OSSL_STORE_load
call, otherwise 0.
.Pp
.Fn OSSL_STORE_delete ,
.Fn OSSL_STORE_ctrl
and
.Fn OSSL_STORE_close
return 1 on success, or 0 on failure.
.Sh SEE ALSO
.Xr ossl_store 7 ,
.Xr OSSL_STORE_INFO 3 ,
.Xr OSSL_STORE_register_loader 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
.Fn OSSL_STORE_delete
was added in OpenSSL 3.2.
.Pp
.Fn OSSL_STORE_open_ex
was added in OpenSSL 3.0.
.Pp
.Vt OSSL_STORE_CTX ,
OSSL_STORE_post_process_info_fn(),
.Fn OSSL_STORE_open ,
.Fn OSSL_STORE_ctrl ,
.Fn OSSL_STORE_load ,
.Fn OSSL_STORE_eof
and
.Fn OSSL_STORE_close
were added in OpenSSL 1.1.1.
.Pp
Handling of NULL
.Fa ctx
argument for
.Fn OSSL_STORE_close
was introduced in OpenSSL 1.1.1h.
.Pp
.Fn OSSL_STORE_ctrl
and
.Xr OSSL_STORE_vctrl 3
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
