.Dd 2025-09-30
.Dt OSSL_CMP_CTX_NEW 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_CTX_new ,
.Nm OSSL_CMP_CTX_free ,
.Nm OSSL_CMP_CTX_reinit ,
.Nm OSSL_CMP_CTX_get0_libctx ,
.Nm OSSL_CMP_CTX_get0_propq ,
.Nm OSSL_CMP_CTX_set_option ,
.Nm OSSL_CMP_CTX_get_option ,
.Nm OSSL_CMP_CTX_set_log_cb ,
.Nm OSSL_CMP_CTX_set_log_verbosity ,
.Nm OSSL_CMP_CTX_print_errors ,
.Nm OSSL_CMP_CTX_set1_serverPath ,
.Nm OSSL_CMP_CTX_set1_server ,
.Nm OSSL_CMP_CTX_set_serverPort ,
.Nm OSSL_CMP_CTX_set1_proxy ,
.Nm OSSL_CMP_CTX_set1_no_proxy ,
.Nm OSSL_CMP_CTX_set_http_cb ,
.Nm OSSL_CMP_CTX_set_http_cb_arg ,
.Nm OSSL_CMP_CTX_get_http_cb_arg ,
.Nm OSSL_CMP_transfer_cb_t ,
.Nm OSSL_CMP_CTX_set_transfer_cb ,
.Nm OSSL_CMP_CTX_set_transfer_cb_arg ,
.Nm OSSL_CMP_CTX_get_transfer_cb_arg ,
.Nm OSSL_CMP_CTX_set1_srvCert ,
.Nm OSSL_CMP_CTX_set1_expected_sender ,
.Nm OSSL_CMP_CTX_set0_trusted ,
.Nm OSSL_CMP_CTX_set0_trustedStore ,
.Nm OSSL_CMP_CTX_get0_trusted ,
.Nm OSSL_CMP_CTX_get0_trustedStore ,
.Nm OSSL_CMP_CTX_set1_untrusted ,
.Nm OSSL_CMP_CTX_get0_untrusted ,
.Nm OSSL_CMP_CTX_set1_cert ,
.Nm OSSL_CMP_CTX_build_cert_chain ,
.Nm OSSL_CMP_CTX_set1_pkey ,
.Nm OSSL_CMP_CTX_set1_referenceValue ,
.Nm OSSL_CMP_CTX_set1_secretValue ,
.Nm OSSL_CMP_CTX_set1_recipient ,
.Nm OSSL_CMP_CTX_push0_geninfo_ITAV ,
.Nm OSSL_CMP_CTX_reset_geninfo_ITAVs ,
.Nm OSSL_CMP_CTX_get0_geninfo_ITAVs ,
.Nm OSSL_CMP_CTX_set1_extraCertsOut ,
.Nm OSSL_CMP_CTX_set0_newPkey ,
.Nm OSSL_CMP_CTX_get0_newPkey ,
.Nm OSSL_CMP_CTX_set1_issuer ,
.Nm OSSL_CMP_CTX_set1_serialNumber ,
.Nm OSSL_CMP_CTX_set1_subjectName ,
.Nm OSSL_CMP_CTX_push1_subjectAltName ,
.Nm OSSL_CMP_CTX_set0_reqExtensions ,
.Nm OSSL_CMP_CTX_reqExtensions_have_SAN ,
.Nm OSSL_CMP_CTX_push0_policy ,
.Nm OSSL_CMP_CTX_set1_oldCert ,
.Nm OSSL_CMP_CTX_set1_p10CSR ,
.Nm OSSL_CMP_CTX_push0_genm_ITAV ,
.Nm OSSL_CMP_certConf_cb_t ,
.Nm OSSL_CMP_certConf_cb ,
.Nm OSSL_CMP_CTX_set_certConf_cb ,
.Nm OSSL_CMP_CTX_set_certConf_cb_arg ,
.Nm OSSL_CMP_CTX_get_certConf_cb_arg ,
.Nm OSSL_CMP_CTX_get_status ,
.Nm OSSL_CMP_CTX_get0_statusString ,
.Nm OSSL_CMP_CTX_get_failInfoCode ,
.Nm OSSL_CMP_CTX_get0_validatedSrvCert ,
.Nm OSSL_CMP_CTX_get0_newCert ,
.Nm OSSL_CMP_CTX_get1_newChain ,
.Nm OSSL_CMP_CTX_get1_caPubs ,
.Nm OSSL_CMP_CTX_get1_extraCertsIn ,
.Nm OSSL_CMP_CTX_set1_transactionID ,
.Nm OSSL_CMP_CTX_set1_senderNonce
.Nd functions for managing the CMP client context data structure
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft OSSL_CMP_CTX *
.Fo OSSL_CMP_CTX_new
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft void
.Fo OSSL_CMP_CTX_free
.Fa "OSSL_CMP_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_reinit
.Fa "OSSL_CMP_CTX *ctx"
.Fc
.Ft OSSL_LIB_CTX *
.Fo OSSL_CMP_CTX_get0_libctx
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft const char *
.Fo OSSL_CMP_CTX_get0_propq
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set_option
.Fa "OSSL_CMP_CTX *ctx"
.Fa "int opt"
.Fa "int val"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_get_option
.Fa "const OSSL_CMP_CTX *ctx"
.Fa "int opt"
.Fc
.Ft /* logging and error reporting: */
 int
.Fo OSSL_CMP_CTX_set_log_cb
.Fa "OSSL_CMP_CTX *ctx"
.Fa "OSSL_CMP_log_cb_t cb"
.Fc
.Fd #define OSSL_CMP_CTX_set_log_verbosity(ctx, level)
.Ft void
.Fo OSSL_CMP_CTX_print_errors
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft /* message transfer: */
 int
.Fo OSSL_CMP_CTX_set1_serverPath
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const char *path"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_server
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const char *address"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set_serverPort
.Fa "OSSL_CMP_CTX *ctx"
.Fa "int port"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_proxy
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const char *name"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_no_proxy
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const char *names"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set_http_cb
.Fa "OSSL_CMP_CTX *ctx"
.Fa "HTTP_bio_cb_t cb"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set_http_cb_arg
.Fa "OSSL_CMP_CTX *ctx"
.Fa "void *arg"
.Fc
.Ft void *
.Fo OSSL_CMP_CTX_get_http_cb_arg
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft typedef OSSL_CMP_MSG *
.Fo 
.Fa *OSSL_CMP_transfer_cb_t
.Fc
(OSSL_CMP_CTX *ctx,
.Bd -literal
                                                 const OSSL_CMP_MSG *req);
 int OSSL_CMP_CTX_set_transfer_cb(OSSL_CMP_CTX *ctx,
                                  OSSL_CMP_transfer_cb_t cb);
 int OSSL_CMP_CTX_set_transfer_cb_arg(OSSL_CMP_CTX *ctx, void *arg);
 void *OSSL_CMP_CTX_get_transfer_cb_arg(const OSSL_CMP_CTX *ctx);
.Ed
.Ft /* server authentication: */
 int
.Fo OSSL_CMP_CTX_set1_srvCert
.Fa "OSSL_CMP_CTX *ctx"
.Fa "X509 *cert"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_expected_sender
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const X509_NAME *name"
.Fc
.Fd #define OSSL_CMP_CTX_set0_trusted OSSL_CMP_CTX_set0_trustedStore
.Ft int
.Fo OSSL_CMP_CTX_set0_trustedStore
.Fa "OSSL_CMP_CTX *ctx"
.Fa "X509_STORE *store"
.Fc
.Fd #define OSSL_CMP_CTX_get0_trusted OSSL_CMP_CTX_get0_trustedStore
.Ft X509_STORE *
.Fo OSSL_CMP_CTX_get0_trustedStore
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_untrusted
.Fa "OSSL_CMP_CTX *ctx"
.Fa "STACK_OF(X509) *certs"
.Fc
.Bd -literal
 STACK_OF(X509) *OSSL_CMP_CTX_get0_untrusted(const OSSL_CMP_CTX *ctx);
.Ed
.Ft /* client authentication: */
 int
.Fo OSSL_CMP_CTX_set1_cert
.Fa "OSSL_CMP_CTX *ctx"
.Fa "X509 *cert"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_build_cert_chain
.Fa "OSSL_CMP_CTX *ctx"
.Fa "X509_STORE *own_trusted"
.Fa "STACK_OF(X509) *candidates"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_pkey
.Fa "OSSL_CMP_CTX *ctx"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_referenceValue
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const unsigned char *ref"
.Fa "int len"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_secretValue
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const unsigned char *sec"
.Fa "int len"
.Fc
.Ft /* CMP message header and extra certificates: */
 int
.Fo OSSL_CMP_CTX_set1_recipient
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const X509_NAME *name"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_push0_geninfo_ITAV
.Fa "OSSL_CMP_CTX *ctx"
.Fa "OSSL_CMP_ITAV *itav"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_reset_geninfo_ITAVs
.Fa "OSSL_CMP_CTX *ctx"
.Fc
.Bd -literal
 STACK_OF(OSSL_CMP_ITAV)
     *OSSL_CMP_CTX_get0_geninfo_ITAVs(const OSSL_CMP_CTX *ctx);
 int OSSL_CMP_CTX_set1_extraCertsOut(OSSL_CMP_CTX *ctx,
                                     STACK_OF(X509) *extraCertsOut);
.Ed
.Ft /* certificate template: */
 int
.Fo OSSL_CMP_CTX_set0_newPkey
.Fa "OSSL_CMP_CTX *ctx"
.Fa "int priv"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_CMP_CTX_get0_newPkey
.Fa "const OSSL_CMP_CTX *ctx"
.Fa "int priv"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_issuer
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const X509_NAME *name"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_serialNumber
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const ASN1_INTEGER *sn"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_subjectName
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const X509_NAME *name"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_push1_subjectAltName
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const GENERAL_NAME *name"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set0_reqExtensions
.Fa "OSSL_CMP_CTX *ctx"
.Fa "X509_EXTENSIONS *exts"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_reqExtensions_have_SAN
.Fa "OSSL_CMP_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_push0_policy
.Fa "OSSL_CMP_CTX *ctx"
.Fa "POLICYINFO *pinfo"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_oldCert
.Fa "OSSL_CMP_CTX *ctx"
.Fa "X509 *cert"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_p10CSR
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const X509_REQ *csr"
.Fc
.Ft /* misc body contents: */
 int
.Fo OSSL_CMP_CTX_push0_genm_ITAV
.Fa "OSSL_CMP_CTX *ctx"
.Fa "OSSL_CMP_ITAV *itav"
.Fc
.Ft /* certificate confirmation: */
 typedef int
.Fo 
.Fa *OSSL_CMP_certConf_cb_t
.Fc
(OSSL_CMP_CTX *ctx, X509 *cert,
.Bd -literal
                                       int fail_info, const char **txt);
 int OSSL_CMP_certConf_cb(OSSL_CMP_CTX *ctx, X509 *cert, int fail_info,
                          const char **text);
 int OSSL_CMP_CTX_set_certConf_cb(OSSL_CMP_CTX *ctx, OSSL_CMP_certConf_cb_t cb);
 int OSSL_CMP_CTX_set_certConf_cb_arg(OSSL_CMP_CTX *ctx, void *arg);
 void *OSSL_CMP_CTX_get_certConf_cb_arg(const OSSL_CMP_CTX *ctx);
.Ed
.Ft /* result fetching: */
 int
.Fo OSSL_CMP_CTX_get_status
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft OSSL_CMP_PKIFREETEXT *
.Fo OSSL_CMP_CTX_get0_statusString
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_get_failInfoCode
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft X509 *
.Fo OSSL_CMP_CTX_get0_validatedSrvCert
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Ft X509 *
.Fo OSSL_CMP_CTX_get0_newCert
.Fa "const OSSL_CMP_CTX *ctx"
.Fc
.Bd -literal
 STACK_OF(X509) *OSSL_CMP_CTX_get1_newChain(const OSSL_CMP_CTX *ctx);
 STACK_OF(X509) *OSSL_CMP_CTX_get1_caPubs(const OSSL_CMP_CTX *ctx);
 STACK_OF(X509) *OSSL_CMP_CTX_get1_extraCertsIn(const OSSL_CMP_CTX *ctx);
.Ed
.Ft /* for testing and debugging purposes: */
 int
.Fo OSSL_CMP_CTX_set1_transactionID
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const ASN1_OCTET_STRING *id"
.Fc
.Ft int
.Fo OSSL_CMP_CTX_set1_senderNonce
.Fa "OSSL_CMP_CTX *ctx"
.Fa "const ASN1_OCTET_STRING *nonce"
.Fc
.Sh DESCRIPTION
This is the context API for using CMP (Certificate Management Protocol)
with OpenSSL.
.Pp
.Fn OSSL_CMP_CTX_new
allocates an
.Vt OSSL_CMP_CTX
structure associated with the library context
.Fa libctx
and property query string
.Fa propq ,
both of which may be NULL to select the defaults.
It initializes the remaining fields to their default values - for
instance, the logging verbosity is set to OSSL_CMP_LOG_INFO, the message
timeout is set to 120 seconds, and the proof-of-possession method is set
to OSSL_CRMF_POPO_SIGNATURE.
.Pp
.Fn OSSL_CMP_CTX_free
deallocates an OSSL_CMP_CTX structure.
If the argument is NULL, nothing is done.
.Pp
.Fn OSSL_CMP_CTX_reinit
prepares the given
.Fa ctx
for a further transaction by clearing the internal CMP transaction (aka
session) status, PKIStatusInfo, and any previous results (newCert,
newChain, caPubs, and extraCertsIn) from the last executed transaction.
It also clears any ITAVs that were added by
.Fn OSSL_CMP_CTX_push0_genm_ITAV .
All other field values (i.e., CMP options) are retained for potential
reuse.
.Pp
.Fn OSSL_CMP_CTX_get0_libctx
returns the
.Fa libctx
argument that was used when constructing
.Fa ctx
with
.Fn OSSL_CMP_CTX_new ,
which may be NULL.
.Pp
.Fn OSSL_CMP_CTX_get0_propq
returns the
.Fa propq
argument that was used when constructing
.Fa ctx
with
.Fn OSSL_CMP_CTX_new ,
which may be NULL.
.Pp
.Fn OSSL_CMP_CTX_set_option
sets the given value for the given option (e.g.,
OSSL_CMP_OPT_IMPLICIT_CONFIRM) in the given OSSL_CMP_CTX structure.
.Pp
The following options can be set:
.Bl -tag -width Ds
.It Sy OSSL_CMP_OPT_LOG_VERBOSITY
The level of severity needed for actually outputting log messages due to
errors, warnings, general info, debugging, etc.
Default is OSSL_CMP_LOG_INFO. See also
.Xr OSSL_CMP_log_open 3 .
.It Sy OSSL_CMP_OPT_KEEP_ALIVE
If the given value is 0 then HTTP connections are not kept open after
receiving a response, which is the default behavior for HTTP 1.0. If the
value is 1 or 2 then persistent connections are requested.
If the value is 2 then persistent connections are required, i.e., in
case the server does not grant them an error occurs.
The default value is 1: prefer to keep the connection open.
.It Sy OSSL_CMP_OPT_MSG_TIMEOUT
Number of seconds a CMP request-response message round trip is allowed
to take before a timeout error is returned.
A value <= 0 means no limitation (waiting indefinitely).
Default is to use the
.Sy OSSL_CMP_OPT_TOTAL_TIMEOUT
setting.
.It Sy OSSL_CMP_OPT_TOTAL_TIMEOUT
Maximum total number of seconds a transaction may take, including
polling etc.
A value <= 0 means no limitation (waiting indefinitely).
Default is 0.
.It Sy OSSL_CMP_OPT_USE_TLS
Use this option to indicate to the HTTP implementation whether TLS is
going to be used for the connection (resulting in HTTPS). The value 1
indicates that TLS is used for client-side HTTP connections, which needs
to be implemented via a callback function set by
.Fn OSSL_CMP_CTX_set_http_cb .
The value 0 indicates that TLS is not used.
Default is -1 for backward compatibility: TLS is used by the client side
if and only if
.Fn OSSL_CMP_CTX_set_http_cb_arg
sets a non-NULL
.Fa arg .
.It Sy OSSL_CMP_OPT_VALIDITY_DAYS
Number of days new certificates are asked to be valid for.
.It Sy OSSL_CMP_OPT_SUBJECTALTNAME_NODEFAULT
Do not take default Subject Alternative Names from the reference
certificate.
.It Sy OSSL_CMP_OPT_SUBJECTALTNAME_CRITICAL
Demand that the given Subject Alternative Names are flagged as critical.
.It Sy OSSL_CMP_OPT_POLICIES_CRITICAL
Demand that the given policies are flagged as critical.
.It Sy OSSL_CMP_OPT_POPO_METHOD
Select the proof of possession method to use.
Possible values are:
.Bd -literal
    OSSL_CRMF_POPO_NONE       - ProofOfPossession field omitted,
                                which implies central key generation
    OSSL_CRMF_POPO_RAVERIFIED - assert that the RA has already
                                verified the PoPo
    OSSL_CRMF_POPO_SIGNATURE  - sign a value with private key,
                                which is the default.
    OSSL_CRMF_POPO_KEYENC     - decrypt the encrypted certificate
                                ("indirect method")
.Ed
.Pp
Note that a signature-based POPO can only be produced if a private key
is provided as the newPkey or client's pkey component of the CMP
context.
.It Sy OSSL_CMP_OPT_DIGEST_ALGNID
The NID of the digest algorithm to be used in RFC 4210's MSG_SIG_ALG for
signature-based message protection and Proof-of-Possession (POPO).
Default is SHA256.
.It Sy OSSL_CMP_OPT_OWF_ALGNID No The NID of the digest algorithm to be used as one-way function (OWF) for MAC-based message protection with password-based MAC (PBM). See RFC 4210 section 5.1.3.1 for details. Default is SHA256.
.It Sy OSSL_CMP_OPT_MAC_ALGNID No The NID of the MAC algorithm to be used for message protection with PBM. Default is HMAC-SHA1 as per RFC 4210.
.It Sy OSSL_CMP_OPT_REVOCATION_REASON
The reason code to be included in a Revocation Request (RR); values:
0..10 (RFC 5210, 5.3.1) or -1 for none, which is the default.
.It Sy OSSL_CMP_OPT_IMPLICIT_CONFIRM
Request server to enable implicit confirm mode, where the client does
not need to send confirmation upon receiving the certificate.
If the server does not enable implicit confirmation in the return
message, then confirmation is sent anyway.
.It Sy OSSL_CMP_OPT_DISABLE_CONFIRM
Do not confirm enrolled certificates, to cope with broken servers not
supporting implicit confirmation correctly.
.Sy WARNING:
This setting leads to unspecified behavior and it is meant exclusively
to allow interoperability with server implementations violating RFC
4210.
.It Sy OSSL_CMP_OPT_UNPROTECTED_SEND
Send request or response messages without CMP-level protection.
.It Sy OSSL_CMP_OPT_UNPROTECTED_ERRORS
Accept unprotected error responses which are either explicitly
unprotected or where protection verification failed.
Applies to regular error messages as well as certificate responses
(IP/CP/KUP) and revocation responses (RP) with rejection.
.Sy WARNING:
This setting leads to unspecified behavior and it is meant exclusively
to allow interoperability with server implementations violating RFC
4210.
.It Sy OSSL_CMP_OPT_IGNORE_KEYUSAGE
Ignore key usage restrictions in the signer's certificate when
validating signature-based protection in received CMP messages.
Else, 'digitalSignature' must be allowed by CMP signer certificates.
.It Sy OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR
Allow retrieving a trust anchor from extraCerts and using that to
validate the certificate chain of an IP message.
This is a quirk option added to support 3GPP TS 33.310.
.Pp
Note that using this option is dangerous as the certificate obtained
this way has not been authenticated (at least not at CMP level).
Taking it over as a trust anchor implements trust-on-first-use (TOFU).
.It Sy OSSL_CMP_OPT_NO_CACHE_EXTRACERTS
Do not cache certificates received in the extraCerts CMP message field.
Otherwise they are stored to potentially help validate further messages.
.El
.Pp
.Fn OSSL_CMP_CTX_get_option
reads the current value of the given option (e.g.,
OSSL_CMP_OPT_IMPLICIT_CONFIRM) from the given OSSL_CMP_CTX structure.
.Pp
.Fn OSSL_CMP_CTX_set_log_cb
sets in
.Fa ctx
the callback function
.Fa cb
for handling error queue entries and logging messages.
When
.Fa cb
is NULL errors are printed to STDERR (if available, else ignored) any
log messages are ignored.
Alternatively,
.Xr OSSL_CMP_log_open 3
may be used to direct logging to STDOUT.
.Pp
.Fn OSSL_CMP_CTX_set_log_verbosity
is a macro setting the OSSL_CMP_OPT_LOG_VERBOSITY context option to the
given level.
.Pp
.Fn OSSL_CMP_CTX_print_errors
outputs any entries in the OpenSSL error queue.
It is similar to
.Xr ERR_print_errors_cb 3
but uses the CMP log callback function if set in the
.Fa ctx
for uniformity with CMP logging if given.
Otherwise it uses
.Xr ERR_print_errors 3
to print to STDERR (unless OPENSSL_NO_STDIO is defined).
.Pp
.Fn OSSL_CMP_CTX_set1_serverPath
sets the HTTP path of the CMP server on the host, also known as "CMP
alias".
The default is
.Qo Li / Qc .
.Pp
.Fn OSSL_CMP_CTX_set1_server
sets the given server
.Fa address
(which may be a hostname or IP address or NULL) in the given
.Fa ctx .
If
.Xr OSSL_CMP_CTX_get_transfer_cb_arg 3
sets a non-NULL argument, this server address information is used for
diagnostic output only.
.Pp
.Fn OSSL_CMP_CTX_set_serverPort
sets the port of the CMP server to connect to.
If not used or the
.Fa port
argument is 0 the default port applies, which is 80 for HTTP and 443 for
HTTPS. If
.Xr OSSL_CMP_CTX_get_transfer_cb_arg 3
sets a non-NULL argument, this server port information is used for
diagnostic output only.
.Pp
.Fn OSSL_CMP_CTX_set1_proxy
sets the HTTP proxy to be used for connecting to the given CMP server
unless overruled by any "no_proxy" settings (see below).
If TLS is not used this defaults to the value of the environment
variable
.Qo Li http_proxy Qc
if set, else
.Qo Li HTTP_PROXY Qc .
Otherwise defaults to the value of
.Qo Li https_proxy Qc
if set, else
.Qo Li HTTPS_PROXY Qc .
An empty proxy string specifies not to use a proxy.
Otherwise the format is
.Qo Li [http[s]://][userinfo@]host[:port][/path][?query][#fragment] Qc ,
where any given userinfo, path, query, and fragment is ignored.
If the host string is an IPv6 address, it must be enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
The default port number is 80, or 443 in case
.Qo Li https: Qc
is given.
.Pp
.Fn OSSL_CMP_CTX_set1_no_proxy
sets the list of server hostnames not to use an HTTP proxy for.
The names may be separated by commas and/or whitespace.
Defaults to the environment variable
.Qo Li no_proxy Qc
if set, else
.Qo Li NO_PROXY Qc .
.Pp
.Fn OSSL_CMP_CTX_set_http_cb
sets the optional BIO connect/disconnect callback function, which has
the prototype
.Bd -literal
 typedef BIO *(*HTTP_bio_cb_t) (BIO *bio, void *arg, int connect, int detail);
.Ed
.Pp
The callback may modify the
.Em bio
provided by
.Xr OSSL_CMP_MSG_http_perform 3
as described for the
.Em bio_update_fn
parameter of
.Xr OSSL_HTTP_open 3 .
The callback may make use of a custom defined argument
.Fa arg ,
as described for the
.Fa arg
parameter of
.Xr OSSL_HTTP_open 3 .
The argument is stored in the OSSL_CMP_CTX using
.Fn OSSL_CMP_CTX_set_http_cb_arg .
See also the
.Sy OSSL_CMP_OPT_USE_TLS
option described above.
.Pp
.Fn OSSL_CMP_CTX_set_http_cb_arg
sets the argument, respectively a pointer to a structure containing
arguments such as an
.Sy SSL_CTX
structure, optionally to be used by the http connect/disconnect callback
function.
.Fa arg
is not consumed, and it must therefore explicitly be freed when not
needed any more.
.Fa arg
may be NULL to clear the entry.
If a non-NULL argument is set, it is an error to use
.Fn OSSL_CMP_CTX_set1_proxy
or
.Fn OSSL_CMP_CTX_set1_no_proxy
for setting non-NULL strings.
.Pp
.Fn OSSL_CMP_CTX_get_http_cb_arg
gets the argument, respectively the pointer to a structure containing
arguments, previously set by
.Fn OSSL_CMP_CTX_set_http_cb_arg
or NULL if unset.
.Pp
.Xr OSSL_CMP_CTX_set_transfer_cb 3
sets the message transfer callback function, which has the type
.Bd -literal
 typedef OSSL_CMP_MSG *(*OSSL_CMP_transfer_cb_t) (OSSL_CMP_CTX *ctx,
                                                  const OSSL_CMP_MSG *req);
.Ed
.Pp
Default is NULL, which implies the use of
.Xr OSSL_CMP_MSG_http_perform 3 .
The callback should send the CMP request message it obtains via the
.Em req
parameter and on success return the response, else it must return NULL.
The transfer callback may make use of a custom defined argument stored
in the ctx by means of
.Xr OSSL_CMP_CTX_set_transfer_cb_arg 3 ,
which may be retrieved again through
.Xr OSSL_CMP_CTX_get_transfer_cb_arg 3 .
.Pp
.Xr OSSL_CMP_CTX_set_transfer_cb_arg 3
sets an argument, respectively a pointer to a structure containing
arguments, optionally to be used by the transfer callback.
.Fa arg
is not consumed, and it must therefore explicitly be freed when not
needed any more.
.Fa arg
may be NULL to clear the entry.
.Pp
.Xr OSSL_CMP_CTX_get_transfer_cb_arg 3
gets the argument, respectively the pointer to a structure containing
arguments, previously set by
.Xr OSSL_CMP_CTX_set_transfer_cb_arg 3
or NULL if unset.
.Pp
.Fn OSSL_CMP_CTX_set1_srvCert
sets the expected server cert in
.Fa ctx
and trusts it directly (even if it is expired) when verifying signed
response messages.
This pins the accepted CMP server and results in ignoring whatever may
be set using
.Fn OSSL_CMP_CTX_set0_trusted .
Any previously set value is freed.
The
.Fa cert
argument may be NULL to clear the entry.
If set, the subject of the certificate is also used as default value for
the recipient of CMP requests and as default value for the expected
sender of CMP responses.
.Pp
.Fn OSSL_CMP_CTX_set1_expected_sender
sets the Distinguished Name (DN) expected in the sender field of
incoming CMP messages.
Defaults to the subject of the pinned server certificate, if any.
This can be used to make sure that only a particular entity is accepted
as CMP message signer, and attackers are not able to use arbitrary
certificates of a trusted PKI hierarchy to fraudulently pose as CMP
server.
Note that this gives slightly more freedom than
.Fn OSSL_CMP_CTX_set1_srvCert ,
which pins the server to the holder of a particular certificate, while
the expected sender name will continue to match after updates of the
server cert.
.Pp
.Fn OSSL_CMP_CTX_set0_trusted
is an alias of the original
.Fn OSSL_CMP_CTX_set0_trustedStore .
It sets in the CMP context
.Fa ctx
the certificate store of type X509_STORE containing trusted
certificates, typically of root CAs.
This is ignored when a certificate is pinned using
.Fn OSSL_CMP_CTX_set1_srvCert .
The store may also hold CRLs and a certificate verification callback
function used for signature-based peer authentication.
Any store entry already set before is freed.
When given a NULL parameter the entry is cleared.
.Pp
.Fn OSSL_CMP_CTX_get0_trusted
is an alias of the original
.Fn OSSL_CMP_CTX_get0_trustedStore .
It extracts from the CMP context
.Fa ctx
the pointer to the currently set certificate store containing trust
anchors etc., or an empty store if unset.
.Pp
.Fn OSSL_CMP_CTX_set1_untrusted
sets up a list of non-trusted certificates of intermediate CAs that may
be useful for path construction for the own CMP signer certificate, for
the own TLS certificate (if any), when verifying peer CMP protection
certificates, and when verifying newly enrolled certificates.
The reference counts of those certificates handled successfully are
increased.
This list of untrusted certificates in
.Fa ctx
will get augmented by extraCerts in received CMP messages unless
.Sy OSSL_CMP_OPT_NO_CACHE_EXTRACERTS
is set.
.Pp
.Xr OSSL_CMP_CTX_get0_untrusted 3
returns a pointer to the list of untrusted certs in
.Fa ctx ,
which may be empty if unset.
.Pp
.Fn OSSL_CMP_CTX_set1_cert
sets the CMP
.Em signer certificate ,
also called
.Em protection certificate ,
related to the private key used for signature-based CMP message
protection.
Therefore the public key of this
.Fa cert
must correspond to the private key set before or thereafter via
.Fn OSSL_CMP_CTX_set1_pkey .
When using signature-based protection of CMP request messages this CMP
signer certificate will be included first in the extraCerts field.
It serves as fallback reference certificate, see
.Fn OSSL_CMP_CTX_set1_oldCert .
The subject of this
.Fa cert
will be used as the sender field of outgoing messages, while the subject
of any cert set via
.Fn OSSL_CMP_CTX_set1_oldCert ,
the subject of any PKCS#10 CSR set via
.Fn OSSL_CMP_CTX_set1_p10CSR ,
and any value set via
.Fn OSSL_CMP_CTX_set1_subjectName
are used as fallback.
.Pp
The
.Fa cert
argument may be NULL to clear the entry.
.Pp
.Fn OSSL_CMP_CTX_build_cert_chain
builds a certificate chain for the CMP signer certificate previously set
in the
.Fa ctx .
It adds the optional
.Fa candidates ,
a list of intermediate CA certs that may already constitute the targeted
chain, to the untrusted certs that may already exist in the
.Fa ctx .
Then the function uses this augmented set of certs for chain
construction.
If
.Fa own_trusted
is NULL it builds the chain as far down as possible and ignores any
verification errors.
Else the CMP signer certificate must be verifiable where the chain
reaches a trust anchor contained in
.Fa own_trusted .
On success the function stores the resulting chain in
.Fa ctx
for inclusion in the extraCerts field of signature-protected messages.
Calling this function is optional; by default a chain construction is
performed on demand that is equivalent to calling this function with the
.Fa candidates
and
.Fa own_trusted
arguments being NULL.
.Pp
.Fn OSSL_CMP_CTX_set1_pkey
sets the client's private key corresponding to the CMP signer
certificate set via
.Fn OSSL_CMP_CTX_set1_cert .
This key is used create signature-based protection (protectionAlg =
MSG_SIG_ALG) of outgoing messages unless a symmetric secret has been set
via
.Fn OSSL_CMP_CTX_set1_secretValue .
The
.Fa pkey
argument may be NULL to clear the entry.
.Pp
.Fn OSSL_CMP_CTX_set1_secretValue
sets in
.Fa ctx
the byte string
.Fa sec
of length
.Fa len
to use as pre-shared secret, or clears it if the
.Fa sec
argument is NULL. If present, this secret is used to create MAC-based
authentication and integrity protection (rather than applying
signature-based protection) of outgoing messages and to verify
authenticity and integrity of incoming messages that have MAC-based
protection (protectionAlg =
.Qo Li MSG_MAC_ALG Qc Ns ).
.Pp
.Fn OSSL_CMP_CTX_set1_referenceValue
sets the given referenceValue
.Fa ref
with length
.Fa len
in the given
.Fa ctx
or clears it if the
.Fa ref
argument is NULL. According to RFC 4210 section 5.1.1, if no value for
the sender field in CMP message headers can be determined (i.e., no CMP
signer certificate and no subject DN is set via
.Fn OSSL_CMP_CTX_set1_subjectName
then the sender field will contain the NULL-DN and the senderKID field
of the CMP message header must be set.
When signature-based protection is used the senderKID will be set to the
subjectKeyIdentifier of the CMP signer certificate as far as present.
If not present or when MAC-based protection is used the
.Fa ref
value is taken as the fallback value for the senderKID.
.Pp
.Fn OSSL_CMP_CTX_set1_recipient
sets the recipient name that will be used in the PKIHeader of CMP
request messages, i.e.
the X509 name of the (CA) server.
.Pp
The recipient field in the header of a CMP message is mandatory.
If not given explicitly the recipient is determined in the following
order: the subject of the CMP server certificate set using
.Fn OSSL_CMP_CTX_set1_srvCert ,
the value set using
.Fn OSSL_CMP_CTX_set1_issuer ,
the issuer of the certificate set using
.Fn OSSL_CMP_CTX_set1_oldCert ,
the issuer of the CMP signer certificate, as far as any of those is
present, else the NULL-DN as last resort.
.Pp
.Fn OSSL_CMP_CTX_push0_geninfo_ITAV
adds
.Fa itav
to the stack in the
.Fa ctx
to be added to the generalInfo field of the CMP PKIMessage header of a
request message sent with this context.
.Pp
.Fn OSSL_CMP_CTX_reset_geninfo_ITAVs
clears any ITAVs that were added by
.Fn OSSL_CMP_CTX_push0_geninfo_ITAV .
.Pp
.Xr OSSL_CMP_CTX_get0_geninfo_ITAVs 3
returns the list of ITAVs set in
.Fa ctx
for inclusion in the generalInfo field of the CMP PKIMessage header of
requests or NULL if not set.
.Pp
.Xr OSSL_CMP_CTX_set1_extraCertsOut 3
sets the stack of extraCerts that will be sent to remote.
.Pp
.Fn OSSL_CMP_CTX_set0_newPkey
can be used to explicitly set the given EVP_PKEY structure as the
private or public key to be certified in the CMP context.
The
.Fa priv
parameter must be 0 if and only if the given key is a public key.
.Pp
.Fn OSSL_CMP_CTX_get0_newPkey
gives the key to use for certificate enrollment dependent on fields of
the CMP context structure: the newPkey (which may be a private or public
key) if present, else the public key in the p10CSR if present, else the
client's private key.
If the
.Fa priv
parameter is not 0 and the selected key does not have a private
component then NULL is returned.
.Pp
.Fn OSSL_CMP_CTX_set1_issuer
sets the name of the intended issuer that will be set in the
CertTemplate, i.e., the X509 name of the CA server.
.Pp
.Fn OSSL_CMP_CTX_set1_serialNumber
sets the serial number optionally used to select the certificate to be
revoked in Revocation Requests (RR).
.Pp
.Fn OSSL_CMP_CTX_set1_subjectName
sets the subject DN that will be used in the CertTemplate structure when
requesting a new cert.
For Key Update Requests (KUR), it defaults to the subject DN of the
reference certificate, see
.Fn OSSL_CMP_CTX_set1_oldCert .
This default is used for Initialization Requests (IR) and Certification
Requests (CR) only if no SANs are set.
The
.Em subjectName
is also used as fallback for the sender field of outgoing CMP messages
if no reference certificate is available.
.Pp
.Fn OSSL_CMP_CTX_push1_subjectAltName
adds the given X509 name to the list of alternate names on the
certificate template request.
This cannot be used if any Subject Alternative Name extension is set via
.Fn OSSL_CMP_CTX_set0_reqExtensions .
By default, unless
.Sy OSSL_CMP_OPT_SUBJECTALTNAME_NODEFAULT
has been set, the Subject Alternative Names are copied from the
reference certificate, see
.Fn OSSL_CMP_CTX_set1_oldCert .
If set and the subject DN is not set with
.Fn OSSL_CMP_CTX_set1_subjectName
then the certificate template of an IR and CR will not be filled with
the default subject DN from the reference certificate.
If a subject DN is desired it needs to be set explicitly with
.Fn OSSL_CMP_CTX_set1_subjectName .
.Pp
.Fn OSSL_CMP_CTX_set0_reqExtensions
sets the X.509v3 extensions to be used in IR/CR/KUR.
.Pp
.Fn OSSL_CMP_CTX_reqExtensions_have_SAN
returns 1 if the context contains a Subject Alternative Name extension,
else 0 or -1 on error.
.Pp
.Fn OSSL_CMP_CTX_push0_policy
adds the certificate policy info object to the X509_EXTENSIONS of the
requested certificate template.
.Pp
.Fn OSSL_CMP_CTX_set1_oldCert
sets the old certificate to be updated in Key Update Requests (KUR) or
to be revoked in Revocation Requests (RR). For RR, this is ignored if an
issuer name and a serial number are provided using
.Fn OSSL_CMP_CTX_set1_issuer
and
.Fn OSSL_CMP_CTX_set1_serialNumber ,
respectively.
For IR/CR/KUR this sets the
.Em reference certificate ,
which otherwise defaults to the CMP signer certificate.
The
.Em reference certificate
determined this way, if any, is used for providing default public key,
subject DN, Subject Alternative Names, and issuer DN entries in the
requested certificate template of IR/CR/KUR messages.
.Pp
The subject of the reference certificate is used as the sender field
value in CMP message headers.
Its issuer is used as default recipient in CMP message headers.
.Pp
.Fn OSSL_CMP_CTX_set1_p10CSR
sets the PKCS#10 CSR to use in P10CR messages.
If such a CSR is provided, its subject and public key fields are also
used as fallback values for the certificate template of IR/CR/KUR/RR
messages, and any extensions included are added to the template of
IR/CR/KUR messages.
.Pp
.Fn OSSL_CMP_CTX_push0_genm_ITAV
adds
.Fa itav
to the stack in the
.Fa ctx
which will be the body of a General Message sent with this context.
.Pp
.Xr OSSL_CMP_certConf_cb 3
is the default certificate confirmation callback function.
If the callback argument is not NULL it must point to a trust store.
In this case the function checks that the newly enrolled certificate can
be verified using this trust store and untrusted certificates from the
.Fa ctx ,
which have been augmented by the list of extraCerts received.
During this verification, any certificate status checking is disabled.
If the callback argument is NULL the function tries building an
approximate chain as far as possible using the same untrusted
certificates from the
.Fa ctx ,
and if this fails it takes the received extraCerts as fallback.
The resulting cert chain can be retrieved using
.Xr OSSL_CMP_CTX_get1_newChain 3 .
This chain excludes the leaf certificate, i.e., the newly enrolled
certificate.
Also the trust anchor (the root certificate) is not included.
.Pp
.Xr OSSL_CMP_CTX_set_certConf_cb 3
sets the callback used for evaluating the newly enrolled certificate
before the library sends, depending on its result, a positive or
negative certConf message to the server.
The callback has type
.Bd -literal
 typedef int (*OSSL_CMP_certConf_cb_t) (OSSL_CMP_CTX *ctx, X509 *cert,
                                        int fail_info, const char **txt);
.Ed
.Pp
and should inspect the certificate it obtains via the
.Fa cert
parameter and may overrule the pre-decision given in the
.Em fail_info
and
.Em *txt
parameters.
If it accepts the certificate it must return 0, indicating success.
Else it must return a bit field reflecting PKIFailureInfo with at least
one failure bit and may set the
.Em *txt
output parameter to point to a string constant with more detail.
The transfer callback may make use of a custom defined argument stored
in the
.Fa ctx
by means of
.Xr OSSL_CMP_CTX_set_certConf_cb_arg 3 ,
which may be retrieved again through
.Xr OSSL_CMP_CTX_get_certConf_cb_arg 3 .
Typically, the callback will check at least that the certificate can be
verified using a set of trusted certificates.
It also could compare the subject DN and other fields of the newly
enrolled certificate with the certificate template of the request.
.Pp
.Xr OSSL_CMP_CTX_set_certConf_cb_arg 3
sets an argument, respectively a pointer to a structure containing
arguments, optionally to be used by the certConf callback.
.Fa arg
is not consumed, and it must therefore explicitly be freed when not
needed any more.
.Fa arg
may be NULL to clear the entry.
.Pp
.Xr OSSL_CMP_CTX_get_certConf_cb_arg 3
gets the argument, respectively the pointer to a structure containing
arguments, previously set by
.Xr OSSL_CMP_CTX_set_certConf_cb_arg 3 ,
or NULL if unset.
.Pp
.Fn OSSL_CMP_CTX_get_status
returns for client contexts the PKIstatus from the last received
CertRepMessage or Revocation Response or error message: =item
.Sy OSSL_CMP_PKISTATUS_accepted
on successful receipt of a GENP message:
.Bl -tag -width Ds
.It Sy OSSL_CMP_PKISTATUS_request
if an IR/CR/KUR/RR/GENM request message could not be produced,
.It Sy OSSL_CMP_PKISTATUS_trans
on a transmission error or transaction error for this type of request,
and
.It Sy OSSL_CMP_PKISTATUS_unspecified
if no such request was attempted or
.Fn OSSL_CMP_CTX_reinit
has been called.
.El
.Pp
For server contexts it returns
.Sy OSSL_CMP_PKISTATUS_trans
if a transaction is open, otherwise
.Sy OSSL_CMP_PKISTATUS_unspecified .
.Pp
.Fn OSSL_CMP_CTX_get0_statusString
returns the statusString from the last received CertRepMessage or
Revocation Response or error message, or NULL if unset.
.Pp
.Fn OSSL_CMP_CTX_get_failInfoCode
returns the error code from the failInfo field of the last received
CertRepMessage or Revocation Response or error message, or -1 if no such
response was received or
.Fn OSSL_CMP_CTX_reinit
has been called.
This is a bit field and the flags for it are specified in the header
file
.Pa <openssl/cmp.h> .
The flags start with OSSL_CMP_CTX_FAILINFO, for example:
OSSL_CMP_CTX_FAILINFO_badAlg.
Returns -1 if the failInfoCode field is unset.
.Pp
.Fn OSSL_CMP_CTX_get0_validatedSrvCert
returns the successfully validated certificate, if any, that the CMP
server used in the current transaction for signature-based response
message protection, or NULL if the server used MAC-based protection.
The value is relevant only at the end of a successful transaction.
It may be used to check the authorization of the server based on its
cert.
.Pp
.Fn OSSL_CMP_CTX_get0_newCert
returns the pointer to the newly obtained certificate in case it is
available, else NULL.
.Pp
.Xr OSSL_CMP_CTX_get1_newChain 3
returns a pointer to a duplicate of the stack of X.509 certificates
computed by
.Xr OSSL_CMP_certConf_cb 3
(if this function has been called) on the last received certificate
response message IP/CP/KUP.
.Pp
.Xr OSSL_CMP_CTX_get1_caPubs 3
returns a pointer to a duplicate of the list of X.509 certificates in
the caPubs field of the last received certificate response message (of
type IP, CP, or KUP), or an empty stack if no caPubs have been received
in the current transaction.
.Pp
.Xr OSSL_CMP_CTX_get1_extraCertsIn 3
returns a pointer to a duplicate of the list of X.509 certificates
contained in the extraCerts field of the last received response message
(except for pollRep and PKIConf), or an empty stack if no extraCerts
have been received in the current transaction.
.Pp
.Fn OSSL_CMP_CTX_set1_transactionID
sets the given transaction ID in the given OSSL_CMP_CTX structure.
.Pp
.Fn OSSL_CMP_CTX_set1_senderNonce
stores the last sent sender
.Fa nonce
in the
.Fa ctx .
This will be used to validate the recipNonce in incoming messages.
.Sh NOTES
CMP is defined in RFC 4210 (and CRMF in RFC 4211).
.Sh RETURN VALUES
.Fn OSSL_CMP_CTX_free
and
.Fn OSSL_CMP_CTX_print_errors
do not return anything.
.Pp
.Fn OSSL_CMP_CTX_new ,
.Fn OSSL_CMP_CTX_get0_libctx ,
.Fn OSSL_CMP_CTX_get0_propq ,
.Fn OSSL_CMP_CTX_get_http_cb_arg ,
.Xr OSSL_CMP_CTX_get_transfer_cb_arg 3 ,
.Fn OSSL_CMP_CTX_get0_trusted ,
.Xr OSSL_CMP_CTX_get0_untrusted 3 ,
.Xr OSSL_CMP_CTX_get0_geninfo_ITAVs 3 ,
.Fn OSSL_CMP_CTX_get0_newPkey ,
.Xr OSSL_CMP_CTX_get_certConf_cb_arg 3 ,
.Fn OSSL_CMP_CTX_get0_statusString ,
.Fn OSSL_CMP_CTX_get0_validatedSrvCert ,
.Fn OSSL_CMP_CTX_get0_newCert ,
.Xr OSSL_CMP_CTX_get0_newChain 3 ,
.Xr OSSL_CMP_CTX_get1_caPubs 3 ,
and
.Xr OSSL_CMP_CTX_get1_extraCertsIn 3
return the intended pointer value as described above or NULL on error.
.Pp
.Fn OSSL_CMP_CTX_get_option ,
.Fn OSSL_CMP_CTX_reqExtensions_have_SAN ,
.Fn OSSL_CMP_CTX_get_status ,
and
.Fn OSSL_CMP_CTX_get_failInfoCode
return the intended value as described above or -1 on error.
.Pp
.Xr OSSL_CMP_certConf_cb 3
returns
.Em fail_info
if it is not equal to 0, else 0 on successful validation, or else a bit
field with the
.Sy OSSL_CMP_PKIFAILUREINFO_incorrectData
bit set.
.Pp
All other functions, including
.Fn OSSL_CMP_CTX_reinit
and
.Fn OSSL_CMP_CTX_reset_geninfo_ITAVs ,
return 1 on success, 0 on error.
.Sh EXAMPLES
The following code omits error handling.
.Pp
Set up a CMP client context for sending requests and verifying
responses:
.Bd -literal
    cmp_ctx = OSSL_CMP_CTX_new();
    OSSL_CMP_CTX_set1_server(cmp_ctx, name_or_address);
    OSSL_CMP_CTX_set1_serverPort(cmp_ctx, port_string);
    OSSL_CMP_CTX_set1_serverPath(cmp_ctx, path_or_alias);
    OSSL_CMP_CTX_set0_trusted(cmp_ctx, ts);
.Ed
.Pp
Set up symmetric credentials for MAC-based message protection such as
PBM:
.Bd -literal
    OSSL_CMP_CTX_set1_referenceValue(cmp_ctx, ref, ref_len);
    OSSL_CMP_CTX_set1_secretValue(cmp_ctx, sec, sec_len);
.Ed
.Pp
Set up the details for certificate requests:
.Bd -literal
    OSSL_CMP_CTX_set1_subjectName(cmp_ctx, name);
    OSSL_CMP_CTX_set0_newPkey(cmp_ctx, 1, initialKey);
.Ed
.Pp
Perform an Initialization Request transaction:
.Bd -literal
    initialCert = OSSL_CMP_exec_IR_ses(cmp_ctx);
.Ed
.Pp
Reset the transaction state of the CMP context and the credentials:
.Bd -literal
    OSSL_CMP_CTX_reinit(cmp_ctx);
    OSSL_CMP_CTX_set1_referenceValue(cmp_ctx, NULL, 0);
    OSSL_CMP_CTX_set1_secretValue(cmp_ctx, NULL, 0);
.Ed
.Pp
Perform a Certification Request transaction, making use of the new
credentials:
.Bd -literal
    OSSL_CMP_CTX_set1_cert(cmp_ctx, initialCert);
    OSSL_CMP_CTX_set1_pkey(cmp_ctx, initialKey);
    OSSL_CMP_CTX_set0_newPkey(cmp_ctx, 1, curentKey);
    currentCert = OSSL_CMP_exec_CR_ses(cmp_ctx);
.Ed
.Pp
Perform a Key Update Request, signed using the cert (and key) to be
updated:
.Bd -literal
    OSSL_CMP_CTX_reinit(cmp_ctx);
    OSSL_CMP_CTX_set1_cert(cmp_ctx, currentCert);
    OSSL_CMP_CTX_set1_pkey(cmp_ctx, currentKey);
    OSSL_CMP_CTX_set0_newPkey(cmp_ctx, 1, updatedKey);
    currentCert = OSSL_CMP_exec_KUR_ses(cmp_ctx);
    currentKey = updatedKey;
.Ed
.Pp
Perform a General Message transaction including, as an example, the
id-it-signKeyPairTypes OID and prints info on the General Response
contents:
.Bd -literal
    OSSL_CMP_CTX_reinit(cmp_ctx);

    ASN1_OBJECT *type = OBJ_txt2obj("1.3.6.1.5.5.7.4.2", 1);
    OSSL_CMP_ITAV *itav = OSSL_CMP_ITAV_create(type, NULL);
    OSSL_CMP_CTX_push0_genm_ITAV(cmp_ctx, itav);

    STACK_OF(OSSL_CMP_ITAV) *itavs;
    itavs = OSSL_CMP_exec_GENM_ses(cmp_ctx);
    print_itavs(itavs);
    sk_OSSL_CMP_ITAV_pop_free(itavs, OSSL_CMP_ITAV_free);
.Ed
.Sh SEE ALSO
.Xr OSSL_CMP_exec_IR_ses 3 ,
.Xr OSSL_CMP_exec_CR_ses 3 ,
.Xr OSSL_CMP_exec_KUR_ses 3 ,
.Xr OSSL_CMP_exec_GENM_ses 3 ,
.Xr OSSL_CMP_exec_certreq 3 ,
.Xr OSSL_CMP_MSG_http_perform 3 ,
.Xr ERR_print_errors_cb 3 ,
.Xr OSSL_HTTP_open 3
.Sh HISTORY
The OpenSSL CMP support was added in OpenSSL 3.0.
.Pp
.Fn OSSL_CMP_CTX_get0_trustedStore
was renamed to
.Fn OSSL_CMP_CTX_get0_trusted
and
.Fn OSSL_CMP_CTX_set0_trustedStore
was renamed to
.Fn OSSL_CMP_CTX_set0_trusted ,
using macros, while keeping the old names for backward compatibility, in
OpenSSL 3.2.
.Pp
.Fn OSSL_CMP_CTX_reset_geninfo_ITAVs
was added in OpenSSL 3.0.8.
.Pp
.Fn OSSL_CMP_CTX_set1_serialNumber ,
.Fn OSSL_CMP_CTX_get0_libctx ,
.Fn OSSL_CMP_CTX_get0_propq ,
and
.Fn OSSL_CMP_CTX_get0_validatedSrvCert
were added in OpenSSL 3.2.
.Pp
.Xr OSSL_CMP_CTX_get0_geninfo_ITAVs 3
was added in OpenSSL 3.3.
.Pp
Support for central key generation, requested via
.Sy OSSL_CRMF_POPO_NONE ,
was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2007-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
