.Dd 2025-09-30
.Dt OSSL_ESS_CHECK_SIGNING_CERTS 3ossl
.Os
.Sh NAME
.Nm OSSL_ESS_signing_cert_new_init ,
.Nm OSSL_ESS_signing_cert_v2_new_init ,
.Nm OSSL_ESS_check_signing_certs
.Nd Enhanced Security Services (ESS) functions
.Sh SYNOPSIS
.In openssl/ess.h
.Ft ESS_SIGNING_CERT *
.Fo OSSL_ESS_signing_cert_new_init
.Fa "const X509 *signcert"
.Fa "const STACK_OF(X509) *certs"
.Fa "int set_issuer_serial"
.Fc
.Ft ESS_SIGNING_CERT_V2 *
.Fo OSSL_ESS_signing_cert_v2_new_init
.Fa "const EVP_MD *hash_alg"
.Fa "const X509 *signcert"
.Fa "const                                                         STACK_OF(X509) *certs"
.Fa "int set_issuer_serial"
.Fc
.Ft int
.Fo OSSL_ESS_check_signing_certs
.Fa "const ESS_SIGNING_CERT *ss"
.Fa "const ESS_SIGNING_CERT_V2 *ssv2"
.Fa "const STACK_OF(X509) *chain"
.Fa "int require_signing_cert"
.Fc
.Sh DESCRIPTION
.Fn OSSL_ESS_signing_cert_new_init
generates a new
.Vt ESS_SIGNING_CERT
structure referencing the given
.Fa signcert
and any given further
.Fa certs
using their SHA-1 fingerprints.
If
.Fa set_issuer_serial
is nonzero then also the issuer and serial number of
.Fa signcert
are included in the
.Sy ESS_CERT_ID
as the
.Sy issuerSerial
field.
For all members of
.Fa certs
the
.Sy issuerSerial
field is always included.
.Pp
.Fn OSSL_ESS_signing_cert_v2_new_init
is the same as
.Fn OSSL_ESS_signing_cert_new_init
except that it uses the given
.Fa hash_alg
and generates a
.Vt ESS_SIGNING_CERT_V2
structure with
.Sy ESS_CERT_ID_V2
elements.
.Pp
.Fn OSSL_ESS_check_signing_certs
checks if the validation chain
.Fa chain
contains the certificates required by the identifiers given in
.Fa ss
and/or
.Fa ssv2 .
If
.Fa require_signing_cert
is nonzero,
.Fa ss
or
.Fa ssv2
must not be NULL. If both
.Fa ss
and
.Fa ssv2
are not NULL, they are evaluated independently.
The list of certificate identifiers in
.Fa ss
is of type
.Sy ESS_CERT_ID ,
while the list contained in
.Fa ssv2
is of type
.Sy ESS_CERT_ID_V2 .
As far as these lists are present, they must be nonempty.
The certificate identified by their first entry must be the first
element of
.Fa chain ,
i.e.
the signer certificate.
Any further certificates referenced in the list must also be found in
.Fa chain .
The matching is done using the given certificate hash algorithm and
value.
In addition to the checks required by RFCs 2624 and 5035, if the
.Sy issuerSerial
field is included in an
.Sy ESSCertID
or
.Sy ESSCertIDv2
it must match the certificate issuer and serial number attributes.
.Sh NOTES
ESS has been defined in RFC 2634, which has been updated in RFC 5035
(ESS version 2) to support hash algorithms other than SHA-1. This is
used for TSP (RFC 3161) and CAdES-BES (informational RFC 5126).
.Sh RETURN VALUES
.Fn OSSL_ESS_signing_cert_new_init
and
.Fn OSSL_ESS_signing_cert_v2_new_init
return a pointer to the new structure or NULL on malloc failure.
.Pp
.Fn OSSL_ESS_check_signing_certs
returns 1 on success, 0 if a required certificate cannot be found, -1 on
other error.
.Sh SEE ALSO
.Xr TS_VERIFY_CTX_set_certs 3 ,
.Xr CMS_verify 3
.Sh HISTORY
.Fn OSSL_ESS_signing_cert_new_init ,
.Fn OSSL_ESS_signing_cert_v2_new_init ,
and
.Fn OSSL_ESS_check_signing_certs
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2021-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
