.Dd 2025-09-30
.Dt OSSL_CMP_ITAV_NEW_CACERTS 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_ITAV_new_caCerts ,
.Nm OSSL_CMP_ITAV_get0_caCerts ,
.Nm OSSL_CMP_ITAV_new_rootCaCert ,
.Nm OSSL_CMP_ITAV_get0_rootCaCert ,
.Nm OSSL_CMP_ITAV_new_rootCaKeyUpdate ,
.Nm OSSL_CMP_ITAV_get0_rootCaKeyUpdate ,
.Nm OSSL_CMP_CRLSTATUS_new1 ,
.Nm OSSL_CMP_CRLSTATUS_create ,
.Nm OSSL_CMP_CRLSTATUS_get0 ,
.Nm OSSL_CMP_ITAV_new0_crlStatusList ,
.Nm OSSL_CMP_ITAV_get0_crlStatusList ,
.Nm OSSL_CMP_ITAV_new_crls ,
.Nm OSSL_CMP_ITAV_get0_crls ,
.Nm OSSL_CMP_ITAV_new0_certReqTemplate ,
.Nm OSSL_CMP_ITAV_get1_certReqTemplate
.Nd CMP utility functions for handling specific genm and genp messages
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft OSSL_CMP_ITAV *
.Fo OSSL_CMP_ITAV_new_caCerts
.Fa "const STACK_OF(X509) *caCerts"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get0_caCerts
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "STACK_OF(X509) **out"
.Fc
.Ft OSSL_CMP_ITAV *
.Fo OSSL_CMP_ITAV_new_rootCaCert
.Fa "const X509 *rootCaCert"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get0_rootCaCert
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "X509 **out"
.Fc
.Ft OSSL_CMP_ITAV *
.Fo OSSL_CMP_ITAV_new_rootCaKeyUpdate
.Fa "const X509 *newWithNew"
.Fa "const X509 *newWithOld"
.Fa "const X509 *oldWithNew"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get0_rootCaKeyUpdate
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "X509 **newWithNew"
.Fa "X509 **newWithOld"
.Fa "X509 **oldWithNew"
.Fc
.Ft OSSL_CMP_CRLSTATUS *
.Fo OSSL_CMP_CRLSTATUS_new1
.Fa "const DIST_POINT_NAME *dpn"
.Fa "const GENERAL_NAMES *issuer"
.Fa "const ASN1_TIME *thisUpdate"
.Fc
.Ft OSSL_CMP_CRLSTATUS *
.Fo OSSL_CMP_CRLSTATUS_create
.Fa "const X509_CRL *crl"
.Fa "const X509 *cert"
.Fa "int only_DN"
.Fc
.Ft int
.Fo OSSL_CMP_CRLSTATUS_get0
.Fa "const OSSL_CMP_CRLSTATUS *crlstatus"
.Fa "DIST_POINT_NAME **dpn"
.Fa "GENERAL_NAMES **issuer"
.Fa "ASN1_TIME **thisUpdate"
.Fc
.Ft OSSL_CMP_ITAV
 *
.Fo OSSL_CMP_ITAV_new0_crlStatusList
.Fa "STACK_OF(OSSL_CMP_CRLSTATUS) *crlStatusList"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get0_crlStatusList
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "STACK_OF(OSSL_CMP_CRLSTATUS) **out"
.Fc
.Ft OSSL_CMP_ITAV *
.Fo OSSL_CMP_ITAV_new_crls
.Fa "const X509_CRL *crl"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get0_crls
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "STACK_OF(X509_CRL) **out"
.Fc
.Ft OSSL_CMP_ITAV
 *
.Fo OSSL_CMP_ITAV_new0_certReqTemplate
.Fa "OSSL_CRMF_CERTTEMPLATE *certTemplate"
.Fa "OSSL_CMP_ATAVS *keySpec"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get1_certReqTemplate
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "OSSL_CRMF_CERTTEMPLATE **certTemplate"
.Fa "OSSL_CMP_ATAVS **keySpec"
.Fc
.Sh DESCRIPTION
ITAV is short for InfoTypeAndValue.
.Pp
.Fn OSSL_CMP_ITAV_new_caCerts
creates an
.Vt OSSL_CMP_ITAV
structure of type
.Fa caCerts
and fills it with a copy of the provided list of certificates.
The
.Fa caCerts
argument may be NULL or contain any number of certificates.
.Pp
.Fn OSSL_CMP_ITAV_get0_caCerts
requires that
.Fa itav
has type
.Fa caCerts .
It assigns NULL to
.Em *out
if there are no CA certificates in
.Fa itav ,
otherwise the internal pointer of type
.Sy STACK_OF(X509)
with the certificates present.
.Pp
.Fn OSSL_CMP_ITAV_new_rootCaCert
creates a new
.Vt OSSL_CMP_ITAV
structure of type
.Fa rootCaCert
that includes the optionally given certificate.
.Pp
.Fn OSSL_CMP_ITAV_get0_rootCaCert
requires that
.Fa itav
has type
.Fa rootCaCert .
It assigns NULL to
.Em *out
if no certificate is included in
.Fa itav ,
otherwise the internal pointer to the certificate contained in the
infoValue field.
.Pp
.Fn OSSL_CMP_ITAV_new_rootCaKeyUpdate
creates a new
.Vt OSSL_CMP_ITAV
structure of type
.Sy rootCaKeyUpdate
that includes an RootCaKeyUpdateContent structure with the optional
.Fa newWithNew ,
.Fa newWithOld ,
and
.Fa oldWithNew
certificates.
An RootCaKeyUpdateContent structure is included only if
.Fa newWithNew
is not NULL.
.Pp
.Fn OSSL_CMP_ITAV_get0_rootCaKeyUpdate
requires that
.Fa itav
has infoType
.Sy rootCaKeyUpdate .
If an update of a root CA certificate is included, it assigns to
.Em *newWithNew
the internal pointer to the certificate contained in the newWithNew
infoValue sub-field of
.Fa itav .
If
.Fa newWithOld
is not NULL, it assigns to
.Em *newWithOld
the internal pointer to the certificate contained in the newWithOld
infoValue sub-field of
.Fa itav .
If
.Fa oldWithNew
is not NULL, it assigns to
.Em *oldWithNew
the internal pointer to the certificate contained in the oldWithNew
infoValue sub-field of
.Fa itav .
Each of these pointers will be set to NULL if no root CA certificate
update is present or the respective sub-field is not included.
.Pp
.Fn OSSL_CMP_CRLSTATUS_new1
allocates a new
.Vt OSSL_CMP_CRLSTATUS
structure that contains either a copy of the distribution point name
.Fa dpn
or a copy of the certificate issuer
.Fa issuer ,
while giving both is an error.
If given, a copy of the CRL issuance time
.Fa thisUpdate
is also included.
.Pp
.Fn OSSL_CMP_CRLSTATUS_create
is a high-level variant of
.Fn OSSL_CMP_CRLSTATUS_new1 .
It fills the thisUpdate field with a copy of the thisUpdate field of
.Fa crl
if present.
It fills the CRLSource field with a copy of the first data item found
using the
.Fa crl
and/or
.Fa cert
parameters as follows.
Any available distribution point name is preferred over issuer names.
Data from
.Fa cert ,
if present, is preferred over data from
.Fa crl .
If no distribution point names are available, candidate issuer names are
taken from following sources, as far as present:
.Bl -tag -width Ds
.It the list of distribution points in the first cRLDistributionPoints extension of Fa cert ,
.It the issuer field of the authority key identifier of Fa cert ,
.It the issuer DN of Fa cert ,
.It the issuer field of the authority key identifier of Fa crl Ns , and
.It the issuer DN of Fa crl .
.El
If <only_DN> is set, a candidate issuer name of type
.Vt GENERAL_NAMES
is accepted only if it contains exactly one general name of type
directoryName.
.Pp
.Fn OSSL_CMP_CRLSTATUS_get0
reads the fields of
.Fa crlstatus
and assigns them to
.Em *dpn ,
.Em *issuer ,
and
.Em *thisUpdate .
.Em *thisUpdate
is assigned only if the
.Fa thisUpdate
argument is not NULL. Depending on the choice present, either
.Em *dpn
or
.Em *issuer
will be NULL.
.Em *thisUpdate
can also be NULL if the field is not present.
.Pp
.Fn OSSL_CMP_ITAV_new0_crlStatusList
creates a new
.Vt OSSL_CMP_ITAV
structure of type
.Fa crlStatusList
that includes the optionally given list of CRL status data, each of
which is of type
.Vt OSSL_CMP_CRLSTATUS .
.Pp
.Fn OSSL_CMP_ITAV_get0_crlStatusList
on success assigns to
.Em *out
an internal pointer to the list of CRL status data in the infoValue
field of
.Fa itav .
The pointer may be NULL if no CRL status data is included.
It is an error if the infoType of
.Fa itav
is not
.Fa crlStatusList .
.Pp
.Fn OSSL_CMP_ITAV_new_crls
creates a new
.Vt OSSL_CMP_ITAV
structure of type
.Sy crls
including an empty list of CRLs if the
.Fa crl
argument is NULL or including a singleton list a with copy of the
provided CRL otherwise.
.Pp
.Fn OSSL_CMP_ITAV_get0_crls
on success assigns to
.Em *out
an internal pointer to the list of CRLs contained in the infoValue field
of
.Fa itav .
The pointer may be NULL if no CRL is included.
It is an error if the infoType of
.Fa itav
is not
.Sy crls .
.Pp
.Fn OSSL_CMP_ITAV_new0_certReqTemplate
creates an
.Vt OSSL_CMP_ITAV
structure of type
.Sy certReqTemplate .
If
.Fa certTemplate
is NULL then also
.Fa keySpec
must be NULL, and the resulting ITAV can be used in a
.Sy genm
message to obtain the requirements a PKI has on the certificate template
used to request certificates, or in a
.Sy genp
message stating that there are no such requirements.
Otherwise the resulting ITAV includes a CertReqTemplateValue structure
with
.Fa certTemplate
of type
.Vt OSSL_CRMF_CERTTEMPLATE
and an optional list of key specifications
.Fa keySpec ,
each being of type
.Sy OSSL_CMP_ATAV ,
and the resulting ATAV can be used in a
.Sy genp
message to provide requirements.
.Pp
.Fn OSSL_CMP_ITAV_get1_certReqTemplate
requires that
.Fa itav
has type
.Sy certReqTemplate .
If assigns NULL to
.Em *certTemplate
if no
.Vt OSSL_CRMF_CERTTEMPLATE
structure with a certificate template value is in
.Fa itav ,
otherwise a copy of the certTemplate field value.
If
.Fa keySpec
is not NULL, it is assigned NULL if the structure is not present in
.Fa itav
or the keySpec field is absent.
Otherwise, the function checks that all elements of keySpec field are of
type
.Sy algId
or
.Sy rsaKeyLen
and assigns to
.Em *keySpec
a copy of the keySpec field.
.Sh NOTES
CMP is defined in RFC 4210.
.Sh RETURN VALUES
.Fn OSSL_CMP_ITAV_new_caCerts ,
.Fn OSSL_CMP_ITAV_new_rootCaCert ,
.Fn OSSL_CMP_ITAV_new_rootCaKeyUpdate ,
.Fn OSSL_CMP_CRLSTATUS_new1 ,
.Fn OSSL_CMP_CRLSTATUS_create ,
.Fn OSSL_CMP_ITAV_new0_crlStatusList ,
.Fn OSSL_CMP_ITAV_new_crls
and
.Fn OSSL_CMP_ITAV_new0_certReqTemplate
return a pointer to the new ITAV structure on success, or NULL on error.
.Pp
.Fn OSSL_CMP_ITAV_get0_caCerts ,
.Fn OSSL_CMP_ITAV_get0_rootCaCert ,
.Fn OSSL_CMP_ITAV_get0_rootCaKeyUpdate ,
.Fn OSSL_CMP_CRLSTATUS_get0 ,
.Fn OSSL_CMP_ITAV_get0_crlStatusList ,
.Fn OSSL_CMP_ITAV_get0_crls
and
.Fn OSSL_CMP_ITAV_get1_certReqTemplate
return 1 on success, 0 on error.
.Sh SEE ALSO
.Xr OSSL_CMP_ITAV_create 3
and
.Xr OSSL_CMP_ITAV_get0_type 3
.Sh HISTORY
.Fn OSSL_CMP_ITAV_new_caCerts ,
.Fn OSSL_CMP_ITAV_get0_caCerts ,
.Fn OSSL_CMP_ITAV_new_rootCaCert ,
.Fn OSSL_CMP_ITAV_get0_rootCaCert ,
.Fn OSSL_CMP_ITAV_new_rootCaKeyUpdate ,
and
.Fn OSSL_CMP_ITAV_get0_rootCaKeyUpdate
were added in OpenSSL 3.2.
.Pp
.Fn OSSL_CMP_CRLSTATUS_new1 ,
.Fn OSSL_CMP_CRLSTATUS_create ,
.Fn OSSL_CMP_CRLSTATUS_get0 ,
.Fn OSSL_CMP_ITAV_new0_crlStatusList ,
.Fn OSSL_CMP_ITAV_get0_crlStatusList ,
.Fn OSSL_CMP_ITAV_new_crls ,
.Fn OSSL_CMP_ITAV_get0_crls ,
.Fn OSSL_CMP_ITAV_new0_certReqTemplate
and
.Fn OSSL_CMP_ITAV_get1_certReqTemplate
were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2022-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
