.Dd 2025-09-30
.Dt OSSL_CMP_STATUSINFO_NEW 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_STATUSINFO_new ,
.Nm OSSL_CMP_snprint_PKIStatusInfo ,
.Nm OSSL_CMP_CTX_snprint_PKIStatus
.Nd function(s) for managing the CMP PKIStatus
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft OSSL_CMP_PKISI *
.Fo OSSL_CMP_STATUSINFO_new
.Fa "int status"
.Fa "int fail_info"
.Fa "const char *text"
.Fc
.Ft char *
.Fo OSSL_CMP_snprint_PKIStatusInfo
.Fa "const OSSL_CMP_PKISI *statusInfo"
.Fa "char *buf"
.Fa "size_t bufsize"
.Fc
.Ft char *
.Fo OSSL_CMP_CTX_snprint_PKIStatus
.Fa "const OSSL_CMP_CTX *ctx"
.Fa "char *buf"
.Fa "size_t bufsize"
.Fc
.Sh DESCRIPTION
This is the PKIStatus API for using CMP (Certificate Management
Protocol) with OpenSSL.
.Pp
.Fn OSSL_CMP_STATUSINFO_new
creates a new PKIStatusInfo structure and fills in the given values.
It sets the status field to
.Fa status ,
copies
.Fa text
(unless it is NULL) to statusString, and interprets
.Fa fail_info
as bit pattern for the failInfo field.
.Pp
.Fn OSSL_CMP_snprint_PKIStatusInfo
places a human-readable string representing the given statusInfo in the
given buffer, with the given maximal length.
.Pp
.Fn OSSL_CMP_CTX_snprint_PKIStatus
places a human-readable string representing the PKIStatusInfo components
of the CMP context
.Fa ctx
in the given buffer, with the given maximal length.
.Sh NOTES
CMP is defined in RFC 4210 (and CRMF in RFC 4211).
.Sh RETURN VALUES
.Fn OSSL_CMP_STATUSINFO_new
returns a pointer to the structure on success, or NULL on error.
.Pp
.Fn OSSL_CMP_snprint_PKIStatusInfo
and
.Fn OSSL_CMP_CTX_snprint_PKIStatus
return a copy of the buffer pointer containing the string or NULL on
error.
.Sh HISTORY
The OpenSSL CMP support was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2007-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
