.Dd 2025-09-30
.Dt OSSL_PARAM 3ossl
.Os
.Sh NAME
.Nm OSSL_PARAM
.Nd a structure to pass or request object parameters
.Sh SYNOPSIS
.In openssl/core.h
.Bd -literal
 typedef struct ossl_param_st OSSL_PARAM;
 struct ossl_param_st {
     const char *key;             /* the name of the parameter */
     unsigned int data_type;      /* declare what kind of content is in data */
     void *data;                  /* value being passed in or out */
     size_t data_size;            /* data size */
     size_t return_size;          /* returned size */
 };
.Ed
.Sh DESCRIPTION
.Sy OSSL_PARAM
is a type that allows passing arbitrary data for some object between two
parties that have no or very little shared knowledge about their
respective internal structures for that object.
.Pp
A typical usage example could be an application that wants to set some
parameters for an object, or wants to find out some parameters of an
object.
.Pp
Arrays of this type can be used for the following purposes:
.Bl -tag -width Ds
.It * Setting parameters for some object
The caller sets up the
.Sy OSSL_PARAM
array and calls some function (the
.Em setter )
that has intimate knowledge about the object that can take the data from
the
.Sy OSSL_PARAM
array and assign them in a suitable form for the internal structure of
the object.
.It * Request parameters of some object
The caller (the
.Em requester )
sets up the
.Sy OSSL_PARAM
array and calls some function (the
.Em responder )
that has intimate knowledge about the object, which can take the
internal data of the object and copy (possibly convert) that to the
memory prepared by the
.Em requester
and pointed at with the
.Sy OSSL_PARAM
.Em data .
.It * Request parameter descriptors
The caller gets an array of constant
.Sy OSSL_PARAM ,
which describe available parameters and some of their properties; name,
data type and expected data size.
For a detailed description of each field for this use, see the field
descriptions below.
.Pp
The caller may then use the information from this descriptor array to
build up its own
.Sy OSSL_PARAM
array to pass down to a
.Em setter
or
.Em responder .
.El
.Pp
Normally, the order of the an
.Sy OSSL_PARAM
array is not relevant.
However, if the
.Em responder
can handle multiple elements with the same key, those elements must be
handled in the order they are in.
.Pp
An
.Sy OSSL_PARAM
array must have a terminating element, where
.Em key
is NULL. The usual full terminating template is:
.Bd -literal
    { NULL, 0, NULL, 0, 0 }
.Ed
.Pp
This can also be specified using
.Xr OSSL_PARAM_END 3 .
.Ss Functional support
Libcrypto offers a limited set of helper functions to handle
.Sy OSSL_PARAM
items and arrays, please see
.Xr OSSL_PARAM_get_int 3 .
Developers are free to extend or replace those as they see fit.
.SsOSSL_PARAM No fields
.Bl -tag -width Ds
.It Em key
The identity of the parameter in the form of a string.
.Pp
In an
.Sy OSSL_PARAM
array, an item with this field set to NULL is considered a terminating
item.
.It Em data_type
The
.Em data_type
is a value that describes the type and organization of the data.
See
.Sx Supported types
below for a description of the types.
.It Em data
.It Em data_size
.Em data
is a pointer to the memory where the parameter data is (when setting
parameters) or shall (when requesting parameters) be stored, and
.Em data_size
is its size in bytes.
The organization of the data depends on the parameter type and flag.
.Pp
The
.Em data_size
needs special attention with the parameter type
.Sy OSSL_PARAM_UTF8_STRING
in relation to C strings.
When setting parameters, the size should be set to the length of the
string, not counting the terminating NUL byte.
When requesting parameters, the size should be set to the size of the
buffer to be populated, which should accommodate enough space for a
terminating NUL byte.
.Pp
When
.Em requesting parameters ,
it's acceptable for
.Em data
to be NULL. This can be used by the
.Em requester
to figure out dynamically exactly how much buffer space is needed to
store the parameter data.
In this case,
.Em data_size
is ignored.
.Pp
When the
.Sy OSSL_PARAM
is used as a parameter descriptor,
.Em data
should be ignored.
If
.Em data_size
is zero, it means that an arbitrary data size is accepted, otherwise it
specifies the maximum size allowed.
.It Em return_size
When an array of
.Sy OSSL_PARAM
is used to request data, the
.Em responder
must set this field to indicate size of the parameter data, including
padding as the case may be.
In case the
.Em data_size
is an unsuitable size for the data, the
.Em responder
must still set this field to indicate the minimum data size required.
(further notes on this in
.Sx NOTES
below).
.Pp
When the
.Sy OSSL_PARAM
is used as a parameter descriptor,
.Em return_size
should be ignored.
.El
.Pp
.Sy NOTE:
.Pp
The key names and associated types are defined by the entity that offers
these parameters, i.e.
names for parameters provided by the OpenSSL libraries are defined by
the libraries, and names for parameters provided by providers are
defined by those providers, except for the pointer form of strings (see
data type descriptions below).
Entities that want to set or request parameters need to know what those
keys are and of what type, any functionality between those two entities
should remain oblivious and just pass the
.Sy OSSL_PARAM
array along.
.Ss Supported types
The
.Em data_type
field can be one of the following types:
.Bl -tag -width Ds
.It Sy OSSL_PARAM_INTEGER
.It Sy OSSL_PARAM_UNSIGNED_INTEGER
The parameter data is an integer (signed or unsigned) of arbitrary
length, organized in native form, i.e.
most significant byte first on Big-Endian systems, and least significant
byte first on Little-Endian systems.
.It Sy OSSL_PARAM_REAL
The parameter data is a floating point value in native form.
.It Sy OSSL_PARAM_UTF8_STRING
The parameter data is a printable string.
.It Sy OSSL_PARAM_OCTET_STRING
The parameter data is an arbitrary string of bytes.
.It Sy OSSL_PARAM_UTF8_PTR
The parameter data is a pointer to a printable string.
.Pp
The difference between this and
.Sy OSSL_PARAM_UTF8_STRING
is that
.Em data
doesn't point directly at the data, but to a pointer that points to the
data.
.Pp
If there is any uncertainty about which to use,
.Sy OSSL_PARAM_UTF8_STRING
is almost certainly the correct choice.
.Pp
This is used to indicate that constant data is or will be passed, and
there is therefore no need to copy the data that is passed, just the
pointer to it.
.Pp
.Em data_size
must be set to the size of the data, not the size of the pointer to the
data.
If this is used in a parameter request,
.Em data_size
is not relevant.
However, the
.Em responder
will set
.Em return_size
to the size of the data.
.Pp
Note that the use of this type is
.Sy fragile
and can only be safely used for data that remains constant and in a
constant location for a long enough duration (such as the life-time of
the entity that offers these parameters).
.It Sy OSSL_PARAM_OCTET_PTR
The parameter data is a pointer to an arbitrary string of bytes.
.Pp
The difference between this and
.Sy OSSL_PARAM_OCTET_STRING
is that
.Em data
doesn't point directly at the data, but to a pointer that points to the
data.
.Pp
If there is any uncertainty about which to use,
.Sy OSSL_PARAM_OCTET_STRING
is almost certainly the correct choice.
.Pp
This is used to indicate that constant data is or will be passed, and
there is therefore no need to copy the data that is passed, just the
pointer to it.
.Pp
.Em data_size
must be set to the size of the data, not the size of the pointer to the
data.
If this is used in a parameter request,
.Em data_size
is not relevant.
However, the
.Em responder
will set
.Em return_size
to the size of the data.
.Pp
Note that the use of this type is
.Sy fragile
and can only be safely used for data that remains constant and in a
constant location for a long enough duration (such as the life-time of
the entity that offers these parameters).
.El
.Sh NOTES
Both when setting and requesting parameters, the functions that are
called will have to decide what is and what is not an error.
The recommended behaviour is:
.Bl -bullet
.It
Keys that a
.Em setter
or
.Em responder
doesn't recognise should simply be ignored.
That in itself isn't an error.
.It
If the keys that a called
.Em setter
recognises form a consistent enough set of data, that call should
succeed.
.It
Apart from the
.Em return_size ,
a
.Em responder
must never change the fields of an
.Sy OSSL_PARAM .
To return a value, it should change the contents of the memory that
.Em data
points at.
.It
If the data type for a key that it's associated with is incorrect, the
called function may return an error.
.Pp
The called function may also try to convert the data to a suitable form
(for example, it's plausible to pass a large number as an octet string,
so even though a given key is defined as an
.Sy OSSL_PARAM_UNSIGNED_INTEGER ,
is plausible to pass the value as an
.Sy OSSL_PARAM_OCTET_STRING Ns ),
but this is in no way mandatory.
.It
If
.Em data
for a
.Sy OSSL_PARAM_OCTET_STRING
or a
.Sy OSSL_PARAM_UTF8_STRING
is NULL, the
.Em responder
should set
.Em return_size
to the size of the item to be returned and return success.
Later the responder will be called again with
.Em data
pointing at the place for the value to be put.
.It
If a
.Em responder
finds that some data sizes are too small for the requested data, it must
set
.Em return_size
for each such
.Sy OSSL_PARAM
item to the minimum required size, and eventually return an error.
.It
For the integer type parameters
.Pf ( Sy OSSL_PARAM_UNSIGNED_INTEGER
and
.Sy OSSL_PARAM_INTEGER Ns ),
a
.Em responder
may choose to return an error if the
.Em data_size
isn't a suitable size (even if
.Em data_size
is bigger than needed).
If the
.Em responder
finds the size suitable, it must fill all
.Em data_size
bytes and ensure correct padding for the native endianness, and set
.Em return_size
to the same value as
.Em data_size .
.El
.Sh EXAMPLES
A couple of examples to just show how
.Sy OSSL_PARAM
arrays could be set up.
.Pp
.Em Example 1
.Pp
This example is for setting parameters on some object:
.Bd -literal
    #include <openssl/core.h>

    const char *foo = "some string";
    size_t foo_l = strlen(foo);
    const char bar[] = "some other string";
    OSSL_PARAM set[] = {
        { "foo", OSSL_PARAM_UTF8_PTR, &foo, foo_l, 0 },
        { "bar", OSSL_PARAM_UTF8_STRING, (void *)&bar, sizeof(bar) - 1, 0 },
        { NULL, 0, NULL, 0, 0 }
    };
.Ed
.Pp
.Em Example 2
.Pp
This example is for requesting parameters on some object:
.Bd -literal
    const char *foo = NULL;
    size_t foo_l;
    char bar[1024];
    size_t bar_l;
    OSSL_PARAM request[] = {
        { "foo", OSSL_PARAM_UTF8_PTR, &foo, 0 /*irrelevant*/, 0 },
        { "bar", OSSL_PARAM_UTF8_STRING, &bar, sizeof(bar), 0 },
        { NULL, 0, NULL, 0, 0 }
    };
.Ed
.Pp
A
.Em responder
that receives this array (as
.Em params
in this example) could fill in the parameters like this:
.Bd -literal
    /* OSSL_PARAM *params */

    int i;

    for (i = 0; params[i].key != NULL; i++) {
        if (strcmp(params[i].key, "foo") == 0) {
            *(char **)params[i].data = "foo value";
            params[i].return_size = 9; /* length of "foo value" string */
        } else if (strcmp(params[i].key, "bar") == 0) {
            memcpy(params[i].data, "bar value", 10);
            params[i].return_size = 9; /* length of "bar value" string */
        }
        /* Ignore stuff we don't know */
    }
.Ed
.Sh SEE ALSO
.Xr openssl-core.h 7 ,
.Xr OSSL_PARAM_get_int 3 ,
.Xr OSSL_PARAM_dup 3 ,
.Xr OSSL_PARAM_construct_utf8_string 3
.Sh HISTORY
.Sy OSSL_PARAM
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
