.Dd 2025-09-30
.Dt OSSL_CMP_ITAV_SET0 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_ITAV_create ,
.Nm OSSL_CMP_ITAV_set0 ,
.Nm OSSL_CMP_ITAV_get0_type ,
.Nm OSSL_CMP_ITAV_get0_value ,
.Nm OSSL_CMP_ITAV_push0_stack_item ,
.Nm OSSL_CMP_ITAV_new0_certProfile ,
.Nm OSSL_CMP_ITAV_get0_certProfile
.Nd OSSL_CMP_ITAV utility functions
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft OSSL_CMP_ITAV *
.Fo OSSL_CMP_ITAV_create
.Fa "ASN1_OBJECT *type"
.Fa "ASN1_TYPE *value"
.Fc
.Ft void
.Fo OSSL_CMP_ITAV_set0
.Fa "OSSL_CMP_ITAV *itav"
.Fa "ASN1_OBJECT *type"
.Fa "ASN1_TYPE *value"
.Fc
.Ft ASN1_OBJECT *
.Fo OSSL_CMP_ITAV_get0_type
.Fa "const OSSL_CMP_ITAV *itav"
.Fc
.Ft ASN1_TYPE *
.Fo OSSL_CMP_ITAV_get0_value
.Fa "const OSSL_CMP_ITAV *itav"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_push0_stack_item
.Fa "STACK_OF(OSSL_CMP_ITAV) **itav_sk_p"
.Fa "OSSL_CMP_ITAV *itav"
.Fc
.Ft OSSL_CMP_ITAV
 *
.Fo OSSL_CMP_ITAV_new0_certProfile
.Fa "STACK_OF(ASN1_UTF8STRING) *certProfile"
.Fc
.Ft int
.Fo OSSL_CMP_ITAV_get0_certProfile
.Fa "const OSSL_CMP_ITAV *itav"
.Fa "STACK_OF(ASN1_UTF8STRING) **out"
.Fc
.Sh DESCRIPTION
ITAV is short for InfoTypeAndValue.
This type is defined in RFC 4210 section 5.3.19 and Appendix F. It is
used at various places in CMP messages, e.g., in the generalInfo
PKIHeader field, to hold a key-value pair.
.Pp
.Fn OSSL_CMP_ITAV_create
creates a new
.Vt OSSL_CMP_ITAV
structure and fills it in.
It combines
.Xr OSSL_CMP_ITAV_new 3
and
.Fn OSSL_CMP_ITAV_set0 .
.Pp
.Fn OSSL_CMP_ITAV_set0
sets the
.Fa itav
with an infoType of
.Fa type
and an infoValue of
.Fa value .
This function uses the pointers
.Fa type
and
.Fa value
internally, so they must
.Sy not
be freed up after the call.
.Pp
.Fn OSSL_CMP_ITAV_get0_type
returns a direct pointer to the infoType in the
.Fa itav .
.Pp
.Fn OSSL_CMP_ITAV_get0_value
returns a direct pointer to the infoValue in the
.Fa itav
as generic
.Vt ASN1_TYPE
pointer.
.Pp
.Fn OSSL_CMP_ITAV_push0_stack_item
pushes
.Fa itav
to the stack pointed to by
.Em *itav_sk_p .
It creates a new stack if
.Em *itav_sk_p
points to NULL.
.Pp
.Fn OSSL_CMP_ITAV_new0_certProfile
creates a new
.Vt OSSL_CMP_ITAV
structure of type
.Fa certProfile
that includes the optionally given list of profile names.
On success, ownership of the list is with the new
.Vt OSSL_CMP_ITAV
structure.
.Pp
.Fn OSSL_CMP_ITAV_get0_certProfile
on success assigns to
.Em *out
an internal pointer to the list of certificate profile names contained
in the infoValue field of
.Fa itav .
The pointer may be NULL if no profile name is included.
It is an error if the infoType of
.Fa itav
is not
.Fa certProfile .
.Sh NOTES
CMP is defined in RFC 4210 and RFC 9480 (and CRMF in RFC 4211).
.Pp
OIDs to use as types in
.Vt OSSL_CMP_ITAV
can be found at
.Lk https://datatracker.ietf.org/doc/html/rfc9480#section-4.2.2 .
The respective OpenSSL NIDs, such as
.Sy NID_id_it_certProfile ,
are defined in the
.Pa <openssl/obj_mac.h>
header file.
.Sh RETURN VALUES
.Fn OSSL_CMP_ITAV_create
and
.Fn OSSL_CMP_ITAV_new0_certProfile
return a pointer to an ITAV structure on success, or NULL on error.
.Pp
.Fn OSSL_CMP_ITAV_set0
does not return a value.
.Pp
.Fn OSSL_CMP_ITAV_get0_type
and
.Fn OSSL_CMP_ITAV_get0_value
return the respective pointer or NULL if their input is NULL.
.Pp
.Fn OSSL_CMP_ITAV_push0_stack_item
and
.Fn OSSL_CMP_ITAV_get0_certProfile
return 1 on success, 0 on error.
.Sh EXAMPLES
The following code creates and sets a structure representing a generic
InfoTypeAndValue sequence, using an OID created from text as type, and
an integer as value.
Afterwards, it is pushed to the
.Sy OSSL_CMP_CTX
to be later included in the requests' PKIHeader's genInfo field.
.Bd -literal
    ASN1_OBJECT *type = OBJ_txt2obj("1.2.3.4.5", 1);
    if (type == NULL) ...

    ASN1_INTEGER *asn1int = ASN1_INTEGER_new();
    if (asn1int == NULL || !ASN1_INTEGER_set(asn1int, 12345)) ...

    ASN1_TYPE *val = ASN1_TYPE_new();
    if (val == NULL) ...
    ASN1_TYPE_set(val, V_ASN1_INTEGER, asn1int);

    OSSL_CMP_ITAV *itav = OSSL_CMP_ITAV_create(type, val);
    if (itav == NULL) ...

    if (!OSSL_CMP_CTX_push0_geninfo_ITAV(ctx, itav)) {
        OSSL_CMP_ITAV_free(itav); /* also frees type and val */
        ...
    }

    ...

    OSSL_CMP_CTX_free(ctx); /* also frees itav */
.Ed
.Sh SEE ALSO
.Xr OSSL_CMP_CTX_new 3 ,
.Xr OSSL_CMP_CTX_free 3 ,
.Xr ASN1_TYPE_set 3
.Sh HISTORY
The OpenSSL CMP support was added in OpenSSL 3.0.
.Pp
.Fn OSSL_CMP_ITAV_new0_certProfile
and
.Fn OSSL_CMP_ITAV_get0_certProfile
were added in OpenSSL 3.3.
.Sh COPYRIGHT
Copyright 2007-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
