.Dd 2025-09-30
.Dt OSSL_ENCODER_CTX_NEW_FOR_PKEY 3ossl
.Os
.Sh NAME
.Nm OSSL_ENCODER_CTX_new_for_pkey ,
.Nm OSSL_ENCODER_CTX_set_cipher ,
.Nm OSSL_ENCODER_CTX_set_passphrase ,
.Nm OSSL_ENCODER_CTX_set_pem_password_cb ,
.Nm OSSL_ENCODER_CTX_set_passphrase_cb ,
.Nm OSSL_ENCODER_CTX_set_passphrase_ui
.Nd Encoder routines to encode EVP_PKEYs
.Sh SYNOPSIS
.In openssl/encoder.h
.Ft OSSL_ENCODER_CTX *

.Fo OSSL_ENCODER_CTX_new_for_pkey
.Fa "const EVP_PKEY *pkey"
.Fa "int selection"
.Fa "const char *output_type"
.Fa "const char *output_structure"
.Fa "const char *propquery"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_cipher
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "const char *cipher_name"
.Fa "const char *propquery"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_passphrase
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "const unsigned char *kstr"
.Fa "size_t klen"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_pem_password_cb
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "pem_password_cb *cb"
.Fa "void *cbarg"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_passphrase_ui
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "const UI_METHOD *ui_method"
.Fa "void *ui_data"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_passphrase_cb
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "OSSL_PASSPHRASE_CALLBACK *cb"
.Fa "void *cbarg"
.Fc
.Sh DESCRIPTION
.Fn OSSL_ENCODER_CTX_new_for_pkey
is a utility function that creates a
.Vt OSSL_ENCODER_CTX ,
finds all applicable encoder implementations and sets them up, so almost
all the caller has to do next is call functions like
.Xr OSSL_ENCODER_to_bio 3 .
.Fa output_type
determines the final output encoding, and
.Fa selection
can be used to select what parts of the
.Fa pkey
should be included in the output.
.Fa output_type
is further discussed in
.Sx Output types
below, and
.Fa selection
is further described in
.Sx Selections .
.Pp
Internally,
.Fn OSSL_ENCODER_CTX_new_for_pkey
uses the names from the
.Xr EVP_KEYMGMT 3
implementation associated with
.Fa pkey
to build a list of applicable encoder implementations that are used to
process the
.Fa pkey
into the encoding named by
.Fa output_type ,
with the outermost structure named by
.Fa output_structure
if that's relevant.
All these implementations are implicitly fetched, with
.Fa propquery
for finer selection.
.Pp
If no suitable encoder implementation is found,
.Fn OSSL_ENCODER_CTX_new_for_pkey
still creates a
.Vt OSSL_ENCODER_CTX ,
but with no associated encoder
.Pf ( Xr OSSL_ENCODER_CTX_get_num_encoders 3
returns zero).
This helps the caller to distinguish between an error when creating the
.Vt OSSL_ENCODER_CTX
and missing encoder implementation, and allows it to act accordingly.
.Pp
.Fn OSSL_ENCODER_CTX_set_cipher
tells the implementation what cipher should be used to encrypt encoded
keys.
The cipher is given by name
.Fa cipher_name .
The interpretation of that
.Fa cipher_name
is implementation dependent.
The implementation may implement the cipher directly itself or by other
implementations, or it may choose to fetch it.
If the implementation supports fetching the cipher, then it may use
.Fa propquery
as properties to be queried for when fetching.
.Fa cipher_name
may also be NULL, which will result in unencrypted encoding.
.Pp
.Fn OSSL_ENCODER_CTX_set_passphrase
gives the implementation a pass phrase to use when encrypting the
encoded private key.
Alternatively, a pass phrase callback may be specified with the
following functions.
.Pp
.Fn OSSL_ENCODER_CTX_set_pem_password_cb ,
.Fn OSSL_ENCODER_CTX_set_passphrase_ui
and
.Fn OSSL_ENCODER_CTX_set_passphrase_cb
sets up a callback method that the implementation can use to prompt for
a pass phrase, giving the caller the choice of preferred pass phrase
callback form.
These are called indirectly, through an internal
.Xr OSSL_PASSPHRASE_CALLBACK 3
function.
.Ss Output types
The possible
.Sy EVP_PKEY
output types depends on the available implementations.
.Pp
OpenSSL has built in implementations for the following output types:
.Bl -tag -width Ds
.It Qo Li TEXT Qc
The output is a human readable description of the key.
.Xr EVP_PKEY_print_private 3 ,
.Xr EVP_PKEY_print_public 3
and
.Xr EVP_PKEY_print_params 3
use this for their output.
.It Qo Li DER Qc
The output is the DER encoding of the
.Fa selection
of the
.Fa pkey .
.It Qo Li PEM Qc
The output is the
.Fa selection
of the
.Fa pkey
in PEM format.
.El
.Ss Selections
.Fa selection
can be any one of the values described in
.Xr EVP_PKEY_fromdata 3 .
.Pp
These are only 'hints' since the encoder implementations are free to
determine what makes sense to include in the output, and this may depend
on the desired output.
For example, an EC key in a PKCS#8 structure doesn't usually include the
public key.
.Sh RETURN VALUES
.Fn OSSL_ENCODER_CTX_new_for_pkey
returns a pointer to an
.Vt OSSL_ENCODER_CTX ,
or NULL if it couldn't be created.
.Pp
.Fn OSSL_ENCODER_CTX_set_cipher ,
.Fn OSSL_ENCODER_CTX_set_passphrase ,
.Fn OSSL_ENCODER_CTX_set_pem_password_cb ,
.Fn OSSL_ENCODER_CTX_set_passphrase_ui
and
.Fn OSSL_ENCODER_CTX_set_passphrase_cb
all return 1 on success, or 0 on failure.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr OSSL_ENCODER 3 ,
.Xr OSSL_ENCODER_CTX 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
