.Dd 2025-09-30
.Dt OSSL_DECODER_FROM_BIO 3ossl
.Os
.Sh NAME
.Nm OSSL_DECODER_from_data ,
.Nm OSSL_DECODER_from_bio ,
.Nm OSSL_DECODER_from_fp
.Nd Routines to perform a decoding
.Sh SYNOPSIS
.In openssl/decoder.h
.Ft int
.Fo OSSL_DECODER_from_bio
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "BIO *in"
.Fc
.Ft int
.Fo OSSL_DECODER_from_fp
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "FILE *fp"
.Fc
.Ft int
.Fo OSSL_DECODER_from_data
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "const unsigned char **pdata"
.Fa "size_t *pdata_len"
.Fc
Feature availability macros:
.Bl -tag -width Ds
.It OSSL_DECODER_from_fp() is only available when Ar OPENSSL_NO_STDIO No is undefined.
.El
.Sh DESCRIPTION
.Fn OSSL_DECODER_from_data
runs the decoding process for the context
.Fa ctx ,
with input coming from
.Em *pdata ,
.Em *pdata_len
bytes long.
Both
.Em *pdata
and
.Em *pdata_len
must be non-NULL. When
.Fn OSSL_DECODER_from_data
returns,
.Em *pdata
is updated to point at the location after what has been decoded, and
.Em *pdata_len
to have the number of remaining bytes.
.Pp
.Fn OSSL_DECODER_from_bio
runs the decoding process for the context
.Fa ctx ,
with the input coming from the
.Vt BIO
.Fa in .
Should it make a difference, it's recommended to have the BIO set in
binary mode rather than text mode.
.Pp
.Fn OSSL_DECODER_from_fp
does the same thing as
.Fn OSSL_DECODER_from_bio ,
except that the input is coming from the
.Vt FILE
.Fa fp .
.Sh RETURN VALUES
.Fn OSSL_DECODER_from_bio ,
.Fn OSSL_DECODER_from_data
and
.Fn OSSL_DECODER_from_fp
return 1 on success, or 0 on failure.
.Sh EXAMPLES
To decode an RSA key encoded with PEM from a bio:
.Bd -literal
 OSSL_DECODER_CTX *dctx;
 EVP_PKEY *pkey = NULL;
 const char *format = "PEM";   /* NULL for any format */
 const char *structure = NULL; /* any structure */
 const char *keytype = "RSA";  /* NULL for any key */
 const unsigned char *pass = "my password";

 dctx = OSSL_DECODER_CTX_new_for_pkey(&pkey, format, structure,
                                      keytype,
                                      OSSL_KEYMGMT_SELECT_KEYPAIR,
                                      NULL, NULL);
 if (dctx == NULL) {
     /* error: no suitable potential decoders found */
 }
 if (pass != NULL)
     OSSL_DECODER_CTX_set_passphrase(dctx, pass, strlen(pass));
 if (OSSL_DECODER_from_bio(dctx, bio)) {
     /* pkey is created with the decoded data from the bio */
 } else {
     /* decoding failure */
 }
 OSSL_DECODER_CTX_free(dctx);
.Ed
.Pp
To decode an EC key encoded with DER from a buffer:
.Bd -literal
 OSSL_DECODER_CTX *dctx;
 EVP_PKEY *pkey = NULL;
 const char *format = "DER";   /* NULL for any format */
 const char *structure = NULL; /* any structure */
 const char *keytype = "EC";   /* NULL for any key */
 const unsigned char *pass = NULL
 const unsigned char *data = buffer;
 size_t datalen = sizeof(buffer);

 dctx = OSSL_DECODER_CTX_new_for_pkey(&pkey, format, structure,
                                      keytype,
                                      OSSL_KEYMGMT_SELECT_KEYPAIR
                                      | OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS,
                                      NULL, NULL);
 if (dctx == NULL) {
     /* error: no suitable potential decoders found */
 }
 if (pass != NULL)
     OSSL_DECODER_CTX_set_passphrase(dctx, pass, strlen(pass));
 if (OSSL_DECODER_from_data(dctx, &data, &datalen)) {
     /* pkey is created with the decoded data from the buffer */
 } else {
     /* decoding failure */
 }
 OSSL_DECODER_CTX_free(dctx);
.Ed
.Sh SEE ALSO
.Xr provider 7 ,
.Xr OSSL_DECODER_CTX 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
