.Dd 2025-09-30
.Dt OSSL_CMP_ATAV_SET0 3ossl
.Os
.Sh NAME
.Nm OSSL_CMP_ATAV ,
.Nm OSSL_CMP_ATAV_create ,
.Nm OSSL_CMP_ATAV_set0 ,
.Nm OSSL_CMP_ATAV_get0_type ,
.Nm OSSL_CMP_ATAV_get0_value ,
.Nm OSSL_CMP_ATAV_new_algId ,
.Nm OSSL_CMP_ATAV_get0_algId ,
.Nm OSSL_CMP_ATAV_new_rsaKeyLen ,
.Nm OSSL_CMP_ATAV_get_rsaKeyLen ,
.Nm OSSL_CMP_ATAVS ,
.Nm OSSL_CMP_ATAV_push1 ,
.Nm OSSL_CMP_ATAV_free
.Nd OSSL_CMP_ATAV utility functions
.Sh SYNOPSIS
.In openssl/cmp.h
.Ft typedef OSSL_CRMF_ATTRIBUTETYPEANDVALUE OSSL_CMP_ATAV;
 OSSL_CMP_ATAV *
.Fo OSSL_CMP_ATAV_create
.Fa "ASN1_OBJECT *type"
.Fa "ASN1_TYPE *value"
.Fc
.Ft void
.Fo OSSL_CMP_ATAV_set0
.Fa "OSSL_CMP_ATAV *atav"
.Fa "ASN1_OBJECT *type"
.Fa "ASN1_TYPE *value"
.Fc
.Ft ASN1_OBJECT *
.Fo OSSL_CMP_ATAV_get0_type
.Fa "const OSSL_CMP_ATAV *atav"
.Fc
.Ft ASN1_TYPE *
.Fo OSSL_CMP_ATAV_get0_value
.Fa "const OSSL_CMP_ATAV *atav"
.Fc
.Ft OSSL_CMP_ATAV *
.Fo OSSL_CMP_ATAV_new_algId
.Fa "const X509_ALGOR *alg"
.Fc
.Ft X509_ALGOR *
.Fo OSSL_CMP_ATAV_get0_algId
.Fa "const OSSL_CMP_ATAV *atav"
.Fc
.Ft OSSL_CMP_ATAV *
.Fo OSSL_CMP_ATAV_new_rsaKeyLen
.Fa "int len"
.Fc
.Ft int
.Fo OSSL_CMP_ATAV_get_rsaKeyLen
.Fa "const OSSL_CMP_ATAV *atav"
.Fc
.Ft typedef
.Fo STACK_OF
.Fa OSSL_CRMF_ATTRIBUTETYPEANDVALUE
.Fc
 OSSL_CMP_ATAVS;
.Ft int
.Fo OSSL_CMP_ATAV_push1
.Fa "OSSL_CMP_ATAVS **sk_p"
.Fa "const OSSL_CMP_ATAV *atav"
.Fc
.Ft void
.Fo OSSL_CMP_ATAV_free
.Fa "OSSL_CMP_ATAV *atav"
.Fc
.Sh DESCRIPTION
.Vt OSSL_CMP_ATAV
is a short hand of
.Vt OSSL_CRMF_ATTRIBUTETYPEANDVALUE ,
defined in RFC 4211 Appendix B. It is typically used in CertRequest
structures, but also in CertReqTemplateContent structures for key
specifications.
.Pp
.Fn OSSL_CMP_ATAV_create
creates a new
.Vt OSSL_CMP_ATAV
structure and fills it in.
It combines
.Xr OSSL_CMP_ATAV_new 3
and
.Fn OSSL_CMP_ATAV_set0 .
.Pp
.Fn OSSL_CMP_ATAV_set0
sets the
.Fa atav
with an infoType of
.Fa type
and an infoValue of
.Fa value .
The pointers
.Fa type
and
.Fa value
may be NULL, otherwise they must
.Sy not
be freed up after the call because their ownership is transferred to
.Fa atav .
The
.Em itav
pointer must not be NULL.
.Pp
.Fn OSSL_CMP_ATAV_get0_type
returns a direct pointer to the infoType in the
.Fa atav
unless it is NULL.
.Pp
.Fn OSSL_CMP_ATAV_get0_value
returns a direct pointer to the infoValue in the
.Fa atav
as generic
.Vt ASN1_TYPE
pointer unless
.Fa atav
is NULL.
.Pp
.Fn OSSL_CMP_ATAV_new_algId
creates a new
.Vt OSSL_CMP_ATAV
structure of type
.Sy algId
and fills it in with a copy of the given
.Fa alg .
.Pp
.Fn OSSL_CMP_ATAV_get0_algId
returns a direct pointer to the algId infoValue in the
.Fa atav
of type
.Vt X509_ALGOR
or NULL if
.Fa atav
is NULL or does not contain an algId.
.Pp
.Fn OSSL_CMP_ATAV_new_rsaKeyLen
creates a new
.Vt OSSL_CMP_ATAV
structure of type
.Sy rsaKeyLen
and fills it in with the given
.Fa len ,
which must be positive.
.Pp
.Fn OSSL_CMP_ATAV_get_rsaKeyLen
returns the RSA key length in rsaKeyLen infoValue in the
.Fa atav ,
-1 if
.Fa atav
is NULL or does not contain an rsaKeyLen or cannot be parsed, or -2 if
the value is less than 1 or is greater than INT_MAX.
.Pp
.Fn OSSL_CMP_ATAV_push1
pushes a copy of
.Fa atav
to the stack of
.Vt OSSL_CMP_ATAV
pointed to by
.Em *sk_p .
It creates a new stack if
.Em *sk_p
points to NULL.
.Pp
.Fn OSSL_CMP_ATAV_free
deallocates
.Fa atav .
It is defined as a macro.
.Sh NOTES
CMP is defined in RFC 4210. CRMF is defined in RFC 4211.
.Sh RETURN VALUES
.Fn OSSL_CMP_ATAV_create ,
.Fn OSSL_CMP_ATAV_new_algId ,
and
.Fn OSSL_CMP_ATAV_new_rsaKeyLen
return a pointer to the ATAV structure on success, or NULL on error.
.Pp
.Fn OSSL_CMP_ATAV_set0
and
.Fn OSSL_CMP_ATAV_free
do not return a value.
.Pp
.Fn OSSL_CMP_ATAV_get0_type ,
.Fn OSSL_CMP_ATAV_get0_value ,
and
.Fn OSSL_CMP_ATAV_get0_algId
return the respective pointer or NULL if their input is NULL.
.Pp
.Fn OSSL_CMP_ATAV_get_rsaKeyLen
return a key length in bits or < 0 on error.
.Pp
.Fn OSSL_CMP_ATAV_push1
returns 1 on success, 0 on error.
.Sh SEE ALSO
.Xr OSSL_CMP_ITAV_new0_certReqTemplate 3 ,
.Xr ASN1_TYPE_set 3
.Sh HISTORY
The
.Vt OSSL_CMP_ATAV
type and related functions were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2022-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
