.Dd 2025-09-30
.Dt OSSL_TRACE_SET_CHANNEL 3ossl
.Os
.Sh NAME
.Nm OSSL_trace_set_channel ,
.Nm OSSL_trace_set_prefix ,
.Nm OSSL_trace_set_suffix ,
.Nm OSSL_trace_set_callback ,
.Nm OSSL_trace_cb
.Nd Enabling trace output
.Sh SYNOPSIS
.In openssl/trace.h
.Ft typedef size_t
.Fo 
.Fa *OSSL_trace_cb
.Fc
(const char *buf, size_t cnt,
.Bd -literal
                                 int category, int cmd, void *data);
.Ed
.Ft void
.Fo OSSL_trace_set_channel
.Fa "int category"
.Fa "BIO *bio"
.Fc
.Ft void
.Fo OSSL_trace_set_prefix
.Fa "int category"
.Fa "const char *prefix"
.Fc
.Ft void
.Fo OSSL_trace_set_suffix
.Fa "int category"
.Fa "const char *suffix"
.Fc
.Ft void
.Fo OSSL_trace_set_callback
.Fa "int category"
.Fa "OSSL_trace_cb cb"
.Fa "void  *data"
.Fc
.Sh DESCRIPTION
If available (see
.Sx Configure Tracing
below), the application can request internal trace output.
This output comes in form of free text for humans to read.
.Pp
The trace output is divided into categories which can be enabled
individually.
Every category can be enabled individually by attaching a so-called
.Em trace channel
to it, which in the simplest case is just a BIO object to which the
application can write the tracing output for this category.
Alternatively, the application can provide a tracer callback in order to
get more finegrained trace information.
This callback will be wrapped internally by a dedicated BIO object.
.Pp
For the tracing code, both trace channel types are indistinguishable.
These are called a
.Em simple trace channel
and a
.Em callback trace channel ,
respectively.
.Pp
.Xr OSSL_TRACE_ENABLED 3
can be used to check whether tracing is currently enabled for the given
category.
Functions like
.Xr OSSL_TRACE1 3
and macros like
.Xr OSSL_TRACE_BEGIN 3
can be used for producing free-text trace output.
.Ss Functions
.Fn OSSL_trace_set_channel
is used to enable the given trace
.Qo Li category Qc
by attaching the
.Vt BIO
.Fa bio
object as (simple) trace channel.
On success the ownership of the BIO is transferred to the channel, so
the caller must not free it directly.
.Pp
.Fn OSSL_trace_set_prefix
and
.Fn OSSL_trace_set_suffix
can be used to add an extra line for each channel, to be output before
and after group of tracing output.
What constitutes an output group is decided by the code that produces
the output.
The lines given here are considered immutable; for more dynamic tracing
prefixes, consider setting a callback with
.Fn OSSL_trace_set_callback
instead.
.Pp
.Fn OSSL_trace_set_callback
is used to enable the given trace
.Fa category
by giving it the tracer callback
.Fa cb
with the associated data
.Fa data ,
which will simply be passed through to
.Fa cb
whenever it's called.
The callback function is internally wrapped by a dedicated BIO object,
the so-called
.Em callback trace channel .
This should be used when it's desirable to do form the trace output to
something suitable for application needs where a prefix and suffix line
aren't enough.
.Pp
.Fn OSSL_trace_set_channel
and
.Fn OSSL_trace_set_callback
are mutually exclusive, calling one of them will clear whatever was set
by the previous call.
.Pp
Calling
.Fn OSSL_trace_set_channel
with NULL for
.Em channel
or
.Fn OSSL_trace_set_callback
with NULL for
.Fa cb
disables tracing for the given
.Fa category .
.Ss Trace callback
The tracer callback must return a
.Sy size_t ,
which must be zero on error and otherwise return the number of bytes
that were output.
It receives a text buffer
.Em buf
with
.Em cnt
bytes of text, as well as the
.Fa category ,
a control number
.Em cmd ,
and the
.Fa data
that was passed to
.Fn OSSL_trace_set_callback .
.Pp
The possible control numbers are:
.Bl -tag -width Ds
.It Sy OSSL_TRACE_CTRL_BEGIN
The callback is called from
.Xr OSSL_trace_begin 3 ,
which gives the callback the possibility to output a dynamic starting
line, or set a prefix that should be output at the beginning of each
line, or something other.
.It Sy OSSL_TRACE_CTRL_WRITE
This callback is called whenever data is written to the BIO by some
regular BIO output routine.
An arbitrary number of
.Sy OSSL_TRACE_CTRL_WRITE
callbacks can occur inside a group marked by a pair of
.Sy OSSL_TRACE_CTRL_BEGIN
and
.Sy OSSL_TRACE_CTRL_END
calls, but never outside such a group.
.It Sy OSSL_TRACE_CTRL_END
The callback is called from
.Xr OSSL_trace_end 3 ,
which gives the callback the possibility to output a dynamic ending
line, or reset the line prefix that was set with
.Sy OSSL_TRACE_CTRL_BEGIN ,
or something other.
.El
.Ss Trace categories
The trace categories are simple numbers available through macros.
.Bl -tag -width Ds
.It Sy OSSL_TRACE_CATEGORY_TRACE
Traces the OpenSSL trace API itself.
.Pp
More precisely, this will generate trace output any time a new trace
hook is set.
.It Sy OSSL_TRACE_CATEGORY_INIT
Traces OpenSSL library initialization and cleanup.
.Pp
This needs special care, as OpenSSL will do automatic cleanup after exit
from
.Qo Li main() Qc ,
and any tracing output done during this cleanup will be lost if the
tracing channel or callback were cleaned away prematurely.
A suggestion is to make such cleanup part of a function that's
registered very early with
.Xr atexit 3 .
.It Sy OSSL_TRACE_CATEGORY_TLS
Traces the TLS/SSL protocol.
.It Sy OSSL_TRACE_CATEGORY_TLS_CIPHER
Traces the ciphers used by the TLS/SSL protocol.
.It Sy OSSL_TRACE_CATEGORY_CONF
Traces details about the provider and engine configuration.
.It Sy OSSL_TRACE_CATEGORY_ENGINE_TABLE
Traces the ENGINE algorithm table selection.
.Pp
More precisely, functions like
.Xr ENGINE_get_pkey_asn1_meth_engine 3 ,
.Xr ENGINE_get_pkey_meth_engine 3 ,
.Xr ENGINE_get_cipher_engine 3 ,
.Xr ENGINE_get_digest_engine 3 ,
will generate trace summaries of the handling of internal tables.
.It Sy OSSL_TRACE_CATEGORY_ENGINE_REF_COUNT
Traces the ENGINE reference counting.
.Pp
More precisely, both reference counts in the ENGINE structure will be
monitored with a line of trace output generated for each change.
.It Sy OSSL_TRACE_CATEGORY_PKCS5V2
Traces PKCS#5 v2 key generation.
.It Sy OSSL_TRACE_CATEGORY_PKCS12_KEYGEN
Traces PKCS#12 key generation.
.It Sy OSSL_TRACE_CATEGORY_PKCS12_DECRYPT
Traces PKCS#12 decryption.
.It Sy OSSL_TRACE_CATEGORY_X509V3_POLICY
Traces X509v3 policy processing.
.Pp
More precisely, this generates the complete policy tree at various point
during evaluation.
.It Sy OSSL_TRACE_CATEGORY_BN_CTX
Traces BIGNUM context operations.
.It Sy OSSL_TRACE_CATEGORY_CMP
Traces CMP client and server activity.
.It Sy OSSL_TRACE_CATEGORY_STORE
Traces STORE operations.
.It Sy OSSL_TRACE_CATEGORY_DECODER
Traces decoder operations.
.It Sy OSSL_TRACE_CATEGORY_ENCODER
Traces encoder operations.
.It Sy OSSL_TRACE_CATEGORY_REF_COUNT
Traces decrementing certain ASN.1 structure references.
.It Sy OSSL_TRACE_CATEGORY_HTTP
Traces the HTTP client, such as message headers being sent and received.
.El
.Pp
There is also
.Sy OSSL_TRACE_CATEGORY_ALL ,
which works as a fallback and can be used to get
.Em all
trace output.
.Pp
Note, however, that in this case all trace output will effectively be
associated with the 'ALL' category, which is undesirable if the
application intends to include the category name in the trace output.
In this case it is better to register separate channels for each trace
category instead.
.Sh RETURN VALUES
.Fn OSSL_trace_set_channel ,
.Fn OSSL_trace_set_prefix ,
.Fn OSSL_trace_set_suffix ,
and
.Fn OSSL_trace_set_callback
return 1 on success, or 0 on failure.
.Sh EXAMPLES
In all examples below, the trace producing code is assumed to be the
following:
.Bd -literal
 int foo = 42;
 const char bar[] = { 0,  1,  2,  3,  4,  5,  6,  7,
                      8,  9, 10, 11, 12, 13, 14, 15 };

 OSSL_TRACE_BEGIN(TLS) {
     BIO_puts(trc_out, "foo: ");
     BIO_printf(trc_out, "%d\en", foo);
     BIO_dump(trc_out, bar, sizeof(bar));
 } OSSL_TRACE_END(TLS);
.Ed
.Ss Simple example
An example with just a channel and constant prefix / suffix.
.Bd -literal
 int main(int argc, char *argv[])
 {
     BIO *err = BIO_new_fp(stderr, BIO_NOCLOSE | BIO_FP_TEXT);
     OSSL_trace_set_channel(OSSL_TRACE_CATEGORY_SSL, err);
     OSSL_trace_set_prefix(OSSL_TRACE_CATEGORY_SSL, "BEGIN TRACE[TLS]");
     OSSL_trace_set_suffix(OSSL_TRACE_CATEGORY_SSL, "END TRACE[TLS]");

     /* ... work ... */
 }
.Ed
.Pp
When the trace producing code above is performed, this will be output on
standard error:
.Bd -literal
 BEGIN TRACE[TLS]
 foo: 42
 0000 - 00 01 02 03 04 05 06 07-08 09 0a 0b 0c 0d 0e 0f   ................
 END TRACE[TLS]
.Ed
.Ss Advanced example
This example uses the callback, and depends on pthreads functionality.
.Bd -literal
 static size_t cb(const char *buf, size_t cnt,
                 int category, int cmd, void *vdata)
 {
     BIO *bio = vdata;
     const char *label = NULL;

     switch (cmd) {
     case OSSL_TRACE_CTRL_BEGIN:
         label = "BEGIN";
         break;
     case OSSL_TRACE_CTRL_END:
         label = "END";
         break;
     }

     if (label != NULL) {
         union {
             pthread_t tid;
             unsigned long ltid;
         } tid;

         tid.tid = pthread_self();
         BIO_printf(bio, "%s TRACE[%s]:%lx\en",
                    label, OSSL_trace_get_category_name(category), tid.ltid);
     }
     return (size_t)BIO_puts(bio, buf);
 }

 int main(int argc, char *argv[])
 {
     BIO *err = BIO_new_fp(stderr, BIO_NOCLOSE | BIO_FP_TEXT);
     OSSL_trace_set_callback(OSSL_TRACE_CATEGORY_SSL, cb, err);

     /* ... work ... */
 }
.Ed
.Pp
The output is almost the same as for the simple example above.
.Bd -literal
 BEGIN TRACE[TLS]:7f9eb0193b80
 foo: 42
 0000 - 00 01 02 03 04 05 06 07-08 09 0a 0b 0c 0d 0e 0f   ................
 END TRACE[TLS]:7f9eb0193b80
.Ed
.Sh NOTES
.Ss Configure Tracing
By default, the OpenSSL library is built with tracing disabled.
To use the tracing functionality documented here, it is therefore
necessary to configure and build OpenSSL with the 'enable-trace' option.
.Pp
When the library is built with tracing disabled, the macro
.Sy OPENSSL_NO_TRACE
is defined in
.Pa <openssl/opensslconf.h>
and all functions described here are inoperational, i.e.
will do nothing.
.Sh SEE ALSO
.Xr OSSL_TRACE_ENABLED 3 ,
.Xr OSSL_TRACE_BEGIN 3 ,
.Xr OSSL_TRACE1 3 ,
.Xr atexit 3
.Sh HISTORY
.Fn OSSL_trace_set_channel ,
.Fn OSSL_trace_set_prefix ,
.Fn OSSL_trace_set_suffix ,
and
.Fn OSSL_trace_set_callback
were all added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
