.Dd 2025-09-30
.Dt OSSL_STORE_INFO 3ossl
.Os
.Sh NAME
.Nm OSSL_STORE_INFO ,
.Nm OSSL_STORE_INFO_get_type ,
.Nm OSSL_STORE_INFO_get0_NAME ,
.Nm OSSL_STORE_INFO_get0_NAME_description ,
.Nm OSSL_STORE_INFO_get0_PARAMS ,
.Nm OSSL_STORE_INFO_get0_PUBKEY ,
.Nm OSSL_STORE_INFO_get0_PKEY ,
.Nm OSSL_STORE_INFO_get0_CERT ,
.Nm OSSL_STORE_INFO_get0_CRL ,
.Nm OSSL_STORE_INFO_get1_NAME ,
.Nm OSSL_STORE_INFO_get1_NAME_description ,
.Nm OSSL_STORE_INFO_get1_PARAMS ,
.Nm OSSL_STORE_INFO_get1_PUBKEY ,
.Nm OSSL_STORE_INFO_get1_PKEY ,
.Nm OSSL_STORE_INFO_get1_CERT ,
.Nm OSSL_STORE_INFO_get1_CRL ,
.Nm OSSL_STORE_INFO_type_string ,
.Nm OSSL_STORE_INFO_free ,
.Nm OSSL_STORE_INFO_new_NAME ,
.Nm OSSL_STORE_INFO_set0_NAME_description ,
.Nm OSSL_STORE_INFO_new_PARAMS ,
.Nm OSSL_STORE_INFO_new_PUBKEY ,
.Nm OSSL_STORE_INFO_new_PKEY ,
.Nm OSSL_STORE_INFO_new_CERT ,
.Nm OSSL_STORE_INFO_new_CRL ,
.Nm OSSL_STORE_INFO_new ,
.Nm OSSL_STORE_INFO_get0_data
.Nd Functions to manipulate OSSL_STORE_INFO objects
.Sh SYNOPSIS
.In openssl/store.h
.Ft typedef struct ossl_store_info_st OSSL_STORE_INFO;

 int
.Fo OSSL_STORE_INFO_get_type
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft const char *
.Fo OSSL_STORE_INFO_get0_NAME
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft char *
.Fo OSSL_STORE_INFO_get1_NAME
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft const char *
.Fo OSSL_STORE_INFO_get0_NAME_description
.Fa "const OSSL_STORE_INFO                                                    *store_info"
.Fc
.Ft char *
.Fo OSSL_STORE_INFO_get1_NAME_description
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_STORE_INFO_get0_PARAMS
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_STORE_INFO_get1_PARAMS
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_STORE_INFO_get0_PUBKEY
.Fa "const OSSL_STORE_INFO *info"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_STORE_INFO_get1_PUBKEY
.Fa "const OSSL_STORE_INFO *info"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_STORE_INFO_get0_PKEY
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft EVP_PKEY *
.Fo OSSL_STORE_INFO_get1_PKEY
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft X509 *
.Fo OSSL_STORE_INFO_get0_CERT
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft X509 *
.Fo OSSL_STORE_INFO_get1_CERT
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft X509_CRL *
.Fo OSSL_STORE_INFO_get0_CRL
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft X509_CRL *
.Fo OSSL_STORE_INFO_get1_CRL
.Fa "const OSSL_STORE_INFO *store_info"
.Fc
.Ft const char *
.Fo OSSL_STORE_INFO_type_string
.Fa "int type"
.Fc
.Ft void
.Fo OSSL_STORE_INFO_free
.Fa "OSSL_STORE_INFO *store_info"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new_NAME
.Fa "char *name"
.Fc
.Ft int
.Fo OSSL_STORE_INFO_set0_NAME_description
.Fa "OSSL_STORE_INFO *info"
.Fa "char *desc"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new_PARAMS
.Fa "DSA *dsa_params"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new_PUBKEY
.Fa "EVP_PKEY *pubkey"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new_PKEY
.Fa "EVP_PKEY *pkey"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new_CERT
.Fa "X509 *x509"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new_CRL
.Fa "X509_CRL *crl"
.Fc
.Ft OSSL_STORE_INFO *
.Fo OSSL_STORE_INFO_new
.Fa "int type"
.Fa "void *data"
.Fc
.Ft void *
.Fo OSSL_STORE_INFO_get0_data
.Fa "int type"
.Fa "const OSSL_STORE_INFO *info"
.Fc
.Sh DESCRIPTION
These functions are primarily useful for applications to retrieve
supported objects from
.Vt OSSL_STORE_INFO
objects and for scheme specific loaders to create
.Vt OSSL_STORE_INFO
holders.
.Ss Types
.Vt OSSL_STORE_INFO
is an opaque type that's just an intermediary holder for the objects
that have been retrieved by
.Xr OSSL_STORE_load 3
and similar functions.
Supported OpenSSL type object can be extracted using one of
.Xr STORE_INFO_get0_<TYPE> 3
where <TYPE> can be NAME, PARAMS, PKEY, CERT, or CRL. The life time of
this extracted object is as long as the life time of the
.Vt OSSL_STORE_INFO
it was extracted from, so care should be taken not to free the latter
too early.
As an alternative,
.Xr STORE_INFO_get1_<TYPE> 3
extracts a duplicate (or the same object with its reference count
increased), which can be used after the containing
.Vt OSSL_STORE_INFO
has been freed.
The object returned by
.Xr STORE_INFO_get1_<TYPE> 3
must be freed separately by the caller.
See
.Sx SUPPORTED OBJECTS
for more information on the types that are supported.
.Ss Functions
.Fn OSSL_STORE_INFO_get_type
takes a
.Vt OSSL_STORE_INFO
and returns the STORE type number for the object inside.
.Pp
.Xr STORE_INFO_get_type_string 3
takes a STORE type number and returns a short string describing it.
.Pp
.Fn OSSL_STORE_INFO_get0_NAME ,
.Fn OSSL_STORE_INFO_get0_NAME_description ,
.Fn OSSL_STORE_INFO_get0_PARAMS ,
.Fn OSSL_STORE_INFO_get0_PUBKEY ,
.Fn OSSL_STORE_INFO_get0_PKEY ,
.Fn OSSL_STORE_INFO_get0_CERT ,
.Fn OSSL_STORE_INFO_get0_CRL
all take a
.Vt OSSL_STORE_INFO
and return the object it holds if the
.Vt OSSL_STORE_INFO
type (as returned by
.Fn OSSL_STORE_INFO_get_type )
matches the function, otherwise NULL.
.Pp
.Fn OSSL_STORE_INFO_get1_NAME ,
.Fn OSSL_STORE_INFO_get1_NAME_description ,
.Fn OSSL_STORE_INFO_get1_PARAMS ,
.Fn OSSL_STORE_INFO_get1_PUBKEY ,
.Fn OSSL_STORE_INFO_get1_PKEY ,
.Fn OSSL_STORE_INFO_get1_CERT
and
.Fn OSSL_STORE_INFO_get1_CRL
all take a
.Vt OSSL_STORE_INFO
and return a duplicate the object it holds if the
.Vt OSSL_STORE_INFO
type (as returned by
.Fn OSSL_STORE_INFO_get_type )
matches the function, otherwise NULL.
.Pp
.Fn OSSL_STORE_INFO_free
frees a
.Vt OSSL_STORE_INFO
and its contained type.
If the argument is NULL, nothing is done.
.Pp
.Fn OSSL_STORE_INFO_new_NAME
,
.Fn OSSL_STORE_INFO_new_PARAMS ,
,
.Fn OSSL_STORE_INFO_new_PUBKEY ,
.Fn OSSL_STORE_INFO_new_PKEY ,
.Fn OSSL_STORE_INFO_new_CERT
and
.Fn OSSL_STORE_INFO_new_CRL
create a
.Vt OSSL_STORE_INFO
object to hold the given input object.
On success the input object is consumed.
.Pp
Additionally, for
.Sy OSSL_STORE_INFO_NAME
objects,
.Fn OSSL_STORE_INFO_set0_NAME_description
can be used to add an extra description.
This description is meant to be human readable and should be used for
information printout.
.Pp
.Fn OSSL_STORE_INFO_new
creates a
.Vt OSSL_STORE_INFO
with an arbitrary
.Fa type
number and
.Fa data
structure.
It's the responsibility of the caller to define type numbers other than
the ones defined by
.Pa <openssl/store.h> ,
and to handle freeing the associated data structure on their own.
.Em Using type numbers that are defined by Pa <openssl/store.h> may cause undefined behaviours, including crashes .
.Pp
.Fn OSSL_STORE_INFO_get0_data
returns the data pointer that was passed to
.Fn OSSL_STORE_INFO_new
if
.Fa type
matches the type number in
.Fa info .
.Pp
.Fn OSSL_STORE_INFO_new
and
.Fn OSSL_STORE_INFO_get0_data
may be useful for applications that define their own STORE data, but
must be used with care.
.Sh SUPPORTED OBJECTS
Currently supported object types are:
.Bl -tag -width Ds
.It OSSL_STORE_INFO_NAME
A name is exactly that, a name.
It's like a name in a directory, but formatted as a complete URI. For
example, the path in URI
.Qo Li file:/foo/bar/ Qc
could include a file named
.Qo Li cookie.pem Qc ,
and in that case, the returned
.Sy OSSL_STORE_INFO_NAME
object would have the URI
.Qo Li file:/foo/bar/cookie.pem Qc ,
which can be used by the application to get the objects in that file.
This can be applied to all schemes that can somehow support a listing of
object URIs.
.Pp
For
.Qo Li file: Qc
URIs that are used without the explicit scheme, the returned name will
be the path of each object, so if
.Qo Li /foo/bar Qc
was given and that path has the file
.Qo Li cookie.pem Qc ,
the name
.Qo Li /foo/bar/cookie.pem Qc
will be returned.
.Pp
The returned URI is considered canonical and must be unique and
permanent for the storage where the object (or collection of objects)
resides.
Each loader is responsible for ensuring that it only returns canonical
URIs.
However, it's possible that certain schemes allow an object (or
collection thereof) to be reached with alternative URIs; just because
one URI is canonical doesn't mean that other variants can't be used.
.Pp
At the discretion of the loader that was used to get these names, an
extra description may be attached as well.
.It OSSL_STORE_INFO_PARAMS
Key parameters.
.It OSSL_STORE_INFO_PKEY
A keypair or just a private key (possibly with key parameters).
.It OSSL_STORE_INFO_PUBKEY
A public key (possibly with key parameters).
.It OSSL_STORE_INFO_CERT
An X.509 certificate.
.It OSSL_STORE_INFO_CRL
A X.509 certificate revocation list.
.El
.Sh RETURN VALUES
.Fn OSSL_STORE_INFO_get_type
returns the STORE type number of the given
.Vt OSSL_STORE_INFO .
There is no error value.
.Pp
.Fn OSSL_STORE_INFO_get0_NAME ,
.Fn OSSL_STORE_INFO_get0_NAME_description ,
.Fn OSSL_STORE_INFO_get0_PARAMS ,
.Fn OSSL_STORE_INFO_get0_PKEY ,
.Fn OSSL_STORE_INFO_get0_CERT
and
.Fn OSSL_STORE_INFO_get0_CRL
all return a pointer to the OpenSSL object on success, NULL otherwise.
.Pp
.Fn OSSL_STORE_INFO_get1_NAME ,
.Fn OSSL_STORE_INFO_get1_NAME_description ,
.Fn OSSL_STORE_INFO_get1_PARAMS ,
.Fn OSSL_STORE_INFO_get1_PKEY ,
.Fn OSSL_STORE_INFO_get1_CERT
and
.Fn OSSL_STORE_INFO_get1_CRL
all return a pointer to a duplicate of the OpenSSL object on success,
NULL otherwise.
.Pp
.Fn OSSL_STORE_INFO_type_string
returns a string on success, or NULL on failure.
.Pp
.Fn OSSL_STORE_INFO_new_NAME ,
.Fn OSSL_STORE_INFO_new_PARAMS ,
.Fn OSSL_STORE_INFO_new_PKEY ,
.Fn OSSL_STORE_INFO_new_CERT
and
.Fn OSSL_STORE_INFO_new_CRL
return a
.Vt OSSL_STORE_INFO
pointer on success, or NULL on failure.
.Pp
.Fn OSSL_STORE_INFO_set0_NAME_description
returns 1 on success, or 0 on failure.
.Sh SEE ALSO
.Xr ossl_store 7 ,
.Xr OSSL_STORE_open 3 ,
.Xr OSSL_STORE_register_loader 3
.Sh HISTORY
The OSSL_STORE API was added in OpenSSL 1.1.1.
.Pp
The OSSL_STORE_INFO_PUBKEY object type was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
