.Dd 2025-09-30
.Dt OSSL_SELF_TEST_SET_CALLBACK 3ossl
.Os
.Sh NAME
.Nm OSSL_SELF_TEST_set_callback ,
.Nm OSSL_SELF_TEST_get_callback
.Nd specify a callback for processing self tests
.Sh SYNOPSIS
.In openssl/self_test.h
.Ft void
.Fo OSSL_SELF_TEST_set_callback
.Fa "OSSL_LIB_CTX *ctx"
.Fa "OSSL_CALLBACK *cb"
.Fa "void *cbarg"
.Fc
.Ft void
.Fo OSSL_SELF_TEST_get_callback
.Fa "OSSL_LIB_CTX *ctx"
.Fa "OSSL_CALLBACK **cb"
.Fa "void **cbarg"
.Fc
.Sh DESCRIPTION
Set or gets the optional application callback (and the callback
argument) that is called during self testing.
The application callback
.Xr OSSL_CALLBACK 3
is associated with a
.Vt OSSL_LIB_CTX .
The application callback function receives information about a running
self test, and may return a result to the calling self test.
See
.Xr openssl-core.h 7
for further information on the callback.
.Sh RETURN VALUES
.Fn OSSL_SELF_TEST_get_callback
returns the callback and callback argument that has been set via
.Fn OSSL_SELF_TEST_set_callback
for the given library context
.Fa ctx .
These returned parameters will be NULL if
.Fn OSSL_SELF_TEST_set_callback
has not been called.
.Sh SEE ALSO
.Xr openssl-core.h 7 ,
.Xr OSSL_PROVIDER-FIPS 7
.Xr OSSL_SELF_TEST_new 3
.Xr OSSL_LIB_CTX 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
