.Dd 2025-09-30
.Dt OSSL_DECODER_CTX_NEW_FOR_PKEY 3ossl
.Os
.Sh NAME
.Nm OSSL_DECODER_CTX_new_for_pkey ,
.Nm OSSL_DECODER_CTX_set_passphrase ,
.Nm OSSL_DECODER_CTX_set_pem_password_cb ,
.Nm OSSL_DECODER_CTX_set_passphrase_ui ,
.Nm OSSL_DECODER_CTX_set_passphrase_cb
.Nd Decoder routines to decode EVP_PKEYs
.Sh SYNOPSIS
.In openssl/decoder.h
.Ft OSSL_DECODER_CTX *

.Fo OSSL_DECODER_CTX_new_for_pkey
.Fa "EVP_PKEY **pkey"
.Fa "const char *input_type"
.Fa "const char *input_struct"
.Fa "const char *keytype"
.Fa "int selection"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propquery"
.Fc
.Ft int
.Fo OSSL_DECODER_CTX_set_passphrase
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "const unsigned char *kstr"
.Fa "size_t klen"
.Fc
.Ft int
.Fo OSSL_DECODER_CTX_set_pem_password_cb
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "pem_password_cb *cb"
.Fa "void *cbarg"
.Fc
.Ft int
.Fo OSSL_DECODER_CTX_set_passphrase_ui
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "const UI_METHOD *ui_method"
.Fa "void *ui_data"
.Fc
.Ft int
.Fo OSSL_DECODER_CTX_set_passphrase_cb
.Fa "OSSL_DECODER_CTX *ctx"
.Fa "OSSL_PASSPHRASE_CALLBACK *cb"
.Fa "void *cbarg"
.Fc
.Sh DESCRIPTION
.Fn OSSL_DECODER_CTX_new_for_pkey
is a utility function that creates a
.Vt OSSL_DECODER_CTX ,
finds all applicable decoder implementations and sets them up, so all
the caller has to do next is call functions like
.Xr OSSL_DECODER_from_bio 3 .
The caller may use the optional
.Fa input_type ,
.Fa input_struct ,
.Fa keytype
and
.Fa selection
to specify what the input is expected to contain.
The
.Fa pkey
must reference an
.Sy EVP_PKEY *
variable that will be set to the newly created
.Vt EVP_PKEY
on successful decoding.
The referenced variable must be initialized to NULL before calling the
function.
.Pp
Internally
.Fn OSSL_DECODER_CTX_new_for_pkey
searches for all available
.Xr EVP_KEYMGMT 3
implementations, and then builds a list of all potential decoder
implementations that may be able to process the encoded input into data
suitable for
.Vt EVP_PKEY Ns s.
All these implementations are implicitly fetched using
.Fa libctx
and
.Fa propquery .
.Pp
The search of decoder implementations can be limited with
.Fa input_type
and
.Fa input_struct
which specifies a starting input type and input structure.
NULL is valid for both of them and signifies that the decoder
implementations will find out the input type on their own.
They are set with
.Xr OSSL_DECODER_CTX_set_input_type 3
and
.Xr OSSL_DECODER_CTX_set_input_structure 3 .
See
.Sx Input Types
and
.Sx Input Structures
below for further information.
.Pp
The search of decoder implementations can also be limited with
.Fa keytype
and
.Fa selection ,
which specifies the expected resulting keytype and contents.
NULL and zero are valid and signify that the decoder implementations
will find out the keytype and key contents on their own from the input
they get.
.Pp
If no suitable decoder implementation is found,
.Fn OSSL_DECODER_CTX_new_for_pkey
still creates a
.Vt OSSL_DECODER_CTX ,
but with no associated decoder
.Pf ( Xr OSSL_DECODER_CTX_get_num_decoders 3
returns zero).
This helps the caller to distinguish between an error when creating the
.Sy OSSL_ENCODER_CTX
and missing encoder implementation, and allows it to act accordingly.
.Pp
.Fn OSSL_DECODER_CTX_set_passphrase
gives the implementation a pass phrase to use when decrypting the
encoded private key.
Alternatively, a pass phrase callback may be specified with the
following functions.
.Pp
.Fn OSSL_DECODER_CTX_set_pem_password_cb ,
.Fn OSSL_DECODER_CTX_set_passphrase_ui
and
.Fn OSSL_DECODER_CTX_set_passphrase_cb
set up a callback method that the implementation can use to prompt for a
pass phrase, giving the caller the choice of preferred pass phrase
callback form.
These are called indirectly, through an internal
.Xr OSSL_PASSPHRASE_CALLBACK 3
function.
.Pp
The internal
.Xr OSSL_PASSPHRASE_CALLBACK 3
function caches the pass phrase, to be reused in all decodings that are
performed in the same decoding run (for example, within one
.Xr OSSL_DECODER_from_bio 3
call).
.Ss Input Types
Available input types depend on the implementations that available
providers offer, and provider documentation should have the details.
.Pp
Among the known input types that OpenSSL decoder implementations offer
for
.Vt EVP_PKEY Ns s
are
.Qo Li DER Qc ,
.Qo Li PEM Qc ,
.Qo Li MSBLOB Qc
and
.Qo Li PVK Qc .
See
.Xr openssl-glossary 7
for further information on what these input types mean.
.Ss Input Structures
Available input structures depend on the implementations that available
providers offer, and provider documentation should have the details.
.Pp
Among the known input structures that OpenSSL decoder implementations
offer for
.Vt EVP_PKEY Ns s
are
.Qo Li pkcs8 Qc
and
.Qo Li SubjectPublicKeyInfo Qc .
.Pp
OpenSSL decoder implementations also support the input structure
.Qo Li type-specific Qc .
This is the structure used for keys encoded according to key type
specific specifications.
For example, RSA keys encoded according to PKCS#1.
.Ss Selections
.Fa selection
can be any one of the values described in
.Xr EVP_PKEY_fromdata 3 .
Additionally
.Fa selection
can also be set to
.Sy 0
to indicate that the code will auto detect the selection.
.Sh RETURN VALUES
.Fn OSSL_DECODER_CTX_new_for_pkey
returns a pointer to a
.Vt OSSL_DECODER_CTX ,
or NULL if it couldn't be created.
.Pp
.Fn OSSL_DECODER_CTX_set_passphrase ,
.Fn OSSL_DECODER_CTX_set_pem_password_cb ,
.Fn OSSL_DECODER_CTX_set_passphrase_ui
and
.Fn OSSL_DECODER_CTX_set_passphrase_cb
all return 1 on success, or 0 on failure.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr OSSL_DECODER 3 ,
.Xr OSSL_DECODER_CTX 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
