.Dd 2025-09-30
.Dt OSSL_ALGORITHM 3ossl
.Os
.Sh NAME
.Nm OSSL_ALGORITHM
.Nd OpenSSL Core type to define a fetchable algorithm
.Sh SYNOPSIS
.In openssl/core.h
.Bd -literal
 typedef struct ossl_algorithm_st OSSL_ALGORITHM;
 struct ossl_algorithm_st {
     const char *algorithm_names;     /* key */
     const char *property_definition; /* key */
     const OSSL_DISPATCH *implementation;
     const char *algorithm_description;
 };
.Ed
.Sh DESCRIPTION
The
.Sy OSSL_ALGORITHM
type is a
.Em public structure
that describes an algorithm that a
.Xr provider 7
provides.
Arrays of this type are returned by providers on demand from the OpenSSL
libraries to describe what algorithms the providers provide
implementations of, and with what properties.
.Pp
Arrays of this type must be terminated with a tuple where
.Em algorithm_names
is NULL.
.Pp
This type of array is typically returned by the provider's operation
querying function, further described in
.Xr provider-base 7 .
.SsOSSL_ALGORITHM No fields
.Bl -tag -width Ds
.It Em algorithm_names
This string is a colon separated set of names / identities, and is used
by the appropriate fetching functionality (such as
.Xr EVP_CIPHER_fetch 3 ,
.Xr EVP_MD_fetch 3 ,
etc) to find the desired algorithm.
.Pp
Multiple names / identities allow a specific algorithm implementation to
be fetched multiple ways.
For example, the RSA algorithm has the following known identities:
.Bl -bullet
.It
.Qo Li RSA Qc
.It
.Qo Li rsaEncryption Qc
.Pp
This is the name of the algorithm's OBJECT IDENTIFIER (OID), as given by
the
.Lk https://www.rfc-editor.org/rfc/rfc8017#appendix-C
.It
.Qo Li 1.2.840.113549.1.1.1 Qc
.Pp
This is the OID itself for
.Qo Li rsaEncryption Qc ,
in canonical decimal text form.
.El
.Pp
The resulting
.Em algorithm_names
string would look like this:
.Bd -literal
 "RSA:rsaEncryption:1.2.840.113549.1.1.1"
.Ed
.Pp
The OpenSSL libraries use the first of the algorithm names as the main
or canonical name, on a per algorithm implementation basis.
.Pp
See the notes
.Sx On the subject of algorithm names
below for a more in depth discussion on
.Em algorithm_names
and how that may interact with applications and libraries, including
OpenSSL's.
.It Em property_definition
This string defines a set of properties associated with a particular
algorithm implementation, and is used by the appropriate fetching
functionality (such as
.Xr EVP_CIPHER_fetch 3 ,
.Xr EVP_MD_fetch 3 ,
etc) for a finer grained lookup of an algorithm implementation, which is
useful in case multiple implementations of the same algorithm are
available.
.Pp
See
.Xr property 7
for a further description of the contents of this string.
.It Em implementation
Pointer to an
.Xr OSSL_DISPATCH 3
array, containing pointers to the functions of a particular algorithm
implementation.
.It Em algorithm_description
A string with a short human-readable description of the algorithm.
.El
.Sh NOTES
.Ss \&On the subject of algorithm names
Providers may find the need to register ASN.1 OIDs for algorithms using
.Xr OBJ_create 3
(via the
.Sy core_obj_create
upcall described in
.Xr provider-base 7 ,
because some application or library -- possibly still the OpenSSL
libraries, even -- use NIDs to look up algorithms.
.Pp
In that scenario, you must make sure that the corresponding
.Sy OSSL_ALGORITHM Ns 's
.Em algorithm_names
includes both the short and the long name.
.Pp
Most of the time, registering ASN.1 OIDs like this shouldn't be
necessary, and applications and libraries are encouraged to use
.Xr OBJ_obj2txt 3
to get a text representation of the OID, which may be a long or short
name for OIDs that are registered, or the OID itself in canonical
decimal text form if not (or if
.Xr OBJ_obj2txt 3
is called with
.Em no_name
= 1).
.Pp
It's recommended to make sure that the corresponding
.Sy OSSL_ALGORITHM Ns 's
.Em algorithm_names
include known names as well as the OID itself in canonical decimal text
form.
That should cover all scenarios.
.Sh SEE ALSO
.Xr crypto 7 ,
.Xr provider-base 7 ,
.Xr openssl-core.h 7 ,
.Xr openssl-core_dispatch.h 7 ,
.Xr OSSL_DISPATCH 3
.Sh HISTORY
.Sy OSSL_ALGORITHM
was added in OpenSSL 3.0
.Sh COPYRIGHT
Copyright 2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
