.Dd 2025-09-30
.Dt OSSL_STORE_LOADER 3ossl
.Os
.Sh NAME
.Nm OSSL_STORE_LOADER ,
.Nm OSSL_STORE_LOADER_fetch ,
.Nm OSSL_STORE_LOADER_up_ref ,
.Nm OSSL_STORE_LOADER_free ,
.Nm OSSL_STORE_LOADER_get0_provider ,
.Nm OSSL_STORE_LOADER_get0_properties ,
.Nm OSSL_STORE_LOADER_is_a ,
.Nm OSSL_STORE_LOADER_get0_description ,
.Nm OSSL_STORE_LOADER_do_all_provided ,
.Nm OSSL_STORE_LOADER_names_do_all ,
.Nm OSSL_STORE_LOADER_CTX ,
.Nm OSSL_STORE_LOADER_new ,
.Nm OSSL_STORE_LOADER_get0_engine ,
.Nm OSSL_STORE_LOADER_get0_scheme ,
.Nm OSSL_STORE_LOADER_set_open ,
.Nm OSSL_STORE_LOADER_set_open_ex ,
.Nm OSSL_STORE_LOADER_set_attach ,
.Nm OSSL_STORE_LOADER_set_ctrl ,
.Nm OSSL_STORE_LOADER_set_expect ,
.Nm OSSL_STORE_LOADER_set_find ,
.Nm OSSL_STORE_LOADER_set_load ,
.Nm OSSL_STORE_LOADER_set_eof ,
.Nm OSSL_STORE_LOADER_set_error ,
.Nm OSSL_STORE_LOADER_set_close ,
.Nm OSSL_STORE_register_loader ,
.Nm OSSL_STORE_unregister_loader ,
.Nm OSSL_STORE_open_fn ,
.Nm OSSL_STORE_open_ex_fn ,
.Nm OSSL_STORE_attach_fn ,
.Nm OSSL_STORE_ctrl_fn ,
.Nm OSSL_STORE_expect_fn ,
.Nm OSSL_STORE_find_fn ,
.Nm OSSL_STORE_load_fn ,
.Nm OSSL_STORE_eof_fn ,
.Nm OSSL_STORE_error_fn ,
.Nm OSSL_STORE_close_fn
.Nd Types and functions to manipulate, register and unregister STORE loaders for different URI schemes
.Sh SYNOPSIS
.In openssl/store.h
.Ft typedef struct ossl_store_loader_st OSSL_STORE_LOADER;

 OSSL_STORE_LOADER *
.Fo OSSL_STORE_LOADER_fetch
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *scheme"
.Fa "const char *properties"
.Fc
.Ft int
.Fo OSSL_STORE_LOADER_up_ref
.Fa "OSSL_STORE_LOADER *loader"
.Fc
.Ft void
.Fo OSSL_STORE_LOADER_free
.Fa "OSSL_STORE_LOADER *loader"
.Fc
.Ft const OSSL_PROVIDER *
.Fo OSSL_STORE_LOADER_get0_provider
.Fa "const OSSL_STORE_LOADER *                                                  loader"
.Fc
.Ft const char *
.Fo OSSL_STORE_LOADER_get0_properties
.Fa "const OSSL_STORE_LOADER *loader"
.Fc
.Ft const char *
.Fo OSSL_STORE_LOADER_get0_description
.Fa "const OSSL_STORE_LOADER *loader"
.Fc
.Ft int
.Fo OSSL_STORE_LOADER_is_a
.Fa "const OSSL_STORE_LOADER *loader"
.Fa "const char *scheme"
.Fc
.Ft void
.Fo OSSL_STORE_LOADER_do_all_provided
.Fa "OSSL_LIB_CTX *libctx"
.Fa "void (*user_fn)(OSSL_STORE_LOADER *loader"
.Fa "void *arg)"
.Fa "void *user_arg"
.Fc
.Ft int
.Fo OSSL_STORE_LOADER_names_do_all
.Fa "const OSSL_STORE_LOADER *loader"
.Fa "void (*fn)(const char *name"
.Fa "void *data)"
.Fa "void *data"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft OSSL_STORE_LOADER *
.Fo OSSL_STORE_LOADER_new
.Fa "ENGINE *e"
.Fa "const char *scheme"
.Fc
.Ft const ENGINE *
.Fo OSSL_STORE_LOADER_get0_engine
.Fa "const OSSL_STORE_LOADER                                              *store_loader"
.Fc
.Ft const char *
.Fo OSSL_STORE_LOADER_get0_scheme
.Fa "const OSSL_STORE_LOADER                                            *store_loader"
.Fc
.Ft /* struct ossl_store_loader_ctx_st is defined differently by each loader */
 typedef struct ossl_store_loader_ctx_st OSSL_STORE_LOADER_CTX;

 typedef OSSL_STORE_LOADER_CTX *
.Fo 
.Fa *OSSL_STORE_open_fn
.Fc
(
.Bd -literal
     const char *uri, const UI_METHOD *ui_method, void *ui_data);
 int OSSL_STORE_LOADER_set_open(OSSL_STORE_LOADER *store_loader,
                                OSSL_STORE_open_fn store_open_function);
 typedef OSSL_STORE_LOADER_CTX *(*OSSL_STORE_open_ex_fn)(
     const char *uri, const UI_METHOD *ui_method, void *ui_data);
 int OSSL_STORE_LOADER_set_open_ex
     (OSSL_STORE_LOADER *store_loader,
      OSSL_STORE_open_ex_fn store_open_ex_function);
 typedef OSSL_STORE_LOADER_CTX *(*OSSL_STORE_attach_fn)
     (const OSSL_STORE_LOADER *loader, BIO *bio,
      OSSL_LIB_CTX *libctx, const char *propq,
      const UI_METHOD *ui_method, void *ui_data);
 int OSSL_STORE_LOADER_set_attach(OSSL_STORE_LOADER *loader,
                                  OSSL_STORE_attach_fn attach_function);
 typedef int (*OSSL_STORE_ctrl_fn)(OSSL_STORE_LOADER_CTX *ctx, int cmd,
                                   va_list args);
 int OSSL_STORE_LOADER_set_ctrl(OSSL_STORE_LOADER *store_loader,
                                OSSL_STORE_ctrl_fn store_ctrl_function);
 typedef int (*OSSL_STORE_expect_fn)(OSSL_STORE_LOADER_CTX *ctx, int expected);
 int OSSL_STORE_LOADER_set_expect(OSSL_STORE_LOADER *loader,
                                  OSSL_STORE_expect_fn expect_function);
 typedef int (*OSSL_STORE_find_fn)(OSSL_STORE_LOADER_CTX *ctx,
                                   OSSL_STORE_SEARCH *criteria);
 int OSSL_STORE_LOADER_set_find(OSSL_STORE_LOADER *loader,
                                OSSL_STORE_find_fn find_function);
 typedef OSSL_STORE_INFO *(*OSSL_STORE_load_fn)(OSSL_STORE_LOADER_CTX *ctx,
                                                UI_METHOD *ui_method,
                                                void *ui_data);
 int OSSL_STORE_LOADER_set_load(OSSL_STORE_LOADER *store_loader,
                                OSSL_STORE_load_fn store_load_function);
 typedef int (*OSSL_STORE_eof_fn)(OSSL_STORE_LOADER_CTX *ctx);
 int OSSL_STORE_LOADER_set_eof(OSSL_STORE_LOADER *store_loader,
                               OSSL_STORE_eof_fn store_eof_function);
 typedef int (*OSSL_STORE_error_fn)(OSSL_STORE_LOADER_CTX *ctx);
 int OSSL_STORE_LOADER_set_error(OSSL_STORE_LOADER *store_loader,
                                 OSSL_STORE_error_fn store_error_function);
 typedef int (*OSSL_STORE_close_fn)(OSSL_STORE_LOADER_CTX *ctx);
 int OSSL_STORE_LOADER_set_close(OSSL_STORE_LOADER *store_loader,
                                 OSSL_STORE_close_fn store_close_function);
.Ed
.Ft int
.Fo OSSL_STORE_register_loader
.Fa "OSSL_STORE_LOADER *loader"
.Fc
.Ft OSSL_STORE_LOADER *
.Fo OSSL_STORE_unregister_loader
.Fa "const char *scheme"
.Fc
.Sh DESCRIPTION
.Vt OSSL_STORE_LOADER
is a method for OSSL_STORE loaders, which implement
.Xr OSSL_STORE_open 3 ,
.Xr OSSL_STORE_open_ex 3 ,
.Xr OSSL_STORE_load 3 ,
.Xr OSSL_STORE_eof 3 ,
.Xr OSSL_STORE_error 3
and
.Xr OSSL_STORE_close 3
for specific storage schemes.
.Pp
.Fn OSSL_STORE_LOADER_fetch
looks for an implementation for a storage
.Fa scheme
within the providers that has been loaded into the
.Vt OSSL_LIB_CTX
given by
.Fa libctx ,
and with the properties given by
.Fa properties .
.Pp
.Fn OSSL_STORE_LOADER_up_ref
increments the reference count for the given
.Fa loader .
.Pp
.Fn OSSL_STORE_LOADER_free
decrements the reference count for the given
.Fa loader ,
and when the count reaches zero, frees it.
If the argument is NULL, nothing is done.
.Pp
.Fn OSSL_STORE_LOADER_get0_provider
returns the provider of the given
.Fa loader .
.Pp
.Fn OSSL_STORE_LOADER_get0_properties
returns the property definition associated with the given
.Fa loader .
.Pp
.Fn OSSL_STORE_LOADER_is_a
checks if
.Fa loader
is an implementation of an algorithm that's identifiable with
.Fa scheme .
.Pp
.Fn OSSL_STORE_LOADER_get0_description
returns a description of the
.Fa loader ,
meant for display and human consumption.
The description is at the discretion of the
.Fa loader
implementation.
.Pp
.Fn OSSL_STORE_LOADER_do_all_provided
traverses all store implementations by all activated providers in the
library context
.Fa libctx ,
and for each of the implementations, calls
.Em user_fn
with the implementation method and
.Fa user_arg
as arguments.
.Pp
.Fn OSSL_STORE_LOADER_names_do_all
traverses all names for the given
.Fa loader ,
and calls
.Em fn
with each name and
.Fa data .
.Ss Legacy Types and Functions (deprecated)
These functions help applications and engines to create loaders for
schemes they support.
These are all deprecated and discouraged in favour of provider
implementations, see
.Xr provider-storemgmt 7 .
.Pp
.Sy OSSL_STORE_LOADER_CTX
is a type template, to be defined by each loader using
.Qo Li struct ossl_store_loader_ctx_st { ... } Qc .
.Pp
.Fa OSSL_STORE_open_fn ,
.Sy OSSL_STORE_open_ex_fn ,
.Sy OSSL_STORE_ctrl_fn ,
.Sy OSSL_STORE_expect_fn ,
.Sy OSSL_STORE_find_fn ,
.Sy OSSL_STORE_load_fn ,
.Sy OSSL_STORE_eof_fn ,
and
.Sy OSSL_STORE_close_fn
are the function pointer types used within a STORE loader.
The functions pointed at define the functionality of the given loader.
.Bl -tag -width Ds
.It Fa OSSL_STORE_open_fn No and Sy OSSL_STORE_open_ex_fn
.Sy OSSL_STORE_open_ex_fn
takes a URI and is expected to interpret it in the best manner possible
according to the scheme the loader implements.
It also takes a
.Sy UI_METHOD
and associated data, to be used any time something needs to be prompted
for, as well as a library context
.Fa libctx
with an associated property query
.Em propq ,
to be used when fetching necessary algorithms to perform the loads.
Furthermore, this function is expected to initialize what needs to be
initialized, to create a private data store
.Pf ( Sy OSSL_STORE_LOADER_CTX ,
see above), and to return it.
If something goes wrong, this function is expected to return NULL.
.Pp
.Fa OSSL_STORE_open_fn
does the same thing as
.Sy OSSL_STORE_open_ex_fn
but uses NULL for the library context
.Fa libctx
and property query
.Em propq .
.It Sy OSSL_STORE_attach_fn
This function takes a
.Sy BIO ,
otherwise works like
.Sy OSSL_STORE_open_ex_fn .
.It Sy OSSL_STORE_ctrl_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer, a command number
.Em cmd
and a
.Sy va_list
.Em args
and is used to manipulate loader specific parameters.
.Pp
Loader specific command numbers must begin at
.Sy OSSL_STORE_C_CUSTOM_START .
Any number below that is reserved for future globally known command
numbers.
.Pp
This function is expected to return 1 on success, 0 on error.
.It Sy OSSL_STORE_expect_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer and a
.Sy OSSL_STORE_INFO
identity
.Em expected ,
and is used to tell the loader what object type is expected.
.Em expected
may be zero to signify that no specific object type is expected.
.Pp
This function is expected to return 1 on success, 0 on error.
.It Sy OSSL_STORE_find_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer and a
.Sy OSSL_STORE_SEARCH
search criterion, and is used to tell the loader what to search for.
.Pp
When called with the loader context being NULL, this function is
expected to return 1 if the loader supports the criterion, otherwise 0.
.Pp
When called with the loader context being something other than NULL,
this function is expected to return 1 on success, 0 on error.
.It Sy OSSL_STORE_load_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer and a
.Sy UI_METHOD
with associated data.
It's expected to load the next available data, mold it into a data
structure that can be wrapped in a
.Sy OSSL_STORE_INFO
using one of the
.Xr OSSL_STORE_INFO 3
functions.
If no more data is available or an error occurs, this function is
expected to return NULL. The
.Sy OSSL_STORE_eof_fn
and
.Sy OSSL_STORE_error_fn
functions must indicate if it was in fact the end of data or if an error
occurred.
.Pp
Note that this function retrieves
.Em one
data item only.
.It Sy OSSL_STORE_eof_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer and is expected to return 1 to indicate that the end of
available data has been reached.
It is otherwise expected to return 0.
.It Sy OSSL_STORE_error_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer and is expected to return 1 to indicate that an error occurred
in a previous call to the
.Sy OSSL_STORE_load_fn
function.
It is otherwise expected to return 0.
.It Sy OSSL_STORE_close_fn
This function takes a
.Sy OSSL_STORE_LOADER_CTX
pointer and is expected to close or shut down what needs to be closed,
and finally free the contents of the
.Sy OSSL_STORE_LOADER_CTX
pointer.
It returns 1 on success and 0 on error.
.El
.Pp
.Fn OSSL_STORE_LOADER_new
creates a new
.Vt OSSL_STORE_LOADER .
It takes an
.Vt ENGINE
.Fa e
and a string
.Fa scheme .
.Fa scheme
must
.Em always
be set.
Both
.Fa e
and
.Fa scheme
are used as is and must therefore be alive as long as the created loader
is.
.Pp
.Fn OSSL_STORE_LOADER_get0_engine
returns the engine of the
.Fa store_loader .
.Fn OSSL_STORE_LOADER_get0_scheme
returns the scheme of the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_open 3
sets the opener function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_open_ex 3
sets the opener with library context function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_attach 3
sets the attacher function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_ctrl 3
sets the control function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_expect 3
sets the expect function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_load 3
sets the loader function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_eof 3
sets the end of file checker function for the
.Fa store_loader .
.Pp
.Xr OSSL_STORE_LOADER_set_close 3
sets the closing function for the
.Fa store_loader .
.Pp
.Fn OSSL_STORE_LOADER_free
frees the given
.Fa store_loader .
If the argument is NULL, nothing is done.
.Pp
.Fn OSSL_STORE_register_loader
register the given
.Fa store_loader
and thereby makes it available for use with
.Xr OSSL_STORE_open 3 ,
.Xr OSSL_STORE_open_ex 3 ,
.Xr OSSL_STORE_load 3 ,
.Xr OSSL_STORE_eof 3
and
.Xr OSSL_STORE_close 3 .
.Pp
.Fn OSSL_STORE_unregister_loader
unregister the store loader for the given
.Fa scheme .
.Sh RETURN VALUES
.Fn OSSL_STORE_LOADER_fetch
returns a pointer to an OSSL_STORE_LOADER object, or NULL on error.
.Pp
.Fn OSSL_STORE_LOADER_up_ref
returns 1 on success, or 0 on error.
.Pp
.Fn OSSL_STORE_LOADER_names_do_all
returns 1 if the callback was called for all names.
A return value of 0 means that the callback was not called for any
names.
.Pp
.Fn OSSL_STORE_LOADER_free
doesn't return any value.
.Pp
.Fn OSSL_STORE_LOADER_get0_provider
returns a pointer to a provider object, or NULL on error.
.Pp
.Fn OSSL_STORE_LOADER_get0_properties
returns a pointer to a property definition string, or NULL on error.
.Pp
.Fn OSSL_STORE_LOADER_is_a
returns 1 if
.Fa loader
was identifiable, otherwise 0.
.Pp
.Fn OSSL_STORE_LOADER_get0_description
returns a pointer to a description, or NULL if there isn't one.
.Pp
The functions with the types
.Fa OSSL_STORE_open_fn ,
.Sy OSSL_STORE_open_ex_fn ,
.Sy OSSL_STORE_ctrl_fn ,
.Sy OSSL_STORE_expect_fn ,
.Sy OSSL_STORE_load_fn ,
.Sy OSSL_STORE_eof_fn
and
.Sy OSSL_STORE_close_fn
have the same return values as
.Xr OSSL_STORE_open 3 ,
.Xr OSSL_STORE_open_ex 3 ,
.Xr OSSL_STORE_ctrl 3 ,
.Xr OSSL_STORE_expect 3 ,
.Xr OSSL_STORE_load 3 ,
.Xr OSSL_STORE_eof 3
and
.Xr OSSL_STORE_close 3 ,
respectively.
.Pp
.Fn OSSL_STORE_LOADER_new
returns a pointer to a
.Vt OSSL_STORE_LOADER
on success, or NULL on failure.
.Pp
.Xr OSSL_STORE_LOADER_set_open 3 ,
.Xr OSSL_STORE_LOADER_set_open_ex 3 ,
.Xr OSSL_STORE_LOADER_set_ctrl 3 ,
.Xr OSSL_STORE_LOADER_set_load 3 ,
.Xr OSSL_STORE_LOADER_set_eof 3
and
.Xr OSSL_STORE_LOADER_set_close 3
return 1 on success, or 0 on failure.
.Pp
.Fn OSSL_STORE_register_loader
returns 1 on success, or 0 on failure.
.Pp
.Fn OSSL_STORE_unregister_loader
returns the unregistered loader on success, or NULL on failure.
.Sh SEE ALSO
.Xr ossl_store 7 ,
.Xr OSSL_STORE_open 3 ,
.Xr OSSL_LIB_CTX 3 ,
.Xr provider-storemgmt 7
.Sh HISTORY
.Fn OSSL_STORE_LOADER_fetch ,
.Fn OSSL_STORE_LOADER_up_ref ,
.Fn OSSL_STORE_LOADER_get0_provider ,
.Fn OSSL_STORE_LOADER_get0_properties ,
.Fn OSSL_STORE_LOADER_get0_description ,
.Fn OSSL_STORE_LOADER_is_a ,
.Fn OSSL_STORE_LOADER_do_all_provided
and
.Fn OSSL_STORE_LOADER_names_do_all
were added in OpenSSL 3.0.
.Pp
.Vt OSSL_STORE_LOADER
and
.Fn OSSL_STORE_LOADER_free
were added in OpenSSL 1.1.1.
.Pp
.Xr OSSL_STORE_LOADER_set_open_ex 3
and
.Xr OSSL_STORE_open_ex_fn 3
were added in OpenSSL 3.0, and are deprecated.
.Pp
.Sy OSSL_STORE_LOADER_CTX ,
.Fn OSSL_STORE_LOADER_new ,
.Xr OSSL_STORE_LOADER_set0_scheme 3 ,
.Fn OSSL_STORE_LOADER_get0_scheme ,
.Fn OSSL_STORE_LOADER_get0_engine ,
.Xr OSSL_STORE_LOADER_set_expect 3 ,
.Xr OSSL_STORE_LOADER_set_find 3 ,
.Xr OSSL_STORE_LOADER_set_attach 3 ,
.Xr OSSL_STORE_LOADER_set_open_ex 3 ,
.Xr OSSL_STORE_LOADER_set_open 3 ,
.Xr OSSL_STORE_LOADER_set_ctrl 3 ,
.Xr OSSL_STORE_LOADER_set_load 3 ,
.Xr OSSL_STORE_LOADER_set_eof 3 ,
.Xr OSSL_STORE_LOADER_set_close 3 ,
.Fn OSSL_STORE_register_loader ,
.Xr OSSL_STORE_LOADER_set_error 3 ,
.Fn OSSL_STORE_unregister_loader ,
OSSL_STORE_open_fn(),
.Xr OSSL_STORE_ctrl_fn 3 ,
.Xr OSSL_STORE_load_fn 3 ,
.Xr OSSL_STORE_eof_fn 3
and
.Xr OSSL_STORE_close_fn 3
were added in OpenSSL 1.1.1, and became deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
