.Dd 2025-09-30
.Dt OSSL_ENCODER_CTX 3ossl
.Os
.Sh NAME
.Nm OSSL_ENCODER_CTX ,
.Nm OSSL_ENCODER_CTX_new ,
.Nm OSSL_ENCODER_settable_ctx_params ,
.Nm OSSL_ENCODER_CTX_set_params ,
.Nm OSSL_ENCODER_CTX_free ,
.Nm OSSL_ENCODER_CTX_set_selection ,
.Nm OSSL_ENCODER_CTX_set_output_type ,
.Nm OSSL_ENCODER_CTX_set_output_structure ,
.Nm OSSL_ENCODER_CTX_add_encoder ,
.Nm OSSL_ENCODER_CTX_add_extra ,
.Nm OSSL_ENCODER_CTX_get_num_encoders ,
.Nm OSSL_ENCODER_INSTANCE ,
.Nm OSSL_ENCODER_INSTANCE_get_encoder ,
.Nm OSSL_ENCODER_INSTANCE_get_encoder_ctx ,
.Nm OSSL_ENCODER_INSTANCE_get_output_type ,
.Nm OSSL_ENCODER_INSTANCE_get_output_structure ,
.Nm OSSL_ENCODER_CONSTRUCT ,
.Nm OSSL_ENCODER_CLEANUP ,
.Nm OSSL_ENCODER_CTX_set_construct ,
.Nm OSSL_ENCODER_CTX_set_construct_data ,
.Nm OSSL_ENCODER_CTX_set_cleanup
.Nd Encoder context routines
.Sh SYNOPSIS
.In openssl/encoder.h
.Ft typedef struct ossl_encoder_ctx_st OSSL_ENCODER_CTX;

 OSSL_ENCODER_CTX *
.Fo OSSL_ENCODER_CTX_new
.Fa 
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_ENCODER_settable_ctx_params
.Fa "OSSL_ENCODER *encoder"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_params
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft void
.Fo OSSL_ENCODER_CTX_free
.Fa "OSSL_ENCODER_CTX *ctx"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_selection
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "int selection"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_output_type
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "const char *output_type"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_output_structure
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "const char *output_structure"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_add_encoder
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "OSSL_ENCODER *encoder"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_add_extra
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_get_num_encoders
.Fa "OSSL_ENCODER_CTX *ctx"
.Fc
.Ft typedef struct ossl_encoder_instance_st OSSL_ENCODER_INSTANCE;
 OSSL_ENCODER *

.Fo OSSL_ENCODER_INSTANCE_get_encoder
.Fa "OSSL_ENCODER_INSTANCE *encoder_inst"
.Fc
.Ft void *

.Fo OSSL_ENCODER_INSTANCE_get_encoder_ctx
.Fa "OSSL_ENCODER_INSTANCE *encoder_inst"
.Fc
.Ft const char *

.Fo OSSL_ENCODER_INSTANCE_get_output_type
.Fa "OSSL_ENCODER_INSTANCE *encoder_inst"
.Fc
.Ft const char *

.Fo OSSL_ENCODER_INSTANCE_get_output_structure
.Fa "OSSL_ENCODER_INSTANCE *encoder_inst"
.Fc
.Ft typedef const void *
.Fo OSSL_ENCODER_CONSTRUCT
.Fa "OSSL_ENCODER_INSTANCE *encoder_inst"
.Fa "void *construct_data"
.Fc
.Ft typedef void
.Fo OSSL_ENCODER_CLEANUP
.Fa "void *construct_data"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_construct
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "OSSL_ENCODER_CONSTRUCT *construct"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_construct_data
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "void *construct_data"
.Fc
.Ft int
.Fo OSSL_ENCODER_CTX_set_cleanup
.Fa "OSSL_ENCODER_CTX *ctx"
.Fa "OSSL_ENCODER_CLEANUP *cleanup"
.Fc
.Sh DESCRIPTION
Encoding an input object to the desired encoding may be done with a
chain of encoder implementations, which means that the output from one
encoder may be the input for the next in the chain.
The
.Vt OSSL_ENCODER_CTX
holds all the data about these encoders.
This allows having generic format encoders such as DER to PEM, as well
as more specialized encoders like RSA to DER.
.Pp
The final output type must be given, and a chain of encoders must end
with an implementation that produces that output type.
.Pp
At the beginning of the encoding process, a constructor provided by the
caller is called to ensure that there is an appropriate provider-side
object to start with.
The constructor is set with
.Fn OSSL_ENCODER_CTX_set_construct .
.Pp
.Vt OSSL_ENCODER_INSTANCE
is an opaque structure that contains data about the encoder that is
going to be used, and that may be useful for the constructor.
There are some functions to extract data from this type, described in
.Sx Constructor
below.
.Ss Functions
.Fn OSSL_ENCODER_CTX_new
creates a
.Vt OSSL_ENCODER_CTX .
.Pp
.Fn OSSL_ENCODER_settable_ctx_params
returns an
.Xr OSSL_PARAM 3
array of parameter descriptors.
.Pp
.Fn OSSL_ENCODER_CTX_set_params
attempts to set parameters specified with an
.Xr OSSL_PARAM 3
array
.Em params .
Parameters that the implementation doesn't recognise should be ignored.
.Pp
.Fn OSSL_ENCODER_CTX_free
frees the given context
.Fa ctx .
If the argument is NULL, nothing is done.
.Pp
.Fn OSSL_ENCODER_CTX_add_encoder
populates the
.Vt OSSL_ENCODER_CTX
.Fa ctx
with a encoder, to be used to encode an input object.
.Pp
.Fn OSSL_ENCODER_CTX_add_extra
finds encoders that further encodes output from already added encoders,
and adds them as well.
This is used to build encoder chains.
.Pp
.Fn OSSL_ENCODER_CTX_set_output_type
sets the ending output type.
This must be specified, and determines if a complete encoder chain is
available.
.Pp
.Fn OSSL_ENCODER_CTX_set_output_structure
sets the desired output structure.
This may be used to determines what encoder implementations may be used.
Depending on the type of object being encoded, the output structure may
not be relevant.
.Pp
.Fn OSSL_ENCODER_CTX_get_num_encoders
gets the number of encoders currently added to the context
.Fa ctx .
.Pp
.Fn OSSL_ENCODER_CTX_set_construct
sets the constructor
.Fa construct .
.Pp
.Fn OSSL_ENCODER_CTX_set_construct_data
sets the constructor data that is passed to the constructor every time
it's called.
.Pp
.Fn OSSL_ENCODER_CTX_set_cleanup
sets the constructor data
.Fa cleanup
function.
This is called by
.Xr OSSL_ENCODER_CTX_free 3 .
.Ss Constructor
A
.Vt OSSL_ENCODER_CONSTRUCT
gets the following arguments:
.Bl -tag -width Ds
.It Fa encoder_inst
The
.Vt OSSL_ENCODER_INSTANCE
for the encoder from which the constructor gets its data.
.It Fa construct_data
The pointer that was set with
.Xr OSSL_ENCODE_CTX_set_construct_data 3 .
.El
.Pp
The constructor is expected to return a valid (non-NULL) pointer to a
provider-native object that can be used as first input of an encoding
chain, or NULL to indicate that an error has occurred.
.Pp
These utility functions may be used by a constructor:
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_encoder
can be used to get the encoder implementation of the encoder instance
.Fa encoder_inst .
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_encoder_ctx
can be used to get the encoder implementation's provider context of the
encoder instance
.Fa encoder_inst .
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_output_type
can be used to get the output type for the encoder implementation of the
encoder instance
.Fa encoder_inst .
This will never be NULL.
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_output_structure
can be used to get the output structure for the encoder implementation
of the encoder instance
.Fa encoder_inst .
This may be NULL.
.Sh RETURN VALUES
.Fn OSSL_ENCODER_CTX_new
returns a pointer to a
.Vt OSSL_ENCODER_CTX ,
or NULL if the context structure couldn't be allocated.
.Pp
.Fn OSSL_ENCODER_settable_ctx_params
returns an
.Xr OSSL_PARAM 3
array, or NULL if none is available.
.Pp
.Fn OSSL_ENCODER_CTX_set_params
returns 1 if all recognised parameters were valid, or 0 if one of them
was invalid or caused some other failure in the implementation.
.Pp
.Fn OSSL_ENCODER_CTX_add_encoder ,
.Fn OSSL_ENCODER_CTX_add_extra ,
.Fn OSSL_ENCODER_CTX_set_construct ,
.Fn OSSL_ENCODER_CTX_set_construct_data
and
.Fn OSSL_ENCODER_CTX_set_cleanup
return 1 on success, or 0 on failure.
.Pp
.Fn OSSL_ENCODER_CTX_get_num_encoders
returns the current number of encoders.
It returns 0 if
.Fa ctx
is NULL.
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_encoder
returns an
.Vt OSSL_ENCODER
pointer on success, or NULL on failure.
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_encoder_ctx
returns a provider context pointer on success, or NULL on failure.
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_output_type
returns a string with the name of the input type, if relevant.
NULL is a valid returned value.
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_output_type
returns a string with the name of the output type.
.Pp
.Fn OSSL_ENCODER_INSTANCE_get_output_structure
returns a string with the name of the output structure.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr OSSL_ENCODER 3
.Sh HISTORY
The functions described here were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
