.Dd 2025-09-30
.Dt OSSL_CRMF_MSG_GET0_TMPL 3ossl
.Os
.Sh NAME
.Nm OSSL_CRMF_MSG_get0_tmpl ,
.Nm OSSL_CRMF_CERTTEMPLATE_get0_publicKey ,
.Nm OSSL_CRMF_CERTTEMPLATE_get0_subject ,
.Nm OSSL_CRMF_CERTTEMPLATE_get0_issuer ,
.Nm OSSL_CRMF_CERTTEMPLATE_get0_serialNumber ,
.Nm OSSL_CRMF_CERTTEMPLATE_get0_extensions ,
.Nm OSSL_CRMF_CERTID_get0_serialNumber ,
.Nm OSSL_CRMF_CERTID_get0_issuer ,
.Nm OSSL_CRMF_ENCRYPTEDKEY_get1_encCert ,
.Nm OSSL_CRMF_ENCRYPTEDKEY_get1_pkey ,
.Nm OSSL_CRMF_ENCRYPTEDKEY_init_envdata ,
.Nm OSSL_CRMF_ENCRYPTEDVALUE_decrypt ,
.Nm OSSL_CRMF_ENCRYPTEDVALUE_get1_encCert ,
.Nm OSSL_CRMF_MSG_get_certReqId ,
.Nm OSSL_CRMF_MSG_centralkeygen_requested
.Nd functions reading from CRMF CertReqMsg structures
.Sh SYNOPSIS
.In openssl/crmf.h
.Ft OSSL_CRMF_CERTTEMPLATE *
.Fo OSSL_CRMF_MSG_get0_tmpl
.Fa "const OSSL_CRMF_MSG *crm"
.Fc
.Ft X509_PUBKEY
 *
.Fo OSSL_CRMF_CERTTEMPLATE_get0_publicKey
.Fa "const OSSL_CRMF_CERTTEMPLATE *tmpl"
.Fc
.Ft const X509_NAME
 *
.Fo OSSL_CRMF_CERTTEMPLATE_get0_subject
.Fa "const OSSL_CRMF_CERTTEMPLATE *tmpl"
.Fc
.Ft const X509_NAME
 *
.Fo OSSL_CRMF_CERTTEMPLATE_get0_issuer
.Fa "const OSSL_CRMF_CERTTEMPLATE *tmpl"
.Fc
.Ft const ASN1_INTEGER
 *
.Fo OSSL_CRMF_CERTTEMPLATE_get0_serialNumber
.Fa "const OSSL_CRMF_CERTTEMPLATE *tmpl"
.Fc
.Ft X509_EXTENSIONS
 *
.Fo OSSL_CRMF_CERTTEMPLATE_get0_extensions
.Fa "const OSSL_CRMF_CERTTEMPLATE *tmpl"
.Fc
.Ft const ASN1_INTEGER
 *
.Fo OSSL_CRMF_CERTID_get0_serialNumber
.Fa "const OSSL_CRMF_CERTID *cid"
.Fc
.Ft const X509_NAME *
.Fo OSSL_CRMF_CERTID_get0_issuer
.Fa "const OSSL_CRMF_CERTID *cid"
.Fc
.Ft X509 *
.Fo OSSL_CRMF_ENCRYPTEDKEY_get1_encCert
.Fa "const OSSL_CRMF_ENCRYPTEDKEY *ecert"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "EVP_PKEY *pkey"
.Fa "unsigned int flags"
.Fc
.Ft EVP_PKEY
 *
.Fo OSSL_CRMF_ENCRYPTEDKEY_get1_pkey
.Fa "OSSL_CRMF_ENCRYPTEDKEY *encryptedKey"
.Fa "X509_STORE *ts"
.Fa "STACK_OF(X509) *extra"
.Fa "EVP_PKEY *pkey"
.Fa "X509 *cert"
.Fa "ASN1_OCTET_STRING *secret"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft OSSL_CRMF_ENCRYPTEDKEY
 *
.Fo OSSL_CRMF_ENCRYPTEDKEY_init_envdata
.Fa "CMS_EnvelopedData *envdata"
.Fc
.Ft unsigned char
 *
.Fo OSSL_CRMF_ENCRYPTEDVALUE_decrypt
.Fa "const OSSL_CRMF_ENCRYPTEDVALUE *enc"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "EVP_PKEY *pkey"
.Fa "int *outlen"
.Fc
.Ft X509
 *
.Fo OSSL_CRMF_ENCRYPTEDVALUE_get1_encCert
.Fa "const OSSL_CRMF_ENCRYPTEDVALUE *ecert"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_get_certReqId
.Fa "const OSSL_CRMF_MSG *crm"
.Fc
.Ft int
.Fo OSSL_CRMF_MSG_centralkeygen_requested
.Fa "const OSSL_CRMF_MSG *crm"
.Fa "const X509_REQ *p10cr"
.Fc
.Sh DESCRIPTION
.Fn OSSL_CRMF_MSG_get0_tmpl
retrieves the certificate template of
.Fa crm .
.Pp
.Fn OSSL_CRMF_CERTTEMPLATE_get0_publicKey
retrieves the public key of the given certificate template
.Fa tmpl .
.Pp
.Fn OSSL_CRMF_CERTTEMPLATE_get0_subject
retrieves the subject name of the given certificate template
.Fa tmpl .
.Pp
.Fn OSSL_CRMF_CERTTEMPLATE_get0_issuer
retrieves the issuer name of the given certificate template
.Fa tmpl .
.Pp
.Fn OSSL_CRMF_CERTTEMPLATE_get0_serialNumber
retrieves the serialNumber of the given certificate template
.Fa tmpl .
.Pp
.Fn OSSL_CRMF_CERTTEMPLATE_get0_extensions
retrieves the X.509 extensions of the given certificate template
.Fa tmpl ,
or NULL if not present.
.Pp
OSSL_CRMF_CERTID_get0_serialNumber retrieves the serialNumber of the
given CertId
.Fa cid .
.Pp
OSSL_CRMF_CERTID_get0_issuer retrieves the issuer name of the given
CertId
.Fa cid ,
which must be of ASN.1 type GEN_DIRNAME.
.Pp
.Fn OSSL_CRMF_ENCRYPTEDKEY_get1_encCert
decrypts the certificate in the given encryptedKey
.Fa ecert ,
using the private key
.Fa pkey ,
library context
.Fa libctx
and property query string
.Fa propq
(see
.Xr OSSL_LIB_CTX 3 Ns ).
This is needed for the indirect POPO method as in RFC 4210 section
5.2.8.2. The function returns the decrypted certificate as a copy,
leaving its ownership with the caller, who is responsible for freeing
it.
.Pp
.Fn OSSL_CRMF_ENCRYPTEDKEY_get1_pkey
decrypts the private key in
.Fa encryptedKey .
If
.Fa encryptedKey
is not of type
.Sy OSSL_CRMF_ENCRYPTEDKEY_ENVELOPEDDATA ,
decryption uses the private key
.Fa pkey .
The library context
.Fa libctx
and property query
.Fa propq
are taken into account as usual.
The rest of this paragraph is relevant only if CMS support not disabled
for the OpenSSL build and
.Fa encryptedKey
is of type case
.Sy OSSL_CRMF_ENCRYPTEDKEY_ENVELOPEDDATA .
Decryption uses the
.Fa secret
parameter if not NULL; otherwise uses the private key <pkey> and the
certificate
.Fa cert
related to
.Fa pkey ,
where
.Fa cert
is recommended to be given if available.
On success, the function verifies the decrypted data as signed data,
using the trust store
.Fa ts
and any untrusted certificates in
.Fa extra .
Doing so, it checks for the purpose "CMP Key Generation Authority"
(cmKGA).
.Pp
.Fn OSSL_CRMF_ENCRYPTEDKEY_init_envdata
returns
.Vt OSSL_CRMF_ENCRYPTEDKEY ,
initialized with the enveloped data
.Fa envdata .
.Pp
.Fn OSSL_CRMF_ENCRYPTEDVALUE_decrypt
decrypts the encrypted value in the given encryptedValue
.Fa enc ,
using the private key
.Fa pkey ,
library context
.Fa libctx
and property query string
.Fa propq
(see
.Xr OSSL_LIB_CTX 3 Ns ).
.Pp
.Fn OSSL_CRMF_ENCRYPTEDVALUE_get1_encCert
decrypts the certificate in the given encryptedValue
.Fa ecert ,
using the private key
.Fa pkey ,
library context
.Fa libctx
and property query string
.Fa propq
(see
.Xr OSSL_LIB_CTX 3 Ns ).
This is needed for the indirect POPO method as in RFC 4210 section
5.2.8.2. The function returns the decrypted certificate as a copy,
leaving its ownership with the caller, who is responsible for freeing
it.
.Pp
.Fn OSSL_CRMF_MSG_get_certReqId
retrieves the certReqId of
.Fa crm .
.Pp
.Fn OSSL_CRMF_MSG_centralkeygen_requested
returns 1 if central key generation is requested i.e., the public key in
the certificate request
.Pf ( Fa crm
is taken if it is non-NULL, otherwise
.Fa p10cr )
is NULL or has an empty key value (with length zero).
In case
.Fa crm
is non-NULL, this is checked for consistency with its
.Sy popo
field (must be NULL if and only if central key generation is requested).
Otherwise it returns 0, and on error a negative value.
.Sh RETURN VALUES
.Fn OSSL_CRMF_MSG_get_certReqId
returns the certificate request ID as a nonnegative integer or -1 on
error.
.Pp
.Fn OSSL_CRMF_MSG_centralkeygen_requested
returns 1 if central key generation is requested, 0 if it is not
requested, and a negative value on error.
.Pp
All other functions return a pointer with the intended result or NULL on
error.
.Sh SEE ALSO
RFC 4211
.Sh HISTORY
The OpenSSL CRMF support was added in OpenSSL 3.0.
.Pp
.Fn OSSL_CRMF_CERTTEMPLATE_get0_publicKey
was added in OpenSSL 3.2.
.Pp
.Fn OSSL_CRMF_ENCRYPTEDKEY_get1_encCert ,
.Fn OSSL_CRMF_ENCRYPTEDKEY_get1_pkey ,
.Fn OSSL_CRMF_ENCRYPTEDKEY_init_envdata ,
.Fn OSSL_CRMF_ENCRYPTEDVALUE_decrypt
and
.Fn OSSL_CRMF_MSG_centralkeygen_requested
were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2007-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
