.Dd 2025-09-30
.Dt PBMAC1_GET1_PBKDF2_PARAM 3ossl
.Os
.Sh NAME
.Nm PBMAC1_get1_pbkdf2_param
.Nd Function to manipulate a PBMAC1 MAC structure
.Sh SYNOPSIS
.In openssl/x509.h
.Ft PBKDF2PARAM *
.Fo PBMAC1_get1_pbkdf2_param
.Fa "const X509_ALGOR *macalg"
.Fc
.Sh DESCRIPTION
.Fn PBMAC1_get1_pbkdf2_param
retrieves a
.Vt PBKDF2PARAM
structure from an
.Em X509_ALGOR
structure.
.Sh RETURN VALUES
.Fn PBMAC1_get1_pbkdf2_param
returns NULL in case when PBMAC1 uses an algorithm apart from
.Sy PBKDF2
or when passed incorrect parameters and a pointer to
.Vt PBKDF2PARAM
structure otherwise.
.Sh CONFORMING TO
IETF RFC 9579
.Pf ( Lk https://tools.ietf.org/html/rfc9579 )
.Sh SEE ALSO
.Xr openssl-pkcs12 1
.Sh HISTORY
The
.Em PBMAC1_get1_pbkdf2_param
function was added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2021-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
