.Dd 2025-09-30
.Dt PEM_READ_CMS 3ossl
.Os
.Sh NAME
.Nm DECLARE_PEM_rw ,
.Nm PEM_read_CMS ,
.Nm PEM_read_bio_CMS ,
.Nm PEM_write_CMS ,
.Nm PEM_write_bio_CMS ,
.Nm PEM_write_DHxparams ,
.Nm PEM_write_bio_DHxparams ,
.Nm PEM_read_ECPKParameters ,
.Nm PEM_read_bio_ECPKParameters ,
.Nm PEM_write_ECPKParameters ,
.Nm PEM_write_bio_ECPKParameters ,
.Nm PEM_read_ECPrivateKey ,
.Nm PEM_write_ECPrivateKey ,
.Nm PEM_write_bio_ECPrivateKey ,
.Nm PEM_read_EC_PUBKEY ,
.Nm PEM_read_bio_EC_PUBKEY ,
.Nm PEM_write_EC_PUBKEY ,
.Nm PEM_write_bio_EC_PUBKEY ,
.Nm PEM_read_NETSCAPE_CERT_SEQUENCE ,
.Nm PEM_read_bio_NETSCAPE_CERT_SEQUENCE ,
.Nm PEM_write_NETSCAPE_CERT_SEQUENCE ,
.Nm PEM_write_bio_NETSCAPE_CERT_SEQUENCE ,
.Nm PEM_read_PKCS8 ,
.Nm PEM_read_bio_PKCS8 ,
.Nm PEM_write_PKCS8 ,
.Nm PEM_write_bio_PKCS8 ,
.Nm PEM_write_PKCS8_PRIV_KEY_INFO ,
.Nm PEM_read_bio_PKCS8_PRIV_KEY_INFO ,
.Nm PEM_read_PKCS8_PRIV_KEY_INFO ,
.Nm PEM_write_bio_PKCS8_PRIV_KEY_INFO ,
.Nm PEM_read_SSL_SESSION ,
.Nm PEM_read_bio_SSL_SESSION ,
.Nm PEM_write_SSL_SESSION ,
.Nm PEM_write_bio_SSL_SESSION ,
.Nm PEM_read_X509_PUBKEY ,
.Nm PEM_read_bio_X509_PUBKEY ,
.Nm PEM_write_X509_PUBKEY ,
.Nm PEM_write_bio_X509_PUBKEY
.Nd PEM object encoding routines
.Sh SYNOPSIS
.In openssl/pem.h
.Bd -literal
 DECLARE_PEM_rw(name, TYPE)
.Ed
.Ft TYPE *
.Fo PEM_read_TYPE
.Fa "FILE *fp"
.Fa "TYPE **a"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft TYPE *
.Fo PEM_read_bio_TYPE
.Fa "BIO *bp"
.Fa "TYPE **a"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_TYPE
.Fa "FILE *fp"
.Fa "const TYPE *a"
.Fc
.Ft int
.Fo PEM_write_bio_TYPE
.Fa "BIO *bp"
.Fa "const TYPE *a"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.In openssl/pem.h
.Ft int
.Fo PEM_write_DHxparams
.Fa "FILE *out"
.Fa "const DH *dh"
.Fc
.Ft int
.Fo PEM_write_bio_DHxparams
.Fa "BIO *out"
.Fa "const DH *dh"
.Fc
.Ft EC_GROUP *
.Fo PEM_read_ECPKParameters
.Fa "FILE *fp"
.Fa "EC_GROUP **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft EC_GROUP *
.Fo PEM_read_bio_ECPKParameters
.Fa "BIO *bp"
.Fa "EC_GROUP **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_ECPKParameters
.Fa "FILE *out"
.Fa "const EC_GROUP *x"
.Fc
.Ft int
.Fo PEM_write_bio_ECPKParameters
.Fa "BIO *out"
.Fa "const EC_GROUP *x"
.Fc
,
.Ft EC_KEY *
.Fo PEM_read_EC_PUBKEY
.Fa "FILE *fp"
.Fa "EC_KEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft EC_KEY *
.Fo PEM_read_bio_EC_PUBKEY
.Fa "BIO *bp"
.Fa "EC_KEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_EC_PUBKEY
.Fa "FILE *out"
.Fa "const EC_KEY *x"
.Fc
.Ft int
.Fo PEM_write_bio_EC_PUBKEY
.Fa "BIO *out"
.Fa "const EC_KEY *x"
.Fc
.Ft EC_KEY *
.Fo PEM_read_ECPrivateKey
.Fa "FILE *out"
.Fa "EC_KEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft EC_KEY *
.Fo PEM_read_bio_ECPrivateKey
.Fa "BIO *out"
.Fa "EC_KEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_ECPrivateKey
.Fa "FILE *out"
.Fa "const EC_KEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "const unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_ECPrivateKey
.Fa "BIO *out"
.Fa "const EC_KEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "const unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Sh DESCRIPTION
To replace the deprecated functions listed above, applications should
use the
.Sy EVP_PKEY
type and
.Xr OSSL_DECODER_from_bio 3
and
.Xr OSSL_ENCODER_to_bio 3
to read and write PEM data containing key parameters or private and
public keys.
.Pp
In the description below,
.Sy Vt TYPE
is used as a placeholder for any of the OpenSSL datatypes, such as
.Sy X509 .
The macro
.Sy DECLARE_PEM_rw
expands to the set of declarations shown in the next four lines of the
synopsis.
.Pp
These routines convert between local instances of ASN1 datatypes and the
PEM encoding.
For more information on the templates, see
.Xr ASN1_ITEM 3 .
For more information on the lower-level routines used by the functions
here, see
.Xr PEM_read 3 .
.Pp
.Sy PEM_read_ Ns Vt TYPE Ns
.Xr 3
reads a PEM-encoded object of
.Sy Vt TYPE
from the file
.Fa fp
and returns it.
The
.Fa cb
and
.Fa u
parameters are as described in
.Xr pem_password_cb 3 .
.Pp
.Sy PEM_read_bio_ Ns Vt TYPE Ns
.Xr 3
is similar to
.Sy PEM_read_ Ns Vt TYPE Ns
.Xr 3
but reads from the BIO
.Fa bp .
.Pp
.Sy PEM_write_ Ns Vt TYPE Ns
.Xr 3
writes the PEM encoding of the object
.Fa a
to the file
.Fa fp .
.Pp
.Sy PEM_write_bio_ Ns Vt TYPE Ns
.Xr 3
similarly writes to the BIO
.Fa bp .
.Sh NOTES
These functions make no assumption regarding the pass phrase received
from the password callback.
It will simply be treated as a byte sequence.
.Sh RETURN VALUES
.Sy PEM_read_ Ns Vt TYPE Ns
.Xr 3
and
.Sy PEM_read_bio_ Ns Vt TYPE Ns
.Xr 3
return a pointer to an allocated object, which should be released by
calling
.Sy Vt TYPE Ns _free Ns
.Xr 3 ,
or NULL on error.
.Pp
.Sy PEM_write_ Ns Vt TYPE Ns
.Xr 3
and
.Sy PEM_write_bio_ Ns Vt TYPE Ns
.Xr 3
return 1 for success or 0 for failure.
.Sh SEE ALSO
.Xr PEM_read 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
The functions
.Fn PEM_write_DHxparams ,
.Fn PEM_write_bio_DHxparams ,
.Fn PEM_read_ECPKParameters ,
.Fn PEM_read_bio_ECPKParameters ,
.Fn PEM_write_ECPKParameters ,
.Fn PEM_write_bio_ECPKParameters ,
.Fn PEM_read_EC_PUBKEY ,
.Fn PEM_read_bio_EC_PUBKEY ,
.Fn PEM_write_EC_PUBKEY ,
.Fn PEM_write_bio_EC_PUBKEY ,
.Fn PEM_read_ECPrivateKey ,
.Fn PEM_read_bio_ECPrivateKey ,
.Fn PEM_write_ECPrivateKey
and
.Fn PEM_write_bio_ECPrivateKey
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 1998-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
