.Dd 2025-09-30
.Dt PEM_X509_INFO_READ_BIO_EX 3ossl
.Os
.Sh NAME
.Nm PEM_X509_INFO_read_ex ,
.Nm PEM_X509_INFO_read ,
.Nm PEM_X509_INFO_read_bio_ex ,
.Nm PEM_X509_INFO_read_bio
.Nd read PEM-encoded data structures into one or moreX509_INFO No objects
.Sh SYNOPSIS
.In openssl/pem.h
.Bd -literal
 STACK_OF(X509_INFO) *PEM_X509_INFO_read_ex(FILE *fp, STACK_OF(X509_INFO) *sk,
                                            pem_password_cb *cb, void *u,
                                            OSSL_LIB_CTX *libctx,
                                            const char *propq);
 STACK_OF(X509_INFO) *PEM_X509_INFO_read(FILE *fp, STACK_OF(X509_INFO) *sk,
                                         pem_password_cb *cb, void *u);
 STACK_OF(X509_INFO) *PEM_X509_INFO_read_bio_ex(BIO *bio,
                                                STACK_OF(X509_INFO) *sk,
                                                pem_password_cb *cb, void *u,
                                                OSSL_LIB_CTX *libctx,
                                                const char *propq);
 STACK_OF(X509_INFO) *PEM_X509_INFO_read_bio(BIO *bp, STACK_OF(X509_INFO) *sk,
                                             pem_password_cb *cb, void *u);
.Ed
.Sh DESCRIPTION
.Xr PEM_X509_INFO_read_ex 3
loads the
.Sy X509_INFO
objects from a file
.Em fp .
.Pp
.Xr PEM_X509_INFO_read 3
is similar to
.Xr PEM_X509_INFO_read_ex 3
but uses the default (NULL) library context
.Em libctx
and empty property query
.Em propq .
.Pp
.Xr PEM_X509_INFO_read_bio_ex 3
loads the
.Sy X509_INFO
objects using a bio
.Em bp .
.Pp
.Xr PEM_X509_INFO_read_bio 3
is similar to
.Xr PEM_X509_INFO_read_bio_ex 3
but uses the default (NULL) library context
.Em libctx
and empty property query
.Em propq .
.Pp
Each of the loaded
.Sy X509_INFO
objects can contain a CRL, a certificate, and/or a private key.
The elements are read sequentially, and as far as they are of different
type than the elements read before, they are combined into the same
.Sy X509_INFO
object.
The idea behind this is that if, for instance, a certificate is followed
by a private key, the private key is supposed to correspond to the
certificate.
.Pp
If the input stack
.Em sk
is NULL a new stack is allocated, else the given stack is extended.
.Pp
The optional
.Em cb
and
.Em u
parameters can be used for providing a pass phrase needed for decrypting
encrypted PEM structures (normally only private keys).
See
.Xr PEM_read_bio_PrivateKey 3
and
.Xr passphrase-encoding 7
for details.
.Pp
The library context
.Em libctx
and property query
.Em propq
are used for fetching algorithms from providers.
.Sh RETURN VALUES
.Xr PEM_X509_INFO_read_ex 3 ,
.Xr PEM_X509_INFO_read 3 ,
.Xr PEM_X509_INFO_read_bio_ex 3
and
.Xr PEM_X509_INFO_read_bio 3
return a stack of
.Sy X509_INFO
objects or NULL on failure.
.Sh SEE ALSO
.Xr PEM_read_bio_ex 3 ,
.Xr PEM_read_bio_PrivateKey 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
The functions
.Xr PEM_X509_INFO_read_ex 3
and
.Xr PEM_X509_INFO_read_bio_ex 3
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
