.Dd 2025-09-30
.Dt PEM_READ_BIO_PRIVATEKEY 3ossl
.Os
.Sh NAME
.Nm pem_password_cb ,
.Nm PEM_read_bio_PrivateKey_ex ,
.Nm PEM_read_bio_PrivateKey ,
.Nm PEM_read_PrivateKey_ex ,
.Nm PEM_read_PrivateKey ,
.Nm PEM_write_bio_PrivateKey_ex ,
.Nm PEM_write_bio_PrivateKey ,
.Nm PEM_write_bio_PrivateKey_traditional ,
.Nm PEM_write_PrivateKey_ex ,
.Nm PEM_write_PrivateKey ,
.Nm PEM_write_bio_PKCS8PrivateKey ,
.Nm PEM_write_PKCS8PrivateKey ,
.Nm PEM_write_bio_PKCS8PrivateKey_nid ,
.Nm PEM_write_PKCS8PrivateKey_nid ,
.Nm PEM_read_bio_PUBKEY_ex ,
.Nm PEM_read_bio_PUBKEY ,
.Nm PEM_read_PUBKEY_ex ,
.Nm PEM_read_PUBKEY ,
.Nm PEM_write_bio_PUBKEY_ex ,
.Nm PEM_write_bio_PUBKEY ,
.Nm PEM_write_PUBKEY_ex ,
.Nm PEM_write_PUBKEY ,
.Nm PEM_read_bio_RSAPrivateKey ,
.Nm PEM_read_RSAPrivateKey ,
.Nm PEM_write_bio_RSAPrivateKey ,
.Nm PEM_write_RSAPrivateKey ,
.Nm PEM_read_bio_RSAPublicKey ,
.Nm PEM_read_RSAPublicKey ,
.Nm PEM_write_bio_RSAPublicKey ,
.Nm PEM_write_RSAPublicKey ,
.Nm PEM_read_bio_RSA_PUBKEY ,
.Nm PEM_read_RSA_PUBKEY ,
.Nm PEM_write_bio_RSA_PUBKEY ,
.Nm PEM_write_RSA_PUBKEY ,
.Nm PEM_read_bio_DSAPrivateKey ,
.Nm PEM_read_DSAPrivateKey ,
.Nm PEM_write_bio_DSAPrivateKey ,
.Nm PEM_write_DSAPrivateKey ,
.Nm PEM_read_bio_DSA_PUBKEY ,
.Nm PEM_read_DSA_PUBKEY ,
.Nm PEM_write_bio_DSA_PUBKEY ,
.Nm PEM_write_DSA_PUBKEY ,
.Nm PEM_read_bio_Parameters_ex ,
.Nm PEM_read_bio_Parameters ,
.Nm PEM_write_bio_Parameters ,
.Nm PEM_read_bio_DSAparams ,
.Nm PEM_read_DSAparams ,
.Nm PEM_write_bio_DSAparams ,
.Nm PEM_write_DSAparams ,
.Nm PEM_read_bio_DHparams ,
.Nm PEM_read_DHparams ,
.Nm PEM_write_bio_DHparams ,
.Nm PEM_write_DHparams ,
.Nm PEM_read_bio_X509 ,
.Nm PEM_read_X509 ,
.Nm PEM_write_bio_X509 ,
.Nm PEM_write_X509 ,
.Nm PEM_read_bio_X509_ACERT ,
.Nm PEM_read_X509_ACERT ,
.Nm PEM_write_bio_X509_ACERT ,
.Nm PEM_write_X509_ACERT ,
.Nm PEM_read_bio_X509_AUX ,
.Nm PEM_read_X509_AUX ,
.Nm PEM_write_bio_X509_AUX ,
.Nm PEM_write_X509_AUX ,
.Nm PEM_read_bio_X509_REQ ,
.Nm PEM_read_X509_REQ ,
.Nm PEM_write_bio_X509_REQ ,
.Nm PEM_write_X509_REQ ,
.Nm PEM_write_bio_X509_REQ_NEW ,
.Nm PEM_write_X509_REQ_NEW ,
.Nm PEM_read_bio_X509_CRL ,
.Nm PEM_read_X509_CRL ,
.Nm PEM_write_bio_X509_CRL ,
.Nm PEM_write_X509_CRL ,
.Nm PEM_read_bio_PKCS7 ,
.Nm PEM_read_PKCS7 ,
.Nm PEM_write_bio_PKCS7 ,
.Nm PEM_write_PKCS7
.Nd PEM routines
.Sh SYNOPSIS
.In openssl/pem.h
.Ft typedef int
.Fo pem_password_cb
.Fa "char *buf"
.Fa "int size"
.Fa "int rwflag"
.Fa "void *u"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_bio_PrivateKey_ex
.Fa "BIO *bp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_bio_PrivateKey
.Fa "BIO *bp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_PrivateKey_ex
.Fa "FILE *fp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_PrivateKey
.Fa "FILE *fp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_PrivateKey_ex
.Fa "BIO *bp"
.Fa "const EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo PEM_write_bio_PrivateKey
.Fa "BIO *bp"
.Fa "const EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_PrivateKey_traditional
.Fa "BIO *bp"
.Fa "EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_PrivateKey_ex
.Fa "FILE *fp"
.Fa "EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo PEM_write_PrivateKey
.Fa "FILE *fp"
.Fa "EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_PKCS8PrivateKey
.Fa "BIO *bp"
.Fa "EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_PKCS8PrivateKey
.Fa "FILE *fp"
.Fa "EVP_PKEY *x"
.Fa "const EVP_CIPHER *enc"
.Fa "char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_PKCS8PrivateKey_nid
.Fa "BIO *bp"
.Fa "const EVP_PKEY *x"
.Fa "int nid"
.Fa "char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_PKCS8PrivateKey_nid
.Fa "FILE *fp"
.Fa "const EVP_PKEY *x"
.Fa "int nid"
.Fa "char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_bio_PUBKEY_ex
.Fa "BIO *bp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_bio_PUBKEY
.Fa "BIO *bp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_PUBKEY_ex
.Fa "FILE *fp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_PUBKEY
.Fa "FILE *fp"
.Fa "EVP_PKEY **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_PUBKEY_ex
.Fa "BIO *bp"
.Fa "EVP_PKEY *x"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo PEM_write_bio_PUBKEY
.Fa "BIO *bp"
.Fa "EVP_PKEY *x"
.Fc
.Ft int
.Fo PEM_write_PUBKEY_ex
.Fa "FILE *fp"
.Fa "EVP_PKEY *x"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo PEM_write_PUBKEY
.Fa "FILE *fp"
.Fa "EVP_PKEY *x"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_bio_Parameters_ex
.Fa "BIO *bp"
.Fa "EVP_PKEY **x"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft EVP_PKEY *
.Fo PEM_read_bio_Parameters
.Fa "BIO *bp"
.Fa "EVP_PKEY **x"
.Fc
.Ft int
.Fo PEM_write_bio_Parameters
.Fa "BIO *bp"
.Fa "const EVP_PKEY *x"
.Fc
.Ft X509 *
.Fo PEM_read_bio_X509
.Fa "BIO *bp"
.Fa "X509 **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft X509 *
.Fo PEM_read_X509
.Fa "FILE *fp"
.Fa "X509 **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_X509
.Fa "BIO *bp"
.Fa "X509 *x"
.Fc
.Ft int
.Fo PEM_write_X509
.Fa "FILE *fp"
.Fa "X509 *x"
.Fc
.Ft X509_ACERT *
.Fo PEM_read_bio_X509_ACERT
.Fa "BIO *bp"
.Fa "X509_ACERT **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft X509_ACERT *
.Fo PEM_read_X509_ACERT
.Fa "FILE *fp"
.Fa "X509_ACERT **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_X509_ACERT
.Fa "BIO *bp"
.Fa "X509_ACERT *x"
.Fc
.Ft int
.Fo PEM_write_X509_ACERT
.Fa "FILE *fp"
.Fa "X509_ACERT *x"
.Fc
.Ft X509 *
.Fo PEM_read_bio_X509_AUX
.Fa "BIO *bp"
.Fa "X509 **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft X509 *
.Fo PEM_read_X509_AUX
.Fa "FILE *fp"
.Fa "X509 **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_X509_AUX
.Fa "BIO *bp"
.Fa "X509 *x"
.Fc
.Ft int
.Fo PEM_write_X509_AUX
.Fa "FILE *fp"
.Fa "X509 *x"
.Fc
.Ft X509_REQ *
.Fo PEM_read_bio_X509_REQ
.Fa "BIO *bp"
.Fa "X509_REQ **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft X509_REQ *
.Fo PEM_read_X509_REQ
.Fa "FILE *fp"
.Fa "X509_REQ **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_X509_REQ
.Fa "BIO *bp"
.Fa "X509_REQ *x"
.Fc
.Ft int
.Fo PEM_write_X509_REQ
.Fa "FILE *fp"
.Fa "X509_REQ *x"
.Fc
.Ft int
.Fo PEM_write_bio_X509_REQ_NEW
.Fa "BIO *bp"
.Fa "X509_REQ *x"
.Fc
.Ft int
.Fo PEM_write_X509_REQ_NEW
.Fa "FILE *fp"
.Fa "X509_REQ *x"
.Fc
.Ft X509_CRL *
.Fo PEM_read_bio_X509_CRL
.Fa "BIO *bp"
.Fa "X509_CRL **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft X509_CRL *
.Fo PEM_read_X509_CRL
.Fa "FILE *fp"
.Fa "X509_CRL **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_X509_CRL
.Fa "BIO *bp"
.Fa "X509_CRL *x"
.Fc
.Ft int
.Fo PEM_write_X509_CRL
.Fa "FILE *fp"
.Fa "X509_CRL *x"
.Fc
.Ft PKCS7 *
.Fo PEM_read_bio_PKCS7
.Fa "BIO *bp"
.Fa "PKCS7 **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft PKCS7 *
.Fo PEM_read_PKCS7
.Fa "FILE *fp"
.Fa "PKCS7 **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_PKCS7
.Fa "BIO *bp"
.Fa "PKCS7 *x"
.Fc
.Ft int
.Fo PEM_write_PKCS7
.Fa "FILE *fp"
.Fa "PKCS7 *x"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft RSA *
.Fo PEM_read_bio_RSAPrivateKey
.Fa "BIO *bp"
.Fa "RSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft RSA *
.Fo PEM_read_RSAPrivateKey
.Fa "FILE *fp"
.Fa "RSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_RSAPrivateKey
.Fa "BIO *bp"
.Fa "RSA *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_RSAPrivateKey
.Fa "FILE *fp"
.Fa "RSA *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft RSA *
.Fo PEM_read_bio_RSAPublicKey
.Fa "BIO *bp"
.Fa "RSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft RSA *
.Fo PEM_read_RSAPublicKey
.Fa "FILE *fp"
.Fa "RSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_RSAPublicKey
.Fa "BIO *bp"
.Fa "RSA *x"
.Fc
.Ft int
.Fo PEM_write_RSAPublicKey
.Fa "FILE *fp"
.Fa "RSA *x"
.Fc
.Ft RSA *
.Fo PEM_read_bio_RSA_PUBKEY
.Fa "BIO *bp"
.Fa "RSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft RSA *
.Fo PEM_read_RSA_PUBKEY
.Fa "FILE *fp"
.Fa "RSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_RSA_PUBKEY
.Fa "BIO *bp"
.Fa "RSA *x"
.Fc
.Ft int
.Fo PEM_write_RSA_PUBKEY
.Fa "FILE *fp"
.Fa "RSA *x"
.Fc
.Ft DSA *
.Fo PEM_read_bio_DSAPrivateKey
.Fa "BIO *bp"
.Fa "DSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft DSA *
.Fo PEM_read_DSAPrivateKey
.Fa "FILE *fp"
.Fa "DSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_DSAPrivateKey
.Fa "BIO *bp"
.Fa "DSA *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_DSAPrivateKey
.Fa "FILE *fp"
.Fa "DSA *x"
.Fa "const EVP_CIPHER *enc"
.Fa "unsigned char *kstr"
.Fa "int klen"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft DSA *
.Fo PEM_read_bio_DSA_PUBKEY
.Fa "BIO *bp"
.Fa "DSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft DSA *
.Fo PEM_read_DSA_PUBKEY
.Fa "FILE *fp"
.Fa "DSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_DSA_PUBKEY
.Fa "BIO *bp"
.Fa "DSA *x"
.Fc
.Ft int
.Fo PEM_write_DSA_PUBKEY
.Fa "FILE *fp"
.Fa "DSA *x"
.Fc
.Ft DSA *
.Fo PEM_read_bio_DSAparams
.Fa "BIO *bp"
.Fa "DSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft DSA *
.Fo PEM_read_DSAparams
.Fa "FILE *fp"
.Fa "DSA **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_DSAparams
.Fa "BIO *bp"
.Fa "DSA *x"
.Fc
.Ft int
.Fo PEM_write_DSAparams
.Fa "FILE *fp"
.Fa "DSA *x"
.Fc
.Ft DH *
.Fo PEM_read_bio_DHparams
.Fa "BIO *bp"
.Fa "DH **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft DH *
.Fo PEM_read_DHparams
.Fa "FILE *fp"
.Fa "DH **x"
.Fa "pem_password_cb *cb"
.Fa "void *u"
.Fc
.Ft int
.Fo PEM_write_bio_DHparams
.Fa "BIO *bp"
.Fa "DH *x"
.Fc
.Ft int
.Fo PEM_write_DHparams
.Fa "FILE *fp"
.Fa "DH *x"
.Fc
.Sh DESCRIPTION
All of the functions described on this page that have a
.Em TYPE
of
.Vt DH ,
.Vt DSA
and
.Vt RSA
are deprecated.
Applications should use
.Xr OSSL_ENCODER_to_bio 3
and
.Xr OSSL_DECODER_from_bio 3
instead.
.Pp
The PEM functions read or write structures in PEM format.
In this sense PEM format is simply base64 encoded data surrounded by
header lines.
.Pp
For more details about the meaning of arguments see the
.Sy PEM FUNCTION ARGUMENTS
section.
.Pp
Each operation has four functions associated with it.
For brevity the term
.Pf \(dq Sy Em TYPE
functions" will be used below to collectively refer to the
.Sy PEM_read_bio_ Ns Em TYPE Ns
.Xr 3 ,
.Sy PEM_read_ Ns Em TYPE Ns
.Xr 3 ,
.Sy PEM_write_bio_ Ns Em TYPE Ns
.Xr 3 ,
and
.Sy PEM_write_ Ns Em TYPE Ns
.Xr 3
functions.
.Pp
Some operations have additional variants that take a library context
.Fa libctx
and a property query string
.Fa propq .
The
.Vt X509 ,
.Vt X509_REQ
and
.Vt X509_CRL
objects may have an associated library context or property query string
but there are no variants of these functions that take a library context
or property query string parameter.
In this case it is possible to set the appropriate library context or
property query string by creating an empty
.Vt X509 ,
.Vt X509_REQ
or
.Vt X509_CRL
object using
.Xr X509_new_ex 3 ,
.Xr X509_REQ_new_ex 3
or
.Xr X509_CRL_new_ex 3
respectively.
Then pass the empty object as a parameter to the relevant PEM function.
See the
.Sx EXAMPLES
section below.
.Pp
The
.Sy PrivateKey
functions read or write a private key in PEM format using an EVP_PKEY
structure.
The write routines use PKCS#8 private key format and are equivalent to
.Fn PEM_write_bio_PKCS8PrivateKey .
The read functions transparently handle traditional and PKCS#8 format
encrypted and unencrypted keys.
.Pp
.Fn PEM_write_bio_PrivateKey_traditional
writes out a private key in the "traditional" format with a simple
private key marker and should only be used for compatibility with legacy
programs.
.Pp
.Fn PEM_write_bio_PKCS8PrivateKey
and
.Fn PEM_write_PKCS8PrivateKey
write a private key in an EVP_PKEY structure in PKCS#8
EncryptedPrivateKeyInfo format using PKCS#5 v2.0 password based
encryption algorithms.
The
.Em cipher
argument specifies the encryption algorithm to use: unlike some other
PEM routines the encryption is applied at the PKCS#8 level and not in
the PEM headers.
If
.Em cipher
is NULL then no encryption is used and a PKCS#8 PrivateKeyInfo structure
is used instead.
.Pp
.Fn PEM_write_bio_PKCS8PrivateKey_nid
and
.Fn PEM_write_PKCS8PrivateKey_nid
also write out a private key as a PKCS#8 EncryptedPrivateKeyInfo however
it uses PKCS#5 v1.5 or PKCS#12 encryption algorithms instead.
The algorithm to use is specified in the
.Fa nid
parameter and should be the NID of the corresponding OBJECT IDENTIFIER
(see NOTES section).
.Pp
The
.Sy PUBKEY
functions process a public key using an EVP_PKEY structure.
The public key is encoded as a SubjectPublicKeyInfo structure.
.Pp
The
.Sy RSAPrivateKey
functions process an RSA private key using an RSA structure.
The write routines uses traditional format.
The read routines handles the same formats as the
.Sy PrivateKey
functions but an error occurs if the private key is not RSA.
.Pp
The
.Sy RSAPublicKey
functions process an RSA public key using an RSA structure.
The public key is encoded using a PKCS#1 RSAPublicKey structure.
.Pp
The
.Sy RSA_PUBKEY
functions also process an RSA public key using an RSA structure.
However, the public key is encoded using a SubjectPublicKeyInfo
structure and an error occurs if the public key is not RSA.
.Pp
The
.Sy DSAPrivateKey
functions process a DSA private key using a DSA structure.
The write routines uses traditional format.
The read routines handles the same formats as the
.Sy PrivateKey
functions but an error occurs if the private key is not DSA.
.Pp
The
.Sy DSA_PUBKEY
functions process a DSA public key using a DSA structure.
The public key is encoded using a SubjectPublicKeyInfo structure and an
error occurs if the public key is not DSA.
.Pp
The
.Sy Parameters
functions read or write key parameters in PEM format using an EVP_PKEY
structure.
The encoding depends on the type of key; for DSA key parameters, it will
be a Dss-Parms structure as defined in RFC2459, and for DH key
parameters, it will be a PKCS#3 DHparameter structure.
.Em These functions only exist for the Vt BIO type .
.Pp
The
.Sy DSAparams
functions process DSA parameters using a DSA structure.
The parameters are encoded using a Dss-Parms structure as defined in
RFC2459.
.Pp
The
.Sy DHparams
functions process DH parameters using a DH structure.
The parameters are encoded using a PKCS#3 DHparameter structure.
.Pp
The
.Vt X509
functions process an X509 certificate using an X509 structure.
They will also process a trusted X509 certificate but any trust settings
are discarded.
.Pp
The
.Vt X509_ACERT
functions process an X509 attribute certificate using an X509_ACERT
structure.
.Pp
The
.Sy X509_AUX
functions process a trusted X509 certificate using an X509 structure.
.Pp
The
.Vt X509_REQ
and
.Sy X509_REQ_NEW
functions process a PKCS#10 certificate request using an X509_REQ
structure.
The
.Vt X509_REQ
write functions use
.Sy CERTIFICATE REQUEST
in the header whereas the
.Sy X509_REQ_NEW
functions use
.Sy NEW CERTIFICATE REQUEST
(as required by some CAs).
The
.Vt X509_REQ
read functions will handle either form so there are no
.Sy X509_REQ_NEW
read functions.
.Pp
The
.Vt X509_CRL
functions process an X509 CRL using an X509_CRL structure.
.Pp
The
.Vt PKCS7
functions process a PKCS#7 ContentInfo using a PKCS7 structure.
.Sh PEM FUNCTION ARGUMENTS
The PEM functions have many common arguments.
.Pp
The
.Fa bp
BIO parameter (if present) specifies the BIO to read from or write to.
The
.Fa bp
BIO parameter
.Sy MUST NOT
be NULL.
.Pp
The
.Fa fp
FILE parameter (if present) specifies the FILE pointer to read from or
write to.
.Pp
The PEM read functions all take an argument
.Em Sy TYPE **x
and return a
.Em Sy TYPE *
pointer.
Where
.Em Sy TYPE
is whatever structure the function uses.
If
.Fa x
is NULL then the parameter is ignored.
If
.Fa x
is not NULL but
.Em *x
is NULL then the structure returned will be written to
.Em *x .
If neither
.Fa x
nor
.Em *x
is NULL then an attempt is made to reuse the structure at
.Em *x
(but see BUGS and EXAMPLES sections).
Irrespective of the value of
.Fa x
a pointer to the structure is always returned (or NULL if an error
occurred).
The caller retains ownership of the returned object and needs to free it
when it is no longer needed, e.g.
using
.Xr X509_free 3
for X509 objects or
.Xr EVP_PKEY_free 3
for EVP_PKEY objects.
.Pp
The PEM functions which write private keys take an
.Fa enc
parameter which specifies the encryption algorithm to use, encryption is
done at the PEM level.
If this parameter is set to NULL then the private key is written in
unencrypted form.
.Pp
The
.Fa cb
argument is the callback to use when querying for the pass phrase used
for encrypted PEM structures (normally only private keys).
.Pp
For the PEM write routines if the
.Fa kstr
parameter is not NULL then
.Fa klen
bytes at
.Fa kstr
are used as the passphrase and
.Fa cb
is ignored.
.Pp
If the
.Fa cb
parameters is set to NULL and the
.Fa u
parameter is not NULL then the
.Fa u
parameter is interpreted as a NUL terminated string to use as the
passphrase.
If both
.Fa cb
and
.Fa u
are NULL then the default callback routine is used which will typically
prompt for the passphrase on the current terminal with echoing turned
off.
.Pp
The default passphrase callback is sometimes inappropriate (for example
in a GUI application) so an alternative can be supplied.
The callback routine has the following form:
.Bd -literal
 int cb(char *buf, int size, int rwflag, void *u);
.Ed
.Pp
.Fa buf
is the buffer to write the passphrase to.
.Fa size
is the maximum length of the passphrase (i.e.
the size of buf).
.Fa rwflag
is a flag which is set to 0 when reading and 1 when writing.
A typical routine will ask the user to verify the passphrase (for
example by prompting for it twice) if
.Fa rwflag
is 1. The
.Fa u
parameter has the same value as the
.Fa u
parameter passed to the PEM routine.
It allows arbitrary data to be passed to the callback by the application
(for example a window handle in a GUI application).
The callback
.Em must
return the number of characters in the passphrase or -1 if an error
occurred.
The passphrase can be arbitrary data; in the case where it is a string,
it is not NUL terminated.
See the
.Sx EXAMPLES
section below.
.Pp
Some implementations may need to use cryptographic algorithms during
their operation.
If this is the case and
.Fa libctx
and
.Fa propq
parameters have been passed then any algorithm fetches will use that
library context and property query string.
Otherwise the default library context and property query string will be
used.
.Sh NOTES
The PEM reading functions will skip any extraneous content or PEM data
of a different type than they expect.
This allows for example having a certificate (or multiple certificates)
and a key in the PEM format in a single file.
.Pp
The old
.Sy PrivateKey
write routines are retained for compatibility.
New applications should write private keys using the
.Fn PEM_write_bio_PKCS8PrivateKey
or
.Fn PEM_write_PKCS8PrivateKey
routines because they are more secure (they use an iteration count of
2048 whereas the traditional routines use a count of 1) unless
compatibility with older versions of OpenSSL is important.
.Pp
The
.Sy PrivateKey
read routines can be used in all applications because they handle all
formats transparently.
.Pp
A frequent cause of problems is attempting to use the PEM routines like
this:
.Bd -literal
 X509 *x;

 PEM_read_bio_X509(bp, &x, 0, NULL);
.Ed
.Pp
this is a bug because an attempt will be made to reuse the data at
.Fa x
which is an uninitialised pointer.
.Pp
These functions make no assumption regarding the pass phrase received
from the password callback.
It will simply be treated as a byte sequence.
.Sh PEM ENCRYPTION FORMAT
These old
.Sy PrivateKey
routines use a non standard technique for encryption.
.Pp
The private key (or other data) takes the following form:
.Bd -literal
 -----BEGIN RSA PRIVATE KEY-----
 Proc-Type: 4,ENCRYPTED
 DEK-Info: DES-EDE3-CBC,3F17F5316E2BAC89

 ...base64 encoded data...
 -----END RSA PRIVATE KEY-----
.Ed
.Pp
The line beginning with
.Em Proc-Type
contains the version and the protection on the encapsulated data.
The line beginning
.Em DEK-Info
contains two comma separated values: the encryption algorithm name as
used by
.Xr EVP_get_cipherbyname 3
and an initialization vector used by the cipher encoded as a set of
hexadecimal digits.
After those two lines is the base64-encoded encrypted data.
.Pp
The encryption key is derived using
.Xr EVP_BytesToKey 3 .
The cipher's initialization vector is passed to
.Xr EVP_BytesToKey 3
as the
.Em salt
parameter.
Internally,
.Sy PKCS5_SALT_LEN
bytes of the salt are used (regardless of the size of the initialization
vector).
The user's password is passed to
.Xr EVP_BytesToKey 3
using the
.Em data
and
.Em datal
parameters.
Finally, the library uses an iteration count of 1 for
.Xr EVP_BytesToKey 3 .
.Pp
The
.Em key
derived by
.Xr EVP_BytesToKey 3
along with the original initialization vector is then used to decrypt
the encrypted data.
The
.Em iv
produced by
.Xr EVP_BytesToKey 3
is not utilized or needed, and NULL should be passed to the function.
.Pp
The pseudo code to derive the key would look similar to:
.Bd -literal
 EVP_CIPHER* cipher = EVP_des_ede3_cbc();
 EVP_MD* md = EVP_md5();

 unsigned int nkey = EVP_CIPHER_get_key_length(cipher);
 unsigned int niv = EVP_CIPHER_get_iv_length(cipher);
 unsigned char key[nkey];
 unsigned char iv[niv];

 memcpy(iv, HexToBin("3F17F5316E2BAC89"), niv);
 rc = EVP_BytesToKey(cipher, md, iv /*salt*/, pword, plen, 1, key, NULL /*iv*/);
 if (rc != nkey)
     /* Error */

 /* On success, use key and iv to initialize the cipher */
.Ed
.Sh BUGS
The PEM read routines in some versions of OpenSSL will not correctly
reuse an existing structure.
Therefore, the following:
.Bd -literal
 PEM_read_bio_X509(bp, &x, 0, NULL);
.Ed
.Pp
where
.Fa x
already contains a valid certificate, may not work, whereas:
.Bd -literal
 X509_free(x);
 x = PEM_read_bio_X509(bp, NULL, 0, NULL);
.Ed
.Pp
is guaranteed to work.
It is always acceptable for
.Fa x
to contain a newly allocated, empty
.Vt X509
object (for example allocated via
.Xr X509_new_ex 3 Ns ).
.Sh RETURN VALUES
The read routines return either a pointer to the structure read or NULL
if an error occurred.
.Pp
The write routines return 1 for success or 0 for failure.
.Sh EXAMPLES
Although the PEM routines take several arguments in almost all
applications most of them are set to 0 or NULL.
.Pp
To read a certificate with a library context in PEM format from a BIO:
.Bd -literal
 X509 *x = X509_new_ex(libctx, NULL);

 if (x == NULL)
     /* Error */

 if (PEM_read_bio_X509(bp, &x, 0, NULL) == NULL)
     /* Error */
.Ed
.Pp
Read a certificate in PEM format from a BIO:
.Bd -literal
 X509 *x;

 x = PEM_read_bio_X509(bp, NULL, 0, NULL);
 if (x == NULL)
     /* Error */
.Ed
.Pp
Alternative method:
.Bd -literal
 X509 *x = NULL;

 if (!PEM_read_bio_X509(bp, &x, 0, NULL))
     /* Error */
.Ed
.Pp
Write a certificate to a BIO:
.Bd -literal
 if (!PEM_write_bio_X509(bp, x))
     /* Error */
.Ed
.Pp
Write a private key (using traditional format) to a BIO using triple DES
encryption, the pass phrase is prompted for:
.Bd -literal
 if (!PEM_write_bio_PrivateKey(bp, key, EVP_des_ede3_cbc(), NULL, 0, 0, NULL))
     /* Error */
.Ed
.Pp
Write a private key (using PKCS#8 format) to a BIO using triple DES
encryption, using the pass phrase "hello":
.Bd -literal
 if (!PEM_write_bio_PKCS8PrivateKey(bp, key, EVP_des_ede3_cbc(),
                                    NULL, 0, 0, "hello"))
     /* Error */
.Ed
.Pp
Read a private key from a BIO using a pass phrase callback:
.Bd -literal
 key = PEM_read_bio_PrivateKey(bp, NULL, pass_cb, "My Private Key");
 if (key == NULL)
     /* Error */
.Ed
.Pp
Skeleton pass phrase callback:
.Bd -literal
 int pass_cb(char *buf, int size, int rwflag, void *u)
 {

     /* We'd probably do something else if 'rwflag' is 1 */
     printf("Enter pass phrase for \e"%s\e"\en", (char *)u);

     /* get pass phrase, length 'len' into 'tmp' */
     char *tmp = "hello";
     if (tmp == NULL) /* An error occurred */
         return -1;

     size_t len = strlen(tmp);

     if (len > size)
         len = size;
     memcpy(buf, tmp, len);
     return len;
 }
.Ed
.Sh SEE ALSO
.Xr EVP_EncryptInit 3 ,
.Xr EVP_BytesToKey 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
The old Netscape certificate sequences were no longer documented in
OpenSSL 1.1.0; applications should use the PKCS7 standard instead as
they will be formally deprecated in a future releases.
.Pp
.Fn PEM_read_bio_PrivateKey_ex ,
.Fn PEM_read_PrivateKey_ex ,
.Fn PEM_read_bio_PUBKEY_ex ,
.Fn PEM_read_PUBKEY_ex
and
.Fn PEM_read_bio_Parameters_ex
were introduced in OpenSSL 3.0.
.Pp
The functions
.Fn PEM_read_bio_RSAPrivateKey ,
.Fn PEM_read_RSAPrivateKey ,
.Fn PEM_write_bio_RSAPrivateKey ,
.Fn PEM_write_RSAPrivateKey ,
.Fn PEM_read_bio_RSAPublicKey ,
.Fn PEM_read_RSAPublicKey ,
.Fn PEM_write_bio_RSAPublicKey ,
.Fn PEM_write_RSAPublicKey ,
.Fn PEM_read_bio_RSA_PUBKEY ,
.Fn PEM_read_RSA_PUBKEY ,
.Fn PEM_write_bio_RSA_PUBKEY ,
.Fn PEM_write_RSA_PUBKEY ,
.Fn PEM_read_bio_DSAPrivateKey ,
.Fn PEM_read_DSAPrivateKey ,
.Fn PEM_write_bio_DSAPrivateKey ,
.Fn PEM_write_DSAPrivateKey ,
.Fn PEM_read_bio_DSA_PUBKEY ,
.Fn PEM_read_DSA_PUBKEY ,
.Fn PEM_write_bio_DSA_PUBKEY ,
.Fn PEM_write_DSA_PUBKEY ;
.Fn PEM_read_bio_DSAparams ,
.Fn PEM_read_DSAparams ,
.Fn PEM_write_bio_DSAparams ,
.Fn PEM_write_DSAparams ,
.Fn PEM_read_bio_DHparams ,
.Fn PEM_read_DHparams ,
.Fn PEM_write_bio_DHparams
and
.Fn PEM_write_DHparams
were deprecated in 3.0.
.Pp
.Fn PEM_read_bio_X509_ACERT ,
.Fn PEM_read_X509_ACERT ,
.Fn PEM_write_bio_X509_ACERT ,
.Fn PEM_write_X509_ACERT
were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2001-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
