.Dd 2025-09-30
.Dt PKCS12_PBE_KEYIVGEN 3ossl
.Os
.Sh NAME
.Nm PKCS12_PBE_keyivgen ,
.Nm PKCS12_PBE_keyivgen_ex ,
.Nm PKCS12_pbe_crypt ,
.Nm PKCS12_pbe_crypt_ex
.Nd PKCS#12 Password based encryption
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo PKCS12_PBE_keyivgen
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *cipher"
.Fa "const EVP_MD *md_type"
.Fa "int en_de"
.Fc
.Ft int
.Fo PKCS12_PBE_keyivgen_ex
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *cipher"
.Fa "const EVP_MD *md_type"
.Fa "int en_de"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft unsigned char *
.Fo PKCS12_pbe_crypt
.Fa "const X509_ALGOR *algor"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "const unsigned char *in"
.Fa "int inlen"
.Fa "unsigned char **data"
.Fa "int *datalen"
.Fa "int en_de"
.Fc
.Ft unsigned char *
.Fo PKCS12_pbe_crypt_ex
.Fa "const X509_ALGOR *algor"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "const unsigned char *in"
.Fa "int inlen"
.Fa "unsigned char **data"
.Fa "int *datalen"
.Fa "int en_de"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Sh DESCRIPTION
.Fn PKCS12_PBE_keyivgen
and
.Fn PKCS12_PBE_keyivgen_ex
take a password
.Fa pass
of length
.Fa passlen ,
parameters
.Fa param
and a message digest function
.Fa md_type
and perform a key derivation according to PKCS#12. The resulting key is
then used to initialise the cipher context
.Fa ctx
with a cipher
.Fa cipher
for encryption
.Pf ( Fa en_de Ns =1)
or decryption
.Pf ( Fa en_de Ns =0).
.Pp
.Fn PKCS12_PBE_keyivgen_ex
also allows the application to specify a library context
.Fa libctx
and property query
.Fa propq
to select appropriate algorithm implementations.
.Pp
.Fn PKCS12_pbe_crypt
and
.Fn PKCS12_pbe_crypt_ex
will encrypt or decrypt a buffer based on the algorithm in
.Fa algor
and password
.Fa pass
of length
.Fa passlen .
The input is from
.Fa in
of length
.Fa inlen
and output is into a malloc'd buffer returned in
.Em *data
of length
.Fa datalen .
The operation is determined by
.Fa en_de ,
encryption
.Pf ( Fa en_de Ns =1)
or decryption
.Pf ( Fa en_de Ns =0).
.Pp
.Fn PKCS12_pbe_crypt_ex
allows the application to specify a library context
.Fa libctx
and property query
.Fa propq
to select appropriate algorithm implementations.
.Pp
.Fa pass
is the password used in the derivation of length
.Fa passlen .
.Fa pass
is an optional parameter and can be NULL. If
.Fa passlen
is -1, then the function will calculate the length of
.Fa pass
using
.Xr strlen 3 .
.Pp
.Em salt
is the salt used in the derivation of length
.Em saltlen .
If the
.Em salt
is NULL, then
.Em saltlen
must be 0. The function will not attempt to calculate the length of the
.Em salt
because it is not assumed to be NULL terminated.
.Pp
.Em iter
is the iteration count and its value should be greater than or equal to
1. RFC 2898 suggests an iteration count of at least 1000. Any
.Em iter
less than 1 is treated as a single iteration.
.Pp
.Em digest
is the message digest function used in the derivation.
.Pp
Functions ending in
.Xr _ex 3
take optional parameters
.Fa libctx
and
.Fa propq
which are used to select appropriate algorithm implementations.
.Sh NOTES
The functions are typically used in PKCS#12 to encrypt objects.
.Pp
These functions make no assumption regarding the given password.
It will simply be treated as a byte sequence.
.Sh RETURN VALUES
.Fn PKCS12_PBE_keyivgen ,
.Fn PKCS12_PBE_keyivgen_ex
return 1 on success or 0 on error.
.Pp
.Fn PKCS12_pbe_crypt
and
.Fn PKCS12_pbe_crypt_ex
return a buffer containing the output or NULL if an error occurred.
.Sh CONFORMING TO
IETF RFC 7292
.Pf ( Lk https://tools.ietf.org/html/rfc7292 )
.Sh SEE ALSO
.Xr EVP_PBE_CipherInit_ex 3 ,
.Xr PKCS8_encrypt_ex 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
.Fn PKCS12_PBE_keyivgen_ex
and
.Fn PKCS12_pbe_crypt_ex
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2014-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
