.Dd 2025-09-30
.Dt PKCS7_VERIFY 3ossl
.Os
.Sh NAME
.Nm PKCS7_verify ,
.Nm PKCS7_get0_signers
.Nd verify a PKCS#7 signedData structure
.Sh SYNOPSIS
.In openssl/pkcs7.h
.Ft int
.Fo PKCS7_verify
.Fa "PKCS7 *p7"
.Fa "STACK_OF(X509) *certs"
.Fa "X509_STORE *store"
.Fa "BIO *indata"
.Fa "BIO *out"
.Fa "int flags"
.Fc
.Bd -literal
 STACK_OF(X509) *PKCS7_get0_signers(PKCS7 *p7, STACK_OF(X509) *certs, int flags);
.Ed
.Sh DESCRIPTION
.Fn PKCS7_verify
is very similar to
.Xr CMS_verify 3 .
It verifies a PKCS#7 signedData structure given in
.Fa p7 .
The optional
.Fa certs
parameter refers to a set of certificates in which to search for
signer's certificates.
It is also used as a source of untrusted intermediate CA certificates
for chain building.
.Fa p7
may contain extra untrusted CA certificates that may be used for chain
building as well as CRLs that may be used for certificate validation.
.Fa store
may be NULL or point to the trusted certificate store to use for chain
verification.
.Fa indata
refers to the signed data if the content is detached from
.Fa p7 .
Otherwise
.Fa indata
should be NULL, and then the signed data must be in
.Fa p7 .
The content is written to the BIO
.Fa out
unless it is NULL.
.Fa flags
is an optional set of flags, which can be used to modify the operation.
.Pp
.Xr PKCS7_get0_signers 3
retrieves the signer's certificates from
.Fa p7 ,
it does
.Sy not
check their validity or whether any signatures are valid.
The
.Fa certs
and
.Fa flags
parameters have the same meanings as in
.Fn PKCS7_verify .
.Sh VERIFY PROCESS
Normally the verify process proceeds as follows.
.Pp
Initially some sanity checks are performed on
.Fa p7 .
The type of
.Fa p7
must be SignedData.
There must be at least one signature on the data and if the content is
detached
.Fa indata
cannot be NULL. If the content is not detached and
.Fa indata
is not NULL then the structure has both embedded and external content.
To treat this as an error, use the flag
.Sy PKCS7_NO_DUAL_CONTENT .
The default behavior allows this, for compatibility with older versions
of OpenSSL.
.Pp
An attempt is made to locate all the signer's certificates, first
looking in the
.Fa certs
parameter (if it is not NULL). Then they are looked up in any
certificates contained in the
.Fa p7
structure unless
.Sy PKCS7_NOINTERN
is set.
If any signer's certificates cannot be located the operation fails.
.Pp
Each signer's certificate is chain verified using the
.Sy smimesign
purpose and using the trusted certificate store
.Fa store
if supplied.
Any internal certificates in the message, which may have been added
using
.Xr PKCS7_add_certificate 3 ,
are used as untrusted CAs unless
.Sy PKCS7_NOCHAIN
is set.
If CRL checking is enabled in
.Fa store
and
.Sy PKCS7_NOCRL
is not set, any internal CRLs, which may have been added using
.Xr PKCS7_add_crl 3 ,
are used in addition to attempting to look them up in
.Fa store .
If
.Fa store
is not NULL and any chain verify fails an error code is returned.
.Pp
Finally the signed content is read (and written to
.Fa out
unless it is NULL) and the signature is checked.
.Pp
If all signatures verify correctly then the function is successful.
.Pp
Any of the following flags (ored together) can be passed in the
.Fa flags
parameter to change the default verify behaviour.
Only the flag
.Sy PKCS7_NOINTERN
is meaningful to
.Xr PKCS7_get0_signers 3 .
.Pp
If
.Sy PKCS7_NOINTERN
is set the certificates in the message itself are not searched when
locating the signer's certificates.
This means that all the signer's certificates must be in the
.Fa certs
parameter.
.Pp
If
.Sy PKCS7_NOCRL
is set and CRL checking is enabled in
.Fa store
then any CRLs in the message itself are ignored.
.Pp
If the
.Sy PKCS7_TEXT
flag is set MIME headers for type
.Qo Li text/plain Qc
are deleted from the content.
If the content is not of type
.Qo Li text/plain Qc
then an error is returned.
.Pp
If
.Sy PKCS7_NOVERIFY
is set the signer's certificates are not chain verified.
.Pp
If
.Sy PKCS7_NOCHAIN
is set then the certificates contained in the message are not used as
untrusted CAs.
This means that the whole verify chain (apart from the signer's
certificates) must be contained in the trusted store.
.Pp
If
.Sy PKCS7_NOSIGS
is set then the signatures on the data are not checked.
.Sh NOTES
One application of
.Sy PKCS7_NOINTERN
is to only accept messages signed by a small number of certificates.
The acceptable certificates would be passed in the
.Fa certs
parameter.
In this case if the signer's certificate is not one of the certificates
supplied in
.Fa certs
then the verify will fail because the signer cannot be found.
.Pp
Care should be taken when modifying the default verify behaviour, for
example setting
.Qo Li PKCS7_NOVERIFY|PKCS7_NOSIGS Qc
will totally disable all verification and any signed message will be
considered valid.
This combination is however useful if one merely wishes to write the
content to
.Fa out
and its validity is not considered important.
.Pp
Chain verification should arguably be performed using the signing time
rather than the current time.
However, since the signing time is supplied by the signer it cannot be
trusted without additional evidence (such as a trusted timestamp).
.Sh RETURN VALUES
.Fn PKCS7_verify
returns 1 for a successful verification and 0 if an error occurs.
.Pp
.Xr PKCS7_get0_signers 3
returns all signers or NULL if an error occurred.
.Pp
The error can be obtained from
.Xr ERR_get_error 3 .
.Sh BUGS
The trusted certificate store is not searched for the signer's
certificates.
This is primarily due to the inadequacies of the current
.Vt X509_STORE
functionality.
.Pp
The lack of single pass processing means that the signed content must
all be held in memory if it is not detached.
.Sh SEE ALSO
.Xr CMS_verify 3 ,
.Xr PKCS7_add_certificate 3 ,
.Xr PKCS7_add_crl 3 ,
.Xr ERR_get_error 3 ,
.Xr PKCS7_sign 3
.Sh COPYRIGHT
Copyright 2002-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
