.Dd 2025-09-30
.Dt PKCS12_SAFEBAG_CREATE_CERT 3ossl
.Os
.Sh NAME
.Nm PKCS12_SAFEBAG_create_cert ,
.Nm PKCS12_SAFEBAG_create_crl ,
.Nm PKCS12_SAFEBAG_create_secret ,
.Nm PKCS12_SAFEBAG_create0_p8inf ,
.Nm PKCS12_SAFEBAG_create0_pkcs8 ,
.Nm PKCS12_SAFEBAG_create_pkcs8_encrypt ,
.Nm PKCS12_SAFEBAG_create_pkcs8_encrypt_ex
.Nd Create PKCS#12 safeBag objects
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create_cert
.Fa "X509 *x509"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create_crl
.Fa "X509_CRL *crl"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create_secret
.Fa "int type"
.Fa "int vtype"
.Fa "const unsigned char* value"
.Fa "int len"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create0_p8inf
.Fa "PKCS8_PRIV_KEY_INFO *p8"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create0_pkcs8
.Fa "X509_SIG *p8"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create_pkcs8_encrypt
.Fa "int pbe_nid"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "int iter"
.Fa "PKCS8_PRIV_KEY_INFO *p8inf"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_SAFEBAG_create_pkcs8_encrypt_ex
.Fa "int pbe_nid"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "int iter"
.Fa "PKCS8_PRIV_KEY_INFO *p8inf"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Sh DESCRIPTION
.Fn PKCS12_SAFEBAG_create_cert
creates a new
.Vt PKCS12_SAFEBAG
of type
.Sy NID_certBag
containing the supplied certificate.
.Pp
.Fn PKCS12_SAFEBAG_create_crl
creates a new
.Vt PKCS12_SAFEBAG
of type
.Sy NID_crlBag
containing the supplied crl.
.Pp
.Fn PKCS12_SAFEBAG_create_secret
creates a new
.Vt PKCS12_SAFEBAG
of type corresponding to a PKCS#12
.Sy secretBag .
The
.Sy secretBag
contents are tagged as
.Fa type
with an ASN1 value of type
.Fa vtype
constructed using the bytes in
.Fa value
of length
.Fa len .
.Pp
.Fn PKCS12_SAFEBAG_create0_p8inf
creates a new
.Vt PKCS12_SAFEBAG
of type
.Sy NID_keyBag
containing the supplied PKCS8 structure.
.Pp
.Fn PKCS12_SAFEBAG_create0_pkcs8
creates a new
.Vt PKCS12_SAFEBAG
of type
.Sy NID_pkcs8ShroudedKeyBag
containing the supplied PKCS8 structure.
.Pp
.Fn PKCS12_SAFEBAG_create_pkcs8_encrypt
creates a new
.Vt PKCS12_SAFEBAG
of type
.Sy NID_pkcs8ShroudedKeyBag
by encrypting the supplied PKCS8
.Fa p8inf .
If
.Fa pbe_nid
is 0, a default encryption algorithm is used.
.Fa pass
is the passphrase and
.Fa iter
is the iteration count.
If
.Fa iter
is zero then a default value of 2048 is used.
If
.Fa salt
is NULL then a salt is generated randomly.
.Pp
.Fn PKCS12_SAFEBAG_create_pkcs8_encrypt_ex
is identical to
.Fn PKCS12_SAFEBAG_create_pkcs8_encrypt
but allows for a library context
.Fa ctx
and property query
.Fa propq
to be used to select algorithm implementations.
.Sh NOTES
.Fn PKCS12_SAFEBAG_create_pkcs8_encrypt
makes assumptions regarding the encoding of the given pass phrase.
See
.Xr passphrase-encoding 7
for more information.
.Pp
.Fn PKCS12_SAFEBAG_create_secret
was added in OpenSSL 3.0.
.Sh RETURN VALUES
All of these functions return a valid
.Vt PKCS12_SAFEBAG
structure or NULL if an error occurred.
.Sh CONFORMING TO
IETF RFC 7292
.Pf ( Lk https://tools.ietf.org/html/rfc7292 )
.Sh SEE ALSO
.Xr PKCS12_create 3 ,
.Xr PKCS12_add_safe 3 ,
.Xr PKCS12_add_safes 3
.Sh HISTORY
.Fn PKCS12_SAFEBAG_create_pkcs8_encrypt_ex
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
