.Dd 2025-09-30
.Dt PKCS12_GET_FRIENDLYNAME 3ossl
.Os
.Sh NAME
.Nm PKCS12_get_friendlyname
.Nd Retrieve the friendlyname attribute from a PKCS#12 safeBag
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft char *
.Fo PKCS12_get_friendlyname
.Fa "PKCS12_SAFEBAG *bag"
.Fc
.Sh DESCRIPTION
.Fn PKCS12_get_friendlyname
retrieves a UTF-8 string representation of the PKCS#9 friendlyName
attribute for a PKCS#12 safeBag item.
.Pp
.Fa bag
is the
.Vt PKCS12_SAFEBAG
to retrieve the attribute from.
.Sh RETURN VALUES
A UTF-8 string, or NULL if the attribute was either not present or an
error occurred.
.Pp
The returned string is allocated by OpenSSL and should be freed by the
user.
.Sh SEE ALSO
.Xr PKCS12_add_friendlyname_asc 3
.Sh COPYRIGHT
Copyright 2019 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
