.Dd 2025-09-30
.Dt PKCS12_ITEM_DECRYPT_D2I 3ossl
.Os
.Sh NAME
.Nm PKCS12_item_decrypt_d2i ,
.Nm PKCS12_item_decrypt_d2i_ex ,
.Nm PKCS12_item_i2d_encrypt ,
.Nm PKCS12_item_i2d_encrypt_ex
.Nd PKCS12 item encrypt/decrypt functions
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft void *
.Fo PKCS12_item_decrypt_d2i
.Fa "const X509_ALGOR *algor"
.Fa "const ASN1_ITEM *it"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "const ASN1_OCTET_STRING *oct"
.Fa "int zbuf"
.Fc
.Ft void *
.Fo PKCS12_item_decrypt_d2i_ex
.Fa "const X509_ALGOR *algor"
.Fa "const ASN1_ITEM *it"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "const ASN1_OCTET_STRING *oct"
.Fa "int zbuf"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft ASN1_OCTET_STRING *
.Fo PKCS12_item_i2d_encrypt
.Fa "X509_ALGOR *algor"
.Fa "const ASN1_ITEM *it"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "void *obj"
.Fa "int zbuf"
.Fc
.Ft ASN1_OCTET_STRING *
.Fo PKCS12_item_i2d_encrypt_ex
.Fa "X509_ALGOR *algor"
.Fa "const ASN1_ITEM *it"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "void *obj"
.Fa "int zbuf"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Sh DESCRIPTION
.Fn PKCS12_item_decrypt_d2i
and
.Fn PKCS12_item_decrypt_d2i_ex
decrypt an octet string containing an ASN.1 encoded object using the
algorithm
.Fa algor
and password
.Fa pass
of length
.Fa passlen .
If
.Fa zbuf
is nonzero then the output buffer will zeroed after the decrypt.
.Pp
.Fn PKCS12_item_i2d_encrypt
and
.Fn PKCS12_item_i2d_encrypt_ex
encrypt an ASN.1 object
.Fa it
using the algorithm
.Fa algor
and password
.Fa pass
of length
.Fa passlen ,
returning an encoded object in
.Fa obj .
If
.Fa zbuf
is nonzero then the buffer containing the input encoding will be zeroed
after the encrypt.
.Pp
Functions ending in
.Xr _ex 3
allow for a library context
.Fa ctx
and property query
.Fa propq
to be used to select algorithm implementations.
.Sh RETURN VALUES
.Fn PKCS12_item_decrypt_d2i
and
.Fn PKCS12_item_decrypt_d2i_ex
return the decrypted object or NULL if an error occurred.
.Pp
.Fn PKCS12_item_i2d_encrypt
and
.Fn PKCS12_item_i2d_encrypt_ex
return the encrypted data as an ASN.1 Octet String or NULL if an error
occurred.
.Sh SEE ALSO
.Xr PKCS12_pbe_crypt_ex 3 ,
.Xr PKCS8_encrypt_ex 3
.Sh HISTORY
.Fn PKCS12_item_decrypt_d2i_ex
and
.Fn PKCS12_item_i2d_encrypt_ex
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
