.Dd 2025-09-30
.Dt PKCS5_PBE_KEYIVGEN 3ossl
.Os
.Sh NAME
.Nm PKCS5_PBE_keyivgen ,
.Nm PKCS5_PBE_keyivgen_ex ,
.Nm PKCS5_pbe2_set ,
.Nm PKCS5_pbe2_set_iv ,
.Nm PKCS5_pbe2_set_iv_ex ,
.Nm PKCS5_pbe_set ,
.Nm PKCS5_pbe_set_ex ,
.Nm PKCS5_pbe2_set_scrypt ,
.Nm PKCS5_pbe_set0_algor ,
.Nm PKCS5_pbe_set0_algor_ex ,
.Nm PKCS5_v2_PBE_keyivgen ,
.Nm PKCS5_v2_PBE_keyivgen_ex ,
.Nm PKCS5_v2_scrypt_keyivgen ,
.Nm PKCS5_v2_scrypt_keyivgen_ex ,
.Nm PKCS5_pbkdf2_set ,
.Nm PKCS5_pbkdf2_set_ex ,
.Nm EVP_PBE_scrypt ,
.Nm EVP_PBE_scrypt_ex
.Nd PKCS#5 Password based encryption routines
.Sh SYNOPSIS
.In openssl/evp.h
.Ft int
.Fo PKCS5_PBE_keyivgen
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *cipher"
.Fa "const EVP_MD *md"
.Fa "int en_de"
.Fc
.Ft int
.Fo PKCS5_PBE_keyivgen_ex
.Fa "EVP_CIPHER_CTX *cctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *cipher"
.Fa "const EVP_MD *md"
.Fa "int en_de"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo PKCS5_v2_PBE_keyivgen
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *cipher"
.Fa "const EVP_MD *md"
.Fa "int en_de"
.Fc
.Ft int
.Fo PKCS5_v2_PBE_keyivgen_ex
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *cipher"
.Fa "const EVP_MD *md"
.Fa "int en_de"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo EVP_PBE_scrypt
.Fa "const char *pass"
.Fa "size_t passlen"
.Fa "const unsigned char *salt"
.Fa "size_t saltlen"
.Fa "uint64_t N"
.Fa "uint64_t r"
.Fa "uint64_t p"
.Fa "uint64_t maxmem"
.Fa "unsigned char *key"
.Fa "size_t keylen"
.Fc
.Ft int
.Fo EVP_PBE_scrypt_ex
.Fa "const char *pass"
.Fa "size_t passlen"
.Fa "const unsigned char *salt"
.Fa "size_t saltlen"
.Fa "uint64_t N"
.Fa "uint64_t r"
.Fa "uint64_t p"
.Fa "uint64_t maxmem"
.Fa "unsigned char *key"
.Fa "size_t keylen"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo PKCS5_v2_scrypt_keyivgen
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *c"
.Fa "const EVP_MD *md"
.Fa "int en_de"
.Fc
.Ft int
.Fo PKCS5_v2_scrypt_keyivgen_ex
.Fa "EVP_CIPHER_CTX *ctx"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "ASN1_TYPE *param"
.Fa "const EVP_CIPHER *c"
.Fa "const EVP_MD *md"
.Fa "int en_de"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.In openssl/x509.h
.Ft int
.Fo PKCS5_pbe_set0_algor
.Fa "X509_ALGOR *algor"
.Fa "int alg"
.Fa "int iter"
.Fa "const unsigned char *salt"
.Fa "int saltlen"
.Fc
.Ft int
.Fo PKCS5_pbe_set0_algor_ex
.Fa "X509_ALGOR *algor"
.Fa "int alg"
.Fa "int iter"
.Fa "const unsigned char *salt"
.Fa "int saltlen"
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbe_set
.Fa "int alg"
.Fa "int iter"
.Fa "const unsigned char *salt"
.Fa "int saltlen"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbe_set_ex
.Fa "int alg"
.Fa "int iter"
.Fa "const unsigned char *salt"
.Fa "int saltlen"
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbe2_set
.Fa "const EVP_CIPHER *cipher"
.Fa "int iter"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbe2_set_iv
.Fa "const EVP_CIPHER *cipher"
.Fa "int iter"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "unsigned char *aiv"
.Fa "int prf_nid"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbe2_set_iv_ex
.Fa "const EVP_CIPHER *cipher"
.Fa "int iter"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "unsigned char *aiv"
.Fa "int prf_nid"
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbe2_set_scrypt
.Fa "const EVP_CIPHER *cipher"
.Fa "const unsigned char *salt"
.Fa "int saltlen"
.Fa "unsigned char *aiv"
.Fa "uint64_t N"
.Fa "uint64_t r"
.Fa "uint64_t p"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbkdf2_set
.Fa "int iter"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "int prf_nid"
.Fa "int keylen"
.Fc
.Ft X509_ALGOR *
.Fo PKCS5_pbkdf2_set_ex
.Fa "int iter"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "int prf_nid"
.Fa "int keylen"
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Sh DESCRIPTION
.Ss Key Derivation
.Fn PKCS5_PBE_keyivgen
and
.Fn PKCS5_PBE_keyivgen_ex
take a password
.Fa pass
of length
.Fa passlen ,
parameters
.Fa param
and a message digest function
.Em md_type
and performs a key derivation according to PKCS#5 PBES1. The resulting
key is then used to initialise the cipher context
.Fa ctx
with a cipher
.Fa cipher
for encryption
.Pf ( Fa en_de Ns =1)
or decryption
.Pf ( Fa en_de Ns =0).
.Pp
.Fa pass
is an optional parameter and can be NULL. If
.Fa passlen
is -1, then the function will calculate the length of
.Fa pass
using
.Xr strlen 3 .
.Pp
.Fn PKCS5_v2_PBE_keyivgen
and
.Fn PKCS5_v2_PBE_keyivgen_ex
are similar to the above but instead use PKCS#5 PBES2 as the encryption
algorithm using the supplied parameters.
.Pp
.Fn PKCS5_v2_scrypt_keyivgen
and
.Fn PKCS5_v2_scrypt_keyivgen_ex
use SCRYPT as the key derivation part of the encryption algorithm.
.Pp
.Fa salt
is the salt used in the derivation of length
.Fa saltlen .
If the
.Fa salt
is NULL, then
.Fa saltlen
must be 0. The function will not attempt to calculate the length of the
.Fa salt
because it is not assumed to be NULL terminated.
.Pp
.Fa iter
is the iteration count and its value should be greater than or equal to
1. RFC 2898 suggests an iteration count of at least 1000. Any
.Fa iter
less than 1 is treated as a single iteration.
.Pp
.Em digest
is the message digest function used in the derivation.
.Pp
Functions ending in
.Xr _ex 3
take optional parameters
.Fa libctx
and
.Fa propq
which are used to select appropriate algorithm implementations.
.Ss Algorithm Identifier Creation
.Fn PKCS5_pbe_set ,
.Fn PKCS5_pbe_set_ex ,
.Fn PKCS5_pbe2_set ,
.Fn PKCS5_pbe2_set_iv ,
.Fn PKCS5_pbe2_set_iv_ex
and
.Fn PKCS5_pbe2_set_scrypt
generate an
.Vt X509_ALGOR
object which represents an AlgorithmIdentifier containing the algorithm
OID and associated parameters for the PBE algorithm.
.Pp
.Fn PKCS5_pbkdf2_set
and
.Fn PKCS5_pbkdf2_set_ex
generate an
.Vt X509_ALGOR
object which represents an AlgorithmIdentifier containing the algorithm
OID and associated parameters for the PBKDF2 algorithm.
.Pp
.Fn PKCS5_pbe_set0_algor
and
.Fn PKCS5_pbe_set0_algor_ex
set the PBE algorithm OID and parameters into the supplied
.Vt X509_ALGOR .
.Pp
If
.Fa salt
is NULL, then
.Fa saltlen
specifies the size in bytes of the random salt to generate.
If
.Fa saltlen
is 0 then a default size is used.
For PBE related functions such as
.Fn PKCS5_pbe_set_ex
the default salt length is 8 bytes.
For PBE2 related functions that use PBKDF2 such as
.Fn PKCS5_pbkdf2_set ,
.Fn PKCS5_pbe2_set_scrypt
and
.Fn PKCS5_pbe2_set
the default salt length is 16 bytes.
.Sh NOTES
The
.Xr *_keyivgen 3
functions are typically used in PKCS#12 to encrypt objects.
.Pp
These functions make no assumption regarding the given password.
It will simply be treated as a byte sequence.
.Sh RETURN VALUES
.Fn PKCS5_PBE_keyivgen ,
.Fn PKCS5_v2_PBE_keyivgen ,
.Fn PKCS5_v2_PBE_keyivgen_ex ,
.Fn PKCS5_v2_scrypt_keyivgen ,
.Fn PKCS5_v2_scrypt_keyivgen_ex ,
.Fn PKCS5_pbe_set0_algor
and
.Fn PKCS5_pbe_set0_algor_ex
return 1 for success and 0 if an error occurs.
.Pp
.Fn PKCS5_pbe_set ,
.Fn PKCS5_pbe_set_ex ,
.Fn PKCS5_pbe2_set ,
.Fn PKCS5_pbe2_set_iv ,
.Fn PKCS5_pbe2_set_iv_ex ,
.Fn PKCS5_pbe2_set_scrypt ,
.Fn PKCS5_pbkdf2_set
and
.Fn PKCS5_pbkdf2_set_ex
return an
.Vt X509_ALGOR
object or NULL if an error occurs.
.Sh CONFORMING TO
IETF RFC 8018
.Pf ( Lk https://tools.ietf.org/html/rfc8018 )
.Sh SEE ALSO
.Xr EVP_PBE_CipherInit_ex 3 ,
.Xr PKCS12_pbe_crypt_ex 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
.Fn PKCS5_v2_PBE_keyivgen_ex ,
.Fn EVP_PBE_scrypt_ex ,
.Fn PKCS5_v2_scrypt_keyivgen_ex ,
.Fn PKCS5_pbe_set0_algor_ex ,
.Fn PKCS5_pbe_set_ex ,
.Fn PKCS5_pbe2_set_iv_ex
and
.Fn PKCS5_pbkdf2_set_ex
were added in OpenSSL 3.0.
.Pp
From OpenSSL 3.0 the PBKDF1 algorithm used in
.Fn PKCS5_PBE_keyivgen
and
.Fn PKCS5_PBE_keyivgen_ex
has been moved to the legacy provider as an EVP_KDF.
.Pp
In OpenSSL 3.2 the default salt length changed from 8 bytes to 16 bytes
for PBE2 related functions such as
.Fn PKCS5_pbe2_set .
This is required for PBKDF2 FIPS compliance.
.Sh COPYRIGHT
Copyright 2021-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
