.Dd 2025-09-30
.Dt PKCS12_SAFEBAG_GET1_CERT 3ossl
.Os
.Sh NAME
.Nm PKCS12_SAFEBAG_get0_attr ,
.Nm PKCS12_SAFEBAG_get0_type ,
.Nm PKCS12_SAFEBAG_get_nid ,
.Nm PKCS12_SAFEBAG_get_bag_nid ,
.Nm PKCS12_SAFEBAG_get0_bag_obj ,
.Nm PKCS12_SAFEBAG_get0_bag_type ,
.Nm PKCS12_SAFEBAG_get1_cert_ex ,
.Nm PKCS12_SAFEBAG_get1_cert ,
.Nm PKCS12_SAFEBAG_get1_crl_ex ,
.Nm PKCS12_SAFEBAG_get1_crl ,
.Nm PKCS12_SAFEBAG_get0_safes ,
.Nm PKCS12_SAFEBAG_get0_p8inf ,
.Nm PKCS12_SAFEBAG_get0_pkcs8
.Nd Get objects from a PKCS#12 safeBag
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft const ASN1_TYPE *
.Fo PKCS12_SAFEBAG_get0_attr
.Fa "const PKCS12_SAFEBAG *bag"
.Fa "int attr_nid"
.Fc
.Ft const ASN1_OBJECT *
.Fo PKCS12_SAFEBAG_get0_type
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft int
.Fo PKCS12_SAFEBAG_get_nid
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft int
.Fo PKCS12_SAFEBAG_get_bag_nid
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft const ASN1_TYPE *
.Fo PKCS12_SAFEBAG_get0_bag_obj
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft const ASN1_OBJECT *
.Fo PKCS12_SAFEBAG_get0_bag_type
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft X509_CRL *
.Fo PKCS12_SAFEBAG_get1_cert_ex
.Fa "const PKCS12_SAFEBAG *bag"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft X509 *
.Fo PKCS12_SAFEBAG_get1_cert
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft X509_CRL *
.Fo PKCS12_SAFEBAG_get1_crl_ex
.Fa "const PKCS12_SAFEBAG *bag"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft X509_CRL *
.Fo PKCS12_SAFEBAG_get1_crl
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft const
.Fo STACK_OF
.Fa PKCS12_SAFEBAG
.Fc
 *PKCS12_SAFEBAG_get0_safes(const PKCS12_SAFEBAG *bag);
.Ft const PKCS8_PRIV_KEY_INFO *
.Fo PKCS12_SAFEBAG_get0_p8inf
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Ft const X509_SIG *
.Fo PKCS12_SAFEBAG_get0_pkcs8
.Fa "const PKCS12_SAFEBAG *bag"
.Fc
.Sh DESCRIPTION
.Fn PKCS12_SAFEBAG_get0_attr
gets the attribute value corresponding to the
.Fa attr_nid .
.Pp
.Fn PKCS12_SAFEBAG_get0_type
gets the
.Sy safeBag
type as an OID, whereas
.Fn PKCS12_SAFEBAG_get_nid
gets the
.Sy safeBag
type as an NID, which could be
.Sy NID_certBag ,
.Sy NID_crlBag ,
.Sy NID_keyBag ,
.Sy NID_secretBag ,
.Sy NID_safeContentsBag
or
.Sy NID_pkcs8ShroudedKeyBag .
.Pp
.Fn PKCS12_SAFEBAG_get_bag_nid
gets the type of the object contained within the
.Vt PKCS12_SAFEBAG .
This corresponds to the bag type for most bags, but can be arbitrary for
.Sy secretBag Ns s.
.Fn PKCS12_SAFEBAG_get0_bag_type
gets this type as an OID.
.Pp
.Fn PKCS12_SAFEBAG_get0_bag_obj
retrieves the object contained within the safeBag.
.Pp
.Fn PKCS12_SAFEBAG_get1_cert_ex
and
.Fn PKCS12_SAFEBAG_get1_crl_ex
return new
.Vt X509
or
.Vt X509_CRL
objects from the item in the safeBag.
.Fa libctx
and
.Fa propq
are used when fetching algorithms, and may optionally be set to NULL.
.Pp
.Fn PKCS12_SAFEBAG_get1_cert
and
.Fn PKCS12_SAFEBAG_get1_crl
are the same as
.Fn PKCS12_SAFEBAG_get1_cert_ex
and
.Fn PKCS12_SAFEBAG_get1_crl_ex
and set the
.Fa libctx
and
.Em prop
to NULL. This will use the default library context.
.Pp
.Fn PKCS12_SAFEBAG_get0_p8inf
and
.Fn PKCS12_SAFEBAG_get0_pkcs8
return the PKCS8 object from a PKCS8shroudedKeyBag or a keyBag.
.Pp
.Xr PKCS12_SAFEBAG_get0_safes 3
retrieves the set of
.Sy safeBags
contained within a safeContentsBag.
.Sh RETURN VALUES
.Fn PKCS12_SAFEBAG_get_nid
and
.Fn PKCS12_SAFEBAG_get_bag_nid
return the NID of the safeBag or bag object, or -1 if there is no
corresponding NID. Other functions return a valid object of the
specified type or NULL if an error occurred.
.Sh SEE ALSO
.Xr PKCS12_create 3 ,
.Xr PKCS12_add_safe 3 ,
.Xr PKCS12_add_safes 3
.Sh HISTORY
The functions
.Fn PKCS12_SAFEBAG_get1_cert_ex
and
.Fn PKCS12_SAFEBAG_get1_crl_ex
were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2019-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
