.Dd 2025-09-30
.Dt PKCS12_ADD_CERT 3ossl
.Os
.Sh NAME
.Nm PKCS12_add_cert ,
.Nm PKCS12_add_key ,
.Nm PKCS12_add_key_ex ,
.Nm PKCS12_add_secret
.Nd Add an object to a set of PKCS#12 safeBags
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_add_cert
.Fa "STACK_OF(PKCS12_SAFEBAG) **pbags"
.Fa "X509 *cert"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_add_key
.Fa "STACK_OF(PKCS12_SAFEBAG) **pbags"
.Fa "EVP_PKEY *key"
.Fa "int key_usage"
.Fa "int iter"
.Fa "int key_nid"
.Fa "const char *pass"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_add_key_ex
.Fa "STACK_OF(PKCS12_SAFEBAG) **pbags"
.Fa "EVP_PKEY *key"
.Fa "int key_usage"
.Fa "int iter"
.Fa "int key_nid"
.Fa "const char *pass"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Ft PKCS12_SAFEBAG *
.Fo PKCS12_add_secret
.Fa "STACK_OF(PKCS12_SAFEBAG) **pbags"
.Fa "int nid_type"
.Fa "const unsigned char *value"
.Fa "int len"
.Fc
.Sh DESCRIPTION
These functions create a new
.Vt PKCS12_SAFEBAG
and add it to the set of safeBags in
.Fa pbags .
.Pp
.Fn PKCS12_add_cert
creates a PKCS#12 certBag containing the supplied certificate and adds
this to the set of PKCS#12 safeBags.
.Pp
.Fn PKCS12_add_key
creates a PKCS#12 keyBag (unencrypted) or a pkcs8shroudedKeyBag
(encrypted) containing the supplied
.Vt EVP_PKEY
and adds this to the set of PKCS#12 safeBags.
If
.Fa key_nid
is not -1 then the key is encrypted with the supplied algorithm, using
.Fa pass
as the passphrase and
.Fa iter
as the iteration count.
If
.Fa iter
is zero then a default value for iteration count of 2048 is used.
.Pp
.Fn PKCS12_add_key_ex
is identical to
.Fn PKCS12_add_key
but allows for a library context
.Fa ctx
and property query
.Fa propq
to be used to select algorithm implementations.
.Pp
.Fn PKCS12_add_secret
creates a PKCS#12 secretBag with an OID corresponding to the supplied
.Fa nid_type
containing the supplied value as an ASN1 octet string.
This is then added to the set of PKCS#12 safeBags.
.Sh NOTES
If a certificate contains an
.Em alias
or a
.Em keyid
then this will be used for the corresponding
.Sy friendlyName
or
.Sy localKeyID
in the PKCS12 structure.
.Pp
.Fn PKCS12_add_key
makes assumptions regarding the encoding of the given pass phrase.
See
.Xr passphrase-encoding 7
for more information.
.Sh RETURN VALUES
A valid
.Vt PKCS12_SAFEBAG
structure or NULL if an error occurred.
.Sh CONFORMING TO
IETF RFC 7292
.Pf ( Lk https://tools.ietf.org/html/rfc7292 )
.Sh SEE ALSO
.Xr PKCS12_create 3
.Sh HISTORY
.Fn PKCS12_add_secret
and
.Fn PKCS12_add_key_ex
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
