.Dd 2025-09-30
.Dt PKCS12_GEN_MAC 3ossl
.Os
.Sh NAME
.Nm PKCS12_gen_mac ,
.Nm PKCS12_setup_mac ,
.Nm PKCS12_set_mac ,
.Nm PKCS12_set_pbmac1_pbkdf2 ,
.Nm PKCS12_verify_mac ,
.Nm PKCS12_get0_mac
.Nd Functions to create and manipulate a PKCS#12 MAC structure
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft int
.Fo PKCS12_gen_mac
.Fa "PKCS12 *p12"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "unsigned char *mac"
.Fa "unsigned int *maclen"
.Fc
.Ft int
.Fo PKCS12_verify_mac
.Fa "PKCS12 *p12"
.Fa "const char *pass"
.Fa "int passlen"
.Fc
.Ft int
.Fo PKCS12_set_mac
.Fa "PKCS12 *p12"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "int iter"
.Fa "const EVP_MD *md_type"
.Fc
.Ft int
.Fo PKCS12_set_pbmac1_pbkdf2
.Fa "PKCS12 *p12"
.Fa "const char *pass"
.Fa "int passlen"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "int iter"
.Fa "const EVP_MD *md_type"
.Fa "const char *prf_md_name"
.Fc
.Ft int
.Fo PKCS12_setup_mac
.Fa "PKCS12 *p12"
.Fa "int iter"
.Fa "unsigned char *salt"
.Fa "int saltlen"
.Fa "const EVP_MD *md_type"
.Fc
.Ft void
.Fo PKCS12_get0_mac
.Fa "const ASN1_OCTET_STRING **pmac"
.Fa "const X509_ALGOR **pmacalg"
.Fa "const ASN1_OCTET_STRING **psalt"
.Fa "const ASN1_INTEGER **piter"
.Fa "const PKCS12 *p12"
.Fc
.Sh DESCRIPTION
.Fn PKCS12_gen_mac
generates an HMAC over the entire PKCS#12 object using the supplied
password along with a set of already configured parameters.
The default key generation mechanism used is PKCS12KDF.
.Pp
.Fn PKCS12_verify_mac
verifies the PKCS#12 object's HMAC using the supplied password.
.Pp
.Fn PKCS12_setup_mac
sets the MAC part of the PKCS#12 structure with the supplied parameters.
.Pp
.Fn PKCS12_set_mac
sets the MAC and MAC parameters into the PKCS#12 object.
.Fn PKCS12_set_pbmac1_pbkdf2
sets the MAC and MAC parameters into the PKCS#12 object when
.Sy PBMAC1
with PBKDF2 is used for protection of the PKCS#12 object.
.Pp
.Fa pass
is the passphrase to use in the HMAC.
.Fa salt
is the salt value to use,
.Fa iter
is the iteration count and
.Fa md_type
is the message digest function to use.
.Fa prf_md_name
specifies the digest used for the PBKDF2 in PBMAC1 KDF.
.Pp
.Fn PKCS12_get0_mac
retrieves any included MAC value,
.Sy X509_ALGOR
object,
.Fa salt ,
and
.Fa iter
count from the PKCS12 object.
.Sh NOTES
If
.Fa salt
is NULL then a suitable salt will be generated and used.
.Pp
If
.Fa iter
is 1 then an iteration count will be omitted from the PKCS#12 structure.
.Pp
.Fn PKCS12_gen_mac ,
.Fn PKCS12_verify_mac ,
.Fn PKCS12_set_mac
and
.Fn PKCS12_set_pbmac1_pbkdf2
make assumptions regarding the encoding of the given passphrase.
See
.Xr passphrase-encoding 7
for more information.
.Sh RETURN VALUES
All functions returning an integer return 1 on success and 0 if an error
occurred.
.Sh CONFORMING TO
IETF RFC 7292
.Pf ( Lk https://tools.ietf.org/html/rfc7292 )
IETF RFC 9579
.Pf ( Lk https://tools.ietf.org/html/rfc9579 )
.Sh SEE ALSO
.Xr d2i_PKCS12 3 ,
.Xr EVP_KDF-PKCS12KDF 7 ,
.Xr PKCS12_create 3 ,
.Xr passphrase-encoding 7
.Sh HISTORY
The
.Em PKCS12_set_pbmac1_pbkdf2
function was added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2021-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
