.Dd 2025-09-30
.Dt PKCS12_ADD1_ATTR_BY_NID 3ossl
.Os
.Sh NAME
.Nm PKCS12_add1_attr_by_NID ,
.Nm PKCS12_add1_attr_by_txt
.Nd Add an attribute to a PKCS#12 safeBag structure
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft int
.Fo PKCS12_add1_attr_by_NID
.Fa "PKCS12_SAFEBAG *bag"
.Fa "int nid"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Ft int
.Fo PKCS12_add1_attr_by_txt
.Fa "PKCS12_SAFEBAG *bag"
.Fa "const char *attrname"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Sh DESCRIPTION
These functions add a PKCS#12 Attribute to the Attribute Set of the
.Fa bag .
.Pp
.Fn PKCS12_add1_attr_by_NID
adds an attribute of type
.Fa nid
with a value of ASN1 type
.Fa type
constructed using
.Fa len
bytes from
.Fa bytes .
.Pp
.Fn PKCS12_add1_attr_by_txt
adds an attribute of type
.Fa attrname
with a value of ASN1 type
.Fa type
constructed using
.Fa len
bytes from
.Fa bytes .
.Sh NOTES
These functions do not check whether an existing attribute of the same
type is present.
There can be multiple attributes with the same type assigned to a
safeBag.
.Pp
Both functions were added in OpenSSL 3.0.
.Sh RETURN VALUES
A return value of 1 indicates success, 0 indicates failure.
.Sh SEE ALSO
.Xr PKCS12_create 3
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
