.Dd 2025-09-30
.Dt PKCS12_CREATE 3ossl
.Os
.Sh NAME
.Nm PKCS12_create ,
.Nm PKCS12_create_ex ,
.Nm PKCS12_create_cb ,
.Nm PKCS12_create_ex2
.Nd create a PKCS#12 structure
.Sh SYNOPSIS
.In openssl/pkcs12.h
.Ft PKCS12 *
.Fo PKCS12_create
.Fa "const char *pass"
.Fa "const char *name"
.Fa "EVP_PKEY *pkey"
.Fa "X509 *cert"
.Fa "STACK_OF(X509) *ca"
.Fa "int nid_key"
.Fa "int nid_cert"
.Fa "int iter"
.Fa "int mac_iter"
.Fa "int keytype"
.Fc
.Ft PKCS12 *
.Fo PKCS12_create_ex
.Fa "const char *pass"
.Fa "const char *name"
.Fa "EVP_PKEY *pkey"
.Fa "X509 *cert"
.Fa "STACK_OF(X509) *ca"
.Fa "int nid_key"
.Fa "int nid_cert"
.Fa "int iter"
.Fa "int mac_iter"
.Fa "int keytype"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fc
.Ft typedef int
.Fo PKCS12_create_cb
.Fa "PKCS12_SAFEBAG *bag"
.Fa "void *cbarg"
.Fc
.Ft PKCS12 *
.Fo PKCS12_create_ex2
.Fa "const char *pass"
.Fa "const char *name"
.Fa "EVP_PKEY *pkey"
.Fa "X509 *cert"
.Fa "STACK_OF(X509) *ca"
.Fa "int nid_key"
.Fa "int nid_cert"
.Fa "int iter"
.Fa "int mac_iter"
.Fa "int keytype"
.Fa "OSSL_LIB_CTX *ctx"
.Fa "const char *propq"
.Fa "PKCS12_create_cb *cb"
.Fa "void *cbarg"
.Fc
.Bd -literal
=head1 DESCRIPTION
.Ed
.Fn PKCS12_create
creates a PKCS#12 structure.
.Pp
.Fa pass
is the passphrase to use.
.Fa name
is the
.Ar friendlyName
to use for the supplied certificate and key.
.Fa pkey
is the private key to include in the structure and
.Fa cert
its corresponding certificates.
.Fa ca ,
if not
.Ar NULL
is an optional set of certificates to also include in the structure.
.Pp
.Fa nid_key
and
.Fa nid_cert
are the encryption algorithms that should be used for the key and
certificate respectively.
The modes GCM, CCM, XTS, and OCB are unsupported.
.Fa iter
is the encryption algorithm iteration count to use and
.Fa mac_iter
is the MAC iteration count to use.
.Fa keytype
is the type of key.
.Pp
.Fn PKCS12_create_ex
is identical to
.Fn PKCS12_create
but allows for a library context
.Fa ctx
and property query
.Fa propq
to be used to select algorithm implementations.
.Pp
.Fn PKCS12_create_ex2
is identical to
.Fn PKCS12_create_ex
but allows for a user defined callback
.Fa cb
of type
.Ar PKCS12_create_cb
to be specified and also allows for an optional argument
.Fa cbarg
to be passed back to the callback.
.Pp
The
.Fa cb
if specified will be called for every safebag added to the PKCS12
structure and allows for optional application processing on the
associated safebag.
For example one such use could be to add attributes to the safebag.
.Sh NOTES
The parameters
.Fa nid_key ,
.Fa nid_cert ,
.Fa iter ,
.Fa mac_iter
and
.Fa keytype
can all be set to zero and sensible defaults will be used.
.Pp
These defaults are: AES password based encryption (PBES2 with PBKDF2 and
AES-256-CBC) for private keys and certificates, the PBKDF2 and MAC key
derivation iteration count of
.Sy PKCS12_DEFAULT_ITER
(currently 2048), and MAC algorithm HMAC with SHA2-256. The MAC key
derivation algorithm used for the outer PKCS#12 structure is PKCS12KDF.
.Pp
The default MAC iteration count is 1 in order to retain compatibility
with old software which did not interpret MAC iteration counts.
If such compatibility is not required then
.Fa mac_iter
should be set to PKCS12_DEFAULT_ITER.
.Pp
.Fa keytype
adds a flag to the store private key.
This is a non standard extension that is only currently interpreted by
MSIE. If set to zero the flag is omitted, if set to
.Sy KEY_SIG
the key can be used for signing only, if set to
.Sy KEY_EX
it can be used for signing and encryption.
This option was useful for old export grade software which could use
signing only keys of arbitrary size but had restrictions on the
permissible sizes of keys which could be used for encryption.
.Pp
If
.Fa name
is
.Dv NULL
and
.Fa cert
contains an
.Em alias
then this will be used for the corresponding
.Sy friendlyName
in the PKCS12 structure instead.
Similarly, if
.Fa pkey
is NULL and
.Fa cert
contains a
.Em keyid
then this will be used for the corresponding
.Sy localKeyID
in the PKCS12 structure instead of the id calculated from the
.Fa pkey .
.Pp
For all certificates in
.Fa ca
then if a certificate contains an
.Em alias
or
.Em keyid
then this will be used for the corresponding
.Sy friendlyName
or
.Sy localKeyID
in the PKCS12 structure.
.Pp
Either
.Fa pkey ,
.Fa cert
or both can be
.Dv NULL
to indicate that no key or certificate is required.
In previous versions both had to be present or a fatal error is
returned.
.Pp
.Fa nid_key
or
.Fa nid_cert
can be set to -1 indicating that no encryption should be used.
.Pp
.Fa mac_iter
can be set to -1 and the MAC will then be omitted entirely.
This can be useful when running with the FIPS provider as the PKCS12KDF
is not a FIPS approvable algorithm.
.Pp
.Fn PKCS12_create
makes assumptions regarding the encoding of the given pass phrase.
See
.Xr passphrase-encoding 7
for more information.
.Pp
If
.Fa cb
is specified, then it should return 1 for success and -1 for a fatal
error.
A return of 0 is intended to mean to not add the bag after all.
.Sh RETURN VALUES
.Fn PKCS12_create
returns a valid
.Vt PKCS12
structure or NULL if an error occurred.
.Sh CONFORMING TO
IETF RFC 7292
.Pf ( Lk https://tools.ietf.org/html/rfc7292 )
.Sh SEE ALSO
.Xr EVP_KDF-PKCS12KDF 7 ,
.Xr d2i_PKCS12 3 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr passphrase-encoding 7
.Sh HISTORY
.Fn PKCS12_create_ex
was added in OpenSSL 3.0.
.Fn PKCS12_create_ex2
was added in OpenSSL 3.2.
.Pp
The defaults for encryption algorithms, MAC algorithm, and the MAC key
derivation iteration count were changed in OpenSSL 3.0 to more modern
standards.
.Sh COPYRIGHT
Copyright 2002-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
