.Dd 2025-09-30
.Dt PKCS7_TYPE_IS_OTHER 3ossl
.Os
.Sh NAME
.Nm PKCS7_type_is_other
.Nd determine content type of PKCS#7 envelopedData structure
.Sh SYNOPSIS
.In openssl/pkcs7.h
.Ft int
.Fo PKCS7_type_is_other
.Fa "PKCS7 *p7"
.Fc
.Sh DESCRIPTION
.Fn PKCS7_type_is_other
returns the whether the content type of a PKCS#7 envelopedData structure
is one of the following content types:
.Pp
NID_pkcs7_data NID_pkcs7_signed NID_pkcs7_enveloped
NID_pkcs7_signedAndEnveloped NID_pkcs7_digest NID_pkcs7_encrypted
.Sh RETURN VALUES
.Fn PKCS7_type_is_other
returns either 0 if the content type is matched or 1 otherwise.
.Sh SEE ALSO
.Xr PKCS7_type_is_data 3 ,
.Xr PKCS7_get_octet_string 3
.Sh COPYRIGHT
Copyright 2002-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
