.Dd 2025-09-30
.Dt PKCS7_SIGN_ADD_SIGNER 3ossl
.Os
.Sh NAME
.Nm PKCS7_sign_add_signer ,
.Nm PKCS7_add_certificate ,
.Nm PKCS7_add_crl
.Nd add information to PKCS7 structure
.Sh SYNOPSIS
.In openssl/pkcs7.h
.Ft PKCS7_SIGNER_INFO *
.Fo PKCS7_sign_add_signer
.Fa "PKCS7 *p7"
.Fa "X509 *signcert"
.Fa "EVP_PKEY *pkey"
.Fa "const EVP_MD *md"
.Fa "int flags"
.Fc
.Ft int
.Fo PKCS7_add_certificate
.Fa "PKCS7 *p7"
.Fa "X509 *cert"
.Fc
.Ft int
.Fo PKCS7_add_crl
.Fa "PKCS7 *p7"
.Fa "X509_CRL *crl"
.Fc
.Sh DESCRIPTION
.Fn PKCS7_sign_add_signer
adds a signer with certificate
.Fa signcert
and private key
.Fa pkey
using message digest
.Fa md
to a PKCS7 signed data structure
.Fa p7 .
.Pp
The
.Vt PKCS7
structure should be obtained from an initial call to
.Xr PKCS7_sign 3
with the flag
.Sy PKCS7_PARTIAL
set or in the case or re-signing a valid PKCS#7 signed data structure.
.Pp
If the
.Fa md
parameter is NULL then the default digest for the public key algorithm
will be used.
.Pp
Unless the
.Sy PKCS7_REUSE_DIGEST
flag is set the returned
.Vt PKCS7
structure is not complete and must be finalized either by streaming (if
applicable) or a call to
.Xr PKCS7_final 3 .
.Sh NOTES
The main purpose of this function is to provide finer control over a
PKCS#7 signed data structure where the simpler
.Xr PKCS7_sign 3
function defaults are not appropriate.
For example if multiple signers or non default digest algorithms are
needed.
.Pp
Any of the following flags (ored together) can be passed in the
.Fa flags
parameter.
.Pp
If
.Sy PKCS7_REUSE_DIGEST
is set then an attempt is made to copy the content digest value from the
.Vt PKCS7
structure: to add a signer to an existing structure.
An error occurs if a matching digest value cannot be found to copy.
The returned
.Vt PKCS7
structure will be valid and finalized when this flag is set.
.Pp
If
.Sy PKCS7_PARTIAL
is set in addition to
.Sy PKCS7_REUSE_DIGEST
then the
.Sy PKCS7_SIGNER_INO
structure will not be finalized so additional attributes can be added.
In this case an explicit call to
.Xr PKCS7_SIGNER_INFO_sign 3
is needed to finalize it.
.Pp
If
.Sy PKCS7_NOCERTS
is set the signer's certificate will not be included in the
.Vt PKCS7
structure, the signer's certificate must still be supplied in the
.Fa signcert
parameter though.
This can reduce the size of the signature if the signers certificate can
be obtained by other means: for example a previously signed message.
.Pp
The signedData structure includes several PKCS#7 authenticatedAttributes
including the signing time, the PKCS#7 content type and the supported
list of ciphers in an SMIMECapabilities attribute.
If
.Sy PKCS7_NOATTR
is set then no authenticatedAttributes will be used.
If
.Sy PKCS7_NOSMIMECAP
is set then just the SMIMECapabilities are omitted.
.Pp
If present the SMIMECapabilities attribute indicates support for the
following algorithms: triple DES, 128 bit RC2, 64 bit RC2, DES and 40
bit RC2. If any of these algorithms is disabled then it will not be
included.
.Pp
.Xr PKCS7_sign_add_signers 3
returns an internal pointer to the
.Vt PKCS7_SIGNER_INFO
structure just added, which can be used to set additional attributes
before it is finalized.
.Pp
.Fn PKCS7_add_certificate
adds to the
.Vt PKCS7
structure
.Fa p7
the certificate
.Fa cert ,
which may be an end-entity (signer) certificate or a CA certificate
useful for chain building.
This is done internally by
.Xr PKCS7_sign_ex 3
and similar signing functions.
It may have to be used before calling
.Xr PKCS7_verify 3
in order to provide any missing certificate(s) needed for verification.
.Pp
.Fn PKCS7_add_crl
adds the CRL
.Fa crl
to the
.Vt PKCS7
structure
.Fa p7 .
This may be called to provide certificate status information to be
included when signing or to use when verifying the
.Vt PKCS7
structure.
.Sh RETURN VALUES
.Xr PKCS7_sign_add_signers 3
returns an internal pointer to the
.Vt PKCS7_SIGNER_INFO
structure just added or NULL if an error occurs.
.Pp
.Fn PKCS7_add_certificate
and
.Fn PKCS7_add_crl
return 1 on success, 0 on error.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr PKCS7_sign_ex 3 ,
.Xr PKCS7_final 3 ,
.Xr PKCS7_verify 3
.Sh HISTORY
The
.Xr PPKCS7_sign_add_signer 3
function was added in OpenSSL 1.0.0.
.Sh COPYRIGHT
Copyright 2007-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
