.Dd 2025-09-30
.Dt PKCS8_PKEY_ADD1_ATTR 3ossl
.Os
.Sh NAME
.Nm PKCS8_pkey_get0_attrs ,
.Nm PKCS8_pkey_add1_attr ,
.Nm PKCS8_pkey_add1_attr_by_NID ,
.Nm PKCS8_pkey_add1_attr_by_OBJ
.Nd PKCS8 attribute functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft const
.Fo STACK_OF
.Fa X509_ATTRIBUTE
.Fc
 *
.Bd -literal
 PKCS8_pkey_get0_attrs(const PKCS8_PRIV_KEY_INFO *p8);
 int PKCS8_pkey_add1_attr(PKCS8_PRIV_KEY_INFO *p8, X509_ATTRIBUTE *attr);
 int PKCS8_pkey_add1_attr_by_NID(PKCS8_PRIV_KEY_INFO *p8, int nid, int type,
                                 const unsigned char *bytes, int len);
 int PKCS8_pkey_add1_attr_by_OBJ(PKCS8_PRIV_KEY_INFO *p8, const ASN1_OBJECT *obj,
                                int type, const unsigned char *bytes, int len);
.Ed
.Sh DESCRIPTION
.Xr PKCS8_pkey_get0_attrs 3
returns a const STACK of X509_ATTRIBUTE present in the passed const
PKCS8_PRIV_KEY_INFO structure
.Sy p8 .
.Pp
.Xr PKCS8_pkey_add1_attr 3
adds a constructed X509_ATTRIBUTE
.Sy attr
to the existing PKCS8_PRIV_KEY_INFO structure
.Sy p8 .
.Pp
.Xr PKCS8_pkey_add1_attr_by_NID 3
and
.Xr PKCS8_pkey_add1_attr_by_OBJ 3
construct a new X509_ATTRIBUTE from the passed arguments and add it to
the existing PKCS8_PRIV_KEY_INFO structure
.Sy p8 .
.Sh RETURN VALUES
.Xr PKCS8_pkey_add1_attr 3 ,
.Xr PKCS8_pkey_add1_attr_by_NID 3 ,
and
.Xr PKCS8_pkey_add1_attr_by_OBJ 3
return 1 for success and 0 for failure.
.Sh NOTES
STACK of X509_ATTRIBUTE is present in many X509-related structures and
some of them have the corresponding set of similar functions.
.Sh SEE ALSO
.Xr crypto 7
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
