.Dd 2025-09-30
.Dt RAND_ADD 3ossl
.Os
.Sh NAME
.Nm RAND_add ,
.Nm RAND_poll ,
.Nm RAND_seed ,
.Nm RAND_status ,
.Nm RAND_event ,
.Nm RAND_screen ,
.Nm RAND_keep_random_devices_open
.Nd add randomness to the PRNG or get its status
.Sh SYNOPSIS
.In openssl/rand.h
.Ft int
.Fo RAND_status
.Fa void
.Fc
.Ft int
.Fo RAND_poll
.Fa 
.Fc
.Ft void
.Fo RAND_add
.Fa "const void *buf"
.Fa "int num"
.Fa "double randomness"
.Fc
.Ft void
.Fo RAND_seed
.Fa "const void *buf"
.Fa "int num"
.Fc
.Ft void
.Fo RAND_keep_random_devices_open
.Fa "int keep"
.Fc
The following functions have been deprecated since OpenSSL 1.1.0, and
can be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo RAND_event
.Fa "UINT iMsg"
.Fa "WPARAM wParam"
.Fa "LPARAM lParam"
.Fc
.Ft void
.Fo RAND_screen
.Fa void
.Fc
.Sh DESCRIPTION
These functions can be used to seed the random generator and to check
its seeded state.
In general, manual (re-)seeding of the default OpenSSL random generator
.Pf ( Xr RAND_OpenSSL 3 )
is not necessary (but allowed), since it does (re-)seed itself
automatically using trusted system entropy sources.
This holds unless the default RAND_METHOD has been replaced or OpenSSL
was built with automatic reseeding disabled, see
.Xr RAND 7
for more details.
.Pp
.Fn RAND_status
indicates whether or not the random generator has been sufficiently
seeded.
If not, functions such as
.Xr RAND_bytes 3
will fail.
.Pp
.Fn RAND_poll
uses the system's capabilities to seed the random generator using random
input obtained from polling various trusted entropy sources.
The default choice of the entropy source can be modified at build time,
see
.Xr RAND 7
for more details.
.Pp
.Fn RAND_add
mixes the
.Fa num
bytes at
.Fa buf
into the internal state of the random generator.
This function will not normally be needed, as mentioned above.
The
.Fa randomness
argument is an estimate of how much randomness is contained in
.Fa buf ,
in bytes, and should be a number between zero and
.Fa num .
Details about sources of randomness and how to estimate their randomness
can be found in the literature; for example [NIST SP 800-90B]. The
content of
.Fa buf
cannot be recovered from subsequent random generator output.
Applications that intend to save and restore random state in an external
file should consider using
.Xr RAND_load_file 3
instead.
.Pp
NOTE: In FIPS mode, random data provided by the application is not
considered to be a trusted entropy source.
It is mixed into the internal state of the RNG as additional data only
and this does not count as a full reseed.
For more details, see
.Xr EVP_RAND 7 .
.Pp
.Fn RAND_seed
is equivalent to
.Fn RAND_add
with
.Fa randomness
set to
.Fa num .
.Pp
.Fn RAND_keep_random_devices_open
is used to control file descriptor usage by the random seed sources.
Some seed sources maintain open file descriptors by default, which
allows such sources to operate in a chroot(2) jail without the
associated device nodes being available.
When the
.Fa keep
argument is zero, this call disables the retention of file descriptors.
Conversely, a nonzero argument enables the retention of file
descriptors.
This function is usually called during initialization and it takes
effect immediately.
This capability only applies to the default provider.
.Pp
.Fn RAND_event
and
.Fn RAND_screen
are equivalent to
.Fn RAND_poll
and exist for compatibility reasons only.
See HISTORY section below.
.Sh RETURN VALUES
.Fn RAND_status
returns 1 if the random generator has been seeded with enough data, 0
otherwise.
.Pp
.Fn RAND_poll
returns 1 if it generated seed data, 0 otherwise.
.Pp
.Fn RAND_event
returns
.Fn RAND_status .
.Pp
The other functions do not return values.
.Sh SEE ALSO
.Xr RAND_bytes 3 ,
.Xr RAND_egd 3 ,
.Xr RAND_load_file 3 ,
.Xr RAND 7
.Xr EVP_RAND 7
.Sh HISTORY
.Fn RAND_event
and
.Fn RAND_screen
were deprecated in OpenSSL 1.1.0 and should not be used.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
