.Dd 2025-09-30
.Dt RAND_LOAD_FILE 3ossl
.Os
.Sh NAME
.Nm RAND_load_file ,
.Nm RAND_write_file ,
.Nm RAND_file_name
.Nd PRNG seed file
.Sh SYNOPSIS
.In openssl/rand.h
.Ft int
.Fo RAND_load_file
.Fa "const char *filename"
.Fa "long max_bytes"
.Fc
.Ft int
.Fo RAND_write_file
.Fa "const char *filename"
.Fc
.Ft const char *
.Fo RAND_file_name
.Fa "char *buf"
.Fa "size_t num"
.Fc
.Sh DESCRIPTION
.Fn RAND_load_file
reads a number of bytes from file
.Fa filename
and adds them to the PRNG. If
.Fa max_bytes
is nonnegative, up to
.Fa max_bytes
are read; if
.Fa max_bytes
is -1, the complete file is read (unless the file is not a regular file,
in that case a fixed number of bytes, 256 in the current implementation,
is attempted to be read).
.Fn RAND_load_file
can read less than the complete file or the requested number of bytes if
it doesn't fit in the return value type.
Do not load the same file multiple times unless its contents have been
updated by
.Fn RAND_write_file
between reads.
Also, note that
.Fa filename
should be adequately protected so that an attacker cannot replace or
examine the contents.
If
.Fa filename
is not a regular file, then user is considered to be responsible for any
side effects, e.g.
non-anticipated blocking or capture of controlling terminal.
.Pp
.Fn RAND_write_file
writes a number of random bytes (currently 128) to file
.Fa filename
which can be used to initialize the PRNG by calling
.Fn RAND_load_file
in a later session.
.Pp
.Fn RAND_file_name
generates a default path for the random seed file.
.Fa buf
points to a buffer of size
.Fa num
in which to store the filename.
.Pp
On all systems, if the environment variable
.Sy RANDFILE
is set, its value will be used as the seed filename.
Otherwise, the file is called
.Qo Li .rnd Qc ,
found in platform dependent locations:
.Bl -tag -width Ds
.It \&On Windows (in order of preference)
.Bd -literal
 %HOME%, %USERPROFILE%, %SYSTEMROOT%, C:\e
.Ed
.It \&On VMS
.Bd -literal
 SYS$LOGIN:
.Ed
.It \&On all other systems
.Bd -literal
 $HOME
.Ed
.El
If
.Qo Li $HOME Qc
(on non-Windows and non-VMS system) is not set either, or
.Fa num
is too small for the pathname, an error occurs.
.Sh RETURN VALUES
.Fn RAND_load_file
returns the number of bytes read or -1 on error.
.Pp
.Fn RAND_write_file
returns the number of bytes written, or -1 if the bytes written were
generated without appropriate seeding.
.Pp
.Fn RAND_file_name
returns a pointer to
.Fa buf
on success, and NULL on error.
.Sh SEE ALSO
.Xr RAND_add 3 ,
.Xr RAND_bytes 3 ,
.Xr RAND 7
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
