.Dd 2025-09-30
.Dt RSA_SET_METHOD 3ossl
.Os
.Sh NAME
.Nm RSA_set_default_method ,
.Nm RSA_get_default_method ,
.Nm RSA_set_method ,
.Nm RSA_get_method ,
.Nm RSA_PKCS1_OpenSSL ,
.Nm RSA_flags ,
.Nm RSA_new_method
.Nd select RSA method
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo RSA_set_default_method
.Fa "const RSA_METHOD *meth"
.Fc
.Ft const RSA_METHOD *
.Fo RSA_get_default_method
.Fa void
.Fc
.Ft int
.Fo RSA_set_method
.Fa "RSA *rsa"
.Fa "const RSA_METHOD *meth"
.Fc
.Ft const RSA_METHOD *
.Fo RSA_get_method
.Fa "const RSA *rsa"
.Fc
.Ft const RSA_METHOD *
.Fo RSA_PKCS1_OpenSSL
.Fa void
.Fc
.Ft int
.Fo RSA_flags
.Fa "const RSA *rsa"
.Fc
.Ft RSA *
.Fo RSA_new_method
.Fa "ENGINE *engine"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the OSSL_PROVIDER APIs.
.Pp
An
.Sy RSA_METHOD
specifies the functions that OpenSSL uses for RSA operations.
By modifying the method, alternative implementations such as hardware
accelerators may be used.
IMPORTANT: See the NOTES section for important information about how
these RSA API functions are affected by the use of
.Vt ENGINE
API calls.
.Pp
Initially, the default RSA_METHOD is the OpenSSL internal
implementation, as returned by
.Fn RSA_PKCS1_OpenSSL .
.Pp
.Fn RSA_set_default_method
makes
.Fa meth
the default method for all RSA structures created later.
.Sy NB :
This is true only whilst no ENGINE has been set as a default for RSA, so
this function is no longer recommended.
This function is not thread-safe and should not be called at the same
time as other OpenSSL functions.
.Pp
.Fn RSA_get_default_method
returns a pointer to the current default RSA_METHOD. However, the
meaningfulness of this result is dependent on whether the ENGINE API is
being used, so this function is no longer recommended.
.Pp
.Fn RSA_set_method
selects
.Fa meth
to perform all operations using the key
.Fa rsa .
This will replace the RSA_METHOD used by the RSA key and if the previous
method was supplied by an ENGINE, the handle to that ENGINE will be
released during the change.
It is possible to have RSA keys that only work with certain RSA_METHOD
implementations (e.g.
from an ENGINE module that supports embedded hardware-protected keys),
and in such cases attempting to change the RSA_METHOD for the key can
have unexpected results.
.Pp
.Fn RSA_get_method
returns a pointer to the RSA_METHOD being used by
.Fa rsa .
This method may or may not be supplied by an ENGINE implementation, but
if it is, the return value can only be guaranteed to be valid as long as
the RSA key itself is valid and does not have its implementation changed
by
.Fn RSA_set_method .
.Pp
.Fn RSA_flags
returns the
.Sy flags
that are set for
.Fa rsa Ns 's
current RSA_METHOD. See the BUGS section.
.Pp
.Fn RSA_new_method
allocates and initializes an RSA structure so that
.Fa engine
will be used for the RSA operations.
If
.Fa engine
is NULL, the default ENGINE for RSA operations is used, and if no
default ENGINE is set, the RSA_METHOD controlled by
.Fn RSA_set_default_method
is used.
.Pp
.Fn RSA_flags
returns the
.Sy flags
that are set for
.Fa rsa Ns 's
current method.
.Pp
.Fn RSA_new_method
allocates and initializes an
.Vt RSA
structure so that
.Sy method
will be used for the RSA operations.
If
.Sy method
is
.Dv NULL ,
the default method is used.
.Sh THE RSA_METHOD STRUCTURE
.Bd -literal
 typedef struct rsa_meth_st
 {
     /* name of the implementation */
     const char *name;

     /* encrypt */
     int (*rsa_pub_enc)(int flen, unsigned char *from,
                        unsigned char *to, RSA *rsa, int padding);

     /* verify arbitrary data */
     int (*rsa_pub_dec)(int flen, unsigned char *from,
                        unsigned char *to, RSA *rsa, int padding);

     /* sign arbitrary data */
     int (*rsa_priv_enc)(int flen, unsigned char *from,
                         unsigned char *to, RSA *rsa, int padding);

     /* decrypt */
     int (*rsa_priv_dec)(int flen, unsigned char *from,
                         unsigned char *to, RSA *rsa, int padding);

     /* compute r0 = r0 ^ I mod rsa->n (May be NULL for some implementations) */
     int (*rsa_mod_exp)(BIGNUM *r0, BIGNUM *I, RSA *rsa);

     /* compute r = a ^ p mod m (May be NULL for some implementations) */
     int (*bn_mod_exp)(BIGNUM *r, BIGNUM *a, const BIGNUM *p,
                       const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx);

     /* called at RSA_new */
     int (*init)(RSA *rsa);

     /* called at RSA_free */
     int (*finish)(RSA *rsa);

     /*
      * RSA_FLAG_EXT_PKEY        - rsa_mod_exp is called for private key
      *                            operations, even if p,q,dmp1,dmq1,iqmp
      *                            are NULL
      * RSA_METHOD_FLAG_NO_CHECK - don't check pub/private match
      */
     int flags;

     char *app_data; /* ?? */

     int (*rsa_sign)(int type,
                     const unsigned char *m, unsigned int m_length,
                     unsigned char *sigret, unsigned int *siglen, const RSA *rsa);
     int (*rsa_verify)(int dtype,
                       const unsigned char *m, unsigned int m_length,
                       const unsigned char *sigbuf, unsigned int siglen,
                       const RSA *rsa);
     /* keygen. If NULL built-in RSA key generation will be used */
     int (*rsa_keygen)(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb);

 } RSA_METHOD;
.Ed
.Sh RETURN VALUES
.Fn RSA_PKCS1_OpenSSL ,
.Xr RSA_PKCS1_null_method 3 ,
.Fn RSA_get_default_method
and
.Fn RSA_get_method
return pointers to the respective RSA_METHODs.
.Pp
.Fn RSA_set_default_method
returns no value.
.Pp
.Fn RSA_set_method
returns a pointer to the old RSA_METHOD implementation that was
replaced.
However, this return value should probably be ignored because if it was
supplied by an ENGINE, the pointer could be invalidated at any time if
the ENGINE is unloaded (in fact it could be unloaded as a result of the
.Fn RSA_set_method
function releasing its handle to the ENGINE). For this reason, the
return type may be replaced with a
.Vt void
declaration in a future release.
.Pp
.Fn RSA_new_method
returns NULL and sets an error code that can be obtained by
.Xr ERR_get_error 3
if the allocation fails.
Otherwise it returns a pointer to the newly allocated structure.
.Sh BUGS
The behaviour of
.Fn RSA_flags
is a mis-feature that is left as-is for now to avoid creating
compatibility problems.
RSA functionality, such as the encryption functions, are controlled by
the
.Sy flags
value in the RSA key itself, not by the
.Sy flags
value in the RSA_METHOD attached to the RSA key (which is what this
function returns).
If the flags element of an RSA key is changed, the changes will be
honoured by RSA functionality but will not be reflected in the return
value of the
.Fn RSA_flags
function - in effect
.Fn RSA_flags
behaves more like an
.Xr RSA_default_flags 3
function (which does not currently exist).
.Sh SEE ALSO
.Xr RSA_new 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
The
.Xr RSA_null_method 3 ,
which was a partial attempt to avoid patent issues, was replaced to
always return NULL in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
