.Dd 2025-09-30
.Dt RSA_PADDING_ADD_PKCS1_TYPE_1 3ossl
.Os
.Sh NAME
.Nm RSA_padding_add_PKCS1_type_1 ,
.Nm RSA_padding_check_PKCS1_type_1 ,
.Nm RSA_padding_add_PKCS1_type_2 ,
.Nm RSA_padding_check_PKCS1_type_2 ,
.Nm RSA_padding_add_PKCS1_OAEP ,
.Nm RSA_padding_check_PKCS1_OAEP ,
.Nm RSA_padding_add_PKCS1_OAEP_mgf1 ,
.Nm RSA_padding_check_PKCS1_OAEP_mgf1 ,
.Nm RSA_padding_add_none ,
.Nm RSA_padding_check_none
.Nd asymmetric encryption padding
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo RSA_padding_add_PKCS1_type_1
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fc
.Ft int
.Fo RSA_padding_check_PKCS1_type_1
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "int rsa_len"
.Fc
.Ft int
.Fo RSA_padding_add_PKCS1_type_2
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fc
.Ft int
.Fo RSA_padding_check_PKCS1_type_2
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "int rsa_len"
.Fc
.Ft int
.Fo RSA_padding_add_PKCS1_OAEP
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "const unsigned char *p"
.Fa "int pl"
.Fc
.Ft int
.Fo RSA_padding_check_PKCS1_OAEP
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "int rsa_len"
.Fa "const unsigned char *p"
.Fa "int pl"
.Fc
.Ft int
.Fo RSA_padding_add_PKCS1_OAEP_mgf1
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "const unsigned char *p"
.Fa "int pl"
.Fa "const EVP_MD *md"
.Fa "const EVP_MD *mgf1md"
.Fc
.Ft int
.Fo RSA_padding_check_PKCS1_OAEP_mgf1
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "int rsa_len"
.Fa "const unsigned char *p"
.Fa "int pl"
.Fa "const EVP_MD *md"
.Fa "const EVP_MD *mgf1md"
.Fc
.Ft int
.Fo RSA_padding_add_none
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fc
.Ft int
.Fo RSA_padding_check_none
.Fa "unsigned char *to"
.Fa "int tlen"
.Fa "const unsigned char *f"
.Fa "int fl"
.Fa "int rsa_len"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the EVP PKEY APIs.
.Pp
The
.Xr RSA_padding_xxx_xxx 3
functions are called from the RSA encrypt, decrypt, sign and verify
functions.
Normally they should not be called from application programs.
.Pp
However, they can also be called directly to implement padding for other
asymmetric ciphers.
.Fn RSA_padding_add_PKCS1_OAEP
and
.Fn RSA_padding_check_PKCS1_OAEP
may be used in an application combined with
.Sy RSA_NO_PADDING
in order to implement OAEP with an encoding parameter.
.Pp
.Xr RSA_padding_add_xxx 3
encodes
.Fa fl
bytes from
.Fa f
so as to fit into
.Fa tlen
bytes and stores the result at
.Fa to .
An error occurs if
.Fa fl
does not meet the size requirements of the encoding method.
.Pp
The following encoding methods are implemented:
.Bl -tag -width Ds
.It PKCS1_type_1
PKCS #1 v2.0 EMSA-PKCS1-v1_5 (PKCS #1 v1.5 block type 1); used for
signatures
.It PKCS1_type_2
PKCS #1 v2.0 EME-PKCS1-v1_5 (PKCS #1 v1.5 block type 2)
.It PKCS1_OAEP
PKCS #1 v2.0 EME-OAEP
.It none
simply copy the data
.El
.Pp
The random number generator must be seeded prior to calling
.Xr RSA_padding_add_xxx 3 .
If the automatic seeding or reseeding of the OpenSSL CSPRNG fails due to
external circumstances (see
.Xr RAND 7 Ns ),
the operation will fail.
.Pp
.Xr RSA_padding_check_xxx 3
verifies that the
.Fa fl
bytes at
.Fa f
contain a valid encoding for a
.Fa rsa_len
byte RSA key in the respective encoding method and stores the recovered
data of at most
.Fa tlen
bytes (for
.Sy RSA_NO_PADDING :
of size
.Fa tlen )
at
.Fa to .
.Pp
For
.Xr RSA_padding_xxx_OAEP 3 ,
.Fa p
points to the encoding parameter of length
.Fa pl .
.Fa p
may be
.Dv NULL
if
.Fa pl
is 0.
.Pp
For
.Xr RSA_padding_xxx_OAEP_mgf1 3 ,
.Fa md
points to the md hash, if
.Fa md
is
.Dv NULL
that means md=sha1, and
.Fa mgf1md
points to the mgf1 hash, if
.Fa mgf1md
is
.Dv NULL
that means mgf1md=md.
.Sh RETURN VALUES
The
.Xr RSA_padding_add_xxx 3
functions return 1 on success, 0 on error.
The
.Xr RSA_padding_check_xxx 3
functions return the length of the recovered data, -1 on error.
Error codes can be obtained by calling
.Xr ERR_get_error 3 .
.Sh WARNINGS
The result of
.Fn RSA_padding_check_PKCS1_type_2
is exactly the information which is used to mount a classical
Bleichenbacher padding oracle attack.
This is an inherent weakness in the PKCS #1 v1.5 padding design.
Prefer PKCS1_OAEP padding.
If that is not possible, the result of
.Fn RSA_padding_check_PKCS1_type_2
should be checked in constant time if it matches the expected length of
the plaintext and additionally some application specific consistency
checks on the plaintext need to be performed in constant time.
If the plaintext is rejected it must be kept secret which of the checks
caused the application to reject the message.
Do not remove the zero-padding from the decrypted raw RSA data which was
computed by
.Xr RSA_private_decrypt 3
with
.Sy RSA_NO_PADDING ,
as this would create a small timing side channel which could be used to
mount a Bleichenbacher attack against any padding mode including
PKCS1_OAEP.
.Pp
You should prefer the use of EVP PKEY APIs for PKCS#1 v1.5 decryption as
they implement the necessary workarounds internally.
.Sh SEE ALSO
.Xr RSA_public_encrypt 3 ,
.Xr RSA_private_decrypt 3 ,
.Xr RSA_sign 3 ,
.Xr RSA_verify 3 ,
.Xr RAND 7
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
