.Dd 2025-09-30
.Dt RSA_NEW 3ossl
.Os
.Sh NAME
.Nm RSA_new ,
.Nm RSA_free
.Nd allocate and free RSA objects
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft RSA *
.Fo RSA_new
.Fa void
.Fc
.Ft void
.Fo RSA_free
.Fa "RSA *rsa"
.Fc
.Sh DESCRIPTION
.Fn RSA_new
allocates and initializes an
.Vt RSA
structure.
It is equivalent to calling RSA_new_method(NULL).
.Pp
.Fn RSA_free
frees the
.Vt RSA
structure and its components.
The key is erased before the memory is returned to the system.
If
.Fa rsa
is NULL nothing is done.
.Sh RETURN VALUES
If the allocation fails,
.Fn RSA_new
returns
.Dv NULL
and sets an error code that can be obtained by
.Xr ERR_get_error 3 .
Otherwise it returns a pointer to the newly allocated structure.
.Pp
.Fn RSA_free
returns no value.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr RSA_generate_key 3 ,
.Xr RSA_new_method 3
.Sh HISTORY
All functions described here were deprecated in OpenSSL 3.0. For
replacement see EVP_PKEY-RSA(7).
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
