.Dd 2025-09-30
.Dt RSA_SIGN_ASN1_OCTET_STRING 3ossl
.Os
.Sh NAME
.Nm RSA_sign_ASN1_OCTET_STRING ,
.Nm RSA_verify_ASN1_OCTET_STRING
.Nd RSA signatures
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo RSA_sign_ASN1_OCTET_STRING
.Fa "int dummy"
.Fa "unsigned char *m"
.Fa "unsigned int m_len"
.Fa "unsigned char *sigret"
.Fa "unsigned int *siglen"
.Fa "RSA *rsa"
.Fc
.Ft int
.Fo RSA_verify_ASN1_OCTET_STRING
.Fa "int dummy"
.Fa "unsigned char *m"
.Fa "unsigned int m_len"
.Fa "unsigned char *sigbuf"
.Fa "unsigned int siglen"
.Fa "RSA *rsa"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use EVP PKEY APIs.
.Pp
.Fn RSA_sign_ASN1_OCTET_STRING
signs the octet string
.Fa m
of size
.Fa m_len
using the private key
.Fa rsa
represented in DER using PKCS #1 padding.
It stores the signature in
.Fa sigret
and the signature size in
.Fa siglen .
.Fa sigret
must point to
.Sy RSA_size(rsa)
bytes of memory.
.Pp
.Fa dummy
is ignored.
.Pp
The random number generator must be seeded when calling
.Fn RSA_sign_ASN1_OCTET_STRING .
If the automatic seeding or reseeding of the OpenSSL CSPRNG fails due to
external circumstances (see
.Xr RAND 7 Ns ),
the operation will fail.
.Pp
.Fn RSA_verify_ASN1_OCTET_STRING
verifies that the signature
.Fa sigbuf
of size
.Fa siglen
is the DER representation of a given octet string
.Fa m
of size
.Fa m_len .
.Fa dummy
is ignored.
.Fa rsa
is the signer's public key.
.Sh RETURN VALUES
.Fn RSA_sign_ASN1_OCTET_STRING
returns 1 on success, 0 otherwise.
.Fn RSA_verify_ASN1_OCTET_STRING
returns 1 on successful verification, 0 otherwise.
.Pp
The error codes can be obtained by
.Xr ERR_get_error 3 .
.Sh BUGS
These functions serve no recognizable purpose.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr RAND_bytes 3 ,
.Xr RSA_sign 3 ,
.Xr RSA_verify 3 ,
.Xr RAND 7
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
