.Dd 2025-09-30
.Dt RSA_CHECK_KEY 3ossl
.Os
.Sh NAME
.Nm RSA_check_key_ex ,
.Nm RSA_check_key
.Nd validate private RSA keys
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo RSA_check_key_ex
.Fa "const RSA *rsa"
.Fa "BN_GENCB *cb"
.Fc
.Ft int
.Fo RSA_check_key
.Fa "const RSA *rsa"
.Fc
.Sh DESCRIPTION
Both of the functions described on this page are deprecated.
Applications should instead use
.Xr EVP_PKEY_public_check 3 ,
.Xr EVP_PKEY_private_check 3
and
.Xr EVP_PKEY_pairwise_check 3 .
.Pp
.Fn RSA_check_key_ex
function validates RSA keys.
It checks that
.Sy p
and
.Sy q
are in fact prime, and that
.Sy n = p*q .
.Pp
It does not work on RSA public keys that have only the modulus and
public exponent elements populated.
It also checks that
.Sy d*e = 1 mod (p-1*q-1) ,
and that
.Sy dmp1 ,
.Sy dmq1
and
.Sy iqmp
are set correctly or are
.Dv NULL .
It performs integrity checks on all the RSA key material, so the RSA key
structure must contain all the private key data too.
Therefore, it cannot be used with any arbitrary RSA key object, even if
it is otherwise fit for regular RSA operation.
.Pp
The
.Fa cb
parameter is a callback that will be invoked in the same manner as
.Xr BN_is_prime_ex 3 .
.Pp
.Fn RSA_check_key
is equivalent to
.Fn RSA_check_key_ex
with a NULL
.Fa cb .
.Sh RETURN VALUES
.Fn RSA_check_key_ex
and
.Fn RSA_check_key
return 1 if
.Fa rsa
is a valid RSA key, and 0 otherwise.
They return -1 if an error occurs while checking the key.
.Pp
If the key is invalid or an error occurred, the reason code can be
obtained using
.Xr ERR_get_error 3 .
.Sh NOTES
Unlike most other RSA functions, this function does
.Sy not
work transparently with any underlying ENGINE implementation because it
uses the key data in the RSA structure directly.
An ENGINE implementation can override the way key data is stored and
handled, and can even provide support for HSM keys - in which case the
RSA structure may contain
.Sy no
key data at all!
If the ENGINE in question is only being used for acceleration or
analysis purposes, then in all likelihood the RSA key data is complete
and untouched, but this can't be assumed in the general case.
.Sh BUGS
A method of verifying the RSA key using opaque RSA API functions might
need to be considered.
Right now
.Fn RSA_check_key
simply uses the RSA structure elements directly, bypassing the
RSA_METHOD table altogether (and completely violating encapsulation and
object-orientation in the process).
The best fix will probably be to introduce a
.Xr \(dqcheck_key 3 "
handler to the RSA_METHOD function table so that alternative
implementations can also provide their own verifiers.
.Sh SEE ALSO
.Xr BN_is_prime_ex 3 ,
.Xr ERR_get_error 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
.Fn RSA_check_key_ex
appeared after OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
