.Dd 2025-09-30
.Dt RSA_BLINDING_ON 3ossl
.Os
.Sh NAME
.Nm RSA_blinding_on ,
.Nm RSA_blinding_off
.Nd protect the RSA operation from timing attacks
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo RSA_blinding_on
.Fa "RSA *rsa"
.Fa "BN_CTX *ctx"
.Fc
.Ft void
.Fo RSA_blinding_off
.Fa "RSA *rsa"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
.Pp
RSA is vulnerable to timing attacks.
In a setup where attackers can measure the time of RSA decryption or
signature operations, blinding must be used to protect the RSA operation
from that attack.
.Pp
.Fn RSA_blinding_on
turns blinding on for key
.Fa rsa
and generates a random blinding factor.
.Fa ctx
is
.Dv NULL
or a preallocated and initialized
.Vt BN_CTX .
.Pp
.Fn RSA_blinding_off
turns blinding off and frees the memory used for the blinding factor.
.Sh RETURN VALUES
.Fn RSA_blinding_on
returns 1 on success, and 0 if an error occurred.
.Pp
.Fn RSA_blinding_off
returns no value.
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
