.Dd 2025-09-30
.Dt RSA_METH_NEW 3ossl
.Os
.Sh NAME
.Nm RSA_meth_get0_app_data ,
.Nm RSA_meth_set0_app_data ,
.Nm RSA_meth_new ,
.Nm RSA_meth_free ,
.Nm RSA_meth_dup ,
.Nm RSA_meth_get0_name ,
.Nm RSA_meth_set1_name ,
.Nm RSA_meth_get_flags ,
.Nm RSA_meth_set_flags ,
.Nm RSA_meth_get_pub_enc ,
.Nm RSA_meth_set_pub_enc ,
.Nm RSA_meth_get_pub_dec ,
.Nm RSA_meth_set_pub_dec ,
.Nm RSA_meth_get_priv_enc ,
.Nm RSA_meth_set_priv_enc ,
.Nm RSA_meth_get_priv_dec ,
.Nm RSA_meth_set_priv_dec ,
.Nm RSA_meth_get_mod_exp ,
.Nm RSA_meth_set_mod_exp ,
.Nm RSA_meth_get_bn_mod_exp ,
.Nm RSA_meth_set_bn_mod_exp ,
.Nm RSA_meth_get_init ,
.Nm RSA_meth_set_init ,
.Nm RSA_meth_get_finish ,
.Nm RSA_meth_set_finish ,
.Nm RSA_meth_get_sign ,
.Nm RSA_meth_set_sign ,
.Nm RSA_meth_get_verify ,
.Nm RSA_meth_set_verify ,
.Nm RSA_meth_get_keygen ,
.Nm RSA_meth_set_keygen ,
.Nm RSA_meth_get_multi_prime_keygen ,
.Nm RSA_meth_set_multi_prime_keygen
.Nd Routines to build up RSA methods
.Sh SYNOPSIS
.In openssl/rsa.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft RSA_METHOD *
.Fo RSA_meth_new
.Fa "const char *name"
.Fa "int flags"
.Fc
.Ft void
.Fo RSA_meth_free
.Fa "RSA_METHOD *meth"
.Fc
.Ft RSA_METHOD *
.Fo RSA_meth_dup
.Fa "const RSA_METHOD *meth"
.Fc
.Ft const char *
.Fo RSA_meth_get0_name
.Fa "const RSA_METHOD *meth"
.Fc
.Ft int
.Fo RSA_meth_set1_name
.Fa "RSA_METHOD *meth"
.Fa "const char *name"
.Fc
.Ft int
.Fo RSA_meth_get_flags
.Fa "const RSA_METHOD *meth"
.Fc
.Ft int
.Fo RSA_meth_set_flags
.Fa "RSA_METHOD *meth"
.Fa "int flags"
.Fc
.Ft void *
.Fo RSA_meth_get0_app_data
.Fa "const RSA_METHOD *meth"
.Fc
.Ft int
.Fo RSA_meth_set0_app_data
.Fa "RSA_METHOD *meth"
.Fa "void *app_data"
.Fc
.Ft int
.Fo 
.Fa "*RSA_meth_get_pub_enc(const RSA_METHOD *meth)"
.Fc
(int flen, const unsigned char *from,
.Bd -literal
                                                     unsigned char *to, RSA *rsa, int padding);
 int RSA_meth_set_pub_enc(RSA_METHOD *rsa,
                          int (*pub_enc)(int flen, const unsigned char *from,
                                         unsigned char *to, RSA *rsa,
                                         int padding));
.Ed
.Ft int
.Fo 
.Fa "*RSA_meth_get_pub_dec(const RSA_METHOD *meth)"
.Fc
.Bd -literal
     (int flen, const unsigned char *from,
      unsigned char *to, RSA *rsa, int padding);
 int RSA_meth_set_pub_dec(RSA_METHOD *rsa,
                          int (*pub_dec)(int flen, const unsigned char *from,
                                         unsigned char *to, RSA *rsa,
                                         int padding));
.Ed
.Ft int
.Fo 
.Fa "*RSA_meth_get_priv_enc(const RSA_METHOD *meth)"
.Fc
(int flen, const unsigned char *from,
.Bd -literal
                                                      unsigned char *to, RSA *rsa,
                                                      int padding);
 int RSA_meth_set_priv_enc(RSA_METHOD *rsa,
                           int (*priv_enc)(int flen, const unsigned char *from,
                                           unsigned char *to, RSA *rsa, int padding));
.Ed
.Ft int
.Fo 
.Fa "*RSA_meth_get_priv_dec(const RSA_METHOD *meth)"
.Fc
(int flen, const unsigned char *from,
.Bd -literal
                                                      unsigned char *to, RSA *rsa,
                                                      int padding);
 int RSA_meth_set_priv_dec(RSA_METHOD *rsa,
                           int (*priv_dec)(int flen, const unsigned char *from,
                                           unsigned char *to, RSA *rsa, int padding));
.Ed
.Ft /* Can be null */
 int
.Fo 
.Fa "*RSA_meth_get_mod_exp(const RSA_METHOD *meth)"
.Fc
(BIGNUM *r0, const BIGNUM *i,
.Bd -literal
                                                     RSA *rsa, BN_CTX *ctx);
 int RSA_meth_set_mod_exp(RSA_METHOD *rsa,
                          int (*mod_exp)(BIGNUM *r0, const BIGNUM *i, RSA *rsa,
                                         BN_CTX *ctx));
.Ed
.Ft /* Can be null */
 int
.Fo 
.Fa "*RSA_meth_get_bn_mod_exp(const RSA_METHOD *meth)"
.Fc
(BIGNUM *r, const BIGNUM *a,
.Bd -literal
                                                        const BIGNUM *p, const BIGNUM *m,
                                                        BN_CTX *ctx, BN_MONT_CTX *m_ctx);
 int RSA_meth_set_bn_mod_exp(RSA_METHOD *rsa,
                             int (*bn_mod_exp)(BIGNUM *r, const BIGNUM *a,
                                               const BIGNUM *p, const BIGNUM *m,
                                               BN_CTX *ctx, BN_MONT_CTX *m_ctx));

 /* called at new */
 int (*RSA_meth_get_init(const RSA_METHOD *meth) (RSA *rsa);
 int RSA_meth_set_init(RSA_METHOD *rsa, int (*init (RSA *rsa));
.Ed
.Ft /* called at free */
 int
.Fo 
.Fa "*RSA_meth_get_finish(const RSA_METHOD *meth)"
.Fc
(RSA *rsa);
.Ft int
.Fo RSA_meth_set_finish
.Fa "RSA_METHOD *rsa"
.Fa "int (*finish)(RSA *rsa)"
.Fc
.Ft int
.Fo 
.Fa "*RSA_meth_get_sign(const RSA_METHOD *meth)"
.Fc
(int type, const unsigned char *m,
.Bd -literal
                                                  unsigned int m_length,
                                                  unsigned char *sigret,
                                                  unsigned int *siglen, const RSA *rsa);
 int RSA_meth_set_sign(RSA_METHOD *rsa,
                       int (*sign)(int type, const unsigned char *m,
                                   unsigned int m_length, unsigned char *sigret,
                                   unsigned int *siglen, const RSA *rsa));
.Ed
.Ft int
.Fo 
.Fa "*RSA_meth_get_verify(const RSA_METHOD *meth)"
.Fc
(int dtype, const unsigned char *m,
.Bd -literal
                                                    unsigned int m_length,
                                                    const unsigned char *sigbuf,
                                                    unsigned int siglen, const RSA *rsa);
 int RSA_meth_set_verify(RSA_METHOD *rsa,
                         int (*verify)(int dtype, const unsigned char *m,
                                       unsigned int m_length,
                                       const unsigned char *sigbuf,
                                       unsigned int siglen, const RSA *rsa));
.Ed
.Ft int
.Fo 
.Fa "*RSA_meth_get_keygen(const RSA_METHOD *meth)"
.Fc
(RSA *rsa, int bits, BIGNUM *e,
.Bd -literal
                                                    BN_GENCB *cb);
 int RSA_meth_set_keygen(RSA_METHOD *rsa,
                         int (*keygen)(RSA *rsa, int bits, BIGNUM *e,
                                       BN_GENCB *cb));
.Ed
.Ft int
.Fo 
.Fa "*RSA_meth_get_multi_prime_keygen(const RSA_METHOD *meth)"
.Fc
(RSA *rsa, int bits,
.Bd -literal
                                                                int primes, BIGNUM *e,
                                                                BN_GENCB *cb);
.Ed
.Ft int
.Fo RSA_meth_set_multi_prime_keygen
.Fa "RSA_METHOD *meth"
.Fa "int (*keygen) (RSA *rsa"
.Fa "int bits"
.Fa "int primes"
.Fa "BIGNUM *e"
.Fa "BN_GENCB *cb)"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
Applications should instead use the OSSL_PROVIDER APIs.
.Pp
The
.Vt RSA_METHOD
type is a structure used for the provision of custom RSA
implementations.
It provides a set of functions used by OpenSSL for the implementation of
the various RSA capabilities.
.Pp
.Fn RSA_meth_new
creates a new
.Vt RSA_METHOD
structure.
It should be given a unique
.Fa name
and a set of
.Fa flags .
The
.Fa name
should be a NULL terminated string, which will be duplicated and stored
in the
.Vt RSA_METHOD
object.
It is the callers responsibility to free the original string.
The flags will be used during the construction of a new
.Sy RSA
object based on this
.Vt RSA_METHOD .
Any new
.Sy RSA
object will have those flags set by default.
.Pp
.Fn RSA_meth_dup
creates a duplicate copy of the
.Vt RSA_METHOD
object passed as a parameter.
This might be useful for creating a new
.Vt RSA_METHOD
based on an existing one, but with some differences.
.Pp
.Fn RSA_meth_free
destroys an
.Vt RSA_METHOD
structure and frees up any memory associated with it.
If the argument is NULL, nothing is done.
.Pp
.Fn RSA_meth_get0_name
will return a pointer to the name of this RSA_METHOD. This is a pointer
to the internal name string and so should not be freed by the caller.
.Fn RSA_meth_set1_name
sets the name of the RSA_METHOD to
.Fa name .
The string is duplicated and the copy is stored in the RSA_METHOD
structure, so the caller remains responsible for freeing the memory
associated with the name.
.Pp
.Fn RSA_meth_get_flags
returns the current value of the flags associated with this RSA_METHOD.
.Fn RSA_meth_set_flags
provides the ability to set these flags.
.Pp
The functions
.Fn RSA_meth_get0_app_data
and
.Fn RSA_meth_set0_app_data
provide the ability to associate implementation specific data with the
RSA_METHOD. It is the application's responsibility to free this data
before the RSA_METHOD is freed via a call to
.Fn RSA_meth_free .
.Pp
.Xr RSA_meth_get_sign 3
and
.Xr RSA_meth_set_sign 3
get and set the function used for creating an RSA signature
respectively.
This function will be called in response to the application calling
.Xr RSA_sign 3 .
The parameters for the function have the same meaning as for
.Xr RSA_sign 3 .
.Pp
.Xr RSA_meth_get_verify 3
and
.Xr RSA_meth_set_verify 3
get and set the function used for verifying an RSA signature
respectively.
This function will be called in response to the application calling
.Xr RSA_verify 3 .
The parameters for the function have the same meaning as for
.Xr RSA_verify 3 .
.Pp
.Xr RSA_meth_get_mod_exp 3
and
.Xr RSA_meth_set_mod_exp 3
get and set the function used for CRT computations.
.Pp
.Xr RSA_meth_get_bn_mod_exp 3
and
.Xr RSA_meth_set_bn_mod_exp 3
get and set the function used for CRT computations, specifically the
following value:
.Bd -literal
 r = a ^ p mod m
.Ed
.Pp
Both the
.Xr mod_exp 3
and
.Xr bn_mod_exp 3
functions are called by the default OpenSSL method during encryption,
decryption, signing and verification.
.Pp
.Xr RSA_meth_get_init 3
and
.Xr RSA_meth_set_init 3
get and set the function used for creating a new RSA instance
respectively.
This function will be called in response to the application calling
.Xr RSA_new 3
(if the current default RSA_METHOD is this one) or
.Xr RSA_new_method 3 .
The
.Xr RSA_new 3
and
.Xr RSA_new_method 3
functions will allocate the memory for the new RSA object, and a pointer
to this newly allocated structure will be passed as a parameter to the
function.
This function may be NULL.
.Pp
.Xr RSA_meth_get_finish 3
and
.Fn RSA_meth_set_finish
get and set the function used for destroying an instance of an RSA
object respectively.
This function will be called in response to the application calling
.Xr RSA_free 3 .
A pointer to the RSA to be destroyed is passed as a parameter.
The destroy function should be used for RSA implementation specific
clean up.
The memory for the RSA itself should not be freed by this function.
This function may be NULL.
.Pp
.Xr RSA_meth_get_keygen 3
and
.Xr RSA_meth_set_keygen 3
get and set the function used for generating a new RSA key pair
respectively.
This function will be called in response to the application calling
.Xr RSA_generate_key_ex 3 .
The parameter for the function has the same meaning as for
.Xr RSA_generate_key_ex 3 .
.Pp
.Xr RSA_meth_get_multi_prime_keygen 3
and
.Fn RSA_meth_set_multi_prime_keygen
get and set the function used for generating a new multi-prime RSA key
pair respectively.
This function will be called in response to the application calling
.Xr RSA_generate_multi_prime_key 3 .
The parameter for the function has the same meaning as for
.Xr RSA_generate_multi_prime_key 3 .
.Pp
.Xr RSA_meth_get_pub_enc 3 ,
.Xr RSA_meth_set_pub_enc 3 ,
.Xr RSA_meth_get_pub_dec 3 ,
.Xr RSA_meth_set_pub_dec 3 ,
.Xr RSA_meth_get_priv_enc 3 ,
.Xr RSA_meth_set_priv_enc 3 ,
.Xr RSA_meth_get_priv_dec 3 ,
.Xr RSA_meth_set_priv_dec 3
get and set the functions used for public and private key encryption and
decryption.
These functions will be called in response to the application calling
.Xr RSA_public_encrypt 3 ,
.Xr RSA_private_decrypt 3 ,
.Xr RSA_private_encrypt 3
and
.Xr RSA_public_decrypt 3
and take the same parameters as those.
.Sh RETURN VALUES
.Fn RSA_meth_new
and
.Fn RSA_meth_dup
return the newly allocated RSA_METHOD object or NULL on failure.
.Pp
.Fn RSA_meth_get0_name
and
.Fn RSA_meth_get_flags
return the name and flags associated with the RSA_METHOD respectively.
.Pp
All other
.Xr RSA_meth_get_* 3
functions return the appropriate function pointer that has been set in
the RSA_METHOD, or NULL if no such pointer has yet been set.
.Pp
RSA_meth_set1_name and all
.Xr RSA_meth_set_* 3
functions return 1 on success or 0 on failure.
.Sh SEE ALSO
.Xr RSA_new 3 ,
.Xr RSA_generate_key_ex 3 ,
.Xr RSA_sign 3 ,
.Xr RSA_set_method 3 ,
.Xr RSA_size 3 ,
.Xr RSA_get0_key 3 ,
.Xr RSA_generate_multi_prime_key 3
.Sh HISTORY
All of these functions were deprecated in OpenSSL 3.0.
.Pp
.Xr RSA_meth_get_multi_prime_keygen 3
and
.Fn RSA_meth_set_multi_prime_keygen
were added in OpenSSL 1.1.1.
.Pp
Other functions described here were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
