.Dd 2025-09-30
.Dt SHA256_INIT 3ossl
.Os
.Sh NAME
.Nm SHA1 ,
.Nm SHA1_Init ,
.Nm SHA1_Update ,
.Nm SHA1_Final ,
.Nm SHA224 ,
.Nm SHA224_Init ,
.Nm SHA224_Update ,
.Nm SHA224_Final ,
.Nm SHA256 ,
.Nm SHA256_Init ,
.Nm SHA256_Update ,
.Nm SHA256_Final ,
.Nm SHA384 ,
.Nm SHA384_Init ,
.Nm SHA384_Update ,
.Nm SHA384_Final ,
.Nm SHA512 ,
.Nm SHA512_Init ,
.Nm SHA512_Update ,
.Nm SHA512_Final
.Nd Secure Hash Algorithm
.Sh SYNOPSIS
.In openssl/sha.h
.Ft unsigned char *
.Fo SHA1
.Fa "const unsigned char *data"
.Fa "size_t count"
.Fa "unsigned char *md_buf"
.Fc
.Ft unsigned char *
.Fo SHA224
.Fa "const unsigned char *data"
.Fa "size_t count"
.Fa "unsigned char *md_buf"
.Fc
.Ft unsigned char *
.Fo SHA256
.Fa "const unsigned char *data"
.Fa "size_t count"
.Fa "unsigned char *md_buf"
.Fc
.Ft unsigned char *
.Fo SHA384
.Fa "const unsigned char *data"
.Fa "size_t count"
.Fa "unsigned char *md_buf"
.Fc
.Ft unsigned char *
.Fo SHA512
.Fa "const unsigned char *data"
.Fa "size_t count"
.Fa "unsigned char *md_buf"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo SHA1_Init
.Fa "SHA_CTX *c"
.Fc
.Ft int
.Fo SHA1_Update
.Fa "SHA_CTX *c"
.Fa "const void *data"
.Fa "size_t len"
.Fc
.Ft int
.Fo SHA1_Final
.Fa "unsigned char *md"
.Fa "SHA_CTX *c"
.Fc
.Ft int
.Fo SHA224_Init
.Fa "SHA256_CTX *c"
.Fc
.Ft int
.Fo SHA224_Update
.Fa "SHA256_CTX *c"
.Fa "const void *data"
.Fa "size_t len"
.Fc
.Ft int
.Fo SHA224_Final
.Fa "unsigned char *md"
.Fa "SHA256_CTX *c"
.Fc
.Ft int
.Fo SHA256_Init
.Fa "SHA256_CTX *c"
.Fc
.Ft int
.Fo SHA256_Update
.Fa "SHA256_CTX *c"
.Fa "const void *data"
.Fa "size_t len"
.Fc
.Ft int
.Fo SHA256_Final
.Fa "unsigned char *md"
.Fa "SHA256_CTX *c"
.Fc
.Ft int
.Fo SHA384_Init
.Fa "SHA512_CTX *c"
.Fc
.Ft int
.Fo SHA384_Update
.Fa "SHA512_CTX *c"
.Fa "const void *data"
.Fa "size_t len"
.Fc
.Ft int
.Fo SHA384_Final
.Fa "unsigned char *md"
.Fa "SHA512_CTX *c"
.Fc
.Ft int
.Fo SHA512_Init
.Fa "SHA512_CTX *c"
.Fc
.Ft int
.Fo SHA512_Update
.Fa "SHA512_CTX *c"
.Fa "const void *data"
.Fa "size_t len"
.Fc
.Ft int
.Fo SHA512_Final
.Fa "unsigned char *md"
.Fa "SHA512_CTX *c"
.Fc
.Sh DESCRIPTION
All of the functions described on this page except for
.Fn SHA1 ,
.Fn SHA224 ,
.Fn SHA256 ,
.Fn SHA384
and
.Fn SHA512
are deprecated.
Applications should instead use
.Xr EVP_DigestInit_ex 3 ,
.Xr EVP_DigestUpdate 3
and
.Xr EVP_DigestFinal_ex 3 ,
or the quick one-shot function
.Xr EVP_Q_digest 3 .
.Fn SHA1 ,
.Fn SHA224 ,
.Fn SHA256 ,
.Fn SHA384 ,
and
.Fn SHA256
can continue to be used.
They can also be replaced by, e.g.,
.Bd -literal
    (EVP_Q_digest(d, n, md, NULL, NULL, "SHA256", NULL) ? md : NULL)
.Ed
.Pp
SHA-1 (Secure Hash Algorithm) is a cryptographic hash function with a
160 bit output.
.Pp
.Fn SHA1
computes the SHA-1 message digest of the
.Sy n
bytes at
.Sy d
and places it in
.Fa md
(which must have space for SHA_DIGEST_LENGTH == 20 bytes of output).
If
.Fa md
is NULL, the digest is placed in a static array.
Note: setting
.Fa md
to NULL is
.Sy not thread safe .
.Pp
The following functions may be used if the message is not completely
stored in memory:
.Pp
.Fn SHA1_Init
initializes a
.Vt SHA_CTX
structure.
.Pp
.Fn SHA1_Update
can be called repeatedly with chunks of the message to be hashed
.Pf ( Fa len
bytes at
.Fa data Ns ).
.Pp
.Fn SHA1_Final
places the message digest in
.Fa md ,
which must have space for SHA_DIGEST_LENGTH == 20 bytes of output, and
erases the
.Vt SHA_CTX .
.Pp
The SHA224, SHA256, SHA384 and SHA512 families of functions operate in
the same way as for the SHA1 functions.
Note that SHA224 and SHA256 use a
.Vt SHA256_CTX
object instead of
.Vt SHA_CTX .
SHA384 and SHA512 use
.Vt SHA512_CTX .
The buffer
.Fa md
must have space for the output from the SHA variant being used (defined
by SHA224_DIGEST_LENGTH, SHA256_DIGEST_LENGTH, SHA384_DIGEST_LENGTH and
SHA512_DIGEST_LENGTH). Also note that, as for the
.Fn SHA1
function above, the
.Fn SHA224 ,
.Fn SHA256 ,
.Fn SHA384
and
.Fn SHA512
functions are not thread safe if
.Fa md
is NULL.
.Sh RETURN VALUES
.Fn SHA1 ,
.Fn SHA224 ,
.Fn SHA256 ,
.Fn SHA384
and
.Fn SHA512
return a pointer to the hash value.
.Pp
.Fn SHA1_Init ,
.Fn SHA1_Update
and
.Fn SHA1_Final
and equivalent SHA224, SHA256, SHA384 and SHA512 functions return 1 for
success, 0 otherwise.
.Sh CONFORMING TO
US Federal Information Processing Standard FIPS PUB 180-4 (Secure Hash
Standard), ANSI X9.30
.Sh SEE ALSO
.Xr EVP_Q_digest 3 ,
.Xr EVP_DigestInit 3
.Sh HISTORY
All of these functions except
.Xr SHA* 3
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
