.Dd 2025-09-30
.Dt SMIME_WRITE_CMS 3ossl
.Os
.Sh NAME
.Nm SMIME_write_CMS
.Nd convert CMS structure to S/MIME format
.Sh SYNOPSIS
.In openssl/cms.h
.Ft int
.Fo SMIME_write_CMS
.Fa "BIO *out"
.Fa "CMS_ContentInfo *cms"
.Fa "BIO *data"
.Fa "int flags"
.Fc
.Sh DESCRIPTION
.Fn SMIME_write_CMS
adds the appropriate MIME headers to a CMS structure to produce an
S/MIME message.
.Pp
.Fa out
is the BIO to write the data to.
.Fa cms
is the appropriate
.Vt CMS_ContentInfo
structure.
If streaming is enabled then the content must be supplied in the
.Fa data
argument.
.Fa flags
is an optional set of flags.
.Sh NOTES
The following flags can be passed in the
.Fa flags
parameter.
.Pp
If
.Sy CMS_DETACHED
is set then cleartext signing will be used, this option only makes sense
for SignedData where
.Sy CMS_DETACHED
is also set when
.Xr CMS_sign 3
is called.
.Pp
If the
.Sy CMS_TEXT
flag is set MIME headers for type
.Sy text/plain
are added to the content, this only makes sense if
.Sy CMS_DETACHED
is also set.
.Pp
If the
.Sy CMS_STREAM
flag is set streaming is performed.
This flag should only be set if
.Sy CMS_STREAM
was also set in the previous call to a CMS_ContentInfo creation
function.
.Pp
If cleartext signing is being used and
.Sy CMS_STREAM
not set then the data must be read twice: once to compute the signature
in
.Xr CMS_sign 3
and once to output the S/MIME message.
.Pp
If streaming is performed the content is output in BER format using
indefinite length constructed encoding except in the case of signed data
with detached content where the content is absent and DER format is
used.
.Sh BUGS
.Fn SMIME_write_CMS
always base64 encodes CMS structures, there should be an option to
disable this.
.Sh RETURN VALUES
.Fn SMIME_write_CMS
returns 1 for success or 0 for failure.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr CMS_sign 3 ,
.Xr CMS_verify 3 ,
.Xr CMS_encrypt 3
.Xr CMS_decrypt 3
.Sh COPYRIGHT
Copyright 2008-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
