.Dd 2025-09-30
.Dt SMIME_READ_ASN1 3ossl
.Os
.Sh NAME
.Nm SMIME_read_ASN1_ex ,
.Nm SMIME_read_ASN1
.Nd parse S/MIME message
.Sh SYNOPSIS
.In openssl/asn1.h
.Ft ASN1_VALUE *
.Fo SMIME_read_ASN1_ex
.Fa "BIO *in"
.Fa "int flags"
.Fa "BIO **bcont"
.Fa "const ASN1_ITEM *it"
.Fa "ASN1_VALUE **x"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft ASN1_VALUE *
.Fo SMIME_read_ASN1
.Fa "BIO *in"
.Fa "BIO **bcont"
.Fa "const ASN1_ITEM *it"
.Fc
.Sh DESCRIPTION
.Fn SMIME_read_ASN1_ex
parses a message in S/MIME format.
.Pp
.Fa in
is a BIO to read the message from.
If the
.Fa flags
argument contains
.Sy CMS_BINARY
then the input is assumed to be in binary format and is not translated
to canonical form.
If in addition
.Sy SMIME_ASCIICRLF
is set then the binary input is assumed to be followed by
.Sy CR
and
.Sy LF
characters, else only by an
.Sy LF
character.
.Fa x
can be used to optionally supply a previously created
.Fa it
ASN1_VALUE object (such as CMS_ContentInfo or PKCS7), it can be set to
NULL. Valid values that can be used by ASN.1 structure
.Fa it
are ASN1_ITEM_rptr(PKCS7) or ASN1_ITEM_rptr(CMS_ContentInfo).
Any algorithm fetches that occur during the operation will use the
.Vt OSSL_LIB_CTX
supplied in the
.Fa libctx
parameter, and use the property query string
.Fa propq
See
.Xr crypto 7
for further details about algorithm fetching.
.Pp
If cleartext signing is used then the content is saved in a memory bio
which is written to
.Em *bcont ,
otherwise
.Em *bcont
is set to NULL.
.Pp
The parsed ASN1_VALUE structure is returned or NULL if an error
occurred.
.Pp
.Fn SMIME_read_ASN1
is similar to
.Fn SMIME_read_ASN1_ex
but sets the value of
.Fa x
to NULL and the value of
.Fa flags
to 0.
.Sh NOTES
The higher level functions
.Xr SMIME_read_CMS_ex 3
and
.Xr SMIME_read_PKCS7_ex 3
should be used instead of
.Fn SMIME_read_ASN1_ex .
.Pp
To support future functionality if
.Fa bcont
is not NULL
.Em *bcont
should be initialized to NULL.
.Sh BUGS
The MIME parser used by
.Fn SMIME_read_ASN1_ex
is somewhat primitive.
While it will handle most S/MIME messages more complex compound formats
may not work.
.Pp
The use of a memory BIO to hold the signed content limits the size of
message which can be processed due to memory restraints: a streaming
single pass option should be available.
.Sh RETURN VALUES
.Fn SMIME_read_ASN1_ex
and
.Fn SMIME_read_ASN1
return a valid
.Vt ASN1_VALUE
structure or
.Dv NULL
if an error occurred.
The error can be obtained from ERR_get_error(3).
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr SMIME_read_CMS_ex 3 ,
.Xr SMIME_read_PKCS7_ex 3 ,
.Xr SMIME_write_ASN1 3 ,
.Xr SMIME_write_ASN1_ex 3
.Sh HISTORY
The function
.Fn SMIME_read_ASN1_ex
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
