.Dd 2025-09-30
.Dt SRP_CREATE_VERIFIER 3ossl
.Os
.Sh NAME
.Nm SRP_create_verifier_ex ,
.Nm SRP_create_verifier ,
.Nm SRP_create_verifier_BN_ex ,
.Nm SRP_create_verifier_BN ,
.Nm SRP_check_known_gN_param ,
.Nm SRP_get_default_gN
.Nd SRP authentication primitives
.Sh SYNOPSIS
.In openssl/srp.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo SRP_create_verifier_BN_ex
.Fa "const char *user"
.Fa "const char *pass"
.Fa "BIGNUM **salt"
.Fa "BIGNUM **verifier"
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *g"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft char *
.Fo SRP_create_verifier_BN
.Fa "const char *user"
.Fa "const char *pass"
.Fa "BIGNUM **salt"
.Fa "BIGNUM **verifier"
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *g"
.Fc
.Ft char *
.Fo SRP_create_verifier_ex
.Fa "const char *user"
.Fa "const char *pass"
.Fa "char **salt"
.Fa "char **verifier"
.Fa "const char *N"
.Fa "const char *g"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft char *
.Fo SRP_create_verifier
.Fa "const char *user"
.Fa "const char *pass"
.Fa "char **salt"
.Fa "char **verifier"
.Fa "const char *N"
.Fa "const char *g"
.Fc
.Ft char *
.Fo SRP_check_known_gN_param
.Fa "const BIGNUM *g"
.Fa "const BIGNUM *N"
.Fc
.Ft SRP_gN *
.Fo SRP_get_default_gN
.Fa "const char *id"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
There are no available replacement functions at this time.
.Pp
The
.Fn SRP_create_verifier_BN_ex
function creates an SRP password verifier from the supplied parameters
as defined in section 2.4 of RFC 5054 using the library context
.Fa libctx
and property query string
.Fa propq .
Any cryptographic algorithms that need to be fetched will use the
.Fa libctx
and
.Fa propq .
See
.Xr crypto 7 .
.Pp
.Fn SRP_create_verifier_BN
is the same as
.Fn SRP_create_verifier_BN_ex
except the default library context and property query string is used.
.Pp
On successful exit
.Em *verifier
will point to a newly allocated BIGNUM containing the verifier and (if a
salt was not provided)
.Em *salt
will be populated with a newly allocated BIGNUM containing a random
salt.
If
.Em *salt
is not NULL then the provided salt is used instead.
The caller is responsible for freeing the allocated
.Em *salt
and
.Em *verifier
BIGNUMS (use
.Xr BN_free 3 Ns ).
.Pp
The
.Fn SRP_create_verifier
function is similar to
.Fn SRP_create_verifier_BN
but all numeric parameters are in a non-standard base64 encoding
originally designed for compatibility with libsrp.
This is mainly present for historical compatibility and its use is
discouraged.
It is possible to pass NULL as
.Fa N
and an SRP group id as
.Fa g
instead to load the appropriate gN values (see
.Fn SRP_get_default_gN ) .
If both
.Fa N
and
.Fa g
are NULL the 8192-bit SRP group parameters are used.
The caller is responsible for freeing the allocated
.Em *salt
and
.Em *verifier
(use
.Xr OPENSSL_free 3 Ns ).
.Pp
The
.Fn SRP_check_known_gN_param
function checks that
.Fa g
and
.Fa N
are valid SRP group parameters from RFC 5054 appendix A.
.Pp
The
.Fn SRP_get_default_gN
function returns the gN parameters for the RFC 5054
.Fa id
SRP group size.
The known ids are "1024", "1536", "2048", "3072", "4096", "6144" and
"8192".
.Sh RETURN VALUES
.Fn SRP_create_verifier_BN_ex
and
.Fn SRP_create_verifier_BN
return 1 on success and 0 on failure.
.Pp
.Fn SRP_create_verifier_ex
and
.Fn SRP_create_verifier
return NULL on failure and a non-NULL value on success: "*" if
.Fa N
is not NULL, the selected group id otherwise.
This value should not be freed.
.Pp
.Fn SRP_check_known_gN_param
returns the text representation of the group id (i.e.
the prime bit size) or NULL if the arguments are not valid SRP group
parameters.
This value should not be freed.
.Pp
.Fn SRP_get_default_gN
returns NULL if
.Fa id
is not a valid group size, or the 8192-bit group parameters if
.Fa id
is NULL.
.Sh EXAMPLES
Generate and store a 8192 bit password verifier (error handling omitted
for clarity):
.Bd -literal
 #include <openssl/bn.h>
 #include <openssl/srp.h>

 const char *username = "username";
 const char *password = "password";

 SRP_VBASE *srpData = SRP_VBASE_new(NULL);

 SRP_gN *gN = SRP_get_default_gN("8192");

 BIGNUM *salt = NULL, *verifier = NULL;
 SRP_create_verifier_BN_ex(username, password, &salt, &verifier, gN->N, gN->g,
                           NULL, NULL);

 SRP_user_pwd *pwd = SRP_user_pwd_new();
 SRP_user_pwd_set1_ids(pwd, username, NULL);
 SRP_user_pwd_set0_sv(pwd, salt, verifier);
 SRP_user_pwd_set_gN(pwd, gN->g, gN->N);

 SRP_VBASE_add0_user(srpData, pwd);
.Ed
.Sh SEE ALSO
.Xr openssl-srp 1 ,
.Xr SRP_VBASE_new 3 ,
.Xr SRP_user_pwd_new 3
.Sh HISTORY
.Fn SRP_create_verifier_BN_ex
and
.Fn SRP_create_verifier_ex
were introduced in OpenSSL 3.0. All other functions were added in
OpenSSL 1.0.1.
.Pp
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2018-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
