.Dd 2025-09-30
.Dt SRP_CALC_B 3ossl
.Os
.Sh NAME
.Nm SRP_Calc_server_key ,
.Nm SRP_Calc_A ,
.Nm SRP_Calc_B_ex ,
.Nm SRP_Calc_B ,
.Nm SRP_Calc_u_ex ,
.Nm SRP_Calc_u ,
.Nm SRP_Calc_x_ex ,
.Nm SRP_Calc_x ,
.Nm SRP_Calc_client_key_ex ,
.Nm SRP_Calc_client_key
.Nd SRP authentication primitives
.Sh SYNOPSIS
.In openssl/srp.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft /* server side .... */
 BIGNUM *
.Fo SRP_Calc_server_key
.Fa "const BIGNUM *A"
.Fa "const BIGNUM *v"
.Fa "const BIGNUM *u"
.Fa "const BIGNUM *b"
.Fa "const BIGNUM *N"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_B_ex
.Fa "const BIGNUM *b"
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *g"
.Fa "const BIGNUM *v"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_B
.Fa "const BIGNUM *b"
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *g"
.Fa "const BIGNUM *v"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_u_ex
.Fa "const BIGNUM *A"
.Fa "const BIGNUM *B"
.Fa "const BIGNUM *N"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_u
.Fa "const BIGNUM *A"
.Fa "const BIGNUM *B"
.Fa "const BIGNUM *N"
.Fc
.Ft /* client side .... */
 BIGNUM *
.Fo SRP_Calc_client_key_ex
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *B"
.Fa "const BIGNUM *g"
.Fa "const BIGNUM *x"
.Fa "const BIGNUM *a"
.Fa "const BIGNUM *u"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_client_key
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *B"
.Fa "const BIGNUM *g"
.Fa "const BIGNUM *x"
.Fa "const BIGNUM *a"
.Fa "const BIGNUM *u"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_x_ex
.Fa "const BIGNUM *s"
.Fa "const char *user"
.Fa "const char *pass"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_x
.Fa "const BIGNUM *s"
.Fa "const char *user"
.Fa "const char *pass"
.Fc
.Ft BIGNUM *
.Fo SRP_Calc_A
.Fa "const BIGNUM *a"
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *g"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
There are no available replacement functions at this time.
.Pp
The SRP functions described on this page are used to calculate various
parameters and keys used by SRP as defined in RFC2945. The server key
and
.Fa B
and
.Fa u
parameters are used on the server side and are calculated via
.Fn SRP_Calc_server_key ,
.Fn SRP_Calc_B_ex ,
.Fn SRP_Calc_B ,
.Fn SRP_Calc_u_ex
and
.Fn SRP_Calc_u .
The client key and
.Fa x
and
.Fa A
parameters are used on the client side and are calculated via the
functions
.Fn SRP_Calc_client_key_ex ,
.Fn SRP_Calc_client_key ,
.Fn SRP_Calc_x_ex ,
.Fn SRP_Calc_x
and
.Fn SRP_Calc_A .
See RFC2945 for a detailed description of their usage and the meaning of
the various BIGNUM parameters to these functions.
.Pp
Most of these functions come in two forms.
Those that take a
.Fa libctx
and
.Fa propq
parameter, and those that don't.
Any cryptogrpahic functions that are fetched and used during the
calculation use the provided
.Fa libctx
and
.Fa propq .
See
.Xr crypto 7
for more details.
The variants that do not take a
.Fa libctx
and
.Fa propq
parameter use the default library context and property query string.
The
.Fn SRP_Calc_server_key
and
.Fn SRP_Calc_A
functions do not have a form that takes
.Fa libctx
or
.Fa propq
parameters because they do not need to fetch any cryptographic
algorithms.
.Sh RETURN VALUES
All these functions return the calculated key or parameter, or NULL on
error.
.Sh SEE ALSO
.Xr openssl-srp 1 ,
.Xr SRP_VBASE_new 3 ,
.Xr SRP_user_pwd_new 3
.Sh HISTORY
SRP_Calc_B_ex, SRP_Calc_u_ex, SRP_Calc_client_key_ex and SRP_Calc_x_ex
were introduced in OpenSSL 3.0.
.Pp
All of the other functions were added in OpenSSL 1.0.1.
.Pp
All of these functions were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
