.Dd 2025-09-30
.Dt SSL_SESSION_GET0_HOSTNAME 3ossl
.Os
.Sh NAME
.Nm SSL_SESSION_get0_hostname ,
.Nm SSL_SESSION_set1_hostname ,
.Nm SSL_SESSION_get0_alpn_selected ,
.Nm SSL_SESSION_set1_alpn_selected
.Nd get and set SNI and ALPN data associated with a session
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const char *
.Fo SSL_SESSION_get0_hostname
.Fa "const SSL_SESSION *s"
.Fc
.Ft int
.Fo SSL_SESSION_set1_hostname
.Fa "SSL_SESSION *s"
.Fa "const char *hostname"
.Fc
.Ft void
.Fo SSL_SESSION_get0_alpn_selected
.Fa "const SSL_SESSION *s"
.Fa "const unsigned char **alpn"
.Fa "size_t *len"
.Fc
.Ft int
.Fo SSL_SESSION_set1_alpn_selected
.Fa "SSL_SESSION *s"
.Fa "const unsigned char *alpn"
.Fa "size_t len"
.Fc
.Sh DESCRIPTION
.Fn SSL_SESSION_get0_hostname
retrieves the Server Name Indication (SNI) value that was sent by the
client when the session was created if the server acknowledged the
client's SNI extension by including an empty SNI extension in response.
Otherwise NULL is returned.
.Pp
The value returned is a pointer to memory maintained within
.Fa s
and should not be free'd.
.Pp
.Fn SSL_SESSION_set1_hostname
sets the SNI value for the hostname to a copy of the string provided in
hostname.
.Pp
.Fn SSL_SESSION_get0_alpn_selected
retrieves the selected ALPN protocol for this session and its associated
length in bytes.
The returned value of
.Sy *alpn
is a pointer to memory maintained within
.Fa s
and should not be free'd.
.Pp
.Fn SSL_SESSION_set1_alpn_selected
sets the ALPN protocol for this session to the value in
.Fa alpn
which should be of length
.Fa len
bytes.
A copy of the input value is made, and the caller retains ownership of
the memory pointed to by
.Fa alpn .
.Sh RETURN VALUES
.Fn SSL_SESSION_get0_hostname
returns the SNI string if available, or NULL if not.
.Pp
.Fn SSL_SESSION_set1_hostname
returns 1 on success or 0 on error.
.Pp
.Fn SSL_SESSION_set1_alpn_selected
returns 1 on success or 0 on error.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr d2i_SSL_SESSION 3 ,
.Xr SSL_SESSION_get_time 3 ,
.Xr SSL_SESSION_free 3
.Sh HISTORY
The
.Fn SSL_SESSION_set1_hostname ,
.Fn SSL_SESSION_get0_alpn_selected
and
.Fn SSL_SESSION_set1_alpn_selected
functions were added in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2016-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
