.Dd 2025-09-30
.Dt SSL_GET_EXTMS_SUPPORT 3ossl
.Os
.Sh NAME
.Nm SSL_get_extms_support
.Nd extended master secret support
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_get_extms_support
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_get_extms_support
indicates whether the current session used extended master secret.
.Pp
This function is implemented as a macro.
.Sh RETURN VALUES
.Fn SSL_get_extms_support
returns 1 if the current session used extended master secret, 0 if it
did not and -1 if a handshake is currently in progress i.e.
it is not possible to determine if extended master secret was used.
.Sh SEE ALSO
.Xr ssl 7
.Sh COPYRIGHT
Copyright 2015-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
