.Dd 2025-09-30
.Dt SSL_CTX_HAS_CLIENT_CUSTOM_EXT 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_has_client_custom_ext
.Nd check whether a handler exists for a particular client extension type
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_has_client_custom_ext
.Fa "const SSL_CTX *ctx"
.Fa "unsigned int ext_type"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_has_client_custom_ext
checks whether a handler has been set for a client extension of type
.Fa ext_type
using
.Xr SSL_CTX_add_client_custom_ext 3 .
.Sh RETURN VALUES
Returns 1 if a handler has been set, 0 otherwise.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_add_client_custom_ext 3
.Sh COPYRIGHT
Copyright 2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
