.Dd 2025-09-30
.Dt SSL_CTX_SET_MSG_CALLBACK 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_msg_callback ,
.Nm SSL_CTX_set_msg_callback_arg ,
.Nm SSL_set_msg_callback ,
.Nm SSL_set_msg_callback_arg ,
.Nm SSL_trace
.Nd install callback for observing protocol messages
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_CTX_set_msg_callback
.Fa "SSL_CTX *ctx"
.Fa "void (*cb)(int write_p"
.Fa "int version"
.Fa "int content_type"
.Fa "const void *buf"
.Fa "size_t len"
.Fa "SSL *ssl"
.Fa "void *arg)"
.Fc
.Ft void
.Fo SSL_CTX_set_msg_callback_arg
.Fa "SSL_CTX *ctx"
.Fa "void *arg"
.Fc
.Ft void
.Fo SSL_set_msg_callback
.Fa "SSL *ssl"
.Fa "void (*cb)(int write_p"
.Fa "int version"
.Fa "int content_type"
.Fa "const void *buf"
.Fa "size_t len"
.Fa "SSL *ssl"
.Fa "void *arg)"
.Fc
.Ft void
.Fo SSL_set_msg_callback_arg
.Fa "SSL *ssl"
.Fa "void *arg"
.Fc
.Ft void
.Fo SSL_trace
.Fa "int write_p"
.Fa "int version"
.Fa "int content_type"
.Fa "const void *buf"
.Fa "size_t len"
.Fa "SSL *ssl"
.Fa "void *arg"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set_msg_callback
or
.Fn SSL_set_msg_callback
can be used to define a message callback function
.Em cb
for observing all SSL/TLS/QUIC protocol messages (such as handshake
messages) that are received or sent, as well as other events that occur
during processing.
.Fn SSL_CTX_set_msg_callback_arg
and
.Fn SSL_set_msg_callback_arg
can be used to set argument
.Fa arg
to the callback function, which is available for arbitrary application
use.
.Pp
.Fn SSL_CTX_set_msg_callback
and
.Fn SSL_CTX_set_msg_callback_arg
specify default settings that will be copied to new
.Vt SSL
objects by
.Xr SSL_new 3 .
.Fn SSL_set_msg_callback
and
.Fn SSL_set_msg_callback_arg
modify the actual settings of an
.Vt SSL
object.
Using a
.Dv NULL
pointer for
.Em cb
disables the message callback.
.Pp
When
.Em cb
is called by the SSL/TLS/QUIC library the function arguments have the
following meaning:
.Bl -tag -width Ds
.It Fa write_p
This flag is
.Sy 0
when a protocol message has been received and
.Sy 1
when a protocol message has been sent.
.It Fa version
The protocol version according to which the protocol message is
interpreted by the library such as
.Sy TLS1_3_VERSION ,
.Sy TLS1_2_VERSION ,
.Sy OSSL_QUIC1_VERSION
etc.
For the SSL3_RT_HEADER pseudo content type (see NOTES below) this value
will be the decoded version/legacy_version field of the record header.
.It Fa content_type
This is one of the content type values defined in the protocol
specification
.Pf ( Sy SSL3_RT_CHANGE_CIPHER_SPEC ,
.Sy SSL3_RT_ALERT ,
.Sy SSL3_RT_HANDSHAKE ;
but never
.Sy SSL3_RT_APPLICATION_DATA
because the callback will only be called for protocol messages).
Alternatively it may be a "pseudo" content type.
These pseudo content types are used to signal some other event in the
processing of data (see NOTES below).
.It Fa buf Ns , Fa len
.Fa buf
points to a buffer containing the protocol message or other data (in the
case of pseudo content types), which consists of
.Fa len
bytes.
The buffer is no longer valid after the callback function has returned.
.It Fa ssl
The
.Vt SSL
object that received or sent the message.
.It Fa arg
The user-defined argument optionally defined by
.Fn SSL_CTX_set_msg_callback_arg
or
.Fn SSL_set_msg_callback_arg .
.El
.Pp
The
.Fn SSL_trace
function can be used as a pre-written callback in a call to
.Fn SSL_CTX_set_msg_callback
or
.Fn SSL_set_msg_callback .
It requires a BIO to be set as the callback argument via
.Fn SSL_CTX_set_msg_callback_arg
or
.Fn SSL_set_msg_callback_arg .
Setting this callback will cause human readable diagostic tracing
information about an SSL/TLS/QUIC connection to be written to the BIO.
.Sh NOTES
Protocol messages are passed to the callback function after decryption
and fragment collection where applicable.
(Thus record boundaries are not visible.)
.Pp
If processing a received protocol message results in an error, the
callback function may not be called.
For example, the callback function will never see messages that are
considered too large to be processed.
.Pp
Due to automatic protocol version negotiation,
.Fa version
is not necessarily the protocol version used by the sender of the
message: If a TLS 1.0 ClientHello message is received by an SSL 3.0-only
server,
.Fa version
will be
.Sy SSL3_VERSION .
.Pp
Pseudo content type values may be sent at various points during the
processing of data.
The following pseudo content types are currently defined:
.Bl -tag -width Ds
.It Sy SSL3_RT_HEADER
Used when a TLS record is sent or received.
The
.Fa buf
contains the record header bytes only.
.It Sy SSL3_RT_INNER_CONTENT_TYPE
Used when an encrypted TLSv1.3 record is sent or received.
In encrypted TLSv1.3 records the content type in the record header is
always SSL3_RT_APPLICATION_DATA. The real content type for the record is
contained in an "inner" content type.
.Fa buf
contains the encoded "inner" content type byte.
.It Sy SSL3_RT_QUIC_DATAGRAM
Used when a QUIC datagram is sent or received.
.It Sy SSL3_RT_QUIC_PACKET
Used when a QUIC packet is sent or received.
.It Sy SSL3_RT_QUIC_FRAME_FULL
Used when a QUIC frame is sent or received.
This is only used for non-crypto and stream data related frames.
The full QUIC frame data is supplied.
.It Sy SSL3_RT_QUIC_FRAME_HEADER
Used when a QUIC stream data or crypto frame is sent or received.
Only the QUIC frame header data is supplied.
.It Sy SSL3_RT_QUIC_FRAME_PADDING
Used when a sequence of one or more QUIC padding frames is sent or
received.
A padding frame consists of a single byte and it is common to have
multiple such frames in a sequence.
Rather than supplying each frame individually the callback will supply
all the padding frames in one go via this pseudo content type.
.El
.Sh RETURN VALUES
.Fn SSL_CTX_set_msg_callback ,
.Fn SSL_CTX_set_msg_callback_arg ,
.Fn SSL_set_msg_callback
and
.Fn SSL_set_msg_callback_arg
do not return values.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_new 3
.Sh HISTORY
The pseudo content type
.Sy SSL3_RT_INNER_CONTENT_TYPE
was added in OpenSSL 1.1.1.
.Pp
The pseudo content types
.Sy SSL3_RT_QUIC_DATAGRAM ,
.Sy SSL3_RT_QUIC_PACKET ,
.Sy SSL3_RT_QUIC_FRAME_FULL ,
.Sy SSL3_RT_QUIC_FRAME_HEADER
and
.Sy SSL3_RT_QUIC_FRAME_PADDING
were added in OpenSSL 3.2.
.Pp
In versions previous to OpenSSL 3.0
.Em cb
was called with 0 as
.Fa version
for the pseudo content type
.Sy SSL3_RT_HEADER
for TLS records.
.Pp
In versions previous to OpenSSL 3.2
.Em cb
was called with 0 as
.Fa version
for the pseudo content type
.Sy SSL3_RT_HEADER
for DTLS records.
.Sh COPYRIGHT
Copyright 2001-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
