.Dd 2025-09-30
.Dt SSL_STATE_STRING 3ossl
.Os
.Sh NAME
.Nm SSL_state_string ,
.Nm SSL_state_string_long
.Nd get textual description of state of an SSL object
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const char *
.Fo SSL_state_string
.Fa "const SSL *ssl"
.Fc
.Ft const char *
.Fo SSL_state_string_long
.Fa "const SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_state_string
returns an abbreviated string indicating the current state of the SSL
object
.Fa ssl .
The returned NUL-terminated string contains 6 or fewer characters.
.Pp
.Fn SSL_state_string_long
returns a descriptive string indicating the current state of the SSL
object
.Fa ssl .
.Sh NOTES
During its use, an SSL objects passes several states.
The state is internally maintained.
Querying the state information is not very informative before or when a
connection has been established.
It however can be of significant interest during the handshake.
.Pp
When using nonblocking sockets, the function call performing the
handshake may return with SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE
condition, so that
.Xr SSL_state_string[_long] 3
may be called.
.Pp
For both blocking or nonblocking sockets, the details state information
can be used within the info_callback function set with the
.Xr SSL_set_info_callback 3
call.
.Sh RETURN VALUES
Detailed description of possible states to be included later.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_info_callback 3
.Sh COPYRIGHT
Copyright 2001-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
