.Dd 2025-09-30
.Dt SSL_GET_VERSION 3ossl
.Os
.Sh NAME
.Nm SSL_client_version ,
.Nm SSL_get_version ,
.Nm SSL_is_dtls ,
.Nm SSL_is_tls ,
.Nm SSL_is_quic ,
.Nm SSL_version
.Nd get the protocol information of a connection
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_client_version
.Fa "const SSL *s"
.Fc
.Ft const char *
.Fo SSL_get_version
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_is_dtls
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_is_tls
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_is_quic
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_version
.Fa "const SSL *s"
.Fc
.Sh DESCRIPTION
For SSL, TLS and DTLS protocols
.Fn SSL_client_version
returns the numeric protocol version advertised by the client in the
legacy_version field of the ClientHello when initiating the connection.
Note that, for TLS, this value will never indicate a version greater
than TLSv1.2 even if TLSv1.3 is subsequently negotiated.
For QUIC connections it returns OSSL_QUIC1_VERSION.
.Pp
.Fn SSL_get_version
returns the name of the protocol used for the connection.
.Fn SSL_version
returns the numeric protocol version used for the connection.
They should only be called after the initial handshake has been
completed.
Prior to that the results returned from these functions may be
unreliable.
.Pp
.Fn SSL_is_dtls
returns 1 if the connection is using DTLS or 0 if not.
.Pp
.Fn SSL_is_tls
returns 1 if the connection is using SSL/TLS or 0 if not.
.Pp
.Fn SSL_is_quic
returns 1 if the connection is using QUIC or 0 if not.
.Sh RETURN VALUES
.Fn SSL_get_version
returns one of the following strings:
.Bl -tag -width Ds
.It SSLv3
The connection uses the SSLv3 protocol.
.It TLSv1
The connection uses the TLSv1.0 protocol.
.It TLSv1.1
The connection uses the TLSv1.1 protocol.
.It TLSv1.2
The connection uses the TLSv1.2 protocol.
.It TLSv1.3
The connection uses the TLSv1.3 protocol.
.It DTLSv0.9
The connection uses an obsolete pre-standardisation DTLS protocol
.It DTLSv1
The connection uses the DTLSv1 protocol
.It DTLSv1.2
The connection uses the DTLSv1.2 protocol
.It QUICv1
The connection uses the QUICv1 protocol.
.It unknown
This indicates an unknown protocol version.
.El
.Pp
.Fn SSL_version
and
.Fn SSL_client_version
return an integer which could include any of the following:
.Bl -tag -width Ds
.It SSL3_VERSION
The connection uses the SSLv3 protocol.
.It TLS1_VERSION
The connection uses the TLSv1.0 protocol.
.It TLS1_1_VERSION
The connection uses the TLSv1.1 protocol.
.It TLS1_2_VERSION
The connection uses the TLSv1.2 protocol.
.It TLS1_3_VERSION
The connection uses the TLSv1.3 protocol (never returned for
.Fn SSL_client_version ) .
.It DTLS1_BAD_VER
The connection uses an obsolete pre-standardisation DTLS protocol
.It DTLS1_VERSION
The connection uses the DTLSv1 protocol
.It DTLS1_2_VERSION
The connection uses the DTLSv1.2 protocol
.It OSSL_QUIC1_VERSION
The connection uses the QUICv1 protocol.
.El
.Sh SEE ALSO
.Xr ssl 7
.Sh HISTORY
The
.Fn SSL_is_dtls
function was added in OpenSSL 1.1.0. The
.Fn SSL_is_tls
and
.Fn SSL_is_quic
functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2001-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
