.Dd 2025-09-30
.Dt SSL_NEW_STREAM 3ossl
.Os
.Sh NAME
.Nm SSL_new_stream ,
.Nm SSL_STREAM_FLAG_UNI ,
.Nm SSL_STREAM_FLAG_NO_BLOCK ,
.Nm SSL_STREAM_FLAG_ADVANCE
.Nd create a new locally-initiated QUIC stream
.Sh SYNOPSIS
.In openssl/ssl.h
.Fd #define SSL_STREAM_FLAG_UNI          (1U << 0)
.Fd #define SSL_STREAM_FLAG_NO_BLOCK     (1U << 1)
.Fd #define SSL_STREAM_FLAG_ADVANCE      (1U << 2)
.Ft SSL *
.Fo SSL_new_stream
.Fa "SSL *ssl"
.Fa "uint64_t flags"
.Fc
.Sh DESCRIPTION
The
.Fn SSL_new_stream
function, when passed a QUIC connection SSL object, creates a new
locally-initiated bidirectional or unidirectional QUIC stream and
returns the newly created QUIC stream SSL object.
.Pp
If the
.Sy SSL_STREAM_FLAG_UNI
flag is passed, a unidirectional stream is created; else a bidirectional
stream is created.
.Pp
To retrieve the stream ID of the newly created stream, use
.Xr SSL_get_stream_id 3 .
.Pp
It is the caller's responsibility to free the QUIC stream SSL object
using
.Xr SSL_free 3 .
The lifetime of the QUIC connection SSL object must exceed that of the
QUIC stream SSL object; in other words, the QUIC stream SSL object must
be freed first.
.Pp
Once a stream has been created using
.Fn SSL_new_stream ,
it may be used in the normal way using
.Xr SSL_read 3
and
.Xr SSL_write 3 .
.Pp
This function can only be used to create stream objects for
locally-initiated streams.
To accept incoming streams initiated by a peer, use
.Xr SSL_accept_stream 3 .
.Pp
Calling
.Fn SSL_new_stream
if there is no default stream already present inhibits the future
creation of a default stream.
See
.Xr openssl-quic 7 .
.Pp
The creation of new streams is subject to flow control by the QUIC
protocol.
If it is currently not possible to create a new locally initiated stream
of the specified type, a call to
.Fn SSL_new_stream
will either block (if the connection is configured in blocking mode)
until a new stream can be created, or otherwise return NULL.
.Pp
This function operates in blocking mode if the QUIC connection SSL
object is configured in blocking mode (see
.Xr SSL_set_blocking_mode 3 Ns ).
It may also be used in nonblocking mode on a connection configured in
blocking mode by passing the flag
.Sy SSL_STREAM_FLAG_NO_BLOCK .
.Pp
The flag
.Sy SSL_STREAM_FLAG_ADVANCE
may be used to create a QUIC stream SSL object even if a new QUIC stream
cannot yet be opened due to flow control.
The caller may begin to use the new stream and fill the write buffer of
the stream by calling
.Xr SSL_write 3 .
However, no actual stream data (or QUIC frames regarding the stream)
will be sent until QUIC flow control allows it.
Any queued data will be sent as soon as a peer permits it.
There is no guarantee the stream will be eventually created; for
example, the connection could fail, or a peer might simply decide never
to increase the number of allowed streams for the remainder of the
connection lifetime.
.Sh RETURN VALUES
.Fn SSL_new_stream
returns a new stream object, or NULL on error.
.Pp
This function fails if called on a QUIC stream SSL object or on a
non-QUIC SSL object.
.Pp
.Fn SSL_new_stream
may also fail if the underlying connection has reached the maximum
stream count, based on the
.Sy max_streams_bidi
or
.Sy max_streams_uni
transport parameter values negotiated with the peer.
In this event the NULL return will be accompanied by an error on the
error stack (obtainable via
.Xr ERR_get_error 3 ) ,
which will contain a reason code of
.Sy SSL_R_STREAM_COUNT_LIMITED .
When this error is encountered, the operation may be retried.
It is recommended that, prior to retry, the error stack be cleared via a
call to
.Xr ERR_clear_error 3 ,
and that the TLS state machine be activated via a call to
.Xr SSL_handle_events 3
to process any potential updates from the server allowing additional
streams to be created.
.Sh SEE ALSO
.Xr SSL_accept_stream 3 ,
.Xr SSL_free 3
.Sh HISTORY
.Fn SSL_new_stream
was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2002-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
