.Dd 2025-09-30
.Dt SSL_CTX_ADD_EXTRA_CHAIN_CERT 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_add_extra_chain_cert ,
.Nm SSL_CTX_get_extra_chain_certs ,
.Nm SSL_CTX_get_extra_chain_certs_only ,
.Nm SSL_CTX_clear_extra_chain_certs
.Nd add, get or clear extra chain certificates
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft long
.Fo SSL_CTX_add_extra_chain_cert
.Fa "SSL_CTX *ctx"
.Fa "X509 *x509"
.Fc
.Ft long
.Fo SSL_CTX_get_extra_chain_certs
.Fa "SSL_CTX *ctx"
.Fa "STACK_OF(X509) **sk"
.Fc
.Ft long
.Fo SSL_CTX_get_extra_chain_certs_only
.Fa "SSL_CTX *ctx"
.Fa "STACK_OF(X509) **sk"
.Fc
.Ft long
.Fo SSL_CTX_clear_extra_chain_certs
.Fa "SSL_CTX *ctx"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_add_extra_chain_cert
adds the certificate
.Fa x509
to the extra chain certificates associated with
.Fa ctx .
Several certificates can be added one after another.
.Pp
.Fn SSL_CTX_get_extra_chain_certs
retrieves the extra chain certificates associated with
.Fa ctx ,
or the chain associated with the current certificate of
.Fa ctx
if the extra chain is empty.
The returned stack should not be freed by the caller.
.Pp
.Fn SSL_CTX_get_extra_chain_certs_only
retrieves the extra chain certificates associated with
.Fa ctx .
The returned stack should not be freed by the caller.
.Pp
.Fn SSL_CTX_clear_extra_chain_certs
clears all extra chain certificates associated with
.Fa ctx .
.Pp
These functions are implemented as macros.
.Sh NOTES
When sending a certificate chain, extra chain certificates are sent in
order following the end entity certificate.
.Pp
If no chain is specified, the library will try to complete the chain
from the available CA certificates in the trusted CA storage, see
.Xr SSL_CTX_load_verify_locations 3 .
.Pp
The
.Fa x509
certificate provided to
.Fn SSL_CTX_add_extra_chain_cert
will be freed by the library when the
.Vt SSL_CTX
is destroyed.
An application
.Sy should not
free the
.Fa x509
object.
.Sh RESTRICTIONS
Only one set of extra chain certificates can be specified per SSL_CTX
structure.
Different chains for different certificates (for example if both RSA and
DSA certificates are specified by the same server) or different SSL
structures with the same parent SSL_CTX cannot be specified using this
function.
For more flexibility functions such as
.Xr SSL_add1_chain_cert 3
should be used instead.
.Sh RETURN VALUES
.Fn SSL_CTX_add_extra_chain_cert
and
.Fn SSL_CTX_clear_extra_chain_certs
return 1 on success and 0 for failure.
Check out the error stack to find out the reason for failure.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_use_certificate 3 ,
.Xr SSL_CTX_set_client_cert_cb 3 ,
.Xr SSL_CTX_load_verify_locations 3
.Xr SSL_CTX_set0_chain 3
.Xr SSL_CTX_set1_chain 3
.Xr SSL_CTX_add0_chain_cert 3
.Xr SSL_CTX_add1_chain_cert 3
.Xr SSL_set0_chain 3
.Xr SSL_set1_chain 3
.Xr SSL_add0_chain_cert 3
.Xr SSL_add1_chain_cert 3
.Xr SSL_CTX_build_cert_chain 3
.Xr SSL_build_cert_chain 3
.Sh COPYRIGHT
Copyright 2000-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
