.Dd 2025-09-30
.Dt SSL_GET_PSK_IDENTITY 3ossl
.Os
.Sh NAME
.Nm SSL_get_psk_identity ,
.Nm SSL_get_psk_identity_hint
.Nd get PSK client identity and hint
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const char *
.Fo SSL_get_psk_identity_hint
.Fa "const SSL *ssl"
.Fc
.Ft const char *
.Fo SSL_get_psk_identity
.Fa "const SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_get_psk_identity_hint
is used to retrieve the PSK identity hint used during the connection
setup related to SSL object
.Fa ssl .
Similarly,
.Fn SSL_get_psk_identity
is used to retrieve the PSK identity used during the connection setup.
.Sh RETURN VALUES
If
.Pf non- Dv NULL ,
.Fn SSL_get_psk_identity_hint
returns the PSK identity hint and
.Fn SSL_get_psk_identity
returns the PSK identity.
Both are
.Dv NULL Ns -terminated.
.Fn SSL_get_psk_identity_hint
may return
.Dv NULL
if no PSK identity hint was used during the connection setup.
.Pp
Note that the return value is valid only during the lifetime of the SSL
object
.Fa ssl .
.Sh SEE ALSO
.Xr ssl 7
.Sh COPYRIGHT
Copyright 2006-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
