.Dd 2025-09-30
.Dt SSL_GET0_PEER_RPK 3ossl
.Os
.Sh NAME
.Nm SSL_add_expected_rpk ,
.Nm SSL_get_negotiated_client_cert_type ,
.Nm SSL_get_negotiated_server_cert_type ,
.Nm SSL_get0_peer_rpk ,
.Nm SSL_SESSION_get0_peer_rpk
.Nd raw public key (RFC7250) support
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_add_expected_rpk
.Fa "SSL *s"
.Fa "EVP_PKEY *rpk"
.Fc
.Ft int
.Fo SSL_get_negotiated_client_cert_type
.Fa "const SSL *s"
.Fc
.Ft int
.Fo SSL_get_negotiated_server_cert_type
.Fa "const SSL *s"
.Fc
.Ft EVP_PKEY *
.Fo SSL_get0_peer_rpk
.Fa "const SSL *s"
.Fc
.Ft EVP_PKEY *
.Fo SSL_SESSION_get0_peer_rpk
.Fa "const SSL_SESSION *ss"
.Fc
.Sh DESCRIPTION
.Fn SSL_add_expected_rpk
adds a DANE TLSA record matching public key
.Fa rpk
to SSL
.Fa s Ns 's
DANE validation policy.
.Pp
.Fn SSL_get_negotiated_client_cert_type
returns the connection's negotiated client certificate type.
.Pp
.Fn SSL_get_negotiated_server_cert_type
returns the connection's negotiated server certificate type.
.Pp
.Fn SSL_get0_peer_rpk
returns the peer's raw public key from SSL
.Fa s .
.Pp
.Fn SSL_SESSION_get0_peer_rpk
returns the peer's raw public key from SSL_SESSION
.Fa ss .
.Sh NOTES
Raw public keys are used in place of certificates when the option is
negotiated.
.Sy SSL_add_expected_rpk()
may be called multiple times to configure multiple trusted keys, this
makes it possible to allow for key rotation, where a peer might be
expected to offer an "old" or "new" key and the endpoint must be able to
accept either one.
.Pp
When raw public keys are used, the certificate verify callback is
called, and may be used to inspect the public key via
X509_STORE_CTX_get0_rpk(3). Raw public keys have no subject, issuer,
validity dates nor digital signature to verify.
They can, however, be matched verbatim or by their digest value, this is
done by specifying one or more TLSA records, see
.Xr SSL_CTX_dane_enable 3 .
.Pp
The raw public key is typically taken from the certificate assigned to
the connection (e.g.
via
.Xr SSL_use_certificate 3 Ns ),
but if a certificate is not configured, then the public key will be
extracted from the assigned private key.
.Pp
The
.Fn SSL_add_expected_rpk
function is a wrapper around
.Xr SSL_dane_tlsa_add 3 .
When DANE is enabled via
.Xr SSL_dane_enable 3 ,
the configured TLSA records will be used to validate the peer's public
key or certificate.
If DANE is not enabled, then no validation will occur.
.Sh RETURN VALUES
.Fn SSL_add_expected_rpk
returns 1 on success and 0 on failure.
.Pp
.Fn SSL_get0_peer_rpk
and
.Fn SSL_SESSION_get0_peer_rpk
return the peer's raw public key as an EVP_PKEY or NULL when the raw
public key is not available.
.Pp
.Fn SSL_get_negotiated_client_cert_type
and
.Fn SSL_get_negotiated_server_cert_type
return one of the following values:
.Bl -tag -width Ds
.It TLSEXT_cert_type_x509
.It TLSEXT_cert_type_rpk
.El
.Sh SEE ALSO
.Xr SSL_CTX_dane_enable 3 ,
.Xr SSL_CTX_set_options 3 ,
.Xr SSL_dane_enable 3 ,
.Xr SSL_get_verify_result 3 ,
.Xr SSL_set_verify 3 ,
.Xr SSL_use_certificate 3 ,
.Xr X509_STORE_CTX_get0_rpk 3
.Sh HISTORY
These functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2023 The OpenSSL Project Authors.
All Rights Reserved.
