.Dd 2025-09-30
.Dt SSL_CTX_SET_CIPHER_LIST 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_cipher_list ,
.Nm SSL_set_cipher_list ,
.Nm SSL_CTX_set_ciphersuites ,
.Nm SSL_set_ciphersuites ,
.Nm OSSL_default_cipher_list ,
.Nm OSSL_default_ciphersuites
.Nd choose list of available SSL_CIPHERs
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_set_cipher_list
.Fa "SSL_CTX *ctx"
.Fa "const char *str"
.Fc
.Ft int
.Fo SSL_set_cipher_list
.Fa "SSL *ssl"
.Fa "const char *str"
.Fc
.Ft int
.Fo SSL_CTX_set_ciphersuites
.Fa "SSL_CTX *ctx"
.Fa "const char *str"
.Fc
.Ft int
.Fo SSL_set_ciphersuites
.Fa "SSL *s"
.Fa "const char *str"
.Fc
.Ft const char *
.Fo OSSL_default_cipher_list
.Fa void
.Fc
.Ft const char *
.Fo OSSL_default_ciphersuites
.Fa void
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set_cipher_list
sets the list of available ciphers (TLSv1.2 and below) for
.Fa ctx
using the control string
.Fa str .
The format of the string is described in
.Xr openssl-ciphers 1 .
The list of ciphers is inherited by all
.Fa ssl
objects created from
.Fa ctx .
This function does not impact TLSv1.3 ciphersuites.
Use
.Fn SSL_CTX_set_ciphersuites
to configure those.
.Fa ctx
.Sy MUST NOT
be NULL.
.Pp
.Fn SSL_set_cipher_list
sets the list of ciphers (TLSv1.2 and below) only for
.Fa ssl .
.Pp
.Fn SSL_CTX_set_ciphersuites
is used to configure the available TLSv1.3 ciphersuites for
.Fa ctx .
This is a simple colon (":") separated list of TLSv1.3 ciphersuite names
in order of preference.
Valid TLSv1.3 ciphersuite names are:
.Bl -tag -width Ds
.It TLS_AES_128_GCM_SHA256
.It TLS_AES_256_GCM_SHA384
.It TLS_CHACHA20_POLY1305_SHA256
.It TLS_AES_128_CCM_SHA256
.It TLS_AES_128_CCM_8_SHA256
.It TLS_SHA384_SHA384 - integrity-only
.It TLS_SHA256_SHA256 - integrity-only
.El
An empty list is permissible.
The default value for this setting is:
.Pp
"TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"
.Pp
.Fn SSL_set_ciphersuites
is the same as
.Fn SSL_CTX_set_ciphersuites
except it configures the ciphersuites for
.Fa ssl .
.Pp
.Fn OSSL_default_cipher_list
returns the default cipher string for TLSv1.2 (and earlier) ciphers.
.Fn OSSL_default_ciphersuites
returns the default cipher string for TLSv1.3 ciphersuites.
.Sh NOTES
The control string
.Fa str
for
.Fn SSL_CTX_set_cipher_list ,
.Fn SSL_set_cipher_list ,
.Fn SSL_CTX_set_ciphersuites
and
.Fn SSL_set_ciphersuites
should be universally usable and not depend on details of the library
configuration (ciphers compiled in).
Thus no syntax checking takes place.
Items that are not recognized, because the corresponding ciphers are not
compiled in or because they are mistyped, are simply ignored.
Failure is only flagged if no ciphers could be collected at all.
.Pp
It should be noted, that inclusion of a cipher to be used into the list
is a necessary condition.
On the client side, the inclusion into the list is also sufficient
unless the security level excludes it.
On the server side, additional restrictions apply.
All ciphers have additional requirements.
ADH ciphers don't need a certificate, but DH-parameters must have been
set.
All other ciphers need a corresponding certificate and key.
.Pp
An RSA cipher can only be chosen, when an RSA certificate is available.
RSA ciphers using DHE need a certificate and key and additional
DH-parameters (see
.Xr SSL_CTX_set_tmp_dh_callback 3 Ns ).
.Pp
A DSA cipher can only be chosen, when a DSA certificate is available.
DSA ciphers always use DH key exchange and therefore need DH-parameters
(see
.Xr SSL_CTX_set_tmp_dh_callback 3 Ns ).
.Pp
When these conditions are not met for any cipher in the list (e.g.
a client only supports export RSA ciphers with an asymmetric key length
of 512 bits and the server is not configured to use temporary RSA keys),
the "no shared cipher" (SSL_R_NO_SHARED_CIPHER) error is generated and
the handshake will fail.
.Pp
.Fn OSSL_default_cipher_list
and
.Fn OSSL_default_ciphersuites
replace SSL_DEFAULT_CIPHER_LIST and TLS_DEFAULT_CIPHERSUITES,
respectively.
The cipher list defines are deprecated as of 3.0.
.Sh RETURN VALUES
.Fn SSL_CTX_set_cipher_list
and
.Fn SSL_set_cipher_list
return 1 if any cipher could be selected and 0 on complete failure.
.Pp
.Fn SSL_CTX_set_ciphersuites
and
.Fn SSL_set_ciphersuites
return 1 if the requested ciphersuite list was configured, and 0
otherwise.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_get_ciphers 3 ,
.Xr SSL_CTX_use_certificate 3 ,
.Xr SSL_CTX_set_tmp_dh_callback 3 ,
.Xr openssl-ciphers 1
.Sh HISTORY
.Fn OSSL_default_cipher_list
and
.Xr OSSL_default_ciphersites 3
are new in 3.0.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
