.Dd 2025-09-30
.Dt SSL_GET0_GROUP_NAME 3ossl
.Os
.Sh NAME
.Nm SSL_get0_group_name
.Nd get name of the group that was used for the key agreement of the current TLS session establishment
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const char *
.Fo SSL_get0_group_name
.Fa "SSL *s"
.Fc
.Sh DESCRIPTION
.Fn SSL_get0_group_name
returns the name of the group that was used for the key agreement of the
current TLS session establishment.
.Sh RETURN VALUES
If non-NULL,
.Fn SSL_get0_group_name
returns the name of the group that was used for the key agreement of the
current TLS session establishment.
If
.Fn SSL_get0_group_name
returns NULL, an error occurred; possibly no TLS session has been
established.
See also
.Xr SSL_get_negotiated_group 3 .
.Pp
Note that the return value is valid only during the lifetime of the SSL
object
.Em ssl .
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_get_negotiated_group 3
.Sh HISTORY
This function was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2023-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
