.Dd 2025-09-30
.Dt SSL_GET_STREAM_ID 3ossl
.Os
.Sh NAME
.Nm SSL_get_stream_id ,
.Nm SSL_get_stream_type ,
.Nm SSL_STREAM_TYPE_NONE ,
.Nm SSL_STREAM_TYPE_READ ,
.Nm SSL_STREAM_TYPE_WRITE ,
.Nm SSL_STREAM_TYPE_BIDI ,
.Nm SSL_is_stream_local
.Nd get QUIC stream ID and stream type information
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft uint64_t
.Fo SSL_get_stream_id
.Fa "SSL *ssl"
.Fc
.Fd #define SSL_STREAM_TYPE_NONE
.Fd #define SSL_STREAM_TYPE_BIDI
.Fd #define SSL_STREAM_TYPE_READ
.Fd #define SSL_STREAM_TYPE_WRITE
.Ft int
.Fo SSL_get_stream_type
.Fa "SSL *ssl"
.Fc
.Ft int
.Fo SSL_is_stream_local
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
The
.Fn SSL_get_stream_id
function returns the QUIC stream ID for a QUIC stream SSL object, or for
a QUIC connection SSL object which has a default stream attached.
.Pp
The
.Fn SSL_get_stream_type
function identifies what operations can be performed on the stream, and
returns one of the following values:
.Bl -tag -width Ds
.It Sy SSL_STREAM_TYPE_NONE
The SSL object is a QUIC connection SSL object without a default stream
attached.
.It Sy SSL_STREAM_TYPE_BIDI
The SSL object is a non-QUIC SSL object, or is a QUIC stream object (or
QUIC connection SSL object with a default stream attached), and that
stream is a bidirectional QUIC stream.
.It Sy SSL_STREAM_TYPE_READ
The SSL object is a QUIC stream object (or QUIC connection SSL object
with a default stream attached), and that stream is a unidirectional
QUIC stream which was initiated by the remote peer; thus, it can be read
from, but not written to.
.It Sy SSL_STREAM_TYPE_WRITE
The SSL object is a QUIC stream object (or QUIC connection SSL object
with a default stream attached), and that stream is a unidirectional
QUIC stream which was initiated by the local application; thus, it can
be written to, but not read from.
.El
.Pp
The
.Fn SSL_is_stream_local
function determines whether a stream was locally created.
.Sh NOTES
While QUICv1 assigns specific meaning to the low two bits of a QUIC
stream ID, QUIC stream IDs in future versions of QUIC are not required
to have the same semantics.
Do not determine stream properties using these bits.
Instead, use
.Fn SSL_get_stream_type
to determine the stream type and
.Xr SSL_get_stream_is_local 3
to determine the stream initiator.
.Pp
The
.Fn SSL_get_stream_type
identifies the type of a QUIC stream based on its identity, and does not
indicate whether an operation can currently be successfully performed on
a stream.
For example, you might locally initiate a unidirectional stream, write
to it, and then conclude the stream using
.Xr SSL_stream_conclude 3 ,
meaning that it can no longer be written to, but
.Fn SSL_get_stream_type
would still return
.Sy SSL_STREAM_TYPE_WRITE .
The value returned by
.Fn SSL_get_stream_type
does not vary over the lifespan of a stream.
.Sh RETURN VALUES
.Fn SSL_get_stream_id
returns a QUIC stream ID, or
.Sy UINT64_MAX
if called on an SSL object which is not a QUIC SSL object, or if called
on a QUIC connection SSL object without a default stream attached.
Note that valid QUIC stream IDs are always below 2**62.
.Pp
.Fn SSL_get_stream_type
returns one of the
.Sy SSL_STREAM_TYPE
values.
.Pp
.Fn SSL_is_stream_local
returns 1 if called on a QUIC stream SSL object which represents a
stream which was locally initiated.
It returns 0 if called on a QUIC stream SSL object which represents a
stream which was remotely initiated by a peer, and -1 if called on any
other kind of SSL object.
.Sh SEE ALSO
.Xr SSL_new_stream 3 ,
.Xr SSL_accept_stream 3
.Sh HISTORY
These functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2002-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
