.Dd 2025-09-30
.Dt SSL_GET_RPOLL_DESCRIPTOR 3ossl
.Os
.Sh NAME
.Nm SSL_get_rpoll_descriptor ,
.Nm SSL_get_wpoll_descriptor ,
.Nm SSL_net_read_desired ,
.Nm SSL_net_write_desired
.Nd obtain information which can be used to determine when network I/O can be performed
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_get_rpoll_descriptor
.Fa "SSL *s"
.Fa "BIO_POLL_DESCRIPTOR *desc"
.Fc
.Ft int
.Fo SSL_get_wpoll_descriptor
.Fa "SSL *s"
.Fa "BIO_POLL_DESCRIPTOR *desc"
.Fc
.Ft int
.Fo SSL_net_read_desired
.Fa "SSL *s"
.Fc
.Ft int
.Fo SSL_net_write_desired
.Fa "SSL *s"
.Fc
.Sh DESCRIPTION
The functions
.Fn SSL_get_rpoll_descriptor
and
.Fn SSL_get_wpoll_descriptor
can be used to determine when an SSL object which represents a QUIC
connection can perform useful network I/O, so that an application using
a QUIC connection SSL object in nonblocking mode can determine when it
should call
.Xr SSL_handle_events 3 .
.Pp
On success, these functions output poll descriptors.
For more information on poll descriptors, see
.Xr BIO_get_rpoll_descriptor 3 .
.Pp
The functions
.Fn SSL_net_read_desired
and
.Fn SSL_net_write_desired
return 1 or 0 depending on whether the SSL object is currently
interested in receiving data from the network and/or writing data to the
network respectively.
If an SSL object is not interested in reading data from the network at
the current time,
.Fn SSL_net_read_desired
will return 0; likewise, if an SSL object is not interested in writing
data to the network at the current time,
.Fn SSL_net_write_desired
will return 0.
.Pp
The intention is that an application using QUIC in nonblocking mode can
use these calls, in conjunction with
.Xr SSL_get_event_timeout 3
to wait for network I/O conditions which allow the SSL object to perform
useful work.
When such a condition arises,
.Xr SSL_handle_events 3
should be called.
.Pp
In particular, the expected usage is as follows:
.Bl -bullet
.It
.Xr SSL_handle_events 3
should be called whenever the timeout returned by
SSL_get_event_timeout(3) (if any) expires
.It
If the last call to
.Fn SSL_net_read_desired
returned 1,
.Xr SSL_handle_events 3
should be called whenever the poll descriptor output by
.Fn SSL_get_rpoll_descriptor
becomes readable.
.It
If the last call to
.Fn SSL_net_write_desired
returned 1,
.Xr SSL_handle_events 3
should be called whenever the poll descriptor output by
.Fn SSL_get_wpoll_descriptor
becomes writable.
.El
.Pp
The return values of the
.Fn SSL_net_read_desired
and
.Fn SSL_net_write_desired
functions may change in response to any call to the SSL object other
than
.Fn SSL_net_read_desired ,
.Fn SSL_net_write_desired ,
.Fn SSL_get_rpoll_descriptor ,
.Fn SSL_get_wpoll_descriptor
and
.Xr SSL_get_event_timeout 3 .
.Pp
On non-QUIC SSL objects, calls to
.Fn SSL_get_rpoll_descriptor
and
.Fn SSL_get_wpoll_descriptor
function the same as calls to
.Xr BIO_get_rpoll_descriptor 3
and
.Xr BIO_get_wpoll_descriptor 3
on the respective read and write BIOs configured on the SSL object.
.Pp
On non-QUIC SSL objects, calls to
.Fn SSL_net_read_desired
and
.Fn SSL_net_write_desired
function identically to calls to
.Xr SSL_want_read 3
and
.Xr SSL_want_write 3
respectively.
.Sh RETURN VALUES
These functions return 1 on success and 0 on failure.
.Sh SEE ALSO
.Xr SSL_handle_events 3 ,
.Xr SSL_get_event_timeout 3 ,
.Xr ssl 7
.Sh HISTORY
The
.Fn SSL_get_rpoll_descriptor ,
.Fn SSL_get_wpoll_descriptor ,
.Fn SSL_net_read_desired
and
.Fn SSL_net_write_desired
functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2022-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
