.Dd 2025-09-30
.Dt SSL_CTX_FLUSH_SESSIONS 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_flush_sessions_ex ,
.Nm SSL_CTX_flush_sessions
.Nd remove expired sessions
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_CTX_flush_sessions_ex
.Fa "SSL_CTX *ctx"
.Fa "time_t tm"
.Fc
The following functions have been deprecated since OpenSSL 3.4, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo SSL_CTX_flush_sessions
.Fa "SSL_CTX *ctx"
.Fa "long tm"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_flush_sessions_ex
causes a run through the session cache of
.Fa ctx
to remove sessions expired at time
.Fa tm .
.Pp
.Fn SSL_CTX_flush_sessions
is an older variant of the function that is not Y2038 safe due to usage
of long datatype instead of time_t.
.Sh NOTES
If enabled, the internal session cache will collect all sessions
established up to the specified maximum number (see
.Xr SSL_CTX_sess_set_cache_size 3 ) .
As sessions will not be reused ones they are expired, they should be
removed from the cache to save resources.
This can either be done automatically whenever 255 new sessions were
established (see
.Xr SSL_CTX_set_session_cache_mode 3 )
or manually by calling
.Fn SSL_CTX_flush_sessions_ex .
.Pp
The parameter
.Fa tm
specifies the time which should be used for the expiration test, in most
cases the actual time given by time(0) will be used.
.Pp
.Fn SSL_CTX_flush_sessions_ex
will only check sessions stored in the internal cache.
When a session is found and removed, the remove_session_cb is however
called to synchronize with the external cache (see
.Xr SSL_CTX_sess_set_get_cb 3 Ns ).
.Sh RETURN VALUES
.Fn SSL_CTX_flush_sessions_ex
does not return a value.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_session_cache_mode 3 ,
.Xr SSL_CTX_set_timeout 3 ,
.Xr SSL_CTX_sess_set_get_cb 3
.Sh HISTORY
.Fn SSL_CTX_flush_sessions_ex
was added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2001-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
