.Dd 2025-09-30
.Dt SSL_SESSION_GET_PROTOCOL_VERSION 3ossl
.Os
.Sh NAME
.Nm SSL_SESSION_get_protocol_version ,
.Nm SSL_SESSION_set_protocol_version
.Nd get and set the session protocol version
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_SESSION_get_protocol_version
.Fa "const SSL_SESSION *s"
.Fc
.Ft int
.Fo SSL_SESSION_set_protocol_version
.Fa "SSL_SESSION *s"
.Fa "int version"
.Fc
.Sh DESCRIPTION
.Fn SSL_SESSION_get_protocol_version
returns the protocol version number used by session
.Fa s .
.Pp
.Fn SSL_SESSION_set_protocol_version
sets the protocol version associated with the SSL_SESSION object
.Fa s
to the value
.Fa version .
This value should be a version constant such as
.Sy TLS1_3_VERSION
etc.
For example, this could be used to set up a session based PSK (see
.Xr SSL_CTX_set_psk_use_session_callback 3 Ns ).
.Sh RETURN VALUES
.Fn SSL_SESSION_get_protocol_version
returns a number indicating the protocol version used for the session;
this number matches the constants
.Em e.g.
.Sy TLS1_VERSION ,
.Sy TLS1_2_VERSION
or
.Sy TLS1_3_VERSION .
.Pp
Note that the
.Fn SSL_SESSION_get_protocol_version
function does
.Sy not
perform a null check on the provided session
.Fa s
pointer.
.Pp
.Fn SSL_SESSION_set_protocol_version
returns 1 on success or 0 on failure.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_psk_use_session_callback 3
.Sh HISTORY
The
.Fn SSL_SESSION_get_protocol_version
function was added in OpenSSL 1.1.0. The
.Fn SSL_SESSION_set_protocol_version
function was added in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2001-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
