.Dd 2025-09-30
.Dt SSL_ALLOC_BUFFERS 3ossl
.Os
.Sh NAME
.Nm SSL_free_buffers ,
.Nm SSL_alloc_buffers
.Nd manage SSL structure buffers
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_free_buffers
.Fa "SSL *ssl"
.Fc
.Ft int
.Fo SSL_alloc_buffers
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_free_buffers
frees the read and write buffers of the given
.Fa ssl .
.Fn SSL_alloc_buffers
allocates the read and write buffers of the given
.Fa ssl .
.Pp
The
.Sy SSL_MODE_RELEASE_BUFFERS
mode releases read or write buffers whenever the buffers have been
drained.
These functions allow applications to manually control when buffers are
freed and allocated.
.Pp
After freeing the buffers, the buffers are automatically reallocated
upon a new read or write.
The
.Fn SSL_alloc_buffers
does not need to be called, but can be used to make sure the buffers are
preallocated.
This can be used to avoid allocation during data processing or with
.Xr CRYPTO_set_mem_functions 3
to control where and how buffers are allocated.
.Pp
These functions are no-ops when used with QUIC SSL objects.
For QUIC,
.Fn SSL_free_buffers
always fails, and
.Fn SSL_alloc_buffers
always succeeds.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It 0 (Failure)
The
.Fn SSL_free_buffers
function returns 0 when there is pending data to be read or written.
The
.Fn SSL_alloc_buffers
function returns 0 when there is an allocation failure.
.It 1 (Success)
The
.Fn SSL_free_buffers
function returns 1 if the buffers have been freed.
This value is also returned if the buffers had been freed before calling
.Fn SSL_free_buffers .
The
.Fn SSL_alloc_buffers
function returns 1 if the buffers have been allocated.
This value is also returned if the buffers had been allocated before
calling
.Fn SSL_alloc_buffers .
.El
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_free 3 ,
.Xr SSL_clear 3 ,
.Xr SSL_new 3 ,
.Xr SSL_CTX_set_mode 3 ,
.Xr CRYPTO_set_mem_functions 3
.Sh COPYRIGHT
Copyright 2017-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
