.Dd 2025-09-30
.Dt SSL_CLEAR 3ossl
.Os
.Sh NAME
.Nm SSL_clear
.Nd reset SSL object to allow another connection
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_clear
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
Reset
.Fa ssl
to allow another connection.
All settings (method, ciphers, BIOs) are kept.
.Sh NOTES
SSL_clear is used to prepare an SSL object for a new connection.
While all settings are kept, a side effect is the handling of the
current SSL session.
If a session is still
.Sy open ,
it is considered bad and will be removed from the session cache, as
required by RFC2246. A session is considered open, if
.Xr SSL_shutdown 3
was not called for the connection or at least
.Xr SSL_set_shutdown 3
was used to set the SSL_SENT_SHUTDOWN state.
.Pp
If a session was closed cleanly, the session object will be kept and all
settings corresponding.
This explicitly means, that e.g.
the special method used during the session will be kept for the next
handshake.
So if the session was a TLSv1 session, an SSL client object will use a
TLSv1 client method for the next handshake and an SSL server object will
use a TLSv1 server method, even if TLS_*_methods were chosen on startup.
This will might lead to connection failures (see
.Xr SSL_new 3 )
for a description of the method's properties.
.Pp
This function is not supported on QUIC SSL objects and returns failure
if called on such an object.
.Sh WARNINGS
.Fn SSL_clear
resets the SSL object to allow for another connection.
The reset operation however keeps several settings of the last sessions
(some of these settings were made automatically during the last
handshake).
It only makes sense for a new connection with the exact same peer that
shares these settings, and may fail if that peer changes its settings
between connections.
Use the sequence
.Xr SSL_get_session 3 ;
.Xr SSL_new 3 ;
.Xr SSL_set_session 3 ;
.Xr SSL_free 3
instead to avoid such failures (or simply
.Xr SSL_free 3 ;
.Xr SSL_new 3
if session reuse is not desired).
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It 0
The
.Fn SSL_clear
operation could not be performed.
Check the error stack to find out the reason.
.It 1
The
.Fn SSL_clear
operation was successful.
.El
.Pp
.Xr SSL_new 3 ,
.Xr SSL_free 3 ,
.Xr SSL_shutdown 3 ,
.Xr SSL_set_shutdown 3 ,
.Xr SSL_CTX_set_options 3 ,
.Xr ssl 7 ,
.Xr SSL_CTX_set_client_cert_cb 3
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
