.Dd 2025-09-30
.Dt SSL_SESSION_REUSED 3ossl
.Os
.Sh NAME
.Nm SSL_session_reused
.Nd query whether a reused session was negotiated during handshake
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_session_reused
.Fa "const SSL *ssl"
.Fc
.Sh DESCRIPTION
Query, whether a reused session was negotiated during the handshake.
.Sh NOTES
During the negotiation, a client can propose to reuse a session.
The server then looks up the session in its cache.
If both client and server agree on the session, it will be reused and a
flag is being set that can be queried by the application.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It 0
A new session was negotiated.
.It 1
A session was reused.
.El
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_set_session 3 ,
.Xr SSL_CTX_set_session_cache_mode 3
.Sh COPYRIGHT
Copyright 2001-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
