.Dd 2025-09-30
.Dt SSL_CTX_GET0_PARAM 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_get0_param ,
.Nm SSL_get0_param ,
.Nm SSL_CTX_set1_param ,
.Nm SSL_set1_param ,
.Nm SSL_CTX_set_purpose ,
.Nm SSL_CTX_set_trust ,
.Nm SSL_set_purpose ,
.Nm SSL_set_trust
.Nd get and set verification parameters
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft X509_VERIFY_PARAM *
.Fo SSL_CTX_get0_param
.Fa "SSL_CTX *ctx"
.Fc
.Ft X509_VERIFY_PARAM *
.Fo SSL_get0_param
.Fa "SSL *ssl"
.Fc
.Ft int
.Fo SSL_CTX_set1_param
.Fa "SSL_CTX *ctx"
.Fa "X509_VERIFY_PARAM *vpm"
.Fc
.Ft int
.Fo SSL_set1_param
.Fa "SSL *ssl"
.Fa "X509_VERIFY_PARAM *vpm"
.Fc
.Ft int
.Fo SSL_CTX_set_purpose
.Fa "SSL_CTX *ctx"
.Fa "int purpose"
.Fc
.Ft int
.Fo SSL_set_purpose
.Fa "SSL *ssl"
.Fa "int purpose"
.Fc
.Ft int
.Fo SSL_CTX_set_trust
.Fa "SSL_CTX *ctx"
.Fa "int trust"
.Fc
.Ft int
.Fo SSL_set_trust
.Fa "SSL *ssl"
.Fa "int trust"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_get0_param
and
.Fn SSL_get0_param
retrieve an internal pointer to the verification parameters for
.Fa ctx
or
.Fa ssl
respectively.
The returned pointer must not be freed by the calling application.
.Pp
.Fn SSL_CTX_set1_param
and
.Fn SSL_set1_param
set the verification parameters to
.Fa vpm
for
.Fa ctx
or
.Fa ssl .
.Pp
The functions
.Fn SSL_CTX_set_purpose
and
.Fn SSL_set_purpose
are shorthands which set the purpose parameter on the verification
parameters object.
These functions are equivalent to calling
.Xr X509_VERIFY_PARAM_set_purpose 3
directly.
.Pp
The functions
.Fn SSL_CTX_set_trust
and
.Fn SSL_set_trust
are similarly shorthands which set the trust parameter on the
verification parameters object.
These functions are equivalent to calling
.Xr X509_VERIFY_PARAM_set_trust 3
directly.
.Sh NOTES
Typically parameters are retrieved from an
.Vt SSL_CTX
or
.Vt SSL
structure using
.Fn SSL_CTX_get0_param
or
.Fn SSL_get0_param
and an application modifies them to suit its needs: for example to add a
hostname check.
.Sh RETURN VALUES
.Fn SSL_CTX_get0_param
and
.Fn SSL_get0_param
return a pointer to an
.Vt X509_VERIFY_PARAM
structure.
.Pp
.Fn SSL_CTX_set1_param ,
.Fn SSL_set1_param ,
.Fn SSL_CTX_set_purpose ,
.Fn SSL_set_purpose ,
.Fn SSL_CTX_set_trust
and
.Fn SSL_set_trust
return 1 for success and 0 for failure.
.Sh EXAMPLES
Check hostname matches "www.foo.com" in peer certificate:
.Bd -literal
 X509_VERIFY_PARAM *vpm = SSL_get0_param(ssl);
 X509_VERIFY_PARAM_set1_host(vpm, "www.foo.com", 0);
.Ed
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr X509_VERIFY_PARAM_set_flags 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2015-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
