.Dd 2025-09-30
.Dt SSL_LOAD_CLIENT_CA_FILE 3ossl
.Os
.Sh NAME
.Nm SSL_load_client_CA_file_ex ,
.Nm SSL_load_client_CA_file ,
.Nm SSL_add_file_cert_subjects_to_stack ,
.Nm SSL_add_dir_cert_subjects_to_stack ,
.Nm SSL_add_store_cert_subjects_to_stack
.Nd load certificate names
.Sh SYNOPSIS
.In openssl/ssl.h
.Bd -literal
 STACK_OF(X509_NAME) *SSL_load_client_CA_file_ex(const char *file,
                                                 OSSL_LIB_CTX *libctx,
                                                 const char *propq);
 STACK_OF(X509_NAME) *SSL_load_client_CA_file(const char *file);
.Ed
.Ft int
.Fo SSL_add_file_cert_subjects_to_stack
.Fa "STACK_OF(X509_NAME) *stack"
.Fa "const char *file"
.Fc
.Ft int
.Fo SSL_add_dir_cert_subjects_to_stack
.Fa "STACK_OF(X509_NAME) *stack"
.Fa "const char *dir"
.Fc
.Ft int
.Fo SSL_add_store_cert_subjects_to_stack
.Fa "STACK_OF(X509_NAME) *stack"
.Fa "const char *store"
.Fc
.Sh DESCRIPTION
.Xr SSL_load_client_CA_file_ex 3
reads certificates from
.Fa file
and returns a STACK_OF(X509_NAME) with the subject names found.
The library context
.Em libctx
and property query
.Em propq
are used when fetching algorithms from providers.
.Pp
.Xr SSL_load_client_CA_file 3
is similar to
.Xr SSL_load_client_CA_file_ex 3
but uses NULL for the library context
.Em libctx
and property query
.Em propq .
.Pp
.Fn SSL_add_file_cert_subjects_to_stack
reads certificates from
.Fa file ,
and adds their subject name to the already existing
.Fa stack .
.Pp
.Fn SSL_add_dir_cert_subjects_to_stack
reads certificates from every file in the directory
.Fa dir ,
and adds their subject name to the already existing
.Fa stack .
.Pp
.Fn SSL_add_store_cert_subjects_to_stack
loads certificates from the
.Fa store
URI, and adds their subject name to the already existing
.Fa stack .
.Sh NOTES
.Xr SSL_load_client_CA_file 3
reads a file of PEM formatted certificates and extracts the X509_NAMES
of the certificates found.
While the name suggests the specific usage as support function for
.Xr SSL_CTX_set_client_CA_list 3 ,
it is not limited to CA certificates.
.Sh RETURN VALUES
The following return values can occur for
.Xr SSL_load_client_CA_file_ex 3 ,
and
.Xr SSL_load_client_CA_file 3 :
.Bl -tag -width Ds
.It NULL
The operation failed, check out the error stack for the reason.
.It Pointer to STACK_OF(X509_NAME)
Pointer to the subject names of the successfully read certificates.
.El
.Pp
The following return values can occur for
.Fn SSL_add_file_cert_subjects_to_stack ,
.Fn SSL_add_dir_cert_subjects_to_stack ,
and
.Fn SSL_add_store_cert_subjects_to_stack :
.Bl -tag -width Ds
.It 0 (Failure)
The operation failed.
.It 1 (Success)
The operation succeeded.
.El
.Sh EXAMPLES
Load names of CAs from file and use it as a client CA list:
.Bd -literal
 SSL_CTX *ctx;
 STACK_OF(X509_NAME) *cert_names;

 ...
 cert_names = SSL_load_client_CA_file("/path/to/CAfile.pem");
 if (cert_names != NULL)
     SSL_CTX_set_client_CA_list(ctx, cert_names);
 else
     /* error */
 ...
.Ed
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr ossl_store 7 ,
.Xr SSL_CTX_set_client_CA_list 3
.Sh HISTORY
.Xr SSL_load_client_CA_file_ex 3
and
.Fn SSL_add_store_cert_subjects_to_stack
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
