.Dd 2025-09-30
.Dt SSL_CTX_SET1_CERT_COMP_PREFERENCE 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set1_cert_comp_preference ,
.Nm SSL_set1_cert_comp_preference ,
.Nm SSL_CTX_compress_certs ,
.Nm SSL_compress_certs ,
.Nm SSL_CTX_get1_compressed_cert ,
.Nm SSL_get1_compressed_cert ,
.Nm SSL_CTX_set1_compressed_cert ,
.Nm SSL_set1_compressed_cert
.Nd Certificate compression functions
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_set1_cert_comp_preference
.Fa "SSL_CTX *ctx"
.Fa "int *algs"
.Fa "size_t len"
.Fc
.Ft int
.Fo SSL_set1_cert_comp_preference
.Fa "SSL *ssl"
.Fa "int *algs"
.Fa "size_t len"
.Fc
.Ft int
.Fo SSL_CTX_compress_certs
.Fa "SSL_CTX *ctx"
.Fa "int alg"
.Fc
.Ft int
.Fo SSL_compress_certs
.Fa "SSL *ssl"
.Fa "int alg"
.Fc
.Ft size_t
.Fo SSL_CTX_get1_compressed_cert
.Fa "SSL_CTX *ctx"
.Fa "int alg"
.Fa "unsigned char **data"
.Fa "size_t *orig_len"
.Fc
.Ft size_t
.Fo SSL_get1_compressed_cert
.Fa "SSL *ssl"
.Fa "int alg"
.Fa "unsigned char **data"
.Fa "size_t *orig_len"
.Fc
.Ft int
.Fo SSL_CTX_set1_compressed_cert
.Fa "SSL_CTX *ctx"
.Fa "int alg"
.Fa "unsigned char *comp_data"
.Fa "size_t comp_length"
.Fa "size_t orig_length"
.Fc
.Ft int
.Fo SSL_set1_compressed_cert
.Fa "SSL *ssl"
.Fa "int alg"
.Fa "unsigned char *comp_data"
.Fa "size_t comp_length"
.Fa "size_t orig_length"
.Fc
.Sh DESCRIPTION
These functions control the certificate compression feature.
Certificate compression is only available for TLSv1.3 as defined in
RFC8879.
.Pp
.Fn SSL_CTX_set1_cert_comp_preference
and
.Fn SSL_set1_cert_comp_preference
are used to specify the preferred compression algorithms.
The
.Fa algs
argument is an array of algorithms, and
.Sy length
is number of elements in the
.Fa algs
array.
Only those algorithms enabled in the library will be accepted in
.Fa algs ,
unknown algorithms in
.Fa algs
are ignored.
On an error, the preference order is left unmodified.
.Pp
The following compression algorithms
.Pf ( Fa alg
arguments) may be used:
.Bl -tag -width Ds
.It * TLSEXT_comp_cert_brotli
.It * TLSEXT_comp_cert_zlib
.It * TLSEXT_comp_cert_zstd
.El
The above is also the default preference order.
If a preference order is not specified, then the default preference
order is sent to the peer and the received peer's preference order will
be used when compressing a certificate.
Otherwise, the configured preference order is sent to the peer and is
used to filter the peer's preference order.
.Pp
.Fn SSL_CTX_compress_certs
and
.Fn SSL_compress_certs
are used to pre-compress all the configured certificates on an
SSL_CTX/SSL object with algorithm
.Fa alg .
If
.Fa alg
is 0, then the certificates are compressed with the algorithms specified
in the preference list.
Calling these functions on a client SSL_CTX/SSL object will result in an
error, as only server certificates may be pre-compressed.
.Pp
.Fn SSL_CTX_get1_compressed_cert
and
.Fn SSL_get1_compressed_cert
are used to get the pre-compressed certificate most recently set that
may be stored for later use.
Calling these functions on a client SSL_CTX/SSL object will result in an
error, as only server certificates may be pre-compressed.
The
.Fa data
and
.Fa orig_len
arguments are required.
.Pp
The compressed certificate data may be passed to
.Fn SSL_CTX_set1_compressed_cert
or
.Fn SSL_set1_compressed_cert
to provide a pre-compressed version of the most recently set
certificate.
This pre-compressed certificate can only be used by a server.
.Sh NOTES
Each side of the connection sends their compression algorithm preference
list to their peer indicating compressed certificate support.
The received preference list is filtered by the configured preference
list (i.e.
the intersection is saved).
As the default list includes all the enabled algorithms, not specifying
a preference will allow any enabled algorithm by the peer.
The filtered peer's preference order is used to determine what algorithm
to use when sending a compressed certificate.
.Pp
Only server certificates may be pre-compressed.
Calling any of these functions (except
.Xr SSL_CTX_set1_cert_comp_preference()/SSL_set1_cert_comp_preference 3 )
on a client SSL_CTX/SSL object will return an error.
Client certificates are compressed on-demand as unique context data from
the server is compressed along with the certificate.
.Pp
For
.Fn SSL_CTX_set1_cert_comp_preference
and
.Fn SSL_set1_cert_comp_preference
the
.Fa len
argument is the size of the
.Fa algs
argument in bytes.
.Pp
The compressed certificate returned by
.Fn SSL_CTX_get1_compressed_cert
and
.Fn SSL_get1_compressed_cert
is the last certificate set on the SSL_CTX/SSL object.
The certificate is copied by the function and the caller must free
.Sy *data
via
.Xr OPENSSL_free 3 .
.Pp
The compressed certificate data set by
.Fn SSL_CTX_set1_compressed_cert
and
.Fn SSL_set1_compressed_cert
is copied into the SSL_CTX/SSL object.
.Pp
.Fn SSL_CTX_compress_certs
and
.Fn SSL_compress_certs
return an error under the following conditions:
.Bl -tag -width Ds
.It * \&If no certificates have been configured.
.It * \&If the specified algorithm Fa alg No is not enabled.
.It * \&If Fa alg No is 0 and no compression algorithms are enabled.
.El
Sending compressed certificates may be disabled on a connection via the
SSL_OP_NO_TX_CERTIFICATE_COMPRESSION option.
Receiving compressed certificates may be disabled on a connection via
the SSL_OP_NO_RX_CERTIFICATE_COMPRESSION option.
.Sh RETURN VALUES
.Fn SSL_CTX_set1_cert_comp_preference ,
.Fn SSL_set1_cert_comp_preference ,
.Fn SSL_CTX_compress_certs ,
.Fn SSL_compress_certs ,
.Fn SSL_CTX_set1_compressed_cert ,
and
.Fn SSL_set1_compressed_cert
return 1 for success and 0 on error.
.Pp
.Fn SSL_CTX_get1_compressed_cert
and
.Fn SSL_get1_compressed_cert
return the length of the allocated memory on success and 0 on error.
.Sh SEE ALSO
.Xr SSL_CTX_set_options 3 ,
.Xr SSL_CTX_use_certificate 3
.Sh HISTORY
These functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
