.Dd 2025-09-30
.Dt SSL_CTX_USE_PSK_IDENTITY_HINT 3ossl
.Os
.Sh NAME
.Nm SSL_psk_server_cb_func ,
.Nm SSL_psk_find_session_cb_func ,
.Nm SSL_CTX_use_psk_identity_hint ,
.Nm SSL_use_psk_identity_hint ,
.Nm SSL_CTX_set_psk_server_callback ,
.Nm SSL_set_psk_server_callback ,
.Nm SSL_CTX_set_psk_find_session_callback ,
.Nm SSL_set_psk_find_session_callback
.Nd set PSK identity hint to use
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft typedef int
.Fo 
.Fa *SSL_psk_find_session_cb_func
.Fc
(SSL *ssl,
.Bd -literal
                                             const unsigned char *identity,
                                             size_t identity_len,
                                             SSL_SESSION **sess);
.Ed
.Ft void
.Fo SSL_CTX_set_psk_find_session_callback
.Fa "SSL_CTX *ctx"
.Fa "SSL_psk_find_session_cb_func cb"
.Fc
.Ft void
.Fo SSL_set_psk_find_session_callback
.Fa "SSL *s"
.Fa "SSL_psk_find_session_cb_func cb"
.Fc
.Ft typedef unsigned int
.Fo 
.Fa *SSL_psk_server_cb_func
.Fc
(SSL *ssl,
.Bd -literal
                                                const char *identity,
                                                unsigned char *psk,
                                                unsigned int max_psk_len);
.Ed
.Ft int
.Fo SSL_CTX_use_psk_identity_hint
.Fa "SSL_CTX *ctx"
.Fa "const char *hint"
.Fc
.Ft int
.Fo SSL_use_psk_identity_hint
.Fa "SSL *ssl"
.Fa "const char *hint"
.Fc
.Ft void
.Fo SSL_CTX_set_psk_server_callback
.Fa "SSL_CTX *ctx"
.Fa "SSL_psk_server_cb_func cb"
.Fc
.Ft void
.Fo SSL_set_psk_server_callback
.Fa "SSL *ssl"
.Fa "SSL_psk_server_cb_func cb"
.Fc
.Sh DESCRIPTION
A server application wishing to use TLSv1.3 PSKs should set a callback
using either
.Fn SSL_CTX_set_psk_find_session_callback
or
.Fn SSL_set_psk_find_session_callback
as appropriate.
.Pp
The callback function is given a pointer to the SSL connection in
.Fa ssl
and an identity in
.Sy identity
of length
.Sy identity_len .
The callback function should identify an SSL_SESSION object that
provides the PSK details and store it in
.Sy *sess .
The SSL_SESSION object should, as a minimum, set the master key, the
ciphersuite and the protocol version.
See
.Xr SSL_CTX_set_psk_use_session_callback 3
for details.
.Pp
It is also possible for the callback to succeed but not supply a PSK. In
this case no PSK will be used but the handshake will continue.
To do this the callback should return successfully and ensure that
.Sy *sess
is NULL.
.Pp
Identity hints are not relevant for TLSv1.3. A server application
wishing to use PSK ciphersuites for TLSv1.2 and below may call
.Fn SSL_CTX_use_psk_identity_hint
to set the given
.Sy NUL Ns -terminated
PSK identity hint
.Fa hint
for SSL context object
.Fa ctx .
.Fn SSL_use_psk_identity_hint
sets the given
.Sy NUL Ns -terminated
PSK identity hint
.Fa hint
for the SSL connection object
.Fa ssl .
If
.Fa hint
is
.Dv NULL
the current hint from
.Fa ctx
or
.Fa ssl
is deleted.
.Pp
In the case where PSK identity hint is
.Dv NULL ,
the server does not send the ServerKeyExchange message to the client.
.Pp
A server application wishing to use PSKs for TLSv1.2 and below must
provide a callback function which is called when the server receives the
ClientKeyExchange message from the client.
The purpose of the callback function is to validate the received PSK
identity and to fetch the pre-shared key used during the connection
setup phase.
The callback is set using the functions
.Fn SSL_CTX_set_psk_server_callback
or
.Fn SSL_set_psk_server_callback .
The callback function is given the connection in parameter
.Fa ssl ,
.Sy NUL Ns -terminated
PSK identity sent by the client in parameter
.Sy identity ,
and a buffer
.Sy psk
of length
.Sy max_psk_len
bytes where the pre-shared key is to be stored.
.Pp
The callback for use in TLSv1.2 will also work in TLSv1.3 although it is
recommended to use
.Fn SSL_CTX_set_psk_find_session_callback
or
.Fn SSL_set_psk_find_session_callback
for this purpose instead.
If TLSv1.3 has been negotiated then OpenSSL will first check to see if a
callback has been set via
.Fn SSL_CTX_set_psk_find_session_callback
or
.Fn SSL_set_psk_find_session_callback
and it will use that in preference.
If no such callback is present then it will check to see if a callback
has been set via
.Fn SSL_CTX_set_psk_server_callback
or
.Fn SSL_set_psk_server_callback
and use that.
In this case the handshake digest will default to SHA-256 for any
returned PSK. TLSv1.3 early data exchanges are possible in PSK
connections only with the
.Vt SSL_psk_find_session_cb_func
callback, and are not possible with the
.Vt SSL_psk_server_cb_func
callback.
.Pp
A connection established via a TLSv1.3 PSK will appear as if session
resumption has occurred so that
.Xr SSL_session_reused 3
will return true.
.Sh RETURN VALUES
.Sy SSL_CTX_use_psk_identity_hint()
and
.Sy SSL_use_psk_identity_hint()
return 1 on success, 0 otherwise.
.Pp
Return values from the TLSv1.2 and below server callback are interpreted
as follows:
.Bl -tag -width Ds
.It 0
PSK identity was not found.
An "unknown_psk_identity" alert message will be sent and the connection
setup fails.
.It \(ra0
PSK identity was found and the server callback has provided the PSK
successfully in parameter
.Sy psk .
Return value is the length of
.Sy psk
in bytes.
It is an error to return a value greater than
.Sy max_psk_len .
.Pp
If the PSK identity was not found but the callback instructs the
protocol to continue anyway, the callback must provide some random data
to
.Sy psk
and return the length of the random data, so the connection will fail
with decryption_error before it will be finished completely.
.El
.Pp
The
.Vt SSL_psk_find_session_cb_func
callback should return 1 on success or 0 on failure.
In the event of failure the connection setup fails.
.Sh NOTES
There are no known security issues with sharing the same PSK between
TLSv1.2 (or below) and TLSv1.3. However, the RFC has this note of
caution:
.Pp
"While there is no known way in which the same PSK might produce related
output in both versions, only limited analysis has been done.
Implementations can ensure safety from cross-protocol related output by
not reusing PSKs between TLS 1.3 and TLS 1.2."
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_psk_use_session_callback 3 ,
.Xr SSL_set_psk_use_session_callback 3
.Sh HISTORY
.Fn SSL_CTX_set_psk_find_session_callback
and
.Fn SSL_set_psk_find_session_callback
were added in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2006-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
