.Dd 2025-09-30
.Dt SSL_CTX_SET1_VERIFY_CERT_STORE 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set0_verify_cert_store ,
.Nm SSL_CTX_set1_verify_cert_store ,
.Nm SSL_CTX_set0_chain_cert_store ,
.Nm SSL_CTX_set1_chain_cert_store ,
.Nm SSL_set0_verify_cert_store ,
.Nm SSL_set1_verify_cert_store ,
.Nm SSL_set0_chain_cert_store ,
.Nm SSL_set1_chain_cert_store ,
.Nm SSL_CTX_get0_verify_cert_store ,
.Nm SSL_CTX_get0_chain_cert_store ,
.Nm SSL_get0_verify_cert_store ,
.Nm SSL_get0_chain_cert_store
.Nd set certificate verification or chain store
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_set0_verify_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_CTX_set1_verify_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_CTX_set0_chain_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_CTX_set1_chain_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_CTX_get0_verify_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE **st"
.Fc
.Ft int
.Fo SSL_CTX_get0_chain_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE **st"
.Fc
.Ft int
.Fo SSL_set0_verify_cert_store
.Fa "SSL *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_set1_verify_cert_store
.Fa "SSL *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_set0_chain_cert_store
.Fa "SSL *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_set1_chain_cert_store
.Fa "SSL *ctx"
.Fa "X509_STORE *st"
.Fc
.Ft int
.Fo SSL_get0_verify_cert_store
.Fa "SSL *ctx"
.Fa "X509_STORE **st"
.Fc
.Ft int
.Fo SSL_get0_chain_cert_store
.Fa "SSL *ctx"
.Fa "X509_STORE **st"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set0_verify_cert_store
and
.Fn SSL_CTX_set1_verify_cert_store
set the certificate store used for certificate verification to
.Fa st .
.Pp
.Fn SSL_CTX_set0_chain_cert_store
and
.Fn SSL_CTX_set1_chain_cert_store
set the certificate store used for certificate chain building to
.Fa st .
.Pp
.Fn SSL_set0_verify_cert_store ,
.Fn SSL_set1_verify_cert_store ,
.Fn SSL_set0_chain_cert_store
and
.Fn SSL_set1_chain_cert_store
are similar except they apply to SSL structure
.Sy ssl .
.Pp
.Xr SSL_CTX_get0_verify_chain_store 3 ,
.Xr SSL_get0_verify_chain_store 3 ,
.Fn SSL_CTX_get0_chain_cert_store
and
.Fn SSL_get0_chain_cert_store
retrieve the objects previously set via the above calls.
A pointer to the object (or NULL if no such object has been set) is
written to
.Sy *st .
.Pp
All these functions are implemented as macros.
Those containing a
.Sy 1
increment the reference count of the supplied store so it must be freed
at some point after the operation.
Those containing a
.Sy 0
do not increment reference counts and the supplied store
.Sy MUST NOT
be freed after the operation.
.Sh NOTES
The stores pointers associated with an SSL_CTX structure are copied to
any SSL structures when
.Xr SSL_new 3
is called.
As a result SSL structures will not be affected if the parent SSL_CTX
store pointer is set to a new value.
.Pp
The verification store is used to verify the certificate chain sent by
the peer: that is an SSL/TLS client will use the verification store to
verify the server's certificate chain and an SSL/TLS server will use it
to verify any client certificate chain.
.Pp
The chain store is used to build the certificate chain.
Details of the chain building and checking process are described in
.Xr openssl-verification-options 1
and
.Xr openssl-verification-options 1 .
.Pp
If the mode
.Sy SSL_MODE_NO_AUTO_CHAIN
is set or a certificate chain is configured already (for example using
the functions such as
.Xr SSL_CTX_add1_chain_cert 3
or
.Xr SSL_CTX_add_extra_chain_cert 3 )
then automatic chain building is disabled.
.Pp
If the mode
.Sy SSL_MODE_NO_AUTO_CHAIN
is set then automatic chain building is disabled.
.Pp
If the chain or the verification store is not set then the store
associated with the parent SSL_CTX is used instead to retain
compatibility with previous versions of OpenSSL.
.Sh RETURN VALUES
All these functions return 1 for success and 0 for failure.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_add_extra_chain_cert 3
.Xr SSL_CTX_set0_chain 3
.Xr SSL_CTX_set1_chain 3
.Xr SSL_CTX_add0_chain_cert 3
.Xr SSL_CTX_add1_chain_cert 3
.Xr SSL_set0_chain 3
.Xr SSL_set1_chain 3
.Xr SSL_add0_chain_cert 3
.Xr SSL_add1_chain_cert 3
.Xr SSL_CTX_build_cert_chain 3
.Xr SSL_build_cert_chain 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2013-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
