.Dd 2025-09-30
.Dt SSL_NEW 3ossl
.Os
.Sh NAME
.Nm SSL_dup ,
.Nm SSL_new ,
.Nm SSL_up_ref
.Nd create an SSL structure for a connection
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft SSL *
.Fo SSL_dup
.Fa "SSL *s"
.Fc
.Ft SSL *
.Fo SSL_new
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_up_ref
.Fa "SSL *s"
.Fc
.Sh DESCRIPTION
.Fn SSL_new
creates a new
.Vt SSL
structure which is needed to hold the data for a TLS/SSL connection.
The new structure inherits the settings of the underlying context
.Fa ctx :
connection method, options, verification settings, timeout settings.
An
.Vt SSL
structure is reference counted.
Creating an
.Vt SSL
structure for the first time increments the reference count.
Freeing it (using SSL_free) decrements it.
When the reference count drops to zero, any memory or resources
allocated to the
.Vt SSL
structure are freed.
.Pp
.Fn SSL_up_ref
increments the reference count for an existing
.Vt SSL
structure.
.Pp
The function
.Fn SSL_dup
creates and returns a new
.Vt SSL
structure from the same
.Vt SSL_CTX
that was used to create
.Fa s .
It additionally duplicates a subset of the settings in
.Fa s
into the new
.Vt SSL
object.
.Pp
For
.Fn SSL_dup
to work, the connection MUST be in its initial state and MUST NOT have
yet started the SSL handshake.
For connections that are not in their initial state
.Fn SSL_dup
just increments an internal reference count and returns the
.Em same
handle.
It may be possible to use
.Xr SSL_clear 3
to recycle an SSL handle that is not in its initial state for reuse, but
this is best avoided.
Instead, save and restore the session, if desired, and construct a fresh
handle for each connection.
.Pp
The subset of settings in
.Fa s
that are duplicated are:
.Bl -tag -width Ds
.It any session data if configured (including the session_id_context)
.It any tmp_dh settings set via Xr SSL_set_tmp_dh 3 No , Xr SSL_set_tmp_dh_callback 3 Ns , or Xr SSL_set_dh_auto 3
.It any configured certificates, private keys or certificate chains
.It any configured signature algorithms, or client signature algorithms
.It any DANE settings
.It any Options set via Xr SSL_set_options 3
.It any Mode set via Xr SSL_set_mode 3
.It any minimum or maximum protocol settings set via Xr SSL_set_min_proto_version 3 No or Xr SSL_set_max_proto_version 3 No (Note: Only from OpenSSL 1.1.1h and above)
.It any verify mode, callback or depth set via Xr SSL_set_verify 3 No or Xr SSL_set_verify_depth 3 No or any configured X509 verification parameters
.It any msg callback or info callback set via Xr SSL_set_msg_callback 3 No or Xr SSL_set_info_callback 3
.It any default password callback set via Xr SSL_set_default_passwd_cb 3
.It any session id generation callback set via Xr SSL_set_generate_session_id 3
.It any configured Cipher List
.It initial accept (server) or connect (client) state
.It the max cert list value set via Xr SSL_set_max_cert_list 3
.It the read_ahead value set via Xr SSL_set_read_ahead 3
.It application specific data set via Xr SSL_set_ex_data 3
.It any CA list or client CA list set via Xr SSL_set0_CA_list 3 No , SSL_set0_client_CA_list() or similar functions
.It any security level settings or callbacks
.It any configured serverinfo data
.It any configured PSK identity hint
.It any configured custom extensions
.It any client certificate types configured via SSL_set1_client_certificate_types
.El
.Fn SSL_dup
is not supported on QUIC SSL objects and returns NULL if called on such
an object.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It NULL
The creation of a new SSL structure failed.
Check the error stack to find out the reason.
.It Pointer to an SSL structure
The return value points to an allocated SSL structure.
.Pp
.Fn SSL_up_ref
returns 1 for success and 0 for failure.
.El
.Sh SEE ALSO
.Xr SSL_free 3 ,
.Xr SSL_clear 3 ,
.Xr SSL_CTX_set_options 3 ,
.Xr SSL_get_SSL_CTX 3 ,
.Xr ssl 7
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
