.Dd 2025-09-30
.Dt SSL_CTX_SET_CERT_STORE 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_cert_store ,
.Nm SSL_CTX_set1_cert_store ,
.Nm SSL_CTX_get_cert_store
.Nd manipulate X509 certificate verification storage
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_CTX_set_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE *store"
.Fc
.Ft void
.Fo SSL_CTX_set1_cert_store
.Fa "SSL_CTX *ctx"
.Fa "X509_STORE *store"
.Fc
.Ft X509_STORE *
.Fo SSL_CTX_get_cert_store
.Fa "const SSL_CTX *ctx"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set_cert_store
sets/replaces the certificate verification storage of
.Fa ctx
to/with
.Fa store .
If another X509_STORE object is currently set in
.Fa ctx ,
it will be X509_STORE_free()ed.
.Fn SSL_CTX_set_cert_store
will take ownership of the
.Fa store ,
i.e., the call
.Qo Li X509_STORE_free(store) Qc
is no longer needed.
.Pp
.Fn SSL_CTX_set1_cert_store
sets/replaces the certificate verification storage of
.Fa ctx
to/with
.Fa store .
The
.Fa store Ns 's
reference count is incremented.
If another X509_STORE object is currently set in
.Fa ctx ,
it will be X509_STORE_free()ed.
.Pp
.Fn SSL_CTX_get_cert_store
returns a pointer to the current certificate verification storage.
.Fa ctx
.Sy MUST NOT
be NULL.
.Sh NOTES
In order to verify the certificates presented by the peer, trusted CA
certificates must be accessed.
These CA certificates are made available via lookup methods, handled
inside the X509_STORE. From the X509_STORE the X509_STORE_CTX used when
verifying certificates is created.
.Pp
Typically the trusted certificate store is handled indirectly via using
.Xr SSL_CTX_load_verify_locations 3 .
Using the
.Fn SSL_CTX_set_cert_store
and
.Fn SSL_CTX_get_cert_store
functions it is possible to manipulate the X509_STORE object beyond the
.Xr SSL_CTX_load_verify_locations 3
call.
.Pp
Currently no detailed documentation on how to use the X509_STORE object
is available.
Not all members of the X509_STORE are used when the verification takes
place.
So will e.g.
the
.Xr verify_callback 3
be overridden with the
.Xr verify_callback 3
set via the
.Xr SSL_CTX_set_verify 3
family of functions.
This document must therefore be updated when documentation about the
X509_STORE object and its handling becomes available.
.Pp
.Fn SSL_CTX_set_cert_store
does not increment the
.Fa store Ns 's
reference count, so it should not be used to assign an X509_STORE that
is owned by another SSL_CTX.
.Pp
To share X509_STOREs between two SSL_CTXs, use
.Fn SSL_CTX_get_cert_store
to get the X509_STORE from the first SSL_CTX, and then use
.Fn SSL_CTX_set1_cert_store
to assign to the second SSL_CTX and increment the reference count of the
X509_STORE.
.Sh RESTRICTIONS
The X509_STORE structure used by an SSL_CTX is used for verifying peer
certificates and building certificate chains, it is also shared by every
child SSL structure.
Applications wanting finer control can use functions such as
.Xr SSL_CTX_set1_verify_cert_store 3
instead.
.Sh RETURN VALUES
.Fn SSL_CTX_set_cert_store
does not return diagnostic output.
.Pp
.Fn SSL_CTX_set1_cert_store
does not return diagnostic output.
.Pp
.Fn SSL_CTX_get_cert_store
returns the current setting.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_load_verify_locations 3 ,
.Xr SSL_CTX_set_verify 3
.Sh COPYRIGHT
Copyright 2001-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
