.Dd 2025-09-30
.Dt SSL_FREE 3ossl
.Os
.Sh NAME
.Nm SSL_free
.Nd free an allocated SSL structure
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_free
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_free
decrements the reference count of
.Fa ssl ,
and removes the SSL structure pointed to by
.Fa ssl
and frees up the allocated memory if the reference count has reached 0.
If
.Fa ssl
is NULL nothing is done.
.Sh NOTES
.Fn SSL_free
also calls the free()ing procedures for indirectly affected items, if
applicable: the buffering BIO, the read and write BIOs, cipher lists
specially created for this
.Fa ssl ,
the
.Sy SSL_SESSION .
Do not explicitly free these indirectly freed up items before or after
calling
.Fn SSL_free ,
as trying to free things twice may lead to program failure.
.Pp
The ssl session has reference counts from two users: the SSL object, for
which the reference count is removed by
.Fn SSL_free
and the internal session cache.
If the session is considered bad, because
.Xr SSL_shutdown 3
was not called for the connection and
.Xr SSL_set_shutdown 3
was not used to set the SSL_SENT_SHUTDOWN state, the session will also
be removed from the session cache as required by RFC2246.
.Pp
When used to free a QUIC stream SSL object, the respective sending and
receiving parts of the stream are reset unless those parts have already
been concluded normally:
.Bl -tag -width Ds
.It
If the stream has a sending part (in other words, if it is bidirectional
or a locally-initiated unidirectional stream) and that part has not been
concluded via a call to
.Xr SSL_stream_conclude 3
or
.Xr SSL_stream_reset 3
on the QUIC stream SSL object, a call to
.Fn SSL_free
automatically resets the sending part of the stream as though
.Xr SSL_stream_reset 3
were called with a QUIC application error code of 0.
.It
If the stream has a receiving part (in other words, if it is
bidirectional or a remotely-initiated unidirectional stream), and the
peer has not yet concluded that part of the stream normally (such as via
a call to
.Xr SSL_stream_conclude 3
on its own end), a call to
.Fn SSL_free
automatically requests the reset of the receiving part of the stream
using a QUIC STOP_SENDING frame with a QUIC application error code of 0.
Note that as per the QUIC protocol, this will automatically cause the
peer to reset that part of the stream in turn (which is its sending
part).
.El
.Pp
A QUIC stream SSL object maintains a reference to a QUIC connection SSL
object internally, therefore a QUIC stream SSL object and its parent
QUIC connection SSL object can be freed in either order.
.Sh RETURN VALUES
.Fn SSL_free
does not provide diagnostic information.
.Pp
.Xr SSL_new 3 ,
.Xr SSL_clear 3 ,
.Xr SSL_shutdown 3 ,
.Xr SSL_set_shutdown 3 ,
.Xr ssl 7
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
