.Dd 2025-09-30
.Dt SSL_GET0_CONNECTION 3ossl
.Os
.Sh NAME
.Nm SSL_get0_connection ,
.Nm SSL_is_connection
.Nd get a QUIC connection SSL object from a QUIC stream SSL object
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft SSL *
.Fo SSL_get0_connection
.Fa "SSL *ssl"
.Fc
.Ft int
.Fo SSL_is_connection
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
The
.Fn SSL_get0_connection
function, when called on a QUIC stream SSL object, returns the QUIC
connection SSL object which the QUIC stream SSL object belongs to.
.Pp
When called on a QUIC connection SSL object, it returns the same object.
.Pp
When called on a non-QUIC object, it returns the same object it was
passed.
.Pp
.Fn SSL_is_connection
returns 1 for QUIC connection SSL objects and for non-QUIC SSL objects,
but returns 0 for QUIC stream SSL objects.
.Sh RETURN VALUES
.Fn SSL_get0_connection
returns the QUIC connection SSL object (for a QUIC stream SSL object)
and otherwise returns the same SSL object passed.
It always returns non-NULL.
.Pp
.Fn SSL_is_connection
returns 1 if the SSL object is not a QUIC stream SSL object and 0
otherwise.
.Sh SEE ALSO
.Xr SSL_new 3 ,
.Xr SSL_new_stream 3 ,
.Xr SSL_accept_stream 3
.Sh HISTORY
These functions were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2002-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
