.Dd 2025-09-30
.Dt SSL_STREAM_CONCLUDE 3ossl
.Os
.Sh NAME
.Nm SSL_stream_conclude
.Nd conclude the sending part of a QUIC stream
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft __owur int
.Fo SSL_stream_conclude
.Fa "SSL *s"
.Fa "uint64_t flags"
.Fc
.Sh DESCRIPTION
.Fn SSL_stream_conclude
signals the normal end-of-stream condition for the send part of a QUIC
stream.
If called on a QUIC connection SSL object with an associated default
stream, it signals the end of the single stream to the peer.
.Pp
Any data already queued for transmission via a call to
.Xr SSL_write 3
will still be written in a reliable manner before the end-of-stream is
signalled, assuming the connection remains healthy.
This function can be thought of as appending a logical end-of-stream
marker after any data which has previously been written to the stream
via calls to
.Xr SSL_write 3 .
Further attempts to call
.Xr SSL_write 3
after calling this function will fail.
.Pp
When calling this on a stream, the receive part of the stream remains
unaffected, and the peer may continue to send data until it also signals
the end of the stream.
Thus,
.Xr SSL_read 3
can still be used.
.Pp
.Fa flags
is reserved and should be set to 0.
.Pp
Only the first call to this function has any effect for a given stream;
subsequent calls are no-ops.
This is considered a success case.
.Pp
This function is not supported on an object other than a QUIC stream SSL
object.
.Sh RETURN VALUES
Returns 1 on success and 0 on failure.
.Pp
Returns 0 if called on an SSL object not representing a QUIC stream.
.Sh SEE ALSO
.Xr openssl-quic 7 ,
.Xr ssl 7 ,
.Xr SSL_shutdown_ex 3
.Sh HISTORY
The
.Fn SSL_stream_conclude
function was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2022-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
