.Dd 2025-09-30
.Dt SSL_CONF_CTX_SET1_PREFIX 3ossl
.Os
.Sh NAME
.Nm SSL_CONF_CTX_set1_prefix
.Nd Set configuration context command prefix
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft unsigned int
.Fo SSL_CONF_CTX_set1_prefix
.Fa "SSL_CONF_CTX *cctx"
.Fa "const char *prefix"
.Fc
.Sh DESCRIPTION
The function
.Fn SSL_CONF_CTX_set1_prefix
sets the command prefix of
.Fa cctx
to
.Fa prefix .
If
.Fa prefix
is
.Dv NULL
it is restored to the default value.
.Sh NOTES
Command prefixes alter the commands recognised by subsequent
.Xr SSL_CONF_cmd 3
calls.
For example for files, if the prefix "SSL" is set then command names
such as "SSLProtocol", "SSLOptions" etc.
are recognised instead of "Protocol" and "Options".
Similarly for command lines if the prefix is "--ssl-" then
"--ssl-no_tls1_2" is recognised instead of "-no_tls1_2".
.Pp
If the
.Sy SSL_CONF_FLAG_CMDLINE
flag is set then prefix checks are case sensitive and "-" is the
default.
In the unlikely even an application explicitly wants to set no prefix it
must be explicitly set to "".
.Pp
If the
.Sy SSL_CONF_FLAG_FILE
flag is set then prefix checks are case insensitive and no prefix is the
default.
.Sh RETURN VALUES
.Fn SSL_CONF_CTX_set1_prefix
returns 1 for success and 0 for failure.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CONF_CTX_new 3 ,
.Xr SSL_CONF_CTX_set_flags 3 ,
.Xr SSL_CONF_CTX_set_ssl_ctx 3 ,
.Xr SSL_CONF_cmd 3 ,
.Xr SSL_CONF_cmd_argv 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2012-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
