.Dd 2025-09-30
.Dt SSL_SESSION_GET0_CIPHER 3ossl
.Os
.Sh NAME
.Nm SSL_SESSION_get0_cipher ,
.Nm SSL_SESSION_set_cipher
.Nd set and retrieve the SSL cipher associated with a session
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const SSL_CIPHER *
.Fo SSL_SESSION_get0_cipher
.Fa "const SSL_SESSION *s"
.Fc
.Ft int
.Fo SSL_SESSION_set_cipher
.Fa "SSL_SESSION *s"
.Fa "const SSL_CIPHER *cipher"
.Fc
.Sh DESCRIPTION
.Fn SSL_SESSION_get0_cipher
retrieves the cipher that was used by the connection when the session
was created, or NULL if it cannot be determined.
.Pp
The value returned is a pointer to an object maintained within
.Fa s
and should not be released.
.Pp
.Fn SSL_SESSION_set_cipher
can be used to set the ciphersuite associated with the SSL_SESSION
.Fa s
to
.Fa cipher .
For example, this could be used to set up a session based PSK (see
.Xr SSL_CTX_set_psk_use_session_callback 3 Ns ).
.Sh RETURN VALUES
.Fn SSL_SESSION_get0_cipher
returns the SSL_CIPHER associated with the SSL_SESSION or NULL if it
cannot be determined.
.Pp
.Fn SSL_SESSION_set_cipher
returns 1 on success or 0 on failure.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr d2i_SSL_SESSION 3 ,
.Xr SSL_SESSION_get_time 3 ,
.Xr SSL_SESSION_get0_hostname 3 ,
.Xr SSL_SESSION_free 3 ,
.Xr SSL_CTX_set_psk_use_session_callback 3
.Sh HISTORY
The
.Fn SSL_SESSION_get0_cipher
function was added in OpenSSL 1.1.0. The
.Fn SSL_SESSION_set_cipher
function was added in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2016-2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
