.Dd 2025-09-30
.Dt SSL_CONF_CTX_SET_FLAGS 3ossl
.Os
.Sh NAME
.Nm SSL_CONF_CTX_set_flags ,
.Nm SSL_CONF_CTX_clear_flags
.Nd Set or clear SSL configuration context flags
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft unsigned int
.Fo SSL_CONF_CTX_set_flags
.Fa "SSL_CONF_CTX *cctx"
.Fa "unsigned int flags"
.Fc
.Ft unsigned int
.Fo SSL_CONF_CTX_clear_flags
.Fa "SSL_CONF_CTX *cctx"
.Fa "unsigned int flags"
.Fc
.Sh DESCRIPTION
The function
.Fn SSL_CONF_CTX_set_flags
sets
.Fa flags
in the context
.Fa cctx .
.Pp
The function
.Fn SSL_CONF_CTX_clear_flags
clears
.Fa flags
in the context
.Fa cctx .
.Sh NOTES
The flags set affect how subsequent calls to
.Xr SSL_CONF_cmd 3
or
.Xr SSL_CONF_argv 3
behave.
.Pp
Currently the following
.Fa flags
values are recognised:
.Bl -tag -width Ds
.It SSL_CONF_FLAG_CMDLINE, SSL_CONF_FLAG_FILE
recognise options intended for command line or configuration file use.
At least one of these flags must be set.
.It SSL_CONF_FLAG_CLIENT, SSL_CONF_FLAG_SERVER
recognise options intended for use in SSL/TLS clients or servers.
One or both of these flags must be set.
.It SSL_CONF_FLAG_CERTIFICATE
recognise certificate and private key options.
.It SSL_CONF_FLAG_REQUIRE_PRIVATE
If this option is set then if a private key is not specified for a
certificate it will attempt to load a private key from the certificate
file when
.Xr SSL_CONF_CTX_finish 3
is called.
If a key cannot be loaded from the certificate file an error occurs.
.It SSL_CONF_FLAG_SHOW_ERRORS
indicate errors relating to unrecognised options or missing arguments in
the error queue.
If this option isn't set such errors are only reflected in the return
values of
.Xr SSL_CONF_set_cmd 3
or
.Xr SSL_CONF_set_argv 3
.El
.Sh RETURN VALUES
.Fn SSL_CONF_CTX_set_flags
and
.Fn SSL_CONF_CTX_clear_flags
returns the new flags value after setting or clearing flags.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CONF_CTX_new 3 ,
.Xr SSL_CONF_CTX_set_ssl_ctx 3 ,
.Xr SSL_CONF_CTX_set1_prefix 3 ,
.Xr SSL_CONF_cmd 3 ,
.Xr SSL_CONF_cmd_argv 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2012-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
