.Dd 2025-09-30
.Dt SSL_SET_SESSION 3ossl
.Os
.Sh NAME
.Nm SSL_set_session
.Nd set a TLS/SSL session to be used during TLS/SSL connect
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_set_session
.Fa "SSL *ssl"
.Fa "SSL_SESSION *session"
.Fc
.Sh DESCRIPTION
.Fn SSL_set_session
sets
.Fa session
to be used when the TLS/SSL connection is to be established.
.Fn SSL_set_session
is only useful for TLS/SSL clients.
When the session is set, the reference count of
.Fa session
is incremented by 1. If the session is not reused, the reference count
is decremented again during
.Xr SSL_connect 3 .
Whether the session was reused can be queried with the
.Xr SSL_session_reused 3
call.
.Pp
If there is already a session set inside
.Fa ssl
(because it was set with
.Fn SSL_set_session
before or because the same
.Fa ssl
was already used for a connection),
.Xr SSL_SESSION_free 3
will be called for that session.
This is also the case when
.Fa session
is a NULL pointer.
If that old session is still
.Sy open ,
it is considered bad and will be removed from the session cache (if
used).
A session is considered open, if
.Xr SSL_shutdown 3
was not called for the connection (or at least
.Xr SSL_set_shutdown 3
was used to set the SSL_SENT_SHUTDOWN state).
.Sh NOTES
SSL_SESSION objects keep internal link information about the session
cache list, when being inserted into one SSL_CTX object's session cache.
One SSL_SESSION object, regardless of its reference count, must
therefore only be used with one SSL_CTX object (and the SSL objects
created from this SSL_CTX object).
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It 0
The operation failed; check the error stack to find out the reason.
.It 1
The operation succeeded.
.El
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_SESSION_free 3 ,
.Xr SSL_get_session 3 ,
.Xr SSL_session_reused 3 ,
.Xr SSL_CTX_set_session_cache_mode 3
.Sh COPYRIGHT
Copyright 2000-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
