.Dd 2025-09-30
.Dt SSL_CTX_GET_VERIFY_MODE 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_get_verify_mode ,
.Nm SSL_get_verify_mode ,
.Nm SSL_CTX_get_verify_depth ,
.Nm SSL_get_verify_depth ,
.Nm SSL_get_verify_callback ,
.Nm SSL_CTX_get_verify_callback
.Nd get currently set verification parameters
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_get_verify_mode
.Fa "const SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_get_verify_mode
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_CTX_get_verify_depth
.Fa "const SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_get_verify_depth
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo 
.Fa "*SSL_CTX_get_verify_callback(const SSL_CTX *ctx)"
.Fc
(int, X509_STORE_CTX *);
.Ft int
.Fo 
.Fa "*SSL_get_verify_callback(const SSL *ssl)"
.Fc
(int, X509_STORE_CTX *);
.Sh DESCRIPTION
.Fn SSL_CTX_get_verify_mode
returns the verification mode currently set in
.Fa ctx .
.Pp
.Fn SSL_get_verify_mode
returns the verification mode currently set in
.Fa ssl .
.Pp
.Fn SSL_CTX_get_verify_depth
returns the verification depth limit currently set in
.Fa ctx .
If no limit has been explicitly set, -1 is returned and the default
value will be used.
.Pp
.Fn SSL_get_verify_depth
returns the verification depth limit currently set in
.Fa ssl .
If no limit has been explicitly set, -1 is returned and the default
value will be used.
.Pp
.Xr SSL_CTX_get_verify_callback 3
returns a function pointer to the verification callback currently set in
.Fa ctx .
If no callback was explicitly set, the NULL pointer is returned and the
default callback will be used.
.Pp
.Xr SSL_get_verify_callback 3
returns a function pointer to the verification callback currently set in
.Fa ssl .
If no callback was explicitly set, the NULL pointer is returned and the
default callback will be used.
.Sh RETURN VALUES
See DESCRIPTION
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_verify 3
.Sh COPYRIGHT
Copyright 2000-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
