.Dd 2025-09-30
.Dt SSL_CTX_SESS_SET_GET_CB 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_sess_set_new_cb ,
.Nm SSL_CTX_sess_set_remove_cb ,
.Nm SSL_CTX_sess_set_get_cb ,
.Nm SSL_CTX_sess_get_new_cb ,
.Nm SSL_CTX_sess_get_remove_cb ,
.Nm SSL_CTX_sess_get_get_cb
.Nd provide callback functions for server side external session caching
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_CTX_sess_set_new_cb
.Fa "SSL_CTX *ctx"
.Fa "int (*new_session_cb)(SSL *"
.Fa "SSL_SESSION *)"
.Fc
.Ft void
.Fo SSL_CTX_sess_set_remove_cb
.Fa "SSL_CTX *ctx"
.Fa "void (*remove_session_cb)(SSL_CTX *ctx"
.Fa "SSL_SESSION *)"
.Fc
.Ft void
.Fo SSL_CTX_sess_set_get_cb
.Fa "SSL_CTX *ctx"
.Fa "SSL_SESSION (*get_session_cb)(SSL *"
.Fa "const unsigned char *"
.Fa int
.Fa "int *)"
.Fc
.Ft int
.Fo 
.Fa "*SSL_CTX_sess_get_new_cb(SSL_CTX *ctx)"
.Fc
(struct ssl_st *ssl,
.Bd -literal
                                              SSL_SESSION *sess);
 void (*SSL_CTX_sess_get_remove_cb(SSL_CTX *ctx))(struct ssl_ctx_st *ctx,
                                                  SSL_SESSION *sess);
 SSL_SESSION *(*SSL_CTX_sess_get_get_cb(SSL_CTX *ctx))(struct ssl_st *ssl,
                                                       const unsigned char *data,
                                                       int len, int *copy);
.Ed
.Sh DESCRIPTION
.Fn SSL_CTX_sess_set_new_cb
sets the callback function that is called whenever a new session was
negotiated.
.Pp
.Fn SSL_CTX_sess_set_remove_cb
sets the callback function that is called whenever a session is removed
by the SSL engine.
For example, this can occur because a session is considered faulty or
has become obsolete because of exceeding the timeout value.
.Pp
.Fn SSL_CTX_sess_set_get_cb
sets the callback function that is called whenever a TLS client proposed
to resume a session but the session could not be found in the internal
session cache (see
.Xr SSL_CTX_set_session_cache_mode 3 Ns ).
(TLS server only.)
.Pp
.Xr SSL_CTX_sess_get_new_cb 3 ,
.Xr SSL_CTX_sess_get_remove_cb 3 ,
and
.Xr SSL_CTX_sess_get_get_cb 3
retrieve the function pointers set by the corresponding set callback
functions.
If a callback function has not been set, the NULL pointer is returned.
.Sh NOTES
In order to allow external session caching, synchronization with the
internal session cache is realized via callback functions.
Inside these callback functions, session can be saved to disk or put
into a database using the
.Xr d2i_SSL_SESSION 3
interface.
.Pp
The
.Xr new_session_cb 3
is called whenever a new session has been negotiated and session caching
is enabled (see
.Xr SSL_CTX_set_session_cache_mode 3 Ns ).
The
.Xr new_session_cb 3
is passed the
.Sy ssl
connection and the nascent ssl session
.Sy sess .
Since sessions are reference-counted objects, the reference count on the
session is incremented before the callback, on behalf of the
application.
If the callback returns
.Sy 0 ,
the session will be immediately removed from the internal cache and the
reference count released.
If the callback returns
.Sy 1 ,
the application retains the reference (for an entry in the
application-maintained "external session cache"), and is responsible for
calling
.Xr SSL_SESSION_free 3
when the session reference is no longer in use.
.Pp
Note that in TLSv1.3, sessions are established after the main handshake
has completed.
The server decides when to send the client the session information and
this may occur some time after the end of the handshake (or not at all).
This means that applications should expect the
.Xr new_session_cb 3
function to be invoked during the handshake (for <= TLSv1.2) or after
the handshake (for TLSv1.3). It is also possible in TLSv1.3 for multiple
sessions to be established with a single connection.
In these case the
.Xr new_session_cb 3
function will be invoked multiple times.
.Pp
In TLSv1.3 it is recommended that each SSL_SESSION object is only used
for resumption once.
One way of enforcing that is for applications to call
.Xr SSL_CTX_remove_session 3
after a session has been used.
.Pp
The
.Xr remove_session_cb 3
is called whenever the SSL engine removes a session from the internal
cache.
This can happen when the session is removed because it is expired or
when a connection was not shutdown cleanly.
It also happens for all sessions in the internal session cache when
.Xr SSL_CTX_free 3
is called.
The
.Xr remove_session_cb 3
is passed the
.Fa ctx
and the ssl session
.Sy sess .
It does not provide any feedback.
.Pp
The
.Xr get_session_cb 3
is only called on SSL/TLS servers, and is given the session id proposed
by the client.
The
.Xr get_session_cb 3
is always called, even when session caching was disabled.
The
.Xr get_session_cb 3
is passed the
.Sy ssl
connection and the session id of length
.Sy length
at the memory location
.Sy data .
By setting the parameter
.Sy copy
to
.Sy 1 ,
the callback can require the SSL engine to increment the reference count
of the SSL_SESSION object; setting
.Sy copy
to
.Sy 0
causes the reference count to remain unchanged.
If the
.Xr get_session_cb 3
does not write to
.Sy copy ,
the reference count is incremented and the session must be explicitly
freed with
.Xr SSL_SESSION_free 3 .
.Sh RETURN VALUES
.Xr SSL_CTX_sess_get_new_cb 3 ,
.Xr SSL_CTX_sess_get_remove_cb 3
and
.Xr SSL_CTX_sess_get_get_cb 3
return different callback function pointers respectively.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr d2i_SSL_SESSION 3 ,
.Xr SSL_CTX_set_session_cache_mode 3 ,
.Xr SSL_CTX_flush_sessions 3 ,
.Xr SSL_SESSION_free 3 ,
.Xr SSL_CTX_free 3
.Sh COPYRIGHT
Copyright 2001-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
