.Dd 2025-09-30
.Dt SSL_SESSION_GET0_PEER 3ossl
.Os
.Sh NAME
.Nm SSL_SESSION_get0_peer
.Nd get details about peer's certificate for a session
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft X509 *
.Fo SSL_SESSION_get0_peer
.Fa "SSL_SESSION *s"
.Fc
.Sh DESCRIPTION
.Fn SSL_SESSION_get0_peer
returns the peer certificate associated with the session
.Fa s
or NULL if no peer certificate is available.
The caller should not free the returned value (unless
.Xr X509_up_ref 3
has also been called).
.Sh RETURN VALUES
.Fn SSL_SESSION_get0_peer
returns a pointer to the peer certificate or NULL if no peer certificate
is available.
.Sh SEE ALSO
.Xr ssl 7
.Sh COPYRIGHT
Copyright 2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
