.Dd 2025-09-30
.Dt SSL_COMP_ADD_COMPRESSION_METHOD 3ossl
.Os
.Sh NAME
.Nm SSL_COMP_add_compression_method ,
.Nm SSL_COMP_get_compression_methods ,
.Nm SSL_COMP_get0_name ,
.Nm SSL_COMP_get_id ,
.Nm SSL_COMP_free_compression_methods
.Nd handle SSL/TLS integrated compression methods
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_COMP_add_compression_method
.Fa "int id"
.Fa "COMP_METHOD *cm"
.Fc
.Bd -literal
 STACK_OF(SSL_COMP) *SSL_COMP_get_compression_methods(void);
 const char *SSL_COMP_get0_name(const SSL_COMP *comp);
 int SSL_COMP_get_id(const SSL_COMP *comp);
.Ed
The following function has been deprecated since OpenSSL 1.1.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft void
.Fo SSL_COMP_free_compression_methods
.Fa void
.Fc
.Sh DESCRIPTION
.Fn SSL_COMP_add_compression_method
adds the compression method
.Fa cm
with the identifier
.Fa id
to the list of available compression methods.
This list is globally maintained for all SSL operations within this
application.
It cannot be set for specific SSL_CTX or SSL objects.
.Pp
.Xr SSL_COMP_get_compression_methods 3
returns a stack of all of the available compression methods or NULL on
error.
.Pp
.Xr SSL_COMP_get0_name 3
returns the name of the compression method
.Sy comp .
.Pp
.Xr SSL_COMP_get_id 3
returns the id of the compression method
.Sy comp .
.Pp
.Fn SSL_COMP_free_compression_methods
releases any resources acquired to maintain the internal table of
compression methods.
.Sh NOTES
The TLS standard (or SSLv3) allows the integration of compression
methods into the communication.
The TLS RFC does however not specify compression methods or their
corresponding identifiers, so there is currently no compatible way to
integrate compression with unknown peers.
It is therefore currently not recommended to integrate compression into
applications.
Applications for non-public use may agree on certain compression
methods.
Using different compression methods with the same identifier will lead
to connection failure.
.Pp
An OpenSSL client speaking a protocol that allows compression (SSLv3,
TLSv1) will unconditionally send the list of all compression methods
enabled with
.Fn SSL_COMP_add_compression_method
to the server during the handshake.
Unlike the mechanisms to set a cipher list, there is no method available
to restrict the list of compression method on a per connection basis.
.Pp
An OpenSSL server will match the identifiers listed by a client against
its own compression methods and will unconditionally activate
compression when a matching identifier is found.
There is no way to restrict the list of compression methods supported on
a per connection basis.
.Pp
If enabled during compilation, the OpenSSL library will have the
following compression methods available:
.Bl -tag -width Ds
.It COMP_zlib()
.It COMP_brotli()
.It COMP_brotli_oneshot()
.It COMP_zstd()
.It COMP_zstd_oneshot()
.El
.Sh RETURN VALUES
.Fn SSL_COMP_add_compression_method
may return the following values:
.Bl -tag -width Ds
.It 0
The operation succeeded.
.It 1
The operation failed.
Check the error queue to find out the reason.
.El
.Pp
.Xr SSL_COMP_get_compression_methods 3
returns the stack of compressions methods or NULL on error.
.Pp
.Xr SSL_COMP_get0_name 3
returns the name of the compression method or NULL on error.
.Pp
.Xr SSL_COMP_get_id 3
returns the name of the compression method or -1 on error.
.Sh SEE ALSO
.Xr ssl 7
.Sh HISTORY
The
.Fn SSL_COMP_free_compression_methods
function was deprecated in OpenSSL 1.1.0. The
.Xr SSL_COMP_get0_name 3
and
.Xr SSL_comp_get_id 3
functions were added in OpenSSL 1.1.0d.
.Sh COPYRIGHT
Copyright 2001-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
