.Dd 2025-09-30
.Dt SSL_GET_PEER_SIGNATURE_NID 3ossl
.Os
.Sh NAME
.Nm SSL_get0_peer_signature_name ,
.Nm SSL_get_peer_signature_nid ,
.Nm SSL_get_peer_signature_type_nid ,
.Nm SSL_get0_signature_name ,
.Nm SSL_get_signature_nid ,
.Nm SSL_get_signature_type_nid
.Nd get TLS message signing types
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_get0_peer_signature_name
.Fa "const SSL *ssl"
.Fa "const char **sigalg"
.Fc
.Ft int
.Fo SSL_get_peer_signature_nid
.Fa "SSL *ssl"
.Fa "int *psig_nid"
.Fc
.Ft int
.Fo SSL_get_peer_signature_type_nid
.Fa "const SSL *ssl"
.Fa "int *psigtype_nid"
.Fc
.Ft int
.Fo SSL_get0_signature_name
.Fa "SSL *ssl"
.Fa "const char **sigalg"
.Fc
.Ft int
.Fo SSL_get_signature_nid
.Fa "SSL *ssl"
.Fa "int *psig_nid"
.Fc
.Ft int
.Fo SSL_get_signature_type_nid
.Fa "const SSL *ssl"
.Fa "int *psigtype_nid"
.Fc
.Sh DESCRIPTION
.Fn SSL_get0_peer_signature_name
sets
.Em *sigalg
to the IANA name of the
.Lk https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme
used by the peer to sign the TLS handshake.
The caller must not free the returned pointer.
The returned string should be copied if it is to be retained beyond the
lifetime of the SSL connection.
.Pp
.Fn SSL_get_peer_signature_nid
sets
.Sy *psig_nid
to the NID of the digest used by the peer to sign TLS messages.
It is implemented as a macro.
.Pp
.Fn SSL_get_peer_signature_type_nid
sets
.Sy *psigtype_nid
to the signature type used by the peer to sign TLS messages.
Currently the signature type is the NID of the public key type used for
signing except for PSS signing where it is
.Sy EVP_PKEY_RSA_PSS .
To differentiate between
.Sy rsa_pss_rsae_*
and
.Sy rsa_pss_pss_*
signatures, it's necessary to check the type of public key in the peer's
certificate.
.Pp
.Fn SSL_get0_signature_name ,
.Fn SSL_get_signature_nid
and
.Fn SSL_get_signature_type_nid
return the equivalent information for the local end of the connection.
.Sh RETURN VALUES
These functions return 1 for success and 0 for failure.
There are several possible reasons for failure: the peer or local end is
a client and did not sign the handshake (did not use a client
certificate), the cipher suite has no signature (e.g.
it uses RSA key exchange or is anonymous), the TLS version is below 1.2
or the functions were called too early, e.g.
before the peer signed a message.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_get_peer_certificate 3 ,
.Sh HISTORY
The
.Fn SSL_get0_peer_signature_name
and
.Fn SSL_get0_signature_name
functions were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2017-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
