.Dd 2025-09-30
.Dt SSL_GET_ALL_ASYNC_FDS 3ossl
.Os
.Sh NAME
.Nm SSL_waiting_for_async ,
.Nm SSL_get_all_async_fds ,
.Nm SSL_get_changed_async_fds
.Nd manage asynchronous operations
.Sh SYNOPSIS
.In openssl/async.h
.In openssl/ssl.h
.Ft int
.Fo SSL_waiting_for_async
.Fa "SSL *s"
.Fc
.Ft int
.Fo SSL_get_all_async_fds
.Fa "SSL *s"
.Fa "OSSL_ASYNC_FD *fd"
.Fa "size_t *numfds"
.Fc
.Ft int
.Fo SSL_get_changed_async_fds
.Fa "SSL *s"
.Fa "OSSL_ASYNC_FD *addfd"
.Fa "size_t *numaddfds"
.Fa "OSSL_ASYNC_FD *delfd"
.Fa "size_t *numdelfds"
.Fc
.Sh DESCRIPTION
.Fn SSL_waiting_for_async
determines whether an SSL connection is currently waiting for
asynchronous operations to complete (see the
.Sy SSL_MODE_ASYNC
mode in
.Xr SSL_CTX_set_mode 3 Ns ).
.Pp
.Fn SSL_get_all_async_fds
returns a list of file descriptor which can be used in a call to
.Xr select 3
or
.Xr poll 3
to determine whether the current asynchronous operation has completed or
not.
A completed operation will result in data appearing as "read ready" on
the file descriptor (no actual data should be read from the file
descriptor).
This function should only be called if the
.Vt SSL
object is currently waiting for asynchronous work to complete (i.e.
.Sy SSL_ERROR_WANT_ASYNC
has been received - see
.Xr SSL_get_error 3 Ns ).
Typically the list will only contain one file descriptor.
However, if multiple asynchronous capable engines are in use then more
than one is possible.
The number of file descriptors returned is stored in
.Em *numfds
and the file descriptors themselves are in
.Em *fds .
The
.Em fds
parameter may be NULL in which case no file descriptors are returned but
.Em *numfds
is still populated.
It is the callers responsibility to ensure sufficient memory is
allocated at
.Em *fds
so typically this function is called twice (once with a NULL
.Em fds
parameter and once without).
.Pp
.Fn SSL_get_changed_async_fds
returns a list of the asynchronous file descriptors that have been added
and a list that have been deleted since the last
.Sy SSL_ERROR_WANT_ASYNC
was received (or since the
.Vt SSL
object was created if no
.Sy SSL_ERROR_WANT_ASYNC
has been received).
Similar to
.Fn SSL_get_all_async_fds
it is the callers responsibility to ensure that
.Em *addfd
and
.Em *delfd
have sufficient memory allocated, although they may be NULL. The number
of added fds and the number of deleted fds are stored in
.Em *numaddfds
and
.Em *numdelfds
respectively.
.Sh RETURN VALUES
.Fn SSL_waiting_for_async
will return 1 if the current SSL operation is waiting for an async
operation to complete and 0 otherwise.
.Pp
.Fn SSL_get_all_async_fds
and
.Fn SSL_get_changed_async_fds
return 1 on success or 0 on error.
.Sh NOTES
On Windows platforms the
.Pa <openssl/async.h>
header is dependent on some of the types customarily made available by
including
.Pa <windows.h> .
The application developer is likely to require control over when the
latter is included, commonly as one of the first included headers.
Therefore, it is defined as an application developer's responsibility to
include
.Pa <windows.h>
prior to
.Pa <openssl/async.h> .
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_get_error 3 ,
.Xr SSL_CTX_set_mode 3
.Sh HISTORY
The
.Fn SSL_waiting_for_async ,
.Fn SSL_get_all_async_fds
and
.Fn SSL_get_changed_async_fds
functions were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2016-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
