.Dd 2025-09-30
.Dt SSL_ACCEPT 3ossl
.Os
.Sh NAME
.Nm SSL_accept
.Nd wait for a TLS/SSL client to initiate a TLS/SSL handshake
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_accept
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_accept
waits for a TLS/SSL client to initiate the TLS/SSL handshake.
The communication channel must already have been set and assigned to the
.Fa ssl
by setting an underlying
.Sy BIO .
.Sh NOTES
The behaviour of
.Fn SSL_accept
depends on the underlying BIO.
.Pp
If the underlying BIO is
.Sy blocking ,
.Fn SSL_accept
will only return once the handshake has been finished or an error
occurred.
.Pp
If the underlying BIO is
.Sy nonblocking ,
.Fn SSL_accept
will also return when the underlying BIO could not satisfy the needs of
.Fn SSL_accept
to continue the handshake, indicating the problem by the return value
-1. In this case a call to
.Xr SSL_get_error 3
with the return value of
.Fn SSL_accept
will yield
.Sy SSL_ERROR_WANT_READ
or
.Sy SSL_ERROR_WANT_WRITE .
The calling process then must repeat the call after taking appropriate
action to satisfy the needs of
.Fn SSL_accept .
The action depends on the underlying BIO. When using a nonblocking
socket, nothing is to be done, but
.Xr select 3
can be used to check for the required condition.
When using a buffering BIO, like a BIO pair, data must be written into
or retrieved out of the BIO before being able to continue.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It 0
The TLS/SSL handshake was not successful but was shut down controlled
and by the specifications of the TLS/SSL protocol.
Call
.Xr SSL_get_error 3
with the return value
.Sy ret
to find out the reason.
.It 1
The TLS/SSL handshake was successfully completed, a TLS/SSL connection
has been established.
.It \(la0
The TLS/SSL handshake was not successful because a fatal error occurred
either at the protocol level or a connection failure occurred.
The shutdown was not clean.
It can also occur if action is needed to continue the operation for
nonblocking BIOs.
Call
.Xr SSL_get_error 3
with the return value
.Sy ret
to find out the reason.
.El
.Sh SEE ALSO
.Xr SSL_get_error 3 ,
.Xr SSL_connect 3 ,
.Xr SSL_shutdown 3 ,
.Xr ssl 7 ,
.Xr bio 7 ,
.Xr SSL_set_connect_state 3 ,
.Xr SSL_do_handshake 3 ,
.Xr SSL_CTX_new 3
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
