.Dd 2025-09-30
.Dt SSL_POLL 3ossl
.Os
.Sh NAME
.Nm SSL_poll ,
.Nm SSL_POLL_EVENT_NONE ,
.Nm SSL_POLL_EVENT_F ,
.Nm SSL_POLL_EVENT_EL ,
.Nm SSL_POLL_EVENT_EC ,
.Nm SSL_POLL_EVENT_ECD ,
.Nm SSL_POLL_EVENT_ER ,
.Nm SSL_POLL_EVENT_EW ,
.Nm SSL_POLL_EVENT_R ,
.Nm SSL_POLL_EVENT_W ,
.Nm SSL_POLL_EVENT_IC ,
.Nm SSL_POLL_EVENT_ISB ,
.Nm SSL_POLL_EVENT_ISU ,
.Nm SSL_POLL_EVENT_OSB ,
.Nm SSL_POLL_EVENT_OSU ,
.Nm SSL_POLL_EVENT_RW ,
.Nm SSL_POLL_EVENT_RE ,
.Nm SSL_POLL_EVENT_WE ,
.Nm SSL_POLL_EVENT_RWE ,
.Nm SSL_POLL_EVENT_E ,
.Nm SSL_POLL_EVENT_IS ,
.Nm SSL_POLL_EVENT_ISE ,
.Nm SSL_POLL_EVENT_I ,
.Nm SSL_POLL_EVENT_OS ,
.Nm SSL_POLL_EVENT_OSE ,
.Nm SSL_POLL_FLAG_NO_HANDLE_EVENTS
.Nd determine or await readiness conditions for one or more pollable objects
.Sh SYNOPSIS
.In openssl/ssl.h
.Fd #define SSL_POLL_EVENT_NONE        0
.Fd #define SSL_POLL_EVENT_F           /* F   (Failure) */
.Fd #define SSL_POLL_EVENT_EL          /* EL  (Exception on Listener) */
.Fd #define SSL_POLL_EVENT_EC          /* EC  (Exception on Conn) */
.Fd #define SSL_POLL_EVENT_ECD         /* ECD (Exception on Conn Drained) */
.Fd #define SSL_POLL_EVENT_ER          /* ER  (Exception on Read) */
.Fd #define SSL_POLL_EVENT_EW          /* EW  (Exception on Write) */
.Fd #define SSL_POLL_EVENT_R           /* R   (Readable) */
.Fd #define SSL_POLL_EVENT_W           /* W   (Writable) */
.Fd #define SSL_POLL_EVENT_IC          /* IC  (Incoming Connection) */
.Fd #define SSL_POLL_EVENT_ISB         /* ISB (Incoming Stream: Bidi) */
.Fd #define SSL_POLL_EVENT_ISU         /* ISU (Incoming Stream: Uni) */
.Fd #define SSL_POLL_EVENT_OSB         /* OSB (Outgoing Stream: Bidi) */
.Fd #define SSL_POLL_EVENT_OSU         /* OSU (Outgoing Stream: Uni) */
.Fd #define SSL_POLL_EVENT_RW          /* R   | W               */
.Fd #define SSL_POLL_EVENT_RE          /* R   | ER              */
.Fd #define SSL_POLL_EVENT_WE          /* W   | EW              */
.Fd #define SSL_POLL_EVENT_RWE         /* RE  | WE              */
.Fd #define SSL_POLL_EVENT_E           /* EL  | EC  | ER  | EW  */
.Fd #define SSL_POLL_EVENT_IS          /* ISB | ISU             */
.Fd #define SSL_POLL_EVENT_ISE         /* IS  | EC              */
.Fd #define SSL_POLL_EVENT_I           /* IS                    */
.Fd #define SSL_POLL_EVENT_OS          /* OSB | OSU             */
.Fd #define SSL_POLL_EVENT_OSE         /* OS  | EC              */
.Ft typedef struct ssl_poll_item_st {
     BIO_POLL_DESCRIPTOR desc;
     uint64_t            events, revents;
 } SSL_POLL_ITEM;

 #define SSL_POLL_FLAG_NO_HANDLE_EVENTS

 int
.Fo SSL_poll
.Fa "SSL_POLL_ITEM         *items"
.Fa "size_t                num_items"
.Fa "size_t                stride"
.Fa "const struct timeval  *timeout"
.Fa "uint64_t              flags"
.Fa "size_t                *result_count"
.Fc
.Sh DESCRIPTION
.Fn SSL_poll
allows the readiness conditions of the resources represented by one or
more BIO_POLL_DESCRIPTOR structures to be determined.
In particular, it can be used to query for readiness conditions on QUIC
connection SSL objects and QUIC stream SSL objects in a single call.
It can also be used to block until at least one of the given resources
is ready.
.Pp
A call to
.Fn SSL_poll
specifies an array of
.Vt SSL_POLL_ITEM
structures, each of which designates a resource which is being polled
for readiness, and a set of event flags which indicate the specific
readiness events which the caller is interested in in relation to the
specified resource.
.Pp
The fields of
.Vt SSL_POLL_ITEM
are as follows:
.Bl -tag -width Ds
.It Em desc
The resource being polled for readiness, as represented by a
.Sy BIO_POLL_DESCRIPTOR .
Currently, this must be a poll descriptor of type
.Sy BIO_POLL_DESCRIPTOR_TYPE_SSL ,
representing an SSL object pointer, and the SSL object must be a QUIC
connection SSL object or QUIC stream SSL object.
.Pp
If a
.Vt SSL_POLL_ITEM
has a poll descriptor type of
.Sy BIO_POLL_DESCRIPTOR_TYPE_NONE ,
or the SSL object pointer is NULL, the
.Vt SSL_POLL_ITEM
array entry is ignored and
.Em revents
will be set to 0 on return.
.It Em events
This is the set of zero or more events which the caller is interested in
learning about in relation to the resource described by
.Em desc .
It is a collection of zero or more
.Sy SSL_POLL_EVENT
flags.
See
.Sx EVENT TYPES
for a description of each of the event types.
.It Em revents
After
.Fn SSL_poll
returns, this is the set of zero or more events which are actually
applicable to the resource described by
.Em desc .
As for
.Em events ,
it is a collection of zero or more
.Sy SSL_POLL_EVENT
flags.
.Pp
.Em revents
need not be a subset of the events specified in
.Em events ,
as some event types are defined as always being enabled (non-maskable).
See
.Sx EVENT
TYPES
for more information.
.El
.Pp
To use
.Fn SSL_poll ,
call it with an array of
.Vt SSL_POLL_ITEM
structures.
The array need remain allocated only for the duration of the call.
.Fa num_items
must be set to the number of entries in the array, and
.Fa stride
must be set to
.Qo Li sizeof(SSL_POLL_ITEM) Qc .
.Pp
The
.Fa timeout
argument specifies the timeout to use, and, implicitly, whether to use
.Fn SSL_poll
in blocking or nonblocking mode:
.Bl -bullet
.It
If
.Fa timeout
is NULL, the function blocks indefinitely until at least one resource is
ready.
.It
If
.Fa timeout
is non-NULL, and it points to a
.Sy struct timeval
which is set to zero, the function operates in nonblocking mode and
returns immediately with readiness information.
.It
If
.Fa timeout
is non-NULL, and it points to a
.Sy struct timeval
which is set to a value other than zero, the function blocks for the
specified interval or until at least one of the specified resources is
ready, whichever comes first.
.El
.Pp
The present implementation of
.Fn SSL_poll
is a subset of the functionality which will eventually be available.
For more information, see
.Sx LIMITATIONS .
.Pp
The following flags are currently defined for the
.Fa flags
argument:
.Bl -tag -width Ds
.It Sy SSL_POLL_FLAG_NO_HANDLE_EVENTS
This flag indicates that internal state machine processing should not be
performed in an attempt to generate new readiness events.
Only existing readiness events will be reported.
.Pp
If this flag is used in nonblocking mode (with a timeout of zero), no
internal state machine processing is performed.
.Pp
If this flag is used in blocking mode (for example, with
.Fa timeout
set to NULL), event processing does not occur unless the function
blocks.
.El
.Pp
The
.Fa result_count
argument is optional.
If it is non-NULL, it is used to output the number of entries in the
array which have nonzero
.Em revents
fields when the call to
.Fn SSL_poll
returns; see
.Sx RETURN VALUES
for details.
.Sh EVENT TYPES
The
.Fn SSL_poll
interface reports zero or more event types on a given resource,
represented by a bit mask.
.Pp
All of the event types are level triggered and represent a readiness or
permanent exception condition; as such, after an event has been reported
by
.Fn SSL_poll
for a resource, it will continue to be reported in future
.Fn SSL_poll
calls until the condition ceases to be in effect.
A caller must mask the given event type bit in future
.Fn SSL_poll
calls if it does not wish to receive repeated notifications and has not
caused the underlying readiness condition (for example, consuming all
available data using
.Xr SSL_read_ex 3
after
.Sy SSL_POLL_EVENT_R
is reported) to be deasserted.
.Pp
Some event types do not make sense on a given kind of resource.
In this case, specifying that event type in
.Em events
is a no-op and will be ignored, and the given event will never be
reported in
.Em revents .
.Pp
Failure of the polling mechanism itself is considered distinct from an
exception condition on a resource which was successfully polled.
See
.Sy SSL_POLL_EVENT_F
and
.Sx RETURN VALUES
for details.
.Pp
In general, an application should always listen for the event types
corresponding to exception conditions if it is listening to the
corresponding non-exception event types (e.g.
.Sy SSL_POLL_EVENT_EC
and
.Sy SSL_POLL_EVENT_ER
for
.Sy SSL_POLL_EVENT_R Ns ),
as not doing so is unlikely to be a sound design.
.Pp
Some event types are non-maskable and may be reported in
.Em revents
regardless of whether they were requested in
.Em events .
.Pp
The following event types are supported:
.Bl -tag -width Ds
.It Sy SSL_POLL_EVENT_F
Polling failure.
This event is raised when a resource could not be polled.
It is distinct from an exception condition reported on a resource which
was successfully polled and represents a failure of the polling process
itself in relation to a resource.
This may mean that
.Fn SSL_poll
does not support the kind of resource specified.
.Pp
Where this event is raised on at least one item in
.Fa items ,
.Fn SSL_poll
will return 0 and the ERR stack will contain information pertaining to
the first item in
.Fa items
with
.Sy SSL_POLL_EVENT_F
set.
See
.Sx RETURN VALUES
for more information.
.Pp
This event type may be raised even if it was not requested in
.Em events ;
specifying this event type in
.Em events
does nothing.
.It Sy SSL_POLL_EVENT_EL
Error at listener level.
This event is raised when a listener has failed, for example if a
network BIO has encountered a permanent error.
.Pp
This event is never raised on objects which are not listeners, but its
occurrence will cause
.Sy SSL_POLL_EVENT_EC
to be raised on all dependent connections.
.It Sy SSL_POLL_EVENT_EC
Error at connection level.
This event is raised when a connection has failed.
In particular, it is raised when a connection begins terminating.
.Pp
This event is never raised on objects which are not connections.
.It Sy SSL_POLL_EVENT_ECD
Error at connection level (drained).
This event is raised when a connection has finished terminating, and has
reached the terminated state.
This event will generally occur after an interval of time passes after
the
.Sy SSL_POLL_EVENT_EC
event is raised on a connection.
.Pp
This event is never raised on objects which are not connections.
.It Sy SSL_POLL_EVENT_ER
Error in read direction.
For QUIC, this is raised only in the event that a stream has a read part
and that read part has been reset by the peer (for example, using a
.Sy RESET_STREAM
frame).
.It Sy SSL_POLL_EVENT_EW
Error in write direction.
For QUIC, this is raised only in the event that a stream has a write
part and that write part has been reset by the peer using a
.Sy STOP_SENDING
frame.
.It Sy SSL_POLL_EVENT_R
Readable.
This event is raised when a QUIC stream SSL object (or a QUIC connection
SSL object with a default stream attached) has application data waiting
to be read using
.Xr SSL_read_ex 3 ,
or a FIN event as represented by
.Sy SSL_ERROR_ZERO_RETURN
waiting to be read.
.Pp
It is not raised in the event of the receiving part of the QUIC stream
being reset by the peer; see
.Sy SSL_POLL_EVENT_ER .
.It Sy SSL_POLL_EVENT_W
Writable.
This event is raised when a QUIC stream SSL object (or a QUIC connection
SSL object with a default stream attached) could accept more application
data using
.Xr SSL_write_ex 3 .
.Pp
This event is never raised by a receive-only stream.
.Pp
This event is never raised by a stream which has had its send part
concluded normally (as with
.Xr SSL_stream_conclude 3 )
or locally reset (as with
.Xr SSL_stream_reset 3 Ns ).
.Pp
This event does not guarantee that a subsequent call to
.Xr SSL_write_ex 3
will succeed.
.It Sy SSL_POLL_EVENT_IC
This event, which is only raised by a QUIC listener SSL object, is
raised when one or more incoming QUIC connections are available to be
accepted using
.Xr SSL_accept_connection 3 .
.It Sy SSL_POLL_EVENT_ISB
This event, which is only raised by a QUIC connection SSL object, is
raised when one or more incoming bidirectional streams are available to
be accepted using
.Xr SSL_accept_stream 3 .
.It Sy SSL_POLL_EVENT_ISU
This event, which is only raised by a QUIC connection SSL object, is
raised when one or more incoming unidirectional streams are available to
be accepted using
.Xr SSL_accept_stream 3 .
.It Sy SSL_POLL_EVENT_OSB
This event, which is only raised by a QUIC connection SSL object, is
raised when QUIC stream creation flow control currently permits at least
one additional bidirectional stream to be locally created.
.It Sy SSL_POLL_EVENT_OSU
This event, which is only raised by a QUIC connection SSL object, is
raised when QUIC stream creation flow control currently permits at least
one additional unidirectional stream to be locally created.
.El
.Sh LIMITATIONS
.Fn SSL_poll
as presently implemented has the following limitation:
.Bl -tag -width Ds
.It
Only
.Sy BIO_POLL_DESCRIPTOR
structures with type
.Sy BIO_POLL_DESCRIPTOR_TYPE_SSL ,
referencing QUIC listener, connection or stream SSL objects, are
supported.
.El
.Pp
This limitation may be revised in a future release of OpenSSL.
.Sh RETURN VALUES
.Fn SSL_poll
returns 1 on success and 0 on failure.
.Pp
Unless the
.Fa items
pointer itself is invalid,
.Fn SSL_poll
will always initialise the
.Em revents
fields of all items in the input array upon returning, even if it
returns failure.
.Pp
If
.Fa result_count
is non-NULL, it is always written with the number of items in the array
with nonzero
.Em revents
fields, even if the
.Fn SSL_poll
call returns failure.
.Pp
It is possible for
.Fa result_count
to be written as 0 even if the
.Fn SSL_poll
call returns success, namely if no events were output but the polling
process was successful (e.g.
in nonblocking usage) or timed out.
.Pp
It is possible for
.Fa result_count
to be written as a nonzero value if the
.Fn SSL_poll
call returns failure, for example due to
.Sy SSL_POLL_EVENT_F
events, or because some events were detected and output before
encountering a failure condition while processing a subsequent entry in
the
.Fa items
array.
.Pp
If at least one
.Sy SSL_POLL_EVENT_F
event is output,
.Fn SSL_poll
is guaranteed to return 0 and guaranteed to place at least one ERR on
the error stack describing the first
.Sy SSL_POLL_EVENT_F
output.
Detailed information on any additional
.Sy SSL_POLL_EVENT_F
events is not available.
.Fn SSL_poll
may or may not return more than one
.Sy SSL_POLL_EVENT_F
event at once.
.Pp
"Normal" events representing exceptional I/O conditions which do not
constitute a failure of the
.Fn SSL_poll
mechanism itself are not considered errors by
.Fn SSL_poll
and are instead represented using their own event type; see
.Sx EVENT TYPES
for details.
.Pp
The caller can establish the meaning of the
.Fn SSL_poll
return and output values as follows:
.Bl -tag -width Ds
.It
If
.Fn SSL_poll
returns 1 and
.Fa result_count
is zero, the operation timed out before any resource was ready.
.It
If
.Fn SSL_poll
returns 1 and
.Fa result_count
is nonzero, that many events were output.
.It
If
.Fn SSL_poll
returns 0 and
.Fa result_count
is zero, the caller has made a basic usage error; check the ERR stack
for details.
.It
If
.Fn SSL_poll
returns 0 and
.Fa result_count
is nonzero, inspect the
.Fa items
array for
.Vt SSL_POLL_ITEM
structures with the
.Sy SSL_POLL_EVENT_F
event type raised in
.Em revents .
The entries added to the ERR stack (of which there is guaranteed to be
at least one) reflect the cause of the failure of the first item in
.Fa items
with
.Sy SSL_POLL_EVENT_F
raised.
Note that there may be events other than
.Em SSL_POLL_EVENT_F
output for items which come before the first item with
.Sy SSL_POLL_EVENT_F
raised, and additional
.Sy SSL_POLL_EVENT_F
events may or may not have been output, both of which which will be
reflected in
.Fa result_count .
.El
.Sh SEE ALSO
.Xr BIO_get_rpoll_descriptor 3 ,
.Xr BIO_get_wpoll_descriptor 3 ,
.Xr SSL_get_rpoll_descriptor 3 ,
.Xr SSL_get_wpoll_descriptor 3
.Sh HISTORY
.Fn SSL_poll
was added in OpenSSL 3.3.
.Pp
Before 3.5,
.Fn SSL_poll
did not support blocking operation and would fail if called with a NULL
.Fa timeout
parameter or a
.Fa timeout
parameter pointing to a
.Sy struct timeval
which was not zero.
.Pp
Before 3.5, the
.Sy SSL_POLL_EVENT_EL
and
.Sy SSL_POLL_EVENT_IC
event types were not present.
.Sh COPYRIGHT
Copyright 2024-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
