.Dd 2025-09-30
.Dt SSL_CTX_USE_SERVERINFO 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_use_serverinfo_ex ,
.Nm SSL_CTX_use_serverinfo ,
.Nm SSL_CTX_use_serverinfo_file
.Nd use serverinfo extension
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_use_serverinfo_ex
.Fa "SSL_CTX *ctx"
.Fa "unsigned int version"
.Fa "const unsigned char *serverinfo"
.Fa "size_t serverinfo_length"
.Fc
.Ft int
.Fo SSL_CTX_use_serverinfo
.Fa "SSL_CTX *ctx"
.Fa "const unsigned char *serverinfo"
.Fa "size_t serverinfo_length"
.Fc
.Ft int
.Fo SSL_CTX_use_serverinfo_file
.Fa "SSL_CTX *ctx"
.Fa "const char *file"
.Fc
.Sh DESCRIPTION
These functions load "serverinfo" TLS extensions into the SSL_CTX. A
"serverinfo" extension is returned in response to an empty ClientHello
Extension.
.Pp
.Fn SSL_CTX_use_serverinfo_ex
loads one or more serverinfo extensions from a byte array into
.Fa ctx .
The
.Fa version
parameter specifies the format of the byte array provided in
.Sy *serverinfo
which is of length
.Fa serverinfo_length .
.Pp
If
.Fa version
is
.Sy SSL_SERVERINFOV2
then the extensions in the array must consist of a 4-byte context, a
2-byte Extension Type, a 2-byte length, and then length bytes of
extension_data.
The context and type values have the same meaning as for
.Xr SSL_CTX_add_custom_ext 3 .
If serverinfo is being loaded for extensions to be added to a
Certificate message, then the extension will only be added for the first
certificate in the message (which is always the end-entity certificate).
.Pp
If
.Fa version
is
.Sy SSL_SERVERINFOV1
then the extensions in the array must consist of a 2-byte Extension
Type, a 2-byte length, and then length bytes of extension_data.
The type value has the same meaning as for
.Xr SSL_CTX_add_custom_ext 3 .
The following default context value will be used in this case:
.Bd -literal
 SSL_EXT_TLS1_2_AND_BELOW_ONLY | SSL_EXT_CLIENT_HELLO
 | SSL_EXT_TLS1_2_SERVER_HELLO | SSL_EXT_IGNORE_ON_RESUMPTION
.Ed
.Pp
.Fn SSL_CTX_use_serverinfo
does the same thing as
.Fn SSL_CTX_use_serverinfo_ex
except that there is no
.Fa version
parameter so a default version of SSL_SERVERINFOV1 is used instead.
.Pp
.Fn SSL_CTX_use_serverinfo_file
loads one or more serverinfo extensions from
.Fa file
into
.Fa ctx .
The extensions must be in PEM format.
Each extension must be in a format as described above for
.Fn SSL_CTX_use_serverinfo_ex .
Each PEM extension name must begin with the phrase "BEGIN SERVERINFOV2
FOR " for SSL_SERVERINFOV2 data or "BEGIN SERVERINFO FOR " for
SSL_SERVERINFOV1 data.
.Pp
If more than one certificate (RSA/DSA) is installed using
.Xr SSL_CTX_use_certificate 3 ,
the serverinfo extension will be loaded into the last certificate
installed.
If e.g.
the last item was an RSA certificate, the loaded serverinfo extension
data will be loaded for that certificate.
To use the serverinfo extension for multiple certificates,
.Fn SSL_CTX_use_serverinfo
needs to be called multiple times, once
.Sy after
each time a certificate is loaded via a call to
.Xr SSL_CTX_use_certificate 3 .
.Sh RETURN VALUES
On success, the functions return 1. On failure, the functions return 0.
Check out the error stack to find out the reason.
.Sh SEE ALSO
.Xr ssl 7
.Sh COPYRIGHT
Copyright 2013-2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
