.Dd 2025-09-30
.Dt SSL_CTX_SET_DOMAIN_FLAGS 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_domain_flags ,
.Nm SSL_CTX_get_domain_flags ,
.Nm SSL_get_domain_flags ,
.Nm SSL_DOMAIN_FLAG_SINGLE_THREAD ,
.Nm SSL_DOMAIN_FLAG_MULTI_THREAD ,
.Nm SSL_DOMAIN_FLAG_THREAD_ASSISTED ,
.Nm SSL_DOMAIN_FLAG_BLOCKING ,
.Nm SSL_DOMAIN_FLAG_LEGACY_BLOCKING
.Nd control the concurrency model used by a QUIC domain
.Sh SYNOPSIS
.In openssl/ssl.h
.Fd #define SSL_DOMAIN_FLAG_SINGLE_THREAD
.Fd #define SSL_DOMAIN_FLAG_MULTI_THREAD
.Fd #define SSL_DOMAIN_FLAG_LEGACY_BLOCKING
.Fd #define SSL_DOMAIN_FLAG_BLOCKING
.Fd #define SSL_DOMAIN_FLAG_THREAD_ASSISTED
.Ft int
.Fo SSL_CTX_set_domain_flags
.Fa "SSL_CTX *ctx"
.Fa "uint64_t flags"
.Fc
.Ft int
.Fo SSL_CTX_get_domain_flags
.Fa "SSL_CTX *ctx"
.Fa "uint64_t *flags"
.Fc
.Ft int
.Fo SSL_get_domain_flags
.Fa "SSL *ssl"
.Fa "uint64_t *flags"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set_domain_flags
and
.Fn SSL_CTX_get_domain_flags
set and get the QUIC domain flags on a
.Vt SSL_CTX
using a QUIC
.Sy SSL_METHOD .
These flags determine the concurrency model which is used for a QUIC
domain.
A detailed introduction to these concepts can be found in
.Xr openssl-quic-concurrency 7 .
.Pp
Applications may use either one the flags here:
.Bl -tag -width Ds
.It Sy SSL_DOMAIN_FLAG_SINGLE_THREAD
Specifying this flag configures the Single-Threaded Concurrency Model
(SCM).
.It Sy SSL_DOMAIN_FLAG_MULTI_THREAD
Speciyfing this flag configures the Contentive Concurrency Model (CCM)
(unless
.Sy SSL_DOMAIN_FLAG_THREAD_ASSISTED
is also specified).
.Pp
If OpenSSL was built without thread support, this is identical to
.Sy SSL_DOMAIN_FLAG_SINGLE_THREAD .
.It Sy SSL_DOMAIN_FLAG_THREAD_ASSISTED
Specifying this flag configures the Thread-Assisted Concurrency Model
(TACM). It implies
.Sy SSL_DOMAIN_FLAG_MULTI_THREAD
and
.Sy SSL_DOMAIN_FLAG_BLOCKING .
.Pp
This concurrency model is not available if OpenSSL was built without
thread support, in which case attempting to configure it will result in
an error.
.It Sy SSL_DOMAIN_FLAG_BLOCKING
Enable reliable support for blocking I/O calls, allocating whatever OS
resources are necessary to realise this.
If this flag is specified,
.Sy SSL_DOMAIN_FLAG_LEGACY_BLOCKING
is ignored.
.It Sy SSL_DOMAIN_FLAG_LEGACY_BLOCKING
Enables legacy blocking compatibility mode.
See
.Xr openssl-quic-concurrency 7 .
.El
.Pp
Mutually exclusive flag combinations result in an error (for example,
combining
.Sy SSL_DOMAIN_FLAG_SINGLE_THREAD
and
.Sy SSL_DOMAIN_FLAG_MULTI_THREADED Ns ).
.Pp
Because exactly one concurrency model must be chosen, the domain flags
cannot be set to 0 and attempting to do so will result in an error.
.Pp
Changing these flags using
.Fn SSL_CTX_set_domain_flags
has no effect on QUIC domains which have already been created.
.Pp
The default set of domain flags set on a newly created
.Vt SSL_CTX
may vary by OpenSSL version, chosen
.Sy SSL_METHOD ,
and operating environment.
See
.Xr openssl-quic-concurrency 7
for details.
An application can retrieve the default domain flags by calling
.Fn SSL_CTX_get_domain_flags
immediately after constructing a
.Vt SSL_CTX .
.Pp
.Fn SSL_get_domain_flags
retrieves the domain flags which are effective for a QUIC domain when
called on any QUIC SSL object under that domain.
.Sh RETURN VALUES
.Fn SSL_CTX_set_domain_flags ,
.Fn SSL_CTX_get_domain_flags
and
.Fn SSL_get_domain_flags
return 1 on success and 0 on failure.
.Pp
.Fn SSL_CTX_set_domain_flags
fails if called with a set of flags which are inconsistent or which
cannot be supported given the current environment.
.Pp
.Fn SSL_CTX_set_domain_flags
and
.Fn SSL_CTX_get_domain_flags
fail if called on a
.Vt SSL_CTX
which is not using a QUIC
.Sy SSL_METHOD .
.Pp
.Fn SSL_get_domain_flags
fails if called on a non-QUIC SSL object.
.Sh SEE ALSO
.Xr SSL_new_domain 3 ,
.Xr openssl-quic-concurrency 7
.Sh HISTORY
These functions were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2024-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
