.Dd 2025-09-30
.Dt SSL_CTX_SET_CTLOG_LIST_FILE 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_default_ctlog_list_file ,
.Nm SSL_CTX_set_ctlog_list_file
.Nd load a Certificate Transparency log list from a file
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_set_default_ctlog_list_file
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_CTX_set_ctlog_list_file
.Fa "SSL_CTX *ctx"
.Fa "const char *path"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set_default_ctlog_list_file
loads a list of Certificate Transparency (CT) logs from the default file
location, "ct_log_list.cnf", found in the directory where OpenSSL is
installed.
.Pp
.Fn SSL_CTX_set_ctlog_list_file
loads a list of CT logs from a specific path.
See
.Xr CTLOG_STORE_new 3
for the file format.
.Sh NOTES
These functions will not clear the existing CT log list - it will be
appended to.
To replace the existing list, use
.Xr SSL_CTX_set0_ctlog_store 3
first.
.Pp
If an error occurs whilst parsing a particular log entry in the file,
that log entry will be skipped.
.Sh RETURN VALUES
.Fn SSL_CTX_set_default_ctlog_list_file
and
.Fn SSL_CTX_set_ctlog_list_file
return 1 if the log list is successfully loaded, and 0 if an error
occurs.
In the case of an error, the log list may have been partially loaded.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_ct_validation_callback 3 ,
.Xr CTLOG_STORE_new 3
.Sh COPYRIGHT
Copyright 2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
