.Dd 2025-09-30
.Dt SSL_CTX_SET_PSK_CLIENT_CALLBACK 3ossl
.Os
.Sh NAME
.Nm SSL_psk_client_cb_func ,
.Nm SSL_psk_use_session_cb_func ,
.Nm SSL_CTX_set_psk_client_callback ,
.Nm SSL_set_psk_client_callback ,
.Nm SSL_CTX_set_psk_use_session_callback ,
.Nm SSL_set_psk_use_session_callback
.Nd set PSK client callback
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft typedef int
.Fo 
.Fa *SSL_psk_use_session_cb_func
.Fc
(SSL *ssl, const EVP_MD *md,
.Bd -literal
                                            const unsigned char **id,
                                            size_t *idlen,
                                            SSL_SESSION **sess);
.Ed
.Ft void
.Fo SSL_CTX_set_psk_use_session_callback
.Fa "SSL_CTX *ctx"
.Fa "SSL_psk_use_session_cb_func cb"
.Fc
.Ft void
.Fo SSL_set_psk_use_session_callback
.Fa "SSL *s"
.Fa "SSL_psk_use_session_cb_func cb"
.Fc
.Ft typedef unsigned int
.Fo 
.Fa *SSL_psk_client_cb_func
.Fc
(SSL *ssl,
.Bd -literal
                                                const char *hint,
                                                char *identity,
                                                unsigned int max_identity_len,
                                                unsigned char *psk,
                                                unsigned int max_psk_len);
.Ed
.Ft void
.Fo SSL_CTX_set_psk_client_callback
.Fa "SSL_CTX *ctx"
.Fa "SSL_psk_client_cb_func cb"
.Fc
.Ft void
.Fo SSL_set_psk_client_callback
.Fa "SSL *ssl"
.Fa "SSL_psk_client_cb_func cb"
.Fc
.Sh DESCRIPTION
A client application wishing to use TLSv1.3 PSKs should use either
.Fn SSL_CTX_set_psk_use_session_callback
or
.Fn SSL_set_psk_use_session_callback
as appropriate.
These functions cannot be used for TLSv1.2 and below PSKs.
.Pp
The callback function is given a pointer to the SSL connection in
.Fa ssl .
.Pp
The first time the callback is called for a connection the
.Sy md
parameter is NULL. In some circumstances the callback will be called a
second time.
In that case the server will have specified a ciphersuite to use already
and the PSK must be compatible with the digest for that ciphersuite.
The digest will be given in
.Sy md .
The PSK returned by the callback is allowed to be different between the
first and second time it is called.
.Pp
On successful completion the callback must store a pointer to an
identifier for the PSK in
.Sy *id .
The identifier length in bytes should be stored in
.Sy *idlen .
The memory pointed to by
.Sy *id
remains owned by the application and should be freed by it as required
at any point after the handshake is complete.
.Pp
Additionally the callback should store a pointer to an SSL_SESSION
object in
.Sy *sess .
This is used as the basis for the PSK, and should, at a minimum, have
the following fields set:
.Bl -tag -width Ds
.It The master key
This can be set via a call to
.Xr SSL_SESSION_set1_master_key 3 .
.It A ciphersuite
Only the handshake digest associated with the ciphersuite is relevant
for the PSK (the server may go on to negotiate any ciphersuite which is
compatible with the digest).
The application can use any TLSv1.3 ciphersuite.
If
.Sy md
is not NULL the handshake digest for the ciphersuite should be the same.
The ciphersuite can be set via a call to <SSL_SESSION_set_cipher(3)>.
The handshake digest of an SSL_CIPHER object can be checked using
<SSL_CIPHER_get_handshake_digest(3)>.
.It The protocol version
This can be set via a call to
.Xr SSL_SESSION_set_protocol_version 3
and should be TLS1_3_VERSION.
.El
.Pp
Additionally the maximum early data value should be set via a call to
.Xr SSL_SESSION_set_max_early_data 3
if the PSK will be used for sending early data.
.Pp
Alternatively an SSL_SESSION created from a previous non-PSK handshake
may also be used as the basis for a PSK.
.Pp
Ownership of the SSL_SESSION object is passed to the OpenSSL library and
so it should not be freed by the application.
.Pp
It is also possible for the callback to succeed but not supply a PSK. In
this case no PSK will be sent to the server but the handshake will
continue.
To do this the callback should return successfully and ensure that
.Sy *sess
is NULL. The contents of
.Sy *id
and
.Sy *idlen
will be ignored.
.Pp
A client application wishing to use PSK ciphersuites for TLSv1.2 and
below must provide a different callback function.
This function will be called when the client is sending the
ClientKeyExchange message to the server.
.Pp
The purpose of the callback function is to select the PSK identity and
the pre-shared key to use during the connection setup phase.
.Pp
The callback is set using functions
.Fn SSL_CTX_set_psk_client_callback
or
.Fn SSL_set_psk_client_callback .
The callback function is given the connection in parameter
.Fa ssl ,
a
.Sy NUL Ns -terminated
PSK identity hint sent by the server in parameter
.Sy hint ,
a buffer
.Sy identity
of length
.Sy max_identity_len
bytes (including the
.Sy NUL Ns -terminator)
where the resulting
.Sy NUL Ns -terminated
identity is to be stored, and a buffer
.Sy psk
of length
.Sy max_psk_len
bytes where the resulting pre-shared key is to be stored.
.Pp
The callback for use in TLSv1.2 will also work in TLSv1.3 although it is
recommended to use
.Fn SSL_CTX_set_psk_use_session_callback
or
.Fn SSL_set_psk_use_session_callback
for this purpose instead.
If TLSv1.3 has been negotiated then OpenSSL will first check to see if a
callback has been set via
.Fn SSL_CTX_set_psk_use_session_callback
or
.Fn SSL_set_psk_use_session_callback
and it will use that in preference.
If no such callback is present then it will check to see if a callback
has been set via
.Fn SSL_CTX_set_psk_client_callback
or
.Fn SSL_set_psk_client_callback
and use that.
In this case the
.Sy hint
value will always be NULL and the handshake digest will default to
SHA-256 for any returned PSK. TLSv1.3 early data exchanges are possible
in PSK connections only with the
.Vt SSL_psk_use_session_cb_func
callback, and are not possible with the
.Vt SSL_psk_client_cb_func
callback.
.Sh NOTES
Note that parameter
.Sy hint
given to the callback may be
.Dv NULL .
.Pp
A connection established via a TLSv1.3 PSK will appear as if session
resumption has occurred so that
.Xr SSL_session_reused 3
will return true.
.Pp
There are no known security issues with sharing the same PSK between
TLSv1.2 (or below) and TLSv1.3. However, the RFC has this note of
caution:
.Pp
"While there is no known way in which the same PSK might produce related
output in both versions, only limited analysis has been done.
Implementations can ensure safety from cross-protocol related output by
not reusing PSKs between TLS 1.3 and TLS 1.2."
.Sh RETURN VALUES
Return values from the
.Vt SSL_psk_client_cb_func
callback are interpreted as follows:
.Pp
On success (callback found a PSK identity and a pre-shared key to use)
the length (> 0) of
.Sy psk
in bytes is returned.
.Pp
Otherwise or on errors the callback should return 0. In this case the
connection setup fails.
.Pp
The SSL_psk_use_session_cb_func callback should return 1 on success or 0
on failure.
In the event of failure the connection setup fails.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_psk_find_session_callback 3 ,
.Xr SSL_set_psk_find_session_callback 3
.Sh HISTORY
.Fn SSL_CTX_set_psk_use_session_callback
and
.Fn SSL_set_psk_use_session_callback
were added in OpenSSL 1.1.1.
.Sh COPYRIGHT
Copyright 2006-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
