.Dd 2025-09-30
.Dt SSL_SET_FD 3ossl
.Os
.Sh NAME
.Nm SSL_set_fd ,
.Nm SSL_set_rfd ,
.Nm SSL_set_wfd
.Nd connect the SSL object with a file descriptor
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_set_fd
.Fa "SSL *ssl"
.Fa "int fd"
.Fc
.Ft int
.Fo SSL_set_rfd
.Fa "SSL *ssl"
.Fa "int fd"
.Fc
.Ft int
.Fo SSL_set_wfd
.Fa "SSL *ssl"
.Fa "int fd"
.Fc
.Sh DESCRIPTION
.Fn SSL_set_fd
sets the file descriptor
.Fa fd
as the input/output facility for the TLS/SSL (encrypted) side of
.Fa ssl .
.Fa fd
will typically be the socket file descriptor of a network connection.
.Pp
When performing the operation, a
.Sy socket BIO
is automatically created to interface between the
.Fa ssl
and
.Fa fd .
The BIO and hence the SSL engine inherit the behaviour of
.Fa fd .
If
.Fa fd
is nonblocking, the
.Fa ssl
will also have nonblocking behaviour.
.Pp
When used on a QUIC connection SSL object, a
.Sy datagram BIO
is automatically created instead of a
.Sy socket BIO .
These functions fail if called on a QUIC stream SSL object.
.Pp
If there was already a BIO connected to
.Fa ssl ,
.Xr BIO_free 3
will be called (for both the reading and writing side, if different).
.Pp
.Fn SSL_set_rfd
and
.Fn SSL_set_wfd
perform the respective action, but only for the read channel or the
write channel, which can be set independently.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It 0
The operation failed.
Check the error stack to find out why.
.It 1
The operation succeeded.
.El
.Sh NOTES
On Windows, a socket handle is a 64-bit data type (UINT_PTR), which
leads to a compiler warning (conversion from 'SOCKET' to 'int', possible
loss of data) when passing the socket handle to
.Xr SSL_set_*fd 3 .
For the time being, this warning can safely be ignored, because although
the Microsoft documentation claims that the upper limit is
INVALID_SOCKET-1 (2^64 - 2), in practice the current
.Xr socket 3
implementation returns an index into the kernel handle table, the size
of which is limited to 2^24.
.Sh SEE ALSO
.Xr SSL_get_fd 3 ,
.Xr SSL_set_bio 3 ,
.Xr SSL_connect 3 ,
.Xr SSL_accept 3 ,
.Xr SSL_shutdown 3 ,
.Xr ssl 7
,
.Xr bio 7
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
