.Dd 2025-09-30
.Dt SSL_CTX_SET_READ_AHEAD 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_read_ahead ,
.Nm SSL_CTX_get_read_ahead ,
.Nm SSL_set_read_ahead ,
.Nm SSL_get_read_ahead ,
.Nm SSL_CTX_get_default_read_ahead
.Nd manage whether to read as many input bytes as possible
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_set_read_ahead
.Fa "SSL *s"
.Fa "int yes"
.Fc
.Ft int
.Fo SSL_get_read_ahead
.Fa "const SSL *s"
.Fc
.Bd -literal
 SSL_CTX_set_read_ahead(SSL_CTX *ctx, int yes);
 long SSL_CTX_get_read_ahead(SSL_CTX *ctx);
 long SSL_CTX_get_default_read_ahead(SSL_CTX *ctx);
.Ed
.Sh DESCRIPTION
.Xr SSL_CTX_set_read_ahead 3
and
.Fn SSL_set_read_ahead
set whether we should read as many input bytes as possible (for
nonblocking reads) or not.
For example if
.Sy x
bytes are currently required by OpenSSL, but
.Sy y
bytes are available from the underlying BIO (where
.Sy y
>
.Sy x Ns ),
then OpenSSL will read all
.Sy y
bytes into its buffer (providing that the buffer is large enough) if
reading ahead is on, or
.Sy x
bytes otherwise.
Setting the parameter
.Fa yes
to 0 turns reading ahead is off, other values turn it on.
.Xr SSL_CTX_set_default_read_ahead 3
is identical to
.Xr SSL_CTX_set_read_ahead 3 .
.Pp
.Xr SSL_CTX_get_read_ahead 3
and
.Fn SSL_get_read_ahead
indicate whether reading ahead has been set or not.
.Xr SSL_CTX_get_default_read_ahead 3
is identical to
.Xr SSL_CTX_get_read_ahead 3 .
.Pp
These functions cannot be used with QUIC SSL objects.
.Fn SSL_set_read_ahead
has no effect if called on a QUIC SSL object.
.Sh NOTES
These functions have no impact when used with DTLS. The return values
for
.Xr SSL_CTX_get_read_head 3
and
.Fn SSL_get_read_ahead
are undefined for DTLS. Setting
.Sy read_ahead
can impact the behaviour of the
.Xr SSL_pending 3
function (see
.Xr SSL_pending 3 Ns ).
.Pp
Since
.Xr SSL_read 3
can return
.Sy SSL_ERROR_WANT_READ
for non-application data records, and
.Xr SSL_has_pending 3
can't tell the difference between processed and unprocessed data, it's
recommended that if read ahead is turned on that
.Sy SSL_MODE_AUTO_RETRY
is not turned off using
.Xr SSL_CTX_clear_mode 3 .
That will prevent getting
.Sy SSL_ERROR_WANT_READ
when there is still a complete record available that hasn't been
processed.
.Pp
If the application wants to continue to use the underlying transport
(e.g.
TCP connection) after the SSL connection is finished using
.Xr SSL_shutdown 3
reading ahead should be turned off.
Otherwise the SSL structure might read data that it shouldn't.
.Sh RETURN VALUES
.Fn SSL_get_read_ahead
and
.Xr SSL_CTX_get_read_ahead 3
return 0 if reading ahead is off, and non zero otherwise.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_pending 3
.Sh COPYRIGHT
Copyright 2015-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
