.Dd 2025-09-30
.Dt SSL_SESSION_GET0_ID_CONTEXT 3ossl
.Os
.Sh NAME
.Nm SSL_SESSION_get0_id_context ,
.Nm SSL_SESSION_set1_id_context
.Nd get and set the SSL ID context associated with a session
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const unsigned char *
.Fo SSL_SESSION_get0_id_context
.Fa "const SSL_SESSION *s"
.Fa "unsigned int *len"
.Fc
.Ft int
.Fo SSL_SESSION_set1_id_context
.Fa "SSL_SESSION *s"
.Fa "const unsigned char *sid_ctx"
.Fa "unsigned int sid_ctx_len"
.Fc
.Sh DESCRIPTION
See
.Xr SSL_CTX_set_session_id_context 3
for further details on session ID contexts.
.Pp
.Fn SSL_SESSION_get0_id_context
returns the ID context associated with the SSL/TLS session
.Fa s .
The length of the ID context is written to
.Sy *len
if
.Fa len
is not NULL.
.Pp
The value returned is a pointer to an object maintained within
.Fa s
and should not be released.
.Pp
.Fn SSL_SESSION_set1_id_context
takes a copy of the provided ID context given in
.Fa sid_ctx
and associates it with the session
.Fa s .
The length of the ID context is given by
.Fa sid_ctx_len
which must not exceed SSL_MAX_SID_CTX_LENGTH bytes.
.Sh RETURN VALUES
.Fn SSL_SESSION_set1_id_context
returns 1 on success or 0 on error.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_set_session_id_context 3
.Sh HISTORY
The
.Fn SSL_SESSION_get0_id_context
function was added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2015-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
