.Dd 2025-09-30
.Dt SSL_CTX_LOAD_VERIFY_LOCATIONS 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_load_verify_dir ,
.Nm SSL_CTX_load_verify_file ,
.Nm SSL_CTX_load_verify_store ,
.Nm SSL_CTX_set_default_verify_paths ,
.Nm SSL_CTX_set_default_verify_dir ,
.Nm SSL_CTX_set_default_verify_file ,
.Nm SSL_CTX_set_default_verify_store ,
.Nm SSL_CTX_load_verify_locations
.Nd set default locations for trusted CA certificates
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_load_verify_dir
.Fa "SSL_CTX *ctx"
.Fa "const char *CApath"
.Fc
.Ft int
.Fo SSL_CTX_load_verify_file
.Fa "SSL_CTX *ctx"
.Fa "const char *CAfile"
.Fc
.Ft int
.Fo SSL_CTX_load_verify_store
.Fa "SSL_CTX *ctx"
.Fa "const char *CAstore"
.Fc
.Ft int
.Fo SSL_CTX_set_default_verify_paths
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_CTX_set_default_verify_dir
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_CTX_set_default_verify_file
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_CTX_set_default_verify_store
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_CTX_load_verify_locations
.Fa "SSL_CTX *ctx"
.Fa "const char *CAfile"
.Fa "const char *CApath"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_load_verify_locations ,
.Fn SSL_CTX_load_verify_dir ,
.Fn SSL_CTX_load_verify_file ,
.Fn SSL_CTX_load_verify_store
specifies the locations for
.Fa ctx ,
at which CA certificates for verification purposes are located.
The certificates available via
.Fa CAfile ,
.Fa CApath
and
.Fa CAstore
are trusted.
.Fa ctx
.Sy MUST NOT
be NULL
.Pp
Details of the certificate verification and chain checking process are
described in
.Xr openssl-verification-options 1 .
.Pp
.Fn SSL_CTX_set_default_verify_paths
specifies that the default locations from which CA certificates are
loaded should be used.
There is one default directory, one default file and one default store.
The default CA certificates directory is called
.Pa certs
in the default OpenSSL directory, and this is also the default store.
Alternatively the
.Sy SSL_CERT_DIR
environment variable can be defined to override this location.
The default CA certificates file is called
.Pa cert.pem
in the default OpenSSL directory.
Alternatively the
.Sy SSL_CERT_FILE
environment variable can be defined to override this location.
.Fa ctx
.Sy MUST NOT
be NULL.
.Pp
.Fn SSL_CTX_set_default_verify_dir
is similar to
.Fn SSL_CTX_set_default_verify_paths
except that just the default directory is used.
.Pp
.Fn SSL_CTX_set_default_verify_file
is similar to
.Fn SSL_CTX_set_default_verify_paths
except that just the default file is used.
.Pp
.Fn SSL_CTX_set_default_verify_store
is similar to
.Fn SSL_CTX_set_default_verify_paths
except that just the default store is used.
.Sh NOTES
If
.Fa CAfile
is not NULL, it points to a file of CA certificates in PEM format.
The file can contain several CA certificates identified by
.Bd -literal
 -----BEGIN CERTIFICATE-----
 ... (CA certificate in base64 encoding) ...
 -----END CERTIFICATE-----
.Ed
.Pp
sequences.
Before, between, and after the certificates text is allowed which can be
used e.g.
for descriptions of the certificates.
.Pp
The
.Fa CAfile
is processed on execution of the
.Fn SSL_CTX_load_verify_locations
function.
.Pp
If
.Fa CApath
is not NULL, it points to a directory containing CA certificates in PEM
format.
The files each contain one CA certificate.
The files are looked up by the CA subject name hash value, which must
hence be available.
If more than one CA certificate with the same name hash value exist, the
extension must be different (e.g.
9d66eef0.0, 9d66eef0.1 etc).
The search is performed in the ordering of the extension number,
regardless of other properties of the certificates.
Use the
.Sy c_rehash
utility to create the necessary links.
.Pp
The certificates in
.Fa CApath
are only looked up when required, e.g.
when building the certificate chain or when actually performing the
verification of a peer certificate.
.Pp
When looking up CA certificates for chain building, the OpenSSL library
will search for suitable certificates first in
.Fa CAfile ,
then in
.Fa CApath .
Details of the chain building process are described in
.Xr openssl-verification-options 1 .
.Pp
If
.Fa CAstore
is not NULL, it's a URI for to a store, which may represent a single
container or a whole catalogue of containers.
Apart from the
.Fa CAstore
not necessarily being a local file or directory, it's generally treated
the same way as a
.Fa CApath .
.Pp
In server mode, when requesting a client certificate, the server must
send the list of CAs of which it will accept client certificates.
This list is not influenced by the contents of
.Fa CAfile
or
.Fa CApath
and must explicitly be set using the
.Xr SSL_CTX_set_client_CA_list 3
family of functions.
.Pp
When building its own certificate chain, an OpenSSL client/server will
try to fill in missing certificates from
.Fa CAfile Ns / Ns Fa CApath ,
if the certificate chain was not explicitly specified (see
.Xr SSL_CTX_add_extra_chain_cert 3 ,
.Xr SSL_CTX_use_certificate 3 .
.Sh WARNINGS
If several CA certificates matching the name, key identifier, and serial
number condition are available, only the first one will be examined.
This may lead to unexpected results if the same CA certificate is
available with different expiration dates.
If a "certificate expired" verification error occurs, no other
certificate will be searched.
Make sure to not have expired certificates mixed with valid ones.
.Sh RETURN VALUES
For SSL_CTX_load_verify_locations the following return values can occur:
.Bl -tag -width Ds
.It 0
The operation failed because
.Fa CAfile
and
.Fa CApath
are NULL or the processing at one of the locations specified failed.
Check the error stack to find out the reason.
.It 1
The operation succeeded.
.El
.Pp
.Fn SSL_CTX_set_default_verify_paths ,
.Fn SSL_CTX_set_default_verify_dir
and
.Fn SSL_CTX_set_default_verify_file
all return 1 on success or 0 on failure.
A missing default location is still treated as a success.
.Sh EXAMPLES
Generate a CA certificate file with descriptive text from the CA
certificates ca1.pem ca2.pem ca3.pem:
.Bd -literal
 #!/bin/sh
 rm CAfile.pem
 for i in ca1.pem ca2.pem ca3.pem ; do
     openssl x509 -in $i -text >> CAfile.pem
 done
.Ed
.Pp
Prepare the directory /some/where/certs containing several CA
certificates for use as
.Fa CApath :
.Bd -literal
 cd /some/where/certs
 c_rehash .
.Ed
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_client_CA_list 3 ,
.Xr SSL_get_client_CA_list 3 ,
.Xr SSL_CTX_use_certificate 3 ,
.Xr SSL_CTX_add_extra_chain_cert 3 ,
.Xr SSL_CTX_set_cert_store 3 ,
.Xr SSL_CTX_set_client_CA_list 3
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
