.Dd 2025-09-30
.Dt SSL_WANT 3ossl
.Os
.Sh NAME
.Nm SSL_want ,
.Nm SSL_want_nothing ,
.Nm SSL_want_read ,
.Nm SSL_want_write ,
.Nm SSL_want_x509_lookup ,
.Nm SSL_want_retry_verify ,
.Nm SSL_want_async ,
.Nm SSL_want_async_job ,
.Nm SSL_want_client_hello_cb
.Nd obtain state information TLS/SSL I/O operation
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_want
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_nothing
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_read
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_write
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_x509_lookup
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_retry_verify
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_async
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_async_job
.Fa "const SSL *ssl"
.Fc
.Ft int
.Fo SSL_want_client_hello_cb
.Fa "const SSL *ssl"
.Fc
.Sh DESCRIPTION
.Fn SSL_want
returns state information for the SSL object
.Fa ssl .
.Fa ssl
.Sy MUST NOT
be NULL.
.Pp
The other
.Xr SSL_want_* 3
calls are shortcuts for the possible states returned by
.Fn SSL_want .
.Sh NOTES
.Fn SSL_want
examines the internal state information of the SSL object.
Its return values are similar to that of
.Xr SSL_get_error 3 .
Unlike
.Xr SSL_get_error 3 ,
which also evaluates the error queue, the results are obtained by
examining an internal state flag only.
The information must therefore only be used for normal operation under
nonblocking I/O. Error conditions are not handled and must be treated
using
.Xr SSL_get_error 3 .
.Pp
The result returned by
.Fn SSL_want
should always be consistent with the result of
.Xr SSL_get_error 3 .
.Sh RETURN VALUES
The following return values can currently occur for
.Fn SSL_want :
.Bl -tag -width Ds
.It SSL_NOTHING
There is no data to be written or to be read.
.It SSL_WRITING
There are data in the SSL buffer that must be written to the underlying
.Sy BIO
layer in order to complete the actual
.Xr SSL_* 3
operation.
A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_WRITE .
.It SSL_READING
More data must be read from the underlying
.Sy BIO
layer in order to complete the actual
.Xr SSL_* 3
operation.
A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_READ .
.It SSL_X509_LOOKUP
The operation did not complete because an application callback set by
.Xr SSL_CTX_set_client_cert_cb 3
has asked to be called again.
A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_X509_LOOKUP .
.It SSL_RETRY_VERIFY
The operation did not complete because a certificate verification
callback has asked to be called again via
.Xr SSL_set_retry_verify 3 .
A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_RETRY_VERIFY .
.It SSL_ASYNC_PAUSED
An asynchronous operation partially completed and was then paused.
See
.Xr SSL_get_all_async_fds 3 .
A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_ASYNC .
.It SSL_ASYNC_NO_JOBS
The asynchronous job could not be started because there were no async
jobs available in the pool (see ASYNC_init_thread(3)). A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_ASYNC_JOB .
.It SSL_CLIENT_HELLO_CB
The operation did not complete because an application callback set by
.Xr SSL_CTX_set_client_hello_cb 3
has asked to be called again.
A call to
.Xr SSL_get_error 3
should return
.Sy SSL_ERROR_WANT_CLIENT_HELLO_CB .
.El
.Pp
.Fn SSL_want_nothing ,
.Fn SSL_want_read ,
.Fn SSL_want_write ,
.Fn SSL_want_x509_lookup ,
.Fn SSL_want_retry_verify ,
.Fn SSL_want_async ,
.Fn SSL_want_async_job ,
and
.Fn SSL_want_client_hello_cb
return 1 when the corresponding condition is true or 0 otherwise.
.Sh QUIC-SPECIFIC CONSIDERATIONS
For QUIC, these functions relate only to the TLS handshake layer.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_get_error 3
.Sh HISTORY
The
.Fn SSL_want_client_hello_cb
function and the SSL_CLIENT_HELLO_CB return value were added in OpenSSL
1.1.1.
.Sh COPYRIGHT
Copyright 2001-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
