.Dd 2025-09-30
.Dt SSL_ACCEPT_STREAM 3ossl
.Os
.Sh NAME
.Nm SSL_accept_stream ,
.Nm SSL_get_accept_stream_queue_len ,
.Nm SSL_ACCEPT_STREAM_NO_BLOCK
.Nd accept an incoming QUIC stream from a QUIC peer
.Sh SYNOPSIS
.In openssl/ssl.h
.Fd #define SSL_ACCEPT_STREAM_NO_BLOCK
.Ft SSL *
.Fo SSL_accept_stream
.Fa "SSL *ssl"
.Fa "uint64_t flags"
.Fc
.Ft size_t
.Fo SSL_get_accept_stream_queue_len
.Fa "SSL *ssl"
.Fc
.Sh DESCRIPTION
The
.Fn SSL_accept_stream
function attempts to dequeue an incoming stream from the given QUIC
connection SSL object and returns the newly allocated QUIC stream SSL
object.
.Pp
If the queue of incoming streams is empty, this function returns NULL
(in nonblocking mode) or waits for an incoming stream (in blocking
mode).
This function may still return NULL in blocking mode, for example if the
underlying connection is terminated.
.Pp
The caller is responsible for managing the lifetime of the returned QUIC
stream SSL object; for more information, see
.Xr SSL_free 3 .
.Pp
This function will block if the QUIC connection SSL object is configured
in blocking mode (see
.Xr SSL_set_blocking_mode 3 Ns ),
but this may be bypassed by passing the flag
.Sy SSL_ACCEPT_STREAM_NO_BLOCK
in
.Fa flags .
If this flag is set, this function never blocks.
.Pp
Calling
.Fn SSL_accept_stream
if there is no default stream already present inhibits the future
creation of a default stream.
See
.Xr openssl-quic 7 .
.Pp
.Fn SSL_get_accept_stream_queue_len
returns the number of incoming streams currently waiting in the accept
queue.
.Pp
These functions can be used from multiple threads for the same QUIC
connection.
.Pp
Depending on whether default stream functionality is being used, it may
be necessary to explicitly configure the incoming stream policy before
streams can be accepted; see
.Xr SSL_set_incoming_stream_policy 3 .
See also
.Xr openssl-quic 7
for more information on default stream functionality.
.Sh RETURN VALUES
.Fn SSL_accept_stream
returns a newly allocated QUIC stream SSL object, or NULL if no new
incoming streams are available, or if the connection has been
terminated, or if called on an SSL object other than a QUIC connection
SSL object.
.Xr SSL_get_error 3
can be used to obtain further information in this case.
.Pp
.Fn SSL_get_accept_stream_queue_len
returns the number of incoming streams currently waiting in the accept
queue, or 0 if called on an SSL object other than a QUIC connection SSL
object.
.Sh SEE ALSO
.Xr openssl-quic 7 ,
.Xr SSL_new_stream 3 ,
.Xr SSL_set_blocking_mode 3 ,
.Xr SSL_free 3
.Sh HISTORY
.Fn SSL_accept_stream
and
.Fn SSL_get_accept_stream_queue_len
were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2002-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
