.Dd 2025-09-30
.Dt SSL_GET_CERTIFICATE 3ossl
.Os
.Sh NAME
.Nm SSL_get_certificate ,
.Nm SSL_get_privatekey
.Nd retrieve TLS/SSL certificate and private key
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft X509 *
.Fo SSL_get_certificate
.Fa "const SSL *s"
.Fc
.Ft EVP_PKEY *
.Fo SSL_get_privatekey
.Fa "const SSL *s"
.Fc
.Sh DESCRIPTION
.Fn SSL_get_certificate
returns a pointer to an
.Vt X509
object representing a certificate used as the local peer's identity.
.Pp
Multiple certificates can be configured; for example, a server might
have both RSA and ECDSA certificates.
The certificate which is returned by
.Fn SSL_get_certificate
is determined as follows:
.Bl -tag -width Ds
.It
If it is called before certificate selection has occurred, it returns
the most recently added certificate, or NULL if no certificate has been
added.
.It
After certificate selection has occurred, it returns the certificate
which was selected during the handshake, or NULL if no certificate was
selected (for example, on a client where no client certificate is in
use).
.El
.Pp
Certificate selection occurs during the handshake; therefore, the value
returned by
.Fn SSL_get_certificate
during any callback made during the handshake process will depend on
whether that callback is made before or after certificate selection
occurs.
.Pp
A specific use for
.Fn SSL_get_certificate
is inside a callback set via a call to
.Xr SSL_CTX_set_tlsext_status_cb 3 .
This callback occurs after certificate selection, where it can be used
to examine a server's chosen certificate, for example for the purpose of
identifying a certificate's OCSP responder URL so that an OCSP response
can be obtained.
.Pp
.Fn SSL_get_privatekey
returns a pointer to the
.Vt EVP_PKEY
object corresponding to the certificate returned by
.Fn SSL_get_certificate ,
if any.
.Sh RETURN VALUES
These functions return pointers to their respective objects, or NULL if
no such object is available.
Returned objects are owned by the SSL object and should not be freed by
users of these functions.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_tlsext_status_cb 3
.Sh COPYRIGHT
Copyright 2001-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
