.Dd 2025-09-30
.Dt SSL_CTX_SESSIONS 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_sessions
.Nd access internal session cache
.Sh SYNOPSIS
.In openssl/ssl.h
.Bd -literal
 LHASH_OF(SSL_SESSION) *SSL_CTX_sessions(SSL_CTX *ctx);
.Ed
.Sh DESCRIPTION
.Xr SSL_CTX_sessions 3
returns a pointer to the lhash databases containing the internal session
cache for
.Sy ctx .
.Sh NOTES
The sessions in the internal session cache are kept in an
.Xr LHASH 3
type database.
It is possible to directly access this database e.g.
for searching.
In parallel, the sessions form a linked list which is maintained
separately from the
.Xr LHASH 3
operations, so that the database must not be modified directly but by
using the
.Xr SSL_CTX_add_session 3
family of functions.
.Sh RETURN VALUES
.Xr SSL_CTX_sessions 3
returns a pointer to the lhash of
.Sy SSL_SESSION .
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr LHASH 3 ,
.Xr SSL_CTX_add_session 3 ,
.Xr SSL_CTX_set_session_cache_mode 3
.Sh COPYRIGHT
Copyright 2001-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
