.Dd 2025-09-30
.Dt SSL_CTX_ADD_SESSION 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_add_session ,
.Nm SSL_CTX_remove_session
.Nd manipulate session cache
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_add_session
.Fa "SSL_CTX *ctx"
.Fa "SSL_SESSION *c"
.Fc
.Ft int
.Fo SSL_CTX_remove_session
.Fa "SSL_CTX *ctx"
.Fa "SSL_SESSION *c"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_add_session
adds the session
.Fa c
to the context
.Fa ctx .
The reference count for session
.Fa c
is incremented by 1. If a session with the same session id already
exists, the old session is removed by calling
.Xr SSL_SESSION_free 3 .
.Pp
.Fn SSL_CTX_remove_session
removes the session
.Fa c
from the context
.Fa ctx
and marks it as non-resumable.
.Xr SSL_SESSION_free 3
is called once for
.Fa c .
.Sh NOTES
When adding a new session to the internal session cache, it is examined
whether a session with the same session id already exists.
In this case it is assumed that both sessions are identical.
If the same session is stored in a different SSL_SESSION object, The old
session is removed and replaced by the new session.
If the session is actually identical (the SSL_SESSION object is
identical),
.Fn SSL_CTX_add_session
is a no-op, and the return value is 0.
.Pp
If a server SSL_CTX is configured with the
SSL_SESS_CACHE_NO_INTERNAL_STORE flag then the internal cache will not
be populated automatically by new sessions negotiated by the SSL/TLS
implementation, even though the internal cache will be searched
automatically for session-resume requests (the latter can be suppressed
by SSL_SESS_CACHE_NO_INTERNAL_LOOKUP). So the application can use
.Fn SSL_CTX_add_session
directly to have full control over the sessions that can be resumed if
desired.
.Sh RETURN VALUES
The following values are returned by all functions:
.Bl -tag -width Ds
.It 0
The operation failed.
In case of the add operation, it was tried to add the same (identical)
session twice.
In case of the remove operation, the session was not found in the cache.
.It 1
The operation succeeded.
.El
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_set_session_cache_mode 3 ,
.Xr SSL_SESSION_free 3
.Sh COPYRIGHT
Copyright 2001-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
