.Dd 2025-09-30
.Dt SSL_GET_PEER_TMP_KEY 3ossl
.Os
.Sh NAME
.Nm SSL_get_peer_tmp_key ,
.Nm SSL_get_server_tmp_key ,
.Nm SSL_get_tmp_key
.Nd get information about temporary keys used during a handshake
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft long
.Fo SSL_get_peer_tmp_key
.Fa "SSL *ssl"
.Fa "EVP_PKEY **key"
.Fc
.Ft long
.Fo SSL_get_server_tmp_key
.Fa "SSL *ssl"
.Fa "EVP_PKEY **key"
.Fc
.Ft long
.Fo SSL_get_tmp_key
.Fa "SSL *ssl"
.Fa "EVP_PKEY **key"
.Fc
.Sh DESCRIPTION
.Fn SSL_get_peer_tmp_key
returns the temporary key provided by the peer and used during key
exchange.
For example, if ECDHE is in use, then this represents the peer's public
ECDHE key.
On success a pointer to the key is stored in
.Sy *key .
It is the caller's responsibility to free this key after use using
.Xr EVP_PKEY_free 3 .
.Pp
.Fn SSL_get_server_tmp_key
is a backwards compatibility alias for
.Fn SSL_get_peer_tmp_key .
Under that name it worked just on the client side of the connection, its
behaviour on the server end is release-dependent.
.Pp
.Fn SSL_get_tmp_key
returns the equivalent information for the local end of the connection.
.Sh RETURN VALUES
All these functions return 1 on success and 0 otherwise.
.Sh NOTES
This function is implemented as a macro.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr EVP_PKEY_free 3
.Sh COPYRIGHT
Copyright 2017-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
