.Dd 2025-09-30
.Dt SSL_SET_BIO 3ossl
.Os
.Sh NAME
.Nm SSL_set_bio ,
.Nm SSL_set0_rbio ,
.Nm SSL_set0_wbio
.Nd connect the SSL object with a BIO
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft void
.Fo SSL_set_bio
.Fa "SSL *ssl"
.Fa "BIO *rbio"
.Fa "BIO *wbio"
.Fc
.Ft void
.Fo SSL_set0_rbio
.Fa "SSL *s"
.Fa "BIO *rbio"
.Fc
.Ft void
.Fo SSL_set0_wbio
.Fa "SSL *s"
.Fa "BIO *wbio"
.Fc
.Sh DESCRIPTION
.Fn SSL_set0_rbio
connects the BIO
.Fa rbio
for the read operations of the
.Fa ssl
object.
The SSL engine inherits the behaviour of
.Fa rbio .
If the BIO is nonblocking then the
.Fa ssl
object will also have nonblocking behaviour.
This function transfers ownership of
.Fa rbio
to
.Fa ssl .
It will be automatically freed using
.Xr BIO_free_all 3
when the
.Fa ssl
is freed.
On calling this function, any existing
.Fa rbio
that was previously set will also be freed via a call to
.Xr BIO_free_all 3
(this includes the case where the
.Fa rbio
is set to the same value as previously).
.Pp
If using a custom BIO,
.Fa rbio
must implement either
.Xr BIO_meth_set_read_ex 3
or
.Xr BIO_meth_set_read 3 .
.Pp
.Fn SSL_set0_wbio
works in the same as
.Fn SSL_set0_rbio
except that it connects the BIO
.Fa wbio
for the write operations of the
.Fa ssl
object.
Note that if the rbio and wbio are the same then
.Fn SSL_set0_rbio
and
.Fn SSL_set0_wbio
each take ownership of one reference.
Therefore, it may be necessary to increment the number of references
available using
.Xr BIO_up_ref 3
before calling the set0 functions.
.Pp
If using a custom BIO,
.Fa wbio
must implement
.Xr BIO_meth_set_write_ex 3
or
.Xr BIO_meth_set_write 3 .
It additionally must implement
.Xr BIO_flush 3
using
.Sy BIO_CTRL_FLUSH
and
.Xr BIO_meth_set_ctrl 3 .
If flushing is unnecessary with
.Fa wbio ,
.Xr BIO_flush 3
should return one and do nothing.
.Pp
.Fn SSL_set_bio
is similar to
.Fn SSL_set0_rbio
and
.Fn SSL_set0_wbio
except that it connects both the
.Fa rbio
and the
.Fa wbio
at the same time, and transfers the ownership of
.Fa rbio
and
.Fa wbio
to
.Fa ssl
according to the following set of rules:
.Bl -bullet
.It
If neither the
.Fa rbio
or
.Fa wbio
have changed from their previous values then nothing is done.
.It
If the
.Fa rbio
and
.Fa wbio
parameters are different and both are different to their previously set
values then one reference is consumed for the rbio and one reference is
consumed for the wbio.
.It
If the
.Fa rbio
and
.Fa wbio
parameters are the same and the
.Fa rbio
is not the same as the previously set value then one reference is
consumed.
.It
If the
.Fa rbio
and
.Fa wbio
parameters are the same and the
.Fa rbio
is the same as the previously set value, then no additional references
are consumed.
.It
If the
.Fa rbio
and
.Fa wbio
parameters are different and the
.Fa rbio
is the same as the previously set value then one reference is consumed
for the
.Fa wbio
and no references are consumed for the
.Fa rbio .
.It
If the
.Fa rbio
and
.Fa wbio
parameters are different and the
.Fa wbio
is the same as the previously set value and the old
.Fa rbio
and
.Fa wbio
values were the same as each other then one reference is consumed for
the
.Fa rbio
and no references are consumed for the
.Fa wbio .
.It
If the
.Fa rbio
and
.Fa wbio
parameters are different and the
.Fa wbio
is the same as the previously set value and the old
.Fa rbio
and
.Fa wbio
values were different to each other, then one reference is consumed for
the
.Fa rbio
and one reference is consumed for the
.Fa wbio .
.El
.Pp
Because of this complexity, this function should be avoided; use
.Fn SSL_set0_rbio
and
.Fn SSL_set0_wbio
instead.
.Pp
Where a new BIO is set on a QUIC connection SSL object, blocking mode
will be disabled on that SSL object if the BIO cannot support blocking
mode.
If another BIO is subsequently set on the SSL object which can support
blocking mode, blocking mode will not be automatically re-enabled.
For more information, see
.Xr SSL_set_blocking_mode 3 .
.Sh RETURN VALUES
.Fn SSL_set_bio ,
.Fn SSL_set0_rbio
and
.Fn SSL_set0_wbio
cannot fail.
.Sh SEE ALSO
.Xr SSL_get_rbio 3 ,
.Xr SSL_connect 3 ,
.Xr SSL_accept 3 ,
.Xr SSL_shutdown 3 ,
.Xr ssl 7 ,
.Xr bio 7
.Sh HISTORY
.Fn SSL_set0_rbio
and
.Fn SSL_set0_wbio
were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
