.Dd 2025-09-30
.Dt SSL_SET_INCOMING_STREAM_POLICY 3ossl
.Os
.Sh NAME
.Nm SSL_set_incoming_stream_policy ,
.Nm SSL_INCOMING_STREAM_POLICY_AUTO ,
.Nm SSL_INCOMING_STREAM_POLICY_ACCEPT ,
.Nm SSL_INCOMING_STREAM_POLICY_REJECT
.Nd manage the QUIC incoming stream policy
.Sh SYNOPSIS
.In openssl/ssl.h
.Fd #define SSL_INCOMING_STREAM_POLICY_AUTO
.Fd #define SSL_INCOMING_STREAM_POLICY_ACCEPT
.Fd #define SSL_INCOMING_STREAM_POLICY_REJECT
.Ft int
.Fo SSL_set_incoming_stream_policy
.Fa "SSL *conn"
.Fa "int policy"
.Fa "uint64_t app_error_code"
.Fc
.Sh DESCRIPTION
.Fn SSL_set_incoming_stream_policy
policy changes the incoming stream policy for a QUIC connection.
Depending on the policy configured, OpenSSL QUIC may automatically
reject incoming streams initiated by the peer.
This is intended to ensure that legacy applications using single-stream
operation with a default stream on a QUIC connection SSL object are not
passed remotely-initiated streams by a peer which those applications are
not prepared to handle.
.Pp
.Fa app_error_code
is an application error code which will be used in any QUIC
.Sy STOP_SENDING
or
.Sy RESET_STREAM
frames generated to implement the policy.
The default application error code is 0.
.Pp
The valid values for
.Fa policy
are:
.Bl -tag -width Ds
.It SSL_INCOMING_STREAM_POLICY_AUTO
This is the default setting.
Incoming streams are accepted according to the following rules:
.Bl -bullet
.It
If the default stream mode (configured using
.Xr SSL_set_default_stream_mode 3 )
is set to
.Sy SSL_DEFAULT_STREAM_MODE_AUTO_BIDI
(the default) or
.Sy SSL_DEFAULT_STREAM_MODE_AUTO_UNI ,
the incoming stream is rejected.
.It
Otherwise (where the default stream mode is
.Sy SSL_DEFAULT_STREAM_MODE_NONE Ns ),
the application is assumed to be stream aware, and the incoming stream
is accepted.
.El
.It SSL_INCOMING_STREAM_POLICY_ACCEPT
Always accept incoming streams, allowing them to be dequeued using
.Xr SSL_accept_stream 3 .
.It SSL_INCOMING_STREAM_POLICY_REJECT
Always reject incoming streams.
.El
.Pp
Where an incoming stream is rejected, it is rejected immediately and it
is not possible to gain access to the stream using
.Xr SSL_accept_stream 3 .
The stream is rejected using QUIC
.Sy STOP_SENDING
and
.Sy RESET_STREAM
frames as appropriate.
.Sh RETURN VALUES
Returns 1 on success and 0 on failure.
.Pp
This function fails if called on a QUIC stream SSL object, or on a
non-QUIC SSL object.
.Sh SEE ALSO
.Xr SSL_set_default_stream_mode 3 ,
.Xr SSL_accept_stream 3
.Sh HISTORY
.Fn SSL_set_incoming_stream_policy
was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2002-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
