.Dd 2025-09-30
.Dt SSL_CTX_SET_SRP_PASSWORD 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set_srp_username ,
.Nm SSL_CTX_set_srp_password ,
.Nm SSL_CTX_set_srp_strength ,
.Nm SSL_CTX_set_srp_cb_arg ,
.Nm SSL_CTX_set_srp_username_callback ,
.Nm SSL_CTX_set_srp_client_pwd_callback ,
.Nm SSL_CTX_set_srp_verify_param_callback ,
.Nm SSL_set_srp_server_param ,
.Nm SSL_set_srp_server_param_pw ,
.Nm SSL_get_srp_g ,
.Nm SSL_get_srp_N ,
.Nm SSL_get_srp_username ,
.Nm SSL_get_srp_userinfo
.Nd SRP control operations
.Sh SYNOPSIS
.In openssl/ssl.h
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft int
.Fo SSL_CTX_set_srp_username
.Fa "SSL_CTX *ctx"
.Fa "char *name"
.Fc
.Ft int
.Fo SSL_CTX_set_srp_password
.Fa "SSL_CTX *ctx"
.Fa "char *password"
.Fc
.Ft int
.Fo SSL_CTX_set_srp_strength
.Fa "SSL_CTX *ctx"
.Fa "int strength"
.Fc
.Ft int
.Fo SSL_CTX_set_srp_cb_arg
.Fa "SSL_CTX *ctx"
.Fa "void *arg"
.Fc
.Ft int
.Fo SSL_CTX_set_srp_username_callback
.Fa "SSL_CTX *ctx"
.Fa "int (*cb) (SSL *s"
.Fa "int *ad"
.Fa "void *arg)"
.Fc
.Ft int
.Fo SSL_CTX_set_srp_client_pwd_callback
.Fa "SSL_CTX *ctx"
.Fa "char *(*cb) (SSL *s"
.Fa "void *arg)"
.Fc
.Ft int
.Fo SSL_CTX_set_srp_verify_param_callback
.Fa "SSL_CTX *ctx"
.Fa "int (*cb) (SSL *s"
.Fa "void *arg)"
.Fc
.Ft int
.Fo SSL_set_srp_server_param
.Fa "SSL *s"
.Fa "const BIGNUM *N"
.Fa "const BIGNUM *g"
.Fa "BIGNUM *sa"
.Fa "BIGNUM *v"
.Fa "char *info"
.Fc
.Ft int
.Fo SSL_set_srp_server_param_pw
.Fa "SSL *s"
.Fa "const char *user"
.Fa "const char *pass"
.Fa "const char *grp"
.Fc
.Ft BIGNUM *
.Fo SSL_get_srp_g
.Fa "SSL *s"
.Fc
.Ft BIGNUM *
.Fo SSL_get_srp_N
.Fa "SSL *s"
.Fc
.Ft char *
.Fo SSL_get_srp_username
.Fa "SSL *s"
.Fc
.Ft char *
.Fo SSL_get_srp_userinfo
.Fa "SSL *s"
.Fc
.Sh DESCRIPTION
All of the functions described on this page are deprecated.
There are no available replacement functions at this time.
.Pp
These functions provide access to SRP (Secure Remote Password)
parameters, an alternate authentication mechanism for TLS. SRP allows
the use of usernames and passwords over unencrypted channels without
revealing the password to an eavesdropper.
SRP also supplies a shared secret at the end of the authentication
sequence that can be used to generate encryption keys.
.Pp
The SRP protocol, version 3 is specified in RFC 2945. SRP version 6 is
described in RFC 5054 with applications to TLS authentication.
.Pp
The
.Fn SSL_CTX_set_srp_username
function sets the SRP username for
.Fa ctx .
This should be called on the client prior to creating a connection to
the server.
The length of
.Fa name
must be shorter or equal to 255 characters.
.Pp
The
.Fn SSL_CTX_set_srp_password
function sets the SRP password for
.Fa ctx .
This may be called on the client prior to creating a connection to the
server.
This overrides the effect of
.Fn SSL_CTX_set_srp_client_pwd_callback .
.Pp
The
.Fn SSL_CTX_set_srp_strength
function sets the SRP strength for
.Fa ctx .
This is the minimal length of the SRP prime in bits.
If not specified 1024 is used.
If not satisfied by the server key exchange the connection will be
rejected.
.Pp
The
.Fn SSL_CTX_set_srp_cb_arg
function sets an extra parameter that will be passed to all following
callbacks as
.Fa arg .
.Pp
The
.Fn SSL_CTX_set_srp_username_callback
function sets the server side callback that is invoked when an SRP
username is found in a ClientHello.
The callback parameters are the SSL connection
.Fa s ,
a writable error flag
.Fa ad
and the extra argument
.Fa arg
set by
.Fn SSL_CTX_set_srp_cb_arg .
This callback should setup the server for the key exchange by calling
.Fn SSL_set_srp_server_param
with the appropriate parameters for the received username.
The username can be obtained by calling
.Fn SSL_get_srp_username .
See
.Xr SRP_VBASE_init 3
to parse the verifier file created by
.Xr openssl-srp 1
or
.Xr SRP_create_verifier 3
to generate it.
The callback should return
.Sy SSL_ERROR_NONE
to proceed with the server key exchange,
.Sy SSL3_AL_FATAL
for a fatal error or any value < 0 for a retryable error.
In the event of a
.Sy SSL3_AL_FATAL
the alert flag given by
.Sy *al
will be sent back.
By default this will be
.Sy SSL_AD_UNKNOWN_PSK_IDENTITY .
.Pp
The
.Fn SSL_CTX_set_srp_client_pwd_callback
function sets the client password callback on the client.
The callback parameters are the SSL connection
.Fa s
and the extra argument
.Fa arg
set by
.Fn SSL_CTX_set_srp_cb_arg .
The callback will be called as part of the generation of the client
secrets.
It should return the client password in text form or NULL to abort the
connection.
The resulting memory will be freed by the library as part of the
callback resolution.
This overrides the effect of
.Fn SSL_CTX_set_srp_password .
.Pp
The
.Fn SSL_CTX_set_srp_verify_param_callback
sets the SRP gN parameter verification callback on the client.
This allows the client to perform custom verification when receiving the
server SRP proposed parameters.
The callback parameters are the SSL connection
.Fa s
and the extra argument
.Fa arg
set by
.Fn SSL_CTX_set_srp_cb_arg .
The callback should return a positive value to accept the server
parameters.
Returning 0 or a negative value will abort the connection.
The server parameters can be obtained by calling
.Fn SSL_get_srp_N
and
.Fn SSL_get_srp_g .
Sanity checks are already performed by the library after the handshake
(B % N non zero, check against the strength parameter) and are not
necessary.
If no callback is set the g and N parameters will be checked against
known RFC 5054 values.
.Pp
The
.Fn SSL_set_srp_server_param
function sets all SRP parameters for the connection
.Fa s .
.Fa N
and
.Fa g
are the SRP group parameters,
.Fa sa
is the user salt,
.Fa v
the password verifier and
.Fa info
is the optional user info.
.Pp
The
.Fn SSL_set_srp_server_param_pw
function sets all SRP parameters for the connection
.Fa s
by generating a random salt and a password verifier.
.Fa user
is the username,
.Fa pass
the password and
.Fa grp
the SRP group parameters identifier for
.Xr SRP_get_default_gN 3 .
.Pp
The
.Fn SSL_get_srp_g
function returns the SRP group generator for
.Fa s ,
or from the underlying SSL_CTX if it is NULL.
.Pp
The
.Fn SSL_get_srp_N
function returns the SRP prime for
.Fa s ,
or from the underlying SSL_CTX if it is NULL.
.Pp
The
.Fn SSL_get_srp_username
function returns the SRP username for
.Fa s ,
or from the underlying SSL_CTX if it is NULL.
.Pp
The
.Fn SSL_get_srp_userinfo
function returns the SRP user info for
.Fa s ,
or from the underlying SSL_CTX if it is NULL.
.Sh RETURN VALUES
All SSL_CTX_set_* functions return 1 on success and 0 on failure.
.Pp
.Fn SSL_set_srp_server_param
returns 1 on success and -1 on failure.
.Pp
The SSL_get_SRP_* functions return a pointer to the requested data, the
memory is owned by the library and should not be freed by the caller.
.Sh EXAMPLES
Setup SRP parameters on the client:
.Bd -literal
 #include <openssl/ssl.h>

 const char *username = "username";
 const char *password = "password";

 SSL_CTX *ctx = SSL_CTX_new(TLS_client_method());
 if (!ctx)
     /* Error */
 if (!SSL_CTX_set_srp_username(ctx, username))
     /* Error */
 if (!SSL_CTX_set_srp_password(ctx, password))
     /* Error */
.Ed
.Pp
Setup SRP server with verifier file:
.Bd -literal
 #include <openssl/srp.h>
 #include <openssl/ssl.h>

 const char *srpvfile = "password.srpv";

 int srpServerCallback(SSL *s, int *ad, void *arg)
 {
     SRP_VBASE *srpData = (SRP_VBASE*) arg;
     char *username = SSL_get_srp_username(s);

     SRP_user_pwd *user_pwd = SRP_VBASE_get1_by_user(srpData, username);
     if (!user_pwd)
         /* Error */
         return SSL3_AL_FATAL;

     if (SSL_set_srp_server_param(s, user_pwd->N, user_pwd->g,
         user_pwd->s, user_pwd->v, user_pwd->info) < 0)
         /* Error */

     SRP_user_pwd_free(user_pwd);
     return SSL_ERROR_NONE;
 }

 SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());
 if (!ctx)
     /* Error */

 /*
  * seedKey should contain a NUL terminated sequence
  * of random non NUL bytes
  */
 const char *seedKey;

 SRP_VBASE *srpData = SRP_VBASE_new(seedKey);
 if (SRP_VBASE_init(srpData, (char*) srpvfile) != SRP_NO_ERROR)
    /* Error */

 SSL_CTX_set_srp_cb_arg(ctx, srpData);
 SSL_CTX_set_srp_username_callback(ctx, srpServerCallback);
.Ed
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr openssl-srp 1 ,
.Xr SRP_VBASE_new 3 ,
.Xr SRP_create_verifier 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.1 and deprecated in OpenSSL
3.0.
.Sh COPYRIGHT
Copyright 2018-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
