.Dd 2025-09-30
.Dt SSL_CTX_ADD1_CHAIN_CERT 3ossl
.Os
.Sh NAME
.Nm SSL_CTX_set0_chain ,
.Nm SSL_CTX_set1_chain ,
.Nm SSL_CTX_add0_chain_cert ,
.Nm SSL_CTX_add1_chain_cert ,
.Nm SSL_CTX_get0_chain_certs ,
.Nm SSL_CTX_clear_chain_certs ,
.Nm SSL_set0_chain ,
.Nm SSL_set1_chain ,
.Nm SSL_add0_chain_cert ,
.Nm SSL_add1_chain_cert ,
.Nm SSL_get0_chain_certs ,
.Nm SSL_clear_chain_certs ,
.Nm SSL_CTX_build_cert_chain ,
.Nm SSL_build_cert_chain ,
.Nm SSL_CTX_select_current_cert ,
.Nm SSL_select_current_cert ,
.Nm SSL_CTX_set_current_cert ,
.Nm SSL_set_current_cert
.Nd extra chain certificate processing
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft int
.Fo SSL_CTX_set0_chain
.Fa "SSL_CTX *ctx"
.Fa "STACK_OF(X509) *sk"
.Fc
.Ft int
.Fo SSL_CTX_set1_chain
.Fa "SSL_CTX *ctx"
.Fa "STACK_OF(X509) *sk"
.Fc
.Ft int
.Fo SSL_CTX_add0_chain_cert
.Fa "SSL_CTX *ctx"
.Fa "X509 *x509"
.Fc
.Ft int
.Fo SSL_CTX_add1_chain_cert
.Fa "SSL_CTX *ctx"
.Fa "X509 *x509"
.Fc
.Ft int
.Fo SSL_CTX_get0_chain_certs
.Fa "SSL_CTX *ctx"
.Fa "STACK_OF(X509) **sk"
.Fc
.Ft int
.Fo SSL_CTX_clear_chain_certs
.Fa "SSL_CTX *ctx"
.Fc
.Ft int
.Fo SSL_set0_chain
.Fa "SSL *ssl"
.Fa "STACK_OF(X509) *sk"
.Fc
.Ft int
.Fo SSL_set1_chain
.Fa "SSL *ssl"
.Fa "STACK_OF(X509) *sk"
.Fc
.Ft int
.Fo SSL_add0_chain_cert
.Fa "SSL *ssl"
.Fa "X509 *x509"
.Fc
.Ft int
.Fo SSL_add1_chain_cert
.Fa "SSL *ssl"
.Fa "X509 *x509"
.Fc
.Ft int
.Fo SSL_get0_chain_certs
.Fa "SSL *ssl"
.Fa "STACK_OF(X509) **sk"
.Fc
.Ft int
.Fo SSL_clear_chain_certs
.Fa "SSL *ssl"
.Fc
.Ft int
.Fo SSL_CTX_build_cert_chain
.Fa "SSL_CTX *ctx"
.Fa flags
.Fc
.Ft int
.Fo SSL_build_cert_chain
.Fa "SSL *ssl"
.Fa flags
.Fc
.Ft int
.Fo SSL_CTX_select_current_cert
.Fa "SSL_CTX *ctx"
.Fa "X509 *x509"
.Fc
.Ft int
.Fo SSL_select_current_cert
.Fa "SSL *ssl"
.Fa "X509 *x509"
.Fc
.Ft int
.Fo SSL_CTX_set_current_cert
.Fa "SSL_CTX *ctx"
.Fa "long op"
.Fc
.Ft int
.Fo SSL_set_current_cert
.Fa "SSL *ssl"
.Fa "long op"
.Fc
.Sh DESCRIPTION
.Fn SSL_CTX_set0_chain
and
.Fn SSL_CTX_set1_chain
set the certificate chain associated with the current certificate of
.Fa ctx
to
.Fa sk .
.Pp
.Fn SSL_CTX_add0_chain_cert
and
.Fn SSL_CTX_add1_chain_cert
append the single certificate
.Fa x509
to the chain associated with the current certificate of
.Fa ctx .
.Pp
.Fn SSL_CTX_get0_chain_certs
retrieves the chain associated with the current certificate of
.Fa ctx .
.Pp
.Fn SSL_CTX_clear_chain_certs
clears any existing chain associated with the current certificate of
.Fa ctx .
(This is implemented by calling
.Fn SSL_CTX_set0_chain
with
.Fa sk
set to
.Dv NULL Ns ).
.Pp
.Fn SSL_CTX_build_cert_chain
builds the certificate chain for
.Fa ctx .
Normally this uses the chain store or the verify store if the chain
store is not set.
If the function is successful the built chain will replace any existing
chain.
The
.Vt flags
parameter can be set to
.Sy SSL_BUILD_CHAIN_FLAG_UNTRUSTED
to use existing chain certificates as untrusted CAs,
.Sy SSL_BUILD_CHAIN_FLAG_NO_ROOT
to omit the root CA from the built chain,
.Sy SSL_BUILD_CHAIN_FLAG_CHECK
to use all existing chain certificates only to build the chain
(effectively sanity checking and rearranging them if necessary), the
flag
.Sy SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR
ignores any errors during verification: if flag
.Sy SSL_BUILD_CHAIN_FLAG_CLEAR_ERROR
is also set verification errors are cleared from the error queue.
Details of the chain building process are described in
.Xr openssl-verification-options 1 .
.Pp
Each of these functions operates on the
.Em current
end entity (i.e.
server or client) certificate.
This is the last certificate loaded or selected on the corresponding
.Fa ctx
structure.
.Pp
.Fn SSL_CTX_select_current_cert
selects
.Fa x509
as the current end entity certificate, but only if
.Fa x509
has already been loaded into
.Fa ctx
using a function such as
.Xr SSL_CTX_use_certificate 3 .
.Pp
.Fn SSL_set0_chain ,
.Fn SSL_set1_chain ,
.Fn SSL_add0_chain_cert ,
.Fn SSL_add1_chain_cert ,
.Fn SSL_get0_chain_certs ,
.Fn SSL_clear_chain_certs ,
.Fn SSL_build_cert_chain ,
.Fn SSL_select_current_cert
and
.Fn SSL_set_current_cert
are similar except they apply to SSL structure
.Fa ssl .
.Pp
.Fn SSL_CTX_set_current_cert
changes the current certificate to a value based on the
.Fa op
argument.
Currently
.Fa op
can be
.Sy SSL_CERT_SET_FIRST
to use the first valid certificate or
.Sy SSL_CERT_SET_NEXT
to set the next valid certificate after the current certificate.
These two operations can be used to iterate over all certificates in an
.Vt SSL_CTX
structure.
.Pp
.Fn SSL_set_current_cert
also supports the option
.Sy SSL_CERT_SET_SERVER .
If
.Fa ssl
is a server and has sent a certificate to a connected client this option
sets that certificate to the current certificate and returns 1. If the
negotiated cipher suite is anonymous (and thus no certificate will be
sent) 2 is returned and the current certificate is unchanged.
If
.Fa ssl
is not a server or a certificate has not been sent 0 is returned and the
current certificate is unchanged.
.Pp
All these functions are implemented as macros.
Those containing a
.Sy 1
increment the reference count of the supplied certificate or chain so it
must be freed at some point after the operation.
Those containing a
.Sy 0
do not increment reference counts and the supplied certificate or chain
.Sy MUST NOT
be freed after the operation.
.Sh NOTES
The chains associate with an SSL_CTX structure are copied to any SSL
structures when
.Xr SSL_new 3
is called.
SSL structures will not be affected by any chains subsequently changed
in the parent SSL_CTX.
.Pp
One chain can be set for each key type supported by a server.
So, for example, an RSA and a DSA certificate can (and often will) have
different chains.
.Pp
The functions
.Fn SSL_CTX_build_cert_chain
and
.Fn SSL_build_cert_chain
can be used to check application configuration and to ensure any
necessary subordinate CAs are sent in the correct order.
Misconfigured applications sending incorrect certificate chains often
cause problems with peers.
.Pp
For example an application can add any set of certificates using
.Xr SSL_CTX_use_certificate_chain_file 3
then call
.Fn SSL_CTX_build_cert_chain
with the option
.Sy SSL_BUILD_CHAIN_FLAG_CHECK
to check and reorder them.
.Pp
Applications can issue non fatal warnings when checking chains by
setting the flag
.Sy SSL_BUILD_CHAIN_FLAG_IGNORE_ERRORS
and checking the return value.
.Pp
Calling
.Fn SSL_CTX_build_cert_chain
or
.Fn SSL_build_cert_chain
is more efficient than the automatic chain building as it is only
performed once.
Automatic chain building is performed on each new session.
.Pp
If any certificates are added using these functions no certificates
added using
.Xr SSL_CTX_add_extra_chain_cert 3
will be used.
.Sh RETURN VALUES
.Fn SSL_set_current_cert
with
.Sy SSL_CERT_SET_SERVER
return 1 for success, 2 if no server certificate is used because the
cipher suites is anonymous and 0 for failure.
.Pp
.Fn SSL_CTX_build_cert_chain
and
.Fn SSL_build_cert_chain
return 1 for success and 0 for failure.
If the flag
.Sy SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR
and a verification error occurs then 2 is returned.
.Pp
All other functions return 1 for success and 0 for failure.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CTX_add_extra_chain_cert 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2013-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
