.Dd 2025-09-30
.Dt SSL_CONF_CTX_NEW 3ossl
.Os
.Sh NAME
.Nm SSL_CONF_CTX_new ,
.Nm SSL_CONF_CTX_free
.Nd SSL configuration allocation functions
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft SSL_CONF_CTX *
.Fo SSL_CONF_CTX_new
.Fa void
.Fc
.Ft void
.Fo SSL_CONF_CTX_free
.Fa "SSL_CONF_CTX *cctx"
.Fc
.Sh DESCRIPTION
The function
.Fn SSL_CONF_CTX_new
allocates and initialises an
.Vt SSL_CONF_CTX
structure for use with the SSL_CONF functions.
.Pp
The function
.Fn SSL_CONF_CTX_free
frees up the context
.Fa cctx .
If
.Fa cctx
is NULL nothing is done.
.Sh RETURN VALUES
.Fn SSL_CONF_CTX_new
returns either the newly allocated
.Vt SSL_CONF_CTX
structure or
.Dv NULL
if an error occurs.
.Pp
.Fn SSL_CONF_CTX_free
does not return a value.
.Sh SEE ALSO
.Xr ssl 7 ,
.Xr SSL_CONF_CTX_set_flags 3 ,
.Xr SSL_CONF_CTX_set_ssl_ctx 3 ,
.Xr SSL_CONF_CTX_set1_prefix 3 ,
.Xr SSL_CONF_cmd 3 ,
.Xr SSL_CONF_cmd_argv 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2012-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
