.Dd 2025-09-30
.Dt SSL_GET1_BUILTIN_SIGALGS 3ossl
.Os
.Sh NAME
.Nm SSL_get1_builtin_sigalgs
.Nd get list of built-in signature algorithms
.Sh SYNOPSIS
.In openssl/tls1.h
.Ft char *
.Fo SSL_get1_builtin_sigalgs
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Sh DESCRIPTION
Return the colon-separated list of built-in and available TLS signature
algorithms.
The string returned must be freed by the user using
.Xr OPENSSL_free 3 .
.Sh NOTES
The string may be empty (strlen==0) if none of the built-in TLS
signature algorithms can be activated, e.g., if suitable providers are
missing.
.Sh RETURN VALUES
NULL may be returned if no memory could be allocated.
Otherwise, a newly allocated string is always returned but it may have
strlen == 0.
.Sh HISTORY
This function was added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
