.Dd 2025-09-30
.Dt TS_RESP_CTX_NEW 3ossl
.Os
.Sh NAME
.Nm TS_RESP_CTX_new_ex ,
.Nm TS_RESP_CTX_new ,
.Nm TS_RESP_CTX_free
.Nd Timestamp response context object creation
.Sh SYNOPSIS
.In openssl/ts.h
.Ft TS_RESP_CTX *
.Fo TS_RESP_CTX_new_ex
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft TS_RESP_CTX *
.Fo TS_RESP_CTX_new
.Fa void
.Fc
.Ft void
.Fo TS_RESP_CTX_free
.Fa "TS_RESP_CTX *ctx"
.Fc
.Sh DESCRIPTION
Creates a response context that can be used for generating responses.
.Pp
.Fn TS_RESP_CTX_new_ex
allocates and initializes a TS_RESP_CTX structure with a library context
of
.Fa libctx
and a property query of
.Fa propq .
The library context and property query can be used to select which
providers supply the fetched algorithms.
.Pp
.Fn TS_RESP_CTX_new
is similar to
.Fn TS_RESP_CTX_new_ex
but sets the library context and property query to NULL. This results in
the default (NULL) library context being used for any operations
requiring algorithm fetches.
.Pp
.Fn TS_RESP_CTX_free
frees the
.Vt TS_RESP_CTX
object
.Fa ctx .
If the argument is NULL, nothing is done.
.Sh RETURN VALUES
If the allocation fails,
.Fn TS_RESP_CTX_new_ex
and
.Fn TS_RESP_CTX_new
return NULL, otherwise it returns a pointer to the newly allocated
structure.
.Sh HISTORY
The function
.Fn TS_RESP_CTX_new_ex
was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2021-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
