.Dd 2025-09-30
.Dt UI_UTIL_READ_PW 3ossl
.Os
.Sh NAME
.Nm UI_UTIL_read_pw_string ,
.Nm UI_UTIL_read_pw ,
.Nm UI_UTIL_wrap_read_pem_callback
.Nd user interface utilities
.Sh SYNOPSIS
.In openssl/ui.h
.Ft int
.Fo UI_UTIL_read_pw_string
.Fa "char *buf"
.Fa "int length"
.Fa "const char *prompt"
.Fa "int verify"
.Fc
.Ft int
.Fo UI_UTIL_read_pw
.Fa "char *buf"
.Fa "char *buff"
.Fa "int size"
.Fa "const char *prompt"
.Fa "int verify"
.Fc
.Ft UI_METHOD *
.Fo UI_UTIL_wrap_read_pem_callback
.Fa "pem_password_cb *cb"
.Fa "int rwflag"
.Fc
.Sh DESCRIPTION
.Fn UI_UTIL_read_pw_string
asks for a passphrase, using
.Fa prompt
as a prompt, and stores it in
.Fa buf .
The maximum allowed size is given with
.Fa length ,
including the terminating NUL byte.
If
.Fa verify
is nonzero, the password will be verified as well.
.Pp
.Fn UI_UTIL_read_pw
does the same as
.Fn UI_UTIL_read_pw_string ,
the difference is that you can give it an external buffer
.Fa buff
for the verification passphrase.
.Pp
.Fn UI_UTIL_wrap_read_pem_callback
can be used to create a temporary
.Vt UI_METHOD
that wraps a given PEM password callback
.Fa cb .
.Fa rwflag
is used to specify if this method will be used for passphrase entry
without (0) or with (1) verification.
When not used any more, the returned method should be freed with
.Xr UI_destroy_method 3 .
.Sh NOTES
.Fn UI_UTIL_read_pw_string
and
.Fn UI_UTIL_read_pw
use default
.Vt UI_METHOD .
See
.Xr UI_get_default_method 3
and friends for more information.
.Pp
The result from the
.Vt UI_METHOD
created by
.Fn UI_UTIL_wrap_read_pem_callback
will generate password strings in the encoding that the given password
callback generates.
The default password prompting functions (apart from
.Fn UI_UTIL_read_pw_string
and
.Fn UI_UTIL_read_pw ,
there is
.Xr PEM_def_callback 3 ,
.Xr EVP_read_pw_string 3
and
.Xr EVP_read_pw_string_min 3 )
all use the default
.Vt UI_METHOD .
.Sh RETURN VALUES
.Fn UI_UTIL_read_pw_string
and
.Fn UI_UTIL_read_pw
return 0 on success or a negative value on error.
.Pp
.Fn UI_UTIL_wrap_read_pem_callback
returns a valid
.Vt UI_METHOD
structure or NULL if an error occurred.
.Sh SEE ALSO
.Xr UI_get_default_method 3
.Sh COPYRIGHT
Copyright 2001-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
