.Dd 2025-09-30
.Dt X509_NEW 3ossl
.Os
.Sh NAME
.Nm X509_new ,
.Nm X509_new_ex ,
.Nm X509_free ,
.Nm X509_up_ref ,
.Nm X509_chain_up_ref ,
.Nm OSSL_STACK_OF_X509_free
.Nd X509 certificate ASN1 allocation and deallocation functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft X509 *
.Fo X509_new
.Fa void
.Fc
.Ft X509 *
.Fo X509_new_ex
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft void
.Fo X509_free
.Fa "X509 *a"
.Fc
.Ft int
.Fo X509_up_ref
.Fa "X509 *a"
.Fc
.Bd -literal
 STACK_OF(X509) *X509_chain_up_ref(STACK_OF(X509) *x);
 void OSSL_STACK_OF_X509_free(STACK_OF(X509) *certs);
.Ed
.Sh DESCRIPTION
The X509 ASN1 allocation routines allocate and free an X509 structure,
which represents an X509 certificate.
.Pp
.Fn X509_new_ex
allocates and initializes a X509 structure with a library context of
.Fa libctx ,
property query of
.Fa propq
and a reference count of
.Sy 1 .
Many X509 functions such as
.Xr X509_check_purpose 3 ,
and
.Xr X509_verify 3
use this library context to select which providers supply the fetched
algorithms (SHA1 is used internally).
This created X509 object can then be used when loading binary data using
.Xr d2i_X509 3 .
.Pp
.Fn X509_new
is similar to
.Fn X509_new_ex
but sets the library context and property query to NULL. This results in
the default (NULL) library context being used for any X509 operations
requiring algorithm fetches.
.Pp
.Fn X509_free
decrements the reference count of
.Vt X509
structure
.Fa a
and frees it up if the reference count is zero.
If the argument is NULL, nothing is done.
.Pp
.Fn X509_up_ref
increments the reference count of
.Fa a .
.Pp
.Xr X509_chain_up_ref 3
increases the reference count of all certificates in chain
.Sy x
and returns a copy of the stack, or an empty stack if
.Fa a
is NULL.
.Pp
.Xr OSSL_STACK_OF_X509_free 3
deallocates the given list of pointers to certificates after calling
.Fn X509_free
on all its elements.
If the argument is NULL, nothing is done.
.Sh NOTES
The function
.Fn X509_up_ref
if useful if a certificate structure is being used by several different
operations each of which will free it up after use: this avoids the need
to duplicate the entire certificate structure.
.Pp
The function
.Xr X509_chain_up_ref 3
doesn't just up the reference count of each certificate.
It also returns a copy of the stack, using
.Xr sk_X509_dup 3 ,
but it serves a similar purpose: the returned chain persists after the
original has been freed.
.Sh RETURN VALUES
If the allocation fails,
.Fn X509_new
returns NULL and sets an error code that can be obtained by
.Xr ERR_get_error 3 .
Otherwise it returns a pointer to the newly allocated structure.
.Pp
.Fn X509_up_ref
returns 1 for success and 0 for failure.
.Pp
.Xr X509_chain_up_ref 3
returns a copy of the stack or NULL if an error occurred.
.Pp
.Xr OSSL_STACK_OF_X509_free 3
has no return value.
.Sh SEE ALSO
.Xr d2i_X509 3 ,
.Xr ERR_get_error 3 ,
.Xr X509_CRL_get0_by_serial 3 ,
.Xr X509_get0_signature 3 ,
.Xr X509_get_ext_d2i 3 ,
.Xr X509_get_extension_flags 3 ,
.Xr X509_get_pubkey 3 ,
.Xr X509_get_subject_name 3 ,
.Xr X509_get_version 3 ,
.Xr X509_NAME_add_entry_by_txt 3 ,
.Xr X509_NAME_ENTRY_get_object 3 ,
.Xr X509_NAME_get_index_by_NID 3 ,
.Xr X509_NAME_print_ex 3 ,
.Xr X509_sign 3 ,
.Xr X509V3_get_d2i 3 ,
.Xr X509_verify_cert 3
.Sh HISTORY
.Fn X509_new_ex
was added in OpenSSL 3.0.
.Pp
.Xr OSSL_STACK_OF_X509_free 3
was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2002-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
