.Dd 2025-09-30
.Dt X509_STORE_SET_VERIFY_CB_FUNC 3ossl
.Os
.Sh NAME
.Nm X509_STORE_set_lookup_crls_cb ,
.Nm X509_STORE_set_verify_func ,
.Nm X509_STORE_get_cleanup ,
.Nm X509_STORE_set_cleanup ,
.Nm X509_STORE_get_lookup_crls ,
.Nm X509_STORE_set_lookup_crls ,
.Nm X509_STORE_get_lookup_certs ,
.Nm X509_STORE_set_lookup_certs ,
.Nm X509_STORE_get_check_policy ,
.Nm X509_STORE_set_check_policy ,
.Nm X509_STORE_get_cert_crl ,
.Nm X509_STORE_set_cert_crl ,
.Nm X509_STORE_get_check_crl ,
.Nm X509_STORE_set_check_crl ,
.Nm X509_STORE_get_get_crl ,
.Nm X509_STORE_set_get_crl ,
.Nm X509_STORE_get_check_revocation ,
.Nm X509_STORE_set_check_revocation ,
.Nm X509_STORE_get_check_issued ,
.Nm X509_STORE_set_check_issued ,
.Nm X509_STORE_CTX_get1_issuer ,
.Nm X509_STORE_get_get_issuer ,
.Nm X509_STORE_set_get_issuer ,
.Nm X509_STORE_CTX_get_verify ,
.Nm X509_STORE_set_verify ,
.Nm X509_STORE_get_verify_cb ,
.Nm X509_STORE_set_verify_cb_func ,
.Nm X509_STORE_set_verify_cb ,
.Nm X509_STORE_CTX_cert_crl_fn ,
.Nm X509_STORE_CTX_check_crl_fn ,
.Nm X509_STORE_CTX_check_issued_fn ,
.Nm X509_STORE_CTX_check_policy_fn ,
.Nm X509_STORE_CTX_check_revocation_fn ,
.Nm X509_STORE_CTX_cleanup_fn ,
.Nm X509_STORE_CTX_get_crl_fn ,
.Nm X509_STORE_CTX_get_issuer_fn ,
.Nm X509_STORE_CTX_lookup_certs_fn ,
.Nm X509_STORE_CTX_lookup_crls_fn
.Nd set verification callback
.Sh SYNOPSIS
.In openssl/x509_vfy.h
.Ft typedef int
.Fo 
.Fa *X509_STORE_CTX_get_issuer_fn
.Fc
(X509 **issuer,
.Bd -literal
                                             X509_STORE_CTX *ctx, X509 *x);
 typedef int (*X509_STORE_CTX_check_issued_fn)(X509_STORE_CTX *ctx,
                                               X509 *x, X509 *issuer);
 typedef int (*X509_STORE_CTX_check_revocation_fn)(X509_STORE_CTX *ctx);
 typedef int (*X509_STORE_CTX_get_crl_fn)(X509_STORE_CTX *ctx,
                                          X509_CRL **crl, X509 *x);
 typedef int (*X509_STORE_CTX_check_crl_fn)(X509_STORE_CTX *ctx, X509_CRL *crl);
 typedef int (*X509_STORE_CTX_cert_crl_fn)(X509_STORE_CTX *ctx,
                                           X509_CRL *crl, X509 *x);
 typedef int (*X509_STORE_CTX_check_policy_fn)(X509_STORE_CTX *ctx);
 typedef STACK_OF(X509) *(*X509_STORE_CTX_lookup_certs_fn)(X509_STORE_CTX *ctx,
                                                           const X509_NAME *nm);
 typedef STACK_OF(X509_CRL) *(*X509_STORE_CTX_lookup_crls_fn)(const
                                                              X509_STORE_CTX *ctx,
                                                              const X509_NAME *nm);
 typedef int (*X509_STORE_CTX_cleanup_fn)(X509_STORE_CTX *ctx);
.Ed
.Ft void
.Fo X509_STORE_set_verify_cb
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_verify_cb verify_cb"
.Fc
.Ft X509_STORE_CTX_verify_cb
.Fo X509_STORE_get_verify_cb
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_verify
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_verify_fn verify"
.Fc
.Ft X509_STORE_CTX_verify_fn
.Fo X509_STORE_CTX_get_verify
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft int
.Fo X509_STORE_CTX_get1_issuer
.Fa "X509 **issuer"
.Fa "X509_STORE_CTX *ctx"
.Fa "X509 *x"
.Fc
.Ft X509_STORE_CTX_get_issuer_fn
.Fo X509_STORE_get_get_issuer
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_get_issuer
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_get_issuer_fn get_issuer"
.Fc
.Ft void
.Fo X509_STORE_set_check_issued
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_check_issued_fn check_issued"
.Fc
.Ft X509_STORE_CTX_check_issued_fn
    
.Fo X509_STORE_get_check_issued
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_check_revocation
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_check_revocation_fn check_revocation"
.Fc
.Ft X509_STORE_CTX_check_revocation_fn
    
.Fo X509_STORE_get_check_revocation
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_get_crl
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_get_crl_fn get_crl"
.Fc
.Ft X509_STORE_CTX_get_crl_fn
.Fo X509_STORE_get_get_crl
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_check_crl
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_check_crl_fn check_crl"
.Fc
.Ft X509_STORE_CTX_check_crl_fn
    
.Fo X509_STORE_get_check_crl
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_cert_crl
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_cert_crl_fn cert_crl"
.Fc
.Ft X509_STORE_CTX_cert_crl_fn
.Fo X509_STORE_get_cert_crl
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_check_policy
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_check_policy_fn check_policy"
.Fc
.Ft X509_STORE_CTX_check_policy_fn
    
.Fo X509_STORE_get_check_policy
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_lookup_certs
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_lookup_certs_fn lookup_certs"
.Fc
.Ft X509_STORE_CTX_lookup_certs_fn
    
.Fo X509_STORE_get_lookup_certs
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_lookup_crls
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_lookup_crls_fn lookup_crls"
.Fc
.Ft X509_STORE_CTX_lookup_crls_fn
    
.Fo X509_STORE_get_lookup_crls
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_set_cleanup
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_cleanup_fn cleanup"
.Fc
.Ft X509_STORE_CTX_cleanup_fn
.Fo X509_STORE_get_cleanup
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft /* Aliases */
 void
.Fo X509_STORE_set_verify_cb_func
.Fa "X509_STORE *st"
.Fa "X509_STORE_CTX_verify_cb verify_cb"
.Fc
.Ft void
.Fo X509_STORE_set_verify_func
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_verify_fn verify"
.Fc
.Ft void
.Fo X509_STORE_set_lookup_crls_cb
.Fa "X509_STORE *xs"
.Fa "X509_STORE_CTX_lookup_crls_fn lookup_crls"
.Fc
.Sh DESCRIPTION
.Fn X509_STORE_set_verify_cb
sets the verification callback of
.Fa xs
to
.Fa verify_cb
overwriting the previous callback.
The callback assigned with this function becomes a default for the one
that can be assigned directly to the corresponding
.Vt X509_STORE_CTX ,
please see
.Xr X509_STORE_CTX_set_verify_cb 3
for further information.
.Pp
.Fn X509_STORE_set_verify
sets the final chain verification function for
.Fa xs
to
.Fa verify .
Its purpose is to go through the chain of certificates and check that
all signatures are valid and that the current time is within the limits
of each certificate's first and last validity time.
The final chain verification functions must return 0 on failure and 1 on
success.
.Em \&If no chain verification function is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_CTX_get1_issuer
tries to find a certificate from the
.Em store
component of
.Fa ctx
that has a subject name matching the issuer name of
.Fa x
and is accepted by the
.Fa check_issued
function in
.Fa ctx .
On success it assigns to
.Em *issuer
the first match that has a suitable validity period or otherwise has the
latest expiration date of all matching certificates.
If the function returns 1 the caller is responsible for freeing
.Em *issuer .
Note that this search does not support backtracking.
.Pp
.Fn X509_STORE_set_get_issuer
sets the function
.Fa get_issuer
that is used to get the "best" candidate issuer certificate of the given
certificate
.Fa x .
When such a certificate is found,
.Fa get_issuer
must up-ref and assign it to
.Em *issuer
and then return 1. Otherwise
.Fa get_issuer
must return 0 if not found and -1 (or 0) on failure.
If
.Fn X509_STORE_set_get_issuer
is not used or
.Fa get_issuer
is NULL then
.Fn X509_STORE_CTX_get1_issuer
is used as the default implementation.
.Pp
.Fn X509_STORE_set_check_issued
sets the function to check that a given certificate
.Fa x
is issued by the issuer certificate
.Fa issuer .
This function must return 0 on failure (among others if
.Fa x
hasn't been issued with
.Fa issuer )
and 1 on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_check_revocation
sets the revocation checking function.
Its purpose is to look through the final chain and check the revocation
status for each certificate.
It must return 0 on failure and 1 on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_get_crl
sets the function to get the crl for a given certificate
.Fa x .
When found, the crl must be assigned to
.Em *crl .
This function must return 0 on failure and 1 on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_check_crl
sets the function to check the validity of the given
.Em crl .
This function must return 0 on failure and 1 on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_cert_crl
sets the function to check the revocation status of the given
certificate
.Fa x
against the given
.Em crl .
This function must return 0 on failure and 1 on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_check_policy
sets the function to check the policies of all the certificates in the
final chain..
This function must return 0 on failure and 1 on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_lookup_certs
and
.Fn X509_STORE_set_lookup_crls
set the functions to look up all the certs or all the CRLs that match
the given name
.Em nm .
These functions return NULL on failure and a pointer to a stack of
certificates
.Pf ( Vt X509 )
or to a stack of CRLs
.Pf ( Sy X509_CRL )
on success.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_set_cleanup
sets the final cleanup function, which is called when the context
.Pf ( Vt X509_STORE_CTX )
is being torn down.
This function doesn't return any value.
.Em \&If no function to get the issuer is provided, the internal default function will be used instead.
.Pp
.Fn X509_STORE_get_verify_cb ,
.Fn X509_STORE_CTX_get_verify ,
.Fn X509_STORE_get_get_issuer ,
.Fn X509_STORE_get_check_issued ,
.Fn X509_STORE_get_check_revocation ,
.Fn X509_STORE_get_get_crl ,
.Fn X509_STORE_get_check_crl ,
.Fn X509_STORE_set_verify ,
.Fn X509_STORE_set_get_issuer ,
.Fn X509_STORE_get_cert_crl ,
.Fn X509_STORE_get_check_policy ,
.Fn X509_STORE_get_lookup_certs ,
.Fn X509_STORE_get_lookup_crls
and
.Fn X509_STORE_get_cleanup
all return the function pointer assigned with
.Fn X509_STORE_set_check_issued ,
.Fn X509_STORE_set_check_revocation ,
.Fn X509_STORE_set_get_crl ,
.Fn X509_STORE_set_check_crl ,
.Fn X509_STORE_set_cert_crl ,
.Fn X509_STORE_set_check_policy ,
.Fn X509_STORE_set_lookup_certs ,
.Fn X509_STORE_set_lookup_crls
and
.Fn X509_STORE_set_cleanup ,
or NULL if no assignment has been made.
.Pp
.Fn X509_STORE_set_verify_cb_func ,
.Fn X509_STORE_set_verify_func
and
.Fn X509_STORE_set_lookup_crls_cb
are aliases for
.Fn X509_STORE_set_verify_cb ,
.Fn X509_STORE_set_verify
and X509_STORE_set_lookup_crls, available as macros for backward
compatibility.
.Sh NOTES
All the callbacks from a
.Vt X509_STORE
are inherited by the corresponding
.Vt X509_STORE_CTX
structure when it is initialized.
See
.Xr X509_STORE_CTX_set_verify_cb 3
for further details.
.Sh BUGS
The macro version of this function was the only one available before
OpenSSL 1.0.0.
.Sh RETURN VALUES
The
.Xr X509_STORE_set_* 3
functions do not return a value.
.Pp
The
.Xr X509_STORE_get_* 3
functions return a pointer of the appropriate function type.
.Pp
.Fn X509_STORE_CTX_get1_issuer
returns 1 if a suitable certificate is found, 0 if not found, -1 on
other error.
.Sh SEE ALSO
.Xr X509_STORE_CTX_set_verify_cb 3 ,
.Xr X509_STORE_CTX_get0_chain 3 ,
.Xr X509_STORE_CTX_verify_cb 3 ,
.Xr X509_STORE_CTX_verify_fn 3 ,
.Xr CMS_verify 3
.Sh HISTORY
The
.Fn X509_STORE_set_verify_cb
function was added in OpenSSL 1.0.0.
.Pp
The functions
.Fn X509_STORE_set_verify_cb ,
.Fn X509_STORE_get_verify_cb ,
.Fn X509_STORE_set_verify ,
.Fn X509_STORE_CTX_get_verify ,
.Fn X509_STORE_set_get_issuer ,
.Fn X509_STORE_get_get_issuer ,
.Fn X509_STORE_set_check_issued ,
.Fn X509_STORE_get_check_issued ,
.Fn X509_STORE_set_check_revocation ,
.Fn X509_STORE_get_check_revocation ,
.Fn X509_STORE_set_get_crl ,
.Fn X509_STORE_get_get_crl ,
.Fn X509_STORE_set_check_crl ,
.Fn X509_STORE_get_check_crl ,
.Fn X509_STORE_set_cert_crl ,
.Fn X509_STORE_get_cert_crl ,
.Fn X509_STORE_set_check_policy ,
.Fn X509_STORE_get_check_policy ,
.Fn X509_STORE_set_lookup_certs ,
.Fn X509_STORE_get_lookup_certs ,
.Fn X509_STORE_set_lookup_crls ,
.Fn X509_STORE_get_lookup_crls ,
.Fn X509_STORE_set_cleanup
and
.Fn X509_STORE_get_cleanup
were added in OpenSSL 1.1.0.
.Sh COPYRIGHT
Copyright 2009-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
