.Dd 2025-09-30
.Dt X509_CHECK_HOST 3ossl
.Os
.Sh NAME
.Nm X509_check_host ,
.Nm X509_check_email ,
.Nm X509_check_ip ,
.Nm X509_check_ip_asc
.Nd X.509 certificate matching
.Sh SYNOPSIS
.In openssl/x509v3.h
.Ft int
.Fo X509_check_host
.Fa "X509 *"
.Fa "const char *name"
.Fa "size_t namelen"
.Fa "unsigned int flags"
.Fa "char **peername"
.Fc
.Ft int
.Fo X509_check_email
.Fa "X509 *"
.Fa "const char *address"
.Fa "size_t addresslen"
.Fa "unsigned int flags"
.Fc
.Ft int
.Fo X509_check_ip
.Fa "X509 *"
.Fa "const unsigned char *address"
.Fa "size_t addresslen"
.Fa "unsigned int flags"
.Fc
.Ft int
.Fo X509_check_ip_asc
.Fa "X509 *"
.Fa "const char *address"
.Fa "unsigned int flags"
.Fc
.Sh DESCRIPTION
The certificate matching functions are used to check whether a
certificate matches a given hostname, email address, or IP address.
The validity of the certificate and its trust level has to be checked by
other means.
.Pp
.Fn X509_check_host
checks if the certificate Subject Alternative Name (SAN) or Subject
CommonName (CN) matches the specified hostname, which must be encoded in
the preferred name syntax described in section 3.5 of RFC 1034. By
default, wildcards are supported and they match only in the left-most
label; but they may match part of that label with an explicit prefix or
suffix.
For example, by default, the host
.Fa name
"www.example.com" would match a certificate with a SAN or CN value of
"*.example.com", "w*.example.com" or "*w.example.com".
.Pp
Per section 6.4.2 of RFC 6125,
.Fa name
values representing international domain names must be given in A-label
form.
The
.Fa namelen
argument must be the number of characters in the name string or zero in
which case the length is calculated with
.Pf strlen( Fa name Ns ).
When
.Fa name
starts with a dot (e.g.
".example.com"), it will be matched by a certificate valid for any
sub-domain of
.Fa name ,
(see also
.Sy X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS
below).
.Pp
When the certificate is matched, and
.Fa peername
is not NULL, a pointer to a copy of the matching SAN or CN from the peer
certificate is stored at the address passed in
.Fa peername .
The application is responsible for freeing the peername via
.Xr OPENSSL_free 3
when it is no longer needed.
.Pp
.Fn X509_check_email
checks if the certificate matches the specified email
.Fa address .
The mailbox syntax of RFC 822 is supported, comments are not allowed,
and no attempt is made to normalize quoted characters.
The mailbox syntax of RFC 6531 is supported for SmtpUTF8Mailbox address
in subjectAltName according to RFC 8398, with similar limitations as for
RFC 822 syntax, and no attempt is made to convert from A-label to
U-label before comparison.
The
.Fa addresslen
argument must be the number of characters in the address string or zero
in which case the length is calculated with
.Pf strlen( Fa address Ns ).
.Pp
.Fn X509_check_ip
checks if the certificate matches a specified IPv4 or IPv6 address.
The
.Fa address
array is in binary format, in network byte order.
The length is either 4 (IPv4) or 16 (IPv6). Only explicitly marked
addresses in the certificates are considered; IP addresses stored in DNS
names and Common Names are ignored.
There are currently no
.Fa flags
that would affect the behavior of this call.
.Pp
.Fn X509_check_ip_asc
is similar, except that the NUL-terminated string
.Fa address
is first converted to the internal representation.
.Pp
The
.Fa flags
argument is usually 0. It can be the bitwise OR of the flags:
.Bl -tag -width Ds
.It Sy X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT ,
.It Sy X509_CHECK_FLAG_NEVER_CHECK_SUBJECT ,
.It Sy X509_CHECK_FLAG_NO_WILDCARDS ,
.It Sy X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS ,
.It Sy X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS .
.It Sy X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS .
.El
The
.Sy X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT
flag causes the function to consider the subject DN even if the
certificate contains at least one subject alternative name of the right
type (DNS name or email address as appropriate); the default is to
ignore the subject DN when at least one corresponding subject
alternative names is present.
.Pp
The
.Sy X509_CHECK_FLAG_NEVER_CHECK_SUBJECT
flag causes the function to never consider the subject DN even if the
certificate contains no subject alternative names of the right type (DNS
name or email address as appropriate); the default is to use the subject
DN when no corresponding subject alternative names are present.
If both
.Sy X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT
and
.Sy X509_CHECK_FLAG_NEVER_CHECK_SUBJECT
are specified, the latter takes precedence and the subject DN is not
checked for matching names.
.Pp
If set,
.Sy X509_CHECK_FLAG_NO_WILDCARDS
disables wildcard expansion; this only applies to
.Sy X509_check_host .
.Pp
If set,
.Sy X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS
suppresses support for "*" as wildcard pattern in labels that have a
prefix or suffix, such as: "www*" or "*www"; this only applies to
.Sy X509_check_host .
.Pp
If set,
.Sy X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS
allows a "*" that constitutes the complete label of a DNS name (e.g.
"*.example.com") to match more than one label in
.Fa name ;
this flag only applies to
.Sy X509_check_host .
.Pp
If set,
.Sy X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS
restricts
.Fa name
values which start with ".", that would otherwise match any sub-domain
in the peer certificate, to only match direct child sub-domains.
Thus, for instance, with this flag set a
.Fa name
of ".example.com" would match a peer certificate with a DNS name of
"www.example.com", but would not match a peer certificate with a DNS
name of "www.sub.example.com"; this flag only applies to
.Sy X509_check_host .
.Sh RETURN VALUES
The functions return 1 for a successful match, 0 for a failed match and
-1 for an internal error: typically a memory allocation failure or an
ASN.1 decoding error.
.Pp
All functions can also return -2 if the input is malformed.
For example,
.Fn X509_check_host
returns -2 if the provided
.Fa name
contains embedded NULs.
.Sh NOTES
Applications are encouraged to use
.Xr X509_VERIFY_PARAM_set1_host 3
rather than explicitly calling
.Xr X509_check_host 3 .
Hostname checks may be out of scope with the DANE-EE(3) certificate
usage, and the internal checks will be suppressed as appropriate when
DANE support is enabled.
.Sh SEE ALSO
.Xr SSL_get_verify_result 3 ,
.Xr X509_VERIFY_PARAM_set1_host 3 ,
.Xr X509_VERIFY_PARAM_add1_host 3 ,
.Xr X509_VERIFY_PARAM_set1_email 3 ,
.Xr X509_VERIFY_PARAM_set1_ip 3
.Sh HISTORY
These functions were added in OpenSSL 1.0.2.
.Sh COPYRIGHT
Copyright 2012-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
