.Dd 2025-09-30
.Dt X509_LOAD_HTTP 3ossl
.Os
.Sh NAME
.Nm X509_load_http ,
.Nm X509_http_nbio ,
.Nm X509_CRL_load_http ,
.Nm X509_CRL_http_nbio
.Nd certificate and CRL loading functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft X509 *
.Fo X509_load_http
.Fa "const char *url"
.Fa "BIO *bio"
.Fa "BIO *rbio"
.Fa "int timeout"
.Fc
.Ft X509_CRL *
.Fo X509_CRL_load_http
.Fa "const char *url"
.Fa "BIO *bio"
.Fa "BIO *rbio"
.Fa "int timeout"
.Fc
The following macros have been deprecated since OpenSSL 3.0, and can be
hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Fd #define X509_http_nbio(rctx, pcert)
.Fd #define X509_CRL_http_nbio(rctx, pcrl)
.Sh DESCRIPTION
.Fn X509_load_http
and
.Fn X509_CRL_load_http
loads a certificate or a CRL, respectively, in ASN.1 format using HTTP
from the given
.Fa url .
.Pp
Maximum size of the HTTP response is 100 kB for certificates and 32 MB
for CRLs and hard coded in the functions.
.Pp
If
.Fa bio
is given and
.Fa rbio
is NULL then this BIO is used instead of an internal one for connecting,
writing the request, and reading the response.
If both
.Fa bio
and
.Fa rbio
are given (which may be memory BIOs, for instance) then no explicit
connection is attempted,
.Fa bio
is used for writing the request, and
.Fa rbio
for reading the response.
.Pp
If the
.Fa timeout
parameter is > 0 this indicates the maximum number of seconds to wait
until the transfer is complete.
A value of 0 enables waiting indefinitely, while a value < 0 immediately
leads to a timeout condition.
.Pp
.Fn X509_http_nbio
and
.Fn X509_CRL_http_nbio
are macros for backward compatibility that have the same effect as the
functions above but with infinite timeout and without the possibility to
specify custom BIOs.
.Sh RETURN VALUES
On success the function yield the loaded value, else NULL. Error
conditions include connection/transfer timeout, parse errors, etc.
.Sh SEE ALSO
.Xr OSSL_HTTP_get 3
.Sh HISTORY
.Fn X509_load_http
and
.Fn X509_CRL_load_http
were added in OpenSSL 3.0.
.Fn X509_http_nbio
and
.Fn X509_CRL_http_nbio
were deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
