.Dd 2025-09-30
.Dt X509_NAME_ENTRY_GET_OBJECT 3ossl
.Os
.Sh NAME
.Nm X509_NAME_ENTRY_get_object ,
.Nm X509_NAME_ENTRY_get_data ,
.Nm X509_NAME_ENTRY_set_object ,
.Nm X509_NAME_ENTRY_set_data ,
.Nm X509_NAME_ENTRY_create_by_txt ,
.Nm X509_NAME_ENTRY_create_by_NID ,
.Nm X509_NAME_ENTRY_create_by_OBJ
.Nd X509_NAME_ENTRY utility functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft ASN1_OBJECT *
.Fo X509_NAME_ENTRY_get_object
.Fa "const X509_NAME_ENTRY *ne"
.Fc
.Ft ASN1_STRING *
.Fo X509_NAME_ENTRY_get_data
.Fa "const X509_NAME_ENTRY *ne"
.Fc
.Ft int
.Fo X509_NAME_ENTRY_set_object
.Fa "X509_NAME_ENTRY *ne"
.Fa "const ASN1_OBJECT *obj"
.Fc
.Ft int
.Fo X509_NAME_ENTRY_set_data
.Fa "X509_NAME_ENTRY *ne"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Ft X509_NAME_ENTRY *
.Fo X509_NAME_ENTRY_create_by_txt
.Fa "X509_NAME_ENTRY **ne"
.Fa "const char *field"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Ft X509_NAME_ENTRY *
.Fo X509_NAME_ENTRY_create_by_NID
.Fa "X509_NAME_ENTRY **ne"
.Fa "int nid"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Ft X509_NAME_ENTRY *
.Fo X509_NAME_ENTRY_create_by_OBJ
.Fa "X509_NAME_ENTRY **ne"
.Fa "const ASN1_OBJECT *obj"
.Fa "int type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fc
.Sh DESCRIPTION
.Fn X509_NAME_ENTRY_get_object
retrieves the field name of
.Fa ne
in and
.Vt ASN1_OBJECT
structure.
.Pp
.Fn X509_NAME_ENTRY_get_data
retrieves the field value of
.Fa ne
in and
.Vt ASN1_STRING
structure.
.Pp
.Fn X509_NAME_ENTRY_set_object
sets the field name of
.Fa ne
to
.Fa obj .
.Pp
.Fn X509_NAME_ENTRY_set_data
sets the field value of
.Fa ne
to string type
.Fa type
and value determined by
.Fa bytes
and
.Fa len .
.Pp
.Fn X509_NAME_ENTRY_create_by_txt ,
.Fn X509_NAME_ENTRY_create_by_NID
and
.Fn X509_NAME_ENTRY_create_by_OBJ
create and return an
.Vt X509_NAME_ENTRY
structure.
.Sh NOTES
.Fn X509_NAME_ENTRY_get_object
and
.Fn X509_NAME_ENTRY_get_data
can be used to examine an
.Vt X509_NAME_ENTRY
function as returned by
.Xr X509_NAME_get_entry 3
for example.
.Pp
.Fn X509_NAME_ENTRY_create_by_txt ,
.Fn X509_NAME_ENTRY_create_by_OBJ ,
.Fn X509_NAME_ENTRY_create_by_NID
and
.Fn X509_NAME_ENTRY_set_data
are seldom used in practice because
.Vt X509_NAME_ENTRY
structures are almost always part of
.Sy X509_NAME
structures and the corresponding
.Sy X509_NAME
functions are typically used to create and add new entries in a single
operation.
.Pp
The arguments of these functions support similar options to the
similarly named ones of the corresponding
.Sy X509_NAME
functions such as
.Xr X509_NAME_add_entry_by_txt 3 .
So for example
.Fa type
can be set to
.Sy MBSTRING_ASC
but in the case of
.Xr X509_set_data 3
the field name must be set first so the relevant field information can
be looked up internally.
.Sh RETURN VALUES
.Fn X509_NAME_ENTRY_get_object
returns a valid
.Vt ASN1_OBJECT
structure if it is set or NULL if an error occurred.
.Pp
.Fn X509_NAME_ENTRY_get_data
returns a valid
.Vt ASN1_STRING
structure if it is set or NULL if an error occurred.
.Pp
.Fn X509_NAME_ENTRY_set_object
and
.Fn X509_NAME_ENTRY_set_data
return 1 on success or 0 on error.
.Pp
.Fn X509_NAME_ENTRY_create_by_txt ,
.Fn X509_NAME_ENTRY_create_by_NID
and
.Fn X509_NAME_ENTRY_create_by_OBJ
return a valid
.Vt X509_NAME_ENTRY
on success or NULL if an error occurred.
.Sh SEE ALSO
.Xr ERR_get_error 3 ,
.Xr d2i_X509_NAME 3 ,
.Xr OBJ_nid2obj 3
.Sh COPYRIGHT
Copyright 2002-2018 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
