.Dd 2025-09-30
.Dt X509_STORE_CTX_NEW 3ossl
.Os
.Sh NAME
.Nm X509_STORE_CTX_new_ex ,
.Nm X509_STORE_CTX_new ,
.Nm X509_STORE_CTX_cleanup ,
.Nm X509_STORE_CTX_free ,
.Nm X509_STORE_CTX_init ,
.Nm X509_STORE_CTX_init_rpk ,
.Nm X509_STORE_CTX_set0_trusted_stack ,
.Nm X509_STORE_CTX_set_cert ,
.Nm X509_STORE_CTX_set0_crls ,
.Nm X509_STORE_CTX_set0_rpk ,
.Nm X509_STORE_CTX_get0_param ,
.Nm X509_STORE_CTX_set0_param ,
.Nm X509_STORE_CTX_get0_untrusted ,
.Nm X509_STORE_CTX_set0_untrusted ,
.Nm X509_STORE_CTX_get_num_untrusted ,
.Nm X509_STORE_CTX_get0_chain ,
.Nm X509_STORE_CTX_set0_verified_chain ,
.Nm X509_STORE_CTX_get0_rpk ,
.Nm X509_STORE_CTX_set_default ,
.Nm X509_STORE_CTX_set_verify ,
.Nm X509_STORE_CTX_verify_fn ,
.Nm X509_STORE_CTX_set_purpose ,
.Nm X509_STORE_CTX_set_trust ,
.Nm X509_STORE_CTX_purpose_inherit
.Nd X509_STORE_CTX initialisation
.Sh SYNOPSIS
.In openssl/x509_vfy.h
.Ft X509_STORE_CTX *
.Fo X509_STORE_CTX_new_ex
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft X509_STORE_CTX *
.Fo X509_STORE_CTX_new
.Fa void
.Fc
.Ft void
.Fo X509_STORE_CTX_cleanup
.Fa "X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_CTX_free
.Fa "X509_STORE_CTX *ctx"
.Fc
.Ft int
.Fo X509_STORE_CTX_init
.Fa "X509_STORE_CTX *ctx"
.Fa "X509_STORE *trust_store"
.Fa "X509 *target"
.Fa "STACK_OF(X509) *untrusted"
.Fc
.Ft int
.Fo X509_STORE_CTX_init_rpk
.Fa "X509_STORE_CTX *ctx"
.Fa "X509_STORE *trust_store"
.Fa "EVP_PKEY *rpk"
.Fc
.Ft void
.Fo X509_STORE_CTX_set0_trusted_stack
.Fa "X509_STORE_CTX *ctx"
.Fa "STACK_OF(X509) *sk"
.Fc
.Ft void
.Fo X509_STORE_CTX_set_cert
.Fa "X509_STORE_CTX *ctx"
.Fa "X509 *target"
.Fc
.Ft void
.Fo X509_STORE_CTX_set0_crls
.Fa "X509_STORE_CTX *ctx"
.Fa "STACK_OF(X509_CRL) *sk"
.Fc
.Ft void
.Fo X509_STORE_CTX_set0_rpk
.Fa "X509_STORE_CTX *ctx"
.Fa "EVP_PKEY *target"
.Fc
.Ft X509_VERIFY_PARAM *
.Fo X509_STORE_CTX_get0_param
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Ft void
.Fo X509_STORE_CTX_set0_param
.Fa "X509_STORE_CTX *ctx"
.Fa "X509_VERIFY_PARAM *param"
.Fc
.Bd -literal
 STACK_OF(X509)* X509_STORE_CTX_get0_untrusted(const X509_STORE_CTX *ctx);
 void X509_STORE_CTX_set0_untrusted(X509_STORE_CTX *ctx, STACK_OF(X509) *sk);
.Ed
.Ft int
.Fo X509_STORE_CTX_get_num_untrusted
.Fa "const X509_STORE_CTX *ctx"
.Fc
.Bd -literal
 STACK_OF(X509) *X509_STORE_CTX_get0_chain(const X509_STORE_CTX *ctx);
 void X509_STORE_CTX_set0_verified_chain(X509_STORE_CTX *ctx, STACK_OF(X509) *chain);
 EVP_PKEY *X509_STORE_CTX_get0_rpk(const X509_STORE_CTX *ctx);
.Ed
.Ft int
.Fo X509_STORE_CTX_set_default
.Fa "X509_STORE_CTX *ctx"
.Fa "const char *name"
.Fc
.Ft typedef int
.Fo 
.Fa *X509_STORE_CTX_verify_fn
.Fc
(X509_STORE_CTX *);
.Ft void
.Fo X509_STORE_CTX_set_verify
.Fa "X509_STORE_CTX *ctx"
.Fa "X509_STORE_CTX_verify_fn verify"
.Fc
.Ft int
.Fo X509_STORE_CTX_set_purpose
.Fa "X509_STORE_CTX *ctx"
.Fa "int purpose"
.Fc
.Ft int
.Fo X509_STORE_CTX_set_trust
.Fa "X509_STORE_CTX *ctx"
.Fa "int trust"
.Fc
.Ft int
.Fo X509_STORE_CTX_purpose_inherit
.Fa "X509_STORE_CTX *ctx"
.Fa "int def_purpose"
.Fa "int purpose"
.Fa "int trust"
.Fc
.Sh DESCRIPTION
These functions initialise an
.Vt X509_STORE_CTX
structure for subsequent use by
.Xr X509_verify_cert 3
or
.Xr X509_STORE_CTX_verify 3 .
.Pp
.Fn X509_STORE_CTX_new_ex
returns a newly initialised
.Vt X509_STORE_CTX
structure associated with the specified library context
.Fa libctx
and property query string
.Fa propq .
Any cryptographic algorithms fetched while performing processing with
the X509_STORE_CTX will use that library context and property query
string.
.Pp
.Fn X509_STORE_CTX_new
is the same as
.Fn X509_STORE_CTX_new_ex
except that the default library context and a NULL property query string
are used.
.Pp
.Fn X509_STORE_CTX_cleanup
internally cleans up an
.Vt X509_STORE_CTX
structure.
It is used by
.Fn X509_STORE_CTX_init
and
.Fn X509_STORE_CTX_free .
.Pp
.Fn X509_STORE_CTX_free
completely frees up
.Fa ctx .
After this call
.Fa ctx
is no longer valid.
If
.Fa ctx
is NULL nothing is done.
.Pp
.Fn X509_STORE_CTX_init
sets up
.Fa ctx
for a subsequent verification operation.
.Pp
.Fn X509_STORE_CTX_init
initializes the internal state and resources of the given
.Fa ctx .
Among others, it sets the verification parameters associated with the
method name
.Qo Li default Qc ,
which includes the
.Qo Li any Qc
purpose, and takes over callback function pointers from
.Fa trust_store
(unless NULL). It must be called before each call to
.Xr X509_verify_cert 3
or
.Xr X509_STORE_CTX_verify 3 ,
i.e., a context is only good for one verification.
If you want to verify a further certificate or chain with the same
.Fa ctx
then you must call
.Fn X509_STORE_CTX_init
again.
The trusted certificate store is set to
.Fa trust_store
of type
.Vt X509_STORE .
This may be NULL because there are no trusted certificates or because
they are provided simply as a list using
.Fn X509_STORE_CTX_set0_trusted_stack .
The certificate to be verified is set to
.Fa target ,
and a list of additional certificates may be provided in
.Fa untrusted ,
which will be untrusted but may be used to build the chain.
The
.Fa target
certificate is not copied (its reference count is not updated), and the
caller must not free it before verification is complete.
Each of the
.Fa trust_store ,
.Fa target
and
.Fa untrusted
parameters can be NULL. Yet note that
.Xr X509_verify_cert 3
and
.Xr X509_STORE_CTX_verify 3
will need a verification target.
This can also be set using
.Fn X509_STORE_CTX_set_cert .
For
.Xr X509_STORE_CTX_verify 3 ,
which takes by default the first element of the list of untrusted
certificates as its verification target, this can be also set indirectly
using
.Xr X509_STORE_CTX_set0_untrusted 3 .
.Pp
.Fn X509_STORE_CTX_init_rpk
sets up
.Fa ctx
for a subsequent verification operation for the
.Fa target
raw public key.
It behaves similarly to
.Fn X509_STORE_CTX_init .
The
.Fa target
raw public key can also be supplied separately, via
.Fn X509_STORE_CTX_set0_rpk .
The
.Fa target
public key is not copied (its reference count is not updated), and the
caller must not free it before verification is complete.
.Pp
.Fn X509_STORE_CTX_set0_trusted_stack
sets the set of trusted certificates of
.Fa ctx
to
.Fa sk .
This is an alternative way of specifying trusted certificates instead of
using an
.Vt X509_STORE
where its complexity is not needed or to make sure that only the given
set
.Fa sk
of certificates are trusted.
.Pp
.Fn X509_STORE_CTX_set_cert
sets the target certificate to be verified in
.Fa ctx
to
.Fa target .
The target certificate is not copied (its reference count is not
updated), and the caller must not free it before verification is
complete.
.Pp
.Fn X509_STORE_CTX_set0_rpk
sets the target raw public key to be verified in
.Fa ctx
to
.Fa target ,
a non-NULL raw public key preempts any target certificate, which is then
ignored.
The
.Fa target
public key is not copied (its reference count is not updated), and the
caller must not free it before verification is complete.
.Pp
.Xr X509_STORE_CTX_set0_verified_chain 3
sets the validated chain to
.Em chain .
Ownership of the chain is transferred to
.Fa ctx ,
and so it should not be free'd by the caller.
.Pp
.Xr X509_STORE_CTX_get0_chain 3
returns the internal pointer used by the
.Fa ctx
that contains the constructed (output) chain.
.Pp
.Xr X509_STORE_CTX_get0_rpk 3
returns the internal pointer used by the
.Fa ctx
that contains the raw public key.
.Pp
.Fn X509_STORE_CTX_set0_crls
sets a set of CRLs to use to aid certificate verification to
.Fa sk .
These CRLs will only be used if CRL verification is enabled in the
associated
.Vt X509_VERIFY_PARAM
structure.
This might be used where additional "useful" CRLs are supplied as part
of a protocol, for example in a PKCS#7 structure.
.Pp
.Fn X509_STORE_CTX_get0_param
retrieves an internal pointer to the verification parameters associated
with
.Fa ctx .
.Pp
.Fn X509_STORE_CTX_set0_param
sets the internal verification parameter pointer to
.Fa param .
After this call
.Fa param
should not be used.
.Pp
.Xr X509_STORE_CTX_get0_untrusted 3
retrieves an internal pointer to the stack of untrusted certificates
associated with
.Fa ctx .
.Pp
.Xr X509_STORE_CTX_set0_untrusted 3
sets the internal pointer to the stack of untrusted certificates
associated with
.Fa ctx
to
.Fa sk .
.Xr X509_STORE_CTX_verify 3
will take the first element, if any, as its default target if the target
certificate is not set explicitly.
.Pp
.Fn X509_STORE_CTX_get_num_untrusted
returns the number of untrusted certificates that were used in building
the chain.
This is can be used after calling
.Xr X509_verify_cert 3
and similar functions.
With
.Xr X509_STORE_CTX_verify 3 ,
this does not count the first chain element.
.Pp
.Xr X509_STORE_CTX_get0_chain 3
returns the internal pointer used by the
.Fa ctx
that contains the validated chain.
.Pp
Details of the chain building and checking process are described in
.Xr openssl-verification-options 1
and
.Xr openssl-verification-options 1 .
.Pp
.Xr X509_STORE_CTX_set0_verified_chain 3
sets the validated chain used by
.Fa ctx
to be
.Em chain .
Ownership of the chain is transferred to
.Fa ctx ,
and so it should not be free'd by the caller.
.Pp
.Fn X509_STORE_CTX_set_default
looks up and sets the default verification method.
This uses the function
.Xr X509_VERIFY_PARAM_lookup 3
to find the set of parameters associated with the given verification
method
.Fa name .
Among others, the parameters determine the trust model and verification
purpose.
More detail, including the list of currently predefined methods, is
described for the
.Sy -verify_name
command-line option in
.Xr openssl-verification-options 1 .
.Pp
.Fn X509_STORE_CTX_set_verify
provides the capability for overriding the default verify function.
This function is responsible for verifying chain signatures and
expiration times.
.Pp
A verify function is defined as an X509_STORE_CTX_verify type which has
the following signature:
.Bd -literal
 int (*verify)(X509_STORE_CTX *);
.Ed
.Pp
This function should receive the current X509_STORE_CTX as a parameter
and return 1 on success or 0 on failure.
.Pp
X509 certificates may contain information about what purposes keys
contained within them can be used for.
For example "TLS WWW Server Authentication" or "Email Protection".
This "key usage" information is held internally to the certificate
itself.
In addition the trust store containing trusted certificates can declare
what purposes we trust different certificates for.
This "trust" information is not held within the certificate itself but
is "meta" information held alongside it.
This "meta" information is associated with the certificate after it is
issued and could be determined by a system administrator.
For example a certificate might declare that it is suitable for use for
both "TLS WWW Server Authentication" and "TLS Client Authentication",
but a system administrator might only trust it for the former.
An X.509 certificate extension exists that can record extended key usage
information to supplement the purpose information described above.
This extended mechanism is arbitrarily extensible and not well suited
for a generic library API; applications that need to validate extended
key usage information in certificates will need to define a custom
"purpose" (see below) or supply a nondefault verification callback
.Pf ( Xr X509_STORE_set_verify_cb_func 3 Ns ).
.Pp
.Fn X509_STORE_CTX_set_purpose
sets the purpose for the target certificate being verified in the
.Fa ctx .
Built-in available values for the
.Fa purpose
argument are
.Sy X509_PURPOSE_SSL_CLIENT ,
.Sy X509_PURPOSE_SSL_SERVER ,
.Sy X509_PURPOSE_NS_SSL_SERVER ,
.Sy X509_PURPOSE_SMIME_SIGN ,
.Sy X509_PURPOSE_SMIME_ENCRYPT ,
.Sy X509_PURPOSE_CRL_SIGN ,
.Sy X509_PURPOSE_ANY ,
.Sy X509_PURPOSE_OCSP_HELPER ,
.Sy X509_PURPOSE_TIMESTAMP_SIGN
and
.Sy X509_PURPOSE_CODE_SIGN .
It is also possible to create a custom purpose value.
Setting a purpose requests that the key usage and extended key usage
(EKU) extensions optionally declared within the certificate and its
chain are verified to be consistent with that purpose.
For SSL client, SSL server, and S/MIME purposes, the EKU is checked also
for the CA certificates along the chain, including any given trust
anchor certificate.
Potentially also further checks are done (depending on the purpose
given).
Every purpose also has an associated default trust value, which will
also be set at the same time.
During verification, this trust setting will be verified to check
whether it is consistent with the trust set by the system administrator
for certificates in the chain.
.Pp
.Fn X509_STORE_CTX_set_trust
sets the trust value for the target certificate being verified in the
.Fa ctx .
Built-in available values for the
.Fa trust
argument are
.Sy X509_TRUST_COMPAT ,
.Sy X509_TRUST_SSL_CLIENT ,
.Sy X509_TRUST_SSL_SERVER ,
.Sy X509_TRUST_EMAIL ,
.Sy X509_TRUST_OBJECT_SIGN ,
.Sy X509_TRUST_OCSP_SIGN ,
.Sy X509_TRUST_OCSP_REQUEST
and
.Sy X509_TRUST_TSA .
It is also possible to create a custom trust value.
Since
.Fn X509_STORE_CTX_set_purpose
also sets the trust value it is normally sufficient to only call that
function.
If both are called then
.Fn X509_STORE_CTX_set_trust
should be called after
.Fn X509_STORE_CTX_set_purpose
since the trust setting of the last call will be used.
.Pp
It should not normally be necessary for end user applications to call
.Fn X509_STORE_CTX_purpose_inherit
directly.
Typically applications should call
.Fn X509_STORE_CTX_set_purpose
or
.Fn X509_STORE_CTX_set_trust
instead.
Using this function it is possible to set the purpose and trust values
for the
.Fa ctx
at the same time.
Both
.Fa ctx
and its internal verification parameter pointer must not be NULL. The
.Fa def_purpose
and
.Fa purpose
arguments can have the same purpose values as described for
.Fn X509_STORE_CTX_set_purpose
above.
The
.Fa trust
argument can have the same trust values as described in
.Fn X509_STORE_CTX_set_trust
above.
Any of the
.Fa def_purpose ,
.Fa purpose
or
.Fa trust
values may also have the value 0 to indicate that the supplied parameter
should be ignored.
After calling this function the purpose to be used for verification is
set from the
.Fa purpose
argument unless the purpose was already set in
.Fa ctx
before, and the trust is set from the
.Fa trust
argument unless the trust was already set in
.Fa ctx
before.
If
.Fa trust
is 0 then the trust value will be set from the default trust value for
.Fa purpose .
If the default trust value for the purpose is
.Em X509_TRUST_DEFAULT
and
.Fa trust
is 0 then the default trust value associated with the
.Fa def_purpose
value is used for the trust setting instead.
.Sh NOTES
The certificates and CRLs in a store are used internally and should
.Sy not
be freed up until after the associated
.Vt X509_STORE_CTX
is freed.
.Sh BUGS
The certificates and CRLs in a context are used internally and should
.Sy not
be freed up until after the associated
.Vt X509_STORE_CTX
is freed.
Copies should be made or reference counts increased instead.
.Sh RETURN VALUES
.Fn X509_STORE_CTX_new
returns a newly allocated context or NULL if an error occurred.
.Pp
.Fn X509_STORE_CTX_init
and
.Fn X509_STORE_CTX_init_rpk
return 1 for success or 0 if an error occurred.
.Pp
.Fn X509_STORE_CTX_get0_param
returns a pointer to an
.Vt X509_VERIFY_PARAM
structure or NULL if an error occurred.
.Pp
.Xr X509_STORE_CTX_get0_rpk 3
returns a pointer to an
.Vt EVP_PKEY
structure if present, or NULL if absent.
.Pp
.Fn X509_STORE_CTX_cleanup ,
.Fn X509_STORE_CTX_free ,
.Fn X509_STORE_CTX_set0_trusted_stack ,
.Fn X509_STORE_CTX_set_cert ,
.Fn X509_STORE_CTX_set0_crls
and
.Fn X509_STORE_CTX_set0_param
do not return values.
.Pp
.Fn X509_STORE_CTX_set_default
returns 1 for success or 0 if an error occurred.
.Pp
.Fn X509_STORE_CTX_get_num_untrusted
returns the number of untrusted certificates used.
.Sh SEE ALSO
.Xr X509_verify_cert 3 ,
.Xr X509_STORE_CTX_verify 3 ,
.Xr X509_VERIFY_PARAM_set_flags 3
.Sh HISTORY
The
.Fn X509_STORE_CTX_set0_crls
function was added in OpenSSL 1.0.0. The
.Fn X509_STORE_CTX_get_num_untrusted
function was added in OpenSSL 1.1.0. The
.Fn X509_STORE_CTX_new_ex
function was added in OpenSSL 3.0. The
.Fn X509_STORE_CTX_init_rpk ,
.Xr X509_STORE_CTX_get0_rpk 3 ,
and
.Fn X509_STORE_CTX_set0_rpk
functions were added in OpenSSL 3.2.
.Pp
There is no need to call
.Fn X509_STORE_CTX_cleanup
explicitly since OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2009-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
