.Dd 2025-09-30
.Dt X509V3_GET_D2I 3ossl
.Os
.Sh NAME
.Nm X509V3_get_d2i ,
.Nm X509V3_add1_i2d ,
.Nm X509V3_EXT_d2i ,
.Nm X509V3_EXT_i2d ,
.Nm X509_get_ext_d2i ,
.Nm X509_add1_ext_i2d ,
.Nm X509_ACERT_get_ext_d2i ,
.Nm X509_ACERT_add1_ext_i2d ,
.Nm X509_CRL_get_ext_d2i ,
.Nm X509_CRL_add1_ext_i2d ,
.Nm X509_REVOKED_get_ext_d2i ,
.Nm X509_REVOKED_add1_ext_i2d ,
.Nm X509_get0_extensions ,
.Nm X509_ACERT_get0_extensions ,
.Nm X509_CRL_get0_extensions ,
.Nm X509_REVOKED_get0_extensions
.Nd X509 extension decode and encode functions
.Sh SYNOPSIS
.In openssl/x509v3.h
.Ft void *
.Fo X509V3_get_d2i
.Fa "const STACK_OF(X509_EXTENSION) *x"
.Fa "int nid"
.Fa "int *crit"
.Fa "int *idx"
.Fc
.Ft int
.Fo X509V3_add1_i2d
.Fa "STACK_OF(X509_EXTENSION) **x"
.Fa "int nid"
.Fa "void *value"
.Fa "int crit"
.Fa "unsigned long flags"
.Fc
.Ft void *
.Fo X509V3_EXT_d2i
.Fa "X509_EXTENSION *ext"
.Fc
.Ft X509_EXTENSION *
.Fo X509V3_EXT_i2d
.Fa "int ext_nid"
.Fa "int crit"
.Fa "void *ext_struc"
.Fc
.Ft void *
.Fo X509_get_ext_d2i
.Fa "const X509 *x"
.Fa "int nid"
.Fa "int *crit"
.Fa "int *idx"
.Fc
.Ft int
.Fo X509_add1_ext_i2d
.Fa "X509 *x"
.Fa "int nid"
.Fa "void *value"
.Fa "int crit"
.Fa "unsigned long flags"
.Fc
.Ft void *
.Fo X509_ACERT_get_ext_d2i
.Fa "const X509_ACERT *x"
.Fa "int nid"
.Fa "int *crit"
.Fa "int *idx"
.Fc
.Ft int
.Fo X509_ACERT_add1_ext_i2d
.Fa "X509_ACERT *x"
.Fa "int nid"
.Fa "void *value"
.Fa "int crit"
.Fa "unsigned long flags"
.Fc
.Ft void *
.Fo X509_CRL_get_ext_d2i
.Fa "const X509_CRL *crl"
.Fa "int nid"
.Fa "int *crit"
.Fa "int *idx"
.Fc
.Ft int
.Fo X509_CRL_add1_ext_i2d
.Fa "X509_CRL *crl"
.Fa "int nid"
.Fa "void *value"
.Fa "int crit"
.Fa "unsigned long flags"
.Fc
.Ft void *
.Fo X509_REVOKED_get_ext_d2i
.Fa "const X509_REVOKED *r"
.Fa "int nid"
.Fa "int *crit"
.Fa "int *idx"
.Fc
.Ft int
.Fo X509_REVOKED_add1_ext_i2d
.Fa "X509_REVOKED *r"
.Fa "int nid"
.Fa "void *value"
.Fa "int crit"
.Fa "unsigned long flags"
.Fc
.Ft const
.Fo STACK_OF
.Fa X509_EXTENSION
.Fc
 *X509_get0_extensions(const X509 *x);
.Ft const
.Fo STACK_OF
.Fa X509_EXTENSION
.Fc
 *X509_ACERT_get0_extensions(const X509 *x);
.Ft const
.Fo STACK_OF
.Fa X509_EXTENSION
.Fc
 *X509_CRL_get0_extensions(const X509_CRL *crl);
.Ft const
.Fo STACK_OF
.Fa X509_EXTENSION
.Fc
 *X509_REVOKED_get0_extensions(const X509_REVOKED *r);
.Sh DESCRIPTION
.Fn X509V3_get_d2i
looks for an extension with OID
.Fa nid
in the extensions
.Fa x
and, if found, decodes it.
If
.Fa idx
is NULL then only one occurrence of an extension is permissible,
otherwise the first extension after index
.Em *idx
is returned and
.Em *idx
updated to the location of the extension.
If
.Fa crit
is not NULL then
.Em *crit
is set to a status value: -2 if the extension occurs multiple times
(this is only returned if
.Fa idx
is NULL), -1 if the extension could not be found, 0 if the extension is
found and is not critical and 1 if critical.
A pointer to an extension specific structure or NULL is returned.
.Pp
.Fn X509V3_add1_i2d
adds extension
.Fa value
to STACK
.Em *x
(allocating a new STACK if necessary) using OID
.Fa nid
and criticality
.Fa crit
according to
.Fa flags .
.Pp
.Fn X509V3_EXT_d2i
attempts to decode the ASN.1 data contained in extension
.Fa ext
and returns a pointer to an extension specific structure or NULL if the
extension could not be decoded (invalid syntax or not supported).
.Pp
.Fn X509V3_EXT_i2d
encodes the extension specific structure
.Fa ext_struc
with OID
.Fa ext_nid
and criticality
.Fa crit .
.Pp
.Fn X509_get_ext_d2i
and
.Fn X509_add1_ext_i2d
operate on the extensions of certificate
.Fa x .
They are otherwise identical to
.Fn X509V3_get_d2i
and
.Fn X509V3_add1_i2d .
.Pp
.Fn X509_ACERT_get_ext_d2i
and
.Fn X509_ACERT_add1_ext_i2d
operate on the extensions of
.Vt X509_ACERT
structure
.Fa x .
They are otherwise identical to
.Fn X509V3_get_d2i
and
.Fn X509V3_add1_i2d .
.Pp
.Fn X509_CRL_get_ext_d2i
and
.Fn X509_CRL_add1_ext_i2d
operate on the extensions of CRL
.Fa crl .
They are otherwise identical to
.Fn X509V3_get_d2i
and
.Fn X509V3_add1_i2d .
.Pp
.Fn X509_REVOKED_get_ext_d2i
and
.Fn X509_REVOKED_add1_ext_i2d
operate on the extensions of
.Vt X509_REVOKED
structure
.Fa r
(i.e for CRL entry extensions).
They are otherwise identical to
.Fn X509V3_get_d2i
and
.Fn X509V3_add1_i2d .
.Pp
.Xr X509_get0_extensions 3 ,
.Xr X509_ACERT_get0_extensions 3 ,
.Xr X509_CRL_get0_extensions 3
and
.Xr X509_REVOKED_get0_extensions 3
return a STACK of all the extensions of a certificate, an attribute
certificate, a CRL or a CRL entry respectively.
.Sh NOTES
In almost all cases an extension can occur at most once and multiple
occurrences is an error.
Therefore, the
.Fa idx
parameter is usually NULL.
.Pp
The
.Fa flags
parameter may be one of the following values.
.Pp
.Sy X509V3_ADD_DEFAULT
appends a new extension only if the extension does not exist.
An error is returned if the extension exists.
.Pp
.Sy X509V3_ADD_APPEND
appends a new extension, ignoring whether the extension exists.
.Pp
.Sy X509V3_ADD_REPLACE
replaces an existing extension.
If the extension does not exist, appends a new extension.
.Pp
.Sy X509V3_ADD_REPLACE_EXISTING
replaces an existing extension.
If the extension does not exist, returns an error.
.Pp
.Sy X509V3_ADD_KEEP_EXISTING
appends a new extension only if the extension does not exist.
An error is
.Sy not
returned if the extension exists.
.Pp
.Sy X509V3_ADD_DELETE
deletes and frees an existing extension.
If the extension does not exist, returns an error.
No new extension is added.
.Pp
If
.Sy X509V3_ADD_SILENT
is bitwise ORed with
.Fa flags :
any error returned will not be added to the error queue.
.Pp
The function
.Fn X509V3_get_d2i
and its variants will return NULL if the extension is not found, occurs
multiple times or cannot be decoded.
It is possible to determine the precise reason by checking the value of
.Em *crit .
The returned pointer must be explicitly freed.
.Pp
The function
.Fn X509V3_add1_i2d
and its variants allocate
.Vt X509_EXTENSION
objects on STACK
.Em *x
depending on
.Fa flags .
The
.Vt X509_EXTENSION
objects must be explicitly freed using
.Xr X509_EXTENSION_free 3 .
.Sh SUPPORTED EXTENSIONS
The following sections contain a list of all supported extensions
including their name and NID.
.Ss PKIX Certificate Extensions
The following certificate extensions are defined in PKIX standards such
as RFC5280.
.Bd -literal
 Basic Constraints                  NID_basic_constraints
 Key Usage                          NID_key_usage
 Extended Key Usage                 NID_ext_key_usage

 Subject Key Identifier             NID_subject_key_identifier
 Authority Key Identifier           NID_authority_key_identifier

 Private Key Usage Period           NID_private_key_usage_period

 Subject Alternative Name           NID_subject_alt_name
 Issuer Alternative Name            NID_issuer_alt_name

 Authority Information Access       NID_info_access
 Subject Information Access         NID_sinfo_access

 Name Constraints                   NID_name_constraints

 Certificate Policies               NID_certificate_policies
 Policy Mappings                    NID_policy_mappings
 Policy Constraints                 NID_policy_constraints
 Inhibit Any Policy                 NID_inhibit_any_policy

 TLS Feature                        NID_tlsfeature
.Ed
.Ss Netscape Certificate Extensions
The following are (largely obsolete) Netscape certificate extensions.
.Bd -literal
 Netscape Cert Type                 NID_netscape_cert_type
 Netscape Base Url                  NID_netscape_base_url
 Netscape Revocation Url            NID_netscape_revocation_url
 Netscape CA Revocation Url         NID_netscape_ca_revocation_url
 Netscape Renewal Url               NID_netscape_renewal_url
 Netscape CA Policy Url             NID_netscape_ca_policy_url
 Netscape SSL Server Name           NID_netscape_ssl_server_name
 Netscape Comment                   NID_netscape_comment
.Ed
.Ss Miscellaneous Certificate Extensions
.Bd -literal
 Strong Extranet ID                 NID_sxnet
 Proxy Certificate Information      NID_proxyCertInfo
.Ed
.Ss PKIX CRL Extensions
The following are CRL extensions from PKIX standards such as RFC5280.
.Bd -literal
 CRL Number                         NID_crl_number
 CRL Distribution Points            NID_crl_distribution_points
 Delta CRL Indicator                NID_delta_crl
 Freshest CRL                       NID_freshest_crl
 Invalidity Date                    NID_invalidity_date
 Issuing Distribution Point         NID_issuing_distribution_point
.Ed
.Pp
The following are CRL entry extensions from PKIX standards such as
RFC5280.
.Bd -literal
 CRL Reason Code                    NID_crl_reason
 Certificate Issuer                 NID_certificate_issuer
.Ed
.Ss OCSP Extensions
.Bd -literal
 OCSP Nonce                         NID_id_pkix_OCSP_Nonce
 OCSP CRL ID                        NID_id_pkix_OCSP_CrlID
 Acceptable OCSP Responses          NID_id_pkix_OCSP_acceptableResponses
 OCSP No Check                      NID_id_pkix_OCSP_noCheck
 OCSP Archive Cutoff                NID_id_pkix_OCSP_archiveCutoff
 OCSP Service Locator               NID_id_pkix_OCSP_serviceLocator
 Hold Instruction Code              NID_hold_instruction_code
.Ed
.Ss Certificate Transparency Extensions
The following extensions are used by certificate transparency, RFC6962
.Bd -literal
 CT Precertificate SCTs             NID_ct_precert_scts
 CT Certificate SCTs                NID_ct_cert_scts
.Ed
.Sh RETURN VALUES
.Fn X509V3_get_d2i ,
its variants, and
.Fn X509V3_EXT_d2i
return a pointer to an extension specific structure or NULL if an error
occurs.
.Pp
.Fn X509V3_add1_i2d
and its variants return 1 if the operation is successful and 0 if it
fails due to a non-fatal error (extension not found, already exists,
cannot be encoded) or -1 due to a fatal error such as a memory
allocation failure.
.Pp
.Fn X509V3_EXT_i2d
returns a pointer to an
.Vt X509_EXTENSION
structure or NULL if an error occurs.
.Pp
.Xr X509_get0_extensions 3 ,
.Xr X509_CRL_get0_extensions 3
and
.Xr X509_REVOKED_get0_extensions 3
return a stack of extensions.
They return NULL if no extensions are present.
.Sh SEE ALSO
.Xr d2i_X509 3 ,
.Xr ERR_get_error 3 ,
.Xr X509_CRL_get0_by_serial 3 ,
.Xr X509_get0_signature 3 ,
.Xr X509_get_ext_d2i 3 ,
.Xr X509_get_extension_flags 3 ,
.Xr X509_get_pubkey 3 ,
.Xr X509_get_subject_name 3 ,
.Xr X509_get_version 3 ,
.Xr X509_NAME_add_entry_by_txt 3 ,
.Xr X509_NAME_ENTRY_get_object 3 ,
.Xr X509_NAME_get_index_by_NID 3 ,
.Xr X509_NAME_print_ex 3 ,
.Xr X509_new 3 ,
.Xr X509_sign 3 ,
.Xr X509_verify_cert 3
.Sh HISTORY
.Fn X509_ACERT_get_ext_d2i ,
.Fn X509_ACERT_add1_ext_i2d ,
.Xr X509_ACERT_get0_extensions 3
were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2015-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
