.Dd 2025-09-30
.Dt X509_CRL_GET0_BY_SERIAL 3ossl
.Os
.Sh NAME
.Nm X509_CRL_get0_by_serial ,
.Nm X509_CRL_get0_by_cert ,
.Nm X509_CRL_get_REVOKED ,
.Nm X509_REVOKED_get0_serialNumber ,
.Nm X509_REVOKED_get0_revocationDate ,
.Nm X509_REVOKED_set_serialNumber ,
.Nm X509_REVOKED_set_revocationDate ,
.Nm X509_CRL_add0_revoked ,
.Nm X509_CRL_sort
.Nd CRL revoked entry utility functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft int
.Fo X509_CRL_get0_by_serial
.Fa "X509_CRL *crl"
.Fa "X509_REVOKED **ret"
.Fa "const ASN1_INTEGER *serial"
.Fc
.Ft int
.Fo X509_CRL_get0_by_cert
.Fa "X509_CRL *crl"
.Fa "X509_REVOKED **ret"
.Fa "X509 *x"
.Fc
.Bd -literal
 STACK_OF(X509_REVOKED) *X509_CRL_get_REVOKED(X509_CRL *crl);
.Ed
.Ft const ASN1_INTEGER *
.Fo X509_REVOKED_get0_serialNumber
.Fa "const X509_REVOKED *r"
.Fc
.Ft const ASN1_TIME *
.Fo X509_REVOKED_get0_revocationDate
.Fa "const X509_REVOKED *r"
.Fc
.Ft int
.Fo X509_REVOKED_set_serialNumber
.Fa "X509_REVOKED *r"
.Fa "ASN1_INTEGER *serial"
.Fc
.Ft int
.Fo X509_REVOKED_set_revocationDate
.Fa "X509_REVOKED *r"
.Fa "ASN1_TIME *tm"
.Fc
.Ft int
.Fo X509_CRL_add0_revoked
.Fa "X509_CRL *crl"
.Fa "X509_REVOKED *rev"
.Fc
.Ft int
.Fo X509_CRL_sort
.Fa "X509_CRL *crl"
.Fc
.Sh DESCRIPTION
.Fn X509_CRL_get0_by_serial
attempts to find a revoked entry in
.Fa crl
for serial number
.Fa serial .
If it is successful, it sets
.Em *ret
to the internal pointer of the matching entry.
As a result,
.Em *ret
.Sy MUST NOT
be freed after the call.
.Pp
.Fn X509_CRL_get0_by_cert
is similar to
.Xr X509_get0_by_serial 3
except it looks for a revoked entry using the serial number of
certificate
.Fa x .
.Pp
.Xr X509_CRL_get_REVOKED 3
returns an internal pointer to a STACK of all revoked entries for
.Fa crl .
.Pp
.Fn X509_REVOKED_get0_serialNumber
returns an internal pointer to the serial number of
.Fa r .
.Pp
.Fn X509_REVOKED_get0_revocationDate
returns an internal pointer to the revocation date of
.Fa r .
.Pp
.Fn X509_REVOKED_set_serialNumber
sets the serial number of
.Fa r
to
.Fa serial .
The supplied
.Fa serial
pointer is not used internally so it should be freed after use.
.Pp
.Fn X509_REVOKED_set_revocationDate
sets the revocation date of
.Fa r
to
.Fa tm .
The supplied
.Fa tm
pointer is not used internally so it should be freed after use.
.Pp
.Fn X509_CRL_add0_revoked
appends revoked entry
.Fa rev
to CRL
.Fa crl .
The pointer
.Fa rev
is used internally so it
.Sy MUST NOT
be freed after the call: it is freed when the parent CRL is freed.
.Pp
.Fn X509_CRL_sort
sorts the revoked entries of
.Fa crl
into ascending serial number order.
.Sh NOTES
Applications can determine the number of revoked entries returned by
.Xr X509_CRL_get_REVOKED 3
using
.Xr sk_X509_REVOKED_num 3
and examine each one in turn using
.Xr sk_X509_REVOKED_value 3 .
.Sh RETURN VALUES
.Fn X509_CRL_get0_by_serial
and
.Fn X509_CRL_get0_by_cert
return 0 for failure, 1 on success except if the revoked entry has the
reason
.Qo Li removeFromCRL Qc
(8), in which case 2 is returned.
.Pp
.Xr X509_CRL_get_REVOKED 3
returns a STACK of revoked entries.
.Pp
.Fn X509_REVOKED_get0_serialNumber
returns an
.Vt ASN1_INTEGER
structure.
.Pp
.Fn X509_REVOKED_get0_revocationDate
returns an
.Vt ASN1_TIME
structure.
.Pp
.Fn X509_REVOKED_set_serialNumber ,
.Fn X509_REVOKED_set_revocationDate ,
.Fn X509_CRL_add0_revoked
and
.Fn X509_CRL_sort
return 1 for success and 0 for failure.
.Sh SEE ALSO
.Xr d2i_X509 3 ,
.Xr ERR_get_error 3 ,
.Xr X509_get0_signature 3 ,
.Xr X509_get_ext_d2i 3 ,
.Xr X509_get_extension_flags 3 ,
.Xr X509_get_pubkey 3 ,
.Xr X509_get_subject_name 3 ,
.Xr X509_get_version 3 ,
.Xr X509_NAME_add_entry_by_txt 3 ,
.Xr X509_NAME_ENTRY_get_object 3 ,
.Xr X509_NAME_get_index_by_NID 3 ,
.Xr X509_NAME_print_ex 3 ,
.Xr X509_new 3 ,
.Xr X509_sign 3 ,
.Xr X509V3_get_d2i 3 ,
.Xr X509_verify_cert 3
.Sh COPYRIGHT
Copyright 2015-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
