.Dd 2025-09-30
.Dt X509_GET_PUBKEY 3ossl
.Os
.Sh NAME
.Nm X509_get_pubkey ,
.Nm X509_get0_pubkey ,
.Nm X509_set_pubkey ,
.Nm X509_get_X509_PUBKEY ,
.Nm X509_REQ_get_pubkey ,
.Nm X509_REQ_get0_pubkey ,
.Nm X509_REQ_set_pubkey ,
.Nm X509_REQ_get_X509_PUBKEY
.Nd get or set certificate or certificate request public key
.Sh SYNOPSIS
.In openssl/x509.h
.Ft EVP_PKEY *
.Fo X509_get_pubkey
.Fa "X509 *x"
.Fc
.Ft EVP_PKEY *
.Fo X509_get0_pubkey
.Fa "const X509 *x"
.Fc
.Ft int
.Fo X509_set_pubkey
.Fa "X509 *x"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft X509_PUBKEY *
.Fo X509_get_X509_PUBKEY
.Fa "const X509 *x"
.Fc
.Ft EVP_PKEY *
.Fo X509_REQ_get_pubkey
.Fa "X509_REQ *req"
.Fc
.Ft EVP_PKEY *
.Fo X509_REQ_get0_pubkey
.Fa "X509_REQ *req"
.Fc
.Ft int
.Fo X509_REQ_set_pubkey
.Fa "X509_REQ *x"
.Fa "EVP_PKEY *pkey"
.Fc
.Ft X509_PUBKEY *
.Fo X509_REQ_get_X509_PUBKEY
.Fa "X509_REQ *x"
.Fc
.Sh DESCRIPTION
.Fn X509_get_pubkey
attempts to decode the public key for certificate
.Fa x .
If successful it returns the public key as an
.Vt EVP_PKEY
pointer with its reference count incremented: this means the returned
key must be freed up after use.
.Fn X509_get0_pubkey
is similar except it does
.Sy not
increment the reference count of the returned
.Vt EVP_PKEY
so it must not be freed up after use.
.Pp
.Fn X509_get_X509_PUBKEY
returns an internal pointer to the
.Vt X509_PUBKEY
structure which encodes the certificate of
.Fa x .
The returned value must not be freed up after use.
.Pp
.Fn X509_set_pubkey
attempts to set the public key for certificate
.Fa x
to
.Fa pkey .
The key
.Fa pkey
should be freed up after use.
.Pp
.Fn X509_REQ_get_pubkey ,
.Fn X509_REQ_get0_pubkey ,
.Fn X509_REQ_set_pubkey
and
.Fn X509_REQ_get_X509_PUBKEY
are similar but operate on certificate request
.Fa req .
.Sh NOTES
The first time a public key is decoded the
.Vt EVP_PKEY
structure is cached in the certificate or certificate request itself.
Subsequent calls return the cached structure with its reference count
incremented to improve performance.
.Sh RETURN VALUES
.Fn X509_get_pubkey ,
.Fn X509_get0_pubkey ,
.Fn X509_get_X509_PUBKEY ,
.Fn X509_REQ_get_pubkey
and
.Fn X509_REQ_get_X509_PUBKEY
return a public key or
.Dv NULL
if an error occurred.
.Pp
.Fn X509_set_pubkey
and
.Fn X509_REQ_set_pubkey
return 1 for success and 0 for failure.
.Sh SEE ALSO
.Xr d2i_X509 3 ,
.Xr ERR_get_error 3 ,
.Xr X509_CRL_get0_by_serial 3 ,
.Xr X509_get0_signature 3 ,
.Xr X509_get_ext_d2i 3 ,
.Xr X509_get_extension_flags 3 ,
.Xr X509_get_subject_name 3 ,
.Xr X509_get_version 3 ,
.Xr X509_NAME_add_entry_by_txt 3 ,
.Xr X509_NAME_ENTRY_get_object 3 ,
.Xr X509_NAME_get_index_by_NID 3 ,
.Xr X509_NAME_print_ex 3 ,
.Xr X509_new 3 ,
.Xr X509_sign 3 ,
.Xr X509V3_get_d2i 3 ,
.Xr X509_verify_cert 3
.Sh COPYRIGHT
Copyright 2015-2016 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
