.Dd 2025-09-30
.Dt X509_CHECK_ISSUED 3ossl
.Os
.Sh NAME
.Nm X509_check_issued
.Nd checks if certificate is apparently issued by another certificate
.Sh SYNOPSIS
.In openssl/x509v3.h
.Ft int
.Fo X509_check_issued
.Fa "X509 *issuer"
.Fa "X509 *subject"
.Fc
.Sh DESCRIPTION
.Fn X509_check_issued
checks if certificate
.Fa subject
was apparently issued using (CA) certificate
.Fa issuer .
This function takes into account not only matching of the issuer field
of
.Fa subject
with the subject field of
.Fa issuer ,
but also compares all sub-fields of the
.Sy authorityKeyIdentifier
extension of
.Fa subject ,
as far as present, with the respective
.Sy subjectKeyIdentifier ,
serial number, and issuer fields of
.Fa issuer ,
as far as present.
It also checks if the
.Sy keyUsage
field (if present) of
.Fa issuer
allows certificate signing.
It does not actually check the certificate signature.
An error is returned if the
.Fa issuer
or the
.Fa subject
are incomplete certificates.
.Sh RETURN VALUES
.Fn X509_check_issued
returns
.Sy X509_V_OK
if all checks are successful or some
.Sy X509_V_ERR*
constant to indicate an error.
.Sh SEE ALSO
.Xr X509_verify_cert 3 ,
.Xr X509_verify 3 ,
.Xr X509_check_ca 3 ,
.Xr openssl-verify 1 ,
.Xr X509_self_signed 3
.Sh COPYRIGHT
Copyright 2015-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
