.Dd 2025-09-30
.Dt X509_CHECK_PURPOSE 3ossl
.Os
.Sh NAME
.Nm X509_check_purpose ,
.Nm X509_PURPOSE_get_count ,
.Nm X509_PURPOSE_get_unused_id ,
.Nm X509_PURPOSE_get_by_sname ,
.Nm X509_PURPOSE_get_by_id ,
.Nm X509_PURPOSE_add ,
.Nm X509_PURPOSE_cleanup ,
.Nm X509_PURPOSE_get0 ,
.Nm X509_PURPOSE_get_id ,
.Nm X509_PURPOSE_get0_name ,
.Nm X509_PURPOSE_get0_sname ,
.Nm X509_PURPOSE_get_trust ,
.Nm X509_PURPOSE_set
.Nd functions related to checking the purpose of a certificate
.Sh SYNOPSIS
.In openssl/x509v3.h
.Ft int
.Fo X509_check_purpose
.Fa "X509 *x"
.Fa "int id"
.Fa "int ca"
.Fc
.Ft int
.Fo X509_PURPOSE_get_count
.Fa void
.Fc
.Ft int
.Fo X509_PURPOSE_get_unused_id
.Fa "OSSL_LIB_CTX *libctx"
.Fc
.Ft int
.Fo X509_PURPOSE_get_by_sname
.Fa "const char *sname"
.Fc
.Ft int
.Fo X509_PURPOSE_get_by_id
.Fa "int id"
.Fc
.Ft int
.Fo X509_PURPOSE_add
.Fa "int id"
.Fa "int trust"
.Fa "int flags"
.Fa "int (*ck) (const X509_PURPOSE *"
.Fa "const X509 *"
.Fa int)
.Fa "const char *name"
.Fa "const char *sname"
.Fa "void *arg"
.Fc
.Ft void
.Fo X509_PURPOSE_cleanup
.Fa void
.Fc
.Ft X509_PURPOSE *
.Fo X509_PURPOSE_get0
.Fa "int idx"
.Fc
.Ft int
.Fo X509_PURPOSE_get_id
.Fa "const X509_PURPOSE *"
.Fc
.Ft char *
.Fo X509_PURPOSE_get0_name
.Fa "const X509_PURPOSE *xp"
.Fc
.Ft char *
.Fo X509_PURPOSE_get0_sname
.Fa "const X509_PURPOSE *xp"
.Fc
.Ft int
.Fo X509_PURPOSE_get_trust
.Fa "const X509_PURPOSE *xp"
.Fc
.Ft int
.Fo X509_PURPOSE_set
.Fa "int *p"
.Fa "int purpose"
.Fc
.Sh DESCRIPTION
.Fn X509_check_purpose
checks if certificate
.Fa x
was created with the purpose represented by
.Fa id .
If
.Fa ca
is nonzero, then certificate
.Fa x
is checked to determine if it's a possible CA with various levels of
certainty possibly returned.
The certificate
.Fa x
must be a complete certificate otherwise the function returns an error.
.Pp
Below are the potential ID's that can be checked:
.Bd -literal
 # define X509_PURPOSE_SSL_CLIENT        1
 # define X509_PURPOSE_SSL_SERVER        2
 # define X509_PURPOSE_NS_SSL_SERVER     3
 # define X509_PURPOSE_SMIME_SIGN        4
 # define X509_PURPOSE_SMIME_ENCRYPT     5
 # define X509_PURPOSE_CRL_SIGN          6
 # define X509_PURPOSE_ANY               7
 # define X509_PURPOSE_OCSP_HELPER       8
 # define X509_PURPOSE_TIMESTAMP_SIGN    9
 # define X509_PURPOSE_CODE_SIGN        10
.Ed
.Pp
The checks performed take into account the X.509 extensions keyUsage,
extendedKeyUsage, and basicConstraints.
.Pp
.Fn X509_PURPOSE_get_count
returns the number of currently defined purposes.
.Pp
.Fn X509_PURPOSE_get_unused_id
returns the smallest purpose id not yet used, which is guaranteed to be
unique and larger than
.Sy X509_PURPOSE_MAX .
The
.Fa libctx
parameter should be used to provide the library context.
It is currently ignored as the purpose mapping table is global.
.Pp
.Fn X509_PURPOSE_get_by_sname
returns the index of the purpose with the given short name or -1 if not
found.
.Pp
.Fn X509_PURPOSE_get_by_id
returns the index of the purpose with the given id or -1 if not found.
.Pp
.Fn X509_PURPOSE_add
adds or modifies a purpose entry identified by
.Fa sname .
Unless the id stays the same for an existing entry,
.Fa id
must be fresh, which can be achieved by using the result of
.Fn X509_PURPOSE_get_unused_id .
The function also sets in the entry the trust id
.Fa trust ,
the given
.Fa flags ,
the purpose (long) name
.Fa name ,
the short name
.Fa sname ,
the purpose checking function
.Em ck
of type
.Sy int (*) (const X509_PURPOSE *, const X509 *, int) ,
and its user data
.Fa arg
which may be retrieved via the
.Vt X509_PURPOSE
pointer.
.Pp
.Fn X509_PURPOSE_cleanup
removes all purposes that are not pre-defined.
.Pp
.Fn X509_PURPOSE_get0
returns an
.Vt X509_PURPOSE
pointer or NULL on error.
.Pp
.Fn X509_PURPOSE_get_id
returns the id of the given
.Vt X509_PURPOSE
structure.
.Pp
.Fn X509_PURPOSE_get0_name
returns the (long) name of the given
.Vt X509_PURPOSE .
.Pp
.Fn X509_PURPOSE_get0_sname
returns the short name of the given
.Vt X509_PURPOSE .
.Pp
.Fn X509_PURPOSE_get_trust
returns the trust id of the given
.Vt X509_PURPOSE .
.Pp
.Fn X509_PURPOSE_set
assigns the given
.Fa purpose
id to the location pointed at by
.Fa p .
This resets to the any purpose if
.Fa purpose
is
.Sy X509_PURPOSE_DEFAULT_ANY .
.Sh RETURN VALUES
.Fn X509_check_purpose
returns the following values.
For non-CA checks
.Bl -tag -width Ds
.It -1 an error condition has occurred
.It 1 if the certificate was created to perform the purpose represented by Fa id
.It 0 if the certificate was not created to perform the purpose represented by Fa id
.El
For CA checks the below integers could be returned with the following
meanings:
.Bl -tag -width Ds
.It -1 an error condition has occurred
.It 0 not a CA or does not have the purpose represented by Fa id
.It 1 is a CA.
.It 2 Only possible in old versions of openSSL when basicConstraints are absent. New versions will not return this value. May be a CA
.It 3 basicConstraints absent but self signed V1.
.It 4 basicConstraints absent but keyUsage present and keyCertSign asserted.
.It 5 legacy Netscape specific CA Flags present
.El
.Fn X509_PURPOSE_get_count
returns the number of currently defined purposes.
.Pp
.Fn X509_PURPOSE_get_unused_id
returns the smallest purpose id not yet used.
.Pp
.Fn X509_PURPOSE_get_by_sname
returns the index of the purpose with the given short name or -1 if not
found.
.Pp
.Fn X509_PURPOSE_get_by_id
returns the index of the purpose with the given id or -1 if not found.
.Pp
int
.Fn X509_PURPOSE_add
returns 1 on success, 0 on error.
.Pp
.Fn X509_PURPOSE_cleanup
does not return anything.
.Pp
.Fn X509_PURPOSE_get0
returns an
.Vt X509_PURPOSE
pointer or NULL on error.
.Pp
.Fn X509_PURPOSE_get_id
returns the id of the given
.Vt X509_PURPOSE
structure.
.Pp
.Fn X509_PURPOSE_get0_name
returns the (long) name of the given
.Vt X509_PURPOSE .
.Pp
.Fn X509_PURPOSE_get0_sname
returns the short name of the given
.Vt X509_PURPOSE .
.Pp
.Fn X509_PURPOSE_get_trust
returns the trust id of the given
.Vt X509_PURPOSE .
.Pp
.Fn X509_PURPOSE_set
returns 1 on success, 0 on error.
.Sh BUGS
The X509_PURPOSE implementation so far is not thread-safe.
There may be race conditions retrieving purpose information while
.Fn X509_PURPOSE_add
or X509_PURPOSE_cleanup(void) is being called.
.Sh HISTORY
.Fn X509_PURPOSE_get_unused_id
was added in OpensSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
