.Dd 2025-09-30
.Dt X509V3_GET_EXT_BY_NID 3ossl
.Os
.Sh NAME
.Nm X509v3_get_ext_count ,
.Nm X509v3_get_ext ,
.Nm X509v3_get_ext_by_NID ,
.Nm X509v3_get_ext_by_OBJ ,
.Nm X509v3_get_ext_by_critical ,
.Nm X509v3_delete_ext ,
.Nm X509v3_add_ext ,
.Nm X509v3_add_extensions ,
.Nm X509_get_ext_count ,
.Nm X509_get_ext ,
.Nm X509_get_ext_by_NID ,
.Nm X509_get_ext_by_OBJ ,
.Nm X509_get_ext_by_critical ,
.Nm X509_delete_ext ,
.Nm X509_add_ext ,
.Nm X509_CRL_get_ext_count ,
.Nm X509_CRL_get_ext ,
.Nm X509_CRL_get_ext_by_NID ,
.Nm X509_CRL_get_ext_by_OBJ ,
.Nm X509_CRL_get_ext_by_critical ,
.Nm X509_CRL_delete_ext ,
.Nm X509_CRL_add_ext ,
.Nm X509_REVOKED_get_ext_count ,
.Nm X509_REVOKED_get_ext ,
.Nm X509_REVOKED_get_ext_by_NID ,
.Nm X509_REVOKED_get_ext_by_OBJ ,
.Nm X509_REVOKED_get_ext_by_critical ,
.Nm X509_REVOKED_delete_ext ,
.Nm X509_REVOKED_add_ext
.Nd extension stack utility functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft int
.Fo X509v3_get_ext_count
.Fa "const STACK_OF(X509_EXTENSION) *x"
.Fc
.Ft X509_EXTENSION *
.Fo X509v3_get_ext
.Fa "const STACK_OF(X509_EXTENSION) *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509v3_get_ext_by_NID
.Fa "const STACK_OF(X509_EXTENSION) *x"
.Fa "int nid"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509v3_get_ext_by_OBJ
.Fa "const STACK_OF(X509_EXTENSION) *x"
.Fa "const ASN1_OBJECT *obj"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509v3_get_ext_by_critical
.Fa "const STACK_OF(X509_EXTENSION) *x"
.Fa "int crit"
.Fa "int lastpos"
.Fc
.Ft X509_EXTENSION *
.Fo X509v3_delete_ext
.Fa "STACK_OF(X509_EXTENSION) *x"
.Fa "int loc"
.Fc
.Bd -literal
 STACK_OF(X509_EXTENSION) *X509v3_add_ext(STACK_OF(X509_EXTENSION) **x,
                                          X509_EXTENSION *ex, int loc);
 STACK_OF(X509_EXTENSION)
      *X509v3_add_extensions(STACK_OF(X509_EXTENSION) **target,
                             const STACK_OF(X509_EXTENSION) *exts);
.Ed
.Ft int
.Fo X509_get_ext_count
.Fa "const X509 *x"
.Fc
.Ft X509_EXTENSION *
.Fo X509_get_ext
.Fa "const X509 *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_get_ext_by_NID
.Fa "const X509 *x"
.Fa "int nid"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509_get_ext_by_OBJ
.Fa "const X509 *x"
.Fa "const ASN1_OBJECT *obj"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509_get_ext_by_critical
.Fa "const X509 *x"
.Fa "int crit"
.Fa "int lastpos"
.Fc
.Ft X509_EXTENSION *
.Fo X509_delete_ext
.Fa "X509 *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_add_ext
.Fa "X509 *x"
.Fa "X509_EXTENSION *ex"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_CRL_get_ext_count
.Fa "const X509_CRL *x"
.Fc
.Ft X509_EXTENSION *
.Fo X509_CRL_get_ext
.Fa "const X509_CRL *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_CRL_get_ext_by_NID
.Fa "const X509_CRL *x"
.Fa "int nid"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509_CRL_get_ext_by_OBJ
.Fa "const X509_CRL *x"
.Fa "const ASN1_OBJECT *obj"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509_CRL_get_ext_by_critical
.Fa "const X509_CRL *x"
.Fa "int crit"
.Fa "int lastpos"
.Fc
.Ft X509_EXTENSION *
.Fo X509_CRL_delete_ext
.Fa "X509_CRL *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_CRL_add_ext
.Fa "X509_CRL *x"
.Fa "X509_EXTENSION *ex"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_REVOKED_get_ext_count
.Fa "const X509_REVOKED *x"
.Fc
.Ft X509_EXTENSION *
.Fo X509_REVOKED_get_ext
.Fa "const X509_REVOKED *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_REVOKED_get_ext_by_NID
.Fa "const X509_REVOKED *x"
.Fa "int nid"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509_REVOKED_get_ext_by_OBJ
.Fa "const X509_REVOKED *x"
.Fa "const ASN1_OBJECT *obj"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509_REVOKED_get_ext_by_critical
.Fa "const X509_REVOKED *x"
.Fa "int crit"
.Fa "int lastpos"
.Fc
.Ft X509_EXTENSION *
.Fo X509_REVOKED_delete_ext
.Fa "X509_REVOKED *x"
.Fa "int loc"
.Fc
.Ft int
.Fo X509_REVOKED_add_ext
.Fa "X509_REVOKED *x"
.Fa "X509_EXTENSION *ex"
.Fa "int loc"
.Fc
.Sh DESCRIPTION
.Fn X509v3_get_ext_count
retrieves the number of extensions in
.Fa x .
.Pp
.Fn X509v3_get_ext
retrieves extension
.Fa loc
from
.Fa x .
The index
.Fa loc
can take any value from 0 to
.Pf X509_get_ext_count( Fa x )
- 1. The returned extension is an internal pointer which
.Sy MUST NOT
be freed by the application.
.Pp
.Fn X509v3_get_ext_by_NID
and
.Fn X509v3_get_ext_by_OBJ
look for an extension with
.Fa nid
or
.Fa obj
from extension STACK
.Fa x .
The search starts from the extension after
.Fa lastpos
or from the beginning if
.Fa lastpos
is -1. If the extension is found, its index is returned, otherwise -1 is
returned.
.Pp
.Fn X509v3_get_ext_by_critical
is similar to
.Fn X509v3_get_ext_by_NID
except it looks for an extension of criticality
.Fa crit .
A zero value for
.Fa crit
looks for a non-critical extension.
A nonzero value looks for a critical extension.
.Pp
.Fn X509v3_delete_ext
deletes the extension with index
.Fa loc
from
.Fa x .
The deleted extension is returned and must be freed by the caller.
If
.Fa loc
is an invalid index value, NULL is returned.
.Pp
.Xr X509v3_add_ext 3
inserts extension
.Fa ex
to STACK
.Em *x
at position
.Fa loc .
If
.Fa loc
is -1, the new extension is added to the end.
A new STACK is allocated if
.Em *x
is NULL. The passed extension
.Fa ex
is duplicated so it must be freed after use.
.Pp
.Xr X509v3_add_extensions 3
adds the list of extensions
.Em exts
to STACK
.Em *target .
The STACK
.Em *target
is returned unchanged if
.Em exts
is NULL or an empty list.
Otherwise a new stack is allocated if
.Em *target
is NULL. An extension to be added that has the same OID as a
pre-existing one replaces this earlier one.
.Pp
.Fn X509_get_ext_count ,
.Fn X509_get_ext ,
.Fn X509_get_ext_by_NID ,
.Fn X509_get_ext_by_OBJ ,
.Fn X509_get_ext_by_critical ,
.Fn X509_delete_ext
and
.Fn X509_add_ext
operate on the extensions of certificate
.Fa x .
They are otherwise identical to the X509v3 functions.
.Pp
.Fn X509_CRL_get_ext_count ,
.Fn X509_CRL_get_ext ,
.Fn X509_CRL_get_ext_by_NID ,
.Fn X509_CRL_get_ext_by_OBJ ,
.Fn X509_CRL_get_ext_by_critical ,
.Fn X509_CRL_delete_ext
and
.Fn X509_CRL_add_ext
operate on the extensions of CRL
.Fa x .
They are otherwise identical to the X509v3 functions.
.Pp
.Fn X509_REVOKED_get_ext_count ,
.Fn X509_REVOKED_get_ext ,
.Fn X509_REVOKED_get_ext_by_NID ,
.Fn X509_REVOKED_get_ext_by_OBJ ,
.Fn X509_REVOKED_get_ext_by_critical ,
.Fn X509_REVOKED_delete_ext
and
.Fn X509_REVOKED_add_ext
operate on the extensions of CRL entry
.Fa x .
They are otherwise identical to the X509v3 functions.
.Sh NOTES
These functions are used to examine stacks of extensions directly.
Applications that want to parse or encode and add an extension should
use the extension encode and decode functions instead, such as
.Xr X509_add1_ext_i2d 3
and
.Xr X509_get_ext_d2i 3 .
.Pp
For
.Fn X509v3_get_ext_by_NID ,
.Fn X509v3_get_ext_by_OBJ ,
.Fn X509v3_get_ext_by_critical
and its variants, a zero index return value is not an error since
extension STACK
.Fa x
indices start from zero.
These search functions start from the extension
.Sy after
the
.Fa lastpos
parameter so it should initially be set to -1. If it is set to zero, the
initial extension will not be checked.
.Pp
.Fn X509v3_delete_ext
and its variants are a bit counter-intuitive because these functions do
not free the extension they delete.
They return an
.Vt X509_EXTENSION
object which must be explicitly freed using
.Xr X509_EXTENSION_free 3 .
.Sh RETURN VALUES
.Fn X509v3_get_ext_count
returns the extension count or 0 for failure.
.Pp
.Fn X509v3_get_ext ,
.Fn X509v3_delete_ext
and
.Fn X509_delete_ext
return an
.Vt X509_EXTENSION
structure or NULL if an error occurs.
.Pp
.Fn X509v3_get_ext_by_OBJ
and
.Fn X509v3_get_ext_by_critical
return the extension index or -1 if an error occurs.
.Pp
.Fn X509v3_get_ext_by_NID
returns the extension index or negative values if an error occurs.
.Pp
.Xr X509v3_add_ext 3
returns a STACK of extensions or NULL on error.
.Pp
.Xr X509v3_add_extensions 3
returns a STACK of extensions or NULL on error or if
.Em *target
is NULL and
.Em exts
is NULL or an empty list.
.Pp
.Fn X509_add_ext
returns 1 on success and 0 on error.
.Sh SEE ALSO
.Xr X509V3_get_d2i 3
.Sh HISTORY
.Xr X509v3_add_extensions 3
was added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2015-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
