.Dd 2025-09-30
.Dt X509_DUP 3ossl
.Os
.Sh NAME
.Nm DECLARE_ASN1_FUNCTIONS ,
.Nm IMPLEMENT_ASN1_FUNCTIONS ,
.Nm ASN1_ITEM ,
.Nm ACCESS_DESCRIPTION_free ,
.Nm ACCESS_DESCRIPTION_new ,
.Nm ADMISSIONS_free ,
.Nm ADMISSIONS_new ,
.Nm ADMISSION_SYNTAX_free ,
.Nm ADMISSION_SYNTAX_new ,
.Nm ASIdOrRange_free ,
.Nm ASIdOrRange_new ,
.Nm ASIdentifierChoice_free ,
.Nm ASIdentifierChoice_new ,
.Nm ASIdentifiers_free ,
.Nm ASIdentifiers_new ,
.Nm ASRange_free ,
.Nm ASRange_new ,
.Nm AUTHORITY_INFO_ACCESS_free ,
.Nm AUTHORITY_INFO_ACCESS_new ,
.Nm AUTHORITY_KEYID_free ,
.Nm AUTHORITY_KEYID_new ,
.Nm BASIC_CONSTRAINTS_free ,
.Nm BASIC_CONSTRAINTS_new ,
.Nm CERTIFICATEPOLICIES_free ,
.Nm CERTIFICATEPOLICIES_new ,
.Nm CMS_ContentInfo_free ,
.Nm CMS_ContentInfo_new ,
.Nm CMS_ContentInfo_new_ex ,
.Nm CMS_ContentInfo_print_ctx ,
.Nm CMS_EnvelopedData_it ,
.Nm CMS_EnvelopedData_dup ,
.Nm CMS_ReceiptRequest_free ,
.Nm CMS_ReceiptRequest_new ,
.Nm CMS_SignedData_free ,
.Nm CMS_SignedData_new ,
.Nm CRL_DIST_POINTS_free ,
.Nm CRL_DIST_POINTS_new ,
.Nm DIRECTORYSTRING_free ,
.Nm DIRECTORYSTRING_new ,
.Nm DISPLAYTEXT_free ,
.Nm DISPLAYTEXT_new ,
.Nm DIST_POINT_NAME_free ,
.Nm DIST_POINT_NAME_new ,
.Nm DIST_POINT_NAME_dup ,
.Nm DIST_POINT_free ,
.Nm DIST_POINT_new ,
.Nm DSAparams_dup ,
.Nm ECPARAMETERS_free ,
.Nm ECPARAMETERS_new ,
.Nm ECPKPARAMETERS_free ,
.Nm ECPKPARAMETERS_new ,
.Nm EDIPARTYNAME_free ,
.Nm EDIPARTYNAME_new ,
.Nm ESS_CERT_ID_dup ,
.Nm ESS_CERT_ID_free ,
.Nm ESS_CERT_ID_new ,
.Nm ESS_CERT_ID_V2_dup ,
.Nm ESS_CERT_ID_V2_free ,
.Nm ESS_CERT_ID_V2_new ,
.Nm ESS_ISSUER_SERIAL_dup ,
.Nm ESS_ISSUER_SERIAL_free ,
.Nm ESS_ISSUER_SERIAL_new ,
.Nm ESS_SIGNING_CERT_dup ,
.Nm ESS_SIGNING_CERT_free ,
.Nm ESS_SIGNING_CERT_it ,
.Nm ESS_SIGNING_CERT_new ,
.Nm ESS_SIGNING_CERT_V2_dup ,
.Nm ESS_SIGNING_CERT_V2_free ,
.Nm ESS_SIGNING_CERT_V2_it ,
.Nm ESS_SIGNING_CERT_V2_new ,
.Nm EXTENDED_KEY_USAGE_free ,
.Nm EXTENDED_KEY_USAGE_new ,
.Nm GENERAL_NAMES_free ,
.Nm GENERAL_NAMES_new ,
.Nm GENERAL_NAME_dup ,
.Nm GENERAL_NAME_free ,
.Nm GENERAL_NAME_new ,
.Nm GENERAL_SUBTREE_free ,
.Nm GENERAL_SUBTREE_new ,
.Nm OSSL_IETF_ATTR_SYNTAX_free ,
.Nm OSSL_IETF_ATTR_SYNTAX_it ,
.Nm OSSL_IETF_ATTR_SYNTAX_new ,
.Nm IPAddressChoice_free ,
.Nm IPAddressChoice_new ,
.Nm IPAddressFamily_free ,
.Nm IPAddressFamily_new ,
.Nm IPAddressOrRange_free ,
.Nm IPAddressOrRange_new ,
.Nm IPAddressRange_free ,
.Nm IPAddressRange_new ,
.Nm ISSUER_SIGN_TOOL_free ,
.Nm ISSUER_SIGN_TOOL_it ,
.Nm ISSUER_SIGN_TOOL_new ,
.Nm ISSUING_DIST_POINT_free ,
.Nm ISSUING_DIST_POINT_it ,
.Nm ISSUING_DIST_POINT_new ,
.Nm NAME_CONSTRAINTS_free ,
.Nm NAME_CONSTRAINTS_new ,
.Nm NAMING_AUTHORITY_free ,
.Nm NAMING_AUTHORITY_new ,
.Nm NETSCAPE_CERT_SEQUENCE_free ,
.Nm NETSCAPE_CERT_SEQUENCE_new ,
.Nm NETSCAPE_SPKAC_free ,
.Nm NETSCAPE_SPKAC_new ,
.Nm NETSCAPE_SPKI_free ,
.Nm NETSCAPE_SPKI_new ,
.Nm NOTICEREF_free ,
.Nm NOTICEREF_new ,
.Nm OCSP_BASICRESP_free ,
.Nm OCSP_BASICRESP_new ,
.Nm OCSP_CERTID_dup ,
.Nm OCSP_CERTID_new ,
.Nm OCSP_CERTSTATUS_free ,
.Nm OCSP_CERTSTATUS_new ,
.Nm OCSP_CRLID_free ,
.Nm OCSP_CRLID_new ,
.Nm OCSP_ONEREQ_free ,
.Nm OCSP_ONEREQ_new ,
.Nm OCSP_REQINFO_free ,
.Nm OCSP_REQINFO_new ,
.Nm OCSP_RESPBYTES_free ,
.Nm OCSP_RESPBYTES_new ,
.Nm OCSP_RESPDATA_free ,
.Nm OCSP_RESPDATA_new ,
.Nm OCSP_RESPID_free ,
.Nm OCSP_RESPID_new ,
.Nm OCSP_RESPONSE_new ,
.Nm OCSP_REVOKEDINFO_free ,
.Nm OCSP_REVOKEDINFO_new ,
.Nm OCSP_SERVICELOC_free ,
.Nm OCSP_SERVICELOC_new ,
.Nm OCSP_SIGNATURE_free ,
.Nm OCSP_SIGNATURE_new ,
.Nm OCSP_SINGLERESP_free ,
.Nm OCSP_SINGLERESP_new ,
.Nm OSSL_AA_DIST_POINT_free ,
.Nm OSSL_AA_DIST_POINT_new ,
.Nm OSSL_AA_DIST_POINT_it ,
.Nm OSSL_ALLOWED_ATTRIBUTES_CHOICE_free ,
.Nm OSSL_ALLOWED_ATTRIBUTES_CHOICE_new ,
.Nm OSSL_ALLOWED_ATTRIBUTES_CHOICE_it ,
.Nm OSSL_ALLOWED_ATTRIBUTES_ITEM_free ,
.Nm OSSL_ALLOWED_ATTRIBUTES_ITEM_new ,
.Nm OSSL_ALLOWED_ATTRIBUTES_ITEM_it ,
.Nm OSSL_ALLOWED_ATTRIBUTES_SYNTAX_free ,
.Nm OSSL_ALLOWED_ATTRIBUTES_SYNTAX_new ,
.Nm OSSL_ALLOWED_ATTRIBUTES_SYNTAX_it ,
.Nm OSSL_ATAV_free ,
.Nm OSSL_ATAV_new ,
.Nm OSSL_ATAV_it ,
.Nm OSSL_ATTRIBUTE_DESCRIPTOR_free ,
.Nm OSSL_ATTRIBUTE_DESCRIPTOR_new ,
.Nm OSSL_ATTRIBUTE_DESCRIPTOR_it ,
.Nm OSSL_ATTRIBUTE_MAPPING_free ,
.Nm OSSL_ATTRIBUTE_MAPPING_new ,
.Nm OSSL_ATTRIBUTE_MAPPING_it ,
.Nm OSSL_ATTRIBUTE_MAPPINGS_free ,
.Nm OSSL_ATTRIBUTE_MAPPINGS_new ,
.Nm OSSL_ATTRIBUTE_MAPPINGS_it ,
.Nm OSSL_ATTRIBUTE_TYPE_MAPPING_free ,
.Nm OSSL_ATTRIBUTE_TYPE_MAPPING_new ,
.Nm OSSL_ATTRIBUTE_TYPE_MAPPING_it ,
.Nm OSSL_ATTRIBUTE_VALUE_MAPPING_free ,
.Nm OSSL_ATTRIBUTE_VALUE_MAPPING_new ,
.Nm OSSL_ATTRIBUTE_VALUE_MAPPING_it ,
.Nm OSSL_ATTRIBUTES_SYNTAX_free ,
.Nm OSSL_ATTRIBUTES_SYNTAX_it ,
.Nm OSSL_ATTRIBUTES_SYNTAX_new ,
.Nm OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX_free ,
.Nm OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX_it ,
.Nm OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX_new ,
.Nm OSSL_BASIC_ATTR_CONSTRAINTS_free ,
.Nm OSSL_BASIC_ATTR_CONSTRAINTS_it ,
.Nm OSSL_BASIC_ATTR_CONSTRAINTS_new ,
.Nm OSSL_CMP_ATAVS_new ,
.Nm OSSL_CMP_ATAVS_free ,
.Nm OSSL_CMP_ATAVS_it ,
.Nm OSSL_CMP_CRLSTATUS_free ,
.Nm OSSL_CMP_ITAV_dup ,
.Nm OSSL_CMP_ITAV_free ,
.Nm OSSL_CMP_MSG_dup ,
.Nm OSSL_CMP_MSG_it ,
.Nm OSSL_CMP_MSG_free ,
.Nm OSSL_CMP_PKIHEADER_free ,
.Nm OSSL_CMP_PKIHEADER_it ,
.Nm OSSL_CMP_PKIHEADER_new ,
.Nm OSSL_CMP_PKISI_dup ,
.Nm OSSL_CMP_PKISI_free ,
.Nm OSSL_CMP_PKISI_it ,
.Nm OSSL_CMP_PKISI_new ,
.Nm OSSL_CMP_PKISTATUS_it ,
.Nm OSSL_CRMF_CERTID_dup ,
.Nm OSSL_CRMF_CERTID_free ,
.Nm OSSL_CRMF_CERTID_it ,
.Nm OSSL_CRMF_CERTID_new ,
.Nm OSSL_CRMF_CERTTEMPLATE_free ,
.Nm OSSL_CRMF_CERTTEMPLATE_it ,
.Nm OSSL_CRMF_CERTTEMPLATE_new ,
.Nm OSSL_CRMF_CERTTEMPLATE_dup ,
.Nm OSSL_CRMF_ATTRIBUTETYPEANDVALUE_dup ,
.Nm OSSL_CRMF_ATTRIBUTETYPEANDVALUE_free ,
.Nm OSSL_CRMF_ENCRYPTEDKEY_free ,
.Nm OSSL_CRMF_ENCRYPTEDKEY_it ,
.Nm OSSL_CRMF_ENCRYPTEDKEY_new ,
.Nm OSSL_CRMF_ENCRYPTEDVALUE_free ,
.Nm OSSL_CRMF_ENCRYPTEDVALUE_it ,
.Nm OSSL_CRMF_ENCRYPTEDVALUE_new ,
.Nm OSSL_CRMF_MSGS_free ,
.Nm OSSL_CRMF_MSGS_it ,
.Nm OSSL_CRMF_MSGS_new ,
.Nm OSSL_CRMF_MSG_dup ,
.Nm OSSL_CRMF_MSG_free ,
.Nm OSSL_CRMF_MSG_it ,
.Nm OSSL_CRMF_MSG_new ,
.Nm OSSL_CRMF_PBMPARAMETER_free ,
.Nm OSSL_CRMF_PBMPARAMETER_it ,
.Nm OSSL_CRMF_PBMPARAMETER_new ,
.Nm OSSL_CRMF_PKIPUBLICATIONINFO_free ,
.Nm OSSL_CRMF_PKIPUBLICATIONINFO_it ,
.Nm OSSL_CRMF_PKIPUBLICATIONINFO_new ,
.Nm OSSL_CRMF_SINGLEPUBINFO_free ,
.Nm OSSL_CRMF_SINGLEPUBINFO_it ,
.Nm OSSL_CRMF_SINGLEPUBINFO_new ,
.Nm OSSL_DAY_TIME_free ,
.Nm OSSL_DAY_TIME_new ,
.Nm OSSL_DAY_TIME_it ,
.Nm OSSL_DAY_TIME_BAND_free ,
.Nm OSSL_DAY_TIME_BAND_new ,
.Nm OSSL_DAY_TIME_BAND_it ,
.Nm OSSL_HASH_free ,
.Nm OSSL_HASH_it ,
.Nm OSSL_HASH_new ,
.Nm OSSL_INFO_SYNTAX_free ,
.Nm OSSL_INFO_SYNTAX_it ,
.Nm OSSL_INFO_SYNTAX_new ,
.Nm OSSL_INFO_SYNTAX_POINTER_free ,
.Nm OSSL_INFO_SYNTAX_POINTER_it ,
.Nm OSSL_INFO_SYNTAX_POINTER_new ,
.Nm OSSL_PRIVILEGE_POLICY_ID_free ,
.Nm OSSL_PRIVILEGE_POLICY_ID_it ,
.Nm OSSL_PRIVILEGE_POLICY_ID_new ,
.Nm OSSL_TARGET_CERT_free ,
.Nm OSSL_TARGET_CERT_it ,
.Nm OSSL_TARGET_CERT_new ,
.Nm OSSL_TARGET_free ,
.Nm OSSL_TARGET_it ,
.Nm OSSL_TARGET_new ,
.Nm OSSL_TARGETING_INFORMATION_free ,
.Nm OSSL_TARGETING_INFORMATION_it ,
.Nm OSSL_TARGETING_INFORMATION_new ,
.Nm OSSL_TARGETS_free ,
.Nm OSSL_TARGETS_it ,
.Nm OSSL_TARGETS_new ,
.Nm OSSL_IETF_ATTR_SYNTAX_VALUE_free ,
.Nm OSSL_IETF_ATTR_SYNTAX_VALUE_it ,
.Nm OSSL_IETF_ATTR_SYNTAX_VALUE_new ,
.Nm OSSL_ISSUER_SERIAL_free ,
.Nm OSSL_ISSUER_SERIAL_new ,
.Nm OSSL_NAMED_DAY_free ,
.Nm OSSL_NAMED_DAY_new ,
.Nm OSSL_NAMED_DAY_it ,
.Nm OSSL_OBJECT_DIGEST_INFO_free ,
.Nm OSSL_OBJECT_DIGEST_INFO_new ,
.Nm OSSL_ROLE_SPEC_CERT_ID_free ,
.Nm OSSL_ROLE_SPEC_CERT_ID_new ,
.Nm OSSL_ROLE_SPEC_CERT_ID_it ,
.Nm OSSL_ROLE_SPEC_CERT_ID_SYNTAX_free ,
.Nm OSSL_ROLE_SPEC_CERT_ID_SYNTAX_new ,
.Nm OSSL_ROLE_SPEC_CERT_ID_SYNTAX_it ,
.Nm OSSL_TIME_PERIOD_free ,
.Nm OSSL_TIME_PERIOD_new ,
.Nm OSSL_TIME_PERIOD_it ,
.Nm OSSL_TIME_SPEC_ABSOLUTE_free ,
.Nm OSSL_TIME_SPEC_ABSOLUTE_new ,
.Nm OSSL_TIME_SPEC_ABSOLUTE_it ,
.Nm OSSL_TIME_SPEC_free ,
.Nm OSSL_TIME_SPEC_new ,
.Nm OSSL_TIME_SPEC_it ,
.Nm OSSL_TIME_SPEC_DAY_free ,
.Nm OSSL_TIME_SPEC_DAY_new ,
.Nm OSSL_TIME_SPEC_DAY_it ,
.Nm OSSL_TIME_SPEC_MONTH_free ,
.Nm OSSL_TIME_SPEC_MONTH_new ,
.Nm OSSL_TIME_SPEC_MONTH_it ,
.Nm OSSL_TIME_SPEC_TIME_free ,
.Nm OSSL_TIME_SPEC_TIME_new ,
.Nm OSSL_TIME_SPEC_TIME_it ,
.Nm OSSL_TIME_SPEC_WEEKS_free ,
.Nm OSSL_TIME_SPEC_WEEKS_new ,
.Nm OSSL_TIME_SPEC_WEEKS_it ,
.Nm OSSL_TIME_SPEC_X_DAY_OF_free ,
.Nm OSSL_TIME_SPEC_X_DAY_OF_new ,
.Nm OSSL_TIME_SPEC_X_DAY_OF_it ,
.Nm OSSL_USER_NOTICE_SYNTAX_free ,
.Nm OSSL_USER_NOTICE_SYNTAX_new ,
.Nm OSSL_USER_NOTICE_SYNTAX_it ,
.Nm OTHERNAME_free ,
.Nm OTHERNAME_new ,
.Nm PBE2PARAM_free ,
.Nm PBE2PARAM_new ,
.Nm PBEPARAM_free ,
.Nm PBEPARAM_new ,
.Nm PBKDF2PARAM_free ,
.Nm PBKDF2PARAM_new ,
.Nm PBMAC1PARAM_free ,
.Nm PBMAC1PARAM_it ,
.Nm PBMAC1PARAM_new ,
.Nm PKCS12_BAGS_free ,
.Nm PKCS12_BAGS_new ,
.Nm PKCS12_MAC_DATA_free ,
.Nm PKCS12_MAC_DATA_new ,
.Nm PKCS12_SAFEBAG_free ,
.Nm PKCS12_SAFEBAG_new ,
.Nm PKCS12_free ,
.Nm PKCS12_new ,
.Nm PKCS7_DIGEST_free ,
.Nm PKCS7_DIGEST_new ,
.Nm PKCS7_ENCRYPT_free ,
.Nm PKCS7_ENCRYPT_new ,
.Nm PKCS7_ENC_CONTENT_free ,
.Nm PKCS7_ENC_CONTENT_new ,
.Nm PKCS7_ENVELOPE_free ,
.Nm PKCS7_ENVELOPE_new ,
.Nm PKCS7_ISSUER_AND_SERIAL_free ,
.Nm PKCS7_ISSUER_AND_SERIAL_new ,
.Nm PKCS7_RECIP_INFO_free ,
.Nm PKCS7_RECIP_INFO_new ,
.Nm PKCS7_SIGNED_free ,
.Nm PKCS7_SIGNED_new ,
.Nm PKCS7_SIGNER_INFO_free ,
.Nm PKCS7_SIGNER_INFO_new ,
.Nm PKCS7_SIGN_ENVELOPE_free ,
.Nm PKCS7_SIGN_ENVELOPE_new ,
.Nm PKCS7_dup ,
.Nm PKCS7_free ,
.Nm PKCS7_new_ex ,
.Nm PKCS7_new ,
.Nm PKCS7_print_ctx ,
.Nm PKCS8_PRIV_KEY_INFO_free ,
.Nm PKCS8_PRIV_KEY_INFO_new ,
.Nm PKEY_USAGE_PERIOD_free ,
.Nm PKEY_USAGE_PERIOD_new ,
.Nm POLICYINFO_free ,
.Nm POLICYINFO_new ,
.Nm POLICYQUALINFO_free ,
.Nm POLICYQUALINFO_new ,
.Nm POLICY_CONSTRAINTS_free ,
.Nm POLICY_CONSTRAINTS_new ,
.Nm POLICY_MAPPING_free ,
.Nm POLICY_MAPPING_new ,
.Nm PROFESSION_INFOS_free ,
.Nm PROFESSION_INFOS_new ,
.Nm PROFESSION_INFO_free ,
.Nm PROFESSION_INFO_new ,
.Nm PROXY_CERT_INFO_EXTENSION_free ,
.Nm PROXY_CERT_INFO_EXTENSION_new ,
.Nm PROXY_POLICY_free ,
.Nm PROXY_POLICY_new ,
.Nm RSAPrivateKey_dup ,
.Nm RSAPublicKey_dup ,
.Nm RSA_OAEP_PARAMS_free ,
.Nm RSA_OAEP_PARAMS_new ,
.Nm RSA_PSS_PARAMS_free ,
.Nm RSA_PSS_PARAMS_new ,
.Nm RSA_PSS_PARAMS_dup ,
.Nm SCRYPT_PARAMS_free ,
.Nm SCRYPT_PARAMS_new ,
.Nm SXNETID_free ,
.Nm SXNETID_new ,
.Nm SXNET_free ,
.Nm SXNET_new ,
.Nm TLS_FEATURE_free ,
.Nm TLS_FEATURE_new ,
.Nm TS_ACCURACY_dup ,
.Nm TS_ACCURACY_free ,
.Nm TS_ACCURACY_new ,
.Nm TS_MSG_IMPRINT_dup ,
.Nm TS_MSG_IMPRINT_free ,
.Nm TS_MSG_IMPRINT_new ,
.Nm TS_REQ_dup ,
.Nm TS_REQ_free ,
.Nm TS_REQ_new ,
.Nm TS_RESP_dup ,
.Nm TS_RESP_free ,
.Nm TS_RESP_new ,
.Nm TS_STATUS_INFO_dup ,
.Nm TS_STATUS_INFO_free ,
.Nm TS_STATUS_INFO_new ,
.Nm TS_TST_INFO_dup ,
.Nm TS_TST_INFO_free ,
.Nm TS_TST_INFO_new ,
.Nm USERNOTICE_free ,
.Nm USERNOTICE_new ,
.Nm X509_ACERT_dup ,
.Nm X509_ACERT_free ,
.Nm X509_ACERT_it ,
.Nm X509_ACERT_new ,
.Nm X509_ACERT_INFO_free ,
.Nm X509_ACERT_INFO_it ,
.Nm X509_ACERT_INFO_new ,
.Nm X509_ACERT_ISSUER_V2FORM_free ,
.Nm X509_ACERT_ISSUER_V2FORM_new ,
.Nm X509_ALGOR_free ,
.Nm X509_ALGOR_it ,
.Nm X509_ALGOR_new ,
.Nm X509_ATTRIBUTE_dup ,
.Nm X509_ATTRIBUTE_free ,
.Nm X509_ATTRIBUTE_new ,
.Nm X509_CERT_AUX_free ,
.Nm X509_CERT_AUX_new ,
.Nm X509_CINF_free ,
.Nm X509_CINF_new ,
.Nm X509_CRL_INFO_free ,
.Nm X509_CRL_INFO_new ,
.Nm X509_CRL_dup ,
.Nm X509_CRL_free ,
.Nm X509_CRL_new_ex ,
.Nm X509_CRL_new ,
.Nm X509_EXTENSION_dup ,
.Nm X509_EXTENSION_free ,
.Nm X509_EXTENSION_new ,
.Nm X509_NAME_ENTRY_dup ,
.Nm X509_NAME_ENTRY_free ,
.Nm X509_NAME_ENTRY_new ,
.Nm X509_NAME_dup ,
.Nm X509_NAME_free ,
.Nm X509_NAME_new ,
.Nm X509_REQ_INFO_free ,
.Nm X509_REQ_INFO_new ,
.Nm X509_REQ_dup ,
.Nm X509_REQ_free ,
.Nm X509_REQ_new ,
.Nm X509_REQ_new_ex ,
.Nm X509_REVOKED_dup ,
.Nm X509_REVOKED_free ,
.Nm X509_REVOKED_new ,
.Nm X509_SIG_free ,
.Nm X509_SIG_new ,
.Nm X509_VAL_free ,
.Nm X509_VAL_new ,
.Nm X509_dup ,
.Nd ASN1 object utilities
.Sh SYNOPSIS
.In openssl/asn1t.h
.Bd -literal
 DECLARE_ASN1_FUNCTIONS(type)
 IMPLEMENT_ASN1_FUNCTIONS(stname)
.Ed
.Ft typedef struct ASN1_ITEM_st ASN1_ITEM;

 extern const ASN1_ITEM TYPE_it;
 TYPE *
.Fo TYPE_new
.Fa void
.Fc
.Ft TYPE *
.Fo TYPE_dup
.Fa "const TYPE *a"
.Fc
.Ft void
.Fo TYPE_free
.Fa "TYPE *a"
.Fc
.Ft int
.Fo TYPE_print_ctx
.Fa "BIO *out"
.Fa "TYPE *a"
.Fa "int indent"
.Fa "const ASN1_PCTX *pctx"
.Fc
The following functions have been deprecated since OpenSSL 3.0, and can
be hidden entirely by defining
.Ar OPENSSL_API_COMPAT
with a suitable version value, see
.Xr openssl_user_macros 7 :
.Ft DSA *
.Fo DSAparams_dup
.Fa "const DSA *dsa"
.Fc
.Ft RSA *
.Fo RSAPrivateKey_dup
.Fa "const RSA *rsa"
.Fc
.Ft RSA *
.Fo RSAPublicKey_dup
.Fa "const RSA *rsa"
.Fc
.Sh DESCRIPTION
In the description below,
.Sy Vt TYPE
is used as a placeholder for any of the OpenSSL datatypes, such as
.Sy X509 .
.Pp
The OpenSSL ASN1 parsing library templates are like a data-driven
bytecode interpreter.
Every ASN1 object as a global variable, TYPE_it, that describes the item
such as its fields.
(On systems which cannot export variables from shared libraries, the
global is instead a function which returns a pointer to a static
variable.
.Pp
The macro
.Xr DECLARE_ASN1_FUNCTIONS 3
is typically used in header files to generate the function declarations.
.Pp
The macro
.Xr IMPLEMENT_ASN1_FUNCTIONS 3
is used once in a source file to generate the function bodies.
.Pp
.Sy Vt TYPE Ns _new Ns
.Xr 3
allocates an empty object of the indicated type.
The object returned must be released by calling
.Sy Vt TYPE Ns _free Ns
.Xr 3 .
.Pp
.Sy Vt TYPE Ns _new_ex Ns
.Xr 3
is similar to
.Sy Vt TYPE Ns _new Ns
.Xr 3
but also passes the library context
.Em libctx
and the property query
.Em propq
to use when retrieving algorithms from providers.
This created object can then be used when loading binary data using
.Sy d2i_ Ns Vt TYPE Ns
.Xr 3 .
.Pp
.Sy Vt TYPE Ns _dup Ns
.Xr 3
copies an existing object, leaving it untouched.
Note, however, that the internal representation of the object may
contain (besides the ASN.1 structure) further data, which is not copied.
For instance, an
.Sy X509
object usually is augmented by cached information on X.509v3 extensions,
etc., and losing it can lead to wrong validation results.
To avoid such situations, better use
.Sy Vt TYPE Ns _up_ref Ns
.Xr 3
if available.
For the case of
.Sy X509
objects, an alternative to using
.Xr X509_up_ref 3
may be to still call
.Sy Vt TYPE Ns _dup Ns
.Xr 3 ,
e.g.,
.Em copied_cert = X509_dup(cert) ,
followed by
.Em X509_check_purpose(copied_cert, -1, 0) ,
which re-builds the cached data.
.Pp
.Sy Vt TYPE Ns _free Ns
.Xr 3
releases the object and all pointers and sub-objects within it.
If the argument is NULL, nothing is done.
.Pp
.Sy Vt TYPE Ns _print_ctx Ns
.Xr 3
prints the object
.Fa a
on the specified BIO
.Fa out .
Each line will be prefixed with
.Fa indent
spaces.
The
.Fa pctx
specifies the printing context and is for internal use; use NULL to get
the default behavior.
If a print function is user-defined, then pass in any
.Fa pctx
down to any nested calls.
.Sh RETURN VALUES
.Sy Vt TYPE Ns _new Ns
.Xr 3 ,
.Sy Vt TYPE Ns _new_ex Ns
.Xr 3
and
.Sy Vt TYPE Ns _dup Ns
.Xr 3
return a pointer to the object or NULL on failure.
.Pp
.Sy Vt TYPE Ns _print_ctx Ns
.Xr 3
returns 1 on success or zero on failure.
.Sh SEE ALSO
.Xr X509_up_ref 3
.Sh HISTORY
The functions
.Xr X509_REQ_new_ex 3 ,
.Xr X509_CRL_new_ex 3 ,
.Xr PKCS7_new_ex 3
and
.Xr CMS_ContentInfo_new_ex 3
were added in OpenSSL 3.0.
.Pp
The functions
.Fn DSAparams_dup ,
.Fn RSAPrivateKey_dup
and
.Fn RSAPublicKey_dup
were deprecated in 3.0.
.Pp
.Xr CMS_EnvelopedData_it 3 ,
.Xr CMS_SignedData_free 3 ,
.Xr CMS_SignedData_new 3
were added in OpenSSL 3.2.
.Pp
.Xr DIST_POINT_NAME_dup 3 ,
.Xr OSSL_IETF_ATTR_SYNTAX_free 3 ,
.Xr OSSL_IETF_ATTR_SYNTAX_it 3 ,
.Xr OSSL_IETF_ATTR_SYNTAX_new 3 ,
.Xr OSSL_ATTRIBUTES_SYNTAX_free 3 ,
.Xr OSSL_ATTRIBUTES_SYNTAX_it 3 ,
.Xr OSSL_ATTRIBUTES_SYNTAX_new 3 ,
.Xr OSSL_BASIC_ATTR_CONSTRAINTS_free 3 ,
.Xr OSSL_BASIC_ATTR_CONSTRAINTS_it 3 ,
.Xr OSSL_BASIC_ATTR_CONSTRAINTS_new 3 ,
.Xr OSSL_CMP_ATAVS_new 3 ,
.Xr OSSL_CMP_ATAVS_free 3 ,
.Xr OSSL_CMP_ATAVS_it 3 ,
.Xr OSSL_CMP_CRLSTATUS_free 3 ,
.Xr OSSL_CRMF_CERTTEMPLATE_dup 3 ,
.Xr OSSL_CRMF_ATTRIBUTETYPEANDVALUE_dup 3 ,
.Xr OSSL_CRMF_ATTRIBUTETYPEANDVALUE_free 3 ,
.Xr OSSL_TARGET_free 3 ,
.Xr OSSL_TARGET_it 3 ,
.Xr OSSL_TARGET_new 3 ,
.Xr OSSL_TARGETING_INFORMATION_free 3 ,
.Xr OSSL_TARGETING_INFORMATION_it 3 ,
.Xr OSSL_TARGETING_INFORMATION_new 3 ,
.Xr OSSL_TARGETS_free 3 ,
.Xr OSSL_TARGETS_it 3 ,
.Xr OSSL_TARGETS_new 3 ,
.Xr OSSL_IETF_ATTR_SYNTAX_VALUE_free 3 ,
.Xr OSSL_IETF_ATTR_SYNTAX_VALUE_it 3 ,
.Xr OSSL_IETF_ATTR_SYNTAX_VALUE_new 3 ,
.Xr OSSL_ISSUER_SERIAL_free 3 ,
.Xr OSSL_ISSUER_SERIAL_new 3 ,
.Xr OSSL_OBJECT_DIGEST_INFO_free 3 ,
.Xr OSSL_OBJECT_DIGEST_INFO_new 3 ,
.Xr OSSL_USER_NOTICE_SYNTAX_free 3 ,
.Xr OSSL_USER_NOTICE_SYNTAX_new 3 ,
.Xr OSSL_USER_NOTICE_SYNTAX_it 3 ,
.Xr PBMAC1PARAM_free 3 ,
.Xr PBMAC1PARAM_it 3 ,
.Xr PBMAC1PARAM_new 3 ,
.Xr X509_ACERT_dup 3 ,
.Xr X509_ACERT_free 3 ,
.Xr X509_ACERT_it 3 ,
.Xr X509_ACERT_new 3 ,
.Xr X509_ACERT_INFO_free 3 ,
.Xr X509_ACERT_INFO_it 3 ,
.Xr X509_ACERT_INFO_new 3 ,
.Xr X509_ACERT_ISSUER_V2FORM_free 3 ,
.Xr X509_ACERT_ISSUER_V2FORM_new 3
were added in OpenSSL 3.4.
.Pp
.Xr OSSL_AA_DIST_POINT_free 3 ,
.Xr OSSL_AA_DIST_POINT_new 3 ,
.Xr OSSL_AA_DIST_POINT_it 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_CHOICE_free 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_CHOICE_new 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_CHOICE_it 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_ITEM_free 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_ITEM_new 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_ITEM_it 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_SYNTAX_free 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_SYNTAX_new 3 ,
.Xr OSSL_ALLOWED_ATTRIBUTES_SYNTAX_it 3 ,
.Xr OSSL_ATAV_free 3 ,
.Xr OSSL_ATAV_it 3 ,
.Xr OSSL_ATAV_new 3 ,
.Xr OSSL_ATTRIBUTE_DESCRIPTOR_free 3 ,
.Xr OSSL_ATTRIBUTE_DESCRIPTOR_new 3 ,
.Xr OSSL_ATTRIBUTE_DESCRIPTOR_it 3 ,
.Xr OSSL_ATTRIBUTE_MAPPINGS_free 3 ,
.Xr OSSL_ATTRIBUTE_MAPPINGS_it 3 ,
.Xr OSSL_ATTRIBUTE_MAPPINGS_new 3 ,
.Xr OSSL_ATTRIBUTE_MAPPING_free 3 ,
.Xr OSSL_ATTRIBUTE_MAPPING_it 3 ,
.Xr OSSL_ATTRIBUTE_MAPPING_new 3 ,
.Xr OSSL_ATTRIBUTE_TYPE_MAPPING_free 3 ,
.Xr OSSL_ATTRIBUTE_TYPE_MAPPING_it 3 ,
.Xr OSSL_ATTRIBUTE_TYPE_MAPPING_new 3 ,
.Xr OSSL_ATTRIBUTE_VALUE_MAPPING_free 3 ,
.Xr OSSL_ATTRIBUTE_VALUE_MAPPING_it 3 ,
.Xr OSSL_ATTRIBUTE_VALUE_MAPPING_new 3 ,
.Xr OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX_free 3 ,
.Xr OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX_it 3 ,
.Xr OSSL_AUTHORITY_ATTRIBUTE_ID_SYNTAX_new 3 ,
.Xr OSSL_HASH_free 3 ,
.Xr OSSL_HASH_it 3 ,
.Xr OSSL_HASH_new 3 ,
.Xr OSSL_INFO_SYNTAX_free 3 ,
.Xr OSSL_INFO_SYNTAX_it 3 ,
.Xr OSSL_INFO_SYNTAX_new 3 ,
.Xr OSSL_INFO_SYNTAX_POINTER_free 3 ,
.Xr OSSL_INFO_SYNTAX_POINTER_it 3 ,
.Xr OSSL_INFO_SYNTAX_POINTER_new 3 ,
.Xr OSSL_PRIVILEGE_POLICY_ID_free 3 ,
.Xr OSSL_PRIVILEGE_POLICY_ID_it 3 ,
.Xr OSSL_PRIVILEGE_POLICY_ID_new 3 ,
.Xr OSSL_ROLE_SPEC_CERT_ID_free 3 ,
.Xr OSSL_ROLE_SPEC_CERT_ID_new 3 ,
.Xr OSSL_ROLE_SPEC_CERT_ID_it 3 ,
.Xr OSSL_ROLE_SPEC_CERT_ID_SYNTAX_free 3 ,
.Xr OSSL_ROLE_SPEC_CERT_ID_SYNTAX_new 3 ,
.Xr OSSL_ROLE_SPEC_CERT_ID_SYNTAX_it 3 ,
.Xr OSSL_DAY_TIME_BAND_free 3 ,
.Xr OSSL_DAY_TIME_BAND_it 3 ,
.Xr OSSL_DAY_TIME_BAND_new 3 ,
.Xr OSSL_DAY_TIME_free 3 ,
.Xr OSSL_DAY_TIME_it 3 ,
.Xr OSSL_DAY_TIME_new 3 ,
.Xr OSSL_NAMED_DAY_free 3 ,
.Xr OSSL_NAMED_DAY_it 3 ,
.Xr OSSL_NAMED_DAY_new 3 ,
.Xr OSSL_TIME_PERIOD_free 3 ,
.Xr OSSL_TIME_PERIOD_it 3 ,
.Xr OSSL_TIME_PERIOD_new 3 ,
.Xr OSSL_TIME_SPEC_ABSOLUTE_free 3 ,
.Xr OSSL_TIME_SPEC_ABSOLUTE_it 3 ,
.Xr OSSL_TIME_SPEC_ABSOLUTE_new 3 ,
.Xr OSSL_TIME_SPEC_DAY_free 3 ,
.Xr OSSL_TIME_SPEC_DAY_it 3 ,
.Xr OSSL_TIME_SPEC_DAY_new 3 ,
.Xr OSSL_TIME_SPEC_MONTH_free 3 ,
.Xr OSSL_TIME_SPEC_MONTH_it 3 ,
.Xr OSSL_TIME_SPEC_MONTH_new 3 ,
.Xr OSSL_TIME_SPEC_TIME_free 3 ,
.Xr OSSL_TIME_SPEC_TIME_it 3 ,
.Xr OSSL_TIME_SPEC_TIME_new 3 ,
.Xr OSSL_TIME_SPEC_WEEKS_free 3 ,
.Xr OSSL_TIME_SPEC_WEEKS_it 3 ,
.Xr OSSL_TIME_SPEC_WEEKS_new 3 ,
.Xr OSSL_TIME_SPEC_X_DAY_OF_free 3 ,
.Xr OSSL_TIME_SPEC_X_DAY_OF_it 3 ,
.Xr OSSL_TIME_SPEC_X_DAY_OF_new 3 ,
.Xr OSSL_TIME_SPEC_free 3 ,
.Xr OSSL_TIME_SPEC_it 3 ,
.Xr OSSL_TIME_SPEC_new 3 ,
.Xr CMS_EnvelopedData_dup 3 ,
.Xr OSSL_CRMF_ENCRYPTEDKEY_free 3 ,
.Xr OSSL_CRMF_ENCRYPTEDKEY_it 3
and
.Xr OSSL_CRMF_ENCRYPTEDKEY_new 3
were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2016-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
