.Dd 2025-09-30
.Dt X509_LOOKUP 3ossl
.Os
.Sh NAME
.Nm X509_LOOKUP ,
.Nm X509_LOOKUP_TYPE ,
.Nm X509_LOOKUP_new ,
.Nm X509_LOOKUP_free ,
.Nm X509_LOOKUP_init ,
.Nm X509_LOOKUP_shutdown ,
.Nm X509_LOOKUP_set_method_data ,
.Nm X509_LOOKUP_get_method_data ,
.Nm X509_LOOKUP_ctrl_ex ,
.Nm X509_LOOKUP_ctrl ,
.Nm X509_LOOKUP_load_file_ex ,
.Nm X509_LOOKUP_load_file ,
.Nm X509_LOOKUP_add_dir ,
.Nm X509_LOOKUP_add_store_ex ,
.Nm X509_LOOKUP_add_store ,
.Nm X509_LOOKUP_load_store_ex ,
.Nm X509_LOOKUP_load_store ,
.Nm X509_LOOKUP_get_store ,
.Nm X509_LOOKUP_by_subject_ex ,
.Nm X509_LOOKUP_by_subject ,
.Nm X509_LOOKUP_by_issuer_serial ,
.Nm X509_LOOKUP_by_fingerprint ,
.Nm X509_LOOKUP_by_alias
.Nd OpenSSL certificate lookup mechanisms
.Sh SYNOPSIS
.In openssl/x509_vfy.h
.Ft typedef x509_lookup_st X509_LOOKUP;

 typedef enum X509_LOOKUP_TYPE;

 X509_LOOKUP *
.Fo X509_LOOKUP_new
.Fa "X509_LOOKUP_METHOD *method"
.Fc
.Ft int
.Fo X509_LOOKUP_init
.Fa "X509_LOOKUP *ctx"
.Fc
.Ft int
.Fo X509_LOOKUP_shutdown
.Fa "X509_LOOKUP *ctx"
.Fc
.Ft void
.Fo X509_LOOKUP_free
.Fa "X509_LOOKUP *ctx"
.Fc
.Ft int
.Fo X509_LOOKUP_set_method_data
.Fa "X509_LOOKUP *ctx"
.Fa "void *data"
.Fc
.Ft void *
.Fo X509_LOOKUP_get_method_data
.Fa "const X509_LOOKUP *ctx"
.Fc
.Ft int
.Fo X509_LOOKUP_ctrl_ex
.Fa "X509_LOOKUP *ctx"
.Fa "int cmd"
.Fa "const char *argc"
.Fa "long argl"
.Fa "char **ret"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo X509_LOOKUP_ctrl
.Fa "X509_LOOKUP *ctx"
.Fa "int cmd"
.Fa "const char *argc"
.Fa "long argl"
.Fa "char **ret"
.Fc
.Ft int
.Fo X509_LOOKUP_load_file_ex
.Fa "X509_LOOKUP *ctx"
.Fa "char *name"
.Fa "long type"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo X509_LOOKUP_load_file
.Fa "X509_LOOKUP *ctx"
.Fa "char *name"
.Fa "long type"
.Fc
.Ft int
.Fo X509_LOOKUP_load_file_ex
.Fa "X509_LOOKUP *ctx"
.Fa "char *name"
.Fa "long type"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo X509_LOOKUP_add_dir
.Fa "X509_LOOKUP *ctx"
.Fa "char *name"
.Fa "long type"
.Fc
.Ft int
.Fo X509_LOOKUP_add_store_ex
.Fa "X509_LOOKUP *ctx"
.Fa "char *uri"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo X509_LOOKUP_add_store
.Fa "X509_LOOKUP *ctx"
.Fa "char *uri"
.Fc
.Ft int
.Fo X509_LOOKUP_load_store_ex
.Fa "X509_LOOKUP *ctx"
.Fa "char *uri"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo X509_LOOKUP_load_store
.Fa "X509_LOOKUP *ctx"
.Fa "char *uri"
.Fc
.Ft X509_STORE *
.Fo X509_LOOKUP_get_store
.Fa "const X509_LOOKUP *ctx"
.Fc
.Ft int
.Fo X509_LOOKUP_by_subject_ex
.Fa "X509_LOOKUP *ctx"
.Fa "X509_LOOKUP_TYPE type"
.Fa "const X509_NAME *name"
.Fa "X509_OBJECT *ret"
.Fa "OSSL_LIB_CTX *libctx"
.Fa "const char *propq"
.Fc
.Ft int
.Fo X509_LOOKUP_by_subject
.Fa "X509_LOOKUP *ctx"
.Fa "X509_LOOKUP_TYPE type"
.Fa "const X509_NAME *name"
.Fa "X509_OBJECT *ret"
.Fc
.Ft int
.Fo X509_LOOKUP_by_issuer_serial
.Fa "X509_LOOKUP *ctx"
.Fa "X509_LOOKUP_TYPE type"
.Fa "const X509_NAME *name"
.Fa "const ASN1_INTEGER *serial"
.Fa "X509_OBJECT *ret"
.Fc
.Ft int
.Fo X509_LOOKUP_by_fingerprint
.Fa "X509_LOOKUP *ctx"
.Fa "X509_LOOKUP_TYPE type"
.Fa "const unsigned char *bytes"
.Fa "int len"
.Fa "X509_OBJECT *ret"
.Fc
.Ft int
.Fo X509_LOOKUP_by_alias
.Fa "X509_LOOKUP *ctx"
.Fa "X509_LOOKUP_TYPE type"
.Fa "const char *str"
.Fa "int len"
.Fa "X509_OBJECT *ret"
.Fc
.Sh DESCRIPTION
The
.Vt X509_LOOKUP
structure holds the information needed to look up certificates and CRLs
according to an associated
.Xr X509_LOOKUP_METHOD 3 .
Multiple
.Vt X509_LOOKUP
instances can be added to an
.Xr X509_STORE 3
to enable lookup in that store.
.Pp
.Fn X509_LOOKUP_new
creates a new
.Vt X509_LOOKUP
using the given lookup
.Fa method .
It can also be created by calling
.Xr X509_STORE_add_lookup 3 ,
which will associate a
.Vt X509_STORE
with the lookup mechanism.
.Pp
.Fn X509_LOOKUP_init
initializes the internal state and resources as needed by the given
.Vt X509_LOOKUP
to do its work.
.Pp
.Fn X509_LOOKUP_shutdown
tears down the internal state and resources of the given
.Vt X509_LOOKUP .
.Pp
.Fn X509_LOOKUP_free
destructs the given
.Vt X509_LOOKUP .
If the argument is NULL, nothing is done.
.Pp
.Fn X509_LOOKUP_set_method_data
and
.Fn X509_LOOKUP_get_method_data
associates and retrieves a pointer to application data to and from the
given
.Vt X509_LOOKUP ,
respectively.
.Pp
.Fn X509_LOOKUP_ctrl_ex
is used to set or get additional data to or from a
.Vt X509_LOOKUP
structure using any control function in the associated
.Xr X509_LOOKUP_METHOD 3 .
The arguments of the control command are passed via
.Fa argc
and
.Fa argl ,
its return value via
.Em *ret .
The library context
.Fa libctx
and property query
.Fa propq
are used when fetching algorithms from providers.
The meaning of the arguments depends on the
.Fa cmd
number of the control command.
In general, this function is not called directly, but wrapped by a macro
call, see below.
The control
.Fa cmd Ns s
known to OpenSSL are discussed in more depth in
.Sx Control Commands .
.Pp
.Fn X509_LOOKUP_ctrl
is similar to
.Fn X509_LOOKUP_ctrl_ex
but uses NULL for the library context
.Fa libctx
and property query
.Fa propq .
.Pp
.Fn X509_LOOKUP_load_file_ex
passes a filename to be loaded immediately into the associated
.Vt X509_STORE .
The library context
.Fa libctx
and property query
.Fa propq
are used when fetching algorithms from providers.
.Fa type
indicates what type of object is expected.
This can only be used with a lookup using the implementation
.Xr X509_LOOKUP_file 3 .
.Pp
.Fn X509_LOOKUP_load_file
is similar to
.Fn X509_LOOKUP_load_file_ex
but uses NULL for the library context
.Fa libctx
and property query
.Fa propq .
.Pp
.Fn X509_LOOKUP_add_dir
passes a directory specification from which certificates and CRLs are
loaded on demand into the associated
.Vt X509_STORE .
.Fa type
indicates what type of object is expected.
This can only be used with a lookup using the implementation
.Xr X509_LOOKUP_hash_dir 3 .
.Pp
.Fn X509_LOOKUP_add_store_ex
passes a URI for a directory-like structure from which containers with
certificates and CRLs are loaded on demand into the associated
.Vt X509_STORE .
The library context
.Fa libctx
and property query
.Fa propq
are used when fetching algorithms from providers.
.Pp
.Fn X509_LOOKUP_add_store
is similar to
.Fn X509_LOOKUP_add_store_ex
but uses NULL for the library context
.Fa libctx
and property query
.Fa propq .
.Pp
.Fn X509_LOOKUP_load_store_ex
passes a URI for a single container from which certificates and CRLs are
immediately loaded into the associated
.Vt X509_STORE .
The library context
.Fa libctx
and property query
.Fa propq
are used when fetching algorithms from providers.
These functions can only be used with a lookup using the implementation
.Xr X509_LOOKUP_store 3 .
.Pp
.Fn X509_LOOKUP_load_store
is similar to
.Fn X509_LOOKUP_load_store_ex
but uses NULL for the library context
.Fa libctx
and property query
.Fa propq .
.Pp
.Fn X509_LOOKUP_load_file_ex ,
.Fn X509_LOOKUP_load_file ,
.Fn X509_LOOKUP_add_dir ,
.Fn X509_LOOKUP_add_store_ex
.Fn X509_LOOKUP_add_store ,
.Fn X509_LOOKUP_load_store_ex
and
.Fn X509_LOOKUP_load_store
are implemented as macros that use
.Fn X509_LOOKUP_ctrl .
.Pp
.Fn X509_LOOKUP_by_subject_ex ,
.Fn X509_LOOKUP_by_subject ,
.Fn X509_LOOKUP_by_issuer_serial ,
.Fn X509_LOOKUP_by_fingerprint ,
and
.Fn X509_LOOKUP_by_alias
look up certificates and CRLs in the
.Xr X509_STORE 3
associated with the
.Vt X509_LOOKUP
using different criteria, where the looked up object is stored in
.Fa ret .
Some of the underlying
.Vt X509_LOOKUP_METHOD Ns s
will also cache objects matching the criteria in the associated
.Vt X509_STORE ,
which makes it possible to handle cases where the criteria have more
than one hit.
.Ss Control Commands
The
.Vt X509_LOOKUP_METHOD Ns s
built into OpenSSL recognize the following
.Fn X509_LOOKUP_ctrl
.Fa cmd Ns s:
.Bl -tag -width Ds
.It Sy X509_L_FILE_LOAD
This is the command that
.Fn X509_LOOKUP_load_file_ex
and
.Fn X509_LOOKUP_load_file
use.
The filename is passed in
.Fa argc ,
and the type in
.Fa argl .
.It Sy X509_L_ADD_DIR
This is the command that
.Fn X509_LOOKUP_add_dir
uses.
The directory specification is passed in
.Fa argc ,
and the type in
.Fa argl .
.It Sy X509_L_ADD_STORE
This is the command that
.Fn X509_LOOKUP_add_store_ex
and
.Fn X509_LOOKUP_add_store
use.
The URI is passed in
.Fa argc .
.It Sy X509_L_LOAD_STORE
This is the command that
.Fn X509_LOOKUP_load_store_ex
and
.Fn X509_LOOKUP_load_store
use.
The URI is passed in
.Fa argc .
.El
.Sh RETURN VALUES
.Fn X509_LOOKUP_new
returns a
.Vt X509_LOOKUP
pointer when successful, or NULL on error.
.Pp
.Fn X509_LOOKUP_init
and
.Fn X509_LOOKUP_shutdown
return 1 on success, or 0 on error.
.Pp
.Fn X509_LOOKUP_ctrl_ex
and
.Fn X509_LOOKUP_ctrl
return -1 if the
.Vt X509_LOOKUP
doesn't have an associated
.Vt X509_LOOKUP_METHOD ,
or 1 if the doesn't have a control function.
Otherwise, it returns what the control function in the
.Vt X509_LOOKUP_METHOD
returns, which is usually 1 on success and 0 on error but could also be
-1 on failure.
.Pp
.Fn X509_LOOKUP_get_store
returns a
.Vt X509_STORE
pointer if there is one, otherwise NULL.
.Pp
.Fn X509_LOOKUP_by_subject_ex
returns 0 if there is no
.Vt X509_LOOKUP_METHOD
that implements any of the
.Xr get_by_subject_ex 3
or
.Xr get_by_subject 3
functions.
It calls
.Xr get_by_subject_ex 3
if present, otherwise
.Xr get_by_subject 3 ,
and returns the result of the function, which is usually 1 on success
and 0 on error.
.Pp
.Fn X509_LOOKUP_by_subject
is similar to
.Fn X509_LOOKUP_by_subject_ex
but passes NULL for both the libctx and propq.
.Pp
.Fn X509_LOOKUP_by_issuer_serial ,
.Fn X509_LOOKUP_by_fingerprint ,
and
.Fn X509_LOOKUP_by_alias
all return 0 if there is no
.Vt X509_LOOKUP_METHOD
or that method doesn't implement the corresponding function.
Otherwise, they return what the corresponding function in the
.Vt X509_LOOKUP_METHOD
returns, which is usually 1 on success and 0 in error.
.Sh SEE ALSO
.Xr X509_LOOKUP_METHOD 3 ,
.Xr X509_STORE 3
.Sh HISTORY
The functions
.Fn X509_LOOKUP_by_subject_ex
and
.Fn X509_LOOKUP_ctrl_ex
were added in OpenSSL 3.0.
.Pp
The macros
.Fn X509_LOOKUP_load_file_ex ,
.Fn X509_LOOKUP_load_store_ex
and
.Xr 509_LOOKUP_add_store_ex 3
were added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
