.Dd 2025-09-30
.Dt X509_LOOKUP_METH_NEW 3ossl
.Os
.Sh NAME
.Nm X509_LOOKUP_METHOD ,
.Nm X509_LOOKUP_meth_new ,
.Nm X509_LOOKUP_meth_free ,
.Nm X509_LOOKUP_meth_set_new_item ,
.Nm X509_LOOKUP_meth_get_new_item ,
.Nm X509_LOOKUP_meth_set_free ,
.Nm X509_LOOKUP_meth_get_free ,
.Nm X509_LOOKUP_meth_set_init ,
.Nm X509_LOOKUP_meth_get_init ,
.Nm X509_LOOKUP_meth_set_shutdown ,
.Nm X509_LOOKUP_meth_get_shutdown ,
.Nm X509_LOOKUP_ctrl_fn ,
.Nm X509_LOOKUP_meth_set_ctrl ,
.Nm X509_LOOKUP_meth_get_ctrl ,
.Nm X509_LOOKUP_get_by_subject_fn ,
.Nm X509_LOOKUP_meth_set_get_by_subject ,
.Nm X509_LOOKUP_meth_get_get_by_subject ,
.Nm X509_LOOKUP_get_by_issuer_serial_fn ,
.Nm X509_LOOKUP_meth_set_get_by_issuer_serial ,
.Nm X509_LOOKUP_meth_get_get_by_issuer_serial ,
.Nm X509_LOOKUP_get_by_fingerprint_fn ,
.Nm X509_LOOKUP_meth_set_get_by_fingerprint ,
.Nm X509_LOOKUP_meth_get_get_by_fingerprint ,
.Nm X509_LOOKUP_get_by_alias_fn ,
.Nm X509_LOOKUP_meth_set_get_by_alias ,
.Nm X509_LOOKUP_meth_get_get_by_alias ,
.Nm X509_OBJECT_set1_X509 ,
.Nm X509_OBJECT_set1_X509_CRL
.Nd Routines to build up X509_LOOKUP methods
.Sh SYNOPSIS
.In openssl/x509_vfy.h
.Ft typedef x509_lookup_method_st X509_LOOKUP_METHOD;

 X509_LOOKUP_METHOD *
.Fo X509_LOOKUP_meth_new
.Fa "const char *name"
.Fc
.Ft void
.Fo X509_LOOKUP_meth_free
.Fa "X509_LOOKUP_METHOD *method"
.Fc
.Ft int
.Fo X509_LOOKUP_meth_set_new_item
.Fa "X509_LOOKUP_METHOD *method"
.Fa "int (*new_item) (X509_LOOKUP *ctx)"
.Fc
.Ft int
.Fo 
.Fa "*X509_LOOKUP_meth_get_new_item(const X509_LOOKUP_METHOD* method)"
.Fc
.Bd -literal
     (X509_LOOKUP *ctx);
.Ed
.Ft int
.Fo X509_LOOKUP_meth_set_free
.Fa "X509_LOOKUP_METHOD *method"
.Fa "void (*free) (X509_LOOKUP *ctx)"
.Fc
.Ft void
.Fo 
.Fa "*X509_LOOKUP_meth_get_free(const X509_LOOKUP_METHOD* method)"
.Fc
.Bd -literal
     (X509_LOOKUP *ctx);
.Ed
.Ft int
.Fo X509_LOOKUP_meth_set_init
.Fa "X509_LOOKUP_METHOD *method"
.Fa "int (*init) (X509_LOOKUP *ctx)"
.Fc
.Ft int
.Fo 
.Fa "*X509_LOOKUP_meth_get_init(const X509_LOOKUP_METHOD* method)"
.Fc
.Bd -literal
     (X509_LOOKUP *ctx);
.Ed
.Ft int
.Fo X509_LOOKUP_meth_set_shutdown
.Fa "X509_LOOKUP_METHOD *method"
.Fa "int (*shutdown) (X509_LOOKUP *ctx)"
.Fc
.Ft int
.Fo 
.Fa "*X509_LOOKUP_meth_get_shutdown(const X509_LOOKUP_METHOD* method)"
.Fc
.Bd -literal
     (X509_LOOKUP *ctx);
.Ed
.Ft typedef int
.Fo 
.Fa *X509_LOOKUP_ctrl_fn
.Fc
(X509_LOOKUP *ctx, int cmd, const char *argc,
.Bd -literal
                                    long argl, char **ret);
 int X509_LOOKUP_meth_set_ctrl(X509_LOOKUP_METHOD *method,
     X509_LOOKUP_ctrl_fn ctrl_fn);
 X509_LOOKUP_ctrl_fn X509_LOOKUP_meth_get_ctrl(const X509_LOOKUP_METHOD *method);
.Ed
.Ft typedef int
.Fo 
.Fa *X509_LOOKUP_get_by_subject_fn
.Fc
(X509_LOOKUP *ctx,
.Bd -literal
                                              X509_LOOKUP_TYPE type,
                                              const X509_NAME *name,
                                              X509_OBJECT *ret);
 int X509_LOOKUP_meth_set_get_by_subject(X509_LOOKUP_METHOD *method,
     X509_LOOKUP_get_by_subject_fn fn);
 X509_LOOKUP_get_by_subject_fn X509_LOOKUP_meth_get_get_by_subject(
     const X509_LOOKUP_METHOD *method);
.Ed
.Ft typedef int
.Fo 
.Fa *X509_LOOKUP_get_by_issuer_serial_fn
.Fc
(X509_LOOKUP *ctx,
.Bd -literal
                                                    X509_LOOKUP_TYPE type,
                                                    const X509_NAME *name,
                                                    const ASN1_INTEGER *serial,
                                                    X509_OBJECT *ret);
 int X509_LOOKUP_meth_set_get_by_issuer_serial(
     X509_LOOKUP_METHOD *method, X509_LOOKUP_get_by_issuer_serial_fn fn);
 X509_LOOKUP_get_by_issuer_serial_fn X509_LOOKUP_meth_get_get_by_issuer_serial(
     const X509_LOOKUP_METHOD *method);
.Ed
.Ft typedef int
.Fo 
.Fa *X509_LOOKUP_get_by_fingerprint_fn
.Fc
(X509_LOOKUP *ctx,
.Bd -literal
                                                  X509_LOOKUP_TYPE type,
                                                  const unsigned char* bytes,
                                                  int len,
                                                  X509_OBJECT *ret);
 int X509_LOOKUP_meth_set_get_by_fingerprint(X509_LOOKUP_METHOD *method,
     X509_LOOKUP_get_by_fingerprint_fn fn);
 X509_LOOKUP_get_by_fingerprint_fn X509_LOOKUP_meth_get_get_by_fingerprint(
     const X509_LOOKUP_METHOD *method);
.Ed
.Ft typedef int
.Fo 
.Fa *X509_LOOKUP_get_by_alias_fn
.Fc
(X509_LOOKUP *ctx,
.Bd -literal
                                            X509_LOOKUP_TYPE type,
                                            const char *str,
                                            int len,
                                            X509_OBJECT *ret);
 int X509_LOOKUP_meth_set_get_by_alias(X509_LOOKUP_METHOD *method,
     X509_LOOKUP_get_by_alias_fn fn);
 X509_LOOKUP_get_by_alias_fn X509_LOOKUP_meth_get_get_by_alias(
     const X509_LOOKUP_METHOD *method);
.Ed
.Ft int
.Fo X509_OBJECT_set1_X509
.Fa "X509_OBJECT *a"
.Fa "X509 *obj"
.Fc
.Ft int
.Fo X509_OBJECT_set1_X509_CRL
.Fa "X509_OBJECT *a"
.Fa "X509_CRL *obj"
.Fc
.Sh DESCRIPTION
The
.Vt X509_LOOKUP_METHOD
type is a structure used for the implementation of new X509_LOOKUP
types.
It provides a set of functions used by OpenSSL for the implementation of
various X509 and X509_CRL lookup capabilities.
One instance of an X509_LOOKUP_METHOD can be associated to many
instantiations of an
.Sy X509_LOOKUP
structure.
.Pp
.Fn X509_LOOKUP_meth_new
creates a new
.Vt X509_LOOKUP_METHOD
structure.
It should be given a human-readable string containing a brief
description of the lookup method.
.Pp
.Fn X509_LOOKUP_meth_free
destroys a
.Vt X509_LOOKUP_METHOD
structure.
If the argument is NULL, nothing is done.
.Pp
.Xr X509_LOOKUP_get_new_item 3
and
.Xr X509_LOOKUP_set_new_item 3
get and set the function that is called when an
.Sy X509_LOOKUP
object is created with
.Xr X509_LOOKUP_new 3 .
If an X509_LOOKUP_METHOD requires any per-X509_LOOKUP specific data, the
supplied new_item function should allocate this data and invoke
.Xr X509_LOOKUP_set_method_data 3 .
.Pp
.Xr X509_LOOKUP_get_free 3
and
.Xr X509_LOOKUP_set_free 3
get and set the function that is used to free any method data that was
allocated and set from within new_item function.
.Pp
.Xr X509_LOOKUP_meth_get_init 3
and
.Fn X509_LOOKUP_meth_set_init
get and set the function that is used to initialize the method data that
was set with
.Xr X509_LOOKUP_set_method_data 3
as part of the new_item routine.
.Pp
.Xr X509_LOOKUP_meth_get_shutdown 3
and
.Fn X509_LOOKUP_meth_set_shutdown
get and set the function that is used to shut down the method data whose
state was previously initialized in the init function.
.Pp
.Xr X509_LOOKUP_meth_get_ctrl 3
and
.Xr X509_LOOKUP_meth_set_ctrl 3
get and set a function to be used to handle arbitrary control commands
issued by
.Xr X509_LOOKUP_ctrl 3 .
The control function is given the X509_LOOKUP
.Sy ctx ,
along with the arguments passed by X509_LOOKUP_ctrl.
.Sy cmd
is an arbitrary integer that defines some operation.
.Sy argc
is a pointer to an array of characters.
.Sy argl
is an integer.
.Sy ret ,
if set, points to a location where any return data should be written to.
How
.Sy argc
and
.Sy argl
are used depends entirely on the control function.
.Pp
.Xr X509_LOOKUP_set_get_by_subject 3 ,
.Xr X509_LOOKUP_set_get_by_issuer_serial 3 ,
.Xr X509_LOOKUP_set_get_by_fingerprint 3 ,
.Xr X509_LOOKUP_set_get_by_alias 3
set the functions used to retrieve an X509 or X509_CRL object by the
object's subject, issuer, fingerprint, and alias respectively.
These functions are given the X509_LOOKUP context, the type of the
X509_OBJECT being requested, parameters related to the lookup, and an
X509_OBJECT that will receive the requested object.
.Pp
Implementations must add objects they find to the
.Sy X509_STORE
object using
.Xr X509_STORE_add_cert 3
or
.Xr X509_STORE_add_crl 3 .
This increments its reference count.
However, the
.Xr X509_STORE_CTX_get_by_subject 3
function also increases the reference count which leads to one too many
references being held.
Therefore, applications should additionally call
.Xr X509_free 3
or
.Xr X509_CRL_free 3
to decrement the reference count again.
.Pp
Implementations should also use either
.Fn X509_OBJECT_set1_X509
or
.Fn X509_OBJECT_set1_X509_CRL
to set the result.
Note that this also increments the result's reference count.
.Pp
Any method data that was created as a result of the new_item function
set by
.Fn X509_LOOKUP_meth_set_new_item
can be accessed with
.Xr X509_LOOKUP_get_method_data 3 .
The
.Sy X509_STORE
object that owns the X509_LOOKUP may be accessed with
.Xr X509_LOOKUP_get_store 3 .
Successful lookups should return 1, and unsuccessful lookups should
return 0.
.Pp
.Xr X509_LOOKUP_get_get_by_subject 3 ,
.Xr X509_LOOKUP_get_get_by_issuer_serial 3 ,
.Xr X509_LOOKUP_get_get_by_fingerprint 3 ,
.Xr X509_LOOKUP_get_get_by_alias 3
retrieve the function set by the corresponding setter.
.Sh RETURN VALUES
The
.Sy X509_LOOKUP_meth_set
functions return 1 on success or 0 on error.
.Pp
The
.Sy X509_LOOKUP_meth_get
functions return the corresponding function pointers.
.Sh SEE ALSO
.Xr X509_STORE_CTX_get_by_subject 3 ,
.Xr X509_STORE_new 3 ,
.Xr SSL_CTX_set_cert_store 3
.Sh HISTORY
The functions described here were added in OpenSSL 1.1.0i.
.Sh COPYRIGHT
Copyright 2018-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
