.Dd 2025-09-30
.Dt X509_REQ_GET_EXTENSIONS 3ossl
.Os
.Sh NAME
.Nm X509_REQ_get_extensions ,
.Nm X509_REQ_add_extensions ,
.Nm X509_REQ_add_extensions_nid
.Nd handle X.509 extension attributes of a CSR
.Sh SYNOPSIS
.In openssl/x509.h
.Bd -literal
 STACK_OF(X509_EXTENSION) *X509_REQ_get_extensions(const X509_REQ *req);
 int X509_REQ_add_extensions(X509_REQ *req, const STACK_OF(X509_EXTENSION) *exts);
 int X509_REQ_add_extensions_nid(X509_REQ *req,
                                 const STACK_OF(X509_EXTENSION) *exts, int nid);
.Ed
.Sh DESCRIPTION
.Xr X509_REQ_get_extensions 3
returns the first list of X.509 extensions found in the attributes of
.Em req .
The returned list is empty if there are no such extensions in
.Em req .
The caller is responsible for freeing the list obtained.
.Pp
.Xr X509_REQ_add_extensions_nid 3
adds to
.Em req
a list of X.509 extensions
.Em exts ,
using
.Em nid
to identify the extensions attribute.
.Em req
is unchanged if
.Em exts
is NULL or an empty list.
This function may be called more than once on the same
.Em req
and
.Em nid .
In such case any previous extensions are augmented, where an extension
to be added that has the same OID as a pre-existing one replaces this
earlier one.
.Pp
.Xr X509_REQ_add_extensions 3
is like
.Xr X509_REQ_add_extensions_nid 3
except that the default
.Sy NID_ext_req
is used.
.Sh RETURN VALUES
.Xr X509_REQ_get_extensions 3
returns a pointer to
.Sy STACK_OF(X509_EXTENSION)
or NULL on error.
.Pp
.Xr X509_REQ_add_extensions 3
and
.Xr X509_REQ_add_extensions_nid 3
return 1 on success, 0 on error.
.Sh COPYRIGHT
Copyright 2022-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
