.Dd 2025-09-30
.Dt X509_ATTRIBUTE 3ossl
.Os
.Sh NAME
.Nm X509_ATTRIBUTE ,
.Nm X509at_get_attr ,
.Nm X509at_get_attr_count ,
.Nm X509at_get_attr_by_NID ,
.Nm X509at_get_attr_by_OBJ ,
.Nm X509at_delete_attr ,
.Nm X509at_add1_attr ,
.Nm X509at_add1_attr_by_OBJ ,
.Nm X509at_add1_attr_by_NID ,
.Nm X509at_add1_attr_by_txt ,
.Nm X509at_get0_data_by_OBJ ,
.Nm X509_ATTRIBUTE_create ,
.Nm X509_ATTRIBUTE_create_by_NID ,
.Nm X509_ATTRIBUTE_create_by_OBJ ,
.Nm X509_ATTRIBUTE_create_by_txt ,
.Nm X509_ATTRIBUTE_set1_object ,
.Nm X509_ATTRIBUTE_set1_data ,
.Nm X509_ATTRIBUTE_count ,
.Nm X509_ATTRIBUTE_get0_data ,
.Nm X509_ATTRIBUTE_get0_object ,
.Nm X509_ATTRIBUTE_get0_type
.Nd X509 attribute functions
.Sh SYNOPSIS
.In openssl/x509.h
.Ft typedef struct x509_attributes_st X509_ATTRIBUTE;

 int
.Fo X509at_get_attr_count
.Fa "const STACK_OF(X509_ATTRIBUTE) *x"
.Fc
.Ft int
.Fo X509at_get_attr_by_NID
.Fa "const STACK_OF(X509_ATTRIBUTE) *x"
.Fa "int nid"
.Fa "int lastpos"
.Fc
.Ft int
.Fo X509at_get_attr_by_OBJ
.Fa "const STACK_OF(X509_ATTRIBUTE) *sk"
.Fa "const ASN1_OBJECT *obj"
.Fa "int lastpos"
.Fc
.Ft X509_ATTRIBUTE *
.Fo X509at_get_attr
.Fa "const STACK_OF(X509_ATTRIBUTE) *x"
.Fa "int loc"
.Fc
.Ft X509_ATTRIBUTE *
.Fo X509at_delete_attr
.Fa "STACK_OF(X509_ATTRIBUTE) *x"
.Fa "int loc"
.Fc
.Bd -literal
 STACK_OF(X509_ATTRIBUTE) *X509at_add1_attr(STACK_OF(X509_ATTRIBUTE) **x,
                                            X509_ATTRIBUTE *attr);
 STACK_OF(X509_ATTRIBUTE) *X509at_add1_attr_by_OBJ(STACK_OF(X509_ATTRIBUTE)
                                                   **x, const ASN1_OBJECT *obj,
                                                   int type,
                                                   const unsigned char *bytes,
                                                   int len);
 STACK_OF(X509_ATTRIBUTE) *X509at_add1_attr_by_NID(STACK_OF(X509_ATTRIBUTE)
                                                   **x, int nid, int type,
                                                   const unsigned char *bytes,
                                                   int len);
 STACK_OF(X509_ATTRIBUTE) *X509at_add1_attr_by_txt(STACK_OF(X509_ATTRIBUTE)
                                                   **x, const char *attrname,
                                                   int type,
                                                   const unsigned char *bytes,
                                                   int len);
 void *X509at_get0_data_by_OBJ(const STACK_OF(X509_ATTRIBUTE) *x,
                               const ASN1_OBJECT *obj, int lastpos, int type);
 X509_ATTRIBUTE *X509_ATTRIBUTE_create(int nid, int atrtype, void *value);
 X509_ATTRIBUTE *X509_ATTRIBUTE_create_by_NID(X509_ATTRIBUTE **attr, int nid,
                                              int atrtype, const void *data,
                                              int len);
 X509_ATTRIBUTE *X509_ATTRIBUTE_create_by_OBJ(X509_ATTRIBUTE **attr,
                                              const ASN1_OBJECT *obj,
                                              int atrtype, const void *data,
                                              int len);
 X509_ATTRIBUTE *X509_ATTRIBUTE_create_by_txt(X509_ATTRIBUTE **attr,
                                              const char *atrname, int type,
                                              const unsigned char *bytes,
                                              int len);
 int X509_ATTRIBUTE_set1_object(X509_ATTRIBUTE *attr, const ASN1_OBJECT *obj);
 int X509_ATTRIBUTE_set1_data(X509_ATTRIBUTE *attr, int attrtype,
                              const void *data, int len);
 void *X509_ATTRIBUTE_get0_data(X509_ATTRIBUTE *attr, int idx, int atrtype,
                                void *data);
 int X509_ATTRIBUTE_count(const X509_ATTRIBUTE *attr);
 ASN1_OBJECT *X509_ATTRIBUTE_get0_object(X509_ATTRIBUTE *attr);
 ASN1_TYPE *X509_ATTRIBUTE_get0_type(X509_ATTRIBUTE *attr, int idx);
.Ed
.Sh DESCRIPTION
.Vt X509_ATTRIBUTE
objects are used by many standards including X509, X509_REQ, PKCS12,
PKCS8, PKCS7 and CMS.
.Pp
The
.Vt X509_ATTRIBUTE
object is used to represent the ASN.1 Attribute as defined in RFC 5280,
i.e.
.Bd -literal
 Attribute ::= SEQUENCE {
   type             AttributeType,
   values    SET OF AttributeValue }

 AttributeType ::= OBJECT IDENTIFIER
 AttributeValue ::= ANY -- DEFINED BY AttributeType
.Ed
.Pp
For example CMS defines the signing-time attribute as:
.Bd -literal
  id-signingTime OBJECT IDENTIFIER ::= { iso(1) member-body(2)
      us(840) rsadsi(113549) pkcs(1) pkcs9(9) 5 }

  SigningTime ::= Time

  Time ::= CHOICE {
    utcTime UTCTime,
    generalizedTime GeneralizedTime }
.Ed
.Pp
In OpenSSL
.Sy AttributeType
maps to an
.Sy ASN1_OBJECT
object and
.Sy AttributeValue
maps to a list of
.Sy ASN1_TYPE
objects.
.Pp
The following functions are used for
.Vt X509_ATTRIBUTE
objects.
.Pp
.Fn X509at_get_attr_by_OBJ
finds the location of the first matching object
.Fa obj
in a list of attributes
.Fa sk .
The search starts at the position after
.Fa lastpos .
If the returned value is positive then it can be used on the next call
to
.Fn X509at_get_attr_by_OBJ
as the value of
.Fa lastpos
in order to iterate through the remaining attributes.
.Fa lastpos
can be set to any negative value on the first call, in order to start
searching from the start of the list.
.Pp
.Fn X509at_get_attr_by_NID
is similar to
.Fn X509at_get_attr_by_OBJ
except that it passes the numerical identifier (NID)
.Fa nid
associated with the object.
See <openssl/obj_mac.h> for a list of NID_*.
.Pp
.Fn X509at_get_attr
returns the
.Vt X509_ATTRIBUTE
object at index
.Fa loc
in the list of attributes
.Fa x .
.Fa loc
should be in the range from 0 to
.Fn X509at_get_attr_count
- 1.
.Pp
.Fn X509at_delete_attr
removes the
.Vt X509_ATTRIBUTE
object at index
.Fa loc
in the list of attributes
.Fa x .
.Pp
.Xr X509at_add1_attr 3
pushes a copy of the passed in
.Vt X509_ATTRIBUTE
object to the list
.Fa x .
Both
.Fa x
and
.Em attr
must be non NULL or an error will occur.
If
.Em *x
is NULL then a new list is created, otherwise it uses the passed in
list.
An error will occur if an existing attribute (with the same attribute
type) already exists in the attribute list.
.Pp
.Xr X509at_add1_attr_by_OBJ 3
creates a new
.Vt X509_ATTRIBUTE
using
.Xr X509_ATTRIBUTE_set1_object 3
and
.Xr X509_ATTRIBUTE_set1_data 3
to assign a new
.Fa obj
with type
.Em type
and data
.Em bytes
of length
.Em len
and then pushes it to the attribute list
.Fa x .
Both
.Fa x
and
.Em attr
must be non NULL or an error will occur.
If
.Em *x
is NULL then a new attribute list is created.
If
.Fa obj
already exists in the attribute list then an error occurs.
.Pp
.Xr X509at_add1_attr_by_NID 3
is similar to
.Xr X509at_add1_attr_by_OBJ 3
except that it passes the numerical identifier (NID)
.Fa nid
associated with the object.
See <openssl/obj_mac.h> for a list of NID_*.
.Pp
.Xr X509at_add1_attr_by_txt 3
is similar to
.Xr X509at_add1_attr_by_OBJ 3
except that it passes a name
.Em attrname
associated with the object.
See <openssl/obj_mac.h> for a list of SN_* names.
.Pp
.Xr X509_ATTRIBUTE_set1_object 3
assigns a
.Sy ASN1_OBJECT
.Fa obj
to the attribute
.Em attr .
If
.Em attr
contained an existing
.Sy ASN1_OBJECT
then it is freed.
An error occurs if either
.Em attr
or
.Fa obj
are NULL, or if the passed in
.Fa obj
cannot be duplicated.
.Pp
.Xr X509_ATTRIBUTE_set1_data 3
pushes a new
.Sy ASN1_TYPE
object onto the
.Em attr
attributes list.
The new object is assigned a copy of the data in
.Em data
of size
.Em len .
If
.Em attrtype
has flag
.Em MBSTRING_FLAG
set then a table lookup using the
.Em attr
attributes NID is used to set an
.Sy ASN1_STRING
using
.Xr ASN1_STRING_set_by_NID 3 ,
and the passed in
.Em data
must be in the format required for that object type or an error will
occur.
If
.Em len
is not -1 then internally
.Xr ASN1_STRING_type_new 3
is used with the passed in
.Em attrtype .
If
.Em attrtype
is 0 the call does nothing except return 1.
.Pp
.Xr X509_ATTRIBUTE_create 3
creates a new
.Vt X509_ATTRIBUTE
using the
.Fa nid
to set the
.Sy ASN1_OBJECT
OID and the
.Em atrtype
and
.Em value
to set the
.Sy ASN1_TYPE .
.Pp
.Xr X509_ATTRIBUTE_create_by_OBJ 3
uses
.Xr X509_ATTRIBUTE_set1_object 3
and
.Xr X509_ATTRIBUTE_set1_data 3
to assign a new
.Fa obj
with type
.Em atrtype
and data
.Em data
of length
.Em len .
If the passed in attribute
.Em attr
OR
.Em *attr
is NULL then a new
.Vt X509_ATTRIBUTE
will be returned, otherwise the passed in
.Vt X509_ATTRIBUTE
is used.
Note that the ASN1_OBJECT
.Fa obj
is pushed onto the attributes existing list of objects, which could be
an issue if the attributes <ASN1_OBJECT> was different.
.Pp
.Xr X509_ATTRIBUTE_create_by_NID 3
is similar to
.Xr X509_ATTRIBUTE_create_by_OBJ 3
except that it passes the numerical identifier (NID)
.Fa nid
associated with the object.
See <openssl/obj_mac.h> for a list of NID_*.
.Pp
.Xr X509_ATTRIBUTE_create_by_txt 3
is similar to
.Xr X509_ATTRIBUTE_create_by_OBJ 3
except that it passes a name
.Em atrname
associated with the object.
See <openssl/obj_mac.h> for a list of SN_* names.
.Pp
.Xr X509_ATTRIBUTE_count 3
returns the number of
.Sy ASN1_TYPE
objects in an attribute
.Em attr .
.Pp
.Xr X509_ATTRIBUTE_get0_type 3
returns the
.Sy ASN1_TYPE
object at index
.Em idx
in the attribute list
.Em attr .
.Em idx
should be in the range of 0 to
.Xr X509_ATTRIBUTE_count 3
- 1 or an error will occur.
.Pp
.Xr X509_ATTRIBUTE_get0_data 3
returns the data of an
.Sy ASN1_TYPE
object at index
.Em idx
in the attribute
.Em attr .
.Em data
is unused and can be set to NULL. An error will occur if the attribute
type
.Em atrtype
does not match the type of the
.Sy ASN1_TYPE
object at index
.Em idx
OR if
.Em atrtype
is either
.Sy V_ASN1_BOOLEAN
or
.Sy V_ASN1_NULL
OR if the
.Em idx
is not in the range 0 to
.Xr X509_ATTRIBUTE_count 3
- 1.
.Pp
.Xr X509at_get0_data_by_OBJ 3
finds the first attribute in an attribute list
.Fa x
that matches the
.Fa obj
starting at index
.Fa lastpos
and returns the data retrieved from the found attributes first
.Sy ASN1_TYPE
object.
An error will occur if the attribute type
.Em type
does not match the type of the
.Sy ASN1_TYPE
object OR if
.Em type
is either
.Sy V_ASN1_BOOLEAN
or
.Sy V_ASN1_NULL
OR the attribute is not found.
If
.Fa lastpos
is less than -1 then an error will occur if there are multiple objects
in the list
.Fa x
that match
.Fa obj .
If
.Fa lastpos
is less than -2 then an error will occur if there is more than one
.Sy ASN1_TYPE
object in the found attribute.
.Sh RETURN VALUES
.Fn X509at_get_attr_count
returns the number of attributes in the list
.Fa x
or -1 if
.Fa x
is NULL.
.Pp
.Fn X509at_get_attr_by_OBJ
returns -1 if either the list is empty OR the object is not found,
otherwise it returns the location of the object in the list.
.Pp
.Fn X509at_get_attr_by_NID
is similar to
.Fn X509at_get_attr_by_OBJ ,
except that it returns -2 if the
.Fa nid
is not known by OpenSSL.
.Pp
.Fn X509at_get_attr
returns either an
.Vt X509_ATTRIBUTE
or NULL if there is a error.
.Pp
.Fn X509at_delete_attr
returns either the removed
.Vt X509_ATTRIBUTE
or NULL if there is a error.
.Pp
.Xr X509_ATTRIBUTE_count 3
returns -1 on error, otherwise it returns the number of
.Sy ASN1_TYPE
elements.
.Pp
.Xr X509_ATTRIBUTE_get0_type 3
returns NULL on error, otherwise it returns a
.Sy ASN1_TYPE
object.
.Pp
.Xr X509_ATTRIBUTE_get0_data 3
returns NULL if an error occurs, otherwise it returns the data
associated with an
.Sy ASN1_TYPE
object.
.Pp
.Xr X509_ATTRIBUTE_set1_object 3
and
.Xr X509_ATTRIBUTE_set1_data 3
returns 1 on success, or 0 otherwise.
.Pp
.Xr X509_ATTRIBUTE_create 3 ,
.Xr X509_ATTRIBUTE_create_by_OBJ 3 ,
.Xr X509_ATTRIBUTE_create_by_NID 3
and
.Xr X509_ATTRIBUTE_create_by_txt 3
return either a
.Vt X509_ATTRIBUTE
on success, or NULL if there is a error.
.Pp
.Xr X509at_add1_attr 3 ,
.Xr X509at_add1_attr_by_OBJ 3 ,
.Xr X509at_add1_attr_by_NID 3
and
.Xr X509at_add1_attr_by_txt 3
return NULL on error, otherwise they return a list of
.Vt X509_ATTRIBUTE .
.Pp
.Xr X509at_get0_data_by_OBJ 3
returns the data retrieved from the found attributes first
.Sy ASN1_TYPE
object, or NULL if an error occurs.
.Sh SEE ALSO
.Xr ASN1_TYPE_get 3 ,
.Xr ASN1_INTEGER_get 3 ,
.Xr ASN1_ENUMERATED_get 3 ,
.Xr ASN1_STRING_get0_data 3 ,
.Xr ASN1_STRING_length 3 ,
.Xr ASN1_STRING_type 3 ,
.Xr X509_REQ_get_attr 3 ,
.Xr EVP_PKEY_get_attr 3 ,
.Xr CMS_signed_get_attr 3 ,
.Xr PKCS8_pkey_get0_attrs 3 ,
.Sh COPYRIGHT
Copyright 2023-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
