.Dd 2025-09-30
.Dt CA.PL 1ossl
.Os
.Sh NAME
.Nm CA.pl
.Nd friendlier interface for OpenSSL certificate programs
.Sh SYNOPSIS
.Nm CA.pl
.Fl ?
|
.Fl h
|
.Fl help
.Pp
.Nm CA.pl
.Fl newcert
|
.Fl newreq
|
.Fl newreq-nodes
|
.Fl xsign
|
.Fl sign
|
.Fl signCA
|
.Fl signcert
|
.Fl crl
|
.Fl newca
.Oo
.Ar extra- Ns Em cmd
.Em parameter ]
.Pp
.Nm CA.pl
.Fl pkcs12
.Oo
.Em certname ]
.Pp
.Nm CA.pl
.Fl verify
.Em certfile
\&...
.Pp
.Nm CA.pl
.Fl revoke
.Em certfile
.Oo
.Em reason ]
.Sh DESCRIPTION
The
.Sy CA.pl
script is a perl script that supplies the relevant command line
arguments to the
.Xr openssl 1
command for some common certificate operations.
It is intended to simplify the process of certificate creation and
management by the use of some simple options.
.Pp
The script is intended as a simple front end for the
.Xr openssl 1
program for use by a beginner.
Its behaviour isn't always what is wanted.
For more control over the behaviour of the certificate commands call the
.Xr openssl 1
command directly.
.Pp
Most of the filenames mentioned below can be modified by editing the
.Sy CA.pl
script.
.Pp
Under some environments it may not be possible to run the
.Sy CA.pl
script directly (for example Win32) and the default configuration file
location may be wrong.
In this case the command:
.Bd -literal
 perl -S CA.pl
.Ed
.Pp
can be used and the
.Sy OPENSSL_CONF
environment variable can be set to point to the correct path of the
configuration file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -? Ns , Sy -h Ns , Sy -help
Prints a usage message.
.It Sy -newcert
Creates a new self signed certificate.
The private key is written to the file
.Pa newkey.pem
and the request written to the file
.Pa newreq.pem .
Invokes
.Xr openssl-req 1 .
.It Sy -newreq
Creates a new certificate request.
The private key is written to the file
.Pa newkey.pem
and the request written to the file
.Pa newreq.pem .
Executes
.Xr openssl-req 1
under the hood.
.It Sy -newreq-nodes
Is like
.Sy -newreq
except that the private key will not be encrypted.
Uses
.Xr openssl-req 1 .
.It Sy -newca
Creates a new CA hierarchy for use with the
.Sy ca
program (or the
.Sy -signcert
and
.Sy -xsign
options).
The user is prompted to enter the filename of the CA certificates (which
should also contain the private key) or by hitting ENTER details of the
CA will be prompted for.
The relevant files and directories are created in a directory called
.Pa demoCA
in the current directory.
Uses
.Xr openssl-req 1
and
.Xr openssl-ca 1 .
.Pp
If the
.Pa demoCA
directory already exists then the
.Sy -newca
command will not overwrite it and will do nothing.
This can happen if a previous call using the
.Sy -newca
option terminated abnormally.
To get the correct behaviour delete the directory if it already exists.
.It Sy -pkcs12
Create a PKCS#12 file containing the user certificate, private key and
CA certificate.
It expects the user certificate and private key to be in the file
.Pa newcert.pem
and the CA certificate to be in the file
.Pa demoCA/cacert.pem ,
it creates a file
.Pa newcert.p12 .
This command can thus be called after the
.Sy -sign
option.
The PKCS#12 file can be imported directly into a browser.
If there is an additional argument on the command line it will be used
as the "friendly name" for the certificate (which is typically displayed
in the browser list box), otherwise the name "My Certificate" is used.
Delegates work to
.Xr openssl-pkcs12 1 .
.It Sy -sign Ns , Sy -signcert Ns , Sy -xsign
Calls the
.Xr openssl-ca 1
command to sign a certificate request.
It expects the request to be in the file
.Pa newreq.pem .
The new certificate is written to the file
.Pa newcert.pem
except in the case of the
.Sy -xsign
option when it is written to standard output.
.It Sy -signCA
This option is the same as the
.Sy -sign
option except it uses the configuration file section
.Sy v3_ca
and so makes the signed request a valid CA certificate.
This is useful when creating intermediate CA from a root CA. Extra
params are passed to
.Xr openssl-ca 1 .
.It Sy -signcert
This option is the same as
.Sy -sign
except it expects a self signed certificate to be present in the file
.Pa newreq.pem .
Extra params are passed to
.Xr openssl-x509 1
and
.Xr openssl-ca 1 .
.It Sy -crl
Generate a CRL. Executes
.Xr openssl-ca 1 .
.It Sy -revoke Em certfile No [ Ns Em reason ]
Revoke the certificate contained in the specified
.Sy certfile .
An optional reason may be specified, and must be one of:
.Sy unspecified ,
.Sy keyCompromise ,
.Sy CACompromise ,
.Sy affiliationChanged ,
.Sy superseded ,
.Sy cessationOfOperation ,
.Sy certificateHold ,
or
.Sy removeFromCRL .
Leverages
.Xr openssl-ca 1 .
.It Sy -verify
Verifies certificates against the CA certificate for
.Pa demoCA .
If no certificates are specified on the command line it tries to verify
the file
.Pa newcert.pem .
Invokes
.Xr openssl-verify 1 .
.It Sy -extra- Ns Em cmd Em parameter
For each option
.Sy extra- Ns Em cmd ,
pass
.Em parameter
to the
.Xr openssl 1
sub-command with the same name as
.Em cmd ,
if that sub-command is invoked.
For example, if
.Xr openssl-req 1
is invoked, the
.Em parameter
given with
.Sy -extra-req
will be passed to it.
For multi-word parameters, either repeat the option or quote the
.Em parameters
so it looks like one word to your shell.
See the individual command documentation for more information.
.El
.Sh EXAMPLES
Create a CA hierarchy:
.Bd -literal
 CA.pl -newca
.Ed
.Pp
Complete certificate creation example: create a CA, create a request,
sign the request and finally create a PKCS#12 file containing it.
.Bd -literal
 CA.pl -newca
 CA.pl -newreq
 CA.pl -sign
 CA.pl -pkcs12 "My Test Certificate"
.Ed
.Sh ENVIRONMENT
The environment variable
.Sy OPENSSL
may be used to specify the name of the OpenSSL program.
It can be a full pathname, or a relative one.
.Pp
The environment variable
.Sy OPENSSL_CONFIG
may be used to specify a configuration option and value to the
.Sy req
and
.Sy ca
commands invoked by this script.
It's value should be the option and pathname, as in
.Qo Li -config /path/to/conf-file Qc .
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-x509 1 ,
.Xr openssl-ca 1 ,
.Xr openssl-req 1 ,
.Xr openssl-pkcs12 1 ,
.Xr config 5
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
