.Dd 2025-09-30
.Dt OPENSSL-PKCS8 1ossl
.Os
.Sh NAME
.Nm openssl-pkcs8
.Nd PKCS#8 format private key conversion command
.Sh SYNOPSIS
.Nm openssl
.Ar pkcs8
.Oo
.Fl help ]
.Oo
.Fl topk8 ]
.Oo
.Fl inform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl in
.Em filename ]
.Oo
.Fl passin
.Em arg ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl passout
.Em arg ]
.Oo
.Fl iter
.Em count ]
.Oo
.Fl noiter ]
.Oo
.Fl nocrypt ]
.Oo
.Fl traditional ]
.Oo
.Fl v2
.Em alg ]
.Oo
.Fl v2prf
.Em alg ]
.Oo
.Fl v1
.Em alg ]
.Oo
.Fl scrypt ]
.Oo
.Fl scrypt_N
.Em N ]
.Oo
.Fl scrypt_r
.Em r ]
.Oo
.Fl scrypt_p
.Em p ]
.Oo
.Fl saltlen
.Em size ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Sh DESCRIPTION
This command processes private keys in PKCS#8 format.
It can handle both unencrypted PKCS#8 PrivateKeyInfo format and
EncryptedPrivateKeyInfo format with a variety of PKCS#5 (v1.5 and v2.0)
and PKCS#12 algorithms.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -topk8
Normally a PKCS#8 private key is expected on input and a private key
will be written to the output file.
With the
.Sy -topk8
option the situation is reversed: it reads a private key and writes a
PKCS#8 format key.
.It Sy -inform Sy DER Ns | Ns Sy PEM Ns , Sy -outform Sy DER Ns | Ns Sy PEM
The input and formats; the default is
.Sy PEM .
See
.Xr openssl-format-options 1
for details.
.Pp
If a key is being converted from PKCS#8 form (i.e.
the
.Sy -topk8
option is not used) then the input file must be in PKCS#8 format.
An encrypted key is expected unless
.Sy -nocrypt
is included.
.Pp
If
.Sy -topk8
is not used and
.Sy PEM
mode is set the output file will be an unencrypted private key in PKCS#8
format.
If the
.Sy -traditional
option is used then a traditional format private key is written instead.
.Pp
If
.Sy -topk8
is not used and
.Sy DER
mode is set the output file will be an unencrypted private key in
traditional DER format.
.Pp
If
.Sy -topk8
is used then any supported private key can be used for the input file in
a format specified by
.Sy -inform .
The output file will be encrypted PKCS#8 format using the specified
encryption parameters unless
.Sy -nocrypt
is included.
.It Sy -traditional
When this option is present and
.Sy -topk8
is not a traditional format private key is written.
.It Sy -in Em filename
This specifies the input file to read a key from or standard input if
this option is not specified.
If the key is encrypted a pass phrase will be prompted for unless
.Sy -passin
is given.
.It Sy -passin Em arg Ns , Sy -passout Em arg
The password source for the input and output file.
For more information about the format of
.Sy arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -out Em filename
This specifies the output file to write a key to or standard output by
default.
The output filename can be the same as the input filename, which leads
to replacing the file contents.
Note that file I/O is not atomic.
The output file is truncated and then written.
.Pp
If any encryption options are set and
.Sy -passout
is not given then a pass phrase will be prompted for.
When password input is interrupted, the output file is not touched.
.It Sy -iter Em count
When creating new PKCS#8 containers, use a given number of iterations on
the password in deriving the encryption key for the PKCS#8 output.
High values increase the time required to brute-force a PKCS#8
container.
.It Sy -noiter
When creating new PKCS#8 containers, use 1 as iteration count.
.It Sy -nocrypt
PKCS#8 keys generated or input are normally PKCS#8
EncryptedPrivateKeyInfo structures using an appropriate password based
encryption algorithm.
With this option an unencrypted PrivateKeyInfo structure is expected or
output.
This option does not encrypt private keys at all and should only be used
when absolutely necessary.
Certain software such as some versions of Java code signing software
used unencrypted private keys.
.It Sy -v2 Em alg
This option sets the PKCS#5 v2.0 algorithm.
.Pp
The
.Em alg
argument is the encryption algorithm to use, valid values include
.Sy aes128 ,
.Sy aes256
and
.Sy des3 .
If this option isn't specified then
.Sy aes256
is used.
.It Sy -v2prf Em alg
This option sets the PRF algorithm to use with PKCS#5 v2.0. A typical
value value would be
.Sy hmacWithSHA256 .
If this option isn't set then the default for the cipher is used or
.Sy hmacWithSHA256
if there is no default.
.Pp
Some implementations may not support custom PRF algorithms and may
require the
.Sy hmacWithSHA1
option to work.
.It Sy -v1 Em alg
This option indicates a PKCS#5 v1.5 or PKCS#12 algorithm should be used.
Some older implementations may not support PKCS#5 v2.0 and may require
this option.
If not specified PKCS#5 v2.0 form is used.
.It Sy -scrypt
Uses the
.Sy scrypt
algorithm for private key encryption using default parameters: currently
N=16384, r=8 and p=1 and AES in CBC mode with a 256 bit key.
These parameters can be modified using the
.Sy -scrypt_N ,
.Sy -scrypt_r ,
.Sy -scrypt_p
and
.Sy -v2
options.
.It Sy -scrypt_N Em N Ns , Sy -scrypt_r Em r Ns , Sy -scrypt_p Em p
Sets the scrypt
.Em N ,
.Em r
or
.Em p
parameters.
.It Sy -saltlen
Sets the length (in bytes) of the salt to use for the PBE algorithm.
If this value is not specified, the default for PBES2 is 16 (128 bits)
and 8 (64 bits) for PBES1.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Sh NOTES
By default, when converting a key to PKCS#8 format, PKCS#5 v2.0 using
256 bit AES with HMAC and SHA256 is used.
.Pp
Some older implementations do not support PKCS#5 v2.0 format and require
the older PKCS#5 v1.5 form instead, possibly also requiring insecure
weak encryption algorithms such as 56 bit DES.
.Pp
Private keys encrypted using PKCS#5 v2.0 algorithms and high iteration
counts are more secure that those encrypted using the traditional SSLeay
compatible formats.
So if additional security is considered important the keys should be
converted.
.Pp
It is possible to write out DER encoded encrypted private keys in PKCS#8
format because the encryption details are included at an ASN1 level
whereas the traditional format includes them at a PEM level.
.Sh PKCS#5 V1.5 AND PKCS#12 ALGORITHMS
Various algorithms can be used with the
.Sy -v1
command line option, including PKCS#5 v1.5 and PKCS#12. These are
described in more detail below.
.Bl -tag -width Ds
.It Sy PBE-MD2-DES PBE-MD5-DES
These algorithms were included in the original PKCS#5 v1.5
specification.
They only offer 56 bits of protection since they both use DES.
.It Sy PBE-SHA1-RC2-64 Ns , Sy PBE-MD2-RC2-64 Ns , Sy PBE-MD5-RC2-64 Ns , Sy PBE-SHA1-DES
These algorithms are not mentioned in the original PKCS#5 v1.5
specification but they use the same key derivation algorithm and are
supported by some software.
They are mentioned in PKCS#5 v2.0. They use either 64 bit RC2 or 56 bit
DES.
.It Sy PBE-SHA1-RC4-128 Ns , Sy PBE-SHA1-RC4-40 Ns , Sy PBE-SHA1-3DES Ns , Sy PBE-SHA1-2DES Ns , Sy PBE-SHA1-RC2-128 Ns , Sy PBE-SHA1-RC2-40
These algorithms use the PKCS#12 password based encryption algorithm and
allow strong encryption algorithms like triple DES or 128 bit RC2 to be
used.
.El
.Sh EXAMPLES
Convert a private key to PKCS#8 format using default parameters (AES
with 256 bit key and
.Sy hmacWithSHA256 Ns ):
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -out enckey.pem
.Ed
.Pp
Convert a private key to PKCS#8 unencrypted format:
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -nocrypt -out enckey.pem
.Ed
.Pp
Convert a private key to PKCS#5 v2.0 format using triple DES:
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -v2 des3 -out enckey.pem
.Ed
.Pp
Convert a private key to PKCS#5 v2.0 format using AES with 256 bits in
CBC mode and
.Sy hmacWithSHA512
PRF:
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -v2 aes-256-cbc -v2prf hmacWithSHA512 -out enckey.pem
.Ed
.Pp
Convert a private key to PKCS#8 using a PKCS#5 1.5 compatible algorithm
(DES):
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -v1 PBE-MD5-DES -out enckey.pem
.Ed
.Pp
Convert a private key to PKCS#8 using a PKCS#12 compatible algorithm
(3DES):
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -out enckey.pem -v1 PBE-SHA1-3DES
.Ed
.Pp
Read a DER unencrypted PKCS#8 format private key:
.Bd -literal
 openssl pkcs8 -inform DER -nocrypt -in key.der -out key.pem
.Ed
.Pp
Convert a private key from any PKCS#8 encrypted format to traditional
format:
.Bd -literal
 openssl pkcs8 -in pk8.pem -traditional -out key.pem
.Ed
.Pp
Convert a private key to PKCS#8 format, encrypting with AES-256 and with
one million iterations of the password:
.Bd -literal
 openssl pkcs8 -in key.pem -topk8 -v2 aes-256-cbc -iter 1000000 -out pk8.pem
.Ed
.Sh STANDARDS
Test vectors from this PKCS#5 v2.0 implementation were posted to the
pkcs-tng mailing list using triple DES, DES and RC2 with high iteration
counts, several people confirmed that they could decrypt the private
keys produced and therefore, it can be assumed that the PKCS#5 v2.0
implementation is reasonably accurate at least as far as these
algorithms are concerned.
.Pp
The format of PKCS#8 DSA (and other) private keys is not well
documented: it is hidden away in PKCS#11 v2.01, section 11.9. OpenSSL's
default DSA PKCS#8 private key format complies with this standard.
.Sh BUGS
There should be an option that prints out the encryption algorithm in
use and other details such as the iteration count.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-dsa 1 ,
.Xr openssl-rsa 1 ,
.Xr openssl-genrsa 1 ,
.Xr openssl-gendsa 1
.Sh HISTORY
The
.Sy -iter
option was added in OpenSSL 1.1.0.
.Pp
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
