.Dd 2025-09-30
.Dt OPENSSL-GENPKEY 1ossl
.Os
.Sh NAME
.Nm openssl-genpkey
.Nd generate a private key or key pair
.Sh SYNOPSIS
.Nm openssl
.Ar genpkey
.Oo
.Fl help ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl outpubkey
.Em filename ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl verbose ]
.Oo
.Fl quiet ]
.Oo
.Fl pass
.Em arg ]
.Oo
.Ar Em cipher ]
.Oo
.Fl paramfile
.Em file ]
.Oo
.Fl algorithm
.Em alg ]
.Oo
.Fl pkeyopt
.Em opt Ns : Ns Em value ]
.Oo
.Fl genparam ]
.Oo
.Fl text ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl engine
.Em id ]
.Pp
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Fl config
.Em configfile ]
.Sh DESCRIPTION
This command generates a private key or key pair.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -out Em filename
Output the private key to the specified file.
If this argument is not specified then standard output is used.
.It Sy -outpubkey Em filename
Output the public key to the specified file.
If this argument is not specified then the public key is not output.
.It Sy -outform Sy DER Ns | Ns Sy PEM
The output format, except when
.Sy -genparam
is given; the default is
.Sy PEM .
See
.Xr openssl-format-options 1
for details.
.Pp
When
.Sy -genparam
is given,
.Sy -outform
is ignored.
.It Sy -verbose
Output "status dots" while generating keys.
.It Sy -quiet
Do not output "status dots" while generating keys.
.It Sy -pass Em arg
The output file password source.
For more information about the format of
.Em arg
see
.Xr openssl-passphrase-options 1 .
.It Sy - Ns Em cipher
This option encrypts the private key with the supplied cipher.
Any algorithm name accepted by
.Xr EVP_get_cipherbyname 3
is acceptable such as
.Sy des3 .
.It Sy -algorithm Em alg
Public key algorithm to use such as RSA, DSA, DH or DHX. If used this
option must precede any
.Sy -pkeyopt
options.
The options
.Sy -paramfile
and
.Sy -algorithm
are mutually exclusive.
Engines or providers may add algorithms in addition to the standard
built-in ones.
.Pp
Valid built-in algorithm names for private key generation are RSA,
RSA-PSS, EC, X25519, X448, ED25519, ED448, ML-DSA and ML-KEM.
.Pp
Valid built-in algorithm names for parameter generation (see the
.Sy -genparam
option) are DH, DSA and EC.
.Pp
Note that the algorithm name X9.42 DH may be used as a synonym for DHX
keys and PKCS#3 refers to DH Keys.
Some options are not shared between DH and DHX keys.
.It Sy -pkeyopt Em opt Ns : Ns Em value
Set the public key algorithm option
.Em opt
to
.Em value .
The precise set of options supported depends on the public key algorithm
used and its implementation.
See
.Sx KEY GENERATION OPTIONS
and
.Sx PARAMETER GENERATION OPTIONS
below for more details.
.Pp
To list the possible
.Em opt
values for an algorithm use:
.Sy openssl
.Sy genpkey
-algorithm XXX -help
.It Sy -genparam
Generate a set of parameters instead of a private key.
If used this option must precede any
.Sy -algorithm ,
.Sy -paramfile
or
.Sy -pkeyopt
options.
.It Sy -paramfile Em filename
Some public key algorithms generate a private key based on a set of
parameters.
They can be supplied using this option.
If this option is used the public key algorithm used is determined by
the parameters.
If used this option must precede any
.Sy -pkeyopt
options.
The options
.Sy -paramfile
and
.Sy -algorithm
are mutually exclusive.
.It Sy -text
Print an (unencrypted) text representation of private and public keys
and parameters along with the PEM or DER structure.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -config Em configfile
See
.Xr openssl 1 .
.El
.Sh KEY GENERATION OPTIONS
The options supported by each algorithm and indeed each implementation
of an algorithm can vary.
The options for the OpenSSL implementations are detailed below.
There are no key generation options defined for the X25519, X448,
ED25519 or ED448 algorithms.
.Ss RSA Key Generation Options
.Bl -tag -width Ds
.It Sy rsa_keygen_bits:numbits
The number of bits in the generated key.
If not specified 2048 is used.
.It Sy rsa_keygen_primes:numprimes
The number of primes in the generated key.
If not specified 2 is used.
.It Sy rsa_keygen_pubexp:value
The RSA public exponent value.
This can be a large decimal or hexadecimal value if preceded by
.Qo Li 0x Qc .
Default value is 65537.
.El
.Ss RSA-PSS Key Generation Options
Note: by default an
.Sy RSA-PSS
key has no parameter restrictions.
.Bl -tag -width Ds
.It Sy rsa_keygen_bits Ns : Ns Em numbits Ns , Sy rsa_keygen_primes Ns : Ns Em numprimes Ns , Sy rsa_keygen_pubexp Ns : Ns Em value
These options have the same meaning as the
.Sy RSA
algorithm.
.It Sy rsa_pss_keygen_md Ns : Ns Em digest
If set the key is restricted and can only use
.Em digest
for signing.
.It Sy rsa_pss_keygen_mgf1_md Ns : Ns Em digest
If set the key is restricted and can only use
.Em digest
as it's MGF1 parameter.
.It Sy rsa_pss_keygen_saltlen Ns : Ns Em len
If set the key is restricted and
.Em len
specifies the minimum salt length.
.El
.Ss EC Key Generation Options
The EC key generation options can also be used for parameter generation.
.Bl -tag -width Ds
.It Sy ec_paramgen_curve Ns : Ns Em curve
The EC curve to use.
OpenSSL supports NIST curve names such as "P-256".
.It Sy ec_param_enc Ns : Ns Em encoding
The encoding to use for parameters.
The
.Em encoding
parameter must be either
.Sy named_curve
or
.Sy explicit .
The default value is
.Sy named_curve .
.El
.Ss ML-DSA Key Generation Options
.Bl -tag -width Ds
.It Sy hexseed Ns : Ns Em seed
This specifies the optional ML-DSA
.Em seed
in hexadecimal form.
The seed is 32 bytes, giving 64 hexadecimal digits.
When generated from an explicit seed the key is completely determined by
the seed value.
If other users can see the command-line arguments of the running
process, this option may compromise the secret key, it is best avoided,
tests-aside.
.Pp
See
.Xr EVP_PKEY-ML-DSA 7
for more detail.
.El
.Ss ML-KEM Key Generation Options
.Bl -tag -width Ds
.It Sy hexseed Ns : Ns Em seed
This specifies the optional ML-KEM
.Em seed
in hexadecimal form.
The seed is 64 bytes, giving 128 hexadecimal digits.
When generated from an explicit seed the key is completely determined by
the seed value.
If other users can see the command-line arguments of the running
process, this option may compromise the secret key, it is best avoided,
tests-aside.
.Pp
See
.Xr EVP_PKEY-ML-KEM 7
for more detail.
.El
.Ss DH Key Generation Options
.Bl -tag -width Ds
.It Sy group Ns : Ns Em name
The
.Sy paramfile
option is not required if a named group is used here.
See the
.Sx DH Parameter Generation Options
section below.
.El
.Sh PARAMETER GENERATION OPTIONS
The options supported by each algorithm and indeed each implementation
of an algorithm can vary.
The options for the OpenSSL implementations are detailed below.
.Ss DSA Parameter Generation Options
.Bl -tag -width Ds
.It Sy dsa_paramgen_bits Ns : Ns Em numbits
The number of bits in the generated prime.
If not specified 2048 is used.
.It Sy dsa_paramgen_q_bits Ns : Ns Em numbits
.It Sy qbits Ns : Ns Em numbits
The number of bits in the q parameter.
Must be one of 160, 224 or 256. If not specified 224 is used.
.It Sy dsa_paramgen_md Ns : Ns Em digest
.It Sy digest Ns : Ns Em digest
The digest to use during parameter generation.
Must be one of
.Sy sha1 ,
.Sy sha224
or
.Sy sha256 .
If set, then the number of bits in
.Sy q
will match the output size of the specified digest and the
.Sy dsa_paramgen_q_bits
parameter will be ignored.
If not set, then a digest will be used that gives an output matching the
number of bits in
.Sy q ,
i.e.
.Sy sha1
if q length is 160,
.Sy sha224
if it 224 or
.Sy sha256
if it is 256.
.It Sy properties Ns : Ns Em query
The
.Em digest
property
.Em query
string to use when fetching a digest from a provider.
.It Sy type Ns : Ns Em type
The type of generation to use.
Set this to 1 to use legacy FIPS186-2 parameter generation.
The default of 0 uses FIPS186-4 parameter generation.
.It Sy gindex Ns : Ns Em index
The index to use for canonical generation and verification of the
generator g. Set this to a positive value ranging from 0..255 to use
this mode.
Larger values will only use the bottom byte.
This
.Em index
must then be reused during key validation to verify the value of g. If
this value is not set then g is not verifiable.
The default value is -1.
.It Sy hexseed Ns : Ns Em seed
The seed
.Em seed
data to use instead of generating a random seed internally.
This should be used for testing purposes only.
This will either produced fixed values for the generated parameters OR
it will fail if the seed did not generate valid primes.
.El
.Ss DH Parameter Generation Options
For most use cases it is recommended to use the
.Sy group
option rather than the
.Sy type
options.
Note that the
.Sy group
option is not used by default if no parameter generation options are
specified.
.Bl -tag -width Ds
.It Sy group Ns : Ns Em name
.It Sy dh_param Ns : Ns Em name
Use a named DH group to select constant values for the DH parameters.
All other options will be ignored if this value is set.
.Pp
Valid values that are associated with the
.Sy algorithm
of
.Sy \(dqDH"
are: "ffdhe2048", "ffdhe3072", "ffdhe4096", "ffdhe6144", "ffdhe8192",
"modp_1536", "modp_2048", "modp_3072", "modp_4096", "modp_6144",
"modp_8192".
.Pp
Valid values that are associated with the
.Sy algorithm
of
.Sy \(dqDHX"
are the RFC5114 names "dh_1024_160", "dh_2048_224", "dh_2048_256".
.It Sy dh_rfc5114 Ns : Ns Em num
If this option is set, then the appropriate RFC5114 parameters are used
instead of generating new parameters.
The value
.Em num
can be one of 1, 2 or 3 that are equivalent to using the option
.Sy group
with one of "dh_1024_160", "dh_2048_224" or "dh_2048_256". All other
options will be ignored if this value is set.
.It Sy pbits Ns : Ns Em numbits
.It Sy dh_paramgen_prime_len Ns : Ns Em numbits
The number of bits in the prime parameter
.Em p .
The default is 2048.
.It Sy qbits Ns : Ns Em numbits
.It Sy dh_paramgen_subprime_len Ns : Ns Em numbits
The number of bits in the sub prime parameter
.Em q .
The default is 224. Only relevant if used in conjunction with the
.Sy dh_paramgen_type
option to generate DHX parameters.
.It Sy safeprime-generator Ns : Ns Em value
.It Sy dh_paramgen_generator Ns : Ns Em value
The value to use for the generator
.Em g .
The default is 2. The
.Sy algorithm
option must be
.Sy \(dqDH"
for this parameter to be used.
.It Sy type Ns : Ns Em string
The type name of DH parameters to generate.
Valid values are:
.Bl -tag -width Ds
.It \(dqgenerator"
Use a safe prime generator with the option
.Sy safeprime_generator
The
.Sy algorithm
option must be
.Sy \(dqDH" .
.It \(dqfips186_4"
FIPS186-4 parameter generation.
The
.Sy algorithm
option must be
.Sy \(dqDHX" .
.It \(dqfips186_2"
FIPS186-4 parameter generation.
The
.Sy algorithm
option must be
.Sy \(dqDHX" .
.It \(dqgroup"
Can be used with the option
.Sy pbits
to select one of "ffdhe2048", "ffdhe3072", "ffdhe4096", "ffdhe6144" or
"ffdhe8192". The
.Sy algorithm
option must be
.Sy \(dqDH" .
.It \(dqdefault"
Selects a default type based on the
.Sy algorithm .
This is used by the OpenSSL default provider to set the type for
backwards compatibility.
If
.Sy algorithm
is
.Sy \(dqDH"
then
.Sy \(dqgenerator"
is used.
If
.Sy algorithm
is
.Sy \(dqDHX"
then
.Sy \(dqfips186_2"
is used.
.El
.It Sy dh_paramgen_type Ns : Ns Em value
The type of DH parameters to generate.
Valid values are 0, 1, 2 or 3 which correspond to setting the option
.Sy type
to "generator", "fips186_2", "fips186_4" or "group".
.It Sy digest Ns : Ns Em digest
The digest to use during parameter generation.
Must be one of
.Sy sha1 ,
.Sy sha224
or
.Sy sha256 .
If set, then the number of bits in
.Sy qbits
will match the output size of the specified digest and the
.Sy qbits
parameter will be ignored.
If not set, then a digest will be used that gives an output matching the
number of bits in
.Sy q ,
i.e.
.Sy sha1
if q length is 160,
.Sy sha224
if it is 224 or
.Sy sha256
if it is 256. This is only used by "fips186_4" and "fips186_2" key
generation.
.It Sy properties Ns : Ns Em query
The
.Em digest
property
.Em query
string to use when fetching a digest from a provider.
This is only used by "fips186_4" and "fips186_2" key generation.
.It Sy gindex Ns : Ns Em index
The index to use for canonical generation and verification of the
generator g. Set this to a positive value ranging from 0..255 to use
this mode.
Larger values will only use the bottom byte.
This
.Em index
must then be reused during key validation to verify the value of g. If
this value is not set then g is not verifiable.
The default value is -1. This is only used by "fips186_4" and
"fips186_2" key generation.
.It Sy hexseed Ns : Ns Em seed
The seed
.Em seed
data to use instead of generating a random seed internally.
This should be used for testing purposes only.
This will either produced fixed values for the generated parameters OR
it will fail if the seed did not generate valid primes.
This is only used by "fips186_4" and "fips186_2" key generation.
.El
.Ss EC Parameter Generation Options
The EC parameter generation options are the same as for key generation.
See
.Sx EC Key Generation Options
above.
.Sh NOTES
The use of the genpkey program is encouraged over the algorithm specific
utilities because additional algorithm options and ENGINE provided
algorithms can be used.
.Sh EXAMPLES
Generate an RSA private key using default parameters:
.Bd -literal
 openssl genpkey -algorithm RSA -out key.pem
.Ed
.Pp
Encrypt output private key using 128 bit AES and the passphrase "hello":
.Bd -literal
 openssl genpkey -algorithm RSA -out key.pem -aes-128-cbc -pass pass:hello
.Ed
.Pp
Generate a 2048 bit RSA key using 3 as the public exponent:
.Bd -literal
 openssl genpkey -algorithm RSA -out key.pem \e
     -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:3
.Ed
.Pp
Generate 2048 bit DSA parameters that can be validated: The output
values for gindex and seed are required for key validation purposes and
are not saved to the output pem file).
.Bd -literal
 openssl genpkey -genparam -algorithm DSA -out dsap.pem -pkeyopt pbits:2048 \e
     -pkeyopt qbits:224 -pkeyopt digest:SHA256 -pkeyopt gindex:1 -text
.Ed
.Pp
Generate DSA key from parameters:
.Bd -literal
 openssl genpkey -paramfile dsap.pem -out dsakey.pem
.Ed
.Pp
Generate 4096 bit DH Key using safe prime group ffdhe4096:
.Bd -literal
 openssl genpkey -algorithm DH -out dhkey.pem -pkeyopt group:ffdhe4096
.Ed
.Pp
Generate 2048 bit X9.42 DH key with 256 bit subgroup using RFC5114
group3:
.Bd -literal
 openssl genpkey -algorithm DHX -out dhkey.pem -pkeyopt dh_rfc5114:3
.Ed
.Pp
Generate a DH key using a DH parameters file:
.Bd -literal
 openssl genpkey -paramfile dhp.pem -out dhkey.pem
.Ed
.Pp
Output DH parameters for safe prime group ffdhe2048:
.Bd -literal
 openssl genpkey -genparam -algorithm DH -out dhp.pem -pkeyopt group:ffdhe2048
.Ed
.Pp
Output 2048 bit X9.42 DH parameters with 224 bit subgroup using RFC5114
group2:
.Bd -literal
 openssl genpkey -genparam -algorithm DHX -out dhp.pem -pkeyopt dh_rfc5114:2
.Ed
.Pp
Output 2048 bit X9.42 DH parameters with 224 bit subgroup using FIP186-4
keygen:
.Bd -literal
 openssl genpkey -genparam -algorithm DHX -out dhp.pem -text \e
     -pkeyopt pbits:2048 -pkeyopt qbits:224 -pkeyopt digest:SHA256 \e
     -pkeyopt gindex:1 -pkeyopt dh_paramgen_type:2
.Ed
.Pp
Output 1024 bit X9.42 DH parameters with 160 bit subgroup using FIP186-2
keygen:
.Bd -literal
 openssl genpkey -genparam -algorithm DHX -out dhp.pem -text \e
     -pkeyopt pbits:1024 -pkeyopt qbits:160 -pkeyopt digest:SHA1 \e
     -pkeyopt gindex:1 -pkeyopt dh_paramgen_type:1
.Ed
.Pp
Output 2048 bit DH parameters:
.Bd -literal
 openssl genpkey -genparam -algorithm DH -out dhp.pem \e
     -pkeyopt dh_paramgen_prime_len:2048
.Ed
.Pp
Output 2048 bit DH parameters using a generator:
.Bd -literal
 openssl genpkey -genparam -algorithm DH -out dhpx.pem \e
     -pkeyopt dh_paramgen_prime_len:2048 \e
     -pkeyopt dh_paramgen_type:1
.Ed
.Pp
Generate EC parameters:
.Bd -literal
 openssl genpkey -genparam -algorithm EC -out ecp.pem \e
        -pkeyopt ec_paramgen_curve:secp384r1 \e
        -pkeyopt ec_param_enc:named_curve
.Ed
.Pp
Generate EC key from parameters:
.Bd -literal
 openssl genpkey -paramfile ecp.pem -out eckey.pem
.Ed
.Pp
Generate EC key directly:
.Bd -literal
 openssl genpkey -algorithm EC -out eckey.pem \e
        -pkeyopt ec_paramgen_curve:P-384 \e
        -pkeyopt ec_param_enc:named_curve
.Ed
.Pp
Generate an X25519 private key:
.Bd -literal
 openssl genpkey -algorithm X25519 -out xkey.pem
.Ed
.Pp
Generate an ED448 private key:
.Bd -literal
 openssl genpkey -algorithm ED448 -out xkey.pem
.Ed
.Pp
Generate an ML-DSA-65 private key:
.Bd -literal
 openssl genpkey -algorithm ML-DSA-65 -out ml-dsa-key.pem
.Ed
.Pp
Generate an ML-KEM-768 private key:
.Bd -literal
 openssl genpkey -algorithm ML-KEM-768 -out ml-kem-key.pem
.Ed
.Sh HISTORY
The ability to use NIST curve names, and to generate an EC key directly,
were added in OpenSSL 1.0.2. The ability to generate X25519 keys was
added in OpenSSL 1.1.0. The ability to generate X448, ED25519 and ED448
keys was added in OpenSSL 1.1.1.
.Pp
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Pp
Support for
.Sy ML-DSA
and
.Sy ML-KEM
was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2006-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
