.Dd 2025-09-30
.Dt OPENSSL-NSEQ 1ossl
.Os
.Sh NAME
.Nm openssl-nseq
.Nd create or examine a Netscape certificate sequence
.Sh SYNOPSIS
.Nm openssl
.Ar nseq
.Oo
.Fl help ]
.Oo
.Fl in
.Em filename ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl toseq ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Sh DESCRIPTION
This command takes a file containing a Netscape certificate sequence and
prints out the certificates contained in it or takes a file of
certificates and converts it into a Netscape certificate sequence.
.Pp
A Netscape certificate sequence is an old Netscape-specific format that
can be sometimes be sent to browsers as an alternative to the standard
PKCS#7 format when several certificates are sent to the browser, for
example during certificate enrollment.
It was also used by Netscape certificate server.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -in Em filename
This specifies the input filename to read or standard input if this
option is not specified.
.It Sy -out Em filename
Specifies the output filename or standard output by default.
.It Sy -toseq
Normally a Netscape certificate sequence will be input and the output is
the certificates contained in it.
With the
.Sy -toseq
option the situation is reversed: a Netscape certificate sequence is
created from a file of certificates.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Sh EXAMPLES
Output the certificates in a Netscape certificate sequence
.Bd -literal
 openssl nseq -in nseq.pem -out certs.pem
.Ed
.Pp
Create a Netscape certificate sequence
.Bd -literal
 openssl nseq -in certs.pem -toseq -out nseq.pem
.Ed
.Sh COPYRIGHT
Copyright 2000-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
