.Dd 2025-09-30
.Dt OPENSSL-DHPARAM 1ossl
.Os
.Sh NAME
.Nm openssl-dhparam
.Nd DH parameter manipulation and generation
.Sh SYNOPSIS
.Nm openssl dhparam
.Oo
.Fl help ]
.Oo
.Fl inform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl in
.Em filename ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl dsaparam ]
.Oo
.Fl check ]
.Oo
.Fl noout ]
.Oo
.Fl text ]
.Oo
.Fl verbose ]
.Oo
.Fl quiet ]
.Oo
.Fl 2 ]
.Oo
.Fl 3 ]
.Oo
.Fl 5 ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Em numbits ]
.Sh DESCRIPTION
This command is used to manipulate DH parameter files.
.Pp
See
.Xr openssl-genpkey 1
for examples on how to generate a key using a named safe prime group
without generating intermediate parameters.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -inform Sy DER Ns | Ns Sy PEM Ns , Sy -outform Sy DER Ns | Ns Sy PEM
The input format and output format; the default is
.Sy PEM .
The object is compatible with the PKCS#3
.Sy DHparameter
structure.
See
.Xr openssl-format-options 1
for details.
.It Sy -in Em filename
This specifies the input file to read parameters from or standard input
if this option is not specified.
.It Sy -out Em filename
This specifies the output file to write parameters to.
Standard output is used if this option is not present.
The output filename can be the same as the input filename, which leads
to replacing the file contents.
Note that file I/O is not atomic.
The output file is truncated and then written.
.It Sy -dsaparam
If this option is used, DSA rather than DH parameters are read or
created; they are converted to DH format.
Otherwise, safe primes (such that (p-1)/2 is also prime) will be used
for DH parameter generation.
.Pp
DH parameter generation with the
.Sy -dsaparam
option is much faster.
Beware that with such DSA-style DH parameters, a fresh DH key should be
created for each use to avoid small-subgroup attacks that may be
possible otherwise.
.It Sy -check
Performs numerous checks to see if the supplied parameters are valid and
displays a warning if not.
.It Sy -2 Ns , Sy -3 Ns , Sy -5
The generator to use, either 2, 3 or 5. If present then the input file
is ignored and parameters are generated instead.
If not present but
.Em numbits
is present, parameters are generated with the default generator 2.
.It Em numbits
This option specifies that a parameter set should be generated of size
.Em numbits .
It must be the last option.
If this option is present then the input file is ignored and parameters
are generated instead.
If this option is not present but a generator
.Pf ( Sy -2 ,
.Sy -3
or
.Sy -5 )
is present, parameters are generated with a default length of 2048 bits.
The minimum length is 512 bits.
The maximum length is 10000 bits.
.It Sy -noout
This option inhibits the output of the encoded version of the
parameters.
.It Sy -text
This option prints out the DH parameters in human readable form.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -verbose
This option enables the output of progress messages, which is handy when
running commands interactively that may take a long time to execute.
.It Sy -quiet
This option suppresses the output of progress messages, which may be
undesirable in batch scripts or pipelines.
.El
.Sh NOTES
This command replaces the
.Sy dh
and
.Sy gendh
commands of previous releases.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-pkeyparam 1 ,
.Xr openssl-dsaparam 1 ,
.Xr openssl-genpkey 1 .
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Pp
The
.Sy -C
option was removed in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
