.Dd 2025-09-30
.Dt OPENSSL-DSAPARAM 1ossl
.Os
.Sh NAME
.Nm openssl-dsaparam
.Nd DSA parameter manipulation and generation
.Sh SYNOPSIS
.Nm openssl dsaparam
.Oo
.Fl help ]
.Oo
.Fl inform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl in
.Em filename ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl noout ]
.Oo
.Fl text ]
.Oo
.Fl genkey ]
.Oo
.Fl verbose ]
.Oo
.Fl quiet ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Em numbits ]
.Oo
.Em numqbits ]
.Sh DESCRIPTION
This command is used to manipulate or generate DSA parameter files.
.Pp
DSA parameter generation can be a slow process and as a result the same
set of DSA parameters is often used to generate several distinct keys.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -inform Sy DER Ns | Ns Sy PEM
The DSA parameters input format; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -outform Sy DER Ns | Ns Sy PEM
The DSA parameters output format; the default is
.Sy PEM .
See
.Xr openssl-format-options 1
for details.
.Pp
Parameters are a sequence of
.Sy ASN.1 INTEGER Ns s:
.Sy p ,
.Sy q ,
and
.Sy g .
This is compatible with RFC 2459
.Sy DSS-Parms
structure.
.It Sy -in Em filename
This specifies the input file to read parameters from or standard input
if this option is not specified.
If the
.Em numbits
parameter is included then this option will be ignored.
.It Sy -out Em filename
This specifies the output file to write parameters to.
Standard output is used if this option is not present.
The output filename can be the same as the input filename, which leads
to replacing the file contents.
Note that file I/O is not atomic.
The output file is truncated and then written.
.It Sy -noout
This option inhibits the output of the encoded version of the
parameters.
.It Sy -text
This option prints out the DSA parameters in human readable form.
.It Sy -genkey
This option will generate a DSA either using the specified or generated
parameters.
.It Sy -verbose
Print extra details about the operations being performed.
.It Sy -quiet
Print fewer details about the operations being performed, which may be
handy during batch scripts and pipelines.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Em numbits
This optional argument specifies that a parameter set should be
generated of size
.Em numbits .
If this argument is included then the input file (if any) is ignored.
.It Em numqbits
This optional argument specifies that a parameter set should be
generated with a subprime parameter q of size
.Em numqbits .
It must be the last argument.
If this argument is included then the input file (if any) is ignored.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-pkeyparam 1 ,
.Xr openssl-gendsa 1 ,
.Xr openssl-dsa 1 ,
.Xr openssl-genrsa 1 ,
.Xr openssl-rsa 1
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Pp
The
.Sy -C
option was removed in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
