.Dd 2025-09-30
.Dt OPENSSL-CMS 1ossl
.Os
.Sh NAME
.Nm openssl-cms
.Nd CMS command
.Sh SYNOPSIS
.Nm openssl
.Ar cms
.Oo
.Fl help ]
.Pp
General options:
.Pp
.Oo
.Fl in
.Em filename ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl config
.Em configfile ]
.Pp
Operation options:
.Pp
.Oo
.Fl encrypt ]
.Oo
.Fl decrypt ]
.Oo
.Fl sign ]
.Oo
.Fl verify ]
.Oo
.Fl resign ]
.Oo
.Fl sign_receipt ]
.Oo
.Fl verify_receipt
.Em receipt ]
.Oo
.Fl digest
.Em digest ]
.Oo
.Fl digest_create ]
.Oo
.Fl digest_verify ]
.Oo
.Fl compress ]
.Oo
.Fl uncompress ]
.Oo
.Fl EncryptedData_encrypt ]
.Oo
.Fl EncryptedData_decrypt ]
.Oo
.Fl data_create ]
.Oo
.Fl data_out ]
.Oo
.Fl cmsout ]
.Pp
File format options:
.Pp
.Oo
.Fl inform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar SMIME ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar SMIME ]
.Oo
.Fl rctform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar SMIME ]
.Oo
.Fl stream ]
.Oo
.Fl indef ]
.Oo
.Fl noindef ]
.Oo
.Fl binary ]
.Oo
.Fl crlfeol ]
.Oo
.Fl asciicrlf ]
.Pp
Keys and password options:
.Pp
.Oo
.Fl pwri_password
.Em password ]
.Oo
.Fl secretkey
.Em key ]
.Oo
.Fl secretkeyid
.Em id ]
.Oo
.Fl inkey
.Em filename Ns | Ns Em uri ]
.Oo
.Fl passin
.Em arg ]
.Oo
.Fl keyopt
.Em name Ns : Ns Em parameter ]
.Oo
.Fl keyform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar P12 Ns | Ns Ar ENGINE ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Pp
Encryption options:
.Pp
.Oo
.Fl originator
.Em file ]
.Oo
.Fl recip
.Em file ]
.Oo
.Em recipient-cert
.Oc
\&...
.Oo
.Ar Em cipher ]
.Oo
.Fl wrap
.Em cipher ]
.Oo
.Fl aes128-wrap ]
.Oo
.Fl aes192-wrap ]
.Oo
.Fl aes256-wrap ]
.Oo
.Fl des3-wrap ]
.Oo
.Fl debug_decrypt ]
.Pp
Signing options:
.Pp
.Oo
.Fl md
.Em digest ]
.Oo
.Fl signer
.Em file ]
.Oo
.Fl certfile
.Em file ]
.Oo
.Fl cades ]
.Oo
.Fl nodetach ]
.Oo
.Fl nocerts ]
.Oo
.Fl noattr ]
.Oo
.Fl nosmimecap ]
.Oo
.Fl no_signing_time ]
.Oo
.Fl receipt_request_all ]
.Oo
.Fl receipt_request_first ]
.Oo
.Fl receipt_request_from
.Em emailaddress ]
.Oo
.Fl receipt_request_to
.Em emailaddress ]
.Pp
Verification options:
.Pp
.Oo
.Fl signer
.Em file ]
.Oo
.Fl content
.Em filename ]
.Oo
.Fl no_content_verify ]
.Oo
.Fl no_attr_verify ]
.Oo
.Fl nosigs ]
.Oo
.Fl noverify ]
.Oo
.Fl nointern ]
.Oo
.Fl cades ]
.Oo
.Fl verify_retcode ]
.Oo
.Fl CAfile
.Em file ]
.Oo
.Fl no-CAfile ]
.Oo
.Fl CApath
.Em dir ]
.Oo
.Fl no-CApath ]
.Oo
.Fl CAstore
.Em uri ]
.Oo
.Fl no-CAstore ]
.Pp
Output options:
.Pp
.Oo
.Fl keyid ]
.Oo
.Fl econtent_type
.Em type ]
.Oo
.Fl text ]
.Oo
.Fl certsout
.Em file ]
.Oo
.Fl to
.Em addr ]
.Oo
.Fl from
.Em addr ]
.Oo
.Fl subject
.Em subj ]
.Pp
Printing options:
.Pp
.Oo
.Fl noout ]
.Oo
.Fl print ]
.Oo
.Fl nameopt
.Em option ]
.Oo
.Fl receipt_request_print ]
.Pp
Validation options:
.Pp
.Oo
.Fl allow_proxy_certs ]
.Oo
.Fl attime
.Em timestamp ]
.Oo
.Fl no_check_time ]
.Oo
.Fl check_ss_sig ]
.Oo
.Fl crl_check ]
.Oo
.Fl crl_check_all ]
.Oo
.Fl explicit_policy ]
.Oo
.Fl extended_crl ]
.Oo
.Fl ignore_critical ]
.Oo
.Fl inhibit_any ]
.Oo
.Fl inhibit_map ]
.Oo
.Fl partial_chain ]
.Oo
.Fl policy
.Em arg ]
.Oo
.Fl policy_check ]
.Oo
.Fl policy_print ]
.Oo
.Fl purpose
.Em purpose ]
.Oo
.Fl suiteB_128 ]
.Oo
.Fl suiteB_128_only ]
.Oo
.Fl suiteB_192 ]
.Oo
.Fl trusted_first ]
.Oo
.Fl no_alt_chains ]
.Oo
.Fl use_deltas ]
.Oo
.Fl auth_level
.Em num ]
.Oo
.Fl verify_depth
.Em num ]
.Oo
.Fl verify_email
.Em email ]
.Oo
.Fl verify_hostname
.Em hostname ]
.Oo
.Fl verify_ip
.Em ip ]
.Oo
.Fl verify_name
.Em name ]
.Oo
.Fl x509_strict ]
.Oo
.Fl issuer_checks ]
.Sh DESCRIPTION
This command handles data in CMS format such as S/MIME v3.1 email
messages.
It can encrypt, decrypt, sign, verify, compress, uncompress, and print
messages.
.Sh OPTIONS
There are a number of operation options that set the type of operation
to be performed: encrypt, decrypt, sign, verify, resign, sign_receipt,
verify_receipt, digest_create, digest_verify, compress, uncompress,
EncryptedData_encrypt, EncryptedData_decrypt, data_create, data_out, or
cmsout.
The relevance of the other options depends on the operation type and
their meaning may vary according to it.
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.El
.Ss General options
.Bl -tag -width Ds
.It Sy -in Em filename
The input message to be encrypted or signed or the message to be
decrypted or verified.
.It Sy -out Em filename
The message text that has been decrypted or verified or the output MIME
format message that has been signed or verified.
.It Sy -config Em configfile
See
.Xr openssl 1 .
.El
.Ss Operation options
.Bl -tag -width Ds
.It Sy -encrypt
Encrypt data for the given recipient certificates.
Input file is the message to be encrypted.
The output file is the encrypted data in MIME format.
The actual CMS type is
.Sy EnvelopedData .
.Pp
Note that no revocation check is done for the recipient cert, so if that
key has been compromised, others may be able to decrypt the text.
.It Sy -decrypt
Decrypt data using the supplied certificate and private key.
Expects encrypted datain MIME format for the input file.
The decrypted data is written to the output file.
.It Sy -sign
Sign data using the supplied certificate and private key.
Input file is the message to be signed.
The signed data in MIME format is written to the output file.
.It Sy -verify
Verify signed data.
Expects a signed data on input and outputs the signed data.
Both clear text and opaque signing is supported.
.Pp
By default, validation of signer certificates and their chain is done
w.r.t.
the S/MIME signing
.Pf ( Qo Li smimesign Qc )
purpose.
For details see
.Xr openssl-verification-options 1 .
.It Sy -resign
Resign a message: take an existing message and one or more new signers.
.It Sy -sign_receipt
Generate and output a signed receipt for the supplied message.
The input message
.Sy must
contain a signed receipt request.
Functionality is otherwise similar to the
.Sy -sign
operation.
.It Sy -verify_receipt Em receipt
Verify a signed receipt in filename
.Sy receipt .
The input message
.Sy must
contain the original receipt request.
Functionality is otherwise similar to the
.Sy -verify
operation.
.It Sy -digest Em digest
When used with
.Sy -sign ,
provides the digest in hexadecimal form instead of computing it from the
original message content.
Cannot be combined with
.Sy -in
or
.Sy -nodetach .
.Pp
This operation is the CMS equivalent of
.Xr openssl-pkeyutl 1
signing.
When signing a pre-computed digest, the security relies on the digest
and its computation from the original message being trusted.
.It Sy -digest_create
Create a CMS
.Sy DigestedData
type.
.It Sy -digest_verify
Verify a CMS
.Sy DigestedData
type and output the content.
.It Sy -compress
Create a CMS
.Sy CompressedData
type.
OpenSSL must be compiled with
.Sy zlib
support for this option to work, otherwise it will output an error.
.It Sy -uncompress
Uncompress a CMS
.Sy CompressedData
type and output the content.
OpenSSL must be compiled with
.Sy zlib
support for this option to work, otherwise it will output an error.
.It Sy -EncryptedData_encrypt
Encrypt content using supplied symmetric key and algorithm using a CMS
.Sy EncryptedData
type and output the content.
.It Sy -EncryptedData_decrypt
Decrypt content using supplied symmetric key and algorithm using a CMS
.Sy EncryptedData
type and output the content.
.It Sy -data_create
Create a CMS
.Sy Data
type.
.It Sy -data_out
.Sy Data
type and output the content.
.It Sy -cmsout
Takes an input message and writes out a PEM encoded CMS structure.
.El
.Ss File format options
.Bl -tag -width Ds
.It Sy -inform Sy DER Ns | Ns Sy PEM Ns | Ns Sy SMIME
The input format of the CMS structure (if one is being read); the
default is
.Sy SMIME .
See
.Xr openssl-format-options 1
for details.
.It Sy -outform Sy DER Ns | Ns Sy PEM Ns | Ns Sy SMIME
The output format of the CMS structure (if one is being written); the
default is
.Sy SMIME .
See
.Xr openssl-format-options 1
for details.
.It Sy -rctform Sy DER Ns | Ns Sy PEM Ns | Ns Sy SMIME
The signed receipt format for use with the
.Sy -receipt_verify ;
the default is
.Sy SMIME .
See
.Xr openssl-format-options 1
for details.
.It Sy -stream Ns , Sy -indef
The
.Sy -stream
and
.Sy -indef
options are equivalent and enable streaming I/O for encoding operations.
This permits single pass processing of data without the need to hold the
entire contents in memory, potentially supporting very large files.
Streaming is automatically set for S/MIME signing with detached data if
the output format is
.Sy SMIME
it is currently off by default for all other operations.
.It Sy -noindef
Disable streaming I/O where it would produce and indefinite length
constructed encoding.
This option currently has no effect.
In future streaming will be enabled by default on all relevant
operations and this option will disable it.
.It Sy -binary
Normally the input message is converted to "canonical" format which is
effectively using CR and LF as end of line: as required by the S/MIME
specification.
When this option is present no translation occurs.
This is useful when handling binary data which may not be in MIME
format.
.It Sy -crlfeol
Normally the output file uses a single
.Sy LF
as end of line.
When this option is present
.Sy CRLF
is used instead.
.It Sy -asciicrlf
When signing use ASCII CRLF format canonicalisation.
This strips trailing whitespace from all lines, deletes trailing blank
lines at EOF and sets the encapsulated content type.
This option is normally used with detached content and an output
signature format of DER. This option is not normally needed when
verifying as it is enabled automatically if the encapsulated content
format is detected.
.El
.Ss Keys and password options
.Bl -tag -width Ds
.It Sy -pwri_password Em password
Specify password for recipient.
.It Sy -secretkey Em key
Specify symmetric key to use.
The key must be supplied in hex format and be consistent with the
algorithm used.
Supported by the
.Sy -EncryptedData_encrypt
.Sy -EncryptedData_decrypt ,
.Sy -encrypt
and
.Sy -decrypt
options.
When used with
.Sy -encrypt
or
.Sy -decrypt
the supplied key is used to wrap or unwrap the content encryption key
using an AES key in the
.Sy KEKRecipientInfo
type.
.It Sy -secretkeyid Em id
The key identifier for the supplied symmetric key for
.Sy KEKRecipientInfo
type.
This option
.Sy must
be present if the
.Sy -secretkey
option is used with
.Sy -encrypt .
With
.Sy -decrypt
operations the
.Em id
is used to locate the relevant key if it is not supplied then an attempt
is used to decrypt any
.Sy KEKRecipientInfo
structures.
.It Sy -inkey Em filename Ns | Ns Em uri
The private key to use when signing or decrypting.
This must match the corresponding certificate.
If this option is not specified then the private key must be included in
the certificate file specified with the
.Sy -recip
or
.Sy -signer
file.
When signing this option can be used multiple times to specify
successive keys.
.It Sy -passin Em arg
The private key password source.
For more information about the format of
.Sy arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -keyopt Em name Ns : Ns Em parameter
For signing and encryption this option can be used multiple times to set
customised parameters for the preceding key or certificate.
It can currently be used to set RSA-PSS for signing, RSA-OAEP for
encryption or to modify default parameters for ECDH.
.It Sy -keyform Sy DER Ns | Ns Sy PEM Ns | Ns Sy P12 Ns | Ns Sy ENGINE
The format of the private key file; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.El
.Ss Encryption and decryption options
.Bl -tag -width Ds
.It Sy -originator Em file
A certificate of the originator of the encrypted message.
Necessary for decryption when Key Agreement is in use for a shared key.
Currently, not allowed for encryption.
.It Sy -recip Em file
When decrypting a message this specifies the certificate of the
recipient.
The certificate must match one of the recipients of the message.
.Pp
When encrypting a message this option may be used multiple times to
specify each recipient.
This form
.Sy must
be used if customised parameters are required (for example to specify
RSA-OAEP).
.Pp
Only certificates carrying RSA, Diffie-Hellman or EC keys are supported
by this option.
.It Em recipient-cert No ...
This is an alternative to using the
.Sy -recip
option when encrypting a message.
One or more certificate filenames may be given.
.It Sy - Ns Em cipher
The encryption algorithm to use.
For example, AES (256 bits) -
.Sy -aes256
or triple DES (168 bits) -
.Sy -des3 .
Any standard algorithm name (as used by the
.Xr EVP_get_cipherbyname 3
function) can also be used preceded by a dash, for example
.Sy -aes-128-cbc .
See
.Xr openssl-enc 1
for a list of ciphers supported by your version of OpenSSL.
.Pp
Currently, the AES variants with GCM mode are the only supported AEAD
algorithms.
.Pp
If not specified, AES-256-CBC is used as the default.
Only used with
.Sy -encrypt
and
.Sy -EncryptedData_create
commands.
.It Sy -wrap Em cipher
Cipher algorithm to use for key wrap when encrypting the message using
Key Agreement for key transport.
The algorithm specified should be suitable for key wrap.
.It Sy -aes128-wrap Ns , Sy -aes192-wrap Ns , Sy -aes256-wrap Ns , Sy -des3-wrap
Use AES128, AES192, AES256, or 3DES-EDE, respectively, to wrap key.
Depending on the OpenSSL build options used,
.Sy -des3-wrap
may not be supported.
.It Sy -debug_decrypt
This option sets the
.Sy CMS_DEBUG_DECRYPT
flag.
This option should be used with caution: see the notes section below.
.El
.Ss Signing options
.Bl -tag -width Ds
.It Sy -md Em digest
Digest algorithm to use when signing or resigning.
If not present then the default digest algorithm for the signing key
will be used (usually SHA1).
.It Sy -signer Em file
A signing certificate.
When signing or resigning a message, this option can be used multiple
times if more than one signer is required.
.It Sy -certfile Em file
Allows additional certificates to be specified.
When signing these will be included with the message.
When verifying, these will be searched for signer certificates and will
be used for chain building.
.Pp
The input can be in PEM, DER, or PKCS#12 format.
.It Sy -cades
When used with
.Sy -sign ,
add an ESS signingCertificate or ESS signingCertificateV2
signed-attribute to the SignerInfo, in order to make the signature
comply with the requirements for a CAdES Basic Electronic Signature
(CAdES-BES).
.It Sy -nodetach
When signing a message use opaque signing: this form is more resistant
to translation by mail relays but it cannot be read by mail agents that
do not support S/MIME. Without this option cleartext signing with the
MIME type multipart/signed is used.
.It Sy -nocerts
When signing a message the signer's certificate is normally included
with this option it is excluded.
This will reduce the size of the signed message but the verifier must
have a copy of the signers certificate available locally (passed using
the
.Sy -certfile
option for example).
.It Sy -noattr
Normally when a message is signed a set of attributes are included which
include the signing time and supported symmetric algorithms.
With this option they are not included.
.It Sy -nosmimecap
Exclude the list of supported algorithms from signed attributes, other
options such as content type and (optionally) signing time are still
included.
.It Sy -no_signing_time
Exclude the signing time from signed attributes, other options such as
content type are still included.
.It Sy -receipt_request_all Ns , Sy -receipt_request_first
For
.Sy -sign
option include a signed receipt request.
Indicate requests should be provided by all recipient or first tier
recipients (those mailed directly and not from a mailing list).
Ignored it
.Sy -receipt_request_from
is included.
.It Sy -receipt_request_from Em emailaddress
For
.Sy -sign
option include a signed receipt request.
Add an explicit email address where receipts should be supplied.
.It Sy -receipt_request_to Em emailaddress
Add an explicit email address where signed receipts should be sent to.
This option
.Sy must
but supplied if a signed receipt is requested.
.El
.Ss Verification options
.Bl -tag -width Ds
.It Sy -signer Em file
If a message has been verified successfully then the signers
certificate(s) will be written to this file if the verification was
successful.
.It Sy -content Em filename
This specifies a file containing the detached content for operations
taking S/MIME input, such as the
.Sy -verify
command.
This is only usable if the CMS structure is using the detached signature
form where the content is not included.
This option will override any content if the input format is S/MIME and
it uses the multipart/signed MIME content type.
.It Sy -no_content_verify
Do not verify signed content signatures.
.It Sy -no_attr_verify
Do not verify signed attribute signatures.
.It Sy -nosigs
Don't verify message signature.
.It Sy -noverify
Do not verify the signers certificate of a signed message.
.It Sy -nointern
When verifying a message normally certificates (if any) included in the
message are searched for the signing certificate.
With this option only the certificates specified in the
.Sy -certfile
option are used.
The supplied certificates can still be used as untrusted CAs however.
.It Sy -cades
When used with
.Sy -verify ,
require and check signer certificate digest.
See the NOTES section for more details.
.It Sy -verify_retcode
Exit nonzero on verification failure.
.It Sy -CAfile Em file Ns , Sy -no-CAfile Ns , Sy -CApath Em dir Ns , Sy -no-CApath Ns , Sy -CAstore Em uri Ns , Sy -no-CAstore
See
.Xr openssl-verification-options 1
for details.
.El
.Ss Output options
.Bl -tag -width Ds
.It Sy -keyid
Use subject key identifier to identify certificates instead of issuer
name and serial number.
The supplied certificate
.Sy must
include a subject key identifier extension.
Supported by
.Sy -sign
and
.Sy -encrypt
options.
.It Sy -econtent_type Em type
Set the encapsulated content type to
.Em type
if not supplied the
.Sy Data
type is used.
The
.Em type
argument can be any valid OID name in either text or numerical format.
.It Sy -text
This option adds plain text (text/plain) MIME headers to the supplied
message if encrypting or signing.
If decrypting or verifying it strips off text headers: if the decrypted
or verified message is not of MIME type text/plain then an error occurs.
.It Sy -certsout Em file
Any certificates contained in the input message are written to
.Em file .
.It Sy -to Ns , Sy -from Ns , Sy -subject
The relevant email headers.
These are included outside the signed portion of a message so they may
be included manually.
If signing then many S/MIME mail clients check the signers certificate's
email address matches that specified in the From: address.
.El
.Ss Printing options
.Bl -tag -width Ds
.It Sy -noout
For the
.Sy -cmsout
operation do not output the parsed CMS structure.
This is useful if the syntax of the CMS structure is being checked.
.It Sy -print
For the
.Sy -cmsout
operation print out all fields of the CMS structure.
This implies
.Sy -noout .
This is mainly useful for testing purposes.
.It Sy -nameopt Em option
For the
.Sy -cmsout
operation when
.Sy -print
option is in use, specifies printing options for string fields.
For most cases
.Sy utf8
is reasonable value.
See
.Xr openssl-namedisplay-options 1
for details.
.It Sy -receipt_request_print
For the
.Sy -verify
operation print out the contents of any signed receipt requests.
.El
.Ss Validation options
.Bl -tag -width Ds
.It Sy -allow_proxy_certs Ns , Sy -attime Ns , Sy -no_check_time Ns , Sy -check_ss_sig Ns , Sy -crl_check Ns , Sy -crl_check_all Ns , Sy -explicit_policy Ns , Sy -extended_crl Ns , Sy -ignore_critical Ns , Sy -inhibit_any Ns , Sy -inhibit_map Ns , Sy -no_alt_chains Ns , Sy -partial_chain Ns , Sy -policy Ns , Sy -policy_check Ns , Sy -policy_print Ns , Sy -purpose Ns , Sy -suiteB_128 Ns , Sy -suiteB_128_only Ns , Sy -suiteB_192 Ns , Sy -trusted_first Ns , Sy -use_deltas Ns , Sy -auth_level Ns , Sy -verify_depth Ns , Sy -verify_email Ns , Sy -verify_hostname Ns , Sy -verify_ip Ns , Sy -verify_name Ns , Sy -x509_strict Sy -issuer_checks
Set various options of certificate chain verification.
See
.Xr openssl-verification-options 1
for details.
.Pp
Any validation errors cause the command to exit.
.El
.Sh NOTES
The MIME message must be sent without any blank lines between the
headers and the output.
Some mail programs will automatically add a blank line.
Piping the mail directly to sendmail is one way to achieve the correct
format.
.Pp
The supplied message to be signed or encrypted must include the
necessary MIME headers or many S/MIME clients won't display it properly
(if at all).
You can use the
.Sy -text
option to automatically add plain text headers.
.Pp
A "signed and encrypted" message is one where a signed message is then
encrypted.
This can be produced by encrypting an already signed message: see the
examples section.
.Pp
This version of the program only allows one signer per message but it
will verify multiple signers on received messages.
Some S/MIME clients choke if a message contains multiple signers.
It is possible to sign messages "in parallel" by signing an already
signed message.
.Pp
The options
.Sy -encrypt
and
.Sy -decrypt
reflect common usage in S/MIME clients.
Strictly speaking these process CMS enveloped data: CMS encrypted data
is used for other purposes.
.Pp
The
.Sy -resign
option uses an existing message digest when adding a new signer.
This means that attributes must be present in at least one existing
signer using the same message digest or this operation will fail.
.Pp
The
.Sy -stream
and
.Sy -indef
options enable streaming I/O support.
As a result the encoding is BER using indefinite length constructed
encoding and no longer DER. Streaming is supported for the
.Sy -encrypt
operation and the
.Sy -sign
operation if the content is not detached.
.Pp
Streaming is always used for the
.Sy -sign
operation with detached data but since the content is no longer part of
the CMS structure the encoding remains DER.
.Pp
If the
.Sy -decrypt
option is used without a recipient certificate then an attempt is made
to locate the recipient by trying each potential recipient in turn using
the supplied private key.
To thwart the MMA attack (Bleichenbacher's attack on PKCS #1 v1.5 RSA
padding) all recipients are tried whether they succeed or not and if no
recipients match the message is "decrypted" using a random key which
will typically output garbage.
The
.Sy -debug_decrypt
option can be used to disable the MMA attack protection and return an
error if no recipient can be found: this option should be used with
caution.
For a fuller description see
.Xr CMS_decrypt 3 Ns ).
.Sh CADES BASIC ELECTRONIC SIGNATURE (CADES-BES)
A CAdES Basic Electronic Signature (CAdES-BES), as defined in the
European Standard ETSI EN 319 122-1 V1.1.1, contains:
.Bl -bullet
.It
The signed user data as defined in CMS (RFC 3852);
.It
Content-type of the EncapsulatedContentInfo value being signed;
.It
Message-digest of the eContent OCTET STRING within encapContentInfo
being signed;
.It
An ESS signingCertificate or ESS signingCertificateV2 attribute, as
defined in Enhanced Security Services (ESS), RFC 2634 and RFC 5035. An
ESS signingCertificate attribute only allows for SHA-1 as digest
algorithm.
An ESS signingCertificateV2 attribute allows for any digest algorithm.
.It
The digital signature value computed on the user data and, when present,
on the signed attributes.
.Pp
NOTE that the
.Sy -cades
option applies to the
.Sy -sign
or
.Sy -verify
operations.
With this option, the
.Sy -verify
operation also requires that the signingCertificate attribute is present
and checks that the given identifiers match the verification trust chain
built during the verification process.
.El
.Sh EXIT CODES
.Bl -tag -width Ds
.It 0
The operation was completely successfully.
.It 1
An error occurred parsing the command options.
.It 2
One of the input files could not be read.
.It 3
An error occurred creating the CMS file or when reading the MIME
message.
.It 4
An error occurred decrypting or verifying the message.
.It 5
The message was verified correctly but an error occurred writing out the
signers certificates.
.El
.Sh COMPATIBILITY WITH PKCS#7 FORMAT
.Xr openssl-smime 1
can only process the older
.Sy PKCS#7
format.
.Sy openssl cms
supports Cryptographic Message Syntax format.
Use of some features will result in messages which cannot be processed
by applications which only support the older format.
These are detailed below.
.Pp
The use of the
.Sy -keyid
option with
.Sy -sign
or
.Sy -encrypt .
.Pp
The
.Sy -outform
.Em PEM
option uses different headers.
.Pp
The
.Sy -compress
option.
.Pp
The
.Sy -secretkey
option when used with
.Sy -encrypt .
.Pp
The use of PSS with
.Sy -sign .
.Pp
The use of OAEP or non-RSA keys with
.Sy -encrypt .
.Pp
Additionally the
.Sy -EncryptedData_create
and
.Sy -data_create
type cannot be processed by the older
.Xr openssl-smime 1
command.
.Sh EXAMPLES
Create a cleartext signed message:
.Bd -literal
 openssl cms -sign -in message.txt -text -out mail.msg \e
        -signer mycert.pem
.Ed
.Pp
Create an opaque signed message
.Bd -literal
 openssl cms -sign -in message.txt -text -out mail.msg -nodetach \e
        -signer mycert.pem
.Ed
.Pp
Create a signed message, include some additional certificates and read
the private key from another file:
.Bd -literal
 openssl cms -sign -in in.txt -text -out mail.msg \e
        -signer mycert.pem -inkey mykey.pem -certfile mycerts.pem
.Ed
.Pp
Create a signed message with two signers, use key identifier:
.Bd -literal
 openssl cms -sign -in message.txt -text -out mail.msg \e
        -signer mycert.pem -signer othercert.pem -keyid
.Ed
.Pp
Send a signed message under Unix directly to sendmail, including
headers:
.Bd -literal
 openssl cms -sign -in in.txt -text -signer mycert.pem \e
        -from steve@openssl.org -to someone@somewhere \e
        -subject "Signed message" | sendmail someone@somewhere
.Ed
.Pp
Verify a message and extract the signer's certificate if successful:
.Bd -literal
 openssl cms -verify -in mail.msg -signer user.pem -out signedtext.txt
.Ed
.Pp
Send encrypted mail using triple DES:
.Bd -literal
 openssl cms -encrypt -in in.txt -from steve@openssl.org \e
        -to someone@somewhere -subject "Encrypted message" \e
        -des3 user.pem -out mail.msg
.Ed
.Pp
Sign and encrypt mail:
.Bd -literal
 openssl cms -sign -in ml.txt -signer my.pem -text \e
        | openssl cms -encrypt -out mail.msg \e
        -from steve@openssl.org -to someone@somewhere \e
        -subject "Signed and Encrypted message" -des3 user.pem
.Ed
.Pp
Note: the encryption command does not include the
.Sy -text
option because the message being encrypted already has MIME headers.
.Pp
Decrypt a message:
.Bd -literal
 openssl cms -decrypt -in mail.msg -recip mycert.pem -inkey key.pem
.Ed
.Pp
The output from Netscape form signing is a PKCS#7 structure with the
detached signature format.
You can use this program to verify the signature by line wrapping the
base64 encoded structure and surrounding it with:
.Bd -literal
 -----BEGIN PKCS7-----
 -----END PKCS7-----
.Ed
.Pp
and using the command,
.Bd -literal
 openssl cms -verify -inform PEM -in signature.pem -content content.txt
.Ed
.Pp
alternatively you can base64 decode the signature and use
.Bd -literal
 openssl cms -verify -inform DER -in signature.der -content content.txt
.Ed
.Pp
Create an encrypted message using 128 bit Camellia:
.Bd -literal
 openssl cms -encrypt -in plain.txt -camellia128 -out mail.msg cert.pem
.Ed
.Pp
Add a signer to an existing message:
.Bd -literal
 openssl cms -resign -in mail.msg -signer newsign.pem -out mail2.msg
.Ed
.Pp
Sign a message using RSA-PSS:
.Bd -literal
 openssl cms -sign -in message.txt -text -out mail.msg \e
        -signer mycert.pem -keyopt rsa_padding_mode:pss
.Ed
.Pp
Create an encrypted message using RSA-OAEP:
.Bd -literal
 openssl cms -encrypt -in plain.txt -out mail.msg \e
        -recip cert.pem -keyopt rsa_padding_mode:oaep
.Ed
.Pp
Use SHA256 KDF with an ECDH certificate:
.Bd -literal
 openssl cms -encrypt -in plain.txt -out mail.msg \e
        -recip ecdhcert.pem -keyopt ecdh_kdf_md:sha256
.Ed
.Pp
Print CMS signed binary data in human-readable form:
.Pp
openssl cms -in signed.cms -binary -inform DER -cmsout -print
.Sh BUGS
The MIME parser isn't very clever: it seems to handle most messages that
I've thrown at it but it may choke on others.
.Pp
The code currently will only write out the signer's certificate to a
file: if the signer has a separate encryption certificate this must be
manually extracted.
There should be some heuristic that determines the correct encryption
certificate.
.Pp
Ideally a database should be maintained of a certificates for each email
address.
.Pp
The code doesn't currently take note of the permitted symmetric
encryption algorithms as supplied in the SMIMECapabilities signed
attribute.
this means the user has to manually include the correct encryption
algorithm.
It should store the list of permitted ciphers in a database and only use
those.
.Pp
No revocation checking is done on the signer's certificate.
.Sh SEE ALSO
.Xr ossl_store-file 7
.Sh HISTORY
The default encryption cipher was changed from 3DES to AES-256 in
OpenSSL 3.5.
.Pp
The use of multiple
.Sy -signer
options and the
.Sy -resign
command were first added in OpenSSL 1.0.0.
.Pp
The
.Sy -keyopt
option was added in OpenSSL 1.0.2.
.Pp
Support for RSA-OAEP and RSA-PSS was added in OpenSSL 1.0.2.
.Pp
The use of non-RSA keys with
.Sy -encrypt
and
.Sy -decrypt
was added in OpenSSL 1.0.2.
.Pp
The -no_alt_chains option was added in OpenSSL 1.0.2b.
.Pp
The
.Sy -nameopt
option was added in OpenSSL 3.0.0.
.Pp
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Pp
The
.Sy -digest
option was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2008-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
