.Dd 2025-09-30
.Dt OPENSSL-FIPSINSTALL 1ossl
.Os
.Sh NAME
.Nm openssl-fipsinstall
.Nd perform FIPS configuration installation
.Sh SYNOPSIS
.Nm openssl fipsinstall
.Oo
.Fl help ]
.Oo
.Fl in
.Em configfilename ]
.Oo
.Fl out
.Em configfilename ]
.Oo
.Fl module
.Em modulefilename ]
.Oo
.Fl provider_name
.Em providername ]
.Oo
.Fl section_name
.Em sectionname ]
.Oo
.Fl verify ]
.Oo
.Fl mac_name
.Em macname ]
.Oo
.Fl macopt
.Em nm Ns : Ns Em v ]
.Oo
.Fl noout ]
.Oo
.Fl quiet ]
.Oo
.Fl pedantic ]
.Oo
.Fl no_conditional_errors ]
.Oo
.Fl no_security_checks ]
.Oo
.Fl hmac_key_check ]
.Oo
.Fl kmac_key_check ]
.Oo
.Fl ems_check ]
.Oo
.Fl no_drbg_truncated_digests ]
.Oo
.Fl signature_digest_check ]
.Oo
.Fl hkdf_digest_check ]
.Oo
.Fl tls13_kdf_digest_check ]
.Oo
.Fl tls1_prf_digest_check ]
.Oo
.Fl sshkdf_digest_check ]
.Oo
.Fl sskdf_digest_check ]
.Oo
.Fl x963kdf_digest_check ]
.Oo
.Fl dsa_sign_disabled ]
.Oo
.Fl no_pbkdf2_lower_bound_check ]
.Oo
.Fl no_short_mac ]
.Oo
.Fl tdes_encrypt_disabled ]
.Oo
.Fl rsa_pkcs15_padding_disabled ]
.Oo
.Fl rsa_pss_saltlen_check ]
.Oo
.Fl rsa_sign_x931_disabled ]
.Oo
.Fl hkdf_key_check ]
.Oo
.Fl kbkdf_key_check ]
.Oo
.Fl tls13_kdf_key_check ]
.Oo
.Fl tls1_prf_key_check ]
.Oo
.Fl sshkdf_key_check ]
.Oo
.Fl sskdf_key_check ]
.Oo
.Fl x963kdf_key_check ]
.Oo
.Fl x942kdf_key_check ]
.Oo
.Fl ecdh_cofactor_check ]
.Oo
.Fl self_test_onload ]
.Oo
.Fl self_test_oninstall ]
.Oo
.Fl corrupt_desc
.Em selftest_description ]
.Oo
.Fl corrupt_type
.Em selftest_type ]
.Oo
.Fl config
.Em parent_config ]
.Sh DESCRIPTION
This command is used to generate a FIPS module configuration file.
This configuration file can be used each time a FIPS module is loaded in
order to pass data to the FIPS module self tests.
The FIPS module always verifies its MAC, but optionally only needs to
run the KAT's once, at installation.
.Pp
The generated configuration file consists of:
.Bl -tag -width Ds
.It - A MAC of the FIPS module file.
.It - A test status indicator.
This indicates if the Known Answer Self Tests (KAT's) have successfully
run.
.It - A MAC of the status indicator.
.It - A control for conditional self tests errors.
By default if a continuous test (e.g a key pair test) fails then the
FIPS module will enter an error state, and no services or cryptographic
algorithms will be able to be accessed after this point.
The default value of '1' will cause the fips module error state to be
entered.
If the value is '0' then the module error state will not be entered.
Regardless of whether the error state is entered or not, the current
operation (e.g.
key generation) will return an error.
The user is responsible for retrying the operation if the module error
state is not entered.
.It - A control to indicate whether run-time security checks are done.
This indicates if run-time checks related to enforcement of security
parameters such as minimum security strength of keys and approved curve
names are used.
The default value of '1' will perform the checks.
If the value is '0' the checks are not performed and FIPS compliance
must be done by procedures documented in the relevant Security Policy.
.El
.Pp
This file is described in
.Xr fips_config 5 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print a usage message.
.It Sy -module Em filename
Filename of the FIPS module to perform an integrity check on.
The path provided in the filename is used to load the module when it is
activated, and this overrides the environment variable
.Sy OPENSSL_MODULES .
.It Sy -out Em configfilename
Filename to output the configuration data to; the default is standard
output.
.It Sy -in Em configfilename
Input filename to load configuration data from.
Must be used if the
.Sy -verify
option is specified.
.It Sy -verify
Verify that the input configuration file contains the correct
information.
.It Sy -provider_name Em providername
Name of the provider inside the configuration file.
The default value is
.Qo Li fips Qc .
.It Sy -section_name Em sectionname
Name of the section inside the configuration file.
The default value is
.Qo Li fips_sect Qc .
.It Sy -mac_name Em name
Specifies the name of a supported MAC algorithm which will be used.
The MAC mechanisms that are available will depend on the options used
when building OpenSSL. To see the list of supported MAC's use the
command
.Qo Li openssl list -mac-algorithms Qc .
The default is
.Sy HMAC .
.It Sy -macopt Em nm Ns : Ns Em v
Passes options to the MAC algorithm.
A comprehensive list of controls can be found in the EVP_MAC
implementation documentation.
Common control strings used for this command are:
.Bl -tag -width Ds
.It Sy key Ns : Ns Em string
Specifies the MAC key as an alphanumeric string (use if the key contains
printable characters only).
The string length must conform to any restrictions of the MAC algorithm.
A key must be specified for every MAC algorithm.
If no key is provided, the default that was specified when OpenSSL was
configured is used.
.It Sy hexkey Ns : Ns Em string
Specifies the MAC key in hexadecimal form (two hex digits per byte).
The key length must conform to any restrictions of the MAC algorithm.
A key must be specified for every MAC algorithm.
If no key is provided, the default that was specified when OpenSSL was
configured is used.
.It Sy digest Ns : Ns Em string
Used by HMAC as an alphanumeric string (use if the key contains
printable characters only).
The string length must conform to any restrictions of the MAC algorithm.
To see the list of supported digests, use the command
.Qo Li openssl list -digest-commands Qc .
The default digest is SHA-256.
.El
.It Sy -noout
Disable logging of the self tests.
.It Sy -pedantic
Configure the module so that it is strictly FIPS compliant rather than
being backwards compatible.
This enables conditional errors, security checks etc.
Note that any previous configuration options will be overwritten and any
subsequent configuration options that violate FIPS compliance will
result in an error.
.It Sy -no_conditional_errors
Configure the module to not enter an error state if a conditional self
test fails as described above.
.It Sy -no_security_checks
Configure the module to not perform run-time security checks as
described above.
.Pp
Enabling the configuration option "no-fips-securitychecks" provides
another way to turn off the check at compile time.
.It Sy -ems_check
Configure the module to enable a run-time Extended Master Secret (EMS)
check when using the TLS1_PRF KDF algorithm.
This check is disabled by default.
See RFC 7627 for information related to EMS.
.It Sy -no_short_mac
Configure the module to not allow short MAC outputs.
See SP 800-185 8.4.2 and FIPS 140-3 ID C.D for details.
.It Sy -hmac_key_check
Configure the module to not allow small keys sizes when using HMAC. See
SP 800-131Ar2 for details.
.It Sy -kmac_key_check
Configure the module to not allow small keys sizes when using KMAC. See
SP 800-131Ar2 for details.
.It Sy -no_drbg_truncated_digests
Configure the module to not allow truncated digests to be used with Hash
and HMAC DRBGs.
See FIPS 140-3 IG D.R for details.
.It Sy -signature_digest_check
Configure the module to enforce signature algorithms to use digests that
are explicitly permitted by the various standards.
.It Sy -hkdf_digest_check
This option is deprecated.
.It Sy -tls13_kdf_digest_check
Configure the module to enable a run-time digest check when deriving a
key by TLS13 KDF. See RFC 8446 for details.
.It Sy -tls1_prf_digest_check
Configure the module to enable a run-time digest check when deriving a
key by TLS_PRF. See NIST SP 800-135r1 for details.
.It Sy -sshkdf_digest_check
Configure the module to enable a run-time digest check when deriving a
key by SSHKDF. See NIST SP 800-135r1 for details.
.It Sy -sskdf_digest_check
This option is deprecated.
.It Sy -x963kdf_digest_check
Configure the module to enable a run-time digest check when deriving a
key by X963KDF. See NIST SP 800-131Ar2 for details.
.It Sy -dsa_sign_disabled
Configure the module to not allow DSA signing (DSA signature
verification is still allowed).
See FIPS 140-3 IG C.K for details.
.It Sy -tdes_encrypt_disabled
Configure the module to not allow Triple-DES encryption.
Triple-DES decryption is still allowed for legacy purposes.
See SP800-131Ar2 for details.
.It Sy -rsa_pkcs15_padding_disabled
Configure the module to not allow PKCS#1 version 1.5 padding to be used
with RSA for key transport and key agreement.
See NIST's SP 800-131A Revision 2 for details.
.It Sy -rsa_pss_saltlen_check
Configure the module to enable a run-time salt length check when
generating or verifying a RSA-PSS signature.
See FIPS 186-5 5.4 (g) for details.
.It Sy -rsa_sign_x931_disabled
Configure the module to not allow X9.31 padding to be used when signing
with RSA. See FIPS 140-3 IG C.K for details.
.It Sy -hkdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by HKDF. See NIST SP 800-131Ar2 for details.
.It Sy -kbkdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by KBKDF. See NIST SP 800-131Ar2 for details.
.It Sy -tls13_kdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by TLS13 KDF. See NIST SP 800-131Ar2 for details.
.It Sy -tls1_prf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by TLS_PRF. See NIST SP 800-131Ar2 for details.
.It Sy -sshkdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by SSHKDF. See NIST SP 800-131Ar2 for details.
.It Sy -sskdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by SSKDF. See NIST SP 800-131Ar2 for details.
.It Sy -x963kdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by X963KDF. See NIST SP 800-131Ar2 for details.
.It Sy -x942kdf_key_check
Configure the module to enable a run-time short key-derivation key check
when deriving a key by X942KDF. See NIST SP 800-131Ar2 for details.
.It Sy -no_pbkdf2_lower_bound_check
Configure the module to not perform run-time lower bound check for
PBKDF2. See NIST SP 800-132 for details.
.It Sy -ecdh_cofactor_check
Configure the module to enable a run-time check that ECDH uses the EC
curves cofactor value when deriving a key.
This only affects the 'B' and 'K' curves.
See SP 800-56A r3 Section 5.7.1.2 for details.
.It Sy -self_test_onload
Do not write the two fields related to the "test status indicator" and
"MAC status indicator" to the output configuration file.
Without these fields the self tests KATS will run each time the module
is loaded.
This option could be used for cross compiling, since the self tests need
to run at least once on each target machine.
Once the self tests have run on the target machine the user could
possibly then add the 2 fields into the configuration using some other
mechanism.
This option defaults to 0 for any OpenSSL FIPS 140-2 provider (OpenSSL
3.0.X). and is not relevant for an OpenSSL FIPS 140-3 provider, since
this is no longer allowed.
.It Sy -self_test_oninstall
The converse of
.Sy -self_test_oninstall .
The two fields related to the "test status indicator" and "MAC status
indicator" are written to the output configuration file.
This field is not relevant for an OpenSSL FIPS 140-3 provider, since
this is no longer allowed.
.It Sy -quiet
Do not output pass/fail messages.
Implies
.Sy -noout .
.It Sy -corrupt_desc Em selftest_description Ns , Sy -corrupt_type Em selftest_type
The corrupt options can be used to test failure of one or more self
tests by name.
Either option or both may be used to select the tests to corrupt.
Refer to the entries for
.Sy st-desc
and
.Sy st-type
in
.Xr OSSL_PROVIDER-FIPS 7
for values that can be used.
.It Sy -config Em parent_config
Test that a FIPS provider can be loaded from the specified configuration
file.
A previous call to this application needs to generate the extra
configuration data that is included by the base
.Qo Li parent_config Qc
configuration file.
See
.Xr config 5
for further information on how to set up a provider section.
All other options are ignored if '-config' is used.
.El
.Sh NOTES
Self tests results are logged by default if the options
.Sy -quiet
and
.Sy -noout
are not specified, or if either of the options
.Sy -corrupt_desc
or
.Sy -corrupt_type
are used.
If the base configuration file is set up to autoload the fips module,
then the fips module will be loaded and self tested BEFORE the
fipsinstall application has a chance to set up its own self test
callback.
As a result of this the self test output and the options
.Sy -corrupt_desc
and
.Sy -corrupt_type
will be ignored.
For normal usage the base configuration file should use the default
provider when generating the fips configuration file.
.Pp
The
.Sy -self_test_oninstall
option was added and the
.Sy -self_test_onload
option was made the default in OpenSSL 3.1.
.Pp
The command and all remaining options were added in OpenSSL 3.0.
.Sh EXAMPLES
Calculate the mac of a FIPS module
.Pa fips.so
and run a FIPS self test for the module, and save the
.Pa fips.cnf
configuration file:
.Bd -literal
 openssl fipsinstall -module ./fips.so -out fips.cnf -provider_name fips
.Ed
.Pp
Verify that the configuration file
.Pa fips.cnf
contains the correct info:
.Bd -literal
 openssl fipsinstall -module ./fips.so -in fips.cnf  -provider_name fips -verify
.Ed
.Pp
Corrupt any self tests which have the description
.Qo Li SHA1 Qc :
.Bd -literal
 openssl fipsinstall -module ./fips.so -out fips.cnf -provider_name fips \e
         -corrupt_desc 'SHA1'
.Ed
.Pp
Validate that the fips module can be loaded from a base configuration
file:
.Bd -literal
 export OPENSSL_CONF_INCLUDE=<path of configuration files>
 export OPENSSL_MODULES=<provider-path>
 openssl fipsinstall -config' 'default.cnf'
.Ed
.Sh SEE ALSO
.Xr config 5 ,
.Xr fips_config 5 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr EVP_MAC 3
.Sh HISTORY
The
.Sy openssl-fipsinstall
application was added in OpenSSL 3.0.
.Pp
The following options were added in OpenSSL 3.1:
.Pp
.Sy -ems_check ,
.Sy -self_test_oninstall
.Pp
The following options were added in OpenSSL 3.2:
.Pp
.Sy -pedantic ,
.Sy -no_drbg_truncated_digests
.Pp
The following options were added in OpenSSL 3.4:
.Pp
.Sy -hmac_key_check ,
.Sy -kmac_key_check ,
.Sy -signature_digest_check ,
.Sy -hkdf_digest_check ,
.Sy -tls13_kdf_digest_check ,
.Sy -tls1_prf_digest_check ,
.Sy -sshkdf_digest_check ,
.Sy -sskdf_digest_check ,
.Sy -x963kdf_digest_check ,
.Sy -dsa_sign_disabled ,
.Sy -no_pbkdf2_lower_bound_check ,
.Sy -no_short_mac ,
.Sy -tdes_encrypt_disabled ,
.Sy -rsa_pkcs15_padding_disabled ,
.Sy -rsa_pss_saltlen_check ,
.Sy -rsa_sign_x931_disabled ,
.Sy -hkdf_key_check ,
.Sy -kbkdf_key_check ,
.Sy -tls13_kdf_key_check ,
.Sy -tls1_prf_key_check ,
.Sy -sshkdf_key_check ,
.Sy -sskdf_key_check ,
.Sy -x963kdf_key_check ,
.Sy -x942kdf_key_check ,
.Sy -ecdh_cofactor_check
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
