.Dd 2025-09-30
.Dt OPENSSL-SPEED 1ossl
.Os
.Sh NAME
.Nm openssl-speed
.Nd test library performance
.Sh SYNOPSIS
.Nm openssl speed
.Oo
.Fl help ]
.Oo
.Fl config
.Em filename ]
.Oo
.Fl elapsed ]
.Oo
.Fl evp
.Em algo ]
.Oo
.Fl hmac
.Em algo ]
.Oo
.Fl cmac
.Em algo ]
.Oo
.Fl mb ]
.Oo
.Fl aead ]
.Oo
.Fl kem-algorithms ]
.Oo
.Fl signature-algorithms ]
.Oo
.Fl multi
.Em num ]
.Oo
.Fl async_jobs
.Em num ]
.Oo
.Fl misalign
.Em num ]
.Oo
.Fl decrypt ]
.Oo
.Fl primes
.Em num ]
.Oo
.Fl seconds
.Em num ]
.Oo
.Fl bytes
.Em num ]
.Oo
.Fl mr ]
.Oo
.Fl mlock ]
.Oo
.Fl testmode ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Em algorithm
.Oc
\&...
.Sh DESCRIPTION
This command is used to test the performance of cryptographic
algorithms.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -config Em filename
Specifies the configuration file to use.
Optional; for a description of the default value, see
.Xr openssl 1 .
.It Sy -elapsed
When calculating operations- or bytes-per-second, use wall-clock time
instead of CPU user time as divisor.
It can be useful when testing speed of hardware engines.
.It Sy -evp Em algo
Use the specified cipher or message digest algorithm via the EVP
interface.
If
.Em algo
is an AEAD cipher, then you can pass
.Sy -aead
to benchmark a TLS-like sequence.
And if
.Em algo
is a multi-buffer capable cipher, e.g.
aes-128-cbc-hmac-sha1, then
.Sy -mb
will time multi-buffer operation.
.Pp
To see the algorithms supported with this option, use
.Qo Li openssl list -digest-algorithms Qc
or
.Qo Li openssl list -cipher-algorithms Qc
command.
.It Sy -multi Em num
Run multiple operations in parallel.
.It Sy -async_jobs Em num
Enable async mode and start specified number of jobs.
.It Sy -misalign Em num
Misalign the buffers by the specified number of bytes.
.It Sy -hmac Em digest
Time the HMAC algorithm using the specified message digest.
.It Sy -cmac Em cipher
Time the CMAC algorithm using the specified cipher e.g.
.Qo Li openssl speed -cmac aes128 Qc .
.It Sy -decrypt
Time the decryption instead of encryption.
Affects only the EVP testing.
.It Sy -mb
Enable multi-block mode on EVP-named cipher.
.It Sy -aead
Benchmark EVP-named AEAD cipher in TLS-like sequence.
.It Sy -kem-algorithms
Benchmark KEM algorithms: key generation, encapsulation, decapsulation.
.It Sy -signature-algorithms
Benchmark signature algorithms: key generation, signature, verification.
.It Sy -primes Em num
Generate a
.Em num Ns -prime
RSA key and use it to run the benchmarks.
This option is only effective if RSA algorithm is specified to test.
.It Sy -seconds Em num
Run benchmarks for
.Em num
seconds.
.It Sy -bytes Em num
Run benchmarks on
.Em num Ns -byte
buffers.
Affects ciphers, digests and the CSPRNG. The limit on the size of the
buffer is INT_MAX - 64 bytes, which for a 32-bit int would be 2147483583
bytes.
.It Sy -mr
Produce the summary in a mechanical, machine-readable, format.
.It Sy -mlock
Lock memory into RAM for more deterministic measurements.
.It Sy -testmode
Runs the speed command in testmode.
Runs only 1 iteration of each algorithm test regardless of any
.Sy -seconds
value.
In the event that any operation fails then the speed command will return
with a failure result.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Em algorithm No ...
If any
.Em algorithm
is given, then those algorithms are tested, otherwise a pre-compiled
grand selection is tested.
.El
.Sh BUGS
The
.Em algorithm
can be selected only from a pre-compiled subset of things that the
.Qo Li openssl speed Qc
command knows about.
To test any additional digest or cipher algorithm supported by OpenSSL
use the
.Qo Li -evp Qc
option.
.Pp
There is no way to test the speed of any additional public key
algorithms supported by third party providers with the
.Qo Li openssl speed Qc
command.
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Pp
DSA512 was removed in OpenSSL 3.2.
.Pp
The
.Sy -testmode
option was added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2000-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
