.Dd 2025-09-30
.Dt OPENSSL-S_CLIENT 1ossl
.Os
.Sh NAME
.Nm openssl-s_client
.Nd SSL/TLS client program
.Sh SYNOPSIS
.Nm openssl
.Ar s_client
.Oo
.Fl help ]
.Oo
.Fl ssl_config
.Em section ]
.Oo
.Fl connect
.Em host Ns : Ns Em port ]
.Oo
.Fl host
.Em hostname ]
.Oo
.Fl port
.Em port ]
.Oo
.Fl bind
.Em host Ns : Ns Em port ]
.Oo
.Fl proxy
.Em host Ns : Ns Em port ]
.Oo
.Fl proxy_user
.Em userid ]
.Oo
.Fl proxy_pass
.Em arg ]
.Oo
.Fl unix
.Em path ]
.Oo
.Fl 4 ]
.Oo
.Fl 6 ]
.Oo
.Fl quic ]
.Oo
.Fl servername
.Em name ]
.Oo
.Fl noservername ]
.Oo
.Fl verify
.Em depth ]
.Oo
.Fl verify_return_error ]
.Oo
.Fl verify_quiet ]
.Oo
.Fl verifyCAfile
.Em filename ]
.Oo
.Fl verifyCApath
.Em dir ]
.Oo
.Fl verifyCAstore
.Em uri ]
.Oo
.Fl cert
.Em filename ]
.Oo
.Fl certform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar P12 ]
.Oo
.Fl cert_chain
.Em filename ]
.Oo
.Fl build_chain ]
.Oo
.Fl CRL
.Em filename ]
.Oo
.Fl CRLform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl crl_download ]
.Oo
.Fl key
.Em filename Ns | Ns Em uri ]
.Oo
.Fl keyform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar P12 Ns | Ns Ar ENGINE ]
.Oo
.Fl pass
.Em arg ]
.Oo
.Fl chainCAfile
.Em filename ]
.Oo
.Fl chainCApath
.Em directory ]
.Oo
.Fl chainCAstore
.Em uri ]
.Oo
.Fl requestCAfile
.Em filename ]
.Oo
.Fl dane_tlsa_domain
.Em domain ]
.Oo
.Fl dane_tlsa_rrdata
.Em rrdata ]
.Oo
.Fl dane_ee_no_namechecks ]
.Oo
.Fl reconnect ]
.Oo
.Fl showcerts ]
.Oo
.Fl prexit ]
.Oo
.Fl no-interactive ]
.Oo
.Fl debug ]
.Oo
.Fl trace ]
.Oo
.Fl nocommands ]
.Oo
.Fl adv ]
.Oo
.Fl security_debug ]
.Oo
.Fl security_debug_verbose ]
.Oo
.Fl msg ]
.Oo
.Fl timeout ]
.Oo
.Fl mtu
.Em size ]
.Oo
.Fl no_ems ]
.Oo
.Fl keymatexport
.Em label ]
.Oo
.Fl keymatexportlen
.Em len ]
.Oo
.Fl msgfile
.Em filename ]
.Oo
.Fl nbio_test ]
.Oo
.Fl state ]
.Oo
.Fl nbio ]
.Oo
.Fl crlf ]
.Oo
.Fl ign_eof ]
.Oo
.Fl no_ign_eof ]
.Oo
.Fl psk_identity
.Em identity ]
.Oo
.Fl psk
.Em key ]
.Oo
.Fl psk_session
.Em file ]
.Oo
.Fl quiet ]
.Oo
.Fl sctp ]
.Oo
.Fl sctp_label_bug ]
.Oo
.Fl fallback_scsv ]
.Oo
.Fl async ]
.Oo
.Fl maxfraglen
.Em len ]
.Oo
.Fl max_send_frag ]
.Oo
.Fl split_send_frag ]
.Oo
.Fl max_pipelines ]
.Oo
.Fl read_buf ]
.Oo
.Fl ignore_unexpected_eof ]
.Oo
.Fl no_tx_cert_comp ]
.Oo
.Fl no_rx_cert_comp ]
.Oo
.Fl brief ]
.Oo
.Fl starttls
.Em protocol ]
.Oo
.Fl xmpphost
.Em hostname ]
.Oo
.Fl name
.Em hostname ]
.Oo
.Fl tlsextdebug ]
.Oo
.Fl sess_out
.Em filename ]
.Oo
.Fl sess_in
.Em filename ]
.Oo
.Fl serverinfo
.Em types ]
.Oo
.Fl status ]
.Oo
.Fl alpn
.Em protocols ]
.Oo
.Fl nextprotoneg
.Em protocols ]
.Oo
.Fl ct ]
.Oo
.Fl noct ]
.Oo
.Fl ctlogfile ]
.Oo
.Fl keylogfile
.Em file ]
.Oo
.Fl early_data
.Em file ]
.Oo
.Fl enable_pha ]
.Oo
.Fl use_srtp
.Em value ]
.Oo
.Fl srpuser
.Em value ]
.Oo
.Fl srppass
.Em value ]
.Oo
.Fl srp_lateuser ]
.Oo
.Fl srp_moregroups ]
.Oo
.Fl srp_strength
.Em number ]
.Oo
.Fl ktls ]
.Oo
.Fl tfo ]
.Oo
.Fl nameopt
.Em option ]
.Oo
.Fl no_ssl3 ]
.Oo
.Fl no_tls1 ]
.Oo
.Fl no_tls1_1 ]
.Oo
.Fl no_tls1_2 ]
.Oo
.Fl no_tls1_3 ]
.Oo
.Fl ssl3 ]
.Oo
.Fl tls1 ]
.Oo
.Fl tls1_1 ]
.Oo
.Fl tls1_2 ]
.Oo
.Fl tls1_3 ]
.Oo
.Fl dtls ]
.Oo
.Fl dtls1 ]
.Oo
.Fl dtls1_2 ]
.Oo
.Fl xkey
.Em infile ]
.Oo
.Fl xcert
.Em file ]
.Oo
.Fl xchain
.Em file ]
.Oo
.Fl xchain_build
.Em file ]
.Oo
.Fl xcertform
.Ar DER Ns | Ns Ar PEM Ns
.Oc
>
.Oo
.Fl xkeyform
.Ar DER Ns | Ns Ar PEM Ns
.Oc
>
.Oo
.Fl CAfile
.Em file ]
.Oo
.Fl no-CAfile ]
.Oo
.Fl CApath
.Em dir ]
.Oo
.Fl no-CApath ]
.Oo
.Fl CAstore
.Em uri ]
.Oo
.Fl no-CAstore ]
.Oo
.Fl bugs ]
.Oo
.Fl no_comp ]
.Oo
.Fl comp ]
.Oo
.Fl no_ticket ]
.Oo
.Fl serverpref ]
.Oo
.Fl client_renegotiation ]
.Oo
.Fl legacy_renegotiation ]
.Oo
.Fl no_renegotiation ]
.Oo
.Fl no_resumption_on_reneg ]
.Oo
.Fl legacy_server_connect ]
.Oo
.Fl no_legacy_server_connect ]
.Oo
.Fl no_etm ]
.Oo
.Fl allow_no_dhe_kex ]
.Oo
.Fl prefer_no_dhe_kex ]
.Oo
.Fl prioritize_chacha ]
.Oo
.Fl strict ]
.Oo
.Fl sigalgs
.Em algs ]
.Oo
.Fl client_sigalgs
.Em algs ]
.Oo
.Fl groups
.Em groups ]
.Oo
.Fl curves
.Em curves ]
.Oo
.Fl named_curve
.Em curve ]
.Oo
.Fl cipher
.Em ciphers ]
.Oo
.Fl ciphersuites
.Em 1.3ciphers ]
.Oo
.Fl min_protocol
.Em minprot ]
.Oo
.Fl max_protocol
.Em maxprot ]
.Oo
.Fl record_padding
.Em padding ]
.Oo
.Fl debug_broken_protocol ]
.Oo
.Fl no_middlebox ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl ssl_client_engine
.Em id ]
.Oo
.Fl allow_proxy_certs ]
.Oo
.Fl attime
.Em timestamp ]
.Oo
.Fl no_check_time ]
.Oo
.Fl check_ss_sig ]
.Oo
.Fl crl_check ]
.Oo
.Fl crl_check_all ]
.Oo
.Fl explicit_policy ]
.Oo
.Fl extended_crl ]
.Oo
.Fl ignore_critical ]
.Oo
.Fl inhibit_any ]
.Oo
.Fl inhibit_map ]
.Oo
.Fl partial_chain ]
.Oo
.Fl policy
.Em arg ]
.Oo
.Fl policy_check ]
.Oo
.Fl policy_print ]
.Oo
.Fl purpose
.Em purpose ]
.Oo
.Fl suiteB_128 ]
.Oo
.Fl suiteB_128_only ]
.Oo
.Fl suiteB_192 ]
.Oo
.Fl trusted_first ]
.Oo
.Fl no_alt_chains ]
.Oo
.Fl use_deltas ]
.Oo
.Fl auth_level
.Em num ]
.Oo
.Fl verify_depth
.Em num ]
.Oo
.Fl verify_email
.Em email ]
.Oo
.Fl verify_hostname
.Em hostname ]
.Oo
.Fl verify_ip
.Em ip ]
.Oo
.Fl verify_name
.Em name ]
.Oo
.Fl x509_strict ]
.Oo
.Fl issuer_checks ]
.Oo
.Fl enable_server_rpk ]
.Oo
.Fl enable_client_rpk ]
.Oo
.Em host Ns : Ns Em port ]
.Sh DESCRIPTION
This command implements a generic SSL/TLS client which connects to a
remote host using SSL/TLS. It is a
.Em very
useful diagnostic tool for SSL servers.
.Sh OPTIONS
In addition to the options below, this command also supports the common
and client only options documented in the "Supported Command Line
Commands" section of the
.Xr SSL_CONF_cmd 3
manual page.
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -ssl_config Em section
Use the specified section of the configuration file to configure the
.Sy SSL_CTX
object.
.It Sy -connect Em host Ns : Ns Em port
This specifies the host and optional port to connect to.
It is possible to select the host and port using the optional target
positional argument instead.
If neither this nor the target positional argument are specified then an
attempt is made to connect to the local host on port 4433. If the host
string is an IPv6 address, it must be enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
.It Sy -host Em hostname
Host to connect to; use
.Sy -connect
instead.
.It Sy -port Em port
Connect to the specified port; use
.Sy -connect
instead.
.It Sy -bind Em host Ns : Ns Em port
This specifies the host address and or port to bind as the source for
the connection.
For Unix-domain sockets the port is ignored and the host is used as the
source socket address.
If the host string is an IPv6 address, it must be enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
.It Sy -proxy Em host Ns : Ns Em port
When used with the
.Sy -connect
flag, the program uses the host and port specified with this flag and
issues an HTTP CONNECT command to connect to the desired server.
If the host string is an IPv6 address, it must be enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
.It Sy -proxy_user Em userid
When used with the
.Sy -proxy
flag, the program will attempt to authenticate with the specified proxy
using basic (base64) authentication.
NB: Basic authentication is insecure; the credentials are sent to the
proxy in easily reversible base64 encoding before any TLS/SSL session is
established.
Therefore, these credentials are easily recovered by anyone able to
sniff/trace the network.
Use with caution.
.It Sy -proxy_pass Em arg
The proxy password source, used with the
.Sy -proxy_user
flag.
For more information about the format of
.Sy arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -unix Em path
Connect over the specified Unix-domain socket.
.It Sy -4
Use IPv4 only.
.It Sy -6
Use IPv6 only.
.It Sy -quic
Connect using the QUIC protocol.
If specified then the
.Sy -alpn
option must also be provided.
.It Sy -servername Em name
Set the TLS SNI (Server Name Indication) extension in the ClientHello
message to the given value.
If
.Sy -servername
is not provided, the TLS SNI extension will be populated with the name
given to
.Sy -connect
if it follows a DNS name format.
If
.Sy -connect
is not provided either, the SNI is set to "localhost".
This is the default since OpenSSL 1.1.1.
.Pp
Even though SNI should normally be a DNS name and not an IP address, if
.Sy -servername
is provided then that name will be sent, regardless of whether it is a
DNS name or not.
.Pp
This option cannot be used in conjunction with
.Sy -noservername .
.It Sy -noservername
Suppresses sending of the SNI (Server Name Indication) extension in the
ClientHello message.
Cannot be used in conjunction with the
.Sy -servername
or
.Sy -dane_tlsa_domain
options.
.It Sy -cert Em filename
The client certificate to use, if one is requested by the server.
The default is not to use a certificate.
.Pp
The chain for the client certificate may be specified using
.Sy -cert_chain .
.It Sy -certform Sy DER Ns | Ns Sy PEM Ns | Ns Sy P12
The client certificate file format to use; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -cert_chain
A file or URI of untrusted certificates to use when attempting to build
the certificate chain related to the certificate specified via the
.Sy -cert
option.
The input can be in PEM, DER, or PKCS#12 format.
.It Sy -build_chain
Specify whether the application should build the client certificate
chain to be provided to the server.
.It Sy -CRL Em filename
CRL file to use to check the server's certificate.
.It Sy -CRLform Sy DER Ns | Ns Sy PEM
The CRL file format; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -crl_download
Download CRL from distribution points in the certificate.
Note that this option is ignored if
.Sy -crl_check
option is not provided.
Note that the maximum size of CRL is limited by
.Xr X509_CRL_load_http 3
function.
.It Sy -key Em filename Ns | Ns Em uri
The client private key to use.
If not specified then the certificate file will be used to read also the
key.
.It Sy -keyform Sy DER Ns | Ns Sy PEM Ns | Ns Sy P12 Ns | Ns Sy ENGINE
The key format; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -pass Em arg
the private key and certificate file password source.
For more information about the format of
.Em arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -verify Em depth
The verify depth to use.
This specifies the maximum length of the server certificate chain and
turns on server certificate verification.
Unless the
.Sy -verify_return_error
option is given, the verify operation continues after errors so all the
problems with a certificate chain can be seen.
As a side effect the connection will never fail due to a server
certificate verify failure.
.Pp
By default, validation of server certificates and their chain is done
w.r.t.
the (D)TLS Server
.Pf ( Qo Li sslserver Qc )
purpose.
For details see
.Xr openssl-verification-options 1 .
.It Sy -verify_return_error
Turns on server certificate verification, like with
.Sy -verify ,
but returns verification errors instead of continuing.
This will typically abort the handshake with a fatal error.
.It Sy -verify_quiet
Limit verify output to only errors.
.It Sy -verifyCAfile Em filename
A file in PEM format containing trusted certificates to use for
verifying the server's certificate.
.It Sy -verifyCApath Em dir
A directory containing trusted certificates to use for verifying the
server's certificate.
This directory must be in "hash format", see
.Xr openssl-verify 1
for more information.
.It Sy -verifyCAstore Em uri
The URI of a store containing trusted certificates to use for verifying
the server's certificate.
.It Sy -chainCAfile Em file
A file in PEM format containing trusted certificates to use when
attempting to build the client certificate chain.
.It Sy -chainCApath Em directory
A directory containing trusted certificates to use for building the
client certificate chain provided to the server.
This directory must be in "hash format", see
.Xr openssl-verify 1
for more information.
.It Sy -chainCAstore Em uri
The URI of a store containing trusted certificates to use when
attempting to build the client certificate chain.
The URI may indicate a single certificate, as well as a collection of
them.
With URIs in the
.Qo Li file: Qc
scheme, this acts as
.Sy -chainCAfile
or
.Sy -chainCApath ,
depending on if the URI indicates a directory or a single file.
See
.Xr ossl_store-file 7
for more information on the
.Qo Li file: Qc
scheme.
.It Sy -requestCAfile Em file
A file containing a list of certificates whose subject names will be
sent to the server in the
.Sy certificate_authorities
extension.
Only supported for TLS 1.3
.It Sy -dane_tlsa_domain Em domain
Enable RFC6698/RFC7671 DANE TLSA authentication and specify the TLSA
base domain which becomes the default SNI hint and the primary reference
identifier for hostname checks.
This must be used in combination with at least one instance of the
.Sy -dane_tlsa_rrdata
option below.
.Pp
When DANE authentication succeeds, the diagnostic output will include
the lowest (closest to 0) depth at which a TLSA record authenticated a
chain certificate.
When that TLSA record is a "2 1 0" trust anchor public key that signed
(rather than matched) the top-most certificate of the chain, the result
is reported as "TA public key verified".
Otherwise, either the TLSA record "matched TA certificate" at a positive
depth or else "matched EE certificate" at depth 0.
.It Sy -dane_tlsa_rrdata Em rrdata
Use one or more times to specify the RRDATA fields of the DANE TLSA
RRset associated with the target service.
The
.Em rrdata
value is specified in "presentation form", that is four whitespace
separated fields that specify the usage, selector, matching type and
associated data, with the last of these encoded in hexadecimal.
Optional whitespace is ignored in the associated data field.
For example:
.Bd -literal
  $ openssl s_client -brief -starttls smtp \e
    -connect smtp.example.com:25 \e
    -dane_tlsa_domain smtp.example.com \e
    -dane_tlsa_rrdata "2 1 1
      B111DD8A1C2091A89BD4FD60C57F0716CCE50FEEFF8137CDBEE0326E 02CF362B" \e
    -dane_tlsa_rrdata "2 1 1
      60B87575447DCBA2A36B7D11AC09FB24A9DB406FEE12D2CC90180517 616E8A18"
  ...
  Verification: OK
  Verified peername: smtp.example.com
  DANE TLSA 2 1 1 ...ee12d2cc90180517616e8a18 matched TA certificate at depth 1
  ...
.Ed
.It Sy -dane_ee_no_namechecks
This disables server name checks when authenticating via DANE-EE(3) TLSA
records.
For some applications, primarily web browsers, it is not safe to disable
name checks due to "unknown key share" attacks, in which a malicious
server can convince a client that a connection to a victim server is
instead a secure connection to the malicious server.
The malicious server may then be able to violate cross-origin scripting
restrictions.
Thus, despite the text of RFC7671, name checks are by default enabled
for DANE-EE(3) TLSA records, and can be disabled in applications where
it is safe to do so.
In particular, SMTP and XMPP clients should set this option as SRV and
MX records already make it possible for a remote domain to redirect
client connections to any server of its choice, and in any case SMTP and
XMPP clients do not execute scripts downloaded from remote servers.
.It Sy -reconnect
Reconnects to the same server 5 times using the same session ID, this
can be used as a test that session caching is working.
.It Sy -showcerts
Displays the server certificate list as sent by the server: it only
consists of certificates the server has sent (in the order the server
has sent them).
It is
.Sy not
a verified chain.
.It Sy -prexit
Print session information when the program exits.
This will always attempt to print out information even if the connection
fails.
Normally information will only be printed out once if the connection
succeeds.
This option is useful because the cipher in use may be renegotiated or
the connection may fail because a client certificate is required or is
requested only after an attempt is made to access a certain URL. Note:
the output produced by this option is not always accurate because a
connection might never have been established.
.It Sy -no-interactive
This flag can be used to run the client in a non-interactive mode.
.It Sy -state
Prints out the SSL session states.
.It Sy -debug
Print extensive debugging information including a hex dump of all
traffic.
.It Sy -nocommands
Do not use interactive command letters.
.It Sy -adv
Use advanced command mode.
.It Sy -security_debug
Enable security debug messages.
.It Sy -security_debug_verbose
Output more security debug output.
.It Sy -msg
Show protocol messages.
.It Sy -timeout
Enable send/receive timeout on DTLS connections.
.It Sy -mtu Em size
Set MTU of the link layer to the specified size.
.It Sy -no_ems
Disable Extended master secret negotiation.
.It Sy -keymatexport Em label
Export keying material using the specified label.
.It Sy -keymatexportlen Em len
Export the specified number of bytes of keying material; default is 20.
.Pp
Show all protocol messages with hex dump.
.It Sy -trace
Show verbose trace output of protocol messages.
.It Sy -msgfile Em filename
File to send output of
.Sy -msg
or
.Sy -trace
to, default standard output.
.It Sy -nbio_test
Tests nonblocking I/O
.It Sy -nbio
Turns on nonblocking I/O
.It Sy -crlf
This option translated a line feed from the terminal into CR+LF as
required by some servers.
.It Sy -ign_eof
Inhibit shutting down the connection when end of file is reached in the
input.
This implicitly turns on
.Sy -nocommands
as well.
.It Sy -quiet
Inhibit printing of session and certificate information.
This implicitly turns on
.Sy -ign_eof
and
.Sy -nocommands
as well.
.It Sy -no_ign_eof
Shut down the connection when end of file is reached in the input.
Can be used to override the implicit
.Sy -ign_eof
after
.Sy -quiet .
.It Sy -psk_identity Em identity
Use the PSK identity
.Em identity
when using a PSK cipher suite.
The default value is "Client_identity" (without the quotes).
.It Sy -psk Em key
Use the PSK key
.Em key
when using a PSK cipher suite.
The key is given as a hexadecimal number without leading 0x, for example
-psk 1a2b3c4d.
This option must be provided in order to use a PSK cipher.
.It Sy -psk_session Em file
Use the pem encoded SSL_SESSION data stored in
.Em file
as the basis of a PSK. Note that this will only work if TLSv1.3 is
negotiated.
.It Sy -sctp
Use SCTP for the transport protocol instead of UDP in DTLS. Must be used
in conjunction with
.Sy -dtls ,
.Sy -dtls1
or
.Sy -dtls1_2 .
This option is only available where OpenSSL has support for SCTP
enabled.
.It Sy -sctp_label_bug
Use the incorrect behaviour of older OpenSSL implementations when
computing endpoint-pair shared secrets for DTLS/SCTP. This allows
communication with older broken implementations but breaks
interoperability with correct implementations.
Must be used in conjunction with
.Sy -sctp .
This option is only available where OpenSSL has support for SCTP
enabled.
.It Sy -fallback_scsv
Send TLS_FALLBACK_SCSV in the ClientHello.
.It Sy -async
Switch on asynchronous mode.
Cryptographic operations will be performed asynchronously.
This will only have an effect if an asynchronous capable engine is also
used via the
.Sy -engine
option.
For test purposes the dummy async engine (dasync) can be used (if
available).
.It Sy -maxfraglen Em len
Enable Maximum Fragment Length Negotiation; allowed values are
.Qo Li 512 Qc ,
.Qo Li 1024 Qc ,
.Qo Li 2048 Qc ,
and
.Qo Li 4096 Qc .
.It Sy -max_send_frag Em int
The maximum size of data fragment to send.
See
.Xr SSL_CTX_set_max_send_fragment 3
for further information.
.It Sy -split_send_frag Em int
The size used to split data for encrypt pipelines.
If more data is written in one go than this value then it will be split
into multiple pipelines, up to the maximum number of pipelines defined
by max_pipelines.
This only has an effect if a suitable cipher suite has been negotiated,
an engine that supports pipelining has been loaded, and max_pipelines is
greater than 1. See
.Xr SSL_CTX_set_split_send_fragment 3
for further information.
.It Sy -max_pipelines Em int
The maximum number of encrypt/decrypt pipelines to be used.
This will only have an effect if an engine has been loaded that supports
pipelining (e.g.
the dasync engine) and a suitable cipher suite has been negotiated.
The default value is 1. See
.Xr SSL_CTX_set_max_pipelines 3
for further information.
.It Sy -read_buf Em int
The default read buffer size to be used for connections.
This will only have an effect if the buffer size is larger than the size
that would otherwise be used and pipelining is in use (see
.Xr SSL_CTX_set_default_read_buffer_len 3
for further information).
.It Sy -ignore_unexpected_eof
Some TLS implementations do not send the mandatory close_notify alert on
shutdown.
If the application tries to wait for the close_notify alert but the peer
closes the connection without sending it, an error is generated.
When this option is enabled the peer does not need to send the
close_notify alert and a closed connection will be treated as if the
close_notify alert was received.
For more information on shutting down a connection, see
.Xr SSL_shutdown 3 .
.It Sy -no_tx_cert_comp
Disables support for sending TLSv1.3 compressed certificates.
.It Sy -no_rx_cert_comp
Disables support for receiving TLSv1.3 compressed certificate.
.It Sy -brief
Only provide a brief summary of connection parameters instead of the
normal verbose output.
.It Sy -starttls Em protocol
Send the protocol-specific message(s) to switch to TLS for
communication.
.Em protocol
is a keyword for the intended protocol.
Currently, the only supported keywords are "smtp", "pop3", "imap",
"ftp", "xmpp", "xmpp-server", "irc", "postgres", "mysql", "lmtp",
"nntp", "sieve" and "ldap".
.It Sy -xmpphost Em hostname
This option, when used with "-starttls xmpp" or "-starttls xmpp-server",
specifies the host for the "to" attribute of the stream element.
If this option is not specified, then the host specified with "-connect"
will be used.
.Pp
This option is an alias of the
.Sy -name
option for "xmpp" and "xmpp-server".
.It Sy -name Em hostname
This option is used to specify hostname information for various
protocols used with
.Sy -starttls
option.
Currently only "xmpp", "xmpp-server", "smtp" and "lmtp" can utilize this
.Sy -name
option.
.Pp
If this option is used with "-starttls xmpp" or "-starttls xmpp-server",
if specifies the host for the "to" attribute of the stream element.
If this option is not specified, then the host specified with "-connect"
will be used.
.Pp
If this option is used with "-starttls lmtp" or "-starttls smtp", it
specifies the name to use in the "LMTP LHLO" or "SMTP EHLO" message,
respectively.
If this option is not specified, then "mail.example.com" will be used.
.It Sy -tlsextdebug
Print out a hex dump of any TLS extensions received from the server.
.It Sy -sess_out Em filename
Output SSL session to
.Em filename .
.It Sy -sess_in Em filename
Load SSL session from
.Em filename .
The client will attempt to resume a connection from this session.
.It Sy -serverinfo Em types
A list of comma-separated TLS Extension Types (numbers between 0 and
65535). Each type will be sent as an empty ClientHello TLS Extension.
The server's response (if any) will be encoded and displayed as a PEM
file.
.It Sy -status
Sends a certificate status request to the server (OCSP stapling).
The server response (if any) is printed out.
.It Sy -alpn Em protocols Ns , Sy -nextprotoneg Em protocols
These flags enable the Enable the Application-Layer Protocol Negotiation
or Next Protocol Negotiation (NPN) extension, respectively.
ALPN is the IETF standard and replaces NPN. The
.Em protocols
list is a comma-separated list of protocol names that the client should
advertise support for.
The list should contain the most desirable protocols first.
Protocol names are printable ASCII strings, for example "http/1.1" or
"spdy/3". An empty list of protocols is treated specially and will cause
the client to advertise support for the TLS extension but disconnect
just after receiving ServerHello with a list of server supported
protocols.
The flag
.Sy -nextprotoneg
cannot be specified if
.Sy -tls1_3
is used.
.It Sy -ct Ns , Sy -noct
Use one of these two options to control whether Certificate Transparency
(CT) is enabled
.Pf ( Sy -ct )
or disabled
.Pf ( Sy -noct Ns ).
If CT is enabled, signed certificate timestamps (SCTs) will be requested
from the server and reported at handshake completion.
.Pp
Enabling CT also enables OCSP stapling, as this is one possible delivery
method for SCTs.
.It Sy -ctlogfile
A file containing a list of known Certificate Transparency logs.
See
.Xr SSL_CTX_set_ctlog_list_file 3
for the expected file format.
.It Sy -keylogfile Em file
Appends TLS secrets to the specified keylog file such that external
programs (like Wireshark) can decrypt TLS connections.
.It Sy -early_data Em file
Reads the contents of the specified file and attempts to send it as
early data to the server.
This will only work with resumed sessions that support early data and
when the server accepts the early data.
.It Sy -enable_pha
For TLSv1.3 only, send the Post-Handshake Authentication extension.
This will happen whether or not a certificate has been provided via
.Sy -cert .
.It Sy -use_srtp Em value
Offer SRTP key management, where
.Sy value
is a colon-separated profile list.
.It Sy -srpuser Em value
Set the SRP username to the specified value.
This option is deprecated.
.It Sy -srppass Em value
Set the SRP password to the specified value.
This option is deprecated.
.It Sy -srp_lateuser
SRP username for the second ClientHello message.
This option is deprecated.
.It Sy -srp_moregroups No This option is deprecated.
Tolerate other than the known
.Sy g
and
.Sy N
values.
.It Sy -srp_strength Em number
Set the minimal acceptable length, in bits, for
.Sy N .
This option is deprecated.
.It Sy -ktls
Enable Kernel TLS for sending and receiving.
This option was introduced in OpenSSL 3.2.0. Kernel TLS is off by
default as of OpenSSL 3.2.0.
.It Sy -tfo
Enable creation of connections via TCP fast open (RFC7413).
.It Sy -no_ssl3 Ns , Sy -no_tls1 Ns , Sy -no_tls1_1 Ns , Sy -no_tls1_2 Ns , Sy -no_tls1_3 Ns , Sy -ssl3 Ns , Sy -tls1 Ns , Sy -tls1_1 Ns , Sy -tls1_2 Ns , Sy -tls1_3
See
.Xr openssl 1 .
.It Sy -dtls Ns , Sy -dtls1 Ns , Sy -dtls1_2
These specify the use of DTLS instead of TLS. See
.Xr openssl 1 .
.It Sy -nameopt Em option
This specifies how the subject or issuer names are displayed.
See
.Xr openssl-namedisplay-options 1
for details.
.It Sy -xkey Em infile Ns , Sy -xcert Em file Ns , Sy -xchain Em file Ns , Sy -xchain_build Em file Ns , Sy -xcertform Sy DER Ns | Ns Sy PEM Ns , Sy -xkeyform Sy DER Ns | Ns Sy PEM
Set extended certificate verification options.
See
.Xr openssl-verification-options 1
for details.
.It Sy -CAfile Em file Ns , Sy -no-CAfile Ns , Sy -CApath Em dir Ns , Sy -no-CApath Ns , Sy -CAstore Em uri Ns , Sy -no-CAstore
See
.Xr openssl-verification-options 1
for details.
.It Sy -bugs Ns , Sy -comp Ns , Sy -no_comp Ns , Sy -no_ticket Ns , Sy -serverpref Ns , Sy -client_renegotiation Ns , Sy -legacy_renegotiation Ns , Sy -no_renegotiation Ns , Sy -no_resumption_on_reneg Ns , Sy -legacy_server_connect Ns , Sy -no_legacy_server_connect Ns , Sy -no_etm Sy -allow_no_dhe_kex Ns , Sy -prefer_no_dhe_kex Ns , Sy -prioritize_chacha Ns , Sy -strict Ns , Sy -sigalgs Em algs Ns , Sy -client_sigalgs Em algs Ns , Sy -groups Em groups Ns , Sy -curves Em curves Ns , Sy -named_curve Em curve Ns , Sy -cipher Em ciphers Ns , Sy -ciphersuites Em 1.3ciphers Ns , Sy -min_protocol Em minprot Ns , Sy -max_protocol Em maxprot Ns , Sy -record_padding Em padding Ns , Sy -debug_broken_protocol Ns , Sy -no_middlebox
See
.Xr SSL_CONF_cmd 3
for details.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -ssl_client_engine Em id
Specify engine to be used for client certificate operations.
.It Sy -allow_proxy_certs Ns , Sy -attime Ns , Sy -no_check_time Ns , Sy -check_ss_sig Ns , Sy -crl_check Ns , Sy -crl_check_all Ns , Sy -explicit_policy Ns , Sy -extended_crl Ns , Sy -ignore_critical Ns , Sy -inhibit_any Ns , Sy -inhibit_map Ns , Sy -no_alt_chains Ns , Sy -partial_chain Ns , Sy -policy Ns , Sy -policy_check Ns , Sy -policy_print Ns , Sy -purpose Ns , Sy -suiteB_128 Ns , Sy -suiteB_128_only Ns , Sy -suiteB_192 Ns , Sy -trusted_first Ns , Sy -use_deltas Ns , Sy -auth_level Ns , Sy -verify_depth Ns , Sy -verify_email Ns , Sy -verify_hostname Ns , Sy -verify_ip Ns , Sy -verify_name Ns , Sy -x509_strict Sy -issuer_checks
Set various options of certificate chain verification.
See
.Xr openssl-verification-options 1
for details.
.Pp
Verification errors are displayed, for debugging, but the command will
proceed unless the
.Sy -verify_return_error
option is used.
.It Sy -enable_server_rpk
Enable support for receiving raw public keys (RFC7250) from the server.
Use of X.509 certificates by the server becomes optional, and servers
that support raw public keys may elect to use them.
Servers that don't support raw public keys or prefer to use X.509
certificates can still elect to send X.509 certificates as usual.
.It Sy -enable_client_rpk
Enable support for sending raw public keys (RFC7250) to the server.
A raw public key will be sent by the client, if solicited by the server,
provided a suitable key and public certificate pair is configured.
Some servers may nevertheless not request any client credentials, or may
request a certificate.
.It Em host Ns : Ns Em port
Rather than providing
.Sy -connect ,
the target host and optional port may be provided as a single positional
argument after all options.
If neither this nor
.Sy -connect
are provided, falls back to attempting to connect to
.Em localhost
on port
.Em 4433 .
If the host string is an IPv6 address, it must be enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
.El
.Sh CONNECTED COMMANDS (BASIC)
If a connection is established with an SSL/TLS server then any data
received from the server is displayed and any key presses will be sent
to the server.
If end of file is reached then the connection will be closed down.
.Pp
When used interactively (which means neither
.Sy -quiet
nor
.Sy -ign_eof
have been given), and neither of
.Sy -adv
or
.Sy -nocommands
are given then "Basic" command mode is entered.
In this mode certain commands are recognized which perform special
operations.
These commands are a letter which must appear at the start of a line.
All further data after the initial letter on the line is ignored.
The commands are listed below.
.Bl -tag -width Ds
.It Sy Q
End the current SSL connection and exit.
.It Sy R
Renegotiate the SSL session (TLSv1.2 and below only).
.It Sy C
Attempt to reconnect to the server using a resumption handshake.
.It Sy k
Send a key update message to the server (TLSv1.3 only)
.It Sy K
Send a key update message to the server and request one back (TLSv1.3
only)
.El
.Sh CONNECTED COMMANDS (ADVANCED)
If
.Sy -adv
has been given then "advanced" command mode is entered.
As with basic mode, if a connection is established with an SSL/TLS
server then any data received from the server is displayed and any key
presses will be sent to the server.
If end of file is reached then the connection will be closed down.
.Pp
Special commands can be supplied by enclosing them in braces, e.g.
"{help}" or "{quit}". These commands can appear anywhere in the text
entered into s_client, but they are not sent to the server.
Some commands can take an argument by ending the command name with ":"
and then providing the argument, e.g.
"{keyup:req}". Some commands are only available when certain protocol
versions have been negotiated.
.Pp
If a newline appears at the end of a line entered into s_client then
this is also sent to the server.
If a command appears on a line on its own with no other text on the same
line, then the newline is suppressed and not sent to the server.
.Pp
The following commands are recognised.
.Bl -tag -width Ds
.It Sy help
Prints out summary help text about the available commands.
.It Sy quit
Close the connection to the peer
.It Sy reconnect
Reconnect to the peer and attempt a resumption handshake
.It Sy keyup
Send a Key Update message.
TLSv1.3 only.
This command takes an optional argument.
If the argument "req" is supplied then the peer is also requested to
update its keys.
Otherwise if "noreq" is supplied the peer is not requested to update its
keys.
The default is "req".
.It Sy reneg
Initiate a renegotiation with the server.
(D)TLSv1.2 or below only.
.It Sy fin
Indicate FIN on the current stream.
QUIC only.
Once FIN has been sent any further text entered for this stream is
ignored.
.El
.Sh NOTES
This command can be used to debug SSL servers.
To connect to an SSL HTTP server the command:
.Bd -literal
 openssl s_client -connect servername:443
.Ed
.Pp
would typically be used (https uses port 443). If the connection
succeeds then an HTTP command can be given such as "GET /" to retrieve a
web page.
.Pp
If the handshake fails then there are several possible causes, if it is
nothing obvious like no client certificate then the
.Sy -bugs ,
.Sy -ssl3 ,
.Sy -tls1 ,
.Sy -no_ssl3 ,
.Sy -no_tls1
options can be tried in case it is a buggy server.
In particular you should play with these options
.Sy before
submitting a bug report to an OpenSSL mailing list.
.Pp
A frequent problem when attempting to get client certificates working is
that a web client complains it has no certificates or gives an empty
list to choose from.
This is normally because the server is not sending the clients
certificate authority in its "acceptable CA list" when it requests a
certificate.
By using this command, the CA list can be viewed and checked.
However, some servers only request client authentication after a
specific URL is requested.
To obtain the list in this case it is necessary to use the
.Sy -prexit
option and send an HTTP request for an appropriate page.
.Pp
If a certificate is specified on the command line using the
.Sy -cert
option it will not be used unless the server specifically requests a
client certificate.
Therefore, merely including a client certificate on the command line is
no guarantee that the certificate works.
.Pp
If there are problems verifying a server certificate then the
.Sy -showcerts
option can be used to show all the certificates sent by the server.
.Pp
This command is a test tool and is designed to continue the handshake
after any certificate verification errors.
As a result it will accept any certificate chain (trusted or not) sent
by the peer.
Non-test applications should
.Sy not
do this as it makes them vulnerable to a MITM attack.
This behaviour can be changed by with the
.Sy -verify_return_error
option: any verify errors are then returned aborting the handshake.
.Pp
The
.Sy -bind
option may be useful if the server or a firewall requires connections to
come from some particular address and or port.
.Ss Note on Non-Interactive Use
When
.Sy s_client
is run in a non-interactive environment (e.g., a cron job or a script
without a valid
.Em stdin Ns ),
it may close the connection prematurely, especially with TLS 1.3. To
prevent this, you can use the
.Sy -ign_eof
flag, which keeps
.Sy s_client
running even after reaching EOF from
.Em stdin .
.Pp
For example:
.Bd -literal
 openssl s_client -connect <server address>:443 -tls1_3
                  -sess_out /path/to/tls_session_params_file
                  -ign_eof </dev/null
.Ed
.Pp
However, relying solely on
.Sy -ign_eof
can lead to issues if the server keeps the connection open, expecting
the client to close first.
In such cases, the client may hang indefinitely.
This behavior is not uncommon, particularly with protocols where the
server waits for a graceful disconnect from the client.
.Pp
For example, when connecting to an SMTP server, the session may pause if
the server expects a QUIT command before closing:
.Bd -literal
 $ openssl s_client -brief -ign_eof -starttls smtp
                    -connect <server address>:25 </dev/null
 CONNECTION ESTABLISHED
 Protocol version: TLSv1.3
 Ciphersuite: TLS_AES_256_GCM_SHA384
 ...
 250 CHUNKING
 [long pause]
.Ed
.Pp
To avoid such hangs, it's better to use an application-level command to
initiate a clean disconnect.
For SMTP, you can send a QUIT command:
.Bd -literal
 printf 'QUIT\er\en' | openssl s_client -connect <server address>:25
                                      -starttls smtp -brief -ign_eof
.Ed
.Pp
Similarly, for HTTP/1.1 connections, including a `Connection: close`
header ensures the server closes the connection after responding:
.Bd -literal
 printf 'GET / HTTP/1.1\er\enHost: <server address>\er\enConnection: close\er\en\er\en'
     | openssl s_client -connect <server address>:443 -brief
.Ed
.Pp
These approaches help manage the connection closure gracefully and
prevent hangs caused by the server waiting for the client to initiate
the disconnect.
.Sh BUGS
Because this program has a lot of options and also because some of the
techniques used are rather old, the C source for this command is rather
hard to read and not a model of how things should be done.
A typical SSL client program would be much simpler.
.Pp
The
.Sy -prexit
option is a bit of a hack.
We should really report information whenever a session is renegotiated.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-sess_id 1 ,
.Xr openssl-s_server 1 ,
.Xr openssl-ciphers 1 ,
.Xr SSL_CONF_cmd 3 ,
.Xr SSL_CTX_set_max_send_fragment 3 ,
.Xr SSL_CTX_set_split_send_fragment 3 ,
.Xr SSL_CTX_set_max_pipelines 3 ,
.Xr ossl_store-file 7
.Sh HISTORY
The
.Sy -no_alt_chains
option was added in OpenSSL 1.1.0. The
.Sy -name
option was added in OpenSSL 1.1.1.
.Pp
The
.Sy -certform
option has become obsolete in OpenSSL 3.0.0 and has no effect.
.Pp
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Pp
The
.Sy -enable_client_rpk ,
.Sy -enable_server_rpk ,
.Sy -no_rx_cert_comp ,
.Sy -no_tx_cert_comp ,
and
.Sy -tfo
options were added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
