.Dd 2025-09-30
.Dt OPENSSL-TS 1ossl
.Os
.Sh NAME
.Nm openssl-ts
.Nd Time Stamping Authority command
.Sh SYNOPSIS
.Nm openssl
.Ar ts
.Fl help
.Pp
.Nm openssl
.Ar ts
.Fl query
.Oo
.Fl config
.Em configfile ]
.Oo
.Fl data
.Em file_to_hash ]
.Oo
.Fl digest
.Em digest_bytes ]
.Oo
.Ar Em digest ]
.Oo
.Fl tspolicy
.Em object_id ]
.Oo
.Fl no_nonce ]
.Oo
.Fl cert ]
.Oo
.Fl in
.Em request.tsq ]
.Oo
.Fl out
.Em request.tsq ]
.Oo
.Fl text ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Pp
.Nm openssl
.Ar ts
.Fl reply
.Oo
.Fl config
.Em configfile ]
.Oo
.Fl section
.Em tsa_section ]
.Oo
.Fl queryfile
.Em request.tsq ]
.Oo
.Fl passin
.Em password_src ]
.Oo
.Fl signer
.Em tsa_cert.pem ]
.Oo
.Fl inkey
.Em filename Ns | Ns Em uri ]
.Oo
.Ar Em digest ]
.Oo
.Fl chain
.Em certs_file.pem ]
.Oo
.Fl tspolicy
.Em object_id ]
.Oo
.Fl in
.Em response.tsr ]
.Oo
.Fl token_in ]
.Oo
.Fl out
.Em response.tsr ]
.Oo
.Fl token_out ]
.Oo
.Fl text ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Pp
.Nm openssl
.Ar ts
.Fl verify
.Oo
.Fl data
.Em file_to_hash ]
.Oo
.Fl digest
.Em digest_bytes ]
.Oo
.Fl queryfile
.Em request.tsq ]
.Oo
.Fl in
.Em response.tsr ]
.Oo
.Fl token_in ]
.Oo
.Fl untrusted
.Em files Ns | Ns Em uris ]
.Oo
.Fl CAfile
.Em file ]
.Oo
.Fl CApath
.Em dir ]
.Oo
.Fl CAstore
.Em uri ]
.Oo
.Fl allow_proxy_certs ]
.Oo
.Fl attime
.Em timestamp ]
.Oo
.Fl no_check_time ]
.Oo
.Fl check_ss_sig ]
.Oo
.Fl crl_check ]
.Oo
.Fl crl_check_all ]
.Oo
.Fl explicit_policy ]
.Oo
.Fl extended_crl ]
.Oo
.Fl ignore_critical ]
.Oo
.Fl inhibit_any ]
.Oo
.Fl inhibit_map ]
.Oo
.Fl partial_chain ]
.Oo
.Fl policy
.Em arg ]
.Oo
.Fl policy_check ]
.Oo
.Fl policy_print ]
.Oo
.Fl purpose
.Em purpose ]
.Oo
.Fl suiteB_128 ]
.Oo
.Fl suiteB_128_only ]
.Oo
.Fl suiteB_192 ]
.Oo
.Fl trusted_first ]
.Oo
.Fl no_alt_chains ]
.Oo
.Fl use_deltas ]
.Oo
.Fl auth_level
.Em num ]
.Oo
.Fl verify_depth
.Em num ]
.Oo
.Fl verify_email
.Em email ]
.Oo
.Fl verify_hostname
.Em hostname ]
.Oo
.Fl verify_ip
.Em ip ]
.Oo
.Fl verify_name
.Em name ]
.Oo
.Fl x509_strict ]
.Oo
.Fl issuer_checks ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Sh DESCRIPTION
This command is a basic Time Stamping Authority (TSA) client and server
application as specified in RFC 3161 (Time-Stamp Protocol, TSP). A TSA
can be part of a PKI deployment and its role is to provide long term
proof of the existence of a certain datum before a particular time.
Here is a brief description of the protocol:
.Bl -enum
.It
The TSA client computes a one-way hash value for a data file and sends
the hash to the TSA.
.It
The TSA attaches the current date and time to the received hash value,
signs them and sends the timestamp token back to the client.
By creating this token the TSA certifies the existence of the original
data file at the time of response generation.
.It
The TSA client receives the timestamp token and verifies the signature
on it.
It also checks if the token contains the same hash value that it had
sent to the TSA.
.El
.Pp
There is one DER encoded protocol data unit defined for transporting a
timestamp request to the TSA and one for sending the timestamp response
back to the client.
This command has three main functions: creating a timestamp request
based on a data file, creating a timestamp response based on a request,
verifying if a response corresponds to a particular request or a data
file.
.Pp
There is no support for sending the requests/responses automatically
over HTTP or TCP yet as suggested in RFC 3161. The users must send the
requests either by ftp or e-mail.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -query
Generate a TS query.
For details see
.Sx Timestamp Request generation .
.It Sy -reply
Generate a TS reply.
For details see
.Sx Timestamp Response generation .
.It Sy -verify
Verify a TS response.
For details see
.Sx Timestamp Response verification .
.El
.Ss Timestamp Request generation
The
.Sy -query
command can be used for creating and printing a timestamp request with
the following options:
.Bl -tag -width Ds
.It Sy -config Em configfile
The configuration file to use.
Optional; for a description of the default value, see
.Xr openssl 1 .
.It Sy -data Em file_to_hash
The data file for which the timestamp request needs to be created.
stdin is the default if neither the
.Sy -data
nor the
.Sy -digest
parameter is specified.
(Optional)
.It Sy -digest Em digest_bytes
It is possible to specify the message imprint explicitly without the
data file.
The imprint must be specified in a hexadecimal format, two characters
per byte, the bytes optionally separated by colons (e.g.
1A:F6:01:... or 1AF601...). The number of bytes must match the message
digest algorithm in use.
(Optional)
.It Sy - Ns Em digest
The message digest to apply to the data file.
Any digest supported by the
.Xr openssl-dgst 1
command can be used.
The default is SHA-256. (Optional)
.It Sy -tspolicy Em object_id
The policy that the client expects the TSA to use for creating the
timestamp token.
Either the dotted OID notation or OID names defined in the config file
can be used.
If no policy is requested the TSA will use its own default policy.
(Optional)
.It Sy -no_nonce
No nonce is specified in the request if this option is given.
Otherwise, a 64-bit long pseudo-random nonce is included in the request.
It is recommended to use a nonce to protect against replay attacks.
(Optional)
.It Sy -cert
The TSA is expected to include its signing certificate in the response.
(Optional)
.It Sy -in Em request.tsq
This option specifies a previously created timestamp request in DER
format that will be printed into the output file.
Useful when you need to examine the content of a request in
human-readable format.
(Optional)
.It Sy -out Em request.tsq
Name of the output file to which the request will be written.
Default is stdout.
(Optional)
.It Sy -text
If this option is specified the output is human-readable text format
instead of DER. (Optional)
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.El
.Ss Timestamp Response generation
A timestamp response (TimeStampResp) consists of a response status and
the timestamp token itself (ContentInfo), if the token generation was
successful.
The
.Sy -reply
command is for creating a timestamp response or timestamp token based on
a request and printing the response/token in human-readable format.
If
.Sy -token_out
is not specified the output is always a timestamp response
(TimeStampResp), otherwise it is a timestamp token (ContentInfo).
.Bl -tag -width Ds
.It Sy -config Em configfile
The configuration file to use.
Optional; for a description of the default value, see
.Xr openssl 1 .
See
.Sx CONFIGURATION FILE OPTIONS
for configurable variables.
.It Sy -section Em tsa_section
The name of the config file section containing the settings for the
response generation.
If not specified the default TSA section is used, see
.Sx CONFIGURATION FILE OPTIONS
for details.
(Optional)
.It Sy -queryfile Em request.tsq
The name of the file containing a DER encoded timestamp request.
(Optional)
.It Sy -passin Em password_src
Specifies the password source for the private key of the TSA. See
description in
.Xr openssl 1 .
(Optional)
.It Sy -signer Em tsa_cert.pem
The signer certificate of the TSA in PEM format.
The TSA signing certificate must have exactly one extended key usage
assigned to it: timeStamping.
The extended key usage must also be critical, otherwise the certificate
is going to be refused.
Overrides the
.Sy signer_cert
variable of the config file.
(Optional)
.It Sy -inkey Em filename Ns | Ns Em uri
The signer private key of the TSA in PEM format.
Overrides the
.Sy signer_key
config file option.
(Optional)
.It Sy - Ns Em digest
Signing digest to use.
Overrides the
.Sy signer_digest
config file option.
(Mandatory unless specified in the config file)
.It Sy -chain Em certs_file.pem
The collection of certificates in PEM format that will all be included
in the response in addition to the signer certificate if the
.Sy -cert
option was used for the request.
This file is supposed to contain the certificate chain for the signer
certificate from its issuer upwards.
The
.Sy -reply
command does not build a certificate chain automatically.
(Optional)
.It Sy -tspolicy Em object_id
The default policy to use for the response unless the client explicitly
requires a particular TSA policy.
The OID can be specified either in dotted notation or with its name.
Overrides the
.Sy default_policy
config file option.
(Optional)
.It Sy -in Em response.tsr
Specifies a previously created timestamp response or timestamp token (if
.Sy -token_in
is also specified) in DER format that will be written to the output
file.
This option does not require a request, it is useful e.g.
when you need to examine the content of a response or token or you want
to extract the timestamp token from a response.
If the input is a token and the output is a timestamp response a default
'granted' status info is added to the token.
(Optional)
.It Sy -token_in
This flag can be used together with the
.Sy -in
option and indicates that the input is a DER encoded timestamp token
(ContentInfo) instead of a timestamp response (TimeStampResp).
(Optional)
.It Sy -out Em response.tsr
The response is written to this file.
The format and content of the file depends on other options (see
.Sy -text ,
.Sy -token_out Ns ).
The default is stdout.
(Optional)
.It Sy -token_out
The output is a timestamp token (ContentInfo) instead of timestamp
response (TimeStampResp).
(Optional)
.It Sy -text
If this option is specified the output is human-readable text format
instead of DER. (Optional)
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Ss Timestamp Response verification
The
.Sy -verify
command is for verifying if a timestamp response or timestamp token is
valid and matches a particular timestamp request or data file.
The
.Sy -verify
command does not use the configuration file.
.Bl -tag -width Ds
.It Sy -data Em file_to_hash
The response or token must be verified against file_to_hash.
The file is hashed with the message digest algorithm specified in the
token.
The
.Sy -digest
and
.Sy -queryfile
options must not be specified with this one.
(Optional)
.It Sy -digest Em digest_bytes
The response or token must be verified against the message digest
specified with this option.
The number of bytes must match the message digest algorithm specified in
the token.
The
.Sy -data
and
.Sy -queryfile
options must not be specified with this one.
(Optional)
.It Sy -queryfile Em request.tsq
The original timestamp request in DER format.
The
.Sy -data
and
.Sy -digest
options must not be specified with this one.
(Optional)
.It Sy -in Em response.tsr
The timestamp response that needs to be verified in DER format.
(Mandatory)
.It Sy -token_in
This flag can be used together with the
.Sy -in
option and indicates that the input is a DER encoded timestamp token
(ContentInfo) instead of a timestamp response (TimeStampResp).
(Optional)
.It Sy -untrusted Em files Ns | Ns Em uris
A set of additional untrusted certificates which may be needed when
building the certificate chain for the TSA's signing certificate.
These do not need to contain the TSA signing certificate and
intermediate CA certificates as far as the response already includes
them.
(Optional)
.Pp
Multiple sources may be given, separated by commas and/or whitespace.
Each file may contain multiple certificates.
.It Sy -CAfile Em file Ns , Sy -CApath Em dir Ns , Sy -CAstore Em uri
See
.Xr openssl-verification-options 1
for details.
At least one of
.Sy -CAfile ,
.Sy -CApath
or
.Sy -CAstore
must be specified.
.It Sy -allow_proxy_certs Ns , Sy -attime Ns , Sy -no_check_time Ns , Sy -check_ss_sig Ns , Sy -crl_check Ns , Sy -crl_check_all Ns , Sy -explicit_policy Ns , Sy -extended_crl Ns , Sy -ignore_critical Ns , Sy -inhibit_any Ns , Sy -inhibit_map Ns , Sy -no_alt_chains Ns , Sy -partial_chain Ns , Sy -policy Ns , Sy -policy_check Ns , Sy -policy_print Ns , Sy -purpose Ns , Sy -suiteB_128 Ns , Sy -suiteB_128_only Ns , Sy -suiteB_192 Ns , Sy -trusted_first Ns , Sy -use_deltas Ns , Sy -auth_level Ns , Sy -verify_depth Ns , Sy -verify_email Ns , Sy -verify_hostname Ns , Sy -verify_ip Ns , Sy -verify_name Ns , Sy -x509_strict Sy -issuer_checks
Set various options of certificate chain verification.
See
.Xr openssl-verification-options 1
for details.
.Pp
Any verification errors cause the command to exit.
.El
.Sh CONFIGURATION FILE OPTIONS
The
.Sy -query
and
.Sy -reply
commands make use of a configuration file.
See
.Xr config 5
for a general description of the syntax of the config file.
The
.Sy -query
command uses only the symbolic OID names section and it can work without
it.
However, the
.Sy -reply
command needs the config file for its operation.
.Pp
When there is a command line switch equivalent of a variable the switch
always overrides the settings in the config file.
.Bl -tag -width Ds
.It Sy tsa No section, Sy default_tsa
This is the main section and it specifies the name of another section
that contains all the options for the
.Sy -reply
command.
This default section can be overridden with the
.Sy -section
command line switch.
(Optional)
.It Sy oid_file
This specifies a file containing additional
.Sy OBJECT IDENTIFIERS .
Each line of the file should consist of the numerical form of the object
identifier followed by whitespace then the short name followed by
whitespace and finally the long name.
(Optional)
.It Sy oid_section
This specifies a section in the configuration file containing extra
object identifiers.
Each line should consist of the short name of the object identifier
followed by
.Sy =
and the numerical form.
The short and long names are the same when this option is used.
(Optional)
.It Sy RANDFILE
At startup the specified file is loaded into the random number
generator, and at exit 256 bytes will be written to it.
(Note: Using a RANDFILE is not necessary anymore, see the
.Sx HISTORY
section.
.It Sy serial
The name of the file containing the hexadecimal serial number of the
last timestamp response created.
This number is incremented by 1 for each response.
If the file does not exist at the time of response generation a new file
is created with serial number 1. (Mandatory)
.It Sy crypto_device
Specifies the OpenSSL engine that will be set as the default for all
available algorithms.
The default value is built-in, you can specify any other engines
supported by OpenSSL (e.g.
use chil for the NCipher HSM). (Optional)
.It Sy signer_cert
TSA signing certificate in PEM format.
The same as the
.Sy -signer
command line option.
(Optional)
.It Sy certs
A file containing a set of PEM encoded certificates that need to be
included in the response.
The same as the
.Sy -chain
command line option.
(Optional)
.It Sy signer_key
The private key of the TSA in PEM format.
The same as the
.Sy -inkey
command line option.
(Optional)
.It Sy signer_digest
Signing digest to use.
The same as the
.Sy - Ns Em digest
command line option.
(Mandatory unless specified on the command line)
.It Sy default_policy
The default policy to use when the request does not mandate any policy.
The same as the
.Sy -tspolicy
command line option.
(Optional)
.It Sy other_policies
Comma separated list of policies that are also acceptable by the TSA and
used only if the request explicitly specifies one of them.
(Optional)
.It Sy digests
The list of message digest algorithms that the TSA accepts.
At least one algorithm must be specified.
(Mandatory)
.It Sy accuracy
The accuracy of the time source of the TSA in seconds, milliseconds and
microseconds.
E.g.
secs:1, millisecs:500, microsecs:100. If any of the components is
missing zero is assumed for that field.
(Optional)
.It Sy clock_precision_digits
Specifies the maximum number of digits, which represent the fraction of
seconds, that need to be included in the time field.
The trailing zeros must be removed from the time, so there might
actually be fewer digits, or no fraction of seconds at all.
Supported only on UNIX platforms.
The maximum value is 6, default is 0. (Optional)
.It Sy ordering
If this option is yes the responses generated by this TSA can always be
ordered, even if the time difference between two responses is less than
the sum of their accuracies.
Default is no.
(Optional)
.It Sy tsa_name
Set this option to yes if the subject name of the TSA must be included
in the TSA name field of the response.
Default is no.
(Optional)
.It Sy ess_cert_id_chain
The SignedData objects created by the TSA always contain the certificate
identifier of the signing certificate in a signed attribute (see RFC
2634, Enhanced Security Services).
If this variable is set to no, only this signing certificate identifier
is included in the SigningCertificate signed attribute.
If this variable is set to yes and the
.Sy certs
variable or the
.Sy -chain
option is specified then the certificate identifiers of the chain will
also be included, where the
.Sy -chain
option overrides the
.Sy certs
variable.
Default is no.
(Optional)
.It Sy ess_cert_id_alg
This option specifies the hash function to be used to calculate the
TSA's public key certificate identifier.
Default is sha256. (Optional)
.El
.Sh EXAMPLES
All the examples below presume that
.Sy OPENSSL_CONF
is set to a proper configuration file, e.g.
the example configuration file
.Pa openssl/apps/openssl.cnf
will do.
.Ss Timestamp Request
To create a timestamp request for
.Pa design1.txt
with SHA-256 digest, without nonce and policy, and without requirement
for a certificate in the response:
.Bd -literal
  openssl ts -query -data design1.txt -no_nonce \e
        -out design1.tsq
.Ed
.Pp
To create a similar timestamp request with specifying the message
imprint explicitly:
.Bd -literal
  openssl ts -query -digest b7e5d3f93198b38379852f2c04e78d73abdd0f4b \e
         -no_nonce -out design1.tsq
.Ed
.Pp
To print the content of the previous request in human readable format:
.Bd -literal
  openssl ts -query -in design1.tsq -text
.Ed
.Pp
To create a timestamp request which includes the SHA-512 digest of
.Pa design2.txt ,
requests the signer certificate and nonce, and specifies a policy id
(assuming the tsa_policy1 name is defined in the OID section of the
config file):
.Bd -literal
  openssl ts -query -data design2.txt -sha512 \e
        -tspolicy tsa_policy1 -cert -out design2.tsq
.Ed
.Ss Timestamp Response
Before generating a response a signing certificate must be created for
the TSA that contains the
.Sy timeStamping
critical extended key usage extension without any other key usage
extensions.
You can add this line to the user certificate section of the config file
to generate a proper certificate;
.Bd -literal
   extendedKeyUsage = critical,timeStamping
.Ed
.Pp
See
.Xr openssl-req 1 ,
.Xr openssl-ca 1 ,
and
.Xr openssl-x509 1
for instructions.
The examples below assume that
.Pa cacert.pem
contains the certificate of the CA,
.Pa tsacert.pem
is the signing certificate issued by
.Pa cacert.pem
and
.Pa tsakey.pem
is the private key of the TSA.
.Pp
To create a timestamp response for a request:
.Bd -literal
  openssl ts -reply -queryfile design1.tsq -inkey tsakey.pem \e
        -signer tsacert.pem -out design1.tsr
.Ed
.Pp
If you want to use the settings in the config file you could just write:
.Bd -literal
  openssl ts -reply -queryfile design1.tsq -out design1.tsr
.Ed
.Pp
To print a timestamp reply to stdout in human readable format:
.Bd -literal
  openssl ts -reply -in design1.tsr -text
.Ed
.Pp
To create a timestamp token instead of timestamp response:
.Bd -literal
  openssl ts -reply -queryfile design1.tsq -out design1_token.der -token_out
.Ed
.Pp
To print a timestamp token to stdout in human readable format:
.Bd -literal
  openssl ts -reply -in design1_token.der -token_in -text -token_out
.Ed
.Pp
To extract the timestamp token from a response:
.Bd -literal
  openssl ts -reply -in design1.tsr -out design1_token.der -token_out
.Ed
.Pp
To add 'granted' status info to a timestamp token thereby creating a
valid response:
.Bd -literal
  openssl ts -reply -in design1_token.der -token_in -out design1.tsr
.Ed
.Ss Timestamp Verification
To verify a timestamp reply against a request:
.Bd -literal
  openssl ts -verify -queryfile design1.tsq -in design1.tsr \e
        -CAfile cacert.pem -untrusted tsacert.pem
.Ed
.Pp
To verify a timestamp reply that includes the certificate chain:
.Bd -literal
  openssl ts -verify -queryfile design2.tsq -in design2.tsr \e
        -CAfile cacert.pem
.Ed
.Pp
To verify a timestamp token against the original data file:
.Bd -literal
  openssl ts -verify -data design2.txt -in design2.tsr \e
        -CAfile cacert.pem
.Ed
.Pp
To verify a timestamp token against a message imprint:
.Bd -literal
  openssl ts -verify -digest b7e5d3f93198b38379852f2c04e78d73abdd0f4b \e
         -in design2.tsr -CAfile cacert.pem
.Ed
.Pp
You could also look at the 'test' directory for more examples.
.Sh BUGS
.Bl -bullet
.It
No support for timestamps over SMTP, though it is quite easy to
implement an automatic e-mail based TSA with
.Xr procmail 1
and
.Xr perl 1 .
HTTP server support is provided in the form of a separate apache module.
HTTP client support is provided by
.Xr tsget 1 .
Pure TCP/IP protocol is not supported.
.It
The file containing the last serial number of the TSA is not locked when
being read or written.
This is a problem if more than one instance of
.Xr openssl 1
is trying to create a timestamp response at the same time.
This is not an issue when using the apache server module, it does proper
locking.
.It
Look for the FIXME word in the source files.
.It
The source code should really be reviewed by somebody else, too.
.It
More testing is needed, I have done only some basic tests (see
test/testtsa).
.El
.Sh HISTORY
OpenSSL 1.1.1 introduced a new random generator (CSPRNG) with an
improved seeding mechanism.
The new seeding mechanism makes it unnecessary to define a RANDFILE for
saving and restoring randomness.
This option is retained mainly for compatibility reasons.
.Pp
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr tsget 1 ,
.Xr openssl-req 1 ,
.Xr openssl-x509 1 ,
.Xr openssl-ca 1 ,
.Xr openssl-genrsa 1 ,
.Xr config 5 ,
.Xr ossl_store-file 7
.Sh COPYRIGHT
Copyright 2006-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
