.Dd 2025-09-30
.Dt OPENSSL-NAMEDISPLAY-OPTIONS 1ossl
.Os
.Sh NAME
.Nm openssl-namedisplay-options
.Nd Distinguished name display options
.Sh SYNOPSIS
.Nm openssl
.Em command
.Oo
.Em options
\&...
.Oc
.Oo
.Em parameters
\&...
.Oc
.Sh DESCRIPTION
OpenSSL provides fine-grain control over how the subject and issuer DN's
are displayed.
This is specified by using the
.Sy -nameopt
option, which takes a comma-separated list of options from the following
set.
An option may be preceded by a minus sign,
.Qo Li - Qc ,
to turn it off.
The first four option arguments are the most commonly used.
.Pp
The default value is
.Qo Li esc_ctrl,utf8,dump_unknown,dump_der,sep_comma_plus_space,sname Qc .
.Sh OPTIONS
.Ss Name Format Option Arguments
The DN output format can be fine tuned with the following flags.
.Bl -tag -width Ds
.It Sy compat
Display the name using an old format from previous OpenSSL versions.
.It Sy RFC2253
Display the name using the format defined in RFC 2253. It is equivalent
to
.Sy esc_2253 ,
.Sy esc_ctrl ,
.Sy esc_msb ,
.Sy utf8 ,
.Sy dump_nostr ,
.Sy dump_unknown ,
.Sy dump_der ,
.Sy sep_comma_plus ,
.Sy dn_rev
and
.Sy sname .
.It Sy oneline
Display the name in one line, using a format that is more readable RFC
2253. It is equivalent to
.Sy esc_2253 ,
.Sy esc_ctrl ,
.Sy esc_msb ,
.Sy utf8 ,
.Sy dump_nostr ,
.Sy dump_der ,
.Sy use_quote ,
.Sy sep_comma_plus_space ,
.Sy space_eq
and
.Sy sname
options.
.It Sy multiline
Display the name using multiple lines.
It is equivalent to
.Sy esc_ctrl ,
.Sy esc_msb ,
.Sy sep_multiline ,
.Sy space_eq ,
.Sy lname
and
.Sy align .
.It Sy esc_2253
Escape the "special" characters in a field, as required by RFC 2253.
That is, any of the characters
.Qo Li ,+"\(la\(ra; Qc ,
.Qo Li # Qc
at the beginning of a string and leading or trailing spaces.
.It Sy esc_2254
Escape the "special" characters in a field as required by RFC 2254 in a
field.
That is, the
.Sy NUL
character and of
.Qo Li ()* Qc .
.It Sy esc_ctrl
Escape non-printable ASCII characters, codes less than 0x20 (space) or
greater than 0x7F (DELETE). They are displayed using RFC 2253
.Qo Li \eXX Qc
notation where
.Sy XX
are the two hex digits representing the character value.
.It Sy esc_msb
Escape any characters with the most significant bit set, that is with
values larger than 127, as described in
.Sy esc_ctrl .
.It Sy use_quote
Escapes some characters by surrounding the entire string with quotation
marks,
.Qo Li \(dq Qc .
Without this option, individual special characters are preceded with a
backslash character,
.Qo Li \e Qc .
.It Sy utf8
Convert all strings to UTF-8 format first as required by RFC 2253. If
the output device is UTF-8 compatible, then using this option (and not
setting
.Sy esc_msb )
may give the correct display of multibyte characters.
If this option is not set, then multibyte characters larger than 0xFF
will be output as
.Qo Li \eUXXXX Qc
for 16 bits or
.Qo Li \eWXXXXXXXX Qc
for 32 bits.
In addition, any UTF8Strings will be converted to their character form
first.
.It Sy ignore_type
This option does not attempt to interpret multibyte characters in any
way.
That is, the content octets are merely dumped as though one octet
represents each character.
This is useful for diagnostic purposes but will result in rather odd
looking output.
.It Sy show_type
Display the type of the ASN1 character string before the value, such as
.Qo Li BMPSTRING: Hello World Qc .
.It Sy dump_der
Any fields that would be output in hex format are displayed using the
DER encoding of the field.
If not set, just the content octets are displayed.
Either way, the
.Sy #XXXX...
format of RFC 2253 is used.
.It Sy dump_nostr
Dump non-character strings, such as ASN.1
.Sy OCTET STRING .
If this option is not set, then non character string types will be
displayed as though each content octet represents a single character.
.It Sy dump_all
Dump all fields.
When this used with
.Sy dump_der ,
this allows the DER encoding of the structure to be unambiguously
determined.
.It Sy dump_unknown
Dump any field whose OID is not recognised by OpenSSL.
.It Sy sep_comma_plus Ns , Sy sep_comma_plus_space Ns , Sy sep_semi_plus_space Ns , Sy sep_multiline
Specify the field separators.
The first word is used between the Relative Distinguished Names (RDNs)
and the second is between multiple Attribute Value Assertions (AVAs).
Multiple AVAs are very rare and their use is discouraged.
The options ending in "space" additionally place a space after the
separator to make it more readable.
The
.Sy sep_multiline
starts each field on its own line, and uses "plus space" for the AVA
separator.
It also indents the fields by four characters.
The default value is
.Sy sep_comma_plus_space .
.It Sy dn_rev
Reverse the fields of the DN as required by RFC 2253. This also reverses
the order of multiple AVAs in a field, but this is permissible as there
is no ordering on values.
.It Sy nofname Ns , Sy sname Ns , Sy lname Ns , Sy oid
Specify how the field name is displayed.
.Sy nofname
does not display the field at all.
.Sy sname
uses the "short name" form (CN for commonName for example).
.Sy lname
uses the long form.
.Sy oid
represents the OID in numerical form and is useful for diagnostic
purpose.
.It Sy align
Align field values for a more readable output.
Only usable with
.Sy sep_multiline .
.It Sy space_eq
Places spaces round the equal sign,
.Qo Li = Qc ,
character which follows the field name.
.El
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
