.Dd 2025-09-30
.Dt OPENSSL-SRP 1ossl
.Os
.Sh NAME
.Nm openssl-srp
.Nd maintain SRP password file
.Sh SYNOPSIS
.Nm openssl srp
.Oo
.Fl help ]
.Oo
.Fl verbose ]
.Oo
.Fl add ]
.Oo
.Fl modify ]
.Oo
.Fl delete ]
.Oo
.Fl list ]
.Oo
.Fl name
.Em section ]
.Oo
.Fl srpvfile
.Em file ]
.Oo
.Fl gn
.Em identifier ]
.Oo
.Fl userinfo
.Em text ]
.Oo
.Fl passin
.Em arg ]
.Oo
.Fl passout
.Em arg ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Fl config
.Em configfile ]
.Oo
.Em user
.Oc
\&...
.Sh DESCRIPTION
This command is deprecated.
It is used to maintain an SRP (secure remote password) file.
At most one of the
.Sy -add ,
.Sy -modify ,
.Sy -delete ,
and
.Sy -list
options can be specified.
These options take zero or more usernames as parameters and perform the
appropriate operation on the SRP file.
For
.Sy -list ,
if no
.Em user
is given then all users are displayed.
.Pp
The configuration file to use, and the section within the file, can be
specified with the
.Sy -config
and
.Sy -name
flags, respectively.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Display an option summary.
.It Sy -verbose
Generate verbose output while processing.
.It Sy -add
Add a user and SRP verifier.
.It Sy -modify
Modify the SRP verifier of an existing user.
.It Sy -delete
Delete user from verifier file.
.It Sy -list
List users.
.It Sy -name
The particular SRP definition to use.
.It Sy -srpvfile Em file
If the config file is not specified,
.Sy -srpvfile
can be used to specify the file to operate on.
.It Sy -gn
Specifies the
.Sy g
and
.Sy N
values, using one of the strengths defined in IETF RFC 5054.
.It Sy -userinfo
specifies additional information to add when adding or modifying a user.
.It Sy -passin Em arg Ns , Sy -passout Em arg
The password source for the input and output file.
For more information about the format of
.Sy arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -config Em configfile
See
.Xr openssl 1 .
.Pp
.Pf [ Sy -rand
.Em files ]
.Pf [ Sy -writerand
.Em file ]
.El
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2017-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
