.Dd 2025-09-30
.Dt OPENSSL-ENGINE 1ossl
.Os
.Sh NAME
.Nm openssl-engine
.Nd load and query engines
.Sh SYNOPSIS
.Nm openssl engine
.Oo
.Fl help ]
.Oo
.Fl v ]
.Oo
.Fl vv ]
.Oo
.Fl vvv ]
.Oo
.Fl vvvv ]
.Oo
.Fl c ]
.Oo
.Fl t ]
.Oo
.Fl tt ]
.Oo
.Fl pre
.Em command ]
\&...
.Oo
.Fl post
.Em command ]
\&...
.Oo
.Em engine
.Oc
\&...
.Sh DESCRIPTION
This command has been deprecated.
Providers should be used instead of engines.
.Pp
This command is used to query the status and capabilities of the
specified
.Em engine Ns s.
Engines may be specified before and after all other command-line flags.
Only those specified are queried.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Display an option summary.
.It Sy -v Sy -vv Sy -vvv Sy -vvvv
Provides information about each specified engine.
The first flag lists all the possible run-time control commands; the
second adds a description of each command; the third adds the input
flags, and the final option adds the internal input flags.
.It Sy -c
Lists the capabilities of each engine.
.It Sy -t
Tests if each specified engine is available, and displays the answer.
.It Sy -tt
Displays an error trace for any unavailable engine.
.It Sy -pre Em command
.It Sy -post Em command
Command-line configuration of engines.
The
.Sy -pre
command is given to the engine before it is loaded and the
.Sy -post
command is given after the engine is loaded.
The
.Em command
is of the form
.Em cmd Ns : Ns Em val
where
.Em cmd
is the command, and
.Em val
is the value for the command.
See the example below.
.Pp
These two options are cumulative, so they may be given more than once in
the same command.
.El
.Sh EXAMPLES
To list all the commands available to a dynamic engine:
.Bd -literal
 $ openssl engine -t -tt -vvvv dynamic
 (dynamic) Dynamic engine loading support
      [ unavailable ]
      SO_PATH: Specifies the path to the new ENGINE shared library
           (input flags): STRING
      NO_VCHECK: Specifies to continue even if version checking fails (boolean)
           (input flags): NUMERIC
      ID: Specifies an ENGINE id name for loading
           (input flags): STRING
      LIST_ADD: Whether to add a loaded ENGINE to the internal list (0=no,1=yes,2=mandatory)
           (input flags): NUMERIC
      DIR_LOAD: Specifies whether to load from 'DIR_ADD' directories (0=no,1=yes,2=mandatory)
           (input flags): NUMERIC
      DIR_ADD: Adds a directory from which ENGINEs can be loaded
           (input flags): STRING
      LOAD: Load up the ENGINE specified by other settings
           (input flags): NO_INPUT
.Ed
.Pp
To list the capabilities of the
.Sy rsax
engine:
.Bd -literal
 $ openssl engine -c
 (rsax) RSAX engine support
  [RSA]
 (dynamic) Dynamic engine loading support
.Ed
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Sy OPENSSL_ENGINES
The path to the engines directory.
.El
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr config 5
.Sh HISTORY
This command was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2016-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
