.Dd 2025-09-30
.Dt OPENSSL 1ossl
.Os
.Sh NAME
.Nm openssl
.Nd OpenSSL command line program
.Sh SYNOPSIS
.Nm openssl
.Em command
.Oo
.Em options
\&...
.Oc
.Oo
.Em parameters
\&...
.Oc
.Pp
.Nm openssl
.Ar no- Ns Em XXX
.Oo
.Em options
.Oc
.Pp
.Nm openssl
.Fl help
|
.Fl version
.Sh DESCRIPTION
OpenSSL is a cryptography toolkit implementing the Secure Sockets Layer
(SSL) and Transport Layer Security (TLS) network protocols and related
cryptography standards required by them.
.Pp
The
.Sy openssl
program is a command line program for using the various cryptography
functions of OpenSSL's
.Sy crypto
library from the shell.
It can be used for
.Bd -literal
 o  Creation and management of private keys, public keys and parameters
 o  Public key cryptographic operations
 o  Creation of X.509 certificates, CSRs and CRLs
 o  Calculation of Message Digests and Message Authentication Codes
 o  Encryption and Decryption with Ciphers
 o  SSL/TLS Client and Server Tests
 o  Handling of S/MIME signed or encrypted mail
 o  Timestamp requests, generation and verification
.Ed
.Sh COMMAND SUMMARY
The
.Sy openssl
program provides a rich variety of commands
.Pf ( Em command
in the
.Sx SYNOPSIS
above).
Each command can have many options and argument parameters, shown above
as
.Em options
and
.Em parameters .
.Pp
Detailed documentation and use cases for most standard subcommands are
available (e.g.,
.Xr openssl-x509 1 Ns ).
The subcommand
.Xr openssl-list 1
may be used to list subcommands.
.Pp
The command
.Sy no- Ns Em XXX
tests whether a command of the specified name is available.
If no command named
.Em XXX
exists, it returns 0 (success) and prints
.Sy no- Ns Em XXX ;
otherwise it returns 1 and prints
.Em XXX .
In both cases, the output goes to
.Sy stdout
and nothing is printed to
.Sy stderr .
Additional command line arguments are always ignored.
Since for each cipher there is a command of the same name, this provides
an easy way for shell scripts to test for the availability of ciphers in
the
.Sy openssl
program.
.Pf ( Sy no- Ns Em XXX
is not able to detect pseudo-commands such as
.Sy quit ,
.Sy list ,
or
.Sy no- Ns Em XXX
itself.)
.Ss Configuration Option
Many commands use an external configuration file for some or all of
their arguments and have a
.Sy -config
option to specify that file.
The default name of the file is
.Pa openssl.cnf
in the default certificate storage area, which can be determined from
the
.Xr openssl-version 1
command using the
.Sy -d
or
.Sy -a
option.
The environment variable
.Sy OPENSSL_CONF
can be used to specify a different file location or to disable loading a
configuration (using the empty string).
.Pp
Among others, the configuration file can be used to load modules and to
specify parameters for generating certificates and random numbers.
See
.Xr config 5
for details.
.Ss Standard Commands
.Bl -tag -width Ds
.It Sy asn1parse
Parse an ASN.1 sequence.
.It Sy ca
Certificate Authority (CA) Management.
.It Sy ciphers
Cipher Suite Description Determination.
.It Sy cms
CMS (Cryptographic Message Syntax) command.
.It Sy crl
Certificate Revocation List (CRL) Management.
.It Sy crl2pkcs7
CRL to PKCS#7 Conversion.
.It Sy dgst
Message Digest calculation.
MAC calculations are superseded by
.Xr openssl-mac 1 .
.It Sy dhparam
Generation and Management of Diffie-Hellman Parameters.
Superseded by
.Xr openssl-genpkey 1
and
.Xr openssl-pkeyparam 1 .
.It Sy dsa
DSA Data Management.
.It Sy dsaparam
DSA Parameter Generation and Management.
Superseded by
.Xr openssl-genpkey 1
and
.Xr openssl-pkeyparam 1 .
.It Sy ec
EC (Elliptic curve) key processing.
.It Sy ecparam
EC parameter manipulation and generation.
.It Sy enc
Encryption, decryption, and encoding.
.It Sy engine
Engine (loadable module) information and manipulation.
.It Sy errstr
Error Number to Error String Conversion.
.It Sy fipsinstall
FIPS configuration installation.
.It Sy gendsa
Generation of DSA Private Key from Parameters.
Superseded by
.Xr openssl-genpkey 1
and
.Xr openssl-pkey 1 .
.It Sy genpkey
Generation of Private Key or Parameters.
.It Sy genrsa
Generation of RSA Private Key.
Superseded by
.Xr openssl-genpkey 1 .
.It Sy help
Display information about a command's options.
.It Sy info
Display diverse information built into the OpenSSL libraries.
.It Sy kdf
Key Derivation Functions.
.It Sy list
List algorithms and features.
.It Sy mac
Message Authentication Code Calculation.
.It Sy nseq
Create or examine a Netscape certificate sequence.
.It Sy ocsp
Online Certificate Status Protocol command.
.It Sy passwd
Generation of hashed passwords.
.It Sy pkcs12
PKCS#12 Data Management.
.It Sy pkcs7
PKCS#7 Data Management.
.It Sy pkcs8
PKCS#8 format private key conversion command.
.It Sy pkey
Public and private key management.
.It Sy pkeyparam
Public key algorithm parameter management.
.It Sy pkeyutl
Public key algorithm cryptographic operation command.
.It Sy prime
Compute prime numbers.
.It Sy rand
Generate pseudo-random bytes.
.It Sy rehash
Create symbolic links to certificate and CRL files named by the hash
values.
.It Sy req
PKCS#10 X.509 Certificate Signing Request (CSR) Management.
.It Sy rsa
RSA key management.
.It Sy rsautl
RSA command for signing, verification, encryption, and decryption.
Superseded by
.Xr openssl-pkeyutl 1 .
.It Sy s_client
This implements a generic SSL/TLS client which can establish a
transparent connection to a remote server speaking SSL/TLS. It's
intended for testing purposes only and provides only rudimentary
interface functionality but internally uses mostly all functionality of
the OpenSSL
.Sy ssl
library.
.It Sy s_server
This implements a generic SSL/TLS server which accepts connections from
remote clients speaking SSL/TLS. It's intended for testing purposes only
and provides only rudimentary interface functionality but internally
uses mostly all functionality of the OpenSSL
.Sy ssl
library.
It provides both an own command line oriented protocol for testing SSL
functions and a simple HTTP response facility to emulate an
SSL/TLS-aware webserver.
.It Sy s_time
SSL Connection Timer.
.It Sy sess_id
SSL Session Data Management.
.It Sy smime
S/MIME mail processing.
.It Sy speed
Algorithm Speed Measurement.
.It Sy spkac
SPKAC printing and generating command.
.It Sy srp
Maintain SRP password file.
This command is deprecated.
.It Sy storeutl
Command to list and display certificates, keys, CRLs, etc.
.It Sy ts
Time Stamping Authority command.
.It Sy verify
X.509 Certificate Verification.
See also the
.Xr openssl-verification-options 1
manual page.
.It Sy version
OpenSSL Version Information.
.It Sy x509
X.509 Certificate Data Management.
.El
.Ss Message Digest Commands
.Bl -tag -width Ds
.It Sy blake2b512
BLAKE2b-512 Digest
.It Sy blake2s256
BLAKE2s-256 Digest
.It Sy md2
MD2 Digest
.It Sy md4
MD4 Digest
.It Sy md5
MD5 Digest
.It Sy mdc2
MDC2 Digest
.It Sy rmd160
RMD-160 Digest
.It Sy sha1
SHA-1 Digest
.It Sy sha224
SHA-2 224 Digest
.It Sy sha256
SHA-2 256 Digest
.It Sy sha384
SHA-2 384 Digest
.It Sy sha512
SHA-2 512 Digest
.It Sy sha3-224
SHA-3 224 Digest
.It Sy sha3-256
SHA-3 256 Digest
.It Sy sha3-384
SHA-3 384 Digest
.It Sy sha3-512
SHA-3 512 Digest
.It Sy keccak-224
KECCAK 224 Digest
.It Sy keccak-256
KECCAK 256 Digest
.It Sy keccak-384
KECCAK 384 Digest
.It Sy keccak-512
KECCAK 512 Digest
.It Sy shake128
SHA-3 SHAKE128 Digest
.It Sy shake256
SHA-3 SHAKE256 Digest
.It Sy sm3
SM3 Digest
.El
.Ss Encryption, Decryption, and Encoding Commands
The following aliases provide convenient access to the most used
encodings and ciphers.
.Pp
Depending on how OpenSSL was configured and built, not all ciphers
listed here may be present.
See
.Xr openssl-enc 1
for more information.
.Bl -tag -width Ds
.It Sy aes128 Ns , Sy aes-128-cbc Ns , Sy aes-128-cfb Ns , Sy aes-128-ctr Ns , Sy aes-128-ecb Ns , Sy aes-128-ofb
AES-128 Cipher
.It Sy aes192 Ns , Sy aes-192-cbc Ns , Sy aes-192-cfb Ns , Sy aes-192-ctr Ns , Sy aes-192-ecb Ns , Sy aes-192-ofb
AES-192 Cipher
.It Sy aes256 Ns , Sy aes-256-cbc Ns , Sy aes-256-cfb Ns , Sy aes-256-ctr Ns , Sy aes-256-ecb Ns , Sy aes-256-ofb
AES-256 Cipher
.It Sy aria128 Ns , Sy aria-128-cbc Ns , Sy aria-128-cfb Ns , Sy aria-128-ctr Ns , Sy aria-128-ecb Ns , Sy aria-128-ofb
Aria-128 Cipher
.It Sy aria192 Ns , Sy aria-192-cbc Ns , Sy aria-192-cfb Ns , Sy aria-192-ctr Ns , Sy aria-192-ecb Ns , Sy aria-192-ofb
Aria-192 Cipher
.It Sy aria256 Ns , Sy aria-256-cbc Ns , Sy aria-256-cfb Ns , Sy aria-256-ctr Ns , Sy aria-256-ecb Ns , Sy aria-256-ofb
Aria-256 Cipher
.It Sy base64
Base64 Encoding
.It Sy bf Ns , Sy bf-cbc Ns , Sy bf-cfb Ns , Sy bf-ecb Ns , Sy bf-ofb
Blowfish Cipher
.It Sy camellia128 Ns , Sy camellia-128-cbc Ns , Sy camellia-128-cfb Ns , Sy camellia-128-ctr Ns , Sy camellia-128-ecb Ns , Sy camellia-128-ofb
Camellia-128 Cipher
.It Sy camellia192 Ns , Sy camellia-192-cbc Ns , Sy camellia-192-cfb Ns , Sy camellia-192-ctr Ns , Sy camellia-192-ecb Ns , Sy camellia-192-ofb
Camellia-192 Cipher
.It Sy camellia256 Ns , Sy camellia-256-cbc Ns , Sy camellia-256-cfb Ns , Sy camellia-256-ctr Ns , Sy camellia-256-ecb Ns , Sy camellia-256-ofb
Camellia-256 Cipher
.It Sy cast Ns , Sy cast-cbc
CAST Cipher
.It Sy cast5-cbc Ns , Sy cast5-cfb Ns , Sy cast5-ecb Ns , Sy cast5-ofb
CAST5 Cipher
.It Sy chacha20
Chacha20 Cipher
.It Sy des Ns , Sy des-cbc Ns , Sy des-cfb Ns , Sy des-ecb Ns , Sy des-ede Ns , Sy des-ede-cbc Ns , Sy des-ede-cfb Ns , Sy des-ede-ofb Ns , Sy des-ofb
DES Cipher
.It Sy des3 Ns , Sy desx Ns , Sy des-ede3 Ns , Sy des-ede3-cbc Ns , Sy des-ede3-cfb Ns , Sy des-ede3-ofb
Triple-DES Cipher
.It Sy idea Ns , Sy idea-cbc Ns , Sy idea-cfb Ns , Sy idea-ecb Ns , Sy idea-ofb
IDEA Cipher
.It Sy rc2 Ns , Sy rc2-cbc Ns , Sy rc2-cfb Ns , Sy rc2-ecb Ns , Sy rc2-ofb
RC2 Cipher
.It Sy rc4
RC4 Cipher
.It Sy rc5 Ns , Sy rc5-cbc Ns , Sy rc5-cfb Ns , Sy rc5-ecb Ns , Sy rc5-ofb
RC5 Cipher
.It Sy seed Ns , Sy seed-cbc Ns , Sy seed-cfb Ns , Sy seed-ecb Ns , Sy seed-ofb
SEED Cipher
.It Sy sm4 Ns , Sy sm4-cbc Ns , Sy sm4-cfb Ns , Sy sm4-ctr Ns , Sy sm4-ecb Ns , Sy sm4-ofb
SM4 Cipher
.El
.Sh OPTIONS
Details of which options are available depend on the specific command.
This section describes some common options with common behavior.
.Ss Program Options
These options can be specified without a command specified to get help
or version information.
.Bl -tag -width Ds
.It Sy -help
Provides a terse summary of all options.
For more detailed information, each command supports a
.Sy -help
option.
Accepts
.Sy --help
as well.
.It Sy -version
Provides a terse summary of the
.Sy openssl
program version.
For more detailed information see
.Xr openssl-version 1 .
Accepts
.Sy --version
as well.
.El
.Ss Common Options
.Bl -tag -width Ds
.It Sy -help
If an option takes an argument, the "type" of argument is also given.
.It Sy --
This terminates the list of options.
It is mostly useful if any filename parameters start with a minus sign:
.Bd -literal
 openssl verify [flags...] -- -cert1.pem...
.Ed
.El
.Ss Format Options
See
.Xr openssl-format-options 1
for manual page.
.Ss Pass Phrase Options
See the
.Xr openssl-passphrase-options 1
manual page.
.Ss Random State Options
Prior to OpenSSL 1.1.1, it was common for applications to store
information about the state of the random-number generator in a file
that was loaded at startup and rewritten upon exit.
On modern operating systems, this is generally no longer necessary as
OpenSSL will seed itself from a trusted entropy source provided by the
operating system.
These flags are still supported for special platforms or circumstances
that might require them.
.Pp
It is generally an error to use the same seed file more than once and
every use of
.Sy -rand
should be paired with
.Sy -writerand .
.Bl -tag -width Ds
.It Sy -rand Em files
A file or files containing random data used to seed the random number
generator.
Multiple files can be specified separated by an OS-dependent character.
The separator is
.Qo Li ; Qc
for MS-Windows,
.Qo Li , Qc
for OpenVMS, and
.Qo Li : Qc
for all others.
Another way to specify multiple files is to repeat this flag with
different filenames.
.It Sy -writerand Em file
Writes the seed data to the specified
.Em file
upon exit.
This file can be used in a subsequent command invocation.
.El
.Ss Certificate Verification Options
See the
.Xr openssl-verification-options 1
manual page.
.Ss Name Format Options
See the
.Xr openssl-namedisplay-options 1
manual page.
.Ss TLS Version Options
Several commands use SSL, TLS, or DTLS. By default, the commands use TLS
and clients will offer the lowest and highest protocol version they
support, and servers will pick the highest version that the client
offers that is also supported by the server.
.Pp
The options below can be used to limit which protocol versions are used,
and whether TCP (SSL and TLS) or UDP (DTLS) is used.
Note that not all protocols and flags may be available, depending on how
OpenSSL was built.
.Bl -tag -width Ds
.It Sy -ssl3 Ns , Sy -tls1 Ns , Sy -tls1_1 Ns , Sy -tls1_2 Ns , Sy -tls1_3 Ns , Sy -no_ssl3 Ns , Sy -no_tls1 Ns , Sy -no_tls1_1 Ns , Sy -no_tls1_2 Ns , Sy -no_tls1_3
These options require or disable the use of the specified SSL or TLS
protocols.
When a specific TLS version is required, only that version will be
offered or accepted.
Only one specific protocol can be given and it cannot be combined with
any of the
.Sy no_
options.
The
.Sy no_*
options do not work with
.Sy s_time
and
.Sy ciphers
commands but work with
.Sy s_client
and
.Sy s_server
commands.
.It Sy -dtls Ns , Sy -dtls1 Ns , Sy -dtls1_2
These options specify to use DTLS instead of TLS. With
.Sy -dtls ,
clients will negotiate any supported DTLS protocol version.
Use the
.Sy -dtls1
or
.Sy -dtls1_2
options to support only DTLS1.0 or DTLS1.2, respectively.
.El
.Ss Engine Options
.Bl -tag -width Ds
.It Sy -engine Em id
Load the engine identified by
.Em id
and use all the methods it implements (algorithms, key storage, etc.),
unless specified otherwise in the command-specific documentation or it
is configured to do so, as described in
.Xr config 5 .
.Pp
The engine will be used for key ids specified with
.Sy -key
and similar options when an option like
.Sy -keyform engine
is given.
.Pp
A special case is the
.Qo Li loader_attic Qc
engine, which is meant just for internal OpenSSL testing purposes and
supports loading keys, parameters, certificates, and CRLs from files.
When this engine is used, files with such credentials are read via this
engine.
Using the
.Qo Li file: Qc
schema is optional; a plain file (path) name will do.
.El
.Pp
Options specifying keys, like
.Sy -key
and similar, can use the generic OpenSSL engine key loading URI scheme
.Qo Li org.openssl.engine: Qc
to retrieve private keys and public keys.
The URI syntax is as follows, in simplified form:
.Bd -literal
    org.openssl.engine:{engineid}:{keyid}
.Ed
.Pp
Where
.Qo Li {engineid} Qc
is the identity/name of the engine, and
.Qo Li {keyid} Qc
is a key identifier that's acceptable by that engine.
For example, when using an engine that interfaces against a PKCS#11
implementation, the generic key URI would be something like this (this
happens to be an example for the PKCS#11 engine that's part of OpenSC):
.Bd -literal
    -key org.openssl.engine:pkcs11:label_some-private-key
.Ed
.Pp
As a third possibility, for engines and providers that have implemented
their own
.Xr OSSL_STORE_LOADER 3 ,
.Qo Li org.openssl.engine: Qc
should not be necessary.
For a PKCS#11 implementation that has implemented such a loader, the
PKCS#11 URI as defined in RFC 7512 should be possible to use directly:
.Bd -literal
    -key pkcs11:object=some-private-key;pin-value=1234
.Ed
.Ss Provider Options
.Bl -tag -width Ds
.It Sy -provider Em name
Load and initialize the provider identified by
.Em name .
The
.Em name
can be also a path to the provider module.
In that case the provider name will be the specified path and not just
the provider module name.
Interpretation of relative paths is platform specific.
The configured "MODULESDIR" path,
.Sy OPENSSL_MODULES
environment variable, or the path specified by
.Sy -provider-path
is prepended to relative paths.
See
.Xr provider 7
for a more detailed description.
.It Sy -provider-path Em path
Specifies the search path that is to be used for looking for providers.
Equivalently, the
.Sy OPENSSL_MODULES
environment variable may be set.
.It Sy -provparam Em [name:]key=value
Set configuration parameter
.Em key
to value
.Em val
in provider
.Em name
(optional), if
.Em name
is not specified, the setting will be applied to all loaded providers.
This option can be specified multiple times, to set multiple parameters.
Options that specify nondefault providers to load should precede this
option if the setting is intended to apply to the to be loaded
providers.
Parameters that only affect provider initialisation must, for now, be
set in the configuration file, only parameters that are also queried as
needed later have any affect when set via this interface.
Only UTF8-string-valued parameters are supported.
See the documentation of the specific provider and associated algorithms
for any supported parameters.
.It Sy -propquery Em propq
Specifies the
.Em property query clause
to be used when fetching algorithms from the loaded providers.
See
.Xr property 7
for a more detailed description.
.El
.Sh ENVIRONMENT
The OpenSSL libraries can take some configuration parameters from the
environment.
.Pp
For information about all environment variables used by the OpenSSL
libraries, such as
.Sy OPENSSL_CONF ,
.Sy OPENSSL_MODULES ,
and
.Sy OPENSSL_TRACE ,
see
.Xr openssl-env 7 .
.Pp
For information about the use of environment variables in configuration,
see
.Xr config 5 .
.Pp
For information about specific commands, see
.Xr openssl-engine 1 ,
.Xr openssl-rehash 1 ,
and
.Xr tsget 1 .
.Pp
For information about querying or specifying CPU architecture flags, see
.Xr OPENSSL_ia32cap 3 ,
.Xr OPENSSL_s390xcap 3
and
.Xr OPENSSL_riscvcap 3 .
.Sh SEE ALSO
.Xr openssl-asn1parse 1 ,
.Xr openssl-ca 1 ,
.Xr openssl-ciphers 1 ,
.Xr openssl-cms 1 ,
.Xr openssl-crl 1 ,
.Xr openssl-crl2pkcs7 1 ,
.Xr openssl-dgst 1 ,
.Xr openssl-dhparam 1 ,
.Xr openssl-dsa 1 ,
.Xr openssl-dsaparam 1 ,
.Xr openssl-ec 1 ,
.Xr openssl-ecparam 1 ,
.Xr openssl-enc 1 ,
.Xr openssl-engine 1 ,
.Xr openssl-errstr 1 ,
.Xr openssl-gendsa 1 ,
.Xr openssl-genpkey 1 ,
.Xr openssl-genrsa 1 ,
.Xr openssl-kdf 1 ,
.Xr openssl-list 1 ,
.Xr openssl-mac 1 ,
.Xr openssl-nseq 1 ,
.Xr openssl-ocsp 1 ,
.Xr openssl-passwd 1 ,
.Xr openssl-pkcs12 1 ,
.Xr openssl-pkcs7 1 ,
.Xr openssl-pkcs8 1 ,
.Xr openssl-pkey 1 ,
.Xr openssl-pkeyparam 1 ,
.Xr openssl-pkeyutl 1 ,
.Xr openssl-prime 1 ,
.Xr openssl-rand 1 ,
.Xr openssl-rehash 1 ,
.Xr openssl-req 1 ,
.Xr openssl-rsa 1 ,
.Xr openssl-rsautl 1 ,
.Xr openssl-s_client 1 ,
.Xr openssl-s_server 1 ,
.Xr openssl-s_time 1 ,
.Xr openssl-sess_id 1 ,
.Xr openssl-smime 1 ,
.Xr openssl-speed 1 ,
.Xr openssl-spkac 1 ,
.Xr openssl-srp 1 ,
.Xr openssl-storeutl 1 ,
.Xr openssl-ts 1 ,
.Xr openssl-verify 1 ,
.Xr openssl-version 1 ,
.Xr openssl-x509 1 ,
.Xr config 5 ,
.Xr crypto 7 ,
.Xr openssl-env 7 .
.Xr ssl 7 ,
.Xr x509v3_config 5
.Sh HISTORY
The
.Sy list
.Pf - Em XXX Ns Sy -algorithms
options were added in OpenSSL 1.0.0; For notes on the availability of
other commands, see their individual manual pages.
.Pp
The
.Sy -issuer_checks
option is deprecated as of OpenSSL 1.1.0 and is silently ignored.
.Pp
The
.Sy -xcertform
and
.Sy -xkeyform
options are obsolete since OpenSSL 3.0 and have no effect.
.Pp
The interactive mode, which could be invoked by running
.Qo Li openssl Qc
with no further arguments, was removed in OpenSSL 3.0, and running that
program with no arguments is now equivalent to
.Qo Li openssl help Qc .
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
