.Dd 2025-09-30
.Dt OPENSSL-PKEY 1ossl
.Os
.Sh NAME
.Nm openssl-pkey
.Nd public or private key processing command
.Sh SYNOPSIS
.Nm openssl
.Ar pkey
.Oo
.Fl help ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Fl check ]
.Oo
.Fl pubcheck ]
.Oo
.Fl in
.Em filename Ns | Ns Em uri ]
.Oo
.Fl inform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar P12 Ns | Ns Ar ENGINE ]
.Oo
.Fl passin
.Em arg ]
.Oo
.Fl pubin ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Ar Em cipher ]
.Oo
.Fl passout
.Em arg ]
.Oo
.Fl traditional ]
.Oo
.Fl pubout ]
.Oo
.Fl noout ]
.Oo
.Fl text ]
.Oo
.Fl text_pub ]
.Oo
.Fl ec_conv_form
.Em arg ]
.Oo
.Fl ec_param_enc
.Em arg ]
.Sh DESCRIPTION
This command processes public or private keys.
They can be converted between various forms and their components
printed.
.Sh OPTIONS
.Ss General options
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -check
This option checks the consistency of a key pair for both public and
private components.
.It Sy -pubcheck
This option checks the correctness of either a public key or the public
component of a key pair.
.El
.Ss Input options
.Bl -tag -width Ds
.It Sy -in Em filename Ns | Ns Em uri
This specifies the input file to read a key from or standard input if
this option is not specified.
.Pp
If the key input is encrypted and
.Sy -passin
is not given a pass phrase will be prompted for.
.It Sy -inform Sy DER Ns | Ns Sy PEM Ns | Ns Sy P12 Ns | Ns Sy ENGINE
The key input format; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -passin Em arg
The password source for the key input.
.Pp
For more information about the format of
.Sy arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -pubin
By default a private key is read from the input.
With this option a public key is read instead.
If the input contains no public key but a private key, its public part
is used.
.El
.Ss Output options
.Bl -tag -width Ds
.It Sy -out Em filename
This specifies the output file to save the encoded and/or text output of
key or standard output if this option is not specified.
The output filename can be the same as the input filename, which leads
to replacing the file contents.
Note that file I/O is not atomic.
The output file is truncated and then written.
.Pp
If any cipher option is set but no
.Sy -passout
is given then a pass phrase will be prompted for.
When password input is interrupted, the output file is not touched.
.It Sy -outform Sy DER Ns | Ns Sy PEM
The key output format; the default is
.Sy PEM .
See
.Xr openssl-format-options 1
for details.
.It Sy - Ns Em cipher
Encrypt the PEM encoded private key with the supplied cipher.
Any algorithm name accepted by
.Xr EVP_get_cipherbyname 3
is acceptable such as
.Sy aes128 .
Encryption is not supported for DER output.
.It Sy -passout Em arg
The password source for the output file.
.Pp
For more information about the format of
.Sy arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -traditional
Normally a private key is written using standard format: this is PKCS#8
form with the appropriate encryption algorithm (if any).
If the
.Sy -traditional
option is specified then the older "traditional" format is used instead.
.It Sy -pubout
By default the private and public key is output; this option restricts
the output to the public components.
This option is automatically set if the input is a public key.
.Pp
When combined with
.Sy -text ,
this is equivalent to
.Sy -text_pub .
.It Sy -noout
Do not output the key in encoded form.
.It Sy -text
Output the various key components in plain text (possibly in addition to
the PEM encoded form).
This cannot be combined with encoded output in DER format.
.It Sy -text_pub
Output in text form only the public key components (also for private
keys).
This cannot be combined with encoded output in DER format.
.It Sy -ec_conv_form Em arg
This option only applies to elliptic-curve based keys.
.Pp
This specifies how the points on the elliptic curve are converted into
octet strings.
Possible values are:
.Sy compressed
(the default value),
.Sy uncompressed
and
.Sy hybrid .
For more information regarding the point conversion forms please read
the X9.62 standard.
.Sy Note
Due to patent issues the
.Sy compressed
option is disabled by default for binary curves and can be enabled by
defining the preprocessor macro
.Sy OPENSSL_EC_BIN_PT_COMP
at compile time.
.It Sy -ec_param_enc Em arg
This option only applies to elliptic curve based public and private
keys.
.Pp
This specifies how the elliptic curve parameters are encoded.
Possible value are:
.Sy named_curve ,
i.e.
the ec parameters are specified by an OID, or
.Sy explicit
where the ec parameters are explicitly given (see RFC 3279 for the
definition of the EC parameters structures).
The default value is
.Sy named_curve .
.Sy Note
the
.Sy implicitlyCA
alternative, as specified in RFC 3279, is currently not implemented in
OpenSSL.
.El
.Sh EXAMPLES
To remove the pass phrase on a private key:
.Bd -literal
 openssl pkey -in key.pem -out keyout.pem
.Ed
.Pp
To encrypt a private key using triple DES:
.Bd -literal
 openssl pkey -in key.pem -des3 -out keyout.pem
.Ed
.Pp
To convert a private key from PEM to DER format:
.Bd -literal
 openssl pkey -in key.pem -outform DER -out keyout.der
.Ed
.Pp
To print out the components of a private key to standard output:
.Bd -literal
 openssl pkey -in key.pem -text -noout
.Ed
.Pp
To print out the public components of a private key to standard output:
.Bd -literal
 openssl pkey -in key.pem -text_pub -noout
.Ed
.Pp
To just output the public part of a private key:
.Bd -literal
 openssl pkey -in key.pem -pubout -out pubkey.pem
.Ed
.Pp
To change the EC parameters encoding to
.Sy explicit :
.Bd -literal
 openssl pkey -in key.pem -ec_param_enc explicit -out keyout.pem
.Ed
.Pp
To change the EC point conversion form to
.Sy compressed :
.Bd -literal
 openssl pkey -in key.pem -ec_conv_form compressed -out keyout.pem
.Ed
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-genpkey 1 ,
.Xr openssl-rsa 1 ,
.Xr openssl-pkcs8 1 ,
.Xr openssl-dsa 1 ,
.Xr openssl-genrsa 1 ,
.Xr openssl-gendsa 1
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2006-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
