.Dd 2025-09-30
.Dt OPENSSL-RAND 1ossl
.Os
.Sh NAME
.Nm openssl-rand
.Nd generate pseudo-random bytes
.Sh SYNOPSIS
.Nm openssl rand
.Oo
.Fl help ]
.Oo
.Fl out
.Em file ]
.Oo
.Fl base64 ]
.Oo
.Fl hex ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Em num Ns
.Oo
.Oc
K|M|G|T
.Sh DESCRIPTION
This command generates
.Em num
random bytes using a cryptographically secure pseudo random number
generator (CSPRNG). A suffix [K|M|G|T] may be appended to the num value
to indicate the requested value be scaled as a multiple of
KiB/MiB/GiB/TiB respectively.
Note that suffixes are case sensitive, and that the suffixes represent
binary multiples (K = 1024 bytes, M = 1024*1024 bytes, etc).
.Pp
The string 'max' may be substituted for a numerical value in num, to
request the maximum number of bytes the CSPRNG can produce per
instantiation.
Currently, this is restricted to 2^61 bytes as per NIST SP 800-90C.
.Pp
The random bytes are generated using the
.Xr RAND_bytes 3
function, which provides a security level of 256 bits, provided it
managed to seed itself successfully from a trusted operating system
entropy source.
Otherwise, the command will fail with a nonzero error code.
For more details, see
.Xr RAND_bytes 3 ,
.Xr RAND 7 ,
and
.Xr EVP_RAND 7 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -out Em file
Write to
.Em file
instead of standard output.
.It Sy -base64
Perform base64 encoding on the output.
.It Sy -hex
Show the output as a hex string.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr RAND_bytes 3 ,
.Xr RAND 7 ,
.Xr EVP_RAND 7
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
