.Dd 2025-09-30
.Dt OPENSSL-PKEYUTL 1ossl
.Os
.Sh NAME
.Nm openssl-pkeyutl
.Nd asymmetric key command
.Sh SYNOPSIS
.Nm openssl
.Ar pkeyutl
.Oo
.Fl help ]
.Oo
.Fl in
.Em file ]
.Oo
.Fl rawin ]
.Oo
.Fl digest
.Em algorithm ]
.Oo
.Fl out
.Em file ]
.Oo
.Fl secret
.Em file ]
.Oo
.Fl sigfile
.Em file ]
.Oo
.Fl inkey
.Em filename Ns | Ns Em uri ]
.Oo
.Fl keyform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar P12 Ns | Ns Ar ENGINE ]
.Oo
.Fl passin
.Em arg ]
.Oo
.Fl pubin ]
.Oo
.Fl certin ]
.Oo
.Fl rev ]
.Oo
.Fl sign ]
.Oo
.Fl verify ]
.Oo
.Fl verifyrecover ]
.Oo
.Fl encrypt ]
.Oo
.Fl decrypt ]
.Oo
.Fl derive ]
.Oo
.Fl peerkey
.Em file ]
.Oo
.Fl peerform
.Ar DER Ns | Ns Ar PEM Ns | Ns Ar P12 Ns | Ns Ar ENGINE ]
.Oo
.Fl encap ]
.Oo
.Fl decap ]
.Oo
.Fl kdf
.Em algorithm ]
.Oo
.Fl kdflen
.Em length ]
.Oo
.Fl kemop
.Em mode ]
.Oo
.Fl pkeyopt
.Em opt Ns : Ns Em value ]
.Oo
.Fl pkeyopt_passin
.Em opt Ns
.Oo
.Pf : Em passarg Ns
.Oc
.Oc
.Oo
.Fl hexdump ]
.Oo
.Fl asn1parse ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl engine_impl ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Fl config
.Em configfile ]
.Sh DESCRIPTION
This command can be used to perform low-level operations on asymmetric
(public or private) keys using any supported algorithm.
.Pp
By default the signing operation (see
.Sy -sign
option) is assumed.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -in Em filename
This specifies the input filename to read data from or standard input if
this option is not specified.
.It Sy -rawin
This indicates that the signature or verification input data is raw
data, which is not hashed by any message digest algorithm.
Except with EdDSA, the user can specify a digest algorithm by using the
.Sy -digest
option.
For signature algorithms like RSA, DSA and ECDSA, the default digest
algorithm is SHA256. For SM2, it is SM3.
.Pp
This option can only be used with
.Sy -sign
and
.Sy -verify .
For EdDSA (the Ed25519 and Ed448 algorithms) this option is implied
since OpenSSL 3.5, and required in earlier versions.
.Pp
The
.Sy -digest
option implies
.Sy -rawin
since OpenSSL 3.5.
.It Sy -digest Em algorithm
This option can only be used with
.Sy -sign
and
.Sy -verify .
It specifies the digest algorithm that is used to hash the input data
before signing or verifying it with the input key.
This option could be omitted if the signature algorithm does not require
preprocessing the input through a pluggable hash function before signing
(for instance, EdDSA). If this option is omitted but the signature
algorithm requires one and the
.Sy -rawin
option is given, a default value will be used (see
.Sy -rawin
for details).
If this option is present, then the
.Sy -rawin
option is implied since OpenSSL 3.5, and required in earlier versions.
.Pp
At this time, HashEdDSA (the ph or "prehash" variant of EdDSA) is not
supported, so the
.Sy -digest
option cannot be used with EdDSA.
.It Sy -out Em filename
Specifies the output filename to write to or standard output by default.
.It Sy -secret Em filename
Specifies the shared-secret output filename for when performing
encapsulation via the
.Sy -encap
option or decapsulation via the
.Sy -decap
option.
The
.Sy -encap
option also produces a separate (public) ciphertext output which is by
default written to standard output, but being
.Em binary
non-text data, is typically also redirected to a file selected via the
.Em -out
option.
.It Sy -sigfile Em file
Signature file, required and allowed for
.Sy -verify
operations only.
.It Sy -inkey Em filename Ns | Ns Em uri
The input key, by default it should be a private key.
.It Sy -keyform Sy DER Ns | Ns Sy PEM Ns | Ns Sy P12 Ns | Ns Sy ENGINE
The key format; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -passin Em arg
The input key password source.
For more information about the format of
.Em arg
see
.Xr openssl-passphrase-options 1 .
.It Sy -pubin
By default a private key is read from the key input.
With this option a public key is read instead.
If the input contains no public key but a private key, its public part
is used.
.It Sy -certin
The input is a certificate containing a public key.
.It Sy -rev
Reverse the order of the input buffer.
This is useful for some libraries (such as CryptoAPI) which represent
the buffer in little-endian format.
This cannot be used in conjunction with
.Sy -rawin .
.It Sy -sign
Sign the input data and output the signed result.
This requires a private key.
Using a message digest operation along with this is recommended, when
applicable, see the
.Sy -rawin
and
.Sy -digest
options for details.
Otherwise, the input data given with the
.Sy -in
option is assumed to already be a digest, but this may then require an
additional
.Sy -pkeyopt
.Qo Li digest: Qc Ns Em md
in some cases (e.g., RSA with the default PKCS#1 padding mode).
Even for other algorithms like ECDSA, where the additional
.Sy -pkeyopt
option does not affect signature output, it is recommended, as it
enables checking that the input length is consistent with the intended
digest.
.It Sy -verify
Verify the input data against the signature given with the
.Sy -sigfile
option and indicate if the verification succeeded or failed.
The input data given with the
.Sy -in
option is assumed to be a hash value unless the
.Sy -rawin
option is specified or implied.
With raw data, when a digest algorithm is applicable, though it may be
inferred from the signature or take a default value, it should also be
specified.
.It Sy -verifyrecover
Verify the given signature and output the recovered data (signature
payload).
For example, in case of RSA PKCS#1 the recovered data is the
.Sy EMSA-PKCS-v1_5
DER encoding of the digest algorithm OID and value as specified in
.Lk https://datatracker.ietf.org/doc/html/rfc8017#section-9.2 .
.Pp
Note that here the input given with the
.Sy -in
option is not a signature input (as with the
.Sy -sign
and
.Sy -verify
options) but a signature output value, typically produced using the
.Sy -sign
option.
.Pp
This option is available only for use with RSA keys.
.It Sy -encrypt
Encrypt the input data using a public key.
.It Sy -decrypt
Decrypt the input data using a private key.
.It Sy -derive
Derive a shared secret using own private (EC)DH key and peer key.
.It Sy -peerkey Em file
File containing the peer public or private (EC)DH key to use with the
key derivation (agreement) operation.
Its type must match the type of the own private key given with
.Sy -inkey .
.It Sy -peerform Sy DER Ns | Ns Sy PEM Ns | Ns Sy P12 Ns | Ns Sy ENGINE
The peer key format; unspecified by default.
See
.Xr openssl-format-options 1
for details.
.It Sy -encap
Use a Key Encapsulation Mechanism
.Pf ( Sy KEM )
to
.Sy encapsulate
a shared-secret to a peer's
.Sy public
key.
The encapsulated result (or ciphertext, non-text binary data) is written
to standard output by default, or else to the file specified with
.Em -out .
The
.Em -secret
option must also be provided to specify the output file for the derived
shared-secret value generated in the encapsulation process.
Encapsulation is supported with a number of public key algorithms,
currently:
.Xr EVP_PKEY-ML-KEM 7 ,
.Xr EVP_KEM-X25519 7 ,
.Xr EVP_KEM-X448 7 ,
and
.Xr EVP_KEM-EC 7 .
The ECX and EC algorithms use the
.Lk https://www.rfc-editor.org/rfc/rfc9180
DHKEM construction.
Encapsulation is also supported with
.Xr EVP_KEM-RSA 7
keys via the
.Sy RSASVE
construction.
.Pp
At the API level, encapsulation and decapsulation are also supported for
a few hybrid ECDHE (no DHKEM) plus
.Sy ML-KEM
algorithms, but these are intended primarily for use with TLS and should
not be used standalone.
There are in any case no standard public and private key formats for the
hybrid algorithms, so it is not possible to provide the required key
material.
.It Sy -decap
Decode an encapsulated secret, with the use of a
.Sy -private
key, to derive the same shared-secret as that obtained when the secret
was encapsulated to the corresponding public key.
The encapsulated secret is by default read from the standard input, or
else from the file specified with
.Sy -in .
The derived shared-secret is written to the file specified with the
.Sy -secret
option, which
.Em must
also be provided.
Decapsulation is supported with a number of public key algorithms,
currently:
.Xr EVP_PKEY-ML-KEM 7 ,
.Xr EVP_KEM-X25519 7 ,
.Xr EVP_KEM-X448 7 ,
and
.Xr EVP_KEM-EC 7 .
The ECX and EC algorithms use the
.Lk https://www.rfc-editor.org/rfc/rfc9180
DHKEM construction.
Decapsulation is also supported with
.Xr EVP_KEM-RSA 7
keys via the
.Sy RSASVE
construction.
.It Sy -kemop Em mode
This option is used with the
.Em -encap Ns / Ns Em -decap
commands and specifies the KEM
.Em mode
specific for the key algorithm when there is no default way to
encapsulate and decapsulate shared secrets with the chosen key type.
All the supported algorithms presently support only their default
.Em mode ,
and this option, though available, is not required.
.It Sy -kdf Em algorithm
Use key derivation function
.Em algorithm .
The supported algorithms are at present
.Sy TLS1-PRF
and
.Sy HKDF .
Note: additional parameters and the KDF output length will normally have
to be set for this to work.
See
.Xr EVP_PKEY_CTX_set_hkdf_md 3
and
.Xr EVP_PKEY_CTX_set_tls1_prf_md 3
for the supported string parameters of each algorithm.
.It Sy -kdflen Em length
Set the output length for KDF.
.It Sy -pkeyopt Em opt Ns : Ns Em value
Public key options specified as opt:value.
See NOTES below for more details.
.It Sy -pkeyopt_passin Em opt Ns [: Ns Em passarg ]
Allows reading a public key option
.Em opt
from stdin or a password source.
If only
.Em opt
is specified, the user will be prompted to enter a password on stdin.
Alternatively,
.Em passarg
can be specified which can be any value supported by
.Xr openssl-passphrase-options 1 .
.It Sy -hexdump
hex dump the output data.
.It Sy -asn1parse
Parse the ASN.1 output data to check its DER encoding and print any
errors.
When combined with the
.Sy -verifyrecover
option, this may be useful in case an ASN.1 DER-encoded structure had
been signed directly (without hashing it) and when checking a signature
in PKCS#1 v1.5 format, which has a DER encoding.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -engine_impl
When used with the
.Sy -engine
option, it specifies to also use engine
.Em id
for crypto operations.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -config Em configfile
See
.Xr openssl 1 .
.El
.Sh NOTES
The operations and options supported vary according to the key algorithm
and its implementation.
The OpenSSL operations and options are indicated below.
.Pp
Unless otherwise mentioned, the
.Sy -pkeyopt
option supports for all public-key types the
.Qo Li digest: Qc Ns Em alg
argument, which specifies the digest in use for the signing and
verification operations.
The value
.Em alg
should represent a digest name as used in the
.Xr EVP_get_digestbyname 3
function for example
.Sy sha256 .
This value is not used to hash the input data.
It is used (by some algorithms) for sanity-checking the lengths of data
passed in and for creating the structures that make up the signature
(e.g.,
.Sy DigestInfo
in RSASSA PKCS#1 v1.5 signatures).
.Pp
For instance, if the value of the
.Sy -pkeyopt
option
.Qo Li digest Qc
argument is
.Sy sha256 ,
the signature or verification input should be the 32 bytes long binary
value of the SHA256 hash function output.
.Pp
Unless
.Sy -rawin
is used or implied, this command does not hash the input data but rather
it will use the data directly as input to the signature algorithm.
Depending on the key type, signature type, and mode of padding, the
maximum sensible lengths of input data differ.
With RSA the signed data cannot be longer than the key modulus.
In case of ECDSA and DSA the data should not be longer than the field
size, otherwise it will be silently truncated to the field size.
In any event the input size must not be larger than the largest
supported digest output size
.Sy EVP_MAX_MD_SIZE ,
which currently is 64 bytes.
.Sh RSA ALGORITHM
The RSA algorithm generally supports the encrypt, decrypt, sign, verify
and verifyrecover operations.
However, some padding modes support only a subset of these operations.
The following additional
.Sy pkeyopt
values are supported:
.Bl -tag -width Ds
.It Sy rsa_padding_mode: Ns Em mode
This sets the RSA padding mode.
Acceptable values for
.Em mode
are
.Sy pkcs1
for PKCS#1 padding,
.Sy none
for no padding,
.Sy oaep
for
.Sy OAEP
mode,
.Sy x931
for X9.31 mode and
.Sy pss
for PSS.
.Pp
In PKCS#1 padding, if the message digest is not set, then the supplied
data is signed or verified directly instead of using a
.Sy DigestInfo
structure.
If a digest is set, then the
.Sy DigestInfo
structure is used and its length must correspond to the digest type.
.Pp
Note, for
.Sy pkcs1
padding, as a protection against the Bleichenbacher attack, the
decryption will not fail in case of padding check failures.
Use
.Sy none
and manual inspection of the decrypted message to verify if the
decrypted value has correct PKCS#1 v1.5 padding.
.Pp
For
.Sy oaep
mode only encryption and decryption is supported.
.Pp
For
.Sy x931
if the digest type is set it is used to format the block data otherwise
the first byte is used to specify the X9.31 digest ID. Sign, verify and
verifyrecover are can be performed in this mode.
.Pp
For
.Sy pss
mode only sign and verify are supported and the digest type must be
specified.
.It Sy rsa_pss_saltlen: Ns Em len
For
.Sy pss
mode only this option specifies the salt length.
Three special values are supported:
.Sy digest
sets the salt length to the digest length,
.Sy max
sets the salt length to the maximum permissible value.
When verifying
.Sy auto
causes the salt length to be automatically determined based on the
.Sy PSS
block structure.
.It Sy rsa_mgf1_md: Ns Em digest
For PSS and OAEP padding sets the MGF1 digest.
If the MGF1 digest is not explicitly set in PSS mode then the signing
digest is used.
.It Sy rsa_oaep_md: Ns Em digest
Sets the digest used for the OAEP hash function.
If not explicitly set then SHA256 is used.
.It Sy rsa_pkcs1_implicit_rejection: Ns Em flag
Disables (when set to 0) or enables (when set to 1) the use of implicit
rejection with PKCS#1 v1.5 decryption.
When enabled (the default), as a protection against Bleichenbacher
attack, the library will generate a deterministic random plaintext that
it will return to the caller in case of padding check failure.
When disabled, it's the callers' responsibility to handle the returned
errors in a side-channel free manner.
.El
.Sh RSA-PSS ALGORITHM
The RSA-PSS algorithm is a restricted version of the RSA algorithm which
only supports the sign and verify operations with PSS padding.
The following additional
.Sy -pkeyopt
values are supported:
.Bl -tag -width Ds
.It Sy rsa_padding_mode: Ns Em mode Ns , Sy rsa_pss_saltlen: Ns Em len Ns , Sy rsa_mgf1_md: Ns Em digest
These have the same meaning as the
.Sy RSA
algorithm with some additional restrictions.
The padding mode can only be set to
.Sy pss
which is the default value.
.Pp
If the key has parameter restrictions then the digest, MGF1 digest and
salt length are set to the values specified in the parameters.
The digest and MG cannot be changed and the salt length cannot be set to
a value less than the minimum restriction.
.El
.Sh DSA ALGORITHM
The DSA algorithm supports signing and verification operations only.
Currently there are no additional
.Sy -pkeyopt
options other than
.Sy digest .
The SHA256 digest is assumed by default.
.Sh DH ALGORITHM
The DH algorithm only supports the derivation operation and no
additional
.Sy -pkeyopt
options.
.Sh EC ALGORITHM
The EC algorithm supports sign, verify and derive operations.
The sign and verify operations use ECDSA and derive uses ECDH. SHA256 is
assumed by default for the
.Sy -pkeyopt
.Sy digest
option.
.Sh X25519 AND X448 ALGORITHMS
The X25519 and X448 algorithms support key derivation only.
Currently there are no additional options.
.Ss SLH-DSA ALGORITHMS
The SLH-DSA algorithms (SLH-DSA-SHA2-128s, SLH-DSA-SHA2-128f,
SLH-DSA-SHA2-192s, SLH-DSA-SHA2-192f, SLH-DSA-SHA2-256s,
SLH-DSA-SHA2-256f) are post-quantum signature algorithms.
When using SLH-DSA with pkeyutl, the following options are available:
.Bl -tag -width Ds
.It Sy -sign
Sign the input data using an SLH-DSA private key.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey slhdsa.pem -out sig
.Ed
.It Sy -verify
Verify the signature using an SLH-DSA public key.
For example:
.Bd -literal
  $ openssl pkeyutl -verify -in file.txt -inkey slhdsa.pem -sigfile sig
.Ed
.El
.Pp
See
.Xr EVP_PKEY-SLH-DSA 7
and
.Xr EVP_SIGNATURE-SLH-DSA 7
for additional details about the SLH-DSA algorithm and its
implementation.
.Sh ML-DSA-44, ML-DSA-65 AND ML-DSA-87 ALGORITHMS
The ML-DSA algorithms are post-quantum signature algorithms that support
signing and verification of "raw" messages.
No preliminary hashing is performed.
When using ML-DSA with pkeyutl, the following options are available:
.Bl -tag -width Ds
.It Sy -sign
Sign the input data using an ML-DSA private key.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig
.Ed
.It Sy -verify
Verify the signature using an ML-DSA public key.
For example:
.Bd -literal
  $ openssl pkeyutl -verify -in file.txt -inkey mldsa65.pem -sigfile sig
.Ed
.It Sy -pkeyopt Em opt Ns : Ns Em value
Additional options for ML-DSA signing and verification:
.Bl -tag -width Ds
.It Sy message-encoding Ns : Ns Em value
Specifies the message encoding mode used for signing.
This controls how the input message is processed before signing.
Valid values are described in
.Xr EVP_SIGNATURE-ML-DSA 7 .
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt message-encoding:1
.Ed
.It Sy test-entropy Ns : Ns Em value
Specifies a test entropy value for deterministic signing.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt test-entropy:abcdefghijklmnopqrstuvwxyz012345
.Ed
.It Sy hextest-entropy Ns : Ns Em value
Specifies a test entropy value in hex format.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt hextest-entropy:000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
.Ed
.It Sy deterministic Ns : Ns Em value
Enables deterministic signing.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt deterministic:1
.Ed
.It Sy mu Ns : Ns Em value
Specifies the mu parameter.
For example:
.Bd -literal
  $ echo -n "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" >file.txt
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt mu:1
.Ed
.El
.It Sy context-string Ns : Ns Em string
Specifies a context string for both signing and verification operations.
The context string must be the same for verification to succeed.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt context-string:mycontext
  $ openssl pkeyutl -verify -in file.txt -inkey mldsa65.pem -sigfile sig -pkeyopt context-string:mycontext
.Ed
.It Sy hexcontext-string Ns : Ns Em string
Specifies a context string in hex format, allowing binary control
values.
For example:
.Bd -literal
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt hexcontext-string:6d79636f6e74657874
.Ed
.El
.Pp
The signing operation supports a
.Sy deterministic Ns : Ns Em bool
option, with
.Em bool
set to
.Qo Li 1 Qc
if a deterministic signature is to be generated with a fixed all zero
random input.
By default, or if the
.Em bool
is
.Qo Li 0 Qc
a random entropy value is used.
A deterministic result can also be obtained by specifying an explicit
entropy value via the
.Sy hextest-entropy Ns : Ns Em value
parameter.
Deterministic
.Sy ML-DSA
signing should only be used in tests.
.Pp
See
.Xr EVP_SIGNATURE-ML-DSA 7
for additional details about the ML-DSA algorithms and their
implementation.
.Sh ML-KEM-512, ML-KEM-768 AND ML-KEM-1024 ALGORITHMS
The ML-KEM algorithms support encapsulation and decapsulation only.
The encapsulation operation supports a
.Sy hexikme Ns : Ns Em entropy
option, with
.Em entropy
the 64 hexadecimal digit encoding of a 32-byte value.
This should only be used in tests, known or leaked values of the option
may compromise the generated shared secret.
.Pp
See
.Xr EVP_KEM-ML-KEM 7
for additional detail.
.Sh ED25519 AND ED448 ALGORITHMS
These algorithms only support signing and verifying.
OpenSSL only implements the "pure" variants of these algorithms so raw
data can be passed directly to them without hashing them first.
OpenSSL only supports "oneshot" operation with these algorithms.
This means that the entire file to be signed/verified must be read into
memory before processing it.
Signing or Verifying very large files should be avoided.
Additionally the size of the file must be known for this to work.
If the size of the file cannot be determined (for example if the input
is stdin) then the sign or verify operation will fail.
.Sh SM2
The SM2 algorithm supports sign, verify, encrypt and decrypt operations.
For the sign and verify operations, SM2 requires an Distinguishing ID
string to be passed in.
The following
.Sy -pkeyopt
value is supported:
.Bl -tag -width Ds
.It Sy distid: Ns Em string
This sets the ID string used in SM2 sign or verify operations.
While verifying an SM2 signature, the ID string must be the same one
used when signing the data.
Otherwise the verification will fail.
.It Sy hexdistid: Ns Em hex_string
This sets the ID string used in SM2 sign or verify operations.
While verifying an SM2 signature, the ID string must be the same one
used when signing the data.
Otherwise the verification will fail.
The ID string provided with this option should be a valid hexadecimal
value.
.El
.Sh EXAMPLES
Sign some data using a private key:
.Bd -literal
 openssl pkeyutl -sign -in file -inkey key.pem -out sig
.Ed
.Pp
Recover the signed data (e.g.
if an RSA key is used):
.Bd -literal
 openssl pkeyutl -verifyrecover -in sig -inkey key.pem
.Ed
.Pp
Verify the signature (e.g.
a DSA key):
.Bd -literal
 openssl pkeyutl -verify -in file -sigfile sig -inkey key.pem
.Ed
.Pp
Sign data using a message digest value (this is currently only valid for
RSA):
.Bd -literal
 openssl pkeyutl -sign -in file -inkey key.pem -out sig -pkeyopt digest:sha256
.Ed
.Pp
Derive a shared secret value:
.Bd -literal
 openssl pkeyutl -derive -inkey key.pem -peerkey pubkey.pem -out secret
.Ed
.Pp
Hexdump 48 bytes of TLS1 PRF using digest
.Sy SHA256
and shared secret and seed consisting of the single byte 0xFF:
.Bd -literal
 openssl pkeyutl -kdf TLS1-PRF -kdflen 48 -pkeyopt md:SHA256 \e
    -pkeyopt hexsecret:ff -pkeyopt hexseed:ff -hexdump
.Ed
.Pp
Derive a key using
.Sy scrypt
where the password is read from command line:
.Bd -literal
 openssl pkeyutl -kdf scrypt -kdflen 16 -pkeyopt_passin pass \e
    -pkeyopt hexsalt:aabbcc -pkeyopt N:16384 -pkeyopt r:8 -pkeyopt p:1
.Ed
.Pp
Derive using the same algorithm, but read key from environment variable
MYPASS:
.Bd -literal
 openssl pkeyutl -kdf scrypt -kdflen 16 -pkeyopt_passin pass:env:MYPASS \e
    -pkeyopt hexsalt:aabbcc -pkeyopt N:16384 -pkeyopt r:8 -pkeyopt p:1
.Ed
.Pp
Sign some data using an
.Xr SM2 7
private key and a specific ID:
.Bd -literal
 openssl pkeyutl -sign -in file -inkey sm2.key -out sig -rawin -digest sm3 \e
    -pkeyopt distid:someid
.Ed
.Pp
Verify some data using an
.Xr SM2 7
certificate and a specific ID:
.Bd -literal
 openssl pkeyutl -verify -certin -in file -inkey sm2.cert -sigfile sig \e
    -rawin -digest sm3 -pkeyopt distid:someid
.Ed
.Pp
Decrypt some data using a private key with OAEP padding using SHA256:
.Bd -literal
 openssl pkeyutl -decrypt -in file -inkey key.pem -out secret \e
    -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256
.Ed
.Pp
Create an ML-DSA key pair and sign data with a specific context string:
.Bd -literal
  $ openssl genpkey -algorithm ML-DSA-65 -out mldsa65.pem
  $ openssl pkeyutl -sign -in file.txt -inkey mldsa65.pem -out sig -pkeyopt context-string:example
.Ed
.Pp
Verify a signature using ML-DSA with the same context string:
.Bd -literal
  $ openssl pkeyutl -verify -in file.txt -inkey mldsa65.pem -sigfile sig -pkeyopt context-string:example
.Ed
.Pp
Generate an ML-KEM key pair and use it for encapsulation:
.Bd -literal
  $ openssl genpkey -algorithm ML-KEM-768 -out mlkem768.pem
  $ openssl pkey -in mlkem768.pem -pubout -out mlkem768_pub.pem
  $ openssl pkeyutl -encap -inkey mlkem768_pub.pem -pubin -out ciphertext -secret shared_secret.bin
.Ed
.Pp
Decapsulate a shared secret using an ML-KEM private key:
.Bd -literal
  $ openssl pkeyutl -decap -inkey mlkem768.pem -in ciphertext -secret decapsulated_secret.bin
.Ed
.Pp
Create an SLH-DSA key pair and sign data:
.Bd -literal
  $ openssl genpkey -algorithm SLH-DSA-SHA2-128s -out slh-dsa.pem
  $ openssl pkeyutl -sign -in file.txt -inkey slh-dsa.pem -out sig
.Ed
.Pp
Verify a signature using SLH-DSA:
.Bd -literal
  $ openssl pkeyutl -verify -in file.txt -inkey slh-dsa.pem -sigfile sig
.Ed
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-genpkey 1 ,
.Xr openssl-pkey 1 ,
.Xr openssl-rsautl 1
.Xr openssl-dgst 1 ,
.Xr openssl-rsa 1 ,
.Xr openssl-genrsa 1 ,
.Xr openssl-kdf 1
.Xr EVP_PKEY_CTX_set_hkdf_md 3 ,
.Xr EVP_PKEY_CTX_set_tls1_prf_md 3 ,
.Sh HISTORY
Since OpenSSL 3.5, the
.Sy -digest
option implies
.Sy -rawin ,
and these two options are no longer required when signing or verifying
with an Ed25519 or Ed448 key.
.Pp
Also since OpenSSL 3.5, the
.Sy -kemop
option is no longer required for any of the supported algorithms, the
only supported
.Sy mode
is now the default.
.Pp
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2006-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
