.Dd 2025-09-30
.Dt OPENSSL-PKEYPARAM 1ossl
.Os
.Sh NAME
.Nm openssl-pkeyparam
.Nd public key algorithm parameter processing command
.Sh SYNOPSIS
.Nm openssl
.Ar pkeyparam
.Oo
.Fl help ]
.Oo
.Fl in
.Em filename ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl text ]
.Oo
.Fl noout ]
.Oo
.Fl check ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Sh DESCRIPTION
This command processes public key algorithm parameters.
They can be checked for correctness and their components printed out.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -in Em filename
This specifies the input file to read parameters from or standard input
if this option is not specified.
.It Sy -out Em filename
This specifies the output filename to write parameters to or standard
output if this option is not specified.
The output filename can be the same as the input filename, which leads
to replacing the file contents.
Note that file I/O is not atomic.
The output file is truncated and then written.
.It Sy -text
Prints out the parameters in plain text in addition to the encoded
version.
.It Sy -noout
Do not output the encoded version of the parameters.
.It Sy -check
This option checks the correctness of parameters.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Sh EXAMPLES
Print out text version of parameters:
.Bd -literal
 openssl pkeyparam -in param.pem -text
.Ed
.Sh NOTES
There are no
.Sy -inform
or
.Sy -outform
options for this command because only PEM format is supported because
the key type is determined by the PEM headers.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-genpkey 1 ,
.Xr openssl-rsa 1 ,
.Xr openssl-pkcs8 1 ,
.Xr openssl-dsa 1 ,
.Xr openssl-genrsa 1 ,
.Xr openssl-gendsa 1
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2006-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
