.Dd 2025-09-30
.Dt OPENSSL-PKCS7 1ossl
.Os
.Sh NAME
.Nm openssl-pkcs7
.Nd PKCS#7 command
.Sh SYNOPSIS
.Nm openssl
.Ar pkcs7
.Oo
.Fl help ]
.Oo
.Fl inform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl outform
.Ar DER Ns | Ns Ar PEM ]
.Oo
.Fl in
.Em filename ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl print ]
.Oo
.Fl print_certs ]
.Oo
.Fl quiet ]
.Oo
.Fl text ]
.Oo
.Fl noout ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Sh DESCRIPTION
This command processes PKCS#7 files.
Note that it only understands PKCS#7 v 1.5 as specified in IETF RFC
2315. It cannot currently parse CMS as described in IETF RFC 2630.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -inform Sy DER Ns | Ns Sy PEM Ns , Sy -outform Sy DER Ns | Ns Sy PEM
The input and formats; the default is
.Sy PEM .
See
.Xr openssl-format-options 1
for details.
.Pp
The data is a PKCS#7 Version 1.5 structure.
.It Sy -in Em filename
This specifies the input filename to read from or standard input if this
option is not specified.
.It Sy -out Em filename
Specifies the output filename to write to or standard output by default.
.It Sy -print
Print out the full PKCS7 object.
.It Sy -print_certs
Prints out any certificates or CRLs contained in the file.
They are preceded by their subject and issuer names in one line format.
.It Sy -quiet
When used with -print_certs, prints out just the PEM-encoded
certificates without any other output.
.It Sy -text
Prints out certificate details in full rather than just subject and
issuer names.
.It Sy -noout
Don't output the encoded version of the PKCS#7 structure (or
certificates if
.Sy -print_certs
is set).
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.El
.Sh EXAMPLES
Convert a PKCS#7 file from PEM to DER:
.Bd -literal
 openssl pkcs7 -in file.pem -outform DER -out file.der
.Ed
.Pp
Output all certificates in a file:
.Bd -literal
 openssl pkcs7 -in file.pem -print_certs -out certs.pem
.Ed
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-crl2pkcs7 1
.Sh HISTORY
The
.Sy -engine
option was deprecated in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2000-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
