.Dd 2025-09-30
.Dt OPENSSL-GENRSA 1ossl
.Os
.Sh NAME
.Nm openssl-genrsa
.Nd generate an RSA private key
.Sh SYNOPSIS
.Nm openssl
.Ar genrsa
.Oo
.Fl help ]
.Oo
.Fl out
.Em filename ]
.Oo
.Fl passout
.Em arg ]
.Oo
.Fl aes128 ]
.Oo
.Fl aes192 ]
.Oo
.Fl aes256 ]
.Oo
.Fl aria128 ]
.Oo
.Fl aria192 ]
.Oo
.Fl aria256 ]
.Oo
.Fl camellia128 ]
.Oo
.Fl camellia192 ]
.Oo
.Fl camellia256 ]
.Oo
.Fl des ]
.Oo
.Fl des3 ]
.Oo
.Fl idea ]
.Oo
.Fl F4 ]
.Oo
.Fl f4 ]
.Oo
.Fl 3 ]
.Oo
.Fl primes
.Em num ]
.Oo
.Fl verbose ]
.Oo
.Fl quiet ]
.Oo
.Fl traditional ]
.Oo
.Fl rand
.Em files ]
.Oo
.Fl writerand
.Em file ]
.Oo
.Fl engine
.Em id ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Oo
.Ar numbits ]
.Sh DESCRIPTION
This command generates an RSA private key.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -out Em filename
Output the key to the specified file.
If this argument is not specified then standard output is used.
.It Sy -passout Em arg
The output file password source.
For more information about the format see
.Xr openssl-passphrase-options 1 .
.It Sy -aes128 Ns , Sy -aes192 Ns , Sy -aes256 Ns , Sy -aria128 Ns , Sy -aria192 Ns , Sy -aria256 Ns , Sy -camellia128 Ns , Sy -camellia192 Ns , Sy -camellia256 Ns , Sy -des Ns , Sy -des3 Ns , Sy -idea
These options encrypt the private key with specified cipher before
outputting it.
If none of these options is specified no encryption is used.
If encryption is used a pass phrase is prompted for if it is not
supplied via the
.Sy -passout
argument.
.It Sy -F4 Ns , Sy -f4 Ns , Sy -3
The public exponent to use, either 65537 or 3. The default is 65537. The
.Sy -3
option has been deprecated.
.It Sy -primes Em num
Specify the number of primes to use while generating the RSA key.
The
.Em num
parameter must be a positive integer that is greater than 1 and less
than 16. If
.Em num
is greater than 2, then the generated key is called a 'multi-prime' RSA
key, which is defined in RFC 8017.
.It Sy -verbose
Print extra details about the operations being performed.
.It Sy -quiet
Print fewer details about the operations being performed, which may be
handy during batch scripts and pipelines.
.It Sy -traditional
Write the key using the traditional PKCS#1 format instead of the PKCS#8
format.
.It Sy -rand Em files Ns , Sy -writerand Em file
See
.Xr openssl 1
for details.
.It Sy -engine Em id
See
.Xr openssl 1 .
This option is deprecated.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy numbits
The size of the private key to generate in bits.
This must be the last option specified.
The default is 2048 and values less than 512 are not allowed.
.El
.Sh NOTES
RSA private key generation essentially involves the generation of two or
more prime numbers.
When generating a private key various symbols will be output to indicate
the progress of the generation.
A
.Sy .
represents each number which has passed an initial sieve test,
.Sy +
means a number has passed a single round of the Miller-Rabin primality
test,
.Sy *
means the current prime starts a regenerating progress due to some
failed tests.
A newline means that the number has passed all the prime tests (the
actual number depends on the key size).
.Pp
Because key generation is a random process the time taken to generate a
key may vary somewhat.
But in general, more primes lead to less generation time of a key.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-genpkey 1 ,
.Xr openssl-gendsa 1
.Sh COPYRIGHT
Copyright 2000-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
