.Dd 2025-09-30
.Dt OPENSSL-S_TIME 1ossl
.Os
.Sh NAME
.Nm openssl-s_time
.Nd SSL/TLS performance timing program
.Sh SYNOPSIS
.Nm openssl
.Ar s_time
.Oo
.Fl help ]
.Oo
.Fl connect
.Em host Ns : Ns Em port ]
.Oo
.Fl www
.Em page ]
.Oo
.Fl cert
.Em filename ]
.Oo
.Fl key
.Em filename ]
.Oo
.Fl reuse ]
.Oo
.Fl new ]
.Oo
.Fl verify
.Em depth ]
.Oo
.Fl time
.Em seconds ]
.Oo
.Fl ssl3 ]
.Oo
.Fl tls1 ]
.Oo
.Fl tls1_1 ]
.Oo
.Fl tls1_2 ]
.Oo
.Fl tls1_3 ]
.Oo
.Fl bugs ]
.Oo
.Fl cipher
.Em cipherlist ]
.Oo
.Fl ciphersuites
.Em val ]
.Oo
.Fl nameopt
.Em option ]
.Oo
.Fl cafile
.Em file ]
.Oo
.Fl CAfile
.Em file ]
.Oo
.Fl no-CAfile ]
.Oo
.Fl CApath
.Em dir ]
.Oo
.Fl no-CApath ]
.Oo
.Fl CAstore
.Em uri ]
.Oo
.Fl no-CAstore ]
.Oo
.Fl provider
.Em name ]
.Oo
.Fl provider-path
.Em path ]
.Oo
.Fl provparam
.Em [name:]key=value ]
.Oo
.Fl propquery
.Em propq ]
.Sh DESCRIPTION
This command implements a generic SSL/TLS client which connects to a
remote host using SSL/TLS. It can request a page from the server and
includes the time to transfer the payload data in its timing
measurements.
It measures the number of connections within a given timeframe, the
amount of data transferred (if any), and calculates the average time
spent for one connection.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -help
Print out a usage message.
.It Sy -connect Em host Ns : Ns Em port
This specifies the host and optional port to connect to.
If the host string is an IPv6 address, it must be enclosed in
.Qo Li [ Qc
and
.Qo Li ] Qc .
.It Sy -www Em page
This specifies the page to GET from the server.
A value of '/' gets the
.Pa index.html
page.
If this parameter is not specified, then this command will only perform
the handshake to establish SSL connections but not transfer any payload
data.
.It Sy -cert Em certname
The certificate to use, if one is requested by the server.
The default is not to use a certificate.
The file is in PEM format.
.It Sy -key Em keyfile
The private key to use.
If not specified then the certificate file will be used.
The file is in PEM format.
.It Sy -verify Em depth
The verify depth to use.
This specifies the maximum length of the server certificate chain and
turns on server certificate verification.
Currently the verify operation continues after errors so all the
problems with a certificate chain can be seen.
As a side effect the connection will never fail due to a server
certificate verify failure.
.It Sy -new
Performs the timing test using a new session ID for each connection.
If neither
.Sy -new
nor
.Sy -reuse
are specified, they are both on by default and executed in sequence.
.It Sy -reuse
Performs the timing test using the same session ID; this can be used as
a test that session caching is working.
If neither
.Sy -new
nor
.Sy -reuse
are specified, they are both on by default and executed in sequence.
.It Sy -bugs
There are several known bugs in SSL and TLS implementations.
Adding this option enables various workarounds.
.It Sy -cipher Em cipherlist
This allows the TLSv1.2 and below cipher list sent by the client to be
modified.
This list will be combined with any TLSv1.3 ciphersuites that have been
configured.
Although the server determines which cipher suite is used it should take
the first supported cipher in the list sent by the client.
See
.Xr openssl-ciphers 1
for more information.
.It Sy -ciphersuites Em val
This allows the TLSv1.3 ciphersuites sent by the client to be modified.
This list will be combined with any TLSv1.2 and below ciphersuites that
have been configured.
Although the server determines which cipher suite is used it should take
the first supported cipher in the list sent by the client.
See
.Xr openssl-ciphers 1
for more information.
The format for this list is a simple colon (":") separated list of
TLSv1.3 ciphersuite names.
.It Sy -time Em length
Specifies how long (in seconds) this command should establish
connections and optionally transfer payload data from a server.
Server and client performance and the link speed determine how many
connections it can establish.
.It Sy -nameopt Em option
This specifies how the subject or issuer names are displayed.
See
.Xr openssl-namedisplay-options 1
for details.
.It Sy -CAfile Em file Ns , Sy -no-CAfile Ns , Sy -CApath Em dir Ns , Sy -no-CApath Ns , Sy -CAstore Em uri Ns , Sy -no-CAstore
See
.Xr openssl-verification-options 1
for details.
.It Sy -provider Em name
.It Sy -provider-path Em path
.It Sy -provparam Em [name:]key=value
.It Sy -propquery Em propq
See
.Xr openssl 1 ,
.Xr provider 7 ,
and
.Xr property 7 .
.It Sy -cafile Em file
This is an obsolete synonym for
.Sy -CAfile .
.It Sy -ssl3 Ns , Sy -tls1 Ns , Sy -tls1_1 Ns , Sy -tls1_2 Ns , Sy -tls1_3
See
.Xr openssl 1 .
.El
.Sh NOTES
This command can be used to measure the performance of an SSL
connection.
To connect to an SSL HTTP server and get the default page the command
.Bd -literal
 openssl s_time -connect servername:443 -www / -CApath yourdir -CAfile yourfile.pem -cipher commoncipher [-ssl3]
.Ed
.Pp
would typically be used (https uses port 443).
.Em commoncipher
is a cipher to which both client and server can agree, see the
.Xr openssl-ciphers 1
command for details.
.Pp
If the handshake fails then there are several possible causes, if it is
nothing obvious like no client certificate then the
.Sy -bugs
and
.Sy -ssl3
options can be tried in case it is a buggy server.
In particular you should play with these options
.Sy before
submitting a bug report to an OpenSSL mailing list.
.Pp
A frequent problem when attempting to get client certificates working is
that a web client complains it has no certificates or gives an empty
list to choose from.
This is normally because the server is not sending the clients
certificate authority in its "acceptable CA list" when it requests a
certificate.
By using
.Xr openssl-s_client 1
the CA list can be viewed and checked.
However, some servers only request client authentication after a
specific URL is requested.
To obtain the list in this case it is necessary to use the
.Sy -prexit
option of
.Xr openssl-s_client 1
and send an HTTP request for an appropriate page.
.Pp
If a certificate is specified on the command line using the
.Sy -cert
option it will not be used unless the server specifically requests a
client certificate.
Therefore, merely including a client certificate on the command line is
no guarantee that the certificate works.
.Sh BUGS
Because this program does not have all the options of the
.Xr openssl-s_client 1
program to turn protocols on and off, you may not be able to measure the
performance of all protocols with all servers.
.Pp
The
.Sy -verify
option should really exit if the server verification fails.
.Sh HISTORY
The
.Sy -cafile
option was deprecated in OpenSSL 3.0.
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-s_client 1 ,
.Xr openssl-s_server 1 ,
.Xr openssl-ciphers 1 ,
.Xr ossl_store-file 7
.Sh COPYRIGHT
Copyright 2004-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
