.Dd 2025-09-30
.Dt TSGET 1ossl
.Os
.Sh NAME
.Nm tsget
.Nd Time Stamping HTTP/HTTPS client
.Sh SYNOPSIS
.Nm tsget
.Fl h
.Em server_url
.Oo
.Fl e
.Em extension ]
.Oo
.Fl o
.Em output ]
.Oo
.Fl v ]
.Oo
.Fl d ]
.Oo
.Fl k
.Em private_key.pem ]
.Oo
.Fl p
.Em key_password ]
.Oo
.Fl c
.Em client_cert.pem ]
.Oo
.Fl C
.Em CA_certs.pem ]
.Oo
.Fl P
.Em CA_path ]
.Oo
.Fl r
.Em files ]
.Oo
.Fl g
.Em EGD_socket ]
.Oo
.Em request
.Oc
\&...
.Sh DESCRIPTION
This command can be used for sending a timestamp request, as specified
in RFC 3161, to a timestamp server over HTTP or HTTPS and storing the
timestamp response in a file.
It cannot be used for creating the requests and verifying responses, you
have to use
.Xr openssl-ts 1
to do that.
This command can send several requests to the server without closing the
TCP connection if more than one requests are specified on the command
line.
.Pp
This command sends the following HTTP request for each timestamp
request:
.Bd -literal
        POST url HTTP/1.1
        User-Agent: OpenTSA tsget.pl/<version>
        Host: <host>:<port>
        Pragma: no-cache
        Content-Type: application/timestamp-query
        Accept: application/timestamp-reply
        Content-Length: length of body

        ...binary request specified by the user...
.Ed
.Pp
It expects a response of type application/timestamp-reply, which is
written to a file without any interpretation.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -h Em server_url
The URL of the HTTP/HTTPS server listening for timestamp requests.
.It Sy -e Em extension
If the
.Sy -o
option is not given this argument specifies the extension of the output
files.
The base name of the output file will be the same as those of the input
files.
Default extension is
.Pa .tsr .
(Optional)
.It Sy -o Em output
This option can be specified only when just one request is sent to the
server.
The timestamp response will be written to the given output file.
\&'-' means standard output.
In case of multiple timestamp requests or the absence of this argument
the names of the output files will be derived from the names of the
input files and the default or specified extension argument.
(Optional)
.It Sy -v
The name of the currently processed request is printed on standard
error.
(Optional)
.It Sy -d
Switches on verbose mode for the underlying perl module
.Xr WWW::Curl::Easy 3p .
You can see detailed debug messages for the connection.
(Optional)
.It Sy -k Em private_key.pem
(HTTPS) In case of certificate-based client authentication over HTTPS
.Em private_key.pem
must contain the private key of the user.
The private key file can optionally be protected by a passphrase.
The
.Sy -c
option must also be specified.
(Optional)
.It Sy -p Em key_password
(HTTPS) Specifies the passphrase for the private key specified by the
.Sy -k
argument.
If this option is omitted and the key is passphrase protected, it will
be prompted for.
(Optional)
.It Sy -c Em client_cert.pem
(HTTPS) In case of certificate-based client authentication over HTTPS
.Em client_cert.pem
must contain the X.509 certificate of the user.
The
.Sy -k
option must also be specified.
If this option is not specified no certificate-based client
authentication will take place.
(Optional)
.It Sy -C Em CA_certs.pem
(HTTPS) The trusted CA certificate store.
The certificate chain of the peer's certificate must include one of the
CA certificates specified in this file.
Either option
.Sy -C
or option
.Sy -P
must be given in case of HTTPS. (Optional)
.It Sy -P Em CA_path
(HTTPS) The path containing the trusted CA certificates to verify the
peer's certificate.
The directory must be prepared with
.Xr openssl-rehash 1 .
Either option
.Sy -C
or option
.Sy -P
must be given in case of HTTPS. (Optional)
.It Sy -r Em files
See
.Xr openssl 1
for more information.
.It Sy -g Em EGD_socket
The name of an EGD socket to get random data from.
(Optional)
.It Em request No ...
List of files containing RFC 3161 DER-encoded timestamp requests.
If no requests are specified only one request will be sent to the server
and it will be read from the standard input.
(Optional)
.El
.Sh ENVIRONMENT VARIABLES
The
.Sy TSGET
environment variable can optionally contain default arguments.
The content of this variable is added to the list of command line
arguments.
.Sh EXAMPLES
The examples below presume that
.Pa file1.tsq
and
.Pa file2.tsq
contain valid timestamp requests, tsa.opentsa.org listens at port 8080
for HTTP requests and at port 8443 for HTTPS requests, the TSA service
is available at the /tsa absolute path.
.Pp
Get a timestamp response for
.Pa file1.tsq
over HTTP, output is written to
.Pa file1.tsr :
.Bd -literal
  tsget -h http://tsa.opentsa.org:8080/tsa file1.tsq
.Ed
.Pp
Get a timestamp response for
.Pa file1.tsq
and
.Pa file2.tsq
over HTTP showing progress, output is written to
.Pa file1.reply
and
.Pa file2.reply
respectively:
.Bd -literal
  tsget -h http://tsa.opentsa.org:8080/tsa -v -e .reply \e
        file1.tsq file2.tsq
.Ed
.Pp
Create a timestamp request, write it to
.Pa file3.tsq ,
send it to the server and write the response to
.Pa file3.tsr :
.Bd -literal
  openssl ts -query -data file3.txt -cert | tee file3.tsq \e
        | tsget -h http://tsa.opentsa.org:8080/tsa \e
        -o file3.tsr
.Ed
.Pp
Get a timestamp response for
.Pa file1.tsq
over HTTPS without client authentication:
.Bd -literal
  tsget -h https://tsa.opentsa.org:8443/tsa \e
        -C cacerts.pem file1.tsq
.Ed
.Pp
Get a timestamp response for
.Pa file1.tsq
over HTTPS with certificate-based client authentication (it will ask for
the passphrase if
.Pa client_key.pem
is protected):
.Bd -literal
  tsget -h https://tsa.opentsa.org:8443/tsa -C cacerts.pem \e
        -k client_key.pem -c client_cert.pem file1.tsq
.Ed
.Pp
You can shorten the previous command line if you make use of the
.Sy TSGET
environment variable.
The following commands do the same as the previous example:
.Bd -literal
  TSGET='-h https://tsa.opentsa.org:8443/tsa -C cacerts.pem \e
        -k client_key.pem -c client_cert.pem'
  export TSGET
  tsget file1.tsq
.Ed
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssl-ts 1 ,
.Xr WWW::Curl::Easy 3p ,
.Lk https://www.rfc-editor.org/rfc/rfc3161.html
.Sh COPYRIGHT
Copyright 2006-2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
