.Dd 2025-09-30
.Dt DES_MODES 7ossl
.Os
.Sh NAME
.Nm des_modes
.Nd the variants of DES and other crypto algorithms of OpenSSL
.Sh DESCRIPTION
Several crypto algorithms for OpenSSL can be used in a number of modes.
Those are used for using block ciphers in a way similar to stream
ciphers, among other things.
.Sh OVERVIEW
.Ss Electronic Codebook Mode (ECB)
Normally, this is found as the function
.Em algorithm Ns
.Xr _ecb_encrypt 3 .
.Bl -bullet
.It
64 bits are enciphered at a time.
.It
The order of the blocks can be rearranged without detection.
.It
The same plaintext block always produces the same ciphertext block (for
the same key) making it vulnerable to a 'dictionary attack'.
.It
An error will only affect one ciphertext block.
.El
.Ss Cipher Block Chaining Mode (CBC)
Normally, this is found as the function
.Em algorithm Ns
.Xr _cbc_encrypt 3 .
Be aware that
.Xr des_cbc_encrypt 3
is not really DES CBC (it does not update the IV); use
.Xr des_ncbc_encrypt 3
instead.
.Bl -bullet
.It
a multiple of 64 bits are enciphered at a time.
.It
The CBC mode produces the same ciphertext whenever the same plaintext is
encrypted using the same key and starting variable.
.It
The chaining operation makes the ciphertext blocks dependent on the
current and all preceding plaintext blocks and therefore blocks can not
be rearranged.
.It
The use of different starting variables prevents the same plaintext
enciphering to the same ciphertext.
.It
An error will affect the current and the following ciphertext blocks.
.El
.Ss Cipher Feedback Mode (CFB)
Normally, this is found as the function
.Em algorithm Ns
.Xr _cfb_encrypt 3 .
.Bl -bullet
.It
a number of bits (j) <= 64 are enciphered at a time.
.It
The CFB mode produces the same ciphertext whenever the same plaintext is
encrypted using the same key and starting variable.
.It
The chaining operation makes the ciphertext variables dependent on the
current and all preceding variables and therefore j-bit variables are
chained together and can not be rearranged.
.It
The use of different starting variables prevents the same plaintext
enciphering to the same ciphertext.
.It
The strength of the CFB mode depends on the size of k (maximal if j ==
k). In my implementation this is always the case.
.It
Selection of a small value for j will require more cycles through the
encipherment algorithm per unit of plaintext and thus cause greater
processing overheads.
.It
Only multiples of j bits can be enciphered.
.It
An error will affect the current and the following ciphertext variables.
.El
.Ss Output Feedback Mode (OFB)
Normally, this is found as the function
.Em algorithm Ns
.Xr _ofb_encrypt 3 .
.Bl -bullet
.It
a number of bits (j) <= 64 are enciphered at a time.
.It
The OFB mode produces the same ciphertext whenever the same plaintext
enciphered using the same key and starting variable.
More over, in the OFB mode the same key stream is produced when the same
key and start variable are used.
Consequently, for security reasons a specific start variable should be
used only once for a given key.
.It
The absence of chaining makes the OFB more vulnerable to specific
attacks.
.It
The use of different start variables values prevents the same plaintext
enciphering to the same ciphertext, by producing different key streams.
.It
Selection of a small value for j will require more cycles through the
encipherment algorithm per unit of plaintext and thus cause greater
processing overheads.
.It
Only multiples of j bits can be enciphered.
.It
OFB mode of operation does not extend ciphertext errors in the resultant
plaintext output.
Every bit error in the ciphertext causes only one bit to be in error in
the deciphered plaintext.
.It
OFB mode is not self-synchronizing.
If the two operation of encipherment and decipherment get out of
synchronism, the system needs to be re-initialized.
.It
Each re-initialization should use a value of the start variable
different from the start variable values used before with the same key.
The reason for this is that an identical bit stream would be produced
each time from the same parameters.
This would be susceptible to a 'known plaintext' attack.
.El
.Ss Triple ECB Mode
Normally, this is found as the function
.Em algorithm Ns
.Xr _ecb3_encrypt 3 .
.Bl -bullet
.It
Encrypt with key1, decrypt with key2 and encrypt with key3 again.
.It
As for ECB encryption but increases the key length to 168 bits.
There are theoretic attacks that can be used that make the effective key
length 112 bits, but this attack also requires 2^56 blocks of memory,
not very likely, even for the NSA.
.It
If both keys are the same it is equivalent to encrypting once with just
one key.
.It
If the first and last key are the same, the key length is 112 bits.
There are attacks that could reduce the effective key strength to only
slightly more than 56 bits, but these require a lot of memory.
.It
If all 3 keys are the same, this is effectively the same as normal ecb
mode.
.El
.Ss Triple CBC Mode
Normally, this is found as the function
.Em algorithm Ns
.Xr _ede3_cbc_encrypt 3 .
.Bl -bullet
.It
Encrypt with key1, decrypt with key2 and then encrypt with key3.
.It
As for CBC encryption but increases the key length to 168 bits with the
same restrictions as for triple ecb mode.
.El
.Sh NOTES
This text was been written in large parts by Eric Young in his original
documentation for SSLeay, the predecessor of OpenSSL. In turn, he
attributed it to:
.Bd -literal
        AS 2805.5.2
        Australian Standard
        Electronic funds transfer - Requirements for interfaces,
        Part 5.2: Modes of operation for an n-bit block cipher algorithm
        Appendix A
.Ed
.Sh SEE ALSO
.Xr BF_encrypt 3 ,
.Xr DES_crypt 3
.Sh COPYRIGHT
Copyright 2000-2017 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
