.Dd 2025-09-30
.Dt EVP_PKEY-DH 7ossl
.Os
.Sh NAME
.Nm EVP_PKEY-DH ,
.Nm EVP_PKEY-DHX ,
.Nm EVP_KEYMGMT-DH ,
.Nm EVP_KEYMGMT-DHX
.Nd EVP_PKEY DH and DHX keytype and algorithm support
.Sh DESCRIPTION
For finite field Diffie-Hellman key agreement, two classes of domain
parameters can be used: "safe" domain parameters that are associated
with approved named safe-prime groups, and a class of "FIPS186-type"
domain parameters.
FIPS186-type domain parameters should only be used for backward
compatibility with existing applications that cannot be upgraded to use
the approved safe-prime groups.
.Pp
See
.Xr EVP_PKEY-FFC 7
for more information about FFC keys.
.Pp
The
.Sy DH
key type uses PKCS#3 format which saves
.Em p
and
.Em g ,
but not the
.Em q
value.
The
.Sy DHX
key type uses X9.42 format which saves the value of
.Em q
and this must be used for FIPS186-4. If key validation is required,
users should be aware of the nuances associated with FIPS186-4 style
parameters as discussed in
.Sx DH and DHX key validation .
.Ss DH and DHX domain parameters
In addition to the common FFC parameters that all FFC keytypes should
support (see
.Xr EVP_PKEY-FFC 7 )
the
.Sy DHX
and
.Sy DH
keytype implementations support the following:
.Bl -tag -width Ds
.It \(dqgroup" ( Ns Sy OSSL_PKEY_PARAM_GROUP_NAME Ns ) <UTF8 string>
Sets or gets a string that associates a
.Sy DH
or
.Sy DHX
named safe prime group with known values for
.Em p ,
.Em q
and
.Em g .
.Pp
The following values can be used by the OpenSSL's default and FIPS
providers: "ffdhe2048", "ffdhe3072", "ffdhe4096", "ffdhe6144",
"ffdhe8192", "modp_2048", "modp_3072", "modp_4096", "modp_6144",
"modp_8192".
.Pp
The following additional values can also be used by OpenSSL's default
provider: "modp_1536", "dh_1024_160", "dh_2048_224", "dh_2048_256".
.Pp
DH/DHX named groups can be easily validated since the parameters are
well known.
For protocols that only transfer
.Em p
and
.Em g
the value of
.Em q
can also be retrieved.
.El
.Ss DH and DHX additional parameters
.Bl -tag -width Ds
.It \(dqencoded-pub-key" ( Ns Sy OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY Ns ) <octet string>
Used for getting and setting the encoding of the DH public key used in a
key exchange message for the TLS protocol.
See
.Xr EVP_PKEY_set1_encoded_public_key 3
and
.Xr EVP_PKEY_get1_encoded_public_key 3 .
.El
.Ss DH additional domain parameters
.Bl -tag -width Ds
.It \(dqsafeprime-generator" ( Ns Sy OSSL_PKEY_PARAM_DH_GENERATOR Ns ) <integer>
Used for DH generation of safe primes using the old safe prime generator
code.
The default value is 2. It is recommended to use a named safe prime
group instead, if domain parameter validation is required.
.Pp
Randomly generated safe primes are not allowed by FIPS, so setting this
value for the OpenSSL FIPS provider will instead choose a named safe
prime group based on the size of
.Em p .
.El
.Ss DH and DHX domain parameter / key generation parameters
In addition to the common FFC key generation parameters that all FFC key
types should support (see
.Xr EVP_PKEY-FFC 7 )
the
.Sy DH
and
.Sy DHX
keytype implementation supports the following:
.Bl -tag -width Ds
.It \(dqtype" ( Ns Sy OSSL_PKEY_PARAM_FFC_TYPE Ns ) <UTF8 string>
Sets the type of parameter generation.
For
.Sy DH
valid values are:
.Bl -tag -width Ds
.It \(dqfips186_4"
.It \(dqdefault"
.It \(dqfips186_2"
These are described in
.Xr EVP_PKEY-FFC 7
.It \(dqgroup"
This specifies that a named safe prime name will be chosen using the
"pbits" type.
.It \(dqgenerator"
A safe prime generator.
See the "safeprime-generator" type above.
This is only valid for
.Sy DH
keys.
.El
.It \(dqpbits" ( Ns Sy OSSL_PKEY_PARAM_FFC_PBITS Ns ) <unsigned integer>
Sets the size (in bits) of the prime 'p'.
.Pp
For "fips186_4" this must be 2048. For "fips186_2" this must be 1024.
For "group" this can be any one of 2048, 3072, 4096, 6144 or 8192.
.It \(dqpriv_len" ( Ns Sy OSSL_PKEY_PARAM_DH_PRIV_LEN Ns ) <integer>
An optional value to set the maximum length of the generated private
key.
The default value used if this is not set is the maximum value of
.Pf BN_num_bits( Em q Ns )).
The minimum value that this can be set to is 2 * s. Where s is the
security strength of the key which has values of 112, 128, 152, 176 and
200 for key sizes of 2048, 3072, 4096, 6144 and 8192.
.El
.Ss DH and DHX key validation
For keys that are not a named group the FIPS186-4 standard specifies
that the values used for FFC parameter generation are also required for
parameter validation.
This means that optional FFC domain parameter values for
.Em seed ,
.Em pcounter
and
.Em gindex
or
.Em hindex
may need to be stored for validation purposes.
For
.Sy DHX
the
.Em seed
and
.Em pcounter
can be stored in ASN1 data (but the
.Em gindex
or
.Em hindex
cannot be stored).
It is recommended to use a
.Sy DH
parameters with named safe prime group instead.
.Pp
With the OpenSSL FIPS provider,
.Xr EVP_PKEY_param_check 3
and
.Xr EVP_PKEY_param_check_quick 3
behave in the following way: the parameters are tested if they are
either an approved safe prime group OR that the FFC parameters conform
to FIPS186-4 as defined in SP800-56Ar3
.Em Assurances of Domain-Parameter Validity .
.Pp
The OpenSSL default provider uses simpler checks that allows there to be
no
.Em q
value for backwards compatibility, however the
.Xr EVP_PKEY_param_check 3
will test the
.Em p
value for being a prime (and a safe prime if
.Em q
is missing) which can take significant time.
The
.Xr EVP_PKEY_param_check_quick 3
avoids the prime tests.
.Pp
.Xr EVP_PKEY_public_check 3
conforms to SP800-56Ar3
.Em FFC Full Public-Key Validation .
.Pp
.Xr EVP_PKEY_public_check_quick 3
conforms to SP800-56Ar3
.Em FFC Partial Public-Key Validation
when the key is an approved named safe prime group, otherwise it is the
same as
.Xr EVP_PKEY_public_check 3 .
.Pp
.Xr EVP_PKEY_private_check 3
tests that the private key is in the correct range according to
SP800-56Ar3. The OpenSSL FIPS provider requires the value of
.Em q
to be set (note that this is implicitly set for named safe prime
groups).
For backwards compatibility the OpenSSL default provider only requires
.Em p
to be set.
.Pp
.Xr EVP_PKEY_pairwise_check 3
conforms to SP800-56Ar3
.Em Owner Assurance of Pair-wise Consistency .
.Sh EXAMPLES
An
.Sy EVP_PKEY
context can be obtained by calling:
.Bd -literal
    EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_from_name(NULL, "DH", NULL);
.Ed
.Pp
A
.Sy DH
key can be generated with a named safe prime group by calling:
.Bd -literal
    int priv_len = 2 * 112;
    OSSL_PARAM params[3];
    EVP_PKEY *pkey = NULL;
    EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_from_name(NULL, "DH", NULL);

    params[0] = OSSL_PARAM_construct_utf8_string("group", "ffdhe2048", 0);
    /* "priv_len" is optional */
    params[1] = OSSL_PARAM_construct_int("priv_len", &priv_len);
    params[2] = OSSL_PARAM_construct_end();

    EVP_PKEY_keygen_init(pctx);
    EVP_PKEY_CTX_set_params(pctx, params);
    EVP_PKEY_generate(pctx, &pkey);
    ...
    EVP_PKEY_free(pkey);
    EVP_PKEY_CTX_free(pctx);
.Ed
.Pp
.Sy DHX
domain parameters can be generated according to
.Sy FIPS186-4
by calling:
.Bd -literal
    int gindex = 2;
    unsigned int pbits = 2048;
    unsigned int qbits = 256;
    OSSL_PARAM params[6];
    EVP_PKEY *param_key = NULL;
    EVP_PKEY_CTX *pctx = NULL;

    pctx = EVP_PKEY_CTX_new_from_name(NULL, "DHX", NULL);
    EVP_PKEY_paramgen_init(pctx);

    params[0] = OSSL_PARAM_construct_uint("pbits", &pbits);
    params[1] = OSSL_PARAM_construct_uint("qbits", &qbits);
    params[2] = OSSL_PARAM_construct_int("gindex", &gindex);
    params[3] = OSSL_PARAM_construct_utf8_string("type", "fips186_4", 0);
    params[4] = OSSL_PARAM_construct_utf8_string("digest", "SHA256", 0);
    params[5] = OSSL_PARAM_construct_end();
    EVP_PKEY_CTX_set_params(pctx, params);

    EVP_PKEY_generate(pctx, &param_key);

    EVP_PKEY_print_params(bio_out, param_key, 0, NULL);
    ...
    EVP_PKEY_free(param_key);
    EVP_PKEY_CTX_free(pctx);
.Ed
.Pp
A
.Sy DH
key can be generated using domain parameters by calling:
.Bd -literal
    EVP_PKEY *key = NULL;
    EVP_PKEY_CTX *gctx = EVP_PKEY_CTX_new_from_pkey(NULL, param_key, NULL);

    EVP_PKEY_keygen_init(gctx);
    EVP_PKEY_generate(gctx, &key);
    EVP_PKEY_print_private(bio_out, key, 0, NULL);
    ...
    EVP_PKEY_free(key);
    EVP_PKEY_CTX_free(gctx);
.Ed
.Pp
To validate
.Sy FIPS186-4
.Sy DHX
domain parameters decoded from
.Sy PEM
or
.Sy DER
data, additional values used during generation may be required to be set
into the key.
.Pp
.Xr EVP_PKEY_todata 3 ,
.Xr OSSL_PARAM_merge 3 ,
and
.Xr EVP_PKEY_fromdata 3
are useful to add these parameters to the original key or domain
parameters before the actual validation.
In production code the return values should be checked.
.Bd -literal
    EVP_PKEY *received_domp = ...; /* parameters received and decoded */
    unsigned char *seed = ...;     /* and additional parameters received */
    size_t seedlen = ...;          /* by other means, required */
    int gindex = ...;              /* for the validation */
    int pcounter = ...;
    int hindex = ...;
    OSSL_PARAM extra_params[4];
    OSSL_PARAM *domain_params = NULL;
    OSSL_PARAM *merged_params = NULL;
    EVP_PKEY_CTX *ctx = NULL, *validate_ctx = NULL;
    EVP_PKEY *complete_domp = NULL;

    EVP_PKEY_todata(received_domp, OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS,
                    &domain_params);
    extra_params[0] = OSSL_PARAM_construct_octet_string("seed", seed, seedlen);
    /*
     * NOTE: For unverifiable g use "hindex" instead of "gindex"
     * extra_params[1] = OSSL_PARAM_construct_int("hindex", &hindex);
     */
    extra_params[1] = OSSL_PARAM_construct_int("gindex", &gindex);
    extra_params[2] = OSSL_PARAM_construct_int("pcounter", &pcounter);
    extra_params[3] = OSSL_PARAM_construct_end();
    merged_params = OSSL_PARAM_merge(domain_params, extra_params);

    ctx = EVP_PKEY_CTX_new_from_name(NULL, "DHX", NULL);
    EVP_PKEY_fromdata_init(ctx);
    EVP_PKEY_fromdata(ctx, &complete_domp, OSSL_KEYMGMT_SELECT_ALL,
                      merged_params);

    validate_ctx = EVP_PKEY_CTX_new_from_pkey(NULL, complete_domp, NULL);
    if (EVP_PKEY_param_check(validate_ctx) > 0)
        /* validation_passed(); */
    else
        /* validation_failed(); */

    OSSL_PARAM_free(domain_params);
    OSSL_PARAM_free(merged_params);
    EVP_PKEY_CTX_free(ctx);
    EVP_PKEY_CTX_free(validate_ctx);
    EVP_PKEY_free(complete_domp);
.Ed
.Sh CONFORMING TO
.Bl -tag -width Ds
.It RFC 7919 (TLS ffdhe named safe prime groups)
.It RFC 3526 (IKE modp named safe prime groups)
.It RFC 5114 (Additional DH named groups for dh_1024_160", \(dqdh_2048_224" and \(dqdh_2048_256").
.El
The following sections of SP800-56Ar3:
.Bl -tag -width Ds
.It 5.5.1.1 FFC Domain Parameter Selection/Generation
.It Appendix D: FFC Safe-prime Groups
.El
The following sections of FIPS186-4:
.Bl -tag -width Ds
.It A.1.1.2 Generation of Probable Primes p and q Using an Approved Hash Function.
.It A.2.3 Generation of canonical generator g.
.It A.2.1 Unverifiable Generation of the Generator g.
.El
.Sh SEE ALSO
.Xr EVP_PKEY-FFC 7 ,
.Xr EVP_KEYEXCH-DH 7
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7 ,
.Xr EVP_KEYMGMT 3 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-FIPS 7
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
