.Dd 2025-09-30
.Dt EVP_SIGNATURE-HMAC 7ossl
.Os
.Sh NAME
.Nm EVP_SIGNATURE-HMAC ,
.Nm EVP_SIGNATURE-Siphash ,
.Nm EVP_SIGNATURE-Poly1305 ,
.Nm EVP_SIGNATURE-CMAC
.Nd The legacyEVP_PKEY No MAC signature implementations
.Sh DESCRIPTION
The algorithms described here have legacy support for creating MACs
using
.Xr EVP_DigestSignInit 3
and related functions.
This is not the preferred way of creating MACs.
Instead you should use the newer
.Xr EVP_MAC_init 3
functions.
This mechanism is provided for backwards compatibility with older
versions of OpenSSL.
.Pp
The same signature parameters can be set using
.Xr EVP_PKEY_CTX_set_params 3
as can be set via
.Xr EVP_MAC_CTX_set_params 3
for the underlying EVP_MAC. See
.Xr EVP_MAC-HMAC 7 ,
.Xr EVP_MAC-Siphash 7 ,
.Xr EVP_MAC-Poly1305 7
and
.Xr EVP_MAC-CMAC 7
for details.
.Bd -literal
 See L<EVP_PKEY-HMAC(7)>, L<EVP_PKEY-Siphash(7)>, L<EVP_PKEY-Poly1305(7)> or
 L<EVP_PKEY-CMAC(7)> for details about parameters that are supported during the
 creation of an EVP_PKEY.
.Ed
.Sh SEE ALSO
.Xr EVP_MAC_init 3 ,
.Xr EVP_DigestSignInit 3 ,
.Xr EVP_PKEY-HMAC 7 ,
.Xr EVP_PKEY-Siphash 7 ,
.Xr EVP_PKEY-Poly1305 7 ,
.Xr EVP_PKEY-CMAC 7 ,
.Xr EVP_MAC-HMAC 7 ,
.Xr EVP_MAC-Siphash 7 ,
.Xr EVP_MAC-Poly1305 7 ,
.Xr EVP_MAC-CMAC 7 ,
.Xr provider-signature 7 ,
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
