.Dd 2025-09-30
.Dt EVP_MD-SHAKE 7ossl
.Os
.Sh NAME
.Nm EVP_MD-SHAKE ,
.Nm EVP_MD-KECCAK-KMAC
.Nd The SHAKE / KECCAK family EVP_MD implementations
.Sh DESCRIPTION
Support for computing SHAKE or KECCAK-KMAC digests through the
.Sy EVP_MD
API.
.Pp
KECCAK-KMAC is an Extendable Output Function (XOF), with a definition
similar to SHAKE, used by the KMAC EVP_MAC implementation (see
.Xr EVP_MAC-KMAC 7 Ns ).
.Ss Identities
This implementation is available in the FIPS provider as well as the
default provider, and includes the following varieties:
.Bl -tag -width Ds
.It KECCAK-KMAC-128
Known names are "KECCAK-KMAC-128" and "KECCAK-KMAC128". This is used by
.Xr EVP_MAC-KMAC128 7 .
Using the notation from NIST FIPS 202 (Section 6.2), we have
.No KECCAK-KMAC-128(M, d)
=
.No KECCAK[256](M || 00, d)
(see the description of KMAC128 in Appendix A of NIST SP 800-185).
.It KECCAK-KMAC-256
Known names are "KECCAK-KMAC-256" and "KECCAK-KMAC256". This is used by
.Xr EVP_MAC-KMAC256 7 .
Using the notation from NIST FIPS 202 (Section 6.2), we have
.No KECCAK-KMAC-256(M, d)
=
.No KECCAK[512](M || 00, d)
(see the description of KMAC256 in Appendix A of NIST SP 800-185).
.It SHAKE-128
Known names are "SHAKE-128" and "SHAKE128".
.It SHAKE-256
Known names are "SHAKE-256" and "SHAKE256".
.El
.Ss Parameters
This implementation supports the following
.Xr OSSL_PARAM 3
entries:
.Bl -tag -width Ds
.It \(dqxoflen" ( Ns Sy OSSL_DIGEST_PARAM_XOFLEN Ns ) <unsigned integer>
Sets or Gets the digest length for extendable output functions.
The length of the "xoflen" parameter should not exceed that of a
.Sy size_t .
.Pp
The SHAKE-128 and SHAKE-256 implementations do not have any default
digest length.
.Pp
This parameter must be set before calling either
.Xr EVP_DigestFinal_ex 3
or
.Xr EVP_DigestFinal 3 ,
since these functions were not designed to handle variable length
output.
It is recommended to either use
.Xr EVP_DigestSqueeze 3
or
.Xr EVP_DigestFinalXOF 3
instead.
.It \(dqsize" ( Ns Sy OSSL_DIGEST_PARAM_SIZE Ns ) <unsigned integer>
An alias of "xoflen".
.El
.Pp
See
.Xr EVP_DigestInit 3
for further information related to parameters
.Sh NOTES
For SHAKE-128, to ensure the maximum security strength of 128 bits, the
output length passed to
.Xr EVP_DigestFinalXOF 3
should be at least 32.
.Pp
For SHAKE-256, to ensure the maximum security strength of 256 bits, the
output length passed to
.Xr EVP_DigestFinalXOF 3
should be at least 64.
.Sh SEE ALSO
.Xr EVP_MD_CTX_set_params 3 ,
.Xr provider-digest 7 ,
.Xr OSSL_PROVIDER-default 7
.Sh HISTORY
Since OpenSSL 3.4 the SHAKE-128 and SHAKE-256 implementations have no
default digest length.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
