.Dd 2025-09-30
.Dt EVP_KEM-X25519 7ossl
.Os
.Sh NAME
.Nm EVP_KEM-X25519 ,
.Nm EVP_KEM-X448
.Nd EVP_KEM X25519 and EVP_KEM X448 keytype and algorithm support
.Sh DESCRIPTION
The
.Sy X25519
and <X448> keytype and its parameters are described in
.Xr EVP_PKEY-X25519 7 .
See
.Xr EVP_PKEY_encapsulate 3
and
.Xr EVP_PKEY_decapsulate 3
for more info.
.Ss X25519 and X448 KEM parameters
.Bl -tag -width Ds
.It \(dqoperation" ( Ns Sy OSSL_KEM_PARAM_OPERATION Ns )<UTF8 string>
The OpenSSL X25519 and X448 Key Encapsulation Mechanisms only support
the following default operation (operating mode):
.Bl -tag -width Ds
.It \(dqDHKEM" ( Ns Sy OSSL_KEM_PARAM_OPERATION_DHKEM )
The encapsulate function generates an ephemeral keypair.
It produces keymaterial by doing an X25519 or X448 key exchange using
the ephemeral private key and a supplied recipient public key.
A HKDF operation using the keymaterial and a kem context then produces a
shared secret.
The shared secret and the ephemeral public key are returned.
The decapsulate function uses the recipient private key and the
ephemeral public key to produce the same keymaterial, which can then be
used to produce the same shared secret.
See
.Lk https://www.rfc-editor.org/rfc/rfc9180.html#name-dh-based-kem-dhkem
.El
.Pp
This can be set using either
.Xr EVP_PKEY_CTX_set_kem_op 3
or
.Xr EVP_PKEY_CTX_set_params 3 .
.It \(dqikme" ( Ns Sy OSSL_KEM_PARAM_IKME Ns ) <octet string>
Used to specify the key material used for generation of the ephemeral
key.
This value should not be reused for other purposes.
It should have a length of at least 32 for X25519, and 56 for X448. If
this value is not set, then a random ikm is used.
.El
.Sh CONFORMING TO
.Bl -tag -width Ds
.It RFC9180
.El
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_set_kem_op 3 ,
.Xr EVP_PKEY_encapsulate 3 ,
.Xr EVP_PKEY_decapsulate 3
.Xr EVP_KEYMGMT 3 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7
.Sh HISTORY
This functionality was added in OpenSSL 3.2.
.Pp
The
.Qo Li operation Qc
(operating mode) was a required parameter prior to OpenSSL 3.5. As of
OpenSSL 3.5,
.Qo Li DHKEM Qc
is the default operating mode, and no explicit value need be specified.
.Sh COPYRIGHT
Copyright 2022-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
