.Dd 2025-09-30
.Dt EVP_PKEY-EC 7ossl
.Os
.Sh NAME
.Nm EVP_PKEY-EC ,
.Nm EVP_KEYMGMT-EC
.Nd EVP_PKEY EC keytype and algorithm support
.Sh DESCRIPTION
The
.Sy EC
keytype is implemented in OpenSSL's default provider.
.Ss Common EC parameters
The normal way of specifying domain parameters for an EC curve is via
the curve name "group".
For curves with no curve name, explicit parameters can be used that
specify "field-type", "p", "a", "b", "generator" and "order".
Explicit parameters are supported for backwards compatibility reasons,
but they are not compliant with multiple standards (including RFC5915)
which only allow named curves.
.Pp
The following Key generation/Gettable/Import/Export types are available
for the built-in EC algorithm:
.Bl -tag -width Ds
.It \(dqgroup" ( Ns Sy OSSL_PKEY_PARAM_GROUP_NAME Ns ) <UTF8 string>
The curve name.
.It \(dqfield-type" ( Ns Sy OSSL_PKEY_PARAM_EC_FIELD_TYPE Ns ) <UTF8 string>
The value should be either "prime-field" or "characteristic-two-field",
which correspond to prime field Fp and binary field F2^m.
.It \(dqp" ( Ns Sy OSSL_PKEY_PARAM_EC_P Ns ) <unsigned integer>
For a curve over Fp
.Em p
is the prime for the field.
For a curve over F2^m
.Em p
represents the irreducible polynomial - each bit represents a term in
the polynomial.
Therefore, there will either be three or five bits set dependent on
whether the polynomial is a trinomial or a pentanomial.
.It \(dqa" ( Ns Sy OSSL_PKEY_PARAM_EC_A Ns ) <unsigned integer>
.It \(dqb" ( Ns Sy OSSL_PKEY_PARAM_EC_B Ns ) <unsigned integer>
.It \(dqseed" ( Ns Sy OSSL_PKEY_PARAM_EC_SEED Ns ) <octet string>
.Em a
and
.Em b
represents the coefficients of the curve For Fp: y^2 mod p = x^3 +ax + b
mod p OR For F2^m: y^2 + xy = x^3 + ax^2 + b
.Pp
.Em seed
is an optional value that is for information purposes only.
It represents the random number seed used to generate the coefficient
.Em b
from a random number.
.It \(dqgenerator" ( Ns Sy OSSL_PKEY_PARAM_EC_GENERATOR Ns ) <octet string>
.It \(dqorder" ( Ns Sy OSSL_PKEY_PARAM_EC_ORDER Ns ) <unsigned integer>
.It \(dqcofactor" ( Ns Sy OSSL_PKEY_PARAM_EC_COFACTOR Ns ) <unsigned integer>
The
.Em generator
is a well defined point on the curve chosen for cryptographic
operations.
The encoding conforms with Sec.
2.3.3 of the SECG SEC 1 ("Elliptic Curve Cryptography") standard.
See
.Xr EC_POINT_oct2point 3 .
Integers used for point multiplications will be between 0 and
.Em order
- 1.
.Em cofactor
is an optional value.
.Em order
multiplied by the
.Em cofactor
gives the number of points on the curve.
.It \(dqdecoded-from-explicit" ( Ns Sy OSSL_PKEY_PARAM_EC_DECODED_FROM_EXPLICIT_PARAMS Ns ) <integer>
Gets a flag indicating whether the key or parameters were decoded from
explicit curve parameters.
Set to 1 if so or 0 if a named curve was used.
.It \(dquse-cofactor-flag" ( Ns Sy OSSL_PKEY_PARAM_USE_COFACTOR_ECDH Ns ) <integer>
Enable Cofactor DH (ECC CDH) if this value is 1, otherwise it uses
normal EC DH if the value is zero.
The cofactor variant multiplies the shared secret by the EC curve's
cofactor (note for some curves the cofactor is 1).
.Pp
See also
.Xr EVP_KEYEXCH-ECDH 7
for the related
.Sy OSSL_EXCHANGE_PARAM_EC_ECDH_COFACTOR_MODE
parameter that can be set on a per-operation basis.
.It \(dqencoding" ( Ns Sy OSSL_PKEY_PARAM_EC_ENCODING Ns ) <UTF8 string>
Set the format used for serializing the EC group parameters.
Valid values are "explicit" or "named_curve".
The default value is "named_curve".
.It \(dqpoint-format" ( Ns Sy OSSL_PKEY_PARAM_EC_POINT_CONVERSION_FORMAT Ns ) <UTF8 string>
Sets or gets the point_conversion_form for the
.Em key .
For a description of point_conversion_forms please see
.Xr EC_POINT_new 3 .
Valid values are "uncompressed" or "compressed".
The default value is "uncompressed".
.It \(dqgroup-check" ( Ns Sy OSSL_PKEY_PARAM_EC_GROUP_CHECK_TYPE Ns ) <UTF8 string>
Sets or Gets the type of group check done when
.Xr EVP_PKEY_param_check 3
is called.
Valid values are "default", "named" and "named-nist".
The "named" type checks that the domain parameters match the inbuilt
curve parameters, "named-nist" is similar but also checks that the named
curve is a nist curve.
The "default" type does domain parameter validation for the OpenSSL
default provider, but is equivalent to "named-nist" for the OpenSSL FIPS
provider.
.It \(dqinclude-public" ( Ns Sy OSSL_PKEY_PARAM_EC_INCLUDE_PUBLIC Ns ) <integer>
Setting this value to 0 indicates that the public key should not be
included when encoding the private key.
The default value of 1 will include the public key.
.It \(dqpub" ( Ns Sy OSSL_PKEY_PARAM_PUB_KEY Ns ) <octet string>
The public key value in encoded EC point format conforming to Sec.
2.3.3 and 2.3.4 of the SECG SEC 1 ("Elliptic Curve Cryptography")
standard.
This parameter is used when importing or exporting the public key value
with the
.Xr EVP_PKEY_fromdata 3
and
.Xr EVP_PKEY_todata 3
functions.
.Pp
Note, in particular, that the choice of point compression format used
for encoding the exported value via
.Xr EVP_PKEY_todata 3
depends on the underlying provider implementation.
Before OpenSSL 3.0.8, the implementation of providers included with
OpenSSL always opted for an encoding in compressed format,
unconditionally.
Since OpenSSL 3.0.8, the implementation has been changed to honor the
.Sy OSSL_PKEY_PARAM_EC_POINT_CONVERSION_FORMAT
parameter, if set, or to default to uncompressed format.
.It \(dqpriv" ( Ns Sy OSSL_PKEY_PARAM_PRIV_KEY Ns ) <unsigned integer>
The private key value.
.It \(dqencoded-pub-key" ( Ns Sy OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY Ns ) <octet string>
Used for getting and setting the encoding of an EC public key.
The public key is expected to be a point conforming to Sec.
2.3.4 of the SECG SEC 1 ("Elliptic Curve Cryptography") standard.
.It \(dqqx" ( Ns Sy OSSL_PKEY_PARAM_EC_PUB_X Ns ) <unsigned integer>
Used for getting the EC public key X component.
.It \(dqqy" ( Ns Sy OSSL_PKEY_PARAM_EC_PUB_Y Ns ) <unsigned integer>
Used for getting the EC public key Y component.
.It \(dqdefault-digest" ( Ns Sy OSSL_PKEY_PARAM_DEFAULT_DIGEST Ns ) <UTF8 string>
Getter that returns the default digest name.
(Currently returns "SHA256" as of OpenSSL 3.0).
.It \(dqdhkem-ikm" ( Ns Sy OSSL_PKEY_PARAM_DHKEM_IKM Ns ) <octet string>
DHKEM requires the generation of a keypair using an input key material
(seed).
Use this to specify the key material used for generation of the private
key.
This value should not be reused for other purposes.
It can only be used for the curves "P-256", "P-384" and "P-521" and
should have a length of at least the size of the encoded private key
(i.e.
32, 48 and 66 for the listed curves).
.El
.Pp
The following Gettable types are also available for the built-in EC
algorithm:
.Bl -tag -width Ds
.It \(dqbasis-type" ( Ns Sy OSSL_PKEY_PARAM_EC_CHAR2_TYPE Ns ) <UTF8 string>
Supports the values "tpBasis" for a trinomial or "ppBasis" for a
pentanomial.
This field is only used for a binary field F2^m.
.It \(dqm" ( Ns Sy OSSL_PKEY_PARAM_EC_CHAR2_M Ns ) <integer>
.It \(dqtp" ( Ns Sy OSSL_PKEY_PARAM_EC_CHAR2_TP_BASIS Ns ) <integer>
.It \(dqk1" ( Ns Sy OSSL_PKEY_PARAM_EC_CHAR2_PP_K1 Ns ) <integer>
.It \(dqk2" ( Ns Sy OSSL_PKEY_PARAM_EC_CHAR2_PP_K2 Ns ) <integer>
.It \(dqk3" ( Ns Sy OSSL_PKEY_PARAM_EC_CHAR2_PP_K3 Ns ) <integer>
These fields are only used for a binary field F2^m.
.Em m
is the degree of the binary field.
.Pp
.Em tp
is the middle bit of a trinomial so its value must be in the range m >
tp > 0.
.Pp
.Em k1 ,
.Em k2
and
.Em k3
are used to get the middle bits of a pentanomial such that m > k3 > k2 >
k1 > 0
.El
.Pp
The following key generation settable parameter is also available for
the OpenSSL FIPS provider's EC algorithm:
.Bl -tag -width Ds
.It \(dqkey-check" ( Ns Sy OSSL_PKEY_PARAM_FIPS_KEY_CHECK Ns ) <integer>
See
.Xr provider-keymgmt 7
for further information.
.El
.Pp
The following key generation Gettable parameter is available for the
OpenSSL FIPS provider's EC algorithm:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_PKEY_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
See
.Xr provider-keymgmt 7
for further information.
.El
.Ss EC key validation
For EC keys,
.Xr EVP_PKEY_param_check 3
behaves in the following way: For the OpenSSL default provider it uses
either
.Xr EC_GROUP_check 3
or
.Xr EC_GROUP_check_named_curve 3
depending on the flag EC_FLAG_CHECK_NAMED_GROUP. The OpenSSL FIPS
provider uses
.Xr EC_GROUP_check_named_curve 3
in order to conform to SP800-56Ar3
.Em Assurances of Domain-Parameter Validity .
.Pp
For EC keys,
.Xr EVP_PKEY_param_check_quick 3
is equivalent to
.Xr EVP_PKEY_param_check 3 .
.Pp
For EC keys,
.Xr EVP_PKEY_public_check 3
and
.Xr EVP_PKEY_public_check_quick 3
conform to SP800-56Ar3
.Em ECC Full Public-Key Validation
and
.Em ECC Partial Public-Key Validation
respectively.
.Pp
For EC Keys,
.Xr EVP_PKEY_private_check 3
and
.Xr EVP_PKEY_pairwise_check 3
conform to SP800-56Ar3
.Em Private key validity
and
.Em Owner Assurance of Pair-wise Consistency
respectively.
.Sh EXAMPLES
An
.Sy EVP_PKEY
context can be obtained by calling:
.Bd -literal
    EVP_PKEY_CTX *pctx =
        EVP_PKEY_CTX_new_from_name(NULL, "EC", NULL);
.Ed
.Pp
An
.Sy EVP_PKEY
ECDSA or ECDH key can be generated with a "P-256" named group by
calling:
.Bd -literal
    pkey = EVP_EC_gen("P-256");
.Ed
.Pp
or like this:
.Bd -literal
    EVP_PKEY *key = NULL;
    OSSL_PARAM params[2];
    EVP_PKEY_CTX *gctx =
        EVP_PKEY_CTX_new_from_name(NULL, "EC", NULL);

    EVP_PKEY_keygen_init(gctx);

    params[0] = OSSL_PARAM_construct_utf8_string(OSSL_PKEY_PARAM_GROUP_NAME,
                                                 "P-256", 0);
    params[1] = OSSL_PARAM_construct_end();
    EVP_PKEY_CTX_set_params(gctx, params);

    EVP_PKEY_generate(gctx, &key);

    EVP_PKEY_print_private(bio_out, key, 0, NULL);
    ...
    EVP_PKEY_free(key);
    EVP_PKEY_CTX_free(gctx);
.Ed
.Pp
An
.Sy EVP_PKEY
EC CDH (Cofactor Diffie-Hellman) key can be generated with a "K-571"
named group by calling:
.Bd -literal
    int use_cdh = 1;
    EVP_PKEY *key = NULL;
    OSSL_PARAM params[3];
    EVP_PKEY_CTX *gctx =
        EVP_PKEY_CTX_new_from_name(NULL, "EC", NULL);

    EVP_PKEY_keygen_init(gctx);

    params[0] = OSSL_PARAM_construct_utf8_string(OSSL_PKEY_PARAM_GROUP_NAME,
                                                 "K-571", 0);
    /*
     * This curve has a cofactor that is not 1 - so setting CDH mode changes
     * the behaviour. For many curves the cofactor is 1 - so setting this has
     * no effect.
     */
    params[1] = OSSL_PARAM_construct_int(OSSL_PKEY_PARAM_USE_COFACTOR_ECDH,
                                         &use_cdh);
    params[2] = OSSL_PARAM_construct_end();
    EVP_PKEY_CTX_set_params(gctx, params);

    EVP_PKEY_generate(gctx, &key);
    EVP_PKEY_print_private(bio_out, key, 0, NULL);
    ...
    EVP_PKEY_free(key);
    EVP_PKEY_CTX_free(gctx);
.Ed
.Sh SEE ALSO
.Xr EVP_EC_gen 3 ,
.Xr EVP_KEYMGMT 3 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7 ,
.Xr EVP_SIGNATURE-ECDSA 7 ,
.Xr EVP_KEYEXCH-ECDH 7
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
