.Dd 2025-09-30
.Dt EVP_PKEY-X25519 7ossl
.Os
.Sh NAME
.Nm EVP_PKEY-X25519 ,
.Nm EVP_PKEY-X448 ,
.Nm EVP_PKEY-ED25519 ,
.Nm EVP_PKEY-ED448 ,
.Nm EVP_KEYMGMT-X25519 ,
.Nm EVP_KEYMGMT-X448 ,
.Nm EVP_KEYMGMT-ED25519 ,
.Nm EVP_KEYMGMT-ED448
.Nd EVP_PKEY X25519, X448, ED25519 and ED448 keytype and algorithm support
.Sh DESCRIPTION
The
.Sy X25519 ,
.Sy X448 ,
.Sy ED25519
and
.Sy ED448
keytypes are implemented in OpenSSL's default and FIPS providers.
These implementations support the associated key, containing the public
key
.Em pub
and the private key
.Em priv .
.Ss Keygen Parameters
.Bl -tag -width Ds
.It \(dqdhkem-ikm" ( Ns Sy OSSL_PKEY_PARAM_DHKEM_IKM Ns ) <octet string>
DHKEM requires the generation of a keypair using an input key material
(seed).
Use this to specify the key material used for generation of the private
key.
This value should not be reused for other purposes.
It should have a length of at least 32 for X25519, and 56 for X448. This
is only supported by X25519 and X448.
.It \(dqfips-indicator" ( Ns Sy OSSL_PKEY_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
This getter is only supported by X25519 and X448 for the FIPS provider.
Since X25519 and X448 are unapproved in FIPS 140-3 this getter return 0.
.Pp
See
.Xr provider-keymgmt 7
for further information.
.El
.Pp
Use
.Xr EVP_PKEY_CTX_set_params 3
after calling
.Xr EVP_PKEY_keygen_init 3 .
.Ss Common X25519, X448, ED25519 and ED448 parameters
In addition to the common parameters that all keytypes should support
(see
.Xr provider-keymgmt 7 Ns ),
the implementation of these keytypes support the following.
.Bl -tag -width Ds
.It \(dqgroup" ( Ns Sy OSSL_PKEY_PARAM_GROUP_NAME Ns ) <UTF8 string>
This is only supported by X25519 and X448. The group name must be
"x25519" or "x448" respectively for those algorithms.
This is only present for consistency with other key exchange algorithms
and is typically not needed.
.It \(dqpub" ( Ns Sy OSSL_PKEY_PARAM_PUB_KEY Ns ) <octet string>
The public key value.
.It \(dqpriv" ( Ns Sy OSSL_PKEY_PARAM_PRIV_KEY Ns ) <octet string>
The private key value.
.It \(dqencoded-pub-key" ( Ns Sy OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY Ns ) <octet string>
Used for getting and setting the encoding of a public key for the
.Sy X25519
and
.Sy X448
key types.
Public keys are expected be encoded in a format as defined by RFC7748.
.El
.Ss ED25519 and ED448 parameters
.Bl -tag -width Ds
.It \(dqmandatory-digest" ( Ns Sy OSSL_PKEY_PARAM_MANDATORY_DIGEST Ns ) <UTF8 string>
The empty string, signifying that no digest may be specified.
.El
.Sh CONFORMING TO
.Bl -tag -width Ds
.It RFC 8032
.It RFC 8410
.El
.Sh EXAMPLES
An
.Sy EVP_PKEY
context can be obtained by calling:
.Bd -literal
    EVP_PKEY_CTX *pctx =
        EVP_PKEY_CTX_new_from_name(NULL, "X25519", NULL);

    EVP_PKEY_CTX *pctx =
        EVP_PKEY_CTX_new_from_name(NULL, "X448", NULL);

    EVP_PKEY_CTX *pctx =
        EVP_PKEY_CTX_new_from_name(NULL, "ED25519", NULL);

    EVP_PKEY_CTX *pctx =
        EVP_PKEY_CTX_new_from_name(NULL, "ED448", NULL);
.Ed
.Pp
An
.Sy X25519
key can be generated like this:
.Bd -literal
    pkey = EVP_PKEY_Q_keygen(NULL, NULL, "X25519");
.Ed
.Pp
An
.Sy X448 ,
.Sy ED25519 ,
or
.Sy ED448
key can be generated likewise.
.Sh SEE ALSO
.Xr EVP_KEYMGMT 3 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7 ,
.Xr EVP_KEYEXCH-X25519 7 ,
.Xr EVP_KEYEXCH-X448 7 ,
.Xr EVP_SIGNATURE-ED25519 7 ,
.Xr EVP_SIGNATURE-ED448 7
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
