.Dd 2025-09-30
.Dt EVP_CIPHER-AES 7ossl
.Os
.Sh NAME
.Nm EVP_CIPHER-AES
.Nd The AES EVP_CIPHER implementations
.Sh DESCRIPTION
Support for AES symmetric encryption using the
.Sy EVP_CIPHER
API.
.Ss Algorithm Names
The following algorithms are available in the FIPS provider as well as
the default provider:
.Bl -tag -width Ds
.It \(dqAES-128-CBC", \(dqAES-192-CBC" and \(dqAES-256-CBC"
.It \(dqAES-128-CBC-CTS", \(dqAES-192-CBC-CTS" and \(dqAES-256-CBC-CTS"
.It \(dqAES-128-CFB", \(dqAES-192-CFB", \(dqAES-256-CFB", \(dqAES-128-CFB1", \(dqAES-192-CFB1", \(dqAES-256-CFB1", \(dqAES-128-CFB8", \(dqAES-192-CFB8" and \(dqAES-256-CFB8"
.It \(dqAES-128-CTR", \(dqAES-192-CTR" and \(dqAES-256-CTR"
.It \(dqAES-128-ECB", \(dqAES-192-ECB" and \(dqAES-256-ECB"
.It \(dqAES-192-OFB", \(dqAES-128-OFB" and \(dqAES-256-OFB"
.It \(dqAES-128-XTS" and \(dqAES-256-XTS"
.It \(dqAES-128-CCM", \(dqAES-192-CCM" and \(dqAES-256-CCM"
.It \(dqAES-128-GCM", \(dqAES-192-GCM" and \(dqAES-256-GCM"
.It \(dqAES-128-WRAP", \(dqAES-192-WRAP", \(dqAES-256-WRAP", \(dqAES-128-WRAP-PAD", \(dqAES-192-WRAP-PAD", \(dqAES-256-WRAP-PAD", \(dqAES-128-WRAP-INV", \(dqAES-192-WRAP-INV", \(dqAES-256-WRAP-INV", \(dqAES-128-WRAP-PAD-INV", \(dqAES-192-WRAP-PAD-INV" and \(dqAES-256-WRAP-PAD-INV"
.It \(dqAES-128-CBC-HMAC-SHA1", \(dqAES-256-CBC-HMAC-SHA1", \(dqAES-128-CBC-HMAC-SHA256" and \(dqAES-256-CBC-HMAC-SHA256"
.El
The following algorithms are available in the default provider, but not
the FIPS provider:
.Bl -tag -width Ds
.It \(dqAES-128-OCB", \(dqAES-192-OCB" and \(dqAES-256-OCB"
.It \(dqAES-128-SIV", \(dqAES-192-SIV" and \(dqAES-256-SIV"
.It \(dqAES-128-GCM-SIV", \(dqAES-192-GCM-SIV" and \(dqAES-256-GCM-SIV"
.El
.Ss Parameters
This implementation supports the parameters described in
.Xr EVP_EncryptInit 3 .
.Sh NOTES
The AES-SIV and AES-WRAP mode implementations do not support streaming.
That means to obtain correct results there can be only one
.Xr EVP_EncryptUpdate 3
or
.Xr EVP_DecryptUpdate 3
call after the initialization of the context.
.Pp
The AES-XTS implementations allow streaming to be performed, but each
.Xr EVP_EncryptUpdate 3
or
.Xr EVP_DecryptUpdate 3
call requires each input to be a multiple of the blocksize.
Only the final
.Xr EVP_EncryptUpdate 3
or
.Xr EVP_DecryptUpdate 3
call can optionally have an input that is not a multiple of the
blocksize but is larger than one block.
In that case ciphertext stealing (CTS) is used to fill the block.
.Sh SEE ALSO
.Xr provider-cipher 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr OSSL_PROVIDER-default 7
.Sh HISTORY
The GCM-SIV mode ciphers were added in OpenSSL version 3.2.
.Sh COPYRIGHT
Copyright 2021-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
