.Dd 2025-09-30
.Dt EVP_PKEY-HMAC 7ossl
.Os
.Sh NAME
.Nm EVP_PKEY-HMAC ,
.Nm EVP_KEYMGMT-HMAC ,
.Nm EVP_PKEY-Siphash ,
.Nm EVP_KEYMGMT-Siphash ,
.Nm EVP_PKEY-Poly1305 ,
.Nm EVP_KEYMGMT-Poly1305 ,
.Nm EVP_PKEY-CMAC ,
.Nm EVP_KEYMGMT-CMAC
.Nd EVP_PKEY legacy MAC keytypes and algorithm support
.Sh DESCRIPTION
The
.Sy HMAC
and
.Sy CMAC
key types are implemented in OpenSSL's default and FIPS providers.
Additionally the
.Sy Siphash
and
.Sy Poly1305
key types are implemented in the default provider.
Performing MAC operations via an EVP_PKEY is considered legacy and are
only available for backwards compatibility purposes and for a restricted
set of algorithms.
The preferred way of performing MAC operations is via the EVP_MAC APIs.
See
.Xr EVP_MAC_init 3 .
.Pp
For further details on using EVP_PKEY based MAC keys see
.Xr EVP_SIGNATURE-HMAC 7 ,
.Xr EVP_SIGNATURE-Siphash 7 ,
.Xr EVP_SIGNATURE-Poly1305 7
or
.Xr EVP_SIGNATURE-CMAC 7 .
.Ss Common MAC parameters
All the
.Sy MAC
keytypes support the following parameters.
.Bl -tag -width Ds
.It \(dqpriv" ( Ns Sy OSSL_PKEY_PARAM_PRIV_KEY Ns ) <octet string>
The MAC key value.
.It \(dqproperties" ( Ns Sy OSSL_PKEY_PARAM_PROPERTIES Ns ) <UTF8 string>
A property query string to be used when any algorithms are fetched.
.El
.Ss CMAC parameters
As well as the parameters described above, the
.Sy CMAC
keytype additionally supports the following parameters.
.Bl -tag -width Ds
.It \(dqcipher" ( Ns Sy OSSL_PKEY_PARAM_CIPHER Ns ) <UTF8 string>
The name of a cipher to be used when generating the MAC.
.It \(dqengine" ( Ns Sy OSSL_PKEY_PARAM_ENGINE Ns ) <UTF8 string>
The name of an engine to be used for the specified cipher (if any).
.El
.Ss Common MAC key generation parameters
MAC key generation is unusual in that no new key is actually generated.
Instead a new provider side key object is created with the supplied raw
key value.
This is done for backwards compatibility with previous versions of
OpenSSL.
.Bl -tag -width Ds
.It \(dqpriv" ( Ns Sy OSSL_PKEY_PARAM_PRIV_KEY Ns ) <octet string>
The MAC key value.
.El
.Ss CMAC key generation parameters
In addition to the common MAC key generation parameters, the CMAC key
generation additionally recognises the following.
.Bl -tag -width Ds
.It \(dqcipher" ( Ns Sy OSSL_PKEY_PARAM_CIPHER Ns ) <UTF8 string>
The name of a cipher to be used when generating the MAC.
.El
.Sh SEE ALSO
.Xr EVP_KEYMGMT 3 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
