.Dd 2025-09-30
.Dt EVP_KDF-PVKKDF 7ossl
.Os
.Sh NAME
.Nm EVP_KDF-PVKKDF
.Nd The PVK EVP_KDF implementation
.Sh DESCRIPTION
Support for computing the
.Sy PVK KDF
PIN-based KDF through the
.Sy EVP_KDF
API.
.Pp
The EVP_KDF-PVKKDF algorithm implements a PVK PIN-based key derivation
function; it derives a key from a password using a salt.
.Ss Identity
"PVKKDF" is the name for this implementation; it can be used with the
.Xr EVP_KDF_fetch 3
function.
.Ss Supported parameters
The supported parameters are:
.Bl -tag -width Ds
.It \(dqpass" ( Ns Sy OSSL_KDF_PARAM_PASSWORD Ns ) <octet string>
.It \(dqsalt" ( Ns Sy OSSL_KDF_PARAM_SALT Ns ) <octet string>
.It \(dqproperties" ( Ns Sy OSSL_KDF_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_KDF_PARAM_DIGEST Ns ) <UTF8 string>
These parameters work as described in
.Xr EVP_KDF 3 .
.El
.Sh NOTES
A typical application of this algorithm is to derive keying material for
an encryption algorithm from a password in the "pass" and a salt in
"salt".
.Pp
No assumption is made regarding the given password; it is simply treated
as a byte sequence.
.Pp
The legacy provider needs to be available in order to access this
algorithm.
.Sh SEE ALSO
.Xr EVP_KDF 3 ,
.Xr EVP_KDF_CTX_new 3 ,
.Xr EVP_KDF_CTX_free 3 ,
.Xr EVP_KDF_CTX_set_params 3 ,
.Xr EVP_KDF_derive 3 ,
.Xr EVP_KDF 3 ,
.Xr OSSL_PROVIDER-legacy 7
.Sh HISTORY
This functionality was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
