.Dd 2025-09-30
.Dt EVP_ASYM_CIPHER-SM2 7ossl
.Os
.Sh NAME
.Nm EVP_ASYM_CIPHER-SM2
.Nd SM2 Asymmetric Cipher algorithm support
.Sh DESCRIPTION
Asymmetric Cipher support for the
.Sy SM2
key type.
.Ss SM2 Asymmetric Cipher parameters
.Bl -tag -width Ds
.It \(dqdigest" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqdigest-props" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_DIGEST_PROPS Ns ) <UTF8 string>
See
.Xr provider-asym_cipher 7 .
.El
.Sh SEE ALSO
.Xr EVP_PKEY-SM2 7 ,
.Xr EVP_PKEY 3 ,
.Xr provider-asym_cipher 7 ,
.Xr provider-keymgmt 7 ,
.Xr OSSL_PROVIDER-default 7
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
