.Dd 2025-09-30
.Dt EVP_RAND-HASH-DRBG 7ossl
.Os
.Sh NAME
.Nm EVP_RAND-HASH-DRBG
.Nd The HASH DRBG EVP_RAND implementation
.Sh DESCRIPTION
Support for the hash deterministic random bit generator through the
.Sy EVP_RAND
API.
.Ss Identity
"HASH-DRBG" is the name for this implementation; it can be used with the
.Xr EVP_RAND_fetch 3
function.
.Ss Supported parameters
The supported parameters are:
.Bl -tag -width Ds
.It \(dqstate" ( Ns Sy OSSL_RAND_PARAM_STATE Ns ) <integer>
.It \(dqstrength" ( Ns Sy OSSL_RAND_PARAM_STRENGTH Ns ) <unsigned integer>
.It \(dqmax_request" ( Ns Sy OSSL_RAND_PARAM_MAX_REQUEST Ns ) <unsigned integer>
.It \(dqreseed_requests" ( Ns Sy OSSL_DRBG_PARAM_RESEED_REQUESTS Ns ) <unsigned integer>
.It \(dqreseed_time_interval" ( Ns Sy OSSL_DRBG_PARAM_RESEED_TIME_INTERVAL Ns ) <integer>
.It \(dqmin_entropylen" ( Ns Sy OSSL_DRBG_PARAM_MIN_ENTROPYLEN Ns ) <unsigned integer>
.It \(dqmax_entropylen" ( Ns Sy OSSL_DRBG_PARAM_MAX_ENTROPYLEN Ns ) <unsigned integer>
.It \(dqmin_noncelen" ( Ns Sy OSSL_DRBG_PARAM_MIN_NONCELEN Ns ) <unsigned integer>
.It \(dqmax_noncelen" ( Ns Sy OSSL_DRBG_PARAM_MAX_NONCELEN Ns ) <unsigned integer>
.It \(dqmax_perslen" ( Ns Sy OSSL_DRBG_PARAM_MAX_PERSLEN Ns ) <unsigned integer>
.It \(dqmax_adinlen" ( Ns Sy OSSL_DRBG_PARAM_MAX_ADINLEN Ns ) <unsigned integer>
.It \(dqreseed_counter" ( Ns Sy OSSL_DRBG_PARAM_RESEED_COUNTER Ns ) <unsigned integer>
.It \(dqproperties" ( Ns Sy OSSL_DRBG_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_DRBG_PARAM_DIGEST Ns ) <UTF8 string>
These parameters work as described in
.Xr EVP_RAND 3 .
.It \(dqfips-indicator" ( Ns Sy OSSL_DRBG_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
.It \(dqdigest-check" ( Ns Sy OSSL_DRBG_PARAM_FIPS_DIGEST_CHECK Ns ) <integer>
These parameters work as described in
.Xr provider-rand 7 .
.El
.Sh NOTES
When the FIPS provider is installed using the
.Sy -no_drbg_truncated_digests
option to fipsinstall, only these digests are permitted (as per
.Lk https://csrc.nist.gov/CSRC/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf Ns ):
.Pp
The default HASH-DRBG implementation attempts to fetch the required
internal algorithms from the provider they are built into (eg the
default provider) regardless of the properties provided.
Should the provider not implement the required algorithms then
properties will be used to find a different implementation.
.Bl -tag -width Ds
.It SHA-1
.It SHA2-256
.It SHA2-512
.It SHA3-256
.It SHA3-512
.El
A context for HASH DRBG can be obtained by calling:
.Bd -literal
 EVP_RAND *rand = EVP_RAND_fetch(NULL, "HASH-DRBG", NULL);
 EVP_RAND_CTX *rctx = EVP_RAND_CTX_new(rand, NULL);
.Ed
.Sh EXAMPLES
.Bd -literal
 EVP_RAND *rand;
 EVP_RAND_CTX *rctx;
 unsigned char bytes[100];
 OSSL_PARAM params[2], *p = params;
 unsigned int strength = 128;

 rand = EVP_RAND_fetch(NULL, "HASH-DRBG", NULL);
 rctx = EVP_RAND_CTX_new(rand, NULL);
 EVP_RAND_free(rand);

 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_DRBG_PARAM_DIGEST, SN_sha512, 0);
 *p = OSSL_PARAM_construct_end();
 EVP_RAND_instantiate(rctx, strength, 0, NULL, 0, params);

 EVP_RAND_generate(rctx, bytes, sizeof(bytes), strength, 0, NULL, 0);

 EVP_RAND_CTX_free(rctx);
.Ed
.Sh CONFORMING TO
NIST SP 800-90A and SP 800-90B
.Sh SEE ALSO
.Xr EVP_RAND 3 ,
.Xr EVP_RAND 3 ,
.Xr openssl-fipsinstall 1
.Sh HISTORY
OpenSSL 3.1.1 introduced the
.Sy -no_drbg_truncated_digests
option to fipsinstall which restricts the permitted digests when using
the FIPS provider in a complaint manner.
For details refer to
.Lk https://csrc.nist.gov/CSRC/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf .
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
