.Dd 2025-09-30
.Dt EVP_KDF-SS 7ossl
.Os
.Sh NAME
.Nm EVP_KDF-SS
.Nd The Single Step / One Step EVP_KDF implementation
.Sh DESCRIPTION
The EVP_KDF-SS algorithm implements the Single Step key derivation
function (SSKDF). SSKDF derives a key using input such as a shared
secret key (that was generated during the execution of a key
establishment scheme) and fixedinfo.
SSKDF is also informally referred to as 'Concat KDF'.
.Pp
The output is considered to be keying material.
.Ss Auxiliary function
The implementation uses a selectable auxiliary function H, which can be
one of:
.Bl -tag -width Ds
.It Sy H(x) = hash(x, digest=md)
.It Sy H(x) = HMAC_hash(x, key=salt, digest=md)
.It Sy H(x) = KMACxxx(x, key=salt, custom="KDF", outlen=mac_size)
.El
Both the HMAC and KMAC implementations set the key using the 'salt'
value.
The hash and HMAC also require the digest to be set.
.Ss Identity
"SSKDF" is the name for this implementation; it can be used with the
.Xr EVP_KDF_fetch 3
function.
.Ss Supported parameters
The supported parameters are:
.Bl -tag -width Ds
.It \(dqproperties" ( Ns Sy OSSL_KDF_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_KDF_PARAM_DIGEST Ns ) <UTF8 string>
This parameter is ignored for KMAC.
.It \(dqmac" ( Ns Sy OSSL_KDF_PARAM_MAC Ns ) <UTF8 string>
.It \(dqmaclen" ( Ns Sy OSSL_KDF_PARAM_MAC_SIZE Ns ) <unsigned integer>
.It \(dqsalt" ( Ns Sy OSSL_KDF_PARAM_SALT Ns ) <octet string>
These parameters work as described in
.Xr EVP_KDF 3 .
.It \(dqkey" ( Ns Sy OSSL_KDF_PARAM_SECRET Ns ) <octet string>
This parameter set the shared secret that is used for key derivation.
.It \(dqinfo" ( Ns Sy OSSL_KDF_PARAM_INFO Ns ) <octet string>
This parameter sets an optional value for fixedinfo, also known as
otherinfo.
.El
.Pp
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_KDF_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling EVP_KDF_derive.
It returns 0 if "key-check" is set to 0 and the check fails.
.It \(dqkey-check" ( Ns Sy OSSL_KDF_PARAM_FIPS_KEY_CHECK Ns ) <integer>
The default value of 1 causes an error during
.Xr EVP_KDF_CTX_set_params 3
if the length of used key-derivation key
.Pf ( Sy OSSL_KDF_PARAM_KEY )
is shorter than 112 bits.
Setting this to zero will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Sh NOTES
A context for SSKDF can be obtained by calling:
.Bd -literal
 EVP_KDF *kdf = EVP_KDF_fetch(NULL, "SSKDF", NULL);
 EVP_KDF_CTX *kctx = EVP_KDF_CTX_new(kdf);
.Ed
.Pp
The output length of an SSKDF is specified via the
.Em keylen
parameter to the
.Xr EVP_KDF_derive 3
function.
.Sh EXAMPLES
This example derives 10 bytes using H(x) = SHA-256, with the secret key
"secret" and fixedinfo value "label":
.Bd -literal
 EVP_KDF *kdf;
 EVP_KDF_CTX *kctx;
 unsigned char out[10];
 OSSL_PARAM params[4], *p = params;

 kdf = EVP_KDF_fetch(NULL, "SSKDF", NULL);
 kctx = EVP_KDF_CTX_new(kdf);
 EVP_KDF_free(kdf);

 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_DIGEST,
                                         SN_sha256, strlen(SN_sha256));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_KEY,
                                          "secret", (size_t)6);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_INFO,
                                          "label", (size_t)5);
 *p = OSSL_PARAM_construct_end();
 if (EVP_KDF_derive(kctx, out, sizeof(out), params) <= 0) {
     error("EVP_KDF_derive");
 }

 EVP_KDF_CTX_free(kctx);
.Ed
.Pp
This example derives 10 bytes using H(x) = HMAC(SHA-256), with the
secret key "secret", fixedinfo value "label" and salt "salt":
.Bd -literal
 EVP_KDF *kdf;
 EVP_KDF_CTX *kctx;
 unsigned char out[10];
 OSSL_PARAM params[6], *p = params;

 kdf = EVP_KDF_fetch(NULL, "SSKDF", NULL);
 kctx = EVP_KDF_CTX_new(kdf);
 EVP_KDF_free(kdf);

 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_MAC,
                                         SN_hmac, strlen(SN_hmac));
 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_DIGEST,
                                         SN_sha256, strlen(SN_sha256));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SECRET,
                                          "secret", (size_t)6);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_INFO,
                                          "label", (size_t)5);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SALT,
                                          "salt", (size_t)4);
 *p = OSSL_PARAM_construct_end();
 if (EVP_KDF_derive(kctx, out, sizeof(out), params) <= 0) {
     error("EVP_KDF_derive");
 }

 EVP_KDF_CTX_free(kctx);
.Ed
.Pp
This example derives 10 bytes using H(x) = KMAC128(x,salt,outlen), with
the secret key "secret" fixedinfo value "label", salt of "salt" and KMAC
outlen of 20:
.Bd -literal
 EVP_KDF *kdf;
 EVP_KDF_CTX *kctx;
 unsigned char out[10];
 OSSL_PARAM params[6], *p = params;

 kdf = EVP_KDF_fetch(NULL, "SSKDF", NULL);
 kctx = EVP_KDF_CTX_new(kdf);
 EVP_KDF_free(kdf);

 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_MAC,
                                         SN_kmac128, strlen(SN_kmac128));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SECRET,
                                          "secret", (size_t)6);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_INFO,
                                          "label", (size_t)5);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SALT,
                                          "salt", (size_t)4);
 *p++ = OSSL_PARAM_construct_size_t(OSSL_KDF_PARAM_MAC_SIZE, (size_t)20);
 *p = OSSL_PARAM_construct_end();
 if (EVP_KDF_derive(kctx, out, sizeof(out), params) <= 0) {
     error("EVP_KDF_derive");
 }

 EVP_KDF_CTX_free(kctx);
.Ed
.Sh CONFORMING TO
NIST SP800-56Cr1.
.Sh SEE ALSO
.Xr EVP_KDF 3 ,
.Xr EVP_KDF_CTX_new 3 ,
.Xr EVP_KDF_CTX_free 3 ,
.Xr EVP_KDF_CTX_set_params 3 ,
.Xr EVP_KDF_CTX_get_kdf_size 3 ,
.Xr EVP_KDF_derive 3 ,
.Xr EVP_KDF 3
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2024 The OpenSSL Project Authors.
All Rights Reserved.
Copyright (c) 2019, Oracle and/or its affiliates.
All rights reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
