.Dd 2025-09-30
.Dt EVP_KEYEXCH-ECDH 7ossl
.Os
.Sh NAME
.Nm EVP_KEYEXCH-ECDH
.Nd ECDH Key Exchange algorithm support
.Sh DESCRIPTION
Key exchange support for the
.Sy ECDH
key type.
.Ss ECDH Key Exchange parameters
.Bl -tag -width Ds
.It \(dqecdh-cofactor-mode" ( Ns Sy OSSL_EXCHANGE_PARAM_EC_ECDH_COFACTOR_MODE Ns ) <integer>
Sets or gets the ECDH mode of operation for the associated key exchange
ctx.
.Pp
In the context of an Elliptic Curve Diffie-Hellman key exchange, this
parameter can be used to select between the plain Diffie-Hellman (DH) or
Cofactor Diffie-Hellman (CDH) variants of the key exchange algorithm.
.Pp
When setting, the value should be 1, 0 or -1, respectively forcing
cofactor mode on, off, or resetting it to the default for the private
key associated with the given key exchange ctx.
.Pp
When getting, the value should be either 1 or 0, respectively signaling
if the cofactor mode is on or off.
.Pp
See also
.Xr provider-keymgmt 7
for the related
.Sy OSSL_PKEY_PARAM_USE_COFACTOR_ECDH
parameter that can be set on a per-key basis.
.It \(dqkdf-type" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_TYPE Ns ) <UTF8 string>
.It \(dqkdf-digest" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_DIGEST Ns ) <UTF8 string>
.It \(dqkdf-digest-props" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_DIGEST_PROPS Ns ) <UTF8 string>
.It \(dqkdf-outlen" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_OUTLEN Ns ) <unsigned integer>
.It \(dqkdf-ukm" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_UKM Ns ) <octet string>
.El
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
.It \(dqkey-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_KEY_CHECK Ns ) <integer>
.It \(dqdigest-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_DIGEST_CHECK Ns ) <integer>
See
.Xr provider-keyexch 7 .
.It \(dqecdh-cofactor-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_ECDH_COFACTOR_CHECK Ns ) <integer>
If required this parameter should before
.Xr OSSL_FUNC_keyexch_derive 3 .
The default value of 1 causes an error during the
OSSL_FUNC_keyexch_derive if the EC curve has a cofactor that is not 1,
and the cofactor is not used.
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Sh EXAMPLES
Examples of key agreement can be found in demos/keyexch.
.Pp
Keys for the host and peer must be generated as shown in
.Xr EVP_PKEY-EC 7
using the same curve name.
.Pp
The code to generate a shared secret for the normal case is identical to
.Xr EVP_KEYEXCH-DH 7 .
.Pp
To derive a shared secret on the host using the host's key and the
peer's public key but also using X963KDF with a user key material:
.Bd -literal
    /* It is assumed that the host_key, peer_pub_key and ukm are set up */
    void derive_secret(EVP_PKEY *host_key, EVP_PKEY *peer_key,
                       unsigned char *ukm, size_t ukm_len)
    {
        unsigned char secret[64];
        size_t out_len = sizeof(secret);
        size_t secret_len = out_len;
        unsigned int pad = 1;
        OSSL_PARAM params[6];
        EVP_PKEY_CTX *dctx = EVP_PKEY_CTX_new_from_pkey(NULL, host_key, NULL);

        EVP_PKEY_derive_init(dctx);

        params[0] = OSSL_PARAM_construct_uint(OSSL_EXCHANGE_PARAM_PAD, &pad);
        params[1] = OSSL_PARAM_construct_utf8_string(OSSL_EXCHANGE_PARAM_KDF_TYPE,
                                                     "X963KDF", 0);
        params[2] = OSSL_PARAM_construct_utf8_string(OSSL_EXCHANGE_PARAM_KDF_DIGEST,
                                                     "SHA1", 0);
        params[3] = OSSL_PARAM_construct_size_t(OSSL_EXCHANGE_PARAM_KDF_OUTLEN,
                                                &out_len);
        params[4] = OSSL_PARAM_construct_octet_string(OSSL_EXCHANGE_PARAM_KDF_UKM,
                                                      ukm, ukm_len);
        params[5] = OSSL_PARAM_construct_end();
        EVP_PKEY_CTX_set_params(dctx, params);

        EVP_PKEY_derive_set_peer(dctx, peer_pub_key);
        EVP_PKEY_derive(dctx, secret, &secret_len);
        ...
        OPENSSL_clear_free(secret, secret_len);
        EVP_PKEY_CTX_free(dctx);
    }
.Ed
.Sh SEE ALSO
.Xr EVP_PKEY-EC 7
.Xr EVP_PKEY 3 ,
.Xr provider-keyexch 7 ,
.Xr provider-keymgmt 7 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
