.Dd 2025-09-30
.Dt EVP_SIGNATURE-DSA 7ossl
.Os
.Sh NAME
.Nm EVP_SIGNATURE-DSA
.Nd TheEVP_PKEY No DSA signature implementation
.Sh DESCRIPTION
Support for computing DSA signatures.
The signature produced with
.Xr EVP_PKEY_sign 3
is DER encoded ASN.1 in the form described in RFC 3279, section 2.2.2.
See
.Xr EVP_PKEY-DSA 7
for information related to DSA keys.
.Pp
As part of FIPS 140-3 DSA is not longer FIPS approved for key generation
and signature validation, but is still allowed for signature
verification.
.Ss Algorithm Names
In this list, names are grouped together to signify that they are the
same algorithm having multiple names.
This also includes the OID in canonical decimal form (which means that
they are possible to fetch if the caller has a mere OID which came out
in this form after a call to
.Xr OBJ_obj2txt 3 Ns ).
.Bl -tag -width Ds
.It \(dqDSA", \(dqdsaEncryption", \(dq1.2.840.10040.4.1"
The base signature algorithm, supported explicitly fetched with
.Xr EVP_PKEY_sign_init_ex2 3 ,
and implicitly fetched (through
.Xr EVP_PKEY-EC 7 )
with
.Xr EVP_DigestSignInit 3
and
.Xr EVP_DigestVerifyInit 3 .
.Pp
It can't be used with
.Xr EVP_PKEY_sign_message_init 3
.It \(dqDSA-SHA1", \(dqDSA-SHA-1", \(dqdsaWithSHA1", \(dq1.2.840.10040.4.3"
.It \(dqDSA-SHA2-224", \(dqDSA-SHA224", \(dqdsa_with_SHA224", \(dq2.16.840.1.101.3.4.3.1"
.It \(dqDSA-SHA2-256", \(dqDSA-SHA256", \(dqdsa_with_SHA256", \(dq2.16.840.1.101.3.4.3.2"
.It \(dqDSA-SHA2-384", \(dqDSA-SHA384", \(dqdsa_with_SHA384", \(dqid-dsa-with-sha384", \(dq1.2.840.1.101.3.4.3.3"
.It \(dqDSA-SHA2-512", \(dqDSA-SHA512", \(dqdsa_with_SHA512", \(dqid-dsa-with-sha512", \(dq1.2.840.1.101.3.4.3.4"
.It \(dqDSA-SHA3-224", \(dqdsa_with_SHA3-224", \(dqid-dsa-with-sha3-224", \(dq2.16.840.1.101.3.4.3.5"
.It \(dqDSA-SHA3-256", \(dqdsa_with_SHA3-256", \(dqid-dsa-with-sha3-256", \(dq2.16.840.1.101.3.4.3.6"
.It \(dqDSA-SHA3-384", \(dqdsa_with_SHA3-384", \(dqid-dsa-with-sha3-384", \(dq2.16.840.1.101.3.4.3.7"
.It \(dqDSA-SHA3-512", \(dqdsa_with_SHA3-512", \(dqid-dsa-with-sha3-512", \(dq2.16.840.1.101.3.4.3.8"
DSA signature schemes with diverse message digest algorithms.
They are all supported explicitly fetched with
.Xr EVP_PKEY_sign_init_ex2 3
and
.Xr EVP_PKEY_sign_message_init 3 .
.El
.Ss Signature Parameters
The following signature parameters can be set using
.Xr EVP_PKEY_CTX_set_params 3 .
This may be called after
.Xr EVP_PKEY_sign_init 3
or
.Xr EVP_PKEY_verify_init 3 ,
and before calling
.Xr EVP_PKEY_sign 3
or
.Xr EVP_PKEY_verify 3 .
They may also be set using
.Xr EVP_PKEY_sign_init_ex 3
or
.Xr EVP_PKEY_verify_init_ex 3 .
.Bl -tag -width Ds
.It \(dqdigest" ( Ns Sy OSSL_SIGNATURE_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqproperties" ( Ns Sy OSSL_SIGNATURE_PARAM_PROPERTIES Ns ) <UTF8 string>
These two are not supported with the DSA signature schemes that already
include a message digest algorithm, See
.Sx Algorithm Names
above.
.It \(dqnonce-type" ( Ns Sy OSSL_SIGNATURE_PARAM_NONCE_TYPE Ns ) <unsigned integer>
.It \(dqkey-check" ( Ns Sy OSSL_SIGNATURE_PARAM_FIPS_KEY_CHECK Ns ) <integer>
.It \(dqdigest-check" ( Ns Sy OSSL_SIGNATURE_PARAM_FIPS_DIGEST_CHECK Ns ) <integer>
.It \(dqsign-check" ( Ns Sy OSSL_SIGNATURE_PARAM_FIPS_SIGN_CHECK Ns ) <int>
The settable parameters are described in
.Xr provider-signature 7 .
.El
.Pp
The following signature parameters can be retrieved using
.Xr EVP_PKEY_CTX_get_params 3 .
.Bl -tag -width Ds
.It \(dqalgorithm-id" ( Ns Sy OSSL_SIGNATURE_PARAM_ALGORITHM_ID Ns ) <octet string>
.It \(dqdigest" ( Ns Sy OSSL_SIGNATURE_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqnonce-type" ( Ns Sy OSSL_SIGNATURE_PARAM_NONCE_TYPE Ns ) <unsigned integer>
.It \(dqfips-indicator" ( Ns Sy OSSL_SIGNATURE_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
The gettable parameters are described in
.Xr provider-signature 7 .
.El
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_set_params 3 ,
.Xr EVP_PKEY_sign 3 ,
.Xr EVP_PKEY_verify 3 ,
.Xr provider-signature 7 ,
.Sh HISTORY
DSA Key generation and signature generation are no longer FIPS approved
in OpenSSL 3.4. See
.Xr fips_module 7
for more information.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
