.Dd 2025-09-30
.Dt EVP_KEM-RSA 7ossl
.Os
.Sh NAME
.Nm EVP_KEM-RSA
.Nd EVP_KEM RSA keytype and algorithm support
.Sh DESCRIPTION
The
.Sy RSA
keytype and its parameters are described in
.Xr EVP_PKEY-RSA 7 .
See
.Xr EVP_PKEY_encapsulate 3
and
.Xr EVP_PKEY_decapsulate 3
for more info.
.Ss RSA KEM parameters
.Bl -tag -width Ds
.It \(dqoperation" ( Ns Sy OSSL_KEM_PARAM_OPERATION Ns ) <UTF8 string>
The OpenSSL RSA Key Encapsulation Mechanism only currently supports the
following default operation (operating mode):
.Bl -tag -width Ds
.It \(dqRSASVE"
The encapsulate function simply generates a secret using random bytes
and then encrypts the secret using the RSA public key (with no padding).
The decapsulate function recovers the secret using the RSA private key.
.El
.Pp
This can be set using
.Xr EVP_PKEY_CTX_set_kem_op 3 .
.It \(dqfips-indicator" ( Ns Sy OSSL_KEM_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
.It \(dqkey-check" ( Ns Sy OSSL_KEM_PARAM_FIPS_KEY_CHECK Ns ) <integer>
These parameters are described in
.Xr provider-kem 7 .
.El
.Sh CONFORMING TO
.Bl -tag -width Ds
.It SP800-56Br2
Section 7.2.1.2 RSASVE Generate Operation (RSASVE.GENERATE). Section
7.2.1.3 RSASVE Recovery Operation (RSASVE.RECOVER).
.El
.Sh SEE ALSO
.Xr EVP_PKEY_CTX_set_kem_op 3 ,
.Xr EVP_PKEY_encapsulate 3 ,
.Xr EVP_PKEY_decapsulate 3
.Xr EVP_KEYMGMT 3 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Pp
The
.Qo Li operation Qc
(operating mode) was a required parameter prior to OpenSSL 3.5. As of
OpenSSL 3.5,
.Qo Li RSASVE Qc
is the default operating mode, and no explicit value need be specified.
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
