.Dd 2025-09-30
.Dt EVP_CIPHER-BLOWFISH 7ossl
.Os
.Sh NAME
.Nm EVP_CIPHER-BLOWFISH
.Nd The BLOBFISH EVP_CIPHER implementations
.Sh DESCRIPTION
Support for BLOWFISH symmetric encryption using the
.Sy EVP_CIPHER
API.
.Ss Algorithm Names
The following algorithms are available in the legacy provider:
.Bl -tag -width Ds
.It \(dqBF-ECB"
.It \(dqBF-CBC"
.It \(dqBF-OFB"
.It \(dqBF-CFB"
.El
.Ss Parameters
This implementation supports the parameters described in
.Xr EVP_EncryptInit 3 .
.Sh SEE ALSO
.Xr provider-cipher 7 ,
.Xr OSSL_PROVIDER-legacy 7
.Sh COPYRIGHT
Copyright 2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
