.Dd 2025-09-30
.Dt EVP_KEYEXCH-DH 7ossl
.Os
.Sh NAME
.Nm EVP_KEYEXCH-DH
.Nd DH Key Exchange algorithm support
.Sh DESCRIPTION
Key exchange support for the
.Sy DH
and
.Sy DHX
key types.
.Pp
Please note that although both key types support the same key exchange
operations, they cannot be used together in a single key exchange.
It is not possible to use a private key of the
.Sy DH
type in key exchange with the public key of
.Sy DHX
type and vice versa.
.Ss DH and DHX key exchange parameters
.Bl -tag -width Ds
.It \(dqpad" ( Ns Sy OSSL_EXCHANGE_PARAM_PAD Ns ) <unsigned integer>
Sets the padding mode for the associated key exchange ctx.
Setting a value of 1 will turn padding on.
Setting a value of 0 will turn padding off.
If padding is off then the derived shared secret may be smaller than the
largest possible secret size.
If padding is on then the derived shared secret will have its first
bytes filled with zeros where necessary to make the shared secret the
same size as the largest possible secret size.
The padding mode parameter is ignored (and padding implicitly enabled)
when the KDF type is set to "X942KDF-ASN1"
.Pf ( Sy OSSL_KDF_NAME_X942KDF_ASN1 Ns ).
.It \(dqkdf-type" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_TYPE Ns ) <UTF8 string>
.It \(dqkdf-digest" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_DIGEST Ns ) <UTF8 string>
.It \(dqkdf-digest-props" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_DIGEST_PROPS Ns ) <UTF8 string>
.It \(dqkdf-outlen" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_OUTLEN Ns ) <unsigned integer>
.It \(dqkdf-ukm" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_UKM Ns ) <octet string>
.It \(dqfips-indicator" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
.It \(dqkey-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_KEY_CHECK Ns ) <integer>
.It \(dqdigest-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_DIGEST_CHECK Ns ) <integer>
See
.Xr provider-keyexch 7 .
.It \(dqcekalg" ( Ns Sy OSSL_KDF_PARAM_CEK_ALG Ns ) <octet string ptr>
See
.Xr provider-kdf 7 .
.El
.Sh EXAMPLES
The examples assume a host and peer both generate keys using the same
named group (or domain parameters).
See
.Xr EVP_PKEY-DH 7 .
Both the host and peer transfer their public key to each other.
.Pp
To convert the peer's generated key pair to a public key in DER format
in order to transfer to the host:
.Bd -literal
    EVP_PKEY *peer_key; /* It is assumed this contains the peers generated key */
    unsigned char *peer_pub_der = NULL;
    int peer_pub_der_len;

    peer_pub_der_len = i2d_PUBKEY(peer_key, &peer_pub_der);
    ...
    OPENSSL_free(peer_pub_der);
.Ed
.Pp
To convert the received peer's public key from DER format on the host:
.Bd -literal
    const unsigned char *pd = peer_pub_der;
    EVP_PKEY *peer_pub_key = d2i_PUBKEY(NULL, &pd, peer_pub_der_len);
    ...
    EVP_PKEY_free(peer_pub_key);
.Ed
.Pp
To derive a shared secret on the host using the host's key and the
peer's public key:
.Bd -literal
    /* It is assumed that the host_key and peer_pub_key are set up */
    void derive_secret(EVP_KEY *host_key, EVP_PKEY *peer_pub_key)
    {
        unsigned int pad = 1;
        OSSL_PARAM params[2];
        unsigned char *secret = NULL;
        size_t secret_len = 0;
        EVP_PKEY_CTX *dctx = EVP_PKEY_CTX_new_from_pkey(NULL, host_key, NULL);

        EVP_PKEY_derive_init(dctx);

        /* Optionally set the padding */
        params[0] = OSSL_PARAM_construct_uint(OSSL_EXCHANGE_PARAM_PAD, &pad);
        params[1] = OSSL_PARAM_construct_end();
        EVP_PKEY_CTX_set_params(dctx, params);

        EVP_PKEY_derive_set_peer(dctx, peer_pub_key);

        /* Get the size by passing NULL as the buffer */
        EVP_PKEY_derive(dctx, NULL, &secret_len);
        secret = OPENSSL_zalloc(secret_len);

        EVP_PKEY_derive(dctx, secret, &secret_len);
        ...
        OPENSSL_clear_free(secret, secret_len);
        EVP_PKEY_CTX_free(dctx);
    }
.Ed
.Pp
Very similar code can be used by the peer to derive the same shared
secret using the host's public key and the peer's generated key pair.
.Sh SEE ALSO
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-FFC 7 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keyexch 7 ,
.Xr provider-keymgmt 7 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
