.Dd 2025-09-30
.Dt EVP_RAND-SEED-SRC 7ossl
.Os
.Sh NAME
.Nm EVP_RAND-SEED-SRC
.Nd The randomness seed source EVP_RAND implementation
.Sh DESCRIPTION
Support for deterministic random number generator seeding through the
.Sy EVP_RAND
API.
.Pp
The seed sources used are specified at the time OpenSSL is configured
for building using the
.Sy --with-rand-seed=
option.
By default, operating system randomness sources are used.
.Ss Identity
"SEED-SRC" is the name for this implementation; it can be used with the
.Xr EVP_RAND_fetch 3
function.
.Ss Supported parameters
The supported parameters are:
.Bl -tag -width Ds
.It \(dqstate" ( Ns Sy OSSL_RAND_PARAM_STATE Ns ) <integer>
.It \(dqstrength" ( Ns Sy OSSL_RAND_PARAM_STRENGTH Ns ) <unsigned integer>
.It \(dqmax_request" ( Ns Sy OSSL_RAND_PARAM_MAX_REQUEST Ns ) <unsigned integer>
These parameters work as described in
.Xr EVP_RAND 3 .
.El
.Sh NOTES
A context for the seed source can be obtained by calling:
.Bd -literal
 EVP_RAND *rand = EVP_RAND_fetch(NULL, "SEED-SRC", NULL);
 EVP_RAND_CTX *rctx = EVP_RAND_CTX_new(rand, NULL);
.Ed
.Sh EXAMPLES
.Bd -literal
 EVP_RAND *rand;
 EVP_RAND_CTX *seed, *rctx;
 unsigned char bytes[100];
 OSSL_PARAM params[2], *p = params;
 unsigned int strength = 128;

 /* Create and instantiate a seed source */
 rand = EVP_RAND_fetch(NULL, "SEED-SRC", NULL);
 seed = EVP_RAND_CTX_new(rand, NULL);
 EVP_RAND_instantiate(seed, strength, 0, NULL, 0, NULL);
 EVP_RAND_free(rand);

 /* Feed this into a DRBG */
 rand = EVP_RAND_fetch(NULL, "CTR-DRBG", NULL);
 rctx = EVP_RAND_CTX_new(rand, seed);
 EVP_RAND_free(rand);

 /* Configure the DRBG */
 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_DRBG_PARAM_CIPHER,
                                         SN_aes_256_ctr, 0);
 *p = OSSL_PARAM_construct_end();
 EVP_RAND_instantiate(rctx, strength, 0, NULL, 0, params);

 EVP_RAND_generate(rctx, bytes, sizeof(bytes), strength, 0, NULL, 0);

 EVP_RAND_CTX_free(rctx);
 EVP_RAND_CTX_free(seed);
.Ed
.Sh SEE ALSO
.Xr EVP_RAND 3 ,
.Xr EVP_RAND 3
.Sh COPYRIGHT
Copyright 2020-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
