.Dd 2025-09-30
.Dt EVP_MD-COMMON 7ossl
.Os
.Sh NAME
.Nm EVP_MD-common
.Nd The OpenSSL EVP_MD implementations, common things
.Sh DESCRIPTION
All the OpenSSL EVP_MD implementations understand the following
.Xr OSSL_PARAM 3
entries that are gettable with
.Xr EVP_MD_get_params 3 ,
as well as these:
.Bl -tag -width Ds
.It \(dqblocksize" ( Ns Sy OSSL_DIGEST_PARAM_BLOCK_SIZE Ns ) <unsigned integer>
The digest block size.
The length of the "blocksize" parameter should not exceed that of a
.Sy size_t .
.Pp
This value can also be retrieved with
.Xr EVP_MD_get_block_size 3 .
.It \(dqsize" ( Ns Sy OSSL_DIGEST_PARAM_SIZE Ns ) <unsigned integer>
The digest output size.
The length of the "size" parameter should not exceed that of a
.Sy size_t .
.Pp
This value can also be retrieved with
.Xr EVP_MD_get_size 3 .
.It \(dqflags" ( Ns Sy OSSL_DIGEST_PARAM_FLAGS Ns ) <unsigned integer>
Diverse flags that describe exceptional behaviour for the digest.
These flags are described in
.Xr EVP_MD_meth_set_flags 3 .
.Pp
The length of the "flags" parameter should equal that of an
.Sy unsigned long int .
.Pp
This value can also be retrieved with
.Xr EVP_MD_get_flags 3 .
.El
.Sh SEE ALSO
.Xr EVP_DigestInit 3 ,
.Xr EVP_MD_get_params 3 ,
.Xr provider-digest 7
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
