.Dd 2025-09-30
.Dt EVP_KDF-HMAC-DRBG 7ossl
.Os
.Sh NAME
.Nm EVP_KDF-HMAC-DRBG
.Nd The HMAC DRBG DETERMINISTIC EVP_KDF implementation
.Sh DESCRIPTION
Support for a deterministic HMAC DRBG using the
.Sy EVP_KDF
API. This is similar to
.Xr EVP_RAND-HMAC-DRBG 7 ,
but uses fixed values for its entropy and nonce values.
This is used to generate deterministic nonce value required by ECDSA and
DSA (as defined in RFC 6979).
.Ss Identity
"HMAC-DRBG-KDF" is the name for this implementation; it can be used with
the
.Xr EVP_KDF_fetch 3
function.
.Ss Supported parameters
The supported parameters are:
.Bl -tag -width Ds
.It \(dqdigest" ( Ns Sy OSSL_DRBG_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqproperties" ( Ns Sy OSSL_DRBG_PARAM_PROPERTIES Ns ) <UTF8 string>
These parameters work as described in
.Xr EVP_KDF 3 .
.It \(dqentropy" ( Ns Sy OSSL_KDF_PARAM_HMACDRBG_ENTROPY Ns ) <octet string>
Sets the entropy bytes supplied to the HMAC-DRBG.
.It \(dqnonce" ( Ns Sy OSSL_KDF_PARAM_HMACDRBG_NONCE Ns ) <octet string>
Sets the nonce bytes supplied to the HMAC-DRBG.
.El
.Sh NOTES
A context for KDF HMAC DRBG can be obtained by calling:
.Bd -literal
 EVP_KDF *kdf = EVP_KDF_fetch(NULL, "HMAC-DRBG-KDF", NULL);
 EVP_KDF_CTX *kdf_ctx = EVP_KDF_CTX_new(kdf, NULL);
.Ed
.Sh CONFORMING TO
RFC 6979
.Sh SEE ALSO
.Xr EVP_KDF 3 ,
.Xr EVP_KDF 3
.Sh HISTORY
The EVP_KDF-HMAC-DRBG functionality was added in OpenSSL 3.2.
.Sh COPYRIGHT
Copyright 2022-2023 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
