.Dd 2025-09-30
.Dt EVP_MAC-KMAC 7ossl
.Os
.Sh NAME
.Nm EVP_MAC-KMAC ,
.Nm EVP_MAC-KMAC128 ,
.Nm EVP_MAC-KMAC256
.Nd The KMAC EVP_MAC implementations
.Sh DESCRIPTION
Support for computing KMAC MACs through the
.Sy EVP_MAC
API.
.Ss Identity
These implementations are identified with one of these names and
properties, to be used with
.Xr EVP_MAC_fetch 3 :
.Bl -tag -width Ds
.It \(dqKMAC-128", \(dqprovider=default" or \(dqprovider=fips"
.It \(dqKMAC-256", \(dqprovider=default" or \(dqprovider=fips"
.El
.Ss Supported parameters
The general description of these parameters can be found in
.Xr EVP_MAC 3 .
.Pp
All these parameters (except for "block-size") can be set with
.Xr EVP_MAC_CTX_set_params 3 .
Furthermore, the "size" parameter can be retrieved with
.Xr EVP_MAC_CTX_get_params 3 ,
or with
.Xr EVP_MAC_CTX_get_mac_size 3 .
The length of the "size" parameter should not exceed that of a
.Sy size_t .
Likewise, the "block-size" parameter can be retrieved with
.Xr EVP_MAC_CTX_get_params 3 ,
or with
.Xr EVP_MAC_CTX_get_block_size 3 .
.Bl -tag -width Ds
.It \(dqkey" ( Ns Sy OSSL_MAC_PARAM_KEY Ns ) <octet string>
Sets the MAC key.
Setting this parameter is identical to passing a
.Em key
to
.Xr EVP_MAC_init 3 .
The length of the key (in bytes) must be in the range 4...512.
.It \(dqcustom" ( Ns Sy OSSL_MAC_PARAM_CUSTOM Ns ) <octet string>
Sets the customization string.
It is an optional value with a length of at most 512 bytes, and is empty
by default.
.It \(dqsize" ( Ns Sy OSSL_MAC_PARAM_SIZE Ns ) <unsigned integer>
Sets the MAC size.
By default, it is 32 for
.Qo Li KMAC-128 Qc
and 64 for
.Qo Li KMAC-256 Qc .
.It \(dqblock-size" ( Ns Sy OSSL_MAC_PARAM_BLOCK_SIZE Ns ) <unsigned integer>
Gets the MAC block size.
It is 168 for
.Qo Li KMAC-128 Qc
and 136 for
.Qo Li KMAC-256 Qc .
.It \(dqxof" ( Ns Sy OSSL_MAC_PARAM_XOF Ns ) <integer>
The "xof" parameter value is expected to be 1 or 0. Use 1 to enable XOF
mode.
The default value is 0.
.It \(dqfips-indicator" ( Ns Sy OSSL_MAC_PARAM_FIPS_APPROVED_INDICATOR Ns ) <int>
This settable parameter is described in
.Xr provider-mac 7 .
.It \(dqno-short-mac" ( Ns Sy OSSL_MAC_PARAM_FIPS_NO_SHORT_MAC Ns ) <integer>
This settable parameter is described in
.Xr provider-mac 7 .
It is used by the OpenSSL FIPS provider and the minimum length output
for KMAC is defined by NIST's SP 800-185 8.4.2.
.It \(dqkey-check" ( Ns Sy OSSL_MAC_PARAM_FIPS_KEY_CHECK Ns ) <integer>
This settable parameter is described in
.Xr provider-mac 7 .
.El
.Pp
The "custom" and "no-short-mac" parameters must be set as part of or
before the
.Xr EVP_MAC_init 3
call.
The "xof" and "size" parameters can be set at any time before
.Xr EVP_MAC_final 3 .
The "key" parameter is set as part of the
.Xr EVP_MAC_init 3
call, but can be set before it instead.
.Sh EXAMPLES
.Bd -literal
  #include <openssl/evp.h>
  #include <openssl/params.h>

  static int do_kmac(const unsigned char *in, size_t in_len,
                     const unsigned char *key, size_t key_len,
                     const unsigned char *custom, size_t custom_len,
                     int xof_enabled, unsigned char *out, int out_len)
  {
      EVP_MAC_CTX *ctx = NULL;
      EVP_MAC *mac = NULL;
      OSSL_PARAM params[4], *p;
      int ret = 0;
      size_t l = 0;

      mac = EVP_MAC_fetch(NULL, "KMAC-128", NULL);
      if (mac == NULL)
          goto err;
      ctx = EVP_MAC_CTX_new(mac);
      /* The mac can be freed after it is used by EVP_MAC_CTX_new */
      EVP_MAC_free(mac);
      if (ctx == NULL)
          goto err;

      /*
       * Setup parameters required before calling EVP_MAC_init()
       * The parameters OSSL_MAC_PARAM_XOF and OSSL_MAC_PARAM_SIZE may also be
       * used at this point.
       */
      p = params;
      *p++ = OSSL_PARAM_construct_octet_string(OSSL_MAC_PARAM_KEY,
                                               (void *)key, key_len);
      if (custom != NULL && custom_len != 0)
        *p++ = OSSL_PARAM_construct_octet_string(OSSL_MAC_PARAM_CUSTOM,
                                                 (void *)custom, custom_len);
      *p = OSSL_PARAM_construct_end();
      if (!EVP_MAC_CTX_set_params(ctx, params))
          goto err;

      if (!EVP_MAC_init(ctx))
          goto err;

      /*
       * Note: the following optional parameters can be set any time
       * before EVP_MAC_final().
       */
      p = params;
      *p++ = OSSL_PARAM_construct_int(OSSL_MAC_PARAM_XOF, &xof_enabled);
      *p++ = OSSL_PARAM_construct_int(OSSL_MAC_PARAM_SIZE, &out_len);
      *p = OSSL_PARAM_construct_end();
      if (!EVP_MAC_CTX_set_params(ctx, params))
          goto err;

      /* The update may be called multiple times here for streamed input */
      if (!EVP_MAC_update(ctx, in, in_len))
          goto err;
      if (!EVP_MAC_final(ctx, out, &l, out_len))
          goto err;
      ret = 1;
  err:
      EVP_MAC_CTX_free(ctx);
      return ret;
  }
.Ed
.Sh SEE ALSO
.Xr EVP_MAC_CTX_get_params 3 ,
.Xr EVP_MAC_CTX_set_params 3 ,
.Xr EVP_MAC 3 ,
.Xr OSSL_PARAM 3 ,
.Lk https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf
.Sh COPYRIGHT
Copyright 2018-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
