.Dd 2025-09-30
.Dt EVP_CIPHER-DES 7ossl
.Os
.Sh NAME
.Nm EVP_CIPHER-DES
.Nd The DES EVP_CIPHER implementations
.Sh DESCRIPTION
Support for DES symmetric encryption using the
.Sy EVP_CIPHER
API.
.Ss Algorithm Names
The following algorithms are available in the FIPS provider as well as
the default provider:
.Bl -tag -width Ds
.It \(dqDES-EDE3-ECB" or \(dqDES-EDE3"
.It \(dqDES-EDE3-CBC" or \(dqDES3"
.El
The following algorithms are available in the default provider, but not
the FIPS provider:
.Bl -tag -width Ds
.It \(dqDES-EDE3-CFB8" and \(dqDES-EDE3-CFB1"
.It \(dqDES-EDE-ECB" or \(dqDES-EDE"
.It \(dqDES-EDE-CBC"
.It \(dqDES-EDE-OFB"
.It \(dqDES-EDE-CFB"
.It \(dqDES3-WRAP"
.El
The following algorithms are available in the legacy provider:
.Bl -tag -width Ds
.It \(dqDES-ECB"
.It \(dqDES-CBC"
.It \(dqDES-OFB"
.It \(dqDES-CFB", \(dqDES-CFB1" and \(dqDES-CFB8"
.It \(dqDESX-CBC"
.El
.Ss Parameters
This implementation supports the parameters described in
.Xr EVP_EncryptInit 3
including "encrypt-check" and "fips-indicator".
.Sh SEE ALSO
.Xr provider-cipher 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-legacy 7 ,
.Sh COPYRIGHT
Copyright 2021-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
