.Dd 2025-09-30
.Dt EVP_KDF-KB 7ossl
.Os
.Sh NAME
.Nm EVP_KDF-KB
.Nd The Key-Based EVP_KDF implementation
.Sh DESCRIPTION
The EVP_KDF-KB algorithm implements the Key-Based key derivation
function (KBKDF). KBKDF derives a key from repeated application of a
keyed MAC to an input secret (and other optional values).
.Pp
The output is considered to be keying material.
.Ss Identity
"KBKDF" is the name for this implementation; it can be used with the
.Xr EVP_KDF_fetch 3
function.
.Ss Supported parameters
The supported parameters are:
.Bl -tag -width Ds
.It \(dqmode" ( Ns Sy OSSL_KDF_PARAM_MODE Ns ) <UTF8 string>
The mode parameter determines which flavor of KBKDF to use - currently
the choices are "counter" and "feedback".
"counter" is the default, and will be used if unspecified.
.It \(dqmac" ( Ns Sy OSSL_KDF_PARAM_MAC Ns ) <UTF8 string>
The value is either CMAC, HMAC, KMAC128 or KMAC256.
.It \(dqdigest" ( Ns Sy OSSL_KDF_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqcipher" ( Ns Sy OSSL_KDF_PARAM_CIPHER Ns ) <UTF8 string>
.It \(dqproperties" ( Ns Sy OSSL_KDF_PARAM_PROPERTIES Ns ) <UTF8 string>
.It \(dqkey" ( Ns Sy OSSL_KDF_PARAM_KEY Ns ) <octet string>
.It \(dqsalt" ( Ns Sy OSSL_KDF_PARAM_SALT Ns ) <octet string>
.It \(dqinfo ( Ns Sy OSSL_KDF_PARAM_INFO Ns ) <octet string>
.It \(dqseed" ( Ns Sy OSSL_KDF_PARAM_SEED Ns ) <octet string>
The seed parameter is unused in counter mode.
.It \(dquse-l" ( Ns Sy OSSL_KDF_PARAM_KBKDF_USE_L Ns ) <integer>
Set to
.Sy 0
to disable use of the optional Fixed Input data 'L' (see SP800-108). The
default value of
.Sy 1
will be used if unspecified.
.It \(dquse-separator" ( Ns Sy OSSL_KDF_PARAM_KBKDF_USE_SEPARATOR Ns ) <integer>
Set to
.Sy 0
to disable use of the optional Fixed Input data 'zero separator' (see
SP800-108) that is placed between the Label and Context.
The default value of
.Sy 1
will be used if unspecified.
.It \(dqr" ( Ns Sy OSSL_KDF_PARAM_KBKDF_R Ns ) <integer>
Set the fixed value 'r', indicating the length of the counter in bits.
.Pp
Supported values are
.Sy 8 ,
.Sy 16 ,
.Sy 24 ,
and
.Sy 32 .
The default value of
.Sy 32
will be used if unspecified.
.El
.Pp
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_KDF_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling EVP_KDF_derive.
It returns 0 if "key-check" is set to 0 and the check fails.
.It \(dqkey-check" ( Ns Sy OSSL_KDF_PARAM_FIPS_KEY_CHECK Ns ) <integer>
The default value of 1 causes an error during
.Xr EVP_KDF_CTX_set_params 3
if the length of used key-derivation key
.Pf ( Sy OSSL_KDF_PARAM_KEY )
is shorter than 112 bits.
Setting this to zero will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Pp
Depending on whether mac is CMAC or HMAC, either digest or cipher is
required (respectively) and the other is unused.
They are unused for KMAC128 and KMAC256.
.Pp
The parameters key, salt, info, and seed correspond to KI, Label,
Context, and IV (respectively) in SP800-108. As in that document, salt,
info, and seed are optional and may be omitted.
.Pp
"mac", "digest", cipher" and "properties" are described in
.Xr EVP_KDF 3 .
.Sh NOTES
A context for KBKDF can be obtained by calling:
.Bd -literal
 EVP_KDF *kdf = EVP_KDF_fetch(NULL, "KBKDF", NULL);
 EVP_KDF_CTX *kctx = EVP_KDF_CTX_new(kdf);
.Ed
.Pp
The output length of an KBKDF is specified via the
.Qo Li keylen Qc
parameter to the
.Xr EVP_KDF_derive 3
function.
.Pp
Note that currently OpenSSL only implements counter and feedback modes.
Other variants may be supported in the future.
.Sh EXAMPLES
This example derives 10 bytes using COUNTER-HMAC-SHA256, with KI
"secret", Label "label", and Context "context".
.Bd -literal
 EVP_KDF *kdf;
 EVP_KDF_CTX *kctx;
 unsigned char out[10];
 OSSL_PARAM params[6], *p = params;

 kdf = EVP_KDF_fetch(NULL, "KBKDF", NULL);
 kctx = EVP_KDF_CTX_new(kdf);
 EVP_KDF_free(kdf);

 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_DIGEST,
                                         "SHA2-256", 0);
 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_MAC,
                                         "HMAC", 0);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_KEY,
                                          "secret", strlen("secret"));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SALT,
                                          "label", strlen("label"));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_INFO,
                                          "context", strlen("context"));
 *p = OSSL_PARAM_construct_end();
 if (EVP_KDF_derive(kctx, out, sizeof(out), params) <= 0)
     error("EVP_KDF_derive");

 EVP_KDF_CTX_free(kctx);
.Ed
.Pp
This example derives 10 bytes using FEEDBACK-CMAC-AES256, with KI
"secret", Label "label", and IV "sixteen bytes iv".
.Bd -literal
 EVP_KDF *kdf;
 EVP_KDF_CTX *kctx;
 unsigned char out[10];
 OSSL_PARAM params[8], *p = params;
 unsigned char *iv = "sixteen bytes iv";

 kdf = EVP_KDF_fetch(NULL, "KBKDF", NULL);
 kctx = EVP_KDF_CTX_new(kdf);
 EVP_KDF_free(kdf);

 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_CIPHER, "AES256", 0);
 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_MAC, "CMAC", 0);
 *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_MODE, "FEEDBACK", 0);
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_KEY,
                                          "secret", strlen("secret"));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SALT,
                                          "label", strlen("label"));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_INFO,
                                          "context", strlen("context"));
 *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SEED,
                                          iv, strlen(iv));
 *p = OSSL_PARAM_construct_end();
 if (EVP_KDF_derive(kctx, out, sizeof(out), params) <= 0)
     error("EVP_KDF_derive");

 EVP_KDF_CTX_free(kctx);
.Ed
.Sh CONFORMING TO
NIST SP800-108, IETF RFC 6803, IETF RFC 8009.
.Sh SEE ALSO
.Xr EVP_KDF 3 ,
.Xr EVP_KDF_CTX_free 3 ,
.Xr EVP_KDF_CTX_get_kdf_size 3 ,
.Xr EVP_KDF_derive 3 ,
.Xr EVP_KDF 3
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Pp
Support for KMAC was added in OpenSSL 3.1.
.Sh COPYRIGHT
Copyright 2019-2024 The OpenSSL Project Authors.
All Rights Reserved.
Copyright 2019 Red Hat, Inc.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
