.Dd 2025-09-30
.Dt EVP_PKEY-FFC 7ossl
.Os
.Sh NAME
.Nm EVP_PKEY-FFC
.Nd EVP_PKEY DSA and DH/DHX shared FFC parameters
.Sh DESCRIPTION
Finite field cryptography (FFC) is a method of implementing discrete
logarithm cryptography using finite field mathematics.
DSA is an example of FFC and Diffie-Hellman key establishment algorithms
specified in SP800-56A can also be implemented as FFC.
.Pp
The
.Sy DSA ,
.Sy DH
and
.Sy DHX
keytypes are implemented in OpenSSL's default and FIPS providers.
The implementations support the basic DSA, DH and DHX keys, containing
the public and private keys
.Em pub
and
.Em priv
as well as the three main domain parameters
.Em p ,
.Em q
and
.Em g .
.Pp
For
.Sy DSA
(and
.Sy DH
that is not a named group) the FIPS186-4 standard specifies that the
values used for FFC parameter generation are also required for parameter
validation.
This means that optional FFC domain parameter values for
.Em seed ,
.Em pcounter
and
.Em gindex
may need to be stored for validation purposes.
For
.Sy DH
the
.Em seed
and
.Em pcounter
can be stored in ASN1 data (but the
.Em gindex
is not).
For
.Sy DSA
however, these fields are not stored in the ASN1 data so they need to be
stored externally if validation is required.
.Pp
The
.Sy DH
key type uses PKCS#3 format which saves p and g, but not the 'q' value.
The
.Sy DHX
key type uses X9.42 format which saves the value of 'q' and this must be
used for FIPS186-4.
.Ss FFC parameters
In addition to the common parameters that all keytypes should support
(see
.Xr provider-keymgmt 7 Ns ),
the
.Sy DSA ,
.Sy DH
and
.Sy DHX
keytype implementations support the following.
.Bl -tag -width Ds
.It \(dqpub" ( Ns Sy OSSL_PKEY_PARAM_PUB_KEY Ns ) <unsigned integer>
The public key value.
.It \(dqpriv" ( Ns Sy OSSL_PKEY_PARAM_PRIV_KEY Ns ) <unsigned integer>
The private key value.
.El
.Ss FFC DSA, DH and DHX domain parameters
.Bl -tag -width Ds
.It \(dqp" ( Ns Sy OSSL_PKEY_PARAM_FFC_P Ns ) <unsigned integer>
A DSA or Diffie-Hellman prime "p" value.
.It \(dqg" ( Ns Sy OSSL_PKEY_PARAM_FFC_G Ns ) <unsigned integer>
A DSA or Diffie-Hellman generator "g" value.
.El
.Ss FFC DSA and DHX domain parameters
.Bl -tag -width Ds
.It \(dqq" ( Ns Sy OSSL_PKEY_PARAM_FFC_Q Ns ) <unsigned integer>
A DSA or Diffie-Hellman prime "q" value.
.It \(dqseed" ( Ns Sy OSSL_PKEY_PARAM_FFC_SEED Ns ) <octet string>
An optional domain parameter
.Em seed
value used during generation and validation of
.Em p ,
.Em q
and canonical
.Em g .
For validation this needs to set the
.Em seed
that was produced during generation.
.It \(dqgindex" ( Ns Sy OSSL_PKEY_PARAM_FFC_GINDEX Ns ) <integer>
Sets the index to use for canonical generation and verification of the
generator
.Em g .
Set this to a positive value from 0..FF to use this mode.
This
.Em gindex
can then be reused during key validation to verify the value of
.Em g .
If this value is not set or is -1 then unverifiable generation of the
generator
.Em g
will be used.
.It \(dqpcounter" ( Ns Sy OSSL_PKEY_PARAM_FFC_PCOUNTER Ns ) <integer>
An optional domain parameter
.Em counter
value that is output during generation of
.Em p .
This value must be saved if domain parameter validation is required.
.It \(dqhindex" ( Ns Sy OSSL_PKEY_PARAM_FFC_H Ns ) <integer>
For unverifiable generation of the generator
.Em g
this value is output during generation of
.Em g .
Its value is the first integer larger than one that satisfies g = h^j
mod p (where g != 1 and "j" is the cofactor).
.It \(dqj" ( Ns Sy OSSL_PKEY_PARAM_FFC_COFACTOR Ns ) <unsigned integer>
An optional informational cofactor parameter that should equal to (p -
1) / q.
.It \(dqvalidate-pq" ( Ns Sy OSSL_PKEY_PARAM_FFC_VALIDATE_PQ Ns ) <unsigned integer>
.It \(dqvalidate-g" ( Ns Sy OSSL_PKEY_PARAM_FFC_VALIDATE_G Ns ) <unsigned integer>
These boolean values are used during FIPS186-4 or FIPS186-2 key
validation checks (See
.Xr EVP_PKEY_param_check 3 )
to select validation options.
By default
.Em validate-pq
and
.Em validate-g
are both set to 1 to check that p,q and g are valid.
Either of these may be set to 0 to skip a test, which is mainly useful
for testing purposes.
.It \(dqvalidate-legacy" ( Ns Sy OSSL_PKEY_PARAM_FFC_VALIDATE_LEGACY Ns ) <unsigned integer>
This boolean value is used during key validation checks (See
.Xr EVP_PKEY_param_check 3 )
to select the validation type.
The default value of 0 selects FIPS186-4 validation.
Setting this value to 1 selects FIPS186-2 validation.
.El
.Ss FFC key generation parameters
The following key generation types are available for DSA and DHX
algorithms:
.Bl -tag -width Ds
.It \(dqtype" ( Ns Sy OSSL_PKEY_PARAM_FFC_TYPE Ns ) <UTF8 string>
Sets the type of parameter generation.
The shared valid values are:
.Bl -tag -width Ds
.It \(dqfips186_4"
The current standard.
.It \(dqfips186_2"
The old standard that should only be used for legacy purposes.
.It \(dqdefault"
This can choose one of "fips186_4" or "fips186_2" depending on other
parameters set for parameter generation.
.El
.It \(dqpbits" ( Ns Sy OSSL_PKEY_PARAM_FFC_PBITS Ns ) <unsigned integer>
Sets the size (in bits) of the prime 'p'.
.It \(dqqbits" ( Ns Sy OSSL_PKEY_PARAM_FFC_QBITS Ns ) <unsigned integer>
Sets the size (in bits) of the prime 'q'.
.Pp
For "fips186_4" this can be either 224 or 256. For "fips186_2" this has
a size of 160.
.It \(dqdigest" ( Ns Sy OSSL_PKEY_PARAM_FFC_DIGEST Ns ) <UTF8 string>
Sets the Digest algorithm to be used as part of the Key Generation
Function associated with the given Key Generation
.Em ctx .
This must also be set for key validation.
.It \(dqproperties" ( Ns Sy OSSL_PKEY_PARAM_FFC_DIGEST_PROPS Ns ) <UTF8 string>
Sets properties to be used upon look up of the implementation for the
selected Digest algorithm for the Key Generation Function associated
with the given key generation
.Em ctx .
This may also be set for key validation.
.It \(dqseed" ( Ns Sy OSSL_PKEY_PARAM_FFC_SEED Ns ) <octet string>
For "fips186_4" or "fips186_2" generation this sets the
.Em seed
data to use instead of generating a random seed internally.
This should be used for testing purposes only.
This will either produce fixed values for the generated parameters OR it
will fail if the seed did not generate valid primes.
.It \(dqgindex" ( Ns Sy OSSL_PKEY_PARAM_FFC_GINDEX Ns ) <integer>
.It \(dqpcounter" ( Ns Sy OSSL_PKEY_PARAM_FFC_PCOUNTER Ns ) <integer>
.It \(dqhindex" ( Ns Sy OSSL_PKEY_PARAM_FFC_H Ns ) <integer>
These types are described above.
.El
.Sh CONFORMING TO
The following sections of SP800-56Ar3:
.Bl -tag -width Ds
.It 5.5.1.1 FFC Domain Parameter Selection/Generation
.El
The following sections of FIPS186-4:
.Bl -tag -width Ds
.It A.1.1.2 Generation of Probable Primes p and q Using an Approved Hash Function.
.It A.2.3 Generation of canonical generator g.
.It A.2.1 Unverifiable Generation of the Generator g.
.El
.Sh SEE ALSO
.Xr EVP_PKEY-DSA 7 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_SIGNATURE-DSA 7 ,
.Xr EVP_KEYEXCH-DH 7 ,
.Xr EVP_KEYMGMT 3 ,
.Xr EVP_PKEY 3 ,
.Xr provider-keymgmt 7 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
