.Dd 2025-09-30
.Dt OPENSSL-CORE_NAMES.H 7ossl
.Os
.Sh NAME
.Nm openssl/core_names.h
.Nd OpenSSL provider parameter names
.Sh SYNOPSIS
.In openssl/core_names.h
.Sh DESCRIPTION
The
.Pa <openssl/core_names.h>
header defines a multitude of macros for
.Xr OSSL_PARAM 3
names, algorithm names and other known names used with OpenSSL's
providers, made available for practical purposes only.
.Pp
Existing names are further described in the manuals for OpenSSL's
providers (see
.Sx SEE ALSO )
and the manuals for each algorithm they provide (listed in those
provider manuals).
.Sh SEE ALSO
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr OSSL_PROVIDER-legacy 7
.Sh HISTORY
The macros described here were added in OpenSSL 3.0.
.Sh CAVEATS
.Em This header file does not constitute a general registry of names .
Providers that implement new algorithms are to be responsible for their
own parameter names.
.Pp
However, authors of provider that implement their own variants of
algorithms that OpenSSL providers support will want to pay attention to
the names provided in this header to work in a compatible manner.
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
