.Dd 2025-09-30
.Dt OSSL_PROVIDER-FIPS 7ossl
.Os
.Sh NAME
.Nm OSSL_PROVIDER-FIPS
.Nd OpenSSL FIPS provider
.Sh DESCRIPTION
The OpenSSL FIPS provider is a special provider that conforms to the
Federal Information Processing Standards (FIPS) specified in FIPS 140-3.
This 'module' contains an approved set of cryptographic algorithms that
is validated by an accredited testing laboratory.
.Ss Properties
The implementations in this provider specifically have these properties
defined for approved algorithms:
.Bl -tag -width Ds
.It \(dqprovider=fips"
.It \(dqfips=yes"
.El
It may be used in a property query string with fetching functions such
as
.Xr EVP_MD_fetch 3
or
.Xr EVP_CIPHER_fetch 3 ,
as well as with other functions that take a property query string, such
as
.Xr EVP_PKEY_CTX_new_from_name 3 .
.Pp
To be FIPS compliant, it is mandatory to include
.Qo Li fips=yes Qc
as part of all property queries.
This ensures that only FIPS approved implementations are used for
cryptographic operations.
The
.Qo Li fips=yes Qc
query may also include other non-crypto support operations that are not
in the FIPS provider, such as asymmetric key encoders, see
.Xr OSSL_PROVIDER-default 7 .
.Pp
It is not mandatory to include
.Qo Li provider=fips Qc
as part of your property query.
Including
.Qo Li provider=fips Qc
in your property query guarantees that the OpenSSL FIPS provider is used
for cryptographic operations rather than other FIPS capable providers.
.Ss Approved algorithms
Algorithms that are fetched using "fips=yes" may still be unapproved if
certain conditions are not met.
See
.Xr fips_module 7
for additional information.
.Ss Provider parameters
See
.Xr provider-base 7
for a list of base parameters.
The OpenSSL FIPS provider also handles FIPS indicator related parameters
as specified by
.Xr fips_config 5 .
.Sh OPERATIONS AND ALGORITHMS
The OpenSSL FIPS provider supports these operations and algorithms:
.Ss Hashing Algorithms / Message Digests
.Bl -tag -width Ds
.It SHA1, see Xr EVP_MD-SHA1 7
.It SHA2, see Xr EVP_MD-SHA2 7
.It SHA3, see Xr EVP_MD-SHA3 7
.It KECCAK-KMAC, see Xr EVP_MD-KECCAK-KMAC 7
.It SHAKE, see Xr EVP_MD-SHAKE 7
.El
.Ss Symmetric Ciphers
.Bl -tag -width Ds
.It AES, see Xr EVP_CIPHER-AES 7
.It 3DES, see Xr EVP_CIPHER-DES 7
.El
.Ss Message Authentication Code (MAC)
.Bl -tag -width Ds
.It CMAC, see Xr EVP_MAC-CMAC 7
.It GMAC, see Xr EVP_MAC-GMAC 7
.It HMAC, see Xr EVP_MAC-HMAC 7
.It KMAC, see Xr EVP_MAC-KMAC 7
.El
.Ss Key Derivation Function (KDF)
.Bl -tag -width Ds
.It HKDF, see Xr EVP_KDF-HKDF 7
.It TLS13-KDF, see Xr EVP_KDF-TLS13_KDF 7
.It SSKDF, see Xr EVP_KDF-SS 7
.It PBKDF2, see Xr EVP_KDF-PBKDF2 7
.It SSHKDF, see Xr EVP_KDF-SSHKDF 7
.It TLS1-PRF, see Xr EVP_KDF-TLS1_PRF 7
.It KBKDF, see Xr EVP_KDF-KB 7
.It X942KDF-ASN1, see Xr EVP_KDF-X942-ASN1 7
.It X942KDF-CONCAT, see Xr EVP_KDF-X942-CONCAT 7
.It X963KDF, see Xr EVP_KDF-X963 7
.El
.Ss Key Exchange
.Bl -tag -width Ds
.It DH, see Xr EVP_KEYEXCH-DH 7
.It ECDH, see Xr EVP_KEYEXCH-ECDH 7
.It X25519, see Xr EVP_KEYEXCH-X25519 7
.It X448, see Xr EVP_KEYEXCH-X448 7
.It ML-KEM, see Xr EVP_KEM-ML-KEM 7
.It TLS1-PRF
.It HKDF
.El
.Ss Asymmetric Signature
.Bl -tag -width Ds
.It RSA, see Xr EVP_SIGNATURE-RSA 7
The
.Sy X931
padding mode "OSSL_PKEY_RSA_PAD_MODE_X931" is no longer supported for
signature generation, but may be used for verification for legacy use
cases.
(This is a FIPS 140-3 requirement)
.It DSA, see Xr EVP_SIGNATURE-DSA 7
.It ED25519, see Xr EVP_SIGNATURE-ED25519 7
.It ED448, see Xr EVP_SIGNATURE-ED448 7
.It ECDSA, see Xr EVP_SIGNATURE-ECDSA 7
.It ML-DSA-44, see Xr EVP_SIGNATURE-ML-DSA 7
.It ML-DSA-65, see Xr EVP_SIGNATURE-ML-DSA 7
.It ML-DSA-87, see Xr EVP_SIGNATURE-ML-DSA 7
.It SLH-DSA, see Xr EVP_SIGNATURE-SLH-DSA 7
.It HMAC, see Xr EVP_SIGNATURE-HMAC 7
.It CMAC, see Xr EVP_SIGNATURE-CMAC 7
.El
.Ss Asymmetric Cipher
.Bl -tag -width Ds
.It RSA, see Xr EVP_ASYM_CIPHER-RSA 7
.El
.Ss Asymmetric Key Encapsulation
.Bl -tag -width Ds
.It RSA, see Xr EVP_KEM-RSA 7
.El
.Ss Asymmetric Key Management
.Bl -tag -width Ds
.It DH, see Xr EVP_KEYMGMT-DH 7
.It DHX, see Xr EVP_KEYMGMT-DHX 7
.It DSA, see Xr EVP_KEYMGMT-DSA 7
.It RSA, see Xr EVP_KEYMGMT-RSA 7
.It RSA-PSS
.It EC, see Xr EVP_KEYMGMT-EC 7
.It ED25519, see Xr EVP_KEYMGMT-ED25519 7
.It ED448, see Xr EVP_KEYMGMT-ED448 7
.It X25519, see Xr EVP_KEYMGMT-X25519 7
This is an unapproved algorithm.
The FIPS 140-3 IG states that "Curves that are included in SP 800-186
but not included in SP 800-56Arev3 are not approved for key agreement".
.It X448, see Xr EVP_KEYMGMT-X448 7
This is an unapproved algorithm.
The FIPS 140-3 IG states that "Curves that are included in SP 800-186
but not" included in SP 800-56Arev3 are not approved for key agreement".
.It TLS1-PRF
.It HKDF
.It HMAC, see Xr EVP_KEYMGMT-HMAC 7
.It CMAC, see Xr EVP_KEYMGMT-CMAC 7
.It ML-DSA-44, see Xr EVP_KEYMGMT-ML-DSA 7
.It ML-DSA-65, see Xr EVP_KEYMGMT-ML-DSA 7
.It ML-DSA-87, see Xr EVP_KEYMGMT-ML-DSA 7
.It SLH-DSA-SHA2-128s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-128f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-192s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-192f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-256s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-256f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-128s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-128f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-192s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-192f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-256s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-256f, see Xr EVP_KEYMGMT-SLH-DSA 7
.El
.Ss Random Number Generation
.Bl -tag -width Ds
.It CRNG-TEST, see Xr EVP_RAND-CRNG-TEST 7
.It CTR-DRBG, see Xr EVP_RAND-CTR-DRBG 7
.It HASH-DRBG, see Xr EVP_RAND-HASH-DRBG 7
.It HMAC-DRBG, see Xr EVP_RAND-HMAC-DRBG 7
.It TEST-RAND, see Xr EVP_RAND-TEST-RAND 7
TEST-RAND is an unapproved algorithm.
.El
.Sh SELF TESTING
A requirement of FIPS modules is to run cryptographic algorithm self
tests.
FIPS 140-3 requires known answer tests to be run on startup as well as
conditional tests that run during cryptographic operations.
.Pp
An optional callback mechanism is available to return information to the
user using
.Xr OSSL_SELF_TEST_set_callback 3 .
.Pp
The parameters passed to the callback are described in
.Xr OSSL_SELF_TEST_new 3
.Pp
The OpenSSL FIPS module uses the following mechanism to provide
information about the self tests as they run.
This is useful for debugging if a self test is failing.
The callback also allows forcing any self test to fail, in order to
check that it operates correctly on failure.
Note that all self tests run even if a self test failure occurs.
.Pp
The FIPS module passes the following type(s) to
.Xr OSSL_SELF_TEST_onbegin 3 .
.Bl -tag -width Ds
.It \(dqModule_Integrity" ( Ns Sy OSSL_SELF_TEST_TYPE_MODULE_INTEGRITY )
Uses HMAC SHA256 on the module file to validate that the module has not
been modified.
The integrity value is compared to a value written to a configuration
file during installation.
.It \(dqKAT_Integrity" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_INTEGRITY )
Used during the Module Integrity test to perform a known answer test on
HMAC SHA256 prior to using it.
.It \(dqKAT_Cipher" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_CIPHER )
Known answer test for a symmetric cipher.
.It \(dqKAT_AsymmetricCipher" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_ASYM_CIPHER )
Known answer test for a asymmetric cipher.
.It \(dqKAT_Digest" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_DIGEST )
Known answer test for a digest.
.It \(dqKAT_AsymmetricKeyGeneration" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_ASYM_KEYGEN )
Known answer test for asymmetric key generation.
.It \(dqKAT_Signature" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_SIGNATURE )
Known answer test for a signature.
.It \(dqPCT_Signature" ( Ns Sy OSSL_SELF_TEST_TYPE_PCT_SIGNATURE )
Pairwise Consistency check for a signature.
.It \(dqKAT_KDF" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_KDF )
Known answer test for a key derivation function.
.It \(dqKAT_KA" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_KA )
Known answer test for key agreement.
.It \(dqKAT_KEM" ( Ns Sy OSSL_SELF_TEST_TYPE_KAT_KEM )
Known answer test for key encapsulation.
.It \(dqDRBG" ( Ns Sy OSSL_SELF_TEST_TYPE_DRBG )
Known answer test for a Deterministic Random Bit Generator.
.It \(dqConditional_PCT" ( Ns Sy OSSL_SELF_TEST_TYPE_PCT )
Conditional test that is run during the generation of key pairs.
.It \(dqImport_PCT" ( Ns Sy OSSL_SELF_TEST_TYPE_PCT_IMPORT )
Conditional test that is run during the import of key pairs.
.It \(dqConditional_KAT" ( Ns Sy OSSL_SELF_TEST_TYPE_PCT_KAT )
Conditional test run during generation that derive the public key from
the private key and checks that the public key matches.
This is a SP 800-56A requirement.
.It \(dqContinuous_RNG_Test" ( Ns Sy OSSL_SELF_TEST_TYPE_CRNG )
Continuous random number generator test.
.It \(dqInstall_Integrity" ( Ns Sy OSSL_SELF_TEST_TYPE_INSTALL_INTEGRITY )
This is deprecated.
The option is no longer used since FIPS 140-3 requires self tests to
always run on startup.
Previous FIPS 140-2 validations allowed the self tests to be run just
once.
.El
.Pp
The FIPS module passes the following descriptions(s) to
.Xr OSSL_SELF_TEST_onbegin 3 .
.Bl -tag -width Ds
.It \(dqHMAC" ( Ns Sy OSSL_SELF_TEST_DESC_INTEGRITY_HMAC )
"Module_Integrity" uses this.
.It \(dqRSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_RSA_PKCS1 )
.It \(dqRSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_RSA )
.It \(dqECDSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_ECDSA )
.It \(dqEDDSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_EDDSA )
.It \(dqDSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_DSA )
.It \(dqML-DSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_ML_DSA )
.It \(dqML-KEM" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_ML_KEM )
.It \(dqSLH-DSA" ( Ns Sy OSSL_SELF_TEST_DESC_PCT_SLH_DSA )
Key generation tests used with the "Pairwise_Consistency_Test" type.
.It \(dqRSA_Encrypt" ( Ns Sy OSSL_SELF_TEST_DESC_ASYM_RSA_ENC )
.It \(dqRSA_Decrypt" ( Ns Sy OSSL_SELF_TEST_DESC_ASYM_RSA_DEC )
"KAT_AsymmetricCipher" uses this to indicate an encrypt or decrypt KAT.
.It \(dqML-DSA" ( Ns Sy OSSL_SELF_TEST_DESC_KEYGEN_ML_DSA )
.It \(dqML-KEM" ( Ns Sy OSSL_SELF_TEST_DESC_KEYGEN_ML_KEM )
.It \(dqSLH-DSA" ( Ns Sy OSSL_SELF_TEST_DESC_KEYGEN_SLH_DSA )
"KAT_AsymmetricKeyGeneration" uses this to indicate a key generation
KAT.
.It \(dqAES_GCM" ( Ns Sy OSSL_SELF_TEST_DESC_CIPHER_AES_GCM )
.It \(dqAES_ECB_Decrypt" ( Ns Sy OSSL_SELF_TEST_DESC_CIPHER_AES_ECB )
.It \(dqTDES" ( Ns Sy OSSL_SELF_TEST_DESC_CIPHER_TDES )
Symmetric cipher tests used with the "KAT_Cipher" type.
.It \(dqSHA1" ( Ns Sy OSSL_SELF_TEST_DESC_MD_SHA1 )
.It \(dqSHA2" ( Ns Sy OSSL_SELF_TEST_DESC_MD_SHA2 )
.It \(dqSHA3" ( Ns Sy OSSL_SELF_TEST_DESC_MD_SHA3 )
Digest tests used with the "KAT_Digest" type.
.It \(dqDSA" ( Ns Sy OSSL_SELF_TEST_DESC_SIGN_DSA )
.It \(dqRSA" ( Ns Sy OSSL_SELF_TEST_DESC_SIGN_RSA )
.It \(dqECDSA" ( Ns Sy OSSL_SELF_TEST_DESC_SIGN_ECDSA )
.It \(dqEDDSA" ( Ns Sy OSSL_SELF_TEST_DESC_SIGN_EDDSA )
.It \(dqML-DSA" ( Ns Sy OSSL_SELF_TEST_DESC_SIGN_ML_DSA )
.It \(dqSLH-DSA" ( Ns Sy OSSL_SELF_TEST_DESC_SIGN_SLH_DSA )
Signature tests used with the "KAT_Signature" type.
.It \(dqECDH" ( Ns Sy OSSL_SELF_TEST_DESC_KA_ECDH )
.It \(dqDH" ( Ns Sy OSSL_SELF_TEST_DESC_KA_DH )
Key agreement tests used with the "KAT_KA" type.
.It \(dqHKDF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_HKDF )
.It \(dqTLS13_KDF_EXTRACT" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_TLS13_EXTRACT )
.It \(dqTLS13_KDF_EXPAND" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_TLS13_EXPAND )
.It \(dqSSKDF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_SSKDF )
.It \(dqX963KDF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_X963KDF )
.It \(dqX942KDF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_X942KDF )
.It \(dqPBKDF2" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_PBKDF2 )
.It \(dqSSHKDF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_SSHKDF )
.It \(dqTLS12_PRF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_TLS12_PRF )
.It \(dqKBKDF" ( Ns Sy OSSL_SELF_TEST_DESC_KDF_KBKDF )
Key Encapsulation Function tests used with the "KAT_KEM" type.
.It \(dqKEM_Encap" ( Ns Sy OSSL_SELF_TEST_DESC_ENCAP_KEM )
.It \(dqKEM_Decap" ( Ns Sy OSSL_SELF_TEST_DESC_DECAP_KEM )
.It \(dqKEM_Decap_Reject" ( Ns Sy OSSL_SELF_TEST_DESC_DECAP_REJ_KEM )
Key Derivation Function tests used with the "KAT_KDF" type.
.It \(dqCTR" ( Ns Sy OSSL_SELF_TEST_DESC_DRBG_CTR )
.It \(dqHASH" ( Ns Sy OSSL_SELF_TEST_DESC_DRBG_HASH )
.It \(dqHMAC" ( Ns Sy OSSL_SELF_TEST_DESC_DRBG_HMAC )
DRBG tests used with the "DRBG" type.
.It \(dqRNG" ( Ns Sy OSSL_SELF_TEST_DESC_RNG )
"Continuous_RNG_Test" uses this.
.El
.Sh EXAMPLES
A simple self test callback is shown below for illustrative purposes.
.Bd -literal
  #include <openssl/self_test.h>

  static OSSL_CALLBACK self_test_cb;

  static int self_test_cb(const OSSL_PARAM params[], void *arg)
  {
    int ret = 0;
    const OSSL_PARAM *p = NULL;
    const char *phase = NULL, *type = NULL, *desc = NULL;

    p = OSSL_PARAM_locate_const(params, OSSL_PROV_PARAM_SELF_TEST_PHASE);
    if (p == NULL || p->data_type != OSSL_PARAM_UTF8_STRING)
        goto err;
    phase = (const char *)p->data;

    p = OSSL_PARAM_locate_const(params, OSSL_PROV_PARAM_SELF_TEST_DESC);
    if (p == NULL || p->data_type != OSSL_PARAM_UTF8_STRING)
        goto err;
    desc = (const char *)p->data;

    p = OSSL_PARAM_locate_const(params, OSSL_PROV_PARAM_SELF_TEST_TYPE);
    if (p == NULL || p->data_type != OSSL_PARAM_UTF8_STRING)
        goto err;
    type = (const char *)p->data;

    /* Do some logging */
    if (strcmp(phase, OSSL_SELF_TEST_PHASE_START) == 0)
        BIO_printf(bio_out, "%s : (%s) : ", desc, type);
    if (strcmp(phase, OSSL_SELF_TEST_PHASE_PASS) == 0
            || strcmp(phase, OSSL_SELF_TEST_PHASE_FAIL) == 0)
        BIO_printf(bio_out, "%s\en", phase);

    /* Corrupt the SHA1 self test during the 'corrupt' phase by returning 0 */
    if (strcmp(phase, OSSL_SELF_TEST_PHASE_CORRUPT) == 0
            && strcmp(desc, OSSL_SELF_TEST_DESC_MD_SHA1) == 0) {
        BIO_printf(bio_out, "%s %s", phase, desc);
        return 0;
    }
    ret = 1;
  err:
    return ret;
  }
.Ed
.Sh NOTES
Some released versions of OpenSSL do not include a validated FIPS
provider.
To determine which versions have undergone the validation process,
please refer to the
.Lk https://www.openssl.org/source/ .
If you require FIPS-approved functionality, it is essential to build
your FIPS provider using one of the validated versions listed there.
Normally, it is possible to utilize a FIPS provider constructed from one
of the validated versions alongside
.Pa libcrypto
and
.Pa libssl
compiled from any release within the same major release series.
This flexibility enables you to address bug fixes and CVEs that fall
outside the FIPS boundary.
.Pp
You can load the FIPS provider into multiple library contexts as any
other provider.
However the following restriction applies.
The FIPS provider cannot be used by multiple copies of OpenSSL libcrypto
in a single process.
.Pp
As the provider saves core callbacks to the libcrypto obtained in the
.Xr OSSL_provider_init 3
call to global data it will fail if subsequent invocations of its
.Xr OSSL_provider_init 3
function yield different addresses of these callbacks than in the
initial call.
This happens when different copies of libcrypto are present in the
memory of the process and both try to load the same FIPS provider.
A workaround is to have a different copy of the FIPS provider loaded for
each of the libcrypto instances in the process.
.Sh SEE ALSO
.Xr openssl-fipsinstall 1 ,
.Xr fips_config 5 ,
.Xr OSSL_SELF_TEST_set_callback 3 ,
.Xr OSSL_SELF_TEST_new 3 ,
.Xr OSSL_PARAM 3 ,
.Xr openssl-core.h 7 ,
.Xr openssl-core_dispatch.h 7 ,
.Xr provider 7 ,
.Lk https://www.openssl.org/source/
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
