.Dd 2025-09-30
.Dt OSSL_PROVIDER-NULL 7ossl
.Os
.Sh NAME
.Nm OSSL_PROVIDER-null
.Nd OpenSSL null provider
.Sh DESCRIPTION
The OpenSSL null provider supplies no algorithms.
.Pp
It can used to guarantee that the default library context and a fallback
provider will not be accidentally accessed.
.Ss Properties
The null provider defines no properties.
.Sh OPERATIONS AND ALGORITHMS
The OpenSSL null provider supports no operations and algorithms.
.Sh SEE ALSO
.Xr provider 7
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
