.Dd 2025-09-30
.Dt OSSL_PROVIDER-BASE 7ossl
.Os
.Sh NAME
.Nm OSSL_PROVIDER-base
.Nd OpenSSL base provider
.Sh DESCRIPTION
The OpenSSL base provider supplies the encoding for OpenSSL's asymmetric
cryptography.
.Ss Properties
The implementations in this provider specifically have this property
defined:
.Bl -tag -width Ds
.It \(dqprovider=base"
.El
It may be used in a property query string with fetching functions.
.Pp
It isn't mandatory to query for this property, except to make sure to
get implementations of this provider and none other.
.Bl -tag -width Ds
.It \(dqtype=parameters"
.It \(dqtype=private"
.It \(dqtype=public"
.El
These may be used in a property query string with fetching functions to
select which data are to be encoded.
Either the private key material, the public key material or the domain
parameters can be selected.
.Bl -tag -width Ds
.It \(dqformat=der"
.It \(dqformat=pem"
.It \(dqformat=text"
.El
These may be used in a property query string with fetching functions to
select the encoding output format.
Either the DER, PEM and plaintext are currently permitted.
.Sh OPERATIONS AND ALGORITHMS
The OpenSSL base provider supports these operations and algorithms:
.Ss Random Number Generation
.Bl -tag -width Ds
.It SEED-SRC, see Xr EVP_RAND-SEED-SRC 7
.It JITTER, see Xr EVP_RAND-JITTER 7
.El
In addition to this provider, the "SEED-SRC" and "JITTER" algorithms are
also available in the default provider.
.Ss Asymmetric Key Encoder
.Bl -tag -width Ds
.It RSA
.It RSA-PSS
.It DH
.It DHX
.It DSA
.It EC
.It ED25519
.It ED448
.It X25519
.It X448
.It SM2
.It ML-DSA-44
.It ML-DSA-65
.It ML-DSA-87
.It ML-KEM-512
.It ML-KEM-768
.It ML-KEM-1024
.It SLH-DSA-SHA2-128s
.It SLH-DSA-SHA2-128f
.It SLH-DSA-SHA2-192s
.It SLH-DSA-SHA2-192f
.It SLH-DSA-SHA2-256s
.It SLH-DSA-SHA2-256f
.It SLH-DSA-SHAKE-128s
.It SLH-DSA-SHAKE-128f
.It SLH-DSA-SHAKE-192s
.It SLH-DSA-SHAKE-192f
.It SLH-DSA-SHAKE-256s
.It SLH-DSA-SHAKE-256f
.El
In addition to this provider, all of these encoding algorithms are also
available in the default provider.
Some of these algorithms may be used in combination with the FIPS
provider.
.Ss Asymmetric Key Decoder
.Bl -tag -width Ds
.It RSA
.It RSA-PSS
.It DH
.It DHX
.It DSA
.It EC
.It ED25519
.It ED448
.It X25519
.It X448
.It SM2
.It DER
.It ML-DSA-44
.It ML-DSA-65
.It ML-DSA-87
.It ML-KEM-512
.It ML-KEM-768
.It ML-KEM-1024
.It SLH-DSA-SHA2-128s
.It SLH-DSA-SHA2-128f
.It SLH-DSA-SHA2-192s
.It SLH-DSA-SHA2-192f
.It SLH-DSA-SHA2-256s
.It SLH-DSA-SHA2-256f
.It SLH-DSA-SHAKE-128s
.It SLH-DSA-SHAKE-128f
.It SLH-DSA-SHAKE-192s
.It SLH-DSA-SHAKE-192f
.It SLH-DSA-SHAKE-256s
.It SLH-DSA-SHAKE-256f
.El
In addition to this provider, all of these decoding algorithms are also
available in the default provider.
Some of these algorithms may be used in combination with the FIPS
provider.
.Ss Stores
.Bl -tag -width Ds
.It file
.It org.openssl.winstore, see Xr OSSL_STORE-winstore 7
.El
In addition to this provider, all of these store algorithms are also
available in the default provider.
.Sh SEE ALSO
.Xr OSSL_PROVIDER-default 7 ,
.Xr openssl-core.h 7 ,
.Xr openssl-core_dispatch.h 7 ,
.Xr provider 7
.Sh HISTORY
This functionality was added in OpenSSL 3.0.
.Pp
Support for
.Sy ML-DSA
and <ML-KEM> was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
