.Dd 2025-09-30
.Dt OSSL-GUIDE-MIGRATION 7ossl
.Os
.Sh NAME
.Nm ossl-guide-migration ,
.Nm migration_guide
.Nd OpenSSL Guide: Migrating from older OpenSSL versions
.Sh SYNOPSIS
See the individual manual pages for details.
.Sh DESCRIPTION
This guide details the changes required to migrate to new versions of
OpenSSL. Currently this covers OpenSSL 3.0 & 3.1. For earlier versions
refer to
.Lk https://github.com/openssl/openssl/blob/master/CHANGES.md .
For an overview of some of the key concepts introduced in OpenSSL 3.0
see
.Xr crypto 7 .
.Sh OPENSSL 3.1
.Ss Main Changes from OpenSSL 3.0
The FIPS provider in OpenSSL 3.1 includes some non-FIPS validated
algorithms, consequently the property query
.Qo Li fips=yes Qc
is mandatory for applications that want to operate in a FIPS approved
manner.
The algorithms are:
.Bl -tag -width Ds
.It Triple DES ECB
.It Triple DES CBC
.It EdDSA
.El
There are no other changes requiring additional migration measures since
OpenSSL 3.0.
.Sh OPENSSL 3.0
.Ss Main Changes from OpenSSL 1.1.1
.Pp
.Em Major Release
.Pp
OpenSSL 3.0 is a major release and consequently any application that
currently uses an older version of OpenSSL will at the very least need
to be recompiled in order to work with the new version.
It is the intention that the large majority of applications will work
unchanged with OpenSSL 3.0 if those applications previously worked with
OpenSSL 1.1.1. However this is not guaranteed and some changes may be
required in some cases.
Changes may also be required if applications need to take advantage of
some of the new features available in OpenSSL 3.0 such as the
availability of the FIPS module.
.Pp
.Em License Change
.Pp
In previous versions, OpenSSL was licensed under the
.Lk https://www.openssl.org/source/license-openssl-ssleay.txt
(both licenses apply).
From OpenSSL 3.0 this is replaced by the
.Lk https://www.openssl.org/source/apache-license-2.0.txt .
.Pp
.Em Providers and FIPS support
.Pp
One of the key changes from OpenSSL 1.1.1 is the introduction of the
Provider concept.
Providers collect together and make available algorithm implementations.
With OpenSSL 3.0 it is possible to specify, either programmatically or
via a config file, which providers you want to use for any given
application.
OpenSSL 3.0 comes with 5 different providers as standard.
Over time third parties may distribute additional providers that can be
plugged into OpenSSL. All algorithm implementations available via
providers are accessed through the "high level" APIs (for example those
functions prefixed with
.Qo Li EVP Qc Ns ).
They cannot be accessed using the
.Sx Low Level APIs .
.Pp
One of the standard providers available is the FIPS provider.
This makes available FIPS validated cryptographic algorithms.
The FIPS provider is disabled by default and needs to be enabled
explicitly at configuration time using the
.Qo Li enable-fips Qc
option.
If it is enabled, the FIPS provider gets built and installed in addition
to the other standard providers.
No separate installation procedure is necessary.
There is however a dedicated
.Qo Li install_fips Qc
make target, which serves the special purpose of installing only the
FIPS provider into an existing OpenSSL installation.
.Pp
Not all algorithms may be available for the application at a particular
moment.
If the application code uses any digest or cipher algorithm via the EVP
interface, the application should verify the result of the
.Xr EVP_EncryptInit 3 ,
.Xr EVP_EncryptInit_ex 3 ,
and
.Xr EVP_DigestInit 3
functions.
In case when the requested algorithm is not available, these functions
will fail.
.Pp
See also
.Sx Legacy Algorithms
for information on the legacy provider.
.Pp
See also
.Sx Completing the installation of the FIPS Module
and
.Sx Using the FIPS Module in applications .
.Pp
.Em Low Level APIs
.Pp
OpenSSL has historically provided two sets of APIs for invoking
cryptographic algorithms: the "high level" APIs (such as the
.Qo Li EVP Qc
APIs) and the "low level" APIs.
The high level APIs are typically designed to work across all algorithm
types.
The "low level" APIs are targeted at a specific algorithm
implementation.
For example, the EVP APIs provide the functions
.Xr EVP_EncryptInit_ex 3 ,
.Xr EVP_EncryptUpdate 3
and
.Xr EVP_EncryptFinal 3
to perform symmetric encryption.
Those functions can be used with the algorithms AES, CHACHA, 3DES etc.
On the other hand, to do AES encryption using the low level APIs you
would have to call AES specific functions such as
.Xr AES_set_encrypt_key 3 ,
.Xr AES_encrypt 3 ,
and so on.
The functions for 3DES are different.
Use of the low level APIs has been informally discouraged by the OpenSSL
development team for a long time.
However in OpenSSL 3.0 this is made more formal.
All such low level APIs have been deprecated.
You may still use them in your applications, but you may start to see
deprecation warnings during compilation (dependent on compiler support
for this).
Deprecated APIs may be removed from future versions of OpenSSL so you
are strongly encouraged to update your code to use the high level APIs
instead.
.Pp
This is described in more detail in
.Sx Deprecation of Low Level Functions
.Pp
.Em Legacy Algorithms
.Pp
Some cryptographic algorithms such as
.Sy MD2
and
.Sy DES
that were available via the EVP APIs are now considered legacy and their
use is strongly discouraged.
These legacy EVP algorithms are still available in OpenSSL 3.0 but not
by default.
If you want to use them then you must load the legacy provider.
This can be as simple as a config file change, or can be done
programmatically.
See
.Xr OSSL_PROVIDER-legacy 7
for a complete list of algorithms.
Applications using the EVP APIs to access these algorithms should
instead use more modern algorithms.
If that is not possible then these applications should ensure that the
legacy provider has been loaded.
This can be achieved either programmatically or via configuration.
See
.Xr crypto 7
man page for more information about providers.
.Pp
.Em Engines and \(dqMETHOD" APIs
.Pp
The refactoring to support Providers conflicts internally with the APIs
used to support engines, including the ENGINE API and any function that
creates or modifies custom "METHODS" (for example
.Xr EVP_MD_meth_new 3 ,
.Xr EVP_CIPHER_meth_new 3 ,
.Xr EVP_PKEY_meth_new 3 ,
.Xr RSA_meth_new 3 ,
.Xr EC_KEY_METHOD_new 3 ,
etc.).
These functions are being deprecated in OpenSSL 3.0, and users of these
APIs should know that their use can likely bypass provider selection and
configuration, with unintended consequences.
This is particularly relevant for applications written to use the
OpenSSL 3.0 FIPS module, as detailed below.
Authors and maintainers of external engines are strongly encouraged to
refactor their code transforming engines into providers using the new
Provider API and avoiding deprecated methods.
.Pp
.Em Support of legacy engines
.Pp
If openssl is not built without engine support or deprecated API
support, engines will still work.
However, their applicability will be limited.
.Pp
New algorithms provided via engines will still work.
.Pp
Engine-backed keys can be loaded via custom
.Sy OSSL_STORE
implementation.
In this case the
.Sy EVP_PKEY
objects created via
.Xr ENGINE_load_private_key 3
will be considered legacy and will continue to work.
.Pp
To ensure the future compatibility, the engines should be turned to
providers.
To prefer the provider-based hardware offload, you can specify the
default properties to prefer your provider.
.Pp
Setting engine-based or application-based default low-level crypto
method such as
.Sy RSA_METHOD
or
.Sy EC_KEY_METHOD
is still possible and keys inside the default provider will use the
engine-based implementation for the crypto operations.
However
.Sy EVP_PKEY Ns s
created by decoding by using
.Sy OSSL_DECODER ,
.Sy PEM_
or
.Sy d2i_
APIs will be provider-based.
To create a fully legacy
.Sy EVP_PKEY Ns s
.Xr EVP_PKEY_set1_RSA 3 ,
.Xr EVP_PKEY_set1_EC_KEY 3
or similar functions must be used.
.Pp
.Em Versioning Scheme
.Pp
The OpenSSL versioning scheme has changed with the OpenSSL 3.0 release.
The new versioning scheme has this format:
.Pp
MAJOR.MINOR.PATCH
.Pp
For OpenSSL 1.1.1 and below, different patch levels were indicated by a
letter at the end of the release version number.
This will no longer be used and instead the patch level is indicated by
the final number in the version.
A change in the second (MINOR) number indicates that new features may
have been added.
OpenSSL versions with the same major number are API and ABI compatible.
If the major number changes then API and ABI compatibility is not
guaranteed.
.Pp
For more information, see
.Xr OpenSSL_version 3 .
.Pp
.Em Other major new features
.Pp
.Pp
.No Certificate Management Protocol (CMP, RFC 4210)
.Pp
This also covers CRMF (RFC 4211) and HTTP transfer (RFC 6712) See
.Xr openssl-cmp 1
and
.Xr OSSL_CMP_exec_certreq 3
as starting points.
.Pp
.No HTTP(S) client
.Pp
A proper HTTP(S) client that supports GET and POST, redirection, plain
and ASN.1-encoded contents, proxies, and timeouts.
.Pp
.No Key Derivation Function API (EVP_KDF)
.Pp
This simplifies the process of adding new KDF and PRF implementations.
.Pp
Previously KDF algorithms had been shoe-horned into using the EVP_PKEY
object which was not a logical mapping.
Existing applications that use KDF algorithms using EVP_PKEY (scrypt,
TLS1 PRF and HKDF) may be slower as they use an EVP_KDF bridge
internally.
All new applications should use the new
.Xr EVP_KDF 3
interface.
See also
.Xr OSSL_PROVIDER-default 7
and
.Xr OSSL_PROVIDER-FIPS 7 .
.Pp
.No Message Authentication Code API (EVP_MAC)
.Pp
This simplifies the process of adding MAC implementations.
.Pp
This includes a generic EVP_PKEY to EVP_MAC bridge, to facilitate the
continued use of MACs through raw private keys in functionality such as
.Xr EVP_DigestSign 3
and
.Xr EVP_DigestVerify 3 .
.Pp
All new applications should use the new
.Xr EVP_MAC 3
interface.
See also
.Xr OSSL_PROVIDER-default 7
and
.Xr OSSL_PROVIDER-FIPS 7 .
.Pp
.No Algorithm Fetching
.Pp
Using calls to convenience functions such as
.Xr EVP_sha256 3
and
.Xr EVP_aes_256_gcm 3
may incur a performance penalty when using providers.
Retrieving algorithms from providers involves searching for an algorithm
by name.
This is much slower than directly accessing a method table.
It is recommended to prefetch algorithms if an algorithm is used many
times.
See
.Xr crypto 7 ,
.Xr crypto 7
and
.Xr crypto 7 .
.Pp
.No Support for Linux Kernel TLS
.Pp
In order to use KTLS, support for it must be compiled in using the
.Qo Li enable-ktls Qc
configuration option.
It must also be enabled at run time using the
.Sy SSL_OP_ENABLE_KTLS
option.
.Pp
.No New Algorithms
.Pp
.Bl -bullet
.It
KDF algorithms "SINGLE STEP" and "SSH"
.Pp
See
.Xr EVP_KDF-SS 7
and
.Xr EVP_KDF-SSHKDF 7
.It
MAC Algorithms "GMAC" and "KMAC"
.Pp
See
.Xr EVP_MAC-GMAC 7
and
.Xr EVP_MAC-KMAC 7 .
.It
KEM Algorithm "RSASVE"
.Pp
See
.Xr EVP_KEM-RSA 7 .
.It
Cipher Algorithm "AES-SIV"
.Pp
See
.Xr EVP_EncryptInit 3 .
.It
AES Key Wrap inverse ciphers supported by EVP layer.
.Pp
The inverse ciphers use AES decryption for wrapping, and AES encryption
for unwrapping.
The algorithms are: "AES-128-WRAP-INV", "AES-192-WRAP-INV",
"AES-256-WRAP-INV", "AES-128-WRAP-PAD-INV", "AES-192-WRAP-PAD-INV" and
"AES-256-WRAP-PAD-INV".
.It
CTS ciphers added to EVP layer.
.Pp
The algorithms are "AES-128-CBC-CTS", "AES-192-CBC-CTS",
"AES-256-CBC-CTS", "CAMELLIA-128-CBC-CTS", "CAMELLIA-192-CBC-CTS" and
"CAMELLIA-256-CBC-CTS". CS1, CS2 and CS3 variants are supported.
.El
.Pp
.No CMS and PKCS#7 updates
.Pp
.Bl -bullet
.It
Added CAdES-BES signature verification support.
.It
Added CAdES-BES signature scheme and attributes support (RFC 5126) to
CMS API.
.It
Added AuthEnvelopedData content type structure (RFC 5083) using AES_GCM
.Pp
This uses the AES-GCM parameter (RFC 5084) for the Cryptographic Message
Syntax.
Its purpose is to support encryption and decryption of a digital
envelope that is both authenticated and encrypted using AES GCM mode.
.It
.Xr PKCS7_get_octet_string 3
and
.Xr PKCS7_type_is_other 3
were made public.
.El
.Pp
.No PKCS#12 API updates
.Pp
The default algorithms for pkcs12 creation with the
.Xr PKCS12_create 3
function were changed to more modern PBKDF2 and AES based algorithms.
The default MAC iteration count was changed to PKCS12_DEFAULT_ITER to
make it equal with the password-based encryption iteration count.
The default digest algorithm for the MAC computation was changed to
SHA-256. The pkcs12 application now supports -legacy option that
restores the previous default algorithms to support interoperability
with legacy systems.
.Pp
Added enhanced PKCS#12 APIs which accept a library context
.Sy OSSL_LIB_CTX
and (where relevant) a property query.
Other APIs which handle PKCS#7 and PKCS#8 objects have also been
enhanced where required.
This includes:
.Pp
.Xr PKCS12_add_key_ex 3 ,
.Xr PKCS12_add_safe_ex 3 ,
.Xr PKCS12_add_safes_ex 3 ,
.Xr PKCS12_create_ex 3 ,
.Xr PKCS12_decrypt_skey_ex 3 ,
.Xr PKCS12_init_ex 3 ,
.Xr PKCS12_item_decrypt_d2i_ex 3 ,
.Xr PKCS12_item_i2d_encrypt_ex 3 ,
.Xr PKCS12_key_gen_asc_ex 3 ,
.Xr PKCS12_key_gen_uni_ex 3 ,
.Xr PKCS12_key_gen_utf8_ex 3 ,
.Xr PKCS12_pack_p7encdata_ex 3 ,
.Xr PKCS12_pbe_crypt_ex 3 ,
.Xr PKCS12_PBE_keyivgen_ex 3 ,
.Xr PKCS12_SAFEBAG_create_pkcs8_encrypt_ex 3 ,
.Xr PKCS5_pbe2_set_iv_ex 3 ,
.Xr PKCS5_pbe_set0_algor_ex 3 ,
.Xr PKCS5_pbe_set_ex 3 ,
.Xr PKCS5_pbkdf2_set_ex 3 ,
.Xr PKCS5_v2_PBE_keyivgen_ex 3 ,
.Xr PKCS5_v2_scrypt_keyivgen_ex 3 ,
.Xr PKCS8_decrypt_ex 3 ,
.Xr PKCS8_encrypt_ex 3 ,
.Xr PKCS8_set0_pbe_ex 3 .
.Pp
As part of this change the EVP_PBE_xxx APIs can also accept a library
context and property query and will call an extended version of the
key/IV derivation function which supports these parameters.
This includes
.Xr EVP_PBE_CipherInit_ex 3 ,
.Xr EVP_PBE_find_ex 3
and
.Xr EVP_PBE_scrypt_ex 3 .
.Pp
.No PKCS#12 KDF versus FIPS
.Pp
Unlike in 1.x.y, the PKCS12KDF algorithm used when a PKCS#12 structure
is created with a MAC that does not work with the FIPS provider as the
PKCS12KDF is not a FIPS approvable mechanism.
.Pp
See
.Xr EVP_KDF-PKCS12KDF 7 ,
.Xr PKCS12_create 3 ,
.Xr openssl-pkcs12 1 ,
.Xr OSSL_PROVIDER-FIPS 7 .
.Pp
.No Windows thread synchronization changes
.Pp
Windows thread synchronization uses read/write primitives (SRWLock) when
supported by the OS, otherwise CriticalSection continues to be used.
.Pp
.No Trace API
.Pp
A new generic trace API has been added which provides support for
enabling instrumentation through trace output.
This feature is mainly intended as an aid for developers and is disabled
by default.
To utilize it, OpenSSL needs to be configured with the
.Qo Li enable-trace Qc
option.
.Pp
If the tracing API is enabled, the application can activate trace output
by registering BIOs as trace channels for a number of tracing and
debugging categories.
See
.Xr OSSL_trace_enabled 3 .
.Pp
.No Key validation updates
.Pp
.Xr EVP_PKEY_public_check 3
and
.Xr EVP_PKEY_param_check 3
now work for more key types.
This includes RSA, DSA, ED25519, X25519, ED448 and X448. Previously (in
1.1.1) they would return -2. For key types that do not have parameters
.Xr EVP_PKEY_param_check 3
will always return 1.
.Pp
.Em Other notable deprecations and changes
.Pp
.Pp
.No The function code part of an OpenSSL error code is no longer relevant
.Pp
This code is now always set to zero.
Related functions are deprecated.
.Pp
.No STACK and HASH macros have been cleaned up
.Pp
The type-safe wrappers are declared everywhere and implemented once.
See
.Xr DEFINE_STACK_OF 3
and
.Xr DEFINE_LHASH_OF_EX 3 .
.Pp
.No The RAND_DRBG subsystem has been removed
.Pp
The new
.Xr EVP_RAND 3
is a partial replacement: the DRBG callback framework is absent.
The RAND_DRBG API did not fit well into the new provider concept as
implemented by EVP_RAND and EVP_RAND_CTX.
.Pp
.No Removed FIPS_mode() and FIPS_mode_set()
.Pp
These functions are legacy APIs that are not applicable to the new
provider model.
Applications should instead use
.Xr EVP_default_properties_is_fips_enabled 3
and
.Xr EVP_default_properties_enable_fips 3 .
.Pp
.No Key generation is slower
.Pp
The Miller-Rabin test now uses 64 rounds, which is used for all prime
generation, including RSA key generation.
This affects the time for larger keys sizes.
.Pp
The default key generation method for the regular 2-prime RSA keys was
changed to the FIPS186-4 B.3.6 method (Generation of Probable Primes
with Conditions Based on Auxiliary Probable Primes).
This method is slower than the original method.
.Pp
.No Change PBKDF2 to conform to SP800-132 instead of the older PKCS5 RFC2898
.Pp
This checks that the salt length is at least 128 bits, the derived key
length is at least 112 bits, and that the iteration count is at least
1000. For backwards compatibility these checks are disabled by default
in the default provider, but are enabled by default in the FIPS
provider.
.Pp
To enable or disable the checks see
.Sy OSSL_KDF_PARAM_PKCS5
in
.Xr EVP_KDF-PBKDF2 7 .
The parameter can be set using
.Xr EVP_KDF_derive 3 .
.Pp
.No Enforce a minimum DH modulus size of 512 bits
.Pp
Smaller sizes now result in an error.
.Pp
.No SM2 key changes
.Pp
EC EVP_PKEYs with the SM2 curve have been reworked to automatically
become EVP_PKEY_SM2 rather than EVP_PKEY_EC.
.Pp
Unlike in previous OpenSSL versions, this means that applications cannot
call
.Sy EVP_PKEY_set_alias_type(pkey, EVP_PKEY_SM2)
to get SM2 computations.
.Pp
Parameter and key generation is also reworked to make it possible to
generate EVP_PKEY_SM2 parameters and keys.
Applications must now generate SM2 keys directly and must not create an
EVP_PKEY_EC key first.
It is no longer possible to import an SM2 key with domain parameters
other than the SM2 elliptic curve ones.
.Pp
Validation of SM2 keys has been separated from the validation of regular
EC keys, allowing to improve the SM2 validation process to reject loaded
private keys that are not conforming to the SM2 ISO standard.
In particular, a private scalar
.Em k
outside the range
.Em 1 <= k < n-1
is now correctly rejected.
.Pp
.No EVP_PKEY_set_alias_type() method has been removed
.Pp
This function made a
.Sy EVP_PKEY
object mutable after it had been set up.
In OpenSSL 3.0 it was decided that a provided key should not be able to
change its type, so this function has been removed.
.Pp
.No Functions that return an internal key should be treated as read only
.Pp
Functions such as
.Xr EVP_PKEY_get0_RSA 3
behave slightly differently in OpenSSL 3.0. Previously they returned a
pointer to the low-level key used internally by libcrypto.
From OpenSSL 3.0 this key may now be held in a provider.
Calling these functions will only return a handle on the internal key
where the EVP_PKEY was constructed using this key in the first place,
for example using a function or macro such as
.Xr EVP_PKEY_assign_RSA 3 ,
.Xr EVP_PKEY_set1_RSA 3 ,
etc.
Where the EVP_PKEY holds a provider managed key, then these functions
now return a cached copy of the key.
Changes to the internal provider key that take place after the first
time the cached key is accessed will not be reflected back in the cached
copy.
Similarly any changes made to the cached copy by application code will
not be reflected back in the internal provider key.
.Pp
For the above reasons the keys returned from these functions should
typically be treated as read-only.
To emphasise this the value returned from
.Xr EVP_PKEY_get0_RSA 3 ,
.Xr EVP_PKEY_get0_DSA 3 ,
.Xr EVP_PKEY_get0_EC_KEY 3
and
.Xr EVP_PKEY_get0_DH 3
have been made const.
This may break some existing code.
Applications broken by this change should be modified.
The preferred solution is to refactor the code to avoid the use of these
deprecated functions.
Failing this the code should be modified to use a const pointer instead.
The
.Xr EVP_PKEY_get1_RSA 3 ,
.Xr EVP_PKEY_get1_DSA 3 ,
.Xr EVP_PKEY_get1_EC_KEY 3
and
.Xr EVP_PKEY_get1_DH 3
functions continue to return a non-const pointer to enable them to be
"freed".
However they should also be treated as read-only.
.Pp
.No The public key check has moved from EVP_PKEY_derive() to EVP_PKEY_derive_set_peer()
.Pp
This may mean result in an error in
.Xr EVP_PKEY_derive_set_peer 3
rather than during
.Xr EVP_PKEY_derive 3 .
To disable this check use EVP_PKEY_derive_set_peer_ex(dh, peer, 0).
.Pp
.No The print format has cosmetic changes for some functions
.Pp
The output from numerous "printing" functions such as
.Xr X509_signature_print 3 ,
.Xr X509_print_ex 3 ,
.Xr X509_CRL_print_ex 3 ,
and other similar functions has been amended such that there may be
cosmetic differences between the output observed in 1.1.1 and 3.0. This
also applies to the
.Sy -text
output from the
.Sy openssl x509
and
.Sy openssl crl
applications.
.Pp
.No Interactive mode from the Sy openssl No program has been removed
.Pp
From now on, running it without arguments is equivalent to
.Sy openssl help .
.Pp
.No The error return values from some control calls (ctrl) have changed
.Pp
One significant change is that controls which used to return -2 for
invalid inputs, now return -1 indicating a generic error condition
instead.
.Pp
.No DH and DHX key types have different settable parameters
.Pp
Previously (in 1.1.1) these conflicting parameters were allowed, but
will now result in errors.
See
.Xr EVP_PKEY-DH 7
for further details.
This affects the behaviour of
.Xr openssl-genpkey 1
for DH parameter generation.
.Pp
.No EVP_CIPHER_CTX_set_flags() ordering change
.Pp
If using a cipher from a provider the
.Sy EVP_CIPH_FLAG_LENGTH_BITS
flag can only be set
.Sy after
the cipher has been assigned to the cipher context.
See
.Xr EVP_EncryptInit 3
for more information.
.Pp
.No Validation of operation context parameters
.Pp
Due to move of the implementation of cryptographic operations to the
providers, validation of various operation parameters can be postponed
until the actual operation is executed where previously it happened
immediately when an operation parameter was set.
.Pp
For example when setting an unsupported curve with
.Xr EVP_PKEY_CTX_set_ec_paramgen_curve_nid 3
this function call will not fail but later keygen operations with the
EVP_PKEY_CTX will fail.
.Pp
.No Removal of function code from the error codes
.Pp
The function code part of the error code is now always set to 0. For
that reason the
.Xr ERR_GET_FUNC 3
macro was removed.
Applications must resolve the error codes only using the library number
and the reason code.
.Pp
.No ChaCha20-Poly1305 cipher does not allow a truncated IV length to be used
.Pp
In OpenSSL 3.0 setting the IV length to any value other than 12 will
result in an error.
Prior to OpenSSL 3.0 the ivlen could be smaller that the required 12
byte length, using EVP_CIPHER_CTX_ctrl(ctx, EVP_CRTL_AEAD_SET_IVLEN,
ivlen, NULL). This resulted in an IV that had leading zero padding.
.Ss Installation and Compilation
Please refer to the INSTALL.md file in the top of the distribution for
instructions on how to build and install OpenSSL 3.0. Please also refer
to the various platform specific NOTES files for your specific platform.
.Ss Upgrading from OpenSSL 1.1.1
Upgrading to OpenSSL 3.0 from OpenSSL 1.1.1 should be relatively
straight forward in most cases.
The most likely area where you will encounter problems is if you have
used low level APIs in your code (as discussed above).
In that case you are likely to start seeing deprecation warnings when
compiling your application.
If this happens you have 3 options:
.Bl -enum
.It
Ignore the warnings.
They are just warnings.
The deprecated functions are still present and you may still use them.
However be aware that they may be removed from a future version of
OpenSSL.
.It
Suppress the warnings.
Refer to your compiler documentation on how to do this.
.It
Remove your usage of the low level APIs.
In this case you will need to rewrite your code to use the high level
APIs instead
.El
.Pp
.Em Error code changes
.Pp
As OpenSSL 3.0 provides a brand new Encoder/Decoder mechanism for
working with widely used file formats, application code that checks for
particular error reason codes on key loading failures might need an
update.
.Pp
Password-protected keys may deserve special attention.
If only some errors are treated as an indicator that the user should be
asked about the password again, it's worth testing these scenarios and
processing the newly relevant codes.
.Pp
There may be more cases to treat specially, depending on the calling
application code.
.Ss Upgrading from OpenSSL 1.0.2
Upgrading to OpenSSL 3.0 from OpenSSL 1.0.2 is likely to be
significantly more difficult.
In addition to the issues discussed above in the section about
.Sx Upgrading from OpenSSL 1.1.1 ,
the main things to be aware of are:
.Bl -enum
.It
The build and installation procedure has changed significantly.
.Pp
Check the file INSTALL.md in the top of the installation for
instructions on how to build and install OpenSSL for your platform.
Also read the various NOTES files in the same directory, as applicable
for your platform.
.It
Many structures have been made opaque in OpenSSL 3.0.
.Pp
The structure definitions have been removed from the public header files
and moved to internal header files.
In practice this means that you can no longer stack allocate some
structures.
Instead they must be heap allocated through some function call
(typically those function names have a
.Qo Li _new Qc
suffix to them).
Additionally you must use "setter" or "getter" functions to access the
fields within those structures.
.Pp
For example code that previously looked like this:
.Bd -literal
 EVP_MD_CTX md_ctx;

 /* This line will now generate compiler errors */
 EVP_MD_CTX_init(&md_ctx);
.Ed
.Pp
The code needs to be amended to look like this:
.Bd -literal
 EVP_MD_CTX *md_ctx;

 md_ctx = EVP_MD_CTX_new();
 ...
 ...
 EVP_MD_CTX_free(md_ctx);
.Ed
.It
Support for TLSv1.3 has been added.
.Pp
This has a number of implications for SSL/TLS applications.
See the
.Lk https://github.com/openssl/openssl/wiki/TLS1.3
for further details.
.El
.Pp
More details about the breaking changes between OpenSSL versions 1.0.2
and 1.1.0 can be found on the
.Lk https://github.com/openssl/openssl/wiki/OpenSSL_1.1.0_Changes .
.Pp
.Em Upgrading from the OpenSSL 2.0 FIPS Object Module
.Pp
The OpenSSL 2.0 FIPS Object Module was a separate download that had to
be built separately and then integrated into your main OpenSSL 1.0.2
build.
In OpenSSL 3.0 the FIPS support is fully integrated into the mainline
version of OpenSSL and is no longer a separate download.
For further information see
.Sx Completing the installation of the FIPS Module .
.Pp
The function calls
.Xr FIPS_mode 3
and
.Xr FIPS_mode_set 3
have been removed from OpenSSL 3.0. You should rewrite your application
to not use them.
See
.Xr fips_module 7
and
.Xr OSSL_PROVIDER-FIPS 7
for details.
.Ss Completing the installation of the FIPS Module
The FIPS Module will be built and installed automatically if FIPS
support has been configured.
The current documentation can be found in the
.Lk https://github.com/openssl/openssl/blob/master/README-FIPS.md
file.
.Ss Programming
Applications written to work with OpenSSL 1.1.1 will mostly just work
with OpenSSL 3.0. However changes will be required if you want to take
advantage of some of the new features that OpenSSL 3.0 makes available.
In order to do that you need to understand some new concepts introduced
in OpenSSL 3.0. Read
.Xr crypto 7
for further information.
.Pp
.Em Library Context
.Pp
A library context allows different components of a complex application
to each use a different library context and have different providers
loaded with different configuration settings.
See
.Xr crypto 7
for further info.
.Pp
If the user creates an
.Sy OSSL_LIB_CTX
via
.Xr OSSL_LIB_CTX_new 3
then many functions may need to be changed to pass additional parameters
to handle the library context.
.Pp
.No Using a Library Context - Old functions that should be changed
.Pp
If a library context is needed then all EVP_* digest functions that
return a
.Sy const EVP_MD *
such as
.Xr EVP_sha256 3
should be replaced with a call to
.Xr EVP_MD_fetch 3 .
See
.Xr crypto 7 .
.Pp
If a library context is needed then all EVP_* cipher functions that
return a
.Sy const EVP_CIPHER *
such as
.Xr EVP_aes_128_cbc 3
should be replaced vith a call to
.Xr EVP_CIPHER_fetch 3 .
See
.Xr crypto 7 .
.Pp
Some functions can be passed an object that has already been set up with
a library context such as
.Xr d2i_X509 3 ,
.Xr d2i_X509_CRL 3 ,
.Xr d2i_X509_REQ 3
and
.Xr d2i_X509_PUBKEY 3 .
If NULL is passed instead then the created object will be set up with
the default library context.
Use
.Xr X509_new_ex 3 ,
.Xr X509_CRL_new_ex 3 ,
.Xr X509_REQ_new_ex 3
and
.Xr X509_PUBKEY_new_ex 3
if a library context is required.
.Pp
All functions listed below with a
.Em NAME
have a replacement function
.Em NAME_ex
that takes
.Sy OSSL_LIB_CTX
as an additional argument.
Functions that have other mappings are listed along with the respective
name.
.Bl -bullet
.It
.Xr ASN1_item_new 3 ,
.Xr ASN1_item_d2i 3 ,
.Xr ASN1_item_d2i_fp 3 ,
.Xr ASN1_item_d2i_bio 3 ,
.Xr ASN1_item_sign 3
and
.Xr ASN1_item_verify 3
.It
.Xr BIO_new 3
.It
.Xr b2i_RSA_PVK_bio 3
and
.Xr i2b_PVK_bio 3
.It
.Xr BN_CTX_new 3
and
.Xr BN_CTX_secure_new 3
.It
.Xr CMS_AuthEnvelopedData_create 3 ,
.Xr CMS_ContentInfo_new 3 ,
.Xr CMS_data_create 3 ,
.Xr CMS_digest_create 3 ,
.Xr CMS_EncryptedData_encrypt 3 ,
.Xr CMS_encrypt 3 ,
.Xr CMS_EnvelopedData_create 3 ,
.Xr CMS_ReceiptRequest_create0 3
and
.Xr CMS_sign 3
.It
.Xr CONF_modules_load_file 3
.It
.Xr CTLOG_new 3 ,
.Xr CTLOG_new_from_base64 3
and
.Xr CTLOG_STORE_new 3
.It
.Xr CT_POLICY_EVAL_CTX_new 3
.It
.Xr d2i_AutoPrivateKey 3 ,
.Xr d2i_PrivateKey 3
and
.Xr d2i_PUBKEY 3
.It
.Xr d2i_PrivateKey_bio 3
and
.Xr d2i_PrivateKey_fp 3
.Pp
Use
.Xr d2i_PrivateKey_ex_bio 3
and
.Xr d2i_PrivateKey_ex_fp 3
.It
.Xr EC_GROUP_new 3
.Pp
Use
.Xr EC_GROUP_new_by_curve_name_ex 3
or
.Xr EC_GROUP_new_from_params 3 .
.It
.Xr EVP_DigestSignInit 3
and
.Xr EVP_DigestVerifyInit 3
.It
.Xr EVP_PBE_CipherInit 3 ,
.Xr EVP_PBE_find 3
and
.Xr EVP_PBE_scrypt 3
.It
.Xr PKCS5_PBE_keyivgen 3
.It
.Xr EVP_PKCS82PKEY 3
.It
.Xr EVP_PKEY_CTX_new_id 3
.Pp
Use
.Xr EVP_PKEY_CTX_new_from_name 3
.It
.Xr EVP_PKEY_derive_set_peer 3 ,
.Xr EVP_PKEY_new_raw_private_key 3
and
.Xr EVP_PKEY_new_raw_public_key 3
.It
.Xr EVP_SignFinal 3
and
.Xr EVP_VerifyFinal 3
.It
.Xr NCONF_new 3
.It
.Xr OCSP_RESPID_match 3
and
.Xr OCSP_RESPID_set_by_key 3
.It
.Xr OPENSSL_thread_stop 3
.It
.Xr OSSL_STORE_open 3
.It
.Xr PEM_read_bio_Parameters 3 ,
.Xr PEM_read_bio_PrivateKey 3 ,
.Xr PEM_read_bio_PUBKEY 3 ,
.Xr PEM_read_PrivateKey 3
and
.Xr PEM_read_PUBKEY 3
.It
.Xr PEM_write_bio_PrivateKey 3 ,
.Xr PEM_write_bio_PUBKEY 3 ,
.Xr PEM_write_PrivateKey 3
and
.Xr PEM_write_PUBKEY 3
.It
.Xr PEM_X509_INFO_read_bio 3
and
.Xr PEM_X509_INFO_read 3
.It
.Xr PKCS12_add_key 3 ,
.Xr PKCS12_add_safe 3 ,
.Xr PKCS12_add_safes 3 ,
.Xr PKCS12_create 3 ,
.Xr PKCS12_decrypt_skey 3 ,
.Xr PKCS12_init 3 ,
.Xr PKCS12_item_decrypt_d2i 3 ,
.Xr PKCS12_item_i2d_encrypt 3 ,
.Xr PKCS12_key_gen_asc 3 ,
.Xr PKCS12_key_gen_uni 3 ,
.Xr PKCS12_key_gen_utf8 3 ,
.Xr PKCS12_pack_p7encdata 3 ,
.Xr PKCS12_pbe_crypt 3 ,
.Xr PKCS12_PBE_keyivgen 3 ,
.Xr PKCS12_SAFEBAG_create_pkcs8_encrypt 3
.It
.Xr PKCS5_pbe_set0_algor 3 ,
.Xr PKCS5_pbe_set 3 ,
.Xr PKCS5_pbe2_set_iv 3 ,
.Xr PKCS5_pbkdf2_set 3
and
.Xr PKCS5_v2_scrypt_keyivgen 3
.It
.Xr PKCS7_encrypt 3 ,
.Xr PKCS7_new 3
and
.Xr PKCS7_sign 3
.It
.Xr PKCS8_decrypt 3 ,
.Xr PKCS8_encrypt 3
and
.Xr PKCS8_set0_pbe 3
.It
.Xr RAND_bytes 3
and
.Xr RAND_priv_bytes 3
.It
.Xr SMIME_write_ASN1 3
.It
.Xr SSL_load_client_CA_file 3
.It
.Xr SSL_CTX_new 3
.It
.Xr TS_RESP_CTX_new 3
.It
.Xr X509_CRL_new 3
.It
.Xr X509_load_cert_crl_file 3
and
.Xr X509_load_cert_file 3
.It
.Xr X509_LOOKUP_by_subject 3
and
.Xr X509_LOOKUP_ctrl 3
.It
.Xr X509_NAME_hash 3
.It
.Xr X509_new 3
.It
.Xr X509_REQ_new 3
and
.Xr X509_REQ_verify 3
.It
.Xr X509_STORE_CTX_new 3 ,
.Xr X509_STORE_set_default_paths 3 ,
.Xr X509_STORE_load_file 3 ,
.Xr X509_STORE_load_locations 3
and
.Xr X509_STORE_load_store 3
.El
.Pp
.No New functions that use a Library context
.Pp
The following functions can be passed a library context if required.
Passing NULL will use the default library context.
.Bl -bullet
.It
.Xr BIO_new_from_core_bio 3
.It
.Xr EVP_ASYM_CIPHER_fetch 3
and
.Xr EVP_ASYM_CIPHER_do_all_provided 3
.It
.Xr EVP_CIPHER_fetch 3
and
.Xr EVP_CIPHER_do_all_provided 3
.It
.Xr EVP_default_properties_enable_fips 3
and
.Xr EVP_default_properties_is_fips_enabled 3
.It
.Xr EVP_KDF_fetch 3
and
.Xr EVP_KDF_do_all_provided 3
.It
.Xr EVP_KEM_fetch 3
and
.Xr EVP_KEM_do_all_provided 3
.It
.Xr EVP_KEYEXCH_fetch 3
and
.Xr EVP_KEYEXCH_do_all_provided 3
.It
.Xr EVP_KEYMGMT_fetch 3
and
.Xr EVP_KEYMGMT_do_all_provided 3
.It
.Xr EVP_MAC_fetch 3
and
.Xr EVP_MAC_do_all_provided 3
.It
.Xr EVP_MD_fetch 3
and
.Xr EVP_MD_do_all_provided 3
.It
.Xr EVP_PKEY_CTX_new_from_pkey 3
.It
.Xr EVP_PKEY_Q_keygen 3
.It
.Xr EVP_Q_mac 3
and
.Xr EVP_Q_digest 3
.It
.Xr EVP_RAND 3
and
.Xr EVP_RAND_do_all_provided 3
.It
.Xr EVP_set_default_properties 3
.It
.Xr EVP_SIGNATURE_fetch 3
and
.Xr EVP_SIGNATURE_do_all_provided 3
.It
.Xr OSSL_CMP_CTX_new 3
and
.Xr OSSL_CMP_SRV_CTX_new 3
.It
.Xr OSSL_CRMF_ENCRYPTEDVALUE_get1_encCert 3
.It
.Xr OSSL_CRMF_MSG_create_popo 3
and
.Xr OSSL_CRMF_MSGS_verify_popo 3
.It
.Xr OSSL_CRMF_pbm_new 3
and
.Xr OSSL_CRMF_pbmp_new 3
.It
.Xr OSSL_DECODER_CTX_add_extra 3
and
.Xr OSSL_DECODER_CTX_new_for_pkey 3
.It
.Xr OSSL_DECODER_fetch 3
and
.Xr OSSL_DECODER_do_all_provided 3
.It
.Xr OSSL_ENCODER_CTX_add_extra 3
.It
.Xr OSSL_ENCODER_fetch 3
and
.Xr OSSL_ENCODER_do_all_provided 3
.It
.Xr OSSL_LIB_CTX_free 3 ,
.Xr OSSL_LIB_CTX_load_config 3
and
.Xr OSSL_LIB_CTX_set0_default 3
.It
.Xr OSSL_PROVIDER_add_builtin 3 ,
.Xr OSSL_PROVIDER_available 3 ,
.Xr OSSL_PROVIDER_do_all 3 ,
.Xr OSSL_PROVIDER_load 3 ,
.Xr OSSL_PROVIDER_set_default_search_path 3
and
.Xr OSSL_PROVIDER_try_load 3
.It
.Xr OSSL_SELF_TEST_get_callback 3
and
.Xr OSSL_SELF_TEST_set_callback 3
.It
.Xr OSSL_STORE_attach 3
.It
.Xr OSSL_STORE_LOADER_fetch 3
and
.Xr OSSL_STORE_LOADER_do_all_provided 3
.It
.Xr RAND_get0_primary 3 ,
.Xr RAND_get0_private 3 ,
.Xr RAND_get0_public 3 ,
.Xr RAND_set_DRBG_type 3
and
.Xr RAND_set_seed_source_type 3
.El
.Pp
.Em Providers
.Pp
Providers are described in detail here
.Xr crypto 7 .
See also
.Xr crypto 7 .
.Pp
.Em Fetching algorithms and property queries
.Pp
Implicit and Explicit Fetching is described in detail here
.Xr crypto 7 .
.Pp
.Em Mapping EVP controls and flags to provider Xr OSSL_PARAM 3 No parameters
.Pp
The existing functions for controls (such as
.Xr EVP_CIPHER_CTX_ctrl 3 )
and manipulating flags (such as
.Xr EVP_MD_CTX_set_flags 3 Ns )internally
use
.Sy OSSL_PARAMS
to pass information to/from provider objects.
See
.Xr OSSL_PARAM 3
for additional information related to parameters.
.Pp
For ciphers see
.Xr EVP_EncryptInit 3 ,
.Xr EVP_EncryptInit 3
and
.Xr EVP_EncryptInit 3 .
.Pp
For digests see
.Xr EVP_DigestInit 3 ,
.Xr EVP_DigestInit 3
and
.Xr EVP_DigestInit 3 .
.Pp
.Em Deprecation of Low Level Functions
.Pp
A significant number of APIs have been deprecated in OpenSSL 3.0. This
section describes some common categories of deprecations.
See
.Sx Deprecated function mappings
for the list of deprecated functions that refer to these categories.
.Pp
.No Providers are a replacement for engines and low-level method overrides
.Pp
Any accessor that uses an ENGINE is deprecated (such as
.Xr EVP_PKEY_set1_engine 3 ) .
Applications using engines should instead use providers.
.Pp
Before providers were added algorithms were overridden by changing the
methods used by algorithms.
All these methods such as
.Xr RSA_new_method 3
and
.Xr RSA_meth_new 3
are now deprecated and can be replaced by using providers instead.
.Pp
.No Deprecated i2d and d2i functions for low-level key types
.Pp
Any i2d and d2i functions such as
.Xr d2i_DHparams 3
that take a low-level key type have been deprecated.
Applications should instead use the
.Xr OSSL_DECODER 3
and
.Xr OSSL_ENCODER 3
APIs to read and write files.
See
.Xr d2i_RSAPrivateKey 3
for further details.
.Pp
.No Deprecated low-level key object getters and setters
.Pp
Applications that set or get low-level key objects (such as
.Xr EVP_PKEY_set1_DH 3
or
.Xr EVP_PKEY_get0 3 )
should instead use the OSSL_ENCODER (See
.Xr OSSL_ENCODER_to_bio 3 )
or OSSL_DECODER (See
.Xr OSSL_DECODER_from_bio 3 )
APIs, or alternatively use
.Xr EVP_PKEY_fromdata 3
or
.Xr EVP_PKEY_todata 3 .
.Pp
.No Deprecated low-level key parameter getters
.Pp
Functions that access low-level objects directly such as
.Xr RSA_get0_n 3
are now deprecated.
Applications should use one of:
.Xr EVP_PKEY_get_bn_param 3 ,
.Xr EVP_PKEY_get_int_param 3 ,
.Xr EVP_PKEY_get_size_t_param 3 ,
.Xr EVP_PKEY_get_utf8_string_param 3 ,
.Xr EVP_PKEY_get_octet_string_param 3 ,
or
.Xr EVP_PKEY_get_params 3 ,
to access fields from an EVP_PKEY. Gettable parameters are listed in:
.Xr EVP_PKEY-RSA 7 ,
.Xr EVP_PKEY-EC 7 ,
.Xr EVP_PKEY-DSA 7 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-FFC 7 ,
.Xr EVP_PKEY-X25519 7 ,
.Xr EVP_PKEY-ML-DSA 7 ,
and
.Xr EVP_PKEY-ML-KEM 7 .
Applications may also use
.Xr EVP_PKEY_todata 3
to return all fields.
.Pp
.No Deprecated low-level key parameter setters
.Pp
Functions that access low-level objects directly such as
.Xr RSA_set0_crt_params 3
are now deprecated.
Applications should use
.Xr EVP_PKEY_fromdata 3
to create new keys from user provided key data.
Keys should be immutable once they are created, so if required the user
may use
.Xr EVP_PKEY_todata 3 ,
.Xr OSSL_PARAM_merge 3 ,
and
.Xr EVP_PKEY_fromdata 3
to create a modified key.
See
.Xr EVP_PKEY-DH 7
for more information.
See
.Sx Deprecated low-level key generation functions
for information on generating a key using parameters.
.Pp
.No Deprecated low-level object creation
.Pp
Low-level objects were created using methods such as
.Xr RSA_new 3 ,
.Xr RSA_up_ref 3
and
.Xr RSA_free 3 .
Applications should instead use the high-level EVP_PKEY APIs, e.g.
.Xr EVP_PKEY_new 3 ,
.Xr EVP_PKEY_up_ref 3
and
.Xr EVP_PKEY_free 3 .
See also
.Xr EVP_PKEY_CTX_new_from_name 3
and
.Xr EVP_PKEY_CTX_new_from_pkey 3 .
.Pp
EVP_PKEYs may be created in a variety of ways: See also
.Sx Deprecated low-level key generation functions ,
.Sx Deprecated low-level key reading and writing functions
and
.Sx Deprecated low-level key parameter setters .
.Pp
.No Deprecated low-level encryption functions
.Pp
Low-level encryption functions such as
.Xr AES_encrypt 3
and
.Xr AES_decrypt 3
have been informally discouraged from use for a long time.
Applications should instead use the high level EVP APIs
.Xr EVP_EncryptInit_ex 3 ,
.Xr EVP_EncryptUpdate 3 ,
and
.Xr EVP_EncryptFinal_ex 3
or
.Xr EVP_DecryptInit_ex 3 ,
.Xr EVP_DecryptUpdate 3
and
.Xr EVP_DecryptFinal_ex 3 .
.Pp
.No Deprecated low-level digest functions
.Pp
Use of low-level digest functions such as
.Xr SHA1_Init 3
have been informally discouraged from use for a long time.
Applications should instead use the high level EVP APIs
.Xr EVP_DigestInit_ex 3 ,
.Xr EVP_DigestUpdate 3
and
.Xr EVP_DigestFinal_ex 3 ,
or the quick one-shot
.Xr EVP_Q_digest 3 .
.Pp
Note that the functions
.Xr SHA1 3 ,
.Xr SHA224 3 ,
.Xr SHA256 3 ,
.Xr SHA384 3
and
.Xr SHA512 3
have changed to macros that use
.Xr EVP_Q_digest 3 .
.Pp
.No Deprecated low-level signing functions
.Pp
Use of low-level signing functions such as
.Xr DSA_sign 3
have been informally discouraged for a long time.
Instead applications should use
.Xr EVP_DigestSign 3
and
.Xr EVP_DigestVerify 3 .
See also
.Xr EVP_SIGNATURE-RSA 7 ,
.Xr EVP_SIGNATURE-DSA 7 ,
.Xr EVP_SIGNATURE-ECDSA 7
and
.Xr EVP_SIGNATURE-ED25519 7 .
.Pp
.No Deprecated low-level MAC functions
.Pp
Low-level mac functions such as
.Xr CMAC_Init 3
are deprecated.
Applications should instead use the new
.Xr EVP_MAC 3
interface, using
.Xr EVP_MAC_CTX_new 3 ,
.Xr EVP_MAC_CTX_free 3 ,
.Xr EVP_MAC_init 3 ,
.Xr EVP_MAC_update 3
and
.Xr EVP_MAC_final 3
or the single-shot MAC function
.Xr EVP_Q_mac 3 .
See
.Xr EVP_MAC 3 ,
.Xr EVP_MAC-HMAC 7 ,
.Xr EVP_MAC-CMAC 7 ,
.Xr EVP_MAC-GMAC 7 ,
.Xr EVP_MAC-KMAC 7 ,
.Xr EVP_MAC-BLAKE2 7 ,
.Xr EVP_MAC-Poly1305 7
and
.Xr EVP_MAC-Siphash 7
for additional information.
.Pp
Note that the one-shot method
.Xr HMAC 3
is still available for compatibility purposes, but this can also be
replaced by using EVP_Q_MAC if a library context is required.
.Pp
.No Deprecated low-level validation functions
.Pp
Low-level validation functions such as
.Xr DH_check 3
have been informally discouraged from use for a long time.
Applications should instead use the high-level EVP_PKEY APIs such as
.Xr EVP_PKEY_check 3 ,
.Xr EVP_PKEY_param_check 3 ,
.Xr EVP_PKEY_param_check_quick 3 ,
.Xr EVP_PKEY_public_check 3 ,
.Xr EVP_PKEY_public_check_quick 3 ,
.Xr EVP_PKEY_private_check 3 ,
and
.Xr EVP_PKEY_pairwise_check 3 .
.Pp
.No Deprecated low-level key exchange functions
.Pp
Many low-level functions have been informally discouraged from use for a
long time.
Applications should instead use
.Xr EVP_PKEY_derive 3 .
See
.Xr EVP_KEYEXCH-DH 7 ,
.Xr EVP_KEYEXCH-ECDH 7
and
.Xr EVP_KEYEXCH-X25519 7 .
.Pp
.No Deprecated low-level key generation functions
.Pp
Many low-level functions have been informally discouraged from use for a
long time.
Applications should instead use
.Xr EVP_PKEY_keygen_init 3
and
.Xr EVP_PKEY_generate 3
as described in
.Xr EVP_PKEY-DSA 7 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-RSA 7 ,
.Xr EVP_PKEY-EC 7
and
.Xr EVP_PKEY-X25519 7 .
The 'quick' one-shot function
.Xr EVP_PKEY_Q_keygen 3
and macros for the most common cases: <EVP_RSA_gen(3)> and
.Xr EVP_EC_gen 3
may also be used.
.Pp
.No Deprecated low-level key reading and writing functions
.Pp
Use of low-level objects (such as DSA) has been informally discouraged
from use for a long time.
Functions to read and write these low-level objects (such as
.Xr PEM_read_DSA_PUBKEY 3 )
should be replaced.
Applications should instead use
.Xr OSSL_ENCODER_to_bio 3
and
.Xr OSSL_DECODER_from_bio 3 .
.Pp
.No Deprecated low-level key printing functions
.Pp
Use of low-level objects (such as DSA) has been informally discouraged
from use for a long time.
Functions to print these low-level objects such as
.Xr DSA_print 3
should be replaced with the equivalent EVP_PKEY functions.
Application should use one of
.Xr EVP_PKEY_print_public 3 ,
.Xr EVP_PKEY_print_private 3 ,
.Xr EVP_PKEY_print_params 3 ,
.Xr EVP_PKEY_print_public_fp 3 ,
.Xr EVP_PKEY_print_private_fp 3
or
.Xr EVP_PKEY_print_params_fp 3 .
Note that internally these use
.Xr OSSL_ENCODER_to_bio 3
and
.Xr OSSL_DECODER_from_bio 3 .
.Pp
.Em Deprecated function mappings
.Pp
The following functions have been deprecated in 3.0.
.Bl -bullet
.It
.Xr AES_bi_ige_encrypt 3
and
.Xr AES_ige_encrypt 3
.Pp
There is no replacement for the IGE functions.
New code should not use these modes.
These undocumented functions were never integrated into the EVP layer.
They implemented the AES Infinite Garble Extension (IGE) mode and AES
Bi-directional IGE mode.
These modes were never formally standardised and usage of these
functions is believed to be very small.
In particular
.Xr AES_bi_ige_encrypt 3
has a known bug.
It accepts 2 AES keys, but only one is ever used.
The security implications are believed to be minimal, but this issue was
never fixed for backwards compatibility reasons.
.It
.Xr AES_encrypt 3 ,
.Xr AES_decrypt 3 ,
.Xr AES_set_encrypt_key 3 ,
.Xr AES_set_decrypt_key 3 ,
.Xr AES_cbc_encrypt 3 ,
.Xr AES_cfb128_encrypt 3 ,
.Xr AES_cfb1_encrypt 3 ,
.Xr AES_cfb8_encrypt 3 ,
.Xr AES_ecb_encrypt 3 ,
.Xr AES_ofb128_encrypt 3
.It
.Xr AES_unwrap_key 3 ,
.Xr AES_wrap_key 3
.Pp
See
.Sx Deprecated low-level encryption functions
.It
.Xr AES_options 3
.Pp
There is no replacement.
It returned a string indicating if the AES code was unrolled.
.It
.Xr ASN1_digest 3 ,
.Xr ASN1_sign 3 ,
.Xr ASN1_verify 3
.Pp
There are no replacements.
These old functions are not used, and could be disabled with the macro
NO_ASN1_OLD since OpenSSL 0.9.7.
.It
.Xr ASN1_STRING_length_set 3
.Pp
Use
.Xr ASN1_STRING_set 3
or
.Xr ASN1_STRING_set0 3
instead.
This was a potentially unsafe function that could change the bounds of a
previously passed in pointer.
.It
.Xr BF_encrypt 3 ,
.Xr BF_decrypt 3 ,
.Xr BF_set_key 3 ,
.Xr BF_cbc_encrypt 3 ,
.Xr BF_cfb64_encrypt 3 ,
.Xr BF_ecb_encrypt 3 ,
.Xr BF_ofb64_encrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions .
The Blowfish algorithm has been moved to the
.Sx Legacy Algorithms .
.It
.Xr BF_options 3
.Pp
There is no replacement.
This option returned a constant string.
.It
.Xr BIO_get_callback 3 ,
.Xr BIO_set_callback 3 ,
.Xr BIO_debug_callback 3
.Pp
Use the respective non-deprecated
.Xr _ex 3
functions.
.It
.Xr BN_is_prime_ex 3 ,
.Xr BN_is_prime_fasttest_ex 3
.Pp
Use
.Xr BN_check_prime 3
which avoids possible misuse and always uses at least 64 rounds of the
Miller-Rabin primality test.
.It
.Xr BN_pseudo_rand 3 ,
.Xr BN_pseudo_rand_range 3
.Pp
Use
.Xr BN_rand 3
and
.Xr BN_rand_range 3 .
.It
.Xr BN_X931_derive_prime_ex 3 ,
.Xr BN_X931_generate_prime_ex 3 ,
.Xr BN_X931_generate_Xpq 3
.Pp
There are no replacements for these low-level functions.
They were used internally by
.Xr RSA_X931_derive_ex 3
and
.Xr RSA_X931_generate_key_ex 3
which are also deprecated.
Use
.Xr EVP_PKEY_keygen 3
instead.
.It
.Xr Camellia_encrypt 3 ,
.Xr Camellia_decrypt 3 ,
.Xr Camellia_set_key 3 ,
.Xr Camellia_cbc_encrypt 3 ,
.Xr Camellia_cfb128_encrypt 3 ,
.Xr Camellia_cfb1_encrypt 3 ,
.Xr Camellia_cfb8_encrypt 3 ,
.Xr Camellia_ctr128_encrypt 3 ,
.Xr Camellia_ecb_encrypt 3 ,
.Xr Camellia_ofb128_encrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions .
.It
.Xr CAST_encrypt 3 ,
.Xr CAST_decrypt 3 ,
.Xr CAST_set_key 3 ,
.Xr CAST_cbc_encrypt 3 ,
.Xr CAST_cfb64_encrypt 3 ,
.Xr CAST_ecb_encrypt 3 ,
.Xr CAST_ofb64_encrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions .
The CAST algorithm has been moved to the
.Sx Legacy Algorithms .
.It
.Xr CMAC_CTX_new 3 ,
.Xr CMAC_CTX_cleanup 3 ,
.Xr CMAC_CTX_copy 3 ,
.Xr CMAC_CTX_free 3 ,
.Xr CMAC_CTX_get0_cipher_ctx 3
.Pp
See
.Sx Deprecated low-level MAC functions .
.It
.Xr CMAC_Init 3 ,
.Xr CMAC_Update 3 ,
.Xr CMAC_Final 3 ,
.Xr CMAC_resume 3
.Pp
See
.Sx Deprecated low-level MAC functions .
.It
.Xr CRYPTO_mem_ctrl 3 ,
.Xr CRYPTO_mem_debug_free 3 ,
.Xr CRYPTO_mem_debug_malloc 3 ,
.Xr CRYPTO_mem_debug_pop 3 ,
.Xr CRYPTO_mem_debug_push 3 ,
.Xr CRYPTO_mem_debug_realloc 3 ,
.Xr CRYPTO_mem_leaks 3 ,
.Xr CRYPTO_mem_leaks_cb 3 ,
.Xr CRYPTO_mem_leaks_fp 3 ,
.Xr CRYPTO_set_mem_debug 3
.Pp
Memory-leak checking has been deprecated in favor of more modern
development tools, such as compiler memory and leak sanitizers or
Valgrind.
.It
.Xr CRYPTO_cts128_encrypt_block 3 ,
.Xr CRYPTO_cts128_encrypt 3 ,
.Xr CRYPTO_cts128_decrypt_block 3 ,
.Xr CRYPTO_cts128_decrypt 3 ,
.Xr CRYPTO_nistcts128_encrypt_block 3 ,
.Xr CRYPTO_nistcts128_encrypt 3 ,
.Xr CRYPTO_nistcts128_decrypt_block 3 ,
.Xr CRYPTO_nistcts128_decrypt 3
.Pp
Use the higher level functions
.Xr EVP_CipherInit_ex2 3 ,
.Xr EVP_CipherUpdate 3
and
.Xr EVP_CipherFinal_ex 3
instead.
See the "cts_mode" parameter in
.Xr EVP_EncryptInit 3 .
See
.Xr EVP_EncryptInit 3
for a AES-256-CBC-CTS example.
.It
.Xr d2i_DHparams 3 ,
.Xr d2i_DHxparams 3 ,
.Xr d2i_DSAparams 3 ,
.Xr d2i_DSAPrivateKey 3 ,
.Xr d2i_DSAPrivateKey_bio 3 ,
.Xr d2i_DSAPrivateKey_fp 3 ,
.Xr d2i_DSA_PUBKEY 3 ,
.Xr d2i_DSA_PUBKEY_bio 3 ,
.Xr d2i_DSA_PUBKEY_fp 3 ,
.Xr d2i_DSAPublicKey 3 ,
.Xr d2i_ECParameters 3 ,
.Xr d2i_ECPrivateKey 3 ,
.Xr d2i_ECPrivateKey_bio 3 ,
.Xr d2i_ECPrivateKey_fp 3 ,
.Xr d2i_EC_PUBKEY 3 ,
.Xr d2i_EC_PUBKEY_bio 3 ,
.Xr d2i_EC_PUBKEY_fp 3 ,
.Xr d2i_RSAPrivateKey 3 ,
.Xr d2i_RSAPrivateKey_bio 3 ,
.Xr d2i_RSAPrivateKey_fp 3 ,
.Xr d2i_RSA_PUBKEY 3 ,
.Xr d2i_RSA_PUBKEY_bio 3 ,
.Xr d2i_RSA_PUBKEY_fp 3 ,
.Xr d2i_RSAPublicKey 3 ,
.Xr d2i_RSAPublicKey_bio 3 ,
.Xr d2i_RSAPublicKey_fp 3
.Pp
See
.Sx Deprecated i2d and d2i functions for low-level key types
.It
.Xr o2i_ECPublicKey 3
.Pp
Use
.Xr EVP_PKEY_set1_encoded_public_key 3 .
See
.Sx Deprecated low-level key parameter setters
.It
.Xr DES_crypt 3 ,
.Xr DES_fcrypt 3 ,
.Xr DES_encrypt1 3 ,
.Xr DES_encrypt2 3 ,
.Xr DES_encrypt3 3 ,
.Xr DES_decrypt3 3 ,
.Xr DES_ede3_cbc_encrypt 3 ,
.Xr DES_ede3_cfb64_encrypt 3 ,
.Xr DES_ede3_cfb_encrypt(),DES_ede3_ofb64_encrypt 3 ,
.Xr DES_ecb_encrypt 3 ,
.Xr DES_ecb3_encrypt 3 ,
.Xr DES_ofb64_encrypt 3 ,
.Xr DES_ofb_encrypt 3 ,
DES_cfb64_encrypt
.Xr DES_cfb_encrypt 3 ,
.Xr DES_cbc_encrypt 3 ,
.Xr DES_ncbc_encrypt 3 ,
.Xr DES_pcbc_encrypt 3 ,
.Xr DES_xcbc_encrypt 3 ,
.Xr DES_cbc_cksum 3 ,
.Xr DES_quad_cksum 3 ,
.Xr DES_check_key_parity 3 ,
.Xr DES_is_weak_key 3 ,
.Xr DES_key_sched 3 ,
.Xr DES_options 3 ,
.Xr DES_random_key 3 ,
.Xr DES_set_key 3 ,
.Xr DES_set_key_checked 3 ,
.Xr DES_set_key_unchecked 3 ,
.Xr DES_set_odd_parity 3 ,
.Xr DES_string_to_2keys 3 ,
.Xr DES_string_to_key 3
.Pp
See
.Sx Deprecated low-level encryption functions .
Algorithms for "DESX-CBC", "DES-ECB", "DES-CBC", "DES-OFB", "DES-CFB",
"DES-CFB1" and "DES-CFB8" have been moved to the
.Sx Legacy Algorithms .
.It
.Xr DH_bits 3 ,
.Xr DH_security_bits 3 ,
.Xr DH_size 3
.Pp
Use
.Xr EVP_PKEY_get_bits 3 ,
.Xr EVP_PKEY_get_security_bits 3
and
.Xr EVP_PKEY_get_size 3 .
.It
.Xr DH_check 3 ,
.Xr DH_check_ex 3 ,
.Xr DH_check_params 3 ,
.Xr DH_check_params_ex 3 ,
.Xr DH_check_pub_key 3 ,
.Xr DH_check_pub_key_ex 3
.Pp
See
.Sx Deprecated low-level validation functions
.It
.Xr DH_clear_flags 3 ,
.Xr DH_test_flags 3 ,
.Xr DH_set_flags 3
.Pp
The
.Sy DH_FLAG_CACHE_MONT_P
flag has been deprecated without replacement.
The
.Sy DH_FLAG_TYPE_DH
and
.Sy DH_FLAG_TYPE_DHX
have been deprecated.
Use
.Xr EVP_PKEY_is_a 3
to determine the type of a key.
There is no replacement for setting these flags.
.It
.Xr DH_compute_key 3
.Xr DH_compute_key_padded 3
.Pp
See
.Sx Deprecated low-level key exchange functions .
.It
.Xr DH_new 3 ,
.Xr DH_new_by_nid 3 ,
.Xr DH_free 3 ,
.Xr DH_up_ref 3
.Pp
See
.Sx Deprecated low-level object creation
.It
.Xr DH_generate_key 3 ,
.Xr DH_generate_parameters_ex 3
.Pp
See
.Sx Deprecated low-level key generation functions .
.It
.Xr DH_get0_pqg 3 ,
.Xr DH_get0_p 3 ,
.Xr DH_get0_q 3 ,
.Xr DH_get0_g 3 ,
.Xr DH_get0_key 3 ,
.Xr DH_get0_priv_key 3 ,
.Xr DH_get0_pub_key 3 ,
.Xr DH_get_length 3 ,
.Xr DH_get_nid 3
.Pp
See
.Sx Deprecated low-level key parameter getters
.It
.Xr DH_get_1024_160 3 ,
.Xr DH_get_2048_224 3 ,
.Xr DH_get_2048_256 3
.Pp
Applications should instead set the
.Sy OSSL_PKEY_PARAM_GROUP_NAME
as specified in
.Xr EVP_PKEY-DH 7 )
to one of "dh_1024_160", "dh_2048_224" or "dh_2048_256" when generating
a DH key.
.It
.Xr DH_KDF_X9_42 3
.Pp
Applications should use
.Xr EVP_PKEY_CTX_set_dh_kdf_type 3
instead.
.It
.Xr DH_get_default_method 3 ,
.Xr DH_get0_engine 3 ,
.Xr DH_meth_* 3 ,
.Xr DH_new_method 3 ,
.Xr DH_OpenSSL 3 ,
.Xr DH_get_ex_data 3 ,
.Xr DH_set_default_method 3 ,
.Xr DH_set_method 3 ,
.Xr DH_set_ex_data 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides
.It
.Xr DHparams_print 3 ,
.Xr DHparams_print_fp 3
.Pp
See
.Sx Deprecated low-level key printing functions
.It
.Xr DH_set0_key 3 ,
.Xr DH_set0_pqg 3 ,
.Xr DH_set_length 3
.Pp
See
.Sx Deprecated low-level key parameter setters
.It
.Xr DSA_bits 3 ,
.Xr DSA_security_bits 3 ,
.Xr DSA_size 3
.Pp
Use
.Xr EVP_PKEY_get_bits 3 ,
.Xr EVP_PKEY_get_security_bits 3
and
.Xr EVP_PKEY_get_size 3 .
.It
.Xr DHparams_dup 3 ,
.Xr DSA_dup_DH 3
.Pp
There is no direct replacement.
Applications may use
.Xr EVP_PKEY_copy_parameters 3
and
.Xr EVP_PKEY_dup 3
instead.
.It
.Xr DSA_generate_key 3 ,
.Xr DSA_generate_parameters_ex 3
.Pp
See
.Sx Deprecated low-level key generation functions .
.It
.Xr DSA_get0_engine 3 ,
.Xr DSA_get_default_method 3 ,
.Xr DSA_get_ex_data 3 ,
.Xr DSA_get_method 3 ,
.Xr DSA_meth_* 3 ,
.Xr DSA_new_method 3 ,
.Xr DSA_OpenSSL 3 ,
.Xr DSA_set_default_method 3 ,
.Xr DSA_set_ex_data 3 ,
.Xr DSA_set_method 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Xr DSA_get0_p 3 ,
.Xr DSA_get0_q 3 ,
.Xr DSA_get0_g 3 ,
.Xr DSA_get0_pqg 3 ,
.Xr DSA_get0_key 3 ,
.Xr DSA_get0_priv_key 3 ,
.Xr DSA_get0_pub_key 3
.Pp
See
.Sx Deprecated low-level key parameter getters .
.It
.Xr DSA_new 3 ,
.Xr DSA_free 3 ,
.Xr DSA_up_ref 3
.Pp
See
.Sx Deprecated low-level object creation
.It
.Xr DSAparams_dup 3
.Pp
There is no direct replacement.
Applications may use
.Xr EVP_PKEY_copy_parameters 3
and
.Xr EVP_PKEY_dup 3
instead.
.It
.Xr DSAparams_print 3 ,
.Xr DSAparams_print_fp 3 ,
.Xr DSA_print 3 ,
.Xr DSA_print_fp 3
.Pp
See
.Sx Deprecated low-level key printing functions
.It
.Xr DSA_set0_key 3 ,
.Xr DSA_set0_pqg 3
.Pp
See
.Sx Deprecated low-level key parameter setters
.It
.Xr DSA_set_flags 3 ,
.Xr DSA_clear_flags 3 ,
.Xr DSA_test_flags 3
.Pp
The
.Sy DSA_FLAG_CACHE_MONT_P
flag has been deprecated without replacement.
.It
.Xr DSA_sign 3 ,
.Xr DSA_do_sign 3 ,
.Xr DSA_sign_setup 3 ,
.Xr DSA_verify 3 ,
.Xr DSA_do_verify 3
.Pp
See
.Sx Deprecated low-level signing functions .
.It
.Xr ECDH_compute_key 3
.Pp
See
.Sx Deprecated low-level key exchange functions .
.It
.Xr ECDH_KDF_X9_62 3
.Pp
Applications may either set this using the helper function
.Xr EVP_PKEY_CTX_set_ecdh_kdf_type 3
or by setting an
.Xr OSSL_PARAM 3
using the "kdf-type" as shown in
.Xr EVP_KEYEXCH-ECDH 7
.It
.Xr ECDSA_sign 3 ,
.Xr ECDSA_sign_ex 3 ,
.Xr ECDSA_sign_setup 3 ,
.Xr ECDSA_do_sign 3 ,
.Xr ECDSA_do_sign_ex 3 ,
.Xr ECDSA_verify 3 ,
.Xr ECDSA_do_verify 3
.Pp
See
.Sx Deprecated low-level signing functions .
.It
.Xr ECDSA_size 3
.Pp
Applications should use
.Xr EVP_PKEY_get_size 3 .
.It
.Xr EC_GF2m_simple_method 3 ,
.Xr EC_GFp_mont_method 3 ,
.Xr EC_GFp_nist_method 3 ,
.Xr EC_GFp_nistp224_method 3 ,
.Xr EC_GFp_nistp256_method 3 ,
.Xr EC_GFp_nistp521_method 3 ,
.Xr EC_GFp_simple_method 3
.Pp
There are no replacements for these functions.
Applications should rely on the library automatically assigning a
suitable method internally when an EC_GROUP is constructed.
.It
.Xr EC_GROUP_clear_free 3
.Pp
Use
.Xr EC_GROUP_free 3
instead.
.It
.Xr EC_GROUP_get_curve_GF2m 3 ,
.Xr EC_GROUP_get_curve_GFp 3 ,
.Xr EC_GROUP_set_curve_GF2m 3 ,
.Xr EC_GROUP_set_curve_GFp 3
.Pp
Applications should use
.Xr EC_GROUP_get_curve 3
and
.Xr EC_GROUP_set_curve 3 .
.It
.Xr EC_GROUP_have_precompute_mult 3 ,
.Xr EC_GROUP_precompute_mult 3 ,
.Xr EC_KEY_precompute_mult 3
.Pp
These functions are not widely used.
Applications should instead switch to named curves which OpenSSL has
hardcoded lookup tables for.
.It
.Xr EC_GROUP_new 3 ,
.Xr EC_GROUP_method_of 3 ,
.Xr EC_POINT_method_of 3
.Pp
EC_METHOD is now an internal-only concept and a suitable EC_METHOD is
assigned internally without application intervention.
Users of
.Xr EC_GROUP_new 3
should switch to a different suitable constructor.
.It
.Xr EC_KEY_can_sign 3
.Pp
Applications should use
.Xr EVP_PKEY_can_sign 3
instead.
.It
.Xr EC_KEY_check_key 3
.Pp
See
.Sx Deprecated low-level validation functions
.It
.Xr EC_KEY_set_flags 3 ,
.Xr EC_KEY_get_flags 3 ,
.Xr EC_KEY_clear_flags 3
.Pp
See
.Xr EVP_PKEY-EC 7
which handles flags as separate parameters for
.Sy OSSL_PKEY_PARAM_EC_POINT_CONVERSION_FORMAT ,
.Sy OSSL_PKEY_PARAM_EC_GROUP_CHECK_TYPE ,
.Sy OSSL_PKEY_PARAM_EC_ENCODING ,
.Sy OSSL_PKEY_PARAM_USE_COFACTOR_ECDH
and
.Sy OSSL_PKEY_PARAM_EC_INCLUDE_PUBLIC .
See also
.Xr EVP_PKEY-EC 7
.It
.Xr EC_KEY_dup 3 ,
.Xr EC_KEY_copy 3
.Pp
There is no direct replacement.
Applications may use
.Xr EVP_PKEY_copy_parameters 3
and
.Xr EVP_PKEY_dup 3
instead.
.It
.Xr EC_KEY_decoded_from_explicit_params 3
.Pp
There is no replacement.
.It
.Xr EC_KEY_generate_key 3
.Pp
See
.Sx Deprecated low-level key generation functions .
.It
.Xr EC_KEY_get0_group 3 ,
.Xr EC_KEY_get0_private_key 3 ,
.Xr EC_KEY_get0_public_key 3 ,
.Xr EC_KEY_get_conv_form 3 ,
.Xr EC_KEY_get_enc_flags 3
.Pp
See
.Sx Deprecated low-level key parameter getters .
.It
.Xr EC_KEY_get0_engine 3 ,
.Xr EC_KEY_get_default_method 3 ,
.Xr EC_KEY_get_method 3 ,
.Xr EC_KEY_new_method 3 ,
.Xr EC_KEY_get_ex_data 3 ,
.Xr EC_KEY_OpenSSL 3 ,
.Xr EC_KEY_set_ex_data 3 ,
.Xr EC_KEY_set_default_method 3 ,
.Xr EC_KEY_METHOD_* 3 ,
.Xr EC_KEY_set_method 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides
.It
.Xr EC_METHOD_get_field_type 3
.Pp
Use
.Xr EC_GROUP_get_field_type 3
instead.
See
.Sx Providers are a replacement for engines and low-level method overrides
.It
.Xr EC_KEY_key2buf 3 ,
.Xr EC_KEY_oct2key 3 ,
.Xr EC_KEY_oct2priv 3 ,
.Xr EC_KEY_priv2buf 3 ,
.Xr EC_KEY_priv2oct 3
.Pp
There are no replacements for these.
.It
.Xr EC_KEY_new 3 ,
.Xr EC_KEY_new_by_curve_name 3 ,
.Xr EC_KEY_free 3 ,
.Xr EC_KEY_up_ref 3
.Pp
See
.Sx Deprecated low-level object creation
.It
.Xr EC_KEY_print 3 ,
.Xr EC_KEY_print_fp 3
.Pp
See
.Sx Deprecated low-level key printing functions
.It
.Xr EC_KEY_set_asn1_flag 3 ,
.Xr EC_KEY_set_conv_form 3 ,
.Xr EC_KEY_set_enc_flags 3
.Pp
See
.Sx Deprecated low-level key parameter setters .
.It
.Xr EC_KEY_set_group 3 ,
.Xr EC_KEY_set_private_key 3 ,
.Xr EC_KEY_set_public_key 3 ,
.Xr EC_KEY_set_public_key_affine_coordinates 3
.Pp
See
.Sx Deprecated low-level key parameter setters .
.It
.Xr ECParameters_print 3 ,
.Xr ECParameters_print_fp 3 ,
.Xr ECPKParameters_print 3 ,
.Xr ECPKParameters_print_fp 3
.Pp
See
.Sx Deprecated low-level key printing functions
.It
.Xr EC_POINT_bn2point 3 ,
.Xr EC_POINT_point2bn 3
.Pp
These functions were not particularly useful, since EC point
serialization formats are not individual big-endian integers.
.It
.Xr EC_POINT_get_affine_coordinates_GF2m 3 ,
.Xr EC_POINT_get_affine_coordinates_GFp 3 ,
.Xr EC_POINT_set_affine_coordinates_GF2m 3 ,
.Xr EC_POINT_set_affine_coordinates_GFp 3
.Pp
Applications should use
.Xr EC_POINT_get_affine_coordinates 3
and
.Xr EC_POINT_set_affine_coordinates 3
instead.
.It
.Xr EC_POINT_get_Jprojective_coordinates_GFp 3 ,
.Xr EC_POINT_set_Jprojective_coordinates_GFp 3
.Pp
These functions are not widely used.
Applications should instead use the
.Xr EC_POINT_set_affine_coordinates 3
and
.Xr EC_POINT_get_affine_coordinates 3
functions.
.It
.Xr EC_POINT_make_affine 3 ,
.Xr EC_POINTs_make_affine 3
.Pp
There is no replacement.
These functions were not widely used, and OpenSSL automatically performs
this conversion when needed.
.It
.Xr EC_POINT_set_compressed_coordinates_GF2m 3 ,
.Xr EC_POINT_set_compressed_coordinates_GFp 3
.Pp
Applications should use
.Xr EC_POINT_set_compressed_coordinates 3
instead.
.It
.Xr EC_POINTs_mul 3
.Pp
This function is not widely used.
Applications should instead use the
.Xr EC_POINT_mul 3
function.
.It
.Sy ENGINE_*()
.Pp
All engine functions are deprecated.
An engine should be rewritten as a provider.
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Sy ERR_load_*() ,
.Xr ERR_func_error_string 3 ,
.Xr ERR_get_error_line 3 ,
.Xr ERR_get_error_line_data 3 ,
.Xr ERR_get_state 3
.Pp
OpenSSL now loads error strings automatically so these functions are not
needed.
.It
.Xr ERR_peek_error_line_data 3 ,
.Xr ERR_peek_last_error_line_data 3
.Pp
The new functions are
.Xr ERR_peek_error_func 3 ,
.Xr ERR_peek_last_error_func 3 ,
.Xr ERR_peek_error_data 3 ,
.Xr ERR_peek_last_error_data 3 ,
.Xr ERR_get_error_all 3 ,
.Xr ERR_peek_error_all 3
and
.Xr ERR_peek_last_error_all 3 .
Applications should use
.Xr ERR_get_error_all 3 ,
or pick information with ERR_peek functions and finish off with getting
the error code by using
.Xr ERR_get_error 3 .
.It
.Xr EVP_CIPHER_CTX_iv 3 ,
.Xr EVP_CIPHER_CTX_iv_noconst 3 ,
.Xr EVP_CIPHER_CTX_original_iv 3
.Pp
Applications should instead use
.Xr EVP_CIPHER_CTX_get_updated_iv 3 ,
.Xr EVP_CIPHER_CTX_get_updated_iv 3
and
.Xr EVP_CIPHER_CTX_get_original_iv 3
respectively.
See
.Xr EVP_CIPHER_CTX_get_original_iv 3
for further information.
.It
.Sy EVP_CIPHER_meth_*() ,
.Xr EVP_MD_CTX_set_update_fn 3 ,
.Xr EVP_MD_CTX_update_fn 3 ,
.Sy EVP_MD_meth_*()
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Xr EVP_PKEY_CTRL_PKCS7_ENCRYPT 3 ,
.Xr EVP_PKEY_CTRL_PKCS7_DECRYPT 3 ,
.Xr EVP_PKEY_CTRL_PKCS7_SIGN 3 ,
.Xr EVP_PKEY_CTRL_CMS_ENCRYPT 3 ,
.Xr EVP_PKEY_CTRL_CMS_DECRYPT 3 ,
and
.Xr EVP_PKEY_CTRL_CMS_SIGN 3
.Pp
These control operations are not invoked by the OpenSSL library anymore
and are replaced by direct checks of the key operation against the key
type when the operation is initialized.
.It
.Xr EVP_PKEY_CTX_get0_dh_kdf_ukm 3 ,
.Xr EVP_PKEY_CTX_get0_ecdh_kdf_ukm 3
.Pp
See the "kdf-ukm" item in
.Xr EVP_KEYEXCH-DH 7
and
.Xr EVP_KEYEXCH-ECDH 7 .
These functions are obsolete and should not be required.
.It
.Xr EVP_PKEY_CTX_set_rsa_keygen_pubexp 3
.Pp
Applications should use
.Xr EVP_PKEY_CTX_set1_rsa_keygen_pubexp 3
instead.
.It
.Xr EVP_PKEY_cmp 3 ,
.Xr EVP_PKEY_cmp_parameters 3
.Pp
Applications should use
.Xr EVP_PKEY_eq 3
and
.Xr EVP_PKEY_parameters_eq 3
instead.
See
.Xr EVP_PKEY_copy_parameters 3
for further details.
.It
.Xr EVP_PKEY_encrypt_old 3 ,
.Xr EVP_PKEY_decrypt_old 3 ,
.Pp
Applications should use
.Xr EVP_PKEY_encrypt_init 3
and
.Xr EVP_PKEY_encrypt 3
or
.Xr EVP_PKEY_decrypt_init 3
and
.Xr EVP_PKEY_decrypt 3
instead.
.It
.Xr EVP_PKEY_get0 3
.Pp
This function returns NULL if the key comes from a provider.
.It
.Xr EVP_PKEY_get0_DH 3 ,
.Xr EVP_PKEY_get0_DSA 3 ,
.Xr EVP_PKEY_get0_EC_KEY 3 ,
.Xr EVP_PKEY_get0_RSA 3 ,
.Xr EVP_PKEY_get1_DH 3 ,
.Xr EVP_PKEY_get1_DSA 3 ,
EVP_PKEY_get1_EC_KEY and
.Xr EVP_PKEY_get1_RSA 3 ,
.Xr EVP_PKEY_get0_hmac 3 ,
.Xr EVP_PKEY_get0_poly1305 3 ,
.Xr EVP_PKEY_get0_siphash 3
.Pp
See
.Sx Functions that return an internal key should be treated as read only .
.It
.Sy EVP_PKEY_meth_*()
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Xr EVP_PKEY_new_CMAC_key 3
.Pp
See
.Sx Deprecated low-level MAC functions .
.It
.Xr EVP_PKEY_assign 3 ,
.Xr EVP_PKEY_set1_DH 3 ,
.Xr EVP_PKEY_set1_DSA 3 ,
.Xr EVP_PKEY_set1_EC_KEY 3 ,
.Xr EVP_PKEY_set1_RSA 3
.Pp
See
.Sx Deprecated low-level key object getters and setters
.It
.Xr EVP_PKEY_set1_tls_encodedpoint 3
.Xr EVP_PKEY_get1_tls_encodedpoint 3
.Pp
These functions were previously used by libssl to set or get an encoded
public key into/from an EVP_PKEY object.
With OpenSSL 3.0 these are replaced by the more generic functions
.Xr EVP_PKEY_set1_encoded_public_key 3
and
.Xr EVP_PKEY_get1_encoded_public_key 3 .
The old versions have been converted to deprecated macros that just call
the new functions.
.It
.Xr EVP_PKEY_set1_engine 3 ,
.Xr EVP_PKEY_get0_engine 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Xr EVP_PKEY_set_alias_type 3
.Pp
This function has been removed.
There is no replacement.
See
.Sx EVP_PKEY_set_alias_type() method has been removed
.It
.Xr HMAC_Init_ex 3 ,
.Xr HMAC_Update 3 ,
.Xr HMAC_Final 3 ,
.Xr HMAC_size 3
.Pp
See
.Sx Deprecated low-level MAC functions .
.It
.Xr HMAC_CTX_new 3 ,
.Xr HMAC_CTX_free 3 ,
.Xr HMAC_CTX_copy 3 ,
.Xr HMAC_CTX_reset 3 ,
.Xr HMAC_CTX_set_flags 3 ,
.Xr HMAC_CTX_get_md 3
.Pp
See
.Sx Deprecated low-level MAC functions .
.It
.Xr i2d_DHparams 3 ,
.Xr i2d_DHxparams 3
.Pp
See
.Sx Deprecated low-level key reading and writing functions
and
.Xr d2i_RSAPrivateKey 3
.It
.Xr i2d_DSAparams 3 ,
.Xr i2d_DSAPrivateKey 3 ,
.Xr i2d_DSAPrivateKey_bio 3 ,
.Xr i2d_DSAPrivateKey_fp 3 ,
.Xr i2d_DSA_PUBKEY 3 ,
.Xr i2d_DSA_PUBKEY_bio 3 ,
.Xr i2d_DSA_PUBKEY_fp 3 ,
.Xr i2d_DSAPublicKey 3
.Pp
See
.Sx Deprecated low-level key reading and writing functions
and
.Xr d2i_RSAPrivateKey 3
.It
.Xr i2d_ECParameters 3 ,
.Xr i2d_ECPrivateKey 3 ,
.Xr i2d_ECPrivateKey_bio 3 ,
.Xr i2d_ECPrivateKey_fp 3 ,
.Xr i2d_EC_PUBKEY 3 ,
.Xr i2d_EC_PUBKEY_bio 3 ,
.Xr i2d_EC_PUBKEY_fp 3
.Pp
See
.Sx Deprecated low-level key reading and writing functions
and
.Xr d2i_RSAPrivateKey 3
.It
.Xr i2o_ECPublicKey 3
.Pp
Use
.Xr EVP_PKEY_get1_encoded_public_key 3 .
See
.Sx Deprecated low-level key parameter getters
.It
.Xr i2d_RSAPrivateKey 3 ,
.Xr i2d_RSAPrivateKey_bio 3 ,
.Xr i2d_RSAPrivateKey_fp 3 ,
.Xr i2d_RSA_PUBKEY 3 ,
.Xr i2d_RSA_PUBKEY_bio 3 ,
.Xr i2d_RSA_PUBKEY_fp 3 ,
.Xr i2d_RSAPublicKey 3 ,
.Xr i2d_RSAPublicKey_bio 3 ,
.Xr i2d_RSAPublicKey_fp 3
.Pp
See
.Sx Deprecated low-level key reading and writing functions
and
.Xr d2i_RSAPrivateKey 3
.It
.Xr IDEA_encrypt 3 ,
.Xr IDEA_set_decrypt_key 3 ,
.Xr IDEA_set_encrypt_key 3 ,
.Xr IDEA_cbc_encrypt 3 ,
.Xr IDEA_cfb64_encrypt 3 ,
.Xr IDEA_ecb_encrypt 3 ,
.Xr IDEA_ofb64_encrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions .
IDEA has been moved to the
.Sx Legacy Algorithms .
.It
.Xr IDEA_options 3
.Pp
There is no replacement.
This function returned a constant string.
.It
.Xr MD2 3 ,
.Xr MD2_Init 3 ,
.Xr MD2_Update 3 ,
.Xr MD2_Final 3
.Pp
See
.Sx Deprecated low-level encryption functions .
MD2 has been moved to the
.Sx Legacy Algorithms .
.It
.Xr MD2_options 3
.Pp
There is no replacement.
This function returned a constant string.
.It
.Xr MD4 3 ,
.Xr MD4_Init 3 ,
.Xr MD4_Update 3 ,
.Xr MD4_Final 3 ,
.Xr MD4_Transform 3
.Pp
See
.Sx Deprecated low-level encryption functions .
MD4 has been moved to the
.Sx Legacy Algorithms .
.It
.Xr MDC2 3 ,
.Xr MDC2_Init 3 ,
.Xr MDC2_Update 3 ,
.Xr MDC2_Final 3
.Pp
See
.Sx Deprecated low-level encryption functions .
MDC2 has been moved to the
.Sx Legacy Algorithms .
.It
.Xr MD5 3 ,
.Xr MD5_Init 3 ,
.Xr MD5_Update 3 ,
.Xr MD5_Final 3 ,
.Xr MD5_Transform 3
.Pp
See
.Sx Deprecated low-level encryption functions .
.It
.Xr NCONF_WIN32 3
.Pp
This undocumented function has no replacement.
See
.Xr config 5
for more details.
.It
.Xr OCSP_parse_url 3
.Pp
Use
.Xr OSSL_HTTP_parse_url 3
instead.
.It
.Sy OCSP_REQ_CTX
type and
.Sy OCSP_REQ_CTX_*()
functions
.Pp
These methods were used to collect all necessary data to form a HTTP
request, and to perform the HTTP transfer with that request.
With OpenSSL 3.0, the type is
.Sy OSSL_HTTP_REQ_CTX ,
and the deprecated functions are replaced with
.Sy OSSL_HTTP_REQ_CTX_*() .
See
.Xr OSSL_HTTP_REQ_CTX 3
for additional details.
.It
.Xr OPENSSL_fork_child 3 ,
.Xr OPENSSL_fork_parent 3 ,
.Xr OPENSSL_fork_prepare 3
.Pp
There is no replacement for these functions.
These pthread fork support methods were unused by OpenSSL.
.It
.Xr OSSL_STORE_ctrl 3 ,
.Xr OSSL_STORE_do_all_loaders 3 ,
.Xr OSSL_STORE_LOADER_get0_engine 3 ,
.Xr OSSL_STORE_LOADER_get0_scheme 3 ,
.Xr OSSL_STORE_LOADER_new 3 ,
.Xr OSSL_STORE_LOADER_set_attach 3 ,
.Xr OSSL_STORE_LOADER_set_close 3 ,
.Xr OSSL_STORE_LOADER_set_ctrl 3 ,
.Xr OSSL_STORE_LOADER_set_eof 3 ,
.Xr OSSL_STORE_LOADER_set_error 3 ,
.Xr OSSL_STORE_LOADER_set_expect 3 ,
.Xr OSSL_STORE_LOADER_set_find 3 ,
.Xr OSSL_STORE_LOADER_set_load 3 ,
.Xr OSSL_STORE_LOADER_set_open 3 ,
.Xr OSSL_STORE_LOADER_set_open_ex 3 ,
.Xr OSSL_STORE_register_loader 3 ,
.Xr OSSL_STORE_unregister_loader 3 ,
.Xr OSSL_STORE_vctrl 3
.Pp
These functions helped applications and engines create loaders for
schemes they supported.
These are all deprecated and discouraged in favour of provider
implementations, see
.Xr provider-storemgmt 7 .
.It
.Xr PEM_read_DHparams 3 ,
.Xr PEM_read_bio_DHparams 3 ,
.Xr PEM_read_DSAparams 3 ,
.Xr PEM_read_bio_DSAparams 3 ,
.Xr PEM_read_DSAPrivateKey 3 ,
.Xr PEM_read_DSA_PUBKEY 3 ,
PEM_read_bio_DSAPrivateKey and
.Xr PEM_read_bio_DSA_PUBKEY 3 ,
.Xr PEM_read_ECPKParameters 3 ,
.Xr PEM_read_ECPrivateKey 3 ,
.Xr PEM_read_EC_PUBKEY 3 ,
.Xr PEM_read_bio_ECPKParameters 3 ,
.Xr PEM_read_bio_ECPrivateKey 3 ,
.Xr PEM_read_bio_EC_PUBKEY 3 ,
.Xr PEM_read_RSAPrivateKey 3 ,
.Xr PEM_read_RSA_PUBKEY 3 ,
.Xr PEM_read_RSAPublicKey 3 ,
.Xr PEM_read_bio_RSAPrivateKey 3 ,
.Xr PEM_read_bio_RSA_PUBKEY 3 ,
.Xr PEM_read_bio_RSAPublicKey 3 ,
.Xr PEM_write_bio_DHparams 3 ,
.Xr PEM_write_bio_DHxparams 3 ,
.Xr PEM_write_DHparams 3 ,
.Xr PEM_write_DHxparams 3 ,
.Xr PEM_write_DSAparams 3 ,
.Xr PEM_write_DSAPrivateKey 3 ,
.Xr PEM_write_DSA_PUBKEY 3 ,
.Xr PEM_write_bio_DSAparams 3 ,
.Xr PEM_write_bio_DSAPrivateKey 3 ,
.Xr PEM_write_bio_DSA_PUBKEY 3 ,
.Xr PEM_write_ECPKParameters 3 ,
.Xr PEM_write_ECPrivateKey 3 ,
.Xr PEM_write_EC_PUBKEY 3 ,
.Xr PEM_write_bio_ECPKParameters 3 ,
.Xr PEM_write_bio_ECPrivateKey 3 ,
.Xr PEM_write_bio_EC_PUBKEY 3 ,
.Xr PEM_write_RSAPrivateKey 3 ,
.Xr PEM_write_RSA_PUBKEY 3 ,
.Xr PEM_write_RSAPublicKey 3 ,
.Xr PEM_write_bio_RSAPrivateKey 3 ,
.Xr PEM_write_bio_RSA_PUBKEY 3 ,
.Xr PEM_write_bio_RSAPublicKey 3 ,
.Pp
See
.Sx Deprecated low-level key reading and writing functions
.It
.Xr PKCS1_MGF1 3
.Pp
See
.Sx Deprecated low-level encryption functions .
.It
.Xr RAND_get_rand_method 3 ,
.Xr RAND_set_rand_method 3 ,
.Xr RAND_OpenSSL 3 ,
.Xr RAND_set_rand_engine 3
.Pp
Applications should instead use
.Xr RAND_set_DRBG_type 3 ,
.Xr EVP_RAND 3
and
.Xr EVP_RAND 7 .
See
.Xr RAND_set_rand_method 3
for more details.
.It
.Xr RC2_encrypt 3 ,
.Xr RC2_decrypt 3 ,
.Xr RC2_set_key 3 ,
.Xr RC2_cbc_encrypt 3 ,
.Xr RC2_cfb64_encrypt 3 ,
.Xr RC2_ecb_encrypt 3 ,
.Xr RC2_ofb64_encrypt 3 ,
.Xr RC4 3 ,
.Xr RC4_set_key 3 ,
.Xr RC4_options 3 ,
.Xr RC5_32_encrypt 3 ,
.Xr RC5_32_set_key 3 ,
.Xr RC5_32_decrypt 3 ,
.Xr RC5_32_cbc_encrypt 3 ,
.Xr RC5_32_cfb64_encrypt 3 ,
.Xr RC5_32_ecb_encrypt 3 ,
.Xr RC5_32_ofb64_encrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions .
The Algorithms "RC2", "RC4" and "RC5" have been moved to the
.Sx Legacy Algorithms .
.It
.Xr RIPEMD160 3 ,
.Xr RIPEMD160_Init 3 ,
.Xr RIPEMD160_Update 3 ,
.Xr RIPEMD160_Final 3 ,
.Xr RIPEMD160_Transform 3
.Pp
See
.Sx Deprecated low-level digest functions .
The RIPE algorithm has been moved to the
.Sx Legacy Algorithms .
.It
.Xr RSA_bits 3 ,
.Xr RSA_security_bits 3 ,
.Xr RSA_size 3
.Pp
Use
.Xr EVP_PKEY_get_bits 3 ,
.Xr EVP_PKEY_get_security_bits 3
and
.Xr EVP_PKEY_get_size 3 .
.It
.Xr RSA_check_key 3 ,
.Xr RSA_check_key_ex 3
.Pp
See
.Sx Deprecated low-level validation functions
.It
.Xr RSA_clear_flags 3 ,
.Xr RSA_flags 3 ,
.Xr RSA_set_flags 3 ,
.Xr RSA_test_flags 3 ,
.Xr RSA_setup_blinding 3 ,
.Xr RSA_blinding_off 3 ,
.Xr RSA_blinding_on 3
.Pp
All of these RSA flags have been deprecated without replacement:
.Pp
.Sy RSA_FLAG_BLINDING ,
.Sy RSA_FLAG_CACHE_PRIVATE ,
.Sy RSA_FLAG_CACHE_PUBLIC ,
.Sy RSA_FLAG_EXT_PKEY ,
.Sy RSA_FLAG_NO_BLINDING ,
.Sy RSA_FLAG_THREAD_SAFE
.Sy RSA_METHOD_FLAG_NO_CHECK
.It
.Xr RSA_generate_key_ex 3 ,
.Xr RSA_generate_multi_prime_key 3
.Pp
See
.Sx Deprecated low-level key generation functions .
.It
.Xr RSA_get0_engine 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides
.It
.Xr RSA_get0_crt_params 3 ,
.Xr RSA_get0_d 3 ,
.Xr RSA_get0_dmp1 3 ,
.Xr RSA_get0_dmq1 3 ,
.Xr RSA_get0_e 3 ,
.Xr RSA_get0_factors 3 ,
.Xr RSA_get0_iqmp 3 ,
.Xr RSA_get0_key 3 ,
.Xr RSA_get0_multi_prime_crt_params 3 ,
.Xr RSA_get0_multi_prime_factors 3 ,
.Xr RSA_get0_n 3 ,
.Xr RSA_get0_p 3 ,
.Xr RSA_get0_pss_params 3 ,
.Xr RSA_get0_q 3 ,
.Xr RSA_get_multi_prime_extra_count 3
.Pp
See
.Sx Deprecated low-level key parameter getters
.It
.Xr RSA_new 3 ,
.Xr RSA_free 3 ,
.Xr RSA_up_ref 3
.Pp
See
.Sx Deprecated low-level object creation .
.It
.Xr RSA_get_default_method 3 ,
RSA_get_ex_data and
.Xr RSA_get_method 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Xr RSA_get_version 3
.Pp
There is no replacement.
.It
.Sy RSA_meth_*() ,
.Xr RSA_new_method 3 ,
RSA_null_method and
.Xr RSA_PKCS1_OpenSSL 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides .
.It
.Sy RSA_padding_add_*() ,
.Sy RSA_padding_check_*()
.Pp
See
.Sx Deprecated low-level signing functions
and
.Sx Deprecated low-level encryption functions .
.It
.Xr RSA_print 3 ,
.Xr RSA_print_fp 3
.Pp
See
.Sx Deprecated low-level key printing functions
.It
.Xr RSA_public_encrypt 3 ,
.Xr RSA_private_decrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions
.It
.Xr RSA_private_encrypt 3 ,
.Xr RSA_public_decrypt 3
.Pp
This is equivalent to doing sign and verify recover operations (with a
padding mode of none).
See
.Sx Deprecated low-level signing functions .
.It
.Xr RSAPrivateKey_dup 3 ,
.Xr RSAPublicKey_dup 3
.Pp
There is no direct replacement.
Applications may use
.Xr EVP_PKEY_dup 3 .
.It
.Xr RSAPublicKey_it 3 ,
.Xr RSAPrivateKey_it 3
.Pp
See
.Sx Deprecated low-level key reading and writing functions
.It
.Xr RSA_set0_crt_params 3 ,
.Xr RSA_set0_factors 3 ,
.Xr RSA_set0_key 3 ,
.Xr RSA_set0_multi_prime_params 3
.Pp
See
.Sx Deprecated low-level key parameter setters .
.It
.Xr RSA_set_default_method 3 ,
.Xr RSA_set_method 3 ,
.Xr RSA_set_ex_data 3
.Pp
See
.Sx Providers are a replacement for engines and low-level method overrides
.It
.Xr RSA_sign 3 ,
.Xr RSA_sign_ASN1_OCTET_STRING 3 ,
.Xr RSA_verify 3 ,
.Xr RSA_verify_ASN1_OCTET_STRING 3 ,
.Xr RSA_verify_PKCS1_PSS 3 ,
.Xr RSA_verify_PKCS1_PSS_mgf1 3
.Pp
See
.Sx Deprecated low-level signing functions .
.It
.Xr RSA_X931_derive_ex 3 ,
.Xr RSA_X931_generate_key_ex 3 ,
.Xr RSA_X931_hash_id 3
.Pp
There are no replacements for these functions.
X931 padding can be set using
.Xr EVP_SIGNATURE-RSA 7 .
See
.Sy OSSL_SIGNATURE_PARAM_PAD_MODE .
.It
.Xr SEED_encrypt 3 ,
.Xr SEED_decrypt 3 ,
.Xr SEED_set_key 3 ,
.Xr SEED_cbc_encrypt 3 ,
.Xr SEED_cfb128_encrypt 3 ,
.Xr SEED_ecb_encrypt 3 ,
.Xr SEED_ofb128_encrypt 3
.Pp
See
.Sx Deprecated low-level encryption functions .
The SEED algorithm has been moved to the
.Sx Legacy Algorithms .
.It
.Xr SHA1_Init 3 ,
.Xr SHA1_Update 3 ,
.Xr SHA1_Final 3 ,
.Xr SHA1_Transform 3 ,
.Xr SHA224_Init 3 ,
.Xr SHA224_Update 3 ,
.Xr SHA224_Final 3 ,
.Xr SHA256_Init 3 ,
.Xr SHA256_Update 3 ,
.Xr SHA256_Final 3 ,
.Xr SHA256_Transform 3 ,
.Xr SHA384_Init 3 ,
.Xr SHA384_Update 3 ,
.Xr SHA384_Final 3 ,
.Xr SHA512_Init 3 ,
.Xr SHA512_Update 3 ,
.Xr SHA512_Final 3 ,
.Xr SHA512_Transform 3
.Pp
See
.Sx Deprecated low-level digest functions .
.It
.Xr SRP_Calc_A 3 ,
.Xr SRP_Calc_B 3 ,
.Xr SRP_Calc_client_key 3 ,
.Xr SRP_Calc_server_key 3 ,
.Xr SRP_Calc_u 3 ,
.Xr SRP_Calc_x 3 ,
.Xr SRP_check_known_gN_param 3 ,
.Xr SRP_create_verifier 3 ,
.Xr SRP_create_verifier_BN 3 ,
.Xr SRP_get_default_gN 3 ,
.Xr SRP_user_pwd_free 3 ,
.Xr SRP_user_pwd_new 3 ,
.Xr SRP_user_pwd_set0_sv 3 ,
.Xr SRP_user_pwd_set1_ids 3 ,
.Xr SRP_user_pwd_set_gN 3 ,
.Xr SRP_VBASE_add0_user 3 ,
.Xr SRP_VBASE_free 3 ,
.Xr SRP_VBASE_get1_by_user 3 ,
.Xr SRP_VBASE_init 3 ,
.Xr SRP_VBASE_new 3 ,
.Xr SRP_Verify_A_mod_N 3 ,
.Xr SRP_Verify_B_mod_N 3
.Pp
There are no replacements for the SRP functions.
.It
.Xr SSL_CTX_set_tmp_dh_callback 3 ,
.Xr SSL_set_tmp_dh_callback 3 ,
.Xr SSL_CTX_set_tmp_dh 3 ,
.Xr SSL_set_tmp_dh 3
.Pp
These are used to set the Diffie-Hellman (DH) parameters that are to be
used by servers requiring ephemeral DH keys.
Instead applications should consider using the built-in DH parameters
that are available by calling
.Xr SSL_CTX_set_dh_auto 3
or
.Xr SSL_set_dh_auto 3 .
If custom parameters are necessary then applications can use the
alternative functions
.Xr SSL_CTX_set0_tmp_dh_pkey 3
and
.Xr SSL_set0_tmp_dh_pkey 3 .
There is no direct replacement for the "callback" functions.
The callback was originally useful in order to have different parameters
for export and non-export ciphersuites.
Export ciphersuites are no longer supported by OpenSSL. Use of the
callback functions should be replaced by one of the other methods
described above.
.It
.Xr SSL_CTX_set_tlsext_ticket_key_cb 3
.Pp
Use the new
.Xr SSL_CTX_set_tlsext_ticket_key_evp_cb 3
function instead.
.It
.Xr WHIRLPOOL 3 ,
.Xr WHIRLPOOL_Init 3 ,
.Xr WHIRLPOOL_Update 3 ,
.Xr WHIRLPOOL_Final 3 ,
.Xr WHIRLPOOL_BitUpdate 3
.Pp
See
.Sx Deprecated low-level digest functions .
The Whirlpool algorithm has been moved to the
.Sx Legacy Algorithms .
.It
.Xr X509_certificate_type 3
.Pp
This was an undocumented function.
Applications can use
.Xr X509_get0_pubkey 3
and
.Xr X509_get0_signature 3
instead.
.It
.Xr X509_http_nbio 3 ,
.Xr X509_CRL_http_nbio 3
.Pp
Use
.Xr X509_load_http 3
and
.Xr X509_CRL_load_http 3
instead.
.El
.Pp
.Em NID handling for provided keys and algorithms
.Pp
The following functions for NID (numeric id) handling have changed
semantics.
.Bl -bullet
.It
.Xr EVP_PKEY_id 3 ,
.Xr EVP_PKEY_get_id 3
.Pp
This function was previously used to reliably return the NID of an
EVP_PKEY object, e.g., to look up the name of the algorithm of such
EVP_PKEY by calling
.Xr OBJ_nid2sn 3 .
With the introduction of
.Xr provider 7 Ns s
.Xr EVP_PKEY_id 3
or its new equivalent
.Xr EVP_PKEY_get_id 3
might now also return the value -1
.Pf ( Sy EVP_PKEY_KEYMGMT )
indicating the use of a provider to implement the EVP_PKEY object.
Therefore, the use of
.Xr EVP_PKEY_get0_type_name 3
is recommended for retrieving the name of the EVP_PKEY algorithm.
.El
.Ss Using the FIPS Module in applications
See
.Xr fips_module 7
and
.Xr OSSL_PROVIDER-FIPS 7
for details.
.Ss OpenSSL command line application changes
.Pp
.Em New applications
.Pp
.Xr openssl-kdf 1
uses the new
.Xr EVP_KDF 3
API.
.Xr openssl-mac 1
uses the new
.Xr EVP_MAC 3
API.
.Pp
.Em Added options
.Pp
.Sy -provider_path
and
.Sy -provider
are available to all apps and can be used multiple times to load any
providers, such as the 'legacy' provider or third party providers.
If used then the 'default' provider would also need to be specified if
required.
The
.Sy -provider_path
must be specified before the
.Sy -provider
option.
.Pp
The
.Sy list
app has many new options.
See
.Xr openssl-list 1
for more information.
.Pp
.Sy -crl_lastupdate
and
.Sy -crl_nextupdate
used by
.Sy openssl ca
allows explicit setting of fields in the generated CRL.
.Pp
.Em Removed options
.Pp
Interactive mode is not longer available.
.Pp
The
.Sy -crypt
option used by
.Sy openssl passwd .
The
.Sy -c
option used by
.Sy openssl x509 ,
.Sy openssl dhparam ,
.Sy openssl dsaparam ,
and
.Sy openssl ecparam .
.Pp
.Em Other Changes
.Pp
The output of Command line applications may have minor changes.
These are primarily changes in capitalisation and white space.
However, in some cases, there are additional differences.
For example, the DH parameters output from
.Sy openssl dhparam
now lists 'P', 'Q', 'G' and 'pcounter' instead of 'prime', 'generator',
'subgroup order' and 'counter' respectively.
.Pp
The
.Sy openssl
commands that read keys, certificates, and CRLs now automatically detect
the PEM or DER format of the input files so it is not necessary to
explicitly specify the input format anymore.
However if the input format option is used the specified format will be
required.
.Pp
.Sy openssl speed
no longer uses low-level API calls.
This implies some of the performance numbers might not be comparable
with the previous releases due to higher overhead.
This applies particularly to measuring performance on smaller data
chunks.
.Pp
b<openssl dhparam>,
.Sy openssl dsa ,
.Sy openssl gendsa ,
.Sy openssl dsaparam ,
.Sy openssl genrsa
and
.Sy openssl rsa
have been modified to use PKEY APIs.
.Sy openssl genrsa
and
.Sy openssl rsa
now write PKCS #8 keys by default.
.Pp
.Em Default settings
.Pp
"SHA256" is now the default digest for TS query used by
.Sy openssl ts .
.Pp
.Em Deprecated apps
.Pp
.Sy openssl rsautl
is deprecated, use
.Sy openssl pkeyutl
instead.
.Sy openssl dhparam ,
.Sy openssl dsa ,
.Sy openssl gendsa ,
.Sy openssl dsaparam ,
.Sy openssl genrsa ,
.Sy openssl rsa ,
.Sy openssl genrsa
and
.Sy openssl rsa
are now in maintenance mode and no new features will be added to them.
.Ss TLS Changes
.Bl -bullet
.It
TLS 1.3 FFDHE key exchange support added
.Pp
This uses DH safe prime named groups.
.It
Support for fully "pluggable" TLSv1.3 groups.
.Pp
This means that providers may supply their own group implementations
(using either the "key exchange" or the "key encapsulation" methods)
which will automatically be detected and used by libssl.
.It
SSL and SSL_CTX options are now 64 bit instead of 32 bit.
.Pp
The signatures of the functions to get and set options on SSL and
SSL_CTX objects changed from "unsigned long" to "uint64_t" type.
.Pp
This may require source code changes.
For example it is no longer possible to use the
.Sy SSL_OP_
macro values in preprocessor
.Qo Li #if Qc
conditions.
However it is still possible to test whether these macros are defined or
not.
.Pp
See
.Xr SSL_CTX_get_options 3 ,
.Xr SSL_CTX_set_options 3 ,
.Xr SSL_get_options 3
and
.Xr SSL_set_options 3 .
.It
.Xr SSL_set1_host 3
and
.Xr SSL_add1_host 3
Changes
.Pp
These functions now take IP literal addresses as well as actual
hostnames.
.It
Added SSL option SSL_OP_CLEANSE_PLAINTEXT
.Pp
If the option is set, openssl cleanses (zeroizes) plaintext bytes from
internal buffers after delivering them to the application.
Note, the application is still responsible for cleansing other copies
(e.g.: data received by
.Xr SSL_read 3 Ns ).
.It
Client-initiated renegotiation is disabled by default.
.Pp
To allow it, use the
.Sy -client_renegotiation
option, the
.Sy SSL_OP_ALLOW_CLIENT_RENEGOTIATION
flag, or the
.Qo Li ClientRenegotiation Qc
config parameter as appropriate.
.It
Secure renegotiation is now required by default for TLS connections
.Pp
Support for RFC 5746 secure renegotiation is now required by default for
SSL or TLS connections to succeed.
Applications that require the ability to connect to legacy peers will
need to explicitly set SSL_OP_LEGACY_SERVER_CONNECT. Accordingly,
SSL_OP_LEGACY_SERVER_CONNECT is no longer set as part of SSL_OP_ALL.
.It
Combining the Configure options no-ec and no-dh no longer disables
TLSv1.3
.Pp
Typically if OpenSSL has no EC or DH algorithms then it cannot support
connections with TLSv1.3. However OpenSSL now supports "pluggable"
groups through providers.
Therefore third party providers may supply group implementations even
where there are no built-in ones.
Attempting to create TLS connections in such a build without also
disabling TLSv1.3 at run time or using third party provider groups may
result in handshake failures.
TLSv1.3 can be disabled at compile time using the "no-tls1_3" Configure
option.
.It
.Xr SSL_CTX_set_ciphersuites 3
and
.Xr SSL_set_ciphersuites 3
changes.
.Pp
The methods now ignore unknown ciphers.
.It
Security callback change.
.Pp
The security callback, which can be customised by application code,
supports the security operation SSL_SECOP_TMP_DH. This is defined to
take an EVP_PKEY in the "other" parameter.
In most places this is what is passed.
All these places occur server side.
However there was one client side call of this security operation and it
passed a DH object instead.
This is incorrect according to the definition of SSL_SECOP_TMP_DH, and
is inconsistent with all of the other locations.
Therefore this client side call has been changed to pass an EVP_PKEY
instead.
.It
New SSL option SSL_OP_IGNORE_UNEXPECTED_EOF
.Pp
The SSL option SSL_OP_IGNORE_UNEXPECTED_EOF is introduced.
If that option is set, an unexpected EOF is ignored, it pretends a close
notify was received instead and so the returned error becomes
SSL_ERROR_ZERO_RETURN.
.It
The security strength of SHA1 and MD5 based signatures in TLS has been
reduced.
.Pp
This results in SSL 3, TLS 1.0, TLS 1.1 and DTLS 1.0 no longer working
at the default security level of 1 and instead requires security level
0. The security level can be changed either using the cipher string with
.Qo Li @SECLEVEL Qc ,
or calling
.Xr SSL_CTX_set_security_level 3 .
This also means that where the signature algorithms extension is missing
from a ClientHello then the handshake will fail in TLS 1.2 at security
level 1. This is because, although this extension is optional, failing
to provide one means that OpenSSL will fallback to a default set of
signature algorithms.
This default set requires the availability of SHA1.
.It
X509 certificates signed using SHA1 are no longer allowed at security
level 1 and above.
.Pp
In TLS/SSL the default security level is 1. It can be set either using
the cipher string with
.Qo Li @SECLEVEL Qc ,
or calling
.Xr SSL_CTX_set_security_level 3 .
If the leaf certificate is signed with SHA-1, a call to
.Xr SSL_CTX_use_certificate 3
will fail if the security level is not lowered first.
Outside TLS/SSL, the default security level is -1 (effectively 0). It
can be set using
.Xr X509_VERIFY_PARAM_set_auth_level 3
or using the
.Sy -auth_level
options of the commands.
.El
.Sh SEE ALSO
.Xr fips_module 7
.Sh HISTORY
The migration guide was created for OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2021-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
