.Dd 2025-09-30
.Dt OSSL_PROVIDER-DEFAULT 7ossl
.Os
.Sh NAME
.Nm OSSL_PROVIDER-default
.Nd OpenSSL default provider
.Sh DESCRIPTION
The OpenSSL default provider supplies the majority of OpenSSL's diverse
algorithm implementations.
If an application doesn't specify anything else explicitly (e.g.
in the application or via config), then this is the provider that will
be used as fallback: It is loaded automatically the first time that an
algorithm is fetched from a provider or a function acting on providers
is called and no other provider has been loaded yet.
.Pp
If an attempt to load a provider has already been made (whether
successful or not) then the default provider won't be loaded
automatically.
Therefore if the default provider is to be used in conjunction with
other providers then it must be loaded explicitly.
Automatic loading of the default provider only occurs a maximum of once;
if the default provider is explicitly unloaded then the default provider
will not be automatically loaded again.
.Ss Properties
The implementations in this provider specifically have this property
defined:
.Bl -tag -width Ds
.It \(dqprovider=default"
.El
It may be used in a property query string with fetching functions such
as
.Xr EVP_MD_fetch 3
or
.Xr EVP_CIPHER_fetch 3 ,
as well as with other functions that take a property query string, such
as
.Xr EVP_PKEY_CTX_new_from_name 3 .
.Pp
It isn't mandatory to query for this property, except to make sure to
get implementations of this provider and none other.
.Pp
Some implementations may define additional properties.
Exact information is listed below
.Sh OPERATIONS AND ALGORITHMS
The OpenSSL default provider supports these operations and algorithms:
.Ss Hashing Algorithms / Message Digests
.Bl -tag -width Ds
.It SHA1, see Xr EVP_MD-SHA1 7
.It SHA2, see Xr EVP_MD-SHA2 7
.It SHA3, see Xr EVP_MD-SHA3 7
.It KECCAK, see Xr EVP_MD-KECCAK 7
.It KECCAK-KMAC, see Xr EVP_MD-KECCAK-KMAC 7
.It SHAKE, see Xr EVP_MD-SHAKE 7
.It BLAKE2, see Xr EVP_MD-BLAKE2 7
.It SM3, see Xr EVP_MD-SM3 7
.It MD5, see Xr EVP_MD-MD5 7
.It MD5-SHA1, see Xr EVP_MD-MD5-SHA1 7
.It RIPEMD160, see Xr EVP_MD-RIPEMD160 7
.It NULL, see Xr EVP_MD-NULL 7
.El
.Ss Symmetric Ciphers
.Bl -tag -width Ds
.It AES, see Xr EVP_CIPHER-AES 7
.It ARIA, see Xr EVP_CIPHER-ARIA 7
.It CAMELLIA, see Xr EVP_CIPHER-CAMELLIA 7
.It 3DES, see Xr EVP_CIPHER-DES 7
.It SM4, see Xr EVP_CIPHER-SM4 7
.It ChaCha20, see Xr EVP_CIPHER-CHACHA 7
.It ChaCha20-Poly1305, see Xr EVP_CIPHER-CHACHA 7
.It NULL, see Xr EVP_CIPHER-NULL 7
.El
.Ss Message Authentication Code (MAC)
.Bl -tag -width Ds
.It BLAKE2, see Xr EVP_MAC-BLAKE2 7
.It CMAC, see Xr EVP_MAC-CMAC 7
.It GMAC, see Xr EVP_MAC-GMAC 7
.It HMAC, see Xr EVP_MAC-HMAC 7
.It KMAC, see Xr EVP_MAC-KMAC 7
.It SIPHASH, see Xr EVP_MAC-Siphash 7
.It POLY1305, see Xr EVP_MAC-Poly1305 7
.El
.Ss Key Derivation Function (KDF)
.Bl -tag -width Ds
.It HKDF, see Xr EVP_KDF-HKDF 7
.It TLS13-KDF, see Xr EVP_KDF-TLS13_KDF 7
.It SSKDF, see Xr EVP_KDF-SS 7
.It PBKDF2, see Xr EVP_KDF-PBKDF2 7
.It PKCS12KDF, see Xr EVP_KDF-PKCS12KDF 7
.It SSHKDF, see Xr EVP_KDF-SSHKDF 7
.It TLS1-PRF, see Xr EVP_KDF-TLS1_PRF 7
.It KBKDF, see Xr EVP_KDF-KB 7
.It X942KDF-ASN1, see Xr EVP_KDF-X942-ASN1 7
.It X942KDF-CONCAT, see Xr EVP_KDF-X942-CONCAT 7
.It X963KDF, see Xr EVP_KDF-X963 7
.It SCRYPT, see Xr EVP_KDF-SCRYPT 7
.It KRB5KDF, see Xr EVP_KDF-KRB5KDF 7
.It HMAC-DRBG, see Xr EVP_KDF-HMAC-DRBG 7
.It ARGON2, see Xr EVP_KDF-ARGON2 7
.El
.Ss Key Exchange
.Bl -tag -width Ds
.It DH, see Xr EVP_KEYEXCH-DH 7
.It ECDH, see Xr EVP_KEYEXCH-ECDH 7
.It X25519, see Xr EVP_KEYEXCH-X25519 7
.It X448, see Xr EVP_KEYEXCH-X448 7
.It ML-KEM-512, see Xr EVP_KEM-ML-KEM-512 7
.It ML-KEM-768, see Xr EVP_KEM-ML-KEM-768 7
.It ML-KEM-1024, see Xr EVP_KEM-ML-KEM-1024 7
.It TLS1-PRF
.It HKDF
.It SCRYPT
.El
.Ss Asymmetric Signature
.Bl -tag -width Ds
.It DSA, see Xr EVP_SIGNATURE-DSA 7
.It RSA, see Xr EVP_SIGNATURE-RSA 7
.It ED25519, see Xr EVP_SIGNATURE-ED25519 7
.It ED448, see Xr EVP_SIGNATURE-ED448 7
.It ECDSA, see Xr EVP_SIGNATURE-ECDSA 7
.It SM2
.It ML-DSA-44, see Xr EVP_SIGNATURE-ML-DSA 7
.It ML-DSA-65, see Xr EVP_SIGNATURE-ML-DSA 7
.It ML-DSA-87, see Xr EVP_SIGNATURE-ML-DSA 7
.It HMAC, see Xr EVP_SIGNATURE-HMAC 7
.It SIPHASH, see Xr EVP_SIGNATURE-Siphash 7
.It POLY1305, see Xr EVP_SIGNATURE-Poly1305 7
.It CMAC, see Xr EVP_SIGNATURE-CMAC 7
.It SLH-DSA-SHA2-128s, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHA2-128f, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHA2-192s, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHA2-192f, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHA2-256s, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHA2-256f, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHAKE-128s, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHAKE-128f, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHAKE-192s, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHAKE-192f, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHAKE-256s, see Xr EVP_SIGNATURE-SLH-DSA 7
.It SLH-DSA-SHAKE-256f, see Xr EVP_SIGNATURE-SLH-DSA 7
.El
.Ss Asymmetric Cipher
.Bl -tag -width Ds
.It RSA, see Xr EVP_ASYM_CIPHER-RSA 7
.It SM2, see Xr EVP_ASYM_CIPHER-SM2 7
.El
.Ss Asymmetric Key Encapsulation
.Bl -tag -width Ds
.It RSA, see Xr EVP_KEM-RSA 7
.It X25519, see Xr EVP_KEM-X25519 7
.It X448, see Xr EVP_KEM-X448 7
.It EC, see Xr EVP_KEM-EC 7
.It ML-KEM-512, see Xr EVP_KEM-ML-KEM-512 7
.It ML-KEM-768, see Xr EVP_KEM-ML-KEM-768 7
.It ML-KEM-1024, see Xr EVP_KEM-ML-KEM-1024 7
.El
.Ss Asymmetric Key Management
.Bl -tag -width Ds
.It DSA, see Xr EVP_KEYMGMT-DSA 7
.It RSA, see Xr EVP_KEYMGMT-RSA 7
.It RSA-PSS
.It EC, see Xr EVP_KEYMGMT-EC 7
.It ED25519, see Xr EVP_KEYMGMT-ED25519 7
.It ED448, see Xr EVP_KEYMGMT-ED448 7
.It SM2, see Xr EVP_KEYMGMT-SM2 7
.It DH, see Xr EVP_KEYMGMT-DH 7
.It DHX, see Xr EVP_KEYMGMT-DHX 7
.It X25519, see Xr EVP_KEYMGMT-X25519 7
.It X448, see Xr EVP_KEYMGMT-X448 7
.It ML-DSA-44, see Xr EVP_KEYMGMT-ML-DSA 7
.It ML-DSA-65, see Xr EVP_KEYMGMT-ML-DSA 7
.It ML-DSA-87, see Xr EVP_KEYMGMT-ML-DSA 7
.It MK-KEM-512, see Xr EVP_KEYMGMT-ML-KEM-512 7
.It MK-KEM-768, see Xr EVP_KEYMGMT-ML-KEM-768 7
.It MK-KEM-1024, see Xr EVP_KEYMGMT-ML-KEM-1024 7
.It SLH-DSA-SHA2-128s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-128f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-192s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-192f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-256s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHA2-256f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-128s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-128f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-192s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-192f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-256s, see Xr EVP_KEYMGMT-SLH-DSA 7
.It SLH-DSA-SHAKE-256f, see Xr EVP_KEYMGMT-SLH-DSA 7
.It TLS1-PRF
.It HKDF
.It SCRYPT
.It HMAC, see Xr EVP_KEYMGMT-HMAC 7
.It SIPHASH, see Xr EVP_KEYMGMT-Siphash 7
.It POLY1305, see Xr EVP_KEYMGMT-Poly1305 7
.It CMAC, see Xr EVP_KEYMGMT-CMAC 7
.El
.Ss Random Number Generation
.Bl -tag -width Ds
.It CTR-DRBG, see Xr EVP_RAND-CTR-DRBG 7
.It HASH-DRBG, see Xr EVP_RAND-HASH-DRBG 7
.It HMAC-DRBG, see Xr EVP_RAND-HMAC-DRBG 7
.It SEED-SRC, see Xr EVP_RAND-SEED-SRC 7
.It JITTER, see Xr EVP_RAND-JITTER 7
.It TEST-RAND, see Xr EVP_RAND-TEST-RAND 7
.El
In addition to this provider, the "SEED-SRC" and "JITTER" algorithms are
also available in the base provider.
.Ss Asymmetric Key Encoder
.Bl -tag -width Ds
.It RSA
.It RSA-PSS
.It DH
.It DHX
.It DSA
.It EC
.It ED25519
.It ED448
.It X25519
.It X448
.It SM2
.It ML-DSA-44
.It ML-DSA-65
.It ML-DSA-87
.It ML-KEM-512
.It ML-KEM-768
.It ML-KEM-1024
.It SLH-DSA-SHA2-128s
.It SLH-DSA-SHA2-128f
.It SLH-DSA-SHA2-192s
.It SLH-DSA-SHA2-192f
.It SLH-DSA-SHA2-256s
.It SLH-DSA-SHA2-256f
.It SLH-DSA-SHAKE-128s
.It SLH-DSA-SHAKE-128f
.It SLH-DSA-SHAKE-192s
.It SLH-DSA-SHAKE-192f
.It SLH-DSA-SHAKE-256s
.It SLH-DSA-SHAKE-256f
.El
In addition to this provider, all of these encoding algorithms are also
available in the base provider.
Some of these algorithms may be used in combination with the FIPS
provider.
.Ss Asymmetric Key Decoder
.Bl -tag -width Ds
.It RSA
.It RSA-PSS
.It DH
.It DHX
.It DSA
.It EC
.It ED25519
.It ED448
.It X25519
.It X448
.It SM2
.It ML-DSA-44
.It ML-DSA-65
.It ML-DSA-87
.It ML-KEM-512
.It ML-KEM-768
.It ML-KEM-1024
.It SLH-DSA-SHA2-128s
.It SLH-DSA-SHA2-128f
.It SLH-DSA-SHA2-192s
.It SLH-DSA-SHA2-192f
.It SLH-DSA-SHA2-256s
.It SLH-DSA-SHA2-256f
.It SLH-DSA-SHAKE-128s
.It SLH-DSA-SHAKE-128f
.It SLH-DSA-SHAKE-192s
.It SLH-DSA-SHAKE-192f
.It SLH-DSA-SHAKE-256s
.It SLH-DSA-SHAKE-256f
.El
In addition to this provider, all of these decoding algorithms are also
available in the base provider.
Some of these algorithms may be used in combination with the FIPS
provider.
.Ss Stores
.Bl -tag -width Ds
.It file
.It org.openssl.winstore, see Xr OSSL_STORE-winstore 7
.El
In addition to this provider, all of these store algorithms are also
available in the base provider.
.Sh SEE ALSO
.Xr openssl-core.h 7 ,
.Xr openssl-core_dispatch.h 7 ,
.Xr provider 7 ,
.Xr OSSL_PROVIDER-base 7
.Sh HISTORY
The RIPEMD160 digest was added to the default provider in OpenSSL 3.0.7.
.Pp
All other functionality was added in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
