.Dd 2025-09-30
.Dt PROVIDER-MAC 7ossl
.Os
.Sh NAME
.Nm provider-mac
.Nd The mac library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Context management */
 void *
.Fo OSSL_FUNC_mac_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_mac_freectx
.Fa "void *mctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_mac_dupctx
.Fa "void *src"
.Fc
.Ft /* Encryption/decryption */
 int
.Fo OSSL_FUNC_mac_init
.Fa "void *mctx"
.Fa "unsigned char *key"
.Fa "size_t keylen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_mac_init_skey
.Fa "void *mctx"
.Fa "const void *key"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_mac_update
.Fa "void *mctx"
.Fa "const unsigned char *in"
.Fa "size_t inl"
.Fc
.Ft int
.Fo OSSL_FUNC_mac_final
.Fa "void *mctx"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsize"
.Fc
.Ft /* MAC parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_mac_gettable_params
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_mac_gettable_ctx_params
.Fa "void *mctx"
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_mac_settable_ctx_params
.Fa "void *mctx"
.Fa "void *provctx"
.Fc
.Ft /* MAC parameters */
 int
.Fo OSSL_FUNC_mac_get_params
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_mac_get_ctx_params
.Fa "void *mctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_mac_set_ctx_params
.Fa "void *mctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The MAC operation enables providers to implement mac algorithms and make
them available to applications via the API functions
.Xr EVP_MAC_init 3 ,
.Xr EVP_MAC_update 3
and
.Xr EVP_MAC_final 3 .
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_mac_newctx
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_mac_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_mac_newctx_fn
     OSSL_FUNC_mac_newctx(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_mac_newctx               OSSL_FUNC_MAC_NEWCTX
 OSSL_FUNC_mac_freectx              OSSL_FUNC_MAC_FREECTX
 OSSL_FUNC_mac_dupctx               OSSL_FUNC_MAC_DUPCTX

 OSSL_FUNC_mac_init                 OSSL_FUNC_MAC_INIT
 OSSL_FUNC_mac_init_skey            OSSL_FUNC_MAC_INIT_SKEY
 OSSL_FUNC_mac_update               OSSL_FUNC_MAC_UPDATE
 OSSL_FUNC_mac_final                OSSL_FUNC_MAC_FINAL

 OSSL_FUNC_mac_get_params           OSSL_FUNC_MAC_GET_PARAMS
 OSSL_FUNC_mac_get_ctx_params       OSSL_FUNC_MAC_GET_CTX_PARAMS
 OSSL_FUNC_mac_set_ctx_params       OSSL_FUNC_MAC_SET_CTX_PARAMS

 OSSL_FUNC_mac_gettable_params      OSSL_FUNC_MAC_GETTABLE_PARAMS
 OSSL_FUNC_mac_gettable_ctx_params  OSSL_FUNC_MAC_GETTABLE_CTX_PARAMS
 OSSL_FUNC_mac_settable_ctx_params  OSSL_FUNC_MAC_SETTABLE_CTX_PARAMS
.Ed
.Pp
A mac algorithm implementation may not implement all of these functions.
In order to be a consistent set of functions, at least the following
functions must be implemented:
.Fn OSSL_FUNC_mac_newctx ,
.Fn OSSL_FUNC_mac_freectx ,
at least one of
.Fn OSSL_FUNC_mac_init
or
.Fn OSSL_FUNC_mac_init_skey ,
.Fn OSSL_FUNC_mac_update ,
.Fn OSSL_FUNC_mac_final .
All other functions are optional.
.Ss Context Management Functions
.Fn OSSL_FUNC_mac_newctx
should create and return a pointer to a provider side structure for
holding context information during a mac operation.
A pointer to this context will be passed back in a number of the other
mac operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
.Pp
.Fn OSSL_FUNC_mac_freectx
is passed a pointer to the provider side mac context in the
.Fa mctx
parameter.
If it receives NULL as
.Fa mctx
value, it should not do anything other than return.
This function should free any resources associated with that context.
.Pp
.Fn OSSL_FUNC_mac_dupctx
should duplicate the provider side mac context in the
.Fa mctx
parameter and return the duplicate copy.
.Ss Encryption/Decryption Functions
.Fn OSSL_FUNC_mac_init
initialises a mac operation given a newly created provider side mac
context in the
.Fa mctx
parameter.
The
.Em params
are set before setting the MAC
.Fa key
of
.Fa keylen
bytes.
.Pp
.Fn OSSL_FUNC_mac_init_skey
is similar but uses an opaque provider-specific object to initialize the
MAC context.
.Pp
.Fn OSSL_FUNC_mac_update
is called to supply data for MAC computation of a previously initialised
mac operation.
The
.Fa mctx
parameter contains a pointer to a previously initialised provider side
context.
.Fn OSSL_FUNC_mac_update
may be called multiple times for a single mac operation.
.Pp
.Fn OSSL_FUNC_mac_final
completes the MAC computation started through previous
.Fn OSSL_FUNC_mac_init
and
.Fn OSSL_FUNC_mac_update
calls.
The
.Fa mctx
parameter contains a pointer to the provider side context.
The resulting MAC should be written to
.Fa out
and the amount of data written to
.Em *outl ,
which should not exceed
.Fa outsize
bytes.
The same expectations apply to
.Fa outsize
as documented for
.Xr EVP_MAC_final 3 .
.Ss Mac Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by these functions.
.Pp
.Fn OSSL_FUNC_mac_get_params
gets details of parameter values associated with the provider algorithm
and stores them in
.Em params .
.Pp
.Fn OSSL_FUNC_mac_set_ctx_params
sets mac parameters associated with the given provider side mac context
.Fa mctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_mac_get_ctx_params
gets details of currently set parameter values associated with the given
provider side mac context
.Fa mctx
and stores them in
.Em params .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_mac_gettable_params ,
.Fn OSSL_FUNC_mac_gettable_ctx_params ,
and
.Fn OSSL_FUNC_mac_settable_ctx_params
all return constant
.Xr OSSL_PARAM 3
arrays as descriptors of the parameters that
.Fn OSSL_FUNC_mac_get_params ,
.Fn OSSL_FUNC_mac_get_ctx_params ,
and
.Fn OSSL_FUNC_mac_set_ctx_params
can handle, respectively.
.Fn OSSL_FUNC_mac_gettable_ctx_params
and
.Fn OSSL_FUNC_mac_settable_ctx_params
will return the parameters associated with the provider side context
.Fa mctx
in its current state if it is not NULL. Otherwise, they return the
parameters associated with the provider side algorithm
.Fa provctx .
.Pp
All MAC implementations are expected to handle the following parameters:
.Bl -tag -width Ds
.It with OSSL_FUNC_set_ctx_params():
.Bl -tag -width Ds
.It \(dqkey" ( Ns Sy OSSL_MAC_PARAM_KEY Ns ) <octet string>
Sets the key in the associated MAC ctx.
This is identical to passing a
.Fa key
argument to the
.Fn OSSL_FUNC_mac_init
function.
.El
.It with OSSL_FUNC_get_params():
.Bl -tag -width Ds
.It \(dqsize" ( Ns Sy OSSL_MAC_PARAM_SIZE Ns ) <integer>
Can be used to get the default MAC size (which might be the only
allowable MAC size for the implementation).
.Pp
Note that some implementations allow setting the size that the resulting
MAC should have as well, see the documentation of the implementation.
.El
.Bl -tag -width Ds
.It \(dqsize" ( Ns Sy OSSL_MAC_PARAM_BLOCK_SIZE Ns ) <integer>
Can be used to get the MAC block size (if supported by the algorithm).
.El
.El
.Pp
The OpenSSL FIPS provider may support the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_MAC_PARAM_FIPS_APPROVED_INDICATOR Ns ) <int>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling the final function.
It may return 0 if either "no-short-mac" or "key-check" are set to 0.
.It \(dqno-short-mac" ( Ns Sy OSSL_MAC_PARAM_FIPS_NO_SHORT_MAC Ns ) <integer>
If required this parameter should be set early via an init function.
The default value of 1 causes an error when too short MAC output is
asked for.
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.It \(dqkey-check" ( Ns Sy OSSL_MAC_PARAM_FIPS_KEY_CHECK Ns ) <integer>
If required this parameter should be set before OSSL_FUNC_mac_init.
The default value of 1 causes an error when small key sizes are asked
for.
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Sh NOTES
The MAC life-cycle is described in
.Xr life_cycle-rand 7 .
Providers should ensure that the various transitions listed there are
supported.
At some point the EVP layer will begin enforcing the listed transitions.
.Sh RETURN VALUES
.Fn OSSL_FUNC_mac_newctx
and
.Fn OSSL_FUNC_mac_dupctx
should return the newly created provider side mac context, or NULL on
failure.
.Pp
.Fn OSSL_FUNC_mac_init ,
.Fn OSSL_FUNC_mac_init_skey ,
.Fn OSSL_FUNC_mac_update ,
.Fn OSSL_FUNC_mac_final ,
.Fn OSSL_FUNC_mac_get_params ,
.Fn OSSL_FUNC_mac_get_ctx_params
and
.Fn OSSL_FUNC_mac_set_ctx_params
should return 1 for success or 0 on error.
.Pp
.Fn OSSL_FUNC_mac_gettable_params ,
.Fn OSSL_FUNC_mac_gettable_ctx_params
and
.Fn OSSL_FUNC_mac_settable_ctx_params
should return a constant
.Xr OSSL_PARAM 3
array, or NULL if none is offered.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr EVP_MAC-BLAKE2 7 ,
.Xr EVP_MAC-CMAC 7 ,
.Xr EVP_MAC-GMAC 7 ,
.Xr EVP_MAC-HMAC 7 ,
.Xr EVP_MAC-KMAC 7 ,
.Xr EVP_MAC-Poly1305 7 ,
.Xr EVP_MAC-Siphash 7 ,
.Xr life_cycle-mac 7 ,
.Xr EVP_MAC 3
.Sh HISTORY
The provider MAC interface was introduced in OpenSSL 3.0. The parameters
"no-short-mac" and "fips-indicator" were added in OpenSSL 3.4.
.Pp
The function
.Fn OSSL_FUNC_mac_init_skey
was introduced in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
