.Dd 2025-09-30
.Dt PROVIDER-KDF 7ossl
.Os
.Sh NAME
.Nm provider-kdf
.Nd The KDF library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Context management */
 void *
.Fo OSSL_FUNC_kdf_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_kdf_freectx
.Fa "void *kctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_kdf_dupctx
.Fa "void *src"
.Fc
.Ft /* Encryption/decryption */
 int
.Fo OSSL_FUNC_kdf_reset
.Fa "void *kctx"
.Fc
.Ft int
.Fo OSSL_FUNC_kdf_derive
.Fa "void *kctx"
.Fa "unsigned char *key"
.Fa "size_t keylen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft /* KDF parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_kdf_gettable_params
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_kdf_gettable_ctx_params
.Fa "void *kcxt"
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_kdf_settable_ctx_params
.Fa "void *kcxt"
.Fa "void *provctx"
.Fc
.Ft /* KDF parameters */
 int
.Fo OSSL_FUNC_kdf_get_params
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_kdf_get_ctx_params
.Fa "void *kctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_kdf_set_ctx_params
.Fa "void *kctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The KDF operation enables providers to implement KDF algorithms and make
them available to applications via the API functions
.Xr EVP_KDF_CTX_reset 3 ,
and
.Xr EVP_KDF_derive 3 .
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_kdf_newctx
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_kdf_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_kdf_newctx_fn
     OSSL_FUNC_kdf_newctx(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
array entries are identified by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_kdf_newctx               OSSL_FUNC_KDF_NEWCTX
 OSSL_FUNC_kdf_freectx              OSSL_FUNC_KDF_FREECTX
 OSSL_FUNC_kdf_dupctx               OSSL_FUNC_KDF_DUPCTX

 OSSL_FUNC_kdf_reset                OSSL_FUNC_KDF_RESET
 OSSL_FUNC_kdf_derive               OSSL_FUNC_KDF_DERIVE

 OSSL_FUNC_kdf_get_params           OSSL_FUNC_KDF_GET_PARAMS
 OSSL_FUNC_kdf_get_ctx_params       OSSL_FUNC_KDF_GET_CTX_PARAMS
 OSSL_FUNC_kdf_set_ctx_params       OSSL_FUNC_KDF_SET_CTX_PARAMS

 OSSL_FUNC_kdf_gettable_params      OSSL_FUNC_KDF_GETTABLE_PARAMS
 OSSL_FUNC_kdf_gettable_ctx_params  OSSL_FUNC_KDF_GETTABLE_CTX_PARAMS
 OSSL_FUNC_kdf_settable_ctx_params  OSSL_FUNC_KDF_SETTABLE_CTX_PARAMS
.Ed
.Pp
A KDF algorithm implementation may not implement all of these functions.
In order to be a consistent set of functions, at least the following
functions must be implemented:
.Fn OSSL_FUNC_kdf_newctx ,
.Fn OSSL_FUNC_kdf_freectx ,
.Fn OSSL_FUNC_kdf_set_ctx_params ,
.Fn OSSL_FUNC_kdf_derive .
All other functions are optional.
.Ss Context Management Functions
.Fn OSSL_FUNC_kdf_newctx
should create and return a pointer to a provider side structure for
holding context information during a KDF operation.
A pointer to this context will be passed back in a number of the other
KDF operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
.Pp
.Fn OSSL_FUNC_kdf_freectx
is passed a pointer to the provider side KDF context in the
.Fa kctx
parameter.
If it receives NULL as
.Fa kctx
value, it should not do anything other than return.
This function should free any resources associated with that context.
.Pp
.Fn OSSL_FUNC_kdf_dupctx
should duplicate the provider side KDF context in the
.Fa kctx
parameter and return the duplicate copy.
.Ss Encryption/Decryption Functions
.Fn OSSL_FUNC_kdf_reset
initialises a KDF operation given a provider side KDF context in the
.Fa kctx
parameter.
.Pp
.Fn OSSL_FUNC_kdf_derive
performs the KDF operation after processing the
.Em params
as per
.Fn OSSL_FUNC_kdf_set_ctx_params .
The
.Fa kctx
parameter contains a pointer to the provider side context.
The resulting key of the desired
.Fa keylen
should be written to
.Fa key .
If the algorithm does not support the requested
.Fa keylen
the function must return error.
.Ss KDF Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by these functions.
.Pp
.Fn OSSL_FUNC_kdf_get_params
gets details of parameter values associated with the provider algorithm
and stores them in
.Em params .
.Pp
.Fn OSSL_FUNC_kdf_set_ctx_params
sets KDF parameters associated with the given provider side KDF context
.Fa kctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_kdf_get_ctx_params
retrieves gettable parameter values associated with the given provider
side KDF context
.Fa kctx
and stores them in
.Em params .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_kdf_gettable_params ,
.Fn OSSL_FUNC_kdf_gettable_ctx_params ,
and
.Fn OSSL_FUNC_kdf_settable_ctx_params
all return constant
.Xr OSSL_PARAM 3
arrays as descriptors of the parameters that
.Fn OSSL_FUNC_kdf_get_params ,
.Fn OSSL_FUNC_kdf_get_ctx_params ,
and
.Fn OSSL_FUNC_kdf_set_ctx_params
can handle, respectively.
.Fn OSSL_FUNC_kdf_gettable_ctx_params
and
.Fn OSSL_FUNC_kdf_settable_ctx_params
will return the parameters associated with the provider side context
.Fa kctx
in its current state if it is not NULL. Otherwise, they return the
parameters associated with the provider side algorithm
.Fa provctx .
.Pp
Parameters currently recognised by built-in KDFs are as follows.
Not all parameters are relevant to, or are understood by all KDFs:
.Bl -tag -width Ds
.It \(dqsize" ( Ns Sy OSSL_KDF_PARAM_SIZE Ns ) <unsigned integer>
Gets the output size from the associated KDF ctx.
If the algorithm produces a variable amount of output, SIZE_MAX should
be returned.
If the input parameters required to calculate the fixed output size have
not yet been supplied, 0 should be returned indicating an error.
.It \(dqkey" ( Ns Sy OSSL_KDF_PARAM_KEY Ns ) <octet string>
Sets the key in the associated KDF ctx.
.It \(dqsecret" ( Ns Sy OSSL_KDF_PARAM_SECRET Ns ) <octet string>
Sets the secret in the associated KDF ctx.
.It \(dqpass" ( Ns Sy OSSL_KDF_PARAM_PASSWORD Ns ) <octet string>
Sets the password in the associated KDF ctx.
.It \(dqcipher" ( Ns Sy OSSL_KDF_PARAM_CIPHER Ns ) <UTF8 string>
.It \(dqdigest" ( Ns Sy OSSL_KDF_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqmac" ( Ns Sy OSSL_KDF_PARAM_MAC Ns ) <UTF8 string>
Sets the name of the underlying cipher, digest or MAC to be used.
It must name a suitable algorithm for the KDF that's being used.
.It \(dqmaclen" ( Ns Sy OSSL_KDF_PARAM_MAC_SIZE Ns ) <octet string>
Sets the length of the MAC in the associated KDF ctx.
.It \(dqproperties" ( Ns Sy OSSL_KDF_PARAM_PROPERTIES Ns ) <UTF8 string>
Sets the properties to be queried when trying to fetch the underlying
algorithm.
This must be given together with the algorithm naming parameter to be
considered valid.
.It \(dqiter" ( Ns Sy OSSL_KDF_PARAM_ITER Ns ) <unsigned integer>
Sets the number of iterations in the associated KDF ctx.
.It \(dqmode" ( Ns Sy OSSL_KDF_PARAM_MODE Ns ) <UTF8 string>
Sets the mode in the associated KDF ctx.
.It \(dqpkcs5" ( Ns Sy OSSL_KDF_PARAM_PKCS5 Ns ) <integer>
Enables or disables the SP800-132 compliance checks.
A mode of 0 enables the compliance checks.
.Pp
The checks performed are:
.Bl -tag -width Ds
.It - the iteration count is at least 1000.
.It - the salt length is at least 128 bits.
.It - the derived key length is at least 112 bits.
.El
.It \(dqukm" ( Ns Sy OSSL_KDF_PARAM_UKM Ns ) <octet string>
Sets an optional random string that is provided by the sender called
"partyAInfo".
In CMS this is the user keying material.
.It \(dqcekalg" ( Ns Sy OSSL_KDF_PARAM_CEK_ALG Ns ) <UTF8 string>
Sets the CEK wrapping algorithm name in the associated KDF ctx.
.It \(dqn" ( Ns Sy OSSL_KDF_PARAM_SCRYPT_N Ns ) <unsigned integer>
Sets the scrypt work factor parameter N in the associated KDF ctx.
.It \(dqr" ( Ns Sy OSSL_KDF_PARAM_SCRYPT_R Ns ) <unsigned integer>
Sets the scrypt work factor parameter r in the associated KDF ctx.
.It \(dqp" ( Ns Sy OSSL_KDF_PARAM_SCRYPT_P Ns ) <unsigned integer>
Sets the scrypt work factor parameter p in the associated KDF ctx.
.It \(dqmaxmem_bytes" ( Ns Sy OSSL_KDF_PARAM_SCRYPT_MAXMEM Ns ) <unsigned integer>
Sets the scrypt work factor parameter maxmem in the associated KDF ctx.
.It \(dqprefix" ( Ns Sy OSSL_KDF_PARAM_PREFIX Ns ) <octet string>
Sets the prefix string using by the TLS 1.3 version of HKDF in the
associated KDF ctx.
.It \(dqlabel" ( Ns Sy OSSL_KDF_PARAM_LABEL Ns ) <octet string>
Sets the label string using by the TLS 1.3 version of HKDF in the
associated KDF ctx.
.It \(dqdata" ( Ns Sy OSSL_KDF_PARAM_DATA Ns ) <octet string>
Sets the context string using by the TLS 1.3 version of HKDF in the
associated KDF ctx.
.It \(dqinfo" ( Ns Sy OSSL_KDF_PARAM_INFO Ns ) <octet string>
Sets the optional shared info in the associated KDF ctx.
.It \(dqseed" ( Ns Sy OSSL_KDF_PARAM_SEED Ns ) <octet string>
Sets the IV in the associated KDF ctx.
.It \(dqxcghash" ( Ns Sy OSSL_KDF_PARAM_SSHKDF_XCGHASH Ns ) <octet string>
Sets the xcghash in the associated KDF ctx.
.It \(dqsession_id" ( Ns Sy OSSL_KDF_PARAM_SSHKDF_SESSION_ID Ns ) <octet string>
Sets the session ID in the associated KDF ctx.
.It \(dqtype" ( Ns Sy OSSL_KDF_PARAM_SSHKDF_TYPE Ns ) <UTF8 string>
Sets the SSH KDF type parameter in the associated KDF ctx.
There are six supported types:
.Bl -tag -width Ds
.It EVP_KDF_SSHKDF_TYPE_INITIAL_IV_CLI_TO_SRV
The Initial IV from client to server.
A single char of value 65 (ASCII char 'A').
.It EVP_KDF_SSHKDF_TYPE_INITIAL_IV_SRV_TO_CLI
The Initial IV from server to client A single char of value 66 (ASCII
char 'B').
.It EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_CLI_TO_SRV
The Encryption Key from client to server A single char of value 67
(ASCII char 'C').
.It EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_SRV_TO_CLI
The Encryption Key from server to client A single char of value 68
(ASCII char 'D').
.It EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_CLI_TO_SRV
The Integrity Key from client to server A single char of value 69 (ASCII
char 'E').
.It EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_SRV_TO_CLI
The Integrity Key from client to server A single char of value 70 (ASCII
char 'F').
.El
.It \(dqconstant" ( Ns Sy OSSL_KDF_PARAM_CONSTANT Ns ) <octet string>
Sets the constant value in the associated KDF ctx.
.It \(dqid" ( Ns Sy OSSL_KDF_PARAM_PKCS12_ID Ns ) <integer>
Sets the intended usage of the output bits in the associated KDF ctx.
It is defined as per RFC 7292 section B.3.
.El
.Sh RETURN VALUES
.Fn OSSL_FUNC_kdf_newctx
and
.Fn OSSL_FUNC_kdf_dupctx
should return the newly created provider side KDF context, or NULL on
failure.
.Pp
.Fn OSSL_FUNC_kdf_derive ,
.Fn OSSL_FUNC_kdf_get_params ,
.Fn OSSL_FUNC_kdf_get_ctx_params
and
.Fn OSSL_FUNC_kdf_set_ctx_params
should return 1 for success or 0 on error.
.Pp
.Fn OSSL_FUNC_kdf_gettable_params ,
.Fn OSSL_FUNC_kdf_gettable_ctx_params
and
.Fn OSSL_FUNC_kdf_settable_ctx_params
should return a constant
.Xr OSSL_PARAM 3
array, or NULL if none is offered.
.Sh NOTES
The KDF life-cycle is described in
.Xr life_cycle-kdf 7 .
Providers should ensure that the various transitions listed there are
supported.
At some point the EVP layer will begin enforcing the listed transitions.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr life_cycle-kdf 7 ,
.Xr EVP_KDF 3 .
.Sh HISTORY
The provider KDF interface was introduced in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2020-2022 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
