.Dd 2025-09-30
.Dt PROVIDER-BASE 7ossl
.Os
.Sh NAME
.Nm provider-base
.Nd The basic OpenSSL library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Functions offered by libcrypto to the providers */
 const OSSL_ITEM *
.Fo core_gettable_params
.Fa "const OSSL_CORE_HANDLE *handle"
.Fc
.Ft int
.Fo core_get_params
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft typedef void
.Fo 
.Fa *OSSL_thread_stop_handler_fn
.Fc
(void *arg);
.Ft int
.Fo core_thread_start
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "OSSL_thread_stop_handler_fn handfn"
.Fa "void *arg"
.Fc
.Ft OPENSSL_CORE_CTX *
.Fo core_get_libctx
.Fa "const OSSL_CORE_HANDLE *handle"
.Fc
.Ft void
.Fo core_new_error
.Fa "const OSSL_CORE_HANDLE *handle"
.Fc
.Ft void
.Fo core_set_error_debug
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "const char *file"
.Fa "int line"
.Fa "const char *func"
.Fc
.Ft void
.Fo core_vset_error
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "uint32_t reason"
.Fa "const char *fmt"
.Fa "va_list args"
.Fc
.Ft int
.Fo core_obj_add_sigid
.Fa "const OSSL_CORE_HANDLE *prov"
.Fa "const char  *sign_name"
.Fa "const char *digest_name"
.Fa "const char *pkey_name"
.Fc
.Ft int
.Fo core_obj_create
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "const char *oid"
.Fa "const char *sn"
.Fa "const char *ln"
.Fc
.Ft /*
  * Some OpenSSL functionality is directly offered to providers via
  * dispatch
  */
 void *
.Fo CRYPTO_malloc
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void *
.Fo CRYPTO_zalloc
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void
.Fo CRYPTO_free
.Fa "void *ptr"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void
.Fo CRYPTO_clear_free
.Fa "void *ptr"
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void *
.Fo CRYPTO_realloc
.Fa "void *addr"
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void *
.Fo CRYPTO_clear_realloc
.Fa "void *addr"
.Fa "size_t old_num"
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void *
.Fo CRYPTO_secure_malloc
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void *
.Fo CRYPTO_secure_zalloc
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void
.Fo CRYPTO_secure_free
.Fa "void *ptr"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft void
.Fo CRYPTO_secure_clear_free
.Fa "void *ptr"
.Fa "size_t num"
.Fa "const char *file"
.Fa "int line"
.Fc
.Ft int
.Fo CRYPTO_secure_allocated
.Fa "const void *ptr"
.Fc
.Ft void
.Fo OPENSSL_cleanse
.Fa "void *ptr"
.Fa "size_t len"
.Fc
.Ft unsigned char *
.Fo OPENSSL_hexstr2buf
.Fa "const char *str"
.Fa "long *buflen"
.Fc
.Ft OSSL_CORE_BIO *
.Fo BIO_new_file
.Fa "const char *filename"
.Fa "const char *mode"
.Fc
.Ft OSSL_CORE_BIO *
.Fo BIO_new_membuf
.Fa "const void *buf"
.Fa "int len"
.Fc
.Ft int
.Fo BIO_read_ex
.Fa "OSSL_CORE_BIO *bio"
.Fa "void *data"
.Fa "size_t data_len"
.Fa "size_t *bytes_read"
.Fc
.Ft int
.Fo BIO_write_ex
.Fa "OSSL_CORE_BIO *bio"
.Fa "const void *data"
.Fa "size_t data_len"
.Fa "size_t *written"
.Fc
.Ft int
.Fo BIO_up_ref
.Fa "OSSL_CORE_BIO *bio"
.Fc
.Ft int
.Fo BIO_free
.Fa "OSSL_CORE_BIO *bio"
.Fc
.Ft int
.Fo BIO_vprintf
.Fa "OSSL_CORE_BIO *bio"
.Fa "const char *format"
.Fa "va_list args"
.Fc
.Ft int
.Fo BIO_vsnprintf
.Fa "char *buf"
.Fa "size_t n"
.Fa "const char *fmt"
.Fa "va_list args"
.Fc
.Ft void
.Fo OSSL_SELF_TEST_set_callback
.Fa "OSSL_LIB_CTX *libctx"
.Fa "OSSL_CALLBACK *cb"
.Fa "void *cbarg"
.Fc
.Ft size_t
.Fo get_entropy
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char **pout"
.Fa "int entropy"
.Fa "size_t min_len"
.Fa "size_t max_len"
.Fc
.Ft size_t
.Fo get_user_entropy
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char **pout"
.Fa "int entropy"
.Fa "size_t min_len"
.Fa "size_t max_len"
.Fc
.Ft void
.Fo cleanup_entropy
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char *buf"
.Fa "size_t len"
.Fc
.Ft void
.Fo cleanup_user_entropy
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char *buf"
.Fa "size_t len"
.Fc
.Ft size_t
.Fo get_nonce
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char **pout"
.Fa "size_t min_len"
.Fa "size_t max_len"
.Fa "const void *salt"
.Fa "size_t salt_len"
.Fc
.Ft size_t
.Fo get_user_nonce
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char **pout"
.Fa "size_t min_len"
.Fa "size_t max_len"
.Fa "const void *salt"
.Fa "size_t salt_len"
.Fc
.Ft void
.Fo cleanup_nonce
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char *buf"
.Fa "size_t len"
.Fc
.Ft void
.Fo cleanup_user_nonce
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "unsigned char *buf"
.Fa "size_t len"
.Fc
.Ft /* Functions for querying the providers in the application library context */
 int
.Fo provider_register_child_cb
.Fa "const OSSL_CORE_HANDLE *handle"
.Fa "int (*create_cb)(const OSSL_CORE_HANDLE *provider"
.Fa "void *cbdata)"
.Fa "int (*remove_cb)(const OSSL_CORE_HANDLE *provider"
.Fa "void *cbdata)"
.Fa "int (*global_props_cb)(const char *props"
.Fa "void *cbdata)"
.Fa "void *cbdata"
.Fc
.Ft void
.Fo provider_deregister_child_cb
.Fa "const OSSL_CORE_HANDLE *handle"
.Fc
.Ft const char *
.Fo provider_name
.Fa "const OSSL_CORE_HANDLE *prov"
.Fc
.Ft void *
.Fo provider_get0_provider_ctx
.Fa "const OSSL_CORE_HANDLE *prov"
.Fc
.Ft const OSSL_DISPATCH *
.Fo provider_get0_dispatch
.Fa "const OSSL_CORE_HANDLE *prov"
.Fc
.Ft int
.Fo provider_up_ref
.Fa "const OSSL_CORE_HANDLE *prov"
.Fa "int activate"
.Fc
.Ft int
.Fo provider_free
.Fa "const OSSL_CORE_HANDLE *prov"
.Fa "int deactivate"
.Fc
.Ft /* Functions offered by the provider to libcrypto */
 void
.Fo provider_teardown
.Fa "void *provctx"
.Fc
.Ft const OSSL_ITEM *
.Fo provider_gettable_params
.Fa "void *provctx"
.Fc
.Ft int
.Fo provider_get_params
.Fa "void *provctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft const OSSL_ALGORITHM *
.Fo provider_query_operation
.Fa "void *provctx"
.Fa "int operation_id"
.Fa "const int *no_store"
.Fc
.Ft void
.Fo provider_unquery_operation
.Fa "void *provctx"
.Fa "int operation_id"
.Fa "const OSSL_ALGORITHM *algs"
.Fc
.Ft const OSSL_ITEM *
.Fo provider_get_reason_strings
.Fa "void *provctx"
.Fc
.Ft int
.Fo provider_get_capabilities
.Fa "void *provctx"
.Fa "const char *capability"
.Fa "OSSL_CALLBACK *cb"
.Fa "void *arg"
.Fc
.Ft int
.Fo provider_self_test
.Fa "void *provctx"
.Fc
.Sh DESCRIPTION
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays, in the call of the provider initialization function.
See
.Xr provider 7
for a description of the initialization function.
They are known as "upcalls".
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from a
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn core_gettable_params
has these:
.Bd -literal
 typedef OSSL_PARAM *
     (OSSL_FUNC_core_gettable_params_fn)(const OSSL_CORE_HANDLE *handle);
 static ossl_inline OSSL_NAME_core_gettable_params_fn
     OSSL_FUNC_core_gettable_params(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Pp
For
.Em in
(the
.Xr OSSL_DISPATCH 3
array passed from
.Pa libcrypto
to the provider):
.Bd -literal
 core_gettable_params           OSSL_FUNC_CORE_GETTABLE_PARAMS
 core_get_params                OSSL_FUNC_CORE_GET_PARAMS
 core_thread_start              OSSL_FUNC_CORE_THREAD_START
 core_get_libctx                OSSL_FUNC_CORE_GET_LIBCTX
 core_new_error                 OSSL_FUNC_CORE_NEW_ERROR
 core_set_error_debug           OSSL_FUNC_CORE_SET_ERROR_DEBUG
 core_vset_error                OSSL_FUNC_CORE_VSET_ERROR
 core_set_error_mark            OSSL_FUNC_CORE_SET_ERROR_MARK
 core_clear_last_error_mark     OSSL_FUNC_CORE_CLEAR_LAST_ERROR_MARK
 core_pop_error_to_mark         OSSL_FUNC_CORE_POP_ERROR_TO_MARK
 core_count_to_mark             OSSL_FUNC_CORE_COUNT_TO_MARK
 core_obj_add_sigid             OSSL_FUNC_CORE_OBJ_ADD_SIGID
 core_obj_create                OSSL_FUNC_CORE_OBJ_CREATE
 CRYPTO_malloc                  OSSL_FUNC_CRYPTO_MALLOC
 CRYPTO_zalloc                  OSSL_FUNC_CRYPTO_ZALLOC
 CRYPTO_free                    OSSL_FUNC_CRYPTO_FREE
 CRYPTO_clear_free              OSSL_FUNC_CRYPTO_CLEAR_FREE
 CRYPTO_realloc                 OSSL_FUNC_CRYPTO_REALLOC
 CRYPTO_clear_realloc           OSSL_FUNC_CRYPTO_CLEAR_REALLOC
 CRYPTO_secure_malloc           OSSL_FUNC_CRYPTO_SECURE_MALLOC
 CRYPTO_secure_zalloc           OSSL_FUNC_CRYPTO_SECURE_ZALLOC
 CRYPTO_secure_free             OSSL_FUNC_CRYPTO_SECURE_FREE
 CRYPTO_secure_clear_free       OSSL_FUNC_CRYPTO_SECURE_CLEAR_FREE
 CRYPTO_secure_allocated        OSSL_FUNC_CRYPTO_SECURE_ALLOCATED
 BIO_new_file                   OSSL_FUNC_BIO_NEW_FILE
 BIO_new_mem_buf                OSSL_FUNC_BIO_NEW_MEMBUF
 BIO_read_ex                    OSSL_FUNC_BIO_READ_EX
 BIO_write_ex                   OSSL_FUNC_BIO_WRITE_EX
 BIO_up_ref                     OSSL_FUNC_BIO_UP_REF
 BIO_free                       OSSL_FUNC_BIO_FREE
 BIO_vprintf                    OSSL_FUNC_BIO_VPRINTF
 BIO_vsnprintf                  OSSL_FUNC_BIO_VSNPRINTF
 BIO_puts                       OSSL_FUNC_BIO_PUTS
 BIO_gets                       OSSL_FUNC_BIO_GETS
 BIO_ctrl                       OSSL_FUNC_BIO_CTRL
 OPENSSL_cleanse                OSSL_FUNC_OPENSSL_CLEANSE
 OSSL_SELF_TEST_set_callback    OSSL_FUNC_SELF_TEST_CB
 ossl_rand_get_entropy          OSSL_FUNC_GET_ENTROPY
 ossl_rand_get_user_entropy     OSSL_FUNC_GET_USER_ENTROPY
 ossl_rand_cleanup_entropy      OSSL_FUNC_CLEANUP_ENTROPY
 ossl_rand_cleanup_user_entropy OSSL_FUNC_CLEANUP_USER_ENTROPY
 ossl_rand_get_nonce            OSSL_FUNC_GET_NONCE
 ossl_rand_get_user_nonce       OSSL_FUNC_GET_USER_NONCE
 ossl_rand_cleanup_nonce        OSSL_FUNC_CLEANUP_NONCE
 ossl_rand_cleanup_user_nonce   OSSL_FUNC_CLEANUP_USER_NONCE
 provider_register_child_cb     OSSL_FUNC_PROVIDER_REGISTER_CHILD_CB
 provider_deregister_child_cb   OSSL_FUNC_PROVIDER_DEREGISTER_CHILD_CB
 provider_name                  OSSL_FUNC_PROVIDER_NAME
 provider_get0_provider_ctx     OSSL_FUNC_PROVIDER_GET0_PROVIDER_CTX
 provider_get0_dispatch         OSSL_FUNC_PROVIDER_GET0_DISPATCH
 provider_up_ref                OSSL_FUNC_PROVIDER_UP_REF
 provider_free                  OSSL_FUNC_PROVIDER_FREE
.Ed
.Pp
For
.Em *out
(the
.Xr OSSL_DISPATCH 3
array passed from the provider to
.Pa libcrypto Ns ):
.Bd -literal
 provider_teardown              OSSL_FUNC_PROVIDER_TEARDOWN
 provider_gettable_params       OSSL_FUNC_PROVIDER_GETTABLE_PARAMS
 provider_get_params            OSSL_FUNC_PROVIDER_GET_PARAMS
 provider_query_operation       OSSL_FUNC_PROVIDER_QUERY_OPERATION
 provider_unquery_operation     OSSL_FUNC_PROVIDER_UNQUERY_OPERATION
 provider_get_reason_strings    OSSL_FUNC_PROVIDER_GET_REASON_STRINGS
 provider_get_capabilities      OSSL_FUNC_PROVIDER_GET_CAPABILITIES
 provider_self_test             OSSL_FUNC_PROVIDER_SELF_TEST
.Ed
.Ss Core functions
.Fn core_gettable_params
returns a constant array of descriptor
.Xr OSSL_PARAM 3 ,
for parameters that
.Fn core_get_params
can handle.
.Pp
.Fn core_get_params
retrieves parameters from the core for the given
.Fa handle .
See
.Sx Core parameters
below for a description of currently known parameters.
.Pp
The
.Fn core_thread_start
function informs the core that the provider has stated an interest in
the current thread.
The core will inform the provider when the thread eventually stops.
It must be passed the
.Fa handle
for this provider, as well as a callback
.Fa handfn
which will be called when the thread stops.
The callback will subsequently be called, with the supplied argument
.Fa arg ,
from the thread that is stopping and gets passed the provider context as
an argument.
This may be useful to perform thread specific clean up such as freeing
thread local variables.
.Pp
.Fn core_get_libctx
retrieves the core context in which the library object for the current
provider is stored, accessible through the
.Fa handle .
This function is useful only for built-in providers such as the default
provider.
Never cast this to OSSL_LIB_CTX in a provider that is not built-in as
the OSSL_LIB_CTX of the library loading the provider might be a
completely different structure than the OSSL_LIB_CTX of the library the
provider is linked to.
Use
.Xr OSSL_LIB_CTX_new_child 3
instead to obtain a proper library context that is linked to the
application library context.
.Pp
.Fn core_new_error ,
.Fn core_set_error_debug
and
.Fn core_vset_error
are building blocks for reporting an error back to the core, with
reference to the
.Fa handle .
.Bl -tag -width Ds
.It core_new_error()
allocates a new thread specific error record.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_new 3 .
.It core_set_error_debug()
sets debugging information in the current thread specific error record.
The debugging information includes the name of the file
.Fa file ,
the line
.Fa line
and the function name
.Fa func
where the error occurred.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_set_debug 3 .
.It core_vset_error()
sets the
.Fa reason
for the error, along with any addition data.
The
.Fa reason
is a number defined by the provider and used to index the reason strings
table that's returned by
.Fn provider_get_reason_strings .
The additional data is given as a format string
.Fa fmt
and a set of arguments
.Fa args ,
which are treated in the same manner as with
.Fn BIO_vsnprintf .
.Fa file
and
.Fa line
may also be passed to indicate exactly where the error occurred or was
reported.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_vset_error 3 .
.It core_set_error_mark()
sets a mark on the current topmost error record if there is one.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_set_mark 3 .
.It core_clear_last_error_mark()
removes the last mark added if there is one.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_clear_last_mark 3 .
.It core_pop_error_to_mark()
pops the top of the error stack until a mark is found.
The mark is then removed.
If there is no mark, the whole stack is removed.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_pop_to_mark 3 .
.It core_count_to_mark()
returns the number of entries on the error stack above the most recently
marked entry, not including that entry.
If there is no mark in the error stack, the number of entries in the
error stack is returned.
.Pp
This corresponds to the OpenSSL function
.Xr ERR_count_to_mark 3 .
.El
.Pp
The
.Fn core_obj_create
function registers a new OID and associated short name
.Fa sn
and long name
.Fa ln
for the given
.Fa handle .
It is similar to the OpenSSL function
.Xr OBJ_create 3
except that it returns 1 on success or 0 on failure.
It will treat as success the case where the OID already exists (even if
the short name
.Fa sn
or long name
.Fa ln
provided as arguments differ from those associated with the existing
OID, in which case the new names are not associated).
.Pp
The
.Fn core_obj_add_sigid
function registers a new composite signature algorithm
.Pf ( Fa sign_name )
consisting of an underlying signature algorithm
.Pf ( Fa pkey_name )
and digest algorithm
.Pf ( Fa digest_name )
for the given
.Fa handle .
It assumes that the OIDs for the composite signature algorithm as well
as for the underlying signature and digest algorithms are either already
known to OpenSSL or have been registered via a call to
.Fn core_obj_create .
It corresponds to the OpenSSL function
.Xr OBJ_add_sigid 3 ,
except that the objects are identified by name rather than a numeric
NID. Any name (OID, short name or long name) can be used to identify the
object.
It will treat as success the case where the composite signature
algorithm already exists (even if registered against a different
underlying signature or digest algorithm).
For
.Fa digest_name ,
NULL or an empty string is permissible for signature algorithms that do
not need a digest to operate correctly.
The function returns 1 on success or 0 on failure.
.Pp
.Fn CRYPTO_malloc ,
.Fn CRYPTO_zalloc ,
.Fn CRYPTO_free ,
.Fn CRYPTO_clear_free ,
.Fn CRYPTO_realloc ,
.Fn CRYPTO_clear_realloc ,
.Fn CRYPTO_secure_malloc ,
.Fn CRYPTO_secure_zalloc ,
.Fn CRYPTO_secure_free ,
.Fn CRYPTO_secure_clear_free ,
.Fn CRYPTO_secure_allocated ,
.Fn BIO_new_file ,
.Xr BIO_new_mem_buf 3 ,
.Fn BIO_read_ex ,
.Fn BIO_write_ex ,
.Fn BIO_up_ref ,
.Fn BIO_free ,
.Fn BIO_vprintf ,
.Fn BIO_vsnprintf ,
.Xr BIO_gets 3 ,
.Xr BIO_puts 3 ,
.Xr BIO_ctrl 3 ,
.Fn OPENSSL_cleanse
and
.Fn OPENSSL_hexstr2buf
correspond exactly to the public functions with the same name.
As a matter of fact, the pointers in the
.Xr OSSL_DISPATCH 3
array are typically direct pointers to those public functions.
Note that the BIO functions take an
.Vt OSSL_CORE_BIO
type rather than the standard
.Sy BIO
type.
This is to ensure that a provider does not mix BIOs from the core with
BIOs used on the provider side (the two are not compatible).
.Fn OSSL_SELF_TEST_set_callback
is used to set an optional callback that can be passed into a provider.
This may be ignored by a provider.
.Pp
.Fn get_entropy
retrieves seeding material from the operating system.
The seeding material will have at least
.Fa entropy
bytes of randomness and the output will have at least
.Fa min_len
and at most
.Fa max_len
bytes.
The buffer address is stored in
.Em *pout
and the buffer length is returned to the caller.
On error, zero is returned.
.Pp
.Fn get_user_entropy
is the same as
.Fn get_entropy
except that it will attempt to gather seed material via the seed source
specified by a call to
.Xr RAND_set_seed_source_type 3
or via
.Xr config 5 .
.Pp
.Fn cleanup_entropy
is used to clean up and free the buffer returned by
.Fn get_entropy .
The entropy pointer returned by
.Fn get_entropy
is passed in
.Fa buf
and its length in
.Fa len .
.Pp
.Fn cleanup_user_entropy
is used to clean up and free the buffer returned by
.Fn get_user_entropy .
The entropy pointer returned by
.Fn get_user_entropy
is passed in
.Fa buf
and its length in
.Fa len .
.Pp
.Fn get_nonce
retrieves a nonce using the passed
.Fa salt
parameter of length
.Fa salt_len
and operating system specific information.
The
.Fa salt
should contain uniquely identifying information and this is included, in
an unspecified manner, as part of the output.
The output is stored in a buffer which contains at least
.Fa min_len
and at most
.Fa max_len
bytes.
The buffer address is stored in
.Em *pout
and the buffer length returned to the caller.
On error, zero is returned.
.Pp
.Fn get_user_nonce
is the same as
.Fn get_nonce
except that it will attempt to gather seed material via the seed source
specified by a call to
.Xr RAND_set_seed_source_type 3
or via
.Xr config 5 .
.Pp
.Fn cleanup_nonce
is used to clean up and free the buffer returned by
.Fn get_nonce .
The nonce pointer returned by
.Fn get_nonce
is passed in
.Fa buf
and its length in
.Fa len .
.Pp
.Fn cleanup_user_nonce
is used to clean up and free the buffer returned by
.Fn get_user_nonce .
The nonce pointer returned by
.Fn get_user_nonce
is passed in
.Fa buf
and its length in
.Fa len .
.Pp
.Fn provider_register_child_cb
registers callbacks for being informed about the loading and unloading
of providers in the application's library context.
.Fa handle
is this provider's handle and
.Fa cbdata
is this provider's data that will be passed back to the callbacks.
It returns 1 on success or 0 otherwise.
These callbacks may be called while holding locks in libcrypto.
In order to avoid deadlocks the callback implementation must not be long
running and must not call other OpenSSL API functions or upcalls.
.Pp
.Em create_cb
is a callback that will be called when a new provider is loaded into the
application's library context.
It is also called for any providers that are already loaded at the point
that this callback is registered.
The callback is passed the handle being used for the new provider being
loadded and this provider's data in
.Fa cbdata .
It should return 1 on success or 0 on failure.
.Pp
.Em remove_cb
is a callback that will be called when a new provider is unloaded from
the application's library context.
It is passed the handle being used for the provider being unloaded and
this provider's data in
.Fa cbdata .
It should return 1 on success or 0 on failure.
.Pp
.Em global_props_cb
is a callback that will be called when the global properties from the
parent library context are changed.
It should return 1 on success or 0 on failure.
.Pp
.Fn provider_deregister_child_cb
unregisters callbacks previously registered via
.Fn provider_register_child_cb .
If
.Fn provider_register_child_cb
has been called then
.Fn provider_deregister_child_cb
should be called at or before the point that this provider's teardown
function is called.
.Pp
.Fn provider_name
returns a string giving the name of the provider identified by
.Fa handle .
.Pp
.Fn provider_get0_provider_ctx
returns the provider context that is associated with the provider
identified by
.Fa prov .
.Pp
.Fn provider_get0_dispatch
gets the dispatch table registered by the provider identified by
.Fa prov
when it initialised.
.Pp
.Fn provider_up_ref
increments the reference count on the provider
.Fa prov .
If
.Fa activate
is nonzero then the provider is also loaded if it is not already loaded.
It returns 1 on success or 0 on failure.
.Pp
.Fn provider_free
decrements the reference count on the provider
.Fa prov .
If
.Fa deactivate
is nonzero then the provider is also unloaded if it is not already
loaded.
It returns 1 on success or 0 on failure.
.Ss Provider functions
.Fn provider_teardown
is called when a provider is shut down and removed from the core's
provider store.
It must free the passed
.Fa provctx .
.Pp
.Fn provider_gettable_params
should return a constant array of descriptor
.Xr OSSL_PARAM 3 ,
for parameters that
.Fn provider_get_params
can handle.
.Pp
.Fn provider_get_params
should process the
.Xr OSSL_PARAM 3
array
.Em params ,
setting the values of the parameters it understands.
.Pp
.Fn provider_query_operation
should return a constant
.Xr OSSL_ALGORITHM 3
that corresponds to the given
.Fa operation_id .
It should indicate if the core may store a reference to this array by
setting
.Em *no_store
to 0 (core may store a reference) or 1 (core may not store a reference).
.Pp
.Fn provider_unquery_operation
informs the provider that the result of a
.Fn provider_query_operation
is no longer directly required and that the function pointers have been
copied.
The
.Fa operation_id
should match that passed to
.Fn provider_query_operation
and
.Fa algs
should be its return value.
.Pp
.Fn provider_get_reason_strings
should return a constant
.Xr OSSL_ITEM 3
array that provides reason strings for reason codes the provider may use
when reporting errors using
.Xr core_put_error 3 .
.Pp
The
.Fn provider_get_capabilities
function should call the callback
.Fa cb
passing it a set of
.Xr OSSL_PARAM 3 Ns s
and the caller supplied argument
.Fa arg .
The
.Xr OSSL_PARAM 3 Ns s
should provide details about the capability with the name given in the
.Fa capability
argument relevant for the provider context
.Fa provctx .
If a provider supports multiple capabilities with the given name then it
may call the callback multiple times (one for each capability).
Capabilities can be useful for describing the services that a provider
can offer.
For further details see the
.Sx CAPABILITIES
section below.
It should return 1 on success or 0 on error.
.Pp
The
.Fn provider_self_test
function should perform known answer tests on a subset of the algorithms
that it uses, and may also verify the integrity of the provider module.
It should return 1 on success or 0 on error.
It will return 1 if this function is not used.
.Pp
None of these functions are mandatory, but a provider is fairly useless
without at least
.Fn provider_query_operation ,
and
.Fn provider_gettable_params
is fairly useless if not accompanied by
.Fn provider_get_params .
.Ss Provider parameters
.Fn provider_get_params
can return the following provider parameters to the core:
.Bl -tag -width Ds
.It \(dqname" ( Ns Sy OSSL_PROV_PARAM_NAME Ns ) <UTF8 ptr>
This points to a string that should give a unique name for the provider.
.It \(dqversion" ( Ns Sy OSSL_PROV_PARAM_VERSION Ns ) <UTF8 ptr>
This points to a string that is a version number associated with this
provider.
OpenSSL in-built providers use OPENSSL_VERSION_STR, but this may be
different for any third party provider.
This string is for informational purposes only.
.It \(dqbuildinfo" ( Ns Sy OSSL_PROV_PARAM_BUILDINFO Ns ) <UTF8 ptr>
This points to a string that is a build information associated with this
provider.
OpenSSL in-built providers use OPENSSL_FULL_VERSION_STR, but this may be
different for any third party provider.
.It \(dqstatus" ( Ns Sy OSSL_PROV_PARAM_STATUS Ns ) <unsigned integer>
This returns 0 if the provider has entered an error state, otherwise it
returns 1.
.El
.Pp
.Fn provider_gettable_params
should return the above parameters.
.Ss Core parameters
.Fn core_get_params
can retrieve the following core parameters for each provider:
.Bl -tag -width Ds
.It \(dqopenssl-version" ( Ns Sy OSSL_PROV_PARAM_CORE_VERSION Ns ) <UTF8 string ptr>
This points to the OpenSSL libraries' full version string, i.e.
the string expanded from the macro
.Sy OPENSSL_VERSION_STR .
.It \(dqprovider-name" ( Ns Sy OSSL_PROV_PARAM_CORE_PROV_NAME Ns ) <UTF8 string ptr>
This points to the OpenSSL libraries' idea of what the calling provider
is named.
.It \(dqmodule-filename" ( Ns Sy OSSL_PROV_PARAM_CORE_MODULE_FILENAME Ns ) <UTF8 string ptr>
This points to a string containing the full filename of the providers
module file.
.El
.Pp
Additionally, provider specific configuration parameters from the config
file are available, in dotted name form.
The dotted name form is a concatenation of section names and final
config command name separated by periods.
.Pp
For example, let's say we have the following config example:
.Bd -literal
 config_diagnostics = 1
 openssl_conf = openssl_init

 [openssl_init]
 providers = providers_sect

 [providers_sect]
 foo = foo_sect

 [foo_sect]
 activate = 1
 data1 = 2
 data2 = str
 more = foo_more

 [foo_more]
 data3 = foo,bar
.Ed
.Pp
The provider will have these additional parameters available:
.Bl -tag -width Ds
.It \(dqactivate"
pointing at the string "1"
.It \(dqdata1"
pointing at the string "2"
.It \(dqdata2"
pointing at the string "str"
.It \(dqmore.data3"
pointing at the string "foo,bar"
.El
.Pp
For more information on handling parameters, see
.Xr OSSL_PARAM 3
as
.Xr OSSL_PARAM_int 3 .
.Sh CAPABILITIES
Capabilities describe some of the services that a provider can offer.
Applications can query the capabilities to discover those services.
.Pp
.Em \(dqTLS-GROUP" Capability
.Pp
The "TLS-GROUP" capability can be queried by libssl to discover the list
of TLS groups that a provider can support.
Each group supported can be used for
.Em key exchange
(KEX) or
.Em key encapsulation method
(KEM) during a TLS handshake.
TLS clients can advertise the list of TLS groups they support in the
supported_groups extension, and TLS servers can select a group from the
offered list that they also support.
In this way a provider can add to the list of groups that libssl already
supports with additional ones.
.Pp
Each TLS group that a provider supports should be described via the
callback passed in through the provider_get_capabilities function.
Each group should have the following details supplied (all are
mandatory, except
.Sy OSSL_CAPABILITY_TLS_GROUP_IS_KEM Ns ):
.Bl -tag -width Ds
.It \(dqtls-group-name" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_NAME Ns ) <UTF8 string>
The name of the group as given in the IANA TLS Supported Groups registry
.Lk https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8 .
.It \(dqtls-group-name-internal" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_NAME_INTERNAL Ns ) <UTF8 string>
The name of the group as known by the provider.
This could be the same as the "tls-group-name", but does not have to be.
.It \(dqtls-group-id" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_ID Ns ) <unsigned integer>
The TLS group id value as given in the IANA TLS Supported Groups
registry.
.Pp
It is possible to register the same group id from within different
providers.
Users should note that if no property query is specified, or more than
one implementation matches the property query then it is unspecified
which implementation for a particular group id will be used.
.It \(dqtls-group-alg" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_ALG Ns ) <UTF8 string>
The name of a Key Management algorithm that the provider offers and that
should be used with this group.
Keys created should be able to support
.Em key exchange
or
.Em key encapsulation method
(KEM), as implied by the optional
.Sy OSSL_CAPABILITY_TLS_GROUP_IS_KEM
flag.
The algorithm must support key and parameter generation as well as the
key/parameter generation parameter,
.Sy OSSL_PKEY_PARAM_GROUP_NAME .
The group name given via "tls-group-name-internal" above will be passed
via
.Sy OSSL_PKEY_PARAM_GROUP_NAME
when libssl wishes to generate keys/parameters.
.It \(dqtls-group-sec-bits" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_SECURITY_BITS Ns ) <unsigned integer>
The number of bits of security offered by keys in this group.
The number of bits should be comparable with the ones given in table 2
and 3 of the NIST SP800-57 document.
.It \(dqtls-group-is-kem" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_IS_KEM Ns ) <unsigned integer>
Boolean flag to describe if the group should be used in
.Em key exchange
(KEX) mode (0, default) or in
.Em key encapsulation method
(KEM) mode (1).
.Pp
This parameter is optional: if not specified, KEX mode is assumed as the
default mode for the group.
.Pp
In KEX mode, in a typical Diffie-Hellman fashion, both sides execute
.Em keygen
then
.Em derive
against the peer public key.
To operate in KEX mode, the group implementation must support the
provider functions as described in
.Xr provider-keyexch 7 .
.Pp
In KEM mode, the client executes
.Em keygen
and sends its public key, the server executes
.Em encapsulate
using the client's public key and sends back the resulting
.Em ciphertext ,
finally the client executes
.Em decapsulate
to retrieve the same
.Em shared secret
generated by the server's
.Em encapsulate .
To operate in KEM mode, the group implementation must support the
provider functions as described in
.Xr provider-kem 7 .
.Pp
Both in KEX and KEM mode, the resulting
.Em shared secret
is then used according to the protocol specification.
.It \(dqtls-min-tls" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_MIN_TLS Ns ) <integer>
.It \(dqtls-max-tls" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_MAX_TLS Ns ) <integer>
.It \(dqtls-min-dtls" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_MIN_DTLS Ns ) <integer>
.It \(dqtls-max-dtls" ( Ns Sy OSSL_CAPABILITY_TLS_GROUP_MAX_DTLS Ns ) <integer>
These parameters can be used to describe the minimum and maximum TLS and
DTLS versions supported by the group.
The values equate to the on-the-wire encoding of the various TLS
versions.
For example TLSv1.3 is 0x0304 (772 decimal), and TLSv1.2 is 0x0303 (771
decimal).
A 0 indicates that there is no defined minimum or maximum.
A -1 indicates that the group should not be used in that protocol.
.El
.Pp
.Em \(dqTLS-SIGALG" Capability
.Pp
The "TLS-SIGALG" capability can be queried by libssl to discover the
list of TLS signature algorithms that a provider can support.
Each signature supported can be used for client- or
server-authentication in addition to the built-in signature algorithms.
TLS1.3 clients can advertise the list of TLS signature algorithms they
support in the signature_algorithms extension, and TLS servers can
select an algorithm from the offered list that they also support.
In this way a provider can add to the list of signature algorithms that
libssl already supports with additional ones.
.Pp
Each TLS signature algorithm that a provider supports should be
described via the callback passed in through the
provider_get_capabilities function.
Each algorithm can have the following details supplied:
.Bl -tag -width Ds
.It \(dqiana-name" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_IANA_NAME Ns ) <UTF8 string>
The name of the signature algorithm as given in the IANA TLS Signature
Scheme registry as "Description":
.Lk https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme .
This value must be supplied.
.It \(dqiana-code-point" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_CODE_POINT Ns ) <unsigned integer>
The TLS algorithm ID value as given in the IANA TLS SignatureScheme
registry.
This value must be supplied.
.Pp
It is possible to register the same code point from within different
providers.
Users should note that if no property query is specified, or more than
one implementation matches the property query then it is unspecified
which implementation for a particular code point will be used.
.It \(dqsigalg-name" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_NAME Ns ) <UTF8 string>
A name for the full (possibly composite hash-and-signature) signature
algorithm.
The provider may, but is not obligated to, provide a signature
implementation with this name; if it doesn't, this is assumed to be a
composite of a pure signature algorithm and a hash algorithm, which must
be given with the parameters "sig-name" and "hash-name".
This value must be supplied.
.It \(dqsigalg-oid" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_OID Ns ) <UTF8 string>
The OID of the "sigalg-name" algorithm in canonical numeric text form.
If this parameter is given,
.Xr OBJ_create 3
will be used to create an OBJ and a NID for this OID, using the
"sigalg-name" parameter for its (short) name.
Otherwise, it's assumed to already exist in the object database,
possibly done by the provider with the
.Fn core_obj_create
upcall.
This value is optional.
.It \(dqsig-name" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_SIG_NAME Ns ) <UTF8 string>
The name of the pure signature algorithm that is part of a composite
"sigalg-name".
If "sigalg-name" is implemented by the provider, this parameter is
redundant and must not be given.
This value is optional.
.It \(dqsig-oid" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_SIG_OID Ns ) <UTF8 string>
The OID of the "sig-name" algorithm in canonical numeric text form.
If this parameter is given,
.Xr OBJ_create 3
will be used to create an OBJ and a NID for this OID, using the
"sig-name" parameter for its (short) name.
Otherwise, it is assumed to already exist in the object database.
This can be done by the provider using the
.Fn core_obj_create
upcall.
This value is optional.
.It \(dqhash-name" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_HASH_NAME Ns ) <UTF8 string>
The name of the hash algorithm that is part of a composite
"sigalg-name".
If "sigalg-name" is implemented by the provider, this parameter is
redundant and must not be given.
This value is optional.
.It \(dqhash-oid" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_HASH_OID Ns ) <UTF8 string>
The OID of the "hash-name" algorithm in canonical numeric text form.
If this parameter is given,
.Xr OBJ_create 3
will be used to create an OBJ and a NID for this OID, using the
"hash-name" parameter for its (short) name.
Otherwise, it's assumed to already exist in the object database,
possibly done by the provider with the
.Fn core_obj_create
upcall.
This value is optional.
.It \(dqkey-type" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_KEYTYPE Ns ) <UTF8 string>
The key type of the public key of applicable certificates.
If this parameter isn't present, it's assumed to be the same as
"sig-name" if that's present, otherwise "sigalg-name".
This value is optional.
.It \(dqkey-type-oid" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_KEYTYPE_OID Ns ) <UTF8 string>
The OID of the "key-type" in canonical numeric text form.
If this parameter is given,
.Xr OBJ_create 3
will be used to create an OBJ and a NID for this OID, using the
"key-type" parameter for its (short) name.
Otherwise, it's assumed to already exist in the object database,
possibly done by the provider with the
.Fn core_obj_create
upcall.
This value is optional.
.It \(dqsec-bits" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_SECURITY_BITS Ns ) <unsigned integer>
The number of bits of security offered by keys of this algorithm.
The number of bits should be comparable with the ones given in table 2
and 3 of the NIST SP800-57 document.
This number is used to determine the security strength of the algorithm
if no digest algorithm has been registered that otherwise defines the
security strength.
If the signature algorithm implements its own digest internally, this
value needs to be set to properly reflect the overall security strength.
This value must be supplied.
.It \(dqtls-min-tls" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_MIN_TLS Ns ) <integer>
.It \(dqtls-max-tls" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_MAX_TLS Ns ) <integer>
.It \(dqtls-min-dtls" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_MIN_DTLS Ns ) <integer>
.It \(dqtls-max-dtls" ( Ns Sy OSSL_CAPABILITY_TLS_SIGALG_MAX_DTLS Ns ) <integer>
These parameters can be used to describe the minimum and maximum TLS and
DTLS versions supported by the signature algorithm.
The values equate to the on-the-wire encoding of the various TLS
versions.
For example TLSv1.3 is 0x0304 (772 decimal), and TLSv1.2 is 0x0303 (771
decimal).
A 0 indicates that there is no defined minimum or maximum.
A -1 in either the min or max field indicates that the signature
algorithm should not be used in that protocol.
Presently, provider signature algorithms are used only with TLS 1.3, if
that's enclosed in the specified range.
.El
.Sh NOTES
The
.Fn core_obj_create
and
.Fn core_obj_add_sigid
functions were not thread safe in OpenSSL 3.0.
.Sh EXAMPLES
This is an example of a simple provider made available as a dynamically
loadable module.
It implements the fictitious algorithm
.Qo Li FOO Qc
for the fictitious operation
.Qo Li BAR Qc .
.Bd -literal
 #include <malloc.h>
 #include <openssl/core.h>
 #include <openssl/core_dispatch.h>

 /* Errors used in this provider */
 #define E_MALLOC       1

 static const OSSL_ITEM reasons[] = {
     { E_MALLOC, "memory allocation failure" }.
     OSSL_DISPATCH_END
 };

 /*
  * To ensure we get the function signature right, forward declare
  * them using function types provided by openssl/core_dispatch.h
  */
 OSSL_FUNC_bar_newctx_fn foo_newctx;
 OSSL_FUNC_bar_freectx_fn foo_freectx;
 OSSL_FUNC_bar_init_fn foo_init;
 OSSL_FUNC_bar_update_fn foo_update;
 OSSL_FUNC_bar_final_fn foo_final;

 OSSL_FUNC_provider_query_operation_fn p_query;
 OSSL_FUNC_provider_get_reason_strings_fn p_reasons;
 OSSL_FUNC_provider_teardown_fn p_teardown;

 OSSL_provider_init_fn OSSL_provider_init;

 OSSL_FUNC_core_put_error *c_put_error = NULL;

 /* Provider context */
 struct prov_ctx_st {
     OSSL_CORE_HANDLE *handle;
 }

 /* operation context for the algorithm FOO */
 struct foo_ctx_st {
     struct prov_ctx_st *provctx;
     int b;
 };

 static void *foo_newctx(void *provctx)
 {
     struct foo_ctx_st *fooctx = malloc(sizeof(*fooctx));

     if (fooctx != NULL)
         fooctx->provctx = provctx;
     else
         c_put_error(provctx->handle, E_MALLOC, __FILE__, __LINE__);
     return fooctx;
 }

 static void foo_freectx(void *fooctx)
 {
     free(fooctx);
 }

 static int foo_init(void *vfooctx)
 {
     struct foo_ctx_st *fooctx = vfooctx;

     fooctx->b = 0x33;
 }

 static int foo_update(void *vfooctx, unsigned char *in, size_t inl)
 {
     struct foo_ctx_st *fooctx = vfooctx;

     /* did you expect something serious? */
     if (inl == 0)
         return 1;
     for (; inl-- > 0; in++)
         *in ^= fooctx->b;
     return 1;
 }

 static int foo_final(void *vfooctx)
 {
     struct foo_ctx_st *fooctx = vfooctx;

     fooctx->b = 0x66;
 }

 static const OSSL_DISPATCH foo_fns[] = {
     { OSSL_FUNC_BAR_NEWCTX, (void (*)(void))foo_newctx },
     { OSSL_FUNC_BAR_FREECTX, (void (*)(void))foo_freectx },
     { OSSL_FUNC_BAR_INIT, (void (*)(void))foo_init },
     { OSSL_FUNC_BAR_UPDATE, (void (*)(void))foo_update },
     { OSSL_FUNC_BAR_FINAL, (void (*)(void))foo_final },
     OSSL_DISPATCH_END
 };

 static const OSSL_ALGORITHM bars[] = {
     { "FOO", "provider=chumbawamba", foo_fns },
     { NULL, NULL, NULL }
 };

 static const OSSL_ALGORITHM *p_query(void *provctx, int operation_id,
                                      int *no_store)
 {
     switch (operation_id) {
     case OSSL_OP_BAR:
         return bars;
     }
     return NULL;
 }

 static const OSSL_ITEM *p_reasons(void *provctx)
 {
     return reasons;
 }

 static void p_teardown(void *provctx)
 {
     free(provctx);
 }

 static const OSSL_DISPATCH prov_fns[] = {
     { OSSL_FUNC_PROVIDER_TEARDOWN, (void (*)(void))p_teardown },
     { OSSL_FUNC_PROVIDER_QUERY_OPERATION, (void (*)(void))p_query },
     { OSSL_FUNC_PROVIDER_GET_REASON_STRINGS, (void (*)(void))p_reasons },
     OSSL_DISPATCH_END
 };

 int OSSL_provider_init(const OSSL_CORE_HANDLE *handle,
                        const OSSL_DISPATCH *in,
                        const OSSL_DISPATCH **out,
                        void **provctx)
 {
     struct prov_ctx_st *pctx = NULL;

     for (; in->function_id != 0; in++)
         switch (in->function_id) {
         case OSSL_FUNC_CORE_PUT_ERROR:
             c_put_error = OSSL_FUNC_core_put_error(in);
             break;
         }

     *out = prov_fns;

     if ((pctx = malloc(sizeof(*pctx))) == NULL) {
         /*
          * ALEA IACTA EST, if the core retrieves the reason table
          * regardless, that string will be displayed, otherwise not.
          */
         c_put_error(handle, E_MALLOC, __FILE__, __LINE__);
         return 0;
     }
     pctx->handle = handle;
     return 1;
 }
.Ed
.Pp
This relies on a few things existing in
.Pa openssl/core_dispatch.h :
.Bd -literal
 #define OSSL_OP_BAR            4711

 #define OSSL_FUNC_BAR_NEWCTX      1
 typedef void *(OSSL_FUNC_bar_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_bar_newctx(const OSSL_DISPATCH *opf)
 { return (OSSL_FUNC_bar_newctx_fn *)opf->function; }

 #define OSSL_FUNC_BAR_FREECTX     2
 typedef void (OSSL_FUNC_bar_freectx_fn)(void *ctx);
 static ossl_inline OSSL_FUNC_bar_freectx(const OSSL_DISPATCH *opf)
 { return (OSSL_FUNC_bar_freectx_fn *)opf->function; }

 #define OSSL_FUNC_BAR_INIT        3
 typedef void *(OSSL_FUNC_bar_init_fn)(void *ctx);
 static ossl_inline OSSL_FUNC_bar_init(const OSSL_DISPATCH *opf)
 { return (OSSL_FUNC_bar_init_fn *)opf->function; }

 #define OSSL_FUNC_BAR_UPDATE      4
 typedef void *(OSSL_FUNC_bar_update_fn)(void *ctx,
                                       unsigned char *in, size_t inl);
 static ossl_inline OSSL_FUNC_bar_update(const OSSL_DISPATCH *opf)
 { return (OSSL_FUNC_bar_update_fn *)opf->function; }

 #define OSSL_FUNC_BAR_FINAL       5
 typedef void *(OSSL_FUNC_bar_final_fn)(void *ctx);
 static ossl_inline OSSL_FUNC_bar_final(const OSSL_DISPATCH *opf)
 { return (OSSL_FUNC_bar_final_fn *)opf->function; }
.Ed
.Sh SEE ALSO
.Xr provider 7
.Sh HISTORY
The concept of providers and everything surrounding them was introduced
in OpenSSL 3.0.
.Pp
Definitions for
.Sy OSSL_CAPABILITY_TLS_SIGALG_MIN_DTLS
and
.Sy OSSL_CAPABILITY_TLS_SIGALG_MAX_DTLS
were added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
