.Dd 2025-09-30
.Dt PROVIDER-KEYEXCH 7ossl
.Os
.Sh NAME
.Nm provider-keyexch
.Nd The keyexch library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Context management */
 void *
.Fo OSSL_FUNC_keyexch_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_keyexch_freectx
.Fa "void *ctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_keyexch_dupctx
.Fa "void *ctx"
.Fc
.Ft /* Shared secret derivation */
 int
.Fo OSSL_FUNC_keyexch_init
.Fa "void *ctx"
.Fa "void *provkey"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_keyexch_set_peer
.Fa "void *ctx"
.Fa "void *provkey"
.Fc
.Ft int
.Fo OSSL_FUNC_keyexch_derive
.Fa "void *ctx"
.Fa "unsigned char *secret"
.Fa "size_t *secretlen"
.Fa "size_t outlen"
.Fc
.Ft /* Key Exchange parameters */
 int
.Fo OSSL_FUNC_keyexch_set_ctx_params
.Fa "void *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keyexch_settable_ctx_params
.Fa "void *ctx"
.Fa "void *provctx"
.Fc
.Ft int
.Fo OSSL_FUNC_keyexch_get_ctx_params
.Fa "void *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keyexch_gettable_ctx_params
.Fa "void *ctx"
.Fa "void *provctx"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The key exchange (OSSL_OP_KEYEXCH) operation enables providers to
implement key exchange algorithms and make them available to
applications via
.Xr EVP_PKEY_derive 3
and other related functions).
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_keyexch_newctx
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_keyexch_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_keyexch_newctx_fn
     OSSL_FUNC_keyexch_newctx(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_keyexch_newctx                OSSL_FUNC_KEYEXCH_NEWCTX
 OSSL_FUNC_keyexch_freectx               OSSL_FUNC_KEYEXCH_FREECTX
 OSSL_FUNC_keyexch_dupctx                OSSL_FUNC_KEYEXCH_DUPCTX

 OSSL_FUNC_keyexch_init                  OSSL_FUNC_KEYEXCH_INIT
 OSSL_FUNC_keyexch_set_peer              OSSL_FUNC_KEYEXCH_SET_PEER
 OSSL_FUNC_keyexch_derive                OSSL_FUNC_KEYEXCH_DERIVE

 OSSL_FUNC_keyexch_set_ctx_params        OSSL_FUNC_KEYEXCH_SET_CTX_PARAMS
 OSSL_FUNC_keyexch_settable_ctx_params   OSSL_FUNC_KEYEXCH_SETTABLE_CTX_PARAMS
 OSSL_FUNC_keyexch_get_ctx_params        OSSL_FUNC_KEYEXCH_GET_CTX_PARAMS
 OSSL_FUNC_keyexch_gettable_ctx_params   OSSL_FUNC_KEYEXCH_GETTABLE_CTX_PARAMS
.Ed
.Pp
A key exchange algorithm implementation may not implement all of these
functions.
In order to be a consistent set of functions a provider must implement
OSSL_FUNC_keyexch_newctx, OSSL_FUNC_keyexch_freectx,
OSSL_FUNC_keyexch_init and OSSL_FUNC_keyexch_derive.
All other functions are optional.
.Pp
A key exchange algorithm must also implement some mechanism for
generating, loading or importing keys via the key management
(OSSL_OP_KEYMGMT) operation.
See
.Xr provider-keymgmt 7
for further details.
.Ss Context Management Functions
.Fn OSSL_FUNC_keyexch_newctx
should create and return a pointer to a provider side structure for
holding context information during a key exchange operation.
A pointer to this context will be passed back in a number of the other
key exchange operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
.Pp
.Fn OSSL_FUNC_keyexch_freectx
is passed a pointer to the provider side key exchange context in the
.Fa ctx
parameter.
This function should free any resources associated with that context.
.Pp
.Fn OSSL_FUNC_keyexch_dupctx
should duplicate the provider side key exchange context in the
.Fa ctx
parameter and return the duplicate copy.
.Ss Shared Secret Derivation Functions
.Fn OSSL_FUNC_keyexch_init
initialises a key exchange operation given a provider side key exchange
context in the
.Fa ctx
parameter, and a pointer to a provider key object in the
.Fa provkey
parameter.
The
.Em params ,
if not NULL, should be set on the context in a manner similar to using
.Xr OSSL_FUNC_keyexch_set_params 3 .
The key object should have been previously generated, loaded or imported
into the provider using the key management (OSSL_OP_KEYMGMT) operation
(see provider-keymgmt(7)>.
.Pp
.Fn OSSL_FUNC_keyexch_set_peer
is called to supply the peer's public key (in the
.Fa provkey
parameter) to be used when deriving the shared secret.
It is also passed a previously initialised key exchange context in the
.Fa ctx
parameter.
The key object should have been previously generated, loaded or imported
into the provider using the key management (OSSL_OP_KEYMGMT) operation
(see provider-keymgmt(7)>.
.Pp
.Fn OSSL_FUNC_keyexch_derive
performs the actual key exchange itself by deriving a shared secret.
A previously initialised key exchange context is passed in the
.Fa ctx
parameter.
The derived secret should be written to the location
.Fa secret
which should not exceed
.Fa outlen
bytes.
The length of the shared secret should be written to
.Em *secretlen .
If
.Fa secret
is NULL then the maximum length of the shared secret should be written
to
.Em *secretlen .
.Ss Key Exchange Parameters Functions
.Fn OSSL_FUNC_keyexch_set_ctx_params
sets key exchange parameters associated with the given provider side key
exchange context
.Fa ctx
to
.Em params ,
see
.Sx Common Key Exchange parameters .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_keyexch_get_ctx_params
gets key exchange parameters associated with the given provider side key
exchange context
.Fa ctx
into
.Em params ,
see
.Sx Common Key Exchange parameters .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_keyexch_settable_ctx_params
yields a constant
.Xr OSSL_PARAM 3
array that describes the settable parameters, i.e.
parameters that can be used with
.Xr OP_signature_set_ctx_params 3 .
If
.Fn OSSL_FUNC_keyexch_settable_ctx_params
is present,
.Fn OSSL_FUNC_keyexch_set_ctx_params
must also be present, and vice versa.
Similarly,
.Fn OSSL_FUNC_keyexch_gettable_ctx_params
yields a constant
.Xr OSSL_PARAM 3
array that describes the gettable parameters, i.e.
parameters that can be handled by
.Xr OP_signature_get_ctx_params 3 .
If
.Fn OSSL_FUNC_keyexch_gettable_ctx_params
is present,
.Fn OSSL_FUNC_keyexch_get_ctx_params
must also be present, and vice versa.
.Pp
Notice that not all settable parameters are also gettable, and vice
versa.
.Ss Common Key Exchange parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by the
.Fn OSSL_FUNC_keyexch_set_ctx_params
and
.Fn OSSL_FUNC_keyexch_get_ctx_params
functions.
.Pp
Common parameters currently recognised by built-in key exchange
algorithms are as follows.
.Bl -tag -width Ds
.It \(dqkdf-type" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_TYPE Ns ) <UTF8 string>
Sets or gets the Key Derivation Function type to apply within the
associated key exchange ctx.
.It \(dqkdf-digest" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_DIGEST Ns ) <UTF8 string>
Sets or gets the Digest algorithm to be used as part of the Key
Derivation Function associated with the given key exchange ctx.
.It \(dqkdf-digest-props" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_DIGEST_PROPS Ns ) <UTF8 string>
Sets properties to be used upon look up of the implementation for the
selected Digest algorithm for the Key Derivation Function associated
with the given key exchange ctx.
.It \(dqkdf-outlen" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_OUTLEN Ns ) <unsigned integer>
Sets or gets the desired size for the output of the chosen Key
Derivation Function associated with the given key exchange ctx.
The length of the "kdf-outlen" parameter should not exceed that of a
.Vt size_t .
.It \(dqkdf-ukm" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_UKM Ns ) <octet string>
Sets the User Key Material to be used as part of the selected Key
Derivation Function associated with the given key exchange ctx.
.It \(dqkdf-ukm" ( Ns Sy OSSL_EXCHANGE_PARAM_KDF_UKM Ns ) <octet string ptr>
Gets a pointer to the User Key Material to be used as part of the
selected Key Derivation Function associated with the given key exchange
ctx.
Providers usually do not need to support this gettable parameter as its
sole purpose is to support functionality of the deprecated
.Xr EVP_PKEY_CTX_get0_ecdh_kdf_ukm 3
and
.Xr EVP_PKEY_CTX_get0_dh_kdf_ukm 3
functions.
.El
.Pp
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling
.Fn OSSL_FUNC_keyexch_derive .
It may return 0 if either the "digest-check" or the "key-check" are set
to 0.
.It \(dqkey-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_KEY_CHECK Ns ) <integer>
If required this parameter should be set using
.Fn OSSL_FUNC_keyexch_init .
The default value of 1 causes an error during the init if the key is not
FIPS approved (e.g.
The key has a security strength of less than 112 bits).
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.It \(dqdigest-check" ( Ns Sy OSSL_EXCHANGE_PARAM_FIPS_DIGEST_CHECK Ns ) <integer>
If required this parameter should be set before any optional digest is
set.
The default value of 1 causes an error when the digest is set if the
digest is not FIPS approved.
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Sh RETURN VALUES
.Fn OSSL_FUNC_keyexch_newctx
and
.Fn OSSL_FUNC_keyexch_dupctx
should return the newly created provider side key exchange context, or
NULL on failure.
.Pp
.Fn OSSL_FUNC_keyexch_init ,
.Fn OSSL_FUNC_keyexch_set_peer ,
.Fn OSSL_FUNC_keyexch_derive ,
.Xr OSSL_FUNC_keyexch_set_params 3 ,
and
.Xr OSSL_FUNC_keyexch_get_params 3
should return 1 for success or 0 on error.
.Pp
.Fn OSSL_FUNC_keyexch_settable_ctx_params
and
.Fn OSSL_FUNC_keyexch_gettable_ctx_params
should always return a constant
.Xr OSSL_PARAM 3
array.
.Sh SEE ALSO
.Xr provider 7
.Sh HISTORY
The provider KEYEXCH interface was introduced in OpenSSL 3.0.
.Pp
The Key Exchange Parameters "fips-indicator", "key-check" and
"digest-check" were added in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2019-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
