.Dd 2025-09-30
.Dt PROVIDER-SKEYMGMT 7ossl
.Os
.Sh NAME
.Nm provider-skeymgmt
.Nd The SKEYMGMT library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Key object destruction */
 void
.Fo OSSL_FUNC_skeymgmt_free
.Fa "void *keydata"
.Fc
.Ft /* Key object import and export functions */
 void *
.Fo OSSL_FUNC_skeymgmt_import
.Fa "void *provctx"
.Fa "int selection"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_skeymgmt_export
.Fa "void *keydata"
.Fa "int selection"
.Fa "OSSL_CALLBACK *param_cb"
.Fa "void *cbarg"
.Fc
.Ft void *
.Fo OSSL_FUNC_skeymgmt_generate
.Fa "void *provctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_skeymgmt_gen_settable_params
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_skeymgmt_imp_settable_params
.Fa "void *provctx"
.Fc
.Ft const char *
.Fo OSSL_FUNC_skeymgmt_get_key_id
.Fa "void *keydata"
.Fc
.Sh DESCRIPTION
The SKEYMGMT operation doesn't have much public visibility in the
OpenSSL libraries, rather it is an internal operation that is designed
to work with operations that use opaque symmetric keys objects.
.Pp
The SKEYMGMT operation shares knowledge with the operations it works
with, therefore the SKEYMGMT and the algorithms which use it must belong
to the same provider.
The OpenSSL libraries will ensure that they do.
.Pp
The primary responsibility of the SKEYMGMT operation is to hold the
provider side key data for the OpenSSL library EVP_SKEY structure.
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from a
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_skeymgmt_free                 OSSL_FUNC_SKEYMGMT_FREE

 OSSL_FUNC_skeymgmt_import               OSSL_FUNC_SKEYMGMT_IMPORT
 OSSL_FUNC_skeymgmt_export               OSSL_FUNC_SKEYMGMT_EXPORT

 OSSL_FUNC_skeymgmt_generate             OSSL_FUNC_SKEYMGMT_GENERATE

 OSSL_FUNC_skeymgmt_get_key_id           OSSL_FUNC_SKEYMGMT_GET_KEY_ID
 OSSL_FUNC_skeymgmt_imp_settable_params  OSSL_FUNC_SKEYMGMT_IMP_SETTABLE_PARAMS
 OSSL_FUNC_skeymgmt_gen_settable_params  OSSL_FUNC_SKEYMGMT_GEN_SETTABLE_PARAMS
.Ed
.Pp
The SKEYMGMT management is inspired by KEYMGMT but is simpler.
.Ss Key Objects
A key object is a collection of data for an symmetric key, and is
represented as
.Fa keydata
in this manual.
.Pp
The exact contents of a key object are defined by the provider, and it
is assumed that different operations in one and the same provider use
the exact same structure to represent this collection of data, so that
for example, a key object that has been created using the SKEYMGMT
interface can be passed as is to other algorithms from the same provider
operations, such as
.Xr OSSL_FUNC_mac_init_opaque 3
(see
.Xr provider-mac 7 Ns ).
.Pp
With the export SKEYMGMT function, it's possible to select a specific
subset of data to handle, governed by the bits in a
.Fa selection
indicator.
The bits are:
.Bl -tag -width Ds
.It Sy OSSL_SKEYMGMT_SELECT_SECRET_KEY
Indicating that the secret key raw bytes in a key object should be
included.
.It Sy OSSL_SKEYMGMT_SELECT_PARAMETERS
Indicating that the parameters in a key object should be included.
.El
.Pp
Combined selector bits are also defined for easier use:
.Bl -tag -width Ds
.It Sy OSSL_SKEYMGMT_SELECT_ALL
Indicating that everything in a key object should be included.
.El
.Pp
The exact interpretation of those bits or how they combine is left to
each function where you can specify a selector.
.Ss Destructing Function
.Fn OSSL_FUNC_skeymgmt_free
should free the passed
.Fa keydata .
.Ss Key Object Import and Export Functions
.Fn OSSL_FUNC_skeymgmt_import
should import data into
.Fa keydata
with values taken from the
.Xr OSSL_PARAM 3
array
.Em params .
It allocates the
.Fa keydata
object (there is no separate allocation function).
.Pp
.Fn OSSL_FUNC_skeymgmt_imp_settable_params
returns a list of parameters that can be provided to the
.Fn OSSL_FUNC_skeymgmt_import
function.
.Pp
.Fn OSSL_FUNC_skeymgmt_export
should extract values indicated by
.Fa selection
from
.Fa keydata ,
create an
.Xr OSSL_PARAM 3
array with them and call
.Fa param_cb
with that array as well as the given
.Fa cbarg .
The passed
.Xr OSSL_PARAM 3
array is transient and is freed upon the return from
.Fa param_cb .
.Ss Key Object Generation Functions
.Fn OSSL_FUNC_skeymgmt_generate
creates a new key according to the values taken from the
.Xr OSSL_PARAM 3
array
.Em params .
It allocates the
.Fa keydata
object.
.Pp
.Fn OSSL_FUNC_skeymgmt_gen_settable_params
returns a list of parameters that can be provided to the
.Fn OSSL_FUNC_skeymgmt_generate
function.
.Ss Key Object Information functions
.Fn OSSL_FUNC_skeymgmt_get_key_id
returns a NUL-terminated string identifying the particular key.
The returned string will be freed by a call to
.Xr EVP_SKEY_free 3
so callers need to copy it themselves if they want to preserve the value
past the key lifetime.
The purpose of this function is providing a printable string that can
help users to access the specific key.
The content of this string is provider-specific.
.Ss Common Import and Export Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure.
.Pp
Common information parameters currently recognised by built-in skeymgmt
algorithms are as follows:
.Bl -tag -width Ds
.It \(dqraw-bytes" ( Ns Sy SKEY_PARAM_RAW_BYTES Ns ) <octet string>
The value represents symmetric key as a byte array.
.It \(dqkey-length" ( Ns Sy SKEY_PARAM_KEY_LENGTH Ns ) <integer>
The value is the byte length of the given key.
.El
.Sh RETURN VALUES
.Fn OSSL_FUNC_skeymgmt_import
and
.Fn OSSL_FUNC_skeymgmt_generate
return a pointer to an allocated object on success and NULL on error.
.Pp
.Fn OSSL_FUNC_skeymgmt_export
returns 1 for success or 0 on error.
.Pp
.Fn OSSL_FUNC_skeymgmt_get_key_id
returns a pointer to a 0-terminated string or NULL.
.Pp
.Fn OSSL_FUNC_skeymgmt_gen_settable_params
and
.Fn OSSL_FUNC_skeymgmt_imp_settable_params
return references to an array of
.Sy OSSL_PARAM
which can be NULL if there are no settable parameters.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr EVP_SKEY 3 ,
.Xr EVP_KEYMGMT 3
.Sh HISTORY
The SKEYMGMT interface was introduced in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2024-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
