.Dd 2025-09-30
.Dt PROVIDER-DECODER 7ossl
.Os
.Sh NAME
.Nm provider-decoder
.Nd The OSSL_DECODER library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Decoder parameter accessor and descriptor */
 const OSSL_PARAM *
.Fo OSSL_FUNC_decoder_gettable_params
.Fa "void *provctx"
.Fc
.Ft int
.Fo OSSL_FUNC_decoder_get_params
.Fa "OSSL_PARAM params[]"
.Fc
.Ft /* Functions to construct / destruct / manipulate the decoder context */
 void *
.Fo OSSL_FUNC_decoder_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_decoder_freectx
.Fa "void *ctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_decoder_settable_ctx_params
.Fa "void *provctx"
.Fc
.Ft int
.Fo OSSL_FUNC_decoder_set_ctx_params
.Fa "void *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft /* Functions to check selection support */
 int
.Fo OSSL_FUNC_decoder_does_selection
.Fa "void *provctx"
.Fa "int selection"
.Fc
.Ft /* Functions to decode object data */
 int
.Fo OSSL_FUNC_decoder_decode
.Fa "void *ctx"
.Fa "OSSL_CORE_BIO *in"
.Fa "int selection"
.Fa "OSSL_CALLBACK *data_cb"
.Fa "void *data_cbarg"
.Fa "OSSL_PASSPHRASE_CALLBACK *cb"
.Fa "void *cbarg"
.Fc
.Ft /* Functions to export a decoded object */
 int
.Fo OSSL_FUNC_decoder_export_object
.Fa "void *ctx"
.Fa "const void *objref"
.Fa "size_t objref_sz"
.Fa "OSSL_CALLBACK *export_cb"
.Fa "void *export_cbarg"
.Fc
.Sh DESCRIPTION
.Em The term \(dqdecode" is used throughout this manual. This includes but is not limited to deserialization as individual decoders can also do decoding into intermediate data formats.
.Pp
The DECODER operation is a generic method to create a provider-native
object reference or intermediate decoded data from an encoded form read
from the given
.Vt OSSL_CORE_BIO .
If the caller wants to decode data from memory, it should provide a
.Xr BIO_s_mem 3
.Sy BIO .
The decoded data or object reference is passed along with eventual
metadata to the
.Em metadata_cb
as
.Xr OSSL_PARAM 3
parameters.
.Pp
The decoder doesn't need to know more about the
.Vt OSSL_CORE_BIO
pointer than being able to pass it to the appropriate BIO upcalls (see
.Xr provider-base 7 Ns ).
.Pp
The DECODER implementation may be part of a chain, where data is passed
from one to the next.
For example, there may be an implementation to decode an object from PEM
to DER, and another one that decodes DER to a provider-native object.
.Pp
The last decoding step in the decoding chain is usually supposed to
create a provider-native object referenced by an object reference.
To import that object into a different provider the
.Fn OSSL_FUNC_decoder_export_object
can be called as the final step of the decoding process.
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_decoder_decode
has these:
.Bd -literal
 typedef int
     (OSSL_FUNC_decoder_decode_fn)(void *ctx, OSSL_CORE_BIO *in,
                                   int selection,
                                   OSSL_CALLBACK *data_cb, void *data_cbarg,
                                   OSSL_PASSPHRASE_CALLBACK *cb, void *cbarg);
 static ossl_inline OSSL_FUNC_decoder_decode_fn*
     OSSL_FUNC_decoder_decode(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_decoder_get_params          OSSL_FUNC_DECODER_GET_PARAMS
 OSSL_FUNC_decoder_gettable_params     OSSL_FUNC_DECODER_GETTABLE_PARAMS

 OSSL_FUNC_decoder_newctx              OSSL_FUNC_DECODER_NEWCTX
 OSSL_FUNC_decoder_freectx             OSSL_FUNC_DECODER_FREECTX
 OSSL_FUNC_decoder_set_ctx_params      OSSL_FUNC_DECODER_SET_CTX_PARAMS
 OSSL_FUNC_decoder_settable_ctx_params OSSL_FUNC_DECODER_SETTABLE_CTX_PARAMS

 OSSL_FUNC_decoder_does_selection      OSSL_FUNC_DECODER_DOES_SELECTION

 OSSL_FUNC_decoder_decode              OSSL_FUNC_DECODER_DECODE

 OSSL_FUNC_decoder_export_object       OSSL_FUNC_DECODER_EXPORT_OBJECT
.Ed
.Ss Names and properties
The name of an implementation should match the target type of object it
decodes.
For example, an implementation that decodes an RSA key should be named
"RSA". Likewise, an implementation that decodes DER data from PEM input
should be named "DER".
.Pp
Properties, as defined in the
.Xr OSSL_ALGORITHM 3
array element of each decoder implementation, can be used to further
specify details about an implementation:
.Bl -tag -width Ds
.It input
This property is used to specify what format of input the implementation
can decode.
.Pp
This property is
.Em mandatory .
.Pp
OpenSSL providers recognize the following input types:
.Bl -tag -width Ds
.It pem
An implementation with that input type decodes PEM formatted data.
.It der
An implementation with that input type decodes DER formatted data.
.It msblob
An implementation with that input type decodes MSBLOB formatted data.
.It pvk
An implementation with that input type decodes PVK formatted data.
.El
.It structure
This property is used to specify the structure that the decoded data is
expected to have.
.Pp
This property is
.Em optional .
.Pp
Structures currently recognised by built-in decoders:
.Bl -tag -width Ds
.It \(dqtype-specific"
Type specific structure.
.It \(dqpkcs8"
Structure according to the PKCS#8 specification.
.It \(dqSubjectPublicKeyInfo"
Encoding of public keys according to the Subject Public Key Info of RFC
5280.
.El
.El
.Pp
The possible values of both these properties is open ended.
A provider may very well specify input types and structures that
libcrypto doesn't know anything about.
.Ss Subset selections
Sometimes, an object has more than one subset of data that is
interesting to treat separately or together.
It's possible to specify what subsets are to be decoded, with a set of
bits
.Fa selection
that are passed in an
.Vt int .
.Pp
This set of bits depend entirely on what kind of provider-side object is
to be decoded.
For example, those bits are assumed to be the same as those used with
.Xr provider-keymgmt 7
(see
.Xr provider-keymgmt 7 )
when the object is an asymmetric keypair - e.g.,
.Sy OSSL_KEYMGMT_SELECT_PRIVATE_KEY
if the object to be decoded is supposed to contain private key
components.
.Pp
.Fn OSSL_FUNC_decoder_does_selection
should tell if a particular implementation supports any of the
combinations given by
.Fa selection .
.Ss Context functions
.Fn OSSL_FUNC_decoder_newctx
returns a context to be used with the rest of the functions.
.Pp
.Fn OSSL_FUNC_decoder_freectx
frees the given
.Fa ctx
as created by
.Fn OSSL_FUNC_decoder_newctx .
.Pp
.Fn OSSL_FUNC_decoder_set_ctx_params
sets context data according to parameters from
.Em params
that it recognises.
Unrecognised parameters should be ignored.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_decoder_settable_ctx_params
returns a constant
.Xr OSSL_PARAM 3
array describing the parameters that
.Fn OSSL_FUNC_decoder_set_ctx_params
can handle.
.Pp
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by
.Fn OSSL_FUNC_decoder_set_ctx_params
and
.Fn OSSL_FUNC_decoder_settable_ctx_params .
.Ss Export function
When a provider-native object is created by a decoder it would be
unsuitable for direct use with a foreign provider.
The export function allows for exporting the object into that foreign
provider if the foreign provider supports the type of the object and
provides an import function.
.Pp
.Fn OSSL_FUNC_decoder_export_object
should export the object of size
.Fa objref_sz
referenced by
.Fa objref
as an
.Xr OSSL_PARAM 3
array and pass that into the
.Fa export_cb
as well as the given
.Fa export_cbarg .
.Ss Decoding functions
.Fn OSSL_FUNC_decoder_decode
should decode the data as read from the
.Vt OSSL_CORE_BIO
.Fa in
to produce decoded data or an object to be passed as reference in an
.Xr OSSL_PARAM 3
array along with possible other metadata that was decoded from the
input.
This
.Xr OSSL_PARAM 3
array is then passed to the
.Fa data_cb
callback.
The
.Fa selection
bits, if relevant, should determine what the input data should contain.
The decoding functions also take an
.Xr OSSL_PASSPHRASE_CALLBACK 3
function pointer along with a pointer to application data
.Fa cbarg ,
which should be used when a pass phrase prompt is needed.
.Pp
It's important to understand that the return value from this function is
interpreted as follows:
.Bl -tag -width Ds
.It True (1)
This means "carry on the decoding process", and is meaningful even
though this function couldn't decode the input into anything, because
there may be another decoder implementation that can decode it into
something.
.Pp
The
.Fa data_cb
callback should never be called when this function can't decode the
input into anything.
.It False (0)
This means "stop the decoding process", and is meaningful when the input
could be decoded into some sort of object that this function
understands, but further treatment of that object results into errors
that won't be possible for some other decoder implementation to get a
different result.
.El
.Pp
The conditions to stop the decoding process are at the discretion of the
implementation.
.Ss Decoder operation parameters
There are currently no operation parameters currently recognised by the
built-in decoders.
.Pp
Parameters currently recognised by the built-in pass phrase callback:
.Bl -tag -width Ds
.It \(dqinfo" ( Ns Sy OSSL_PASSPHRASE_PARAM_INFO Ns ) <UTF8 string>
A string of information that will become part of the pass phrase prompt.
This could be used to give the user information on what kind of object
it's being prompted for.
.El
.Sh RETURN VALUES
.Fn OSSL_FUNC_decoder_newctx
returns a pointer to a context, or NULL on failure.
.Pp
.Fn OSSL_FUNC_decoder_set_ctx_params
returns 1, unless a recognised parameter was invalid or caused an error,
for which 0 is returned.
.Pp
.Fn OSSL_FUNC_decoder_settable_ctx_params
returns a pointer to an array of constant
.Xr OSSL_PARAM 3
elements.
.Pp
.Fn OSSL_FUNC_decoder_does_selection
returns 1 if the decoder implementation supports any of the
.Fa selection
bits, otherwise 0.
.Pp
.Fn OSSL_FUNC_decoder_decode
returns 1 to signal that the decoding process should continue, or 0 to
signal that it should stop.
.Sh SEE ALSO
.Xr provider 7
.Sh HISTORY
The DECODER interface was introduced in OpenSSL 3.0.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
