.Dd 2025-09-30
.Dt PROVIDER-DIGEST 7ossl
.Os
.Sh NAME
.Nm provider-digest
.Nd The digest library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * Digests support the following function signatures in OSSL_DISPATCH arrays.
  *
.Fo 
.Fa "The function signatures are not actual functions"
.Fc
.
.Ft */

 /* Context management */
 void *
.Fo OSSL_FUNC_digest_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_digest_freectx
.Fa "void *dctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_digest_dupctx
.Fa "void *dctx"
.Fc
.Ft void
.Fo OSSL_FUNC_digest_copyctx
.Fa "void *voutctx"
.Fa "void *vinctx"
.Fc
.Ft /* Digest generation */
 int
.Fo OSSL_FUNC_digest_init
.Fa "void *dctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_digest_update
.Fa "void *dctx"
.Fa "const unsigned char *in"
.Fa "size_t inl"
.Fc
.Ft int
.Fo OSSL_FUNC_digest_final
.Fa "void *dctx"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsz"
.Fc
.Ft int
.Fo OSSL_FUNC_digest_digest
.Fa "void *provctx"
.Fa "const unsigned char *in"
.Fa "size_t inl"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsz"
.Fc
.Ft /* Digest parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_digest_gettable_params
.Fa "void *provctx"
.Fc
.Ft /* Digest operation parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_digest_gettable_ctx_params
.Fa "void *dctx"
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_digest_settable_ctx_params
.Fa "void *dctx"
.Fa "void *provctx"
.Fc
.Ft /* Digest parameters */
 int
.Fo OSSL_FUNC_digest_get_params
.Fa "OSSL_PARAM params[]"
.Fc
.Ft /* Digest operation parameters */
 int
.Fo OSSL_FUNC_digest_set_ctx_params
.Fa "void *dctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_digest_get_ctx_params
.Fa "void *dctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The DIGEST operation enables providers to implement digest algorithms
and make them available to applications via the API functions
.Xr EVP_DigestInit_ex 3 ,
.Xr EVP_DigestUpdate 3
and
.Xr EVP_DigestFinal 3
(and other related functions).
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_digest_newctx
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_digest_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_digest_newctx_fn
     OSSL_FUNC_digest_newctx(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_digest_newctx               OSSL_FUNC_DIGEST_NEWCTX
 OSSL_FUNC_digest_freectx              OSSL_FUNC_DIGEST_FREECTX
 OSSL_FUNC_digest_dupctx               OSSL_FUNC_DIGEST_DUPCTX
 OSSL_FUNC_digest_copyctx              OSSL_FUNC_DIGEST_COPYCTX

 OSSL_FUNC_digest_init                 OSSL_FUNC_DIGEST_INIT
 OSSL_FUNC_digest_update               OSSL_FUNC_DIGEST_UPDATE
 OSSL_FUNC_digest_final                OSSL_FUNC_DIGEST_FINAL
 OSSL_FUNC_digest_digest               OSSL_FUNC_DIGEST_DIGEST

 OSSL_FUNC_digest_get_params           OSSL_FUNC_DIGEST_GET_PARAMS
 OSSL_FUNC_digest_get_ctx_params       OSSL_FUNC_DIGEST_GET_CTX_PARAMS
 OSSL_FUNC_digest_set_ctx_params       OSSL_FUNC_DIGEST_SET_CTX_PARAMS

 OSSL_FUNC_digest_gettable_params      OSSL_FUNC_DIGEST_GETTABLE_PARAMS
 OSSL_FUNC_digest_gettable_ctx_params  OSSL_FUNC_DIGEST_GETTABLE_CTX_PARAMS
 OSSL_FUNC_digest_settable_ctx_params  OSSL_FUNC_DIGEST_SETTABLE_CTX_PARAMS
.Ed
.Pp
A digest algorithm implementation may not implement all of these
functions.
In order to be usable all or none of OSSL_FUNC_digest_newctx,
OSSL_FUNC_digest_freectx, OSSL_FUNC_digest_init,
OSSL_FUNC_digest_update, OSSL_FUNC_digest_final and
OSSL_FUNC_digest_get_params should be implemented.
All other functions are optional.
.Ss Context Management Functions
.Fn OSSL_FUNC_digest_newctx
should create and return a pointer to a provider side structure for
holding context information during a digest operation.
A pointer to this context will be passed back in a number of the other
digest operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
.Pp
.Fn OSSL_FUNC_digest_freectx
is passed a pointer to the provider side digest context in the
.Fa dctx
parameter.
This function should free any resources associated with that context.
.Pp
.Fn OSSL_FUNC_digest_dupctx
should duplicate the provider side digest context in the
.Fa dctx
parameter and return the duplicate copy.
.Pp
.Fn OSSL_FUNC_digest_copyctx
should copy the provider side digest context in the
.Fa vinctx
parameter to the
.Fa voutctx
parameter which is the another provider side context.
The OSSL_FUNC_digest_copyctx function is used in the EVP_MD_CTX_copy_ex
function to speed up HMAC operations in the PBKDF2. This function is
optional, and dupctx will be used if there is no EVP_MD_CTX_copy_ex
function.
.Ss Digest Generation Functions
.Fn OSSL_FUNC_digest_init
initialises a digest operation given a newly created provider side
digest context in the
.Fa dctx
parameter.
The
.Em params ,
if not NULL, should be set on the context in a manner similar to using
.Fn OSSL_FUNC_digest_set_ctx_params .
.Pp
.Fn OSSL_FUNC_digest_update
is called to supply data to be digested as part of a previously
initialised digest operation.
The
.Fa dctx
parameter contains a pointer to a previously initialised provider side
context.
.Fn OSSL_FUNC_digest_update
should digest
.Fa inl
bytes of data at the location pointed to by
.Fa in .
.Fn OSSL_FUNC_digest_update
may be called multiple times for a single digest operation.
.Pp
.Fn OSSL_FUNC_digest_final
generates a digest started through previous
.Fn OSSL_FUNC_digest_init
and
.Fn OSSL_FUNC_digest_update
calls.
The
.Fa dctx
parameter contains a pointer to the provider side context.
The digest should be written to
.Em *out
and the length of the digest to
.Em *outl .
The digest should not exceed
.Fa outsz
bytes.
.Pp
.Fn OSSL_FUNC_digest_digest
is a "oneshot" digest function.
No provider side digest context is used.
Instead the provider context that was created during provider
initialisation is passed in the
.Fa provctx
parameter (see
.Xr provider 7 Ns ).
.Fa inl
bytes at
.Fa in
should be digested and the result should be stored at
.Fa out .
The length of the digest should be stored in
.Em *outl
which should not exceed
.Fa outsz
bytes.
.Ss Digest Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by these functions.
.Pp
.Fn OSSL_FUNC_digest_get_params
gets details of the algorithm implementation and stores them in
.Em params .
.Pp
.Fn OSSL_FUNC_digest_set_ctx_params
sets digest operation parameters for the provider side digest context
.Fa dctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_digest_get_ctx_params
gets digest operation details details from the given provider side
digest context
.Fa dctx
and stores them in
.Em params .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_digest_gettable_params
returns a constant
.Xr OSSL_PARAM 3
array containing descriptors of the parameters that
.Fn OSSL_FUNC_digest_get_params
can handle.
.Pp
.Fn OSSL_FUNC_digest_gettable_ctx_params
and
.Fn OSSL_FUNC_digest_settable_ctx_params
both return constant
.Xr OSSL_PARAM 3
arrays as descriptors of the parameters that
.Fn OSSL_FUNC_digest_get_ctx_params
and
.Fn OSSL_FUNC_digest_set_ctx_params
can handle, respectively.
The array is based on the current state of the provider side context if
.Fa dctx
is not NULL and on the provider side algorithm
.Fa provctx
otherwise.
.Pp
Parameters currently recognised by built-in digests with this function
are as follows.
Not all parameters are relevant to, or are understood by all digests:
.Bl -tag -width Ds
.It \(dqblocksize" ( Ns Sy OSSL_DIGEST_PARAM_BLOCK_SIZE Ns ) <unsigned integer>
The digest block size.
The length of the "blocksize" parameter should not exceed that of a
.Vt size_t .
.It \(dqsize" ( Ns Sy OSSL_DIGEST_PARAM_SIZE Ns ) <unsigned integer>
The digest output size.
The length of the "size" parameter should not exceed that of a
.Vt size_t .
.It \(dqflags" ( Ns Sy OSSL_DIGEST_PARAM_FLAGS Ns ) <unsigned integer>
Diverse flags that describe exceptional behaviour for the digest:
.Bl -tag -width Ds
.It Sy EVP_MD_FLAG_ONESHOT
This digest method can only handle one block of input.
.It Sy EVP_MD_FLAG_XOF
This digest method is an extensible-output function (XOF).
.It Sy EVP_MD_FLAG_DIGALGID_NULL
When setting up a DigestAlgorithmIdentifier, this flag will have the
parameter set to NULL by default.
Use this for PKCS#1.
.Em Note: if combined with EVP_MD_FLAG_DIGALGID_ABSENT, the latter will override.
.It Sy EVP_MD_FLAG_DIGALGID_ABSENT
When setting up a DigestAlgorithmIdentifier, this flag will have the
parameter be left absent by default.
.Em Note: if combined with EVP_MD_FLAG_DIGALGID_NULL, the latter will be overridden.
.It Sy EVP_MD_FLAG_DIGALGID_CUSTOM
Custom DigestAlgorithmIdentifier handling via ctrl, with
.Sy EVP_MD_FLAG_DIGALGID_ABSENT
as default.
.Em Note: if combined with EVP_MD_FLAG_DIGALGID_NULL, the latter will be overridden.
Currently unused.
.El
.Pp
The length of the "flags" parameter should equal that of an
.Sy unsigned long int .
.El
.Ss Digest Context Parameters
.Fn OSSL_FUNC_digest_set_ctx_params
sets digest parameters associated with the given provider side digest
context
.Fa dctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
See
.Xr OSSL_PARAM 3
for further details on the parameters structure.
.Pp
.Fn OSSL_FUNC_digest_get_ctx_params
gets details of currently set parameters values associated with the give
provider side digest context
.Fa dctx
and stores them in
.Em params .
See
.Xr OSSL_PARAM 3
for further details on the parameters structure.
.Sh RETURN VALUES
.Fn OSSL_FUNC_digest_newctx
and
.Fn OSSL_FUNC_digest_dupctx
should return the newly created provider side digest context, or NULL on
failure.
.Pp
.Fn OSSL_FUNC_digest_init ,
.Fn OSSL_FUNC_digest_update ,
.Fn OSSL_FUNC_digest_final ,
.Fn OSSL_FUNC_digest_digest ,
.Xr OSSL_FUNC_digest_set_params 3
and
.Fn OSSL_FUNC_digest_get_params
should return 1 for success or 0 on error.
.Pp
.Xr OSSL_FUNC_digest_size 3
should return the digest size.
.Pp
.Xr OSSL_FUNC_digest_block_size 3
should return the block size of the underlying digest algorithm.
.Sh BUGS
The
.Xr EVP_Q_digest 3 ,
.Xr EVP_Digest 3
and
.Xr EVP_DigestFinal_ex 3
API calls do not expect the digest size to be larger than
EVP_MAX_MD_SIZE. Any algorithm which produces larger digests is unusable
with those API calls.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-legacy 7 ,
.Xr EVP_MD-common 7 ,
.Xr EVP_MD-BLAKE2 7 ,
.Xr EVP_MD-MD2 7 ,
.Xr EVP_MD-MD4 7 ,
.Xr EVP_MD-MD5 7 ,
.Xr EVP_MD-MD5-SHA1 7 ,
.Xr EVP_MD-MDC2 7 ,
.Xr EVP_MD-RIPEMD160 7 ,
.Xr EVP_MD-SHA1 7 ,
.Xr EVP_MD-SHA2 7 ,
.Xr EVP_MD-SHA3 7 ,
.Xr EVP_MD-KECCAK 7
.Xr EVP_MD-SHAKE 7 ,
.Xr EVP_MD-SM3 7 ,
.Xr EVP_MD-WHIRLPOOL 7 ,
.Xr EVP_MD-NULL 7 ,
.Xr life_cycle-digest 7 ,
.Xr EVP_DigestInit 3
.Sh HISTORY
The provider DIGEST interface was introduced in OpenSSL 3.0.
.Fn OSSL_FUNC_digest_copyctx
was added in 3.5 version.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
