.Dd 2025-09-30
.Dt PROVIDER-KEYMGMT 7ossl
.Os
.Sh NAME
.Nm provider-keymgmt
.Nd The KEYMGMT library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Key object
.Fo 
.Fa keydata
.Fc
 creation and destruction */
.Ft void *
.Fo OSSL_FUNC_keymgmt_new
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_keymgmt_free
.Fa "void *keydata"
.Fc
.Ft /* Generation, a more complex constructor */
 void *
.Fo OSSL_FUNC_keymgmt_gen_init
.Fa "void *provctx"
.Fa "int selection"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_keymgmt_gen_set_template
.Fa "void *genctx"
.Fa "void *template"
.Fc
.Ft int
.Fo OSSL_FUNC_keymgmt_gen_get_params
.Fa "void *genctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_keymgmt_gen_set_params
.Fa "void *genctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_gen_gettable_params
.Fa "void *genctx"
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_gen_settable_params
.Fa "void *genctx"
.Fa "void *provctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_keymgmt_gen
.Fa "void *genctx"
.Fa "OSSL_CALLBACK *cb"
.Fa "void *cbarg"
.Fc
.Ft void
.Fo OSSL_FUNC_keymgmt_gen_cleanup
.Fa "void *genctx"
.Fc
.Ft /* Key loading by object reference, also a constructor */
 void *
.Fo OSSL_FUNC_keymgmt_load
.Fa "const void *reference"
.Fa "size_t reference_sz"
.Fc
.Ft /* Key object information */
 int
.Fo OSSL_FUNC_keymgmt_get_params
.Fa "void *keydata"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_gettable_params
.Fa "void *provctx"
.Fc
.Ft int
.Fo OSSL_FUNC_keymgmt_set_params
.Fa "void *keydata"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_settable_params
.Fa "void *provctx"
.Fc
.Ft /* Key object content checks */
 int
.Fo OSSL_FUNC_keymgmt_has
.Fa "const void *keydata"
.Fa "int selection"
.Fc
.Ft int
.Fo OSSL_FUNC_keymgmt_match
.Fa "const void *keydata1"
.Fa "const void *keydata2"
.Fa "int selection"
.Fc
.Ft /* Discovery of supported operations */
 const char *
.Fo OSSL_FUNC_keymgmt_query_operation_name
.Fa "int operation_id"
.Fc
.Ft /* Key object import and export functions */
 int
.Fo OSSL_FUNC_keymgmt_import
.Fa "void *keydata"
.Fa "int selection"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_import_types
.Fa "int selection"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_import_types_ex
.Fa "void *provctx"
.Fa "int selection"
.Fc
.Ft int
.Fo OSSL_FUNC_keymgmt_export
.Fa "void *keydata"
.Fa "int selection"
.Fa "OSSL_CALLBACK *param_cb"
.Fa "void *cbarg"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_export_types
.Fa "int selection"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_keymgmt_export_types_ex
.Fa "void *provctx"
.Fa "int selection"
.Fc
.Ft /* Key object duplication, a constructor */
 void *
.Fo OSSL_FUNC_keymgmt_dup
.Fa "const void *keydata_from"
.Fa "int selection"
.Fc
.Ft /* Key object validation */
 int
.Fo OSSL_FUNC_keymgmt_validate
.Fa "const void *keydata"
.Fa "int selection"
.Fa "int checktype"
.Fc
.Sh DESCRIPTION
The KEYMGMT operation doesn't have much public visibility in OpenSSL
libraries, it's rather an internal operation that's designed to work in
tandem with operations that use private/public key pairs.
.Pp
Because the KEYMGMT operation shares knowledge with the operations it
works with in tandem, they must belong to the same provider.
The OpenSSL libraries will ensure that they do.
.Pp
The primary responsibility of the KEYMGMT operation is to hold the
provider side key data for the OpenSSL library EVP_PKEY structure.
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from a
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_keymgmt_new
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_keymgmt_new_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_keymgmt_new_fn
     OSSL_FUNC_keymgmt_new(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_keymgmt_new                  OSSL_FUNC_KEYMGMT_NEW
 OSSL_FUNC_keymgmt_free                 OSSL_FUNC_KEYMGMT_FREE

 OSSL_FUNC_keymgmt_gen_init             OSSL_FUNC_KEYMGMT_GEN_INIT
 OSSL_FUNC_keymgmt_gen_set_template     OSSL_FUNC_KEYMGMT_GEN_SET_TEMPLATE
 OSSL_FUNC_keymgmt_gen_get_params       OSSL_FUNC_KEYMGMT_GEN_GET_PARAMS
 OSSL_FUNC_keymgmt_gen_gettable_params  OSSL_FUNC_KEYMGMT_GEN_GETTABLE_PARAMS
 OSSL_FUNC_keymgmt_gen_set_params       OSSL_FUNC_KEYMGMT_GEN_SET_PARAMS
 OSSL_FUNC_keymgmt_gen_settable_params  OSSL_FUNC_KEYMGMT_GEN_SETTABLE_PARAMS
 OSSL_FUNC_keymgmt_gen                  OSSL_FUNC_KEYMGMT_GEN
 OSSL_FUNC_keymgmt_gen_cleanup          OSSL_FUNC_KEYMGMT_GEN_CLEANUP

 OSSL_FUNC_keymgmt_load                 OSSL_FUNC_KEYMGMT_LOAD

 OSSL_FUNC_keymgmt_get_params           OSSL_FUNC_KEYMGMT_GET_PARAMS
 OSSL_FUNC_keymgmt_gettable_params      OSSL_FUNC_KEYMGMT_GETTABLE_PARAMS
 OSSL_FUNC_keymgmt_set_params           OSSL_FUNC_KEYMGMT_SET_PARAMS
 OSSL_FUNC_keymgmt_settable_params      OSSL_FUNC_KEYMGMT_SETTABLE_PARAMS

 OSSL_FUNC_keymgmt_query_operation_name OSSL_FUNC_KEYMGMT_QUERY_OPERATION_NAME

 OSSL_FUNC_keymgmt_has                  OSSL_FUNC_KEYMGMT_HAS
 OSSL_FUNC_keymgmt_validate             OSSL_FUNC_KEYMGMT_VALIDATE
 OSSL_FUNC_keymgmt_match                OSSL_FUNC_KEYMGMT_MATCH

 OSSL_FUNC_keymgmt_import               OSSL_FUNC_KEYMGMT_IMPORT
 OSSL_FUNC_keymgmt_import_types         OSSL_FUNC_KEYMGMT_IMPORT_TYPES
 OSSL_FUNC_keymgmt_import_types_ex      OSSL_FUNC_KEYMGMT_IMPORT_TYPES_EX
 OSSL_FUNC_keymgmt_export               OSSL_FUNC_KEYMGMT_EXPORT
 OSSL_FUNC_keymgmt_export_types         OSSL_FUNC_KEYMGMT_EXPORT_TYPES
 OSSL_FUNC_keymgmt_export_types_ex      OSSL_FUNC_KEYMGMT_EXPORT_TYPES_EX

 OSSL_FUNC_keymgmt_dup                  OSSL_FUNC_KEYMGMT_DUP
.Ed
.Ss Key Objects
A key object is a collection of data for an asymmetric key, and is
represented as
.Fa keydata
in this manual.
.Pp
The exact contents of a key object are defined by the provider, and it
is assumed that different operations in one and the same provider use
the exact same structure to represent this collection of data, so that
for example, a key object that has been created using the KEYMGMT
interface that we document here can be passed as is to other provider
operations, such as
.Xr OP_signature_sign_init 3
(see
.Xr provider-signature 7 Ns ).
.Pp
With some of the KEYMGMT functions, it's possible to select a specific
subset of data to handle, governed by the bits in a
.Fa selection
indicator.
The bits are:
.Bl -tag -width Ds
.It Sy OSSL_KEYMGMT_SELECT_PRIVATE_KEY
Indicating that the private key data in a key object should be
considered.
.It Sy OSSL_KEYMGMT_SELECT_PUBLIC_KEY
Indicating that the public key data in a key object should be
considered.
.It Sy OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS
Indicating that the domain parameters in a key object should be
considered.
.It Sy OSSL_KEYMGMT_SELECT_OTHER_PARAMETERS
Indicating that other parameters in a key object should be considered.
.Pp
Other parameters are key parameters that don't fit any other
classification.
In other words, this particular selector bit works as a last resort bit
bucket selector.
.El
.Pp
Some selector bits have also been combined for easier use:
.Bl -tag -width Ds
.It Sy OSSL_KEYMGMT_SELECT_ALL_PARAMETERS
Indicating that all key object parameters should be considered,
regardless of their more granular classification.
.Pp
This is a combination of
.Sy OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS
and
.Sy OSSL_KEYMGMT_SELECT_OTHER_PARAMETERS .
.It Sy OSSL_KEYMGMT_SELECT_KEYPAIR
Indicating that both the whole key pair in a key object should be
considered, i.e.
the combination of public and private key.
.Pp
This is a combination of
.Sy OSSL_KEYMGMT_SELECT_PRIVATE_KEY
and
.Sy OSSL_KEYMGMT_SELECT_PUBLIC_KEY .
.It Sy OSSL_KEYMGMT_SELECT_ALL
Indicating that everything in a key object should be considered.
.El
.Pp
The exact interpretation of those bits or how they combine is left to
each function where you can specify a selector.
.Pp
It's left to the provider implementation to decide what is reasonable to
do with regards to received selector bits and how to do it.
Among others, an implementation of
.Fn OSSL_FUNC_keymgmt_match
might opt to not compare the private half if it has compared the public
half, since a match of one half implies a match of the other half.
.Ss Constructing and Destructing Functions
.Fn OSSL_FUNC_keymgmt_new
should create a provider side key object.
The provider context
.Fa provctx
is passed and may be incorporated in the key object, but that is not
mandatory.
.Pp
.Fn OSSL_FUNC_keymgmt_free
should free the passed
.Fa keydata .
.Pp
.Fn OSSL_FUNC_keymgmt_gen_init ,
.Fn OSSL_FUNC_keymgmt_gen_set_template ,
.Fn OSSL_FUNC_keymgmt_gen_get_params ,
.Fn OSSL_FUNC_keymgmt_gen_gettable_params ,
.Fn OSSL_FUNC_keymgmt_gen_set_params ,
.Fn OSSL_FUNC_keymgmt_gen_settable_params ,
.Fn OSSL_FUNC_keymgmt_gen
and
.Fn OSSL_FUNC_keymgmt_gen_cleanup
work together as a more elaborate context based key object constructor.
.Pp
.Fn OSSL_FUNC_keymgmt_gen_init
should create the key object generation context and initialize it with
.Em selections ,
which will determine what kind of contents the key object to be
generated should get.
The
.Em params ,
if not NULL, should be set on the context in a manner similar to using
.Fn OSSL_FUNC_keymgmt_set_params .
.Pp
.Fn OSSL_FUNC_keymgmt_gen_set_template
should add
.Fa template
to the context
.Fa genctx .
The
.Fa template
is assumed to be a key object constructed with the same KEYMGMT, and
from which content that the implementation chooses can be used as a
template for the key object to be generated.
Typically, the generation of a DSA or DH key would get the domain
parameters from this
.Fa template .
.Pp
.Fn OSSL_FUNC_keymgmt_gen_get_params
should retrieve parameters into
.Em params
in the key object generation context
.Fa genctx .
.Pp
.Fn OSSL_FUNC_keymgmt_gen_gettable_params
should return a constant array of descriptor
.Xr OSSL_PARAM 3 ,
for parameters that
.Fn OSSL_FUNC_keymgmt_gen_get_params
can handle.
.Pp
.Fn OSSL_FUNC_keymgmt_gen_set_params
should set additional parameters from
.Em params
in the key object generation context
.Fa genctx .
.Pp
.Fn OSSL_FUNC_keymgmt_gen_settable_params
should return a constant array of descriptor
.Xr OSSL_PARAM 3 ,
for parameters that
.Fn OSSL_FUNC_keymgmt_gen_set_params
can handle.
.Pp
.Fn OSSL_FUNC_keymgmt_gen
should perform the key object generation itself, and return the result.
The callback
.Fa cb
should be called at regular intervals with indications on how the key
object generation progresses.
.Pp
.Fn OSSL_FUNC_keymgmt_gen_cleanup
should clean up and free the key object generation context
.Fa genctx
.Pp
.Fn OSSL_FUNC_keymgmt_load
creates a provider side key object based on a
.Fa reference
object with a size of
.Fa reference_sz
bytes, that only the provider knows how to interpret, but that may come
from other operations.
Outside the provider, this reference is simply an array of bytes.
.Pp
At least one of
.Fn OSSL_FUNC_keymgmt_new ,
.Fn OSSL_FUNC_keymgmt_gen
and
.Fn OSSL_FUNC_keymgmt_load
are mandatory, as well as
.Fn OSSL_FUNC_keymgmt_free
and
.Fn OSSL_FUNC_keymgmt_has .
Additionally, if
.Fn OSSL_FUNC_keymgmt_gen
is present,
.Fn OSSL_FUNC_keymgmt_gen_init
and
.Fn OSSL_FUNC_keymgmt_gen_cleanup
must be present as well.
.Ss Key Object Information Functions
.Fn OSSL_FUNC_keymgmt_get_params
should extract information data associated with the given
.Fa keydata ,
see
.Sx Common Information Parameters .
.Pp
.Fn OSSL_FUNC_keymgmt_gettable_params
should return a constant array of descriptor
.Xr OSSL_PARAM 3 ,
for parameters that
.Fn OSSL_FUNC_keymgmt_get_params
can handle.
.Pp
If
.Fn OSSL_FUNC_keymgmt_gettable_params
is present,
.Fn OSSL_FUNC_keymgmt_get_params
must also be present, and vice versa.
.Pp
.Fn OSSL_FUNC_keymgmt_set_params
should update information data associated with the given
.Fa keydata ,
see
.Sx Common Information Parameters .
.Pp
.Fn OSSL_FUNC_keymgmt_settable_params
should return a constant array of descriptor
.Xr OSSL_PARAM 3 ,
for parameters that
.Fn OSSL_FUNC_keymgmt_set_params
can handle.
.Pp
If
.Fn OSSL_FUNC_keymgmt_settable_params
is present,
.Fn OSSL_FUNC_keymgmt_set_params
must also be present, and vice versa.
.Ss Key Object Checking Functions
.Fn OSSL_FUNC_keymgmt_query_operation_name
should return the name of the supported algorithm for the operation
.Fa operation_id .
This is similar to
.Xr provider_query_operation 3
(see
.Xr provider-base 7 Ns ),
but only works as an advisory.
If this function is not present, or returns NULL, the caller is free to
assume that there's an algorithm from the same provider, of the same
name as the one used to fetch the keymgmt and try to use that.
.Pp
.Fn OSSL_FUNC_keymgmt_has
should check whether the given
.Fa keydata
contains the subsets of data indicated by the
.Em selector .
A combination of several selector bits must consider all those subsets,
not just one.
An implementation is, however, free to consider an empty subset of data
to still be a valid subset.
For algorithms where some selection is not meaningful such as
.Sy OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS
for RSA keys the function should just return 1 as the selected subset is
not really missing in the key.
.Pp
.Fn OSSL_FUNC_keymgmt_validate
should check if the
.Fa keydata
contains valid data subsets indicated by
.Fa selection .
Some combined selections of data subsets may cause validation of the
combined data.
For example, the combination of
.Sy OSSL_KEYMGMT_SELECT_PRIVATE_KEY
and
.Sy OSSL_KEYMGMT_SELECT_PUBLIC_KEY
(or
.Sy OSSL_KEYMGMT_SELECT_KEYPAIR
for short) is expected to check that the pairwise consistency of
.Fa keydata
is valid.
The
.Fa checktype
parameter controls what type of check is performed on the subset of
data.
Two types of check are defined:
.Sy OSSL_KEYMGMT_VALIDATE_FULL_CHECK
and
.Sy OSSL_KEYMGMT_VALIDATE_QUICK_CHECK .
The interpretation of how much checking is performed in a full check
versus a quick check is key type specific.
Some providers may have no distinction between a full check and a quick
check.
For algorithms where some selection is not meaningful such as
.Sy OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS
for RSA keys the function should just return 1 as there is nothing to
validate for that selection.
.Pp
.Fn OSSL_FUNC_keymgmt_match
should check if the data subset indicated by
.Fa selection
in
.Fa keydata1
and
.Fa keydata2
match.
It is assumed that the caller has ensured that
.Fa keydata1
and
.Fa keydata2
are both owned by the implementation of this function.
.Ss Key Object Import, Export and Duplication Functions
.Fn OSSL_FUNC_keymgmt_import
should import data indicated by
.Fa selection
into
.Fa keydata
with values taken from the
.Xr OSSL_PARAM 3
array
.Em params .
.Pp
.Fn OSSL_FUNC_keymgmt_export
should extract values indicated by
.Fa selection
from
.Fa keydata ,
create an
.Xr OSSL_PARAM 3
array with them and call
.Fa param_cb
with that array as well as the given
.Fa cbarg .
.Pp
.Fn OSSL_FUNC_keymgmt_import_types
and
.Fn OSSL_FUNC_keymgmt_import_types_ex
should return a constant array of descriptor
.Xr OSSL_PARAM 3
for data indicated by
.Fa selection ,
for parameters that
.Fn OSSL_FUNC_keymgmt_import
can handle.
Either
.Fn OSSL_FUNC_keymgmt_import_types
or
.Fn OSSL_FUNC_keymgmt_import_types_ex ,
must be implemented, if
.Fn OSSL_FUNC_keymgmt_import_types_ex
is implemented, then it is preferred over
.Fn OSSL_FUNC_keymgmt_import_types .
Providers that are supposed to be backward compatible with OpenSSL 3.0
or 3.1 must continue to implement
.Fn OSSL_FUNC_keymgmt_import_types .
.Pp
.Fn OSSL_FUNC_keymgmt_export_types
and
.Fn OSSL_FUNC_keymgmt_export_types_ex
should return a constant array of descriptor
.Xr OSSL_PARAM 3
for data indicated by
.Fa selection ,
that the
.Fn OSSL_FUNC_keymgmt_export
callback can expect to receive.
Either
.Fn OSSL_FUNC_keymgmt_export_types
or
.Fn OSSL_FUNC_keymgmt_export_types_ex ,
must be implemented, if
.Fn OSSL_FUNC_keymgmt_export_types_ex
is implemented, then it is preferred over
.Fn OSSL_FUNC_keymgmt_export_types .
Providers that are supposed to be backward compatible with OpenSSL 3.0
or 3.1 must continue to implement
.Fn OSSL_FUNC_keymgmt_export_types .
.Pp
.Fn OSSL_FUNC_keymgmt_dup
should duplicate data subsets indicated by
.Fa selection
or the whole key data
.Fa keydata_from
and create a new provider side key object with the data.
.Ss Common Information Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure.
.Pp
Common information parameters currently recognised by all built-in
keymgmt algorithms are as follows:
.Bl -tag -width Ds
.It \(dqbits" ( Ns Sy OSSL_PKEY_PARAM_BITS Ns ) <integer>
The value should be the cryptographic length of the cryptosystem to
which the key belongs, in bits.
The definition of cryptographic length is specific to the key
cryptosystem.
.It \(dqmax-size" ( Ns Sy OSSL_PKEY_PARAM_MAX_SIZE Ns ) <integer>
The value should be the maximum size that a caller should allocate to
safely store a signature (called
.Em sig
in
.Xr provider-signature 7 Ns ),
the result of asymmetric encryption / decryption
.Pf ( Em out
in
.Xr provider-asym_cipher 7 ,
a derived secret
.Pf ( Em secret
in
.Xr provider-keyexch 7 ,
and similar data).
.Pp
Providers need to implement this parameter in order to properly support
various use cases such as CMS signing.
.Pp
Because an EVP_KEYMGMT method is always tightly bound to another method
(signature, asymmetric cipher, key exchange, ...) and must be of the
same provider, this number only needs to be synchronised with the
dimensions handled in the rest of the same provider.
.It \(dqsecurity-bits" ( Ns Sy OSSL_PKEY_PARAM_SECURITY_BITS Ns ) <integer>
The value should be the number of security bits of the given key.
Bits of security is defined in SP800-57.
.It \(dqmandatory-digest" ( Ns Sy OSSL_PKEY_PARAM_MANDATORY_DIGEST Ns ) <UTF8 string>
If there is a mandatory digest for performing a signature operation with
keys from this keymgmt, this parameter should get its name as value.
.Pp
When
.Xr EVP_PKEY_get_default_digest_name 3
queries this parameter and it's filled in by the implementation, its
return value will be 2.
.Pp
If the keymgmt implementation fills in the value
.Qo Li \(dq" Qc
or
.Qo Li \(dqUNDEF" Qc ,
.Xr EVP_PKEY_get_default_digest_name 3
will place the string
.Qo Li \(dqUNDEF" Qc
into its argument
.Em mdname .
This signifies that no digest should be specified with the corresponding
signature operation.
.It \(dqdefault-digest" ( Ns Sy OSSL_PKEY_PARAM_DEFAULT_DIGEST Ns ) <UTF8 string>
If there is a default digest for performing a signature operation with
keys from this keymgmt, this parameter should get its name as value.
.Pp
When
.Xr EVP_PKEY_get_default_digest_name 3
queries this parameter and it's filled in by the implementation, its
return value will be 1. Note that if
.Sy OSSL_PKEY_PARAM_MANDATORY_DIGEST
is responded to as well,
.Xr EVP_PKEY_get_default_digest_name 3
ignores the response to this parameter.
.Pp
If the keymgmt implementation fills in the value
.Qo Li \(dq" Qc
or
.Qo Li \(dqUNDEF" Qc ,
.Xr EVP_PKEY_get_default_digest_name 3
will place the string
.Qo Li \(dqUNDEF" Qc
into its argument
.Em mdname .
This signifies that no digest has to be specified with the corresponding
signature operation, but may be specified as an option.
.El
.Pp
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_PKEY_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling
.Fn OSSL_FUNC_keymgmt_gen
function.
It may return 0 if either the "key-check", or "sign-check" are set to 0.
.It \(dqkey-check" ( Ns Sy OSSL_PKEY_PARAM_FIPS_KEY_CHECK Ns ) <integer>
If required this parameter should be set using
.Fn OSSL_FUNC_keymgmt_gen_set_params
or
.Fn OSSL_FUNC_keymgmt_gen_init .
The default value of 1 causes an error during the init if the key is not
FIPS approved (e.g.
The key has a security strength of less than 112 bits).
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.It \(dqsign-check" ( Ns Sy OSSL_PKEY_PARAM_FIPS_SIGN_CHECK Ns ) <integer>
If required this parameter should be set before the
.Fn OSSL_FUNC_keymgmt_gen
function.
This value is not supported by all keygen algorithms.
The default value of 1 will cause an error if the generated key is not
allowed to be used for signing.
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Sh RETURN VALUES
.Fn OSSL_FUNC_keymgmt_new
and
.Fn OSSL_FUNC_keymgmt_dup
should return a valid reference to the newly created provider side key
object, or NULL on failure.
.Pp
.Fn OSSL_FUNC_keymgmt_import ,
.Fn OSSL_FUNC_keymgmt_export ,
.Fn OSSL_FUNC_keymgmt_get_params
and
.Fn OSSL_FUNC_keymgmt_set_params
should return 1 for success or 0 on error.
.Pp
.Fn OSSL_FUNC_keymgmt_validate
should return 1 on successful validation, or 0 on failure.
.Pp
.Fn OSSL_FUNC_keymgmt_has
should return 1 if all the selected data subsets are contained in the
given
.Fa keydata
or 0 otherwise.
.Pp
.Fn OSSL_FUNC_keymgmt_query_operation_name
should return a pointer to a string matching the requested operation, or
NULL if the same name used to fetch the keymgmt applies.
.Pp
.Fn OSSL_FUNC_keymgmt_gettable_params
and
.Fn OSSL_FUNC_keymgmt_settable_params
.Fn OSSL_FUNC_keymgmt_import_types ,
.Fn OSSL_FUNC_keymgmt_import_types_ex ,
.Fn OSSL_FUNC_keymgmt_export_types ,
.Fn OSSL_FUNC_keymgmt_export_types_ex
should always return a constant
.Xr OSSL_PARAM 3
array.
.Sh SEE ALSO
.Xr EVP_PKEY_get_size 3 ,
.Xr EVP_PKEY_get_bits 3 ,
.Xr EVP_PKEY_get_security_bits 3 ,
.Xr provider 7 ,
.Xr EVP_PKEY-X25519 7 ,
.Xr EVP_PKEY-X448 7 ,
.Xr EVP_PKEY-ED25519 7 ,
.Xr EVP_PKEY-ED448 7 ,
.Xr EVP_PKEY-EC 7 ,
.Xr EVP_PKEY-RSA 7 ,
.Xr EVP_PKEY-DSA 7 ,
.Xr EVP_PKEY-DH 7 ,
.Xr EVP_PKEY-ML-DSA 7 ,
.Xr EVP_PKEY-ML-KEM 7 ,
.Xr EVP_PKEY-SLH-DSA 7 .
.Sh HISTORY
The KEYMGMT interface was introduced in OpenSSL 3.0.
.Pp
Functions
.Fn OSSL_FUNC_keymgmt_import_types_ex ,
and
.Fn OSSL_FUNC_keymgmt_export_types_ex
were added with OpenSSL 3.2.
.Pp
The functions
.Fn OSSL_FUNC_keymgmt_gen_get_params
and
.Fn OSSL_FUNC_keymgmt_gen_gettable_params
were added in OpenSSL 3.4.
.Pp
The parameters "sign-check" and "fips-indicator" were added in OpenSSL
3.4.
.Pp
Support for the
.Sy ML-DSA ,
.Sy ML-KEM
and
.Sy SLH-DSA
algorithms was added in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
