.Dd 2025-09-30
.Dt PROVIDER-CIPHER 7ossl
.Os
.Sh NAME
.Nm provider-cipher
.Nd The cipher library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Context management */
 void *
.Fo OSSL_FUNC_cipher_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_cipher_freectx
.Fa "void *cctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_cipher_dupctx
.Fa "void *cctx"
.Fc
.Ft /* Encryption/decryption */
 int
.Fo OSSL_FUNC_cipher_encrypt_init
.Fa "void *cctx"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "const unsigned char *iv"
.Fa "size_t ivlen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_decrypt_init
.Fa "void *cctx"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "const unsigned char *iv"
.Fa "size_t ivlen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_encrypt_skey_init
.Fa "void *cctx"
.Fa "void *skeydata"
.Fa "const unsigned char *iv"
.Fa "size_t ivlen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_encrypt_skey_init
.Fa "void *cctx"
.Fa "void *skeydata"
.Fa "const unsigned char *iv"
.Fa "size_t ivlen"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_update
.Fa "void *cctx"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsize"
.Fa "const unsigned char *in"
.Fa "size_t inl"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_final
.Fa "void *cctx"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsize"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_cipher
.Fa "void *cctx"
.Fa "unsigned char *out"
.Fa "size_t *outl"
.Fa "size_t outsize"
.Fa "const unsigned char *in"
.Fa "size_t inl"
.Fc
.Ft /* Encryption/decryption using cipher pipeline */
 int
.Fo OSSL_FUNC_cipher_pipeline_encrypt_init
.Fa "void *cctx"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "size_t numpipes"
.Fa "const unsigned char **iv"
.Fa "size_t ivlen"
.Fa "const OSSL_PARAM params[]"
.Fc
)
.Ft int
.Fo OSSL_FUNC_cipher_pipeline_decrypt_init
.Fa "void *cctx"
.Fa "const unsigned char *key"
.Fa "size_t keylen"
.Fa "size_t numpipes"
.Fa "const unsigned char **iv"
.Fa "size_t ivlen"
.Fa "const OSSL_PARAM params[]"
.Fc
)
.Ft int
.Fo OSSL_FUNC_cipher_pipeline_update
.Fa "void *cctx"
.Fa "size_t numpipes"
.Fa "unsigned char **out"
.Fa "size_t *outl"
.Fa "const size_t *outsize"
.Fa "const unsigned char **in"
.Fa "const size_t *inl"
.Fc
)
.Ft int
.Fo OSSL_FUNC_cipher_pipeline_final
.Fa "void *cctx"
.Fa "size_t numpipes"
.Fa "unsigned char **out"
.Fa "size_t *outl"
.Fa "const size_t *outsize"
.Fc
)
.Ft /* Cipher parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_cipher_gettable_params
.Fa "void *provctx"
.Fc
.Ft /* Cipher operation parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_cipher_gettable_ctx_params
.Fa "void *cctx"
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_cipher_settable_ctx_params
.Fa "void *cctx"
.Fa "void *provctx"
.Fc
.Ft /* Cipher parameters */
 int
.Fo OSSL_FUNC_cipher_get_params
.Fa "OSSL_PARAM params[]"
.Fc
.Ft /* Cipher operation parameters */
 int
.Fo OSSL_FUNC_cipher_get_ctx_params
.Fa "void *cctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_cipher_set_ctx_params
.Fa "void *cctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The CIPHER operation enables providers to implement cipher algorithms
and make them available to applications via the API functions
.Xr EVP_EncryptInit_ex 3 ,
.Xr EVP_EncryptUpdate 3
and
.Xr EVP_EncryptFinal 3
(as well as the decrypt equivalents and other related functions).
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_cipher_newctx
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_cipher_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_cipher_newctx_fn
     OSSL_FUNC_cipher_newctx(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_cipher_newctx                    OSSL_FUNC_CIPHER_NEWCTX
 OSSL_FUNC_cipher_freectx                   OSSL_FUNC_CIPHER_FREECTX
 OSSL_FUNC_cipher_dupctx                    OSSL_FUNC_CIPHER_DUPCTX

 OSSL_FUNC_cipher_encrypt_init              OSSL_FUNC_CIPHER_ENCRYPT_INIT
 OSSL_FUNC_cipher_decrypt_init              OSSL_FUNC_CIPHER_DECRYPT_INIT
 OSSL_FUNC_cipher_encrypt_skey_init         OSSL_FUNC_CIPHER_ENCRYPT_SKEY_INIT
 OSSL_FUNC_cipher_decrypt_skey_init         OSSL_FUNC_CIPHER_DECRYPT_SKEY_INIT
 OSSL_FUNC_cipher_update                    OSSL_FUNC_CIPHER_UPDATE
 OSSL_FUNC_cipher_final                     OSSL_FUNC_CIPHER_FINAL
 OSSL_FUNC_cipher_cipher                    OSSL_FUNC_CIPHER_CIPHER

 OSSL_FUNC_cipher_pipeline_encrypt_init     OSSL_FUNC_CIPHER_PIPELINE_ENCRYPT_INIT
 OSSL_FUNC_cipher_pipeline_decrypt_init     OSSL_FUNC_CIPHER_PIPELINE_DECRYPT_INIT
 OSSL_FUNC_cipher_pipeline_update           OSSL_FUNC_CIPHER_PIPELINE_UPDATE
 OSSL_FUNC_cipher_pipeline_final            OSSL_FUNC_CIPHER_PIPELINE_FINAL

 OSSL_FUNC_cipher_get_params                OSSL_FUNC_CIPHER_GET_PARAMS
 OSSL_FUNC_cipher_get_ctx_params            OSSL_FUNC_CIPHER_GET_CTX_PARAMS
 OSSL_FUNC_cipher_set_ctx_params            OSSL_FUNC_CIPHER_SET_CTX_PARAMS

 OSSL_FUNC_cipher_gettable_params           OSSL_FUNC_CIPHER_GETTABLE_PARAMS
 OSSL_FUNC_cipher_gettable_ctx_params       OSSL_FUNC_CIPHER_GETTABLE_CTX_PARAMS
 OSSL_FUNC_cipher_settable_ctx_params       OSSL_FUNC_CIPHER_SETTABLE_CTX_PARAMS
.Ed
.Pp
A cipher algorithm implementation may not implement all of these
functions.
In order to be a consistent set of functions there must at least be a
complete set of "encrypt" functions, or a complete set of "decrypt"
functions, or a single "cipher" function.
Similarly, there can be a complete set of pipeline "encrypt" functions,
and/or a complete set of pipeline "decrypt" functions.
In all cases the OSSL_FUNC_cipher_get_params and both
OSSL_FUNC_cipher_newctx and OSSL_FUNC_cipher_freectx functions must be
present.
All other functions are optional.
.Ss Context Management Functions
.Fn OSSL_FUNC_cipher_newctx
should create and return a pointer to a provider side structure for
holding context information during a cipher operation.
A pointer to this context will be passed back in a number of the other
cipher operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
.Pp
.Fn OSSL_FUNC_cipher_freectx
is passed a pointer to the provider side cipher context in the
.Fa cctx
parameter.
This function should free any resources associated with that context.
.Pp
.Fn OSSL_FUNC_cipher_dupctx
should duplicate the provider side cipher context in the
.Fa cctx
parameter and return the duplicate copy.
.Ss Encryption/Decryption Functions
.Fn OSSL_FUNC_cipher_encrypt_init
initialises a cipher operation for encryption given a newly created
provider side cipher context in the
.Fa cctx
parameter.
The key to be used is given in
.Fa key
which is
.Fa keylen
bytes long.
The IV to be used is given in
.Fa iv
which is
.Fa ivlen
bytes long.
The
.Em params ,
if not NULL, should be set on the context in a manner similar to using
.Fn OSSL_FUNC_cipher_set_ctx_params .
.Pp
.Fn OSSL_FUNC_cipher_decrypt_init
is the same as
.Fn OSSL_FUNC_cipher_encrypt_init
except that it initialises the context for a decryption operation.
.Pp
.Fn OSSL_FUNC_cipher_encrypt_skey_init
and
.Xr OSSL_FUNC_cipher_decrypt_skey_init 3
are variants of
.Fn OSSL_FUNC_cipher_encrypt_init
and
.Fn OSSL_FUNC_cipher_decrypt_init
for working with opaque objects containing provider-specific key handles
instead of raw bytes.
.Pp
.Fn OSSL_FUNC_cipher_update
is called to supply data to be encrypted/decrypted as part of a
previously initialised cipher operation.
The
.Fa cctx
parameter contains a pointer to a previously initialised provider side
context.
.Fn OSSL_FUNC_cipher_update
should encrypt/decrypt
.Fa inl
bytes of data at the location pointed to by
.Fa in .
The encrypted data should be stored in
.Fa out
and the amount of data written to
.Em *outl
which should not exceed
.Fa outsize
bytes.
.Fn OSSL_FUNC_cipher_update
may be called multiple times for a single cipher operation.
It is the responsibility of the cipher implementation to handle input
lengths that are not multiples of the block length.
In such cases a cipher implementation will typically cache partial
blocks of input data until a complete block is obtained.
The pointers
.Fa out
and
.Fa in
may point to the same location, in which case the encryption must be
done in-place.
If
.Fa out
and
.Fa in
point to different locations, the requirements of
.Xr EVP_EncryptUpdate 3
and
.Xr EVP_DecryptUpdate 3
guarantee that the two buffers are disjoint.
Similarly, the requirements of
.Xr EVP_EncryptUpdate 3
and
.Xr EVP_DecryptUpdate 3
ensure that the buffer pointed to by
.Fa out
contains sufficient room for the operation being performed.
.Pp
.Fn OSSL_FUNC_cipher_final
completes an encryption or decryption started through previous
.Fn OSSL_FUNC_cipher_encrypt_init
or
.Fn OSSL_FUNC_cipher_decrypt_init ,
and
.Fn OSSL_FUNC_cipher_update
calls.
The
.Fa cctx
parameter contains a pointer to the provider side context.
Any final encryption/decryption output should be written to
.Fa out
and the amount of data written to
.Em *outl
which should not exceed
.Fa outsize
bytes.
The same expectations apply to
.Fa outsize
as documented for
.Xr EVP_EncryptFinal 3
and
.Xr EVP_DecryptFinal 3 .
.Pp
.Fn OSSL_FUNC_cipher_cipher
performs encryption/decryption using the provider side cipher context in
the
.Fa cctx
parameter that should have been previously initialised via a call to
.Fn OSSL_FUNC_cipher_encrypt_init
or
.Fn OSSL_FUNC_cipher_decrypt_init .
This should call the raw underlying cipher function without any padding.
This will be invoked in the provider as a result of the application
calling
.Xr EVP_Cipher 3 .
The application is responsible for ensuring that the input is a multiple
of the block length.
The data to be encrypted/decrypted will be in
.Fa in ,
and it will be
.Fa inl
bytes in length.
The output from the encryption/decryption should be stored in
.Fa out
and the amount of data stored should be put in
.Em *outl
which should be no more than
.Fa outsize
bytes.
.Pp
.Fn OSSL_FUNC_cipher_pipeline_encrypt_init ,
.Fn OSSL_FUNC_cipher_pipeline_decrypt_init
.Fn OSSL_FUNC_cipher_pipeline_update ,
and
.Fn OSSL_FUNC_cipher_pipeline_final
are similar to the non-pipeline variants, but are used when the
application is using cipher pipelining.
The
.Fa numpipes
parameter is the number of pipes in the pipeline.
The
.Fa iv
parameter is an array of buffers with IVs, each
.Fa ivlen
bytes long.
The
.Fa in
and
.Fa out
are arrays of buffer pointers.
The
.Fa inl
and
.Fa outl ,
.Fa outsize
are arrays of size_t representing corresponding buffer length as similar
to the non-pipeline variants.
All arrays are of length
.Fa numpipes .
See
.Xr EVP_CipherPipelineEncryptInit 3
for more information.
.Ss Cipher Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by these functions.
.Pp
.Fn OSSL_FUNC_cipher_get_params
gets details of the algorithm implementation and stores them in
.Em params .
.Pp
.Fn OSSL_FUNC_cipher_set_ctx_params
sets cipher operation parameters for the provider side cipher context
.Fa cctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_cipher_get_ctx_params
gets cipher operation details details from the given provider side
cipher context
.Fa cctx
and stores them in
.Em params .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_cipher_gettable_params ,
.Fn OSSL_FUNC_cipher_gettable_ctx_params ,
and
.Fn OSSL_FUNC_cipher_settable_ctx_params
all return constant
.Xr OSSL_PARAM 3
arrays as descriptors of the parameters that
.Fn OSSL_FUNC_cipher_get_params ,
.Fn OSSL_FUNC_cipher_get_ctx_params ,
and
.Fn OSSL_FUNC_cipher_set_ctx_params
can handle, respectively.
.Fn OSSL_FUNC_cipher_gettable_ctx_params
and
.Fn OSSL_FUNC_cipher_settable_ctx_params
will return the parameters associated with the provider side context
.Fa cctx
in its current state if it is not NULL. Otherwise, they return the
parameters associated with the provider side algorithm
.Fa provctx .
.Pp
Parameters currently recognised by built-in ciphers are listed in
.Xr EVP_EncryptInit 3 .
Not all parameters are relevant to, or are understood by all ciphers.
.Sh RETURN VALUES
.Fn OSSL_FUNC_cipher_newctx
and
.Fn OSSL_FUNC_cipher_dupctx
should return the newly created provider side cipher context, or NULL on
failure.
.Pp
.Fn OSSL_FUNC_cipher_encrypt_init ,
.Fn OSSL_FUNC_cipher_decrypt_init ,
.Fn OSSL_FUNC_cipher_update ,
.Fn OSSL_FUNC_cipher_final ,
.Fn OSSL_FUNC_cipher_cipher ,
.Fn OSSL_FUNC_cipher_encrypt_skey_init ,
.Xr OSSL_FUNC_cipher_decrypt_skey_init 3 ,
.Fn OSSL_FUNC_cipher_pipeline_encrypt_init ,
.Fn OSSL_FUNC_cipher_pipeline_decrypt_init ,
.Fn OSSL_FUNC_cipher_pipeline_update ,
.Fn OSSL_FUNC_cipher_pipeline_final ,
.Fn OSSL_FUNC_cipher_get_params ,
.Fn OSSL_FUNC_cipher_get_ctx_params
and
.Fn OSSL_FUNC_cipher_set_ctx_params
should return 1 for success or 0 on error.
.Pp
.Fn OSSL_FUNC_cipher_gettable_params ,
.Fn OSSL_FUNC_cipher_gettable_ctx_params
and
.Fn OSSL_FUNC_cipher_settable_ctx_params
should return a constant
.Xr OSSL_PARAM 3
array, or NULL if none is offered.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr OSSL_PROVIDER-FIPS 7 ,
.Xr OSSL_PROVIDER-default 7 ,
.Xr OSSL_PROVIDER-legacy 7 ,
.Xr EVP_CIPHER-AES 7 ,
.Xr EVP_CIPHER-ARIA 7 ,
.Xr EVP_CIPHER-BLOWFISH 7 ,
.Xr EVP_CIPHER-CAMELLIA 7 ,
.Xr EVP_CIPHER-CAST 7 ,
.Xr EVP_CIPHER-CHACHA 7 ,
.Xr EVP_CIPHER-DES 7 ,
.Xr EVP_CIPHER-IDEA 7 ,
.Xr EVP_CIPHER-RC2 7 ,
.Xr EVP_CIPHER-RC4 7 ,
.Xr EVP_CIPHER-RC5 7 ,
.Xr EVP_CIPHER-SEED 7 ,
.Xr EVP_CIPHER-SM4 7 ,
.Xr EVP_CIPHER-NULL 7 ,
.Xr life_cycle-cipher 7 ,
.Xr EVP_EncryptInit 3
.Sh HISTORY
The provider CIPHER interface was introduced in OpenSSL 3.0.
.Pp
The
.Fn OSSL_FUNC_cipher_encrypt_skey_init
and
.Xr OSSL_FUNC_cipher_decrypt_skey_init 3
were introduced in OpenSSL 3.5.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
