.Dd 2025-09-30
.Dt PROVIDER-RAND 7ossl
.Os
.Sh NAME
.Nm provider-rand
.Nd The random number generation library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Context management */
 void *
.Fo OSSL_FUNC_rand_newctx
.Fa "void *provctx"
.Fa "void *parent"
.Fa "const OSSL_DISPATCH *parent_calls"
.Fc
.Ft void
.Fo OSSL_FUNC_rand_freectx
.Fa "void *ctx"
.Fc
.Ft /* Random number generator functions: NIST */
 int
.Fo OSSL_FUNC_rand_instantiate
.Fa "void *ctx"
.Fa "unsigned int strength"
.Fa "int prediction_resistance"
.Fa "const unsigned char *pstr"
.Fa "size_t pstr_len"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_uninstantiate
.Fa "void *ctx"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_generate
.Fa "void *ctx"
.Fa "unsigned char *out"
.Fa "size_t outlen"
.Fa "unsigned int strength"
.Fa "int prediction_resistance"
.Fa "const unsigned char *addin"
.Fa "size_t addin_len"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_reseed
.Fa "void *ctx"
.Fa "int prediction_resistance"
.Fa "const unsigned char *ent"
.Fa "size_t ent_len"
.Fa "const unsigned char *addin"
.Fa "size_t addin_len"
.Fc
.Ft /* Random number generator functions: additional */
 size_t
.Fo OSSL_FUNC_rand_nonce
.Fa "void *ctx"
.Fa "unsigned char *out"
.Fa "size_t outlen"
.Fa "int strength"
.Fa "size_t min_noncelen"
.Fa "size_t max_noncelen"
.Fc
.Ft size_t
.Fo OSSL_FUNC_rand_get_seed
.Fa "void *ctx"
.Fa "unsigned char **buffer"
.Fa "int entropy"
.Fa "size_t min_len"
.Fa "size_t max_len"
.Fa "int prediction_resistance"
.Fa "const unsigned char *adin"
.Fa "size_t adin_len"
.Fc
.Ft void
.Fo OSSL_FUNC_rand_clear_seed
.Fa "void *ctx"
.Fa "unsigned char *buffer"
.Fa "size_t b_len"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_verify_zeroization
.Fa "void *ctx"
.Fc
.Ft /* Context Locking */
 int
.Fo OSSL_FUNC_rand_enable_locking
.Fa "void *ctx"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_lock
.Fa "void *ctx"
.Fc
.Ft void
.Fo OSSL_FUNC_rand_unlock
.Fa "void *ctx"
.Fc
.Ft /* RAND parameter descriptors */
 const OSSL_PARAM *
.Fo OSSL_FUNC_rand_gettable_params
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_rand_gettable_ctx_params
.Fa "void *ctx"
.Fa "void *provctx"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_rand_settable_ctx_params
.Fa "void *ctx"
.Fa "void *provctx"
.Fc
.Ft /* RAND parameters */
 int
.Fo OSSL_FUNC_rand_get_params
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_get_ctx_params
.Fa "void *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_rand_set_ctx_params
.Fa "void *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The RAND operation enables providers to implement random number
generation algorithms and random number sources and make them available
to applications via the API function
.Xr EVP_RAND 3 .
.Ss Context Management Functions
.Fn OSSL_FUNC_rand_newctx
should create and return a pointer to a provider side structure for
holding context information during a rand operation.
A pointer to this context will be passed back in a number of the other
rand operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
The parameter
.Fa parent
specifies another rand instance to be used for seeding purposes.
If NULL and the specific instance supports it, the operating system will
be used for seeding.
The parameter
.Fa parent_calls
points to the dispatch table for
.Fa parent .
Thus, the parent need not be from the same provider as the new instance.
.Pp
.Fn OSSL_FUNC_rand_freectx
is passed a pointer to the provider side rand context in the
.Em mctx
parameter.
If it receives NULL as
.Fa ctx
value, it should not do anything other than return.
This function should free any resources associated with that context.
.Ss Random Number Generator Functions: NIST
These functions correspond to those defined in NIST SP 800-90A and SP
800-90C.
.Pp
.Fn OSSL_FUNC_rand_instantiate
is used to instantiate the DRBG
.Fa ctx
at a requested security
.Fa strength .
In addition,
.Fa prediction_resistance
can be requested.
Additional input
.Fa addin
of length
.Fa addin_len
bytes can optionally be provided.
The parameters specified in
.Em params
configure the DRBG and these should be processed before instantiation.
.Pp
.Fn OSSL_FUNC_rand_uninstantiate
is used to uninstantiate the DRBG
.Fa ctx .
After being uninstantiated, a DRBG is unable to produce output until it
is instantiated anew.
.Pp
.Fn OSSL_FUNC_rand_generate
is used to generate random bytes from the DRBG
.Fa ctx .
It will generate
.Fa outlen
bytes placing them into the buffer pointed to by
.Fa out .
The generated bytes will meet the specified security
.Fa strength
and, if
.Fa prediction_resistance
is true, the bytes will be produced after reseeding from a live entropy
source.
Additional input
.Fa addin
of length
.Fa addin_len
bytes can optionally be provided.
.Ss Random Number Generator Functions: Additional
.Fn OSSL_FUNC_rand_nonce
is used to generate a nonce of the given
.Fa strength
with a length from
.Fa min_noncelen
to
.Fa max_noncelen .
If the output buffer
.Fa out
is NULL, the length of the nonce should be returned.
.Pp
.Fn OSSL_FUNC_rand_get_seed
is used by deterministic generators to obtain their seeding material
from their parent.
The seed bytes will meet the specified security level of
.Fa entropy
bits and there will be between
.Fa min_len
and
.Fa max_len
inclusive bytes in total.
If
.Fa prediction_resistance
is true, the bytes will be produced from a live entropy source.
Additional input
.Fa addin
of length
.Fa addin_len
bytes can optionally be provided.
A pointer to the seed material is returned in
.Em *buffer
and this must be freed by a later call to
.Fn OSSL_FUNC_rand_clear_seed .
.Pp
.Fn OSSL_FUNC_rand_clear_seed
frees a seed
.Fa buffer
of length
.Fa b_len
bytes which was previously allocated by
.Fn OSSL_FUNC_rand_get_seed .
.Pp
.Fn OSSL_FUNC_rand_verify_zeroization
is used to determine if the internal state of the DRBG is zero.
This capability is mandated by NIST as part of the self tests, it is
unlikely to be useful in other circumstances.
.Ss Context Locking
When DRBGs are used by multiple threads, there must be locking employed
to ensure their proper operation.
Because locking introduces an overhead, it is disabled by default.
.Pp
.Fn OSSL_FUNC_rand_enable_locking
allows locking to be turned on for a DRBG and all of its parent DRBGs.
From this call onwards, the DRBG can be used in a thread safe manner.
.Pp
.Fn OSSL_FUNC_rand_lock
is used to lock a DRBG. Once locked, exclusive access is guaranteed.
.Pp
.Fn OSSL_FUNC_rand_unlock
is used to unlock a DRBG.
.Ss Rand Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by these functions.
.Pp
.Fn OSSL_FUNC_rand_get_params
gets details of parameter values associated with the provider algorithm
and stores them in
.Em params .
.Pp
.Fn OSSL_FUNC_rand_set_ctx_params
sets rand parameters associated with the given provider side rand
context
.Fa ctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_rand_get_ctx_params
gets details of currently set parameter values associated with the given
provider side rand context
.Fa ctx
and stores them in
.Em params .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_rand_gettable_params ,
.Fn OSSL_FUNC_rand_gettable_ctx_params ,
and
.Fn OSSL_FUNC_rand_settable_ctx_params
all return constant
.Xr OSSL_PARAM 3
arrays as descriptors of the parameters that
.Fn OSSL_FUNC_rand_get_params ,
.Fn OSSL_FUNC_rand_get_ctx_params ,
and
.Fn OSSL_FUNC_rand_set_ctx_params
can handle, respectively.
.Fn OSSL_FUNC_rand_gettable_ctx_params
and
.Fn OSSL_FUNC_rand_settable_ctx_params
will return the parameters associated with the provider side context
.Fa ctx
in its current state if it is not NULL. Otherwise, they return the
parameters associated with the provider side algorithm
.Fa provctx .
.Pp
Parameters currently recognised by built-in rands are as follows.
Not all parameters are relevant to, or are understood by all rands:
.Bl -tag -width Ds
.It \(dqstate" ( Ns Sy OSSL_RAND_PARAM_STATE Ns ) <integer>
Returns the state of the random number generator.
.It \(dqstrength" ( Ns Sy OSSL_RAND_PARAM_STRENGTH Ns ) <unsigned integer>
Returns the bit strength of the random number generator.
.It \(dqfips-indicator" ( Ns Sy OSSL_RAND_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This option is used by the OpenSSL FIPS provider and is not supported by
all EVP_RAND sources.
.El
.Pp
For rands that are also deterministic random bit generators (DRBGs),
these additional parameters are recognised.
Not all parameters are relevant to, or are understood by all DRBG rands:
.Bl -tag -width Ds
.It \(dqreseed_requests" ( Ns Sy OSSL_DRBG_PARAM_RESEED_REQUESTS Ns ) <unsigned integer>
Reads or set the number of generate requests before reseeding the
associated RAND ctx.
.It \(dqreseed_time_interval" ( Ns Sy OSSL_DRBG_PARAM_RESEED_TIME_INTERVAL Ns ) <integer>
Reads or set the number of elapsed seconds before reseeding the
associated RAND ctx.
.It \(dqmax_request" ( Ns Sy OSSL_DRBG_PARAM_RESEED_REQUESTS Ns ) <unsigned integer>
Specifies the maximum number of bytes that can be generated in a single
call to OSSL_FUNC_rand_generate.
.It \(dqmin_entropylen" ( Ns Sy OSSL_DRBG_PARAM_MIN_ENTROPYLEN Ns ) <unsigned integer>
.It \(dqmax_entropylen" ( Ns Sy OSSL_DRBG_PARAM_MAX_ENTROPYLEN Ns ) <unsigned integer>
Specify the minimum and maximum number of bytes of random material that
can be used to seed the DRBG.
.It \(dqmin_noncelen" ( Ns Sy OSSL_DRBG_PARAM_MIN_NONCELEN Ns ) <unsigned integer>
.It \(dqmax_noncelen" ( Ns Sy OSSL_DRBG_PARAM_MAX_NONCELEN Ns ) <unsigned integer>
Specify the minimum and maximum number of bytes of nonce that can be
used to instantiate the DRBG.
.It \(dqmax_perslen" ( Ns Sy OSSL_DRBG_PARAM_MAX_PERSLEN Ns ) <unsigned integer>
.It \(dqmax_adinlen" ( Ns Sy OSSL_DRBG_PARAM_MAX_ADINLEN Ns ) <unsigned integer>
Specify the minimum and maximum number of bytes of personalisation
string that can be used with the DRBG.
.It \(dqreseed_counter" ( Ns Sy OSSL_DRBG_PARAM_RESEED_COUNTER Ns ) <unsigned integer>
Specifies the number of times the DRBG has been seeded or reseeded.
.It \(dqdigest" ( Ns Sy OSSL_DRBG_PARAM_DIGEST Ns ) <UTF8 string>
.It \(dqcipher" ( Ns Sy OSSL_DRBG_PARAM_CIPHER Ns ) <UTF8 string>
.It \(dqmac" ( Ns Sy OSSL_DRBG_PARAM_MAC Ns ) <UTF8 string>
Sets the name of the underlying cipher, digest or MAC to be used.
It must name a suitable algorithm for the DRBG that's being used.
.It \(dqproperties" ( Ns Sy OSSL_DRBG_PARAM_PROPERTIES Ns ) <UTF8 string>
Sets the properties to be queried when trying to fetch an underlying
algorithm.
This must be given together with the algorithm naming parameter to be
considered valid.
.El
.Pp
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_DRBG_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling
.Fn OSSL_FUNC_rand_generate .
It may return 0 if the "digest-check" is set to 0.
.It \(dqdigest-check" ( Ns Sy OSSL_DRBG_PARAM_FIPS_DIGEST_CHECK Ns ) <integer>
If required this parameter should be set before the digest is set.
The default value of 1 causes an error when the digest is set if the
digest is not FIPS approved (e.g.
truncated digests).
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Sh RETURN VALUES
.Fn OSSL_FUNC_rand_newctx
should return the newly created provider side rand context, or NULL on
failure.
.Pp
.Fn OSSL_FUNC_rand_gettable_params ,
.Fn OSSL_FUNC_rand_gettable_ctx_params
and
.Fn OSSL_FUNC_rand_settable_ctx_params
should return a constant
.Xr OSSL_PARAM 3
array, or NULL if none is offered.
.Pp
.Fn OSSL_FUNC_rand_nonce
returns the size of the generated nonce, or 0 on error.
.Pp
.Fn OSSL_FUNC_rand_get_seed
returns the size of the generated seed, or 0 on error.
.Pp
All of the remaining functions should return 1 for success or 0 on
error.
.Sh NOTES
The RAND life-cycle is described in
.Xr life_cycle-rand 7 .
Providers should ensure that the various transitions listed there are
supported.
At some point the EVP layer will begin enforcing the listed transitions.
.Sh SEE ALSO
.Xr provider 7 ,
.Xr RAND 7 ,
.Xr EVP_RAND 7 ,
.Xr life_cycle-rand 7 ,
.Xr EVP_RAND 3
.Sh HISTORY
The provider RAND interface was introduced in OpenSSL 3.0. The Rand
Parameters "fips-indicator" and "digest-check" were added in OpenSSL
3.4.
.Sh COPYRIGHT
Copyright 2020-2024 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
