.Dd 2025-09-30
.Dt PROVIDER-ASYM_CIPHER 7ossl
.Os
.Sh NAME
.Nm provider-asym_cipher
.Nd The asym_cipher library \(la-\(ra provider functions
.Sh SYNOPSIS
.In openssl/core_dispatch.h
.In openssl/core_names.h
.Ft /*
  * None of these are actual functions, but are displayed like this for
  * the function signatures for functions that are offered as function
  * pointers in OSSL_DISPATCH arrays.
  */

 /* Context management */
 void *
.Fo OSSL_FUNC_asym_cipher_newctx
.Fa "void *provctx"
.Fc
.Ft void
.Fo OSSL_FUNC_asym_cipher_freectx
.Fa "void *ctx"
.Fc
.Ft void *
.Fo OSSL_FUNC_asym_cipher_dupctx
.Fa "void *ctx"
.Fc
.Ft /* Encryption */
 int
.Fo OSSL_FUNC_asym_cipher_encrypt_init
.Fa "void *ctx"
.Fa "void *provkey"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_asym_cipher_encrypt
.Fa "void *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outlen"
.Fa "size_t outsize"
.Fa "const unsigned char *in"
.Fa "size_t inlen"
.Fc
.Ft /* Decryption */
 int
.Fo OSSL_FUNC_asym_cipher_decrypt_init
.Fa "void *ctx"
.Fa "void *provkey"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft int
.Fo OSSL_FUNC_asym_cipher_decrypt
.Fa "void *ctx"
.Fa "unsigned char *out"
.Fa "size_t *outlen"
.Fa "size_t outsize"
.Fa "const unsigned char *in"
.Fa "size_t inlen"
.Fc
.Ft /* Asymmetric Cipher parameters */
 int
.Fo OSSL_FUNC_asym_cipher_get_ctx_params
.Fa "void *ctx"
.Fa "OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_asym_cipher_gettable_ctx_params
.Fa "void *provctx"
.Fc
.Ft int
.Fo OSSL_FUNC_asym_cipher_set_ctx_params
.Fa "void *ctx"
.Fa "const OSSL_PARAM params[]"
.Fc
.Ft const OSSL_PARAM *
.Fo OSSL_FUNC_asym_cipher_settable_ctx_params
.Fa "void *provctx"
.Fc
.Sh DESCRIPTION
This documentation is primarily aimed at provider authors.
See
.Xr provider 7
for further information.
.Pp
The asymmetric cipher (OSSL_OP_ASYM_CIPHER) operation enables providers
to implement asymmetric cipher algorithms and make them available to
applications via the API functions
.Xr EVP_PKEY_encrypt 3 ,
.Xr EVP_PKEY_decrypt 3
and other related functions).
.Pp
All "functions" mentioned here are passed as function pointers between
.Pa libcrypto
and the provider in
.Xr OSSL_DISPATCH 3
arrays via
.Xr OSSL_ALGORITHM 3
arrays that are returned by the provider's
.Xr provider_query_operation 3
function (see
.Xr provider-base 7 Ns ).
.Pp
All these "functions" have a corresponding function type definition
named
.Sy OSSL_FUNC_{name}_fn ,
and a helper function to retrieve the function pointer from an
.Xr OSSL_DISPATCH 3
element named
.Sy OSSL_FUNC_{name} .
For example, the "function"
.Fn OSSL_FUNC_asym_cipher_newctx
has these:
.Bd -literal
 typedef void *(OSSL_FUNC_asym_cipher_newctx_fn)(void *provctx);
 static ossl_inline OSSL_FUNC_asym_cipher_newctx_fn
     OSSL_FUNC_asym_cipher_newctx(const OSSL_DISPATCH *opf);
.Ed
.Pp
.Xr OSSL_DISPATCH 3
arrays are indexed by numbers that are provided as macros in
.Xr openssl-core_dispatch.h 7 ,
as follows:
.Bd -literal
 OSSL_FUNC_asym_cipher_newctx               OSSL_FUNC_ASYM_CIPHER_NEWCTX
 OSSL_FUNC_asym_cipher_freectx              OSSL_FUNC_ASYM_CIPHER_FREECTX
 OSSL_FUNC_asym_cipher_dupctx               OSSL_FUNC_ASYM_CIPHER_DUPCTX

 OSSL_FUNC_asym_cipher_encrypt_init         OSSL_FUNC_ASYM_CIPHER_ENCRYPT_INIT
 OSSL_FUNC_asym_cipher_encrypt              OSSL_FUNC_ASYM_CIPHER_ENCRYPT

 OSSL_FUNC_asym_cipher_decrypt_init         OSSL_FUNC_ASYM_CIPHER_DECRYPT_INIT
 OSSL_FUNC_asym_cipher_decrypt              OSSL_FUNC_ASYM_CIPHER_DECRYPT

 OSSL_FUNC_asym_cipher_get_ctx_params       OSSL_FUNC_ASYM_CIPHER_GET_CTX_PARAMS
 OSSL_FUNC_asym_cipher_gettable_ctx_params  OSSL_FUNC_ASYM_CIPHER_GETTABLE_CTX_PARAMS
 OSSL_FUNC_asym_cipher_set_ctx_params       OSSL_FUNC_ASYM_CIPHER_SET_CTX_PARAMS
 OSSL_FUNC_asym_cipher_settable_ctx_params  OSSL_FUNC_ASYM_CIPHER_SETTABLE_CTX_PARAMS
.Ed
.Pp
An asymmetric cipher algorithm implementation may not implement all of
these functions.
In order to be a consistent set of functions a provider must implement
OSSL_FUNC_asym_cipher_newctx and OSSL_FUNC_asym_cipher_freectx.
It must also implement both of OSSL_FUNC_asym_cipher_encrypt_init and
OSSL_FUNC_asym_cipher_encrypt, or both of
OSSL_FUNC_asym_cipher_decrypt_init and OSSL_FUNC_asym_cipher_decrypt.
OSSL_FUNC_asym_cipher_get_ctx_params is optional but if it is present
then so must OSSL_FUNC_asym_cipher_gettable_ctx_params.
Similarly, OSSL_FUNC_asym_cipher_set_ctx_params is optional but if it is
present then so must OSSL_FUNC_asym_cipher_settable_ctx_params.
.Pp
An asymmetric cipher algorithm must also implement some mechanism for
generating, loading or importing keys via the key management
(OSSL_OP_KEYMGMT) operation.
See
.Xr provider-keymgmt 7
for further details.
.Ss Context Management Functions
.Fn OSSL_FUNC_asym_cipher_newctx
should create and return a pointer to a provider side structure for
holding context information during an asymmetric cipher operation.
A pointer to this context will be passed back in a number of the other
asymmetric cipher operation function calls.
The parameter
.Fa provctx
is the provider context generated during provider initialisation (see
.Xr provider 7 Ns ).
.Pp
.Fn OSSL_FUNC_asym_cipher_freectx
is passed a pointer to the provider side asymmetric cipher context in
the
.Fa ctx
parameter.
This function should free any resources associated with that context.
.Pp
.Fn OSSL_FUNC_asym_cipher_dupctx
should duplicate the provider side asymmetric cipher context in the
.Fa ctx
parameter and return the duplicate copy.
.Ss Encryption Functions
.Fn OSSL_FUNC_asym_cipher_encrypt_init
initialises a context for an asymmetric encryption given a provider side
asymmetric cipher context in the
.Fa ctx
parameter, and a pointer to a provider key object in the
.Fa provkey
parameter.
The
.Em params ,
if not NULL, should be set on the context in a manner similar to using
.Fn OSSL_FUNC_asym_cipher_set_ctx_params .
The key object should have been previously generated, loaded or imported
into the provider using the key management (OSSL_OP_KEYMGMT) operation
(see
.Xr provider-keymgmt 7 Ns ).
.Fn OSSL_FUNC_asym_cipher_encrypt
performs the actual encryption itself.
A previously initialised asymmetric cipher context is passed in the
.Fa ctx
parameter.
The data to be encrypted is pointed to by the
.Fa in
parameter which is
.Fa inlen
bytes long.
Unless
.Fa out
is NULL, the encrypted data should be written to the location pointed to
by the
.Fa out
parameter and it should not exceed
.Fa outsize
bytes in length.
The length of the encrypted data should be written to
.Em *outlen .
If
.Fa out
is NULL then the maximum length of the encrypted data should be written
to
.Em *outlen .
.Ss Decryption Functions
.Fn OSSL_FUNC_asym_cipher_decrypt_init
initialises a context for an asymmetric decryption given a provider side
asymmetric cipher context in the
.Fa ctx
parameter, and a pointer to a provider key object in the
.Fa provkey
parameter.
The
.Em params ,
if not NULL, should be set on the context in a manner similar to using
.Fn OSSL_FUNC_asym_cipher_set_ctx_params .
The key object should have been previously generated, loaded or imported
into the provider using the key management (OSSL_OP_KEYMGMT) operation
(see
.Xr provider-keymgmt 7 Ns ).
.Pp
.Fn OSSL_FUNC_asym_cipher_decrypt
performs the actual decryption itself.
A previously initialised asymmetric cipher context is passed in the
.Fa ctx
parameter.
The data to be decrypted is pointed to by the
.Fa in
parameter which is
.Fa inlen
bytes long.
Unless
.Fa out
is NULL, the decrypted data should be written to the location pointed to
by the
.Fa out
parameter and it should not exceed
.Fa outsize
bytes in length.
The length of the decrypted data should be written to
.Em *outlen .
If
.Fa out
is NULL then the maximum length of the decrypted data should be written
to
.Em *outlen .
.Ss Asymmetric Cipher Parameters
See
.Xr OSSL_PARAM 3
for further details on the parameters structure used by the
.Fn OSSL_FUNC_asym_cipher_get_ctx_params
and
.Fn OSSL_FUNC_asym_cipher_set_ctx_params
functions.
.Pp
.Fn OSSL_FUNC_asym_cipher_get_ctx_params
gets asymmetric cipher parameters associated with the given provider
side asymmetric cipher context
.Fa ctx
and stores them in
.Em params .
Passing NULL for
.Em params
should return true.
.Pp
.Fn OSSL_FUNC_asym_cipher_set_ctx_params
sets the asymmetric cipher parameters associated with the given provider
side asymmetric cipher context
.Fa ctx
to
.Em params .
Any parameter settings are additional to any that were previously set.
Passing NULL for
.Em params
should return true.
.Pp
Parameters currently recognised by built-in asymmetric cipher algorithms
are as follows.
Not all parameters are relevant to, or are understood by all asymmetric
cipher algorithms:
.Bl -tag -width Ds
.It \(dqpad-mode" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_PAD_MODE Ns ) <UTF8 string> OR <integer>
The type of padding to be used.
The interpretation of this value will depend on the algorithm in use.
.It \(dqdigest" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_OAEP_DIGEST Ns ) <UTF8 string>
Gets or sets the name of the OAEP digest algorithm used when OAEP
padding is in use.
.It \(dqdigest" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_DIGEST Ns ) <UTF8 string>
Gets or sets the name of the digest algorithm used by the algorithm
(where applicable).
.It \(dqdigest-props" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_OAEP_DIGEST_PROPS Ns ) <UTF8 string>
Gets or sets the properties to use when fetching the OAEP digest
algorithm.
.It \(dqdigest-props" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_DIGEST_PROPS Ns ) <UTF8 string>
Gets or sets the properties to use when fetching the cipher digest
algorithm.
.It \(dqmgf1-digest" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_MGF1_DIGEST Ns ) <UTF8 string>
Gets or sets the name of the MGF1 digest algorithm used when OAEP or PSS
padding is in use.
.It \(dqmgf1-digest-props" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_MGF1_DIGEST_PROPS Ns ) <UTF8 string>
Gets or sets the properties to use when fetching the MGF1 digest
algorithm.
.It \(dqoaep-label" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_OAEP_LABEL Ns ) <octet string ptr>
Gets the OAEP label used when OAEP padding is in use.
.It \(dqoaep-label" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_OAEP_LABEL Ns ) <octet string>
Sets the OAEP label used when OAEP padding is in use.
.It \(dqtls-client-version" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_TLS_CLIENT_VERSION Ns ) <unsigned integer>
The TLS protocol version first requested by the client.
.It \(dqtls-negotiated-version" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_TLS_CLIENT_VERSION Ns ) <unsigned integer>
The negotiated TLS protocol version.
.It \(dqimplicit-rejection" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_IMPLICIT_REJECTION Ns ) <unsigned integer>
Gets or sets the use of the implicit rejection mechanism for RSA PKCS#1
v1.5 decryption.
When set (non zero value), the decryption API will return a
deterministically random value if the PKCS#1 v1.5 padding check fails.
This makes exploitation of the Bleichenbacher significantly harder, even
if the code using the RSA decryption API is not implemented in
side-channel free manner.
Set by default in OpenSSL providers.
.El
.Pp
The OpenSSL FIPS provider also supports the following parameters:
.Bl -tag -width Ds
.It \(dqfips-indicator" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_FIPS_APPROVED_INDICATOR Ns ) <integer>
A getter that returns 1 if the operation is FIPS approved, or 0
otherwise.
This may be used after calling either
.Fn OSSL_FUNC_asym_cipher_encrypt
or
.Fn OSSL_FUNC_asym_cipher_decrypt .
It may return 0 if "key-check" is set to 0.
.It \(dqkey-check" ( Ns Sy OSSL_ASYM_CIPHER_PARAM_FIPS_KEY_CHECK Ns ) <integer>
If required this parameter should be set using either
.Fn OSSL_FUNC_asym_cipher_encrypt_init
or
.Fn OSSL_FUNC_asym_cipher_decrypt_init .
The default value of 1 causes an error during the init if the key is not
FIPS approved (e.g.
The key has a security strength of less than 112 bits).
Setting this to 0 will ignore the error and set the approved
"fips-indicator" to 0. This option breaks FIPS compliance if it causes
the approved "fips-indicator" to return 0.
.El
.Pp
.Fn OSSL_FUNC_asym_cipher_gettable_ctx_params
and
.Fn OSSL_FUNC_asym_cipher_settable_ctx_params
get a constant
.Xr OSSL_PARAM 3
array that describes the gettable and settable parameters, i.e.
parameters that can be used with
.Xr OSSL_FUNC_asym_cipherget_ctx_params 3
and
.Fn OSSL_FUNC_asym_cipher_set_ctx_params
respectively.
.Sh RETURN VALUES
.Fn OSSL_FUNC_asym_cipher_newctx
and
.Fn OSSL_FUNC_asym_cipher_dupctx
should return the newly created provider side asymmetric cipher context,
or NULL on failure.
.Pp
All other functions should return 1 for success or 0 on error.
.Sh SEE ALSO
.Xr provider 7
.Sh HISTORY
The provider ASYM_CIPHER interface was introduced in OpenSSL 3.0. The
Asymmetric Cipher Parameters "fips-indicator" and "key-check" were added
in OpenSSL 3.4.
.Sh COPYRIGHT
Copyright 2019-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
