.Dd 2025-09-30
.Dt X509 7ossl
.Os
.Sh NAME
.Nm x509
.Nd X.509 certificate handling
.Sh SYNOPSIS
.In openssl/x509.h
.Sh DESCRIPTION
An X.509 certificate is a structured grouping of information about an
individual, a device, or anything one can imagine.
An X.509 CRL (certificate revocation list) is a tool to help determine
if a certificate is still valid.
The exact definition of those can be found in the X.509 document from
ITU-T, or in RFC3280 from PKIX. In OpenSSL, the type X509 is used to
express such a certificate, and the type X509_CRL is used to express a
CRL.
.Pp
A related structure is a certificate request, defined in PKCS#10 from
RSA Security, Inc, also reflected in RFC2896. In OpenSSL, the type
X509_REQ is used to express such a certificate request.
.Pp
To handle some complex parts of a certificate, there are the types
X509_NAME (to express a certificate name), X509_ATTRIBUTE (to express a
certificate attribute), X509_EXTENSION (to express a certificate
extension) and a few more.
.Pp
Finally, there's the supertype X509_INFO, which can contain a CRL, a
certificate and a corresponding private key.
.Pp
.Sy X509_ Ns Em XXX ,
.Sy d2i_X509_ Ns Em XXX ,
and
.Sy i2d_X509_ Ns Em XXX
functions handle X.509 certificates, with some exceptions, shown below.
.Pp
.Sy X509_CRL_ Ns Em XXX ,
.Sy d2i_X509_CRL_ Ns Em XXX ,
and
.Sy i2d_X509_CRL_ Ns Em XXX
functions handle X.509 CRLs.
.Pp
.Sy X509_REQ_ Ns Em XXX ,
.Sy d2i_X509_REQ_ Ns Em XXX ,
and
.Sy i2d_X509_REQ_ Ns Em XXX
functions handle PKCS#10 certificate requests.
.Pp
.Sy X509_NAME_ Ns Em XXX
functions handle certificate names.
.Pp
.Sy X509_ATTRIBUTE_ Ns Em XXX
functions handle certificate attributes.
.Pp
.Sy X509_EXTENSION_ Ns Em XXX
functions handle certificate extensions.
.Sh SEE ALSO
.Xr X509_NAME_ENTRY_get_object 3 ,
.Xr X509_NAME_add_entry_by_txt 3 ,
.Xr X509_NAME_add_entry_by_NID 3 ,
.Xr X509_NAME_print_ex 3 ,
.Xr X509_NAME_new 3 ,
.Xr PEM_X509_INFO_read 3 ,
.Xr d2i_X509 3 ,
.Xr d2i_X509_ALGOR 3 ,
.Xr d2i_X509_CRL 3 ,
.Xr d2i_X509_NAME 3 ,
.Xr d2i_X509_REQ 3 ,
.Xr d2i_X509_SIG 3 ,
.Xr crypto 7
.Sh COPYRIGHT
Copyright 2003-2021 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
