.Dd 2025-09-30
.Dt CONFIG 5ossl
.Os
.Sh NAME
.Nm config
.Nd OpenSSL CONF library configuration files
.Sh DESCRIPTION
This page documents the syntax of OpenSSL configuration files, as parsed
by
.Xr NCONF_load 3
and related functions.
This format is used by many of the OpenSSL commands, and to initialize
the libraries when used by any application.
.Pp
The first part describes the general syntax of the configuration files,
and subsequent sections describe the semantics of individual modules.
Other modules are described in
.Xr fips_config 5
and
.Xr x509v3_config 5 .
The syntax for defining ASN.1 values is described in
.Xr ASN1_generate_nconf 3 .
.Sh SYNTAX
A configuration file is a series of lines.
Blank lines, and whitespace between the elements of a line, have no
significance.
A comment starts with a
.Sy #
character; the rest of the line is ignored.
If the
.Sy #
is the first non-space character in a line, the entire line is ignored.
.Ss Directives
Two directives can be used to control the parsing of configuration
files:
.Sy .include
and
.Sy .pragma .
.Pp
For compatibility with older versions of OpenSSL, an equal sign after
the directive will be ignored.
Older versions will treat it as an assignment, so care should be taken
if the difference in semantics is important.
.Pp
A file can include other files using the include syntax:
.Bd -literal
  .include [=] pathname
.Ed
.Pp
If
.Sy pathname
is a simple filename, that file is included directly at that point.
Included files can have
.Sy .include
statements that specify other files.
If
.Sy pathname
is a directory, all files within that directory that have a
.Qo Li .cnf Qc
or
.Qo Li .conf Qc
extension will be included.
(This is only available on systems with POSIX IO support.)
Any sub-directories found inside the
.Sy pathname
are
.Sy ignored .
Similarly, if a file is opened while scanning a directory, and that file
has an
.Sy .include
directive that specifies a directory, that is also ignored.
.Pp
As a general rule, the
.Sy pathname
should be an absolute path; this can be enforced with the
.Sy abspath
and
.Sy includedir
pragmas, described below.
The environment variable
.Sy OPENSSL_CONF_INCLUDE ,
if it exists, is prepended to all relative pathnames.
If the pathname is still relative, it is interpreted based on the
current working directory.
.Pp
To require all file inclusions to name absolute paths, use the following
directive:
.Bd -literal
 .pragma [=] abspath:value
.Ed
.Pp
The default behavior, where the
.Sy value
is
.Sy false
or
.Sy off ,
is to allow relative paths.
To require all
.Sy .include
pathnames to be absolute paths, use a
.Sy value
of
.Sy true
or
.Sy on .
.Pp
In these files, the dollar sign,
.Sy $ ,
is used to reference a variable, as described below.
On some platforms, however, it is common to treat
.Sy $
as a regular character in symbol names.
Supporting this behavior can be done with the following directive:
.Bd -literal
 .pragma [=] dollarid:value
.Ed
.Pp
The default behavior, where the
.Sy value
is
.Sy false
or
.Sy off ,
is to treat the dollarsign as indicating a variable name;
.Qo Li foo$bar Qc
is interpreted as
.Qo Li foo Qc
followed by the expansion of the variable
.Qo Li bar Qc .
If
.Sy value
is
.Sy true
or
.Sy on ,
then
.Qo Li foo$bar Qc
is a single seven-character name and variable expansions must be
specified using braces or parentheses.
.Bd -literal
 .pragma [=] includedir:value
.Ed
.Pp
If a relative pathname is specified in the
.Sy .include
directive, and the
.Sy OPENSSL_CONF_INCLUDE
environment variable doesn't exist, then the value of the
.Sy includedir
pragma, if it exists, is prepended to the pathname.
.Ss Settings
A configuration file is divided into a number of
.Em sections .
A section begins with the section name in square brackets, and ends when
a new section starts, or at the end of the file.
The section name can consist of alphanumeric characters and underscores.
Whitespace between the name and the brackets is removed.
.Pp
The first section of a configuration file is special and is referred to
as the
.Sy default
section.
This section is usually unnamed and spans from the start of file until
the first named section.
When a name is being looked up, it is first looked up in the current or
named section, and then the default section if necessary.
.Pp
The environment is mapped onto a section called
.Sy ENV .
.Pp
Within a section are a series of name/value assignments, described in
more detail below.
As a reminder, the square brackets shown in this example are required,
not optional:
.Bd -literal
 [ section ]
 name1 = This is value1
 name2 = Another value
 ...
 [ newsection ]
 name1 = New value1
 name3 = Value 3
.Ed
.Pp
The
.Sy name
can contain any alphanumeric characters as well as a few punctuation
symbols such as
.Sy .
.Sy ,
.Sy ;
and
.Sy _ .
Whitespace after the name and before the equal sign is ignored.
.Pp
If a name is repeated in the same section, then all but the last value
are ignored.
In certain circumstances, such as with Certificate DNs, the same field
may occur multiple times.
In order to support this, commands like
.Xr openssl-req 1
ignore any leading text that is preceded with a period.
For example:
.Bd -literal
 1.OU = First OU
 2.OU = Second OU
.Ed
.Pp
The
.Sy value
consists of the string following the
.Sy =
character until end of line with any leading and trailing whitespace
removed.
.Pp
The value string undergoes variable expansion.
The text
.Qo Li $var Qc
or
.Qo Li ${var} Qc
inserts the value of the named variable from the current section.
To use a value from another section use
.Qo Li $section::name Qc
or
.Qo Li ${section::name} Qc .
By using
.Qo Li $ENV::name Qc ,
the value of the specified environment variable will be substituted.
.Pp
Variables must be defined before their value is referenced, otherwise an
error is flagged and the file will not load.
This can be worked around by specifying a default value in the
.Sy default
section before the variable is used.
.Pp
Any name/value settings in an
.Sy ENV
section are available to the configuration file, but are not propagated
to the environment.
.Pp
It is an error if the value ends up longer than 64k.
.Pp
It is possible to escape certain characters by using a single
.Sy '
or double
.Sy \(dq
quote around the value, or using a backslash
.Sy \e
before the character, By making the last character of a line a
.Sy \e
a
.Sy value
string can be spread across multiple lines.
In addition the sequences
.Sy \en ,
.Sy \er ,
.Sy \eb
and
.Sy \et
are recognized.
.Pp
The expansion and escape rules as described above that apply to
.Sy value
also apply to the pathname of the
.Sy .include
directive.
.Sh OPENSSL LIBRARY CONFIGURATION
The sections below use the informal term
.Em module
to refer to a part of the OpenSSL functionality.
This is not the same as the formal term
.Em FIPS module ,
for example.
.Pp
The OpenSSL configuration looks up the value of
.Sy openssl_conf
in the default section and takes that as the name of a section that
specifies how to configure any modules in the library.
It is not an error to leave any module in its default configuration.
An application can specify a different name by calling
.Xr CONF_modules_load_file 3 ,
for example, directly.
.Pp
OpenSSL also looks up the value of
.Sy config_diagnostics .
If this exists and has a nonzero numeric value, any error suppressing
flags passed to
.Xr CONF_modules_load 3
will be ignored.
This is useful for diagnosing misconfigurations but its use in
production requires additional consideration.
With this option enabled, a configuration error will completely prevent
access to a service.
Without this option and in the presence of a configuration error, access
will be allowed but the desired configuration will
.Sy not
be used.
.Bd -literal
 # These must be in the default section
 config_diagnostics = 1
 openssl_conf = openssl_init

 [openssl_init]
 oid_section = oids
 providers = providers
 alg_section = evp_properties
 ssl_conf = ssl_configuration
 engines = engines
 random = random

 [oids]
 ... new oids here ...

 [providers]
 ... provider stuff here ...

 [evp_properties]
 ... EVP properties here ...

 [ssl_configuration]
 ... SSL/TLS configuration properties here ...

 [engines]
 ... engine properties here ...

 [random]
 ... random properties here ...
.Ed
.Pp
The semantics of each module are described below.
The phrase "in the initialization section" refers to the section
identified by the
.Sy openssl_conf
or other name (given as
.Sy openssl_init
in the example above).
The examples below assume the configuration above is used to specify the
individual sections.
.Ss ASN.1 Object Identifier Configuration
The name
.Sy oid_section
in the initialization section names the section containing name/value
pairs of OID's.
The name is the short name; the value is an optional long name followed
by a comma, and the numeric value.
While some OpenSSL commands have their own section for specifying OID's,
this section makes them available to all commands and applications.
.Bd -literal
 [oids]
 shortName = a very long OID name, 1.2.3.4
 newoid1 = 1.2.3.4.1
 some_other_oid = 1.2.3.5
.Ed
.Pp
If a full configuration with the above fragment is in the file
.Pa example.cnf ,
then the following command line:
.Bd -literal
 OPENSSL_CONF=example.cnf openssl asn1parse -genstr OID:1.2.3.4.1
.Ed
.Pp
will output:
.Bd -literal
 0:d=0  hl=2 l=   4 prim: OBJECT            :newoid1
.Ed
.Pp
showing that the OID "newoid1" has been added as "1.2.3.4.1".
.Ss Provider Configuration
The name
.Sy providers
in the initialization section names the section containing cryptographic
provider configuration.
The name/value assignments in this section each name a provider, and
point to the configuration section for that provider.
The provider-specific section is used to specify how to load the module,
activate it, and set other parameters.
.Pp
Within a provider section, the following names have meaning:
.Bl -tag -width Ds
.It Sy identity
This is used to specify an alternate name, overriding the default name
specified in the list of providers.
For example:
.Bd -literal
 [providers]
 foo = foo_provider

 [foo_provider]
 identity = my_fips_module
.Ed
.It Sy module
Specifies the pathname of the module (typically a shared library) to
load.
.It Sy activate
If present and set to one of the values yes, on, true or 1, then the
associated provider will be activated.
Conversely, setting this value to no, off, false, or 0 will prevent the
provider from being activated.
Settings can be given in lower or uppercase.
Setting activate to any other setting, or omitting a setting value will
result in an error.
.Pp
If enabled, informs the library to clear the error stack on failure to
activate requested provider.
A value of 1, yes, true or on (in lower or uppercase) will activate this
setting, while a value of 0, no, false, or off (again in lower or
uppercase) will disable this setting.
Any other value will produce an error.
Note this setting defaults to off if not provided
.El
.Pp
All parameters in the section as well as sub-sections are made available
to the provider.
.Pp
.Em Default provider and its activation
.Pp
If no providers are activated explicitly, the default one is activated
implicitly.
See
.Xr OSSL_PROVIDER-default 7
for more details.
.Pp
If you add a section explicitly activating any other provider(s), you
most probably need to explicitly activate the default provider,
otherwise it becomes unavailable in openssl.
It may make the system remotely unavailable.
.Ss EVP Configuration
The name
.Sy alg_section
in the initialization section names the section containing algorithmic
properties when using the
.Sy EVP
API.
.Pp
Within the algorithm properties section, the following names have
meaning:
.Bl -tag -width Ds
.It Sy default_properties
The value may be anything that is acceptable as a property query string
for
.Xr EVP_set_default_properties 3 .
.It Sy fips_mode No (deprecated)
The value is a boolean that can be
.Sy yes
or
.Sy no .
If the value is
.Sy yes ,
this is exactly equivalent to:
.Bd -literal
 default_properties = fips=yes
.Ed
.Pp
If the value is
.Sy no ,
nothing happens.
Using this name is deprecated, and if used, it must be the only name in
the section.
.El
.Ss SSL Configuration
The name
.Sy ssl_conf
in the initialization section names the section containing the list of
SSL/TLS configurations.
As with the providers, each name in this section identifies a section
with the configuration for that name.
For example:
.Bd -literal
 [ssl_configuration]
 server = server_tls_config
 client = client_tls_config
 system_default = tls_system_default

 [server_tls_config]
 ... configuration for SSL/TLS servers ...

 [client_tls_config]
 ... configuration for SSL/TLS clients ...
.Ed
.Pp
The configuration name
.Sy system_default
has a special meaning.
If it exists, it is applied whenever an
.Sy SSL_CTX
object is created.
For example, to impose system-wide minimum TLS and DTLS protocol
versions:
.Bd -literal
 [tls_system_default]
 MinProtocol = TLSv1.2
 MinProtocol = DTLSv1.2
.Ed
.Pp
The minimum TLS protocol is applied to
.Sy SSL_CTX
objects that are TLS-based, and the minimum DTLS protocol to those are
DTLS-based.
The same applies also to maximum versions set with
.Sy MaxProtocol .
.Pp
Each configuration section consists of name/value pairs that are parsed
by
.Sy SSL_CONF_cmd(3) ,
which will be called by
.Xr SSL_CTX_config 3
or
.Xr SSL_config 3 ,
appropriately.
Note that any characters before an initial dot in the configuration
section are ignored, so that the same command can be used multiple
times.
This probably is most useful for loading different key types, as shown
here:
.Bd -literal
 [server_tls_config]
 RSA.Certificate = server-rsa.pem
 ECDSA.Certificate = server-ecdsa.pem
.Ed
.Ss Engine Configuration
The name
.Sy engines
in the initialization section names the section containing the list of
ENGINE configurations.
As with the providers, each name in this section identifies an engine
with the configuration for that engine.
The engine-specific section is used to specify how to load the engine,
activate it, and set other parameters.
.Pp
Within an engine section, the following names have meaning:
.Bl -tag -width Ds
.It Sy engine_id
This is used to specify an alternate name, overriding the default name
specified in the list of engines.
If present, it must be first.
For example:
.Bd -literal
 [engines]
 foo = foo_engine

 [foo_engine]
 engine_id = myfoo
.Ed
.It Sy dynamic_path
This loads and adds an ENGINE from the given path.
It is equivalent to sending the ctrls
.Sy SO_PATH
with the path argument followed by
.Sy LIST_ADD
with value
.Sy 2
and
.Sy LOAD
to the dynamic ENGINE. If this is not the required behaviour then
alternative ctrls can be sent directly to the dynamic ENGINE using ctrl
commands.
.It Sy init
This specifies whether to initialize the ENGINE. If the value is
.Sy 0
the ENGINE will not be initialized, if the value is
.Sy 1
an attempt is made to initialize the ENGINE immediately.
If the
.Sy init
command is not present then an attempt will be made to initialize the
ENGINE after all commands in its section have been processed.
.It Sy default_algorithms
This sets the default algorithms an ENGINE will supply using the
function
.Xr ENGINE_set_default_string 3 .
.El
.Pp
All other names are taken to be the name of a ctrl command that is sent
to the ENGINE, and the value is the argument passed with the command.
The special value
.Sy EMPTY
means no value is sent with the command.
For example:
.Bd -literal
 [engines]
 foo = foo_engine

 [foo_engine]
 dynamic_path = /some/path/fooengine.so
 some_ctrl = some_value
 default_algorithms = ALL
 other_ctrl = EMPTY
.Ed
.Ss Random Configuration
The name
.Sy random
in the initialization section names the section containing the random
number generator settings.
.Pp
Within the random section, the following names have meaning:
.Bl -tag -width Ds
.It Sy random
This is used to specify the random bit generator.
For example:
.Bd -literal
 [random]
 random = CTR-DRBG
.Ed
.Pp
The available random bit generators are:
.Bl -tag -width Ds
.It Sy CTR-DRBG
.It Sy HASH-DRBG
.It Sy HMAC-DRBG
.El
.It Sy cipher
This specifies what cipher a
.Sy CTR-DRBG
random bit generator will use.
Other random bit generators ignore this name.
The default value is
.Sy AES-256-CTR .
.It Sy digest
This specifies what digest the
.Sy HASH-DRBG
or
.Sy HMAC-DRBG
random bit generators will use.
Other random bit generators ignore this name.
.It Sy properties
This sets the property query used when fetching the random bit generator
and any underlying algorithms.
.It Sy seed
This sets the randomness source that should be used.
By default
.Sy SEED-SRC
will be used outside of the FIPS provider.
The FIPS provider uses call backs to access the same randomness sources
from outside the validated boundary.
.It Sy seed_properties
This sets the property query used when fetching the randomness source.
.It Sy random_provider
This sets the provider to use for the
.Xr RAND_bytes 3
calls instead of the built-in entropy sources.
It defaults to "fips".
If the named provider is not loaded, the built-in entropy sources will
be used.
.El
.Sh EXAMPLES
This example shows how to use quoting and escaping.
.Bd -literal
 # This is the default section.
 HOME = /temp
 configdir = $ENV::HOME/config

 [ section_one ]
 # Quotes permit leading and trailing whitespace
 any = " any variable name "
 other = A string that can \e
 cover several lines \e
 by including \e\e characters
 message = Hello World\en

 [ section_two ]
 greeting = $section_one::message
.Ed
.Pp
This example shows how to expand environment variables safely.
In this example, the variable
.Sy tempfile
is intended to refer to a temporary file, and the environment variable
.Sy TEMP
or
.Sy TMP ,
if present, specify the directory where the file should be put.
Since the default section is checked if a variable does not exist, it is
possible to set
.Sy TMP
to default to
.Pa /tmp ,
and
.Sy TEMP
to default to
.Sy TMP .
.Bd -literal
 # These two lines must be in the default section.
 TMP = /tmp
 TEMP = $ENV::TMP

 # This can be used anywhere
 tmpfile = ${ENV::TEMP}/tmp.filename
.Ed
.Pp
This example shows how to enforce FIPS mode for the application
.Pa sample .
.Bd -literal
 sample = fips_config

 [fips_config]
 alg_section = evp_properties

 [evp_properties]
 default_properties = "fips=yes"
.Ed
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Sy OPENSSL_CONF
The path to the config file, or the empty string for none.
Ignored in set-user-ID and set-group-ID programs.
.It Sy OPENSSL_ENGINES
The path to the engines directory.
Ignored in set-user-ID and set-group-ID programs.
.It Sy OPENSSL_MODULES
The path to the directory with OpenSSL modules, such as providers.
Ignored in set-user-ID and set-group-ID programs.
.It Sy OPENSSL_CONF_INCLUDE
The optional path to prepend to all
.Sy .include
paths.
.El
.Sh BUGS
There is no way to include characters using the octal
.Sy \ennn
form.
Strings are all null terminated so nulls cannot form part of the value.
.Pp
The escaping isn't quite right: if you want to use sequences like
.Sy \en
you can't use any quote escaping on the same line.
.Pp
The limit that only one directory can be opened and read at a time can
be considered a bug and should be fixed.
.Sh HISTORY
An undocumented API,
.Xr NCONF_WIN32 3 ,
used a slightly different set of parsing rules there were intended to be
tailored to the Microsoft Windows platform.
Specifically, the backslash character was not an escape character and
could be used in pathnames, only the double-quote character was
recognized, and comments began with a semi-colon.
This function was deprecated in OpenSSL 3.0; applications with
configuration files using that syntax will have to be modified.
.Sh SEE ALSO
.Xr openssl-x509 1 ,
.Xr openssl-req 1 ,
.Xr openssl-ca 1 ,
.Xr openssl-fipsinstall 1 ,
.Xr ASN1_generate_nconf 3 ,
.Xr EVP_set_default_properties 3 ,
.Xr CONF_modules_load 3 ,
.Xr CONF_modules_load_file 3 ,
.Xr RAND_bytes 3 ,
.Xr fips_config 5 ,
and
.Xr x509v3_config 5 .
.Sh COPYRIGHT
Copyright 2000-2025 The OpenSSL Project Authors.
All Rights Reserved.
.Pp
Licensed under the Apache License 2.0 (the "License").
You may not use this file except in compliance with the License.
You can obtain a copy in the file LICENSE in the source distribution or
at
.Lk https://www.openssl.org/source/license.html .
