# This BSD makefile helps provide a deterministic means of doing a "clean"
# vendor import of OpenSSL.
#
# Recommended use:
#
#   % make clean
#   % make patch
#   % make configure
#   % make all

NO_OBJ=

LCRYPTO_SRC=	${SRCTOP}/crypto/openssl
LCRYPTO_DOC=	${LCRYPTO_SRC}/doc

CAT?=		/bin/cat
CC?=		cc
GMAKE?=		gmake
LD?=		ld
MV?=		/bin/mv
PERL?=		perl
RM?=		/bin/rm
SETENVI=	/usr/bin/env -i

LOCALBASE=	/usr/local
SETENV=		env -i PATH=${LOCALBASE}/bin:/bin:/usr/bin

PATCH=		/usr/bin/patch
PATCH_STRIP=	-p0
PATCH_ARGS=	--forward --quiet -E ${PATCH_STRIP}
PATCH_ARGS+=	-V simple
PATCH_ARGS+=	--suffix .orig

FILES_TO_PATCH=	\
	Configurations/unix-Makefile.tmpl \
	include/crypto/bn_conf.h.in \
	include/openssl/configuration.h.in \

PATCH_FILES=	${FILES_TO_PATCH:S/^/patch-/:S/\//-/g:S/^/freebsd\//g}

.PHONY: patch configure all
.ORDER: patch configure all

LOCALBASE=	/usr/local
WRK_ENV=	CC=${CC} \
		LD=${LD} \
		PATH=${LOCALBASE}/bin:/bin:/usr/bin

configure:
	@(cd ${.CURDIR} && ${SETENVI} \
	    ${WRK_ENV} \
	    ${PERL} ./Configure \
	    disable-aria \
	    disable-egd \
	    disable-idea \
	    disable-mdc2 \
	    disable-sm2 \
	    disable-sm3 \
	    disable-sm4 \
	    enable-ec_nistp_64_gcc_128 \
	    enable-ktls \
	    enable-sctp \
	    --openssldir=etc \
	    --prefix=/usr)
	@echo "Building configdata.pm for later use."
	@(cd ${.CURDIR} && \
	     ${SETENVI} ${WRK_ENV} ${GMAKE} -j ${.MAKE.JOBS} ${FILES_TO_PATCH:S/.in$//})
	@(cd ${.CURDIR} && \
	     ${SETENVI} ${WRK_ENV} ${GMAKE} -j ${.MAKE.JOBS} configdata.pm)

	@echo "Populating Makefile.version with release information"
	@(cd ${LCRYPTO_SRC} && ${SETENVI} ${WRK_ENV} ${PERL} \
	     ${LCRYPTO_SRC}/freebsd/dump_version_from_configdata.pl > \
	     ${SRCTOP}/secure/lib/libcrypto/Makefile.version)

all:
	@echo "==> Building generated files (headers, manpages, etc)"
	@(cd ${.CURDIR} && \
	     ${SETENVI} ${WRK_ENV} ${GMAKE} -j ${.MAKE.JOBS} build_all_generated)

	# 1. Fix --prefix.
	#    a. Not sure why --prefix isn't honored properly, even though it's
	#       passed to Configure; the files might be getting rebuilt
	#       post-Configure, somehow.
	# 2. Remove duplicate path in CFLAGS.
	# 3. Remove duplicate path in includedir(s).
	@echo "==> Fixing pkgconfig files"
	@find . -name \*.pc -print -exec sed -i '' -E \
	    -e 's,^prefix=.+,prefix=/usr,' \
	    -e 's,[[:space:]]+(\-I)?\$\{prefix\}/\./include[[:space:]]*,,g' \
	    {} +

	@echo "==> Cleaning / rebuilding ASM"
	@(cd ${SRCTOP}/secure/lib/libcrypto && \
	     ${SETENVI} ${WRK_ENV} ${MAKE} cleanasm && \
	     ${SETENVI} ${WRK_ENV} ${MAKE} buildasm)

	@cd ${.CURDIR} && ${MAKE} __sync_manpages
	@cd ${.CURDIR} && ${MAKE} __regenerate-manpage-makefiles

__regenerate-manpage-makefiles: .PHONY
	@echo "==> Regenerating manpage Makefiles"
.for man_sect in 3 5 7
	@echo "==> Regenerating manpage Makefiles (section ${man_sect})"
	@find ${SRCTOP}/secure/lib/libcrypto/man/man${man_sect}/ \
	    -name "*.${man_sect}" -type f \
	    -exec ${LCRYPTO_SRC}/freebsd/generate_libcrypto_manpage_makefiles.py {} \; | \
	    sort > ${SRCTOP}/secure/lib/libcrypto/man/man${man_sect}/Makefile
.endfor

__sync_manpages: .PHONY
	@echo "==> Syncing manpages (section 1)"
	@rsync -a --delete \
	    --exclude 'Makefile*' --exclude '*.1' \
	    ${LCRYPTO_DOC}/man/ \
	    ${SRCTOP}/secure/lib/libcrypto/man

	@echo "==> Syncing manpages (sections {3,5,7})"
	@rsync -a --delete \
	    --exclude 'Makefile*' --exclude '*.[357]' \
	    ${LCRYPTO_DOC}/man/man1/ \
	    ${SRCTOP}/secure/usr.bin/openssl/man

patch:
	# Spam arch-specific overrides to config files.
.for file in ${PATCH_FILES}
	@echo "==> Applying patch ${file}"
	@${SETENVI} ${PATCH} ${PATCH_ARGS} < ${file}
.endfor

makepatch: .PHONY
.for file in ${FILES_TO_PATCH}
	ORIG=${file}.orig; \
	NEW=${file}; \
	OUT=${.CURDIR}/freebsd/patch-${file:S/\//-/g}; \
	TZ=UTC diff -audp $${ORIG} $${NEW} | \
	sed \
		-e '/^---/s|\.[0-9]* +0000$$| UTC|' \
		-e '/^+++/s|\([[:blank:]][-0-9:.+]*\)*$$||' \
		> $${OUT} || true
.endfor

clean: .PHONY
.for file in ${FILES_TO_PATCH}
	@echo "==> Restoring ${file}"
	-@${MV} ${file}.orig ${file}
.endfor
	@(cd ${SRCTOP}/secure/lib/libcrypto && \
	    ${SETENVI} ${WRK_ENV} ${MAKE} cleanasm)

	-@(cd ${.CURDIR} && ${GMAKE} ${.TARGET})

.include <sys.mk>
